### ISSUE TITLE
Implementation/Example?

### ISSUE THREAD

**Issue by timdoes** [transistorsoft/react-native-background-geolocation#1]
This is exactly what I have been looking for!

Can you provide an example or instructions for implementing this in a current react-native build (or new build)?

Again, I am very excited to see this in action. Thank you!

-Tim

**Comment by christocracy** [comment]
Working on it.  It works but the npm install messes up.  Requires Xcode
mucky muck.

I've ported my popular Cordova Background Geolocation plugin.

You can see the API here (see README)
http://christocracy.github.io/cordova-background-geolocation/

On Thursday, May 21, 2015, Tim Gaines <notifications@github.com> wrote:

> This is exactly what I have been looking for!
>
> Can you provide an example or instructions for implementing this in a
> current react-native build (or new build)?
>
> Again, I am very excited to see this in action. Thank you!
>
> -Tim
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/react-native-background-geolocation/issues/1>
> .
>


-- 
Snet from Gmail Mobile

**Comment by timdoes** [comment]
Awesome! I look forward to trying it out.

-Tim

**Comment by christocracy** [comment]
Got MapBox rendering.  Pretty close.  Sorry, busy with the Cordova end of things.  Good news is the core framework used with Cordova does in fact work with React Native.

https://github.com/mapbox/react-native-mapbox-gl

The installation is still a little fuzzy with npm not playing nice with symlinks but I can prob adjust my Xcode build script to build without symlinks.

I'll try and post what I've got soon.  I'm really a noob with RN so I could prob use some help at this point now.  Pretty tough coming back to RN after weeks/months hiatus.  Always breaking changes when I come back at it.

**Comment by christocracy** [comment]
Demo app:  https://github.com/transistorsoft/rn-background-geolocation-demo

**Comment by timdoes** [comment]
I will take a look at this tonight. Thank you so much!
