### ISSUE TITLE
NSInvalidArgumentException TSAuthorization.m:232 - unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by newoga** [transistorsoft/react-native-background-geolocation#1005]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS
* OS version: 13.3.1 (96.8%), 13.3 (3.2%)
* Device manufacturer / model: Mostly iPhone 10,3 (but iPhone 8,4 - iPhone 12,5)
* React Native version (`react-native -v`): 0.60.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  autoSync: true,
  batchSync: false,
  debug: false,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 50,
  httpRootProperty: '.',
  locationTemplate,
  logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
  method: 'POST',
  reset: true,
  startOnBoot: false,
  stopOnTerminate: false,
  url: 'redacted',
  authorization: {
    strategy: 'JWT',
    accessToken: session.token,
    refreshToken: session.refreshToken,
    refreshUrl: 'redacted',
    refreshPayload: {
     authType: 'refresh',
     username: parseJwt(session.token).sub,
     refreshToken: '{refreshToken}',
     },
     expires: session.tokenExpiresInSecs,
  }
}

```

## Expected Behavior

No errors.

## Actual Behavior

We're seeing this error occasionally in our production logs but it is not yet clear what impact it is having  to users.

## Steps to Reproduce

Have not yet been able to reproduce locally.

## Context
We've been seeing this error pop up for iOS users in our production logs since switching to using the authorization configuration that `react-native-background-geolocation` supports.

## Debug logs

_No debug logs yet, still trying to reproduce locally._

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Show me the full stacktrace.  I'd guess that one of the values on your `session` object is `null` or invalid.

```javascript
accessToken: session.token,
    refreshToken: session.refreshToken,
    refreshUrl: 'redacted',
    refreshPayload: {
     authType: 'refresh',
     username: parseJwt(session.token).sub,
     refreshToken: '{refreshToken}',
     },
     expires: session.tokenExpiresInSecs,
```

**Comment by newoga** [comment]
Thanks for the quick response. Working on reproducing this now.  Below is a stacktrace output I have. Hopefully it helps.

```
NSInvalidArgumentException -[__NSArrayI stringValue]: unrecognized selector sent to instance 0x28049fb60 
    Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
    /usr/lib/libobjc.A.dylib _objc_exception_throw
    Frameworks/CoreFoundation.framework/CoreFoundation -[NSObject(NSObject) doesNotRecognizeSelector:]
    Frameworks/CoreFoundation.framework/CoreFoundation ____forwarding___
    Frameworks/CoreFoundation.framework/CoreFoundation ___forwarding_prep_0___
    /Users/chris/workspace/background-geolocation/native/transistor-locationmanager/src/ios/TSLocationManager/TSLocationManager/Config/TSAuthorization.m:232:26 -[TSAuthorization applyResponseData:data:]
    /Users/chris/workspace/background-geolocation/native/transistor-locationmanager/src/ios/TSLocationManager/TSLocationManager/Config/TSAuthorization.m:229:13 -[TSAuthorization applyResponseData:data:]
    /Users/chris/workspace/background-geolocation/native/transistor-locationmanager/src/ios/TSLocationManager/TSLocationManager/Config/TSAuthorization.m:209:5 -[TSAuthorization refreshAuthorization:]
    /Users/chris/workspace/background-geolocation/native/transistor-locationmanager/src/ios/TSLocationManager/TSLocationManager/Config/TSAuthorization.m:167:47 __43-[TSAuthorization resolve:success:failure:]_block_invoke
    Frameworks/CFNetwork.framework/CFNetwork _CFNetServiceBrowserSearchForServices
    Frameworks/CFNetwork.framework/CFNetwork __CFHTTPMessageSetResponseProxyURL
    Frameworks/Foundation.framework/Foundation ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
    Frameworks/Foundation.framework/Foundation -[NSBlockOperation main]
    Frameworks/Foundation.framework/Foundation ___NSOPERATION_IS_INVOKING_MAIN__
    Frameworks/Foundation.framework/Foundation -[NSOperation start]
    Frameworks/Foundation.framework/Foundation ___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
    Frameworks/Foundation.framework/Foundation ___NSOQSchedule_f
    /usr/lib/system/libdispatch.dylib __dispatch_block_async_invoke2
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_continuation_pop
    /usr/lib/system/libdispatch.dylib __dispatch_async_redirect_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain
    /usr/lib/system/libdispatch.dylib __dispatch_worker_thread2
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
    /usr/lib/system/libsystem_pthread.dylib _start_wqthread
```

**Comment by christocracy** [comment]
Ok, the error comes while decoding the refresh-url response from your server.  Please send me an example of the data returned from your server.

**Comment by newoga** [comment]
Ah, I see. Thanks for the heads up!

Our server responds with with something like this:

```json
{
    "token": "<jwt-token>",
    "refreshToken": "<jwt-token>",
    "permissions": {
      "app": [
        "permission-a",
        "permission-b"
       ]
    },
    "tokenExpiresInSecs": 900,
    "refreshTokenExpiresInSecs": 31536000
}
```

I bet it's finding the `refreshTokenExpiresInSecs` and trying to parse that.

**Comment by christocracy** [comment]
>I bet it's finding the refreshTokenExpiresInSecs and trying to parse that.

Shouldn't be.  The plugin performs regular expressions upon the actual data, not the keys.

However, can you experiment with your server response and remove `refreshTokenExpiresInSecs`.  If that doesn't work, remove `tokenExpiresInSecs` and see if it fixes it.

**Comment by newoga** [comment]
> However, can you experiment with your server response and remove refreshTokenExpiresInSecs. If that doesn't work, remove tokenExpiresInSecs and see if it fixes it.

Sure, I've been context switching a little bit today, but I'll post my results here as soon as I can.

**Comment by newoga** [comment]
@christocracy Sorry for the late response. I was able to configure the library to connect to a local instance of our authorization server. Unfortunately no variation of removing the `refreshTokenExpiresInSecs`, `tokenExpiresInSecs`, and `permissions` keys seemed to have any effect on removing this error.

That all being said, this error does not appear to affect the library from being able to get a new token and publish location events. The entire time while these errors are logging, location events are still persisting on the server.

Let me know if there is anything else I should try.

**Comment by christocracy** [comment]
Can you show me an *exact* raw response without redaction?

Email it to me at chris@transistorsoft.com.

I have a native iOS test-case I can plug it into

**Comment by newoga** [comment]
Will do, thanks much!

**Comment by christocracy** [comment]
Ok, I've reproduced the problem in my test-case.  It's because of the `mkt: []`.  The recursive iterator didn't consider the case of encountering an `[]` in the response.  

If the plugin encounters an `[]`, I'm going make it ignore that branch in the data-structure.  I doubt anyone is going to hide their `token` / `refreshToken` / `expires` in an `[]`.   This should fix it.

```diff
if ([value isKindOfClass:[NSDictionary class]]) {
    [self applyResponseData:auth data:value];
    continue;
+} else if ([value isKindOfClass:[NSArray class]]) {
+    continue;
+}
```

Also, be aware that the plugin assumes that the format of `refreshToken` does *not* resemble that of a JWT (ie: `XXX.YYY.ZZZ`).  The plugin uses regular expressions to "taste" the data.  If you make both `token` and `refreshToken` have the same format, it could mistake a `refreshToken` for `token`.

The plugin assumes `refreshToken` to be a simple hash, like [this](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/)
![](https://dl.dropbox.com/s/ffwsje9ka9j3x2p/Screenshot%202020-03-17%2010.19.10.png?dl=1)

**Comment by christocracy** [comment]
You've purchased a license, right?  This fix will be posted first to the private repo.

**Comment by newoga** [comment]
Yup, we have a license. Thanks much for the quick response!

> Also, be aware that the plugin assumes that the format of refreshToken does not resemble that of a JWT (ie: XXX.YYY.ZZZ). The plugin uses regular expressions to "taste" the data. If you make both token and refreshToken have the same format, it could mistake a refreshToken for token.

We'll look into changing our refresh token format so that this will not cause issues in the future.

**Comment by christocracy** [comment]
Right, I recall we did a video conf.

**Comment by newoga** [comment]
Yeah, I wasn't exactly a mobile developer at the time but I've somewhat inherited some of this project 😄

**Comment by newoga** [comment]
> Also, be aware that the plugin assumes that the format of refreshToken does not resemble that of a JWT (ie: XXX.YYY.ZZZ). The plugin uses regular expressions to "taste" the data. If you make both token and refreshToken have the same format, it could mistake a refreshToken for token.

@christocracy  Would you be open to adding a key to the `authorization` configuration that allows us to explicitly define which keys contain the auth and refresh tokens?

**Comment by christocracy** [comment]
I’d rather not.  It makes the api much more complex.  Just don’t send a jwt as the refreshToken, it’s not supposed to be.  It’s just supposed to a simple hash.
