### ISSUE TITLE
How to enable and disable tracking?

### ISSUE THREAD

**Issue by JuniorSchulz** [transistorsoft/react-native-background-geolocation#1006]
I have an application that has the function of tracking and identifying a user via qrcode, but I need to enable and disable tracking in some situations is it possible?

**Comment by christocracy** [comment]
#start / #stop methods.

**Comment by JuniorSchulz** [comment]
Okay, via settings parameter is there any way?

**Comment by christocracy** [comment]
>Okay, via settings parameter is there any way?

I don't see what the point of that would be.  When you want to start tracking, you `BackgroundGeolocation.start()`.  To stop, `BackgroundGeolocation.stop()`.

**Comment by JuniorSchulz** [comment]
The development of the application was done by a third company and we were looking for an option to not request the code change for the company.

**Comment by christocracy** [comment]
Impossible.  You *must* change the code.

**Comment by JuniorSchulz** [comment]
Okay, thanks
