### ISSUE TITLE
Regarding Android background tracking.

### ISSUE THREAD

**Issue by nicoache1** [transistorsoft/react-native-background-geolocation#1008]
## Android background tracking.

This is not an issue most like a question.

Regarding this in Android https://developer.android.com/guide/components/services

```Note: If your app targets API level 26 or higher, the system imposes restrictions on running background services when the app itself isn't in the foreground. In most situations, for example, you shouldn't access location information from the background. Instead, schedule tasks using WorkManager.```

In my app I want to track the information of the user behaviour while driving, i think that the user at least need to maintain the app open in background to properly works, please can you confirm this?

**Comment by christocracy** [comment]
The plugin uses a foreground service.  Foreground services are immune from limits.
