### ISSUE TITLE
Pressing the notification will re-render the whole app and crashes when using deeplinks with react-navigation

### ISSUE THREAD

**Issue by timomeh** [transistorsoft/react-native-background-geolocation#1010]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 10 (QQ2A.200305.003)
* Device manufacturer / model: Both emulator and real device (Pixel 4)
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  reset: true,

  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  disableElasticity: false,
  elasticityMultiplier: 0.75,
  stationaryRadius: 50,

  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,

  method: 'PUT',
  headers: { ...API_HEADERS },
  url: API_ROOT + '/location',

  httpRootProperty: 'foobar',
  locationTemplate:
    '{"latest_latitude":<%= latitude %>,"latest_longitude":<%= longitude %>}',

  batchSync: false,
  autoSync: true,
  foregroundService: true,

  notification: {
    channelName: 'Foo Bar',
    priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
    title: 'Foo Bar',
    text: 'Foo Bar Baz'
  }
}
```

## Expected Behavior

Pressing the sticky notification while the app is open should not re-render the whole app.

## Actual Behavior

Pressing the sticky notification while the app is open re-renders the app. The Splash Screen re-appears, the app is loading again, and I'm having crashes due to deep-linking with react-navigation.

## Steps to Reproduce

I can reproduce it with minimal changes of the demo app:

1. Setup demo-app from https://github.com/timomeh/rn-background-geolocation-notification-crash
2. Go to Simple Map
3. Turn on Tracking
4. Swipe down notification tray and click on the BG Geolocation Notification

## Context

I'm using Deep Linking with react-navigation/native. The `useLinking` hook checks if it was already mounted and crashes if it mounts a second time. See here:

https://github.com/react-navigation/react-navigation/blob/aaf01e01e7b47b375f68aebe6d0effe82878d060/packages/native/src/useLinking.native.tsx#L20-L32

I reproduced this behavior inside the demo app. I've also set `activity android:launchMode = singleTask` like the [React Native Docs recommend](https://reactnative.dev/docs/linking#basic-usage).

Even without my changes you can see that clicking the notification re-renders the whole app – it briefly flashes white before restoring its last state. It doesn't crash when the notification was clicked while the app is in the background.

This does not happen with other actions which causes the app to become active again, e.g. with remote notifications or when clicking/triggering a deeplink. The active app always continues. Only when clicking the background geolocation notification will the app re-render.

**Comment by christocracy** [comment]
This is fixed in the private "customer's only" version.

![](https://dl.dropboxusercontent.com/s/285oka5bydxiyrw/Screenshot%202020-03-18%2017.28.46.png?dl=1)

`3.6.0` is due to be released to public repo soon.

**Comment by timomeh** [comment]
Nice, thanks for the info Chris! I'll consider this solved.
