### ISSUE TITLE
Location permission dialog doesn't appear - crash of the app

### ISSUE THREAD

**Issue by nicolaseberle** [transistorsoft/react-native-background-geolocation#1012]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Nexus 5S
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  componentDidMount() {
    ////
    // 1.  Wire up event-listeners
    //

    // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.onLocation(this.onLocation, this.onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange(this.onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.onActivityChange(this.onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.onProviderChange(this.onProviderChange);

    ////
    // 2.  Execute #ready method (required)
    //


    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5,
      locationUpdateInterval: 5000,  // Get a location every 5 seconds
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'https://overland.openhumans.org/XXXXXXXXXXXXX/',
      batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      autoSyncThreshold: 100,
      maxBatchSize: 10000,
      httpRootProperty: 'locations',
      locationTemplate: '{\
        "type": "Feature", \
        "geometry": { \
          "type": "Point",    \
          "coordinates": [      <%=longitude%>,      <%=latitude%>    ]  },\
        "properties": {    \
          "timestamp": "<%= timestamp %>",    \
          "battery_level": <%=battery.level%>,    \
          "speed": <%=speed%>, \
          "altitude": <%=altitude%>,\
          "horizontal_accuracy": <%=accuracy%>,\
          "vertical_accuracy": <%=altitude_accuracy%>,\
          "significant_change": "disabled",\
          "locations_in_payload": 1,\
          "battery_state": <%=battery.is_charging%>,\
          "device_id": "",\
          "wifi": "" ,\
          "deferred": 1000,\
          "desired_accuracy": 100,\
          "activity": <%=activity.type%>,\
          "pauses": <%=is_moving%>,\
          "motion": ["driving","stationary"]\
        }\
      }'
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        ////
        // 3. Start tracking!
        //

        BackgroundGeolocation.start(function() {
          console.log("- Start success");

        });

      }
    });

  }
```

## Expected Behavior
I'm expecting to see the location-service permission dialog box.

## Actual Behavior

Crash of the app

When I comment the BackgroundGeolocation.start() command, the UI is loaded correctly. 

## Context
When I authorized manually the app, I have no bug.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
03-26 11:06:11.558 29063 29180 I TSLocationManager:   🔵  LocationAuthorization: Requesting Background permission
03-26 11:06:11.564 29063 29063 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-26 11:06:11.567 29063 29063 E AndroidRuntime: FATAL EXCEPTION: main
03-26 11:06:11.567 29063 29063 E AndroidRuntime: Process: com.overlandandroid, PID: 29063
03-26 11:06:11.567 29063 29063 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at com.intentfilter.androidpermissions.PermissionManager.registerBroadcastReceiver(PermissionManager.java:87)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at com.intentfilter.androidpermissions.PermissionHandler.registerForBroadcastIfNeeded(PermissionHandler.java:124)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:44)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at com.transistorsoft.locationmanager.util.b$5.run(Unknown Source:31)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.overlandandroid-BGCpB7yApIlQOIjRZjWxcA==/base.apk"],nativeLibraryDirectories=[/data/app/com.overlandandroid-BGCpB7yApIlQOIjRZjWxcA==/lib/arm64, /data/app/com.overlandandroid-BGCpB7yApIlQOIjRZjWxcA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-26 11:06:11.567 29063 29063 E AndroidRuntime: 	... 12 more
03-26 11:06:11.578 29063 29063 E TSLocationManager: [c.t.l.a.BackgroundGeolocation$e uncaughtException] 
03-26 11:06:11.578 29063 29063 E TSLocationManager:   ‼️  Uncaught Exception: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
03-26 11:06:11.578 29063 29063 E TSLocationManager: {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":100,"batchSync":true,"configUrl":"","debug":true,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":true,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":5,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"encrypt":false,"extras":{},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.rnbackgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"locations","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"{        \"type\": \"Feature\",         \"geometry\": {           \"type\": \"Point\",              \"coordinates\": [      <%=longitude%>,      <%=latitude%>    ]  },        \"properties\": {              \"timestamp\": \"<%= timestamp %>\",              \"battery_level\": <%=battery.level%>,              \"speed\": <%=speed%>,           \"altitude\": <%=altitude%>,          \"horizontal_accuracy\": <%=accuracy%>,          \"vertical_accuracy\": <%=altitude_accuracy%>,          \"significant_change\": \"disabled\",          \"locations_in_payload\": 1,          \"battery_state\": <%=battery.is_charging%>,          \"device_id\": \"\",          \"wifi\": \"\" ,          \"deferred\": 1000,          \"desired_accuracy\": 100,          \"activity\": <%=activity.type%>,          \"pauses\": <%=is_moving%>,          \"motion\": [\"driving\",\"stationary\"]        }      }","locationTimeout":60,"locationUpdateInterval":5000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":10000,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":1,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"https:\/\/overland.openhumans.org\/5ye71az9mu\/","useSignificantChangesOnly":false,"enabled":false,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false}
03-26 11:06:11.578 29063 29063 E TSLocationManager: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at com.intentfilter.androidpermissions.PermissionManager.registerBroadcastReceiver(PermissionManager.java:87)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at com.intentfilter.androidpermissions.PermissionHandler.registerForBroadcastIfNeeded(PermissionHandler.java:124)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:44)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at com.transistorsoft.locationmanager.util.b$5.run(Unknown Source:31)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at android.os.Handler.handleCallback(Handler.java:790)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at android.os.Looper.loop(Looper.java:164)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-26 11:06:11.578 29063 29063 E TSLocationManager: 	at java.lang.reflect.Method.invoke(Native Method)

```

</details>

**Comment by christocracy** [comment]
It’s not a *bug*, it’s an error in your Android gradle Config.

```
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
```

Post the following files:
- android/build.gradle
- android/app/build.gradle

**Comment by nicolaseberle** [comment]
android/build.gradle
`buildscript {
    ext {
        googlePlayServicesLocationVersion = "17.0.0"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        appCompatVersion = "1.0.2"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

`

android/app/build.gradle


`apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

def jscFlavor = 'org.webkit:android-jsc:+'

def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.overlandandroid"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation project(':react-native-background-fetch')
    implementation project(':react-native-background-geolocation')
    implementation project(':react-native-vector-icons')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
Project background_geolocation = project(':react-native-background-geolocation')
apply from: "${background_geolocation.projectDir}/app.gradle"
`

**Comment by christocracy** [comment]
And gradle.properties.

**Comment by nicolaseberle** [comment]
:)

`# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

android.useAndroidX=true
android.enableJetifier=true
`

**Comment by nicolaseberle** [comment]
settings.gradle

`
rootProject.name = 'OverlandAndroid'
include ':react-native-background-fetch'
project(':react-native-background-fetch').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-fetch/android')
include ':react-native-background-geolocation'
project(':react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-geolocation/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
`

**Comment by christocracy** [comment]
You haven’t upgraded your app for auto-linking.  See [react-native upgrade guide](https://reactnative.dev/docs/upgrading)

**Comment by nicolaseberle** [comment]
What makes you say that ? Seems to me I did the right thing.

**Comment by nicolaseberle** [comment]
I created new project from start. Seems to work. Thx

**Comment by christocracy** [comment]
The whole idea behind *auto-linking* is that no longer need to manage 3rd-party dependencies like this:
```gradle
dependencies {
    implementation project(':react-native-background-fetch')
    implementation project(':react-native-background-geolocation')
    implementation project(':react-native-vector-icons')
    .
    .
    .
```
or this (`settings.gradle`)
```
include ':react-native-background-fetch'
project(':react-native-background-fetch').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-fetch/android')
include ':react-native-background-geolocation'
project(':react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-geolocation/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
```

Look at the [SampleApp app/build.gradle](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/app/build.gradle#L199-L210) and [settings.gradle](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/settings.gradle).   This **one line** *automatically links* all 3rd-party dependencies:
```
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
```

And in [`MainApplication.java`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/app/src/main/java/com/transistorsoft/backgroundgeolocation/react/MainApplication.java#L26), *auto-linking* there too (no references to 3rd party dependencies required)

**Comment by nicolaseberle** [comment]
Just for information.

I upgraded my project, but that didn't work. I had to add this line in the app/build.gradle

dependencies {
   implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
}

**Comment by maihemboom** [comment]
> 
> 
> Just for information.
> 
> I upgraded my project, but that didn't work. I had to add this line in the app/build.gradle
> 
> dependencies {
> implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
> }

Thanks for that. start() did not work for me (logged for permission request but nothing happened), this resolved it.
