### ISSUE TITLE
Random positions

### ISSUE THREAD

**Issue by JuniorSchulz** [transistorsoft/react-native-background-geolocation#1014]
I realize that sometimes I get some positions very far from my current location, has anyone experienced this problem?

**Comment by christocracy** [comment]
This can happen depending on the environment.  You will never get perfect results.  You're expected to filter out data as desired (`location.accuracy` is a good place to start filtering).

**Comment by JuniorSchulz** [comment]
Is there a standard of precision that states that the position is of quality?

**Comment by christocracy** [comment]
[`location.coords.accuracy`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.coords.html#accuracy)

**Comment by JuniorSchulz** [comment]
The higher the accuracy the better the quality of the position? From how much (Ex: 1600) the position is no longer of quality?

**Comment by christocracy** [comment]
A geolocation is not a simple point in space.  It’s a **Circle** of radius `accuracy` meters.

- If the accuracy is 5 meters, the device is somewhere inside a circle of radius 5 meters.
- if the accuracy is *1000* meters, the device is somewhere within a circle of **1000** meters.
