### ISSUE TITLE
I didn't find the equivalence of allowDeferredLocationUpdates in your API  

### ISSUE THREAD

**Issue by nicolaseberle** [transistorsoft/react-native-background-geolocation#1016]
How can I reach the function "allowDeferredLocationUpdates" from your API ?

I'm interested to setup a defer location updates.

https://developer.apple.com/documentation/corelocation/cllocationmanager/1620547-allowdeferredlocationupdates

Thx

**Comment by christocracy** [comment]
Search the API docs’ `Config` class for the word *“defer”.*  It’s `Config.deferTime`

**Comment by nicolaseberle** [comment]
Thank you. I saw Config.deferTime but it's only a timer not a distance threshold like in https://developer.apple.com/documentation/corelocation/cllocationmanager/1620547-allowdeferredlocationupdates
