### ISSUE TITLE
Background geolocation - duplicate latitude and longitude and reduce the ping result count

### ISSUE THREAD

**Issue by manojkumaraut** [transistorsoft/react-native-background-geolocation#1018]
## Your Environment
* Plugin version:3.4.2
* Platform: Android
* OS version:7.1
* Device manufacturer / model:
* React Native version (`react-native -v`):0.61
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
        desiredAccuracy: 0,
        stationaryRadius: 5,
        distanceFilter: 150,
        debug: false,
        startOnBoot: false,
        stopOnTerminate: false
    }, (state) => {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
        if (!state.enabled) {
            BackgroundGeolocation.start(function () {
                console.log("- Start success");
            });
        }
```

## Expected Behavior
1.Reduce the ping result from the background geolocation on-location event to limited
2. Eliminate the duplicate coordinates

## Actual Behavior
![image](https://user-images.githubusercontent.com/9800500/78028571-dda5f000-737c-11ea-831a-fd67d3130c89.png)

**Distance filter is working fine** 
1. Out of **900** latitude and longitude  , only **270** is original and remaining **600** are duplicates 

```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onLocation((location) => {
        // Triggers with duplicate coordinates
      
    });
```
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you manually posting these locations to your server?  Are you aware of [`Location.sample`](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#onlocation)

![](https://dl.dropbox.com/s/prroo1vplr9xh5h/Screenshot%202020-03-31%2009.39.22.png?dl=1)

**Comment by manojkumaraut** [comment]
Yes, we are  manually posting these locations to your server. once got location from the BackgroundGeolocation.onLocation method

Could you  share some code samples under implementation of Location.sample  ?

**Comment by christocracy** [comment]
>Could you share some code samples

```javascript
onLocation(location) {
  if (location.sample) return;
  .
  .
  .
});
```

**Comment by manojkumaraut** [comment]
Thanks Chris .... I will check and update you ....

**Comment by manojkumaraut** [comment]
![image](https://user-images.githubusercontent.com/9800500/78047589-2918c800-7396-11ea-9eff-32e18b2083e0.png)

location.sample undefined it says chris

**Comment by christocracy** [comment]
`location.sample` is present **only** when it's a `sample`.  When it's not a sample, it's undefined.

**Comment by manojkumaraut** [comment]
so when duplicate  latitude and longitude comes ... the sample will return  true ... is it correct chris ?

**Comment by christocracy** [comment]
When the plugin changes state from *moving->stationary* (or vice-versa) or executes `#getCurrentPosition`, the plugin turns on location-services to collect *several "samples"* (up to 5) before settling on the best available location.  it does not take the first location that comes in -- it takes time for the device to connect to sufficient GPS satellites. 

These "samples" are all provided to the `onLocation` event.  When you see `location.sample === true`, that's a sample and you should **not** send them to your server.

**Comment by manojkumaraut** [comment]
Chris , location.sample works fine  in  stationary, but  in moving state still i am  receiving the duplicates  latitude and longitude .any solution to resolve this issue

**Comment by christocracy** [comment]
Provide logs.  See wiki “Debugging” to learn how to fetch log using #emailLog method.
