### ISSUE TITLE
timestamp & timezone

### ISSUE THREAD

**Issue by nicolaseberle** [transistorsoft/react-native-background-geolocation#1020]
[Android]
Hi,

In the doc
"timestamp": [ISO-8601 UTC], // eg:  "2015-05-05T04:31:54.123Z"

How can I add in the timestamp that is sent in the locationTemplate the timezone offset of timestamp ? (the Z means "zero UTC offset") 

I mean, I would like to have
locationTempalte:{
...
timestamp: <%= timestampWithOffset) =>
}
timestampWithOffset = the real local time

**Comment by christocracy** [comment]
You have no control over `timestamp`.  You *could* add the `timezone` of the device in `Config.params`

```javascript
BackgroundGeolocation.ready({
  params: {
    timezone: theDeviceTimeZone
  }
});
```
The `Config.params` are merged with the rendered `locationTemplate`

**Comment by nicolaseberle** [comment]
Perfect. I didn't notice this parameter. I guess in minute ?

**Comment by nicolaseberle** [comment]
SI unit is seconde :)

**Comment by christocracy** [comment]
The plugin doesn’t do anything with this timezone you provide.  It’s your server’s responsibility to take that timezone and deal with the provided utc timestamp as required.

**Comment by nicolaseberle** [comment]
My customer can't change the param of the API request that they are using. A tip via <% ruby erb-style %> ?

**Comment by christocracy** [comment]
It's *impossible* to change the format of `timestamp`

**Comment by nicolaseberle** [comment]
ok. copy
