### ISSUE TITLE
Question, stop headless task

### ISSUE THREAD

**Issue by littlehome-eugene** [transistorsoft/react-native-background-geolocation#1024]
We couldn't fix the crashing bug and want to take out this library from our app.

We did took out all the code related to this library months ago

We are still receiving app crash report saying geolocation headless task is not registered.

Is there a way to stop the task without reinserting the library into our app?
(because we don't know why we are having such high crash with this lib, we are afraid to use this library to stop the task)

If it's not possible, I think it'll be beneficial to all to have a documentation on how to properly `removes` the lib from an app.

On our test device, we even uninstalled old app and installed app fresh with no `react-native-background-gelocation` code whatsoever, and still seeing the license warning (because it's debug build)

**Comment by littlehome-eugene** [comment]
I found https://github.com/transistorsoft/react-native-background-geolocation/issues/731


So you have to leave the headless, and call `ready()` with `enableHeadless: false, reset: true`

Would the following be minimal sufficient code to safely remove the lib?

```
# in index.js
BackgroundGeolocation.registerHeadlessTask(async () => {})

# in your app

BackgroundGeolocation.ready({
enableHeadless: false,
reset: true
}, () => {
  console.log("- BackgroundGeolocation is ready: ");
});
```

**Comment by christocracy** [comment]
That’s correct.

**Comment by littlehome-eugene** [comment]
Thank you, So `start()` is not neccessary?
