### ISSUE TITLE
Question, example GraphQL - BatchSync.

### ISSUE THREAD

**Issue by nicoache1** [transistorsoft/react-native-background-geolocation#1026]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS 
* OS version: macOS Mojave 10.14.6
* Device manufacturer / model: iPhone 11
* React Native version: 0.61.5
* Plugin config
```
const backgroundGeolocationConfig: GeoConfig = {
    autoSync: true,
    batchSync: true,
    debug: true,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 3,
    enableHeadless: true, // <-- enable this hear sounds for background-geolocation life-cycle.
    headers: {
      Accept: 'application/graphql',
    }, // <-- Auto start tracking when device is powered-up.
    locationTemplate:
      '{"query": "mutation { trackDataMutation($locationDataPoints: [LocationDataPointInput!]!) { trackData(locationDataPoints: $locationDataPoints):[LocationDataPoint]! } }"}',
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE, // <-- [Default: true] Set true to sync each location to server as it arrives.
    maxRecordsToPersist: 5,
    startOnBoot: true,
    stopOnTerminate: false,
    stopTimeout: 1,
    url: Config.API_HOST,
  }
```

## Expected Behavior
Send all the locations to my graphQL server.

## Actual Behavior
Im getting errors with the location template.

## Context
Im trying to send some various locations to my graphQL server. Im see some examples of how to do this when is only one location 

- [https://github.com/transistorsoft/flutter_background_geolocation/issues/38](https://github.com/transistorsoft/flutter_background_geolocation/issues/38)
- [https://github.com/transistorsoft/react-native-background-geolocation/issues/630](https://github.com/transistorsoft/react-native-background-geolocation/issues/630)

But i didnt find anyone with the batch sync in true. Could you please provide some example of how achieve this?

**Comment by christocracy** [comment]
> Im getting errors with the location template.

What errors?

**Comment by nicoache1** [comment]
> > Im getting errors with the location template.
> 
> What errors?

Sorry i forgot to paste that.

<img width="881" alt="Screen Shot 2020-04-13 at 1 09 03 PM" src="https://user-images.githubusercontent.com/26419582/79137015-526b2800-7d88-11ea-9201-0a121c20ecb7.png">

Im think that is related to a bad location template, because its reaching but maybe i miss something..

**Comment by christocracy** [comment]
What is the schema your server *expects* compared with with you’re *receiving*?

**Comment by nicoache1** [comment]
The server expects an array of this.

```
type LocationDataPoint {
accuracy: Float!
activity: Int
activityConfidence: Int
altitude: Float!
event: String!
heading: Float!
id: ID!
isMoving: Boolean
latitude: Float
longitude: Float
odometer: Float!
recordedAt: ISO8601DateTime
spped: Float!
uuid: String
}
```

and im receiving i think something like this 

```
type LocationDataPointInput {
latitude: Float!
longitude: Float!
accuracy: Float
spped: Float
heading: Float
altitude: Float
activity: Int!
activityConfidence: Int!
recordedAt: ISO8601DateTime!
uuid: String!
event: String
isMoving: Boolean!
odometer: Float
}
```

**Comment by christocracy** [comment]
Why don’t you print what you’re *receiving* in your server logs and paste it here?

**Comment by nicoache1** [comment]
Thank you so much, i manage to solve the thing seeing the server, etc. Just one question, exists the field recorded_at? It should be `<%= recorded_at %>` ?

**Comment by christocracy** [comment]
>  It should be <%= recorded_at %> ?

No.  See the api docs Config.locationTemplate for available variables.

**Comment by nicoache1** [comment]
Just another question that comes to us, im using a rails server and we are struggling a bit to parse the response because it appends the params to another root and the query is inside that root so graphql fails if i not do some hack, its there a way to avoid this?

<img width="645" alt="Screen Shot 2020-04-14 at 10 38 01 AM" src="https://user-images.githubusercontent.com/26419582/79231509-8b64d480-7e3c-11ea-8620-501b6898d414.png">

**Comment by christocracy** [comment]
Perhaps you're interested in `Config.httpRootProperty`?

**Comment by nicoache1** [comment]
> Perhaps you're interested in `Config.httpRootProperty`?

Yes, i used the `.` as i see in the docs and the result was that it appends "_json" as you can see in the image..

**Comment by christocracy** [comment]
This will be Rails automatically appending the json from the body of the HTTP request to its own special param `_json`.

**Comment by nicoache1** [comment]
Hmm im going to check Rails then, thank you!

**Comment by christocracy** [comment]
Have you tried this?
```ruby
data = JSON.parse(request.body.read)
```

**Comment by nicoache1** [comment]
I would try with that, thanks!

**Comment by nicoache1** [comment]
Just to let record of the problem, it's not something related to Rails.
The problem is with Apollo Client and the batching, when you are using batching Apollo Client appends the _json and that is the issue. Here in the next link is the issue and the solution for that.

[Documentation](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/queries/multiplex.md)
