### ISSUE TITLE
array of floats provided to geofence extras got parsed to array of ints on android

### ISSUE THREAD

**Issue by nasmuris** [transistorsoft/react-native-background-geolocation#1027]
## Your Environment
* Plugin version: 3.6.2, 3.4.2
* Platform: Android
* OS version: -
* Device manufacturer / model: -
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOW,
  distanceFilter: 1000.0,
  reset: false,
  stopTimeout: 1,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
  stopOnTerminate: false,
  startOnBoot: true,
  enableHeadless: true,
  maxDaysToPersist: 14,
  geofenceProximityRadius: 50000,
```

## Expected Behavior
array of numbers in geofence event extras should be the same as provided when adding geofence
## Actual Behavior
values of array of numbers is parsed to int, using e.g.
``` extras= {x:{y:23.3, z:23.4}}``` works fine
## Steps to Reproduce
create geofence event with extras `{x:[123.456,789.056]}` received value in on geofence event is `{x:[123,789]}`

**Comment by christocracy** [comment]
Looks like issue is caused within the react-native facade of the plugin [here](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/RNBackgroundGeolocationModule.java#L1177-L1178)

**Comment by christocracy** [comment]
And in the case of [`mapToJson`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/RNBackgroundGeolocationModule.java#L1148-L1149), the plugin uses `getDouble` instead of `getInt`.

It should be fine to change `arrayToJson` to use `getDouble` as well, instead of `getInt`.
