### ISSUE TITLE
iOS app killed when no movement despite preventSuspend: true

### ISSUE THREAD

**Issue by activegiving** [transistorsoft/react-native-background-geolocation#1029]
The app on iOS is regularly killed in background while location tracking is paused and no movement of the user is happening. 

We understood from the description that with `preventSuspend: true` this shall not happen (at least as regular as we experience it). But also found this thread https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1052 (knowing that this is cordova), which states that iOS `preventSuspend` requires `Always` and are now wondering about the required settings, as we thought that 'Only when using the app' is sufficient. 

When testing with another GPS tracking App (e.g. Strava) there are no kills (the app stays alive while in background for +10 minutes).  

## Your Environment
* Plugin version: 3.6.2
* Platform: iOS
* OS version: 13.3.1
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
private ready = () => {
   return BackgroundGeolocation.ready(
     {
       // Geolocation Config
       desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
       distanceFilter: 10,
       disableElasticity: true,
       // Application config
       logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
       stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
       preventSuspend: true,
       foregroundService: true,
       heartbeatInterval: 60,
       stopOnStationary: false,
       locationAuthorizationRequest: 'Any',
       locationAuthorizationAlert: {
         titleWhenNotEnabled: 'Location services are off',
         titleWhenOff: 'Location services are off',
         instructions: 'Please grant location permissions in your settings',
         cancelButton: 'Cancel',
         settingsButton: 'Settings',
       },
     },
```

## Expected Behavior

App should *stay alive* when in background and movement of the user stops. 

## Actual Behavior

When the app is in background and GPS tracking is paused for about 1-2 minutes & the user is not moving and another app is opened (e.g. taking an image with the camera), the app is killed.  

## Steps to Reproduce

1. Location tracking started
2. Location tracking is paused and movement is is also stopped
3. Location tracking app in background and camera opened to take pictures
4. Reopening the tracking app, it starts with Splash Screen and activities are lost

## Context

Keeping the app alive while it is paused during a workout (e.g. running) and taking a picture with camera. 

## Debug logs

no debug logs available

**Comment by christocracy** [comment]
`Config.preventSuspend` **requires** `Always`.

99% of use-cases **do not require** `preventSuspend: true`.  You probably don't need it.

**Comment by activegiving** [comment]
So does this mean that by not setting `preventSuspent: true` we would have less app kills?

**Comment by activegiving** [comment]
@christocracy fyi - our app is a fitness activity app which has a lot of running, cycling, walking, hiking activities with pauses by the people taking images and alike

**Comment by christocracy** [comment]
>we would have less app kills?

No.  It's perfectly normal and expected that iOS periodically terminates apps in the background in order to free up memory for the current app running in the foreground (eg: telephone call).

>our app is a fitness activity app which has a lot of running, cycling, walking, hiking activities with pauses by the people taking images and alike

You don't need `preventSuspend: true`.  This feature is my own hack of iOS.  It's become more unreliable as iOS evolves.  Don't use it.

**Comment by activegiving** [comment]
Thanks Chris for insights. So are you still suggesting `preventSuspend: true` at all anymore?

**Comment by christocracy** [comment]
You should *not* use it.

**Comment by activegiving** [comment]
Hey @christocracy I hope you don't mind me asking again about this issue: until now we have left the toggle for preventSuspend set to `true` and before we switch it to `false`, I wanted to confirm that the chance of app kills gets lowered if we do so. 

You stated in the above messages, that the toggle has become more unreliable as iOS evolved. Do you have information, that the toggle being set to `true` actually also results in a higher chance of kills? 

Thanks for your input!

**Comment by christocracy** [comment]
>I wanted to confirm that the chance of app kills gets lowered if we do so.

I don't see how that should be related at all.  You can assume that iOS *will* kill an app sitting dormant in the background at some point in the future.  This is perfectly normal and expected for both iOS and Android to free up memory by terminating apps in the background.

If the device moves, the plugin will resume tracking.  It doesn't matter if the app is terminated in the background.

**Comment by alexander-potemkin** [comment]
I will jump in here with a clarification: what do I do, to make sure the app is on background, working, even if the person is not moving - considering the same fitness case, when the person stopped and needs some rest?
