### ISSUE TITLE
BackgroundGeolocation.watchPosition() not gives regular location update on iOS simulator

### ISSUE THREAD

**Issue by vikrantnegi** [transistorsoft/react-native-background-geolocation#1030]
Using BackgroundGeolocation.watchPosition() on iOS simulator and using location debugging feature "Freeway drive" gives only one location.

## Your Environment
* Plugin version: 3.6.2
* Platform: iOS Simulator
* OS version: 13.3
* Device manufacturer / model: iPhone 11
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript 
 // Traditional API still works:
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
    })
      .then(state => {
        console.log('- BackgroundGeolocation is ready: ', state);
        BackgroundGeolocation.watchPosition(
          location => {
            console.log('[watchPosition] -', location);
            const {latitude, longitude, speed} = location.coords;
          },
          errorCode => {
            console.log('[watchPosition] ERROR -', errorCode);
          },
          {
            //interval: 1000,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            persist: true,
            extras: {foo: 'bar'},
            timeout: 60000,
          },
        );
      })
      .catch(error => {
        console.log('- BackgroundGeolocation error: ', error);
      });
```

## Expected Behavior
I'm getting is_moving: false maybe because of odometer not working on simulator and due to this it is not giving regular location updates.
Is there a way I can receive the location updates in iOS simulator since it normally works using native geolocation API? 

## Actual Behavior
I'm getting only single location on console from the simulator.

## Steps to Reproduce
1. Run the watchLocation method
2. Turn on any of the iOS simulator debug method "freeway drive"
3. Check the console for the location updates
4. Only  getting one location update

## Context
Is there way to debug the `watchLocation` method on iOS simulator and get the location updates regularly?

**Comment by vikrantnegi** [comment]
@christocracy Any help with this? Thanks

**Comment by christocracy** [comment]
What are you hoping to achieve with watchPosition?

**Comment by vikrantnegi** [comment]
I'm trying to get the continuous location updates as the device moves with the user? But watchPosition does't seems to be working with iOS simulator debug feature.

**Comment by christocracy** [comment]
You don’t need to use `#watchPosition`.  Only `#start`.

Don’t use watchPosition

**Comment by vikrantnegi** [comment]
Thanks. I'm using `#start` but still i'm not receiving any location updates when using iOS simulator location debug feature.

Is intentional that we cannot get location updates in the iOS simulator debug location feature? Is this plugin supposed to work only for real moving devices?

**Comment by christocracy** [comment]
> Is this intentional

No, you’re doing something wrong.  Are you watching the logs?  Why are you not configuring `debug: true`?
