### ISSUE TITLE
OnLocation emits event with old timestamp

### ISSUE THREAD

**Issue by IrmantasVaracinskas** [transistorsoft/react-native-background-geolocation#1038]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS
* OS version: 13.3.1
* Device manufacturer / model: iphone 10r
* React Native version (`react-native -v`):0.61.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
     locationAuthorizationAlert: this._getLocationAlertConfig(),
     distanceFilter: 30,
     preventSuspend: true,
     heartbeatInterval: 60,
     desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
     disableStopDetection: true,
     pausesLocationUpdatesAutomatically: false,
     locationAuthorizationRequest: 'Always'
}
```

## Expected Behavior

When onLocation is called if I compare current time with location timestamp there shouldn't be much of difference (a second or two)

## Actual Behavior

onLocation is called with locations which's timestamps are up to a minute old

Is this expected behaviour or maybe it is configurable? I've tried changing heartbeatInterval but that didn't help

Thanks in advance

**Comment by christocracy** [comment]
That can happen.  When changing state, the plugin requests *multiple* location "samples" before settling on the final `onMotionChange` location.  See `location.sample === true`:

```javascript
onLocation(location) {
  if (location.sample === true) {
    console.log('- this is a location sample and not persisted to the plugin's SQLite');
  }
}
```

**Comment by christocracy** [comment]
Also, the location provided to `onHeartbeat` **WILL** be old.  Only the "last known location" is provided.  The plugin does *not* turn on location-services to request new locations in `onHeartbeat`.

If you want a fresh location in your `onHeartbeat` event, it's your responsibility to execute `BackgroundGeolocation.getCurrentPosition` as desired.
