### ISSUE TITLE
 TypeScript getLocations Return Type Fix

### ISSUE THREAD

**Issue by jsmith** [transistorsoft/react-native-background-geolocation#1040]
## Your Environment
* Plugin version: N/A
* Platform: iOS or Android
* OS version: N/A
* Device manufacturer / model: N/A
* React Native version: N/A
* Plugin config: N/A

## Expected Behavior
`getLocations` to return `Array<Location>`

## Actual Behavior
`getLocations` returns `Array<Object>` which I have to cast to `Array<Location`.

## Steps to Reproduce
N/A

## Context
Trying to get the locations and then use them.

## Debug logs
N/A

I use the TypeScript types for this library and noticed that `getLocations` currently returns an array of generic objects instead of an array of location objects. I looked at the commit that introduced this and see that it hasn't been modified since your initial TypeScript introduction a few years back.

To fix this, this line:
```typescript
static getLocations(success?:(locations:Array<Object>) => void, failure?:Function): Promise<Array<Object>>;
```

found [here](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/src/declarations/BackgroundGeolocation.d.ts#L1084) can easily be replaced by:
```typescript
    static getLocations(success?:(locations:Array<Location>) => void, failure?:Function): Promise<Array<Location>>;
```

It's pretty easy to work around this issue but it would be nice to not have to do any casting if possible! I can create a PR if you want, just let me know!

Thanks for your library :)

**Comment by christocracy** [comment]
Yes, why don’t you do a PR?

**Comment by jsmith** [comment]
Oops, this can be closed!
