### ISSUE TITLE
Does the app continue logging after a crash? (Does stopOnTerminate handles termination & crash as well)

### ISSUE THREAD

**Issue by jamilhaddadin** [transistorsoft/react-native-background-geolocation#1042]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS
* OS version: 13.3.1
* Device manufacturer / model: iPhoneX
* React Native version 0.61.5
*config:
     desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50
      locationUpdateInterval: 15,
      fastestLocationUpdateInterval: 15
      disableMotionActivityUpdates: true,
      stopTimeout: 1,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true

## Expected Behavior
once the application crashes, the application should keep login in android & wait for the mobile to move 200 meters (as per the stopOnTerminate documentation) the reboot

## Actual Behavior
I am not 100% sure, but we suspect that when the app crashes, it does not reboot after the geofence of 200 Meter

## Steps to Reproduce
1. Allow the app to crash
2. walk around for 200 meters
3. check the context, you will notice that the application is not logging points

## Context
I am trying to ensure that the application will keep logging even in case it crashes

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
How are you “making it crash”?

Yes, the plugin will continue working after a crash.  It’s no different than terminating the app.
