### ISSUE TITLE
Question regarding Odometer

### ISSUE THREAD

**Issue by nicoache1** [transistorsoft/react-native-background-geolocation#1045]
# Odometer

#### Description

I see in the docs that the odometer is the distance in miles travelled. But how exactly this works?

- Is the distance between two points or its the value of the total trip ( a sum of all the odometer registry in the location data points)?
- If I have trip A and trip B, the odometer would be the sum of the two? or it restarts everytime that it detects a motion change from stationary/moving?

Thank you!

**Comment by christocracy** [comment]
>I see in the docs that the odometer is the distance in miles travelled.

It's not *miles*, it's *meters*.

>But how exactly this works?

The plugin keep track of the last location.  Every time a new location is recorded, it does something like this:

```java
odometer += currentLocation.distanceTo(lastLocation);
```

**Comment by nicoache1** [comment]
> The plugin keep track of the last location. Every time a new location is recorded, it does something like this:

Even if i delete everything from the database ?

**Comment by christocracy** [comment]
>Even if i delete everything from the database ?

Yes.  The odometer calculation has nothing to do with locations in its SQLite database.  The plugin holds a reference to `lastOdometerLocation` in memory (in addition to storing it in `SharedPreferences` if app is terminated).

**Comment by nicoache1** [comment]
I understand, thank you for your quick response Chris!
