### ISSUE TITLE
Is there any method to stop sound ?

### ISSUE THREAD

**Issue by RashVenkat6795** [transistorsoft/react-native-background-geolocation#1046]
I'm implementing playSound() in certain methods but under certain conditions i want to turn off.
Like stopSound() ?
## Your Environment
* Plugin version: 3.6.2
* Platform: iOS 
* OS version: 13
* Device manufacturer / model: iphone 11
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.playSound(1021,(success) => console.log("sound success",success),(error) => console.log("sound error", error))
```

## Expected Behavior
Something like BackgroundGeolocation.stopSound

**Comment by khyper** [comment]
`debug : true,        // <-- enable this hear debug sounds.` From docs this line enables sound. 
Set it to false to disable sound

**Comment by christocracy** [comment]
Do not attempt to use `playSound` in a production app.  These sound-files are stripped from the app in release builds (they consume about 1Mb).

**Comment by RashVenkat6795** [comment]
Oh i didnt know about it
Thanks for the info!
