### ISSUE TITLE
Appstore refusing because of background tracking because of UIBackgroundModes

### ISSUE THREAD

**Issue by lander854** [transistorsoft/react-native-background-geolocation#1047]
I`m using only foreground location tracking but because the package uses background location api appstore is refusing to accept it because of UIBackgroundModes

## Your Environment
* Plugin version: latest
* Platform: iOS
* OS version:iOS 13
* Device manufacturer / model: Iphone 
* React Native version (`react-native -v`): 62.0
* Plugin config basic
only function used is
```
    BackgroundGeolocation.getCurrentLocation(function(locations) {
      console.log(locations);
    });
```
## Expected Behavior

appstore should accept becuase it is not using background location

## Actual Behavior
appstore refusing app because of background geolocation

UIBackgroundModes

</details>

**Comment by christocracy** [comment]
Simply disable the `[x] Location updaters` Background Capability in XCode.
![](https://dl.dropbox.com/s/nf0v442j0kvy5wp/Screenshot%202020-05-08%2010.45.39.png?dl=1)

Be sure to configure `locationAuthorizationRequest: "WhenInUse"`
