### ISSUE TITLE
Android - 2-3 seconds after starting tracking location, onMotionChange says event is not moving

### ISSUE THREAD

**Issue by tolik85** [transistorsoft/react-native-background-geolocation#1050]
## Your Environment
* Plugin version:
* Platform:Android
* OS version: API 28
* Device manufacturer / model: Emulator
* React Native version (`react-native -v`): 0.62
* Plugin config
```    distanceFilter: 10,
    stopTimeout: 1,
    desiredAccuracy: Platform.OS === 'ios'
      ? BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION
      : BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    locationAuthorizationRequest: 'Always',
    disableMotionActivityUpdates: true,
    debug: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    pausesLocationUpdatesAutomatically: false,
    batchSync: false
```

## Expected Behavior
The location tracking should continue.

## Actual Behavior
The location tracking is stopped.

## Steps to Reproduce

1.
2.
3.
4.

## Context
I am trying to simply track my location when the device is in foreground/background.
First in foreground. 
As soon as I start the plugin, 2-3 seconds afterwards I get a callback onMotionChange with event.isMoving = false. And since then I don't get onLocation events anymore.
My Android Emulator is simulating a route movement by car.

## Debug logs

<details><summary>Logs</summary>

This is what I get from the plugin:
```{
  "trackingMode": 1,
  "enabled": true,
  "stationaryRadius": 25,
  "isMoving": false,
  "httpTimeout": 60000,
  "forceReloadOnSchedule": false,
  "deferTime": 0,
  "configUrl": "",
  "autoSyncThreshold": 0,
  "activityRecognitionInterval": 10000,
  "isFirstBoot": true,
  "speedJumpFilter": 300,
  "locationsOrderDirection": "ASC",
  "locationAuthorizationRequest": "Always",
  "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
  "headers": {},
  "forceReloadOnMotionChange": false,
  "fastestLocationUpdateInterval": -1,
  "enableHeadless": true,
  "stopOnStationary": false,
  "params": {},
  "maxDaysToPersist": 1,
  "logMaxDays": 3,
  "locationTimeout": 60,
  "foregroundService": true,
  "extras": {},
  "encrypt": false,
  "enableTimestampMeta": false,
  "distanceFilter": 10,
  "desiredOdometerAccuracy": 100,
  "allowIdenticalLocations": false,
  "didLaunchInBackground": false,
  "url": "",
  "startOnBoot": true,
  "scheduleUseAlarmManager": false,
  "maxBatchSize": -1,
  "forceReloadOnLocationChange": false,
  "desiredAccuracy": -1,
  "authorization": {},
  "stopTimeout": 1,
  "persistMode": 2,
  "minimumActivityRecognitionConfidence": 75,
  "locationUpdateInterval": 1000,
  "geofenceTemplate": "",
  "forceReloadOnGeofence": false,
  "disableElasticity": false,
  "stopOnTerminate": false,
  "motionTriggerDelay": 0,
  "logLevel": 5,
  "geofenceProximityRadius": 1000,
  "geofenceModeHighAccuracy": false,
  "forceReloadOnBoot": false,
  "elasticityMultiplier": 1,
  "disableStopDetection": false,
  "disableLocationAuthorizationAlert": false,
  "autoSync": true,
  "schedulerEnabled": false,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "stopAfterElapsedMinutes": 0,
  "schedule": [],
  "persist": true,
  "maxRecordsToPersist": -1,
  "locationTemplate": "",
  "httpRootProperty": "location",
  "heartbeatInterval": -1,
  "forceReloadOnHeartbeat": false,
  "disableAutoSyncOnCellular": false,
  "batchSync": false,
  "odometer": 0,
  "useSignificantChangesOnly": false,
  "notification": {
    "actions": [],
    "strings": {},
    "priority": 0,
    "largeIcon": "",
    "smallIcon": "",
    "channelName": "TSLocationManager",
    "color": "",
    "text": "Location Service activated",
    "title": "",
    "layout": ""
  },
  "method": "POST",
  "geofenceInitialTriggerEntry": true,
  "disableMotionActivityUpdates": true,
  "debug": true
}

</details>

**Comment by christocracy** [comment]
The motion api is correct.  You’re testing on a simulator.  The motion api doesn’t report movement in a simulator.  See Wiki *Debugging* and *Philosophy of Operation*.

**Comment by tolik85** [comment]
Weird, why closed? I cannot use this plugin using Android emulator then?
I don't get onLocation events.

**Comment by christocracy** [comment]
The plugin triggers in response to *movement* reported by the *motion api* (accelerator, gyroscope, magnetometer).  This api doesn’t report movement in the simulator. 

As noted in wiki *Debugging*, you must manually put the plugin into the *moving* state by executing `changePace(true)`.

**Comment by digitlninja** [comment]
Hi @christocracy, if one has to manually trigger state change, what happens in the real world? I'm testing on my device and It's not clear if this changeState or shaking must happen in release too.

**Comment by christocracy** [comment]
>if one has to manually trigger state change, what happens in the real world? 

The Android plugin is listening to the *Motion API (accelerometer+gyroscope+magnetometer)*.  When the device is detected to be moving, the plugin automatically turns on location-services and begins tracking.  As a safety mechanism, the Android plugin also monitors a geofence around the last known position.  If the device exits that geofence (requires moving at least 200 meters from last known position), it too can automatically trigger the plugin into the moving state if the motion api fails to respond.

See Wiki [*Philosophy of Operation*](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

**Comment by Wingsclub** [comment]
Hi christocracy, I am using the Mock location app for tracking the cabs application. When I pause from the mock location app then how can   I tell my code that the cab is paused. Simply, I want to know how can I check that my shuttle is moving or not.

**Comment by christocracy** [comment]
`BackgroundGeolocation.changePace(false)`

**Comment by Wingsclub** [comment]
Thanks christocracy for your instant reply. So for that, I will have to install that package right but I am already using the geolocation package. Will it affect the code?

**Comment by christocracy** [comment]
>So for that, I will have to install that package right

what is "*that*" package?

**Comment by Wingsclub** [comment]
Background Geolocation for React-Native. We will have to install that 

> > So for that, I will have to install that package right
> 
> what is "_that_" package?

Background Geolocation for React-Native. We wil have to install it first right?

**Comment by christocracy** [comment]
>We will have to install it first right?

@Wingsclub Are you telling me you *don't* have `react-native-background-geolocation` installed?  I can't offer you any support for `react-native-background-geolocation` *until you have installed* `react-native-background-geolocation`.

**Comment by Wingsclub** [comment]
> > We will have to install it first right?
> 
> @Wingsclub Are you telling me you _don't_ have `react-native-background-geolocation` installed? I can't offer you any support for `react-native-background-geolocation` _until you have installed_ `react-native-background-geolocation`.

I installed it and now it working fine for me. Thank you👍😊
