### ISSUE TITLE
PerformanceLogger: Attempting to start a timespan that already exists  renderApplication_React_render

### ISSUE THREAD

**Issue by sergey94** [transistorsoft/react-native-background-geolocation#1052]
After reopening app with { stopOnTerminate: false } and started tracking, the app doesn't start.
In console I am getting following:

```PerformanceLogger: Attempting to start a timespan that already exists  renderApplication_React_render```
```PerformanceLogger: Attempting to end a timespan that has already ended  renderApplication_React_render```

Could it be connected with Background Geolocation?

react-native-background-geolocation 3.4.2
react-native 0.59

**Comment by christocracy** [comment]
>Could it be connected with Background Geolocation?

I've never heard of this.
