### ISSUE TITLE
Geofence proximity should be evaluated based on circle closest point not only center

### ISSUE THREAD

**Issue by Buthrakaur** [transistorsoft/react-native-background-geolocation#1054]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS, Android
* OS version: any
* Device manufacturer / model: any
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOW,
  distanceFilter: 1000.0,
  reset: false,
  stopTimeout: 1,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
  stopOnTerminate: false,
  startOnBoot: true,
  enableHeadless: true,
  maxDaysToPersist: 14,
  geofenceProximityRadius: 50000,
  notification: {
    smallIcon: 'drawable/ic_stat_ic_notification',
    largeIcon: 'drawable/ic_stat_ic_notification',
  },
}
```

## Expected Behavior

Geofence proximity algorithm which is described [here](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#geofenceproximityradius) should calculate active and also prioritize geofences based on closest circle point to current user location. So for example if I have this setup:
![geofences](https://user-images.githubusercontent.com/126757/82027002-df5d1600-9693-11ea-8ad1-1073f74632be.png)
I'd expect the big orange "IGNORED GEOFENCE" to be evaluated as the closest geofence and just work.

## Actual Behavior

The big orange "IGNORED GEOFENCE" doesn't fire probably because of how geofences are evaluated and prioritized - it looks like the algorithm work based on geofence circle centers and not based on the circle area closest point which would make much more sense.

## Steps to Reproduce

1. setup lot of (iOS 20+, Android 100+) small geofences around current user location with centers inside the `geofenceProximityRadius` circle (this simulates e.g. interesting houses = small geofence for each house)
2. setup a big geofence with center outside `geofenceProximityRadius` circle, but with area intersecting the `geofenceProximityRadius` circle
3. the big geofence doesn't fire as it looks like it's either disabled because the center isn't inside the `geofenceProximityRadius` circle or it gets low priority based on geofence center distance and because of the limit of the OS (iOS 20, Android 100)

## Context

We're trying to combine small and big size geofences and realized the large geofences frequently don't work. We use small geofences (~200m radius) for points of interests in a city (this results in hundreds of geofences for a city) in combination with large geofences (~0.5-10km radius) to cover whole cities or districts and realized the large ones frequently don't work.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
```

</details>

**Comment by christocracy** [comment]
I’m aware of this limitation when using large geofences and it’s not an easy problem to overcome.  In the meantime, you should configure the geofenceProximityRadius to be larger than your largest geofence radius.

**Comment by Buthrakaur** [comment]
This would mean to set `geofenceProximityRadius` to 20km or so and could potentially match 1000+ geofences in our case. Is it ok in terms of app performance etc?

And second question - how exactly does the algorithm sort the geofences to use the native geofencing API for "closest" 20/100 geofences? I mean if it uses geofence centers than setting high `geofenceProximityRadius` won't help as there could always be 20/100 geofences with centers closer to a user thus blocking the large geofence from being used.

**Comment by Buthrakaur** [comment]
I checked our config and we already use `geofenceProximityRadius: 50000` so it looks like the answer to my second question is the algorithm uses geofence centers which means there's no workaround to the issue now. Is that right?

**Comment by christocracy** [comment]
> which means there's no workaround to the issue now. Is that right?

Correct.  SQLite doesn’t have geospatial functions.  The required trigonometry upon the geofence center point are pre-computed and stored within database columns.

**Comment by Buthrakaur** [comment]
I understand it's diffucult to find a solution with good enough performance, but it's still a serious bug. Could you please share some more details about the algorithm? Maybe we could find a viable fix together.. I think you need to recalculate the distance to each geofence time to time as the user moves anyway and can't imagine a solution other than loading the list of geofences from the DB into memory, calculating the distance and sorting geofences based on that in case you aren't able to use geospatial query in the DB itself..?

**Comment by christocracy** [comment]
The `|geofences|` table looks like this, with pre-computed trigonometric values (eg: `sin_latitude`, `cos_latitude`, etc)
![](https://dl.dropbox.com/s/fap197ka0m4q8wh/Screenshot%202020-05-16%2011.48.27.png?dl=1)

adding a geofence pre-computes these values like so (*Android/Java* shown):
```java
private static double deg2rad(double degrees) {
        return Math.PI * degrees / 180;
}

private ContentValues getContentValues(TSGeofence geofence) {
        ContentValues values = new ContentValues();
        JSONObject extras = geofence.getExtras();
        values.put("identifier", geofence.getIdentifier());
        values.put("radius", geofence.getRadius());
        values.put("latitude", geofence.getLatitude());
        values.put("sin_latitude", Math.sin(deg2rad(geofence.getLatitude())));
        values.put("cos_latitude", Math.cos(deg2rad(geofence.getLatitude())));
        values.put("longitude", geofence.getLongitude());
        values.put("sin_longitude", Math.sin(deg2rad(geofence.getLongitude())));
        values.put("cos_longitude", Math.cos(deg2rad(geofence.getLongitude())));
        values.put("notifyOnEntry", geofence.getNotifyOnEntry());
        values.put("notifyOnExit", geofence.getNotifyOnExit());
        values.put("notifyOnDwell", geofence.getNotifyOnDwell());
        values.put("loiteringDelay", geofence.getLoiteringDelay());
        values.put("extras", (extras != null) ? extras.toString() : null);

        return values;
    }
```

Performing the geospatial query does this:
```java
public List<TSGeofence> allWithinRadius(double radius, double latitude, double longitude, int limit) {
        List<TSGeofence> rs = new ArrayList<>();

        Cursor cursor = null;
        SQLiteDatabase dbh = dbh();

        double querySinLat = Math.sin(deg2rad(latitude));
        double queryCosLat = Math.cos(deg2rad(latitude));
        double querySinLng = Math.sin(deg2rad(longitude));
        double queryCosLng = Math.cos(deg2rad(longitude));
        double queryRadius = Math.cos(radius/1000/EARTH_RADIUS_KM);

        String query = "SELECT "
            + "identifier, radius, latitude, longitude, notifyOnEntry, notifyOnExit, notifyOnDwell, loiteringDelay, extras, (" +querySinLat + " * sin_latitude + " + queryCosLat + " * cos_latitude * (cos_longitude * " +queryCosLng +" + sin_longitude * " + querySinLng + ")) AS distance "
            + "FROM " + LocationOpenHelper.GEOFENCES_TABLE_NAME + " "
            + "WHERE distance > " + queryRadius + " "
            + "ORDER BY distance DESC "
            + "LIMIT " + limit;

        try {
            cursor = dbh.rawQuery(query, null);
            while (cursor.moveToNext()) {
                try {
                    rs.add(hydrate(cursor));
                } catch (TSGeofence.Exception e) {
                    TSLog.logger.error(TSLog.error(e.getMessage()));
                    e.printStackTrace();
                }
            }
        } finally {
            if (cursor != null) {
                cursor.close();
            }
        }
        return rs;
    }
```

**Comment by Buthrakaur** [comment]
Thanks for sharing the details. Did you consider using SpatiaLite instead of pure SQLite? The [distance function](http://www.gaia-gis.it/gaia-sins/spatialite-sql-4.3.0.html#p13) would probably solve this issue. I see there's both Android and iOS port, but didn't work with SpatiaLite personally yet.

**Comment by christocracy** [comment]
Yes, but it adds significant complexity to the plugin’s dependency-mgmt.

Also, it would force every app to use the plugin’s version of SQLite.

Spacialite must be *compiled-into* SQLite.  I’ve used it before in the past.
