### ISSUE TITLE
App crashed on IOS 13 device (by far) -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: instructions)

### ISSUE THREAD

**Issue by jacky-ew** [transistorsoft/react-native-background-geolocation#1055]
## Your Environment
* Plugin version: 3.3.2
* Platform: iOS
* OS version: 13
* Device manufacturer / model: Iphone 11
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	distanceFilter: 0,
	locationTimeout: 120,
	stopTimeout: 10,
	debug: __DEV__,
	logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
	stopOnTerminate: false,
	startOnBoot: true,
	locationAuthorizationRequest: "WhenInUse",
	reset: __DEV__,
	allowIdenticalLocations: true,
	disableElasticity: true,
	persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
	maxRecordsToPersist: 1000,
	maxDaysToPersist: 7,
	enableHeadless: true,
	geofenceInitialTriggerEntry: false
```

## Expected Behavior
app runs smoothly in release mode

## Actual Behavior
app crashes on ready() call

## Steps to Reproduce

1. call ready() in didmount()
## Debug logs
on Release mode, no logs tracked
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

i notice that on v3.4.2, there is this fix
`[Fixed] iOS crash when launching first time -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: authorization)'`
could it be the same issue? thanks

**Comment by christocracy** [comment]
No, not same issue.  Show me the *entire* stacktrace.

**Comment by christocracy** [comment]
And show me the XCode logs of your app booting.

**Comment by christocracy** [comment]
Your error is related to `Config.locationAuthorizationAlert`.  You’re not using that option anywhere?

**Comment by christocracy** [comment]
Why are you doing this?
```
reset: __DEV__,
```

Do you know what `Config.reset` does?  In most cases, you don't need to provide `reset` at all, simply let it default to `true`.

**Comment by jacky-ew** [comment]
yes, im using it in a certain component, called in didmount().
will update you again, trying to reproduce the case

**Comment by christocracy** [comment]
Show me where you're using `locationAuthorizationAlert`

**Comment by jacky-ew** [comment]
Hi @christocracy , it appears to be another issue related to translation library, closing this.
