### ISSUE TITLE
License Validation Failure

### ISSUE THREAD

**Issue by dev7050** [transistorsoft/react-native-background-geolocation#1056]
Hello @christocracy,

I am using react-native-background-geolocation for my projects. It works fine in previous apps which are live but when I upgraded project to latest version of react native it's now showing error of License validation failure. I am using the same key for both but getting issues in release build. 

react-native - "0.61.5"
react-native-background-geolocation": "^3.4.2"

Since auto-linking I have followed the doc for react-native > 0.60 but still not works on release build. Debug works fine.

**Comment by christocracy** [comment]
Email the following information to `chris@transistorsoft.com`:
- Order #
- `AndroidManifest.xml`
