### ISSUE TITLE
react-native-background-fetch needed for pure Geofencing?

### ISSUE THREAD

**Issue by m-ruhl** [transistorsoft/react-native-background-geolocation#1057]
## Your Environment
* Plugin version: 3.6.2
* Platform: iOS / Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        disableLocationAuthorizationAlert: true,
        enableHeadless: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_WARNING,
        persistMode: BackgroundGeolocation.PERSIST_MODE_NONE,
        startOnBoot: true,
        stopOnTerminate: false
```

Is all the configuration of `react-native-background-fetch` and permissions needed for only pure Geofencing.. or is it okay to only install `react-native-background-geolocation`?

I know for iOS you don't need any Background-Mode to do Geofencing, and I didn't find a clear answer in the documentation.

**Comment by christocracy** [comment]
iOS requires the existence of the TSBackgroundFetch symbols or it won’t compile.
