### ISSUE TITLE
Ruby erb-style tags in LocationTemplate

### ISSUE THREAD

**Issue by nicolaseberle** [transistorsoft/react-native-background-geolocation#1058]
## Your Environment
* Platform: Android

I try to use Ruby erb-style tags condition "if" in the locationTemplate, but it is not interpreted.
```javascript
"battery_state": <% if battery.is_charging == "True" %>charging<% elsif %>unplugged<% end %>,
```
Any advice to change the state of battery_state with specific string ?

**Comment by christocracy** [comment]
Logic is not supported.
