### ISSUE TITLE
'onGeofence' event at JS realm when the app is not running

### ISSUE THREAD

**Issue by rimzici** [transistorsoft/react-native-background-geolocation#1059]
## Your Environment
* Plugin version: ^3.6.2
* Platform: iOS and Android
* OS version: Android 10 and iOS 13
* Device manufacturer / model: Nokia 8.1 and iPhone5s
* React Native version (`react-native -v`): 0.62.2
* Plugin config

<details>
  <summary>Code</summary>

```js 
return BackgroundGeolocation.ready({
			// Geolocation Config
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			distanceFilter: 10,
			// Activity Recognition
			stopTimeout: 1,
			// Application config
			debug: __DEV__, // <-- enable this hear sounds for background-geolocation life-cycle.
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
			stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
			startOnBoot: true, // <-- Auto start tracking when device is powered-up.
			// HTTP / SQLite config
			batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
			autoSync: false, // <-- [Default: true] Set true to sync each location to server as it arrives.
			// Android: Foreground service
			foregroundService: true,
			notification: {
				title: 'Telldus Live! Mobile',
				text: 'GeoFence Tracking',
				smallIcon: 'drawable/icon_notif', // <-- defaults to app icon
				largeIcon: 'drawable/icon_notif',
			},
		}).then(async (state: Object): Object => {
			if (!state.enabled) {
				state = await dispatch(startGeofences());
			}
			if (state.enabled) {
				try {
					let location = await BackgroundGeolocation.getCurrentPosition({
						timeout: 30,
						maximumAge: 5000,
						desiredAccuracy: 10,
						samples: 3,
					}) || {};
					const {
						latitude,
						longitude,
					} = location.coords || {};
					dispatch(setCurrentLocation({
						latitude,
						longitude,
					}));
				} catch (e) {
					// Ignore
				}
			}
			return state;
		});
```
</details>

## Expected Behavior

**GIVEN THE LISTENERS ARE NOT CLEARED AT UNMOUNT**

In both the platforms, expect the `onGeofence` event at the JS realm to be fired during all three cases(app running in foreground, background, app killed)

## Actual Behavior

**Have not tested in iOS**

In Android `onGeofence` event seem to be not consistent when the app is not running in the foreground.

## Steps to Reproduce

Ignoring this part as it is not relevant.

## Context

In my use case, starting the SDK in `TrackingMode: 0`. Irrespective of the app state if I could receive `onGeofence` event at the JS side, consistently in both the platforms, would make the job a lot easier.

Assuming the app is not running in foreground, upon `onGeofence` event, could start a background task and execute some actions based on it(involves multiple API requests). Stop the task once done.

I am aware that [headless](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode) is an option in Android to receive events even when app is killed. That could get a little dirty as I will need access to "redux store" inside my headless method.

If headless is my last resort means happy to implement that, but could you please suggest some equivalent way to handle events in iOS when the app is not running?

You have done a great job with the docs and may be there are many similar issues already out there, My Bad! was getting mixed messages from different issues!

Say, reading [this](https://github.com/transistorsoft/react-native-background-geolocation/issues/938#issuecomment-570650393) get a feeling that at least in iOS there is a chance that the `onGeofence` event will be fired always, what ever the app state be. And then [this thread](https://github.com/transistorsoft/react-native-background-geolocation/issues/896#issuecomment-552200383)[but android] contradicts my above assumption :)

Will be very helpful to hear from you, which is the best way to receive `onGeofence` event at JS realm, irrespective of app state, consistently in both the platforms.

Thanks!

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Ignoring this part as it is not relevant.
```

</details>

**Comment by christocracy** [comment]
When your Android app is *terminated*, there are no more `onXXX` events.   Your RN app no longer exists.  

```javascript
// This no longer exists in headless state:
AppRegistry.registerComponent('YourApp', () => App);
```

All Android events are sent to your configured *Headless Task* (assuming you've configured `enableHeadless: true`.

**Comment by rimzici** [comment]
Thanks for the quick response!

Is there any way to listen for those events at the native side?

**Comment by christocracy** [comment]
If you want to receive events from the plugin while your Android app is terminated, the *only* way is by implementing [Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode)

**Comment by rimzici** [comment]
Ok. What about iOS?

**Comment by christocracy** [comment]
iOS has no concept of "*Headless*".  That's why the Wiki is titled "*Android Headless Mode*".

If the iOS plugin fires an event, your app is necessarily completely alive in the background, just as if launched from the home-screen.

**Comment by rimzici** [comment]
Ah I see. Think that can battery intensive.

**Comment by christocracy** [comment]
>Think that can battery intensive.

Not really.  I run a number of versions of my demo app for *React Native*, *Cordova*, *Flutter* and *pure native* on my device that track me everywhere I go.

- Battery Activity &mdash; Last 10 days:
![](https://dl.dropbox.com/s/htzrzn3hswluk61/Screenshot%202020-05-18%2010.40.07.png?dl=1)

**Comment by rimzici** [comment]
Wow. That is interesting!

Thanks for your time @christocracy
