### ISSUE TITLE
Android message toast

### ISSUE THREAD

**Issue by Geo1001** [transistorsoft/react-native-background-geolocation#1060]
* Plugin version:
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version: 0.60.5
* Plugin config

Expected Behavior
To not show android toast

Actual Behavior
Showing a toast message of invalid key.

Im only using this library for ios. In android there is a toast of invalid key that shows up when i turn it on. Is there a way to deactivate it? Or does this toast does not show up if I upload my app to google play console?

**Comment by christocracy** [comment]
>Is there a way to deactivate it

Show me your `package.json`

**Comment by tristanyong** [comment]
Sorry to intrude but I am currently facing the same issue as Geo1001. Is there a way I can prevent the toast message from appearing as I am not using the library for android?

**Comment by christocracy** [comment]
Show me your package.json

**Comment by tristanyong** [comment]
{
  "rnpm": {
    "assets": [
      "resources/fonts"
    ]
  },
  "name": "auth",
  "version": "2.8.8",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "lint": "eslint .",
    "ios": "open ios/auth.xcworkspace"
  },
  "dependencies": {
    "@babel/runtime": "^7.3.1",
    "@react-native-community/async-storage": "^1.7.0",
    "@react-native-community/geolocation": "^2.0.2",
    "firebase": "^5.3.1",
    "lottie-ios": "^3.1.3",
    "lottie-react-native": "^3.3.2",
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-android-open-settings": "^1.3.0",
    "react-native-background-fetch": "^3.0.5",
    "react-native-background-geolocation": "^3.6.2",
    "react-native-cache": "^1.1.7",
    "react-native-camera": "^2.10.1",
    "react-native-check-box": "^2.1.7",
    "react-native-dark-mode": "^0.2.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-fbsdk": "^1.0.4",
    "react-native-firebase": "~5.6.0",
    "react-native-geocoding": "^0.3.0",
    "react-native-gifted-chat": "^0.13.0",
    "react-native-global-props": "^1.1.5",
    "react-native-google-autocomplete": "^0.1.5",
    "react-native-google-signin": "^1.2.3",
    "react-native-icon-badge": "^1.1.3",
    "react-native-image-crop-picker": "^0.31.1",
    "react-native-iphone-x-helper": "^1.2.0",
    "react-native-keycode": "^1.0.5",
    "react-native-map-clustering": "^1.3.2",
    "react-native-maps": "^0.27.1",
    "react-native-maps-super-cluster": "^1.5.0",
    "react-native-modal-datetime-picker": "^7.6.0",
    "react-native-permissions": "^1.2.0",
    "react-native-router-flux": "^4.0.6",
    "react-native-svg": "^9.5.1",
    "react-native-svg-charts": "^5.4.0",
    "react-native-svg-transformer": "^0.13.0",
    "react-native-swiper": "^1.6.0-rc.3",
    "react-native-switch-pro": "^1.0.4",
    "react-native-vector-icons": "^6.4.2",
    "react-native-webview": "^9.1.1",
    "react-router-navigation": "^1.0.0-rc.5",
    "react-spring": "^8.0.25",
    "scheduler": "^0.14.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "babel-preset-react-native": "4.0.0",
    "eslint": "^6.5.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.13.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0",
    "schedule": "^0.4.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "lint": "eslint *.js **/*.js"
}

**Comment by christocracy** [comment]
Why would you use it only for iOS?  There’s no way to prevent the toast.

**Comment by tristanyong** [comment]
we wanted to run it with live users before fully committing to purchase the license in android. But no worries, thank you for getting back on this matter

**Comment by christocracy** [comment]
There is no way to hide the Toast message without purchasing a license key.
