### ISSUE TITLE
App architecture/configuration questions.

### ISSUE THREAD

**Issue by VolodymyrTelenko** [transistorsoft/react-native-background-geolocation#1061]
We will develop(improve|modify existing, actually) mobile app (android only for now).
App architecture is relatively simple.

 - user makes pairing of mobile and some simple hardware(*) through Bluetooth.
From that hardware we get ... an id and maybe 1-2 other info attributes.

- after that we need to start 2 background processes. 
a - background-geolocation. we need to send coordinates to our server trough http.
b - we need inform that paired hardware(*) : we are working correctly, coordinates are sent (last sending time)...  we need to inform it every minute.

- user can stop and start both services again. 

that's all
---------------------------

so, my questions are...

1. i have an id and, maybe, few other attributes(SOME KIND OF EXTENDED DEVICE IDENTIFIERS). i need to send them as a part of background-geolocation http post. How can i do it? Important note : sometimes i need to reconfigure that process(change these attributes) : 
- user stops background process. user chooses different devices, we have different id and we need to start sending coordinates with these new attributes. 
My first idea was to use "#ready" for this. Parameters field, for example. But...
"⚠️ Warning: You must call #ready once and only once, each time your app is launched.
Do not hide the call to #ready within a view which is loaded only by clicking a UI action. "
so... how can i reconfigure background-geolocation ?

2. As i wrote i need to inform hardware(*) every 1 minute. It would be just one BleManager method call. Something like BleManager.Write(...). How can i implement this? Could i use your library for that? 
IMHO i need something like this
  MyBackgroundTask.Ready(...  interval: 60
  ...
  MyBackgroundTask.Start( () => BleManager.Write(...) )
  ...
  MyBackgroundTask.Stop(

Thank you.

**Comment by christocracy** [comment]
See API docs `Config.params`, `Config.extras`, `BackgroundGeolocation.setConfig`.

**Comment by VolodymyrTelenko** [comment]
hi again! it's almost ok, but...

BackgroundGeolocation.ready(
      {
        url: trackerHost,
        reset: true, //?
        stopTimeout: 1,
        debug: true, //sounds
        logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
        foregroundService: true,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        notification: {
          title: "eobu geolocation service",
          text: "Tracking engaged"
        },
        **params: {
          "obuserialnumber": "54072010191108887777777815"
        },**
        distanceFilter: 10,
        enableHeadless: true,
        heartbeatInterval: 60
      },
      async state => {

later

   BackgroundGeolocation.setConfig({
        **params: {
          "obuserialnumber": "54072010191108427777777815"
        }**
      });

in log 

[Tue Jun 02 2020 18:14:54.110]  LOG      - Configure success:  {"activityRecognitionInterval": 10000, "allowIdenticalLocations": false, "authorization": {}, "autoSync": true, "autoSyncThreshold": 0, "batchSync": false, "configUrl": "", "debug": true, "deferTime": 0, "desiredAccuracy": 0, "desiredOdometerAccuracy": 100, "didLaunchInBackground": false, "disableAutoSyncOnCellular": false, "disableElasticity": false, "disableLocationAuthorizationAlert": false, "disableMotionActivityUpdates": false, "disableStopDetection": false, "distanceFilter": 10, "elasticityMultiplier": 1, "enableHeadless": true, "enableTimestampMeta": false, "enabled": false, "encrypt": false, "extras": {}, "fastestLocationUpdateInterval": -1, "forceReloadOnBoot": false, "forceReloadOnGeofence": false, "forceReloadOnHeartbeat": false, "forceReloadOnLocationChange": false, "forceReloadOnMotionChange": false, "forceReloadOnSchedule": false, "foregroundService": true, "geofenceInitialTriggerEntry": true, "geofenceModeHighAccuracy": false, "geofenceProximityRadius": 1000, "geofenceTemplate": "", "headers": {}, "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask", "heartbeatInterval": 60, "httpRootProperty": "location", "httpTimeout": 60000, "isFirstBoot": true, "isMoving": false, "locationAuthorizationRequest": "Always", "locationTemplate": "", "locationTimeout": 60, "locationUpdateInterval": 1000, "locationsOrderDirection": "ASC", "logLevel": 4, "logMaxDays": 3, "maxBatchSize": -1, "maxDaysToPersist": 1, "maxRecordsToPersist": -1, "method": "POST", "minimumActivityRecognitionConfidence": 75, "motionTriggerDelay": 0, "notification": {"actions": [], "channelName": "TSLocationManager", "color": "", "largeIcon": "", "layout": "", "priority": 0, "smallIcon": "", "strings": {}, "text": "Tracking engaged", "title": "eobu geolocation service"}, "odometer": 0, **"params": {"obuserialnumber": "54072010191108887777777815"}**, "persist": true, "persistMode": 2, "schedule": [], "scheduleUseAlarmManager": false, "schedulerEnabled": false, "speedJumpFilter": 300, "startOnBoot": true, "stationaryRadius": 25, "stopAfterElapsedMinutes": 0, "stopOnStationary": false, "stopOnTerminate": false, "stopTimeout": 1, "trackingMode": 1, "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking", "url": "https://myserver.cz/PositionDataServer/senddata", "useSignificantChangesOnly": false}

but... 
I THINK it's not in post...

when i send such json

{
"location": {
	"coords": {
		"latitude": 2.0,
		"longitude": 2.0,
		"accuracy": 2.0,
		"speed": 2.0,
		"heading": 2.0,
		"altitude": 2.0
	},
	"extras": {
	"foo": "bar"
},
"obuserialnumber":"54072010191108420000000815"
}

on "my" server manually it works
but when mobile app does it...
in server log i see this 

2.06.2020 17:07:06.242  Verbose       BP.Service  ThreadPool[0x00]#0    WSStorePositionDataService[0x00000007]
                         Begin WSStorePositionDataService.Execute(StorePositionDataInput: { PositionData: PositionDataInput: { Location: PositionDataLocation: { **ObuSerialNumber: null**, Coords: PositionDataCoords: { Latitude: 50.0319269, Longitude: 14.4860811, Speed: -1, Accuracy: 15.2, Heading: -1, Altitude: 356.9 }, Extras: {}, Activity: {
  "type": "still",
  "confidence": 100
}, Geofence: null, Battery: {
  "is_charging": true,
  "level": 0.86
}, Timestamp: "2020-06-02T11:23:37.302Z", Uuid: "561c5ec5-2bd2-4c87-ba53-188345b15f2d", Event: "motionchange", IsMoving: False, Meters: 0 } }, MessageHeaders: [0]{  } })
----------------------

and... actually i dont know **how to check what exactly my app sends to server**...

is it possible, that my 
   params: {
          "obuserialnumber": "54072010191108887777777815"
   },
settings arent applied on config/post?

thank You in advance

**Comment by dbsali** [comment]
The server json post looks like this

{
  "id": 42994715,
  "company_id": 6312,
  "company_token": "dbs",
  "device_id": 16122,
  "device_model": "iPad6,11",
  "created_at": "2020-05-14T14:59:40.798Z",
  "framework": "react-native",
  "version": "12.4.1",
  "updated_at": "2020-05-14T14:59:40.798Z",
  "activity_type": "still",
  "activity_confidence": 100,
  "battery_level": 1,
  "battery_is_charging": false,
  "uuid": "1487D541-682A-4BED-A072-E86F841AC1F4",
  "event": "motionchange",
  "extras": {},
  "odometer": 275.6,
  "is_moving": false,
  "timestamp": "2020-05-14T14:50:31.277Z",
  "floor": null,
  "speed": -1,
  "heading": -1,
  "accuracy": 65,
  "altitude": 7.3,
  "latitude": 30.3672169974202,
  "longitude": -91.1059837136331,
  "altitude_accuracy": 10,
  "recorded_at": "2020-05-14T14:50:31.277Z"
}

**Comment by dbsali** [comment]
How are you binding your auth token to the app token class ? Check is you have a valid token for posting locations back at server.

**Comment by VolodymyrTelenko** [comment]
hi!
do i need a auth token for simple(not secure) example?
as for me and according to this - no

https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-using-the-plugin

by the way...
its not react-native-background-geolocation error.
it was our server error.

but... what about this
we have duplication's in events timestamps
is it ok?

timestamp":"2020-06-02T19:27:55.658Z"

"timestamp":"2020-06-02T19:27:55.550Z"
"timestamp":"2020-06-02T19:27:55.550Z"

"timestamp":"2020-06-02T19:30:29.858Z"

"timestamp":"2020-06-02T19:30:30.902Z"
"timestamp":"2020-06-02T19:30:30.902Z"

"timestamp":"2020-06-02T20:01:33.482Z"

----------------------

its not good for us because we have some db constraints...

**Comment by VolodymyrTelenko** [comment]
"location":{"event":"motionchange","is_moving":false,"uuid":"0b89f646-448c-4d14-8f31-494901cf73b0","timestamp":"2020-06-02T19:30:30.902Z","odometer":55928.1,"mock":true,"coords":{"latitude":49.941644862889305,"longitude":15.253268703818323,"accuracy":3.9,"speed":0,"heading":-1,"altitude":0},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":1},"extras":{}}}

{"location":{"event":"providerchange","provider":{"network":false,"gps":false,"enabled":false,"status":3},"is_moving":false,"uuid":"710d420a-bd6d-4a2a-bfea-85548890d896","timestamp":"2020-06-02T19:30:30.902Z","odometer":55928.1,"mock":true,"coords":{"latitude":49.941644862889305,"longitude":15.253268703818323,"accuracy":3.9,"speed":0,"heading":-1,"altitude":0},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":1},"extras":{}}}

**Comment by VolodymyrTelenko** [comment]
hm...

we have two events with the same type and the same timestamp

{"location":{"event":"motionchange","is_moving":false,"uuid":"04670134-a12c-415f-86d1-b6a02c15bf3d","timestamp":"2020-06-02T19:27:55.550Z","odometer":0,"mock":true,"coords":{"latitude":49.941644862889305,"longitude":15.253268703818323,"accuracy":6.9,"speed":0,"heading":-1,"altitude":0},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":1},"extras":{}}}

{"location":{"event":"motionchange","is_moving":false,"uuid":"19f2e8df-99d0-47df-a265-ec96565d26c2","timestamp":"2020-06-02T19:27:55.550Z","odometer":0,"mock":true,"coords":{"latitude":49.941644862889305,"longitude":15.253268703818323,"accuracy":6.9,"speed":0,"heading":-1,"altitude":0},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":1},"extras":{}}}

**Comment by VolodymyrTelenko** [comment]
@dbsali 

we have such json-s

{"location":{"event":"motionchange","is_moving":false,"uuid":"b6b98cf2-e5ad-4702-99a0-0b767b3e0d6d","timestamp":"2020-06-02T18:00:32.712Z","odometer":0,"coords":{"latitude":50.0319203,"longitude":14.486117,"accuracy":20.2,"speed":-1,"heading":-1,"altitude":356.9},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"

what we need to do to have 

"created_at": "2020-05-14T14:59:40.798Z",
...
"updated_at": "2020-05-14T14:59:40.798Z",
...
"timestamp": "2020-05-14T14:50:31.277Z",
...
"recorded_at": "2020-05-14T14:50:31.277Z"
...

in it?

**Comment by VolodymyrTelenko** [comment]
sorry for annoying but... its 22:54 in Prague... it was long day and i want to go home :)
could you please answer on last question/s?

1. how can i filter which events to send on server?
2. is it possible to have unique timestamps?
3. is it possible to customize post json? i mean... add such attributes for example

"created_at": "2020-05-14T14:59:40.798Z",
"updated_at": "2020-05-14T14:59:40.798Z",
"timestamp": "2020-05-14T14:50:31.277Z",
"recorded_at": "2020-05-14T14:50:31.277Z"

thank you!

**Comment by dbsali** [comment]
Why don't you add the extra fields in DB ? if you are not able to post those attributes through the app.

**Comment by VolodymyrTelenko** [comment]
sorry but i don't understand :(
you told me : the server json post looks like this
but... my json posts looks different
i just ask you.. how to configure module to send json like in your example.

we need such data from module. its not about additional fields in our db...

**Comment by dbsali** [comment]
Show me your config ?

**Comment by VolodymyrTelenko** [comment]
// Step 2:  #configure:
    BackgroundGeolocation.ready(
      {
        url: trackerHost,
        reset: true, //?
        stopTimeout: 1,
        debug: true, //sounds
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        foregroundService: true,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        notification: {
          title: "eobu geolocation service",
          text: "Tracking engaged"
        },
        distanceFilter: 10,
        enableHeadless: true,
        heartbeatInterval: 60
      },
      async state => {
        console.log("- Configure success: ", state);

        if (state.enabled) {
          await BackgroundGeolocation.stop();
          console.log("BackgroundGeolocation.stop");
        }
      }
    );
  }

**Comment by dbsali** [comment]
Are you using PHP ?

**Comment by VolodymyrTelenko** [comment]
**react-native**-background-geolocation

so... js/ts...

**Comment by dbsali** [comment]
On the server side

**Comment by VolodymyrTelenko** [comment]
.net
but... why? its not important...
json from client is the same on any server...

**Comment by christocracy** [comment]
> what we need to do to have
>"created_at": "2020-05-14T14:59:40.798Z",
>"updated_at": "2020-05-14T14:59:40.798Z",
>"recorded_at": "2020-05-14T14:50:31.277Z"

The plugin has no business adding those attributes.  Those are the responsibility of your server to add those.

**Comment by VolodymyrTelenko** [comment]
@christocracy ok, thank you for your answer.

but what about timestamps? nad events filtering
" - how can i filter which events to send on server?
- is it possible to have unique timestamps?"

**Comment by christocracy** [comment]
There a variety of situations where the same location may be recorded.
- transitioning between moving states.
- executing getCurrentPosition.

It’s impossible to speculate without logs from the plugin.  Are you observing the logs?
