### ISSUE TITLE
License Validation Failure (in debug mode) - Android

### ISSUE THREAD

**Issue by m-tbox** [transistorsoft/react-native-background-geolocation#1062]
Hello @christocracy ,

**Environment**
react-native - "0.59.9"
react-native-background-geolocation": "3.6.2"
plugin configs:
```
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 2,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url:  apiUrl,
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
       ...headers
      },
      params: {               // <-- Optional HTTP params
        lat: 'lat',
        long: 'long'
      }
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        ////
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
  }
```

I am making debug build on Redmi Note 4 Android 7 using following command 
`npx react-native run-android`

When I open the app I get License Validation Failure toast 

![Screenshot_2020-05-18-12-17-02-364_com src](https://user-images.githubusercontent.com/20038122/82316813-cc757900-99e6-11ea-9bdf-1a38153fce16.jpg)

**Comment by christocracy** [comment]
If you haven’t purchased a license, that Toast is normal and expected.

The plugin is fully functional in debug builds so you can try before you buy, in spite of the warning.

**Comment by m-tbox** [comment]
@christocracy thanks for the fast response. I have added debug points on the callback events i.e onLocation onMotion but onMotionChange but when move and change location these callbacks are not called

**Comment by christocracy** [comment]
See wiki *Debugging*

**Comment by rleira** [comment]
@christocracy I'm in debug mode and followed steps here: https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID.md

I'm using:
```
    "react-native": "0.61.5",
    "react-native-background-fetch": "^3.1.0",
    "react-native-background-geolocation": "^3.8.1",
```

And still get:

<img width="277" alt="Screen Shot 2020-08-13 at 20 03 53" src="https://user-images.githubusercontent.com/11665728/90195585-3318f180-dda0-11ea-8119-21f74d243e39.png">

Command used to run:
```
react-native run-android
```

Anything else I should look into?

**Comment by christocracy** [comment]
Have you purchase a license?  If that, that message is *expected*.

**Comment by rleira** [comment]
@christocracy not sure I understand the documentation and you say that for debug the license is not required

> If you haven’t purchased a license, that Toast is normal and expected.
> 
> The plugin is fully functional in **debug builds** so you can try before you buy, in spite of the warning.

**Comment by christocracy** [comment]
If you haven’t yet purchased a license, the plugin is fully functional in debug builds.

Yes, you can expect a “Licence Validation Failure” message.  Ignore it and continue testing.  It *is* working.

**Comment by matheusyuri7** [comment]
hello @christocracy I'm planning to use this library only for ios devices, but this message keep showing on android devices. Is there a way I can hide this message on android?
