### ISSUE TITLE
watchPosition not work after Terminate App

### ISSUE THREAD

**Issue by bapdola304** [transistorsoft/react-native-background-geolocation#1063]
My config: 
BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      stopOnTerminate: false,
      reset: true,
      forceRequestLocation: true,
      stopTimeout: 999,
      foregroundService: true,
      enableHeadless: true,
    });

My function:
BackgroundGeolocation.watchPosition(
      this.onLocationChanged,
      function (errorCode) {
      },
      {
        interval: 10000,    // <-- retrieve a location every 10s.
      }
    );

Why i Terminate App then function watchPosition not working ?
Tks.

**Comment by christocracy** [comment]
That’s the expected behavior.  If it didn’t do this, location-services would turn on forever and kill the battery.  watchPosition is designed for use when your app is in the foreground only.  It’s not meant for long term use in the background.

**Comment by bapdola304** [comment]
tks  @christocracy
