### ISSUE TITLE
Location not updating on server after app has been terminated for some minutes

### ISSUE THREAD

**Issue by m-tbox** [transistorsoft/react-native-background-geolocation#1064]
Hello @christocracy 

After the app been in closed for some minutes and device is still then if I start to move location is not being updated . I am using following config and environment 

**Environment**

React Native version: 0.59.9
Plugin version: 0.6.3
Platform: Android
OS version: 7
Device manufacturer and model: Redmi Note 4

**Plugin configuration options**

```
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      foregroundService: true,
      // HTTP / SQLite config
      url: apiUrl,
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "X-FOO": "bar"
      },
      params: {               // <-- Optional HTTP params
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
      if (!state.enabled) {
        ////
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
    BackgroundGeolocation.start(function() {
      console.log("- Start success");
    })
  }
```

**Comment by christocracy** [comment]
Are you watching adb logcat?

**Comment by christocracy** [comment]
Also see http://dontkillmyapp.com

**Comment by bapdola304** [comment]
hi @christocracy 
this is my issue
my config: 
configureBackgroundGeolocation() {
    // Step 1:  Listen to events:
    BackgroundGeolocation.onLocation(this.onLocation);
    // Step 2:  #configure:
    BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 4,
      autoSync: true,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
    });
  }

after app has been terminated, function onLocation don't trigger? tks @christocracy

**Comment by christocracy** [comment]
> after app has been terminated, function onLocation don't trigger?

Correct.  See wiki “Headless JS”

**Comment by bapdola304** [comment]
> > after app has been terminated, function onLocation don't trigger?
> 
> Correct. See wiki “Headless JS”

hi @christocracy  I used Headless JS, but i don't know stop it when I use function BackgroundGeolocation.registerHeadlessTask().
tks.

**Comment by christocracy** [comment]
>but i don't know stop it

I don't understand what you're saying.

**Comment by bapdola304** [comment]
> > but i don't know stop it
> 
> I don't understand what you're saying.

I mean, I use BackgroundGeolocation.registerHeadlessTask() to run app after app has been terminated. How do i stop BackgroundGeolocation.registerHeadlessTask() ?

**Comment by christocracy** [comment]
You don’t.

**Comment by bapdola304** [comment]
> You don’t.
hi @christocracy , I havae a warning: "registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'BackgroundGeolocation' "

**How do I check if it exists and don't call back?**

**Comment by christocracy** [comment]
I have no idea.  You registerHeadlessTask index.js.  Nowhere else.  Ever.
