### ISSUE TITLE
Geofence Radius Clarification

### ISSUE THREAD

**Issue by objectiveSee** [transistorsoft/react-native-background-geolocation#1065]
## Your Environment
* Plugin version: 
```
   "react-native": "~0.61.5",
    "react-native-background-fetch": "^3.0.5",
    "react-native-background-geolocation": "^3.6.2",
```
* Platform: iOS or Android: iOS 13 Simulator
* OS version: 13
* Device manufacturer / model: Apples
* React Native version (`react-native -v`):
```
🚐 react-native -v
react-native-cli: 2.0.1
react-native: 0.61.5
```
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
      {
        // Geolocation Config
        desiredAccuracy: ACCURACY_REQUESTED,
        distanceFilter: 60,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: DEBUG_BACKGROUND_GEO, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: STOP_ON_TERMINATE, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: START_ON_BOOT, // <-- Auto start tracking when device is powered-up.
        // HTTP / SQLite config
        // TODO: configure remote server if desired
        autoSync: false,
        // geofenceModeHighAccuracy: true,  Android only?
        /*
          url: 'http://yourserver.com/locations',
          batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
          autoSync: false, // <-- [Default: true] Set true to sync each location to server as it arrives.
          headers: {
            // <-- Optional HTTP headers
            'X-FOO': 'bar',
          },
          params: {
            // <-- Optional HTTP params
            auth_token: 'maybe_your_server_authenticates_via_token_YES?',
          },
          */
      },
```

## Expected Behavior
According to documentation there is a minimum 1000m value for `geofenceProximityRadius`. However elsewhere in the docs it says "The minimum reliable radius is 200 meters." and the code examples use 200m not 1000m. Can we be using 200 instead of 1000? For me 1000m is not accurate enough and I will have to implement additional code to see if they are inside my location when they are inside the "wider" 1000m geofence. This seems like extra work so I'd love a clarification on the docs. Additionally, any help on how to detect/monitor if someone is within a smaller radius location. Seems like I'll need an additional "more precise" monitoring layer on top of this library - which is a lot of work IMHO. In my testing w/ the Expo location library I was seeing pretty accurate geofence responses with 20-100m FWIW. Could we just remove the "enforced" 1000m limit?

Thanks!

Doc 1: https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#geofenceproximityradius

Doc 2: https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.geofence.html

## Actual Behavior
NA

## Steps to Reproduce
NA

## Context
See Above

## Debug logs
NA

**Comment by objectiveSee** [comment]
Also, separate but related... I noticed that you can't use `BackgroundGeolocation.onGeofence` in conjunction with `BackgroundGeolocation.start`. Instead you must use `onGeofencesChanged` instead. Is that correct? The two APIs seem to be the same, could they not be unified?


```
BackgroundGeolocation.onGeofence((event) => {
  console.log("[onGeofence] ", event);
});
```



https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#ongeofence

**Comment by christocracy** [comment]
geofenceProximityRadius has nothing to do with Geofence.radius.  They are completely different.  You generally don’t need to concern yourself geofenceProximityRadius.

onGeofence too is completely different than onGeofencesChange.  You don’t need to worry about onGeofencesChange.
