### ISSUE TITLE
not working on android without GMS (google mobile service ) 

### ISSUE THREAD

**Issue by omernaser** [transistorsoft/react-native-background-geolocation#1066]
a lot of our client use this plugin and can't work on huawei device bcz its HMS Base we need to make a integration with Huawei mobile service we have the same functionality of google and the same method and event name but we need to change the importing  of google can any one help us on this issue i think its a easy thing but we don't have access to the core code please advice 

## Your Environment
* Plugin version:latest
* Platform:  Android
* OS version:androdi 10,9
* Device manufacturer / model:huawei mate 30 hms (not gms)
```javascript <!-- Syntax-highlighting:  paste your code below -->
```

## Expected Behavior

should works in both HMS and GMS 
## Actual Behavior

not working in HMS Devices
## Steps to Reproduce

1.just run the it on HMS Device you will see the error at the log

## Context

</details>

**Comment by christocracy** [comment]
This plugin has no support for Huawei's HMS.

**Comment by omernaser** [comment]
please refer to the following image for more info 
![image](https://user-images.githubusercontent.com/13206366/82926610-226a9380-9f88-11ea-9a7b-b8cf97bb1fac.png)
 this is the file of is exist on TSLocationManager

![image](https://user-images.githubusercontent.com/13206366/82926763-55148c00-9f88-11ea-909c-a7d1869cdda1.png)

and we have the sample importing on huawei as this

import com.huawei.hms.location.LocationServices;
import com.huawei.hms.location.FusedLocationProviderClient;
import com.huawei.hms.location.LocationRequest;
import com.huawei.hms.location.LocationResult;
import com.huawei.hmf.tasks.Tasks;

**Comment by christocracy** [comment]
I won't be supporting HMS any time soon.

**Comment by omernaser** [comment]
can you advice if can i make it in workaround way

**Comment by christocracy** [comment]
>can you advice if can i make it in workaround way

I have no advice.

**Comment by christocracy** [comment]
Do you know of *any* react-native plugin supporting HMS currently?

**Comment by omernaser** [comment]
no , but i am on huawei team if we can help in any thing to make it faster please let me know

**Comment by christocracy** [comment]
I **HATE** Huawei devices.  They're *the absolute worst* devices on earth for background-services.  Have you seen http://dontkillmyapp.com?

**Comment by omernaser** [comment]
i got it i will contact with my team if they can help on this issue

**Comment by christocracy** [comment]
Let me know when Huawei allows background-services to run as documented in *Android API* without app developers being forced to instruct their users to [modify a long list of various settings](https://dontkillmyapp.com/huawei) to allow background-location tracking to work.

Then I *might* be interested in supporting HMS.  Until then, the fewer people using Huawei devices, the better.

**Comment by deveasywork** [comment]
Hi. I have a similar issue with a few of my paid users that are using Huawei phone. In my apps, I am using this library to acquire their location. 

I found this 
https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/location-description-rn-v4 

Would it be something possible for the library to use it to support for HMS phone? 

"instruct their users to modify a long list of various settings" would still be acceptable for me as it's their choice to use this phone model and I think it's fine considering they already doing some extra steps to download apps not in Huawei App Gallery. 

But it would be best if we can at least get the location for them from my apps, even though they have to do some prior settings themselves.

**Comment by christocracy** [comment]
I've been playing with the [Huawei Convertor](https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/convertor-0000001050147221):  Huawei support is coming soon.

**Comment by christocracy** [comment]
Who wants to be *the first* to test *Huawei HMS* support?  Install the plugin from this repo (branch `#hms`)

```bash
$ yarn add https://github.com/transistorsoft/react-native-background-geolocation.git#hms
```

Unfortunately, I discovered *after purchase* that my __`$650`__ *Nova 9 SE* does not have a *Gyroscope* and HMS `ActivityRecognition` API doesn't work when *Gyroscope* is missing.  *Google Play Services'* `ActivityRecognition` API will still work with at least an *accelerometer*.

```
TSLocationManager: ╔═════════════════════════════════════════════
TSLocationManager: ║ DEVICE SENSORS
TSLocationManager: ╠═════════════════════════════════════════════
TSLocationManager: ╟─ ✅  ACCELEROMETER: {Sensor name="acc_s004_002 Accelerometer Non-wakeup", vendor="Kionix", version=132096, type=1, maxRange=78.45318, resolution=0.0023928226, power=0.145, minDelay=2500}
TSLocationManager: ╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
TSLocationManager: ╟─ ✅  MAGNETOMETER: {Sensor name="mag_s004_001 Magnetometer Non-wakeup", vendor="QST", version=258, type=2, maxRange=4912.0, resolution=0.1, power=1.1, minDelay=10000}
TSLocationManager: ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="sns_smd  Wakeup", vendor="qualcomm", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.025, minDelay=-1}
TSLocationManager: ╚═════════════════════════════════════════════
```

**Comment by rodrigodiasf1984** [comment]
Hi, I'm getting this error too, but in a xiami device: 
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/30758309/9a17bfde-3282-4bfe-b3e2-60fed9d87474)

how can I solve this? Thanks
