### ISSUE TITLE
How can I get action(ENTER/EXIT/DWEL) from current location.

### ISSUE THREAD

**Issue by TinhLa** [transistorsoft/react-native-background-geolocation#1070]
Hi @christocracy,

According to the title, I want to get action(Enter/exit/dwell) of Geofences base on my current location without onGeofence() function.
I have already addGeofences.
Which the function work for that?

**Comment by christocracy** [comment]
When a geofence is triggered, onGeofence event fires.  Period.  Geofence triggers are handled by the operating system.  The plugin is only the messenger.  It doesn’t *cause* geofences to fire by executing getCurrentPosition

**Comment by TinhLa** [comment]
Hi @christocracy 

It's mean, I can't check which geofence that I'm in, right?

Thanks.

**Comment by christocracy** [comment]
No.  The plugin does not remember this.  You must take care of that yourself.  Your server will know this.
