### ISSUE TITLE
How to get location updates consistently regardless if the app is in the foreground or not

### ISSUE THREAD

**Issue by supermar1010** [transistorsoft/react-native-background-geolocation#1071]
## Your Environment
* Plugin version: 
* Platform: Android
* OS version: 10
* Device manufacturer / model: Emulator
* React Native version (`react-native -v`): 3.2.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    {
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
    },
```

## Expected Behavior
I want to receive location updates in the foreground the same way as I do while in background. So only if the device is physically moving and with the distance filter?

## Actual Behavior

I tried using `watchPosition` but this leads to updates every second without movement.

**Comment by supermar1010** [comment]
I want location updates while the app is in foreground and the device moves.

I think I found the solution, somehow the tracking worked only with the app in background, I added a call to `changePace(true)` as I'm testing in a simulator right now, now it also works in the foreground. A bit weird why t worked in the background but whateveer works now, I have to test on a real device nethertheless.

**Comment by christocracy** [comment]
This is not weird at all.  The plugin triggers location tracking when the motion api says the device is moving (accelerometer, gyroscope, magnetometer).  The motion api doesn’t work in emulator.

See wiki *Debugging* and *Philosophy of Operation*.

**Comment by supermar1010** [comment]
I know, the weird thing was, that it worked flawless while in background, but not while in foreground.

**Comment by christocracy** [comment]
The plugin doesn't care if the app is in the foreground, background or terminated.  It only cares if the device is *moving*.  If the device is moving, the plugin will record locations according to your configured `distanceFilter` / `locationUpdateInterval`, regardless of background/foreground/terminated.

You'll never be able to experience the true behaviour of the plugin in Android emulator.  It's best to test on a real device with real movement.

**Comment by Ruzen1** [comment]
@christocracy Hey Chris, I wanted to know on what basis will the location get updated if I don't write distanceFilter or locationUpdateInterval in config.

**Comment by christocracy** [comment]
Read the wiki *Philosophy of Operation*.

The default distanceFilter is 10.
