### ISSUE TITLE
App crashes on iOS when screen locked and permission granted is just "When in use"

### ISSUE THREAD

**Issue by Buthrakaur** [transistorsoft/react-native-background-geolocation#1072]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS, Android
* OS version: any
* Device manufacturer / model: any
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOW,
  distanceFilter: 1000.0,
  reset: false,
  stopTimeout: 1,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
  stopOnTerminate: false,
  startOnBoot: true,
  enableHeadless: true,
  maxDaysToPersist: 14,
  geofenceProximityRadius: 50000,
  notification: {
    smallIcon: 'drawable/ic_stat_ic_notification',
    largeIcon: 'drawable/ic_stat_ic_notification',
  },
}
```

## Expected Behavior

App should not crash after screen locked. The geofences won't obviously work on lock screen because of insufficient location permission and plugin should handle missing permissions on its own.

## Actual Behavior

App crashes when plugin is started and screen locked. It looks like the issue may be caused by the plugin trying to display a "Background location is not enabled" dialog 
![image](https://user-images.githubusercontent.com/126757/83891225-213a2300-a74d-11ea-92d8-cc0ed631b88c.png)
 on the background because if we lock the screen with this dialog open the app doesn't crash.

## Steps to Reproduce

1. launch app with plugin started and some geofences added
2. grant only "While in use" permission when asked
3. lock screen
4. unlock screen - home screen is displayed as the app crashed on background

## Context

We try to make our app usable even for users who granted just "while in use" location permission - the geofencing should work for them in foreground and stop working on background without crashing the app.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- If you have a crash, you need to provide the stacktrace.
- If you don't care what the user authorizes for location, see `Config.locationAuthorizationRequest`
