### ISSUE TITLE
the onHeartBeat handler stops being called

### ISSUE THREAD

**Issue by placka** [transistorsoft/react-native-background-geolocation#1073]
Our program has to:
 - send current coordinates to the server as often as possible
 - send a set of commands to a separate device trough bluetooth at least once a minute. Each data transmission only takes about 2-3 seconds.
 
 I used your plugin and configured the sending of the coordinates. 
 Bluetooth communication was done in the onheartbeat handler.
 
 The problem is as follows: It seems like during the active sending of the coordinates by HTTP the onHeartBeat handler stops being called.
 Could you please suggest any possible solutions for us.
 
 Thank you

**Comment by christocracy** [comment]
You’ve ignored the issue template which asked you which platform (iOS or Android).

The two operate completely different in the terminated state.

**Comment by VolodymyrTelenko** [comment]
sorry for that

* Plugin version: 3.6.2
* Platform: iOS or Android
  it's Android for now but we plan to provide ios version in the future
* OS version: 10
* Device manufacturer / model: samsung a20
* React Native version (`react-native -v`): 2.0.1/0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready(
      {
        url: trackerHost,
        reset: true, //?
        stopTimeout: 1,
        debug: true, //sounds
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        foregroundService: true,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        notification: {
          title: "eOBU Geolocation Service",
          text: "Tracking engaged"
        },
        distanceFilter: 10,
        enableHeadless: true,
        heartbeatInterval: 60
      },
```

**Comment by VolodymyrTelenko** [comment]
sorry for that

* Plugin version: 3.6.2
* Platform: iOS or Android
  it's Android for now but we plan to provide ios version in the future
* OS version: 10
* Device manufacturer / model: samsung a20
* React Native version (`react-native -v`): 2.0.1/0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready(
      {
        url: trackerHost,
        reset: true, //?
        stopTimeout: 1,
        debug: true, //sounds
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        foregroundService: true,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        notification: {
          title: "eOBU Geolocation Service",
          text: "Tracking engaged"
        },
        distanceFilter: 10,
        enableHeadless: true,
        heartbeatInterval: 60
      },
```
