### ISSUE TITLE
Rebuild libpbkdf2.so with SDK R19C and make sure c++_shared is used

### ISSUE THREAD

**Issue by K-Leon** [transistorsoft/react-native-background-geolocation#1074]
While using this Library with newer React Native Versions i noticed that there is a mismatch between the use c++_shared versions in libpbkdf2 and React Native itself. (Since 0.60 - Noticed it with 0.62)

Usually this isn't that big of a deal because of pickFirst Rules and a mostly lucky buildorder. But i'am seeing severe Issues due to mismatching c++_shared implementations / loading issues with third party libraries. As soon as react-native-background-geolocation is getting into the mix c++_shared loading from third party lib isn't working properly anymore. 

I hope it is solved by rebuilding libpbkdf2.so with SDK R19C. This is the one that React Native uses. 

But i'm not sure if the issues are only caused by the SDK version or that library isn't using c++_shared at all (https://developer.android.com/ndk/guides/cpp-support) (Following the ndk docs it is highly recommended)

**Comment by christocracy** [comment]
This was implemented by someone who wanted to encrypt the location data in the SDK's sqlite db as well as HTTP data uploaded to configured `url`, enabled with `Config.encrypt`.  Most people probably don't even use this feature.

I literally copied the compiled `libpbkdf2` libs into the plugin's source from [rncryptor-android](https://github.com/byteamaze/rncryptor-android/tree/master/RNCryptorAndroid/src/main/jniLibs).

What specifically is the issue?  Is there a build error?

**Comment by K-Leon** [comment]
It digged deeper and it looks like the rncryptor lib is embedding the c++ std library directly. (Static Link) I have a third party library that relies - like react native - on c++_shared. (Namely HERE SDK) They don‘t have a that robust loading system like facebook with soloader. This means it fails detecting and loading the c++ standard library. 

Now I’m trying to get rid of it. I already checked the rncryptor library. As far as I can tell the native library is only used for the crypt function that is probably not relevant for this feature?

**Comment by christocracy** [comment]
Can you show me the specific build-error your'e seeing?

**Comment by K-Leon** [comment]
It is the result of a runtime check for c++_shared. `Native libraries missing: c++_shared.` Skipping the Check leads to a crash on native side.

As soon as i add your aar library to the mix this starts to happen. The only explanation i have so far are the .so libraries for the crypt feature. Would it be by chance possible to make a build without rncryptor? This would help me a lot to test the theory.

Thanks in Advance!

**Comment by christocracy** [comment]
I’ve had builds issues with libpbkdf2 when I yarn add the plugin, which is solved by gradlew clean.

Maybe next week I can l produce a build without rncryptor.

**Comment by christocracy** [comment]
I’ve had builds issues with libpbkdf2 when I yarn add the plugin, which is solved by gradlew clean.

Maybe next week I can l produce a build without rncryptor.

**Comment by K-Leon** [comment]
I experimented a bit more and noticed that the JNI Issues started with the Android X Build ( 3.7.x) and it isn't related to any other dependencies you're relying on. I tested every part in isolation.

Everything works until including the AAR. As soon as it is getting loaded the JNI Issues are starting. (Dependency tree and everything is also fine. (The Versions that should get loaded are getting loaded)
There seems to be something conflicting and the only thing that could - as far as i can guess - cause this is rncryptor. 

(Gradle Clean and everything else is mandatory and properly executed.)

**Comment by kaplanlior** [comment]
> I literally copied the compiled `libpbkdf2` libs into the plugin's source from [rncryptor-android](https://github.com/byteamaze/rncryptor-android/tree/master/RNCryptorAndroid/src/main/jniLibs).

Do you have the source code for those binaries?
