### ISSUE TITLE
Android Geofences without Geolocation issues

### ISSUE THREAD

**Issue by glenharris** [transistorsoft/react-native-background-geolocation#1075]
Hi there, congrats on a very well written library with great documentation.  I am evaluating your library for standalone geofencing, and I am having some issues.

## My Environment
* Plugin version: 3.7.0
* Platform: Android
* OS version: 9 
* Device manufacturer / model: Huawei Y5 2019, AMN-LX2, v9.1.0.213
* React Native version (`react-native -v`): 4.10.0
* Plugin config
I have set up a repo with an example project, let me know if you prefer code excerpts instead.
https://github.com/glenharris/rnbg-test.git

## Expected Behavior
I expect to get geofence events as I enter and leave geofenced regions (without having location tracking enabled).

## Actual Behavior
No geofence events are received, apart from an initial event when startGeofences() is called.

## Steps to Reproduce
Start the app in debug mode (npm run start, npm run android etc)
It will automatically create a series of 8 geofences 500m radially surrounding you, and one centered on you.  Each geofence is 200m radius.
Tap the 'Geofence' switch.  This will call BackgroundGeolocation.startGeofences().
Move around (e.g. walk 500m east).
No notifications are received when you leave the 'origin' geofence, or when you enter the 'Offset E 500m' geofence.

## Context
Note that this has been tested on a physical device, with physical movement.

I am fairly sure that I have followed the android plugin install instructions correctly.

Note that if you manually press the 'Update Distance' button, it will call BackgroundGeolocation.getCurrentPosition(), and this seems to remind RNBG to remember to send the correct (late) geofence events based on the current position.

Note that if instead of pressing the 'Geofence' toggle, you press the 'Location + Geofence' toggle, it will call BackgroundGeolocation.start(), and then the geofence events are received as expected.  In other words, when the only change is replacing start() with startGeofences(), then app stops working.

Note that the app is remaining foreground for this simple testcase, so I am assuming that a HeadlessTask is not required for correct operation.

Note that I have not validated behavior on an iOS device.

If you press 'Update Geofences' it will delete the current geofences, and create new ones surrounding your current position.

## Debug logs
Let me know if you need me to add my logs.

**Comment by christocracy** [comment]
With Huawei devices, in my experience the worst devices for background-services, see http://dontkillmyapp.com

**Comment by glenharris** [comment]
Hmm, does that imply I should try it with adding HeadlessTask, or is it more devious than that?

**Comment by christocracy** [comment]
The sdk operates regardless of headless-task.  

First apply the recommendations at http://dontkillmyapp.com.
