### ISSUE TITLE
Is there any way to get event when user turns off the location.

### ISSUE THREAD

**Issue by ssinghal1989** [transistorsoft/react-native-background-geolocation#1081]
## Your Environment
* Plugin version:3.7.0
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
User should see mobile notifications whenever he exit and enter into the fence. And notification to turn on his location if he turns off his location.

</details>

**Comment by christocracy** [comment]
The plugin has 12 events you can listen to.  You should read the api docs and familiarize yourself with all of them.

You will find one of them particularly interesting for the subject of this issue.
