### ISSUE TITLE
Possible errors for 'ready', 'start' and 'stop'

### ISSUE THREAD

**Issue by Legi0n1138** [transistorsoft/react-native-background-geolocation#1084]
Hi! 
Geolocation is a crucial feature of the app I'm currently working at. The situation when tracking fails for some reason is unacceptable, so I'm trying to take into account all possible cases. However, I'm not sure how to handle errors thrown by methods of this lib.

I checked out the docs and haven't found what I was looking for...

Where can I acquire information on the list errors that can be thrown by `ready`, `start`, and `stop` methods?

## Your Environment
* Plugin version: `react-native-background-geolocation-android`, latest
* Platform: iOS and Android
* React Native version (`react-native -v`): 0.61.5

**Comment by christocracy** [comment]
- `#ready` / `#start` will fail if user clicks `[Deny]` on location authorization dialog or if authorization.
- `#stop` will never error.

See `onProviderChange` to capture location authorization events.
See `onLocation` to capture location errors.

**Comment by Legi0n1138** [comment]
>    will fail if user clicks `[Deny]` on location authorization dialog or if authorization fails to resolve (eg: user clicks `[x] stop asking` on dialog).

So `Permission denied` error, right? Or are there any others?
