### ISSUE TITLE
Not getting events in iOS device

### ISSUE THREAD

**Issue by salilgupta2510** [transistorsoft/react-native-background-geolocation#1086]
## Your Environment
* Plugin version: 3.7.0
* Platform: iOS
* OS version: 13+
* Device manufacturer / model: iPhone 6S
* React Native version (`react-native -v`): 0.61.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
It should give events when the user exits from the geofence.

## Actual Behavior
It is not giving events on a real device but gives events on emulator when the location spoofed.

## Steps to Reproduce

1.
2.
3.
4.

## Context
Creating a geofence for user and it should notify the user when the user exit or enter in the defined geofence.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- Minimum reliable geofence radius is `200` meters.
- Geofence exit events can take some distance out of the geofence before they fire.  The following image shows a 200 meter geofence.  The red markers represent the `EXIT` event:
![](https://dl.dropbox.com/s/zyb6ovtkseybyy2/Screenshot%202020-06-22%2010.52.03.png?dl=1)
- FIeld-test with `debug: true` so you can *hear* the events while out field-testing.
