### ISSUE TITLE
headless mode is not working on iOS

### ISSUE THREAD

**Issue by salilgupta2510** [transistorsoft/react-native-background-geolocation#1087]
## Your Environment
Plugin version: 3.7.0
Platform: iOS
OS version: 13+
Device manufacturer / model: iPhone 6S
React Native version (react-native -v): 0.61.4
Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
User should get events of geofence when the app is in the background or terminated

## Actual Behavior
No events received when the app is in the background or terminated

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by michalpechnet** [comment]
Headless mode is Android feature only

**Comment by salilgupta2510** [comment]
What can be done if we want the events when the ios app is terminated or in background ?

**Comment by michalpechnet** [comment]
Honestly I never tried this library when app is terminated so I can't give you any advice. But for background usage there is no advanced settings needed. As far as I know geofences is not so accurate. Have you tried to move far from geofence (for example 1km or more)?

**Comment by christocracy** [comment]
@salilgupta2510 See the API docs `Config.stopOnTerminate` to learn about iOS behaviour when the app is terminated.
