### ISSUE TITLE
beginBackgroundTask is not a function

### ISSUE THREAD

**Issue by yonahforst** [transistorsoft/react-native-background-geolocation#109]
Using 1.3.1 on RN 0.30.0, when I try to do something like:
```js
    BackgroundGeolocation.beginBackgroundTask(taskID => {
      BackgroundGeolocation.getCurrentPosition({timeout: 30, desiredAccuracy: 10}, location => {
        fetch(`https://myserver.com/user/${this._getMyId()}`, {
          method: 'POST',
          headers: new Headers({
            'Authorization': basic_auth,
            'Content-Type': 'application/json',
          }),
          body: JSON.stringify({location: location, updatedAt: location.timestamp}),
        }).then(res => {
          if (res.status != 201) {
            console.warn('background location: error sending location to server:', res)
          }
        }).catch(e => {
          console.warn('background location: error sending location to server:', e)
        }).then(() => BackgroundGeolocation.finish(taskID))
      }, function(error) {
        console.warn("background location: error:" + error)
        BackgroundGeolocation.finish(taskID)
      })
    })
```

I get error: `2016-08-09 19:34:32.321 [error][tid:com.facebook.react.JavaScript] _reactNativeBackgroundGeolocation2.default.beginBackgroundTask is not a function. (In '_reactNativeBackgroundGeolocation2.default.beginBackgroundTask', '_reactNativeBackgroundGeolocation2.default.beginBackgroundTask' is undefined)`

possibly because although `beginBackgroundTask` is exported from RNBackgroundGeolocation.m, it doesn't seem to be exported from RNBackgroundGeolocation.ios.js

**Comment by christocracy** [comment]
Yes, this seems to be missing on the js api, thanks.

**Comment by reallistic** [comment]
Note that you can call it directly:

```
const { RNBackgroundGeolocation } = require('react-native').NativeModules;
RNBackgroundGeolocation.beginBackgroundTask(callback);
```

**Comment by christocracy** [comment]
Yea, for sure it's a public method on the native code.  It's simply missing in the js API.

**Comment by DVassilev** [comment]
@christocracy Are you going to add it to JS API?

**Comment by christocracy** [comment]
Yes, I will.  I look into it today.

**Comment by DVassilev** [comment]
Thank you, appreciate the great library.
