### ISSUE TITLE
[Android] Not working, no location update 

### ISSUE THREAD

**Issue by cnkyrpsgl** [transistorsoft/react-native-background-geolocation#1092]
## Your Environment
* Plugin version: 3.7.0
* Platform: Android
* OS version: 7 and 10 (two test devices)
* Device manufacturer / model: Samsung s6 edge, Samsung a30
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const locationUpdateInterval = 5000;
const maxRecordsToPersist = 500;
...
...
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      foregroundService: true,
      locationsOrderDirection: 'ASC',
      disableElasticity: true,
      distanceFilter: 0, // Must be 0 or locationUpdateInterval is ignored!
      allowIdenticalLocations: true,
      locationUpdateInterval,
      maxRecordsToPersist,
      disableLocationAuthorizationAlert: true,
      headers: {
        'X-Device-Type': 'NORMAL',
        'X-Device-Channel': 'APP',
        'X-Device-Version': getVersion(),
        'Content-Type': 'application/json'
      }
    })
```

## Expected Behavior

In every 5 seconds, onLocation is expected to send track location. 
## Actual Behavior

It just send 2-3 locations when app is opening and it is dead after that.
## Steps to Reproduce

1. npm run android
2. open the app
3. check react-native log-android, logcat or reactotron

## Context

Trying to send location
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Sample location event on app opening:
[16:24:56] D | ReactNativeJS ▶︎ '[DEBUG]', '[location] - ', { extras: {},
                             │ battery: { level: 1, is_charging: true },
                             │ activity: { confidence: 100, type: 'still' },
                             │ coords:
                             │ { altitude: 172.2,
                             │ heading: -1,
                             │ speed: -1,
                             │ accuracy: 19.6,
                             │ longitude: 29.1510523,
                             │ latitude: 40.9932279 },
                             │ odometer: 0,
                             │ timestamp: '2020-06-25T13:24:56.006Z',
                             │ uuid: 'xxxxxxxxxxxxxxxxxxxxx',
                             └ is_moving: false }
```

</details>

**Comment by christocracy** [comment]
Perhaps you're not aware of this plugin's [*Philosophy of Operation*](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)?

**Comment by sobanarshad85** [comment]
can you please guide what is the exact reason, i have read philosophy but couldnt get the point, like it was suppose to work exact for one year and then somehow it stopped it self.

**Comment by christocracy** [comment]
@sobanarshad85 are you associated with author of this post @cnkyrpsgl?

**Comment by sobanarshad85** [comment]
oops sorry, i was searching for solution and mistakenly i commented here, sorry i have my own issue, sowehow similer to this

**Comment by sobanarshad85** [comment]
@cnkyrpsgl is your issue resolved?

**Comment by cnkyrpsgl** [comment]
Philosophy of Operation states why back-geo is closed. My issue is resolved by manuelly toggling `bgGeo.changePace(true, function() {
  console.log('- plugin is now tracking');
});`

**Comment by sobanarshad85** [comment]
@cnkyrpsgl are you sure by doing this "manual true", it'll be able to go on and off, like only tracking when moving?

**Comment by christocracy** [comment]
You can simulate motion-triggering behaviour on a real device by shaking the device vigorously in the air for ~30s.

**Comment by sobanarshad85** [comment]
Thanks alot @christocracy
