### ISSUE TITLE
[Question] Store locations in SDK database only if condition is met

### ISSUE THREAD

**Issue by neXorianus** [transistorsoft/react-native-background-geolocation#1094]
Is it possible to only record locations to database if a certain condition is met?

The use case is, we want to send location data to our server, but only, if the user allows us to (toggle in app settings) and if the app currently has a "run" loaded.

I thought about setting the `maxRecordsToPersist` config to `0` and the `url` to `undefined` while the conditions are not met, but i fear that this would delete all stored records that have not been synced yet.

We need the User location in-app at all times, but are only interested on locations when the condition is met.

How do I only record to SDK-DB on *condition-met* so a batch-sync can handle data as soon as the app gets online, without polluting with *unimportant* location?

## Your Environment
* Plugin version: ~3.4.2
* Platform: iOS & Android 
* OS version: does not matter
* Device manufacturer / model: ---
* React Native version (`react-native -v`):react-native-cli: 2.0.1; react-native: 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      disableElasticity: true,
      locationUpdateInterval: 5000,
      fastestLocationUpdateInterval: 3000,
      activityRecognitionInterval: 5000,
      stopOnTerminate: true,
      startOnBoot: false,

      // debug options so tracking also works in (non moving) emulator: (TODO: increase / disable for prod)
      distanceFilter: 1,   // TODO: increase for prod
      stationaryRadius: 1, // TODO: increase for prod
      isMoving: true,
      stopOnStationary: false,
      preventSuspend: true,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,

      // dont persist any data on the Phone, if the user does not want to
      maxRecordsToPersist: 0,

      // TODO: only upload tracking data to backend if user agreed
      url: undefined,//API_URL + '/locations',
      autoSync: true,
      autoSyncThreshold: 10,
      batchSync: true,
      params: {
        "id": id,
      },
      headers: await this.apiService.getAuthHeader(),
      locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}'
}
```

**Comment by christocracy** [comment]
See API docs `Config.persistMode`

**Comment by neXorianus** [comment]
Thank you @christocracy 
This is exactly what i was searching for!
