### ISSUE TITLE
"Waiting for previous start action to complete" is logged many times

### ISSUE THREAD

**Issue by AnurajDev** [transistorsoft/react-native-background-geolocation#1097]
## Your Environment
* Plugin version: 3.4.2 
* Platform: Android
* OS version: Android 10 (various)
* Device manufacturer / model: Pixel 3a (various devices)
* React Native version (`react-native -v`): 0.60.3
* Plugin config : 
```javascript <!-- Syntax-highlighting:  paste your code below -->
 {
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopTimeout: 10,
      enableHeadless: false,
      stopOnTerminate: true, 
      heartbeatInterval: 60,
      preventSuspend: true,
      autoSync: true, 
      url: `<URL>`,
      headers: {<key>: <value>},
      httpRootProperty: ".",
      locationTemplate:
        '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, "batteryLevel":<%= battery.level %> , "speed":<%= speed %> , "ts": "<%= timestamp %>"  }'
    }
```

Additionally, start() is called after state.enabled is checked.

```
 (state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start();
      }
 }

```

The Sentry logs "Waiting for previous start action to complete" from various devices.

**Comment by christocracy** [comment]
Where are these logs?  How do I reproduce this?

**Comment by AnurajDev** [comment]
@christocracy  The logs are from sentry.io which is configured in my app. I am sorry, even I don't know how to reproduce this issue. Every day sentry is showing this message (more than 1000 occurrences over a period of 6 months as of now) which is really annoying. I want to ensure that this does not affect the performance of the app.

![backgroundgeolocation](https://user-images.githubusercontent.com/47019442/86806710-befb7780-c096-11ea-84d1-ce8b544463e6.PNG)
