### ISSUE TITLE
exiting a geofence triggers onLocation event 

### ISSUE THREAD

**Issue by ReneMarquez** [transistorsoft/react-native-background-geolocation#1098]
## Your Environment
* Plugin version: 3.7.0
* Platform: iOS
* OS version: 13.5
* Device manufacturer / model: iPhone (simulator)
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 200,
      stopTimeout: 5,
      debug: false,              // <-- enable this hear debug sounds.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      url:null,
      batchSync: false,
      autoSync: false,
      autoSyncThreshold: 1,
      disableElasticity: true,
      geofenceModeHighAccuracy: true
    }, (state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          this.getStartPosition();
          startUpLocation = false;
        }.bind(this));
      }
      else{
        this.getStartPosition();
        startUpLocation = false;
      }
    });
  }
```

## Expected Behavior

geofence events should be handled by onGeofence
## Actual Behavior

exiting a geofence triggers a onLocation event
## Steps to Reproduce

1. Create geofence
2. Enter geofence
3. When exiting geofence, onLocation event triggers
4.

## Context

Is there any way (config) to stop this behaviour? it is weird that it only happens when I exit a geofence, but not when entering one? I need to prevent this, because on the onLocation handler, if some conditions are met, I redraw some elements in a map, but this event triggering via geofence its triggering it prematurely, I tried adding extra properties to geofence, so I could diferentiate the events, but extras property is empty for geofence events on onLocation
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Every recorded location is sent to the onLocation event, including those resulting from a geofence event,  this is expected.

If you don’t want to deal with these in onLocation, check for the presence of `location.geofence` property.  When it exists, ignore it.

**Comment by ReneMarquez** [comment]
> Every recorded location is sent to the onLocation event, including those resulting from a geofence event. this is expected.
> 
> If you don’t want to deal with these in onLocation, check for the presence of `location.geofence` property. When it exists, ignore it.

thats the thing, theres never a `location.geofence` property, even if its triggered by a geofence (that property is available on `onGeofence`) or the event property, the event property is available when a `onMotionChange` happens tho

**Comment by christocracy** [comment]
Then is must be a regular tracking-location.

**Comment by ReneMarquez** [comment]
> Then is must be a regular tracking-location.

so then my issue is with distanceFilter? because I'm updating it dynamically with `BackgroundGeolocation.setConfig({})` depending on the speed; updating distanceFilter this way should use the new distance instantly right? or am I missing a step.
Thanks

**Comment by christocracy** [comment]
When you change distanceFilter on iOS, a location is emitted immediately by the native API.

Why are you *manually* changing distanceFilter with speed?  The SDK already has this “elasticity” functionality built-in.
