### ISSUE TITLE
Can I get the bearing in degrees?

### ISSUE THREAD

**Issue by vuhoangha** [transistorsoft/react-native-background-geolocation#1100]
## Your Environment
* Platform: iOS/Android
* React Native version (`react-native -v`): 0.59.9

## Expected Behavior
Hi team,
I want to get the bearing in degrees but I can't find any documents for this.
Thank you!

**Comment by christocracy** [comment]
`location.coords.heading`

**Comment by vuhoangha** [comment]
I used function "getCurrentPosition" but it returned heading = -1

```
{
  "coords": {
    "floor": null,
    "longitude": 105.78607093841107,
    "speed": -1,
    "latitude": 20.99351572100308,
    "accuracy": 65,
    "heading": -1,
    "altitude": 1.9,
    "altitude_accuracy": 10
  },
  "extras": {
    
  },
  "is_moving": false,
  "odometer": 0,
  "uuid": "6C11271F-4366-48A4-BB5A-95600E4B502A",
  "activity": {
    "type": "still",
    "confidence": 100
  },
  "battery": {
    "level": 0.8399999737739563,
    "is_charging": true
  },
  "timestamp": "2020-07-20T02:49:26.046Z"
}
```

**Comment by christocracy** [comment]
Yes, and `accuracy: 65` showing this location came from WiFi, not gps.  You are probably indoors.  Gps doesn’t work indoors.

Go test outside.
