### ISSUE TITLE
[Android] Background service not working after change power saving mode and sleep my phone

### ISSUE THREAD

**Issue by bapdola304** [transistorsoft/react-native-background-geolocation#1101]
## Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 10
* Device manufacturer / model: V-smart Joy 2+, Oppo Reno3
* React Native version (`react-native -v`): 0.61.5

## Expected Behavior

 I expected **background service** always running even though I turn on **power saving mode** of my device
## Actual Behavior

When I turn on **power saving mode** and turn off screen(sleep status) my device, so **background service** not running any more

**Comment by christocracy** [comment]
Why do you expect there to be no consequences to turning on power-saving mode?

**Comment by nnvanhao** [comment]
> Why do you expect there to be no consequences to turning on power-saving mode?

Hi christocracy, I think to have the same problem. When I turn on power save mode and turn off the screen (sleep mode of the phone), Background Service does not work. Is there any way for it to work normally while power save mode is on? Thanks.

**Comment by christocracy** [comment]
It’s named “power save mode” for a reason, no?

GPS and http requests running in foreground-services consume a lot of power.

You can listen to onPowerSaveChange to learn when the device enters this state.

**Comment by nnvanhao** [comment]
> It’s named “power save mode” for a reason, no?
> 
> GPS and http requests running in foreground-services consume a lot of power.
> 
> You can listen to onPowerSaveChange to learn when the device enters this state.

Thanks christocracy.
