### ISSUE TITLE
[iOS] App is not receiving location updates after its killed 

### ISSUE THREAD

**Issue by rajkumarwaghmare** [transistorsoft/react-native-background-geolocation#1103]
## Your Environment
* Plugin version:3.6.2
* Platform: iOS 
* OS version: 13.5.1
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`):3.2.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
      distanceFilter: 50,
      stationaryRadius: 100,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: false, // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'some url',
      locationTemplate: `some location template`
      extras: {
        uid: uid,
      },
      headers: {
        //Some header
      },
      batchSync: true, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
      autoSyncThreshold: 5, // Tied with autoSync
      persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
      //AuthorizationAlert is displayed even if location is ON but not set to "Always"
      disableLocationAuthorizationAlert: true,
```

## Expected Behavior
When app is killed by user (app not running in the background), location is tracked (sent to server)

## Actual Behavior
When app is on foreground or running in background, location is tracked as expected.
When app is killed by user app(not running in the background), location is not tracked (not sent to server)

## Steps to Reproduce

1. Kill the app (released to users on TestFlight)
2.Start moving (or simulate location by Xcode debugger) more than 1km
3.Notice that location is not tracked and sent to server

**Comment by mikehardy** [comment]
This has been asked and answered in the issues a lot if you search, but the thing is on iOS if you force-close an app (kill it, swipe it away, however you want to describe that), your app is now dead dead. It's not coming back till the user opens it. It's a platform limitation.

**Comment by christocracy** [comment]
@mikehardy not true,  I think you’re talking about background-fetch, this is background-geolocation.

@rajkumarwaghmare see wiki “Debugging”, set debug: true and test this in the simulator with *Freeway Drive*.

I’ve testing this nearly every day on my devices for ~6 years.  It rarely fails and if it does, it’s due to device settings (eg WiFi disabled, location-services Config) or the environment (rural vs urban environment).

**Comment by christocracy** [comment]
Also, your app **must** call `#ready` *no matter what*, **each time your app launches**.

**Comment by rajkumarwaghmare** [comment]
@christocracy 
When i debug on simulator with Freeway Driver, i can see that app is receiving the location updates in background.

But when i test it with device, i never receive location updates in background after app is killed

**Comment by christocracy** [comment]
Then your issue is device-related (ie: Settings as mentioned above) or environmental (presence of Wifi signals, spacing of cell towers), physical obstacles (mountains, tall buildings, etc).

**Comment by rajkumarwaghmare** [comment]
>eg WiFi disabled
When WiFi is disabled, then location wont be tracked? or is it otherwise?

**Comment by christocracy** [comment]
In order for the plugin to detect the device is moving, the device must exit a geofence being monitored around the last known position.  In order for a geofence to fire, WiFi **must** be enabled.

iOS automatically persists monitored geofences, in spite of app terminate / device reboot.

**Comment by rajkumarwaghmare** [comment]
>In order for a geofence to fire, WiFi must be enabled.

So if i kill the app in night before going to sleep (WiFi is available n enabled as im in home)
If in this state, i move out of my house tomorrow morning (WiFi becomes unavailable when i go away from house)
So in that case geofence wont fire?

**Comment by christocracy** [comment]
“WiFi enabled” does not mean the device must be connected to your home WiFi router.

Apple/google maintain a giant database of WiFi routers and their associated location.

The device merely needs WiFi enabled so it can sense all those available WiFi signals as you travel throughout the world.

**Comment by mikehardy** [comment]
oh my goodness! You are right, sorry about the misinformation @rajkumarwaghmare  - the motion activity API will bring the app back to life on iOS. It was fetch I was thinking about - background fetch stops completely when you force close.

**Comment by christocracy** [comment]
> the motion activity API will bring the app back to life on iOS.

Sorry, @mikehardy — that’s incorrect too :)  iOS doesn’t allow`CMMotionActivityManager` to operate independently in the background.  It’s incapable of relaunching a terminated app.

Only the Geofencing API and Significant Location Changes (SLC) apis are capable of relaunching a terminated iOS app.

**Comment by mikehardy** [comment]
Still on the first cup of coffee and already learning stuff 🤣  - thanks 😄

**Comment by christocracy** [comment]
If a background-fetch event causes and app that was terminated by the *OS* (ie not *user-terminated*) to relaunch, the SDK *does* sample the `CMotionActivityManager` api for the 30s it has — if the motion-activity reports *moving*, the SDK *will* trigger a state-change and initiate tracking.  hitting that 30s window would require some luck, but it’s there.

**Comment by mikehardy** [comment]
...and I do see that fetch (which is rare itself on iOS) occasionally come right before a location event, so that explains the coupling there as well. Rare as you say but does happen. All very interesting, iOS is a tough beast to make a mental model for

**Comment by pkt-dev** [comment]
#

> > the motion activity API will bring the app back to life on iOS.
> 
> Sorry, @mikehardy — that’s incorrect too :) iOS doesn’t allow`CMMotionActivityManager` to operate independently in the background. It’s incapable of relaunching a terminated app.
> 
> Only the Geofencing and Significant Location Changes (SLC) apis are capable of relaunching a terminated iOS app, both of which the SDK is monitoring.

I read on iOS documentation and part of your documentation that for the SLC to fire, the "distance" (geofence) must be ~200 meters. So I'm wondering if that is accurate and if so, any sort of workaround for doing some like say 5 meters? It appears that the app Life 360 is somehow accomplishing this and we are kinda dumbfounded as to how.

**Comment by christocracy** [comment]
> any sort of workaround for doing some like say 5 meters?

If there were, it would have been done some time over the last 6 years I've been working on this.

>It appears that the app Life 360 is somehow accomplishing this

No they're not.  They're using the same [`CLLocationManager`](https://developer.apple.com/documentation/corelocation/cllocationmanager) API from iOS `CoreLocation`.

**Comment by christocracy** [comment]
Over a larger scale where a typical mobile app will track a user, the 200 meter initial distance is negligible.

![](https://dl.dropbox.com/s/lkpalexbo5maby6/Screenshot%202020-07-16%2019.45.45.png?dl=1)

**Comment by pkt-dev** [comment]
Thank you for your timely response.

Hmm perhaps we are missing something then with our implementation of BackgroundGeolocation. All I can tell is that on Life 360 on an iOS device, I can terminate the app (not just background), and move about 5 meters or so and on a separate device see that update within a couple seconds. In which we want to achieve similar results. Maybe you have advice on how we could achieve this using `CoreLocation`?

And yes, over that large of scale its not as important.

**Comment by christocracy** [comment]
> I can terminate the app (not just background), and move about 5 meters 

It’s Impossible for a terminated iOS app to re-engage location tracking by moving a mere 5 meters.

> Maybe you have advice on how we could achieve this using CoreLocation?

This plugin *is* an interface to CoreLocation.

Perhaps you didn’t read what I wrote above:

“* If there were, it would have been done some time over the last 6 years I've been working on this.*”.

No matter how many ways you ask the same question, you’re going to get the same answer from me.

**Comment by pkt-dev** [comment]
Well, apologies for being redundant then...I don't mean to waste your time repeating yourself. I'm just trying to understand the tools I have to work with. And I can see that other applications have accomplished what I'm desiring with "apparently" the same tools, but everything I'm reading/hearing (you, iOS docs, stackoverflow, etc.) is saying its impossible. So obviously either what I'm seeing is not "real" or everything I'm reading/hearing is wrong.

I understand you've been working with this stuff for the past 6 years and have much more insight...so thank you for your assistance.

**Comment by christocracy** [comment]
I suggest you re-perform your Life360 test, terminate the app then let the device sit stationary and untouched for 3 min before moving.

**Comment by christocracy** [comment]
And unplugged from power.

**Comment by pkt-dev** [comment]
Okay. I'll do some more testing on it. Is there a reason I'd need to let the device sit stationary after terminating? From your comments above I thought the movement of the device would not matter if the app is terminated. I'd just have to make sure I don't move it more than ~200 meters (thus avoiding the SLC).

> > Sorry, @mikehardy — that’s incorrect too :) iOS doesn’t allow`CMMotionActivityManager` to operate independently in the background. It’s incapable of relaunching a terminated app.
> > Only the Geofencing and Significant Location Changes (SLC) apis are capable of relaunching a terminated iOS app, both of which the SDK is monitoring.
>

**Comment by lyseiha** [comment]
If i use this plugin and make ios app still tracking when app killed/terminated, is Appstore approve to the store?

**Comment by christocracy** [comment]
Have a read of the api docs Config.stopOnTerminate.

The sdk is using published, public iOS `CoreLocation` apis that are purposely designed by Apple engineers to do exactly what they’re designed to do.

This sdk is not a hack of iOS apis.  It does the same things that any native app is capable of.

Of course, your app is still subject to Apple’s review process — if Apple feels your app doesn’t *deserve* to use the *Background Location* capability checkbox in XCode, they could tell you that and reject your app.  That would have nothing specifically to do with this sdk,

Some people try to use this sdk to make an *Alarm Clock* app, using background location capability to keep an app running in the background to run a timer:  of course Apple would reject that app.

**Comment by lyseiha** [comment]
Thank @christocracy

**Comment by kirit75623** [comment]
is anyone know how to do this ??

**Comment by ganeshmohane** [comment]
> is anyone know how to do this ??

what?
