### ISSUE TITLE
Tiny issue in documentation comments, locationTimeout and disableElasticity are not boolean

### ISSUE THREAD

**Issue by krachtstefan** [transistorsoft/react-native-background-geolocation#1106]
I just found a small documentation issue in the `Config.d.ts`. `locationTimeout` is documented as `boolean` but defined as `number`. Probably happend during a refactoring. I thought you should know.

```javascript
/**
* Disable automatic, speed-based [[distanceFilter]] scaling.
*
* Defaults to **`false`**.  Set **`true`** to disable automatic, speed-based [[distanceFilter]] elasticity.
*/
locationTimeout?: number;
```

Great job with this library by the way. I'm currently testing it and it looks like I will purchase a license very soon. 

EDIT: `disableElasticity` is not affected.

**Comment by dorthwein** [comment]
Ran into this as well - documentation needs to be updated and clarified.  I'm getting locationTimeout errors spamming and trying to figure out why.
