### ISSUE TITLE
No header available in onHttp callback response

### ISSUE THREAD

**Issue by ugurakkurt** [transistorsoft/react-native-background-geolocation#1107]
I am trying to gather header data that is sent in the response of location data. However there is no way of parsing headers in BackgroundGeolocation.onHttp callback method.

## Your Environment
* Plugin version: 3.7.0
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung S6
* React Native version: 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.setConfig({
          url: `${REST_URL}/api/location/track`,
          headers: {
            'X-Device-Type': 'NORMAL',
            'X-Device-Channel': 'APP',
            'X-Device-Version': getVersion(),
            'Content-Type': 'application/json',
            Cookie: cookie
          },
          httpRootProperty: '.',
          httpTimeout: 3000,
          locationTemplate: `{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"createdAt": "<%= timestamp %>"}`
        });
```

## Expected Behavior
I expect to find response headers within onHttp callback.

## Actual Behavior
No headers exist to parse in response.

## Steps to Reproduce
1. Just send some location after configuring background geolocation library.
2. Parse http-posted location response in onHttp callback.
  BackgroundGeolocation.onHttp(response => {
            const { success } = response;
            if (!success) {
              logger.info('[location http] FAILURE: ', response);
            } 
          //  No header data is available in response to parse here
          });

## Context
I am trying to gather header data sent within location response.

**Comment by christocracy** [comment]
The plugin doesn’t provide headers.  It provides the http response-text only.

**Comment by ugurakkurt** [comment]
Can it be possible to provider the headers?

**Comment by christocracy** [comment]
I’d rather not, as it would break the api for others.

Nobody has requested this in 5 years.

Rather than sending data In headers, return a json response containing the desired data you’re currently placing in response headers.

**Comment by ugurakkurt** [comment]
It was about session management. So I can say it is not possible to send session headers in body. However, I can disable session for it in backend as a workaround. So no worries. Will close the issue.

**Comment by nyilmaz** [comment]
Hi @christocracy , we are using licensed version of rnbl project for android. Session resolving strategy by cookie header is commonly used by many web applications. spring framework also uses cookie storage for session management by default. Please consider adding support for cookie authentication.
