### ISSUE TITLE
geofence not working when the app is killed state

### ISSUE THREAD

**Issue by akshay2801-rgb** [transistorsoft/react-native-background-geolocation#1109]
I am testing with ios and android debug build. I have call the api in geofence events. the api triggers when the app is active or background state but when the app is killed by user the api + event doesn't called .

**Your Environment**

- plugin version:  3.7.0
- platform : Android/ iOS
- react native version: 0.61.5

**My Code**
   
      componentDidMount() {
            // call geofence method
           BackgroundGeolocation.ready({
                    // Geolocation Config
                    geofenceModeHighAccuracy: true,
                    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                    distanceFilter: 10,
                    // Activity Recognition
                    stopTimeout: 999999999,
                    showsBackgroundLocationIndicator: true,
                    // Application config
                    debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
                    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                    stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
                    startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
                    // HTTP / SQLite config
                    url: 'http://yourserver.com/locations',
                    preventSuspend: true,
                    pausesLocationUpdatesAutomatically: false,
                    geofenceInitialTriggerEntry:true,
                    disableStopDetection: true,
                    heartbeatInterval: 30,
                    batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                    autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
                    headers: {              // <-- Optional HTTP headers
                        "X-FOO": "bar"
                    },
                    params: {               // <-- Optional HTTP params
                        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
                    },
                    reset: false
                }, (state) => {

                    BackgroundGeolocation.startGeofences();
                    console.log("- BackgroundGeolocation is configured and ready: ", state.enabled)
                    
                        
                    // BackgroundGeolocation.start(() => {
                    //     console.log("------------------------------- Start success")
                    // })
                    
                })

                 BackgroundGeolocation.addGeofence({
                            identifier: "Home",
                            radius: 150,
                            latitude: CARELAT,
                            longitude: CARELONG,
                            notifyOnEntry: true,
                            notifyOnExit: true,
                            extras: {
                                route_id: 123
                            }
                        }).then((success) => {
                            console.log("[addGeofence] success", success);
                        }).catch((error) => {
                            console.log("[addGeofence] FAILURE: ", error);
                        });

            BackgroundGeolocation.onGeofence(geofence => {
                console.log("[geofence] ")
                this.onFileSystem(JSON.stringify(geofence))
          
                        fetch(`https://xyz`)
                        .then(res => res.json())
                        .then((myJson) => {
                            console.log( myJson)
                            
                        })
                        .catch(err => console.log(err);
            })

      }

**Expected Behavior**
the api should call up when the user enters/exits a geofence even if the app is in  killed state.

**Actual Behavior**
the api called up when the app is active or background state

please suggest some solution.

**Comment by christocracy** [comment]
The plugin has a built-in http service

> url: 'http://yourserver.com/locations'

If you’re not using the Config.url, you should leave that url **blank**.  The plugin **IS** executing http requests to that url, **and failing**.

**Comment by akshay2801-rgb** [comment]
@christocracy  same code not working on android if the app is in killed state

**Comment by christocracy** [comment]
For *Android*, see Wiki [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode).

`BackgroundGeolocation.onGeofence` does not fire when *Android* app is terminated.

**Comment by akshay2801-rgb** [comment]
@christocracy  thanks for help

**Comment by akshay2801-rgb** [comment]
@christocracy  In iphone geolocation not working properly in background. In the background, they do not send the location continuously after sending the location for 1 hour and half hour. and also geofence call some time nd some time not


my code

componentDidMount() {
       
                BackgroundGeolocation.on('location', this.onLocation.bind(this), this.onError)
                BackgroundGeolocation.on('motionchange', this.onMotionChange.bind(this)) 
                BackgroundGeolocation.on('activitychange', this.onActivityChange.bind(this)) 
                BackgroundGeolocation.on('providerchange', this.onProviderChange.bind(this)) 
                BackgroundGeolocation.on('heartbeat', this.getGPS.bind(this))

       BackgroundGeolocation.ready({
                // Geolocation Config
                geofenceModeHighAccuracy: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 10,
                // Activity Recognition
                stopTimeout: 999999999,
                showsBackgroundLocationIndicator: true,
                // Application config
                debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
                startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
                // HTTP / SQLite config
                url: 'http://yourserver.com/locations',
                preventSuspend: true,
                pausesLocationUpdatesAutomatically: false,
                geofenceInitialTriggerEntry:true,
                disableStopDetection: true,
                heartbeatInterval: 30,
                batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
                headers: {              // <-- Optional HTTP headers
                    "X-FOO": "bar"
                },
                params: {               // <-- Optional HTTP params
                    "auth_token": "maybe_your_server_authenticates_via_token_YES?"
                },
                reset: false
            }, (state) => {

                BackgroundGeolocation.startGeofences();
                console.log("- BackgroundGeolocation is configured and ready: ", state.enabled)
                
                    
                // BackgroundGeolocation.start(() => {
                //     console.log("------------------------------- Start success")
                // })
                
            })


             BackgroundGeolocation.addGeofence({
                        identifier: "Home",
                        radius: 150,
                        latitude: CARELAT,
                        longitude: CARELONG,
                        notifyOnEntry: true,
                        notifyOnExit: true,
                        extras: {
                            route_id: 123
                        }
                    }).then((success) => {
                        console.log("[addGeofence] success", success);
                    }).catch((error) => {
                        console.log("[addGeofence] FAILURE: ", error);
                    });


        BackgroundGeolocation.onGeofence(geofence => {
            console.log("[geofence] ")
            this.onFileSystem(JSON.stringify(geofence))
      
                    fetch(`https://xyz`)
                    .then(res => res.json())
                    .then((myJson) => {
                        console.log( myJson)
                        
                    })
                    .catch(err => console.log(err);
        })
        
        BackgroundGeolocation.start((state) => {
                    console.log('- BackgroundGeolocation started, state: ', state)
                   
                    BackgroundTimer.start();
                    this.iosTimer = setInterval(this.getGPS, 30000)
                    BackgroundTimer.stop();
                })


    }


         getGPS = (params = {}) => {
          
               BackgroundGeolocation.getCurrentPosition({
                        timeout: 30,          // 30 second timeout to fetch location
                        persist: true,        // Defaults to state.enabled
                        maximumAge: 60000,
                        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH
                    },location=> this.onLocation(location),
                      err => console.log('is this undefined?', err),
                    );
           }



         onLocation(location) {

            // this.onFileSystem(JSON.stringify(location))
            console.log('- [event] location: ', location)
          }

         onError(error) {
            console.warn('- [event] location error ', error)
         }

         onActivityChange(activity) {
            console.log('- [event] activitychange: ', activity)  // eg: 'on_foot', 'still', 'in_vehicle'     
            this.getGPS()
            this.setState({ lastActivity: activity.activity })
         }

         onProviderChange(provider) {
            console.log('- [event] providerchange: ', provider)
            this.getGPS()
         }

         onMotionChange(location) {
             console.log('- [event] motionchange: ', location.isMoving, location)
            this.getGPS()
         }


Expected Behavior
location working continuously in every state (background/foreground) and geofence call every time 

Actual Behavior
location working proper in foreground but in background not working continuously and geofence not call every time

**Comment by christocracy** [comment]
See Wiki *Debugging*.

**Comment by ResQRestoration** [comment]
Still facing this issue
Not able to get geo fence data when app is killed
