### ISSUE TITLE
ld: framework not found TSBackgroundFetch for architecture x86_64

### ISSUE THREAD

**Issue by romanchukenator** [transistorsoft/react-native-background-geolocation#111]
I'm getting a linker command error when I try to build and run either through command line or in xcode. 

My deployment target is 8.0 after I had some warnings telling me that:

```ld: warning: object file (../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager_vers.o)) was built for newer iOS version (8.0) than being linked (7.0)```

Upping my target version didn't help and I'm still left with the original error. Any ideas?

**Comment by christocracy** [comment]
See Announcement [here](https://github.com/transistorsoft/react-native-background-geolocation/issues/107).  New dependency added.

**Comment by christocracy** [comment]
I assume you fixed your issue?  Can I close this?

**Comment by romanchukenator** [comment]
Sorry! Yes! Absolutely!
