### ISSUE TITLE
desiredAccuracy

### ISSUE THREAD

**Issue by FrancoFasano** [transistorsoft/react-native-background-geolocation#1110]
desiredAccuracy setted to high provide GPS+WIFI+Cellular markers.
I need to test with only GPS markers without WIFI and Cellular markers.
Is a way to do this ? or a method to identify markers types from sended data ?

## Your Environment
* Plugin version: 3.8.1
* Platform: Android
* OS version: android 7, 8 & 9
* Device manufacturer / model: Blackview BV8000Pro, BV9600Pro
* React Native version (`react-native -v`): 0.59
* Plugin config
```
javascript <!-- Syntax-highlighting:  paste your code below -->
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,    // GPS + Wifi + Cellular,
```

## Expected Behavior
GPS markers only

## Actual Behavior
GPS + Wifi + Cellular markers

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- When GPS is available, GPS will be used.  GPS is only available when the device is outdoors.
- When device is indoors, location will come from Wifi.
- When all else fails, location will come from Cellular.

There is no possible way to choose that location only come from GPS.
