### ISSUE TITLE
libpbkdf2 source files

### ISSUE THREAD

**Issue by kaplanlior** [transistorsoft/react-native-background-geolocation#1112]
Follow up for #1074

## Your Environment
* Plugin version: 3.4.2-3.8.1
* Platform: Android
* OS version: n/a
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.60
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
Know which source code was compiled for the libpbkdf2 binaries.

## Actual Behavior
Binary only distribution:
https://github.com/transistorsoft/react-native-background-geolocation/issues/1074#issuecomment-666313226
https://github.com/byteamaze/rncryptor-android/issues/1

## Steps to Reproduce
Any use of this package, files are part of the arr archive.

## Context

Verify sources of all code (manifest) / code review

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Purpose?

**Comment by kaplanlior** [comment]
Verify the code, identifying problem and fixing them (if any), being able to rebuild (reproducible builds CI) and such.
The regular things you do when you have the full source code instead of binaries built a few years ago.

Also, you might want to enjoy updates done by the upstream (although I can't verify it's actually upstream): https://github.com/RNCryptor/RNCryptor/blob/master/CHANGELOG.md
