### ISSUE TITLE
Abilities of Android Headless Mode

### ISSUE THREAD

**Issue by juraam** [transistorsoft/react-native-background-geolocation#1114]
## Your Environment
* Plugin version: 3.8.1
* Platform: Android
* OS version: NA
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.61.8
* Plugin config

## Expected Behavior
If I register headless task with Your Lib, can I send any api requests inside handler of headless task? Can I access to react native such as Async Storage inside this task?
I'm iOS developer and I understand when CLLocationManager works iOS app is active, so it is in background or foreground, so my first question: Do callbacks of event listeners in react native call in bg mode in iOS ?
But in Android in foreground event listeners will be call but in background only headless task listener will work, is it right ?

## Debug logs

</details>

**Comment by christocracy** [comment]
>can I send any api requests inside handler of headless task? 

You can do whatever you wish.  It's your callback function.

>Can I access to react native such as Async Storage inside this task?

Yes, of course.

>Do callbacks of event listeners in react native call in bg mode in iOS ?

Yes.

>But in Android in foreground event listeners will be call but in background only headless task listener will work, is it right ?

No.  There are *three* states:  *foreground*, *background* and *terminated* (headless).

The Android headless-task operates only in the *terminated* state, where your app's UI no longer exists.
