### ISSUE TITLE
[Android] Background-geolocation service don't running after i sleep device a long time ( about over 1 hours or 2 hours )

### ISSUE THREAD

**Issue by bapdola304** [transistorsoft/react-native-background-geolocation#1117]
## Production
* Plugin version:
* Platform:  Android
* OS version: 10
* Device manufacturer / model: Samsung M20
* React Native version (`react-native -v`): 0.61.5

## Expected Behavior
 - I Expected **Background-geolocation** service can running after my phone sleep a long time ( about over 1 hours or 2 hours )

## Actual Behavior
 - When I minimize app, sleep app and I don't touch my phone anymore,  **Background-geolocation** service is running util about  over 1 hours or 2 hours later it stops

**Comment by christocracy** [comment]
How do you know the “service stops”?

Have you tried going outside for a trip (walk, car ride, etc)?

**Comment by bapdola304** [comment]
> How do you know the “service stops”?
> 
> Have you tried going outside for a trip (walk, car ride, etc)?

**Comment by bapdola304** [comment]
> How do you know the “service stops”?
> 
> Have you tried going outside for a trip (walk, car ride, etc)?

Service still works. I use **BackgroundGeolocation.watchPosition** set interval 10 second, but after about over 1 hours or 2 hours **BackgroundGeolocation.watchPosition** not working

**Comment by christocracy** [comment]
You’re not supposed to use watchPosition for long periods of time.  It’s designed for use only while your app is in the foreground.

The only thing you need to do to track a device is `start()`.  That’s it.

**Comment by bapdola304** [comment]
> You’re not supposed to use watchPosition for long periods of time. It’s designed for use only while your app is in the foreground.
> 
> The only thing you need to do to track a device is `start()`. That’s it.

I want to tracking the device continuously, I will try BackgroundGeolocation.start() and BackgroundGeolocation.on('location', onLocation, onLocationError) and set distanceFilter = 0. thanks @christocracy

**Comment by christocracy** [comment]
I suggest you read the Wiki *Philosophy of Operation*.

**Comment by christocracy** [comment]
Btw, the method `on` was deprecated ~2 years ago in favor of `onXXX` (eg `onLocation`.

**Comment by bapdola304** [comment]
thanks @christocracy , I have issue, when i use **BackgroundGeolocation.on('location', this.onLocation**) in ComponentDidMount function. How do I detect that this **BackgroundGeolocation.on('location', this.onLocation**) function is registered and when I run the application again without registration. Because every time I run the application again, it will re-run many of the same functions

**Comment by christocracy** [comment]
In `componentDidUnmount`, call `.removeListeners()`

**Comment by nnvanhao** [comment]
Hi **christocracy**, I try using BackgroundGeolocation.on('location', onLocation, onLocationError) and set distanceFilter = 0, but about 1 hour and device sleep so **on('location')** not running anymore. So I try to add **heartbeat** function but after on('location') not running then heartbeat not start. What should I do, my wish is that heartbeat **always** **running** regardless of **sleep in long mode**. Thanks so much

**Comment by christocracy** [comment]
Why are you *still* using the *deprecated* method `#on`?  I already warned you about that.

**Comment by christocracy** [comment]
See wiki *Debugging* and observe the logs.

**Comment by nnvanhao** [comment]
> See wiki _Debugging_ and observe the logs.

Sr **christocracy**, I had changed #on to BackgroundGeolocation.onLocation & BackgroundGeolocation.onHeartbeat, onLocation run 1 hour and it's stop, and then onHeartbeat not start. I tried many ways but onHeartbeat doesn't work. I use 2 devices, the first device is Samsung that onLocation for 1 hour, and the second device is Vsmart onLocation runs for 2.5 hours and both devices are not running after that time. I don't know why there is a difference.

**Comment by victor9645** [comment]
I have a problem with something similar, I need to use the distance filter at 50, and now I read that just doing .start () is enough, what I wanted to know is how can I get that latitude and longitude, how do I get that back doing just start, or if I can test in production environment with the transistor console.

**Comment by christocracy** [comment]
>what I wanted to know is how can I get that latitude and longitude

By listening to the `onLocation` event.

**Comment by victor9645** [comment]
Great, that worked for me, my problem is background work now, I use this way:
BackgroundGeolocation.onLocation((location)=>{
                console.log("Location",location);
                 Alert.alert("Ubication",JSON.stringify(location.coords.latitude));

                 BackgroundGeolocation.startBackgroundTask().then((taskId) => {
                  console.log("Location back",location);
                  BackgroundGeolocation.stopBackgroundTask(taskId);
                });
   })

And I get this error when changing position having closed the app: 
 **No task registered for key BackgroundGeolocation**
I do not know where it would be failing, the only thing I need to do is control the position every 50 meters with the filter already applied, which works for me both in the foreground and in the background with the app closed, but it only works when minimizing and when closing the error occurs shown when trying to use backgroundTask, thanks in advance.

**Comment by victor9645** [comment]
Great, that is already fixed.
I now have a problem, I want to run my task in the background and I have the code as follows:

let HeadlessTask = async (event) => {
                let params = event.params;
                console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);
                
                switch (event.name) {
                  case 'heartbeat':
                    // Use await for async tasks
                    let location = await getLocation();
                    console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
                    break;
                }
              }


              let getLocation = () => {
                return new Promise((resolve) => {
                  BackgroundGeolocation.onLocation((location)=>{
                    console.log("Location",location);
                     Alert.alert("Ubication",JSON.stringify(location.coords.latitude));
    
                     BackgroundGeolocation.startBackgroundTask().then((taskId) => {
                      console.log("Location back",location);
                      BackgroundGeolocation.stopBackgroundTask(taskId);
                    });
    
    
                  })
                });
              };



             let HeadlessTask = async (event) => {
                let params = event.params;
                console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);
                
                switch (event.name) {
                  case 'heartbeat':
                    // Use await for async tasks
                    let location = await getLocation();
                    console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
                    break;
                }
              }

              let getLocation = () => {
                return new Promise((resolve) => {
                  BackgroundGeolocation.onLocation((location)=>{
                    console.log("Location",location);
                     Alert.alert("Ubication",JSON.stringify(location.coords.latitude));
    
                     BackgroundGeolocation.startBackgroundTask().then((taskId) => {
                      console.log("Location back",location);
                      BackgroundGeolocation.stopBackgroundTask(taskId);
                    });
    
    
                  })
                });
              };
              BackgroundGeolocation.registerHeadlessTask(HeadlessTask);


What I do is put this code inside a switch, that if this is true, the BackgroundLocation.start () is executed and others, it works, I can close the app and it continues registering the location, but my problem is when entering the app again , I get the following error:
registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'BackgroundGeolocation'

As I understand it, I am calling the headlessTask twice with the same key, but I need that every time the switch is set to true, it is executed.

**Comment by christocracy** [comment]
@victor9645 The title of this issue is *Background-geolocation service don't running after i sleep device a long time ( about over 1 hours or 2 hours )*.  I think your latest post is *off-topic*.

**Comment by victor9645** [comment]
Sorry, I already separated it to a different one.

**Comment by JimmyKho** [comment]
> Btw, the method `on` was deprecated ~2 years ago in favor of `onXXX` (eg `onLocation`}.

Hi @christocracy, may I know in which version the onLocation implemented?

**Comment by christocracy** [comment]
>may I know in which version the onLocation implemented?

Why?

**Comment by JimmyKho** [comment]
> > may I know in which version the onLocation implemented?
> 
> Why?

@christocracy , because we usually only distribute updates through react-native-code-push, we only update the packages whenever necessary. Currently my app is using version react-native-background-geolocation@2.14.2, and still using method #on. So wondering if version 2.14.2 already has the method #onLocation.

And we are also going to try the method #changePace as well.

Thank you.

**Comment by christocracy** [comment]
>react-native-background-geolocation@2.14.2,

[2.14.2](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#2142-2018-11-20) is nearly **two years old**.  You're not interested in supporting iOS 13/14 and Android 10/11?  Your app is not likely working on those devices.

If you want to see if some particular Javascript API method is supported for your version, browse the tags `2.14.2`:

![](https://dl.dropbox.com/s/vzwktqlmd3kjcqq/Screen%20Shot%202020-09-25%20at%209.46.03%20AM.png?dl=1)

Browse to the Javascript API, as [`src/index.js`](https://github.com/transistorsoft/react-native-background-geolocation/tree/2.14.2/src)

Search for the symbol [`onLocation`](https://github.com/transistorsoft/react-native-background-geolocation/blob/2.14.2/src/index.js):

**Comment by JimmyKho** [comment]
> > react-native-background-geolocation@2.14.2,
> 
> [2.14.2](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#2142-2018-11-20) is nearly **two years old**. You're not interested in supporting iOS 13/14 and Android 10/11? Your app is not likely working on those devices.
> 
> If you want to see if some particular Javascript API method is supported for your version, browse the tags `2.14.2`:
> 
> ![](https://camo.githubusercontent.com/b3a1379c953f76b682f8faf360b283f4713ac09c/68747470733a2f2f646c2e64726f70626f782e636f6d2f732f767a776b74716c6d64336b6a6371712f53637265656e25323053686f74253230323032302d30392d32352532306174253230392e34362e3033253230414d2e706e673f646c3d31)
> 
> Browse to the Javascript API, at [`src/index.js`](https://github.com/transistorsoft/react-native-background-geolocation/tree/2.14.2/src)
> 
> Search for the symbol [`onLocation`](https://github.com/transistorsoft/react-native-background-geolocation/blob/2.14.2/src/index.js):

@christocracy would that means all these while my app geolocation has not been working on ios 13 and android 10? Then I have to update the package soonest. Thank you.

**Comment by christocracy** [comment]
>would that means all these while my app geolocation has not been working on ios 13 and android 10?

Most likely.  A version of the plugin from 2 years ago has no knowledge of the radical new permission constraints and requirements that [iOS 13 / Android 10](https://medium.com/@transistorsoft/ios-13-and-android-q-support-beb7595d2c24) and [iOS 14 / Android 11](https://medium.com/@transistorsoft/ios-14-android-11-support-6ba6514e281c) have introduced.

**Comment by roberth-fsl** [comment]
Hi I want to capture the coordinates every 10 mins I implemented the HeartBeats approach I tested every 1 min but something it works and stops after sometime, sometimes doesnt work at all, 

this is the function I created

const geolocation = async () => {
  console.log('calling GEOLICATION');
  BackgroundGeolocation.ready(
    {
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,

      // Application config
      heartbeatInterval: 60,
      debug: true, // <-- enable this hear debug sounds.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      enableHeadless: true,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when app terminated.
      startOnBoot: true,
    },
    state => {
      if (!state.enabled) {
        BackgroundGeolocation.start(function () {
          console.log('- Start success');
        });
      }
    },
  );

  BackgroundGeolocation.onHeartbeat(async event => {
    BackgroundGeolocation.getCurrentPosition({
      timeout: 30, // 30 second timeout to fetch location
      maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
      desiredAccuracy: 10, // Try to fetch a location with an accuracy of `10` meters.
      samples: 3,
    }).then(async location => {
      console.log('[getCurrentPosition] onHeartbeat: ', location);

      try {
        const { resource } = await api(
          'post',
          appConstants.EP.TECHNICIAN_INFO,
          {
            latitude: location.coords.latitude,
            longitude: location.coords.longitude,
            batteryChargeLevel: Math.floor(location.battery.level * 100),
          },
        );
      } catch (err) {}
    });
  });
};

export default geolocation;


I called it from the first screen I show in HomeScreen:


const HomeScreen = ({ navigation }) => {

  useEffect(() => {
    geolocation();
    return () => {
      BackgroundGeolocation.removeListeners();
    };
  }, []);

Also I have registered the heardless in the Index.js

let HeadlessTask = async event => {
  let params = event.params;

  switch (event.name) {
    case 'heartbeat':
      // Use await for async tasks
      // let location = await getCurrentPosition();
      // console.log(
      //   '[BackgroundGeolocation HeadlessTask] - getCurrentPosition:',
      //   location,
      // );
      break;
  }
};

BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

I would appreciate any help

Thanks
