### ISSUE TITLE
Library does not find module in NativeModules

### ISSUE THREAD

**Issue by chris-verclytte** [transistorsoft/react-native-background-geolocation#112]
Hello,

I am getting this error while trying to configure the service
```
    TypeError: Cannot read property 'configure' of undefined
    at Object.API.configure (node_modules/react-native-background-geolocation/RNBackgroundGeolocation.ios.js:14:28)
```

It seems that in "RNBackgroundGeolocation.ios.js“,  the module is not found at this line:
```
    const { RNBackgroundGeolocation } = require('react-native').NativeModules;
```
which make me think I have a problem with the ios configuration but i followed the tutorial step by step for both react-native-background-fetch and react-native-background-geolocation and tried it several times but I am still getting this error.

Has anyone already had this problem ?
Thanks.

**Comment by christocracy** [comment]
What was it?

**Comment by chris-verclytte** [comment]
Sorry for this one, I was totally off track, had not seen this was only appearing in unit tests because out of device context. I had to mock this to get rid of native code.

**Comment by oluckyman** [comment]
Had the same problem. Managed it to work by thoughtful walking thru instructions:
1. https://github.com/transistorsoft/react-native-background-fetch/blob/master/INSTALL.md
2. https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL.md

**Comment by nsainaney** [comment]
The links above are dead. I followed the manual instructions in README.md but am getting this error

**Comment by nsainaney** [comment]
`react-native link react-native-mauron85-background-geolocation` Gives the following errors:

```
Error: ENOENT: no such file or directory, open '/Projects/ios/empty-project-template/Info.plist'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.<anonymous> (/Projects/node_modules/react-native-mauron85-background-geolocation/scripts/postlink.js:29:28)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
/Projects/node_modules/react-native/local-cli/core/makeCommand.js:27
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node node_modules/react-native-mauron85-background-geolocation/scripts/postlink.js" command
    at ChildProcess.prelink (/Projects/node_modules/react-native/local-cli/core/makeCommand.js:27:15)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by christocracy** [comment]
Those links come from 2016.  See the [README](https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-setup-guides)

Before editing your post, you wrote:
```
react-native link react-native-mauron85-background-geolocation Gives the following errors:
```

This is **not** the Mauron85 version.  That is a *fork* of my original open-source project from ~5 years ago.

**Comment by nsainaney** [comment]
Thank you

**Comment by christocracy** [comment]
@nsainaney If you want the *best*, supported full-time for the last 4 years (and Made In Canada), innovating constantly, *this* is it.  If you want to use a side-project where you *might* get a response to your support requests, use the Mauron85 fork.

**Comment by christocracy** [comment]
What is this weird path?

/Users/narayans/Projects/node_modules

Your project name is Projects?

**Comment by christocracy** [comment]
Are you *sure* you changed directory into the project you created *before* adding the plugin.

And do not use the word “test” in your project name.  There’s a bug in the setup script that gets confused with “test target”

**Comment by nsainaney** [comment]
No. I had to do a search an replace to remove client names etc. Apologies. Did a search and replace so all paths are: /Users/narayans/Projects/CLIENT/PROJECT/node_modules

**Comment by christocracy** [comment]
$react-native init Foo

Add the plugin into a blank app.  Follow the react-native link instructions again

**Comment by nsainaney** [comment]
> Are you _sure_ you changed directory into the project you created _before_ adding the plugin.
> 
> And do not use the word “test” in your project name. There’s a bug in the setup script that gets confused with “test target”

That's correct. The path doesn't have the word _test_ (I found the note) and the project name is never changed after `npm install react-native-background-geolocation`. It appears Expo is not supported.

The steps I'm doing are:

1. expo init LocationPoC
2. npm install
3. expo eject (ExpoKit)
4. npm install react-native-background-geolocation
5. react-native link ...

**Comment by christocracy** [comment]
Too bad for you.  I dislike Expo.  More trouble than it’s worth.

Go pure React Native and save yourself a world of trouble.
