### ISSUE TITLE
installation  issue

### ISSUE THREAD

**Issue by suralove** [transistorsoft/react-native-background-geolocation#1123]
* What went wrong:
Could not compile build file 'D:\ooooooooooooo\AwesomeProject\android\app\build.gradle'.
> startup failed:
  build file 'D:\ooooooooooooo\AwesomeProject\android\app\build.gradle': 85: expecting EOF, found 'background_geolocation' @ line 85, column 10.
     +Project background_geolocation = project(':react-native-background-geolocation')
              ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

**Comment by christocracy** [comment]
Those preceding `+` symbols in the setup guide or a **diff**.  You're not actually supposed to paste the `+` symbols.

![](https://dl.dropbox.com/s/qqpvqotnvo6z9yd/Screen%20Shot%202020-09-01%20at%201.09.03%20PM.png?dl=1)
