### ISSUE TITLE
Prevent apps main business logic to be executed from terminated state

### ISSUE THREAD

**Issue by Kida007** [transistorsoft/react-native-background-geolocation#1124]
Prevent apps main logic to be executed from terminated state

## Your Environment
* Plugin version: 3.8.1
* Platform: iOS 
* OS version: 13.5
* Device manufacturer / model: iPhone 11 simulator
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
      {
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
       // HTTP / SQLite config
          url: 'http://yourserver.com/locations',
         batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
         autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
         headers: {
         <-- Optional HTTP headers
           'X-FOO': 'bar',
         },
      (state) => {
        console.log('- BackgroundGeolocation is configured and ready: ', state.enabled);
      },
    );
```

## Expected Behavior

Ideally just want to update the location of the user to the server when the app in background and foreground, which i think just can be handled by SQLite/HTTP config . and don't want to run other logics and effects of different react-components when the app is in background.
## Actual Behavior

when the app is in background all of the unwanted JS code is executed with ( app's init flow, effects of different component ) and one of my useEffect block which even starts data polling is also executed ( highly unwanted ) . How can i just stick to the background service just making an HTTP call to server with location and nothing else.

## Steps to Reproduce

1. react-native run-ios
2. open the app 
3. terminate the app 
4. see the logs in react-native bundler executing everything in background

## Context

so my location logs are working perfectly in all 3 state ( foreground, background, app terminated ) . but when app is terminated and the location service starts in background it executes all of the app logics and therefore useEffects of each components. just want a way to prevent that

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
When iOS launches an app in the background, it’s completely launched just as if launched from the home screen.

I’m unaware of any way to achieve what you want.

**Comment by Kida007** [comment]
Thanks so much for quick reply . i managed to solve this via react-native AppState and restricted running of unwanted effects on background start.

**Comment by christocracy** [comment]
The plugin *does* have an iOS-only [`State.didLaunchInBackground`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.state.html#didlaunchinbackground).

You're probably reading something similar in `AppState` to determine when an app is launched in the background.

**Comment by Kida007** [comment]
yes you are right . `AppState` also lets know if the app in  background | active | inactive
