### ISSUE TITLE
Using log level VERBOSE in release mode

### ISSUE THREAD

**Issue by jacky-ew** [transistorsoft/react-native-background-geolocation#1126]
## Your Environment
* Plugin version: 3.3.2
* Platform: iOS and Android
* OS version: all
* Device manufacturer / model: all
* React Native version (`react-native -v`): 0.61.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	distanceFilter: 0,
	locationTimeout: 120,
	stopTimeout: 10,
	debug: true,
	logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
	stopOnTerminate: false,
	startOnBoot: true,
	locationAuthorizationRequest: "WhenInUse",
	reset: __DEV__,
	allowIdenticalLocations: true,
	disableElasticity: true,
	persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
	maxRecordsToPersist: 1000,
	maxDaysToPersist: 7,
	enableHeadless: true,
	geofenceInitialTriggerEntry: false
```

## Expected Behavior
We wanted to get the logs from users if any tracking mistakes occurs. But according to the docs we should not put log level to be VERBOSE in release mode. May I know how will it affect the app or device?

## Actual Behavior
Log level NONE in release mode

## Steps to Reproduce

1. set log level NONE by default
2. set to log level VERBOSE to get log from user

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> May I know how will it affect the app or device?

- will consume up to several megabytes of storage / day (up to `logMaxDays`).
- extra load on cpu performing database inserts for log-entries, affecting battery usage.

**Comment by jacky-ew** [comment]
if on android we clear app cache, will it clear the consumed storage?

**Comment by christocracy** [comment]
Why don’t you try it and see?

**Comment by jacky-ew** [comment]
Hi @christocracy, also we realised that when emailLog executes, on android device, there will show a Share to option, where we can also share the log files to whatsapp or any other communication application available. 

Is this the expected behaviour?
Also i could not locate the log file anywhere within android storage (android > data > BUNDLE_ID). Is the log not saved to internal storage?

**Comment by christocracy** [comment]
> Is this the expected behaviour?

Yes.

See api docs BackgroundGeolocation.logger

The logs are stored in SQLite.  There is also a method getLog.
