### ISSUE TITLE
onLocation triggered with startGeofences

### ISSUE THREAD

**Issue by Uday-Samineni97** [transistorsoft/react-native-background-geolocation#1127]
LocationChange is triggered with startGeofences i.e tracking mode 0 and returning the coords.

* Plugin version:3.81.
* Platform: iOS and Android

 Expected Behavior
startGeofences should track only geofences.

Actual Behavior
startGeofences triggering onLocation and returning the location co-ordinates also.

 Context
We are trying to track the user's location on DWELL event i.e after entering the geofence by calling start method and track only geofence after exiting the geofences.

{"useSignificantChangesOnly":false,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","schedule":[],"logLevel":3,"locationTimeout":60,"forceReloadOnSchedule":false,"forceReloadOnGeofence":false,"disableAutoSyncOnCellular":false,"desiredOdometerAccuracy":100,"desiredAccuracy":-1,"activityRecognitionInterval":10000,"schedulerEnabled":false,"enabled":true,"stopTimeout":20,"startOnBoot":true,"params":{},"locationsOrderDirection":"ASC","encrypt":false,"enableTimestampMeta":false,"elasticityMultiplier":1,"deferTime":0,"batchSync":false,"stopOnTerminate":false,"stopAfterElapsedMinutes":0,"geofenceProximityRadius":8000,"forceReloadOnMotionChange":false,"enableHeadless":true,"disableMotionActivityUpdates":false,"configUrl":"","allowIdenticalLocations":false,"maxDaysToPersist":1,"geofenceTemplate":"","geofenceModeHighAccuracy":false,"geofenceInitialTriggerEntry":true,"forceReloadOnLocationChange":false,"forceReloadOnBoot":false,"disableStopDetection":false,"url":"","stationaryRadius":25,"scheduleUseAlarmManager":false,"persistMode":2,"persist":true,"minimumActivityRecognitionConfidence":75,"maxRecordsToPersist":-1,"isMoving":false,"httpRootProperty":"location","disableElasticity":false,"debug":false,"didLaunchInBackground":false,"isFirstBoot":true,"trackingMode":0,"stopOnStationary":false,"notification":{"actions":[],"strings":{},"priority":0,"largeIcon":"","smallIcon":"","channelName":"TSLocationManager","color":"","text":"Location Service activated","title":"","layout":""},"method":"POST","locationUpdateInterval":1000,"locationTemplate":"","heartbeatInterval":-1,"fastestLocationUpdateInterval":5000,"authorization":{},"odometer":0,"speedJumpFilter":200,"maxBatchSize":-1,"logMaxDays":3,"httpTimeout":60000,"autoSyncThreshold":0,"autoSync":true,"motionTriggerDelay":0,"locationAuthorizationRequest":"Always","headlessJobService":"com.transistorsoft.rnbackgroundgeolocation.HeadlessTask","headers":{},"foregroundService":true,"forceReloadOnHeartbeat":false,"extras":{},"distanceFilter":10,"disableLocationAuthorizationAlert":false}: "INSIDE START GEOFENCE PROMISE"

{"extras":{},"battery":{"level":0.3,"is_charging":true},"activity":{"confidence":100,"type":"still"},"coords":{"altitude":-1,"heading":-1,"speed":-1,"accuracy":14,"longitude":80.0834864,"latitude":17.2255525},"odometer":0,"timestamp":"2020-09-03T12:55:56.801Z","uuid":"870afdfb-8155-41af-8057-3bbfbe94799b","is_moving":false,"event":"motionchange"}: "INSIDE LOCATION HANDLER EVENT"

{"extras":{},"battery":{"level":0.28,"is_charging":false},"activity":{"confidence":100,"type":"in_vehicle"},"coords":{"altitude":-1,"heading":-1,"speed":-1,"accuracy":600,"longitude":80.0868408,"latitude":17.2273537},"odometer":0,"timestamp":"2020-09-03T13:02:22.327Z","uuid":"c399b195-4f9a-4a1a-a692-e531bbe36a92","is_moving":false}: "INSIDE LOCATION HANDLER EVENT"

**Comment by christocracy** [comment]
Every recorded location is sent to `onLocation`, that includes locations recorded from a geofence event.

**Comment by Uday-Samineni97** [comment]
But startGeofences shouldn't record the location, right? As it tracks only the geofence events.

**Comment by christocracy** [comment]
Yes.

**Comment by christocracy** [comment]
You can *expect* to receive a location periodically during `startGeofences`.  You will not see a location recorded each `distanceFilter` meters.
