### ISSUE TITLE
App is receiving too much location updates

### ISSUE THREAD

**Issue by Omarkth** [transistorsoft/react-native-background-geolocation#1128]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS
* OS version: 13.3.1
* Device manufacturer / model: reported on iPhone 8 & iPhone X
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    const bgConfig = {
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      locationUpdateInterval: 900000,
      fastestLocationUpdateInterval: 0,
      notification: {
        text: "I'm in the background",
      },
      disableMotionActivityUpdates: false,
      stopTimeout: 1,
      logLevel: 0,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
      enableHeadless: true,
      persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
      maxRecordsToPersist: -1,
      maxDaysToPersist: 10000000
    };
    const state = await BackgroundGeolocation.ready(bgConfig);
```

## Expected Behavior
The application should receive a new location update every 50 meters or so

## Actual Behavior
The application received many location updates with less than 50 meters distance, looks like it ignored the "distanceFilter" config

## Steps to Reproduce

No steps to reproduce

## Context
This case happens at the staging environment, For many testers the logged locations were just fine, and match the configurations. For some testers and at specific scenarios (that we're not sure about) the app received too many location updates with less than 50 meters distance..

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
No logs since this happens on staging..
```

</details>

**Comment by christocracy** [comment]
The plugin *never* ignores `distanceFilter` when the device is in constant movement.

**Comment by jamilhaddadin** [comment]
HI @christocracy, I am working with the same team with Omar, We and many companies worldwide trust TransistorSoft in our business-critical applications! but as Omar has mentioned, in very few cases (our application has 1M users), we are experiencing extreme logging regardless of the 50Meter distanceFilter.

We would love to understand your view on what are the potential reasons for this? any pointer from is invaluable!

![toTransistorSoft](https://user-images.githubusercontent.com/9879719/92521526-0d0f3180-f226-11ea-99e2-26fe00d633f9.png)

**Comment by christocracy** [comment]
I have no idea what you're showing me.  See Wiki *Debugging* and learn to observe the logs from the plugin.

**Comment by christocracy** [comment]
btw, what is your *Order #*?
