### ISSUE TITLE
ActivityType remains still even the user keeps moving

### ISSUE THREAD

**Issue by Uday-Samineni97** [transistorsoft/react-native-background-geolocation#1129]
The activity type doesn't change with respect to user movement sometimes.

## Your Environment
* Plugin version: 3.81
* Platform: iOS and Android
* Device manufacturer / model: MI
* React Native version (`react-native -v`): 0.61.15

## Expected Behavior
The activity type should change with respect to user movement.

## Actual Behavior
The activity type remains still even the user moves in Vehicle.

## Context
I am recording the checkout on exiting the geofence when the activity type is in_vehicle.

## Debug logs
[log file.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/5182487/log.file.gz)

**Comment by christocracy** [comment]
Your Config provided to `.ready` is relevant to your issue.  You’ve not shown it here.

**Comment by Uday-Samineni97** [comment]
const BackgroundGeolocationConfig: Config = {
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  stopTimeout: 20,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
  enableHeadless: true,
  stopOnTerminate: false,
  startOnBoot: true,
  batchSync: false,
  autoSync: true,
  geofenceProximityRadius: 8000,
  geofenceModeHighAccuracy: false,
  foregroundService: true,
  allowIdenticalLocations: false,
  fastestLocationUpdateInterval: 5000,
  distanceFilter: 10,
  speedJumpFilter: 200,
  stationaryRadius: 25,
};
This is the config @christocracy

**Comment by christocracy** [comment]
The Android motion API operates by aggregating sensor data from *accelerometer*, *gyroscope* and *magnetometer*.

- If you're testing on Android emulator, those sensors won't trigger the motion api.
- If you're testing with mocked location with your device sitting stationary on your desk, those sensors won't trigger the motion api.

The only way to trigger the motion API is to *physically move*.

**Comment by Uday-Samineni97** [comment]
Yeah I was moving in a vehicle in the case of logs i have posted above. But the activity is still.

**Comment by christocracy** [comment]
You can observe motion-transitions in the logs:
```
09-07 11:53:25.732 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: walking
╟─ 🎾  ENTER: still
╚═════════════════════════════════════════════
```

The Android motion api is a black box with nothing more than an on/off switch.  The output depends on the sensors in the device (accelerometer, gyroscope, magnetometer).

**Comment by christocracy** [comment]
Also, when having a problem, the first thing to do is use `LOG_LEVEL_VERBOSE`.
