### ISSUE TITLE
Locations not sending after updating plugins

### ISSUE THREAD

**Issue by armin23615** [transistorsoft/react-native-background-geolocation#1131]
## Your Environment
* Plugin version: 3.9.0
* Platform: iOS 
* OS version: 12.4.8
* Device manufacturer / model: iPhone 6
* React Native version (`react-native -v`): 0.60
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  BackgroundGeolocation.ready(
    {
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      disableElasticity: true,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, // <-- enable this hear debug sounds.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when app terminated.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: config.API_URL + '/locations',
      batchSync: true, // <-- Set true to sync locations to server in a single HTTP request.
      autoSync: true, // <-- Set true to sync each location to server as it arrives.
      headers: {
        // <-- Optional HTTP headers
      },
      notificationsEnabled: false,
    },
    (state) => {
      // console.log('- BackgroundGeolocation is configured and ready: ', state.enabled)

      if (!state.enabled) {
        // Start tracking
        BackgroundGeolocation.start(function() {
          // console.log('- Start success')
        })
      }
    }
  )
```

## Actual Behavior

Locations not sending

## Steps to Reproduce

1.
2.
3.
4.

## Context

I wanted to schedule new react-native-background-fetch so I updated it from version 2.7.1 to 3.1.0 but then my app crashed after calling BackgroundGeolocation.start() 

Then I updated this plugin from version 3.3.2 to 3.9.0 and app stopped crashing, but it sends only one location (when BackgroundGeolocation.start() is called).

Is it possible to schedule another background-fetch while having background-geolocation or maybe plugin versions are not compatible?
Locations were sending fine before updating these two plugins? 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>but it sends only one location (when BackgroundGeolocation.start() is called

That's exactly what the sdk is supposed to do.

Are you watching the `$ adb logcat` when unexpected things occur, such as crashes?

**Comment by armin23615** [comment]
Yes, but it doesn't keep sending locations. My distance filter is 100m and nothing is recorded even after few kilometers (except that first location).
There are no crashes.

**Comment by christocracy** [comment]
When *anything* goes wrong, the *first* thing you go is fetch the logs from the plugin.  See Wiki *Debugging*.
