### ISSUE TITLE
Android version and call API?

### ISSUE THREAD

**Issue by xcarpentier** [transistorsoft/react-native-background-geolocation#1132]
Hi @christocracy !

Does `react-native-background-geolocalisation` ping a server (i.e. API) on android version to check the license key or whatever network call? Would like to pay and use the android version.

If yes, is it possible to remove this call?

I have this requirement for an app and if not I will not pay and then not use it at all! (my customer said so)
Thanks.
🙂

## Your Environment
* Plugin version: `v3.9.0?`
* Platform: `Android`
* OS version: `-`
* Device manufacturer / model: `-`
* React Native version (`react-native -v`): `0.63.2`
* Plugin config `-`

## Expected Behavior
No call of a server in the android version.

## Actual Behavior
I don't know but seems to be the case on my usage in an old version.

## Steps to Reproduce
N/A

## Context
Want to use Android but need more information.

## Debug logs
N/A

**Comment by christocracy** [comment]
>ping a server (i.e. API) on android version to check the license key or whatever network call?

No.  The plugin contains an *optional* HTTP service where you can configure the plugin to upload each recorded location to *your own* server via `Config.url`.

If you don't want the plugin to upload locations to your server, don't configure `#url` to `#ready` method.

The plugin does *not* require a server to validate license keys.  The plugin does not secretly upload data to any 3rd party service.
