### ISSUE TITLE
IOS background issue

### ISSUE THREAD

**Issue by maheshsutharbypt** [transistorsoft/react-native-background-geolocation#1135]
The SDK showing notification. like Motion-trigger timer cancelled in background and not getting location.

## Your Environment
* Plugin version:3.7.0
* Platform: iOS
* OS version:13.3.1
* Device manufacturer / model:MN8X2B/A
* React Native version (`react-native -v`):0.60.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
			// Geolocation Config
			desiredAccuracy: Platform.OS == 'android' ? BackgroundGeolocation.DESIRED_ACCURACY_HIGH : BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
			distanceFilter: 3,
			//foregroundService: true,
			notification: {
				smallIcon: "drawable/push_notification_icon"
			},
			pausesLocationUpdatesAutomatically: false,
			preventSuspend: true,
			// Activity Recognition
			stopTimeout: 60,
			disableStopDetection: true,
			pausesLocationUpdatesAutomatically: false,
			// Application config
			debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
			stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
			startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
			// HTTP / SQLite config
			url: NetworkManager.getNetworkInstance().serverUrl + '/v1/child/childCheckInOut',
			batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
			autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
			maxRecordsToPersist: 1,
			headers: {              // <-- Optional HTTP headers
				Authorization: DataManager.getInstance().currentUserDetails.jwtToken
			},
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
**Ignored Issue Template**

>Plugin version:
Platform: iOS or Android
OS version:
Device manufacturer / model:
React Native version (react-native -v):
Plugin config

**Comment by christocracy** [comment]
**Edit** your post to provide required information and this issue will be re-opened.

**Comment by maheshsutharbypt** [comment]
> Plugin version:3.7.0
> Platform: iOS
> OS version:13.3.1
> Device manufacturer / model: MN8X2B/A
> React Native version (react-native -v):0.60.3
> 
> Plugin config:
> 
> BackgroundGeolocation.ready({
> 			// Geolocation Config
> 			desiredAccuracy: Platform.OS == 'android' ? BackgroundGeolocation.DESIRED_ACCURACY_HIGH : BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
> 			distanceFilter: 3,
> 			//foregroundService: true,
> 			notification: {
> 				smallIcon: "drawable/push_notification_icon"
> 			},
> 			pausesLocationUpdatesAutomatically: false,
> 			preventSuspend: true,
> 			// Activity Recognition
> 			stopTimeout: 60,
> 			disableStopDetection: true,
> 			pausesLocationUpdatesAutomatically: false,
> 			// Application config
> 			debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
> 			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
> 			stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
> 			startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
> 			// HTTP / SQLite config
> 			url: NetworkManager.getNetworkInstance().serverUrl + '/v1/child/childCheckInOut',
> 			batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
> 			autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
> 			maxRecordsToPersist: 1,
> 			headers: {              // <-- Optional HTTP headers
> 				Authorization: DataManager.getInstance().currentUserDetails.jwtToken
> 			},

**Comment by christocracy** [comment]
I said **Edit** your post.  

![](https://dl.dropbox.com/s/83tdtd97xxuvtb2/Screen%20Shot%202020-09-17%20at%2010.44.35%20AM.png?dl=1)

**Comment by christocracy** [comment]
- See API docs `Config.debug`
- Provide logs.  See Wiki *Debugging*.

**Comment by maheshsutharbypt** [comment]
![WhatsApp Image 2020-09-16 at 4 47 35 PM](https://user-images.githubusercontent.com/62061992/93772836-efd25e00-fc3c-11ea-8f53-fdcca7cca707.jpeg)

**Comment by maheshsutharbypt** [comment]
![Uploading WhatsApp Image 2020-09-16 at 4.47.35 PM.jpeg…]()

**Comment by maheshsutharbypt** [comment]
![WhatsApp Image 2020-09-16 at 4 47 35 PM](https://user-images.githubusercontent.com/62061992/93773144-5a839980-fc3d-11ea-88fd-179c908095b4.jpeg)

**Comment by christocracy** [comment]
Now go outside for 200 meter walk.

**Comment by maheshsutharbypt** [comment]
Yes i walked but not working sometime

**Comment by maheshsutharbypt** [comment]
When i am going out side on morning its not working first time even after 200 covering in my car.

**Comment by christocracy** [comment]
>not working sometime

It all depends on the output of the Motion-recognition API to report a motion-activity such as `on_foot`, `in_vehicle`, etc.

Observe your logs for the output from the Motion-recognition system.
