### ISSUE TITLE
license validating URL

### ISSUE THREAD

**Issue by empiteranga** [transistorsoft/react-native-background-geolocation#1137]
## Your Environment
* Plugin version: 3.7.0
* Platform: Android
* OS version:8.1.0
* Device manufacturer / model:Emulator 
* React Native version (`react-native -v`): 0.60.5
* Plugin config

</details>
All are working fine, we need to clarify what is the API URL hit for validating the license key. because we need to whitelist that URL from our system

Actually this is not a bug, just need to know the API URL

**Comment by christocracy** [comment]
The plugin does not validate via remote server.  It's all done locally on the device.
