### ISSUE TITLE
HeadlessTask

### ISSUE THREAD

**Issue by victor9645** [transistorsoft/react-native-background-geolocation#1138]
`I have a problem, I want to run my task in the background and I have the code as follows:

let HeadlessTask = async (evento) => {
let params = event.params;
console.log ('[BackgroundGeolocation HeadlessTask] -', event.name, params);

            switch (event.name) {
              case 'heartbeat':
                // Use await for async tasks
                let location = await getLocation();
                console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
                break;
            }
          }

          let getLocation = () => {
            return new Promise((resolve) => {
              BackgroundGeolocation.onLocation((location)=>{
                console.log("Location",location);
                 Alert.alert("Ubication",JSON.stringify(location.coords.latitude));

                 BackgroundGeolocation.startBackgroundTask().then((taskId) => {
                  console.log("Location back",location);
                  BackgroundGeolocation.stopBackgroundTask(taskId);
                });

              })
            });
          };

         let HeadlessTask = async (event) => {
            let params = event.params;
            console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);
            
            switch (event.name) {
              case 'heartbeat':
                // Use await for async tasks
                let location = await getLocation();
                console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
                break;
            }
          }

          let getLocation = () => {
            return new Promise((resolve) => {
              BackgroundGeolocation.onLocation((location)=>{
                console.log("Location",location);
                 Alert.alert("Ubication",JSON.stringify(location.coords.latitude));

                 BackgroundGeolocation.startBackgroundTask().then((taskId) => {
                  console.log("Location back",location);
                  BackgroundGeolocation.stopBackgroundTask(taskId);
                });

              })
            });
          };
          BackgroundGeolocation.registerHeadlessTask(HeadlessTask);
Lo que hago es poner este código dentro de un switch, que si esto es cierto se ejecuta el BackgroundLocation.start () y otros, funciona, puedo cerrar la aplicación y sigue registrando la ubicación, pero mi problema es al ingresar al aplicación nuevamente, obtengo el siguiente error:
registerHeadlessTask o registerCancellableHeadlessTask llamado varias veces para la misma clave 'BackgroundGeolocation'

Según tengo entendido, estoy llamando a headlessTask dos veces con la misma clave, pero necesito que cada vez que el interruptor se establece en verdadero, se ejecute.`

**Comment by christocracy** [comment]
Your code makes no sense.  `onLocation` is an **event listener**, not a method to generate a location request.

See api docs `getCurrentPosition`.

Also, use https://translate.google.com

**Comment by victor9645** [comment]
I had asked you a while ago how I do to obtain the latitude and longitude with distanceFilter, which method should I use so that I take the distanceFilter and you told me to use the onLocation to obtain the location, which in theory worked because now when I walk I get said location, and I wanted to replicate the same thing but in the background, oh and in fact I have been using google translator for a long time, thanks for the kindness.

**Comment by christocracy** [comment]
Read read the api docs.  Read the wiki *Philosophy of Operation*.
