### ISSUE TITLE
A way to handle the cancel button click on LocationAuthroizationAlert

### ISSUE THREAD

**Issue by olegbraginmmc** [transistorsoft/react-native-background-geolocation#1140]
## Your Environment
* Plugin version: 3.9.0
* Platform: iOS
* OS version: iOS 14 (or at least iOS 11)
* Device manufacturer / model: iPhone 11 Pro
* React Native version (`react-native -v`): 0.62.2

## Expected Behavior

When I press the cancel button on LocationAuthorizationAlert, I want to run some code which saves user choice to not bug him with alerts anymore.
## Actual Behavior

The LocationAuthorizationAlert just closes.

The main idea is to ask a user for some elevated permissions like 'Always' just once. Some people do not want to let the app track them always. I searched through the docs for some way to handle that using the library integrated methods, but wasn't able to find anything useful.

**Comment by christocracy** [comment]
There's no way to handle the cancel button click.  The only way to do that would be to add a new event-listener and that would require a lot of infrastructure to support it.

Perhaps the plugin can render a `[ ] Don't warn me` checkbox on the dialog?

**Comment by olegbraginmmc** [comment]
A some kind of a checkbox is also possible, as long as it serves the same goal. THe tricky part is the UIAlertController under iOS and corresponding stuff on Android. On iOS adding a switch (UISwitch, a visual representation of checkbox) is tricky, to avoid any dirty hacks it's better to then render the custom UIView with all the UI rendered as necessary. I'm not sure about the Android, but I think there are some complications too. 

How about then adding a Configuration Setting, something like: `askForPermissionsOnce: Boolean`, which if `true` asks for requested permissions only once for user app installation?

**Comment by christocracy** [comment]
See API docs `Config.disableLocationAuthorizationAlert`

**Comment by christocracy** [comment]
Also, customers should post issues in the [private repo](https://github.com/transistorsoft/react-native-background-geolocation-android).  Issues posted there are given priority to those posted here in the public repo.

**Comment by olegbraginmmc** [comment]
Ok. Thanks for the answers.
