### ISSUE TITLE
Altitude Vs rawAltitude

### ISSUE THREAD

**Issue by mofmn** [transistorsoft/react-native-background-geolocation#1141]
I am referencing this API documentation - https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.coords.html#altitude
&
https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.location.html

It does not match what i see in the coords object provided by the position object in the onLocation method. I have an altitude value, a rawAltitude value and no altitude accuracy value. Here is a sample of what is returned:

```
{"activity": {"confidence": 100, "type": "still"}, "battery": {"is_charging": false, "level": 1}, "coords": {"accuracy": 5, "altitude": 727, "heading": 225, "latitude": 36.6735227, "longitude": 137.8449041, "rawAltitude": 727, "speed": 2.41}, "extras": {}, "is_moving": true, "odometer": 5716.7001953125, "timestamp": "2020-09-23T07:06:56.705Z", "uuid": "916c8ebd-97d3-427a-a089-64844d0a02b1"}
```

The issue is that i am not sure what the difference between Altitude and rawAltitude is as i cant find documentation. It also seems that Altitude seems reluctant to change, as i was testing today and it would stick to one value while raw altitude would change as expected. This may be intentional but i don't understand the way it intends to behave. I can show a log of this data at request. I imagine this is resolved by an update to documentation. This was tested in Android but i imagine it applies to both environments.

## Your Environment
* Plugin version: 3.9.0
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.63.2

**Comment by christocracy** [comment]
- The Android plugin is not currently sending `altitude_accuracy`
- I have no idea how you're seeing `"rawAltitude": 727` in the location object.  The SDK code contains no reference to this attribute.

>This was tested in Android but i imagine it applies to both environments.

No.  The two libraries are completely different.  The iOS plugin is implemented with Obj-c while Android is implemented with Java.  They are as different as apples and oranges.  They merely share a common Javascript API in front of them.

**Comment by christocracy** [comment]
However, I do see that the Android SDK has not been providing `altitude_accuracy`.  This is available from Android's [`Location.getVerticalAccuracy`](https://developer.android.com/reference/android/location/Location#getVerticalAccuracyMeters()).  This will be added in the next release.

iOS *does* provide `vertical_accuracy` already.

**Comment by mofmn** [comment]
> * I have no idea how you're seeing `"rawAltitude": 727` in the location object.  The SDK code contains no reference to this attribute.

You and me both. This is pulled straight from .onLocation, so its straight from your plugin. Is this something that you see when testing your plugin, or is it somehow only occurring in certain environments? Could it be an android version issue? I am using a pixel 2 api 30 Just in case that makes a difference, apologies for not including it initially.

**Comment by christocracy** [comment]
The *entire* src-tree for the library does not contain the String `"rawAltitude"`.

The plugin's Android library composes Java `JSONObject` instances to communicate back to RN.  The plugin's Android library *explicitly* decides what keys to populate in the `JSONObject`.  There is no such key defined for `"rawAltitude"`.

**Comment by mofmn** [comment]
My apologies, i am working with pre existing code and it seems the previous author mutated the data elsewhere for no obvious reason.

**Comment by christocracy** [comment]
**Note:**  Following still applies:

>The Android plugin is not currently sending altitude_accuracy.  This will be added in the next release.
