### ISSUE TITLE
distance filter ignored 

### ISSUE THREAD

**Issue by KianooshSoleimani** [transistorsoft/react-native-background-geolocation#1142]
## Your Environment
* Plugin version: 3.9.0
* Platform: iOS
* OS version: 14.0
* Device manufacturer / model: iphone 11 pro
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5000,
      disableElasticity: false,
      elasticityMultiplier: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Yo, location-services not enabled',
        titleWhenOff: 'Yo, location-services OFF',
        instructions: "You must enable 'Always' in location-services, buddy",
        cancelButton: 'Cancel',
        settingsButton: 'Settings',
      },
      locationAuthorizationRequest: 'Always',
      foregroundService: true,
      enableHeadless: true,
      showsBackgroundLocationIndicator: false,
      disableLocationAuthorizationAlert: false,
    }).then((state) => {
      console.log(
        '[ready] BackgroundGeolocation is configured and ready to use',
        state,
      );

      if (!state.enabled) {
        BackgroundGeolocation.start(function () {});
      }
    });
```

## Expected Behavior
got listener location update at every 5000 meters

## Actual Behavior
the speed of device was 35 m/s and I got location update at every 25 seconds so 35 * 25 ~ 1000 meters but i set distance filter to 5000 meters

## Steps to Reproduce

1.
2.
3.
4.

## Context

freeway drive
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plugin is monitoring the iOS Significant Location Changes API, which returns a location about every 1000 meters.

It's pointless to configure the plugin with distanceFilter `5000` if you're doing this in an attempt to conserve power.  It doesn't save much energy vs value of `0`.

Location-services is a collection of radio receivers connecting to satellites in space.  When the plugin is in the *moving* state, the GPS radio is on and connecting to satellites constantly, regardless of how high you set `distanceFilter`.  `distanceFilter` merely controls the rate that a location is pulled off the radio stream and delivered to your app.

You might as well just configure `useSignificantChangesOnly: true`
