### ISSUE TITLE
best configuration

### ISSUE THREAD

**Issue by KianooshSoleimani** [transistorsoft/react-native-background-geolocation#1144]
## Your Environment
* Plugin version: 3.9.0
* Platform: iOS
* OS version: 14.0
* Device manufacturer / model: iPhone 11 pro
* React Native version : 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  BackgroundGeolocation.ready({
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 20000,
      disableElasticity: false,
      elasticityMultiplier: 5,
      stopOnTerminate: false,
      startOnBoot: true,
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Yo, location-services not enabled',
        titleWhenOff: 'Yo, location-services OFF',
        instructions: "You must enable 'Always' in location-services, buddy",
        cancelButton: 'Cancel',
        settingsButton: 'Settings',
      },
      locationAuthorizationRequest: 'Always',
      foregroundService: true,
      enableHeadless: true,
      showsBackgroundLocationIndicator: false,
      disableLocationAuthorizationAlert: false,
      useSignificantChangesOnly: true,
    }).then((state) => {
      console.log(
        '[ready] BackgroundGeolocation is configured and ready to use',
        state,
      );

      if (!state.enabled) {
        BackgroundGeolocation.start(function () {});
      }
    });
```

## Expected Behavior

Dear Customer Service Manager,

First of all let me thank you indeed for your wonderful product.

To make sure that purchasing your Background Geo-Location License would be the best possible option for us, we have installed your package on ios devices and changed and tried many different configurations, sorry to say even after many trial and errors we couldn’t get expected results.

We hereby would like to request your professional suggestion on how to configure the settings of your package in order to reach our expected results based on the following requirements and purchase the License immediately afterward:

Our Requirements:

1. Our clients are Truck Drivers and most of their routes are out of the cities on the highways between them.

2. We will require the precise location of our clients every 30 to 40 Kilometers.

3. We will require the speed and Mobile charge percentage of our clients with the precise location we receive.

4. We will require the distance, our clients have travelled .

5. We will require the reposts of status changed by our clients such as terminating our application, turning location service off or stopping the app from getting location service.

6. We only require the location of our clients while driving / moving and don’t need the location while they are stopped or not moving .

7. Last but not least and very important is the Mobile battery consumption of our clients. So we will require the best possible setting to use minimum Mobile battery power.

I trust your professional Team to provide us the best possible configurations considering our requirements.

Warmly,
## Context

actually freeway drive

**Comment by KianooshSoleimani** [comment]
@christocracy waiting for your reponse

**Comment by christocracy** [comment]
>We will require the precise location of our clients every 30 to 40 Kilometers.

- `useSignificantChangesOnly` records a location about every 1000 meters.  `distanceFilter` ,` disableElasticity`, and `elasticityMultiplier` are ignored.

>We will require the distance, our clients have travelled .

Impossible with `useSignificantChangesOnly: true`.  The distance travelled will be *wildly* inaccurate, since odometer updates will be performed only about every 1000 meters.

>Last but not least and very important is the Mobile battery consumption of our clients. So we will require the best possible setting to use minimum Mobile battery power.

Since `useSignificantChangesOnly: true` records a location only about every 1000 meters, battery consumption will be low.
