### ISSUE TITLE
Android - timestamps with wrong year and time are getting posted.

### ISSUE THREAD

**Issue by ankur-1989** [transistorsoft/react-native-background-geolocation#1146]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: Android 10
* Device manufacturer / model:  it is happening at customer side would need to ask them about exact information if required.
* React Native version (`react-native -v`): 0.62.2 
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    stopOnTerminate: false,
    enableHeadless: Platform.OS === 'android' ? true : false,
    foregroundService: Platform.OS === 'android' ? true : false,
    preventSuspend: Platform.OS === 'android' ? false : true,
    heartbeatInterval: 60,
    startOnBoot: true,
    locationAuthorizationAlert: {
      titleWhenNotEnabled: translations.titleWhenNotEnabled,
      titleWhenOff: translations.titleWhenOff,
      instructions: translations.instructions,
      cancelButton: translations.cancel,
      settingsButton: translations.settings,
    },
    distanceFilter: Platform.OS === 'ios' ? 50 : 0,
    locationUpdateInterval: 60000,
    batchSync: true,
    autoSync: true,
    maxBatchSize: 10,
    autoSyncThreshold: Platform.OS === 'ios' ? 10 : 5,
    notification: {
      title: translations['lastGps'],
      text: translations['startGpsTracking'],
    },
   url: `${BASE_URL}/transports/${transportId}/gps/batch`,
      method: 'PUT',
      headers: {
        token: token,
      },
      httpRootProperty: '.',
      locationTemplate:
        '{"lat":<%= latitude %>,"lng":<%= longitude %>,"positionAccuracyError": <%= accuracy %>, "atd": "<%= timestamp %>" }',
      extras: {
        driverId: `${code}${driverId}`,
      },
```

## Expected Behavior

It should send the current timestamp of the system.
## Actual Behavior

 it is sending timestamp like this "2001-02-14T16:50:36.000Z"

## Context

We are just using the location service and sending the GPS signals as configured above in a batch.
## Debug logs

<details><summary>Logs</summary>

Currently, I don't have the logs as this is happening at the customer side in production. Would it be possible to tell what is happening without the logs?

</details>

**Comment by christocracy** [comment]
> Would it be possible to tell what is happening without the logs?

No.  Logs are required.  Are you sure the customer hasn’t changed the date on his/her phone?

**Comment by ankur-1989** [comment]
It sends sometimes not always.

**Comment by christocracy** [comment]
How do you know the customer is not changing the date on their phone *“sometimes”*?

**Comment by ankur-1989** [comment]
I'll ask the customer about this if that is the case, but I was wondering even if the customer changes the data how come it is sending the timestamp of the year 2001.

**Comment by ankur-1989** [comment]
one more strange thing that happens even though I have configured the threshold to 5 for android in a batch but it sends the data for more than 5 signals. the last log that we received at the back end was of 1600+ signals in a batch. Could you please tell us when can this be possible?

**Comment by christocracy** [comment]
> how come it is sending the timestamp of the year 2001.

I have no idea.  I don’t experience this on my 11 Android test devices.  Perhaps he changed the year to 2001?

> the last log that we received at the back end was of 1600+ signals in a batch. 

No idea.  Let me know how to reproduce it.

**Comment by ankur-1989** [comment]
I will ask the customer about it tomorrow. About the batch, is there any chance that if the location service does not get the 200 response from the backend then it keeps on accumulating the records and try to send all of them in a batch?

**Comment by christocracy** [comment]
>OS version: Android 10

This shouldn't apply, because you stated this problem occurs on an Android 10 device, but in case you just "made that up" while posting your issue, you'll want to search ["GPS week rollover bug"](https://en.wikipedia.org/wiki/GPS_Week_Number_Rollover)

>Plugin version: 3.4.2

Version [3.6.2](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#362---2020-04-08) includes a hack-fix for the "*GPS week rollover bug*".

>[Fixed] Android: Add hack for older devices to fix "GPS Week Rollover" bug where incorrect timestamp is recorded from GPS (typically where year is older by 20 years).

Btw, why are you using `3.4.2`?  The latest version [3.9.0](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#390--2020-08-20) includes support for Android 11 and iOS 14.  Also, if you've purchased a license, you should be posting issues to &mdash; *and installing the plugin from* &mdash; the private repo, where `3.9.1` was released today.

**Comment by christocracy** [comment]
>It sends sometimes not always.

Since the *GPS Week Rollover Bug* only affects GPS, locations recorded from Wifi/Cellular provider (ie: when device is not outdoors) are not affected by this bug.

**Comment by ankur-1989** [comment]
Thanks for informing me about this. I'll check the version 3.9.0 and 3.6.2 and could you please provide me with the link where I should post the issue in case if anything comes up in the future.

**Comment by christocracy** [comment]
The private repo is here:  https://github.com/transistorsoft/react-native-background-geolocation-android

If that url is 404, it means you don't have access and you should ask the license-admin to login to the *Product Dashboard* (where keys are managed) and click the `[+ Add Member]` button.

**Comment by ankur-1989** [comment]
Thanks for the quick information Chris!!

**Comment by mikehardy** [comment]
I get bizarre dates from clients. The kids borrow the phones and one of the ways around certain restrictions is apparently date-hacking the phone back in time, so then the SDK sends bogus times. It's one of those "you can never trust client data" things. I log those times but I also log the time the server actually received the timestamp as well.

**Comment by mikehardy** [comment]
I actually got a friend's kid (the friend was testing my app so had it installed) in trouble by mentioning it when we first saw it. The friend had no idea the kid was trying to hack around things, ha. Good luck

**Comment by ankur-1989** [comment]
Thanks for the info :)
