### ISSUE TITLE
Geofence events not reliable in android[Battery Optimisation disabled]

### ISSUE THREAD

**Issue by rimzici** [transistorsoft/react-native-background-geolocation#1147]
## Your Environment
* Plugin version: ^3.9.0
* Platform: Android
* OS version: 10
* Device manufacturer / model: Nokia (8.1)
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
return BackgroundGeolocation.ready({
			// Geolocation Config
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			geofenceInitialTriggerEntry: false,
			distanceFilter: 5,
			locationUpdateInterval: 1000,
			fastestLocationUpdateInterval: 1000,
			// Activity Recognition
			stopTimeout: 5,
			// Application config
			debug: true,
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
			logMaxDays: 15,
			stopOnTerminate:  false,
			startOnBoot: true,
			// HTTP / SQLite config
			batchSync: false,
			autoSync: false,
			// Android
			enableHeadless: true,
			geofenceModeHighAccuracy: true,
			geofenceProximityRadius: 400,
			foregroundService: true,
			notification: {
				smallIcon: 'drawable/icon_notif',
				largeIcon: 'drawable/icon_notif',
				title: 'Telldus Live! Mobile',
				text: formatMessage(i18n.geoFenceTrackingActive),
			},
			// iOS
			preventSuspend: true,
		}).then(async (state: Object): Object => {
			if (!state.enabled || state.trackingMode !== 0) {
				state = await dispatch(startGeofences());
			}
			if (state.enabled) {
				try {
					dispatch(getCurrentLocation());
				} catch (e) {
					// Ignore
				}
			}
			return state;
		});
```

## Expected Behavior

Expect geofence actions to be reliable.

## Actual Behavior

Fence events fired sometimes but not reliable.

## Steps to Reproduce

1. Add a fence
2. Let it run over a day or two

## Context

I have a single geofence added, and have set ENTRY/EXIT actions on it. It worked fine once, few hours after it was added(the app was closed completely). The next day I travelled through the same path as before, a little further, but no fence events were fired, none logged(app was closed completely).

**Timeline when fence worked fine**

- 09-30 12:50:56.366 INFO [GeofenceDAO create] // Geofence created
- 09-30 16:21:49.029 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: EXIT

- 09-30 16:41:52.003 INFO [GeofencingService a] 
╔═════════════════════════════════════════════
║ Geofencing Event: ENTER

This was on 09-30, the next day(10-01) no log at all during the time I travelled. I travelled between the time 08:45 AM - 09:30 AM, you may check the log below, there is no event(any log at all) during this time. First log on this day(10-01) is registered only at 10:29 AM. And that was when I opened the app after getting back home.

## Debug logs

<details><summary>Logs</summary>

Android Log:
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Rimneshs-MacBook-Air:live-app-v3 rimneshfernandez$ adb logcat -s TSLocationManager
* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -
--------- beginning of crash
--------- beginning of system
--------- beginning of main
10-01 11:12:49.552  5122  5122 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot] 
10-01 11:12:49.552  5122  5122 I TSLocationManager:   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
10-01 11:12:59.583  5122  9011 I TSLocationManager: [c.t.l.scheduler.ScheduleEvent onOneShot] 
10-01 11:12:59.583  5122  9011 I TSLocationManager: ╔═════════════════════════════════════════════
10-01 11:12:59.583  5122  9011 I TSLocationManager: ║ ⏰ OneShot event fired: TERMINATE_EVENT
10-01 11:12:59.583  5122  9011 I TSLocationManager: ╠═════════════════════════════════════════════
10-01 11:12:59.587  5122  9011 D TSLocationManager: [c.t.l.event.TerminateEvent <init>] 
10-01 11:12:59.587  5122  9011 D TSLocationManager:   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
10-01 11:17:45.921  5122  5122 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot] 
10-01 11:17:45.921  5122  5122 I TSLocationManager:   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
10-01 11:17:55.986  5122  9341 I TSLocationManager: [c.t.l.scheduler.ScheduleEvent onOneShot] 
10-01 11:17:55.986  5122  9341 I TSLocationManager: ╔═════════════════════════════════════════════
10-01 11:17:55.986  5122  9341 I TSLocationManager: ║ ⏰ OneShot event fired: TERMINATE_EVENT
10-01 11:17:55.986  5122  9341 I TSLocationManager: ╠═════════════════════════════════════════════
10-01 11:17:55.989  5122  9341 D TSLocationManager: [c.t.l.event.TerminateEvent <init>] 
10-01 11:17:55.989  5122  9341 D TSLocationManager:   ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
```

The log from getLog method -> [background-geolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/5309741/background-geolocation.log)

</details>

App Name: Telldus Live! Mobile

<details><summary>Screenshot - OS Battery optimisation disabled</summary>

![Screenshot_20201001-120208](https://user-images.githubusercontent.com/16771765/94776079-a7eecc00-03de-11eb-9d6e-63226cda6d91.png)

</details>

<details><summary>Screenshot of fence marked in map</summary>

![fence](https://user-images.githubusercontent.com/16771765/94773870-49bfea00-03da-11eb-8c44-25e48508e63d.png)

</details>

<details><summary>Timeline of my travel when geofence did not fire, from Google Maps</summary>

![Screenshot_20201001-105537](https://user-images.githubusercontent.com/16771765/94774121-d5397b00-03da-11eb-9c9a-7820a6f56f6f.png)

![Screenshot_20201001-105614](https://user-images.githubusercontent.com/16771765/94774141-e08ca680-03da-11eb-885a-a24b0abd5af4.png)

</details>

**NOTE on the screenshots**

- Fence marked is around my home.

- In the Google Maps timeline screenshot, the fence is around the place that is marked as "You are here"(my location).

- To get an idea about my travel, in the fence's screen and timeline screenshot there are common places "Palloor Sub Station" and "Palloor Police Station", this makes sure that I have went past the fence.

**Other Notes**

- Location permission : "Allow all the time", physical activity : "allow".

- OS Battery Optimisation is disabled for the app in all test devices below

- Facing this issue in most of the devices tested

| Device/Model  | Operating System |
| ------------- | ------------- |
| Nokia 8.1  | 10  |
| Nokia 4.2  | 10  |
| Huawei p20 pro(with Google services)  | 10  |
| BlackBerry KEY2  | 8.1.0  |

- Have tried different configs, like, setting `distanceFilter` to `0`, and `locationUpdateInterval` as `30000`. Still not reliable.

Thanks in advance.

**Comment by christocracy** [comment]
I regularly test with a *Nokia TA-27 @ 8.0.0* and *Huawei P20 Lite (ANE-LX3) @ 8.0.0*.  I had to follow the instructions at http://dontkillmyapp.com **to get both these devices to work**:

Yesterday's field-test:

- *Nokia TA-27 @ 8.0.0*

![](https://dl.dropbox.com/s/oeu8uqn7aj7o0ly/Screen%20Shot%202020-10-01%20at%208.42.15%20AM.png?dl=1)

- *Huawei P20 Lite @ 8.0.0*:

![](https://www.dropbox.com/s/xos2gy9x5urxl45/Screen%20Shot%202020-10-01%20at%208.43.06%20AM.png?dl=1)

**Comment by rimzici** [comment]
Thanks!
Have you had chance to see the service responsible for killing the apps in BlackBerry devices?
Turning off the general battery optimisation does not seem to help.

**Comment by christocracy** [comment]
>Have you had chance to see the service responsible for killing the apps in BlackBerry devices?

I don't know anything about BlackBerry devices.  The plugin does not support BlackBerry.

>Turning off the general battery optimisation does not seem to help.

Did you follow the *exact* instructions at http://dontkillmyapp.com?  There's more involved than simply *turning off battery optimization" for both *Huawei* and *Nokia*.

**Comment by vegasag** [comment]
I have the same issue that rimzici explains. I have a Samsung Galaxy Note10 Lite phone. 

I've done the steps by http://dontkillmyapp.com-url 

(with slightly different UI on Note 10, but basically:  

* Disable Put unused apps to sleep
* Disable Auto-disable unused apps
* Remove your app from the list of sleeping apps
* Disable background restrictions for your app
+ location Always)

I was out an hour ago and I mapped the following sequence where I compared iPhone and Android

Geofence | Phone | Trigger in/out | Time 
Area A | Android | Out | 15:15
Area A | ios | Out | 15:15
Area B | Android | In | 15:19
Area B | ios | In | 15:19
Area B | Android | Out | 15:22
Area B | ios | Out | 15:23
Area C | Android | In | //
Area C | Ios | In | 15:26
Area C | Android | Out | 15:34
Area C | Ios | Out | 15:36
Area A | Android | In | //
Area A | Ios | In | 15:41

As you can see it works as expected in all events but 2 (out of 6 android events). 

For my part, I do not have Battery Optimisation disabled, as it states (Samsung Note10) that this option will turn off background location.

**Comment by rimzici** [comment]
> Did you follow the _exact_ instructions at http://dontkillmyapp.com? There's more involved than simply *turning off battery optimization" for both _Huawei_ and _Nokia_.

Trying out in Nokia(8.1). Have added macros and ran as suggested. Will keep it running for few days and see.

![Screenshot_20201001-195950](https://user-images.githubusercontent.com/16771765/94823122-1f454f80-0421-11eb-8b7c-3bfed3f84a09.png)

Thanks!

**Comment by rimzici** [comment]
After following instructions at  http://dontkillmyapp.com for Nokia. Fence events now works fine, can receive events after device reboot as well.
