### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by LukePenkava** [transistorsoft/react-native-background-geolocation#1148]
When using npm install i am getting error Authenticating the plugin. I have license key in AndroidManifest, checked that its correct one. I have also went through installation process and updated everything. I have just paid license maintenance fee. 
 Not sure what i can do about it, its probably something basic. I didnt touch this plugin for almost year, so i am a bit rusty on what to do.

## Your Environment
* Plugin version: 3.9.0
* OS version: MacOS 10.15.7
* React Native version (`react-native -v`): 0.63.3

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
 Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/transistorsoft/react-native-background-geolocation-android.git
npm ERR! 
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/transistorsoft/react-native-background-geolocation-android.git/'
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/home/.npm/_logs/2020-10-01T10_35_31_686Z-debug.log
```

</details>

**Comment by christocracy** [comment]
Customers:  please post support requests in the [private repo](https://github.com/transistorsoft/react-native-background-geolocation-android)
