### ISSUE TITLE
Is it possible to attach metadata to the location events saved in the local database

### ISSUE THREAD

**Issue by vessp** [transistorsoft/react-native-background-geolocation#115]
My app has Journey objects and each recorded location belongs to a Journey.  The user may start and stop different journeys whenever they please so I need to link the recorded position with the journey id and submit this information together to the server.  So is it possible to add some metadata to the database row to be synced later?

**Comment by vessp** [comment]
Nevermind, I think the 'extras' configuration is what I was looking for, thanks!

**Comment by christocracy** [comment]
Exactly.
