### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by freightlive** [transistorsoft/react-native-background-geolocation#1152]
## Your Environment
* Plugin version: 3.9.1
* Platform: Android
* OS version: 10.0 and 9
* Device manufacturer / model: 10 is emulator, 9 is Galaxy Xcover 4
* React Native version (`react-native -v`): 0.63.2
* Plugin config
Same crash happens with or without config. This happens directly after following the installation steps

## Expected Behavior
The app launches

## Actual Behavior
I get an error message saying: 
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
The app shows an error view opening but not the view itself. I can't extract a stack trace. All I know is that this only happens in Android

## Context
Just trying to launch the app

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
--------- beginning of crash
--------- beginning of main
10-06 11:40:08.969 26302 26503 E TSLocationManager: 
10-06 11:40:08.969 26302 26503 E TSLocationManager: ╔═════════════════════════════════════════════
10-06 11:40:08.969 26302 26503 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.bumbal
10-06 11:40:08.969 26302 26503 E TSLocationManager: ╠═════════════════════════════════════════════
10-06 11:40:08.969 26302 26503 E TSLocationManager: ╟─ Failed to find license key in AndroidManifest.  Ensure you've added the key within <application><meta-data android:name="com.transistorsoft.locationmanager.license" android:value="<YOUR LICENSE KEY>" />
10-06 11:40:08.969 26302 26503 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
10-06 11:40:08.969 26302 26503 E TSLocationManager: ╚═════════════════════════════════════════════
10-06 11:41:28.947 26677 26739 E TSLocationManager: 
10-06 11:41:28.947 26677 26739 E TSLocationManager: ╔═════════════════════════════════════════════
10-06 11:41:28.947 26677 26739 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.bumbal
10-06 11:41:28.947 26677 26739 E TSLocationManager: ╠═════════════════════════════════════════════
10-06 11:41:28.947 26677 26739 E TSLocationManager: ╟─ Failed to find license key in AndroidManifest.  Ensure you've added the key within <application><meta-data android:name="com.transistorsoft.locationmanager.license" android:value="<YOUR LICENSE KEY>" />
10-06 11:41:28.947 26677 26739 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
10-06 11:41:28.947 26677 26739 E TSLocationManager: ╚═════════════════════════════════════════════
10-06 11:44:52.348 27120 28155 E TSLocationManager: 
10-06 11:44:52.348 27120 28155 E TSLocationManager: ╔═════════════════════════════════════════════
10-06 11:44:52.348 27120 28155 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.bumbal
10-06 11:44:52.348 27120 28155 E TSLocationManager: ╠═════════════════════════════════════════════
10-06 11:44:52.348 27120 28155 E TSLocationManager: ╟─ Failed to find license key in AndroidManifest.  Ensure you've added the key within <application><meta-data android:name="com.transistorsoft.locationmanager.license" android:value="<YOUR LICENSE KEY>" />
10-06 11:44:52.348 27120 28155 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
10-06 11:44:52.348 27120 28155 E TSLocationManager: ╚═════════════════════════════════════════════
10-06 11:54:18.846 28946 29183 E TSLocationManager: 
10-06 11:54:18.846 28946 29183 E TSLocationManager: ╔═════════════════════════════════════════════
10-06 11:54:18.846 28946 29183 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.bumbal
10-06 11:54:18.846 28946 29183 E TSLocationManager: ╠═════════════════════════════════════════════
10-06 11:54:18.846 28946 29183 E TSLocationManager: ╟─ Failed to find license key in AndroidManifest.  Ensure you've added the key within <application><meta-data android:name="com.transistorsoft.locationmanager.license" android:value="<YOUR LICENSE KEY>" />
10-06 11:54:18.846 28946 29183 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
10-06 11:54:18.846 28946 29183 E TSLocationManager: ╚═════════════════════════════════════════════
--------- beginning of system
```

</details>

If you guys need other information, please ask. We would like to use your services but at the moment our app just crashes after following your setup guides.

**Comment by christocracy** [comment]
Have you tried terminating and restarting your react-native dev server?

**Comment by freightlive** [comment]
Oh so many times. I've tried after resetting cache for gradle and react and no dice.

**Comment by christocracy** [comment]
Observe your react-native console for stack-trace output.

**Comment by freightlive** [comment]
I have added a txt file with all logs up unto the error. I would like to add that the app doesn't crash, it tries to show the React error view but it never expands. There is no stacktrace to be found. Maybe in the react error view but it unfortunately doesn't get renderer. The opening of the view is shown with a black bar coming from the bottom of the screen traveling to the top of the screen.
[Stacktrace.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/5346078/Stacktrace.txt)

**Comment by mikehardy** [comment]
Pasting your error message into a web search engine reveals most people have success with variations of the work achieved with `npx react-native-clean-project` followed by a pod install then a fresh attempt.

**Comment by freightlive** [comment]
I cleaned the project with the command and also manually once and the Android version is still not working

**Comment by christocracy** [comment]
Start by building a simple *Hello World* app and first learn to use the plugin in isolation of your app.

**Comment by freightlive** [comment]
The iOS version of the plugin is working just fine, it's specifically the Android version. I may not get this error on a clean build so I don't think this will help. I quickly did it anyway, didn't get any crashes this time around luckily.
This library however is causing an error in our app before it even has a chance to execute, I do not think this is because we have to "learn to use the plugin".
We are really interested in using this library in our app but we need some support because there is something specifically in the Android version that isn't working with the rest of our app.

**Comment by freightlive** [comment]
Hello there, we would still like some help! Hopefully you can get back to us

**Comment by christocracy** [comment]
Sorry, but this is not an issue with the plugin.  I suggest you create a fresh new *Hello World* app and experiment with the plugin in isolation of your application code.
