### ISSUE TITLE
[New Feature ?] GetLocations : is it possible to keep locations already sent to server in database ?

### ISSUE THREAD

**Issue by arochedy** [transistorsoft/react-native-background-geolocation#1153]
## Your Environment
* Plugin version:
* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
   BackgroundGeolocation.getLocations().then((result) => {
        console.log("resu : " + JSON.stringify(result));
      })
```

## Expected Behavior

I want to use getLocations to get every locations recorded by the plugin (even if they are already sent to the server)

I need this because sometimes on android, the app is shuttingdown, positions are sent to the server but not saved in my app. When the user go back on the map I want to show him all recorded positions. 

## Actual Behavior

GetLocations return empty array (I think that it's because all locations are sent to the server (like said here [https://github.com/transistorsoft/react-native-background-geolocation/issues/604
](https://github.com/transistorsoft/react-native-background-geolocation/issues/604) )

Is it possible to update the doc to explain that getLocations only return locations that are not already sent to the server ?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plugin's location database shouldn't be used for long-term storage.  I suggest you implement your own storage mechanism, inserting them using the `onLocation` event (and headless-task if using `enableHeadless: true`).

**Comment by arochedy** [comment]
Ok :  Do you have a example using redux ?

**Comment by christocracy** [comment]
No.
