### ISSUE TITLE
onHttp not emmited, not fire

### ISSUE THREAD

**Issue by ArhontSL** [transistorsoft/react-native-background-geolocation#1154]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 0,
                locationUpdateInterval: 60000,
                stopTimeout: 1,
                stopOnTerminate: false,
                startOnBoot: false,
                heartbeatInterval: 60,
                foregroundService: true,
                allowIdenticalLocations: true,
                enableHeadless: false,

                url: `my url`,
                headers: {'X-AUTH-TOKEN': `Bearer ${auth.token!.access}`},
                autoSync: true,
                batchSync: false,
                method: 'PUT',
                locationTemplate: '{"clientActionTime":"<%= timestamp =>","latitude":<%= latitude %>,"longitude":<%= longitude %>,"altitude":<%= altitude %>,"accuracy":<%= accuracy% >,"isMock:false"}',

                reset: true,
                debug: false,
            }
```

## Expected Behavior

Once a minute, it determines the coordinates and sends it to the server. The event should fire onHttp.

## Actual Behavior

The event onHttp does not fire.

## Steps to Reproduce

I think it started after calling destroyLocations.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
[Переслано от Jurij]
{
    "activityRecognitionInterval": 10000,
    "allowIdenticalLocations": true,
    "authorization": {},
    "autoSync": true,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "configUrl": "",
    "debug": false,
    "deferTime": 0,
    "desiredAccuracy": -1,
    "desiredOdometerAccuracy": 100,
    "disableAutoSyncOnCellular": false,
    "disableElasticity": false,
    "disableLocationAuthorizationAlert": false,
    "disableMotionActivityUpdates": true,
    "disableStopDetection": true,
    "distanceFilter": 0,
    "elasticityMultiplier": 1,
    "enableHeadless": false,
    "enableTimestampMeta": false,
    "encrypt": false,
    "extras": {},
    "fastestLocationUpdateInterval": -1,
    "forceReloadOnBoot": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnSchedule": false,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": true,
    "geofenceModeHighAccuracy": false,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {
        "X-AUTH-TOKEN": "Bearer "
    },
    "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
    "heartbeatInterval": 60,
    "httpRootProperty": "location",
    "httpTimeout": 60000,
    "isMoving": false,
    "locationAuthorizationRequest": "Always",
    "locationTemplate": "{\"clientActionTime\":\"<%= timestamp =>\",\"latitude\":<%= latitude %>,\"longitude\":<%= longitude %>,\"altitude\":<%= altitude %>,\"accuracy\":<%= accuracy% >,\"isMock:false\"}",
    "locationTimeout": 60,
    "locationUpdateInterval": 60000,
    "locationsOrderDirection": "ASC",
    "logLevel": 0,
    "logMaxDays": 3,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": -1,
    "method": "PUT",
    "minimumActivityRecognitionConfidence": 75,
    "notification": {
        "layout": "",
        "title": "",
        "text": "Location Service activated",
        "color": "",
        "channelName": "TSLocationManager",
        "smallIcon": "",
        "largeIcon": "",
        "priority": 0,
        "strings": {},
        "actions": []
    },
    "params": {},
    "persist": true,
    "persistMode": 2,
    "schedule": [],
    "scheduleUseAlarmManager": false,
    "speedJumpFilter": 300,
    "startOnBoot": false,
    "stationaryRadius": 25,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": false,
    "stopTimeout": 1,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "my url",
    "useSignificantChangesOnly": false,
    "enabled": true,
    "schedulerEnabled": false,
    "trackingMode": 1,
    "odometer": 0,
    "isFirstBoot": false,
    "didLaunchInBackground": false
}
```
</details>

**Comment by christocracy** [comment]
Are you watching the logs?  The plugin is logging everything it does.  See the Wiki *Debugging*.

**Comment by ArhontSL** [comment]
Help me figure out what error I have in the template.
![image](https://user-images.githubusercontent.com/35353167/95590301-9052bb80-0a4e-11eb-8010-85890ff098e7.png)

My template
locationTemplate: '{"clientActionTime":"<%= timestamp =>","latitude":<%= latitude %>,"longitude":<%= longitude %>,"altitude":<%= altitude %>,"accuracy":<%= accuracy% >,"isMock:false"}',

It seems to me that everything is according to the documentation. Why unknown variable?

**Comment by christocracy** [comment]
Pretty clear to me what the issue is.

```
"clientActionTime":"<%= timestamp =>"  // <-- FAIL
"latitude":<%= latitude %>  // <-- correct
```

**Comment by ArhontSL** [comment]
You're right. Silly mistake.

But now another problem. The template is correct. There is no mistake.
But the structure of the transmitted data is standard. As if there is no template at all.

locationTemplate: '{"clientActionTime":"<%= timestamp %>","latitude":<%= latitude %>,"longitude":<%= longitude %>,"altitude":<%= altitude %>,"accuracy":<%= accuracy% >,"isMock:false"}',

This is what the server gets

{"location":{"event":"motionchange","is_moving":false,"uuid":"39ce4bab-b3cc-40b6-ab11-9e20c0f33fb5","timestamp":"2020-10-09T13:48:24.445Z","odometer":0,"coords":{"latitude":53.9466279,"longitude":27.6895449,"accuracy":40.2,"speed":0.04,"heading":3.16,"altitude":270.5},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":1},"extras":{}}}

**Comment by christocracy** [comment]
The plugin renders the template and inserts into its database at the time the location is recorded.  If you have existing records in the plugin's database that were recorded *before* you implemented `locationTemplate`, the plugin is still trying to post those to your server, again and again and again.  Those records won't be destroyed until :
- Your server returns a `200` response.
- `Config.maxDaysToPersist` causes the plugin to automatically delete them.
- You manually delete them with `BackgroundGeolocation.destroyLocations()`

**Comment by ArhontSL** [comment]
There is something wrong with this

BackgroundGeolocation.destroyLocations()

As soon as I did this, it stopped being called again onHttp

**Comment by christocracy** [comment]
You're to remove that line after 1 boot of your app.  It's not supposed to be there **permanently**.  You just want to clear out the junk **once**.

**Comment by ArhontSL** [comment]
Many thanks! You helped me a lot. Sorry for the silly questions.

**Comment by ArhontSL** [comment]
One small question. Can I specify in the template a modifier (regular
  expression?) to change the date format?

2020-10-09T15:33:54.484Z to Y-m-d H:i:s

**Comment by christocracy** [comment]
No.
