### ISSUE TITLE
Don't get background locations in IOS when app is killed

### ISSUE THREAD

**Issue by gaurav07june** [transistorsoft/react-native-background-geolocation#1155]
When the app is in foreground it works fine but when the app is killed either by user or by OS, don't get the location update.

* Plugin version: "react-native-background-fetch": "^3.1.0",
    "react-native-background-geolocation": "^3.9.0",
* Platform: iOS
* OS version: 10.15.6
* Device manufacturer / model: IPhone Pro max
* React Native version (`react-native -v`): "0.61.3"
* Plugin config

componentDidMount(){
  
      BackgroundGeolocation.onLocation(this.onLocation.bind(this), this.onError.bind(this));
      BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
      BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));
      BackgroundGeolocation.onProviderChange(this.onProviderChange.bind(this));
      BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 5,
        stopTimeout: 1,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
        foregroundService: true,
        url : "some url here",
        autoSync: true,
        autoSyncThreshold: 10,
        isMoving: false,
        batchSync: true,
        method: "POST",
        extras: {'imei': deviceInfo.uniqueId},
        stationaryRadius: 27,
        notification: {
          sticky: true,
          title: "KOGO App Tracker",
          text: "Your live trip is started.",
          channelName: "KOGO App Tracker",
          smallIcon: "mipmap/ic_notification", // <-- defaults to app icon
          largeIcon: "mipmap/ic_launcher",
          priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH
        }
      }, (state) => {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

        if (!state.enabled) {
          BackgroundGeolocation.start(function() {
            console.log("- Start success");
            BackgroundGeolocation.changePace(false);
          });
        }
      });
    }
  }
## Expected Behavior
It should fetch location in app killed state too.

## Actual Behavior
When the app is killed , getting no location data

**Comment by christocracy** [comment]
Have you read the API docs for [Config.stopOnTerminate](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#stoponterminate)?

![](https://www.dropbox.com/s/2oseiurtm6lzrj6/Screen%20Shot%202020-10-12%20at%201.51.37%20PM.png?dl=1)

**Comment by gaurav07june** [comment]
I have set stopOnTerminate: false, which will enable tracking in background. Also, I have defined stationaryRadius: 27, which would, I think, will create a geofence of 27 meter radius. Now when I cross this 27 meter geofence, it should update the location, but it is not even I move for kilometers. Am I using some wrong config . Can u please guide me regarding this?

**Comment by christocracy** [comment]
> Also, I have defined stationaryRadius: 27, which would, I think, will create a geofence of 27 meter radius

No.  The minimum `stationaryRadius` that iOS will respond to is `200` meters.  You can set it `0`, it won't matter.

After terminating an iOS app, tracking will not resume until the device moves *a minimum* of `200` meters.  There is no "workaround".  This is a fact of life with iOS.

**Comment by christocracy** [comment]
I suggest you test in the iOS simulator with `debug: true` and simulate location with *Freeway Drive*.
- Launch app.  Simulate location with *Freeway Drive*.  Ensure locations are being recorded.
- Terminate app.
- Your app will relaunch a few seconds and tracking resumes.

**Comment by gaurav07june** [comment]
Thanks for you suggestion chris, I'll try this way.
Just for a check, I was using another application for background location tracking simultaneously with my app. And there was not a single deviations in the path for that app while my app was showing long straight lines. Both were facing same device or location conditions.

**Comment by christocracy** [comment]
It’s impossible for any iOS app to not have its tracking disrupted by at least 200 meters after app terminate.
