### ISSUE TITLE
Add speed-accuracy and course-accuracy

### ISSUE THREAD

**Issue by xcarpentier** [transistorsoft/react-native-background-geolocation#1156]
## Your Environment
* Plugin version: 3.9.0
* Platform: iOS (Android)
* OS version: 12+
* Device manufacturer / model: iPhone*
* React Native version (`react-native -v`): 0.63
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 0,
  heartbeatInterval: 60,
  preventSuspend: true,
  stopOnStationary: false,
  disableLocationAuthorizationAlert: true,
  isMoving: true,
  allowIdenticalLocations: true,
```

## Expected Behavior
Be able to get [speed accuracy](https://developer.apple.com/documentation/corelocation/cllocation/3524340-speedaccuracy) and [course accuracy](https://developer.apple.com/documentation/corelocation/cllocation/3524338-courseaccuracy)

## Actual Behavior
Not able to find speed accuracy and course accuracy.

## Steps to Reproduce
Use `onLocation` and see the result not containing speed-accuracy nor course-accuracy.

## Context
Getting speed accuracy and course accuracy

## Debug logs
no

**Comment by christocracy** [comment]
Will be added to next release in **private repo**.  It will not likely be mirrored here to the public repo for about 3 months.

Customers *please* post issues in the *private repo*, not here in the public repo.

**Comment by christocracy** [comment]
I always attempt to provide a common API for both Android and iOS wherever possible.

**Comment by christocracy** [comment]
The first thing I ask myself is does iOS' [CLLocation](https://developer.apple.com/documentation/corelocation/cllocation?language=objc) and Android's [Location](https://developer.android.com/reference/android/location/Location#getSpeedAccuracyMetersPerSecond()) offer similar properties?  The answer, in this case, is *yes*.
