### ISSUE TITLE
suppress the license validation error in android release builds

### ISSUE THREAD

**Issue by annucy** [transistorsoft/react-native-background-geolocation#1157]
## Your Environment
* Plugin version:^3.9.1
* Platform: Android
* OS version:10
* Device manufacturer / model: Oneplus
* React Native version (`react-native -v`):0.61.5
* Plugin config
  Did set up for react-native-background-geolocation for IOS and android. 

## Expected Behavior
There should be a way to suppress the license validation error in android release builds.

## Actual Behavior
license validation error is shown at App start itself, even if we don't intent to use the library in android.

## Steps to Reproduce
NA

## Context
Did set up for react-native-background-geolocation for IOS and android. We are planning to use the library only for IOS and it works as expected(license is not required here). But while making release build for android, it show the license key validation error. Is there any way to suppress this error message in android?

## Debug logs
NA
<details><summary>Logs</summary>
Did set up for react-native-background-geolocation for IOS and android. We are planning to use the library only for IOS and it works as expected(license is not required here). But while making release build for android, it show the license key validation error. Is there any way to suppress this error message in android?
</details>

**Comment by christocracy** [comment]
Show me your `package.json`

**Comment by annucy** [comment]
> Show me your `package.json`

{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "rnpm": {
    "assets": [
      "./src/assets/fonts/"
    ]
  },
  "dependencies": {
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "0.1.5",
    "@react-native-community/progress-view": "^1.1.0",
    "@react-native-firebase/analytics": "^7.6.7",
    "@react-native-firebase/app": "^8.4.5",
    "@react-native-firebase/crashlytics": "^8.4.9",
    "@react-native-firebase/messaging": "^7.9.0",
    "@react-native-firebase/perf": "^7.4.8",
    "amazon-cognito-identity-js": "3.2.1",
    "async": "2.6.0",
    "aws-sdk": "2.596.0",
    "expr-eval": "2.0.2",
    "install": "0.13.0",
    "libphonenumber-js": "1.7.30",
    "moment": "2.24.0",
    "moment-timezone": "^0.5.23",
    "react": "16.9.0",
    "react-localization": "1.0.15",
    "react-native": "0.61.5",
    "react-native-action-button": "^2.8.5",
    "react-native-android-location-enabler": "^1.2.1",
    "react-native-background-fetch": "^2.8.0",
    "react-native-background-geolocation": "^3.9.1",
    "react-native-communications": "2.2.1",
    "react-native-document-picker": "^3.5.3",
    "react-native-dropdown-menu": "^2.0.0",
    "react-native-elements": "1.2.7",
    "react-native-geocoder": "^0.5.0",
    "react-native-geolocation-service": "^5.0.0",
    "react-native-gesture-handler": "1.5.3",
    "react-native-global-props": "^1.1.5",
    "react-native-image-crop-picker": "^0.35.1",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "0.9.1",
    "react-native-keyboard-aware-view": "0.0.14",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-material-ui": "^1.30.1",
    "react-native-modal": "11.5.3",
    "react-native-modal-datetime-picker": "^7.5.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-modalbox": "1.4.2",
    "react-native-open-settings": "^1.0.1",
    "react-native-pdf": "5.0.9",
    "react-native-permissions": "^1.1.1",
    "react-native-progress": "4.0.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-root-toast": "3.0.1",
    "react-native-safe-area-context": "0.6.2",
    "react-native-screens": "2.0.0-alpha.22",
    "react-native-segmented-control-tab": "^3.4.1",
    "react-native-splash-screen": "3.2.0",
    "react-native-step-indicator": "0.0.8",
    "react-native-swiper-flatlist": "1.0.3",
    "react-native-switch": "^1.5.0",
    "react-native-tab-view": "1.0.2",
    "react-native-vector-icons": "^7.0.0",
    "react-native-version-number": "^0.3.6",
    "react-navigation": "4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "^2.0.8",
    "react-navigation-tabs": "^2.7.0",
    "react-redux": "^5.0.7",
    "redux": "4.0.5",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "mocha": "^5.2.0",
    "should": "^13.2.3",
    "babel-eslint": "8.2.5",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react-native": "4.0.0",
    "@babel/core": "7.6.2",
    "@babel/runtime": "7.6.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.5.1",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by christocracy** [comment]
> Is there any way to suppress this error message in android?

Sorry, not possible.

**Comment by CodeXiD** [comment]
Hi ! I also faced this problem, if I am not mistaken it is possible to solve this problem, I created a file **react-native.config.js** and added the following code

```js
module.exports = {
  dependencies: {
    "react-native-background-geolocation": {
      platforms: {
        android: null, // Отключает линковку для Android
      },
    },
  },
}

```
