### ISSUE TITLE
Issue on battery life while getting latitude and longitude even application in background

### ISSUE THREAD

**Issue by itvalues** [transistorsoft/react-native-background-geolocation#1158]
## My Environment
* Plugin version: 3.9.0
* Platform: iOS and Android
* OS version: All Android and iOS mobile
* Device manufacturer / model: All Android and iPhone model
* React Native version (`react-native -v`): 0.61.5
* Plugin config

```
BackgroundGeolocation.ready({
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        enableHeadless: true,
        distanceFilter: 0,
        locationUpdateInterval: 900000,
        isMoving: true,
        notification: {
          title: '*******',
          text: 'Location sharing in progress for automated security camera'
        },
        preventSuspend: true,
        // Activity Recognition
        // stopTimeout: 1,
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
        disableMotionActivityUpdates: true,
        disableStopDetection: true
      }, (state) => {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
      });
    }
```

## Expected Behavior
Need to get the latitude and longitude of the mobile and have to send to another device to compare the distance between the two mobiles. If the distance is less than 50m have to automate some future.

## Actual Behavior
We are implemented as per your documentation to getting latitude and longitude for automation. But we are not getting proper latitude and longitude when distance filter is in 10m, And sometimes if mobile doesn't have any acceleration we couldn't get latitude and longitude so we couldn't able to build up that automation feature. So we have used a timer to achieve this functionality in both iOS and Android. And it's working fine. But we are getting latitude and longitude based on a timer so we are facing issue on battery draining

**Comment by christocracy** [comment]
>But we are not getting proper latitude and longitude when distance filter is in 10m

GPS is nothing more than a constant radio stream of information.  `distanceFilter` / `locationUpdateInterval` merely control how often a sample is taken from the stream.  Using `distanceFilter` vs `locationUpdateInterval` has no affect on accuracy.

- It's well-known that time-based location-updates consume more energy than distance-based.
- `disableStopDetection: true` You realize that the plugin is going to keep location-services on forever, draining the battery, until you explicitly call `changePace(false)`?
- `preventSuspend: true,` The API docs warn that this will consume much more energy on iOS devices.
