### ISSUE TITLE
Socket after stoponterminate

### ISSUE THREAD

**Issue by bajjajjrajjesh** [transistorsoft/react-native-background-geolocation#1159]
## Your Environment
* Plugin version: 3.9.1
* Platform: iOS & Android
* OS version: ios 14 & android 11
* Device manufacturer / model: iphone x & samsung m40
* React Native version (`react-native -v`): 59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Socket to work after the app is killed
## Actual Behavior

socket stops working after i kill the app
## Steps to Reproduce

1.
2.
3.
4.

## Context

i want to to make sure that socket is working even after the app is killed
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>socket stops working after i kill the app

I would certainly *expect* a socket to terminate after terminating the app.  You created that Socket with your foreground app.  When that app gets terminated, so too does your socket.

**Comment by bajjajjrajjesh** [comment]
What is the solution to update the location to server if socket will not work with this?

**Comment by christocracy** [comment]
I have little experience with Sockets.  It's recommended to let the plugin handle uploading to server via its own built-in HTTP service, then you don't have these problems.  Search the API docs for *HTTP Guide*.

**Comment by bajjajjrajjesh** [comment]
Can you please explain how does you in built system works and how will that data reach my server. I didn't find any such doc please help.

**Comment by christocracy** [comment]
Did you read the "HTTP Guide" in the api docs?

**Comment by bajjajjrajjesh** [comment]
I have looked in [this](https://transistorsoft.github.io/react-native-background-geolocation/modules/_react_native_background_geolocation_.html#httpmethod) and I can't find any thing called http guide.

**Comment by christocracy** [comment]
You're not looking hard enough.

The main docs exist the `BackgroundGeolocation` class.

![](https://dl.dropbox.com/s/8zurdekfz6r4j5q/Screen%20Shot%202020-10-27%20at%2012.48.02%20PM.png?dl=1)

`[CTRL]+[F] "Http Guide"`

![](https://dl.dropbox.com/s/6wtuv9wz8z0o1ok/Screen%20Shot%202020-10-27%20at%2012.46.50%20PM.png?dl=1)

**Comment by bajjajjrajjesh** [comment]
This docs says how to use in app. It no where says about the server side implementation. 

- Do you have a web module which needs to be deployed to update the location. 
- Or we have use your server to update location. If yes then how do I get location update to my system. 
- How do I send custom Param from my app. In my case it's trip I'd.
