### ISSUE TITLE
Question: Storing recorded locations on the device to be used as a cache even after syncing

### ISSUE THREAD

**Issue by vessp** [transistorsoft/react-native-background-geolocation#116]
Hi, my question is, what is the best approach for keeping a history of locations on the device even after syncing to the server.  I'm considering the use case where the device obtains internet intermittently while recording.  I still want to show a history of where the user has gone, but if they close and open the app while having no internet after syncing to the server, the database will already have deleted some of the records.

Is there a way to prevent records from being deleted when syncing and distinguish which ones have been submitted, or do I need to create my own table to hold submitted records as the cache?

Thanks

**Comment by christocracy** [comment]
The plugin doesn't deal with long term storage of locations.  Once the server says "200 OK", the plugin eagerly deletes it from the database.

This is your responsibility.
