### ISSUE TITLE
Limit  latitude longitude number of decimals 

### ISSUE THREAD

**Issue by empiteranga** [transistorsoft/react-native-background-geolocation#1161]
## Your Environment
* Plugin version:^3.7.0
* Platform: iOS or Android(both)
* React Native version (`0.60.5`):

all are working fine, just want to know is there any way to limit the latitude and longitude decimal points

**Comment by christocracy** [comment]
Why??  the number of digits corresponds to the accuracy of the location.  If you remove digits, you would remove accuracy.

**Comment by empiteranga** [comment]
yes, we know that, but our client wants to have only a maximum of 6 digits

**Comment by christocracy** [comment]
The plugin is not going to remove digits from latitude/longitude.

If you your client wants to remove digits, have them do it on the server.

**Comment by empiteranga** [comment]
ok thanks for the reply
