### ISSUE TITLE
Background Geolocation demo app not fetching location when app is killed

### ISSUE THREAD

**Issue by satyarth02** [transistorsoft/react-native-background-geolocation#1163]
Downloaded Background Geolocation app for android and did a quick test for about 2 kms on foot. It is working for foreground and background but not when app is killed.

 Environment
* Plugin version: 3.9.0
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Vivo 1820
* React Native version : 0.61.3
* Plugin config
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 5,
    stopTimeout: 1,
    debug: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false, 
    startOnBoot: true,  
    autoSync: true,
    url: 'some url'
    
    
## Expected Behavior
App should fetch location when killed.

## Actual Behavior
Don't get location data hence straight lines when app is killed

## Steps to Reproduce

1.
2.
3.
4.

## Context

I tried with the default settings and then killed the app after some time. I didn't get any location for that duration.

Then I checked 'don't optimize battery' for the app. but it is not sending location in app killed state.

Default setting was
StopOnTerminate : false
startOnboot : true,
stopTimeout : 1,
distanceFilter : 10,

Please suggest, why I am getting this behaviour while you have documented that the app would get location in killed state.

I was moving in the duration when app was killed.

## Debug logs

please checkout 

http://tracker.transistorsoft.com/kogo?device=20014&end=2020-10-30%2021%3A0&start=2020-10-30%2018%3A0

**Comment by christocracy** [comment]
See http://dontkillmyapp.com.

Apply suggested changes to device settings according to your device model.
