### ISSUE TITLE
BackgroundGeoLocation not started after stoptimeout fire

### ISSUE THREAD

**Issue by KianooshSoleimani** [transistorsoft/react-native-background-geolocation#1165]
## Your Environment
* Plugin version: 3.9.1
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung / SM-M115F
* React Native version (`react-native -v`):  0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 500,
      disableElasticity: false,
      elasticityMultiplier: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      locationAuthorizationRequest: 'Always',
      foregroundService: true,
      enableHeadless: true,
      showsBackgroundLocationIndicator: false,
      disableLocationAuthorizationAlert: false,
      disableStopDetection: false,
      pausesLocationUpdatesAutomatically: false,
      disableMotionActivityUpdates: false,
      stopOnStationary: false,
      stopTimeout: 10,
      geofenceModeHighAccuracy: true,
```

## Expected Behavior
When app started everything is good and working properly but when device not moving and stopped after timeout 10minutes backgroundgeolocation is stopped and so far so good but when device started and is moving true nothing happend and backgroundgeolocation doesnt start i should mention the battery optimization is off for this testing

## Actual Behavior
after timeout 10minute background geo location stopped and doesnt start after device moving

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by KianooshSoleimani** [comment]
@christocracy i really apperciated if you answer me,

**Comment by christocracy** [comment]
Are you observing the plugin logs?  See wiki *Debugging*.
