### ISSUE TITLE
Failed to resolve: com.transistorsoft:tslocationmanager:+

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#1169]
## Your Environment
* Plugin version: 3.7.0
* Platform: Android
* OS version: all
* Device manufacturer / model: all
* React Native version (`react-native -v`): 0.63.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE

```
 BackgroundGeolocation.onLocation(this.onLocation, this.onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange(this.onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.onActivityChange(this.onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.onProviderChange(this.onProviderChange);

    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      //debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      disableLocationAuthorizationAlert: true,
      // HTTP / SQLite config
      // url: 'http://yourserver.com/locations',
      // batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      // autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        // BackgroundGeolocation.start(function() {
        //   console.log("- Start success");
        // });
      //  BackgroundGeolocation.startGeofences(function() {
      //     console.log("- Start Geofences success 1");
      //   });
      }
```

```

## Expected Behavior

I can build an app

## Actual Behavior

I can't build an app and get an error: 'Failed to resolve: com.transistorsoft:tslocationmanager:+'.
Yesterday everything was working fine!

## Steps to Reproduce

1. Run Android app

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You must perform the [Android Auto-linking Setup](https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-setup-guides)
