### ISSUE TITLE
is there any way to get number of Satellites from this plugin

### ISSUE THREAD

**Issue by empiteranga** [transistorsoft/react-native-background-geolocation#1172]
## Your Environment
Plugin version:^3.7.0
Platform: iOS or Android(both)
React Native version (0.60.5)

is there any way to get the number of Satellites from this plugin

**Comment by christocracy** [comment]
>is there any way to get the number of Satellites from this plugin

No.

**Comment by empiteranga** [comment]
can you give some clarification for this, because our clients ask why we can't get the number of satellites from this paid package

**Comment by christocracy** [comment]
- On iOS, it is impossible to get satellite data.
- The Android plugin uses the ['FusedLocationProviderClient`](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient) from *Google Play Services*.  This API *fuses* location-data from all possible sources (GPS, Wifi, Cellular) to provide the best possible location at any given time.  This API does not provide satellite data.
