### ISSUE TITLE
Background location delay on iOS

### ISSUE THREAD

**Issue by allan-swiftfare** [transistorsoft/react-native-background-geolocation#1173]
There is a delay before receiving background locations on ios. It looks like it's the 250m radius. Testing the behaviour side by side on other apps (Run Keeper) they get locations throughout.

I assume I'm missing a config option (current config is below).

I have bought a license if that makes a different to app behaviour. 

## Your Environment
* Plugin version: 3.9.1
* Platform: iOS 
* OS version: 13.5.1
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        BackgroundGeolocation.ready({
            notification: {
                title: "XXXX",
                text: "XXXXX",
            },
            // Geolocation Config
            triggerActivities: "in_vehicle, on_bicycle, on_foot, running, walking, stationary, still",
            geofenceProximityRadius: 20,
            isMoving: true,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 5,
            stationaryRadius: 5,
            disableElasticity: true,
            showsBackgroundLocationIndicator: true,
            // Activity Recognition
            stopTimeout: 15,
            // Application config
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
            // HTTP / SQLite config
            batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: false,         // <-- [Default: true] Set true to sync each location to server as it arri
        })
```

## Expected Behavior

I expect to be able to get location updates while in the background at the same frequency that other apps are able to.

## Actual Behavior

Running my app, and run keeper at the same time, in the background I got a continuous path with run keeper, but there was a lag with my app. The lag looked like it was about 250m.

I can include screenshots of the path in the different apps.

## Steps to Reproduce

1. Call start() to start monitoring locations
2. Background the app
3. Go for walk
4. Open the app back up and see the delay in collecting background locations.

## Context

I was trying to record the path that my walk took

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
An app like "RunKeeper" also has a button the user presses `[Start Workout]` which turns on location services.

This plugin *automatically* turns on location services when the device is detected to be moving (which required movement of about 200 meters).

You can do the same as *RunKeeper* by placing a UI button that executes `changePace(true)`.

**Comment by allan-swiftfare** [comment]
Awesome, thanks - I'll give it a go.

FWIW I made the assumption that isMoving in the config was having this effect? Does that just have an effect when I call BackgroundGeolocation.ready ?

**Comment by christocracy** [comment]
Yes, setting isMoving effectively causes start() to call changePace(true)
