### ISSUE TITLE
Payload too large error while syncing data to server

### ISSUE THREAD

**Issue by satyarth02** [transistorsoft/react-native-background-geolocation#1178]
## Your Environment
* Plugin version: ^3.9.1
* Platform: Android
* OS version: Android 10
* Device manufacturer / model: OnePlus GM1911
* React Native version (`react-native -v`): 3.2.1
* Plugin config

"activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {},
  "autoSync": true,
  "autoSyncThreshold": 10,
  "backgroundPermissionRationale": {
    "title": "Allow to access to this device's location in the background?",
    "message": "In order to track your activity in the background, please enable *Allow all the time* location permission",
    "positiveAction": "Change to *Allow all the time*",
    "negativeAction": "Cancel"
  },
  "batchSync": true,
  "configUrl": "",
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableStopDetection": false,
  "distanceFilter": 5,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "enableTimestampMeta": false,
  "encrypt": false,
  "extras": {
    "imei": "some value"
  },
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 1,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "Some title",
    "text": "Some message",
    "color": "",
    "channelName": "App Tracker",
    "smallIcon": "mipmap\/ic_notification",
    "largeIcon": "mipmap\/ic_launcher",
    "priority": 1,
    "sticky": true,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 1,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "http:\/\/api.some url",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 23213.798828125,
  "isFirstBoot": false,
  "didLaunchInBackground": false
}

## Expected Behavior
It should sync data to server properly

## Actual Behavior
Once I switched off the internet, and switched on after some time, I start getting HttpService error, and after some time, Payload too large in log.

## Context
I was moving with internet on and everything was ok. data was syncing to server and getting the correct path.
But once I switched off internet for some time. Data syncing to server stopped and checking the log showed Http failure and payload too large error.

## Debug logs

 🔴  LocationRequestService destroyed
11-23 16:04:50.212 INFO [HttpService a] 
  🔵  HTTP POST batch (409)
11-23 16:04:50.212 DEBUG [b allWithLocking] 
  ✅  Locked 409 records
11-23 16:04:50.220 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [notification, notification.text]
11-23 16:04:52.139 WARN [HttpService$i onResponse] 
  ⚠️  Response: 413, Payload Too Large
11-23 16:04:52.144 DEBUG [b unlock] 
  ✅  UNLOCKED (409)
11-23 16:04:52.180 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 3
11-23 16:04:52.181 DEBUG [AbstractService a] ⚙️︎  finish BackgroundTaskService [eventCount: 0, sticky: false]
11-23 16:04:52.183 DEBUG [AbstractService onDestroy] 
  🔴  BackgroundTaskService destroyed

I am putting log file here.
[praveerSirTrip.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/5583558/praveerSirTrip.gz)
![WhatsApp Image 2020-11-23 at 7 19 58 PM](https://user-images.githubusercontent.com/73731314/99972939-30795f80-2dc5-11eb-8f66-1f59f61b8acd.jpeg)
![WhatsApp Image 2020-11-23 at 7 28 26 PM](https://user-images.githubusercontent.com/73731314/99972954-353e1380-2dc5-11eb-945b-6b082d81eadc.jpeg)

**Comment by mikehardy** [comment]
That's your server returning a 413, complaining about payload size.
I would guess you either need to reconfigure your server so it can handle the larger payloads, or take advantage of the configuration settings in the plugin to send smaller chunks of data https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#maxbatchsize
