### ISSUE TITLE
Avast - "We've moved TSLocationManager to your Virus Chest because it was infected with MacOS:Pirrit-CS [PUP]"

### ISSUE THREAD

**Issue by edgarbonillag** [transistorsoft/react-native-background-geolocation#1179]
## Your Environment
* Plugin version: -> 3.9.3
* Platform: iOS or Android -> Both
* OS version: 10.15.7 MacOS Catalina
* Device manufacturer / model: Apple MacBook Pro 15-inch mid-2015
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```
Not necessary to put as it is not relevant.
```

## Expected Behavior

 `yarn add react-native-background-geolocation@3.9.3`
Package should install

## Actual Behavior

`yarn add react-native-background-geolocation@3.9.3`
Package installation gets interrupted and the Avast window appears showing the message:
"We've moved TSLocationManager to your Virus Chest because it was infected with MacOS:Pirrit-CS [PUP]"

## Steps to Reproduce

0. Have Avast installed.
1. Execute `yarn add react-native-background-geolocation@3.9.3`

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
From Avast:

Threat name: MacOS:Pirrit.CS [PUP]
Severity: (2 out of 3)
File name: TSLocationManager
File path: /Users/username/Library/Caches/Yarn/v6/npm-react-native-background-geolocation-3.9.3-7bab17653c852e3b54fa2765a85f1ae3d6bf548a-integrity/node_modules/react-native-background-geolocation/ios/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager
Process: /usr/local/Cellar/node@10/10.21.0/bin/node
Detected by: File Shield
Status: Threat blocked
```

</details>

**Comment by mikehardy** [comment]
This may be infected in your cache, not the original distribution. 

Here's the file as you pull it from github: https://github.com/transistorsoft/react-native-background-geolocation/blob/f8b75ad73f9e3fe3d3bc534940a0d757da99b1e0/ios/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager


Not sure how exactly to run a test detection against it, but if you download that file directly and have your Avast scan it, the result could be interesting. Note there are reports of false positives of this one, as well as virus packages with false negatives, so any result is just a result until corroborated.

**Comment by christocracy** [comment]
Likely a false positive.  A virus inserting itself into a compiled Obj-c framework doesn't seem plausible.

**Comment by edgarbonillag** [comment]
> This may be infected in your cache, not the original distribution.
> 
> Here's the file as you pull it from github: https://github.com/transistorsoft/react-native-background-geolocation/blob/f8b75ad73f9e3fe3d3bc534940a0d757da99b1e0/ios/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager
> 
> Not sure how exactly to run a test detection against it, but if you download that file directly and have your Avast scan it, the result could be interesting. Note there are reports of false positives of this one, as well as virus packages with false negatives, so any result is just a result until corroborated.

Hi @mikehardy and @christocracy , thank you for your answers. I did what it's mentioned above and Avast marks the file downloaded directly from the repo as a threat.
So, maybe it can be a false positive. But just in case, can you double-check that file and if you determine it is indeed a false positive, please close the issue and let me know.

Thank you very much.

**Comment by christocracy** [comment]
*MalwareBytes* says all is good on my machine:

![](https://dl.dropbox.com/s/5bsuf1yy0lyslr1/Screen%20Shot%202020-11-25%20at%209.32.38%20AM.png?dl=1)

**Comment by mikehardy** [comment]
Not trying to be a pain, but it appears malwarebytes is false negative for at least some versions of this one

https://www.virustotal.com/gui/file/96b5ab22505da91c50369b64ecee36279ee507c8c986a4b3d5aa2cc8c966653b/detection

I wish there was just a byte string (or strings) we could grep for rather than relying on opaque malware detection engines. I've got no special knowledge here unfortunately

**Comment by mikehardy** [comment]
For the record, I also think infection is implausible, I'm 99% this is false positive, but paranoia pays (to a certain extend) in security, so just trying to pin down that last %

**Comment by christocracy** [comment]
Ran *Avast* on my machine:

![](https://dl.dropbox.com/s/2son6hqcrrz0itc/Screen%20Shot%202020-11-25%20at%204.46.38%20PM.png?dl=1)

Someone on private Cordova repo reported this too, which references *Process: FileProvider.framework`, which is an iOS System library.

![](https://dl.dropbox.com/s/zxrwoagvzys2zkt/Screen%20Shot%202020-11-25%20at%204.48.23%20PM.png?dl=1)

**Comment by mohamedsharaf** [comment]
> Ran _Avast_ on my machine:
> 
> ![](https://camo.githubusercontent.com/69124fe1f52b6e052658a78cb269b9a98a2dc1ded25430c57aad9601730fecb9/68747470733a2f2f646c2e64726f70626f782e636f6d2f732f32736f6e3668716372727a306974632f53637265656e25323053686f74253230323032302d31312d32352532306174253230342e34362e3338253230504d2e706e673f646c3d31)
> 
> Someone on private Cordova repo reported this too, which references *Process: FileProvider.framework`, which is an iOS System library.
> 
> ![](https://camo.githubusercontent.com/fd56acaf5b2f28c482b1efc56de26fcfb3ceffe8510478c72a22e80d42341a17/68747470733a2f2f646c2e64726f70626f782e636f6d2f732f7a7872776f6167767a7973327a6b742f53637265656e25323053686f74253230323032302d31312d32352532306174253230342e34382e3233253230504d2e706e673f646c3d31)


this is file system because its extracting from zip 
npm install from git url git blocked
git clone fails git blocked 
download repo in zip and extract git the above image

**Comment by christocracy** [comment]
Using https://virustotal.com and uploading different [versions](https://github.com/transistorsoft/react-native-background-geolocation/releases) of `TSLocationManager` starting with `3.0.0`, I've found the exact version where this starts being detected.  I had a hunch it would be when I introduced the new `Config.encrypt` feature (with [`RNCryptor`](https://github.com/RNCryptor/RNCryptor)) and I was right.

The exact version where this starts being detected is [`3.4.0`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#340---2019-12-02)

**Comment by christocracy** [comment]
Removing `RNCryptor` from the library [cleans it up](https://www.virustotal.com/gui/file/37d4944358cad2061af35bd455177fccb2b606d5de27ee8708093495bd6d687d/detection).  

I'm going to throw the `Config.encrypt` feature in the garbage.

**Comment by mohamedsharaf** [comment]
@christocracy 

I think its because you are using the old version of RNCryptor which is known to have vulnerabilities  try the new version and i think it will work fine

regards

**Comment by christocracy** [comment]
@mohamedsharaf Reference?

**Comment by mohamedsharaf** [comment]
https://robnapier.net/rncryptor-hmac-vulnerability
https://seclists.org/fulldisclosure/2015/Jun/28

hope this help

**Comment by christocracy** [comment]
- Your first reference is from year *2012*.
- Your second link is from year *2015*.

`Config.encrypt` was introduced a year ago (*2019*) using what is still the latest version of [RNCRyptor 5.1.0](https://github.com/RNCryptor/RNCryptor/blob/master/CHANGELOG.md)

**Comment by christocracy** [comment]
`Config.encrypt` feature is removed in branch [release-3.10.0](https://github.com/transistorsoft/react-native-background-geolocation/tree/release-3.10.0).  Go ahead and analyze [`TSLocationManager`](https://github.com/transistorsoft/react-native-background-geolocation/tree/release-3.10.0/ios/RNBackgroundGeolocation/TSLocationManager.framework) from that branch.

**Comment by mohamedsharaf** [comment]
its clean now can u update 
cordova version

**Comment by christocracy** [comment]
All 3 plugin versions (`react-native`, `cordova` and `flutter`) have been pushed..

**Comment by christocracy** [comment]
Latest 3.10.0 released today has removed Config.encrypt.
