### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by valiaghaei** [transistorsoft/react-native-background-geolocation#1181]
Hi 
when i want to  run in simulator  i face  this  error:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
my Gradlew version  is  6.2
Should  i  upgrade  it  to  7 ?

**Comment by christocracy** [comment]
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

You need not be concerned about this.  You should use the same version of Gradle used by react-native.
