### ISSUE TITLE
Getting very few coordinates in background while recording a ride in iphone 11

### ISSUE THREAD

**Issue by ayushreactiveworks** [transistorsoft/react-native-background-geolocation#1182]
## Your Environment
* Plugin version: react-native-background-geolocation": "3.9.3" & react-native-background-fetch": "3.1.0"
* Platform: iOS 
* OS version: 13.6
* Device manufacturer / model: iphone 11
* React Native version (`react-native -v`):0.61.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
            autoSync: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            reset: false,
            foregroundService: true,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            startOnBoot: true,
            stopOnTerminate: false,
            heartbeatInterval: 60
        }, (state) => {
            if (!state.enabled ) {
                this.startTrackingLocation();
            }
        });
```

## Expected Behavior
While recording i should get more coordinates in background

## Actual Behavior
getting very few coordinates while recording a ride in background

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Typical tracking in my daily field-testing looks like this (`distanceFilter: 50`):

![](https://dl.dropbox.com/s/z1p30y3qt6oyqjh/Screen%20Shot%202020-12-01%20at%2010.01.35%20AM.png?dl=1)

If you're having a problem, the first step is to observe the plugin's logs.  See Wiki *Debugging* to learn how to fetch logs.

**Comment by ayushreactiveworks** [comment]
I have checked the logs and didn't found out any abnormality.

**Comment by christocracy** [comment]
Have you tried the /example app in this repo?

**Comment by ayushreactiveworks** [comment]
yes in that i am getting coordinates in background.

**Comment by christocracy** [comment]
Why are you telling the plugin to `reset: false`?
