### ISSUE TITLE
Capture Geolocation every 10 mins

### ISSUE THREAD

**Issue by roberth-fsl** [transistorsoft/react-native-background-geolocation#1183]
## Your Environment
* Plugin version:3.9.3
* Platform: Android
* OS version:27
* Device manufacturer / model:
* React Native version (`react-native -v`):0.63.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
Hi I want to capture the coordinates every 10 mins I implemented the HeartBeats approach I tested every 1 min but sometimes it works and stops after sometime, sometimes doesnt work at all,

this is the function I created

const geolocation = async () => {
console.log('calling GEOLICATION');
BackgroundGeolocation.ready(
{
// Geolocation Config
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,

  // Application config
  heartbeatInterval: 60,
  debug: true, // <-- enable this hear debug sounds.
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  enableHeadless: true,
  stopOnTerminate: false, // <-- Allow the background-service to continue tracking when app terminated.
  startOnBoot: true,
},
state => {
  if (!state.enabled) {
    BackgroundGeolocation.start(function () {
      console.log('- Start success');
    });
  }
},
);

BackgroundGeolocation.onHeartbeat(async event => {
BackgroundGeolocation.getCurrentPosition({
timeout: 30, // 30 second timeout to fetch location
maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
desiredAccuracy: 10, // Try to fetch a location with an accuracy of 10 meters.
samples: 3,
}).then(async location => {
console.log('[getCurrentPosition] onHeartbeat: ', location);

  try {
    const { resource } = await api(
      'post',
      appConstants.EP.TECHNICIAN_INFO,
      {
        latitude: location.coords.latitude,
        longitude: location.coords.longitude,
        batteryChargeLevel: Math.floor(location.battery.level * 100),
      },
    );
  } catch (err) {}
});
});
};

export default geolocation;

I called it from the first screen I show in HomeScreen:

const HomeScreen = ({ navigation }) => {

useEffect(() => {
geolocation();
return () => {
BackgroundGeolocation.removeListeners();
};
}, []);

Also I have registered the heardless in the Index.js

let HeadlessTask = async event => {
let params = event.params;

switch (event.name) {
case 'heartbeat':
// Use await for async tasks
// let location = await getCurrentPosition();
// console.log(
// '[BackgroundGeolocation HeadlessTask] - getCurrentPosition:',
// location,
// );
break;
}
};

BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

I would appreciate any help

Thanks
```

## Expected Behavior
Capture the geolocation every 10 mins

## Actual Behavior
Sometimes it works and then stop after a few moments 

## Steps to Reproduce

1.
2.
3.
4.

## Context
Capture the coordinates every 10 mins and share it to a server

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Device manufacturer / model:

**Comment by roberth-fsl** [comment]
Pixel 3a version 27

**Comment by christocracy** [comment]
Are you watching the plugin logs with `$ adb logcat *:S TSLocationManager:V`?

**Comment by roberth-fsl** [comment]
yes sir looks like it's workring, but the console.log I put in in the heartbeat never gets call

12-01 13:44:55.097 25727 25727 D TSLocationManager: ╔═════════════════════════════════════════════
12-01 13:44:55.097 25727 25727 D TSLocationManager: ║ TrackingService: LocationResult
12-01 13:44:55.097 25727 25727 D TSLocationManager: ╠═════════════════════════════════════════════
12-01 13:44:55.097 25727 25727 D TSLocationManager: ╟─ 📍  Location[fused 4.600608,-74.103745 hAcc=20 et=+9h10m49s112ms alt=0.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 15ms, time: 1606848300000
12-01 13:44:55.098 25727 25727 I TSLocationManager: [c.t.l.service.TrackingService b] 
12-01 13:44:55.098 25727 25727 I TSLocationManager:   ℹ️  Distance from stoppedAtLocation: 9.064632
12-01 13:44:55.098 25727 25727 D TSLocationManager: [c.t.l.service.AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
12-01 13:44:55.102 25727  7931 D TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
12-01 13:44:55.102 25727  7931 D TSLocationManager: ╔═════════════════════════════════════════════
12-01 13:44:55.102 25727  7931 D TSLocationManager: ║ Process LocationResult
12-01 13:44:55.102 25727  7931 D TSLocationManager: ╠═════════════════════════════════════════════
12-01 13:44:55.103 25727  7931 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 20.0
12-01 13:44:55.111 25727  7931 D TSLocationManager: [c.t.l.l.TSLocationManager incrementOdometer] Odometer: 333629.94
12-01 13:44:55.127 25727 31302 I TSLocationManager: [c.t.l.data.sqlite.b persist] 
12-01 13:44:55.127 25727 31302 I TSLocationManager:   ✅  INSERT: 7a3fdd9d-a33a-41d0-9cbf-5c56ebb75b05
12-01 13:44:56.092 25727 25727 D TSLocationManager: [c.t.l.service.AbstractService a] 
12-01 13:44:56.092 25727 25727 D TSLocationManager:   🎾  TrackingService [eventCount: 1]
12-01 13:44:56.093 25727 25727 D TSLocationManager: [c.t.l.service.TrackingService b] 
12-01 13:44:56.093 25727 25727 D TSLocationManager: ╔═════════════════════════════════════════════
12-01 13:44:56.093 25727 25727 D TSLocationManager: ║ TrackingService: LocationResult
12-01 13:44:56.093 25727 25727 D TSLocationManager: ╠═════════════════════════════════════════════
12-01 13:44:56.093 25727 25727 D TSLocationManager: ╟─ 📍  Location[fused 4.600672,-74.103657 hAcc=20 et=+9h10m50s108ms vel=23.38 bear=53.0 vAcc=??? sAcc=??? bAcc=??? {Bundle[{}]}], age: 16ms, time: 1606848301000
12-01 13:44:56.094 25727 25727 I TSLocationManager: [c.t.l.service.TrackingService b] 
12-01 13:44:56.094 25727 25727 I TSLocationManager:   ℹ️  Distance from stoppedAtLocation: 21.1125
12-01 13:44:56.094 25727 25727 D TSLocationManager: [c.t.l.service.AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
12-01 13:44:56.096 25727  7929 D TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
12-01 13:44:56.096 25727  7929 D TSLocationManager: ╔═════════════════════════════════════════════
12-01 13:44:56.096 25727  7929 D TSLocationManager: ║ Process LocationResult
12-01 13:44:56.096 25727  7929 D TSLocationManager: ╠═════════════════════════════════════════════
12-01 13:44:56.097 25727  7929 I TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
12-01 13:44:56.097 25727  7929 I TSLocationManager:   🔵  Re-scaled distanceFilter: 10.0->60.0)
12-01 13:44:56.100 25727  7929 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 20.0
12-01 13:44:56.122 25727  3971 I TSLocationManager: [c.t.l.data.sqlite.b persist] 
12-01 13:44:56.122 25727  3971 I TSLocationManager:   ✅  INSERT: 1b7c4208-4719-4bff-b939-b7fff179ceb0
12-01 13:44:56.257 25727 25727 D TSLocationManager: [c.t.l.service.AbstractService a] 
12-01 13:44:56.257 25727 25727 D TSLocationManager:   🎾  TrackingService [eventCount: 1]
12-01 13:44:56.259 25727 25727 D TSLocationManager: [c.t.l.service.TrackingService b]

**Comment by christocracy** [comment]
console.log get rendered to the `ReactNativeJS` logcat tag.

`$ adb logcat *:S TSLocationManager:V ReactNativeJS:V`

**Comment by roberth-fsl** [comment]
the issue is that it stops and I dont know the reason

![image](https://user-images.githubusercontent.com/73902778/100787181-413b5e00-33e1-11eb-9187-972ca3d22be7.png)

I think it's better if you could tell me how to set up the library in order to get the geolocation every 10 mins, should I use the HeartBeats or locationUpdateInterval? should I call the function in the Index or in the first screen as I did it? 

Thanks in advance

**Comment by christocracy** [comment]
Heartbeat stops when the device is detected to be moving.

Heartbeat operates only while the device is in the *stationary* state.

**Comment by roberth-fsl** [comment]
so based on what you said I should use onLocation and set up the settings locationUpdateInterval:10*60*1000 (10 mins) and it should work how I want it right?

you know I noticed once I start the app the first time it went well but as soon as I reload it, it's when it gets messy, where do you recommend initiating the library and how do I make sure the reload will work?

**Comment by christocracy** [comment]
>where do you recommend initiating the library and how do I make sure the reload will work?

As soon as your app launches, call `.ready()` ASAP.  Calling `.ready()` does not imply `.start()`.
