### ISSUE TITLE
Background Geolocation Plugin not working in Real Time 

### ISSUE THREAD

**Issue by manojkumaraut** [transistorsoft/react-native-background-geolocation#1186]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 
* Device manufacturer / model: Gionee P7 Max 
* React Native version (`react-native -v`): 0.61
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  BackgroundGeolocation.ready({
        desiredAccuracy: 0,
        stationaryRadius: 5,
        distanceFilter: 150,
        debug: false,
        startOnBoot: false,
        stopOnTerminate: false
    }, (state) => {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
        if (!state.enabled) {
            BackgroundGeolocation.start(function () {
                console.log("- Start success");
            });
        }
    });
    BackgroundGeolocation.onLocation((location) => {
}
```

## Actual Behavior
The Background Geolocation plugin is  **not working** in both foreground and background in real time while driving (Note ; Currently the climate is Rainy and Cloudy season ) and is in High Accuracy Mode
The Plugin is  updating the location when we use Mock Location route app simulator.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See Wiki *Debugging*.  The plugin cannot automatically trigger location-tracking from mocked location.  The plugin triggers location tracking when the motion API says the device is moving.  Motion API doesn't work in emulator.

See the note in Wiki *Debugging* about using mock location apps.

**Comment by christocracy** [comment]
For testing on *real* devices, the first thing you do is enable verbose logging and `debug: true`.  Also see http://dontkillmyapp.com.

**Comment by manojkumaraut** [comment]
This issue is happening from Last week only ...Earlier it was working fine in real time also.

**Comment by manojkumaraut** [comment]
Hi chris, Enabled debug : true option and ran a  test in real device and latitude and longitude got received continuously and working fine.

When i change  the debug to false, only 4 latitude and longitude points received for an hour journey...
Is there any plugin update need to de done with the existing licensed version ?

**Comment by christocracy** [comment]
`debug` has no effect on performance.  Nor does *release* vs *debug*.  The latest version is [3.9.4](https://github.com/transistorsoft/react-native-background-geolocation)

**Comment by manojkumaraut** [comment]
currently our version is 3.4.2 with release mode

**Comment by christocracy** [comment]
>Plugin version: 3.4.2

I know.  That's why I said that.

**Comment by manojkumaraut** [comment]
Is it mandatory to upgrade to the latest version ?

**Comment by manojkumaraut** [comment]
Will there needs to be optimized for the GPS data receive during rainy / cloudy season ?

**Comment by christocracy** [comment]
>Is it mandatory to upgrade to the latest version?

Do you care about support the latest Android 10 / 11 with `targetSdkVersion 29`?

>Will there needs to be optimized for the GPS data receive during rainy / cloudy season ?

There's nothing you can do about environmental problems.

**Comment by manojkumaraut** [comment]
Yes chris , we need to support the latest Android 10 / 11 with targetSdkVersion 29.

**Comment by christocracy** [comment]
Then *yes*, you will want to use the latest version `3.9.4`.

**Comment by fatpig0416** [comment]
Hey, man. Your example is even not running. and the package is very difficult to test.

**Comment by christocracy** [comment]
I field test the sample app almost every day on the following devices:

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 11
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by christocracy** [comment]
@fatpig0416 If you're jumping into someone else's issue, your should post all the information requested in the Issue Template, particularly your **Device manufacturer**.

>Device manufacturer / model: Gionee P7 Max

If the SampleApp doesn't work on some particular device, see http://dontkillmyapp.com

**Comment by fatpig0416** [comment]
Hi, christocracy. thanks for your package and your reply.
I tried to check if the package trigger exit event in real-time, tried this(mocking leave-arrive virtual route) in Android emulator Pixel_3_API_29 because I can't always move 200 meters for testing.
But couldn't get any event.
I am trying to use this package for such a purpose.
Scenario:
A user books a room in a building on my app and he stays in that room.
But when he goes out(exit event of geofence) of the building(lobby door), app should do some action(cancel bookings by request to backend).
Can I use your package for this purpose?
Thanks.

**Comment by christocracy** [comment]
See Wiki *Debugging*.  There's a note there about testing with *Mocked* location using `changePace(true)`.

>Can I use your package for this purpose?

The minimum geofence `radius` is 200 meters.  Yes, it will work for that purpose.

Geofence triggering does not work reliably with *mocked location*.
