### ISSUE TITLE
The application closes on other android devices.

### ISSUE THREAD

**Issue by herenoch15** [transistorsoft/react-native-background-geolocation#1188]
the application closes on other android devices.
i have two huwaei phones.
and the backgrournd does not work on the other device

where does the concern come from?

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Huawei are the worst devices on earth for background services.  See http://dontkillmyapp.com

**Comment by herenoch15** [comment]
But the Demo application works well on both devices

**Comment by christocracy** [comment]
Then there must be a problem in your own application code.  See Wiki *Debugging*.
