### ISSUE TITLE
An exception occurred in BackgroundGeolocation which stopped location tracking for some time

### ISSUE THREAD

**Issue by gaurav07june** [transistorsoft/react-native-background-geolocation#1190]
## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: samsung SM-A707F
* React Native version (`react-native -v`): 3.2.1
* Plugin config

"activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {},
  "autoSync": true,
  "autoSyncThreshold": 10,
  "backgroundPermissionRationale": {
    "title": "Allow to access to this device's location in the background?",
    "message": "In order to track your activity in the background, please enable *Allow all the time* location permission",
    "positiveAction": "Change to *Allow all the time*",
    "negativeAction": "Cancel"
  },
  "batchSync": true,
  "configUrl": "",
  "debug": true,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableStopDetection": false,
  "distanceFilter": 5,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "encrypt": false,
  "extras": {
    "imei": "some value"
  },
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
  "heartbeatInterval": 60,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 1,
  "maxBatchSize": 60,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "App Tracker",
    "text": "Your live trip is started.",
    "color": "",
    "channelName": "App Tracker",
    "smallIcon": "mipmap\/ic_notification",
    "largeIcon": "mipmap\/ic_launcher",
    "priority": 1,
    "sticky": true,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 1,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "http:\/\/some url",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 44233.08984375,
  "isFirstBoot": false,
  "didLaunchInBackground": false
}
## Expected Behavior
It should track location perfectly.

## Actual Behavior
While analysing the log, Got an exception at the time when tracking stopped for almost 10 minutes.

## Debug logs
 ✅  INSERT: 40278753-9182-450e-a267-43335d29d547
12-10 07:45:40.534 INFO [TSLocationManager removeLocationUpdates] 
  🔴  Location-services: OFF
12-10 07:45:40.539 ERROR [BackgroundGeolocation$v0 uncaughtException] 
  ‼️  Uncaught Exception: SyntaxError: JSON Parse error: Unexpected identifier "undefined", stack:
parse@-1
<unknown>@384:1793
<unknown>@1726:2073
value@47:1280
value@27:3685
<unknown>@27:841
value@27:2939
value@27:813
value@-1

{"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":10,"backgroundPermissionRationale":{"title":"Allow KOGO to access to this device's location in the background?","message":"In order to track your activity in the background, please enable *Allow all the time* location permission","positiveAction":"Change to *Allow all the time*","negativeAction":"Cancel"},"batchSync":true,"configUrl":"","debug":true,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":5,"elasticityMultiplier":1,"enableHeadless":true,"enableTimestampMeta":false,"encrypt":false,"extras":{"imei":"7fc26d22e6f01f15"},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.rnbackgroundgeolocation.HeadlessTask","heartbeatInterval":60,"httpRootProperty":"location","httpTimeout":60000,"isMoving":true,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":1,"maxBatchSize":60,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"KOGO App Tracker","text":"KOGO app tracker detects you moving.","color":"","channelName":"KOGO App Tracker","smallIcon":"mipmap\/ic_notification","largeIcon":"mipmap\/ic_launcher","priority":1,"sticky":true,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":1,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"http:\/\/dev.kogotrips.com:32288","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":2892.4619140625,"isFirstBoot":true,"didLaunchInBackground":false}

com.facebook.react.common.JavascriptException: SyntaxError: JSON Parse error: Unexpected identifier "undefined", stack:
parse@-1
<unknown>@384:1793
<unknown>@1726:2073
value@47:1280
value@27:3685
<unknown>@27:841
value@27:2939
value@27:813
value@-1

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:237)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:919)

12-10 08:21:20.860 INFO [TSConfig print] 
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="lsm6dsm Accelerometer Non-wakeup", vendor="STMicro", version=340, type=1, maxRange=78.4532, resolution=0.0023928226, power=0.15, minDelay=4808}
╟─ ✅  GYROSCOPE: {Sensor name="lsm6dsm Gyroscope Non-wakeup", vendor="STMicro", version=340, type=4, maxRange=17.452778, resolution=6.1084726E-4, power=0.555, minDelay=4808}
╟─ ✅  MAGNETOMETER: {Sensor name="ak0991x Magnetometer Non-wakeup", vendor="akm", version=10077, type=2, maxRange=4912.0, resolution=0.15, power=1.1, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="smd  Wakeup", vendor="Samsung", version=1, type=17, maxRange=1.0, resolution=0.01, power=0.001, minDelay=-1}
╚═════════════════════════════════════════════
12-10 08:21:20.863 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:12451000)
12-10 08:21:20.883 DEBUG [TSLocationManager$d run] 
  ℹ️  Load last odometer location: Location[TSLocationManager 11.354023,76.695554 hAcc=4 t=?!? et=?!? vAcc=??? sAcc=??? bAcc=??? {Bundle[{odometer=2892.462}]}]
12-10 08:21:20.889 DEBUG [AbstractService a] 
  🎾  ActivityRecognitionService [eventCount: 1]
12-10 08:21:20.889 DEBUG [HttpService startMonitoringConnectivityChanges] 
  🎾  Start monitoring connectivity changes
12-10 08:21:20.895 DEBUG [BackgroundGeolocation isMainActivityActive] NO
12-10 08:21:20.896 DEBUG [HeadlessTask onHeadlessEvent] 💀  event: activitychange
12-10 08:21:20.899 INFO [HeartbeatService c] 
  🔴  Stop heartbeat
12-10 08:21:20.907 INFO [BackgroundGeolocation d] 
  🎾  Start monitoring location-provider changes
12-10 08:21:20.909 DEBUG [BackgroundGeolocation isMainActivityActive] NO
12-10 08:21:20.911 DEBUG [HttpService a] 
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? true
╠═════════════════════════════════════════════

**Comment by christocracy** [comment]
BackgroundGeolocation implements a global exception-handler to catch and log *all* uncaught exceptions for your entire app.

This exception is not *caused* by `BackgroundGeolocation`.

You seem to have a JSON parsing error somewhere in your code.  

```
com.facebook.react.common.JavascriptException: SyntaxError: JSON Parse error: Unexpected identifier "undefined"
```
