### ISSUE TITLE
Demo app not tracking when the app in background or killed

### ISSUE THREAD

**Issue by gaurav07june** [transistorsoft/react-native-background-geolocation#1193]
## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version: 8
* Device manufacturer / model: Vivo
* React Native version (`react-native -v`): 3.2.1
* Plugin config
Default used in Demo application
## Expected Behavior
should track in background or killed state

## Actual Behavior
Not tracking when app goes in background or killed

## Context
I am using demo application for testing on my mobile phone. 
I followed don't kill my app and do all the settings. 
The app is working fine when in foreground but when goes to background or killed , it stopped tracking.

## Debug logs
http://tracker.transistorsoft.com/kogo?device=20014&end=2020-12-11%2023%3A0&start=2020-12-11%2021%3A0
this is what I get on the demo server

Start date: 11 Dec 2020 9:00 PM
End date : 11 Dec 2020 11:00 PM
</details>

**Comment by christocracy** [comment]
See http://dontkillmyapp.com

**Comment by gaurav07june** [comment]
I have done all the settings in following the link. Still getting same way of tracking
@christocracy One more thing , there is no notification in the notification tray. May be due to that not getting location when app is in background or killed.
Why I am not getting notification?

**Comment by christocracy** [comment]
See Wiki debugging.  Observe the logs from the plugin.
