### ISSUE TITLE
sending location randomly

### ISSUE THREAD

**Issue by bajjajjrajjesh** [transistorsoft/react-native-background-geolocation#1194]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS
* OS version: 14.2
* Device manufacturer / model: Apple iPhone X
* React Native version (`react-native -v`): 0.59
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
    {
      url: `${servicesConfig.api.webUrl}/driverlocations`,
      autoSync: true,
      scheduleUseAlarmManager: true,
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      stopTimeout: 5,
      headers: {
        AUTHORIZATION: this.props.getJWTHeader
      },
      params: {
        tripId: trip_id,
        driverId: driver_id,
        platform:Platform.OS
      },
      locationsOrderDirection: "DESC",
      maxDaysToPersist: 14,

      locationAuthorizationAlert: {
        titleWhenNotEnabled: "Your location settings need updating",
        titleWhenOff: "Your location settings need updating",
        instructions: "Please set your TruckTracker location settings to “Always”. This optimises the app’s ability to track the truck. Remember, your location is only being recorded whilst a trip is in progress.",
        cancelButton: "Cancel",
        settingsButton: "Settings"
      },//<~ For IOS only
      showsBackgroundLocationIndicator:true,//<~ For IOS only
      locationAuthorizationRequest: 'Always',// <~ For IOS only
      debug: false,
      enableHeadless: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
      notification: {
        sticky: true,
        title: 'Truck Tracker App Tracking',
        text: 'Your live trip is started.',
        channelName: 'DLS App Tracker',
        smallIcon: 'mipmap/ic_notification', // <-- defaults to app icon
        largeIcon: 'mipmap/ic_launcher',
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
      },
    })
```

## Expected Behavior

It should not send location randomly and sync shall work consistently
## Actual Behavior

I do trip 1 and it was tracking and sending location. I did a next trip from same phone and it was randomly sending location to server of the 1st trip which is maybe 200km away and location come to current location again and then again sometimes it goes back. Sometime it also goes back to old location of same trip.

I understand turning on autosync will send my old location but my question is why will it send location after 4-5 hours, isnt it suppose location immeditely after it has come back to network. 
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
When you have a problem like this, the first step is to fetch logs from the plugin.  The plugin saves logs to its own internal SQLite database for a default of 3 days.  See Wiki *Debugging* to learn how to fetch logs from the plugin.

**Comment by bajjajjrajjesh** [comment]
This issue is happening on clients apps and I have no access to there app. What is the other way to find the issue?

**Comment by christocracy** [comment]
>What is the other way to find the issue?

Start by reproducing the problem yourself.  I test iOS almost every day for > 6 years.  The SampleApp never seems to fail for me.

Also, map screenshots showing the problem can be helpful.

![](https://dl.dropbox.com/s/gbwk0gxpu7seunl/Screen%20Shot%202020-12-15%20at%209.31.43%20PM.png?dl=1)

**Comment by bajjajjrajjesh** [comment]
So my findings are it sending location of previous day in current trip. I will also send you screenshot of issue Map for your reference.
