### ISSUE TITLE
Odometer is always 0

### ISSUE THREAD

**Issue by arochedy** [transistorsoft/react-native-background-geolocation#1195]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Actual Behavior
On location event : location.odomter is always equal to 0 :( 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You have ignored the issue template.

>Plugin version:
Platform: iOS or Android
OS version:
Device manufacturer / model:
React Native version (react-native -v):
Plugin config
