### ISSUE TITLE
Cannot start motion-activity updates:  permission is denied  in the log and Location not being tracked in Android 11

### ISSUE THREAD

**Issue by gaurav07june** [transistorsoft/react-native-background-geolocation#1196]
## Your Environment
* Plugin version: 3.9.3
* Platform:  Android
* OS version: 11
* Device manufacturer / model: OnePlus IN2021
* React Native version (`react-native -v`): 3.2.1
* Plugin config
let state = await BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 5,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          title: "Allow to access this device's location even when closed or not in use.",
          message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
          positiveAction: 'Change to *Allow all the time*',
          negativeAction: 'Cancel'
        },
        stopTimeout: 1,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        maxDaysToPersist: 14,
        heartbeatInterval: 60,
        logMaxDays: 1,
        url : PRO_SYNC_URL,
        autoSyncThreshold: 10,
        batchSync: true,
        method: "POST",
        extras: {'imei': deviceInfo.uniqueId},
        foregroundService: true,
        notification: {
          sticky: true,
          title: "App Tracker",
          text: "Your live trip is started.",
          channelName: "App Tracker",
          smallIcon: "mipmap/ic_notification",
          largeIcon: "mipmap/ic_launcher",
          priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH
        }
      });
## Expected Behavior
It should track perfectly in Android 11

## Actual Behavior
Library is not tracking even when app is foreground or background. Analysing the log, I found Cannot start motion-activity updates:  permission is denied.
I explicitly provided the physical activity permission but no difference.

## Debug logs

12-16 17:09:38.827 DEBUG [TSLocationManagerActivity execute] locationsettings
12-16 17:09:38.827 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
12-16 17:09:38.827 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [autoSyncThreshold, backgroundPermissionRationale, backgroundPermissionRationale.title, backgroundPermissionRationale.message, backgroundPermissionRationale.positiveAction, backgroundPermissionRationale.negativeAction, batchSync, debug, desiredAccuracy, distanceFilter, enableHeadless, extras, heartbeatInterval, logLevel, logMaxDays, maxDaysToPersist, notification, notification.title, notification.text, notification.smallIcon, notification.largeIcon, notification.priority, notification.sticky, notification.channelName, startOnBoot, stopOnTerminate, stopTimeout, url]
12-16 17:09:38.834 INFO [c e] 
  🔵  LocationAuthorization: Requesting Background permission
12-16 17:09:38.835 INFO [c d] 
  🔵  Should show backgroundPermissionRationale? true
12-16 17:09:38.887 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

12-16 17:09:38.888 DEBUG [TSLocationManagerActivity execute] android.permission.ACCESS_BACKGROUND_LOCATION
12-16 17:09:38.982 DEBUG [TSLocationManagerActivity stop] eventCount: 1
12-16 17:09:39.008 INFO [c e] 
  🔵  LocationAuthorization: Requesting Background permission
12-16 17:09:39.009 INFO [c d] 
  🔵  Should show backgroundPermissionRationale? false
12-16 17:09:40.852 DEBUG [TSLocationManagerActivity execute] locationsettings
12-16 17:09:40.852 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
12-16 17:09:40.877 DEBUG [TSLocationManagerActivity stop] eventCount: 1
12-16 17:09:56.447 DEBUG [TSLocationManagerActivity stop] eventCount: 0
12-16 17:09:56.526 DEBUG [TSLocationManagerActivity onDestroy] 
12-16 17:09:56.786 WARN [ActivityRecognitionService b] 
  ⚠️  Cannot start motion-activity updates:  permission is denied
12-16 17:09:56.793 DEBUG [HttpService startMonitoringConnectivityChanges] 
  🎾  Start monitoring connectivity changes
12-16 17:09:56.796 DEBUG [a c] 
  🎾  Start monitoring powersave changes
12-16 17:09:56.798 DEBUG [HttpService a] 
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? true
╠═════════════════════════════════════════════

12-16 17:09:56.813 DEBUG [TSLocationManagerActivity execute] locationsettings
12-16 17:09:56.814 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
12-16 17:09:56.863 DEBUG [TSLocationManagerActivity stop] eventCount: 0
12-16 17:09:56.887 INFO [HeartbeatService b] 
  🎾  Start heartbeat (60s)
12-16 17:09:56.906 DEBUG [TSLocationManagerActivity onDestroy] 
12-16 17:09:56.914 INFO [TrackingService a] 
  🔵  setPace: false → false
12-16 17:09:56.914 INFO [c f] 
  🔵  LocationAuthorization: Requesting permission
12-16 17:09:56.923 INFO [c$i onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted
12-16 17:09:57.103 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
12-16 17:09:57.103 INFO [LocationRequestService a] 
  ℹ️  Location availability: true
12-16 17:09:57.103 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
12-16 17:09:57.122 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
12-16 17:09:57.123 INFO [LocationRequestService b] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 2
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 15.626839,73.731244 hAcc=4 et=+1d20h4m0s426ms alt=-78.80000305175781 vel=0.0579109 bear=57.64409 vAcc=2 sAcc=0 bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 43ms, time: 1608118798000

12-16 17:09:57.124 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: false
12-16 17:09:57.125 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 32.034
12-16 17:09:57.128 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
12-16 17:09:57.178 DEBUG [LocationRequestService b] SingleLocationRequest 2 isFinished? true
12-16 17:09:57.179 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
12-16 17:09:57.180 INFO [b persist] 
  ✅  INSERT: 406db17d-310e-4cd8-ab2d-5b116da8646a
12-16 17:09:57.185 WARN [ActivityRecognitionService b] 
  ⚠️  Cannot start motion-activity updates:  permission is denied
12-16 17:09:57.186 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 1)
╠═════════════════════════════════════════════

12-16 17:09:57.187 DEBUG [TSGeofenceManager startMonitoringStationaryRegion] 
  🎾  Start monitoring stationary region (radius: 150.0m 15.6268393,73.7312437 hAcc=4.068)
12-16 17:09:57.213 DEBUG [AbstractService a] 
  🎾  BackgroundTaskService [eventCount: 1]
12-16 17:09:57.214 INFO [BackgroundTaskManager onStartJob] ⏳ startBackgroundTask: 1
12-16 17:09:57.222 INFO [TrackingService h] 
╔═════════════════════════════════════════════
║ TrackingService motionchange: false
╠═════════════════════════════════════════════

12-16 17:09:57.222 DEBUG [AbstractService a] 
  🎾  TrackingService [eventCount: 1]
12-16 17:09:57.223 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: false]
12-16 17:09:57.226 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [notification, notification.text]
12-16 17:09:57.238 DEBUG [b allWithLocking] 
  ✅  Locked 1 records
12-16 17:09:57.243 INFO [HttpService a] 
  🔵  HTTP POST batch (1)
12-16 17:09:57.435 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService destroyed
12-16 17:09:57.485 DEBUG [AbstractService onDestroy] 
  🔴  TrackingService destroyed
12-16 17:09:57.801 INFO [HttpService flush] 
  ℹ️  HttpService is busy
12-16 17:09:57.825 INFO [HttpService$i onResponse] 
  🔵  Response: 200
12-16 17:09:57.826 DEBUG [b destroyAll] 
  ✅  DELETED: (1)
12-16 17:09:57.828 DEBUG [b allWithLocking] 
  ✅  Locked 0 records
12-16 17:09:57.828 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 1
12-16 17:09:57.828 DEBUG [AbstractService a] ⚙️︎  finish BackgroundTaskService [eventCount: 0, sticky: false]
12-16 17:09:57.835 DEBUG [AbstractService onDestroy] 
  🔴  BackgroundTaskService destroyed
12-16 17:11:03.517 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:11:03.519 DEBUG [HeartbeatService$a run] ❤️
12-16 17:11:03.588 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:11:03.853 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:12:13.646 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:12:13.647 DEBUG [HeartbeatService$a run] ❤️
12-16 17:12:13.711 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:12:13.985 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:12:41.065 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
12-16 17:12:51.115 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

12-16 17:12:51.123 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
12-16 17:13:07.658 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:13:07.658 DEBUG [HeartbeatService$a run] ❤️
12-16 17:13:07.705 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:13:07.991 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:13:58.751 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:13:58.752 DEBUG [HeartbeatService$a run] ❤️
12-16 17:13:58.829 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:13:59.121 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:15:09.323 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:15:09.329 DEBUG [HeartbeatService$a run] ❤️
12-16 17:15:09.392 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:15:09.653 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:15:15.587 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
12-16 17:15:25.603 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

12-16 17:15:25.605 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
12-16 17:16:00.065 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:16:00.066 DEBUG [HeartbeatService$a run] ❤️
12-16 17:16:00.109 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:16:00.368 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:16:56.949 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:16:56.949 DEBUG [HeartbeatService$a run] ❤️
12-16 17:16:56.979 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:16:57.244 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:17:57.695 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:17:57.696 DEBUG [HeartbeatService$a run] ❤️
12-16 17:17:57.734 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:17:58.011 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:18:35.452 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
12-16 17:18:45.464 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

12-16 17:18:45.466 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
12-16 17:18:57.792 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:18:57.793 DEBUG [HeartbeatService$a run] ❤️
12-16 17:18:57.809 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:18:58.067 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:19:04.644 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
12-16 17:19:14.691 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

12-16 17:19:14.695 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
12-16 17:20:00.128 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:20:00.129 DEBUG [HeartbeatService$a run] ❤️
12-16 17:20:00.188 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:20:00.462 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:23:31.886 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:23:31.887 DEBUG [HeartbeatService$a run] ❤️
12-16 17:23:31.970 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:23:32.225 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:23:33.522 INFO [c e] 
  🔵  LocationAuthorization: Requesting Background permission
12-16 17:23:33.523 INFO [c d] 
  🔵  Should show backgroundPermissionRationale? false
12-16 17:23:33.547 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
12-16 17:23:33.745 DEBUG [TSLocationManagerActivity execute] locationsettings
12-16 17:23:33.746 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
12-16 17:23:33.785 WARN [RNBackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
12-16 17:23:33.788 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [extras, notification, notification.text]
12-16 17:23:33.797 DEBUG [TSLocationManagerActivity stop] eventCount: 0
12-16 17:23:33.856 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

12-16 17:23:33.900 DEBUG [TSLocationManagerActivity onDestroy] 
12-16 17:23:38.353 INFO [TSScheduleManager oneShot] 
  ⏰ Oneshot TERMINATE_EVENT is already pending
12-16 17:23:38.826 DEBUG [BackgroundGeolocation a] 
  🔴  Cleared callbacks
12-16 17:23:38.826 DEBUG [BackgroundGeolocation a] 
  🔴  Cleared callbacks
12-16 17:23:38.829 INFO [BackgroundGeolocation$k0 run] 
╔═════════════════════════════════════════════
║ MainActivity was destroyed
╠═════════════════════════════════════════════
╟─ stopOnTerminate: false
╟─ enabled: true

12-16 17:23:38.847 DEBUG [BackgroundGeolocation a] 
  🔴  Cleared callbacks
12-16 17:23:43.570 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

12-16 17:23:43.571 DEBUG [BackgroundGeolocation isMainActivityActive] NO
12-16 17:23:43.572 DEBUG [HeadlessTask onHeadlessEvent] 💀  event: terminate
12-16 17:23:43.573 DEBUG [HeadlessTask$2 onHeadlessJsTaskStart] taskId: 1
12-16 17:23:43.576 DEBUG [HeadlessTask$2 onHeadlessJsTaskFinish] taskId: 1
12-16 17:24:02.215 DEBUG [AbstractService a] 
  🎾  HeartbeatService [eventCount: 1]
12-16 17:24:02.216 DEBUG [HeartbeatService$a run] ❤️
12-16 17:24:02.293 DEBUG [BackgroundGeolocation isMainActivityActive] NO
12-16 17:24:02.294 DEBUG [HeadlessTask onHeadlessEvent] 💀  event: heartbeat
12-16 17:24:02.295 DEBUG [AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
12-16 17:24:02.298 DEBUG [HeadlessTask$2 onHeadlessJsTaskStart] taskId: 2
12-16 17:24:02.299 DEBUG [HeadlessTask$2 onHeadlessJsTaskFinish] taskId: 2
12-16 17:24:02.565 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService destroyed
12-16 17:24:20.210 INFO [c e] 
  🔵  LocationAuthorization: Requesting Background permission
12-16 17:24:20.212 INFO [c d] 
  🔵  Should show backgroundPermissionRationale? false
12-16 17:24:20.259 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
12-16 17:24:20.504 DEBUG [TSLocationManagerActivity execute] locationsettings
12-16 17:24:20.504 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
12-16 17:24:20.528 DEBUG [TSLocationManagerActivity stop] eventCount: 0
12-16 17:24:20.556 WARN [RNBackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
12-16 17:24:20.561 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [extras]
12-16 17:24:20.578 DEBUG [TSLocationManagerActivity onDestroy] 
12-16 17:24:20.589 INFO [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

12-16 17:24:23.860 INFO [c f] 
  🔵  LocationAuthorization: Requesting permission
12-16 17:24:23.861 INFO [c$i onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted

**Comment by christocracy** [comment]
Do to *Settings->Applications->Your App->Permissions->Physical Activity*

**Comment by gaurav07june** [comment]
Tracking working fine on Android 10. I think this is Android 11 specific issue.

**Comment by christocracy** [comment]
I primarily develop on a *Pixel 3a @ 11*.  I always develop / test on the latest Android OS.

**Comment by gaurav07june** [comment]
I did it explicitly as I have mentioned. But It didn't ask for physical activity permission too.

**Comment by gaurav07june** [comment]
I know @christocracy that you would be doing testing on Latest Android version. And I have used latest SDK Version 3.9.3. and followed all the manual setting too. I don't know what causing this.

**Comment by gaurav07june** [comment]
await BackgroundGeolocation.setConfig({locationAuthorizationRequest: 'Always'});
let status = await BackgroundGeolocation.requestPermission();

I am asking for permission before BackgroundGeolocation.ready()

**Comment by christocracy** [comment]
Also, the plugin has a fallback mechanism using *stationary geofence* (like iOS) when *Physical Activity* permission is denied.  The device must most at least 200 meters before tracking engages.

I just did a fresh install of the SampleApp on *Pixel 3a @ 11*.  It successfully requests *Physical Activity Permission*.

![](https://dl.dropbox.com/s/k0dtprurhj6quce/physical-activity-permission.gif?dl=1)

**Comment by gaurav07june** [comment]
Initially I used compileSdkVersion = 30 targetSdkVersion = 30 which cause crash on Android 11. Currently using compileSdkVersion = 29 targetSdkVersion = 29 and no crash.
do you thing this issue might be related to this?

**Comment by gaurav07june** [comment]
googlePlayServicesLocationVersion = "17.0.0"  
googlePlayServicesVersion = "+"

this is the setting in build.gradle .

**Comment by gaurav07june** [comment]
> Also, the plugin has a fallback mechanism using _stationary geofence_ (like iOS) when _Physical Activity_ permission is denied. The device must most at least 200 meters before tracking engages.

And If I explicitly call BackgroundGeolocation.changePace(true). after BackgroundGeolocation.start(). will it engage the plugin in tracking?

**Comment by christocracy** [comment]
>Initially I used compileSdkVersion = 30 targetSdkVersion = 30 which cause crash on Android 11.

The [SampleApp uses `compileSdkVersion / targetSdkVersion 30`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/build.gradle#L10-L11)

The *SampleApp* has a `requestPermission` action in the popup menu that can be used to initially request-permission before `start()` -- *Physical Activity* permission is successfully requested.

https://dl.dropbox.com/s/5xecs16k5i2dlm4/physical-activity-requestPermission.gif?dl=0

**Comment by gaurav07june** [comment]
Thanks @christocracy for the support. I'll look into the issue following the sample app.

**Comment by gaurav07june** [comment]
> googlePlayServicesVersion = "+"
One last hit.
Is this ok to use?

**Comment by christocracy** [comment]
The plugin uses Gradle Config Var named [`googlePlayServicesLocationVersion`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-AUTO.md#open_file_folder-androidbuildgradle)

I wouldn't use version "+".  I'd set it to the latest available version, which is [17.1.0](https://maven.google.com/web/index.html#com.google.android.gms:play-services-location:17.1.0)

**Comment by gaurav07june** [comment]
Thank u very much
