### ISSUE TITLE
Disable local notifications

### ISSUE THREAD

**Issue by fatpig0416** [transistorsoft/react-native-background-geolocation#1198]
Hi, thanks for your plugin.
## Your Environment
* Plugin version: 3.9.3
* Platform: iOS and Android
* React Native version (`react-native -v`): 0.63.3
* 
## Expected Behavior
I want to disable all local notifications on both Android and iOS

## Actual Behavior
Currently, various local notifications are sometimes shown and this might make customers confused.

## Steps to Reproduce
Just start geo-fence service

Thanks

**Comment by christocracy** [comment]
You have neglected to provide the Plugin Config asked for in the issue template.

**Comment by fatpig0416** [comment]
reset: true,
  desiredAccuracy: BGGeoLocation.DESIRED_ACCURACY_NAVIGATION,
  distanceFilter: 10,
  geofenceInitialTriggerEntry: false,
  locationAuthorizationRequest: 'Always',
  stopTimeout: 30,
  pausesLocationUpdatesAutomatically: false,
  disableStopDetection: true,
  isMoving: true,
  stopOnStationary: true,
  debug: __DEV__,
  logLevel: BGGeoLocation.LOG_LEVEL_VERBOSE,
  autoSync: false,
  stopOnTerminate: false,
  startOnBoot: true,
  enableHeadless: true,


I apologize for my unclear report.
here is the config of your plug in

**Comment by christocracy** [comment]
Show me a screenshot of the notification for both Android / iOS that you're talking about.

**Comment by fatpig0416** [comment]
![image](https://user-images.githubusercontent.com/38931218/102510999-3b24cd00-40c3-11eb-8e06-164332ab8852.png)

**Comment by fatpig0416** [comment]
I want to turn off notifications even on iOS

**Comment by christocracy** [comment]
See API docs `Config.debug`

**Comment by fatpig0416** [comment]
Thanks
