### ISSUE TITLE
Getting a drift in location while tracking

### ISSUE THREAD

**Issue by gaurav07june** [transistorsoft/react-native-background-geolocation#1200]
* Plugin version: 3.9.3
* Platform:  Android
* OS version: 10
* Device manufacturer / model: samsung SM-A707F
* React Native version (`react-native -v`): 3.2.1
* Plugin config

let state = await BackgroundGeolocation.ready({
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 5,
locationAuthorizationRequest: 'Always',
backgroundPermissionRationale: {
title: "Allow to access this device's location even when closed or not in use.",
message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
positiveAction: 'Change to Allow all the time',
negativeAction: 'Cancel'
},
stopTimeout: 1,
debug: true,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
autoSync: true,
stopOnTerminate: false,
startOnBoot: true,
enableHeadless: true,
maxDaysToPersist: 14,
heartbeatInterval: 60,
logMaxDays: 1,
url : PRO_SYNC_URL,
autoSyncThreshold: 10,
batchSync: true,
method: "POST",
extras: {'imei': deviceInfo.uniqueId},
foregroundService: true,
notification: {
sticky: true,
title: "App Tracker",
text: "Your live trip is started.",
channelName: "App Tracker",
smallIcon: "mipmap/ic_notification",
largeIcon: "mipmap/ic_launcher",
priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH
}
});

## Context
While tracking I am getting a drift in locations. please see the image. What could be the reason and can I handle it with some setting in plugin.
![WhatsApp Image 2020-12-22 at 9 33 09 AM](https://user-images.githubusercontent.com/32128709/102847658-dc4fb280-4438-11eb-9ba6-1112853c1855.jpeg)

**Comment by christocracy** [comment]
Likely gps errors from the device due to the environment.

The plugin is only the messenger, delivering locations exactly as provided by the device's location api.

**Comment by christocracy** [comment]
When you look at those poor locations, you will likely find a correspondingly poor `location.coords.accuracy` (eg: `1000`).

**Comment by gaurav07june** [comment]
Thanks for your support . It is helpful.
