### ISSUE TITLE
 I have a problem in your library, because it is giving some straight lines and crossing guards and taking too long to start the transmission with the server!

### ISSUE THREAD

**Issue by otonielloliveira** [transistorsoft/react-native-background-geolocation#1202]
## Your Environment
* Plugin version:3.9.3
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
async configureBackgroundGeolocation() {
    let token = await getTokenFromStorage();

    // Step 1:  Listen to events:
    BackgroundGeolocation.onLocation(this.onLocation.bind(this));
    BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
    BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));

    // Step 2:  #configure:
    BackgroundGeolocation.ready(
      {
        reset: true,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
        activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
        distanceFilter: 10,
        startOnBoot: true,
        stopTimeout: 1,
        forceReloadOnLocationChange: true,
        allowIdenticalLocations: true,
        desiredOdometerAccuracy: 5,
        useSignificantChangesOnly: true,
        locationTemplate:
          '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"created_at_gps":"<%= timestamp %>","speed":<%= speed %>,"odometer":<%= odometer %>,"is_moving":<%= is_moving %>,"type":"<%= activity.type %>","confidence":<%= activity.confidence %>,"level":<%= battery.level %>,"is_charging":<%= battery.is_charging %>,"mock":<%= mock %>,"timestamp":"<%= timestamp %>","accuracy": <%= accuracy %>}',
        extras: {
          worked_route_id: this.state.route.worked_route.id,
          status: 0,
        },
        headers: {
          Authorization: `bearer ${token}`,
        },

        url: 'API URL',
        method: 'POST',
        stopOnTerminate: false,
        httpRootProperty: 'location',
        notification: {
          title: 'O serviço de geolocalização está ativado',
          text: 'O serviço de geolocalização está ativado',
        },
        autoSync: true,
        autoSyncThreshold: 5,
        batchSync: false, // <-- Set true to sync locations to server in a single HTTP request.
      },
      (state) => {
        if (!state.enabled) {
          BackgroundGeolocation.start();
          this.setState({
            enabled: state.enabled,
            isMoving: state.isMoving,
            showsUserLocation: state.enabled,
          });
        }
      },
    );
  }
```

## Actual Behavior

![image](https://user-images.githubusercontent.com/12397172/103370190-ee6dc880-4aaa-11eb-8efb-313eb34ecfce.png)

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/12397172/103370132-c41c0b00-4aaa-11eb-941d-45dfa3792d2a.png)

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Do not ignore the issue template:

>Platform: iOS or Android
>OS version:
>Device manufacturer / model:

**Comment by christocracy** [comment]
I see nothing wrong with your maps.  Those locations are extremely close.  Go for a *long* field-test of several kilometers.

**Comment by otonielloliveira** [comment]
Platform: Android
OS version:
Device manufacturer / model: J7 - Prime - Android : > 10

![image](https://user-images.githubusercontent.com/12397172/103370584-ebbfa300-4aab-11eb-93b7-8ad4e3f24ed9.png)
![image](https://user-images.githubusercontent.com/12397172/103370629-07c34480-4aac-11eb-8b2f-6b7052920059.png)

**Comment by christocracy** [comment]
Your top image is meaningless to me without showing individual points.  I suggest you test against the dev server at http://tracker.transistorsoft.com (See API docs [Config.transistorAuthorizationToken](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#transistorauthorizationtoken)

![](https://www.dropbox.com/s/dtyk41oo1ikjbax/Screen%20Shot%202020-12-30%20at%2012.41.12%20PM.png?dl=1)

Your second image was likely from using mocked location, where the location constantly flips back and forth between mock location and real GPS.

**Comment by christocracy** [comment]
If by model *J7*, you mean [Samsung J7](https://www.gsmarena.com/samsung_galaxy_j7_(2016)-7870.php), these budget device are missing important sensors *Gyroscope* and *Magnetometer* (they only have an accelerometer).  These device are not ideal for location-tracking.  The *Samsung J7* is not a good device for development.
