### ISSUE TITLE
Help with http request modification 

### ISSUE THREAD

**Issue by bajjajjrajjesh** [transistorsoft/react-native-background-geolocation#1204]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS 
* OS version: 14.2
* Device manufacturer / model: iPhone X 
* React Native version (`react-native -v`): 0.59
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

BackgroundGeolocation.ready(
    {
      url: `${servicesConfig.api.webUrl}/driverlocations`,
      autoSync: true,
      scheduleUseAlarmManager: true,
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      stopTimeout: 5,
      headers: {
        AUTHORIZATION: this.props.getJWTHeader
      },
      params: {
        tripId: trip_id,
        driverId: driver_id,
        platform:Platform.OS
      },
      locationsOrderDirection: "DESC",
      maxDaysToPersist: 14,

      locationAuthorizationAlert: {
        titleWhenNotEnabled: "Your location settings need updating",
        titleWhenOff: "Your location settings need updating",
        instructions: "Please set your TruckTracker location settings to “Always”. This optimises the app’s ability to track the truck. Remember, your location is only being recorded whilst a trip is in progress.",
        cancelButton: "Cancel",
        settingsButton: "Settings"
      },//<~ For IOS only
      showsBackgroundLocationIndicator:true,//<~ For IOS only
      locationAuthorizationRequest: 'Always',// <~ For IOS only
      debug: false,
      enableHeadless: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
      notification: {
        sticky: true,
        title: ' App Tracking',
        text: 'Your live trip is started.',
        channelName: 'App Tracker',
        smallIcon: 'mipmap/ic_notification', // <-- defaults to app icon
        largeIcon: 'mipmap/ic_launcher',
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
      },
    })
```

## Expected Behavior

During http request of location which are sent to my server, I want some modification done. 

Basically when the app is killed and user device location is collected in server I want to turn off background location services based on specific response from the api. I need help with that where and how can I make that change. 

I also want to make sure hollow purple location icon isn’t shown in privacy setting when background location is turned off. 
## Actual Behavior

We are unable to turn off background location when app is killed in ios. 

When background location is turned off hollow purple location is shown sometimes 
## Steps to Reproduce

1.
2.
3.
4.

## Context

I want to make sure location is tracked only and only when we have an active trip. 
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See the api docs "HTTP Guide".  Search that page for "RPC".

**Comment by bajjajjrajjesh** [comment]
In the api where location is sent in that I am sending response as follow yet location service is not getting turned off\

{
  "background_geolocation": [
    ["stop"]
  ]
}

**Comment by christocracy** [comment]
You're saying that iOS does not stop recording locations and uploading to your server?

**Comment by bajjajjrajjesh** [comment]
So ios stop sending location to the server but it keeps tracking the location and in the privacy setting if iPhone it shows me purple arrow which states that location is tracked.

**Comment by christocracy** [comment]
What makes you think the plugin continues to track the location if locations stop being uploaded?

**Comment by christocracy** [comment]
If you are using a `Config.schedule`, iOS continues to monitor the *"Significant Location Changes"* API, which records a location about every 1000 meters.  The iOS scheduler needs this in order to periodically evaluate the schedule.  This will result in the "Hollow purple icon" while the plugin is stopped with an active schedule.

**Comment by christocracy** [comment]
If you want to completely stop the scheduler, you must call `.stopSchedule()`.
