### ISSUE TITLE
heartbeat event doesn't fire regulary

### ISSUE THREAD

**Issue by katalityk00** [transistorsoft/react-native-background-geolocation#1206]
With some device heartbeat event doesn't fire every ``hearbeatInterval`` seconds.

## Your Environment
* Plugin version: 3.9.3
* Platform:  Android
* OS version:
* Device manufacturer / model: **Samsung a20e** & **Xiaomi pocophone f1**
* React Native version (`react-native -v`): 0.63.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: true,
  startOnBoot: false,
  heartbeatInterval: 70, 
  foregroundService: true,
  forceReloadOnBoot: false,
  forceReloadOnMotionChange: false,
  forceReloadOnLocationChange: false,
  forceReloadOnGeofence: false,
  forceReloadOnHeartbeat: false,
  enableHeadless: false, 
```

## Expected Behavior

Heartbeat event fire every 70 secs in when the device activity is ``STILL``

## Actual Behavior

In some case, apparently depending on the device the heartbeat events does not fire every 70.

For my Xiaomi some times heartbeat will miss some timing.
For my Samsung it seems to can't fire more other than every 5 mins.
## Steps to Reproduce

1.
2.
3.
4.

## Context

I need to fire the heartbeat event as frequently as I can (I've tried with 60 and 600 and) I come to the same conclusion. When the heartbeat is frequent it seems to fire more randomly.
I've used already https://dontkillmyapp.com/ to try to fix this.
It's may be normal. but what can I do to make it work perfectly.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
There's nothing you can do.  You are at the mercy of the device manufacturer.  Heartbeat can consume a lot of power over time with frequent wakeups.
