### ISSUE TITLE
Heartbeat event doesn't getting called in case of stationary location when app is killed.

### ISSUE THREAD

**Issue by Reenagrg100** [transistorsoft/react-native-background-geolocation#1208]
## Your Environment
* Plugin version: react-native-background-geolocation": "3.9.3" & react-native-background-fetch": "3.0.6"
* Platform: iOS and android
* OS version: 13.5
* Device manufacturer / model: iPhone SE (2nd gen)
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
export const configureBackgroundGeoLocation = () => {
  BackgroundGeolocation.ready(
    {
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: stores.locationStore.fetchRadius || 10, //distance required for getting location update        // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      locationAuthorizationRequest: 'Always',
      heartbeatInterval: 60,
      preventSuspend: true, //required for heartbeat event for ios,
      foregroundService: true,
    },
    state => {
      LOGGER.log(
        '- BackgroundGeolocation is configured and ready: ',
        state.enabled,
      );

      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          LOGGER.log('- Start success');
        });
      }
    },
  );

BackgroundGeolocation.on('location', location => {
    console.log('On location:', location);
    location && getLocationInputAndSave(location);
  });

  /**
   * this will get called whenever it has been elapsed 1 min and device is sationary i.e there is no change in location from last 1min
   */
  BackgroundGeolocation.onHeartbeat(event => {
    // You could request a new location if you wish.

    BackgroundGeolocation.getCurrentPosition({
      samples: 1,
      persist: true,
    }).then(location => {
      console.log('On heartbeat:', location);
      // location && getLocationInputAndSave(location);
    });
  });
```

## Expected Behavior

We should get stationary data by calling the heartbeat event even if the app is killed. 

## Actual Behavior

We are not getting stationary data when the app is killed although we are getting it when the app is in foreground or background state. 

## Steps to Reproduce

1. 
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Reenagrg100** [comment]
Hey @bajjajjrajjesh by chance did you face this kind of issue ever? I was seeing you have also opened another issue.

**Comment by bajjajjrajjesh** [comment]
Hi @Reenagrg100 I don't think I ever faced this issue. My question is why you want to get stationary data

**Comment by Reenagrg100** [comment]
Thanks, @bajjajjrajjesh for getting back. Actually, my scenerio is something like that we are getting location updates based on distance filter( if a user is moving) and based on time (if a user is stationary). We want continuous data. I know in the case of stationary it will keep giving us the last fetched location till the time user changes his location only the timestamp will get changed here.

**Comment by Reenagrg100** [comment]
Also, I'm not getting even moving data on android when the app is been killed. Any thoughts on it @bajjajjrajjesh?

**Comment by bajjajjrajjesh** [comment]
Is your app working when in foreground?

You can take a look at this

```
distanceFilter: stores.locationStore.fetchRadius || 10, 
```

I am not sure but you may consider changing this to 

```
distanceFilter: 10, 
```

Additionally I am not using heartbeat for iOS, I left it on its default option what ever it is

If it still doesn't work I will share you a config to see if that works for you

**Comment by bajjajjrajjesh** [comment]
@Reenagrg100 you should reach @christocracy for your issue as he is the best person to answer any of your question.

**Comment by Reenagrg100** [comment]
Yeah, I'm getting proper data in both foreground and background and on iOS even in the killed state but not on android. Although, on iOS it takes 3-4 mins when the app goes to killed state in providing the next location updates. Did you also notice the same? But that's okay. 
But on android, it's not providing at all even I waited for 10-15 mins. 

**distanceFilter: stores.locationStore.fetchRadius || 10,** 

No, that's not an issue, it's only I'm picking distance radius from the store and have kept 10 as default.

**Comment by Reenagrg100** [comment]
> @Reenagrg100 you should reach @christocracy for your issue as he is the best person to answer any of your question.

For sure thanks, I'm waiting for him to reply.

**Comment by Reenagrg100** [comment]
> Is your app working when in foreground?
> 
> You can take a look at this
> 
> ```
> distanceFilter: stores.locationStore.fetchRadius || 10, 
> ```
> 
> I am not sure but you may consider changing this to
> 
> ```
> distanceFilter: 10, 
> ```
> 
> Additionally I am not using heartbeat for iOS, I left it on its default option what ever it is
> 
> If it still doesn't work I will share you a config to see if that works for you

Got it man @bajjajjrajjesh , I needed to add enableHeadless:true in my config for android and I missed that. Got to know from https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode.

**Comment by Reenagrg100** [comment]
Hey @christocracy the issue which I have opened doesn't get solved yet. I was talking about the other issue above. Can you please help me with the issue which I have opened. ?

**Comment by christocracy** [comment]
iOS cannot fire the heartbeat event when the app is terminated.  When an iOS app is terminated, everything stops.  iOS has no such concept of *"Headless"* as Android does.

**Comment by christocracy** [comment]
on iOS, your app *will* automatically relaunch when the device moves ~200 meters, and tracking *will* resume.

**Comment by Reenagrg100** [comment]
Okay, so there is no way to get stationary location updates on iOS based on heartbeat interval? Any other way?

**Comment by christocracy** [comment]
>Okay, so there is no way to get stationary location updates on iOS based on heartbeat interval? 

When  the app is **terminated**, no -- It's impossible.

>Any other way?

No.  It's impossible.

**Comment by Reenagrg100** [comment]
Also, I'm using headless mode in android but little as it also emits "heartbeat" event as heartbeat interval does. So, how can we implement both. 

As we need to register a headless task to get updates in headless mode. But, it will be working only in the killed state, then how I get location updates in the foreground and background updates based on heartbeat interval? 



let BackgroundGeolocationHeadlessTask = async event => {
  let params = event.params;
  console.log('headless task');
  console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);

  switch (event.name) {
    case 'heartbeat':
      // Use await for async tasks
      let location = await BackgroundGeolocation.getCurrentPosition({
        samples: 1,
        persist: false,
      });
      console.log(
        '[BackgroundGeolocation HeadlessTask] - getCurrentPosition:',
        location,
      );
      break;
  }
};

BackgroundGeolocation.registerHeadlessTask(BackgroundGeolocationHeadlessTask);

**Comment by christocracy** [comment]
- When your *Android* app is alive (either foreground or background), your `hearbeat` event arrives here:

```javascript
BackgroundGeolocaiton.onHeartbeat((event) {
  console.log('[heartbeat]', event);
});

- When your *Android* app is terminated, your `heartbeat` events (and all events) arrive in your registered headless-task.

An Android app has 3 states:
- foreground
- background
- terminated.

"Headless" = terminated.

**Comment by Reenagrg100** [comment]
Got it. Thanks a lot for explaining it. @christocracy.

**Comment by Reenagrg100** [comment]
I'll try and if it works successfully then will close the issue.

**Comment by Reenagrg100** [comment]
I'm also seeing that heartbeat interval working fine in iOS but on android when the app goes to the background, it provides updates only for 5-6 mins if my heartbeat interval is 60secs, and after that **onHeartbeat** stops calling. and in the foreground for one heartbeat interval, I'm getting multiple updates( duplicate data)

**Comment by Reenagrg100** [comment]
<img width="1043" alt="Screenshot 2021-01-08 at 3 48 22 PM" src="https://user-images.githubusercontent.com/59276080/104045657-e7f6f380-5204-11eb-9765-3ed1f3b2cefb.png">

and sometimes I also got this error in OnLocation callback in case of heartbeat event.

**Comment by Reenagrg100** [comment]
<img width="863" alt="Screenshot 2021-01-08 at 3 53 05 PM" src="https://user-images.githubusercontent.com/59276080/104045909-402df580-5205-11eb-89e8-de488e8b5533.png">

You can also follow this one to see the **timestamp** of all the updates.

**Comment by christocracy** [comment]
You're aware that the location provided to heartbeat event is simply the last known location?  It is the same location provided to each fired event.  The plugin does *not* turn on location services to fetch a new location with each event.  This is documented in the api docs for then onHeartbeat event.

If you want a fresh location, see api docs `getCurrentPosition`.

**Comment by Reenagrg100** [comment]
I know but the heartbeat event doesn't getting called correctly. location would remain the same but **timestamp** will be changed. We need stationary updates as well. Also, I'm seeing 408 error many times when app is in background state. Why so? @christocracy

**Comment by Reenagrg100** [comment]
> * When your _Android_ **or** _iOS_ app is alive (either foreground or background), your `hearbeat` event arrives here:
> 
> ```js
> BackgroundGeolocaiton.onHeartbeat((event) {
>   console.log('[heartbeat]', event);
> });
> ```
> 
> * When your _Android_ app is terminated, your `heartbeat` events (and all events) arrive in your registered headless-task.
> 
> An Android app has 3 states:
> 
> * foreground
> * background
> * terminated.
> 
> "Headless" = terminated.

hey, @christocracy I just tested it in the same way as you explained to me but I'm seeing these kinds of logs in the killed state based on distance filter. 
First thing, it's not going to the headless mode as it should be.
Secondly, it's throwing some internal error "mutation...". 


<img width="991" alt="Screenshot 2021-01-08 at 11 29 09 PM" src="https://user-images.githubusercontent.com/59276080/104048505-50e06a80-5209-11eb-8759-c9f76cb0916c.png">

**Comment by christocracy** [comment]
The plugin has nothing to do with *GraphQL*.
