### ISSUE TITLE
Crashes in Android with large Geofences

### ISSUE THREAD

**Issue by tharakanwn2014** [transistorsoft/react-native-background-geolocation#1209]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Ulefone / X
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE


      BackgroundGeolocation.onLocation(
        (location) => {
          onChangeLocation(location);
        },
        (error) => {
          console.log('[location] ERROR: ', error);
        },
      );

   BackgroundGeolocation.ready(
        {
          // Geolocation Config
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 5,
          // Activity Recognition
          stopTimeout: 1,
          stopOnStationary: false,
          stationaryRadius: 1,
          allowIdenticalLocations: true,
          locationUpdateInterval: 1000,

          // Application config
          debug: true, // <-- enable this hear debug sounds.
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: false, // <-- Allow the background-service to continue tracking when app terminated.
          startOnBoot: true, // <-- Auto start tracking when device is powered-up.
          // HTTP / SQLite config
          url: '<server url >',
          batchSync: false, // <-- Set true to sync locations to server in a single HTTP request.
          autoSync: true, // <-- Set true to sync each location to server as it arrives.
          headers: {
            // <-- Optional HTTP headers
            Authorization: 'Bearer ' + token,
            Accept: 'application/json',
          },
          params: {
            // <-- Optional HTTP params
          },
        },
        (state) => {
          console.log(
            '- BackgroundGeolocation is configured and ready: ',
            state.enabled,
          );

          if (!state.enabled) {
            ////
            // 3. Start tracking!
            //
            BackgroundGeolocation.start(function () {
              console.log('- Start success');
            });
          }
        },
      );

BackgroundGeolocation.addGeofences(geoFences); //number of geoFences around 20,000
```
## Expected Behavior

Should work on Android without crashing after a few seconds

## Actual Behavior

Crashing Android app after few seconds of loading 

## Steps to Reproduce

1.
2.
3.
4.

## Context

Trying to load about 20,000 geofences 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
01-08 14:14:44.891  5823  5892 I TSLocationManager:   ✅  671264
01-08 14:14:44.895  5823  5892 I TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
01-08 14:14:44.895  5823  5892 I TSLocationManager:   ✅  670050
01-08 14:14:44.898  5823  5892 I TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
01-08 14:14:44.898  5823  5892 I TSLocationManager:   ✅  66010848
01-08 14:14:44.902  5823  5892 I TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
01-08 14:14:44.902  5823  5892 I TSLocationManager:   ✅  71010468
01-08 14:14:44.905  5823  5892 I TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
01-08 14:14:44.905  5823  5892 I TSLocationManager:   ✅  191051
01-08 14:14:44.907  5823  5892 I TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
01-08 14:14:44.907  5823  5892 I TSLocationManager:   ✅  191935
01-08 14:14:44.908  5823  5892 W libc    : pthread_create failed: clone failed: Try again
01-08 14:14:44.909  5823  5892 W zygote64: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
01-08 14:14:44.917  5823  5892 W libc    : pthread_create failed: clone failed: Try again
01-08 14:14:44.917  5823  5892 W zygote64: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
01-08 14:14:44.926  5823  5892 W libc    : pthread_create failed: clone failed: Try again
01-08 14:14:44.926  5823  5892 W zygote64: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
01-08 14:14:44.928  5823  5892 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
01-08 14:14:44.928  5823  5892 E AndroidRuntime: Process: io.testxyz.xyz, PID: 5823
01-08 14:14:44.928  5823  5892 E AndroidRuntime: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
01-08 14:14:44.928  5823  5892 E AndroidRuntime:        at java.lang.Thread.nativeCreate(Native Method)
01-08 14:14:44.928  5823  5892 E AndroidRuntime:        at java.lang.Thread.start(Thread.java:733)
01-08 14:14:44.928  5823  5892 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
01-08 14:14:44.928  5823  5892 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1038)

</details>

**Comment by christocracy** [comment]
>Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: 

20k geofences *is* pretty extreme.

**Comment by tharakanwn2014** [comment]
Actually, I need to use 100000 geofences. do you have any suggestions?

**Comment by christocracy** [comment]
Your device is running out of memory.  Add more memory?

> I need to use 100000 geofences. do you have any suggestions?

I suggest you don't.  I suggest you add only a small subset of geofences based upon the current location of the device.

**Comment by tharakanwn2014** [comment]
Ok thank you
