### ISSUE TITLE
Not able to receive any location updates unless ChangePace is set to true

### ISSUE THREAD

**Issue by ckrc** [transistorsoft/react-native-background-geolocation#1210]
## Your Environment
* Plugin version:  3.9.1
* Platform: Android
* OS version:  9
* Device manufacturer / model: Samsung Galaxy s8
* React Native version (`react-native -v`):  0.63.2
* Plugin config
```
      BackgroundGeolocation.ready({
          triggerActivities: "on_foot, walking, running",
          // Geolocation Config
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 0,
          locationUpdateInterval: 2000,
          // Activity Recognition
          stopTimeout: 2,
          // Application config
          debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
          startOnBoot: false, 
        }, (state) => {
      // alert('BackgroundGeolocation started successfully.');  
      console.log('BackgroundGeolocation started successfully.');
    });
```

## Expected Behavior
This is for a walk tracking app and when tracking starts, it should receive location data every 2 seconds (based on the config above) and updates the map to show the walked route. 

## Actual Behavior
Calling ```BackgroundGeolocation.start()``` does not seems to trigger the location service at all (at the office with WIFI / outside with 4g) or at least not immediately and get no location updates 99% of the time. However, it happened a few times in the past where the location service did start after walking for a little while (>2 mins i think) but most of time the location does not trigger.  

At the end I found that I have to call ```BackgroundGeolocation.changePace(true)``` to make the phone's location service to start working reliably and it does work every time. 

However, it creates another problem. 
When the location service is first started, the location data received does not seem to be accurate as the phone is actually stationary (at the office with WIFI connection) but the app keeps receiving location data randomly (at surrounding areas) which causes my mobile app to draw the inaccurate routes 

## Steps to Reproduce

1.
2.
3.
4.

## Context
A walking app to show the walked route on the map.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

Please help and happy to purchase the license if I can make it to work reliably (at lease for this DEV / TEST phone)

**Comment by christocracy** [comment]
Are you observing `$ adb locat *:S TSLocationManager:V`?  See wiki *Debugging*.

While observing `logcat`, shake your device vigorously to observe the motion API output.

**Comment by ckrc** [comment]
Thanks @christocracy 
I will give this a try and report here later
