### ISSUE TITLE
Promise<Location> for BackgroundGeolocationMock.getCurrentPosition doesn't seem to work

### ISSUE THREAD

**Issue by PauliusLiekis** [transistorsoft/react-native-background-geolocation#1211]
## Your Environment
* Plugin version: 3.9.3
* Platform: iOS
* OS version: 13.4.1
* Device manufacturer / model: iPhone7+
* React Native version (`react-native -v`): react-native-cli: 2.0.1, react-native: 0.62.2

## Expected Behavior
```javascript
const res = await BackgroundGeolocation.getCurrentPosition(
      { maximumAge: 5000 },
      (location) => { console.log("callback: ", location); },
      (error) => {}
);
console.log("promise", res);
```

This should log:
```
callback: { coords: ..., etc }
promise: { coords: ..., etc }
```

## Actual Behavior
It logs:
```
promise: undefined
callback: { coords: ..., etc }
```
so I'm actually surprised by the order.

## Steps to Reproduce

Just try using both callback and promise of `getCurrentPosition`. Do both of them work as expected?

Actually even without await  `BackgroundGeolocation.getCurrentPosition` returns `undefined` and not a `Promise` object.

## Context
Use API according to the Typescript definitions.

**Comment by christocracy** [comment]
You're not using the API correctly.  The `Promise` API was implemented relatively recently and in order to be backwards compatible with the existing API, the Javascript code counts `arguments` supplied to the method.

To use the `Promise` API, you supply just one `Options` argument.

```javascipt
try {
  let location = await BackgroundGeolocation.getCurrentPosition(options);
  console.log('[getCurrentPosition] succes: ', location);
} catch (error) {
  console.warn('[getCurrentPosition] error: ', error);
}
```

**Comment by PauliusLiekis** [comment]
> You're not using the API correctly. The Promise API was implemented relatively recently and in order to be backwards compatible with the existing API, the Javascript code counts arguments supplied to the method.

I suspected that, but I couldn't find any mention of this in the docs. Then the real issue is that the type definitions for the API are wrong. It's supposed to be something like this if you don't want to confuse the developers:

```
static getCurrentPosition(options: CurrentPositionRequest, success:(location:Location) => void, failure?:(errorCode:LocationError) => void): void;
static getCurrentPosition(options: CurrentPositionRequest): Promise<Location>;
```

Also, the detection seems to be done based on the argument count instead of the contents of the arguments, i.e. I can not wrap your function like this:

```
  static async getCurrentPositionWrap(
    options: CurrentPositionRequest,
    success?: (location: Location) => void,
    failure?: (errorCode: LocationError) => void
  ) {
    return BackgroundGeolocation.getCurrentPosition(
      options,
      success,
      failure
    );
  }
```

as it seems to hit the wrong API, when I do a call like this: `getCurrentPositionWrap(options)`.

**Comment by christocracy** [comment]
If you want to "wrap" the plugin's API and you want to use `Promise`, just *forget about* the 2nd and 3rd args (`success?` and `failure?`).

**Comment by christocracy** [comment]
```javascript
static async getCurrentPositionWrap(
    options: CurrentPositionRequest
  ) {
    return BackgroundGeolocation.getCurrentPosition(
      options
    );
  }
```

It seems pointless to wrap that now.

**Comment by PauliusLiekis** [comment]
Sure, I understand that. 

I'm just saying that your API definitions are wrong. For example, I make this sort of call:

`const res: Promise<Location> = BackgroundGeolocation.getCurrentPosition(options, success);`

The Typescript gives 0 errors, when in fact the type of `res` is not `Promise`, it's `void` and this should not compile.

**Comment by christocracy** [comment]
It's unfortunate but a difficult problem to solve while maintaining backwards compatibility.  We're fortunate I was able to bolt-on a Typescript API at all, an API that is shared verbatim between both the Cordova and React Native versions of the plugin.  it was a lot of work.

**Comment by PauliusLiekis** [comment]
So yeah, I'm saying this would do the trick, i.e. you can have multiple function overloads in the definitions with the correct return types:
```
static getCurrentPosition(options: CurrentPositionRequest, success:(location:Location) => void, failure?:(errorCode:LocationError) => void): void;
static getCurrentPosition(options: CurrentPositionRequest): Promise<Location>;
```

Anyway, I understand that it's a lot of hassle to duplicate every method and documentation for it that returns a promise! and also maintain that afterwards... So no worries :)

**Comment by christocracy** [comment]
The Typescript API is only a thin layer of ice on the exposed portion of the tip of the iceberg (the iOS / Android RN native portion of the plugin).  Most of the action occurs below the surface in the pure native iOS (`TSLocationManager.framework`) / Android (`tslocationmanager.aar`) libraries, which are shared between all 3 version of the plugin (*Cordova, React Native, Flutter*).  I like to avoid messing with that thin layer of Javascript API.

![](https://dl.dropbox.com/s/yugvfwuvi04getw/Screen%20Shot%202021-01-12%20at%2010.50.14%20AM.png?dl=1)
