### ISSUE TITLE
Get Current Location

### ISSUE THREAD

**Issue by olegbraginmmc** [transistorsoft/react-native-background-geolocation#1213]
## Your Environment
* Plugin version: latest
* Platform: iOS and Android
* OS version: iOS 14, Android 9/10/11
* Device manufacturer / model: Apple / Samsung
* React Native version (`react-native -v`): latest
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Call a method to grab current location

## Actual Behavior

Wasn't able to find such a method

## Steps to Reproduce

1.
2.
3.
4.

## Context

We have 2 geo location libs in the app, one for background tracking, one is used to get current location. We want to use only transistorsoft lib for both. Is it possible? 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs BackgroundGeolocation.getCurrentPosition
