### ISSUE TITLE
Is it possible to detect user is driving or walking?  

### ISSUE THREAD

**Issue by davitN** [transistorsoft/react-native-background-geolocation#1214]
I want to detect what is the activity type of the user and send it to the server (driving walking...)
I couldn't find the way. thanks.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The `activity` information is appended to each recorded location.

You can also get this information by listening to the event `onActivityChange`.
