### ISSUE TITLE
Getting how closer to the closest Geofence

### ISSUE THREAD

**Issue by tharakanwn2014** [transistorsoft/react-native-background-geolocation#1215]
## Your Environment
* Plugin version:3.9.3
* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Context

Is there a way to get the distance to the closest geofence with the plugin?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
There is no built-in method for this.  I suggest you listen to event `onGeofencesChange` to receive the list of currently monitored geofences (max 20 for iOS; 100 for Android).  Iterate through this list and calculate distance yourself.

**Comment by Seodiddy** [comment]
ok thank you
