### ISSUE TITLE
Latitude and longitude are not getting updated every time

### ISSUE THREAD

**Issue by haresh12** [transistorsoft/react-native-background-geolocation#1219]
## Your Environment
* Plugin version:3.9.4
* Platform: Android
* OS version:8
* Device manufacturer / model: Samsung galaxy A50
* React Native version (`react-native -v`): 0.60
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  BackgroundGeolocation.ready({
           desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 20,  // added this and removed locationupdateinterval propertity
            disableElasticity : false,
            allowIdenticalLocations: false,
            stopOnTerminate: false,
            stopTimeout:25,
            startOnBoot: true,
            url: "my server url",
            params: {
                "orderId": "j07dWwydVo1zKp_nSokV1NzsxucADKS7wUI2T039",
            },
            headers: {
                "authorization": "Bearer xyz",
            },
            autoSync: true,
            foregroundService: true,
            preventSuspend: true,
            debug: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
        }, (state) => {
            console.log('- Configure enabled: ', state.enabled);
            console.log('- Configure isMoving: ', state.isMoving);
            setEnabled(state.enabled)
            setIsMovig(state.isMoving)
        });
    }
```

## Expected Behavior

It should be update new lat-lng every 15 sec. (Because all the time i was on moving state)
## Actual Behavior

 Not updating location every 15 sec.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
{"_id":"j07dWwydVo1zKp_nSokV1NzsxucADKS7wUI2T039","__v":0,"createdAt":"2021-01-20T12:59:48.595Z","lat":23.07889,"lng":72.6467784,"updatedAt":"2021-01-20T13:12:18.614Z"},{"_id":"j07dWwydVo1zKp_nSokV1NzsxucADKS7wUI2T039","__v":0,"createdAt":"2021-01-20T12:59:48.595Z","lat":23.07889,"lng":72.6467784,"updatedAt":"2021-01-20T13:12:33.653Z"},{"_id":"j07dWwydVo1zKp_nSokV1NzsxucADKS7wUI2T039","__v":0,"createdAt":"2021-01-20T12:59:48.595Z","lat":23.07889,"lng":72.6467784,"updatedAt":"2021-01-20T13:12:48.798Z"},{"_id":"j07dWwydVo1zKp_nSokV1NzsxucADKS7wUI2T039","__v":0,"createdAt":"2021-01-20T12:59:48.595Z","lat":23.0811102,"lng":72.648338,"updatedAt":"2021-01-20T13:13:03.746Z"},{"_id":"j07dWwydVo1zKp_nSokV1NzsxucADKS7wUI2T039","__v":0,"createdAt":"2021-01-20T12:59:48.595Z","lat":23.0811102,"lng":72.648338,"updatedAt":"2021-01-20T13:13:24.585Z"},{"_id":"j07dWwydVo1zKp_nSokV1NzsxucADKS7wUI2T039","__v":0,"createdAt":"2021-01-20T12:59:48.595Z","lat":23.0833304,"lng":72.6498975,"updatedAt":"2021-01-20T13:13:39.348Z"},{"_id":"j07dWwydVo1zKp_nSokV1NzsxucADKS7wUI2T039","__v":0,"createdAt":"2021-01-20T12:59:48.595Z","lat":23.0833304,"lng":72.6498975,"updatedAt":"2021-01-20T13:13:54.518Z"},
```

</details>

**Comment by christocracy** [comment]
>Not updating location every 15 sec.

- How often *is* it updating?  See `Config.locationUpdateInterval`
- See Wiki *Debugging*.  Learn to observe logs from the plugin.

**Comment by haresh12** [comment]
See locationupdateinterval update location in every 15sec no issue with that but what I am saying I was in moving state and crossed almost 3 4 km and I location was triggered in every 15 sec but in location objects almost all the location where same you can see the log. See these are the real number I traveled 15km got almost 55 locations but from those 55 if we fillter duplicate then hardly 8 to 9 location and I don’t know what’s wrong with my code.

**Comment by christocracy** [comment]
In the Config you've provided above, you have **not** set locationUpdateInterval.  You set *fastestLocationUpdateInterval*.

**Comment by christocracy** [comment]
It's always better to use *distance-based* tracking rather than time-based.  It consumes less energy.  Also, iOS doesn't even support time-based location updates.

**Comment by christocracy** [comment]
>and I don’t know what’s wrong with my code.

There is no problem with your code.  It's more likely device-related.  I suggest you gather logs from your device.  See Wiki *Debugging* and gather logs with `emailLog` method.

**Comment by haresh12** [comment]
Ok i was using time based tracking because we only need this library for android but as you said distance based is good approach to go with so i changed code as you can see in above code section. So now i should get location in every 20 meter distance and then i downloaded lockito for mock location and it almost worked like i am getting location as expected. But only question i have right now is when we use library url property then library send lat-lng to server by it self so which location this url is going to send is it going to be most accurate. Because when we are using onLocation callback we are getting many samples and those samples are not at all accurate(even some time 5 to 6 km difference) .So could you please tell me with this url which location going to be sent to server.Are this url also going to send the samples to the server?
 If you're manually POSTing location to your server, you should ignore these locations. (this is what you have mentioned in 
 document and that's why we decided to go with url where library send lat-lng by it self). Please help me out with this.

**Comment by christocracy** [comment]
The plugin's built-in HTTP service does *not* post location where `location.sample == true`.

**Comment by haresh12** [comment]
So can I go ahead with above code and purchase key because I tried almost everything and this one seems to work.Let me know if any suggestions because task is quite simple like just send accurate lat-lng to server.

**Comment by christocracy** [comment]
>So can I go ahead with above code and purchase

Yes.

Your config is is set to best possible location results.
