### ISSUE TITLE
Library does not update location on Android

### ISSUE THREAD

**Issue by joaonnetonunes** [transistorsoft/react-native-background-geolocation#1222]
## Your Environment
* Plugin version:  3.8.1
* Platform: Android
* OS version:  10
* Device manufacturer / model: Xiaomi MI a3
* React Native version (react-native -v):  0.62.2
* Plugin config
javascript 
debug: false,
        reset: true,
        url: urlApi, //TRACKER_HOST
        headers: {
          Authorization: 'Bearer ' + token,
        },
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        locationUpdateInterval: 10000,
        fastestLocationUpdateInterval: 10000,
        allowIdenticalLocations: true,
        useSignificantChangesOnly: false,
        foregroundService: true,
        autoSync: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        stopTimeout: 15,

## Expected Behavior
The plug-in sends location updates to our server every 1000 ms

## Actual Behavior
The device only sends the location to our server when it starts, after that just calling the BackgroundGeolocation.getCurrentPosition() function.

## Steps to Reproduce

1. Set the configuration
2. Start the library
3. Walk with the device and check locations updates

## Debug logs

<details><summary>Logs</summary>
 
PASTE_YOUR_LOGS_HERE
</details>

**Comment by christocracy** [comment]
- See Wiki *Debugging*.  Learn to monitor and fetch logs from the plugin.
- See http://dontkillmyapp.com

**Comment by nasmuris** [comment]
I'm having the same problem on multiple Android devices, where we can get any location updates after some time even on **FOREGROUND** if we dont have `always` permission
used config:
```
{ 
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOWEST,
  distanceFilter: 1000.0,
  reset: true,
  stopOnTerminate: false,
  startOnBoot: true,
  enableHeadless: true,
  maxDaysToPersist: 14,
  geofenceProximityRadius: 50000,
  notification: {
    smallIcon: 'mipmap/ic_notification',
    largeIcon: 'mipmap/logo_smg_white',
    priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
    text: translate('androidGeolocationNotificationText', undefined),
    title: translate('androidGeolocationNotificationTitle', undefined),
  },
  disableMotionActivityUpdates: false,
  disableLocationAuthorizationAlert: true,
  locationAuthorizationRequest: 'Always',
  useSignificantChangesOnly: false,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 1.0,
}
```
## Debug/Testing results
the same route was taken with both always and whenInUse permission and **APP WAS ON FOREGROUND**
### session with always:
<img width="513" alt="Screenshot 2021-02-26 at 20 19 19" src="https://user-images.githubusercontent.com/22944924/109345229-1cd01000-7870-11eb-88c9-33576f4a2a69.png">

### session with whenInUse
<img width="501" alt="Screenshot 2021-02-26 at 20 18 43" src="https://user-images.githubusercontent.com/22944924/109345286-2fe2e000-7870-11eb-8590-0a5eb0063dc5.png">

**Comment by christocracy** [comment]
You're aware that Android doesn't monitor geofences with `WhenInUse` authorization?

**Comment by nasmuris** [comment]
@christocracy Yes, I'm, classic `onLocation` updates should work though.

**Comment by nasmuris** [comment]
@christocracy Ok, so as you pointed out, all the location updates are from geofences, it seems there is some problem with the location listener itself as I'm not receiving any location updates even with Demo application on Android 9 (Moto Z3 Play) (`getCurrentPosition` works and GMap's`UserLocation` is moving ) unless I `call BackgroundGeolocation.changePace(true)`
In the meantime I updated to `"react-native-background-geolocation": "^3.10.0",` in my app, encouting the same behavior...

**Comment by christocracy** [comment]
See wiki *Debugging*.  Are you observing logs from the plugin?

**Comment by nasmuris** [comment]
@christocracy I've collected several logs while testing different scenarios yesterday. here they're
[whenInUse.log](https://github.com/transistorsoft/react-native-background-geolocation/files/6106825/whenInUse.log)
[whenInUseAfterRestart.log](https://github.com/transistorsoft/react-native-background-geolocation/files/6106826/whenInUseAfterRestart.log)
[motionActivity.log](https://github.com/transistorsoft/react-native-background-geolocation/files/6106827/motionActivity.log)
[motionActivityAfterRestart.log](https://github.com/transistorsoft/react-native-background-geolocation/files/6106828/motionActivityAfterRestart.log)
[alwaysAfterRestart.log](https://github.com/transistorsoft/react-native-background-geolocation/files/6106830/backgroundAfterRestart.log)

the strange thing is the geolocation module doesn't work even with location always unless I restart the app

My app flow is:
1. `BCG.ready()` on app init (component mount)
2. `BCG.start();` `BCG.changePace(true);` AFTER user granted location permission
3. update config when user grants motion activity permission/ location always permission

config:
```
{
  desiredAccuracy: hasMotionActivity ? BackgroundGeolocation.DESIRED_ACCURACY_HIGH : BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
  distanceFilter: hasMotionActivity ? 1.0 : 25,
  reset: true,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
  stopOnTerminate: !hasLocationAlwaysPermission,
  startOnBoot: hasLocationAlwaysPermission,
  enableHeadless: hasLocationAlwaysPermission,
  geofenceProximityRadius: 50000,
  disableMotionActivityUpdates: !hasMotionActivity,
  disableLocationAuthorizationAlert: true,
  locationAuthorizationRequest: hasLocationAlwaysPermission ? 'Always' : 'WhenInUse',
  useSignificantChangesOnly: false,
}
```

**Comment by jaroslav009** [comment]
Have the same issue

**Comment by christocracy** [comment]
This issue is closed
