### ISSUE TITLE
Motion change events are slow to register

### ISSUE THREAD

**Issue by Appkidd** [transistorsoft/react-native-background-geolocation#1227]
## Your Environment
* Plugin version: 3.9.0
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung Galaxy A10 (SM-A105FN)
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
  activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
  disableElasticity: true,
  foregroundService: true,
  notification: { text: '📡 Your location is being transmitted' },
  preventSuspend: Platform.OS === 'ios',
  fastestLocationUpdateInterval: 5000,
  locationUpdateInterval: 5000,
  heartbeatInterval: 60,
  distanceFilter: 0,
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
})
```

## Expected Behavior

The module should log motion changes in a timely fashion.

## Actual Behavior

The module can take several minutes before logging a change in motion, despite having high accuracy and recording a very low speed.

See here for an example: [tracker](http://tracker.transistorsoft.com/RYGO?device=22596&end=2021-1-27%200%3A0&start=2021-1-26%2021%3A45)

If you look towards the cluster with 44 markers located in a car park. The vehicle is stationary for ~4 minutes before `is_moving` updates correctly to `false`.

Our application requires that we log as a vehicle becomes stationary, and as a vehicle exits the stationary state. Are these events working as expected, and if so would we be better off using the speed to determine the vehicle's state?

## Steps to Reproduce

1. Use configuration above and log motion events

## Context

Trying to accurately log when the vehicle enters/exits a stationary state.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Logs had expired in logcat, if these are required let me know and I'll do another trip (but I'm hoping this is more of a usage issue than a technical one)
```

</details>

**Comment by Appkidd** [comment]
> - stopTimeout
> 
> Defaults to 5 minutes. When in the moving state, specifies the number of minutes to wait before turning off location-services and transitioning to stationary state after the ActivityRecognition System detects the device is STILL. An example use-case for this configuration is to delay GPS OFF while in a car waiting at a traffic light.

This would seem to be the cause.

How would we go about adjusting our implementation so that we receive the motion events instantly, but continue to only turn off the GPS after 5 minutes?

Our application requires that we log when a vehicle enters/exits a stationary state (like traffic lights), but we don't want to immediately switch off the GPS. Any ideas?

**Comment by christocracy** [comment]
There is no such thing as "instant" *automatic* state-changes from stationary -> moving state.  On iOS, this requires movement of at least 200 meters.  Android can be quicker, depending on the device quality.

You *don't want* the plugin to enter the stationary state at a stop light -- you'll want a high enough stopTimeout to prevent that.  You will listen to the onActivityChange event to learn the motion-state (assuming the user has granted your app the motion permission).

Have you read the wiki "*Philosophy of Operation*.

**Comment by christocracy** [comment]
> is_moving conflicts with true

is_moving represents whether the plugin is in the low power *stationary* state, where the plugin is asleep with location-services OFF and your app is not currently tracking the device location.

**Comment by Appkidd** [comment]
Many thanks for the additional clarification.

**Comment by Appkidd** [comment]
@christocracy So we're now observing the activity via `onActivityChange` to measure when a vehicle is stationary.

This flow works perfectly:

- Walk to car (invokes with `walking`)
- Get in car and drive for ~1 min (invokes with `in_vehicle`)
- Get out of car and walk back to office (invokes with `walking`)
- Sit down in office (invokes with `still`)

However, with this flow, we get stuck at `in_vehicle`:

- Walk to car (invokes with `walking`)
- Get in car and drive for ~1 min (invokes with `in_vehicle`)
- Sit in car with engine off for 15 minutes and device perfectly still: stays at `in_vehicle`

Is this likely to be device specific? Could we manually tell the plugin to start `stopTimeout` if we see it fit to do so due to ActivityRecognitionClient not updating the state correctly?

**Comment by christocracy** [comment]
>Is this likely to be device specific?

Certainly.

>Could we manually tell the plugin to start stopTimeout

No, but you can manually toggle the plugin into the *stationary* state with:

```javascript
// Providing true will place the plugin into the moving state.
BackgroundGeolocation.changePace(false)
```

**Comment by Appkidd** [comment]
Sorry to open an old post, but the environment/code is the same.

Is it possible to _only_ enter the moving state with `changePace(true)`, and not when motionchange events are fired?

From reading the Philosophy of Operation, it seems like the motion will change automatically based on the motion state from ActivityRecognitionAPI.

In our application, we only wish to track the user's location when they hit start and we call `changePace(true)` like the jogging example, but crucially we still need to keep the services on with `start()` as we need the heartbeats. Is this possible?

**Comment by Appkidd** [comment]
Looks like you don't need to call `start()` for heartbeats. And there's the answer! We'll adjust our flow so that we're calling `start()` and use `isMoving: true` in the ready config.

**Comment by christocracy** [comment]
> Looks like you don't need to call start()

Yes you do.  The plugin does not fire *any* events or consume any power unless it has been `.star()`ed (ie when `state.enabled` is true).

**Comment by Appkidd** [comment]
My mistake. In that case, my original question stands. Is it possible to to prevent the app entering `moving` state automatically? We only wish to begin actively tracking after `changePace(true)` regardless of motion events.

**Comment by christocracy** [comment]
>  Is it possible to to prevent the app entering moving

Yes.  Try tell the plugin to `.stop()`.  Use background-fetch for your “heartbeat-type” periodic tasks

**Comment by Appkidd** [comment]
Great - will do that. Thanks again for your help.
