### ISSUE TITLE
#stopSchedule() log message says "#startSchedule"

### ISSUE THREAD

**Issue by ryankask** [transistorsoft/react-native-background-geolocation#123]
This is very minor but I noticed that when calling #stopSchedule(), in the logs it says:

```
- RCTBackgroundGeoLocation #startSchedule
```

The location indicator in the status bar goes away so I'm assuming it's actually stopped and the log message needs to be updated.

**Comment by christocracy** [comment]
Correct. 
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/RNBackgroundGeolocation/RNBackgroundGeolocation.m#L142

**Comment by ryankask** [comment]
PR for this: https://github.com/transistorsoft/react-native-background-geolocation/pull/125
