### ISSUE TITLE
Odometer always return 0 in iPhone 6 and iPhone x, can you please help me to find out issue.

### ISSUE THREAD

**Issue by tnmsoftwares** [transistorsoft/react-native-background-geolocation#1233]
Below is my configuration, please check it.

const MANUALCONFIGIOS = {
    reset: true,
    desiredAccuracy: 0,// BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 1, //20
    stopOnTerminate: true, //because auto start-stop disable now
    startOnBoot: false,
    stopTimeout: 2,
    stopDetectionDelay: 5,
    stationaryRadius: 20,
    desiredOdometerAccuracy: 5000
};

**Comment by christocracy** [comment]
Show me your code.  You're doing something wrong and it's not your Config.

**Comment by tnmsoftwares** [comment]
Fixed now
