### ISSUE TITLE
How To Configure For Headless Event To Update Location For Specific Interval Or After Specific Distance

### ISSUE THREAD

**Issue by VinitBhavsar** [transistorsoft/react-native-background-geolocation#1234]
## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung Galaxy A20
* React Native version (`react-native -v`):  0.60.1
* Plugin config

## Expected Behavior
After Terminating App, I Want To Update Location After Specific Interval/Distance.

## Actual Behavior
Currently, It Only Updates After 30 Sec For Once. If I Start Fake Location Service It Called Multiple Time.
```
BackgroundGeolocation.ready(
{
distanceFilter: 200,
preventSuspend: true,
stopOnTerminate: false,
startOnBoot: true,
debug: true,
enableHeadless: true,
foregroundService: true,
locationUpdateInterval: 60000, 
}
```

distanceFilter and locationUpdateInterval is for example. While testing only one option is set.

It works perfectly when App goes into the background state.

But When I Terminate the application. It Called After 30 Sec For 1st time. 

If I start a fake location it executes multiple times, instead of defined distanceFilter or locationUpdateInterval.

```
let HeadlessTask = async (event) => {
  let params = event.params;
  console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);
  
  switch (event.name) {
    case 'heartbeat':
      // Use await for async tasks
      let location = await getCurrentPosition();
      console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
      break;
  }
}

let getCurrentPosition = () => {
  return new Promise((resolve) => {
    BackgroundGeolocation.getCurrentPosition(
    {
      samples: 1,
      persist: false
    },
    (location) => {
      resolve(location);
    }, (error) => {
      resolve(error);
    });
  });
};

BackgroundGeolocation.registerHeadlessTask(HeadlessTask);
```

Which event case to do so?

**Comment by christocracy** [comment]
Locations from Mock apps are throttled by Config.fastestLocationUpdateInterval

**Comment by christocracy** [comment]
Read the api docs.

**Comment by christocracy** [comment]
```javascript
let getCurrentPosition = () => {
  return new Promise((resolve) => {
    BackgroundGeolocation.getCurrentPosition(
    {
      samples: 1,
      persist: false
    },
    (location) => {
      resolve(location);
    }, (error) => {
      resolve(error);
    });
  });
};
```

Did you know that most plugin methods *already return a `Promise`?  You're needlessly wrapping this in a `Promise`.

```javascript
let location = await BackgroundGeolocation.getCurrentPosition({
  samples: 1,
  persist: false
});
```

Look at the [source for `getCurrentPosition`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/src/NativeModule.js#L291-L298) and [docs](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#getcurrentposition)

![](https://dl.dropbox.com/s/2wfc9reylp9ipxr/Screen%20Shot%202021-02-04%20at%208.22.04%20AM.png?dl=1)

**Comment by VinitBhavsar** [comment]
```
let HeadlessTask = async (event) => {
  let params = event.params;
  console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);
  
  switch (event.name) {
    case 'terminated':
      // Use await for async tasks
      let location = await getCurrentPosition();
      console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
     //API CALL
      break;
  }
}
```
The issue, I'm facing is here. 

If I removed a switch case try to getCurrentPosition(); It executes continuously. It checks neither distanceFilter nor locationUpdateInterval. That is the issue I'm facing, So what should be event case for that.

**Comment by christocracy** [comment]
> `case 'terminated'`

The event is named `terminate`, not `terminated`.

>If I removed a switch case try to getCurrentPosition(); It executes continuously

Yes, because you've created an infinite loop, since `getCurrentPosition` generates headless `location` events generates `location` events generate `location` events generate `location` events...to infinity.

>All I want to do is update the location after every 5 min even if the device location is not changed.

This is impossible on iOS.  On Android, you can use `heartbeatInterval` and execute `await BackgroundGeolocation.getCurrentPosition` in the headless `heartbeat` event.

**Comment by christocracy** [comment]
>All I want to do is update the location after every 5 min even if the device location is not changed.

You might be interested in using `react-native-background-fetch` for this.

**Comment by VinitBhavsar** [comment]
Thank You For your Quick Reply. I'll Check This.
