### ISSUE TITLE
Geofence spawn multiple occurrence of the same geofence

### ISSUE THREAD

**Issue by dreamsystems** [transistorsoft/react-native-background-geolocation#1235]
## Your Environment
* Plugin version: 3.9.3
* Platform: iOS and Android
* OS version: Android 8 and Ios 14.3
* Device manufacturer / model: Simulator for ios and Wiko Y50 for android
* React Native version (`0.63.4`):

## Expected Behavior

Return one occurence per geofence.

## Actual Behavior

Returns multiple occurence per geofence.

## Steps to Reproduce

1. Load the app and see the console.log(geofence) result 
2. Add a marker with and within a geofence and see the console.log(geofence) result

Is there a way to force geofence to return only one occurrence per geofence ?

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
{"action": "ENTER", "identifier": "bear", "location": {"activity": {"confidence": 100 ...}
{"action": "ENTER", "identifier": "bear", "location": {"activity": {"confidence": 100 ...}
{"action": "ENTER", "identifier": "bear", "location": {"activity": {"confidence": 100 ...}
{"action": "ENTER", "identifier": "bomb", "location": {"activity": {"confidence": 100 ...}
{"action": "ENTER", "identifier": "bomb", "location": {"activity": {"confidence": 100 ...}
{"action": "ENTER", "identifier": "bomb", "location": {"activity": {"confidence": 100 ...}
```
The plugin returns multiple occurence of the same geofence when i load the app on startup and when i add a marker in a geofence zone.

Add a marker
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
          <TouchableOpacity 
            style={styles.reportContainer}
            onPress={() => {
              if (this.state.markerPosition) {
                this.props.store.markers.push({ownerId: this.props.store.userId ,id: this.props.route.params.category.id, name: 
                this.props.route.params.category.name, coords: {latitude: this.state.markerPosition.latitude,
                  longitude: this.state.markerPosition.longitude}})
              } else {
                this.props.store.markers.push({ownerId: this.props.store.userId ,id: this.props.route.params.category.id, name: 
                this.props.route.params.category.name, coords: {latitude: this.state.region.latitude,
                  longitude: this.state.region.longitude}})
              }
              this.props.navigation.navigate('Home')
            }}
            >  
            <Text style={styles.reportText}>Rapporter</Text>
          </TouchableOpacity>
```

Add a geofence
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
<MapView
        ref={(ref) => {this.map = ref}}
        style={styles.map}
        showsUserLocation
        region={this.state.region}>
        {this.state.markers.map((marker, index) => {
            BackgroundGeolocation.addGeofence({
              latitude: marker.coords.latitude,
              longitude: marker.coords.longitude,
              identifier: marker.id,
              radius: 5200,
              notifyOnEntry: true
            })
            return <View>
              <Marker
            key={index}
            coordinate={marker.coords}>
            ...
```

onGeofence method
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
UNSAFE_componentWillUpdate() {
    BackgroundGeolocation.onGeofence(geofence => {  
      console.log(geofence)
      Tts.speak(threatTypeToText(geofence.identifier))
    })
```

**Comment by christocracy** [comment]
Please don't ignore the issue template.  **Edit** your issue and provide the following information:

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I see you've updated the your issue.  Well done.

```javascript
UNSAFE_componentWillUpdate() {
    BackgroundGeolocation.onGeofence(geofence => {  
      console.log(geofence)
      Tts.speak(threatTypeToText(geofence.identifier))
    })
```
This is *not* where you should be listening to plugin events.  

Listening to events is like adding speakers to your stereo system.  Every time you `onGeofence`, you're basically adding a new speaker.  

Listen to events, such as `onGeofence`, just *once* when your component *mounts*.

You're basically doing this:
```
for (let n=0;n<10;n++) {
  BackgroundGeolocation.onGeofence(geofence => {  
      console.log(geofence);
      Tts.speak(threatTypeToText(geofence.identifier))
   });
}
```

Modify your code as follows and observe **how often** this method executes:

```javascript
UNSAFE_componentWillUpdate() {
    console.log('[componentWillUpdate] EXECUTED');
}
```

**Comment by dreamsystems** [comment]
This revolve the problem when i add a new marker with geofence, thanks. Remains the plugin returns multiple occurence of the same geofence when i load the app on startup. It's random. Sometime this works, sometime the geofence is rendering two times.

**Comment by christocracy** [comment]
>Sometime this works, sometime the geofence is rendering two times.

See Wiki *Debugging*.  Provide logs from the plugin where this occurs.

**Comment by christocracy** [comment]
And if you're experiencing this during development while hot-reloading, you're probably accumulating `onGeofence` event-listeners each time a hot reload occurs.

This is why I call [`removeListeners` when `componentWillUnmount`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/src/hello-world/HelloWorld.tsx#L73-L77)

**Comment by christocracy** [comment]
While developing with this plugin, it's a good idea to monitor `logcat` in a terminal window.
- tag `TSLocationManger:V`:  messages from the plugin.  `V` for verbose.
- tag `ReactNativeJS:V`:  messages from your Javascript `console.log`

```bash
$ adb logcat *:S TSLocationManager:V ReactNativeJS:V`
```

![](https://dl.dropbox.com/s/5lp7zf9letxcu5v/Screen%20Shot%202021-02-04%20at%2012.43.17%20PM.png?dl=1)

**Comment by christocracy** [comment]
`logcat` of a `geofence` event on Android.

![](https://dl.dropbox.com/s/r5ghlntwc77uqay/Screen%20Shot%202021-02-04%20at%2012.54.22%20PM.png?dl=1)

**Comment by christocracy** [comment]
Also note that once `addGeofence` is called, that geofence is stored in the plugin's SQLite database.  You don't need to `addGeofence` *every time your app launches*.  If you do, the plugin is going to first `DELETE FROM geofences WHERE identifier=?` the existing geofence before re-adding the new record.  If you are doing this, this is **not** a cause of your reported issue.

Once a geofence is added with `addGeofence`, it is **monitored forever** until you `removeGeofence` or tell the plugin to `BackgroundGeolocation.stop()`

**Comment by dreamsystems** [comment]
Thanks
