### ISSUE TITLE
Wrong geofence location

### ISSUE THREAD

**Issue by dreamsystems** [transistorsoft/react-native-background-geolocation#1236]
## Your Environment
* Plugin version: 3.9.3
* Platform: iOS and Android
* OS version: Android 8 and Ios 14.3
* Device manufacturer / model: Simulator for ios and Wiko Y50 for android
* React Native version (0.63.4):

## Expected Behavior
The plugin set the right location for a geofence

## Actual Behavior
The plugin set the wrong location for a geofence

## Steps to Reproduce

1. Set the onGeofencesChange(event) event to console.log(event)
2. Set the onGeofence(geofence) event to console.log(geofence)
3. Add a geofence
4. See the console.log(event), check the coordinates.
5. See the console.log(geofence), check the coordinates.
6. There are not the same. There are right when the onGeofencesChange(event) fire and wrong when onGeofence(geofence) event fire.

Expected coordinates
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
LOG MarkerPosition latitude: 43.908889699999996. MarkerPosition longitude: 2.1137745999999997.
```

The onGeofencesChange(event) fire, the coordinates are right

onGeofencesChange(event)
```
LOG {"off": [], "on": [{"identifier": "bee", "latitude": 43.908889699999996, ... , "longitude": 2.1137745999999997, ... }]}
```

Then the onGeofence(geofence) event fire, the coordinates are wrong

onGeofence(geofence) event
```
LOG {"action": "ENTER", "identifier": "bee", "location": { ... "latitude": 43.9193974, "longitude": 2.1295725, ... }}
LOG Geofence latitude: 43.9193974. Geofence longitude: 2.1295725.
```

i add a geofence in this manner
```
<TouchableOpacity 
            onPress={() => {
              console.log(`MarkerPosition latitude: ${this.state.markerPosition.latitude}. MarkerPosition longitude: 
              ${this.state.markerPosition.longitude}.`)
              BackgroundGeolocation.addGeofence({
                  latitude: this.state.markerPosition.latitude,
                  longitude: this.state.markerPosition.longitude,
                  identifier: this.props.route.params.category.id,
                  radius: threatTypeToRadius(this.props.route.params.category.id),
                  notifyOnEntry: true
                })
              this.props.navigation.navigate('Home')
            }}
            >  
            <Text style={styles.reportText}>Report</Text>
</TouchableOpacity>```

**Comment by christocracy** [comment]
I'm not sure you understand what `onGeofencesChange` is.  These are the geofences that the plugin is currently *monitoring*.  These do no represent an *enter* or *exit* event.  The coordinate you see is the *center coordinate* of the geofence you used with `addGeofence`.

`onGeofence` is a geofence *event* (*enter* / *exit* / *dwell*).  The location in a geofence event is the location *where the event occurred*.

**Comment by dreamsystems** [comment]
I understand now, thanks.
