### ISSUE TITLE
Schema of HTTP post JSON

### ISSUE THREAD

**Issue by ryankask** [transistorsoft/react-native-background-geolocation#124]
I noticed that the schema of the JSON being sent when HTTP sync is enabled is slightly different went posting a batch vs posting a single location update.

It looks like when there is more than one unsynced location stored, an array of locations is sent:

```
{
    "location": [
        {
            ...
        }
    ]
}
```

When there is only one location, it is a single object:

```
{
    "location": {
        ...
    }
}
```

Is this intended? I originally thought that if `batchSync` was set to `true`, an array of locations would always be posted and if it was `false`, a single object (or maybe always an array for consistency).

As an aside, I want to report the last location, if available. Are these the best settings for this?

```
{
     ....
     batchSync: false,
     autoSync: true,
     maxRecordsToPersist: 1
}
```

Apologies for posting multiple issues in quick succession!

**Comment by christocracy** [comment]
It is correct, as documented in Wiki
https://github.com/transistorsoft/react-native-background-geolocation/wiki/Location-Data-Schema

If you only want the last-recorded location, that config will work.  Imagine the user is on an airplane and loses network connection.  The device can still record GPS locations during the flight (I once recorded a complete flight between NYC and Montreal).  Once he lands, the plugin's db will only contain the last-recorded location.  When network is restored, the plugin will send just the last location to the server.  The entire flight tracking was forgotten.

**Comment by ryankask** [comment]
Thanks for the update and explanation.

I guess with this schema you could introspect the location prop's type to determine if the request is a batch sync or not. 

Thanks.
