### ISSUE TITLE
"app would like to access your motion & fitness activity " how to remove that Alert ?

### ISSUE THREAD

**Issue by Rishabhcore7** [transistorsoft/react-native-background-geolocation#1240]
## Your Environment
* Plugin version:3.9.3
* Platform: iOS 
* OS version:
* Device manufacturer / model: IOS 14.4
* React Native version (`react-native -v`):0.59.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See API docs `Config.disableMotionActivityUpdates`.

**Comment by Rishabhcore7** [comment]
so does it effect any functionalities ? 
like i'm currently getting latitude longitude when user move on location event ?

**Comment by Rishabhcore7** [comment]
i read the docs and it says it is used to improve the battery performance, we strongly recommend to not disable this
Can we change that Message "app would like to access your motion & fitness activity"
