### ISSUE TITLE
"No task registered for key BackgroundGeolocation"

### ISSUE THREAD

**Issue by JarvisPos** [transistorsoft/react-native-background-geolocation#1241]
Hello, yesterday we bought react-native-background-location key. We think we have done the installation correctly. When the application is closed, we get a warning like "No task registered for key BackgroundGeolocation". What could be the reason for this?
When the application is closed, we cannot get a location. We are using onLocation (). I have to use a different method.

**Comment by JarvisPos** [comment]
In the onLocation method, I connect with the socket and send the location to the service. There is no problem sending location in foreground and background, but location sending is stopped when the application is closed. I logged that "No task registered for key BackgroundGeolocation" gave this warning.

**Comment by christocracy** [comment]
You must not ignore the issue template.  **edit your issue** and provide the following information requested.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by JarvisPos** [comment]
Plugin version: 3.9.3
Platform: Android
OS version: 8 and 10
Device manufacturer / model: asus zenfone 3 and xaomi red mi note 8 pro
React Native version (react-native -v): 062.2
Plugin config
  BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      locationUpdateInterval: 6000,
      stopTimeout: 5,
      maxDaysToPersist: 14,
      // Activity Recognition
      notification: {
        title: "Konum",
        text: "JaviPos konum izleme aktif.",
      },
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      autoSync: true,
      enableHeadless: true

    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        ////
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(function () {
          console.log("- Start success");
        });
      }

    }, (error) => {
      console.warn('BackgroundGeolocation error: ', error)
    });


    BackgroundGeolocation.onLocation(async location => {
      console.log('object', location.coords.latitude, location.coords.longitude)
      //console.log("[location] ", location);

    if (courierHubConnection !== null) {
      dispatch(sendMessageCourierSocket(location.coords.latitude, location.coords.longitude))
    }
    else {
      await dispatch(setCourierHubConnection())
      dispatch(sendMessageCourierSocket(location.coords.latitude, location.coords.longitude))
    }
  }, error => {
    console.log("[location] ERROR: ", error);
  });

**Comment by christocracy** [comment]
Now **edit your original** post and add the now completed template into it.

**Comment by christocracy** [comment]
![](https://dl.dropbox.com/s/dph11pik58wxvoz/Screen%20Shot%202021-02-13%20at%208.13.07%20AM.png?dl=1)
