### ISSUE TITLE
License key after purchasing the plugin

### ISSUE THREAD

**Issue by dreamsystems** [transistorsoft/react-native-background-geolocation#1242]
## Your Environment
* Plugin version: 3.9.3
* Platform: iOS and Android
* OS version: Android 8 and Ios 14.3
* Device manufacturer / model: Simulator for ios and Wiko Y50 for android
* React Native version (0.63.4):

## Expected Behavior

Get the licence by email.
## Actual Behavior

No licence key in the email.
## Steps to Reproduce

1. Purchase the product.
2. Check the email.

My question, where is the licence key when purchasing the product.
My email: martinthomasdev@gmail.com

**Comment by dreamsystems** [comment]
It's good now. I have found your website.

**Comment by christocracy** [comment]
![](https://www.dropbox.com/s/gjd47bx0rrq6adq/Screen%20Shot%202021-02-14%20at%2012.22.08%20PM.png?dl=1)

Questions like this best handled by sending an email from my Site's /contact page.

Check your mail and follow the instructions.
