### ISSUE TITLE
Background Location Speed Calculate

### ISSUE THREAD

**Issue by JarvisPos** [transistorsoft/react-native-background-geolocation#1244]
In the incoming location information, the speed comes as 22.96. How can I calculate the speed. Example so that I can show it as 120km / Hour. Thanks 

Settings
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      stopTimeout: 5,
      locationUpdateInterval:10000,
      // Activity Recognition
      notification: {
        title: "Konum",
        text: "JaviPos konum izleme aktif.",
      },
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      autoSync: true,
      batchSync: false,
      enableHeadless: true,
      url: "",
      httpRootProperty: "data",
      extras: {
        "PackageUserId": UserId,
        "PackageUserName": NameSurname,
        "BrandId": BrandId
      },
      locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"accuracy":<%= accuracy %>,"altitude":<%= altitude %>,"altitude_accuracy":<%= altitude_accuracy %>,"heading":<%= heading %>,"speed":<%= speed %>,"is_charging":<%= battery.is_charging %>,"level":<%= battery.level %>,"type":"<%= activity.type %>","_event":"<%= event %>","timestamp":"<%= timestamp %>","uuid":"<%= uuid %>"}'
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version: Android  10
* Device manufacturer / model: Redmi Pro 8
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The speed is in meters/second.

Upscaling to km/h is simple mathematics.
