### ISSUE TITLE
Deactivate background location

### ISSUE THREAD

**Issue by dreamsystems** [transistorsoft/react-native-background-geolocation#1245]
## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Wiko Y50
* React Native version (`0.63.4`):

## Expected Behavior

The application run without background location. 

## Actual Behavior

The application run with background location. 

## Context

My application has been rejected from the playstore due to: Unable to verify background feature in app.
I want to deactivate background location but i don't see something like this
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
``` 
in the android manifest file. I have only something like this
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
``` 
Where i can deactivate background location ? Thanks

**Comment by christocracy** [comment]
See my latest blog at https://transistorsoft.medium.com

**Comment by dreamsystems** [comment]
I have read your article. There is no mention about how to deactivate background location. Set `stopOnTerminate: true`, `startOnBoot: false`, and set `<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" tools:node="remove" />` is enough to deactivate background location ?

**Comment by christocracy** [comment]
> but i don't see something like this

The plugin has *its own* `AndroidManifest.xml` containing *all* its required permissions, which is *merged into* your own app's.

>I have read your article. There is no mention about how to deactivate background location

Sure there is, right at the end of the article.

![](https://dl.dropbox.com/s/lw2u6f2xuw5wh1n/Screen%20Shot%202021-02-16%20at%207.56.44%20PM.png?dl=1)

>My application has been rejected from the playstore due to: Unable to verify background feature in app

If I were you, I'd simply follow the instructions on my blog.  I've released three of my own apps following those instructions.

**Comment by dreamsystems** [comment]
Thanks

**Comment by christocracy** [comment]
Please close your issues when satisfied.
