### ISSUE TITLE
Track location iOS background with permission as “when in use”

### ISSUE THREAD

**Issue by bajjajjrajjesh** [transistorsoft/react-native-background-geolocation#1247]
## Your Environment
* Plugin version: 3.9.1
* Platform: iOS
* OS version: 14.4
* Device manufacturer / model:iPhone 12
* React Native version (`react-native -v`): 0.59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Track location when app is killed and in background with permission of location as “when in use”
## Actual Behavior

I need to set location permission to “always” to enable app to track location when in background or app is killed. 
## Steps to Reproduce

1.
2.
3.
4.

## Context

I want to use location service as when in use still track location 
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
How do you expect that to happen, with *magic*?

When your app is *terminated*, it is clearly **no longer in use**.

**Comment by bajjajjrajjesh** [comment]
I know this was a silly question but my client has this specific requirement and he claimed that this is possible so I wanted to take one chance to check with you if its possible or not.

**Comment by bajjajjrajjesh** [comment]
But one question I have does it means app can be in background for 5 hours and still track location with when in use permission?

**Comment by christocracy** [comment]
Ask yourself;  "*When I put any app in the background, is it in-use*?"

**Comment by bajjajjrajjesh** [comment]
It isn't but maybe I got confused. Thanks for attending my silly questions.

**Comment by christocracy** [comment]
With `WhenInUse` permission, if one engages location-services *while the app is in-use* (eg a UI button [Start Workout]  calling `.changePace(true)` in a *Jogging App*), then the OS will continue recording locations in the *background* (not *terminated*).

**Comment by vovkind** [comment]
@christocracy hi.

> With `WhenInUse` permission, if one engages location-services _while the app is in-use_ (eg a UI button [Start Workout] calling `.changePace(true)` in a _Jogging App_), then the OS will continue recording locations in the _background_ (not _terminated_).

Hi, Chris. 

With regarding written above, I have a question.
In my case, I want to simulate behaviour of Waze/Google Maps for iOS devices. Both require only WhileInUse permission granted for Location services, and _somehow_ they are perfectly working in the background. So I need to track location with granted WhileInUse permission, while the app is in the background.

It's OK for me to use changePace(true), like a Jogging App.
When I will set changePace(false), will be heartBeatEvent triggered yet? I need it triggered when the device in the stationary state.

Thank you in advance, Chris.
