### ISSUE TITLE
Plugin does not fire location change event on real device

### ISSUE THREAD

**Issue by rend-alsaadi** [transistorsoft/react-native-background-geolocation#1248]
The onLocation event handler is not triggered when using the plugin on real devices. Works perfectly when using on xCode simulator 

## Your Environment
* Plugin version: 3.10.0
* Platform: iOS
* OS version: 14.3
* Device manufacturer / model: iPhone SE
* React Native version (`react-native -v`): 0.61.4
* Plugin config

const Home = () => {
	const {
		state,
		requestLocationPermission,
		sendLocation,
		getCurrentLocation,
		locationChangedCounter,
	} = useContext(BackgroundLocationContext);
	const authContext = useContext(AuthContext);
	const mapContext = useContext(MapContext);

	const [backgroundLocationSwitch, setBackgroundLocationSwitch] = useState(
		false
	);
	const [backgroundLocationReady, setBackgroundLocationReady] = useState(null);
	let areaPolygons = [];

	useEffect(() => {
		getLocationPermission = async () => {
			await requestLocationPermission();
		};
		getLocationPermission();

		BackgroundGeolocation.onLocation(
			onLocationChange,
			onBackgroundLocationError
		);

		BackgroundGeolocation.onActivityChange(onActivityChange);

		BackgroundGeolocation.ready({
			logLevel: 0,
			stopTimeout: 10,
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			distanceFilter: 1,
			stopOnTerminate: false,
			startOnBoot: false,
			disableStopDetection: true,
			pausesLocationUpdatesAutomatically: false,
		});

		return () => {
			console.log("unmounted");
			BackgroundGeolocation.removeListeners();
		};
	}, []);

	const setBackgroundLocationEmitter = async (toggle) => {
		if (toggle === false) {
			console.log("Stop background tracker");
			BackgroundGeolocation.stop();
		} else if (toggle === true) {
			console.log("Starting background tracker");
			BackgroundGeolocation.start();
			let location = await getCurrentLocation();
			sendLocation(location, authContext.state.user);
		}
	};

	const onLocationChange = async (location) => {
		if (!_.isEmpty(areaPolygons)) {
			let inArea = checkInArea(location, areaPolygons);
			inArea ? sendLocation(location, authContext.state.user) : null;
		} else {
			areaPolygons = JSON.parse(await AsyncStorage.getItem("areaPolygons"));
		}
	};

	const onMotionChange = (event) => {
		console.log("[motionchange] -");
	};

	const onActivityChange = (event) => {
		console.log("[activitychange] -", event); // eg: 'on_foot', 'still', 'in_vehicle'
	};

	const onBackgroundLocationError = (error) => {
		console.log(("Error", error));
	};

	return (
		<SafeAreaView>
			<View style={styles.container}>
				<Image
					style={styles.image}
					source={require("../../assets/images/logo.jpg")}
				/>

				<Text style={styles.header}>Welcome to ThruGreen</Text>
				<Text style={styles.caption}>
					Flip the switch below to get started.
				</Text>
				<Switch
					style={styles.switch}
					value={backgroundLocationSwitch}
					onValueChange={(toggle) => {
						setBackgroundLocationSwitch(toggle);
						setBackgroundLocationEmitter(toggle);
					}}
					trackColor={{ false: "#F78D8D", true: "#3EB56C" }}
				/>
			</View>
		</SafeAreaView>
	);
};

const styles = StyleSheet.create({
	container: {
		borderColor: "red",
		backgroundColor: "white",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
		height: "100%",
	},
	header: {
		borderTopColor: "#3EB56C",
		borderTopWidth: 1,
		fontSize: 36,
		color: "#525252",
		paddingTop: 35,
		marginTop: 35,
		marginBottom: 5,
		alignSelf: "center",
		textAlign: "center",
	},
	caption: {
		fontSize: 17,
		color: "#333",
		alignSelf: "center",
		textAlign: "center",
		marginBottom: 40,
	},
	image: {
		marginTop: 20,
	},
	switch: {
		transform: [{ scaleX: 1.2 }, { scaleY: 1.2 }],
	},
});

export default Home;
## Expected Behavior
onLocation should fire while moving

## Actual Behavior
It seems to not fire the onLocation event handler in real devices despite having the correct permissions set. 

## Steps to Reproduce

1.
2.
3.
4.

## Context
It seems like after iOS 14 was released we started seeing problems. However, I've gone through the instructions and made sure the plugins are installed correctly. The strangeness is coming from the fact that it works in the simulator (even when simulating with a real device via USB), but not when app is deployed on TestFlight. 

## Debug logs
I'm not sure how to get logs while device is running the TestFlight version of the app. 
<details><summary>Logs</summary>
</details>

**Comment by rend-alsaadi** [comment]
Oh and I also have a membership because we use this for android as well.

**Comment by christocracy** [comment]
I've not heard of a problem like this on iOS from thousands of other customers.

**Comment by christocracy** [comment]
I suggest you enable verbose logged and fetch the logs from plugin.

**Comment by rend-alsaadi** [comment]
Hi @christocracy - my fault, I figured it out. It was a silly expo-related mistake. Thank you!
