### ISSUE TITLE
Not receiving Geolocation Updates on android build.

### ISSUE THREAD

**Issue by karlotracs** [transistorsoft/react-native-background-geolocation#1249]
Hi! Licenced user here. 

I have previously built the app and succesfully received location updates with the library, but in a recent update, Im not receiving a single request, if I run in my localhost the requests are made correctly. Where do I have to look to discard any licencing or building issue?

And please can you indicate me how licenced GitHub issues support works? Thanks in advance

**Comment by christocracy** [comment]
See Wiki *Debugging*.  Fetch logs from the plugin.

>And please can you indicate me how licenced GitHub issues support works? Thanks in advance

You're supposed to use the *Private Repo*.  Check your mail:
![](https://dl.dropbox.com/s/qh7winor2rzz1cy/Screen%20Shot%202021-02-23%20at%205.00.37%20PM.png?dl=1)
