### ISSUE TITLE
Heartbeat timer affected by battery optimization

### ISSUE THREAD

**Issue by eduardooliveiracastro** [transistorsoft/react-native-background-geolocation#1251]
## Your Environment
* Plugin version: 3.9.1
* Platform: Android
* OS version: 10
* Device manufacturer / model: Oneplus 5
* React Native version: 0.62.2
* Plugin config
```javascript 
onHeartbeat = () => {
  BackgroundGeolocation.getCurrentPosition()
}
componentDidMount(){
    BackgroundGeolocation.onHeartbeat(this.onHeartbeat);

    BackgroundGeolocation.ready({
      heartbeatInterval:60,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      disableStopDetection: true,
      stopTimeout: 1,
      debug: true, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
      stopOnTerminate: false,  
      startOnBoot: true,       
      
      url: 'http://myurl.com/myfile.php',
      batchSync: false,   
      autoSync: true,      

    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
}
```

## Expected Behavior
Every 60 seconds send location to API when APP is open or running on background

## Actual Behavior
When connected via wall socket works like flawlessly but when connect to the PC or not connected at all makes the request less often until the point it seems to stop sending.
This seems to be a battery optimization related issue so I changed the APP battery settings to "don't optimize' but didn't work.

## Context
Inform the API about my current location every 60 seconds even if it hasn't been changed

**Comment by christocracy** [comment]
You should expect the heartbeat to be throttled by the operating system.

**Comment by christocracy** [comment]
The reason Android manufacturers have resorted to drastic process killing measures, requiring the existence of http://dontkillmyapp.com, is because of developers expecting to run code constantly in the background at specific and *fast* intervals.
