### ISSUE TITLE
GPS accuracy is too high, library return 4673 in my iPhone x, iOS 14.4 and its not calculating distance

### ISSUE THREAD

**Issue by tnmsoftwares** [transistorsoft/react-native-background-geolocation#1255]
My iPhone X background-geolocation library return location accuracy 4673 and not calculating distance, can you please help what is issue.

My config:
const IOSConfig = {
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
    distanceFilter: 20,
    stopOnTerminate: false, //Uses for auto start stop
    startOnBoot: true, //Uses for auto start stop
    stopTimeout: 2,
    stopDetectionDelay: 5,
    stationaryRadius: 20,
};

-Every time return more than 4000 accuracy.

*Below configuration set in my device.
-Low power mode off
-Enable wifi
-Background app refresh enable
![Screenshot 2021-03-02 at 20 23 24](https://user-images.githubusercontent.com/6085381/109666417-2bcb0100-7b95-11eb-9cf8-4a467b22cbc7.png)

**Comment by tnmsoftwares** [comment]
someone can you please help me on this issue?

**Comment by christocracy** [comment]
>desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,

This is the only control you have.  Everything is else is related to device or environment.

**Comment by tnmsoftwares** [comment]
Thank you for your reply, but location desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION, so why it returned more than 4000 current accuracy and odometer always return 0 distance.

**Comment by christocracy** [comment]
> and odometer always return 0 

Because it’s pointless to do math with such wildly inaccurate data.  See api docs Config.desiredOdometerAccuracy

Btw, you ** ignored the issue template**, which asked you for important information, such as **OS version**.

**Comment by tnmsoftwares** [comment]
it's fixed now.
