### ISSUE TITLE
How to control when to ask for Android Runtime Permission

### ISSUE THREAD

**Issue by lobothijau** [transistorsoft/react-native-background-geolocation#1256]
I am updating my app to comply with Play Store's new location permission to show disclosure dialog on the first launch. However, my dialog is always shown after the permission dialog and sometimes dismissed by the permission dialog. 

Is there a way to control when the app permission request displayed (because the first screen is a login screen, so it doesn't have to be shown on that page).

**Comment by christocracy** [comment]
Don't call `BackgroundGeolocation.start()` until you want the plugin to request permission.

Don't do this:

```javascript
BackgroundGeolocation.ready(config).then(state => {
  BackgroundGeolocation.start();  // <-- Don't do this here.  This is where permission will be requested.
});
```
