### ISSUE TITLE
still not tracking

### ISSUE THREAD

**Issue by digitlninja** [transistorsoft/react-native-background-geolocation#1258]
## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
This was closed without chance to respond:
https://github.com/transistorsoft/react-native-background-geolocation/issues/1257#issue-824646653

So, even if i shake the device rigurously, it does not log/track.

</details>

**Comment by christocracy** [comment]
Duplicate #1257.

Don't abuse the issues system, is makes me angry.

**Comment by digitlninja** [comment]
> Duplicate #1257.
> 
> Don't abuse the issues system, is makes me angry.

apologies, it didnt give me the option to reply on that other issue
