### ISSUE TITLE
Question concerning background heartbeat behavior on iOS and Android 

### ISSUE THREAD

**Issue by radioipcloud** [transistorsoft/react-native-background-geolocation#1262]
Hello!

We have a specific scenario in mind that we would like to do with the licensed version of your react native background geolocation library.

I am trying to see if :

- It is feasible to use the Heartbeat feature in headless mode on Android or using it in parallel with preventSuspend on iOS to capture heartbeat events and log the current location of a phone indefinitely 24/7 when a device is not in motion (i.e. standing still for long periods)

- Secondly, In the same scenario as before, if the heartbeat was set to 1 min, is it normal that we end up seeing 5 minutes intervals or more when running in headless mode but when the UI is running we see it perform the 1 min exactly as configured ?

Best regards

**Comment by christocracy** [comment]
> with preventSuspend on iOS

Avoid preventSuspend for iOS.  This is a brittle hack required by 1% of use-cases.

You simply don't get to have a consistent update in the background while the device is stationary.  Why do think both Android and iOS become more and more strict with each release?

This kind of developer behavior is also precisely why the Android manufacturers have become so insane with force-killing services, requiring the existence of http://dontkillmyapp.com.

Mobile is a completely different paradigm than developing a desktop app running on a PC plugged into AC power.  On mobile, where the user's battery is a finite resource, "*you can't always get what you want*".

I suggest you use background-fetch for your periodic tasks.

When the device is detected to be moving, the plugin will do its job.

**Comment by christocracy** [comment]
> is it normal that we end up seeing 5 minutes 

Yes.  You can expect the OS to throttle timers with lack of activity from the user, in order to protect the device-owners's battery.

**Comment by christocracy** [comment]
The Android version of background-fetch can execute `scheduleTask` quite regularly when you use `forceAlarmManager: true, periodic: false`, the reschedule another `scheduleTask` when each event fires.

iOS `scheduleTask` is almost useless and might fire a couple of times / day, far less than the default periodic `fetch` task.

**Comment by dphamz** [comment]
> I suggest you use background-fetch for your periodic tasks.

> When the device is detected to be moving, the plugin will do its job.

Will the background-fetch periodic tasks work even when phone goes into doze mode (which is when the device isn't moving for a while)?

**Comment by christocracy** [comment]
Configured as suggested above, background fetch uses [this method from Android AlarmManager](https://developer.android.com/reference/android/app/AlarmManager#setAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent))

**Comment by radioipcloud** [comment]
Really appreciate the feedback ! It's not that we wanted necessarily to do this but we wanted to make sure what would be the expected behavior and adjust according to it.
