### ISSUE TITLE
disableLocationAuthorizationAlert: true takes no effect if stopOnTerminate=false

### ISSUE THREAD

**Issue by nasmuris** [transistorsoft/react-native-background-geolocation#1263]
`disableLocationAuthorizationAlert: true` takes no effect if `stopOnTerminate:false` provided, if `stopOnTerminate:true`, alert is not shown

## Environment
"react-native-background-fetch": "^3.1.0",
"react-native-background-geolocation": "^3.10.0",* Platform: Android
* OS version: 11
* Device manufacturer / model: Pixel 4a (5G)
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```
{
...
stopOnTerminate: false,
disableLocationAuthorizationAlert: true,
locationAuthorizationRequest: "WhenInUse",
...
}
```

## Expected Behavior
LocationAuthorizationAlert should not be shown
## Actual Behavior
LocationAuthorizationAlert is shown 
## Steps to Reproduce
apply provided config fragment

**Comment by christocracy** [comment]
Show me logs and a screenshot.

**Comment by nasmuris** [comment]
It seems like this issue happens only after reloading JS, cannot reproduce on release build
