### ISSUE TITLE
"Location services off" prompt blocks modals from appearing

### ISSUE THREAD

**Issue by Sakarisson** [transistorsoft/react-native-background-geolocation#1264]
## Your Environment
* Plugin version: 4.0.1
* Platform: iOS
* OS version: 14.4
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{}
```

## Expected Behavior

While the "Location services off" prompt is visible, content behind it should still be able to update appropriately (at least after it was dismissed).

## Actual Behavior

If a modal's `visible` prop changes from `false` to `true` while the "Location services off" prompt is visible, the modal will not become visible, even after the prompt has been dismissed.

I'm not sure if this is an issue with React Native itself or this library, but at least I was not able to reproduce in React Native itself by doing something similar with `ReactNative.Alert`

Here is a video for extra context: 

![screencast 2021-03-17 13-39-01](https://user-images.githubusercontent.com/14796211/111462155-c1829680-8726-11eb-82b3-a1b2dd3393fc.gif)

## Steps to Reproduce
Reproducible demo: https://github.com/Sakarisson/ReactNativeModalBug

1. Set location permission to "Never"
2. Close demo
3. Turn on demo
4. The "Location services off" prompt should appear. Press "Cancel"
5. When the prompt disappears, the modal is not visible, even though its `visible` prop has been set to `true`

**Comment by christocracy** [comment]
You can set `true` `Config.disableLocationAuthorizationAlert` to disable this mechanism.  Use `onProviderChange` event to show your own Alert as desired.  I have no idea how I would attempt to resolve this.

**Comment by Sakarisson** [comment]
Thanks for the quick answer! The workaround is a bit unfortunate, since the authorization alert is a very handy feature. 

Would you have any initial thought as to what might be causing the problem? Especially if this is a React Native bug, I'd like to create a RN-only repro and submit the issue to them.
