### ISSUE TITLE
Gyroscopic events

### ISSUE THREAD

**Issue by radioipcloud** [transistorsoft/react-native-background-geolocation#1265]
Is there a way to have access to gyroscope/accelerometer data (i.e. x,y,z)  ... I did not seem to find any way to have access to it. 
My guess is that it's not available but just wanted to be sure.

Best regards

**Comment by christocracy** [comment]
No.  The plugin does not listen to raw Gyroscope/Accelerometer.  It listens to higher level `MotionAPI` that aggregates this information internally and simply spits out `on_foot`, `in_vehicle`, `on_bicycle`, `still`, etc.

You are responsible for listening to sensors yourself by implementing some 3rd-party plugin specializing in Sensors.
