### ISSUE TITLE
Headless 'location' case runs even if the device is not moved anywhere

### ISSUE THREAD

**Issue by Ruzen1** [transistorsoft/react-native-background-geolocation#1267]
Headless 'location' and also the onLocation function runs even if the covered distance is not equal to the distanceFilter.

## Your Environment
* Plugin version: ^3.9.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: Google Pixel 4A 5G
* React Native version (`react-native -v`): 0.61.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
// This is the headless task
let HeadlessTask = async event => {
    switch (event.name) {
// This is being run everytime there is change in location maybe
        case 'location':
            await logTestRepository.logErrorToFirestore('location', event)
            // 現在地情報をGeoPointTypeにキャスト
            const currentPosition = {
                lat: event.params.coords.latitude,
                lng: event.params.coords.longitude,
            }

            await Notification.sendNotification(currentPosition)
            break
    }
}


// the config part
     BackgroundGeolocation.ready(
            {
                locationAuthorizationRequest: 'Always',
                disableLocationAuthorizationAlert: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 1000,
                stopTimeout: 10,
                debug: true, //TODO: MAke this false while merging
                logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
                stopOnTerminate: false,
                startOnBoot: true,
                autoSync: false,
                enableHeadless: true,
            },
```

## Expected Behavior

The Plugin should get the location and run the onLocation function only if 1000m distance is covered.
## Actual Behavior

It runs even if 1000m is not covered. When the app is killed, it runs even if I move slightly.

## Steps to Reproduce

1. 
2.
3.
4.

## Context

I was trying to run the onLocation function after every 1000m covered.
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plugin toggles into the moving state when the Motion API says the device is moving.  It doesn't care about your distanceFilter at that point.  Only once in the *moving* state will it *then* start recording locations according to `distanceFilter`.

Yes, if you simply walk around your house, the plugin will toggle into the *moving* state many times (and then record another location once it toggles back to the *stationary* state.

- See API docs `Config.motionTriggerDelay`.
- Read Wiki *Philosophy of Operation*.

**Comment by christocracy** [comment]
Also see Config.useSignificantChangesOnly: true.
