### ISSUE TITLE
Do not trigger onLocation when getCurrentLocation runs

### ISSUE THREAD

**Issue by Ruzen1** [transistorsoft/react-native-background-geolocation#1268]
## Your Environment
* Plugin version: ^3.9.0
* Platform: iOS and Android
* OS version: any
* Device manufacturer / model: any
* React Native version (`react-native -v`): 0.61.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 BackgroundGeolocation.ready(
            {
                locationAuthorizationRequest: 'Always',
                disableLocationAuthorizationAlert: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: Number(passingBooksMovingDistanceMeters),
                stopTimeout: 10,
                debug: true, //TODO: MAke this false while merging
                logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
                stopOnTerminate: false,
                startOnBoot: true,
                autoSync: false,
                enableHeadless: true,
                motionTriggerDelay: 30000,
            },
```

## Expected Behavior

onLocation runs whenever getCurrentLocation runs 

## Actual Behavior

I don't want to run onLocation when getCurrentLocation is used

## Context

I am using getCurrentLocation in a page but it results in running the onLocation function as written in the docs.
Is there any way to not let the onLocation function run when getCurrentLocation runs. I know about useSignificantChanges only but I only want the particular getCurrentLocation no to trigger the onLocation.

</details>

**Comment by christocracy** [comment]
> Is there any way to not let the onLocation 

No
