### ISSUE TITLE
Get location after every 15 min in background or app killed.

### ISSUE THREAD

**Issue by talibbk** [transistorsoft/react-native-background-geolocation#1270]
## Your Environment
* Plugin version:^3.9.0
* Platform: iOS and Android
* OS version:any
* Device manufacturer / model:any
* React Native version (`react-native -v`):0.61.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```
BackgroundGeolocation.ready(
            {
                locationAuthorizationRequest: 'Always',
                disableLocationAuthorizationAlert: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: Number(passingBooksMovingDistanceMeters),
                stopTimeout: 10,
                debug: true, //TODO: MAke this false while merging
                logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
                stopOnTerminate: false,
                startOnBoot: true,
                autoSync: false,
                enableHeadless: true,
                motionTriggerDelay: 30000,
            },
## Expected Behavior

I need to get current location every 15min even when app is killed or in background regardless of device in motion or stationary.
## Steps to Reproduce

1.
2.
3.
4.

## Context

After every 15min min get device's current location.
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Use [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch) for this.

**Comment by madisvain** [comment]
@christocracy could you please help us understand if we should also implement [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch)

We have been currently trying to implement this with the [heartbeatInterval](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#heartbeatinterval) but its quite unreliable.

What would be the main difference or arguments agains / for using one or other solution? What we are trying to do is notify our web app that indeed even without any location changes the driver is on duty and receiving new orders.

Would react-native-background-fetch also be preferable to background geolocation heartbeat catching in this use case?
