### ISSUE TITLE
backgroundPermissionRationale not showing custom message.

### ISSUE THREAD

**Issue by awasser-omnispear** [transistorsoft/react-native-background-geolocation#1278]
I've set the backgroundPermissionRationale parameter as shown in the config below.  However, when running the app, a generic change location access message shows instead.

## Your Environment
* Plugin version: 4.0.2
* Platform: iOS or Android: Android
* OS version: 11
* Device manufacturer / model: Pixel 4 (Android Simulator)
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    debug: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 1,
    url: globals.socketServerUrl + '/driver/android-location',
    triggerActivities: 'in_vehicle, on_bicycle, on_foot, running, walking',
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: {
        title: 'Allow {applicationName} to access this device\'s location even when closed.',
        message: 'This app uses location data to record, report, and track your deliveries in real-time even when the app is closed or not in use.  To enable this, Please choose "Change to {backgroundPermissionOptionLabel}"',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
    },
    autoSync: true,
    autoSyncThreshold: 1,
    stopOnTerminate: false,
    stopTimeout: 99999999,
    startOnBoot: true,
    enableHeadless: true,
    stopOnStationary: false,
    isMoving: true
}
```

## Expected Behavior

It should show the message put in the backgroundPermissionRationale
## Actual Behavior

It shows a generic message: "This app wants to access your location all the time, even when you're not using the app."
## Steps to Reproduce

1. N/A

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
```

</details>

**Comment by christocracy** [comment]
Show me a screenshot.  I don't see any such text within the plugin's source.  The defaults are:

```java
private static final String DEFAULT_TITLE = "Allow {" + TEMPLATE_TAG_APPLICATION_NAME + "} to access this device's location even when closed or not in use?";
    private static final String DEFAULT_MESSAGE = "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.";
```

**Comment by awasser-omnispear** [comment]
![Uploading Screenshot_1616796160.png…]()

**Comment by awasser-omnispear** [comment]
![Screenshot_1616796160](https://user-images.githubusercontent.com/31863006/112698950-3198c700-8e61-11eb-93f0-dde6b90b60f3.png)

**Comment by mikehardy** [comment]
I bet that's targetSdk still 29 not 30. With the deadline looming I'm finally working through this myself and I think that's one of the items that can alter behavior

**Comment by christocracy** [comment]
For best performance, you want to use `targetSdkVersion 30`.

**Comment by christocracy** [comment]
The dialog you're seeing here is the stopgap one produced by the OSz.  This is not backgroundPermissionRationale.

**Comment by awasser-omnispear** [comment]
Alright. Thanks @mikehardy and @christocracy!  I'll work on migrating to sdk 30 and report back.

**Comment by awasser-omnispear** [comment]
Migration to SDK 30 solved this issue, and the custom message now appears.
Thanks very much!
