### ISSUE TITLE
 Cannot get background location when application is killed in iOS 14.4.1 

### ISSUE THREAD

**Issue by arkenyazilim** [transistorsoft/react-native-background-geolocation#1279]
## Your Environment
* Plugin version: 3.10.0
* Platform: iOS
* OS version: 14.4.1
* Device manufacturer / model: iPhone 12 Pro
* React Native version (`react-native -v`): 0.62..2
* Plugin config
   desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 40,
      stopTimeout: 5,
      showsBackgroundLocationIndicator: true,
      preventSuspend:true,
      heartbeatInterval:60,
      //locationUpdateInterval: 7000,
      //Activity Recognition
      notification: {
        title: "Konum",
        text: "JaviPos konum izleme aktif.",
      },
      //Application config 
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      autoSync: true,
      batchSync: false,
      httpTimeout: 5000,
      maxRecordsToPersist: 1,
      maxDaysToPersist: 1,
      enableHeadless: true,
```

## Expected Behavior
<!--- Tell us what should happen -->
the app continues to take location even in the event of being killed.

## Actual Behavior
<!--- Tell us what happens instead -->
On iOS device the location sending process ends when the application is killed. Positioning does not activate again. The problem is only experienced when the app is dead. Position is taken without any problem while the application is active or in the background.



## Context
When the application is open, background or dead, we take the user's location and post it to the url. 
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md and https://github.com/transistorsoft/react-native-background-fetch/ blob / master / docs / INSTALL-AUTO-IOS.md # configure-background-capabilities The application on this link has been configured.

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I think you're jumping to conclusions.

**Comment by arkenyazilim** [comment]
We are getting it for now. preventSuspend: true,
heartbeatInterval: 60 Additional solutions offered for now.

**Comment by christocracy** [comment]
preventSuspend is not required for the plugin to work.  I don't recommend using that with iOS.

iOS heartbeat halts when app is terminated.

**Comment by arkenyazilim** [comment]
preventSuspend: true,
HeartbeatInterval: 60, before adding, after the application was killed, 200 meters were moved, but the location was not taken. Then, when we added these parameters and we got a result, we thought that the reason was that these parameters were not available. I performed the steps in the url you uploaded one by one.

**Comment by arkenyazilim** [comment]
OK thanks. We will do a test again. but until it detects this situation, preventSuspend will not have a negative effect on the application, right?

**Comment by christocracy** [comment]
Did you read the :warning: in the API docs for `Config.preventSuspend`?

**Comment by arkenyazilim** [comment]
Of course I did. When I worked like this, a question mark arose in my mind. Thank you I got the answer.
