### ISSUE TITLE
onLocation runs twice at the beginning unwantedly

### ISSUE THREAD

**Issue by Ruzen1** [transistorsoft/react-native-background-geolocation#1280]
the onLocation function runs twice even if I havent used onMotionChange, getCurrentPosition and watchPosition.
I know it runs as per the location updated . But wasnt it be called just once at the very beginning?

## Your Environment
* Plugin version: ^3.9.0
* Platform: iOS and Android
* OS version: any
* Device manufacturer / model: any
* React Native version (`react-native -v`): 0.61.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 BackgroundGeolocation.ready(
            {
                locationAuthorizationRequest: 'Always',
                disableLocationAuthorizationAlert: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                stopTimeout: 10,
                debug: true, //TODO: MAke this false while merging
                logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
                stopOnTerminate: false,
                startOnBoot: true,
                autoSync: false,
                enableHeadless: true,
                motionTriggerDelay: 30000,
            },
```

## Expected Behavior

onLocation should run only once at the first startup of the app

## Actual Behavior

onLocation is running twice unwantedly even if am not using any onMotionChange, getCurrentPosition and watchPosition.
I know it runs as per the location updated . But wasnt it be called just once at the very beginning?

## Context

I am trying to call the onLocation only once when the app gets started at the very beginning.

</details>

**Comment by christocracy** [comment]
See [Location.sample](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.location.html#sample).

Also see [onLocation](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#onlocation

![](https://dl.dropbox.com/s/hbu4tfzlvyalmb9/Screen%20Shot%202021-03-29%20at%209.42.54%20AM.png?dl=1)

**Comment by Ruzen1** [comment]
@christocracy  Hey Chris, Thank you for your response. It was very helpful.
How can I know that the onLocation was triggered by the getCurrentPosition? I checked the location schema but I don't find anything that would say that it was triggered by getCurrentPosition. Could you please share me some ideas if there is any way?
Thank you

**Comment by christocracy** [comment]
```javascript
BackgroundGeolocation.onLocation((location) => {
  if (location.extras.getCurrentPosition) {
    console.log('- location is from getCurrentPosition');
  }
  if (location.sample == true) {
    console.log('- location is a sample');
  }
});

BackgroundGeolocation.getCurrentPosition({
  extras: {
    getCurrentPosition: true
  }
});
```

**Comment by Ruzen1** [comment]
Thank you  very much , Sir!
