### ISSUE TITLE
Timestamp of the location out-of-sync of the capture timestamp

### ISSUE THREAD

**Issue by mcatel** [transistorsoft/react-native-background-geolocation#1281]
## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: Sansung J8
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        locationUpdateInterval: 5000,
        distanceFilter: 50,
        stationaryRadius: 25,
        stopOnTerminate: false,
        startOnBoot: false,
        disableElasticity: true,
        enableHeadless: true,
        heartbeatInterval: 120,

        activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
        allowIdenticalLocations: true,

        autoSync: true,
        batchSync: true,

        disableMotionActivityUpdates: true,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          title: 'Permitir que {applicationName} acesse o local deste dispositivo em segundo plano?',
          message: `Para rastrear sua atividade em segundo plano,
          ative a permissão de localização {backgroundPermissionOptionLabel}`,
          positiveAction: 'Mude para {backgroundPermissionOptionLabel}',
          negativeAction: 'Cancelar',
        },
        locationAuthorizationAlert: {
          titleWhenNotEnabled: 'Ei, serviços de localização não habilitados',
          titleWhenOff: 'Ei, serviços de localização OFF',
          instructions: "Você deve habilitar 'Sempre' nos serviços de localização, amigo",
          cancelButton: 'Cancelar',
          settingsButton: 'Configurações',
        },

        foregroundService: true,
        notification: {
          title: 'Go2Route - Motorista',
          text: 'Serviço de localização rodando em segundo plano',
          color: '#ED682F',
          largeIcon: 'drawable/icon',
          smallIcon: 'drawable/icon',
        },

        pausesLocationUpdatesAutomatically: false,
        showsBackgroundLocationIndicator: true,

        url,
        httpRootProperty: '.',
        locationTemplate: '{"latitude": <%= latitude %>,"longitude": <%= longitude %>,"velocidade": <%= speed %>,"dataEvento": "<%= timestamp %>","dataEquipamento": "<%= timestamp %>"}',
        headers: {
          'Content-Type': 'application/json',
          Authorization: loginJson.token,
          Companies: companies,
        },
        extras: {
          placa: storageLicensePlate,
        },
      }, () => { setIsReady(true); });
```

## Expected Behavior

Service send the position with the date it was picked up.

## Actual Behavior

In places where the connection is stable it works perfectly as shown in the image below

![](https://cdn.discordapp.com/attachments/749010215231553739/827218438811549756/unknown.png)

However, where the connection is weak, the service is sending the position with the date on which it is able to carry out the sending, causing some "spikes", as shown in the image below.

![](https://cdn.discordapp.com/attachments/749010215231553739/827219222643736626/unknown.png)

## Steps to Reproduce

1.
2.
3.
4.

## Context

We are having problems with "noise data" and we have already applied the kalman filter, which resulted in a better trace, but it still persists. We believe that the position has the wrong date.

Is there a way to send the date according to the date we captured the location?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Is there a way to send the date according to the date we captured the location?

See Config.enableTimestampMeta.

**Comment by Felipedelima123** [comment]
Hey @christocracy this really does help me too, but this config is only accessible on the event, not on the sync template, can you help us for this be accessible on the send template? Will be a lot of work for us implement the send and sync positions to the backend ourselves just because of this. The current send and sync is working perfectly.

**Comment by christocracy** [comment]
You've posted this to the public repo.  I can make it available but it will first appear in the private repo.  If you're installing the plugin from public npm version, you won't see it for about 3 months.

**Comment by Felipedelima123** [comment]
@christocracy no problem, we can change the public to the private, can you point me for the docs of how use it?

**Comment by christocracy** [comment]
See the readme of the private repo.

**Comment by Felipedelima123** [comment]
@christocracy OK, do you have any idea when it will be available?

**Comment by christocracy** [comment]
Please post a feature request at the private repo,
