### ISSUE TITLE
Extras are empty

### ISSUE THREAD

**Issue by tonygomez** [transistorsoft/react-native-background-geolocation#1282]
The GPS location extras is empty.  We are expecting extras from a mock location via Trimble mobile manager (see last section on this page for extras they are sending https://help.trimblegeospatial.com/TMM/Third-party-apps.htm)

## Your Environment
* Plugin version: 4.0.2
* Platform: Android
* OS version: Android 11
* Device manufacturer / model: Samsung Galaxy Tab S6 Lite / SM-P610
* React Native version (`react-native -v`): 0.63.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.getCurrentPosition(
      {
        persist: true,
        samples: 1,
      },
      (position) => {
        const {latitude, longitude, altitude} = position.coords;
        updateItem({key: 'latitude', value: latitude.toString()});
        updateItem({key: 'longitude', value: longitude.toString()});
        updateItem({key: 'altitude', value: altitude.toString()});

        if (position.extras && position.extras !== {}) {
          updateItem({
            key: 'gpsExtras',
            value: JSON.stringify(position.extras),
          });
        }
      },
      (error) => {
        // console.warn('- getCurrentPosition error: ', error);
        // setPointData(JSON.stringify(error));
        showErrorToast(`ERROR: ${error.message}`);
      },
    );
```

## Expected Behavior
We expected the Location extras to be populated

## Actual Behavior
The extras are empty

## Steps to Reproduce
1. Start trimble mobile manager (https://help.trimblegeospatial.com/TMM/Home.htm)
2. Confirm mock location sharing is enabled on android
3. Open our app and receive position information
4.

## Context
I am trusting that Trimble mobile manager is sending the extras and somehow bg is not receiving them.  I used your sample android app and also confirmed extras are empty there. (hello world sample).

Your help is greatly appreciated!

## Debug logs

None

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You're doing it wrong and I have no idea what a "Timble Mobile Manager" is.

I have no idea what this `updateItem` is supposed to do.

There is nothing wrong with the plugin's `extras`.

**Comment by tonygomez** [comment]
"You're doing it wrong "
@christocracy can you please elaborate on what we are doing wrong?

**Comment by tonygomez** [comment]
@christocracy 

This is what I was looking for
https://github.com/tonygomez/react-native-geolocation/commit/6cd9a64f26ed0df40b663c4b03b58c6265e9ab52

**Comment by christocracy** [comment]
I still have no idea what you're expecting.  The plugin doesn't provide extras from foreign mock location apps.

If you're trying to figure out if a location is mocked, see API docs [Location.mock](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.location.html#mock)

```javascript
BackgroundGeolocation.onLocation((location) => {
  console.log('- Mock location: ', location.mock);
});
```

**Comment by tonygomez** [comment]
That is the issue you do not forward extras from a mock location. I don't know if it works from a non-mock location since I cannot test that at the moment.

What does work is the link I sent in a previous message.  I added this bit of code to the community geolocation package and works great from a mock (and I am assuming non-mock) location.

**Comment by christocracy** [comment]
The plugin's `Config.extras` / `Location.extras` has nothing at all to do with `android.location.Location.extras`

**Comment by tonygomez** [comment]
> The plugin's `Config.extras` / `Location.extras` has nothing at all to do with `android.location.Location.extras`

Yep. That is what dawned on me. The naming is so similar it was a bit confusing. I initially saw the Location.extras and assumed this was from the GPS extras.  After looking closer I saw config extras and put the two together.

You have a fantastic product and I would like to use it for future projects but NOT having gps extras is a show-stopper for us.  Do you think that you can forward the GPS extras?

Thanks!

**Comment by christocracy** [comment]
>NOT having gps extra

In production (ie: not from a Mock location app), locations come from `FusedLocationProvicerClient`.  There are no "GPS extras".

**Comment by tonygomez** [comment]
> > NOT having gps extra
> 
> In production (ie: not from a Mock location app), locations come from `FusedLocationProviderClient`. There are no "GPS extras".

To clarify, this does have a production use case.  This is not simply for testing or debugging.  A mock location can be used when a third party application pre-processes the data and forwards it to you.

In my case trimble (and others doe the same) corrects the gps location so that we get centimeter level accuracy and forwards the gps data to other apps on the device. It does this via by setting itself as a mock provider.

This is very common in the construction / survey industry.

Thanks for the update!
