### ISSUE TITLE
Update docs with functional & hook based approach

### ISSUE THREAD

**Issue by KPS250** [transistorsoft/react-native-background-geolocation#1283]
Please update docs with a functional & hook based approach.

## Your Environment
Not required

## Expected Behavior
Not required

## Actual Behavior
Not required

## Steps to Reproduce
Not required

## Context
Need to use functional approach instead of class-based component

## Debug logs
Not required

**Comment by christocracy** [comment]
Why??

Not going to happen.

**Comment by sohaibjaved44** [comment]
@christocracy It is needed as most of RN dev went to functional components
