### ISSUE TITLE
Best solution to periodically fetch the location in an App 

### ISSUE THREAD

**Issue by annucy** [transistorsoft/react-native-background-geolocation#1285]
## Your Environment
* Plugin version:3.2.2
* Platform: iOS and Android
* OS version: Android above 6.0, IOS above 12
* React Native version (`react-native -v`): 61.5
* Plugin config

## Context
This is more of a query - What is the best solution to periodically (say 17 mins) fetch the location in an App(even when App is in background or app is not in memory)

Approach 1 - use heartbeat Interval - for the event to occur every 17 mins , and do a getPosition to read the current location
Approach 2 - WatchPosition with an interval for 17 mins, and get the position.

Also I want to know whether this approach will work for both android and IOS even when app not in memory, provided I have given stopOnTerminate as false.

**Comment by christocracy** [comment]
- Do **NOT** use `watchPosition` when your app is in the background.  This method is designed for use **only in the foreground**.
- It is *impossible* to have periodic code run on iOS when the app is terminated.
- use `react-native-background-fetch` (already included as a dependency).

**Comment by annucy** [comment]
> * Do **NOT** use `watchPosition` when your app is in the background.  This method is designed for use **only in the foreground**.
> * It is _impossible_ to have periodic code run on iOS when the app is terminated.
> * use `react-native-background-fetch` (already included as a dependency).

But, it is mentioned as the following in react-native-background-fetch
When your app is terminated, iOS no longer fires events — There is no such thing as stopOnTerminate: false for iOS.
So I believe, this only works for android as you said.

So, coming to my problem, i need only location update to be sent to my server with a periodicity of 17 mins. What would be the best solution for this? In your demo video, even after swiping the app from memory, we could get the location update.

Can I use onLocation callback, but only send the location as per my required periodicity(by putting some logic for this).

**Comment by christocracy** [comment]
When an iOS app is terminated, the **only** thing that will re-awaken your app is to move *at least 200 meters*.

You **cannot** run periodic code when an iOS is terminated.  There is no solution in the universe to do that.

**Comment by christocracy** [comment]
This plugin is designed to track devices **ONLY** when the device is detected to be **moving**.  See Wiki *Philosophy of Operation*.

When the device is *stationary*, the plugin does not record locations.  If you want to do that, it's your responsibility to implement *hearbeat* or `react-native-background-fetch` and execute `BackgroundGeolocation.getCurrentPosition` as desired.

And for iOS, as stated above, when user terminates your app, you **cannot** hear from it again until the device *moves* at least 200 meters.

**Comment by annucy** [comment]
> When an iOS app is terminated, the **only** thing that will re-awaken your app is to move _at least 200 meters_.
> 
> You **cannot** run periodic code when an iOS app is terminated. There is no solution in the universe to do that.

Ok Thanks!. So once App is terminated and the devices moves some distance, we will start getting location updates again.

**Comment by christocracy** [comment]
Read the API docs `Config.stopOnTerminate`.

**Comment by annucy** [comment]
> Read the API docs `Config.stopOnTerminate`.

Thanks for the detailed explanation.

**Comment by christocracy** [comment]
There is over 6 years of built-up knowledge in the docs.  It is very important to consult the docs.
