### ISSUE TITLE
Manually refresh tokens in native code

### ISSUE THREAD

**Issue by LadislavBohm** [transistorsoft/react-native-background-geolocation#1286]
This is more of a question that bug I hope it's ok. Main description is below in Context.

## Your Environment
* Plugin version: 4.0.1
* Platform: both
* OS version: A11, iOS14
* Device manufacturer / model: any
* React Native version (`react-native -v`): 64
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    debug: environment.name === 'DEVELOPMENT',
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    maxDaysToPersist: 100,
    stationaryRadius: 25,
    heartbeatInterval: -1,
    distanceFilter: 50,
    useSignificantChangesOnly: false, //set this to true in order to save energy drastically
    fastestLocationUpdateInterval: 10 * 2000, //once every 20 seconds
    disableElasticity: true,
    stopTimeout: 5,
    stopOnStationary: false,
    stopOnTerminate: false,
    startOnBoot: true,
    forceReloadOnBoot: false,
    persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
    foregroundService: true,
    allowIdenticalLocations: false,
    locationAuthorizationRequest: 'Always',
    autoSync: true,
    httpRootProperty: '.', //put data directly into root
    batchSync: true,
    autoSyncThreshold: 3, //send locations in batches of 3
    locationsOrderDirection: 'ASC',
    method: 'POST',
    url: `${environment.apiUrl}/api/tracking/batch`,
    extras: undefined,
    locationTemplate: locationTemplate,
    geofenceTemplate: '',
  }
```

## Expected Behavior
We are using MSAL OAuth on our API which is an external Identity provider by Microsoft. I cannot use built-in helper for handling JWT flow. I want to ideally continuously send locations to server even when app is in background/not-running because access token has short expiration.

## Actual Behavior

If I handle onHttp event in JS I can only do that using headless JS on Android. So there doesn't seem to be a JS-only way of doing this on both platforms.

## Steps to Reproduce
1. start tracking
2. kill app
3. locations won't get sent once access token expires

## Context
What I implemented so far is this:

Two native listeners (in Swift and Java) that are listening to onHttp native event. They check whether response is 401, perform token refresh, set new token and call sync on plugin.

1. I would like to ask whether this is generally correct approach to handle this?
2. Is it ok to register these events (onHttp) even before plugin "ready" is called? I do that in MainApplication (Android) and AppDelegate (iOS)
3. Is my java/swift code for updating headers section of plugin configuration correct?
```
    private void setNewAccessToken(String accessToken) {
        TSConfig.getInstance(context)
                .updateWithBuilder()
                .setHeader("authorization", "Bearer " + accessToken)
                .commit();
        //call manual sync with new token
        BackgroundGeolocation.getInstance(context).sync();
    }
```
```
  private func setNewTokenAndSync(accessToken: String) -> Void {
    let tsConfig = TSConfig.sharedInstance();
    let headers: [AnyHashable: Any] = [
      "authorization": "Bearer " + accessToken,
    ]
    tsConfig?.setValue(headers, forKey: "headers");
    TSLocationManager.sharedInstance()?.sync(self.onSyncSuccess(_:), failure: self.onSyncFailure(_:));
  }
```
4. Subsequent calls to setConfig/ready from JS will merge configuration with what is currently configured, is that correct? So  my headers section set from native code should not get overwritten.

**Comment by christocracy** [comment]
You don't need to use native code.

See API docs `Config.headers`.  Configuring an authorization token is exactly what `Config.headers` was designed for.

You will listen to `onHttp` event for `403` errors.  That will be your cue to refresh your token, using `setConfig` to apply new `Config.headers`.

**Comment by LadislavBohm** [comment]
But this JS onHttp event will not work when app is killed (at least on iOS), right? I know I can set it from JS but I would like the refresh to work even after phone reboot and those cases.

**Comment by christocracy** [comment]
For iOS, in order for an onHttp event to fire, a location must have been recorded.  In order for a location to have been recorded, you app will must have been alive.

For Android, see api docs Config.enableHeadless.

**Comment by LadislavBohm** [comment]
Thanks for the info, looks like I should have asked before I already implemented all that and spare myself of one-day Swift speed course.
