### ISSUE TITLE
What is `accuracy` inside `coords` in `Location` object

### ISSUE THREAD

**Issue by kiddkevin00** [transistorsoft/react-native-background-geolocation#1287]
## Your Environment
N/A

## Expected Behavior

Not a bug

## Actual Behavior

Not a bug

## Steps to Reproduce
N/A

## Context

What is `accuracy` inside `coords` in `Location` object? For example, I get `{ ... coords: { accuracy: 30 } }`. What 30 means?

## Debug logs

N/A

**Comment by christocracy** [comment]
A geolocation is not a simple point in space.  It's a circle of probability with radius `accuracy`.

In reality, the device's actual position is somewhere inside that circle.

**Comment by kiddkevin00** [comment]
Oh I see so 30 means 30 centimeters or inches? Thanks

**Comment by christocracy** [comment]
meters.

**Comment by ChrisWiles** [comment]
@christocracy so 100% probability that the location is within the accuracy radius?

**Comment by christocracy** [comment]
>so 100% probability that the location is within the accuracy radius?

Accuracy is provided by the native iOS and Android APIs.  Here is what [Android Location.getAccuracy()](https://developer.android.com/reference/android/location/Location#getAccuracy()) and iOS [CLLocation.horizontalAccuracy](https://developer.apple.com/documentation/corelocation/cllocation/1423599-horizontalaccuracy) say.
