### ISSUE TITLE
Is there anyway to stop the first location coming when the user opens my app?

### ISSUE THREAD

**Issue by Ruzen1** [transistorsoft/react-native-background-geolocation#1288]
## Your Environment
* Plugin version: ^3.9.0
* Platform: iOS or Android
* OS version: any
* Device manufacturer / model: any
* React Native version (`react-native -v`): 0.61.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
            {
                locationAuthorizationRequest: 'Always',
                disableLocationAuthorizationAlert: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                stopTimeout: 10,
                debug: false,
                logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
                stopOnTerminate: false,
                startOnBoot: true,
                autoSync: false,
                enableHeadless: true,
                motionTriggerDelay: 30000,
                preventSuspend: true, //iOSがアプリをsuspendしないように
            },
            async state => {
                if (!state.enabled) {
                    const locationPermission = await Permission.checkPermissionLocation()
                    if (locationPermission) {
                        BackgroundGeolocation.start()
                    }
                }
            },
        )
```

## Expected Behavior

I don't want the library to get the first location as soon as the app is opened.
## Actual Behavior

Whenever I open my app, I get a location as soon as I open my app.
## Steps to Reproduce

1.
2.
3.
4.

## Context

I am actually trying to not get the location as soon as  the app is opened.However, I do want the plugin running.
Is there any way I can differentiate the only first location when the app is opened? Please note the user doesnt make the location permission to always.
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Ruzen1** [comment]
@christocracy Hey Chris,
 Is there any way to distinguish the locations coming in after the written distance filter value and the location which comes in when I first open the app? 
 Your co-operation is highly appreciated.
 Thank you

**Comment by christocracy** [comment]
Why are you even concerned with this?

**Comment by Ruzen1** [comment]
@christocracy Thank you for the interest.
Actually, the app sends a notification when there is a location gained. 
We want the notification to occur but not when the app is started.

**Comment by christocracy** [comment]
No, there is no way to prevent the first location being recorded.  It is *required* for the plugin to know exactly where it is when the app is started.

**Comment by Ruzen1** [comment]
@christocracy I see. Thanks, mate. 
One last question, is there a way to delay the first location, then?

**Comment by christocracy** [comment]
> is there a way to delay the first location, then?

No.
