### ISSUE TITLE
How to show the request-location-permission dialog right after our permission-description page

### ISSUE THREAD

**Issue by kiddkevin00** [transistorsoft/react-native-background-geolocation#1289]
## Your Environment

* Platform: Both iOS and Android

## Expected Behavior

We want the 2 request-location-permission dialogs (one for [Alow While Using App] and the other for [Change to Always Allow]) on iOS as well as 1 request-location-permission dialog on Android to pop up right after our permission-description page, which is not the first page of our app.

## Actual Behavior

The dialog(s) show on the first page of the app since according to the documentation `BackgroundGeolocation.ready()` should only be called once and should be called on the first page of the app

## Steps to Reproduce

1. Call `const state = await BackgroundGeolocation.ready({...}); if (!state.enabled) await BackgroundGeolocation.start()` in the `componentDidMount` in the first page of our app

## Context

We want the 2 request-location-permission dialogs (one for [Alow While Using App] and the other for [Change to Always Allow]) on iOS as well as 1 request-location-permission dialog on Android to pop up right after our permission-description page, which is not the first page of our app.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
N/A
```

</details>

**Comment by christocracy** [comment]
See api docs `.requestPermission`

Do not execute that until `.ready` resolves.

**Comment by kiddkevin00** [comment]
Where can I find it in here:
https://transistorsoft.github.io/react-native-background-geolocation/

Should I call .start after .requestpermission?

**Comment by christocracy** [comment]
**Use the search**.
![](https://dl.dropbox.com/s/13kg3u67ana04lz/Screen%20Shot%202021-04-18%20at%206.13.19%20PM.png?dl=1)

>Should I call .start after .requestpermission?

If you're just going to call `.start()` right after calling `requestPermission`, you might as well just call just `.start()`.

`.start()` **AUTOMATICALLY** requests permission.

**Comment by kiddkevin00** [comment]
Thank you!
