### ISSUE TITLE
The permission dialog box shows up while running getCurrentPosition

### ISSUE THREAD

**Issue by Ruzen1** [transistorsoft/react-native-background-geolocation#1292]
## Your Environment
* Plugin version:^3.9.0
* Platform: iOS or Android
* OS version: any
* Device manufacturer / model: any
* React Native version (`react-native -v`): 0.61.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
            {
                locationAuthorizationRequest: 'Always',
                disableLocationAuthorizationAlert: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                stopTimeout: 10,
                debug: false,
                logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
                stopOnTerminate: false,
                startOnBoot: true,
                autoSync: false,
                enableHeadless: true,
                motionTriggerDelay: 30000,
                preventSuspend: true, //iOSがアプリをsuspendしないように
            },
```

## Expected Behavior

I don't want the permission dialog box to open when the getCurrentPosition is executed.
## Actual Behavior

Right now, even if I have decide to use it without location, when getCurrentPosition is run, it shows the permission request dialog box.

## Context

I am trying to make my app also be used without the need of location. So, I want the library to do nothing when the app has no permission granted for location or even if the location of device is turned off

</details>

**Comment by christocracy** [comment]
This isn't going to change.  

If you don't wish for permission to be requested, don't call getCurrentPosition.

**Comment by Ruzen1** [comment]
I see. Thank you @christocracy

**Comment by christocracy** [comment]
The plugin has a method to determine the current location permission.

**Comment by alessandro-bottamedi** [comment]
On iOS, Requesting getCurrentPosition the plugin asks me for location permissions always in the background, even if the app is active, shouldn't it only ask for location permissions when in use?

**Comment by christocracy** [comment]
>On iOS, Requesting getCurrentPosition the plugin asks me for location permissions always

The requests permission according to your `Config.locationAuthorizationRequest`.  If you want it to request `WhenInUse`, set `locationAuthorizationRequest: 'WhenInUse`.
