### ISSUE TITLE
Expo support for this plugin.

### ISSUE THREAD

**Issue by Sunfocus** [transistorsoft/react-native-background-geolocation#1294]
We are trying to use this plugin in expo react native project. Project is already (ejected / detached).
But when we trying to initialise the plugin using this function `BackgroundGeolocation.ready`. We are always getting below error:
`TypeError: null is not an object (evaluating 'RNBackgroundGeolocation.addEventListener')`

I have already checked the same issue also here:
https://github.com/transistorsoft/react-native-background-geolocation/issues/470
And I checked the installation again to see, if I missed any point. But all looks ok.

So I tried to create a React native CLI (not expo) project, and used the same code (attached below) that I used in expo project. And this code is working fine.  The `BackgroundGeolocation` successfully initialised and `onLocation` function also called.

## Your Environment
* Plugin version: 4.0.2
* Platform: iOS / Android (both)
* OS version: Android 9
* Device manufacturer / model: Samsung tab and simulators
* React Native version (`react-native -v`): 0.63.4 (in expo and expo version: 40.0.0) and 0.64.0 (in CLI)
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const state = await BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
      distanceFilter: 50,
      stopTimeout: 1,
      geofenceInitialTriggerEntry: true,
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true
    })
    if (!state.enabled) {
      console.log('[initGeofences] starting background geolocation...')
      await BackgroundGeolocation.start()
    }
```

## Expected Behavior
It should work in both React native EXPO and react native CLI.

## Actual Behavior
Only works in React native CLI, and not working in expo. Even we have same code.

## Steps to Reproduce
Simple just tried to initialise the `BackgroundGeolocation` on app launch.

My question:
- Is this plugin supported by expo? if yes then if there are any version

**Comment by christocracy** [comment]
See [Ejecting from Managed Workflow](https://docs.expo.io/bare/customizing/)

**Comment by Sunfocus** [comment]
It works now.
