### ISSUE TITLE
usage along with react-native-background-fetch

### ISSUE THREAD

**Issue by nasmuris** [transistorsoft/react-native-background-geolocation#1295]
## Question
Is it safe to use own `react-native-background-fetch` config along with `react-native-background-geolocation`?
In other words, since `background-fetch` is peer dependency, if I use
```
 BackgroundFetch.configure({ minimumFetchInterval: 24 hours } , customEventHandler, customTimoutHandler);
```
will it affect `react-native-background-geolocation` or not?

## Environment
* Plugin version: any
* Platform: any
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): any

**Comment by christocracy** [comment]
>will it affect react-native-background-geolocation or not?

`fetch` does *not* affect `background-geolocation`.
