### ISSUE TITLE
Help Needed- Is there a way to replace API call with Socket Connection for location updates?

### ISSUE THREAD

**Issue by KPS250** [transistorsoft/react-native-background-geolocation#1297]
The library provides a way to have endpoint configured to send location updates in killed/background/foreground state. Is there a way to replace this to socket connection since API call is heavy and at hard  & costly to scale at server level.

## Your Environment
Not Required

## Expected Behavior
Need to replace API call with socket connection

## Actual Behavior
The library has provision for API call for location update

## Steps to Reproduce
Not Required

## Context
Location update  with API:
```
      url: 'http://yourserver.com/locations',
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "X-FOO": "bar"
      },
      params: {               // <-- Optional HTTP params
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
```

**Comment by christocracy** [comment]
The plugin will not support sockets.

**Comment by zeeshan-shabbir** [comment]
@christocracy  Is This libary support websockets i:e socket Io? now

**Comment by christocracy** [comment]
No

**Comment by zeeshan-shabbir** [comment]
is there anyway one can implement sockets? I have configured with iOS and working absolutely fine . The only issue is that its calling api (server) again and again. 
I have tested for one devices what if there is 100s of devices calling same api again and again? 
there is possibility of server down.
kindly guide me.
thanks

**Comment by Nagoorkani27** [comment]
Still looking for a way. Additionally, I am facing challenges with sockets not functioning in the background of apps. Are there any updates, solutions, or alternative approaches, particularly for ensuring background functionality?
