### ISSUE TITLE
[iOS] "Always" permission no longer show up

### ISSUE THREAD

**Issue by katalityk00** [transistorsoft/react-native-background-geolocation#1298]
## Your Environment
* Plugin version: 4.0.3
* Platform: iOS
* OS version: 14.3
* Device manufacturer / model: iPhone 6s
* React Native version (`react-native -v`): 0.63.4 
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  locationAuthorizationRequest: "WhenInUse",
  locationAuthorizationAlert: {
    titleWhenNotEnabled:
      "Location permission is not set to always",
    titleWhenOff: "Location permission is not enabled",
    instructions:
      'you must set the location permission to always if you want to run the app properly',
    cancelButton: "Cancel",
    settingsButton: "Parameters",
  },
```

## Expected Behavior

I read the doc and find that we cant set always at the first run of the app so after ``  BackgroundGeolocation.start() `` I simply do 
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.setConfig(
{
    locationAuthorizationRequest: 'Always',
});
```
and it worked before
## Steps to Reproduce

1.
2.
3.
4.

## Context

I updated the version of react-native and the version of this plugin and now it recognize that the app is in "WhenInUse" and prompt me the alert but when I go to the parameters the "always" permission do not show up anymore. To do this I restart a new app so may be I miss some config required by iOS.
any idea ?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>but when I go to the parameters the "always" permission do not show up anymore

What do you mean by this?

**Comment by katalityk00** [comment]
I can't set the location permission on always
<img width="357" alt="Capture d’écran 2021-05-18 à 17 52 09" src="https://user-images.githubusercontent.com/15433584/118684411-79552280-b802-11eb-8b0c-c86885fa594b.png">

**Comment by christocracy** [comment]
The set of permissions available to your app is controlled by your `.plist` file, not the plugin's code.

See the [Setup Doc](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md#configure-usage-strings-in-infoplist)

**Comment by christocracy** [comment]
You're welcome.
