### ISSUE TITLE
showsBackgroundLocationIndicator not works in iOS

### ISSUE THREAD

**Issue by abhishekSutariya1** [transistorsoft/react-native-background-geolocation#1300]
We are implementing showsBackgroundLocationIndicator props of BackgroundGeolocation.ready() method and it’s not working in iOS. Hence  status bar not changes its appearance when it’s value is true.
## Your Environment
* Plugin version: 4.0.2
* Platform: iOS or Android: iOS
* OS version: 14.3
* Device manufacturer / model: Apple iphone 11
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
      {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 30,
        stopTimeout: 1,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        showsBackgroundLocationIndicator: true,
      },
      state => {
        if (!state.enabled) {
          BackgroundGeolocation.start(function () {
            console.log('- Start success');
           });
        }
      },
    );
```

## Expected Behavior
showsBackgroundLocationIndicator: true
// nothing happened 

## Actual Behavior
A Boolean indicating whether the status bar changes its appearance when an app uses location services in the background with Always authorization.
(https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#showsbackgroundlocationindicator)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It works fine for me.

![image](https://user-images.githubusercontent.com/14999/119114303-0b704d00-b9f4-11eb-90ec-c031c734795b.jpeg)

**Comment by christocracy** [comment]
No

**Comment by christocracy** [comment]
You know an iOS device must move *at least* 200 meters before tracking engages?  **only then** should you expect to see the indicator appear, after location-services are turned on.

**Comment by abhishekSutariya1** [comment]
It appears when getting location. Thanks
