### ISSUE TITLE
Background Location Fluctuating With a difference of 10km 

### ISSUE THREAD

**Issue by neonsec** [transistorsoft/react-native-background-geolocation#1301]
## Your Environment
* Plugin version: 3.10.0
* Platform: iOS or Android
* OS version: 9,10,11
* Device manufacturer / model: Samsung, OPPO
* React Native version (`react-native -v`): 0.63.4
* Plugin config

### Code
```
BackgroundGeolocation.getCurrentPosition({
          persist: true,
          samples: 1,
          maximumAge: 0
        }, (location) => {
  console.log("location ->",location);
        }, (error) => {
          console.warn('- getCurrentPosition error: ', error);
        });
```

## Expected Behavior
Location should not deviate when in background.  We see a huge difference in location being updated. Especially in the background

## Actual Behavior
Location is fluctuating from correct location to some random location in the span of every minutes. It happens when app is in background and jumps from one location to another location

## Context
We are getting the background current position and pushing them to servers in background

##Impact
Around 5% of our users are facing and this is affecting us in production

</details>

**Comment by christocracy** [comment]
You are allowing just samples: 1.

That in insufficient number of samples to allow the gps radio to warm up and connect to gps satellites.

The first sample returned likely comes from the low-accuracy Cell provider.

Increase samples (default is 3).

**Comment by neonsec** [comment]
Okay, we will update this to check if this solves the issue.

**Comment by neonsec** [comment]
We changed the samples to 4 but still facing the issue. 

```
BackgroundGeolocation.getCurrentPosition(
  {
    timeout: 30,
    persist: true,
    maximumAge: 5000,
    desiredAccuracy: 10,
    samples: 4,
  },
  (location) => {
    console.log(location);
  },
  (error) => {
    console.warn(error);
  }
);
```

**Comment by neonsec** [comment]
Is there a way to find the accuracy of the location? , we will not update our server if the accuracy is low

**Comment by christocracy** [comment]
Of course you can find Accuracy.

See Location in api docs for all available attributes.

**Comment by neonsec** [comment]
we see the accuracy in meters is not even close. we are seeing some device giving accuracy:50 meters but the actual deviation is  3km+

**Comment by christocracy** [comment]
The plugin is only the mail man delivering locations exactly as manufactured by the operating system.
