### ISSUE TITLE
Android BackgroundGeolocation crash while opening another app

### ISSUE THREAD

**Issue by tinmar33** [transistorsoft/react-native-background-geolocation#1302]
## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: OnePlus Nord N100
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
    {
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stationaryRadius: 10,
      stopOnTerminate: true,
      reset: true,
      foregroundService: true,
      preventSuspend: true,
      showsBackgroundLocationIndicator: true,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    } as Config,
    state => {
      if (!state.enabled) {
        BackgroundGeolocation.start().then(() => {
          BackgroundGeolocation.changePace(true)
        })
      }
    },
  )
```

## Expected Behavior

Keep the app in background without crashing

## Actual Behavior

The app is crashing with this device (I tried with 3 others Android device and I don't have the issue) when i open another app while using background location at the same time. I tried other apps like Waze, Google Maps, Runtastic and it works fine.
I tried all the steps for my device of dontkillmyapp, but it doesn't help.

**It doesn't crash if i'm not using the background location**

## Steps to Reproduce

1. Run the app on a OnePlus Nord N100
2. Run background location
3. Launch another app
4. The background location app is killed

## Context

I'm trying to use the background location to track the user positions

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
05-21 17:33:09.963 14095 14095 I my.app.bundle.id: System.exit called, status: 0
05-21 17:33:09.966 14095 14095 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
05-21 17:33:09.967  1823  1979 D ExtBatteryStatsService: ext-flush too soon, skip
05-21 17:33:09.967  1823  1979 D MyBatteryStatsHelper: ===processSingleAppUsage===
```

</details>

**Comment by christocracy** [comment]
This is not a "crash".

I have no idea what this is.  Have you googled it?

**Comment by tinmar33** [comment]
Yes but I didn't find anything for the moment

**Comment by tinmar33** [comment]
With `stopOnTerminate: false`, and the `ACCESS_BACKGROUND_LOCATION` permission, the app is no longer "killed", but it's not exactly what i need

**Comment by tinmar33** [comment]
Any update on it @christocracy ?
