### ISSUE TITLE
Sensor fusion issue w/ motion change true => reports historical location/time data

### ISSUE THREAD

**Issue by WoodburyShortridge** [transistorsoft/react-native-background-geolocation#1303]
## Your Environment
* Plugin version: 4.0.3
* Platform: iOS
* OS version: 14.4.2
* Device manufacturer / model: Apple iPhone 11
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  "autoSync": false, 
  "batchSync": true, 
  "desiredAccuracy": -1, 
  "disableLocationAuthorizationAlert": true, 
  "distanceFilter": 10, 
  "elasticityMultiplier": 1, 
  "isMoving": true, 
  "logLevel": 1, 
  "params": {
    "deviceId": "9AA8B07F-5693-4EE5-920A-88406330FA56", 
    "userId": "L9nLzzErSwp4jcYcx"
  }, 
  "reset": true, 
  "showsBackgroundLocationIndicator": false, 
  "startOnBoot": true, 
  "stopOnTerminate": false, 
  "stopTimeout": 10, 
  "url": "<my server>/api/bg"
}
```

## Expected Behavior

When the BG Geolocation starts either from user launching the app, or from a significant distance after a sleepTimeout, the onMotionChange CB is fired w/ property isMoving = true, and the location property should be the most recent/accurate. 

## Actual Behavior

When the BG Geolocation starts either from user launching the app, or from a significant distance after a sleepTimeout, the onMotionChange CB is fired w/ property isMoving = true and the location property is sometimes a random location in the distant past. The onLocationChange CB is also fired w/ an is_moving=true location that is sometimes also a matching random location in the distant past.

There seems to be some kind of sensor fusion bug going on where the wrong location obj is not being delivered on motion change trues.

Here is an example of one in a path:
![tf_lie](https://user-images.githubusercontent.com/24487544/119379731-75535580-bc85-11eb-8af6-d55dd913e206.png)
^ this motion change true has a location,time,etc. of a point very far in the past. 

And here you can clearly see the issue in my logging framework on this same motion change true event:
<img width="1201" alt="ts_lie" src="https://user-images.githubusercontent.com/24487544/119380132-ee52ad00-bc85-11eb-8501-1e8677aafc90.png">
^ the location.date (rename of TS timestamp) is 3:59 EST, however the time of actually receiving the CB/event (Client event time) is 4:43 EST. There were many proceeding location updates that had a more current time/location than this as you can see from the map plot. 

## Steps to Reproduce

1. Allow tracker to "sleep" by staying still and awaiting a motion change false
2. Travel a sig distance OR restart tracking
3. Sometimes to initial montionChange and locationChange is a random location very far in the past

## Context

Have locations in a logical order

**Comment by christocracy** [comment]
See Config.enableTimestampMeta for more time data about location.

**Comment by WoodburyShortridge** [comment]
thanks @christocracy. However, I don't believe more timestamp meta will help me. Unless you are suggesting it's the OS not TS that is reporting the incorrect location. Can you clarify? The core issue is that at 4:43 EST the onMotionChange and onLocationChange CBs both get an event that says the device is at a location it isn't and that the time of the event is 3:59 EST. This looks suspiciously like a sensor fusion issue. I.e. the wrong location is being sent on motion change true events. Can you explain why the location on these events would be one from 45 minutes ago despite having dozens of more current locations in the table. Thanks for your help, trying to wrap my head around this issue.

**Comment by christocracy** [comment]
>This looks suspiciously like a sensor fusion issue

I doubt that.  When location-services are turned on, the radios begin connecting to GPS satellites.  The iOS location API begins streaming locations from all the different providers (Cellular, Wifi, GPS) asap.  Initial locations can be old.

The plugin requests a number of location samples before settling upon the most accurate recent location.

I suggest you gather logs.  See wiki *Debugging*.  You will see in the logs these location samples arriving and being evaluated.

**Comment by WoodburyShortridge** [comment]
Thanks @chestercharles thats super helpful background. I figured "Initial locations can be old", especially if the API can't get a good lock when location-services are turned on. But I am still confused why it would settle on a location that is 45mins old while there are 50+ more recent high-accuracy locations available which put the device in a completely different location?

Please let me know your thoughts and I will try to reproduce and observe the samples arriving.

**Comment by WoodburyShortridge** [comment]
I think the issue is that the location is requested with the intention of associating an accurate location to the motion change event. However it turns out that the location winds up somehow being older than even dozens of high-accuracy locations that can be found in the locations table.
