### ISSUE TITLE
Using the library to just request location permission but getting this error when release on Play Store

### ISSUE THREAD

**Issue by kiddkevin00** [transistorsoft/react-native-background-geolocation#1304]
## Your Environment
* Plugin version: N/A
* Platform: Android
* OS version: N/A
* Device manufacturer / model: N/A
* React Native version (`react-native -v`): N/A
* Plugin config

I haven't called BackgroundGeolocation.ready({...})

## Actual Behavior

I use this plugin to only do one thing so far, which is to request Always Allow location permission for iOS by calling ` BackgroundGeolocation.requestPermission()` and I do purchase the license so that I won't get a warning when launching the app on Android. But when I publish the app on Play Store, I get this error but I didn't add BACKGROUND_LOCATION in my AndroidManifest.xml file and I don't need Always Allow Location permission for now. Can you advise?
<img width="1524" alt="Screen Shot 2021-05-24 at 5 18 25 PM" src="https://user-images.githubusercontent.com/7229339/119421669-1822c880-bcb4-11eb-92e3-3d60b76c9a25.png">

## Expected Behavior

No error when releasing on Play Store when not using Always Allow location permission

## Steps to Reproduce

1. import BackgroundGeolocation, { AuthorizationStatus } from 'react-native-background-geolocation';
2. const status: AuthorizationStatus = await BackgroundGeolocation.requestPermission();
3. Not even calling BackgroundGeolocation.ready(...)
4. Release to Play Store

## Context

Release the app to Play Store

## Debug logs

<img width="1524" alt="Screen Shot 2021-05-24 at 5 18 25 PM" src="https://user-images.githubusercontent.com/7229339/119421669-1822c880-bcb4-11eb-92e3-3d60b76c9a25.png">

**Comment by christocracy** [comment]
https://link.medium.com/Y1g5frtfxgb
