### ISSUE TITLE
Android not sending location when phone is locked

### ISSUE THREAD

**Issue by bajjajjrajjesh** [transistorsoft/react-native-background-geolocation#1305]
## Your Environment
* Plugin version: 3.9.1
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung M40
* React Native version (`react-native -v`): ^0.64.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const bgConfig = {
      url: `https://app.example.com/api/offline-data`,
      autoSync: true,
      debug: true,
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      locationAuthorizationRequest: Platform.OS === 'ios' ? 'WhenInUse' : 'Always',
      preventSuspend: false,
      stopTimeout: 5,
      params: {
        orderId,
        platform: Platform.OS
      },
      locationsOrderDirection: "ASC",
      maxDaysToPersist: 14,
      showsBackgroundLocationIndicator: true,//<~ For IOS only
      debug: false,
      enableHeadless: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,
      notification: {
        sticky: true,
        title: 'App Tracking',
        text: 'Your live trip is started.',
        channelName: 'App Tracker',
        smallIcon: 'mipmap/ic_notification', // <-- defaults to app icon
        largeIcon: 'mipmap/ic_launcher',
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
      },
    };
```

## Expected Behavior

App should track and send location when phone is locked
## Actual Behavior

When I lock the phone after few second and sometimes after few minutes location tracking stops working.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you observing your logs?

**Comment by bajjajjrajjesh** [comment]
I am running this on my device and use lockito app and its not connected to my system. Other then finding log what else can be possible issue. I will try to find out the log and share with you.

**Comment by christocracy** [comment]
See wiki "*Debugging*".

**Comment by bajjajjrajjesh** [comment]
Hi @christocracy I have updated the log in the task please check and update for any suggestions

**Comment by christocracy** [comment]
Have you consulted http://dontkillmyapp.com for your device?

**Comment by bajjajjrajjesh** [comment]
I am not sure what you mean by that?

**Comment by christocracy** [comment]
Click the link and read the website.

**Comment by bajjajjrajjesh** [comment]
Are you suggesting to integrate with this plugin? I saw this website and it says Samsung device won't run background app? does it means you plugin will not work in samunsg devices?

**Comment by christocracy** [comment]
I regularly test on 3 Samsung devices.  Consult http://dontkillmyapp.com and edit your device Settings as directed.

**Comment by bajjajjrajjesh** [comment]
I saw this website and it is asking for lot of manual changes to be done in the device setting. This way it's very difficult to use the app. Even after all this changes app is not working after locking the device.

**Comment by bajjajjrajjesh** [comment]
I tried your demo app after making all the setting changes as per http://dontkillmyapp.com/ even after that its not working

**Comment by christocracy** [comment]
The problem is with your device, not the plugin's code.  I field-test almost daily on the following device without problems:

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 12
- Samsung Galaxy S20 FE @ 11.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by bajjajjrajjesh** [comment]
What's the problem with my device? do you suggest if I reset my phone it will start working properly?

**Comment by bajjajjrajjesh** [comment]
Also how many of your testing device is android 11 and also how many are Samsung and android 11?

**Comment by christocracy** [comment]
>What's the problem with my device 

I have no idea.  I suggest you closely observe your `$ adb logcat` logs.

**Comment by bajjajjrajjesh** [comment]
I sent you my log. Shall send my log after after this setting changes?

**Comment by christocracy** [comment]
I suggest **YOU** closely observe your logs and look for problems.  When you find something interesting, grab that part of your logs and let me know.

**Comment by bajjajjrajjesh** [comment]
I am not sure what should I see in that log. Anything specific I should look in log? also to generate log using your demo app?

**Comment by bajjajjrajjesh** [comment]
Please check the log from your demo app.
[Uploading background-geolocation-demo-app.log…]()

**Comment by christocracy** [comment]
>05-26 20:31:55.912 DEBUG [TrackingService a] 🐞 Mock location detected with motion-activity STILL:  stopTimeout timer would normally be initiated here 🐞.

You are testing with *Mock Location App*.  Go outside for a 1km walk  and test with *real* movement.

**Comment by bajjajjrajjesh** [comment]
But your docs advise that we can use lockito to test the app?? I can go out and test in real also but this is not a solution to do a proper  testing specially to test large distance and few hours or days of tracking.

**Comment by christocracy** [comment]
Just go do it.

**Comment by bajjajjrajjesh** [comment]
I walked for some 500 meters and it was tracking i guess. I could figure out by debug sound that its working. I will need to do a longer ride to identify if it's working for properly or not. 

If it works whats the solution to test the app? Also how is its possible same app is working fine on android 10 with mock location app and working on android 11
