### ISSUE TITLE
BG location Not Getting frequently

### ISSUE THREAD

**Issue by abhishekSutariya1** [transistorsoft/react-native-background-geolocation#1306]
When location service is enabled and the app is in the background after some time if the user open google map then not getting BG location update.

- User is in the background for around 1 hour after that we cannot be getting the location.
 is there any specific config that we have to do then let us know?

## Your Environment
* Plugin version: 4.0.2
* Platform: iOS or Android: ios
* OS version: (ios 14.4)
* Device manufacturer / model: Apple 
* React Native version (`react-native -v`): 0.63.4
* Plugin config

```
BackgroundGeolocation.ready(
      {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 30,
        stopTimeout: 1,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: true,
        startOnBoot: true,
        showsBackgroundLocationIndicator: true,
        locationAuthorizationAlert: {
          titleWhenNotEnabled: "Location-services not enabled",
          titleWhenOff: "Location-services OFF",
          instructions: "You must enable 'Always' in location-services",
          cancelButton: "Cancel",
          settingsButton: "Settings"
        },
        method: 'POST',
        url: `${Config.API_URL}/api/trucks/notify-driver-location`,
        batchSync: false,
        autoSync: true,
        reset: true,
        headers: {
          Authorization: userStore.authToken,
        },
        extras: {
          e_truckId: truckId,
        },
        params: {
          id: truckId,
          offset: moment().zone(),
          dispatch_id: dispatchId,
        },
      },
      state => {
        if (!state.enabled) {
          BackgroundGeolocation.start(function () {
            console.log('- Start success');
          });
        }
      },
```

## Expected Behavior
We got location update continues in the background.

## Actual Behavior
we can not get location update in this case ( When location service is enabled and the app is in the background after some time if user open google map then not getting BG location update ).

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki "Debugging".  Learn to observe plugin logs.

**Comment by abhishekSutariya1** [comment]
I have observed the logs below & PFA.
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =    {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didLaunchInBackground = 0;
    didRequestUpgradeLocationAuthorization = 1;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 30;
    elasticityMultiplier = 1;
    enableTimestampMeta = 0;
    enabled = 1;
    extras =    {
        "e_truckId" = 6;
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers =    {
        Authorization = 2rW0174WCG0CYbwaC3Eb0oQ5TSdLrDkIAa2Rf3f2vLqK8vwKpO1vHHsP2JHE1ZI1;
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 1;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =    {
        cancelButton = Cancel;
        instructions = "You must enable 'Always' in location-services";
        settingsButton = Settings;
        titleWhenNotEnabled = "Location-services not enabled";
        titleWhenOff = "Location-services OFF";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "10426.41168540193";
    params =    {
        "dispatch_id" = 231;
        id = 6;
        offset = 420;
    };
    pausesLocationUpdatesAutomatically = 1;
    persistMode = 2;
    preventSuspend = 0;
    schedule =    (
    );
    schedulerEnabled = 0;
    showsBackgroundLocationIndicator = 1;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 1;
    stopTimeout = 1;
    trackingMode = 1;
    url = "https://omni-duct-server-dev.cpptl.co/api/trucks/notify-driver-location";
    useSignificantChangesOnly = 0;
}
[background-geolocation.log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/6674892/background-geolocation.log.gz)

**Comment by christocracy** [comment]
Your attached log-file is empty.

**Comment by abhishekSutariya1** [comment]
Here it is logs with log-file.

`{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =    {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didLaunchInBackground = 0;
    didRequestUpgradeLocationAuthorization = 1;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 30;
    elasticityMultiplier = 1;
    enableTimestampMeta = 0;
    enabled = 1;
    extras =    {
        "e_truckId" = 6;
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers =    {
        Authorization = 2rW0174WCG0CYbwaC3Eb0oQ5TSdLrDkIAa2Rf3f2vLqK8vwKpO1vHHsP2JHE1ZI1;
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 1;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =    {
        cancelButton = Cancel;
        instructions = "You must enable 'Always' in location-services";
        settingsButton = Settings;
        titleWhenNotEnabled = "Location-services not enabled";
        titleWhenOff = "Location-services OFF";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "29324.54037099788";
    params =    {
        "dispatch_id" = 231;
        id = 6;
        offset = "-420";
    };
    pausesLocationUpdatesAutomatically = 1;
    persistMode = 2;
    preventSuspend = 0;
    schedule =    (
    );
    schedulerEnabled = 0;
    showsBackgroundLocationIndicator = 1;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 1;
    stopTimeout = 1;
    trackingMode = 1;
    url = "https://omni-duct-server-dev.cpptl.co/api/trucks/notify-driver-location";
    useSignificantChangesOnly = 0;
}
`
[background-geolocation.log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/6690996/background-geolocation.log.gz)

**Comment by abhishekSutariya1** [comment]
Any Updates on the above logs?

**Comment by christocracy** [comment]
I see nothing unusual in these logs.  Everything looks healthy and great.
