### ISSUE TITLE
Provide constants for event names

### ISSUE THREAD

**Issue by LadislavBohm** [transistorsoft/react-native-background-geolocation#1310]
## Your Environment
* Plugin version: 4.0.3
* Platform: both
* OS version: all
* Device manufacturer / model: any
* React Native version (`react-native -v`): 0.64

## Expected Behavior
I would expect to have some strongly typed event names if possible. Because I could not even find event names in documentation. I guess that "onLocation" event is called "location" but it was try/error process.

```
BackgroundGeolocation.onLocation(handleOnLocation);
BackgroundGeolocation.removeListener(BackgroundGeolocation.EVENT_LOCATION, handleOnLocation);
```

## Actual Behavior
I have to have a code like this and also I have to figure out event name myself.
```
BackgroundGeolocation.onLocation(handleOnLocation);
BackgroundGeolocation.removeListener('location', handleOnLocation);
```

I know this more of a "nice-to-have" issue but since the Typescript support is already very good it would be nice to have this as well.

**Comment by christocracy** [comment]
Agreed.  I'll see what I can do.

**Comment by christocracy** [comment]
This is implemented locally now.  It will be introduced here in the public repo when next merged from the private repo.

![](https://dl.dropbox.com/s/7m107lgbs3d9wcx/Screen%20Shot%202021-06-03%20at%2012.08.08%20PM.png?dl=1)
