### ISSUE TITLE
Location not send on iOS

### ISSUE THREAD

**Issue by robertoaltieri** [transistorsoft/react-native-background-geolocation#1312]
## Environment
* Plugin version: 3.10.0
* Platform: iOS
* OS version: 14.4.2
* Device manufacturer / model: iPhone10,6
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        locationAuthorizationRequest: 'Always',
        url: ENV.trackerLocation,
        authorization: {
          strategy: "JWT",
          accessToken: accessToken,
          refreshToken: refreshToken,
          refreshUrl: ENV.trackerRefreshToken,
          refreshPayload: {
            refresh_token: "{refreshToken}"
          },
          expires: expiration
        },
        backgroundPermissionRationale: PERMISSION_RATIONALE,
        reset: false,
        stopTimeout: 1,
        debug: DEBUG,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        foregroundService: true,
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        notification: {
          title: APPCONFIG.applicationName,
          text: STRINGS.trackingEngaged,
          channelName: STRINGS.recording,
          smallIcon: 'drawable/ic_notification'
        },
        heartbeatInterval: APPCONFIG.heartBeatInterval,
        enableHeadless: true,
        maxDaysToPersist: APPCONFIG.maxDaysToPersist
```

## Expected Behavior

The app should send the locations

## Actual Behavior
Very randomly, for the production build only so far, the app does not send the locations until it is uninstalled and then reinstalled

## Steps to Reproduce
Preconditions: running production build

1) start the app
2) Turn the tracking on
3) give all the permissions
4) Kill the app
5) Restart the app
6) Sometimes the tracking is OFF (BUG)
7) Even when the tracking is ON the locations are not sent to the backend (BUG)
8) In the log I can see many instances of ` ( -[TSHttpService finish:error:] Success: 0)`

## Context
In almost all cases the app works but there are random cases when the sending of the locations fails.
In the logs I see  `( -[TSHttpService finish:error:] Success: 0)`. What does that mean?
Is it true that `[TSLocationManager persistLocation:]_block_invoke INSERT: 1220A8AD-9DA1-488E-A269-81413B36C4A1` means that the location has been persisted in the database?
 Is there a way to understand what is going wrong?

## Debug logs
╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 1
╚═══════════════════════════════════════════════════════════

2021-06-06 12:17:30.460 ✅-[LocationDAO unlock]_block_invoke UNLOCKED ALL RECORDS

2021-06-06 12:17:30.462 ℹ️+[LocationAuthorization run:onCancel:] status: 3

2021-06-06 12:17:30.463 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 1220A8AD-9DA1-488E-A269-81413B36C4A1

2021-06-06 12:17:30.464 ℹ️-[TSLocationManager log:message:] [location] - [object Object]

2021-06-06 12:17:30.464 ℹ️-[TSLocationManager log:message:] [js] RNBackgroundFetch failed to start

2021-06-06 12:17:30.506 ℹ️-[TSConfig persist] 

2021-06-06 12:17:30.508 🔵-[TSLocationManager ready] 

2021-06-06 12:17:30.509 ℹ️-[TSConfig didDeviceReboot] didDeviceReboot? 1

2021-06-06 12:17:30.509 ℹ️-[TSLocationManager log:message:] [providerchange] - [object Object]

2021-06-06 12:17:30.514 ℹ️-[TSLocationManager log:message:] Ready completed state.enabled = false state.isMoving = false

2021-06-06 12:17:30.515 ℹ️-[TSConfig persist] 

2021-06-06 12:17:30.520 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2021-06-06 12:17:30.520 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════

2021-06-06 12:17:30.528 🔵-[TSLocationManager getCurrentPosition:] 

2021-06-06 12:17:30.528 🎾-[LocationManager startUpdatingLocation] ON

2021-06-06 12:17:30.535 
📍<+50.80670192,-0.04733798> +/- 65.00m (speed -1.00 mps / course -1.00) @ 06/06/2021, 12:17:30 British Summer Time

2021-06-06 12:17:30.535 🔴-[LocationManager stopUpdatingLocation] OFF

2021-06-06 12:17:30.536 
╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 1
╚═══════════════════════════════════════════════════════════

2021-06-06 12:17:30.538 ℹ️+[LocationAuthorization run:onCancel:] status: 3

2021-06-06 12:17:30.540 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: D181FA3C-FF29-402D-9FEB-559003199264

2021-06-06 12:17:30.540 ℹ️-[TSLocationManager log:message:] [location] - [object Object]

2021-06-06 12:17:30.545 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2021-06-06 12:17:30.545 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════

2021-06-06 12:17:30.966 ℹ️-[TSLocationManager log:message:] scheduleVechiclesListUpdate start

2021-06-06 12:17:30.966 ✅-[BackgroundTaskManager createBackgroundTask] 2

2021-06-06 12:17:31.188 ℹ️-[TSLocationManager log:message:] updateRegistration STARTED

2021-06-06 12:17:45.671 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager start] 
╚═══════════════════════════════════════════════════════════

2021-06-06 12:17:45.671 ℹ️-[TSLocationManager doStart:] trackingMode: 1

**Comment by christocracy** [comment]
Are you using code from the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo) and posting to `tracker.transistorsoft.com` or using your own instance of [background-geolocation-console](https://github.com/transistorsoft/background-geolocation-console)?

I suspect you're having issues wth `Authorization`.

>-[TSHttpService finish:error:] Success: 0)

Means the plugin bailed out of attempting an HTTP request, likely because the plugin is not configured with a valid `url`.

You are not showing the full logs of the plugin, which prints the config it was booted with.

**Comment by robertoaltieri** [comment]
Thank you. I'll investigate it. I'm using my own server:
```
╔═════════════════════════════════════════════
║ TSLocationManager (build 373)
╠══════════════════════════════════════════════
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =     {
        accessToken = "eyJra<redacted>";
        expires = 1622885841;
        refreshPayload =         {
            "refresh_token" = "{refreshToken}";
        };
        refreshToken = "eyJjd<redacted>";
        refreshUrl = "https://mobility-api-01.bayes.st/api/refresh_token";
        strategy = JWT;
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didLaunchInBackground = 0;
    didRequestUpgradeLocationAuthorization = 1;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 10;
    elasticityMultiplier = 1;
    enableTimestampMeta = 0;
    enabled = 1;
    extras =     {
        "app_build" = 1;
        "app_version" = "1.1.3";
        manufacturer = Apple;
        model = "iPhone10,6";
        version = "14.4.2";
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers =     {
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "5561.811763434857";
    params =     {
    };
    pausesLocationUpdatesAutomatically = 1;
    persistMode = 2;
    preventSuspend = 0;
    schedule =     (
    );
    schedulerEnabled = 0;
    showsBackgroundLocationIndicator = 0;
    startOnBoot = 0;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 1;
    stopTimeout = 5;
    trackingMode = 1;
    url = "";
    useSignificantChangesOnly = 0;
}
```

**Comment by robertoaltieri** [comment]
mmm `url = "";` I think you found my issue. Thanks

**Comment by christocracy** [comment]
I see you're configuring `reset: false`.  That should generally not be used unless you know exactly what that does.

You just remove that Config option, the default is `true`.

**Comment by robertoaltieri** [comment]
I see OK. It has been like that for more than one year but it looks like it is causing some race condition now. Anyway, I'm happy to close the ticket. I think I have all the info I needed to start investigating. Thank you for your help.
