### ISSUE TITLE
how to get location when the app in background 

### ISSUE THREAD

**Issue by ferasabufares** [transistorsoft/react-native-background-geolocation#1316]
## Your Environment
* Plugin version: 4.1.0
* Platform: Android
* OS version: 9
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.64.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
import BackgroundGeolocation from "react-native-background-geolocation";

export default class App extends Component {
  componentWillMount() {
    ////
    // 1.  Wire up event-listeners
    //

    // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.onLocation(this.onLocation, this.onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange(this.onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.onActivityChange(this.onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.onProviderChange(this.onProviderChange);

    ////
    // 2.  Execute #ready method (required)
    //
    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'http://yourserver.com/locations',
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "X-FOO": "bar"
      },
      params: {               // <-- Optional HTTP params
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        ////
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
  }

  // You must remove listeners when your component unmounts
  componentWillUnmount() {
    BackgroundGeolocation.removeListeners();
  }
  onLocation(location) {
    console.log('[location] -', location);
  }
  onError(error) {
    console.warn('[location] ERROR -', error);
  }
  onActivityChange(event) {
    console.log('[activitychange] -', event);  // eg: 'on_foot', 'still', 'in_vehicle'
  }
  onProviderChange(provider) {
    console.log('[providerchange] -', provider.enabled, provider.status);
  }
  onMotionChange(event) {
    console.log('[motionchange] -', event.isMoving, event.location);
  }
}
```

## Expected Behavior
i don't know how to get current positions when app in background 
i follow the instruction and i install it successfully 
then i use the Example 

## Actual Behavior

i got this in console 
```
[location] - {"activity": {"confidence": 100, "type": "still"}, "battery": {"is_charging": true, "level": 1}, "coords": {"accuracy": 15.8, "altitude": 1035.2, "altitude_accuracy": 3, "heading": -1, "heading_accuracy": -1, "latitude": 31.9964142, "longitude": 35.8835884, "speed": -1, "speed_accuracy": -1}, "extras": {}, "is_moving": false, "odometer": 0, "timestamp": "2021-06-08T12:54:36.586Z", "uuid": "d09e4456-8327-4b8c-a65f-3267caafab71"}


 LOG  [motionchange] - false {"activity": {"confidence": 100, "type": "still"}, "battery": {"is_charging": true, "level": 1}, "coords": {"accuracy": 15.8, "altitude": 1035.2, "altitude_accuracy": 3, "heading": -1, "heading_accuracy": -1, "latitude": 31.9964142, "longitude": 35.8835884, "speed": -1, "speed_accuracy": -1}, "extras": {}, "is_moving": false, "odometer": 0, "timestamp": "2021-06-08T12:54:36.586Z", "uuid": "d09e4456-8327-4b8c-a65f-3267caafab71"}
```
## Debug logs

-->
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
// Import BackgroundGeolocation + any optional interfaces

```

</details>

**Comment by christocracy** [comment]
Have you read the wiki *Philosophy of Operation*?  This plugin automatically starts recording location when the device is detected to be moving.  This typically requires movement of about 200 meters.

All recorded locations are relayed to the `onLocation` event handler.

**Comment by ferasabufares** [comment]
@christocracy  how to make it update location  when movement less than 200 meters

**Comment by ferasabufares** [comment]
@christocracy  and when the app in background onLocation event  will work automatically without import react-native-background-fetch ??

**Comment by ferasabufares** [comment]
hello mr chris scott

thank you for your response
FYI  I am a licensed user

first i want to ask about notification label when it is show ?? and why it
is disappear ??

you said that  onLocation event requires movement of about 200 meters
to work  so how to make wrok when movement less than 200 meters???  .

should i use  react-native-background-fetch  to  get location when the app
in background  ??
this is my config

    BackgroundGeolocation.ready(
      {
        locationAuthorizationRequest: 'Always',
        disableLocationAuthorizationAlert: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        stopTimeout: 1,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
        stopOnTerminate: false,
        startOnBoot: true,
        autoSync: false,
        enableHeadless: true,
        preventSuspend: true, //iOSがアプリをsuspendしないように
        reset: false,
        distanceFilter: 10,
        foregroundService: true,
        backgroundPermissionRationale: {
          title:

"Allow SahmBoxDrive to access this device's location even when closed
or not in use."
,
          message:

'This app collects location data to enable recording your trips to
work and calculate distance-travelled.'
,
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel',
        },
        maxDaysToPersist: 1,
      },
      state => {
        console.log(
          '- BackgroundGeolocation is configured and ready: ',
          state.enabled,
        );

        if (!state.enabled) {
          ////
          // 3. Start tracking!
          //
          BackgroundGeolocation.start(function () {
            console.log('- Start success');
          });
        }
      },
    );
