### ISSUE TITLE
onGeoFence not working in background.

### ISSUE THREAD

**Issue by ShubhamBalgujar** [transistorsoft/react-native-background-geolocation#1318]
Your Environment
* Plugin version: 3.9.3
* Platform:Android
* OS version: Android 10
* Device manufacturer / model:
* React Native version (react-native -v): 0.60.5
* Plugin config
Class A.js
 `//configure the geo fences
                if (arrObjGeoFence.length) {

                    BackgroundGeolocation.removeGeofences().then(success => {
                        console.log("[removeGeofences] all geofences have been destroyed");
                        BackgroundGeolocation.addGeofences(arrObjGeoFence).then((success) => {
                            console.log("[addGeofences] success");
                            this.props.onGeofencesAdded(arrObjGeoFence);
                        }).catch((error) => {
                            this.props.onGeofencesAdded(arrObjGeoFence);
                            console.log("[addGeofences] FAILURE: ", error);
                        });
                    })
                }`
Class B

`<A
                    ref={(handle) => {
                        this.A = handle;
                    }}
                   
                    onGeofencesAdded={(arrGeoFence) => {
                        this.trackGeoFence(arrGeoFence);
                    }}
                />

trackGeoFence = (arrGeoFence) => {

        BackgroundGeolocation.ready({
            debug: true,
            startOnBoot: true,
            stopOnTerminate: false,
            geofenceModeHighAccuracy: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            notification: {
                smallIcon: "drawable/ic_notification"
            }
        }, async (state) => {
            if (!state.enabled) {
                BackgroundGeolocation.startGeofences();
            }
        });

        const watchID = this.getCurrentLocationAndAddress();
        this.watchID = watchID;

        BackgroundGeolocation.onGeofence(event => {
            //check action if user has entered or exited the geofence
            if (this.props.lastStatus != event.action) {
                console.log('lastStatus:  ' + this.props.lastStatus);
                arrGeoFence.map((item, index) => {
                    if (event.identifier == item.identifier) {
                        if (event.action == "ENTER") {
                          
                            if (this.A != null) {
                                this.A.publishNotification()
                                this.props.updateLastStatus(event.action);
                            }
                        } else if (event.action == "EXIT") {
                           
                            if (this.A != null) {
                                this.A.publishNotification()
                                this.props.updateLastStatus(event.action);
                            }
                        }
                    }
                });
            }
        });
    }`
## Expected Behavior
OnGeofence should be called in background and publish Notification.

## Actual Behavior
OnGeoFence called inconsistent in background

**Comment by christocracy** [comment]
Where's your plugin logs of a failure case?

**Comment by sobanfly** [comment]
also going through the same case. is that working in foreground mode?

**Comment by christocracy** [comment]
@sobanfly no you are not having the same issue.  You reported an issue with ios (and your problem is likely in your own code or not traveling far enough).

Now get off this issue.

**Comment by christocracy** [comment]
Also, you forgot this:

>Device manufacturer / model:
