### ISSUE TITLE
how to make on location event  works with any movement

### ISSUE THREAD

**Issue by ferasabufares** [transistorsoft/react-native-background-geolocation#1319]
## Your Environment
* Plugin version:4.1.0
* Platform: Android
* OS version:9
* Device manufacturer / model: samsung s7
* React Native version (`react-native -v`):0.64.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
   BackgroundGeolocation.ready(
      {
        locationAuthorizationRequest: Platform.OS === 'ios' ? 'WhenInUse' : 'Always',
        showsBackgroundLocationIndicator: true,//<~ For IOS only
        disableLocationAuthorizationAlert: false,
        locationAuthorizationAlert: {
          titleWhenNotEnabled: "location_titleWhenNotEnabled",
          titleWhenOff: "location_titleWhenOff",
          instructions: "location_instructions",
          cancelButton: "location_cancelButton",
          settingsButton: "location_settingsButton"
        },
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
        stopTimeout: 100,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
        stopOnTerminate: false,
        startOnBoot: true,
        autoSync: false,
        enableHeadless: true,
        preventSuspend: true, //iOSがアプリをsuspendしないように
        reset: true,
        distanceFilter: 0.00001,
        foregroundService: true,
        backgroundPermissionRationale: {
          title:this.props.language.collectLocation,
          message:this.props.language.locationTitle,
          positiveAction: this.props.language.enableLocation,
          negativeAction: this.props.language.Cancel,
        },
        maxDaysToPersist: 1,
      },
      state => {
        // console.log(
        //   '- BackgroundGeolocation is configured and ready: ',
        //   state.enabled,
        // );

        if (!state.enabled) {
          ////
          // 3. Start tracking!
          //
          BackgroundGeolocation.start(function () {
            // console.log('- Start success');
          });
        }
      },
    );
```

## Expected Behavior
is there any way to make location service always activated
i need to get location with any movement

and after i reboot my device the plugin not work
## Actual Behavior
when start the app notification label appear for second then it is disappear ??

https://ibb.co/JqW4zdB
https://ibb.co/5cHb46Q

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Have you read the wiki ["Philosophy of Operation"](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

This plugin is designed to track location **only** when the device is detected to be moving.  When the device is *stationary*, the plugin is not at all interested in wasting battery power.

>when start the app notification label appear for second then it is disappear ??

Yes, this is normal.  When the app launches, the plugin asks "where am I?", records a location and goes back to sleep until the device is detected to be moving, when the plugin will awaken, launch a foreground-service (and corresponding notification) and begin aggressively tracking the location according to your configured `Config.distanceFilter`.

**Comment by X-Titouan** [comment]
How can I get the best accuracy possible of someone who is unconscious (not moving) ?

1: I start the location service and I don't move the phone. Logs are:

65
65
65
65

I stop after 30 sec

2. I start the location service and I move the phone from right to letf with my hand. Logs are:

65
65,
65,
65,
65,
40, 
28,
20

I stop after 30 sec

As I fake phone movments, the tracker still sends me updates and so I get better accuracies.

How can I get location updates from a stationary user ?

**Comment by christocracy** [comment]
>How can I get location updates from a stationary user ?

See [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch) for periodic callbacks (which you can use to execute `BackgroundGeolocation.getCurrentPosition` while the device is stationary.

**Comment by X-Titouan** [comment]
I will dig into that :)

What is the difference bewteen a watchPosition and then stopWatchPosition and a traditonnal start and stop ?

**Comment by christocracy** [comment]
watchPosition is to be used for short periods of time while app is in foreground.  It is **not** to be used in the background.  You don't need watchPosition.

**Comment by X-Titouan** [comment]
Alright, thank you :)

**Comment by X-Titouan** [comment]
On your API documentation, getCurrentPosition can be configured with a timeout. If we use this function with a 300 sec timeout in Quit mode, the function will be killed anyway 20 sec after by iOS right ?

**Comment by christocracy** [comment]
No it won't.  Everything halts when an iOS app is terminated.  You don't get 20s on a terminated iOS app, that's impossible.
