### ISSUE TITLE
iPhone is using Location (hollow location icon) after app is terminated and Background Geolocation is "stop" 

### ISSUE THREAD

**Issue by jonmajorc** [transistorsoft/react-native-background-geolocation#1320]
## Your Environment
* Plugin version: 4.0.2
* Platform: iOS or Android
* OS version: iOS 14.4.2
* Device manufacturer / model: iPhone 12 Pro
* React Native version (`react-native -v`) :0.63.3
* Plugin config

Trying a combination of some things to try to get the hollow indicator to disappear
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      debug: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION, // iOS
      triggerActivities: "in_vehicle", // android
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      useSignificantChangesOnly: false, // Set true in order to disable constant background-tracking. Locations will be recorded only periodically.
      showsBackgroundLocationIndicator: true,
      enableHeadless: false, // android
      stopOnTerminate: true,
      foregroundService: true,
      isMoving: true,
      stopOnStationary: false,
      disableStopDetection: true,
      distanceFilter: 100,
      startOnBoot: false,
      batchSync: false,
      autoSync: false,
      notification: {
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
        smallIcon: "mipmap/notification_icon", // <-- defaults to app icon
        largeIcon: "mipmap/notification_icon",
        sticky: true,
        layout: "notification_location_layout",
        actions: ["stopButton"],
        title: "Location is being tracked",
        channelName: "Route Tracker",
      },
    },
```

## Expected Behavior
When the user terminates the app the location icon in the status bar disappears like other apps (Google Maps, Waze, etc.)

## Actual Behavior
When the user terminates the app the location icon goes from an active to a hollow icon.
![image](https://user-images.githubusercontent.com/7799266/121706358-2d149f80-ca9b-11eb-81d3-b9406fb88a48.png)

## Steps to Reproduce
1. Set **Always** for location service for app
2. Start tracking via `startSchedule` 
3. Stop tracking and kill app
4. Location status indicator will be a hollow icon

## Context
Shut down background tracking.

## Debug logs
N/A

Thanks for the package!!

**Comment by christocracy** [comment]
>stopOnTerminate: true,

The plugin has no idea if an app has been terminated, so continues to monitor its "stationary geofence" (thus the hollow circle).

The *next time* your app is re-launched due to the `stationary-geofence` exit event, the plugin will detect the app has been freshly launched, notice that `stopOnTerminate: true`, then finally stop monitoring the stationary-geofence and the hollow icon will disappear.

**Comment by jonmajorc** [comment]
On a real device, if I stop the service before terminating the app, I still see the hollow icon 🧐  --  If I stop the SDK, I would expect it would completely shut down any monitoring?

The odd thing is the simulator works as expected... 

**Simulator:** 
![Kapture 2021-06-11 at 10 54 52](https://user-images.githubusercontent.com/7799266/121714828-d65f9380-caa3-11eb-95ce-434b72f22a9d.gif)

Thanks for the help!

**Comment by christocracy** [comment]
>On a real device, if I stop the service before terminating the app, I still see the hollow icon

Perhaps the plugin is not at fault here then.  It could be *any* app running on your device.

I'm running **four** versions of the *Sample App* (*React Native*, *Flutter*, *Cordova* and *Capacitor*).  I just toggled each app *OFF*.  The location icons disappears after *exactly* 10 seconds.

**Comment by jonmajorc** [comment]
Good to know! Any chance you could share the config you're running?

**Comment by christocracy** [comment]
Config doesn't matter.  Calling `.stop()` is all that matters.  See your *Settings > Privacy > Location Services* to see a list of all apps currently using location-services on your device.  All four of my SampleApps show a grey icon after calling `.stop()`.

![](https://dl.dropbox.com/s/8n73mtnqb1ne4fo/Screen%20Shot%202021-06-11%20at%2012.28.39%20PM.png?dl=1)

**Comment by jonmajorc** [comment]
Yeah, everything looks good there! I actually did some further investigating and looks like there is another location package I found within this app. Based on what I am finding, that one is not turning off. 

Thanks a lot for your time!
