### ISSUE TITLE
Stop NSMotionUsageDescription request on app start, will ask manually later.

### ISSUE THREAD

**Issue by sobanfly** [transistorsoft/react-native-background-geolocation#1321]
Hi,
do we have a way to stop asking for motion request when iOS app starts, I wanna ask it later manually when plugin suppose to start work. A control over asking for permissions?
for IOS?
for android?
for both?

**Comment by sobanfly** [comment]
in config use disableMotionActivityUpdates: true will make motion request off.

**Comment by christocracy** [comment]
Congratulations on using the API docs to solve your own problem.
