### ISSUE TITLE
Apple reject app due to Tracking Transparency issues

### ISSUE THREAD

**Issue by WaseemAhmed645** [transistorsoft/react-native-background-geolocation#1322]
## Your Environment
* Plugin version: 4.0.2
* Platform: iOS 
* OS version: 14.5
* Device manufacturer / model: apple
* React Native version (`react-native -v`):
* Plugin config
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Allow for customer to see your current location on map to track their order.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Allow if you want to show nearest resturents orders.</string>
	<key>NSMotionUsageDescription</key>
	<string>Allow if you want to know the correct path to reach the customer location.</string>
	<key>NSPhotoLibraryUsageDescription</key>

## Expected Behavior
tracking work fine but apple reject the app that is the issues i want to be live my project

## Actual Behavior

Since you indicated in App Store Connect that you collect data in order to track the user, we need to confirm that App Tracking Transparency has been correctly implemented.

Next Steps

Please explain where we can find the App Tracking Transparency permission request in your app. The request should appear before any data is collected that could be used to track the user.

If your app does not track users, please update your app privacy information in App Store Connect. You must have the Account Holder or Admin role to update app privacy information.

Resources

- Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about tracking.
- See Frequently Asked Questions about the new requirements for apps that track users.
- Review developer documentation for App Tracking Transparency.

Since your App Store Connect status is Metadata Rejected, we do NOT require a new binary. To revise the metadata, visit App Store Connect to select your app and revise the desired metadata values. Once you’ve completed all changes, reply to this message in Resolution Center and we will continue the review.

## Steps to Reproduce

1. use guide as provided by the library 
2. make all changes into but got transparency issues

## Context
I do simple tracking the order for customer to show their order on the maps where their is currently

## Debug logs
No Debug log this is the issues with the such permission i cant understand kindly guide where.i can change the code or permission to get out from this issues 
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->

#From Apple


Guideline 2.1 - Information Needed


We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request.
```

</details>

**Comment by christocracy** [comment]
This has nothing to do with `BackgroundGeolocation`.  Use a 3rd-party plugin:
https://github.com/mrousavy/react-native-tracking-transparency#readme

**Comment by WaseemAhmed645** [comment]
@christocracy  if i uninstall this library this work fine ?

**Comment by christocracy** [comment]
Uninstall "*what*" library?

**Comment by mikehardy** [comment]
Even according to @mrousavy he's not sure why that module exists vs the more robust react-native-permissions, which includes the App Tracking Transparency permission, FYI

**Comment by WaseemAhmed645** [comment]
> Uninstall "_what_" library?

i means you ask me to using this https://github.com/mrousavy/react-native-tracking-transparency#readme or removing it because it already in my package.json

**Comment by WaseemAhmed645** [comment]
> Even according to @mrousavy he's not sure why that module exists vs the more robust react-native-permissions, which includes the App Tracking Transparency permission, FYI

which thing is better for me to use and get off from this is issues i spend much more time on it but got no sucess

**Comment by christocracy** [comment]
>vs the more robust react-native-permissions, which includes the App Tracking Transparency permission, FYI

Ah, thanks @mikehardy.  I'm was not aware `react-native-permissions` had implemented this.

Still, there's not really much involved with implementing this API.  A [*getter* and a *requester*] method (https://github.com/mrousavy/react-native-tracking-transparency/blob/master/ios/TrackingTransparency.m).

**Comment by mikehardy** [comment]
If you already have that one, I'd switch, personally:

https://github.com/mrousavy/react-native-tracking-transparency/issues/8

If you have *any* ATT framework and it's not working, then you're doing something wrong. Note that testing it is a bit tricky, the react-native-persmissions repo has more information

**Comment by WaseemAhmed645** [comment]
@mikehardy thanks for you time , i am not using any ATT i am using the Geolocation of @christocracy for tracking the rider but apple make the issues of ATT before using the Geolocation i am using diff technique for tracking but got no success in background tracking and in those days my app is publish on apple store without tracking but when we know about the @christocracy sir library we are very happy to implement this and get a wonderful result but after this apple make this ATT issues i don't know why this issues happen

**Comment by mikehardy** [comment]
@WaseemAhmed645 your last comment doesn't make sense to me from the perspective of a geolocation library issue. Either your app uses analytics (in some way, any way) and Apple wants you to implement ATT or not. I was mostly commenting because I collaborate with @christocracy and I know he remembers things so I was giving him a better library pointer for future reference.

Your project, and it's need to implement ATT or not, and it's successful implementation of ATT or not, is your own issue which you must determine and resolve, using the library of your choice.

**Comment by WaseemAhmed645** [comment]
@christocracy @mikehardy Thanks for you time , i am not mention any where that your library making issues i need suggestion only you library work awesome . Thanks for your support
