### ISSUE TITLE
Testing For Android 12

### ISSUE THREAD

**Issue by talibbk** [transistorsoft/react-native-background-geolocation#1324]
I am trying to test my app for upcoming Android 12.
My build fails at :

Execution failed for task ':app:installDevDebug'.
com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl545282450.tmp/base.apk (at Binary XML file line #340): com.transistorsoft.tsbackgroundfetch.BootReceiver: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present.

I have fixed other similar errors by adding attribute android:exported to < activity > components that have < intent-filter > s declared in the app’s AndroidManifest.xml file, but i can't find solution for this one.
I am using react-native-background-geolocation which requires react-native-background-fetch as dependency.
I hope you can look into this.
Thankyou
## Your Environment
* Plugin version:^3.9.0
* Platform: Android
* OS version: Android 12
* Device manufacturer / model: Google / Pixel 4a
* React Native version (`react-native -v`): 0.61.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
      {
        locationAuthorizationRequest: "Always",
        disableLocationAuthorizationAlert: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        stopTimeout: 10,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
        stopOnTerminate: false,
        startOnBoot: true,
        autoSync: false,
        enableHeadless: true,
        motionTriggerDelay: 30000,
        preventSuspend: true //iOSがアプリをsuspendしないように
      },
      async (state) => {
        if (!state.enabled) {
          const locationPermission = await Permission.checkPermissionLocation()
          if (locationPermission) {
            BackgroundGeolocation.start()
          }
        }
      }
    )
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Able to build
## Actual Behavior

Get Error : 
* What went wrong:
Execution failed for task ':app:installDevDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl215726433.tmp/base.apk (at Binary XML file line #340): com.transistorsoft.tsbackgroundfetch.BootReceiver: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version:^3.9.0

v3.9.0 is incompatible with Android-12

Use latest `4.1.1` and `react-native-background-fetch@4.0.1`

`targetSdkVersion "S"` won't be ready for a few months but `compileSdkVersion "android-S" is fine.

I'm running *Android 12 Beta* on my primary dev device *Pixel 3a*.

**Comment by talibbk** [comment]
@christocracy thankyou for fast reply as always!  
Will compatibility for targetSdkVersion "S" be available before launch of android 12?  
When do you estimate it to be done?

**Comment by christocracy** [comment]
It is not important to targetSdkVersion S for at least 6 months.

I will be looking into over the summer.

**Comment by talibbk** [comment]
@christocracy 
Hello.
has this issue been addressed?

**Comment by christocracy** [comment]
>has this issue been addressed?

Yes.  I'm developing and testing on `targetSdkVersion 31`.  Always use latest version (currently `4.2.2`).

**Comment by talibbk** [comment]
Hello @christocracy 
Thankyou for writing us back.
Is it possible for you to notify us when its ready to be developed on `targetSdkVersion 31` ?

**Comment by christocracy** [comment]
No, I'll never remember this issue. 

I suggest you subscribe to commits  on this repo and keep your eyes on the CHANGELOG.  You can also subscribe to my blog at https://transistorsoft.medium.com.
