### ISSUE TITLE
Very few locations tracked on iOS in comparison to Android

### ISSUE THREAD

**Issue by LadislavBohm** [transistorsoft/react-native-background-geolocation#1326]
## Your Environment
* Plugin version: 4.0.3
* Platform: iOS
* OS version: 14.6
* Device manufacturer / model: IPhone XR (vs OnePlus 7, Android 11)
* React Native version (`react-native -v`): 0.64.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =     {
    };
    autoSync = 1;
    autoSyncThreshold = 1;
    batchSync = 1;
    debug = 0;
    desiredAccuracy = "-2";
    desiredOdometerAccuracy = 100;
    didDeviceReboot = 0;
    didLaunchInBackground = 0;
    didRequestUpgradeLocationAuthorization = 0;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 1;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 25;
    elasticityMultiplier = 0;
    enableTimestampMeta = 0;
    enabled = 0;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 2000;
    geofenceTemplate = "";
    headers =     {
        authorization = "__placeholder__";
    };
    heartbeatInterval = 60;
    httpRootProperty = ".";
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =     {
        cancelButton = __placeholder__;
        instructions = "__placeholder__";
        settingsButton = "__placeholder__";
        titleWhenNotEnabled = "__placeholder__";
        titleWhenOff = "__placeholder__";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "[\"<%= uuid %>\", \"<%= timestamp %>\", <%= latitude %>, <%= longitude %>, <%= accuracy %>, <%= altitude %>, <%= altitude_accuracy %>, <%= odometer %>, \"<%= activity.type %>\", <%= activity.confidence %>]";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 4;
    logMaxDays = 15;
    maxBatchSize = 200;
    maxDaysToPersist = 100;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "2716.794513849743";
    params =     {
    };
    pausesLocationUpdatesAutomatically = 1;
    persistMode = 1;
    preventSuspend = 0;
    schedule =     (
    );
    schedulerEnabled = 0;
    showsBackgroundLocationIndicator = 1;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 10;
    trackingMode = 1;
    url = "__placeholder__";
    useSignificantChangesOnly = 0;
}
```

## Expected Behavior
I went for a run with both Android and iOS devices. Turned on our app and started tracking (I even applied more aggressive 25 vs 50 distance filter on iOS). On Android it worked flawlessly, everything was tracked according to configuration.

On iOS it only tracked like 4 locations. The track I went for was about 4 kilometers long.

## Actual Behavior
Android result
<img width="179" alt="android-test" src="https://user-images.githubusercontent.com/4920886/122737761-ad988480-d281-11eb-9909-dda1e5931393.png">

iOS result
<img width="190" alt="ios-test" src="https://user-images.githubusercontent.com/4920886/122737789-b4bf9280-d281-11eb-831c-0293c7952106.png">

## Steps to Reproduce
1. Turn on tracking on both devices
2. Go to homepage
3. Turn off display
4. Keep walking/running whatever

## Context
I disabled elasticity, I also turn on pace immediately after I start tracking (setPace(true)). Is it because I move the app from being focused in the foreground on iOS?
I am just able to get even similar results like you when you posted in some other issue where it looked perfect.

I can provide more info as we have two iOS devices for testing and both show the same issue.

What I find interesting is that the route I took was from point A -> B and then B -> A taking the same path. As you can see from iOS picture it took locations on almost exactly the same spot.

**Comment by christocracy** [comment]
See wiki *Debugging*.  Enable verbose logging.

Fetch logs from plugin using emailLog method.

**Comment by LadislavBohm** [comment]
Ok I did take slightly longer route and tested it again with VERBOSE. I had 4 phones with me:

- 3 Android devices of varies versions, all without issue recorded whole route
- 1 iOS device that has the same problem

Even though I set logging to verbose it shows way less logs on iOS than Android, also the trip started at about 17:40 and ended about 18:06.

[ios-background-geolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/6688103/ios-background-geolocation.log)

**Comment by christocracy** [comment]
Are you looking at the logs?  It's  full of warnings.

**Comment by LadislavBohm** [comment]
Yes I was inspecting them and I don't see any reason why it isn't collecting almost any locations.

I can see some warning about extras, but I am not using them anywhere in my config. Also it is colleting **some** locations so I guess if my config was wrong completely it wouldn't collect anything.

It fails to send locations to server which is expected because phone only has wifi enabled and there was no connection. For example I don't see why there is a ten minute gap with no logs after HTTP service has failed:
```
2021-06-21 17:45:54.490 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 65.0

2021-06-21 17:45:54.491 ⚠️-[TSLocation toJson:] Appending #extras to last index of [Array] in JSON template

2021-06-21 17:45:54.498 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: AD590ADB-BAF0-4792-8E21-C3F2FDC66C05

2021-06-21 17:45:54.498 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2021-06-21 17:45:54.498 ⚠️-[TSHttpService flush:] No network connection

2021-06-21 17:45:54.498 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════

2021-06-21 17:45:59.489 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | on_foot/66 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2021-06-21 18:05:40.488 ℹ️-[TSDBLogger db_save] Log committed
```

I can see that isMoving: 1 so I would guess that location services are active and app should be collecting locations. Maybe I am interpreting it wrong though.

**Comment by christocracy** [comment]
Your logs show 16 locations recorded between `17:39:52.103` and `18:11:31.874`.  That looks like a reasonable number of locations to have recorded during that time (~30min).

Here's what tracking looks like for me every time on iOS (`distanceFilter: 50`):

https://dl.dropbox.com/s/lb03wamr96uk6lx/Screen%20Shot%202021-06-21%20at%201.28.57%20PM.png?dl=1

**Comment by LadislavBohm** [comment]
Well it's almost 8km long and I have ```distanceFilter: 50``` as well. On all Android devices I have about 74 locations recorded during that trip.
On iOS like you said it's 16 which looks more like ```distancefFilter: 500```. I understand that those config values cannot be guaranteed but I did not expect it to be such a huge difference between platforms.

In your picture I can see that you got about 16 locations over a distance of just about 450 meters.

**Comment by christocracy** [comment]
Here's a bike ride I do with both iOS and Android.  Their tracking is almost identical.

This is my experience after 6 years.

### iPhone 12 Pro
![](https://dl.dropbox.com/s/mwgdagsrhj9eid9/Screen%20Shot%202021-06-21%20at%201.45.47%20PM.png?dl=1)

### Pixel 3a
![](https://dl.dropbox.com/s/n3z584hf2njvpju/Screen%20Shot%202021-06-21%20at%201.45.11%20PM.png?dl=1)

**Comment by LadislavBohm** [comment]
Would you be willing to share you configuration so I can test it? Not sure what else to try to be honest.

**Comment by christocracy** [comment]
I suggest you install the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo) on your iOS device.

Do not look at the code.  Just run it on your device then go outside for a test.  Use the *Advanced App* -- it has a settings screen.

**Comment by LadislavBohm** [comment]
I tested the sample app, looked for any differences and found out that someone accidentally removed background capability from XCode settings.
Right now tracking works pretty much identical to Android so far.
