### ISSUE TITLE
Option to make permisson request dialog background not pressable

### ISSUE THREAD

**Issue by tunguyenbhtech** [transistorsoft/react-native-background-geolocation#1329]
## Your Environment
* Plugin version: 3.9.3
* Platform: Android
* OS version: Android 11
* Device manufacturer / model: Samsung Galaxy Note 10
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const DEFAULT_CONFIG: Config = {
    // Logging & Debug Options
    // debug: __DEV__, // debug sounds / notifications
    logLevel: useLog
        ? BackgroundGeolocation.LOG_LEVEL_VERBOSE
        : BackgroundGeolocation.LOG_LEVEL_OFF,
    logMaxDays: APP_CONFIG.logMaxDays,

    // Geolocation Config
    desiredAccuracy: APP_CONFIG.locationDesiredAccuracy,
    distanceFilter: APP_CONFIG.locationDistanceFilter,
    // Activity Recognition
    stopTimeout: APP_CONFIG.stopTimeout,
    // Allow the background-service to continue tracking when user closes the app.
    stopOnTerminate: false,
    heartbeatInterval: APP_CONFIG.heartbeatInterval,
    // app already handled it by listening to providerchange event
    // and react native has a bug with not being able to present multiple alert / modal at the same time
    // ( freeze UI - a view layer on top not being removed )
    // https://github.com/facebook/react-native/issues/10471
    disableLocationAuthorizationAlert: true,
    // request location permission "Always" dialog text config
    // https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353
    backgroundPermissionRationale: {
        title: `Allow ${APP_CONFIG.companyName} to access to this device's location in the background?`,
        message: `In order to track your activity in the background, please enable ${backgroundPermissionOptionLabel} location permission`,
        positiveAction: `Change to ${backgroundPermissionOptionLabel}`,
        negativeAction: 'Cancel',
    },
};
```

## Expected Behavior
Should be able to configure the location permission request dialog to not cancallable to prevent user from accidentally press outside of dialog and skip the request

## Actual Behavior
Touching outside permission dialog ignore the dialog

## Steps to Reproduce
1. start the app with plugin configured
2. press outside of permission dialog

## Context
I'm trying to prevent user from accidentally pressing outside of permission dialog and skip it

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
What permission dialog are you talking about?  Show a screenshot.

If it's the native OS dialog, there's nothing you can do about that.  That dialog is presented and managed by the operating system.

**Comment by tunguyenbhtech** [comment]
I see, thanks, it's the OS dialog.
It didn't throw error at the `.ready` call like when user press deny but only at the `.startTracking` so we handled it accordingly.
