### ISSUE TITLE
Typescript enums?

### ISSUE THREAD

**Issue by chrisdrackett** [transistorsoft/react-native-background-geolocation#1336]
I'm new to the library and loving it so far!

One thing I'm curious about is if you would be open to PR's to update the typescript types to use enums. For example changing:

```

  interface GeofenceEvent {
    /**
    * The identifier of the geofence which fired.
    */
    identifier: string;
    /**
    * The transition type: `ENTER`, `EXIT`, `DWELL`
    */
    action: string;
    /**
    * The [[Location]] where the geofence transition occurred.
    */
    location: Location;
    /**
    * Optional [[Geofence.extras]]
    */
    extras?: Extras;
  }
}
```

to

```

  export enum GeofenceAction {
    ENTER = 'ENTER',
    EXIT = 'EXIT',
    DWELL = 'DWELL'
  }

  interface GeofenceEvent {
    /**
    * The identifier of the geofence which fired.
    */
    identifier: string;
    /**
    * The transition type.
    */
    action: GeoFenceAction;
    /**
    * The [[Location]] where the geofence transition occurred.
    */
    location: Location;
    /**
    * Optional [[Geofence.extras]]
    */
    extras?: Extras;
  }
}
```

I didn't want to undertake this kind of work unless it would be welcome!

**Comment by danb10** [comment]
Another option would be `type GeoFenceAction = 'ENTER' | 'EXIT' | 'DWELL'`

**Comment by chrisdrackett** [comment]
I'd be game for this as well!

**Comment by chrisdrackett** [comment]
Keeping a list here in case I or someone else gets to this issue:

existing, but not enums:
- `LogLevel`
- `LocationAccuracy`
- `NotificationPriority`
- `ActivityType`
- `AuthorizationStatus`
- `AccuracyAuthorization`
- `TrackingMode`
- `LocationError`
- `LocationAuthorizationRequest`

possible enhancements:
- `GeofenceAction` (`GeofenceEvent.action`)
-

**Comment by chrisdrackett** [comment]
not sure if I can reopen now that this is closed...
