### ISSUE TITLE
possible to turn on debug mode after start?

### ISSUE THREAD

**Issue by chrisdrackett** [transistorsoft/react-native-background-geolocation#1339]
## Your Environment
* Plugin version: 4.1.1
* Platform: iOS
* OS version: 14.6
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.64
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
      {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 15,
        stopTimeout: 5,
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      },

```

## Expected Behavior
Calling `BackgroundGeolocation.setConfig({ debug: true })` should turn debug on.

## Actual Behavior
I can see `debug` set to `true` in the state after calling the above, but I don't get debug sounds or notifications. If I set debug to true in the initial config things work as expected.

## Context
I want to add a toggle to my dev settings to turn debug on and off.

**Comment by christocracy** [comment]
The SampleApp (*Advanced App*) has a Settings screen which uses `setConfig` to change options.

I've never had a problem with changing `debug` option at run-time.  I often use this during field-testing to toggle the debug sound FX on/off.

![](https://dl.dropbox.com/s/su1ga662rydw1f0/Screen%20Shot%202021-07-10%20at%202.26.02%20PM.png?dl=1)

**Comment by chrisdrackett** [comment]
thanks, I think I'm having issues around when I setup event handlers as well. I have `BackgroundGeolocation.onLocation` setup for example but its content isn't firing. Is there a chance I have more than once instance of BackgroundGeolocation or something? I have its setup in a `useEffect` with no dependencies at the top level of my app.

**Comment by chrisdrackett** [comment]
anyways, that's probably another issue. Thanks!

**Comment by christocracy** [comment]
> there a chance I have more than once instance of BackgroundGeolocation or something?

There is no such thing as "multiple instances".
