### ISSUE TITLE
`Always` location option is not available for app in TestFlight

### ISSUE THREAD

**Issue by mykolasmolis** [transistorsoft/react-native-background-geolocation#1341]
First of all - thank you for all the hard work building this so helpful plugin!

Followed the instructions to setup React Native iOS app.

However, when deploying app on TestFlight I don't see Always option. Tried to search for it in documentation and Google. Don't really get the answer.

I understand iOS restricts this option in user dialog, but can't get it why it is not available in explicit app options. Am I missing something?

![Screenshot 2021-07-12 at 23 39 02](https://user-images.githubusercontent.com/37137051/125353041-b5bc7f00-e36a-11eb-9c55-cd1ce6cafa2a.png)

Thank you!

**Comment by christocracy** [comment]
Review the iOS Setup Instructions in the readme.

**Comment by mykolasmolis** [comment]
Reviewed these instructions:
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md
https://github.com/transistorsoft/react-native-background-fetch/blob/master/docs/INSTALL-AUTO-IOS.md#configure-background-capabilities

Looks like all the steps are done. Is there some specific instruction I should specifically look at? Totally lost :(

**Comment by mykolasmolis** [comment]
Ok so I found some mismatch in `Info.pllist` values. `Privacy - Location Always and When in Use Usage Description` has to be chosen. I chose `Privacy - Location Always Usage Description` by mistake. Let's see if the fix helps.

**Comment by mykolasmolis** [comment]
Yap - the fix helped - better be carefull with those properties next time. Sorry for confussion :)
