### ISSUE TITLE
The onLocation event is not working after the application in stationary status and in the background state in 30 minutes

### ISSUE THREAD

**Issue by thuyducati** [transistorsoft/react-native-background-geolocation#1344]
## Your Environment
* Plugin version: 4.0.3
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung Galaxy S21
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 20,
    locationAuthorizationRequest: 'WhenInUse',
    notification: {
        title: "locationTrackingTitle",
        text: "locationTrackingContent",
        smallIcon: `@drawable/ic_push_notification`,
        channelName: "Location Tracking"
    },
    stopTimeout: 5,
    debug: false
}
```

## Expected Behavior
onLocation event is triggered.

## Actual Behavior
After 30 minutes app in stationary status and in the BACKGROUND mode, moving for a while until foreground-service is started (the associated notification displayed), then keeping moving until onLocation event is triggered, but it is NOT.

## Steps to Reproduce

1. Launch the application.
2. The foreground-service will ON, then OFF.
3. Move the application to BACKGROUND mode and wait for 30 minutes. Application will be in STATIONARY status (a foreground-service tracking notification is not displayed).
4. Moving for a while to start service (foreground-service tracking notification is displayed).
5. After service is started, keep moving until onLocation event is trigger.

## Context
For more information for how I check onLocation event works or not, in my onLocation event, whenever it is triggered, it will send request to my server, at that time, to know whether event is working or not, I will check the log in my server. But I don't see any logs in my server. Next, I move the application to foreground state, and back to background state again, and I started moving, onLocation event was triggered.
If I don't wait for 30 minutes and start moving until foreground-service is started, onLocation event will be triggered.

I really appreciate any help.
Thank you so much!

**Comment by christocracy** [comment]
The SampleApp has been using the onLocation event to draw markers on the map for over 6 years.

**Comment by thuyducati** [comment]
> The SampleApp has been using the onLocation event to draw markers on the map for over 6 years.

@christocracy 
Excuse me, Chris. I do not understand your answer. I am using your library for tracking user location, what I want is whenever user start moving, the event listener will detect this and send the location information to the application. As you said, the onLocation event is use for drawing markers on the map. So, except the onLocation event, could you tell me which other event listener will help me detect whenever user location has any changes?

**Comment by christocracy** [comment]
> could you tell me which other event listener will help me detect whenever user location has any changes?

Every recorded location is provided to `onLocation`.  I suspect it's your HTTP call which is not executing in the background due to react-native and not the plugin's fault, and that `onLocation` **IS** firing.

Use the plugin's [Logger](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/logger.html) to print a log message.

Then fetch the plugin's logs using [emailLog](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/logger.html#emaillog) to see if your log messages exist there.

**Comment by christocracy** [comment]
>The SampleApp has been using the onLocation event to draw markers on the map for over 6 years.

If `onLocation` was not working as intended, I would see blank spots in the SampleApp's tracking where `onLocation` failed to be called, thus no map markers rendered.

**Comment by thuyducati** [comment]
@christocracy 
Many thanks for your answer. Did you notice the config "locationAuthorizationRequest" in my BackgroundGeolocation.ready() function? I separate 2 values for each platform, I set this value for this config is "WhenInUse" (Android) and "Always" (iOS). And I realize that I can see my recorded location is provided to onLocation event-handler on iOS devices with the config "locationAuthorizationRequest" as "Always". But on Android devices, I cannot see any recorded location. I don't think I have a problem with the HTTP call in the background execution. So, do I need to change the value of locationAuthorizationRequest to "Always" for working in background on Android devices?

**Comment by christocracy** [comment]
> So, do I need to change the value of locationAuthorizationRequest to "Always" for working in background on Android devices?

Yes
