### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 221): 499

### ISSUE THREAD

**Issue by awhinaawhina** [transistorsoft/react-native-background-geolocation#1345]
Your Environment
Plugin version:
Platform: iOS or Android
OS version: macOS Catalina Version: 10.15.7 
Device manufacturer / model: 
React Native version (react-native -v): 0.63.3
Plugin config

BackgroundGeolocation.onLocation(this.onLocation, this.onError);
  
         // This handler fires when movement states changes (stationary->moving; moving->stationary)
         BackgroundGeolocation.onMotionChange(this.onMotionChange);
     
         // This event fires when a change in motion activity is detected
         BackgroundGeolocation.onActivityChange(this.onActivityChange);
     
         // This event fires when the user toggles location-services authorization
         BackgroundGeolocation.onProviderChange(this.onProviderChange);
     
         //
        //  2.  Execute #ready method (required)
         
         BackgroundGeolocation.ready({
           // Geolocation Config
           desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
           distanceFilter: 10,
           // Activity Recognition
           stopTimeout: 1,
           // Application config
           debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
           logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
           stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
           startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
           // HTTP / SQLite config
           url: 'http://yourserver.com/locations',
           batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
           autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
           headers: {              // <-- Optional HTTP headers
             "X-FOO": "bar"
           },
           params: {               // <-- Optional HTTP params
             "auth_token": "maybe_your_server_authenticates_via_token_YES?"
           }
         }, (state) => {
           console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
     
          //  if (!state.enabled) {
             ////
             // 3. Start tracking!
             //
             BackgroundGeolocation.start(function() {
               console.log("- Start success");
             });
          //  }
         });

Expected Behavior : To get location coordinates on position change.

Actual Behavior: Possible Unhandled Promise Rejection (id: 221): 499

Steps to Reproduce

1. Start the BackgroundGeolocation Listner and after 1 min an app crash is occured

**Comment by christocracy** [comment]
- Your code is unreadable.  Please learn to use [Github Syntax Highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
- Ignored issue template

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************
-->


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
