### ISSUE TITLE
Heading magentic or true?

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [transistorsoft/react-native-background-geolocation#1346]
Not an issue per se, but trying to understand if the heading coming back in coords is true north or magnetic north? And what is heading_accuracy telling me? The documentation says in degrees. So if I get a value of 51 what is that saying?

**Comment by christocracy** [comment]
See the native API docs:

### Heading
- Android [`Location.getBearing`](https://developer.android.com/reference/android/location/Location#getBearing())
- iOS [`CLLocation.course`](https://developer.apple.com/documentation/corelocation/cllocation/1423832-course)

### `heading_accuracy`
- Android [`Location.getBearingAccuracyDegrees`](https://developer.android.com/reference/android/location/Location#getBearingAccuracyDegrees())
- iOS [`CLLocation.courseAccuracy`](https://developer.apple.com/documentation/corelocation/cllocation/3524338-courseaccuracy)
