### ISSUE TITLE
Location template not applied with reset: true set in config

### ISSUE THREAD

**Issue by luskin** [transistorsoft/react-native-background-geolocation#1351]
## Your Environment
* Plugin version: 3.9.3
* Platform: iOS & Android 
* OS version: latest
* Device manufacturer / model: all
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const createBackgroundTrackingConfiguration = (uid: string): Partial<BackgroundGeoloctionConfig> => ({
  // Geolocation Config
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 200,

  // Android
  allowIdenticalLocations: true,
  foregroundService: true,
  enableHeadless: true,
  disableLocationAuthorizationAlert: true,
  notification: {
    title: '{REDACTED}',
    text: '{REDACTED}',
  },

  // Activity Recognition
  stopTimeout: 1,

  // Application config
  debug: false,
  reset: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: false,
  startOnBoot: true,
  locationTemplate: `
  {
    "latitude":<%= latitude %>,
    "longitude":<%= longitude %>,
    "recordedAt":"<%= timestamp %>",
    "heading":<%= heading %>,
    "speed":<%= speed %>,
    "altitude":<%= altitude %>,
    "isMoving":<%= is_moving %>,
    "movementType": "<%= activity.type %>",
    "movementTypeConfidence": <%= activity.confidence %>,
    "batteryLevel":<%= battery.level %>,
    "isCharging":<%= battery.is_charging %>,
    "odometer":<%= odometer%>
  }
  `,
  extras: {
    firebaseUserKey: uid,
  },

  // HTTP
  url: `{REDACTED}/v1/locations`,
  httpRootProperty: '.',
  batchSync: false,
  autoSync: true,
})
```

## Expected Behavior
When flagging `reset: true` (which is actually true by default) the `locationTemplate` should be used when pinging to our `url`.

## Actual Behavior
After codepush update, RNGeolocation is pinging to our new URL but not adhering to the location template. We know that the codepush update was applied because the `url` field in the config changed and we are seeing these original location payloads being sent instead of `locationTemplate` payloads.

These are the logs from DataDog coming from the updated application (with new `url`):
```js
{
  coords: {
    speed_accuracy: 3.13,
    speed: 32.6,
    longitude: -81.3277235791588,
    floor: null,
    heading_accuracy: 5.28,
    latitude: 29.70071836363709,
    accuracy: 4.7,
    altitude_accuracy: 3.5,
    altitude: 13,
    heading: 160.72
  },
  extras: {},
  is_moving: true,
  odometer: 199020.9,
  uuid: 'FC989D47-F685-4653-BA0F-785AE3554028',
  activity: { type: 'in_vehicle', confidence: 100 },
  battery: { level: 0.949999988079071, is_charging: false },
  timestamp: '2021-07-23T07:36:49.000Z'
}
```

## Steps to Reproduce

1. Update `config` with location template, from NOT having a location template before
2. Update `url` to a new backend url
3. Codepush update to users that were already using a previous configuration
4. 

## Context
New backend endpoint, with new schema.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by luskin** [comment]
We also use `react-native-background-fetch`

Is it possible that this package needs some kind of a hard app reset to apply the new template to the headless task?

**Comment by christocracy** [comment]
The plugin contains old locations in SQLite that were generated with previous template.  Use `.destroyLocations()` to clear them out.

**Comment by luskin** [comment]
@christocracy That's a good call-out, but I don't think that's the problem in this case. The timestamps of the locations coming through are after the update, and affecting thousands of active devices in real-time right now (that are on the latest app version). Anything else you can think of?

**Comment by luskin** [comment]
Also, by that theory, those locations would eventually all be sent through and the error rate should drop back to 0, instead the error rate is remaining constant.

**Comment by christocracy** [comment]
Locations are rendered to JSON only once, using the `locationTemplate` configured at that time.  Existing locations in SQLite are not re-rendered when `locationTemplate` changes.

I'm sure you have old locations stored in SQLite.

**Comment by luskin** [comment]
@christocracy if `batchSync` is false, and a location ping receives an error, does it skip and move onto the next location or does it get stuck and attempt to retry? Just trying to debug on our end why thousands of up-to-date devices are unable to send us proper location payloads right now.

**Comment by christocracy** [comment]
>receives an error, does it skip and move onto the next location or does it get stuck and attempt to retry?

It halts and keeps re-attempting the failed location before moving onto the next.

**Comment by christocracy** [comment]
If your server sends a `200` response (regardless if it's an error), the plugin will then delete that location and move onto the next.

**Comment by luskin** [comment]
We are patching our location service now, great information thank you @christocracy. That would explain why up-to-date locations are not making their way through.

QQ: Can it be a `204`? Would any `2XX` suffice?

**Comment by christocracy** [comment]
>QQ: Can it be a 204? Would any 2XX suffice?

```java
public Boolean isSuccess() {
    return (status == 200  || status == 201 || status == 204);
}
```
