### ISSUE TITLE
Issue using `disableLocationAuthorizationAlert` and `Ask Next Time` on iOS

### ISSUE THREAD

**Issue by chrisdrackett** [transistorsoft/react-native-background-geolocation#1352]
## Your Environment
* Plugin version: 4.1.1
* Platform: iOS
* OS version: 14.6
* Device manufacturer / model: iPhone 12
* React Native version (`react-native -v`): 0.64
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 15,
        stopTimeout: 5,
        elasticityMultiplier: 2,
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        disableLocationAuthorizationAlert: true, // <-- we handle the location alerts ourselves.
      },
```

## Expected Behavior
When `disableLocationAuthorizationAlert` I don't ever expect to see an alert asking for location permission without triggering one myself.

## Actual Behavior

When I set `Ask Next Time` in system settings I get a "Allow [App Name] to use your location?" dialog. Related, if I choose "Allow when using app" and then "Change to always allow" in the next dialog the system location setting stays as "Ask Next Time" and from here on I don't get the dialog

## Steps to Reproduce

1. set `disableLocationAuthorizationAlert` to true
2. set system location to "Ask Next Time"
3. open app
4. dialog appears (not expected)
5. select "allow" in dialog and "always allow" in next dialog
6. check settings, setting is still "Ask Next Time"

## Context
I want to show the dialog myself, but if I did want to use background-geolocation I would want my changes to be reflected in settings in this case

## Debug logs

Not getting output of logs when doing this for some reason, in the console its blank.

**Comment by christocracy** [comment]
What you experience here is the OS's permission workflow, not the plugin's custom dialog, whose presence is controlled by disableLocationAuthorizationAlert.

**Comment by chrisdrackett** [comment]
I see, if I have `startOnBoot` on and `stopOnTerminate` set to false I'm guessing that the plugin is still trying to get location values which is triggering this?

**Comment by christocracy** [comment]
If you've told the plugin to start(), naturally location permission is required.

If you don't want the plugin to request permission, then clearly you're not interested in receiving location and should the plugin to stop().

**Comment by chrisdrackett** [comment]
Ok, if I stop with the above options will the plug-in start itself on boot/terminate still?

**Comment by christocracy** [comment]
> stop with the above options will the plug-in start itself on boot/terminate still?

stop() means stop everything, like toggling the power button OFF on any electronic device.
