### ISSUE TITLE
Callback behavior when app is killed

### ISSUE THREAD

**Issue by mykolasmolis** [transistorsoft/react-native-background-geolocation#1353]
I'd like to ask a question, because can not find in documentation (which is by the way amazing!). The library works great when app is active or working in background. However, when I kill the app it looks like none of the callbacks such as `onLocation`, `onGeofence`, `onHeartbeat` seems to be called. My configuration is:
```
    startOnBoot: true,
    stopOnTerminate: false,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    locationAuthorizationRequest: 'Always',
    heartbeatInterval: 60,
    preventSuspend: true,
```
Are my exceptions wrong? Am I missing some point in docs?

Thank you!

**Comment by christocracy** [comment]
For Android, that's correct.

See api docs Config.enableHeadless
