### ISSUE TITLE
calling `BackgroundGeolocation.requestPermission` returns success before I'm able to ask user for permission

### ISSUE THREAD

**Issue by chrisdrackett** [transistorsoft/react-native-background-geolocation#1354]
## Your Environment
* Plugin version: 4.1.1
* Platform: iOS
* OS version: 14.6
* Device manufacturer / model: iPhone 12
* React Native version (`react-native -v`): 0.64
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 15,
        stopTimeout: 5,
        elasticityMultiplier: 2,
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        disableLocationAuthorizationAlert: true, // <-- we handle the location alerts ourselves.
        locationAuthorizationRequest: 'Always'
      },
```
## Expected Behavior
When the user has `When In Use` permissions and I have `locationAuthorizationRequest: 'Always'` set calling `BackgroundGeolocation.requestPermission` should wait for the user to take action before running the success callback.

## Actual Behavior

The success callback is called right away with `AUTHORIZATION_STATUS_WHEN_IN_USE`. I'm not able to react to `AUTHORIZATION_STATUS_ALWAYS` because success is never called with this status.

## Steps to Reproduce

1. Set device to `When In Use` for app in question
2. set `locationAuthorizationRequest` to `Always` in config
3. call `BackgroundGeolocation.requestPermission` with a callback for success
4.

## Context
my code looks like the following:

```
BackgroundGeolocation.requestPermission(
          (successStatus) => {
            switch (successStatus) {
              /**
               * If the user asked to turn background tracking on but we only get
               * `when in use` let them know.
               */
              case BackgroundGeolocation.AUTHORIZATION_STATUS_WHEN_IN_USE:
                if (backgroundLocationIsOn) { // our app setting for background location tracking
                  noBackgroundLocationPermissionDetectedAlert() // our alert that background permission is needed
                }
                break
            }
          },
          (failureStatus) => {
            switch (failureStatus) {
              /**
               * If we fail to get permission, let the user know
               * so they can either fix it or we can turn tracking off.
               */
              case BackgroundGeolocation.AUTHORIZATION_STATUS_NOT_DETERMINED:
              case BackgroundGeolocation.AUTHORIZATION_STATUS_RESTRICTED:
              case BackgroundGeolocation.AUTHORIZATION_STATUS_DENIED:
                noLocationPermsUserInitiated() // our alert for letting the user know they need permission
                break
            }
          },
        )
```

my issue is that when we detect that a user only has `when in use` I call the above to try and get `always` permission. The alert is shown as expected, but before the user can turn on background permission the success callback fires with `BackgroundGeolocation.AUTHORIZATION_STATUS_WHEN_IN_USE`. This means if the user gives us `always` permission they then get an error from our app that they need background permission even though they just gave it.

**Comment by christocracy** [comment]
iOS is strict with location permission dialog.  You only get one shot at requesting the OS managed permission dialog.

After that, the OS prevents you from spamming the user to request permission.

**Comment by chrisdrackett** [comment]
ok, so even though the dialog is being presented by `BackgroundGeolocation.requestPermission` correctly I can't listen for its success a second time?

**Comment by christocracy** [comment]
Correct,  the plugin cannot know if iOS is going to present its dialog or not.  It's a tricky situation with OS-managed permission dialog.

**Comment by chrisdrackett** [comment]
got it, thanks I'll noodle on how to handle this edge case :)
