### ISSUE TITLE
Android Heartbeat event not firing

### ISSUE THREAD

**Issue by Gilipok** [transistorsoft/react-native-background-geolocation#1356]
## Your Environment
* Plugin version: 3.9.0
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung Galaxy A10
* React Native version (`react-native -v`): 0.63.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    {
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
      autoSync: true,
      autoSyncThreshold: 5,
      batchSync: true,
      stopTimeout: 5,
      enableHeadless: true,
      distanceFilter: 10,
      scheduleUseAlarmManager: false,
      locationAuthorizationRequest: 'Always',
      heartbeatInterval: 60,
      preventSuspend: true,
      speedJumpFilter: 300,
      stationaryRadius: 150,
      debug: false,
      logMaxDays: 5,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      url: 'https://mobile#############.com/post_v3_test/',
      foregroundService: true,
      params: {
        token: currentToken,
      },
      notification: {
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
        title: '##########',
        text: '#################',
        smallIcon: 'mipmap/ic_notification',
      },
```

## Expected Behavior
Getting the current coordinates at a specific interval using heartbeat.

## Actual Behavior
After HearbeatService run:
7971 14450 D TSLocationManager: [c.t.l.s.HeartbeatService$a run] ❤️
7971 14450 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
7971  7971 D TSLocationManager: [c.t.r.HeadlessTask onHeadlessEvent] 💀  event: heartbeat
7971  7971 D TSLocationManager: [c.t.r.HeadlessTask$2 onHeadlessJsTaskStart] taskId: 1
7971  8420 W ReactNativeJS: No task registered for key BackgroundGeolocation
7971 14450 D TSLocationManager: [c.t.l.service.AbstractService a] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
7971  7971 D TSLocationManager: [c.t.r.HeadlessTask$2 onHeadlessJsTaskFinish] taskId: 1
7971  7971 D TSLocationManager: [c.t.l.service.AbstractService onDestroy] 
7971  7971 D TSLocationManager:   🔴  HeartbeatService destroyed
it exits and cannot execute BackgroundGeolocation.getCurrentPosition()

## Steps to Reproduce

1. Launch the application.
2. The foreground-service will ON, then OFF.
3. Move the application to BACKGROUND mode and wait 5 minutes.
4. execute adb logcat

## Context

I need to get the current coordinates of the user, even if there is no movement, once every 1-2 hours using BackgroundGeolocation.onHeartbeat ():
```javascript <!-- Syntax-highlighting:  paste your code below -->
  BackgroundGeolocation.onHeartbeat(async (event) => {
    console.log('[onHeartbeat] ', event);
    await BackgroundGeolocation.changePace(true, () => {
      console.log('now is tracking');
    });

    await BackgroundGeolocation.getCurrentPosition({
      samples: 5,
      persist: true,
    }).then((location) => {
      console.log('GET CURRENT LOCATION: ', location);
    });
  });
```
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> No task registered for key BackgroundGeolocation

You did not call `BackgroundGeolocation.registerHeadlessTask(yourFunction)` in your app's root `index.js`

**Comment by Gilipok** [comment]
Thanks for fast response @christocracy, now it works.
