### ISSUE TITLE
Plugin is not STOPPED if terminating app with stopOnTerminated is true and location arrow is hollow color

### ISSUE THREAD

**Issue by hongtuanquyen** [transistorsoft/react-native-background-geolocation#1358]
## Your Environment
* Plugin version: 4.0.3
* Platform: iOS
* OS version: 14.3
* Device manufacturer / model: iphone 11 pro
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript
BackgroundGeolocation.ready(
    {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: DISTANCE_FILTER,
        locationAuthorizationRequest: 'Always',
        showsBackgroundLocationIndicator: true,
        disableLocationAuthorizationAlert: true,
        stopTimeout: 5,
        debug: false
    }, (state) => {
        if (state.enabled) {
            Alert.alert("configBackgroundGeolocation", "ENABLED");
        } else {
            Alert.alert("configBackgroundGeolocation", "DISABLED");
            BackgroundGeolocation.start();
        }
    }
);

...

componentWillUnmount() {
    BackgroundGeolocation.removeListeners();
    BackgroundGeolocation.stop();
 }
```

## Expected Behavior
Service Location is STOPPED after terminating app.

## Actual Behavior
Service Location is NOT STOPPED after terminating app.

## Steps to Reproduce
 1. Launch app
 2. Service ON -> OFF. Move app into BACKGROUND state
 3. Wait for awhile to let location arrow to be hollow color
 4. Kill app (location arrow is not disappeared)
 5. Re-Open app

## Context
I have checked my config stopOnTerminated and it is true, that means if I kill/terminate my app, service will be stopped (location arrow will be disappeared). 
However, it was not, the location arrow was still in Status bar with Hollow color. Then, I openned my app, alert show that it is ENABLED.
In step 3 and 4, if I don't wait for awhile and kill app immediately (arrow location is in solid color), service will be stopped.

I also check your Sample App in this link https://github.com/transistorsoft/rn-background-geolocation-demo. After cloning, I modified the stopOnTerminated to true and add Alert to show plugin state in HelloWorld.tsx.
Then, I repeated the steps like I listed, and it also show Alert with ENABLED state.
Step to reproduce in SampleApp:
1. Open Hello World screen
2. Toggle to start plugin. Allow all permissions (Always and Motion/Fitness)
3. Move app into BACKGROUND state
4. Wait for awhile to let location arrow to be hollow color
5. Kill app (location arrow is not disappeared)
6. Re-Open app

So, Is this behavior normal ? Are there any ways to really STOP plugin immediately(location arrow is disappeared immediately) after terminating app ?

I really appreciate any help.
Thank you so much!
@christocracy

**Comment by christocracy** [comment]
See api docs Config.stopOnTerminate.

**Comment by hongtuanquyen** [comment]
Thanks for you reply.
I think you may not understand my issue. I'll make this clearer.
I have read your docs Config.stopOnTerminate carefully before posting this. There are 2 things I understand from your docs.
First, with config stopOnTerminate = true, plugin will be stopped immediately if I kill my app regardless of OS (Android / iOS)
Second, with config stopOnTerminate = false, there are 2 different behaviors between iOS and Android.

I send you issue video, please take your little time to check this to know more about the issue:
https://youtu.be/oQxyK9o4aHY

At 0.10 -> 0.28: Kill app with solid location arrow in Status bar => state.enabled is false
At 0.28 -> the rest of video: Kill app with hollow location arrow in Status bar => state.enabled is true

@christocracy

**Comment by feras-merwas** [comment]
@hongtuanquyen did you manage to make it stop

**Comment by christocracy** [comment]
I've test this dozens of times in my demo app when people report this and it always works properly.

It always comes down to something you're doing in your own code / some other plugin responsible.

Go ahead and try the demo app.
