### ISSUE TITLE
App stops working after 10-15 mins in background and starts again when app is opened

### ISSUE THREAD

**Issue by mmjac10** [transistorsoft/react-native-background-geolocation#1359]
## Your Environment
* Plugin version: 4.1.1
* Platform:  Android
* OS version: 9
* Device manufacturer / model: OnePlus 5T
* React Native version (`react-native -v`): 0.64
* Plugin config
BackgroundGeolocation.ready(
      {
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: false, // <-- Auto start tracking when device is powered-up.,
      }

## Expected Behavior
App should run with along with the plugin in background.

## Actual Behavior
App stops running after 10-15 mins when in background.

##Steps to Reproduce
1. Start app
2. Press home icon to make app go to background
3. Wait for more than 10min 
4. Open app again. (App reboots)
 
## Context
I am trying to run an app which sends location updates on a Pubnub channel to users. this plugin is used to keep app running in background. I am calling BackgroudnGeolocation.start() as soon as user presses a toggle button. i have checked if the location is being tracked or not. I also installed the plugin's official app which also stops after a few mins and boots up again when i open it up.

**Comment by christocracy** [comment]
The OS can and will terminate dormant apps running in the background when the OS is under memory pressure.

If the device moves by about 200 meters, the OS will relaunch your app in the background and tracking will resume.

Try it.  Terminate your app with debug: true then go outside for a 1km walk.

**Comment by mmjac10** [comment]
> The OS can and will terminate dormant apps running in the background when the OS is under memory pressure.
> 
> If the device moves by about 200 meters, the OS will relaunch your app in the background and tracking will resume.
> 
> Try it. Terminate your app with debug: true then go outside for a 1km walk.

Okay, the app does relaunch. Is it possible to relaunch app in fewer than 200 meters? I am using the Headless method now to listen heartbeat events which is working for about 45min without moving much.

**Comment by christocracy** [comment]
> Is it possible to relaunch app in fewer than 200 meters?

No
