### ISSUE TITLE
iOS heartbeat skips intervals

### ISSUE THREAD

**Issue by mykolasmolis** [transistorsoft/react-native-background-geolocation#1363]
Again - thanks a lot for support so far! Coming back with an issue that might be straight forward to you. This is how I receive hearbeat custom URL posts to my back-end from iOS device with `preventSuspend: true` and `heartbeatInterval: 600, // 10 min`.

![image](https://user-images.githubusercontent.com/37137051/128719515-212c41a4-15cd-42f9-a0c9-5a9b71e35d6e.png)

I can see duplications (or 2 immediate heartbeats), but what is most important some beats are completelly missed - even 3 in a row.

Any ideas?

**Comment by christocracy** [comment]
The OS throttles heartbeat events for power-saving.  It can queue up several and fire them all at once.

**Comment by mykolasmolis** [comment]
Our solution makes an action if no heartbeat reported for 30 mins. I wonder if it would be more realiable to set heartbeat to 5 mins? To receive at least one in 30 mins?

**Comment by christocracy** [comment]
I don't know.  Try it.

**Comment by mykolasmolis** [comment]
Will test tomorrow - provide the results and we can close the ticket.

**Comment by mykolasmolis** [comment]
Set heartbeat interval to 5 mins. This is the backend log:

![image](https://user-images.githubusercontent.com/37137051/129677123-28f04c82-0ad7-4be3-ba2f-909bbd314493.png)

Since EXIT timeout is set to 30 mins. Rare skips between events is not an issue.

Thank you for help!
