### ISSUE TITLE
Location service start is super laggy on android

### ISSUE THREAD

**Issue by Travisrockgit** [transistorsoft/react-native-background-geolocation#1364]
## Your Environment
* Plugin version: 4.1.1
* Platform: Android
* OS version: Android 11
* Device manufacturer / model: Samsung Galaxy Note 10+ 5G
* React Native version (`react-native -v`): 0.61.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
The plugin Config:
componentWillMount() {

    // 1.  Wire up event-listeners

    BackgroundGeolocation.onLocation((location) => {
      if (location.coords.speed == null) { return }
      let mph = location.coords.speed * MPS_TO_MPH
      console.log(mph);
      if (mph < 0) { mph = 0.0 }
      const { prevVelocity, avcOn } = this.state
      if (Math.abs(prevVelocity - mph) >= 1) {
        this.setState({ volByAvc: true })
        if (avcOn) {
          this.updateManualVolume(mph)
        }

      }
    }, (error) => {
      console.warn('[location] ERROR -', error);
    })

    // 2.  Execute #ready method (required)
    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: true,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: false,        // <-- Auto start tracking when device is powered-up.

    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);


    });
  }
```
```javascript <!-- Syntax-highlighting:  paste your code below -->
How I am calling to start the location update:

  BackgroundGeolocation.start(function () {
      console.log("- Start success");
    });

```
## Expected Behavior

Location start updating continuously after "start()" function is called. 
## Actual Behavior

Location will update once and then stop. I was able to "activate" the update after calling BackgroundGeolocation.stop() and then then BackgroundGeolocation.start() several times. But I am not sure if this is a delay issue since I had tried waiting a while to stop and start, but could not see a clear pattern
## Steps to Reproduce

1. Go to the screen where the config loads
2. Call the start() function
3. Location updates once and then will stop

## Context

I am trying to start and stop the location update on demand (switch on and off). Any help would be appreciated! Also please let me know if this is the official support channel, I paid for a license specifically for android platform since this works really well. Thanks much!

**Comment by christocracy** [comment]
> Location start updating continuously after "start()" function is called.

This is not how it works.  Read the wiki *Philosophy of Operation*.  

It typically takes movement of ~200 meters before the plugin detects the device is moving and only then turns on location services to begin recording location.

**Comment by christocracy** [comment]
If you wish to manually toggle the plugin into the *moving* state, see api docs .changePace.

**Comment by Travisrockgit** [comment]
Got it, I will try it out. Thanks for your time.
