### ISSUE TITLE
Trying to convert to functional vs class components

### ISSUE THREAD

**Issue by russmenum** [transistorsoft/react-native-background-geolocation#1366]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^4.1.1",
* Platform: iOS or Android: IOS
* OS version: Launching iPhone 11 (iOS 14.3) 
* Device manufacturer / model: sim while debugging
* React Native version (`react-native -v`):  "react-native": "~0.63.4",
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
useEffect(() => {
		configureBackgroundGeolocation();
		// setInitialLocation();
		//loadMarkers();

		// Specify how to clean up after this effect:
		// return () => {
		// 	BackgroundGeolocation.removeListeners();
		// };
	}, []);


	const configureBackgroundGeolocation = async () => {
    console.log("THIS CODE RAN")
		////
    // 1.  Wire up event-listeners
    //

    // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.onLocation(onLocation, onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange(onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.onActivityChange(onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.onProviderChange(onProviderChange);

    ////
    // 2.  Execute #ready method (required)
    //
    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'http://yourserver.com/locations',
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "X-FOO": "bar"
      },
      params: {               // <-- Optional HTTP params
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        ////
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });

    const onLocation = (location) => {
      console.log('[location] -', location);
    }
    const onError = (error) => {
      console.warn('[location] ERROR -', error);
    }
    const onActivityChange = (event) => {
      console.log('[activitychange] -', event);  // eg: 'on_foot', 'still', 'in_vehicle'
    }
    const onProviderChange = (provider) => {
      console.log('[providerchange] -', provider.enabled, provider.status);
    }
    const onMotionChange = (event) => {
      console.log('[motionchange] -', event.isMoving, event.location);
    }
    
    //
	};
```

## Expected Behavior
I would expect this to log a location and do what it would in the class-based component

## Actual Behavior
I get 
```
 WARN     Possible Unhandled Promise Rejection (id: 1):
"BackgroundGeolocation#on must be provided a callback as 2nd argument.  If you're attempting to use the Promise API to listen to an event, it won't work, since a Promise can only evaluate once, while the callback function must be executed for each event."


```

## Steps to Reproduce

1. Create a functional component
2. use the modified example code  above to be in the standard for a functional vs class components
3. Try and run the app/component
4.

## Context
I am trying to update this to work using functional instead of class components so I can run this where I need to in this app and have access to hooks and context when making the ```BackgroundGeolocation.ready({``` config. I basicaly need access to useEffects and so on when the app is in the foreground or to track or not will probably not refresh right.  My understanding is if when I toggle tracking off I call ```BackgroundGeolocation.removeListeners();``` I will stop end background tracking?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
WARN     Possible Unhandled Promise Rejection (id: 1):
"BackgroundGeolocation#on must be provided a callback as 2nd argument.  If you're attempting to use the Promise API to listen to an event, it won't work, since a Promise can only evaluate once, while the callback function must be executed for each event."
```

</details>

**Comment by russmenum** [comment]
OK, I am iffy on how much I understand this tool, kind of just chucking along at the docs and getting there but convinced I am using some of it wrong. But since I had a hard time finding this going to close this ticket with an example code for how I used this in a functional component with hooks and side effects, and a state-based on-off switch.

```javascript <!-- Syntax-highlighting:  paste your code below -->
    const [activeTrack, setActiveTrack] = useState(false);

    BackgroundGeolocation.onLocation(location => {
      console.log("[location] ", location);
    }, error => {
      console.log("[location] ERROR: ", error);
    });
    BackgroundGeolocation.onHttp((response) => {
      console.log("[onHttp] ", response);
    });

    useEffect(() => {
      if (activeTrack) {
        configureBackgroundGeolocation();
      } else {
        BackgroundGeolocation.stop();
        BackgroundGeolocation.removeListeners();
      }
    }, [activeTrack]);

    const configureBackgroundGeolocation = async () => {
      // ////
      // // 2.  Execute #ready method (required)
      // //
      BackgroundGeolocation.ready({
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 150,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
        // HTTP / SQLite config
        url: 'http://yourserver.com/locations',
        batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
        headers: {              // <-- Optional HTTP headers
          "X-FOO": "bar"
        },
        params: {               // <-- Optional HTTP params
          "auth_token": "maybe_your_server_authenticates_via_token_YES?"
        }
      }, (state) => {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

        if (!state.enabled) {
          ////
          // 3. Start tracking!
          //
          BackgroundGeolocation.start(function() {
            console.log("- Start success");
          });
        }
      });
    };


```

I will need to reach out to see how the Android Keys work, not seeing if they cover the GOOGLE permission or not

**Comment by rpajf** [comment]
i used context to my application , this lib shoud use a hooks example, if u still wanna check `import AsyncStorage from '@react-native-community/async-storage';
import firestore from '@react-native-firebase/firestore';
import React, { createContext, useContext, useEffect, useState } from 'react';
import {requestLocationPermission} from './getPermission'
import BackgroundGeolocation from "react-native-background-geolocation";


const BgeolocationContext = createContext({})


const BGeolocationProvider = (
  { onLocation,
    onMotionChange,
    onActivityChange,
    onProviderChange,
    onError,
    children }
) => {
  Platform.OS === 'android' ? requestLocationPermission() : ''




  const _onLocation = (location) => {
    
    
  }
  const _onMotionChange = (location) => {
    console.log(location)

  }
  const _onActivityChange = (location) => {
    console.log(location)

  }
  const _onProviderChange = (location) => {
    console.log(location)

  }
  

  useEffect(() => {

    _onLocation();
  }, [BackgroundGeolocation.onLocation]);

  useEffect(() => {
    _onMotionChange();
  }, [BackgroundGeolocation.onMotionChange]);

  useEffect(() => {
    _onActivityChange();
  }, [BackgroundGeolocation.onActivityChange]);

  useEffect(() => {
    _onProviderChange();
  }, [BackgroundGeolocation.onProviderChange]);


  useEffect(() => {
    // BackgroundGeolocation.getCurrentPosition

    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'http://yourserver.com/locations',
      batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: { // <-- Optional HTTP headers
        'X-FOO': 'bar'
      },
      params: { // <-- Optional HTTP params
        auth_token: 'maybe_your_server_authenticates_via_token_YES?'
      }
    }, (state) => {
      console.log('- BackgroundGeolocation is configured and ready: ', state.enabled);

      if (!state.enabled) {
        /// /
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(() => {
          console.log('- Start success');
        });
      }
      console.log(state);

    });
  }, []);
 
  return (<BgeolocationContext.Provider>{children}</BgeolocationContext.Provider>)

}

const useBgeolocation = () => {
  const contxt = useContext(BgeolocationContext)
  return contxt
}
export { BGeolocationProvider, useBgeolocation };
`
