### ISSUE TITLE
Trying to configure the fetch for background tracking

### ISSUE THREAD

**Issue by russmenum** [transistorsoft/react-native-background-geolocation#1367]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^4.1.1",
* Platform: iOS or Android: iOS
* OS version: Launching iPhone 11 (iOS 14.3)
* Device manufacturer / model: Simulator
* React Native version (`react-native -v`): "react-native": "~0.63.4",
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'http://yourserver.com/locations',
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "Accept", "application/json",
        "Content-Type", "application/json",
        "Authorization", `Bearer ${userToken}`
      },
      // params: {               // <-- Optional HTTP params
      //   "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      // }
    }
```
Because I have zero control over this fetch I am somewhat blindly assuming the header and URL are being used right, and that it knows it should be a POST.
```javascript <!-- Syntax-highlighting:  paste your code below -->
var raw = JSON.stringify({
      "driver": var,
      "title": "ping",
      "lat": location["coords"]["latitude"],
      "lng": location["coords"]["longitude"]
    });

    var requestOptions = {
      method: 'POST',
      headers: myHeaders,
      body: raw,
      redirect: 'follow'
    };
```
But I still need a way to specify that the ```req.body``` should be as far as format and values to both send my props and the ```location["coords"]["latitude"]``` and ```location["coords"]["longitude"]``` this library would make correctly.

## Expected Behavior
I expect to have a way to configure the body of my POST like you would with a reak ```.fetch```. But I have no clue how

## Actual Behavior
Even when I have the log working in the console can not get it to the BE because I can not control the fetch. The BE will only accept a properly configured req. 

## Steps to Reproduce

1. Run a working config with no set up of the fetch POST object to match the spec of the BE
2.
3.
4.

## Debug logs DO NOT HAVE ANY AND NO CLUE WHERE TO LOG WHAT THIS CONTROLLED IN LIBRAY FETCH IS EVEN TRYING TO DO

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by russmenum** [comment]
To update I am just not following the doc on this

What I am trying to do
```javascript <!-- Syntax-highlighting:  paste your code below -->
httpRootProperty: 'body',
locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>}',
extras: {
        "driver": "TEST HARDCODE IOS 2",
        "title": "ping"//,
        // "lat": 1,
        // "lng": 1
}
```
in place of 
```javascript <!-- Syntax-highlighting:  paste your code below -->
var raw = JSON.stringify({
      "driver": var,
      "title": "ping",
      "lat": location["coords"]["latitude"],
      "lng": location["coords"]["longitude"]
    });

    var requestOptions = {
      method: 'POST',
      headers: myHeaders,
      body: raw,
      redirect: 'follow'
    };
```



result of 
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onHttp((response) => {
      // let status = response.status;
      // let success = response.success;
      // let responseText = response.responseText;
      console.log("[onHttp] ", response);
    });
```
is
```
[onHttp]  {"responseText": "{\"message\":\"4 validation errors occurred\",\"url\":\"\\/gpspoints\",\"code\":422}", "status": 422, "success": false}


```

BACK END SIDE
```
Error: [Crud\Error\Exception\ValidationException] 4 validation errors occurred 
```



These errors tell me the problem is the JSON body is not formatted correctly, but I am not seeing what would be wrong. Is the POST sending RAW or JSON.stringify? Tossed  ```httpRootProperty: 'body',``` on just in case it was something like that. But kind of at a loss on what is wrong with this body when the built-in fetch is setting it up?

**Comment by christocracy** [comment]
If it wasn't valid json, an http request wouldn't even be invoked.  I suggest you observe your http server logs and compare what is being posted vs what you expect and re-configure accordingly.

**Comment by russmenum** [comment]
@christocracy the ```Error: [Crud\Error\Exception\ValidationException] 4 validation errors occurred ``` is all I have on the BE side to go off of.

Is there any way to LOG FE side what this library is actually trying to POST? If I could just see what is going on I could debug this, but this controlled fetch makes it basicaly a black box

**Comment by russmenum** [comment]
OK after some hoops set up a mini node server to log all this in sand box

```
body: {
    location: {
      lng: -122.406417,
      lat: 37.785834,
      title: 'ping',
      driver: 'TEST HARDCODE IOS THEIR FETCH'
    }
  },
```

Is what it is producing. Is there a way to tell this to not nest in a ```location``` object?

**Comment by russmenum** [comment]
OK, I guess this is "resolved" given that an endpoint looking for ```req.body.location```;  but I would say a way to move that to the body with a parameter would be a great feater request. Not all projects will have control over the BE or it may be a different team. So a way to have that level of control over the req would be grate.

And while I have complained a lot. Thank you @christocracy
