### ISSUE TITLE
Broke react-native-google-maps-directions opening google maps on android

### ISSUE THREAD

**Issue by russmenum** [transistorsoft/react-native-background-geolocation#1368]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^4.1.1",
* Platform: iOS or Android: Android
* OS version: Android 7 test phone and Android 11 simulator
* Device manufacturer / model: Pixel 3a in sumlator, z2 force test phone
* React Native version (`react-native -v`): "react-native": "~0.63.4",
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
// Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'http://yourserver.com/locations',
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "X-FOO": "bar"
      },
      params: {               // <-- Optional HTTP params
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
```

## Expected Behavior
Before I added this library the [react-native-google-maps-directions
](https://github.com/tiaanduplessis/react-native-google-maps-directions) was working fine and opened google maps on both IOS and Android. Now on android, it is broken, I get this message about not having a key on android, but not sure why that would break opening google maps?

## Actual Behavior
Nothing the app kind of locks up and can't even try and run this on RELEASE, and in DEBUG I get an error about 
```
 WARN     Possible Unhandled Promise Rejection (id: 0):
Error: Could not open the url: https://www.google.com/maps/dir/?api=1&travelmode=driving&dir_action=navigate&destination=37.342853199500524%2C-121.85306267133025&origin=37.4219983%2C-122.084
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:118874:40
tryCallOne@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5605:16
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5706:27
_callTimer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30666:17
_callImmediatesPass@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30705:17
callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30922:33
__callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:4893:35
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:4679:34
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:4876:15
flushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:4678:21
flushedQueue@[native code]
```

## Steps to Reproduce

1. Install [react-native-google-maps-directions
](https://github.com/tiaanduplessis/react-native-google-maps-directions)
2. install react-native-background-geolocation
3. Try and use react-native-google-maps-directions to open google maps on Android
4.

## Context
Trying to open google maps to give the user turn by turn passing it the correct GPS points. Android app must be able to do this

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
 WARN     Possible Unhandled Promise Rejection (id: 0):
Error: Could not open the url: https://www.google.com/maps/dir/?api=1&travelmode=driving&dir_action=navigate&destination=37.342853199500524%2C-121.85306267133025&origin=37.4219983%2C-122.084
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:118874:40
tryCallOne@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5605:16
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5706:27
_callTimer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30666:17
_callImmediatesPass@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30705:17
callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30922:33
__callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:4893:35
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:4679:34
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:4876:15
flushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:4678:21
flushedQueue@[native code]
```

</details>

**Comment by christocracy** [comment]
Have you tried seeking support with the plugin reporting your error?

**Comment by russmenum** [comment]
@christocracy I have switched the Android side to direct Google Directions API link but was reporting the odd behavior as it is just odd... 

A bit off-topic; but as expected am getting all the LICENCE errors on ```release``` builds Android side even though we are not using this library at all Android side, at least not yet. 

Here are the concerns Android side:

1) with it doing all this Transistorsoft license validation: what would happen if Transistorsoft is down? Have no problem paying for good software. But, want to know the point of failure that comes with it. As stated even when the Android App is not using this at all it is still triggering FAILED LICENCE errors. I was expecting that once we tried to use it on Android not just because we are looking at setting that up. 

2) Because Android and Google are hyper-controlling on Background location and wanting all apps that use it to request and get approval to include ```<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />```; when using this library is all access in the foreground like it is in what we are doing now? With no way to test that before buying a key point I need to be clear on is if we would also need to get an OK from Google? Or this is 100% though ```android:foregroundServiceType``` and local to the device so there is no point of failure other than a user is blocking access to location?

Long and short I want to make sure we will never have downtime or errors on Android because of something at Transistorsoft. Or can that happen?

**Comment by christocracy** [comment]
>am getting all the LICENCE errors on release builds Android side even though we are not using this library at all Android side

That's correct.  Once the plugin is added, a license is required for release builds.

>with it doing all this Transistorsoft license validation: what would happen if Transistorsoft is down? 
 
The SDK does not validate license key remotely.  It's all done locally on the device.  There is no such thing as "Transistosoft downtime".

>Because Android and Google are hyper-controlling on Background location

This is between your and Apple / Google, whether they believe your app deserves the "Background Location " capability.   [See my blog for Android requirements](https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353) or how to opt-out.

**Comment by russmenum** [comment]
@christocracy IYO better to try and get this approved from day 1 or get a working ver of the app approved and then address this?

You have been a big help, and I assume you plan to stay around for at least a few years?

I am trying to figure out how that works, as I can see updates being needed overtime or things breaking. Are the TOS basically needing to rebuy keys/support every year even though keys do not exp? Or how do that work?

**Comment by christocracy** [comment]
> and I assume you plan to stay around for at least a few years?

I've been doing this full time for over 6 years (since Android 4; iOS 7) and I see no end in sight.

**Comment by christocracy** [comment]
Purchased keys unlock the plugin forever.  Optional yearly fee $165 provides another year access to the private repo for latest updates and priority support.

The public version on npm is mirrored from the private repo about every 3 months.
