### ISSUE TITLE
stopOnTerminate and startOnBoot possible influence on how app works in background

### ISSUE THREAD

**Issue by mykolasmolis** [transistorsoft/react-native-background-geolocation#1371]
Hi again - wanted to ask your help.

My current setup is:
![image](https://user-images.githubusercontent.com/37137051/129677616-7208a7ba-0c12-4ed0-80ec-60b5f48517e4.png)

Also geofence is set:
![image](https://user-images.githubusercontent.com/37137051/129677763-ca3b9f63-af6a-4d94-a4ff-8380be4a1fa4.png)

However, after Tipit app stays in background for some 12 hours - the geofence appears to stop working (even when `preventSuspend: true`, again - app is not terminated), no `ENTER`, `EXIT` events are fired.

What we noticed that when these settings were enabled:
```
stopOnTerminate: false,
startOnBoot: true,
```

The geofence appeared to work even after 12 hours app is not being used.

Does it mean that `stopOnTerminate` and `startOnBoot` config also has impact on the way app runs in background?

**Comment by christocracy** [comment]
iOS can and **will** terminate apps running in the background in order to free up memory for the app currently in the foreground.  After 24 hours in background, you should expect the OS to have *terminated* you app.

**Comment by mykolasmolis** [comment]
Thank you for confirmation.
