### ISSUE TITLE
http sync always returns 301 and success: false

### ISSUE THREAD

**Issue by kendenc** [transistorsoft/react-native-background-geolocation#1375]
## Your Environment
* Plugin version:
* Platform: iOS
* OS version: 14
* Device manufacturer / model: iPhone 11
* React Native version (`react-native -v`): 0.64.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready(
      {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 4,
        stopTimeout: 1,
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        url: 'http://localhost:8080',
        batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
        autoSyncThreshold: 1,
        heartbeatInterval: 1,
      },
      state => {
        console.log(
          '- BackgroundGeolocation is configured and ready: ',
          state.enabled,
        );
      },
    );
```

## Expected Behavior
The package will POST each new location to my server

## Actual Behavior
The package POSTs to my server and my server sees the request responding with a 200.

However the response `onHttp` listener shows a http status code of either `301` + `success: false` the result is that the package keeps retrying to send the first location.

## Context
I'm attempting to send location updates to server.
The server is an extremely basic nodejs server

I've tried:
- hosting the server on both linux and OSX within a home network and localhost
- simulator and physical device
- I can hit the server from my terminal using a curl request
- I can hit the server using a fetch request within the react native app

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Put an /endpoint on your url.

`http://localhost:8080/endpoint`
