### ISSUE TITLE
How to fire the location post event every 5 seconds.

### ISSUE THREAD

**Issue by binzailani3136** [transistorsoft/react-native-background-geolocation#138]
Hi
I think, by using your library, it only able to post the location in case of it detects that the location has been changed.
It means that, if I stay in one place for a long time and during that time, it is not able to fire the location post event.
Am I right?
Is there anyway to post the event every 5 second or every 1 second by using your library?
If that is possible, I will buy your Android version.
Thanks.

**Comment by christocracy** [comment]
The plugin was designed around Apple & Google's published guidelines for location-tracking.

time-based geolocation is a battery killer.  Android can allow it by configuring `{locationUpdateInterval: 5000, distanceFilter: 0}`.  "distanceFilter trumps locationUpdateInterval".  As soon as `distanceFilter > 0`, `locationUpdateInterval` is ignored.

iOS is strictly distance-based.

However, I just introduced a new [`#watchPosition`](https://shop.transistorsoft.com/blogs/news/new-backgroundgeolocation-feature-watchposition) method.  

The plugin also has a `#getCurrentPosition` method.
