### ISSUE TITLE
Inconsistency on Background location - Android

### ISSUE THREAD

**Issue by jaimebiernaski** [transistorsoft/react-native-background-geolocation#1382]
We are using this library in multiple android devices, but we are facing huge problems with inconsistency when the app in working on background. The lib starts sending the location as expected, but suddenly it stops, than it backs... Our solution needs integrity on getting the user location, but until the moment we were unable to achieve consistency.

We need figure out if there is some missing setup to fix this bug, or we should move on to other solution alternative.

## Your Environment
* Plugin version: "^4.1.1"
* Platform: Android
* OS version: Multiple
* Device manufacturer / model: Multiple
* React Native version (`react-native -v`): 0.63.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BGL.DESIRED_ACCURACY_HIGH,
  distanceFilter: 20,
  stationaryRadius: 10,
  notification: {
    title: 'Localização em segundo plano',
    text: 'ativada',
    smallIcon: 'drawable/ic_stat_onesignal_default',
    largeIcon: 'drawable/ic_stat_onesignal_default',
  },
  locationProvider: BGL.ACTIVITY_PROVIDER,
  stopOnTerminate: false,
  startOnBoot: false,
  httpRootProperty: '.',
  locationTemplate: LOCATION_TEMPLATE,
  batchSync: true,
  maxBatchSize: 20,
  autoSync: true,
  reset: true,
  foregroundService: true,
  stopTimeout: 100,
  debug: false,
  logLevel: BGL.LOG_LEVEL_ERROR,
  allowIdenticalLocations: false,
}
```

* The setup changes to 
```javascript <!-- Syntax-highlighting:  paste your code below -->
 const newConfig = {
      url: `${API}trips/driver/${driverId}/locations/batch`,
      headers: {
        Authorization: `Bearer ${token}`,
      },
      extras: {
        trip_id: tripId,
      },
    };

    if (actualState.extras?.trip_id === tripId) return;

    await BGL.setConfig(newConfig);
```

## Expected Behavior

Getting the user location constantly.

## Actual Behavior

1. starts
2. stops for a period 
3. sometimes it starts again
4. and so on

![BLG-issue](https://user-images.githubusercontent.com/31888408/130785008-f1ce9ab2-e4b3-4639-ac45-935efba410b9.png)

## Steps to Reproduce

It is an inconsistent behavior, we can not describe steps to reproduce it.

## Context

Get the location when the app it running (background and foreground)

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by mikehardy** [comment]
Probably device specific and related to https://dontkillmyapp.com/ / vendor-specific power-saving violations of Android AOSP background behavior rules

**Comment by jaimebiernaski** [comment]
There is some way to improve this with the lib setup? we already tried to send by batch, but didnt work.

**Comment by christocracy** [comment]
> There is some way to improve this with the lib setup?

I have never heard of this ever reported and looking at the source, I don't see how it's even possible.

**Comment by klougod** [comment]
> > There is some way to improve this with the lib setup?
> 
> I have never heard of this ever reported and looking at the source, I don't see how it's even possible.

We do the setup like shown above, and every time data is updated(via redux) we update the config with our trip data this way:

![image](https://user-images.githubusercontent.com/39575288/130832198-231d5419-ec6d-4e32-9048-54af0159f60c.png)

this forceSync function is there because when we want to update the settings and for some reason there are some locations to send it throw an exception, the way we found to solve this is:
![image](https://user-images.githubusercontent.com/39575288/130832510-1ee4e4cf-1463-46a6-850f-05270dfc75fb.png)

maybe you could help us improve this

**Comment by LadislavBohm** [comment]
In my experience it was happening on our Huawei phones. Solution was to go to Android settings for out app -> "App launch" -> "Manage automatically" -> set to **off**. Then we no longer experience drops of locations being recorded.
Note that other brands have similar settings with different name and even Huawei once renamed it.
