### ISSUE TITLE
Stop Always Location Permision 

### ISSUE THREAD

**Issue by denisvely** [transistorsoft/react-native-background-geolocation#1383]
![2021-09-07 13 52 57](https://user-images.githubusercontent.com/28669083/132333080-67e8e6ec-a821-4ef6-9999-1d65ac5ac2cb.jpg)
## Your Environment
* Plugin version: ^4.1.1
* Platform: iOS
* OS version: 14.6
* Device manufacturer / model: MGJ83GH/A
* React Native version (`react-native -v`): ~0.63.4
* Plugin config

BackgroundGeolocation.ready({
	locationAuthorizationRequest: 'WhenInUse',
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	distanceFilter: 500,
	activityRecognitionInterval: 10000, // Android
	fastestLocationUpdateInterval: 10000,
	forceReloadOnGeofence: true,
	stopOnTerminate: true,
	startOnBoot: true,
	foregroundService: true,
	heartbeatInterval: 60 * 10,
	logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
	autoSync: false,
	reset: true,
	extras: {
		route_id: 1,
		filterDistance: 500,
	},
	disableLocationAuthorizationAlert: true,
})

## Expected Behavior
Remove functionality for Always Location Permision and using only WhileInUse.
According to this params: disableLocationAuthorizationAlert, locationAuthorizationRequest

## Actual Behavior
After interacting with the app and then killing the app the Always Location Permision shows.

## Steps to Reproduce
After interacting with the react-native app and then killing it the Location Popup is shown.

## Context
Remove functionality for Always Location Permision and using only WhileInUse.

**Comment by christocracy** [comment]
Post your package.json

You are likely using another package that requests Always authorization.

**Comment by denisvely** [comment]
{
	"scripts": {
		"start": "react-native start",
		"android": "react-native run-android",
		"ios": "react-native run-ios",
		"web": "expo start --web",
		"eject": "expo eject",
		"debug-build": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ && cd android && ./gradlew assembleDebug && cd ..",
		"release-build": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/ && rm -rf android/app/src/main/res/drawable-* && rm -rf android/app/src/main/res/raw/* && cd android && ./gradlew assembleRelease && cd .."
	},
	"dependencies": {
		"@react-native-async-storage/async-storage": "^1.13.4",
		"@react-native-clipboard/clipboard": "^1.7.0",
		"@react-native-community/netinfo": "5.9.7",
		"@react-native-firebase/analytics": "~11.5.0",
		"@react-native-firebase/app": "~11.5.0",
		"@react-native-firebase/dynamic-links": "~11.2.0",
		"@react-native-masked-view/masked-view": "^0.2.6",
		"@react-navigation/bottom-tabs": "^5.11.7",
		"@react-navigation/native": "^5.9.2",
		"@react-navigation/stack": "^5.14.2",
		"@vseslav/react-native-horizontal-picker": "^0.1.1",
		"accordion-collapse-react-native": "^1.0.1",
		"axios": "^0.21.1",
		"deep-equal": "^2.0.5",
		"expo": "~40.0.0",
		"expo-constants": "~9.3.3",
		"expo-contacts": "~8.6.0",
		"expo-device": "~2.4.0",
		"expo-font": "~8.4.0",
		"expo-linear-gradient": "~8.4.0",
		"expo-local-authentication": "^11.1.1",
		"expo-localization": "~9.1.0",
		"expo-location": "~10.0.0",
		"expo-notifications": "~0.8.2",
		"expo-permissions": "~10.0.0",
		"expo-sms": "~8.4.0",
		"expo-splash-screen": "~0.8.1",
		"expo-status-bar": "~1.0.3",
		"expo-updates": "~0.4.0",
		"i18next": "^19.8.9",
		"lodash": "^4.17.21",
		"moment": "^2.20.1",
		"react": "16.13.1",
		"react-dom": "16.13.1",
		"react-i18next": "^11.8.7",
		"react-native": "~0.63.4",
		"react-native-appearance": "~0.3.3",
		"react-native-background-actions": "^2.6.0",
		"react-native-background-fetch": "^4.0.3",
		"react-native-background-geolocation": "^4.1.1",
		"react-native-calendars": "^1.17.0",
		"react-native-circular-progress": "^1.3.7",
		"react-native-countdown-circle-timer": "^2.5.1",
		"react-native-date-picker": "^3.3.2",
		"react-native-dropdown-picker": "^4.0.2",
		"react-native-gesture-handler": "~1.8.0",
		"react-native-google-fit": "^0.16.2",
		"react-native-health": "^1.7.1",
		"react-native-maps": "0.27.1",
		"react-native-otp-verify": "^1.0.4",
		"react-native-progress-bar-animated": "^1.0.6",
		"react-native-reanimated": "~1.13.0",
		"react-native-safe-area-context": "3.1.9",
		"react-native-screens": "~2.15.2",
		"react-native-shadow": "^1.2.2",
		"react-native-shadow-2": "^3.0.0",
		"react-native-svg": "^12.1.1",
		"react-native-svg-animations": "^0.2.6",
		"react-native-swipe-gestures": "^1.0.5",
		"react-native-text-gradient": "^0.1.7",
		"react-native-unimodules": "^0.12.0",
		"react-native-vector-icons": "^8.1.0",
		"react-native-web": "~0.13.12",
		"react-native-webview": "^11.6.5",
		"react-redux": "^7.2.2",
		"redux": "^4.0.5",
		"redux-devtools-extension": "^2.13.8",
		"rn-sliding-up-panel": "^2.4.5"
	},
	"devDependencies": {
		"@babel/core": "~7.9.0",
		"babel-eslint": "^10.1.0",
		"babel-jest": "~25.2.6",
		"eslint": "^7.20.0",
		"eslint-plugin-react": "^7.22.0",
		"jest": "~25.2.6",
		"prop-types": "^15.7.2",
		"react-test-renderer": "~16.13.1"
	},
	"private": true,
	"name": "dzihealthapp",
	"version": "1.0.0"
}

**Comment by christocracy** [comment]
Are you executing the method `BackgroundGeolocation.getCurrentPosition()` when your app boots?

**Comment by denisvely** [comment]
@christocracy - Yes.
Here is the whole .ready() function

BackgroundGeolocation.ready({
			locationAuthorizationRequest: 'WhenInUse',
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			distanceFilter: 500,
			activityRecognitionInterval: 10000, // Android
			fastestLocationUpdateInterval: 10000,
			forceReloadOnGeofence: true,
			stopOnTerminate: true,
			startOnBoot: true,
			foregroundService: true,
			heartbeatInterval: 60 * 10,
			logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
			autoSync: false,
			reset: true,
			extras: {
				route_id: 1,
				filterDistance: 500,
			},
			disableLocationAuthorizationAlert: true,
		})
			.then((state) => {
				console.log('- BackgroundGeolocation is ready: ', state.enabled);
				if (!state.enabled) {
					BackgroundGeolocation.start(async () => {
						if (isFirstLoad) {
							const userLocation = await getCurrentUserLocation();
							if (userLocation && !userLocation.sample) {
								sendLocation.fetch(userLocation);
							}
							isFirstLoad = false;
						}
					});
				}
			})
			.catch((error) => {
				console.log('- BackgroundGeolocation error: ', error);
			});

**Comment by christocracy** [comment]
Please learn to use [Github Syntax Highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) on code-blocks.

**Comment by denisvely** [comment]
> Are you executing the method `BackgroundGeolocation.getCurrentPosition()` when your app boots?

Yes, I am using it.

**Comment by christocracy** [comment]
Show me your code where you're executing `getCurrentPosition()` and `.ready()`

**Comment by denisvely** [comment]
````javascript

```javascript
export const getCurrentUserLocation = () => {
	return BackgroundGeolocation.getCurrentPosition({
		timeout: 5,
		persist: true,
		maximumAge: 5000,
		desiredAccuracy: 10,
		samples: 1,
	});
};

```
BackgroundGeolocation.ready({
			locationAuthorizationRequest: 'WhenInUse',
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			distanceFilter: 500,
			activityRecognitionInterval: 10000, // Android
			fastestLocationUpdateInterval: 10000,
			forceReloadOnGeofence: true,
			stopOnTerminate: true,
			startOnBoot: true,
			foregroundService: true,
			heartbeatInterval: 60 * 10,
			logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
			autoSync: false,
			reset: true,
			extras: {
				route_id: 1,
				filterDistance: 500,
			},
			disableLocationAuthorizationAlert: true,
		})
			.then((state) => {
				console.log('- BackgroundGeolocation is ready: ', state.enabled);
				if (!state.enabled) {
					BackgroundGeolocation.start(async () => {
						if (isFirstLoad) {
							const userLocation = await getCurrentUserLocation();
							if (userLocation && !userLocation.sample) {
								sendLocation.fetch(userLocation);
							}
							isFirstLoad = false;
						}
					});
				}
			})
			.catch((error) => {
				console.log('- BackgroundGeolocation error: ', error);
			});
````

**Comment by christocracy** [comment]
Now provide plugin logs where this is reproduced.  See wiki *Debugging*
