### ISSUE TITLE
Remove permission motion and fitness

### ISSUE THREAD

**Issue by dmontecillo** [transistorsoft/react-native-background-geolocation#1384]
## Your Environment
* Plugin version: Release 4.2.2
* Platform: iOS 
* OS version: 14.7.1
* Device manufacturer / model: iPhone 12
* React Native version (`react-native -v`):  0.64.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    // REMOVE FEATURE
    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    // BackgroundGeolocation.onMotionChange(onMotionChange);

    // This event fires when a change in motion activity is detected
    // BackgroundGeolocation.onActivityChange(onActivityChange);
```
Removes content in info.plist as well

## Expected Behavior
It should not ask `Motion and Fitness` permission

## Actual Behavior
Rejected by Apple since it requires a information in info.plist

## Steps to Reproduce
1. Include latest release library 4.2.2
2. Remove option to get location by motion and activity 
3. Remove plist information regarding motion and fitness

## Context
Removal of Motion and Fitness permission

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs Config.disableMotionActivity

**Comment by chrisl777** [comment]
Note that the docs discourage disabling, as it will drain battery power more quickly. It is strongly recommended not to disable, see notes: https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#disablemotionactivityupdates

**Comment by christocracy** [comment]
I just wrote that to scare people into not disabling it.
