### ISSUE TITLE
Android listeners when app is killed

### ISSUE THREAD

**Issue by hasan642** [transistorsoft/react-native-background-geolocation#1386]
## Your Environment
* Plugin version: 4.2.2
* Android
* OS version:  11
* Device manufacturer / model:  Realme (RMX3081)
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  reset: true,
  // Geolocation Config
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 5,
  // Activity Recognition
  stopTimeout: 5, // 5 minutes by default
  stationaryRadius: 25,
  // Application config
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
  startOnBoot: true, // <-- Auto start tracking when device is powered-up.
  heartbeatInterval: 60000,
  disableMotionActivityUpdates: true,
  enableHeadless: false,
  allowIdenticalLocations: false,
  maxDaysToPersist: 1,
  logMaxDays: 0, // <-- disabled logs
  stopOnStationary: true,
  useSignificantChangesOnly: true,
  showsBackgroundLocationIndicator: true,
  // geofencing config.
  geofenceProximityRadius: 2000,
  geofenceModeHighAccuracy: true,
  geofenceInitialTriggerEntry: true, // notify immediatly if the device in geofence area when start the plugin
  locationUpdateInterval: 2000,
  triggerActivities: 'on_bicycle,in_vehicle,on_foot,walking,running',
  persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
  foregroundService: true,
```

## Expected Behavior
should execute the onLocation call back when i move

## Actual Behavior
triggers events (sound debugging) and native logs appeared but js listeners not executed

## Steps to Reproduce
``` /**
 * @prettier
 *
 * File: Geofencing.tsx
 * Developed By Hasan Alawneh
 * Email: alawneh@zenhr.com
 * Date: 2021-09-06
 * Desc: This file contains a Geofencing component.
 */

import { useEffect } from 'react';
import BackgroundGeolocation, {
  Location as BGLoc,
  LocationError as BGLocError,
  ProviderChangeEvent as BGProviderChangeEvent,
  GeofenceEvent as BGGeofenceEvent,
  Geofence as BGGeofence,
} from 'react-native-background-geolocation';
import { config } from 'utils/geofencing';
import * as Sentry from 'sentry-expo';
import { reduxStore, RootState } from 'reducers';
import { useSelector } from 'react-redux';
import { Platform } from 'react-native';

/**
 * A function component with no UI that
 * * handles geofencing events.
 */
function Geofencing() {
  // use redux state.
  const employeeData = useSelector((s: RootState) => s.employee);
  const isAutoClockInOutEnabled = employeeData.profile.employee?.auto_mobile_clock_in_out;

  /**
   * Handles on new location recieved.
   */
  const onLocation = (l: BGLoc) => {
    console.log('Location recieved:', l);
  };

  /**
   * Handles on location error.
   */
  const onLocationError = (e: BGLocError) => {
    console.log('location error:', e);
  };

  /**
   * Handles on the provider changes.
   */
  const onProviderChange = (p: BGProviderChangeEvent) => {
    console.log('provider chnaged:', p);
  };

  /**
   * Subscribes on geofencing events.
   */
  const onGeofence = async ({ action, identifier, location, extras }: BGGeofenceEvent) => {
    console.log('[GEOFENCE]:- ', { action, identifier, location, extras });
    Sentry.Native.captureMessage(JSON.stringify(`${Platform.OS}- ${action}`));
    Sentry.Native.captureMessage(JSON.stringify({ action, identifier, location, extras }));
    // get some requied data from the storage side
    // to make an apis.
    // const serverUrl = await StorageHelper.get('server_url');
    // const auth = await StorageHelper.get('app_auth_token');
    // // grap the params.
    // if (action === 'ENTER') {
    //   console.log('enter the geofence', identifier);
    //   Sentry.Native.captureEvent({
    //     tags: {
    //       serverUrl: JSON.stringify(serverUrl),
    //       auth: JSON.stringify(auth)
    //     }
    //   });
    // } else if (action === 'EXIT') {
    //   console.log('exit the geofence', identifier);
    //   Sentry.Native.captureEvent({
    //     tags: {
    //       serverUrl: JSON.stringify(serverUrl),
    //       auth: JSON.stringify(auth)
    //     }
    //   });
    // }
  };

  /**
   * Subscribes to enabled state changes.
   */
  const onEnabledChange = (isEnabled: boolean) => {
    console.log('enabled state changed', isEnabled);
  };

  // ready the geofencing plugin.
  useEffect(() => {
    (async function () {
      console.log({ isAutoClockInOutEnabled });
      if (!isAutoClockInOutEnabled) return;

      // get data from redux store direct.
      const workBranches = reduxStore.getState().employee.profile.employee?.work_locations || [];

      // trsnaform work location to geofence.
      const regions: BGGeofence[] = [];
      workBranches?.forEach((it) => {
        regions.push({
          identifier: String(`${it.name}-${it.id}`),
          latitude: parseFloat('31.9588137'),
          longitude: parseFloat('35.8687151'), 
          radius: 200,
          notifyOnEntry: true,
          notifyOnExit: true,
          notifyOnDwell: true,
        });
      });

      // monitor all geofences.
      await BackgroundGeolocation.addGeofences(regions);

      // wire up event-listeners
      BackgroundGeolocation.onLocation(onLocation, onLocationError);
      BackgroundGeolocation.onProviderChange(onProviderChange);
      BackgroundGeolocation.onGeofence(onGeofence);
      BackgroundGeolocation.onEnabledChange(onEnabledChange);

      // ready the plug-in with the config.
      BackgroundGeolocation.ready(config, (s) => {
        if (!s.enabled) {
          BackgroundGeolocation.startGeofences(() => {
            console.log('- Start success');
          });
        }
      });
    })();
  }, [isAutoClockInOutEnabled]);

  // kill listeners when close the app.
  useEffect(() => {
    return function () {
      BackgroundGeolocation.removeListeners();
    };
  }, []);

  return null;
}

/**
 * export as default
 */
export default Geofencing;
```

## Context
I'm trying to monitor geofences with .startGeofences (no location tracking)

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs Config.enableHeadless

**Comment by hasan642** [comment]
- should is use enableHeadless if i want to use callbacks such as "onLocation", what about iOS is needs that?
- on Android it is not working even with "enableHeadless", headless task is not triggered when app is killed !
- can i read the redux state when app killed?

and please write down the link of example app.
thank you

**Comment by christocracy** [comment]
>should is use enableHeadless if i want to use callbacks such as "onLocation", what about iOS is needs that?

You don't yet understand [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode).  Your React Native App does not exist in the headless state.  There are no `onLocation` event-listeners in headless mode.

All plugin events are routed to your registered headless-task in the terminated state.

>what about iOS is needs that?

*Headless Mode* is an Android-only mechanism.  On iOS, the entire app is re-launched in the background when tracking occurs, just as if launched from the home-screen.  There is no such thing as *Headless Mode* on iOS.

>on Android it is not working even with "enableHeadless", headless task is not triggered when app is killed !

See Wiki *Debugging* and learn to observe the plugin logs.

>can i read the redux state when app killed?

This has nothing to do with the plugin.

**Comment by rpajf** [comment]
@christocracy the correct way of removing listeners on a functional component would be ?
`useEffect(()=>{
      configureBackgroundlocation()
      return () => Backgroundgeolocation.removeListeners()
},[someConditionToStop])`

**Comment by hasan642** [comment]
it is working perfectly now with headless task, but with mock location only !!
if i tested on my real device (driving or walking) service is not triggered.

my code:
`
import { Component } from "react";
import BackgroundGeolocation from "react-native-background-geolocation";
import * as Sentry from "@sentry/react-native";

export default class App extends Component {
  async componentDidMount() {
    // add geofence
    try {
      await BackgroundGeolocation.addGeofences([
        {
          identifier: "My Home",
          latitude: 32.0203081,
          longitude: 36.0085815,
          radius: 200,
          notifyOnEntry: true,
          notifyOnExit: true,
          notifyOnDwell: true,
        },
      ]);
      Sentry.captureMessage("geofenced added");
    } catch (e) {
      Sentry.captureMessage(
        "error in add geofence " + JSON.stringify(e.message)
      );
    }

    ////
    // 1.  Wire up event-listeners
    //

    // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.onLocation(this.onLocation, this.onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange(this.onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.onActivityChange(this.onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.onProviderChange(this.onProviderChange);

    BackgroundGeolocation.onGeofence((e) => {
      Sentry.captureMessage(
        "in geofence component " + JSON.stringify(e.action)
      );
    });

    ////
    // 2.  Execute #ready method (required)
    //
    BackgroundGeolocation.ready(
      {
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        // HTTP / SQLite config
        url: "http://yourserver.com/locations",
        batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
        headers: {
          // <-- Optional HTTP headers
          "X-FOO": "bar",
        },
        params: {
          // <-- Optional HTTP params
          auth_token: "maybe_your_server_authenticates_via_token_YES?",
        },
        enableHeadless: true,
        geofenceInitialTriggerEntry: true,
      },
      (state) => {
        console.log(
          "- BackgroundGeolocation is configured and ready: ",
          state.enabled
        );

        if (!state.enabled) {
          ////
          // 3. Start tracking!
          //
          BackgroundGeolocation.start(function () {
            console.log("- Start success");
            Sentry.captureMessage("servce started");
          });
        }
      }
    );
  }

  // You must remove listeners when your component unmounts
  componentWillUnmount() {
    BackgroundGeolocation.removeListeners();
  }
  onLocation(location) {
    console.log("[location] -", location);
  }
  onError(error) {
    console.warn("[location] ERROR -", error);
  }
  onActivityChange(event) {
    console.log("[activitychange] -", event); // eg: 'on_foot', 'still', 'in_vehicle'
  }
  onProviderChange(provider) {
    console.log("[providerchange] -", provider.enabled, provider.status);
  }
  onMotionChange(event) {
    console.log("[motionchange] -", event.isMoving, event.location);
  }

  render() {
    return null;
  }
}
`
platform: Android 11

thank you @christocracy

**Comment by christocracy** [comment]
The problem can only be due to your particular device.  See https://dontkillmyapp.com

**Comment by hasan642** [comment]
but yesterday it was working well !
sometimes working well, sometimes not.
