### ISSUE TITLE
Support for Visits Location Service?

### ISSUE THREAD

**Issue by zkwentz** [transistorsoft/react-native-background-geolocation#1387]
```
Note: More of a question than an issue.
```

Does this plugin support (or plan to support) the [Visits Location Service](https://developer.apple.com/documentation/corelocation/getting_the_user_s_location/using_the_visits_location_service) from iOS?

**Comment by christocracy** [comment]
It's never been a popular request over the last 5 years or so.

**Comment by zkwentz** [comment]
Understood, thanks for the fast response!
