### ISSUE TITLE
How to send the latitude and longitude only to the server?

### ISSUE THREAD

**Issue by binzailani3136** [transistorsoft/react-native-background-geolocation#139]
Hi.
I've some curious please.
If I configure server url here, I think, it seems that it sends all information to server with this structure format.

```json
{"coords":{"speed":0,"longitude":-122.0312186,"latitude":37.33233141,"accuracy":10,"heading":-1,"altitude":0,"altitudeAccuracy":-1},"is_heartbeat":false,"is_moving":true,"odometer":10696.46724283703,"uuid":"17FE2514-AEC4-41FE-A186-0B40493750FB","activity":{"type":"unknown","confidence":100},"battery":{"level":-1,"is_charging":false},"timestamp":"2016-09-26T13:27:27.763Z"}
```

But I would like to send only the current latitude and longitude to the url which is configured here like this format.
BackgroundGeolocation.configure({

``` json
url:'http://abc/post.php',
params:{
     latitude: current latitude fetched by this library,
     longitude: current longitude fetched by this library
}
```

How can I do this?
Is it possible or do I need to do this here?

``` Javascript
        BackgroundGeolocation.on('location', function(location) {
            console.log('- [js]location: ', JSON.stringify(location));
            //send current latitude and longitude to hosting server.
        });
```

Thanks.

**Comment by christocracy** [comment]
It's not possible currently.  I've toyed with the idea of adding a configurable template to render the JSON response but it needs more work.

**Comment by binzailani3136** [comment]
Thanks for your reply.
Then If I don't put url on BackgroundGeolocation.configure({...}) and put the post request here BackgroundGeolocation.on('location', function(location) {
            console.log('- [js]location: ', JSON.stringify(location));
            //send current latitude and longitude to hosting server.
});
Then what happened?
Is it possible?
Could I stop post request which is configured by default and customise it as my mind?

**Comment by christocracy** [comment]
If you don't provide an `#url`, the plugin's built-in http layer is disabled.  You're free to do anything you wish in *any* of the event-callbacks, including performing your own HTTP request.

If you care about `stopOnTerminate` on **Android** though, your Javascript isn't running when the user terminates the app.  The plugin's native background-service is unaffected by app-termination and can continue posting to your server with the built-in http layer.  If you disable the plugin's http layer, your server will no longer receive locations until the app is rebooted (the background-service will continue to persist these locations to is SQLite db, available via `#getLocations` method).

**Comment by binzailani3136** [comment]
Thanks.
And that means, If I don't provide an #url to default configuration of this library, and implement my own http request on event-callbacks, it will not send locations anymore when app has been terminated?

**Comment by christocracy** [comment]
If you don't provide an `#url`, the plugin's HTTP layer is completely **disabled**.

**Comment by binzailani3136** [comment]
Very thanks for your answer.
Another question is - When the network connection is not available, it seems that It stores all location data to sqlite3 database on local storage and once the connection is established, it sends them all data at time to the url provided on default configuration.
Am I right?

**Comment by christocracy** [comment]
The plugin persists each recorded location to SQLite, regardless of anything (unless plugin is `#stop`ped or configured with `maxRecordsToPersist: 0` or you `#getCurrentPosition` with options `{persist: false}`.

After a location is persisted, the plugin asks "am I configured with an `#url` and `autoSync: true`?  if so: `SELECT * FROM locations` and begin POSTing.

When the plugin's http layer receives `200 OK` from your server, it `DELETE`s that location from its db.

**Comment by binzailani3136** [comment]
And another question is, I applied stopOnTerminate: false and terminated the app.
In this case, It seems that background service don't posts the locations to server anymore.
Location post request not more fired.
But I want to send user's location regularly to the server depends on his movements even the app has been terminated.
It seems that this is not working as background service.

This is what I did for configuration.
BackgroundGeolocation.configure({
            enabled: true,
            desiredAccuracy: 10,
            stationaryRadius: 25,
            distanceFilter: 10,
            stopTimeout: 1,       
            debug: true, 
            stopOnTerminate: false, 
            startOnBoot: true,        
            url: Global.API_URL + '/position/_set',
            batchSync: false,     
            autoSync: true,        
            maxDaysToPersist: 1,    
            headers: {             
                'Content-Type': 'application/json',
            },
            params: {             
                token : Global.APP_PREFS.TOKEN
            },
     },

**Comment by christocracy** [comment]
when you post code, surround it with [3-backticks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).  You can specify the language to highlight as well.  I've been editing each of your posts so far.  Edit your previous post to show how it's done.

On iOS, when user terminates the app, your app *does* terminate and posts *will* stop for a brief period, until the device moves another 100-200 meters or the plugin receives a "background-fetch" event (typically every 15min).  When the first of those conditions occurs, iOS will reboot your app in the background and the plugin will resume tracking.

**Comment by christocracy** [comment]
To see a demo video of this behaviour of terminating iOS app with `stopOnTerminate: false`, go [here](http://www.transistorsoft.com/shop/products/react-native-background-geolocation), scroll down to video.

Or simply try it yourself:  boot your app in Simulator and enabled `Debug -> Location -> Freeway Drive`.  Kill your app.  Wait and watch.

**Comment by binzailani3136** [comment]
Thanks so much and very sorry for my rough issue postings. I will beautify postings in future. :)
And very sorry for disturbing you but two more questions please...

If I don't want to post the location logs to server which are stored while I am not connected to network, How can I do?

And If the the network is not available, is it automatically stop posting locations or continue to try post even it fails due to bad network connection.

Now, I am very happy to know that such library is available for React Native.
So, I will definitely use this library for my project.

**Comment by binzailani3136** [comment]
I don't need to store the location logs to local sqlite database while I am not connected to network and I also don't need to send them at once when the connection is get recovered. 
Just only need to send the locations of movements  while I am connected to network.

**Comment by christocracy** [comment]
>If I don't want to post the location logs to server which are stored while I am not connected to network, How can I do?

There's a `#clearDatabase` method.

>And If the the network is not available, is it automatically stop posting locations or continue to try post even it fails due to bad network connection.

As long as there are records in the database, the plugin will keep trying until your server says "200 OK".  If `maxDaysToPersist` expires on any record's timestamp, the plugin will delete those records.  The plugin will also respect `maxRecordsToPersist`.

**Comment by christocracy** [comment]
I suggest you find some plugin that allows you to detect whether you're connected to network or not.

once you do that, you're free to reconfigure the plugin at any time.  If you were to `setConfig({maxRecordsToPersist: 0})`, the plugin will no longer persist any locations to its database (a value of `-1` means no limit).

**Comment by binzailani3136** [comment]
It means that even network is available and if I put ''maxRecordsToPersis: 0 , it doesn't post the locations to server?

**Comment by christocracy** [comment]
If you tell the plugin `maxRecordsToPersist: 0`, it immediately deletes all records from the database.

Like I said, the plugin's HTTP layer operates by `SELECT * FROM locations`.  If that query returns 0 records, there's nothing to sync.

**Comment by binzailani3136** [comment]
And could you explain relations about `maxRecordsToPersist` and `maxDaysToPersist`? For example,

**Comment by binzailani3136** [comment]
Could you explain relation between `maxDaysToPersist` and `maxRecordsToPersist`?

**Comment by binzailani3136** [comment]
Could you explain relation between `maxDaysToPersist` and `maxRecordsToPersist`?

**Comment by binzailani3136** [comment]
Could you explain relation between `maxDaysToPersist` and `maxRecordsToPersist`? For example, If I set `maxRecordsToPersist:5` and `maxDaysToPersist:1`, then only 5 location logs are stored and they are not updated during 1 day and they will updated after 1 day later and again and again?

**Comment by christocracy** [comment]
`maxDaysToPersist` is the maximum number of days a record is allowed to live in the database.
`maxRecordsToPersist` is the total number or records allow to live in the database.  If you configure `maxRecordsToPersist: 10` and the plugin inserts a records such that the count becomes **11**, the plugin will delete the oldest record so that the count is **10** again.

**Comment by christocracy** [comment]
If you configure `maxDaysToPersist: 1` while the plugin contains some number of records, close the app at `12:00 pm`, then re-open the app tomorrow at `12:00 pm`, the db will be empty.

**Comment by binzailani3136** [comment]
Aha. so even I set `maxRecordsToPersist:5`, it automatically stores new data and deletes old data.
What I want to do is - While I lost connection, I don't want to post locations and also don't want to store the locations on local sqlite db but once the connection recovered, I would like to start to post the locations which retrieved after connection recovered.
Summarise:
1) need to use 3rd party library to know if connection is lost or not.
2) once if i get the connection status, I can configure `enabled` option as `true` or `false` depend on network connection. 
Here I am not sure if it is right for turn on and turn off this service.
And also, I don't know if this service will start immediately if I turn on this service by calling `bgGeo.start();` or configuring `enabled:true`.
3) If I set `maxRecordsToPersist:1`, it will send only 1 location log after connection is recovered.
Here, I also have a question. If I configure as `maxRecordsToPersist:1`, maybe, at the every time of adding new data, it will also delete the log every time because maximum log count is only 1.
So can it be the reason of slowing the app performance?
I am really taking care of the performance of app.

Could you advise me what should be the best option in my case?

**Comment by fgaleano** [comment]
Just wanted to comment that I would like to see a configurable template for the JSON payload. That way we can customize what we send and discard things that we don't need.

**Comment by christocracy** [comment]
I've been experimenting with this today:

```Obj-c
NSString *template = @"{\"coords\":{\"lat\":{{latitude}}, \"lng\":{{longitude}}, \"speed\":{{speed}}, \"heading\":{{heading}}, \"accuracy\":{{accuracy}}}, \"battery\":{\"lev\":{{battery_level}}, \"chg\":{{battery_is_charging}}}, \"event\":\"{{event}}\", \"is_moving\":{{is_moving}}, \"uuid\":\"{{uuid}}\", \"extras\":{{extras}} }";
```

```json
{"coords":{"lat":37.65334007, "lng":-122.45534515, "speed":31.92, "heading":314.3, "accuracy":5}, "battery":{"lev":-1, "chg":false}, "event":"", "is_moving":true, "uuid":"0F35B214-93F2-4AA5-A83A-ADBCCBD9D806", "extras":null }
```

@all Please provide some example template you might use.  I wonder if people might want to send an `[]`, eg:

```
template: "[{{latitude}}, {{longitude}}, {{speed}}]"
```

**Comment by christocracy** [comment]
Array-data will work too:
```Obj-c
NSString *template = @"[{{latitude}}, {{longitude}}, {{heading}}, {{speed}}]";
```

```json
[37.57412937, -122.3999204, 329.77, 33.73]
```

**Comment by fgaleano** [comment]
@christocracy I liked the first approach, it would even let us set up our own object properties which is nice. The only downside is the escaping of strings and extra characters. But I'm assuming that is a limitation of the template syntax.

**Comment by christocracy** [comment]
I'm nearly ready to post a beta-version to the [Premium Repo](http://www.transistorsoft.com/shop/products/react-native-background-geolocation).  It won't arrive here in the Free version for some time.

Escaping is not necessary:  that was just because it was `Obj-c` I posted above.  The templates will come via your Javascript config `{}` sent to `#configure`:
```
config = {
  httpRootProperty: 'data',
  locationTemplate: '{"event":"{{event}}", "timestamp":"{{timestamp}}", "uuid":"{{uuid}}", "lat":{{latitude}}, "lng":{{longitude}}, "spd":{{speed}}, "acy":{{accuracy}}, "alt":{{altitude}}, "alt_acy":{{altitude_accuracy}}, "is_moving":{{is_moving}}, "odometer":{{odometer}}, "battery":"{{battery_level}}:{{battery_is_charging}}", "activity":"{{activity_type}}:{{activity_confidence}}"}'
};

```

```
------------------------------------------------
- POST /locations
 {
  "data": {
    "uuid": "179318E4-BE2E-436F-BDA7-BC814DC1806E",
    "odometer": 6399.2,
    "timestamp": "2017-02-14T22:26:51.911Z",
    "battery": "-1:false",
    "lat": 37.49878972,
    "spd": 33.87,
    "settings.extras": "location-extras",
    "is_moving": true,
    "acy": 5,
    "lng": -122.31639398,
    "alt_acy": -1,
    "alt": 0,
    "activity": "unknown:100"
  },
```

**Comment by christocracy** [comment]
This is done.

**Comment by soban1234** [comment]
@christocracy i have to send my current lat long to server, i provide url in url field, headers in headers, now where to write lat long to send?

**Comment by christocracy** [comment]
@soban1234 search api docs for “HTTP Guide”
