### ISSUE TITLE
'TSBackgroundFetch/TSBackgroundFetch.h' file not found

### ISSUE THREAD

**Issue by datoonw13** [transistorsoft/react-native-background-geolocation#1391]
when I'm trying to archive a project using Xcode I'm getting this error: 
"'TSBackgroundFetch/TSBackgroundFetch.h' file not found"

It worked before. now I can generate the debug build but the release build fails, not sure why. 
I've removed and reinstalled plugins, pods, restarted xcode but still not working.

"react-native-background-fetch": "^4.0.1",
"react-native-background-geolocation": "^4.3.0",

## Your Environment
* Plugin version:
* Platform: iOS
* OS version: MacOS 11.5.2
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
the build fails

## Actual Behavior
the build should succeed

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
/Users/davit/Desktop/projects/socialize-front-end/node_modules/react-native-background-fetch/ios/RNBackgroundFetch/RNBackgroundFetch+AppDelegate.m:11:9: 'TSBackgroundFetch/TSBackgroundFetch.h' file not found
```
</details>

**Comment by christocracy** [comment]
- XCode version
- `$ pod --version

**Comment by datoonw13** [comment]
Xcode: 12.5.1 (12E507)
pod: 1.11.2

**Comment by christocracy** [comment]
Duplicate #902

**Comment by IronTony** [comment]
Also here I wrote the same: https://github.com/transistorsoft/react-native-background-fetch/issues/359
Xcode: 12.5.1
pod: 1.11.2

**Comment by IronTony** [comment]
@datoonw13  Check this settings: 
![image](https://user-images.githubusercontent.com/3645225/133892273-e008e768-edaf-4d21-ade5-c5497ec5e9d2.png)

**Comment by datoonw13** [comment]
@IronTony it was 10.0
I've changed to 11.0 and it works now, thanks.
