### ISSUE TITLE
Is it possible to get ENTER or EXIT geofence status by calling a lib method?

### ISSUE THREAD

**Issue by mykolasmolis** [transistorsoft/react-native-background-geolocation#1392]
Took a look at geofence methods - could not find a method that would return geofence state. Thanks in advance!

**Comment by christocracy** [comment]
There is no method to query geofence state.

Listen to onGeofence event to be informed of geofence events when they happen and save your own state as desired.

**Comment by mykolasmolis** [comment]
Thanks, makes sense!
