### ISSUE TITLE
Apple Silicon not supported

### ISSUE THREAD

**Issue by rubenmaas** [transistorsoft/react-native-background-geolocation#1395]
## Your Environment
* Plugin version: 4.3.0
* Platform: iOS
* OS version: 15.0
* Device manufacturer / model: Simulator
* React Native version (`react-native -v`): 0.64.1
* Plugin config: N/A

## Expected Behavior
We're expecting the app to build to the simulator

## Actual Behavior
Build fails with the following error

```
⚠️  ld: Could not find or use auto-linked framework 'TSBackgroundFetch'
⚠️  ld: Could not find or use auto-linked framework 'GoogleAppMeasurement'

❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps to Reproduce
All steps are done on a MacBook Pro 13" with Apple Silicon
1. Install the package as documented
2. Install pods
3. Build the app

## Context
We really would like to add this package to an existing app.

## Debug logs
N/A

**Comment by christocracy** [comment]
Mac Silicon support was introduced in [`background-geolocation` `v4`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#400--2021-03-09) and [`background-fetch`  `v4`](https://github.com/transistorsoft/react-native-background-fetch/blob/master/CHANGELOG.md#400--2021-02-12)

I bought myself a new Macbook Air with Apple Silicon specifically to test support for new Apple silicon.

**Comment by mikehardy** [comment]
I use it successfully on an M1 mac.
It's not easy though in general - react-native on an M1 is very subtle, and Xcode builds in general on an M1 are subtle.

Using react-native 0.65.1, and Xcode 12.5.1 or Xcode 13, and an M1, you will likely want this entire chunk in your Podfile at the end

```ruby

    installer.aggregate_targets.each do |aggregate_target| 
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
          # without explicitly clearing this out, it flaps between excluding arm64 or not
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = ""
          # Fix some library / linker errors
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
          config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
          config.build_settings['EXCLUDED_ARCHS'] = 'i386'
        end
      end
      aggregate_target.user_project.save
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|

        # We support a smaller range of deployment than some libraries, eliminate related noise
        # This also avoids a nasty Folly bug about an API not available until ios10+
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSMinimumDeployVersion

        # Using the un-qualified names means you can swap in different implementations, for example ccache
        config.build_settings["CC"] = "clang"
        config.build_settings["LD"] = "clang"
        config.build_settings["CXX"] = "clang++"
        config.build_settings["LDPLUSPLUS"] = "clang++"
      end
    end

    # If you move versions around though you get another nasty Folly bug about redefined symbols, fix that...
    `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
  end
```

I've collaborated extensively with the react-native core team to reduce the set of things needed by end users, and we're getting close in the react-native 0.66.0 release that's about to come but until then, get those hacks in there and give it a try

**Comment by mikehardy** [comment]
Reference:
https://github.com/facebook/react-native/issues/31941

**Comment by rubenmaas** [comment]
Wow, that was quick. I will try this and get back to you. Thanks 🙏🏼

**Comment by mikehardy** [comment]
At least for me personally it's because I've worked so hard on the M1 stuff and it's been admittedly awful to hack through. I don't wish it on anyone else.

@christocracy just always has instant tech support haha

**Comment by rubenmaas** [comment]
I've added the partial you provided to the Podfile, ran `pod install` and now I'm trying to build the app again but now it fails instantly:

```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65
The linked library '...' is missing one or more architectures required by this target: arm64
```

**Comment by christocracy** [comment]
>⚠️  ld: Could not find or use auto-linked framework 'GoogleAppMeasurement'

This one is not related to my stuff.  The plugin contains no reference to `GoogleAppMeasurement`.

**Comment by rubenmaas** [comment]
I know, but still there is `TSBackgroundFetch`

**Comment by rubenmaas** [comment]
none, but in the `react-native-background-geolocation` package is this:
```
...
"dependencies": {
  "react-native-background-fetch": "~4.0.1"
},
...
```

**Comment by mikehardy** [comment]
Not sure about why GoogleAppMeasurement isn't happy but that is getting close to the react-native-firebase area where I'm the primary maintainer. I am certain [that pod builds correctly](https://github.com/invertase/react-native-firebase/blob/c56bdb3171e998efa1b7860519a06a5fb3515ac2/tests/ios/Podfile.lock#L75) on all platforms but as mentioned above it's really subtle - for me - when I'm building google-y / firebase-y stuff.

I had to throw this in recently to get it working, note the interpolation in the build command: https://github.com/invertase/react-native-firebase/blob/c56bdb3171e998efa1b7860519a06a5fb3515ac2/tests/package.json#L60

**Comment by christocracy** [comment]
>none, but in the react-native-background-geolocation package.json is this:

This is your problem.  Transistive dependencies cannot be auto-linked by RN.  You **must** *manually* install `react-native-background-fetch` as a first-class citizen, [as documented in the iOS Setup](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md)

![](https://dl.dropbox.com/s/27an9i256i91i8v/Screen%20Shot%202021-10-01%20at%2010.37.41%20AM.png?dl=1)

**Comment by rubenmaas** [comment]
🙈 I've must have missed that, thanks for pointing that out for me..
