### ISSUE TITLE
Is there a way to know when RNBG opens your app in the background vs a user?

### ISSUE THREAD

**Issue by albertstill** [transistorsoft/react-native-background-geolocation#1398]
On iOS, I believe RNBG causes my app to open occasionally in the background in a headless (not Android headless feature) state while it's tracking, I assume this is by design? 

In my app this triggers the same tracking events that fire when the user opens the app, causing incorrect tracking. Normally I see this happen to users less than a handful of times over a day.

Is there a way to know if the app has been opened by RNBG, maybe through props or it's API so I could stop my code firing tracking events?

Thanks

## Your Environment
* Plugin version: 3.9.3
* Platform: iOS
* OS version: many
* Device manufacturer / model: many
* React Native version (`react-native -v`): 0.64.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      distanceFilter: 25,
      stopOnTerminate: false,
      startOnBoot: true,
      foregroundService: true,

      schedule: scheduleArray,

      // http options
      url:  TRACKING_ENDPOINT,
      params: {
        device: {
          uuid: deviceInfo.getModel().replace(/[\s.,]/g, '-'),
          model: deviceInfo.getModel(),
          platform: deviceInfo.getSystemName(),
          manufacturer: await deviceInfo.getManufacturer(),
          version: deviceInfo.getSystemVersion(),
          framework: 'ReactNative',
        },
      },
      autoSyncThreshold: 20,
      batchSync: true,
      maxBatchSize: 60,
    }
```

**Comment by christocracy** [comment]
See API docs [State.didLaunchInBackground](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/state.html#didlaunchinbackground)
