### ISSUE TITLE
Is there any way to hide push notifications at the time of sending captured locations to hosting server?

### ISSUE THREAD

**Issue by binzailani3136** [transistorsoft/react-native-background-geolocation#140]
Hi.
I would like to hide push notifications which are fired at the time of sending user locations to the server.
How can I do it?
Best wishes and regards.
Bin

**Comment by christocracy** [comment]
These are simply to assist you during development.

debug: false

**Comment by christocracy** [comment]
These are simply to assist you during development.

debug: false

**Comment by binzailani3136** [comment]
Ohhh, so many thanks. :)
