### ISSUE TITLE
understanding docs / stopping background services

### ISSUE THREAD

**Issue by earnestware** [transistorsoft/react-native-background-geolocation#1403]
## Your Environment
* Plugin version: ^4.4.0
* Platform: iOS
* OS version: Mac 11.6
* Device manufacturer / model: iOS simulator 13 / iPhone 12  / 15.1
* React Native version (`react-native -v`): 6.1.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```
## Context
The goal is to, given some condition, start the location service, have it run foreground/background for some time (would never run for more that 8 - 10 hours), then to stop the service completely. What I don't see is this stopping - shutting down the service. Other than in the example where you remove the listeners but I'm unsure about this because this would happen (I think) when the app was terminated - but you still want the BG service to track the location when moving ....  So the overall goal is understand how to start/stop the service and to allow run in foreground/background. It's possible even to start the service, allow to run in background, and on reboot, then to open the app and given a condition need to shut down the service. I think I understand how to start everything up - that's clear, it's the shutting down. 
Sort of new to RN so maybe that's issue. Any assistance would be great.

</details>

**Comment by earnestware** [comment]
oh - there's a method named .stop() 
:)

**Comment by christocracy** [comment]
Think of the plugin like an *electronic device*, such as a stereo receiver.
- Adding event-listeners (eg: `onLocation`, `onMotionChange`) is like wiring up speakers.
- `.start()` and `.stop()` is like the POWER switch.

**Comment by earnestware** [comment]
it always comes back to RTFM 👍
