### ISSUE TITLE
URL not set when config applied in .ready() 

### ISSUE THREAD

**Issue by earnestware** [transistorsoft/react-native-background-geolocation#1404]
## Your Environment
* Plugin version: ^4.4.0
* Platform: iOS 
* OS version: Mac 11.6
* Device manufacturer / model:  iOS simulator 13 / iPhone 12 / 15.1
* React Native version (`react-native -v`): 6.1.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

  
 BackgroundGeolocation.ready({
    url: 'https://app.mydomain.com/api/gps',
    params: {
      "employee_id": 1318,
      "client_id" : 4000
    },
    // Debug
    reset: false,
    debug: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    // Geolocation
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
    distanceFilter: 10,
    stopTimeout: 5,
    // Permissions
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: {
      title: "Allow {applicationName} to access this device's location even when closed or not in use.",
      message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
      positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
      negativeAction: 'Cancel'
    },
    // HTTP & Persistence
    autoSync: true,
    autoSyncThreshold: 5, 
    batchSync: false, 
    maxDaysToPersist: 14,
    // Application
    preventSuspend: true,
    heartbeatInterval: 60,
    // android 
    locationUpdateInterval:30000,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true
  }, (state) => {
      console.log("[state] enabled ", state.enabled);
      console.log(state);
  }
);
```

## Expected Behavior

I expect that  console.log(state); would show Config.url to be set as above. instead, it's ""

## Actual Behavior

Config.url = ""  
## Steps to Reproduce

1.
2.
3.
4.

## Context

Trying to understand the component by building simple app to start/stop the service and record locations. I have fully tested my URL using postman and confidence that's it working correctly.  
Even going to https://tracker.transistorsoft.com/earnestware it's not showing any data... 
For my code - see attached. 
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
[homescreen.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/7491207/homescreen.txt)

</details

>

**Comment by christocracy** [comment]
>reset: false,

Do you know what `reset: false` means?  99% of use-cases don't need that, including you.

**Comment by christocracy** [comment]
The only reason `reset: false` exists (the default is `true`) was for my own purpose in support of the demo app, so that the Settings screen could drive the config and not be reset those settings provided to `.ready(...)` with each boot.

I want the values set in the *Settings* screen to *stick*.

![](https://dl.dropboxusercontent.com/s/8lvnpp0gowitagq/settings-framed-350.png?dl=1)

**Comment by earnestware** [comment]
ok thanks! must have missed that somehow. thank you
