### ISSUE TITLE
Mismatched uuids between mobile and server

### ISSUE THREAD

**Issue by vessp** [transistorsoft/react-native-background-geolocation#141]
I've come across something that is causing me to have duplicate copies of each location.  This happens after I set my config and call start() on the plugin.  I begin receiving locations on my local device, and I have also configured my server url with auto sync so the locations are also posted to my server.  However when comparing the locations in my local device callback and in my server logs I noticed something strange.  The local object and server object have exactly the same latitude, longitude, timestamp, etc just as they should, but the uuid is different making me unable to identify them as the same point.  

I did some more testing by calling getCurrentPosition() and then insertLocation() and in this case the the client and server locations had correctly matching uuids.

I know the points are actually the same and should have the same uuid because the timestamps match. Am i missing something?

**Comment by christocracy** [comment]
What version are you using?

**Comment by vessp** [comment]
version 1.3.3

**Comment by christocracy** [comment]
Update to latest `1.4.3`.  Problem solved.

**Comment by christocracy** [comment]
Have a look at the CHANGELOG.  [watchPosition](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#watchpositionsuccessfn-failurefn-options) method is now available.
