### ISSUE TITLE
[CHANGEME] This app collects location data for FEATURE X and FEATURE Y .

### ISSUE THREAD

**Issue by Nikhath-1211** [transistorsoft/react-native-background-geolocation#1410]
I have been using the license version of cordova-background-geolocation-lt in my native cordova app, Because of these context text [CHANGEME] This app collects location data for FEATURE X and FEATURE Y . Google play console rejected due to policies violation  , aren't able to customize the text explaining why it should be tracked . so mainly need to change the text/message in Alert permissions.

## Your Environment
* Plugin version: cordova-background-geolocation-lt 3.10.0 "BackgroundGeolocation"
* Platform: iOS and Android 
* OS version: 11.3.1
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
![Screenshot_20211115_110855](https://user-images.githubusercontent.com/94528297/142182064-68d9b64c-229b-4d5d-8e26-6c16334e2302.png)

```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

The Alert  for location tracking permission should be given a custom message /proper message to user why it's being asked  for?

## Actual Behavior

The Alert  for location tracking permission displays message as [CHANGEME] This app collects location data for FEATURE X and FEATURE Y .

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
![Screenshot_20211115_110855](https://user-images.githubusercontent.com/94528297/142180524-b64133ce-0751-47fa-831c-8c1221dbc328.png)

</details>

**Comment by Nikhath-1211** [comment]
Using the cordova -v 10.0.0  *current version

**Comment by christocracy** [comment]
> Using the cordova -v 10.0.0 *current version

This is not the Cordova repo.  It's the react-native version.

There is also a Capacitor and Flutter version.

**Comment by Nikhath-1211** [comment]
Yes its the react-native version, Could you please help to change me the [CHANGEME] text

> > Using the cordova -v 10.0.0 *current version
> 
> This is not the Cordova repo. It's the react-native version.
> 
> There is also a Capacitor and Flutter version.

**Comment by Nikhath-1211** [comment]
Actually its native one , with both android and iOS patforms

**Comment by christocracy** [comment]
>Plugin version: cordova-background-geolocation-lt 3.10.0 "BackgroundGeolocation"

This is Cordova.  Post Cordova support requests at the Cordova repo.  This is the react-native version.

**Comment by mailyokesh** [comment]
I use "react-native-background-geolocation": "^4.4.4" version of the plugin and ssee the same message in android. Is there anything we need to provide for android config? Not able to find any relevant information in the documentation. @christocracy  if you could point me to relevant doc that would be helpful.
