### ISSUE TITLE
[Android] location settings opens before any action on the backgroundPermissionRational modal

### ISSUE THREAD

**Issue by AlexandreKueny** [transistorsoft/react-native-background-geolocation#1411]
I have locationAuthorizationRequest set to Always.
When the first authorization modal opens and I select "While using the app", I'm redirected to the app's settings without any prompt. When I go back to my app, then the backgroundPermissionRationale modal is shown.

The demo app works fine, but I can't figure out what is wrong with my code.

**Comment by christocracy** [comment]
You likely have some other plugin requesting permissions.

**Comment by AlexandreKueny** [comment]
I don't think I have.
Here is my package.json, maybe you can see any package that could cause the issue ?

"@react-native-community/async-storage": "1.12.1",
    "@react-native-community/datetimepicker": "3.4.7",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-firebase/app": "^11.3.1",
    "@react-native-firebase/messaging": "^11.3.1",
    "@react-navigation/drawer": "5.12.5",
    "@react-navigation/native": "5.9.4",
    "@react-navigation/stack": "5.14.4",
    "@testing-library/react-native": "7.1.0",
    "appcenter": "^4.1.0",
    "appcenter-analytics": "^4.1.0",
    "appcenter-crashes": "^4.1.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "metro-config": "0.65.1",
    "react-native": "0.64.0",
    "react-native-auth0": "^2.10.0",
    "react-native-background-fetch": "^4.0.1",
    "react-native-background-geolocation": "^4.1.1",
    "react-native-bing-maps": "^0.1.1",
    "react-native-bootsplash": "^3.2.6",
    "react-native-gesture-handler": "1.10.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-onetrust-cmp": "6.20.0",
    "react-native-permissions": "3.0.4",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "1.13.2",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "2.17.1",
    "react-native-signature-capture": "^0.4.12",
    "react-native-svg": "12.1.0",
    "react-native-webview": "^11.13.1",
    "react-navigation": "4.4.4",
    "react-redux": "^7.2.2"

**Comment by christocracy** [comment]
```
react-native-bing-maps": "^0.1.1",
"react-native-permissions": "3.0.4",
```

**Comment by AlexandreKueny** [comment]
Right, I missed these two.
I removed them both from the package.json and the native android code, but the issue is still present.

The backgroundPermissionRationale modal should display automatically after I click on "When using the app" of the first authorization modal right ? Or is there any method to call ?

**Comment by christocracy** [comment]
Someone else reported the same issue, can't remember if it was here, Cordova, Capacitor or Flutter -- but they found the problem was in their own app code.

I test this on several of my own devices with my demo app and I've never seen it.

Your problem is not related to the plugin.

I suggest you try my demo app and see.

**Comment by christocracy** [comment]
> The demo app works fine, but I can't figure out what is wrong with my code.

Oh, you tried that.

What's your targetSdkVersion?

**Comment by AlexandreKueny** [comment]
targetSdkVersion is 30

**Comment by christocracy** [comment]
>targetSdkVersion is 30

That's what you want.

**Comment by HassanRaza03** [comment]
facing the same issue.

**Comment by christocracy** [comment]
Create for me a simple HelloWorld app that reproduces the issue.

**Comment by AlexandreKueny** [comment]
@HassanRaza03 The main issue for me was that calls to `BackgroundGeolocation.ready` and `BackgroundGeolocation.start` were made multiple times. Since I've fixed this, the issue only happened a few times.

**Comment by hassan-kiffgo** [comment]
@AlexandreKueny thanks for the timely response, had the same issue but after removing multiple calls to BackgroundGeolocation.ready function everything is working fine now.
