### ISSUE TITLE
maxDaysToPersist: How to set it to "unlimited"?

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1413]
## Your Environment
* Plugin version: 4.4.4
* Platform: iOS and Android
* OS version: Any
* Device manufacturer / model: Any
* React Native version (`react-native -v`): 0.63.2

## Expected Behavior
I want to store the Location for an unlimited time in the Database.

## Actual Behavior
The documentation gives no hint how to do that. It only says "Maximum number of days to store a geolocation in plugin's SQLite database."

## Steps to Reproduce
https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/config.html#maxdaystopersist

**Comment by christocracy** [comment]
Why don't you just give a *really* big number?

**Comment by christocracy** [comment]
36500 would be 100 years.

**Comment by Stophface** [comment]
Hey @christocracy 
that came into my mind, but I wanted to be sure. It would be a bad surprise if it silently sets it a maximum without giving notice and then, after half a year or so, the entries in the database get deleted. 

Is there a way to query/run SQL on the database?

**Comment by christocracy** [comment]
You need to be very careful with that setting. In theory, you could consume all the memory of a device.

**Comment by Stophface** [comment]
@christocracy I am aware of that. Is there a way to query the database your library creates? Or is it "locked" away? 
I am working on an offline first application, which means I *have* to store the data on the device. If your database is not accessible, I'd move the location points to my own database. But, since your software comes already with a database, it totally makes sense to use that database. Besides, you solved already the "saving points in database while app is in the background", which would save me a lot of time.

**Comment by christocracy** [comment]
The plugin has limited querying ability exposed.  See `.getCount()`, `.destroyLocations()`.

**Comment by Stophface** [comment]
Bummer... Well, maybe I have to expose my own queries. I've never done that, going native. But in the end its only an SQL query I have, which I have to make available to React Native. Maybe I can take your code as a template and add my own methods to it...

Or is it possible to tweak the HTTP Service that it broadcasts the data to a local database?

**Comment by christocracy** [comment]
What are you trying to do?  The plug-in's SQLite db acts merely as a short-term queue for its own http service.

If you want access to your own local db of locations, make your own database and use the plug-in's onLocation event to do your `INSERT INTO`.  For Android terminated case, you'd do your inserts in your HeadlessTask as well.

**Comment by Stophface** [comment]
I checked and realized, that I cannot extend your code base. Bummer!

Yeah, using the `onLocation` event and insert the locations into my own DB is plan B. However, doing it that way I have to handle the whole "App is in the background, insert it into the database anyway/queue it until app is in the foreground nad insert it then" from the JS side myself. Your Plug In inserts location data into the database when the app is in the background/queues it properly so that it gets inserted once that app is in the foreground. Using that instead of writing it myself makes sense to me, because its already well done by you. 
The database I'd set up is a SQLite database too... The table would have a few more columns, but besides that, there should not be so much difference in storing location data.
