### ISSUE TITLE
[docs] Missing iOS Freeway Drive JSON data

### ISSUE THREAD

**Issue by matbrady** [transistorsoft/react-native-background-geolocation#1415]
## Your Environment
**N/A**

## Expected Behavior
Wiki link should direct to a JSON file containing geofence objects that exist along the iOS Freeway Drive route

## Actual Behavior
Link directs to a section of private geofence objects located in Montréal. [here](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/src/advanced/lib/SettingsService.ts#L649-L651)

<img width="200" alt="Screen Shot 2021-12-01 at 1 51 52 PM" src="https://user-images.githubusercontent.com/1770862/144296805-6083e40e-3d52-422d-818b-e2e76a48cd09.png">

## Summary

Within the [Debugging](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging/884a944678a181ca8beb464b2c4c371a92b7c328#testing-geofences-in-ios-simulator) section of the wiki, the "a handy JSON file" link points [here](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/src/advanced/lib/SettingsService.ts#L649-L651). It looks like it [previously linked to the cordova specific repo](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging/_compare/95435a6c7837ff0b133e682482ec62cbbae812d2#diff-7ab4dad0c749e83db84252b8efa31ce713135e4329e4f4772b93f21ca7b2c081L138) which had a `city_drive.json` JSON file. 

This certainly isn't required but would be super helpful to quickly validate working geofences within the iOS simulator.

**Comment by christocracy** [comment]
The data you want [*is in* that file](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/src/advanced/lib/SettingsService.ts#L891-L893), just that the line-numbers referenced by the link had changed.

https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/src/advanced/lib/SettingsService.ts#L891-L893
