### ISSUE TITLE
Does the package requires background location permission?

### ISSUE THREAD

**Issue by gauravroyzz** [transistorsoft/react-native-background-geolocation#1417]
## Your Environment
* Plugin version:4.4.2
* Platform: iOS or Android - Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.66.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

We don't ask for background permission explicitly in our app, still our app is getting rejected by Playstore for prominent disclosure.
Does this package internally adds the 
```<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />```

**Comment by christocracy** [comment]
> Does the package requires background location permission

This plugin is named “background-geolocation”.  It should not be surprising that it does.

**Comment by tchiteu** [comment]
In my case, the app only uses background location from one condition. Is it possible to request access to the background location only when needed?

**Comment by christocracy** [comment]
> Is it possible to request access to the background location only when needed?

Yes, see Config.locationAuthorizationRequest.  However, if you want at some point to request “Always” authorization, then your AndroidManifest **must** include the `BACKGROUND_LOCATION` permission (which the plugin automatically inserts) and you must justify that in the *Google Play Console.*

**Comment by tchiteu** [comment]
> 
I'm developing for ios, when opening the app the first thing it does is ask for permission to use the location in the background. With the plugin configuration I was not able to remove the request.

**Comment by tchiteu** [comment]
> > Is it possible to request access to the background location only when needed?
> 
> Yes, see Config.locationAuthorizationRequest. However, if you want at some point to request “Always” authorization, then your AndroidManifest **must** include the `BACKGROUND_LOCATION` permission (which the plugin automatically inserts) and you must justify that in the _Google Play Console._

I'm developing for ios, when opening the app the first thing it does is ask for permission to use the location in the background. With the plugin configuration I was not able to remove the request.

**Comment by christocracy** [comment]
The plugin doesn’t request permission until .start() is called.  

Don’t call .start() until you’re ready to start tracking.

**Comment by christocracy** [comment]
Also, read api docs Config.locationAuthorizationRequest, as noted above.

**Comment by tchiteu** [comment]
Thank you so much for the quick support.
