### ISSUE TITLE
Some android device not working

### ISSUE THREAD

**Issue by xesun** [transistorsoft/react-native-background-geolocation#1418]
## Your Environment
* Plugin version:4.4.4
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung S9
* React Native version (`react-native -v`): react-native-cli: 2.0.1
react-native: 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
          {
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            stopTimeout: 1,
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
            stopOnTerminate: true, // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: false, // <-- Auto start tracking when device is powered-up.
            batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
            url: Api.location3,
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          state => {
            console.log(
              '- BackgroundGeolocation is configured and ready: ',
              state.enabled,
            );

            if (!state.enabled) {
              BackgroundGeolocation.start(function() {
                console.log('- Start success');
              });
            }
          },
        );
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 't.coords.latitude'), stack:
<unknown>@1549:1118
u@1386:2945
value@48:1279
value@28:3350
<unknown>@28:747
value@28:2610
value@28:719
value@-1

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:764)
```

</details>

**Comment by christocracy** [comment]
> Plugin version:

**Comment by xesun** [comment]
> * Plugin version:4.4.4
> * Platform: Android
> * OS version: 9
> * Device manufacturer / model: Samsung S9
> * React Native version (`react-native -v`): react-native-cli: 2.0.1
>   react-native: 0.63.4

**Comment by christocracy** [comment]
Show me some of your JavaScript code where you’re interacting with plugin events.

**Comment by christocracy** [comment]
And see wiki *Debugging*

**Comment by xesun** [comment]
const locationUpdater = useCallback(() => {
    if (token && token.length > 0) {
      try {
        BackgroundGeolocation.onLocation(location => {
          if (location && location.coords) {
            if (
              !myref.current ||
              (location.coords.latitude !== myref.current.latitude &&
                location.coords.longitude !== myref.current.longitude &&
                location.coords.latitude !== 0 &&
                location.coords.longitude !== 0)
            ) {
              myref.current = {
                latitude: location.coords.latitude,
                longitude: location.coords.longitude,
              };
              setPosition({
                latitude: location.coords.latitude,
                longitude: location.coords.longitude,
                accuracy: location.coords.accuracy,
              });
            }
          }
        });
        BackgroundGeolocation.ready(
          {
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            stopTimeout: 1,
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
            stopOnTerminate: true, // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: false, // <-- Auto start tracking when device is powered-up.
            batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
            url: Api.location3,
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          state => {
            console.log(
              '- BackgroundGeolocation is configured and ready: ',
              state.enabled,
            );

            if (!state.enabled) {
              BackgroundGeolocation.start(function() {
                console.log('- Start success');
              });
            }
          },
        );
      } catch (e) {
        AlertHelper.show('info', 'Алдаа', `${JSON.stringify(e)}`);
      }
    }
  }, [token]);

  useEffect(() => {
    if (token && token.length > 0) {
      locationUpdater();
    }
  }, [locationUpdater, token]);

**Comment by christocracy** [comment]
Please learn to [Syntax Highlight Codeblocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
