### ISSUE TITLE
Geolocation tracking notification disappears and does not track location

### ISSUE THREAD

**Issue by manish-ims** [transistorsoft/react-native-background-geolocation#1421]
## Environment
* Plugin version: 4.4.4
* Platform: Android
* OS version: 10
* Device manufacturer / model: Pixel 5 (emulator), Redmi Y3, One plus 3, Samsung A31
* React Native version (`react-native -v`): 0.63.3

```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      backgroundPermissionRationale: {
         title:
           "Allow {applicationName} to access this device's location even when closed or not in use.",
         message:
           'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel',
       },
      autoSync: true,
      stopOnTerminate: false,
      startOnBoot: true,
      locationAuthorizationRequest:
        Platform.OS === 'ios' ? 'WhenInUse' : 'Always',
    })
      .then((state) => {
        if (!state.enabled) {
          BackgroundGeolocation.start().then((state) => {
            BackgroundGeolocation.onLocation(this.onLocation.bind(this));
          });
        }
      })
      .catch((error) => {
        console.log(error);
      });
```

## Expected Behavior
It should have fired BackgroundGeolocation.onLocation method on every location change. 

## Actual Behavior
It only works one time (the location is caught in the server) and the notification tile quickly disappears after it from the notification container disallowing this.onLocation.bind(this) to get fired on location change.

## Context
I am trying to create a salesperson tracking app for a client.

## Debug logs
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
How are you testing this?  In the emulator?  Have you tried going outside for a real field test (at least 1km).

The plugin does not detect device motion in the emulator.

**Comment by christocracy** [comment]
The foreground notification is supposed to disappear.  It will re-activate once the device is detected to be moving.

see wiki “Philosophy or Operation”.

**Comment by manish-ims** [comment]
I have been testing this in an emulator and real devices while being stationary. While going out on the field, it worked. Thanks.
