### ISSUE TITLE
Exit event is not triggering

### ISSUE THREAD

**Issue by waseem-wassu** [transistorsoft/react-native-background-geolocation#1422]
Plugin version: 4.0.0
Platform: Android
OS version: 10
Device manufacturer / model: Samsung,moto,Redmi
React Native version (react-native -v): 0.63.4

        BackgroundGeolocation.onGeofence(geofence => {
            console.log("geofence", geofence.identifier, geofence.action);
            if(geofence.action == 'ENTER'){
                dingenter.play(success => {
                    console.log(success,"success");
                    if (success) {
                      console.log('successfully finished playing in onGeofence');
                    } else {
                      console.log('playback failed due to audio decoding errors');
                    }
                  });
            }else if(geofence.action == 'EXIT'){
                dingexit.setVolume(1);
                dingexit.play(success => {
                    console.log(success,"success");
                    if (success) {
                      console.log('successfully finished playing in onGeofence');
                    } else {
                      console.log('playback failed due to audio decoding errors');
                    }
                  });
            }
        }

        Expected Behavior
        should get both ENTRY and EXIT events

        Actual Behavior
        Now we have implemented sound only for geofence entry and exit by using a custom player. But the strange thing is we are receiving the Entry info from the NPM side but exit info is not receiving

        Debug logs
        "action": "ENTER", "extras": {"route_id": "834"}, "identifier": "834", "location": {"activity": {"confidence": 100, "type": "still"}, "battery": {"is_charging": true, "level": 1}, "coords": {"accuracy": 23.6, "altitude": 688.7, "altitude_accuracy": 1.3, "heading": -1, "heading_accuracy": -1, "latitude": 74.525252, "longitude": 16.5906164, "speed": -1, "speed_accuracy": -1}, "event": "geofence", "extras": {"route_id": "834"}, "geofence": {"action": "ENTER", "extras": [Object], "identifier": "834"}, "is_moving": false, "odometer": 0, "timestamp": "2021-12-14T12:49:26.210Z", "uuid": "**************"}}

**Comment by christocracy** [comment]
The issue template is *not* optional, it is required.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by waseem-wassu** [comment]
.
