### ISSUE TITLE
Exit event is not triggering

### ISSUE THREAD

**Issue by vandana87** [transistorsoft/react-native-background-geolocation#1423]
## Your Environment
* Plugin version : **4.0.0**
* Platform:  **Android**
* OS version : **10**
* Device manufacturer / model : **Samsung ,moto ,Redmi**
* React Native version (`react-native -v`) : **0.63.4**

```
 BackgroundGeolocation.onGeofence(geofence => {
        console.log("geofence", geofence.identifier, geofence.action);
        if(geofence.action == 'ENTER'){
            dingenter.play(success => {
                console.log(success,"success");
                if (success) {
                  console.log('successfully finished playing in onGeofence');
                } else {
                  console.log('playback failed due to audio decoding errors');
                }
              });
        }else if(geofence.action == 'EXIT'){
            dingexit.setVolume(1);
            dingexit.play(success => {
                console.log(success,"success");
                if (success) {
                  console.log('successfully finished playing in onGeofence');
                } else {
                  console.log('playback failed due to audio decoding errors');
                }
              });
        }
    }
```

## Expected Behavior
 should listen to both ENTRY and EXIT events

## Actual Behavior
Now we have implemented sound only for geofence entry and exit by using a custom player. But the strange thing is we are receiving the Entry information from the NPM side but exit information is not receiving.

## Context
Trying to get entry and exit events.

## Debug logs
```
"action": "ENTER", "extras": {"route_id": "834"}, "identifier": "834", "location": {"activity": {"confidence": 100, "type": "still"}, "battery": {"is_charging": true, "level": 1}, "coords": {"accuracy": 23.6, "altitude": 688.7, "altitude_accuracy": 1.3, "heading": -1, "heading_accuracy": -1, "latitude": 74.525252, "longitude": 16.5906164, "speed": -1, "speed_accuracy": -1}, "event": "geofence", "extras": {"route_id": "834"}, "geofence": {"action": "ENTER", "extras": [Object], "identifier": "834"}, "is_moving": false, "odometer": 0, "timestamp": "2021-12-14T12:49:26.210Z", "uuid": "**************"}}
```

</details>

**Comment by christocracy** [comment]
Why not show the geofence data you’re providing to `.addGeofence`?

**Comment by vandana87** [comment]
// Remove the old geo fence while adding new geo fence date//
BackgroundGeolocation.removeGeofences().then(success => {

            var current = 1;
            var total = geofenceOptions.length;

            geofenceOptions.forEach(function (loc) {
                var options = {
                    identifier: loc.identifier,
                    radius: loc.radius,
                    latitude: loc.latitude,
                    longitude: loc.longitude,
                    notifyOnEntry: true,
                    notifyOnExit: true,
                    extras: {
                        route_id: loc.identifier
                    }
                };
// Removing old geo fence end//


//Adding nee geo fence//
                BackgroundGeolocation.addGeofence(options).then((success) => {
                   
                    locationAdded(current, total, geofenceOptions);
                    current++;
                }).catch((error) => {
                    console.log("[addGeofences] FAILURE: ", error);
                });
            })

        }).catch(function(err){
            console.log('Error while removing old geolocations ' + err);
        })
    }
}

// End of adding new geo fence//

**Comment by christocracy** [comment]
What is your `radius: loc.radius,`?

**Comment by vandana87** [comment]
For radius of 10KM we are sending like below:
{"address": "Paris, France", "identifier": "415", "latitude": 48.864716, "longitude": 2.349014, "notifyOnEntry": true, "notifyOnExit": true, "radius": 10000}

**Comment by christocracy** [comment]
Perhaps a large radius doesn’t work very well.

have you tried field-testing with a smaller radius, such as  200 meters?

**Comment by vandana87** [comment]
Our minimum radius limit is 1km and it varies up to 10km and we tried with 1km, 2 km....but cannot trigger EXIT event

**Comment by christocracy** [comment]
I suggest you first test with 200 and work your way up.

**Comment by vandana87** [comment]
as per your suggestion we tried with 200m  but still the exit event didn't triggered

**Comment by vandana87** [comment]
We have even  tried with your demo app  ,in that also exit event is not triggering ,

demo_app link: https://github.com/transistorsoft/rn-background-geolocation-demo

**Comment by christocracy** [comment]
The problem must be your environment.  Test geofences in different regions.

I’ve been testing geofences in my neighborhood for over 5 years and they never fail.

**Comment by vandana87** [comment]
We got the issue why it's not sending EXIT event. Below is the reason:
While adding geo fence it's taking the correct co ordinates and giving success response but while comparing live location the added coordinates are missing and it's comparing live location with live location and hence it's triggering ENTER event all the time. Not sure why npm is not comparing live location with added location. It's comparing live location with live location. Please advise.

**Comment by christocracy** [comment]
The plugin does not do any “comparing” of locations with geofences.  Geofence triggering is completely handled by the operating system.  The plugin has nothing to do with geofence triggering.
