### ISSUE TITLE
Is there an event for on geofence add / remove?

### ISSUE THREAD

**Issue by Kaz-z** [transistorsoft/react-native-background-geolocation#1429]
## Your Environment
* Plugin version: 4.4.4
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung S10
* React Native version (`react-native -v`): 0.66.3

## Context

It would be handy if there was an event to signify when a geofence has been added / removed. Main reason being is that I'd like to display a preview of the geofence without having to turn the plugin 'on'.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I don’t understand.

**Comment by Kaz-z** [comment]
If we use the demo app as an example. You only get to see the geofence when the plugin is switched on (using the toggle in the header). I'd like to show a preview of the geofence when the plugin is off. One way of doing that is to subscribe to an event that tells me when a geofence has been added using the UI thats triggered on the long press method. Once I know that I can render the geofences accordingly. Does that make more sense?

**Comment by christocracy** [comment]
Use getGeofences to retrieve a list of geofences.  There is no such event to do what you want.

**Comment by Kaz-z** [comment]
Fair enough. Thanks for the quick response.
