### ISSUE TITLE
Calling "BackgroundGeolocation.start" function causes app state to change and back quickly

### ISSUE THREAD

**Issue by Travisrockgit** [transistorsoft/react-native-background-geolocation#1430]
## Your Environment
* Plugin version: 4.1.1
* Platform: iOS and Android
* OS version: iOS (15), Android (11)
* Device manufacturer / model: Apple iPhone 12 and Google Pixel 4
* React Native version (`react-native -v`): 0.61.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
componentWillMount() {

    // 1.  Wire up event-listeners

    BackgroundGeolocation.onLocation((location) => {
      if (location.coords.speed == null) { return }
      let mph = location.coords.speed * MPS_TO_MPH
      // console.log(`The current spped is~~~~---------${mph}`)
      if (mph < 0) { mph = 0.0 }
      const { prevVelocity, avcOn } = this.state
      if (Math.abs(prevVelocity - mph) >= 1) {
        this.setState({ volByAvc: true })
        if (avcOn) {
          this.updateManualVolume(mph)
        }

      }
    }, (error) => {
      console.warn('[location] ERROR -', error);
    })

    // 2.  Execute #ready method (required)
    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      // disableMotionActivityUpdates: true,
      // Activity Recognition
      stopTimeout: 1440,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: true,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: false,        // <-- Auto start tracking when device is powered-up.

    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);


    });
  }

componentDidMount(){
BackgroundGeolocation.start(function () {
      console.log("- Start success");
    });
}
```

## Expected Behavior

AppState stays active since it has not gone to background or inactive

## Actual Behavior

AppState changed to "background" on Android and "inactive" on iOS and quickly back to "active"

## Steps to Reproduce

1. Call the "BackgroundGeolocation.start" function and monitor the app state changes

## Context

I am utilizing the app state to do certain things when app goes to a particular state. Started noticing weird behaviors on the screen where "BackgroundGeolocation.start" is called. Logged the app state and realizing that calling the function will cause the split second app state change. I am wondering why this behaviors occur

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Yes, this is supposed to happen.  Android has a mechanism that can analyze the device’s current settings (Eg Location Services disabled) and present a dialog asking the user if they’d like to enable location services.  This requires presentation or a new Activity, which is responsible for this phenomenon.

try it:  disable location services in device settings then call start.

see api docs Config.disableLocationAuthorizationAlert

**Comment by Travisrockgit** [comment]
Awesome it makes sense and I tried your suggested solution, it worked, thanks for the quick response.
