### ISSUE TITLE
promise from getCurrentPosition sometimes is not resolved

### ISSUE THREAD

**Issue by anija** [transistorsoft/react-native-background-geolocation#1434]
## Your Environment
* Plugin version: 4.4.4
* Platform: iOS (both emulator and real device)
* OS version: 15.1, 15.2
* Device manufacturer / model: Emulator, iPhone Xr
* React Native version: 0.66.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  reset: true,
  disableElasticity: true,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  locationAuthorizationRequest: 'Always',
  disableLocationAuthorizationAlert: false,
  stopDetectionDelay: 0,
  stopTimeout: 0,
  stopOnStationary: false,
  disableStopDetection: true,
  pausesLocationUpdatesAutomatically: false,
  heartbeatInterval: 60,
  activityType: 4,
  disableMotionActivityUpdates: false,
  stopOnTerminate: true,
  startOnBoot: false,
  preventSuspend: true,
  foregroundService: false,
  enableHeadless: false,
  debug: true,
  logLevel: Config.environment === 'dev'
    ? BackgroundGeolocation.LOG_LEVEL_VERBOSE
    : BackgroundGeolocation.LOG_LEVEL_INFO,
  logMaxDays: 1,

  persistMode: BackgroundGeolocation.PERSIST_MODE_NONE,
  autoSync: false
}
```
This configuration is then changed with:

```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  useSignificantChangesOnly: false,
  startOnBoot: true,
  stopOnTerminate: false,
  preventSuspend: true,
  foregroundService: true,
  geofenceInitialTriggerEntry: true,
  geofenceModeHighAccuracy: true,
  geofenceProximityRadius: 20,
  persistMode: BackgroundGeolocation.PERSIST_MODE_ALL,
  desiredOdometerAccuracy: 50,
  heartbeatInterval: 60,
  enableHeadless: true,
  stopTimeout: 0,
  desiredAccuracy: Platform.OS === 'ios' ? BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION : BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  disableElasticity: true,
  distanceFilter: 10,
  stationaryRadius: 25,
  fastestLocationUpdateInterval: 2500,
}
```

## Actual Behavior
Both on emulator and device, promise from getCurrentPosition sometimes is not resolved
```javascript
BackgroundGeolocation.getCurrentPosition({ maximumAge: 15e3, desiredAccuracy: 15, timeout: 15, persist: false })
  .then(async ({ coords }) => {
    console.log('> received current position');
  })
  .catch(() => {
    console.log('> error receiving current position');
  })
```
Neither then or catch are executed.
Sometimes it works, sometimes it just stuck there.

Nothing is logged.

## Expected Behavior
After timeout the promise should be or resolver or rejected.

**Comment by christocracy** [comment]
Provide logs from XCode where this is reproduced.

**Comment by christocracy** [comment]
>maximumAge: 15e3

This is not a valid value for `maximumAge`

**Comment by anija** [comment]
> > maximumAge: 15e3
> 
> This is not a valid value for `maximumAge`

changed to 15000, still getting the same behaviour.

**Comment by christocracy** [comment]
Xcode logs.

**Comment by christocracy** [comment]
Also, create for me a simple hello world app that reproduces the problem.  Push it to a public GitHub repo and share the repo here.

**Comment by anija** [comment]
> ```
> 📍<+45.43542000,+9.28519200> +/- 5.00m (speed -1.00 mps / course -1.00) @ 1/13/22, 6:36:42 PM Ora standard dell’Europa centrale
> 2022-01-13 18:36:43.109908+0100 Ski Win[39872:425863] 
> ╔═══════════════════════════════════════════════════════════
> ║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 5
> ╚═══════════════════════════════════════════════════════════
> ```
> 
> The plugin is waiting for 4 more samples to arrive before it resolves the `getCurrentPosition` call.
> 
> You can speed this up by providing [`samples: 1`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/currentpositionrequest.html#samples), for example.

Thank you, i will try. But consider that is not a matter of time: the location never arrives, even after hours.
