### ISSUE TITLE
Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.

### ISSUE THREAD

**Issue by brandtiwari007** [transistorsoft/react-native-background-geolocation#1437]
## Your Environment
* Plugin version:
* Platform: android
* OS version:android 12
* Device manufacturer / model:Samsung (S10)
* React Native version (`react-native -v`):0.61.4
  BackgroundGeolocation.ready(
      {
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 1,
        locationUpdateInterval:true,
        autoSync: true, 
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        // HTTP / SQLite config
        notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
        foregroundService: true,
        heartbeatInterval: 1,
        locationAuthorizationAlert: {
          titleWhenOff: I18n.t("LocationServicesOff"),
          titleWhenNotEnabled: I18n.t("BackgroundLocationNotEnabled"),
          instructions: I18n.t("LocationServicesInstructions"),
          cancelButton: I18n.t("Cancel"),
          settingsButton: I18n.t("Settings")
        },
        // url: "http://192.168.100.42:3000/api/locations",
        url: `${url}/updateLocation`,
        batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
        // headers: {
        //   // <-- Optional HTTP headers
        //   "X-FOO": "bar"
        // },
        params: {
          // <-- Optional HTTP params
          uid: this.props.userProfile._id,
          userToken: this.props.token
        },
        notification: {
          title: I18n.t("notificationAppName"),
          text: I18n.t("notificationText"),
          // layout: "notification_layout",
          smallIcon: "drawable/ic_stat_group",
          color: "#E0535B"
        }
```



## Steps to Reproduce

1.update the library to v4.4.2
2.
3.
4.

## Context
Trying to update library---
 Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - file:/home/raghvendra/.m2/repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/home/raghvendra/.m2/repository/com/transistorsoft/tslocationmanager/
       - file:/home/raghvendra/projects/locator/fs-locator/node_modules/react-native/android/com/transistorsoft/tslocationmanager/maven-metadata.xml

**Comment by christocracy** [comment]
Duplicate #541.  You need to follow the [Setup Guide](https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-setup-guides)
