### ISSUE TITLE
HTTP Post not called anymore

### ISSUE THREAD

**Issue by jeroenbourgois** [transistorsoft/react-native-background-geolocation#144]
Sadly I do not have much more information :( Using RN 0.34. On Android everything works fine, on iOS the http event handler is never called.

I tried resetting the simulator and completely removing and installing the latest version of the plugin.

Any idea where to look?

**Comment by christocracy** [comment]
I'll check it out ASAP

**Comment by christocracy** [comment]
However, which version of plugin?

**Comment by jeroenbourgois** [comment]
Maybe I should install the 1.5.0? I just installed with the `npm` command from the readme, that gave me `1.4.3`

**Comment by christocracy** [comment]
Show me the result of #getConfig

**Comment by christocracy** [comment]
1.5.0 refractors the iOS logging system.  See changelog

**Comment by jeroenbourgois** [comment]
Yes, but I thought first I would get the 1.5.0 after `npm install`. Sorry about that, I will comment out the log option. You want the result of the `configure` method call, thus the `state` object passed in the callback?

**Comment by jeroenbourgois** [comment]
Oh my! Sorry man, what a dumb mistake.
Good catch to trace the config, should have thought about is. The url was undefined... I was importing the variable from a config js file where I just declared it as const, *without* exporting it.

Shame on me! Sorry to waste your time!

**Comment by christocracy** [comment]
iOS logging is significantly improved now in `1.5.0`.  
- Logs are persisted to db for 3 days (default; configurable with `logMaxDays`).
- Configurable verbosity (@see docs for `logLevel`)
- `#emailLog` method works now.
