### ISSUE TITLE
Initialise background geolocation from the persisted extras which are set from .setConfig()

### ISSUE THREAD

**Issue by varundey** [transistorsoft/react-native-background-geolocation#1446]
## Your Environment
* Plugin version: 4.4.4
* Platform: Android
* OS version: Android 9+
* Device manufacturer / model: Any
* React Native version (`react-native -v`): 0.63.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    "didDeviceReboot": false,
    "isFirstBoot": false,
    "odometer": 0,
    "trackingMode": 1,
    "schedulerEnabled": false,
    "enabled": false,
    "useSignificantChangesOnly": false,
    "url": "redacted",
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "stopTimeout": 5,
    "stopAfterElapsedMinutes": 0,
    "stationaryRadius": 25,
    "startOnBoot": true,
    "speedJumpFilter": 300,
    "scheduleUseAlarmManager": false,
    "persistMode": 2,
    "notification": {
        "strings": {},
        "sticky": true,
        "priority": 0,
        "largeIcon": "",
        "smallIcon": "",
        "title": "Staging App",
        "channelName": "TSLocationManager",
        "actions": [],
        "color": "",
        "text": "Background service is running",
        "layout": ""
    },
    "maxRecordsToPersist": -1,
    "logLevel": 5,
    "locationsOrderDirection": "ASC",
    "schedule": [],
    "locationTemplate": "",
    "stopOnStationary": false,
    "locationAuthorizationRequest": "Always",
    "authorization": {},
    "deferTime": 0,
    "geofenceProximityRadius": 1000,
    "isMoving": false,
    "params": {},
    "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
    "motionTriggerDelay": 0,
    "httpRootProperty": "location",
    "enableHeadless": false,
    "heartbeatInterval": -1,
    "maxBatchSize": -1,
    "minimumActivityRecognitionConfidence": 75,
    "logMaxDays": 3,
    "geofenceModeHighAccuracy": false,
    "stopOnTerminate": false,
    "method": "POST",
    "disableElasticity": false,
    "locationUpdateInterval": 1000,
    "locationTimeout": 60,
    "foregroundService": true,
    "disableMotionActivityUpdates": false,
    "didLaunchInBackground": false,
    "autoSync": true,
    "fastestLocationUpdateInterval": -1,
    "disableStopDetection": false,
    "extras": {},
    "desiredOdometerAccuracy": 100,
    "elasticityMultiplier": 1,
    "configUrl": "",
    "distanceFilter": 10,
    "enableTimestampMeta": false,
    "maxDaysToPersist": 1,
    "allowIdenticalLocations": false,
    "disableAutoSyncOnCellular": false,
    "disableLocationAuthorizationAlert": false,
    "batchSync": false,
    "geofenceTemplate": "",
    "persist": true,
    "backgroundPermissionRationale": {
        "negativeAction": "Cancel",
        "positiveAction": "Change to Always",
        "message": "redacted",
        "title": "Allow App to use background location even when you are not using the app"
    },
    "desiredAccuracy": -1,
    "activityRecognitionInterval": 10000,
    "httpTimeout": 60000,
    "autoSyncThreshold": 0,
    "headers": {
        "Authorization": "redacted"
    },
    "debug": false,
    "geofenceInitialTriggerEntry": true
}
```

## Expected Behavior

Extras params for the configs should be persisted on app launch which are set after .ready is called from .setConfig()

## Actual Behavior

extras gets reinitialised to `{}` on calling .ready upon app restart

## Steps to Reproduce

1. Open the app the first time, .ready() should be called with supplied configs
2. Trigger an event which calls .setConfig() with extras config and call .start(). Location pings should have extras in them
3. Close/kill the app. Location pings should still have extras in them
4. Restart the app
5. Location pings have extras as `{}` since on restart the .ready() gets called again which resets extras

## Context

Hi, thank you for your work on the sdk. I am a licensed user and have a question if we can persist the extras while initialising Backgroundgeolocation on app restart. I have a use case where I need to set extras on a certain event (A) which should be persisted until user has triggered another event (B). Both A and B could happen much later after app is started (or Backgroundgeolocation.ready is called)

Since while doing Backgroundgeolocation.ready() I have to pass in all the configs along with extras, the first time it is set to default as `{}`. On app restart this extras param gets lost and hence I have to run a Backgroundgeolocation.getState before calling ready so that I can pass in the extras from the persisted state to the ready configs.

To do this, I have to maintain an internal state within my app and also ensure that the race condition between .ready() and .getState() is handled. I'm not sure if I'm doing something wrong here or if there's a better way to do this but is there a way I can initialise the .ready from the persisted state. One other way I can think of is to do `.ready(.getState())` but the promise nature of the two APIs make this a bit weird.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
That is correct.  When `.ready()` is called, all config options are reset to default and the new `Config` object supplied to` .ready()` is applied.

You should manage your `extras` separately using `AsyncStorage` and provide them to `.ready()`.

**Comment by varundey** [comment]
Hi @christocracy , do you recommend managing and syncing state externally in something like AsyncStorage? Asking this because the SDK also has a persistent storage and this can be levaraged by doing a .getState() before calling .ready(). Is there any downside of using the sdk's storage for this purpose?

**Comment by christocracy** [comment]
If you provide .reset: false to .ready, the Config will not be reset and the Config provided to .ready() will be consumed **only** at the first install. 

If you changed the Config during development with reset: false, your changes will be ignored.  Be sure to understand this.

When you update Config using .setConfig(), it will be persisted.
