### ISSUE TITLE
Clarification on useSignificantChangesOnly

### ISSUE THREAD

**Issue by stharvey** [transistorsoft/react-native-background-geolocation#1451]
I'm sorry if this isn't the correct place to ask this question - please redirect me if not.

I am looking for some clarification on the use of "useSignificantChangesOnly".

I see from Apple's documentation that the "Significant-Change Location Service" makes use of cell tower and WiFi signals for determining location (https://developer.apple.com/documentation/corelocation/getting_the_user_s_location/using_the_significant-change_location_service).

Does this mean that if the plugin is configured with "useSignificantChangesOnly" but the device is in flight mode, or otherwise out of range of any cell or WiFi signals, that no location data will be received?  Or will this revert back to GPS as necessary?

I'm sorry if this has been asked before or explained in the docs, I did have a look but couldn't see it.

**Comment by stharvey** [comment]
Ah thanks Chris, that explains it.  Yes confirmed that it works on simulator iOS 14.  I'll disable this option on my app for iOS 15.0-15.3

Thanks again.

**Comment by christocracy** [comment]
I'm sure *significant location changes* probably works in the iOS simulator.  iOS bugs typically appear only on *real* devices.
