### ISSUE TITLE
Stop Foreground Services Notification Being shown when the location services are turned off

### ISSUE THREAD

**Issue by ghost** [transistorsoft/react-native-background-geolocation#1456]
## Your Environment
* Plugin version:  4.1.1
* Platform:  Android
* React Native version (`react-native -v`): 0.61.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready(
      {
        locationAuthorizationRequest: "Always",
        disableLocationAuthorizationAlert: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        stopTimeout: 10,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
        stopOnTerminate: false,
        startOnBoot: true,
        autoSync: false,
        enableHeadless: true,
        motionTriggerDelay: 30000,
        preventSuspend: true, //iOSがアプリをsuspendしないように
        notification: {
          smallIcon: "drawable/ic_stat_ic_notification"
        }
      },
      async (state) => {
        if (!state.enabled) {
          const locationPermission = await Permission.checkPermissionLocation()
          if (locationPermission) {
            BackgroundGeolocation.start()
          }
        }
      }
    )```

## Expected Behavior
<!--- Tell us what should happen -->
The [location services activated] notification(Foreground service) that shows up everytime in Android must not show up when the locations are turned off.

## Actual Behavior
<!--- Tell us what happens instead -->
The [location services activated] notification(Foreground service) shows up even if the locations are turned off.

## Context
<!--- What were you trying to do? -->
just trying to make. it more sensible to users.

</details>

**Comment by r-shakya-ebs** [comment]
@christocracy Thank you for your attention.

Here is the screenshot. As you can see, the location is turned off but still the notification from the app of Location Services Activated still shows up. 

We are targeting not to show that notification when the location is turned off.

Your advice is highly appreciated !! Thank You.

![rn_image_picker_lib_temp_468914cf-e31f-45a7-ad30-d356c7e924cc](https://user-images.githubusercontent.com/90761254/159401657-b2c9eed7-3419-41d5-ba4b-1a90e52cd7bc.png)

**Comment by christocracy** [comment]
If you want to turn off the plugin when the user disables location-services, you’re free to do that by listening to the onProviderChange event and telling the plugin to `.stop()` as you see fit.

**Comment by r-shakya-ebs** [comment]
Thank you very much for your advice. It did stop it but , it has to start when the location services are turned on . Seems like once stopped, the app has to be opened again for the the BGLocation to start right?

**Comment by r-shakya-ebs** [comment]
@christocracy Is there a way to start the library from the native codes like MainActivity.java? 

I was thinking to listen the providerChange event in the mainactivity.java and if its true, i would start the plugin maybe?

**Comment by christocracy** [comment]
>Is there a way to start the library from the native codes like MainActivity.java

It makes no difference whether you call `.start()` from the plugin's Javascript API vs using the Java aPI [`BackgroundGeolocation.getAdapter(context).start()`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/RNBackgroundGeolocationModule.java#L438-L443) from your `MainActivity.java`.

In Android 12, foreground-services are no longer allowed to be started while your app is in the background.  Calling `BackgroundGeolocation.start()` launches a foreground-service.
