### ISSUE TITLE
[CHANGEME] this app collects location data for FEATURE X and FEATURE Y

### ISSUE THREAD

**Issue by brandtiwari007** [transistorsoft/react-native-background-geolocation#1457]
How can I change this message, and from where this message is triggering automatically in android

**Comment by christocracy** [comment]
See Config.backgroundPermissionRationale

**Comment by grubstarstar** [comment]
I've tried this and the message remains. DO I need to do anything else?

**Comment by christocracy** [comment]
Likely because you sent `reset: false` to .ready, causing your Config changes to be ignored.

**Comment by grubstarstar** [comment]
Doesn't seem to be that, this is my config.

```
if (process.env.NODE_ENV === 'development') {
					// fetch the token so we get the field testing debugger console
					transistorAuthorizationToken = await BackgroundGeolocation.findOrCreateTransistorAuthorizationToken(
						'out-there-dating',
						'richard.garner',
					)
				}
				await BackgroundGeolocation.ready({
					locationAuthorizationRequest: 'WhenInUse',
					backgroundPermissionRationale: {
						title: "Allow {applicationName} to access to this device's location when closed or not in use?",
						message:
							"If you would like to receive a notification when you are at an {applicationName} compatible venue then you'll need to enable {backgroundPermissionOptionLabel} location permission",
						positiveAction: 'Change to {backgroundPermissionOptionLabel}',
						negativeAction: 'Cancel',
					},
					disableLocationAuthorizationAlert: true,
					geofenceModeHighAccuracy: true,
					// desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
					// TODO: was using DESIRED_ACCURACY_HIGH but Joe and Alex were getting checked out. Trying this but it probably uses more battery.
					desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
					distanceFilter: 5,
					stopTimeout: 5,
					foregroundService: true,
					debug: config.DEBUG_LOCATION_SOUNDS === 'true',
					logLevel: __DEV__ ? BackgroundGeolocation.LOG_LEVEL_VERBOSE : BackgroundGeolocation.LOG_LEVEL_OFF,
					stopOnTerminate: false,
					startOnBoot: true,
					geofenceInitialTriggerEntry: false,
					// Turn these on for testing GPX location files in Xcode as it will not detect motion.
					// disableStopDetection: true,
					// pausesLocationUpdatesAutomatically: false,
					isMoving: true,
					transistorAuthorizationToken,
				})
```

**Comment by grubstarstar** [comment]
I'm also trying to find the text "CHANGEME" or "FEATURE" in either the `react-native-background-geolocation-android`, or `react-native-background-fetch` but can't find it. Is this a dialog triggered by Android itself or the RNBGL module?

**Comment by grubstarstar** [comment]
Should I create a new issue for this?

**Comment by christocracy** [comment]
Then you are calling getCurrentPosition() before .ready() resolves.

**Comment by grubstarstar** [comment]
ah okay, that could very well be it. I will take a look. Thanks.

**Comment by grubstarstar** [comment]
It looks like it's a call to `.start()` that is happening just before `.ready()`. The reason I'm delaying ready until then is because I am requesting permissions from the user myself using another module so I have full control over the user experience. If I call `ready()` earlier so that it is complete when I try to `.start()` the plugin, it will try to get permissions from the user too early.

Is there a way of stopping RNBGL from requesting permissions itself so I can have full control? I thought `disableLocationAuthorizationAlert: true` was supposed to do this but it doesn't seem to be.

**Comment by christocracy** [comment]
You aren’t supposed to call .start() until .ready() resolves.

the plugin is not *ready* until .ready() resolves.  It is called *ready* on purpose.

**Comment by papa-jake** [comment]
Could this result from calling getProviderState before .ready() resolves? Is it safe to say that no methods from the plugin should be used until after .ready() resolves?

**Comment by christocracy** [comment]
> Could this result from calling getProviderState before

No.

> Is it safe to say that 

No.  Only methods which **request location**.  .start(), .getCurrentPosition().  Those methods will request location permission. 

Your Config provided to .ready() is not consumed until .ready() resolves.

If you cause the plugin to request permission *before* your Config is applied, then the plugin will use its current default values.

**Comment by batiabner** [comment]
Re-open got this message, this is my code 

 // --- START BACKGROUND LOCATION ---
  React.useEffect(() => {
    const setupBackgroundGeolocation = async () => {
      try {
        // Retrieve countryCode and token asynchronously
        const {code: countryCode, shortName: country} =
          await retrieveGlobalCountry();
        const token = await retrieveUserSession();

        /// 0. Request permissions
        await BackgroundGeolocation.requestPermission();

        /// 1. Subscribe to events
        const onLocation = BackgroundGeolocation.onLocation(location => {
          console.log('[onLocation]', location);
          // Call the hook to save the location
        });

        const onMotionChange = BackgroundGeolocation.onMotionChange(event => {
          console.log('[onMotionChange]', event);
        });

        const onActivityChange = BackgroundGeolocation.onActivityChange(
          event => {
            console.log('[onActivityChange]', event);
          },
        );

        const onProviderChange = BackgroundGeolocation.onProviderChange(
          event => {
            console.log('[onProviderChange]', event);
          },
        );

        // Listen to HTTP requests
        BackgroundGeolocation.onHttp(response => {
          console.log(response);
        });

        /// 2. Configure BackgroundGeolocation
        await BackgroundGeolocation.ready({
          // Geolocation Config
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 50,
          // Activity Recognition
          stopTimeout: 5,
          // Application config
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: false, // Continue tracking even if the app is terminated.
          startOnBoot: true, // Restart tracking when the device restarts.
          enableHeadless: true, // Support for background service when app is not active.
          // HTTP / SQLite config
          url: `${API_URL}/user_locations`,
          autoSync: true, // <-- [Default: true] Sync each location to the server as it arrives.
          headers: {
            Language: i18next.language,
            Authorization: `Bearer ${token['token']}`,
            Country: countryCode,
          },
        }).then(state => {
          console.log('BackgroundGeolocation is configured and ready.');
          if (!state.enabled) {
            BackgroundGeolocation.stop();
            BackgroundGeolocation.start(() => {
              console.log('BackgroundGeolocation started successfully.');
            });
          }
        });

        // Clean up event listeners on component unmount
        return () => {
          onLocation.remove();
          onMotionChange.remove();
          onActivityChange.remove();
          onProviderChange.remove();
        };
      } catch (error) {
        console.error('Error setting up BackgroundGeolocation:', error);
      }
    };

    // Call the async function
    setupBackgroundGeolocation();
  }, []);

  // --- END BACKGROUND LOCATION ---

**Comment by christocracy** [comment]
You’re very clearly calling .requestPermission before you’ve even provided the Config to .ready(config).

How do you expect the dialog to show the correct values if you’re initiating the permission request before the plug-in even been provided the Config??

**Comment by christocracy** [comment]
Also see api docs Config.backgroundPermissionRationale

**Comment by batiabner** [comment]
Thanks for your response, I'll try with this new code


`// --- START BACKGROUND LOCATION ---
  React.useEffect(() => {
    const setupBackgroundGeolocation = async () => {
      try {
        // Retrieve countryCode and token asynchronously
        const {code: countryCode, shortName: country} =
          await retrieveGlobalCountry();
        const token = await retrieveUserSession();
        
        /// 1. Subscribe to events
        const onLocation = BackgroundGeolocation.onLocation(location => {
          console.log('[onLocation]', location);
          // Call the hook to save the location
        });

        const onMotionChange = BackgroundGeolocation.onMotionChange(event => {
          console.log('[onMotionChange]', event);
        });

        const onActivityChange = BackgroundGeolocation.onActivityChange(
          event => {
            console.log('[onActivityChange]', event);
          },
        );

        const onProviderChange = BackgroundGeolocation.onProviderChange(
          event => {
            console.log('[onProviderChange]', event);
          },
        );

        // Listen to HTTP requests
        BackgroundGeolocation.onHttp(response => {
          console.log(response);
        });

        /// 2. Configure BackgroundGeolocation
        await BackgroundGeolocation.ready({
          // Other configuration options
          backgroundPermissionRationale: {
            title: 'Allow {AppName} to access your location',
            message:
              'This app collects location data to enable {FEATURE X} and {FEATURE Y}, even when the app is closed or not in use.',
            positiveAction: 'Allow',
            negativeAction: 'Deny',
          },
          // Geolocation Config
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 50,
          // Activity Recognition
          stopTimeout: 5,
          // Application config
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: false, // Continue tracking even if the app is terminated.
          startOnBoot: true, // Restart tracking when the device restarts.
          enableHeadless: true, // Support for background service when app is not active.
          // HTTP / SQLite config
          url: `${API_URL}/user_locations`,
          autoSync: true, // <-- [Default: true] Sync each location to the server as it arrives.
          headers: {
            Language: i18next.language,
            Authorization: `Bearer ${token['token']}`,
            Country: countryCode,
          },
        }).then(state => {
          console.log('BackgroundGeolocation is configured and ready.');
          if (!state.enabled) {
            BackgroundGeolocation.stop();
            BackgroundGeolocation.start(() => {
              console.log('BackgroundGeolocation started successfully.');
            });
          }
        });

        // Clean up event listeners on component unmount
        return () => {
          onLocation.remove();
          onMotionChange.remove();
          onActivityChange.remove();
          onProviderChange.remove();
        };
      } catch (error) {
        console.error('Error setting up BackgroundGeolocation:', error);
      }
    };

    // Call the async function
    setupBackgroundGeolocation();
  }, []);

  // --- END BACKGROUND LOCATION ---`

**Comment by christocracy** [comment]
Learn to syntax highlight your code.  It’s easy,

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by batiabner** [comment]
Thanks for the suggestions, It seems to be working
