### ISSUE TITLE
BackgroundGeolocation.stop() stops "pending" locations to be sent to config.url

### ISSUE THREAD

**Issue by alejandrofloresm** [transistorsoft/react-native-background-geolocation#1465]
## Your Environment
* Plugin version: 4.1.1
* Platform: Android
* OS version: Android
* Device manufacturer / model: Samsung 
* React Native version (`react-native -v`):
react-native-cli: 2.0.1
react-native: 0.67.2
* Plugin config
```javascript 
{
    autoSync: true,
    debug: false,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    disableElasticity: false,
    distanceFilter: 30,
    enableHeadless: true,
    fastestLocationUpdateInterval: 10000,
    foregroundService: true,
    geofenceProximityRadius: 1000,
    heartbeatInterval: 60,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    logMaxDays: 0,
    method: 'POST',
    preventSuspend: true,
    stopDetectionDelay: 1000,
    stopOnTerminate: false,
    stopTimeout: 5,
    triggerActivities: 'in_vehicle, on_bicycle, running, walking, on_foot',
    url: "https://my-services.the-system.test",
    persist: true,
    persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
}
```

## Expected Behavior
After calling BackgroundGeolocation.stop() and if the Internet access is restored the "pending" sent locations will be sent to the config.url

## Actual Behavior
After calling BackgroundGeolocation.stop() if the Internet access is restored the "pending" locations are NOT sent to the config.url

## Context
Sent locations that couldn't be sent to the config.url even after the tracking service has been stopped

**Comment by christocracy** [comment]
> Sent locations that couldn't be sent to the config.url even after the tracking service has been stopped

.stop() really means *stop* everything, including listeners on network connectivity.  It doesn't mean "*stop unless...*".

This is not going to change.

You are free to call .sync() at your own leisure.
