### ISSUE TITLE
foreground service notification and location service icons are flickering in status bar In the kill mode 

### ISSUE THREAD

**Issue by PrasadFeker** [transistorsoft/react-native-background-geolocation#1467]
## Your Environment
* Plugin version: 4.4.6
* Platform: Android
* OS version: Redmi Y2 
* Device manufacturer / model: M1 model
* React Native version (`react-native -v`): 0.63.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
GetBackGroundLocation = () => {
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      fastestLocationUpdateInterval: 5000,
      foregroundService: true,
    }).then((state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start();
      }
    });
  };
```

## Expected Behavior
foreground service notification and location service icons are not flickered in status bar

## Actual Behavior
foreground service notification and location service icons are flickered in status bar when application is in kill mode
 
 ##Headless task code
 
let HeadlessTask = async (event) => {
  let params = event.params;
  
  switch (event.name) {
    case 'heartbeat':
      console.log('heartbeat');
      // Use await for async tasks
      break;

    case 'motionchange':
      console.log('motionchange');
      // Use await for async tasks
      break;

    case 'location':
      console.log('location');
      // Use await for async tasks
      await getCurrentPosition();

      break;
  }
};

**Comment by christocracy** [comment]
You are causing an infinite loop requesting getCurrentPosition when a headless `location` event arrives, since getCurrentPosition **will generate** a location event.

```

case 'location':
  console.log('location');
  // Use await for async tasks
  await getCurrentPosition();
```

**Comment by christocracy** [comment]
As noted in your issue #1467, you're causing an infinite loop.

**Comment by PrasadFeker** [comment]
Thank you, Its working fine now
