### ISSUE TITLE
Location usage icon is always ON even for static GPS location

### ISSUE THREAD

**Issue by aksonov** [transistorsoft/react-native-background-geolocation#147]
Does it mean that this library always checks location? I need to save battery and check only when moving.

**Comment by christocracy** [comment]
No.  The plugin monitors a geofence while in stationary-mode.  The presence of the *location-services* icon does **not** imply GPS specifically.

Native *location-services* != GPS.

Location-services  is the aggregation of multiple location-providers, of which GPS is just 1.

1. GPS
2. Network triangulation
3. Cell-tower triangulation.

Geofencing, uses 2 & 3 when your app is suspended.

**Comment by aksonov** [comment]
Thanks, i didn't know that. Too pity that Apple shows that indicator for 2 & 3. Most users thought that once they see such icons, their battery is draining, like post below:
https://discussions.apple.com/thread/6537650?tstart=0

**Comment by aksonov** [comment]
@christocracy 1. Is there any way to disable it and provide checking once per minute, for example? 
2. How to stop usage of location server after 30 minutes, for example?

**Comment by christocracy** [comment]
Execute `#stop` method.  Keep track of a timestamp in your own app and make a decision to call `#stop` or `#start`.

BackgroundGeolocation plugin includes a dependency called [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch) (created by me) which will boot your app in the background about every 15min, providing exactly 30s of bg time.  Use this event to make your decisions.

**Comment by christocracy** [comment]
You do not need to `npm install` `background-fetch`.  It's already available to you.  Just:
```
import BackgroundFetch from "react-native-background-fetch";
```
