### ISSUE TITLE
Android 12 Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE crash

### ISSUE THREAD

**Issue by ozberkctn** [transistorsoft/react-native-background-geolocation#1471]
We are facing an issue which is `Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`
The error comes from -> com.intentfilter.androidpermissions.PermissionManager.notificationDismissIntent (PermissionManager.java:103)
com.transistorsoft.locationmanager.util.c$i.run (Unknown Source:15)

Does that library still not support Android 12?

Environment
* Plugin version: 4.4.4
* Platform: Android
* OS version: Android 12
* Device manufacturer / model: Samsung, Oppo, Xiaomi, Vivo
* React Native version (`react-native -v`): 0.64.0

</details>

**Comment by christocracy** [comment]
If you've purchased a license, the private repo has an updated version of android-permissions

**Comment by ozberkctn** [comment]
Thanks for the reply @christocracy. You mean the 4.4.6 version right?

**Comment by christocracy** [comment]
No, I mean `4.5.0`, in the private repo, available to customers who've purchased a license.

Have you purchased a license?

<img width="1237" alt="Screen Shot 2022-04-19 at 9 40 37 AM" src="https://user-images.githubusercontent.com/14999/164017161-7a607261-17bd-451a-ba6f-e492644a3a2a.png">

**Comment by Nr9** [comment]
We are in the same situation! We purchased the license. However, I did not know that there was a private repo. I searched the README for the information regarding this private repo and unfortunately I did not find anything.

**Comment by christocracy** [comment]
Simply append "-android" to this gut repo url to hit the private repo (if you have access).

**Comment by saransh-malik** [comment]
@christocracy We did purchase a license a while back and are able to use the package in release version but I can't seem to access the private repo, is there a fixed time after which we need a renewal or something?

**Comment by christocracy** [comment]
@saransh-malik Please email me regarding licensing questions.

**Comment by TranNghiaHiep** [comment]
> Yes, we have purchased the license. We got the key to being able to use the SDK, However, I realized that we are using the version which is not required a license. I am shocked. Thanks for enlightening us. We will start using private repo.

I'm facing the same issue. So, We use the email when we purchase this? Thanks

**Comment by julien9999** [comment]
@christocracy how do we access the private repo? the email used to purchase the license needs to match with GitHub profile email?

**Comment by christocracy** [comment]
The product admin can grant access to members in the Customer Dashboard, where keys are managed.

**Comment by jindalashish** [comment]
I've purchased 2 license keys. My github user is also added as a member in transistor software dashboard. But still I'm not able to access private repo.
