### ISSUE TITLE
After installing this geolocation it plugin got a wkwebview issue in ios

### ISSUE THREAD

**Issue by sivagreenocean** [transistorsoft/react-native-background-geolocation#1477]
## Your Environment
* Plugin version:4.1.1
* Platform: iOS 
* OS version: cordova ios 5.1.1
* Device manufacturer / model: simulatot 13 pro

## Expected Behavior

this plugin should allow wkwebview
## Actual Behavior

it is not supporting wkweb view
## Steps to Reproduce

1.we have tried cordova ios.6.2.0 / 4.6.0 also facing same issue
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
#11	0x0000000108b4c70e in -[CDVBackgroundGeolocation ready:] at /Volumes/Workspace/Hybrid/Project/fp_base_cloud/platforms/ios/FP Product/Plugins/cordova-background-geolocation-lt/CDVBackgroundGeolocation.m:66
#12	0x0000000108d94b67 in -[CDVCommandQueue execute:] at /Volumes/Workspace/Hybrid/Project/fp_base_cloud/platforms/ios/CordovaLib/Classes/Public/CDVCommandQueue.m:181
#13	0x0000000108b6062b in -[CDVWKWebViewEngine userContentController:didReceiveScriptMessage:] at /Volumes/Workspace/Hybrid/Project/fp_base_cloud/platforms/ios/FP Product/Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m:343
#14	0x0000000108b6193a in -[CDVWKWeakScriptMessageHandler userContentController:didReceiveScriptMessage:] at /Volumes/Workspace/Hybrid/Project/fp_base_cloud/platforms/ios/FP Product/Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m:491

```

</details>

**Comment by christocracy** [comment]
The plugin has nothing to do with webview.

create for a simple hello world project that reproduces this and share it with me in a public GitHub repo.

**Comment by christocracy** [comment]
>OS version: cordova ios 5.1.1

Why are you posting a *Cordova* issue to the *React Native* plugin's repo?
