### ISSUE TITLE
When mobile is locked in background/kill-mode, not getting location updates in Samsung M30S 

### ISSUE THREAD

**Issue by PrasadFeker** [transistorsoft/react-native-background-geolocation#1479]
## Your Environment
* Plugin version:4.4.6
* Platform:  Android
* OS version: 11
* Device manufacturer / model: Samsung M30s
* React Native version (`react-native -v`):0.63.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      // debug: true,
      fastestLocationUpdateInterval: 5000,
      foregroundService: true,
    }).then((state) => {
      if (!state.enabled) {
        if (Platform.OS === 'android') {
          //   ToastAndroid.show('calledd', ToastAndroid.SHORT);
        } else {
          console.log('IOS', 'shshjs');
          //  Alert.alert('ashbdhas', 'sd');
        }

        BackgroundGeolocation.start();
      }
    });
    
```

## Expected Behavior

Should get location updates for every 5 seconds in foreground, background and kill-mode.

## Actual Behavior

When mobile screen is locked and application is in background/kill-mode, we are unable to get location updates.

**Comment by christocracy** [comment]
The first step for these type of issues is to visit http://dontkillmyapp.com

**Comment by christocracy** [comment]
Also see wiki *Debugging* and learn to observe the plug-in’s logs.

**Comment by GurjeetLamba** [comment]
> The first step for these type of issues is to visit http://dontkillmyapp.com

I have followed these steps but , still getting this issue , Not getting location when device screen is lock
