### ISSUE TITLE
Getting AAPT: error: resource android:attr/lStar not found. error after installing react-native-background-geolocation

### ISSUE THREAD

**Issue by gaurav07june** [transistorsoft/react-native-background-geolocation#1481]
Getting AAPT: error: resource android:attr/lStar not found. error after installing react-native-background-geolocation

* Plugin version: "^4.7.1"
* Platform: Android
* OS version:  11
* Device manufacturer / model: vivo Y21
* React Native version : 0.64.0
* Plugin config

    BackgroundGeolocation.ready({
      reset: true,
      elasticityMultiplier: 1,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1,
      stopTimeout: 1,
      debug: false,
      logMaxDays: 1,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      autoSync: true,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      maxBatchSize: 30,
      maxDaysToPersist: 14,
      heartbeatInterval: 60,
      url: PRO_SYNC_URL,
      autoSyncThreshold: 10,
      batchSync: true,
      method: "POST",
      foregroundService: true,
      preventSuspend: true,
    }
## Expected Behavior
After installing the library, there should not be any installation errro.

## Actual Behavior
 When I try to run the project, I a getting AAPT: error: resource android:attr/lStar not found
My Android/build.gradle =>

ext {
        supportLibVersion = "28.0.0"
        googlePlayServicesLocationVersion = "19.0.1"  // Or higher.
        googlePlayServicesVersion = "+"

        buildToolsVersion = "30.0.1"
        minSdkVersion = 24
        compileSdkVersion = 31
        targetSdkVersion = 31

        //androidXCore = "1.7.0"

        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.2.0"
        appCompatVersion = "1.1.0"
        androidMapsUtilsVersion = "2.2.5"
    }

## Context

Getting the following log
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/gauravsingh/.gradle/caches/transforms-2/files-2.1/22574ce76ff94b580f063fd066e5fc3d/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by christocracy** [comment]
> googlePlayServicesVersion = "+"

Well that certainly looks highly unusual and not recommended.

have you looked at this?
https://github.com/mostafa-mansour1/previewAnyFile/issues/39

**Comment by gaurav07june** [comment]
ext {
        supportLibVersion = "28.0.0"
        googlePlayServicesLocationVersion = "19.0.1"  // Or higher.
        googlePlayServicesVersion = "17.0.0"

        buildToolsVersion = "30.0.1"
        minSdkVersion = 24
        compileSdkVersion = 31
        targetSdkVersion = 31

        //androidXCore = "1.7.0"

        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.2.0"
        appCompatVersion = "1.1.0"
        androidMapsUtilsVersion = "2.2.5"
    }

I had already tried with a specific version but the same issue. For "+" thing I searched into react-native-background-location library and found
if (useAndroidX) {
        api(group: 'com.transistorsoft', name:'tslocationmanager', version: '+')
        implementation "androidx.localbroadcastmanager:localbroadcastmanager:$localBroadcastManagerVersion"
    } else {
        api(group: 'com.transistorsoft', name:'tslocationmanager-reverse', version: '+')
    }

in Android/build.gradle.
Can it be the cause of issue? The project runs after uninstalling the library.

**Comment by mikehardy** [comment]
Never use plus signs in your dependencies unless you are in control of the dependencies (note: Chris is in control of the tslocation dependencies - since they are in a *local maven repo published with the package*). There should be no plus signs anywhere else.

If you are getting the lStar message it means you are not ready for androidx core 1.7.0 yet, and you need to take control of that dep so that 1.7.0 doesn't leak in yet, like

https://stackoverflow.com/a/69024140/9910298

**Comment by christocracy** [comment]
> since they are in a local maven repo published with the package)

That’s correct.

**Comment by johnbaishya** [comment]
still this issue is not solved in my case
