### ISSUE TITLE
Sending same location after a while on the go

### ISSUE THREAD

**Issue by ademirtemur** [transistorsoft/react-native-background-geolocation#1484]
## Your Environment
* Plugin version: 4.7.1
* Platform: iOS and Android
* OS version: any
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.66.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
                   desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
                    stationaryRadius: 0,
                    distanceFilter: 0,
                    startOnBoot: true,
                    stopOnTerminate: false,
                    stopOnStationary: false,
                    locationUpdateInterval: 10000,
                    fastestLocationUpdateInterval: 10000,
                    pausesLocationUpdatesAutomatically: false,
                    locationAuthorizationRequest: "Always",
                    autoSync: true,
                    disableElasticity: false,
                    heartbeatInterval: 60,
                    preventSuspend: true,
                    locationTimeout: 65,
                    activityRecognitionInterval: 10000,
                    // allowIdenticalLocations: false,
                    disableStopDetection: true,
                    autoSyncThreshold: 0,
                    batchSync: false,
                    showsBackgroundLocationIndicator: false,
                    disableMotionActivityUpdates: false,
                    disableAutoSyncOnCellular: false,
                    enableHeadless: true,
                    triggerActivities: "on_foot, walking, running, on_bicycle, in_vehicle",
                    enableTimestampMeta: true,
                    persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
                    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                    url: <POST_URL>,
                    method: 'POST',
```

## Expected Behavior

**Should send different locations on the go**

## Actual Behavior

_COMING_

{event='null', isMoving=true, uuid=6784fc4f-3d13-40c6-b2d8-c9afafdec453, timeStamp=2022-05-22T16:06:21.857Z, timestampMeta=TimestampMeta{time=2022-05-22 16:06:21.856, systemTime=2022-05-22 16:06:21.919, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741819405077123, longitude=29.094805956975016, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

{event='null', isMoving=true, uuid=8c16898f-2b28-4961-9061-16ac6c1b709c, timeStamp=2022-05-22T16:06:36.862Z, timestampMeta=TimestampMeta{time=2022-05-22 16:06:36.862, systemTime=2022-05-22 16:06:36.912, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741819405387652, longitude=29.094805956668118, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

{event='null', isMoving=true, uuid=a5587101-635b-4b95-8a24-d5bb88226eb7, timeStamp=2022-05-22T16:06:51.938Z, timestampMeta=TimestampMeta{time=2022-05-22 16:06:51.938, systemTime=2022-05-22 16:06:51.969, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741819405486147, longitude=29.094805956570774, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

**### _IT IS SENDING SAME LOCATION ON MOVING AFTER HERE_**

{event='null', isMoving=true, uuid=e9649fe4-fe98-41c1-b82f-6090a33555fc, timeStamp=2022-05-22T16:07:01.699Z, timestampMeta=TimestampMeta{time=2022-05-22 16:07:01.699, systemTime=2022-05-22 16:07:01.725, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741813599187026, longitude=29.094841772298057, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

{event='null', isMoving=true, uuid=e9649fe4-fe98-41c1-b82f-6090a33555fc, timeStamp=2022-05-22T16:07:01.699Z, timestampMeta=TimestampMeta{time=2022-05-22 16:07:01.699, systemTime=2022-05-22 16:07:01.725, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741813599187026, longitude=29.094841772298057, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

{event='null', isMoving=true, uuid=e9649fe4-fe98-41c1-b82f-6090a33555fc, timeStamp=2022-05-22T16:07:01.699Z, timestampMeta=TimestampMeta{time=2022-05-22 16:07:01.699, systemTime=2022-05-22 16:07:01.725, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741813599187026, longitude=29.094841772298057, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

{event='null', isMoving=true, uuid=e9649fe4-fe98-41c1-b82f-6090a33555fc, timeStamp=2022-05-22T16:07:01.699Z, timestampMeta=TimestampMeta{time=2022-05-22 16:07:01.699, systemTime=2022-05-22 16:07:01.725, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741813599187026, longitude=29.094841772298057, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

{event='null', isMoving=true, uuid=e9649fe4-fe98-41c1-b82f-6090a33555fc, timeStamp=2022-05-22T16:07:01.699Z, timestampMeta=TimestampMeta{time=2022-05-22 16:07:01.699, systemTime=2022-05-22 16:07:01.725, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741813599187026, longitude=29.094841772298057, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

{event='null', isMoving=true, uuid=e9649fe4-fe98-41c1-b82f-6090a33555fc, timeStamp=2022-05-22T16:07:01.699Z, timestampMeta=TimestampMeta{time=2022-05-22 16:07:01.699, systemTime=2022-05-22 16:07:01.725, systemClockElaspsedRealtime=0, elapsedRealtime=null}, odometer=777, coords=Coordinates{latitude=37.741813599187026, longitude=29.094841772298057, accuracy=65.0, speed=-1.0, speedAccuracy=-1.0, heading=-1.0, headingAccuracy=-1.0, altitude=475.2, altitudeAccuracy=10.0}, activity=Activity{type='still', confidence=100.0}, battery=Battery{isCharging=false, level=0.5199999809265137}, extras=Extras{}}

**_AND IS GOING LIKE THIS_**

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> uuid=a5587101-635b-4b95-8a24-d5bb88226eb7

It’s going to keep sending that location until your server returns http status 200/202/203

until then, the plugin will keep trying, trying, trying.
