### ISSUE TITLE
Service does not complete tracking

### ISSUE THREAD

**Issue by andreaMoyotl** [transistorsoft/react-native-background-geolocation#1485]
## Your Environment
* Plugin version: ^4.4.4
* Platform: Android
* OS version: Android
* Device manufacturer / model: OPPO A16
* React Native version (`react-native -v`): react-native-cli: 2.0.1   react-native: 0.67.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    autoSync: true,
    debug: false,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    disableElasticity: false,
    distanceFilter: 30,
    enableHeadless: true,
    fastestLocationUpdateInterval: 10000,
    foregroundService: true,
    geofenceProximityRadius: 1000,
    heartbeatInterval: 60,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    logMaxDays: 0,
    method: 'POST',
    preventSuspend: true,
    stopDetectionDelay: 1000,
    stopOnTerminate: false,
    stopTimeout: 5,
    triggerActivities: 'in_vehicle, on_bicycle, running, walking, on_foot',
    url: "https://my-services.the-system.test",
    persist: true,
    persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
}

```

## Expected Behavior
The plugin shouldn't stop doing the tracking.

## Actual Behavior
A route is made with a device exposed to changes of signal coverage. During a point in the route the plugin stops the tracking and does not reflect new registered points.

## Context
A route is made with a device exposed to changes of signal coverage. This problem has occurred on several occasions with different devices  without a common pattern.

</details>

**Comment by christocracy** [comment]
> OS version: Android

“android” is not an OS Version.

> changes of signal coverage

I’m not sure what “signal coverage” means.

see wiki Debugging and gather logs from the plugin using .emailLog method.

**Comment by andreaMoyotl** [comment]
Thanks for your answer. 

Sorry, it's Android 11.
With signal coverage I mean that sometimes the device can have 4g, 3g or no signal at all.

This issue doesn't happen with all the routes we have made (happens randomly).
In an exercise the log sent an 408 error after this the plug-in didn't try to send any register even though we use BackgroundGeolocation.sync().

**Comment by christocracy** [comment]
Cellular connection doesn’t affect tracking.  While outdoors, the plugin is probably using GPS.

most of my 13 test devices don’t even have a SIM card.

**Comment by andreaMoyotl** [comment]
Ok, we followed the instructions of https://dontkillmyapp.com/ to avoid the 408 error but it has not worked. Is there something else we can try or another cause?

**Comment by christocracy** [comment]
Provide logs
