### ISSUE TITLE
Issue with Android appcompat

### ISSUE THREAD

**Issue by rarenatoe** [transistorsoft/react-native-background-geolocation#1486]
## Your Environment
* Plugin version: 4.6.0 and 4.7.1
* Platform: Android
* OS version: Android 8.1
* Device manufacturer / model: Pixel 3 (Doesn't matter)
* React Native version (`react-native -v`): 0.67.4
* appcompat: 1.3.1, 1.4.1

## Expected Behavior

Expected my app to work without error.

## Actual Behavior

Version 4.4.6 works well, however 4.6.0 and 4.7.1 throw up this error:
![image](https://user-images.githubusercontent.com/44821537/171061064-55b7a5ab-251d-4671-8bf7-07c56816d115.png)

This is highly linked to appcompat for whatever raeson.

## Steps to Reproduce

1. Use react native TextInput in your app.
2. run android 8.1 emulator, doesn't matter which model.
3. install the dependency on version 4.6.0
4. run android app
5. crash

## Context

I'm trying to get my app to work with the latest "stable" versions of `react-native-background-geolocation` but old android versions are failing.

**Comment by christocracy** [comment]
I don’t know what that’s all about but I had that error in the demo app.

I googled the error and fixed it with [this](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/9e7e719d5d64243d823d6e3bfa6ff446e9bef93c/android/app/build.gradle#L232)

**Comment by rarenatoe** [comment]
Thanks yeah I saw that too but that's more of a hotfix

**Comment by christocracy** [comment]
That’s all there is at the moment.

the plugin needs appcompat >= 1.3.1 due to its latest update of android-permissions dependency.

something is borked with TextView and appcompat >= 1.3.1.  

Somebody in RN will hopefully figure that out at some point.

**Comment by mikehardy** [comment]
They have already fixed that - but the fix is in react-native 0.68+, once you upgrade to that you may use AppCompat 1.4+

https://github.com/facebook/react-native/issues/31572
https://github.com/facebook/react-native/commit/e21f8ec34984551f87a306672160cc88e67e4793

**Comment by christocracy** [comment]
Thanks @mikehardy
