### ISSUE TITLE
Physical Activity & Location Permission Strings cannot change

### ISSUE THREAD

**Issue by idealkw** [transistorsoft/react-native-background-geolocation#1487]
## Your Environment
* Plugin version: ^4.4.6
* Platform: Android
* OS version: 12
* Device manufacturer / model: Redmi Note 10 Pro Max
* React Native version (`react-native -v`): 0.67.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  BackgroundGeolocation.ready({
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          // title: "Allow access to this device's location in the background?",
          message:
            'This app requires background location to notify you on entering and exiting your GPS zone',
          positiveAction: 'Change to Allow all the time',
          negativeAction: 'Cancel',
        },
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        locationUpdateInterval: 20000,
        distanceFilter: 0,
        stopTimeout: 5,
        debug: false,
        enableHeadless: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        geofenceModeHighAccuracy: true,
        disableMotionActivityUpdates: false,
        preventSuspend: true,
        heartbeatInterval: 60,
      })
        .then(state => {
          console.log(
            '- BackgroundGeolocation is configured and ready: ',
            state.enabled,
          );
          BackgroundGeolocation.startGeofences().then(() =>
            console.log('geofence start'),
          );
          BackgroundGeolocation.addGeofences(
            zones
              ?.map((zone, index) => {
                if (zone?.is_active) {
                  let zoneIdentify = zone?.id
                    .toString()
                    .concat('$')
                    .concat(zone?.zone_name);
                  return {
                    identifier: zoneIdentify,
                    radius: zone?.zone_radius * 1000,
                    latitude: Number(zone?.zone_latitude),
                    longitude: Number(zone?.zone_longitude),
                    notifyOnEntry: true,
                    notifyOnExit: true,
                  };
                }
              })
              .filter(({radius}) => radius > 0),
          )
            .then(success => {
              console.log('[addGeofences] success', success);
            })
            .catch(error => {
              console.log('[addGeofences] FAILURE: ', error);
            }
[background-geolocation (6).log](https://github.com/transistorsoft/react-native-background-geolocation/files/8813298/background-geolocation.6.log)
);
        })
```

## Expected Behavior
I want to change the Physical Activity permission string. It is set to "Allow [app name] to access your physical activity?" by default. In order to share the purpose of this permission to the user i need to add this string.

## Actual Behavior
Physical Activity permission popup is coming with this string "Allow [app name] to access your physical activity?". And it is not coming before the background location permission dialogue box.

## Context
We are taking location permission before showing the purpose of this permission. It is leading to rejection in review on Google Play Store. So we want to add purpose of taking location and physical activity permission.

</details>

**Comment by christocracy** [comment]
>I want to change the Physical Activity permission string

The plugin has no mechanism to change that.  I'm not even aware that is *can* be changed.

**Comment by idealkw** [comment]
Okay , But I am getting rejected from the play store , as now a days they want us to properly describe why we are using the physical activity ,here i am attaching a screenshot which I have received from them. 

Do review these as it required now to change the string on all appearances .
<img width="658" alt="Screenshot 2022-06-02 at 10 40 10 AM" src="https://user-images.githubusercontent.com/103848633/171557137-d6183d79-d14e-41bd-b9c0-4ae6d293f4ca.png">

**Comment by christocracy** [comment]
“*Prominent Disclosure*” is explained in my blog post above.

show me a screenshot of your “prominent disclosure” you’re producing.

**Comment by idealkw** [comment]
Yeah sure , there are two disclosures we have Physical Activity & Location access
![IMG_20220602_161228](https://user-images.githubusercontent.com/103848633/171613457-08e2b595-40c3-4af4-9b2c-570efcb6ff55.jpg)
![IMG_20220602_161556](https://user-images.githubusercontent.com/103848633/171613467-3285ec55-f4c3-484a-a92b-c4e304820869.jpg)

**Comment by christocracy** [comment]
As I suspected, *neither* of those are what Google refers to as “*Prominent Disclosure*”.

please go back to my blog post and carefully read about “Prominent Disclosure”, a simple alert that YOU produce and show with your own code *before* you request any permissions,

**Comment by christocracy** [comment]
https://link.medium.com/cwjT7XmYwqb

**Comment by idealkw** [comment]
Yeah , I miss understood ,thanks for the clarification , you article helps us alot we got approve  on play store 
Thanks
