### ISSUE TITLE
HTTP post requests are being sent to server even after stopSchedule.

### ISSUE THREAD

**Issue by mahesh-agrawal-616** [transistorsoft/react-native-background-geolocation#1489]
## Your Environment
* Plugin version: 3.9.3
* Platform: iOS or Android iOS
* OS version: 15.2
* Device manufacturer / model: iPhone 13 Pro
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.stopSchedule();
BackgroundGeolocation.onHttp((response) => {
    console.log("[onHttp] ", JSON.stringify(response));
});
```
## Expected Behavior

I was expecting that the HTTP post process should stop after calling stopSchedule();
## Actual Behavior

onHTTP is being called even after stopping the schedule.
## Steps to Reproduce

1. Start the schedule with HTTP request details by setting the config.
2. Stop the schedule after some time.
3. Observe the onHTTP is still being called.

## Context

Was trying to track users location based on schedule.
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
[onHttp]  { responseCode: 500 }
</details>

**Comment by christocracy** [comment]
Are you observing the plug-in’s logs in `adb logcat` or using `.emailLog()` method?

**Comment by mahesh-agrawal-616** [comment]
I am observing the calls on my backend and i am sure that its my log as the entire app is in dev mode and i am only working on this.
