### ISSUE TITLE
the locations contain null geofence even if the user enters or exits a geofence when the app is terminated but if the user opens the app or minimizes it the locations contain the geofence info

### ISSUE THREAD

**Issue by code-with-me1312** [transistorsoft/react-native-background-geolocation#1491]
## Your Environment
* Plugin version: 4.4.4
* Platform: iOS or Android
* OS version: Mac os
* Device manufacturer / model:
* React Native version (`react-native -v`):0.67.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 15,
    stopTimeout: 5,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,
    startOnBoot: true,
    url: `${constants.baseUrl}/api/locations/`,
    batchSync: false,
    autoSync: true,
    headers: {
      Authorization: token,
    },
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: {
      title:
        "Allow CommuteSaver to access this device's location even when closed or not in use ?",
      message:
        'CommuteSaver collects location data to enable co2 emissions calculation even when the app is closed or not in use.',
    }
  })
```

## Expected Behavior

the location should contain the geofence info if the user passes through a geofence even if the app is terminated.

## Actual Behavior

the location doesn't contain the geofence info even if the user passes through a geofence while the app is terminated.

## Steps to Reproduce

1. terminated the app
2. pass through a geofence
3. location object will have null geofence 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
```

</details>

**Comment by christocracy** [comment]
>Platform: iOS or Android
>OS version: Mac os
>Debug logs

See Wiki *Debugging* to learn how to view and/or retrieve logs from the plugin.

**Comment by mikehardy** [comment]
> Plugin version: 4.4.4

also, use current version just in case something has already been fixed...

**Comment by MostafaMareyAhmed** [comment]
@christocracy is it possible to see the logs when the app is terminated?

**Comment by christocracy** [comment]
In your terminal:
```
$ adb logcat *:S TSLocationManager:V
```
