### ISSUE TITLE
android 12 toast

### ISSUE THREAD

**Issue by lukasa1993** [transistorsoft/react-native-background-geolocation#1492]
on android 12 toast wraps and instructions aren't readable

**Comment by mikehardy** [comment]
A screenshot of exactly which toast you  mean would be nice

I do see this, it's new to me: https://developer.android.com/guide/topics/ui/notifiers/toasts

> If your app targets Android 12 (API level 31) or higher, its toast is limited to two lines of text and shows the application icon next to the text. Be aware that the line length of this text varies by screen size, so it's good to make the text as short as possible.

Indicated workarounds are snackbar or notification...

**Comment by lukasa1993** [comment]
it disappears so fast i couldn't take picture i'll try again, basically toast to guide new user how to set it up

**Comment by mikehardy** [comment]
alternatively then, exact steps to reproduce.
There's actually a template that includes these things, so we don't have to spend our valuable time commenting back and forth for obvious questions ;-)

```
<!--
*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************
-->

<!--
  Provide a general summary of the issue in the Title above
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

```

**Comment by mikehardy** [comment]
Those aren't...steps?
Steps are:
1) maybe something like git clone something
2) maybe something like install something on some specific thing (like, real device using android 12, or, emulator or whatever)
3) do something
4) see something wrong

I'm just saying, if I'm your co-worker, and you are my manager, I come to you with this report, and if you don't tell me to come back to the office with something specific, we're going to have an employer/employee chat right?

**Comment by christocracy** [comment]
Edit your original post.  Provide *all* the information requested in the issue template.
