### ISSUE TITLE
[Android] onMotionChange not working as expected

### ISSUE THREAD

**Issue by avishain** [transistorsoft/react-native-background-geolocation#1499]
## Your Environment
* Plugin version: 4.3.0
* Platform: Android
* OS version: Android >= 11
* Device manufacturer / model: Xiaomi  || Samsung || One Plus
* React Native version (`react-native -v`): 0.65.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            allowIdenticalLocations: true,
            stopTimeout: 5,
            isMoving: true,
            debug: false, 
            logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
            stopOnTerminate: true,  
            startOnBoot: false,        
            batchSync: false,       
            autoSync: false,        
            maxRecordsToPersist: 1000,
        })
```

## Expected Behavior
WHEN - start driving on bicycle --> onActivityChange will fire with the value of 'on_bicycle' after few seconds
WHEN - stop cycling --> onActivityChange will fire with the value of 'still' after few seconds

## Actual Behavior
It's extremely inconsistent. most of the time the event is not being emitted when it should (from still to active and vise-versa) and when it does it happens 10-50 seconds after the change in activity really happens.

## Steps to Reproduce
1. start tracking activity
2. start walking/cycling
3. stop moving
4. repeat 2-3
5. stop tracking activity

## Context

I want it to work like pro fitness apps work (like Strava), i.e. fire the 'on_bicycle' activity type at most 8-10 seconds after actual activity start. fire the 'still' activity type at most 8-10 seconds after actual activity pauses.

#### comment
It happens also with the app I downloaded from the PlayStore (BGGeolocation)

**Comment by christocracy** [comment]
The MotionActivity api is a black box provided by *Google Play Services*.  It has nothing more than an ON/OFF switch.  There is nothing to configure thus there is no possible way to improve performance.

the performance of the MotionActivity api varies greatly across devices and depends upon the quality of the sensors on the particular device (accelerometer, gyroscope and magnetometer).

**Comment by christocracy** [comment]
The plugin uses a geofence around the last known position as a backup triggering mechanism.  That typically requires movement of ~200 meters from last known position to trigger, unless the motion api triggers before.

**Comment by christocracy** [comment]
The plugin migrated to the new [requestActivityTransitionUpdates](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient#requestActivityTransitionUpdates(com.google.android.gms.location.ActivityTransitionRequest,%20android.app.PendingIntent)) several years ago.

before that, it used the older [requestActivityUpdates](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient#requestActivityUpdates(long,%20android.app.PendingIntent)).

I won’t be going back to the older version.
