### ISSUE TITLE
getGeofences doesn't return as documented

### ISSUE THREAD

**Issue by JAStanton** [transistorsoft/react-native-background-geolocation#15]
`getGeofences` returns a geofence per argument instead of an array of geofences as its first argument.

```jsx
getGeofences(function(geofence1, geofence2, geofence3, etc...) {
  ...
});
```
instead of
```jsx
getGeofences(function(geofences) {
  ...
});
```

In the react export on the objectiveC side the callback function expects an array of arguments, you're just giving it an array of geofences.

**Comment by christocracy** [comment]
Thanks I'll fix it up asap.
