### ISSUE TITLE
Is it possible to filter the locations sent to the server via the HTTP feature

### ISSUE THREAD

**Issue by stephen776** [transistorsoft/react-native-background-geolocation#1503]
What I would like to do is have the location tracking running at a high level of accuracy (I'm targeting iOS) and I'd like to sync the events to my server in batches with the HTTP feature which I can accomplish via the available confiuration

I'm wondering if it's possible to filter the "batch" of locations before making the POST.

For example - if my batch contains 30 locations, I'd like to analyze the locations and remove "insignificant" coordinates from the batch to reduce the data sent to my server. An example of filtering the "insignificant" coords would be something like:

If 20 of my 30 coords are relatively co-linear, I can omit some of the "middle" points on the straight line. So in this case I'd only need to send maybe 15 coords to my server instead of all 30.

I'd like to avoid reducing the distance filter in order to preserve high levels of detail if the device is navigating around curve or otherwise not in a "straight" line

**Comment by christocracy** [comment]
You’re free to call `.getLocations()` and call [`.destroyLocation(location.uuid)`](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#destroylocation) on those you’re not interested in, *before* calling `.sync()`.

the http service feeds of records found in SQLite.

**Comment by stephen776** [comment]
Awesome! - thanks for the info
