### ISSUE TITLE
Android onLocation not firing after initial location

### ISSUE THREAD

**Issue by discodane** [transistorsoft/react-native-background-geolocation#1505]
## Your Environment
* Plugin version: 4.4.4
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.67
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
// Simplified for debug purposes
// Initialization of the lib:
let initialized = false;
export const initializeLocationWatcherService = ({ store, config }) => {
  if (initialized === true) {
    return;
  }

  BackgroundGeolocation.on('location', location => onLocationChange(store, location));

  BackgroundGeolocation.on('providerchange', provider => onProviderChange(store, provider));

  BackgroundGeolocation.on('heartbeat', () => onHeartbeat(store));

  BackgroundGeolocation.ready({
    ...config,
    reset: true,
  }, state => onBGReady(state));
  initialized = true;
};

export const onBGReady = async state => {
  BackgroundGeolocation.start();
};


// Config:
export const defaultBackgroundGeolocationConfig = {
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 2,
  fastestLocationUpdateInterval: 1000,
  stationaryRadius: 2,
  debug: false,
  stopOnTerminate: false,
  startOnBoot: false,
  disableLocationAuthorizationAlert: true,
  locationAuthorizationRequest: 'Always',
  heartbeatInterval: 300,
  preventSuspend: true,
  stopTimeout: 5,
  notification: {
    priority: 1,
  },
  backgroundPermissionRationale: {
    title: 'Allow DRIVE to Access Location?',
    message: 'This lets DRIVE track the load location from your device.',
    positiveAction: 'Always Allow Access',
    negativeAction: 'Don\'t Allow',
  },
};
```

## Expected Behavior

On android, using lockito to simulate a car ride, with permissions set to "while in use" and the app foregrounded, I expect the on('location') callback to fire constantly

## Actual Behavior

on('location') is called once at startup, and not again for +-6 minutes

## Steps to Reproduce

1. Login to app,
2. Go through app permissions setting the location permissions to "while in use"
3. Cancel the "change to always" prompt to keep it on while in use permission
4. Notice the location watcher isn't firing when doing a car ride simulation
5. Wait for 5-6 minutes and see +- 10 location pings all at once, and then stop again for another +- 5-6 minutes

## Context

I'm trying to log live location updates

## Debug logs

<details><summary>Logs</summary>
It creates no logs until 5-6 minutes when the location pings finally come in, after which you see normal looking location change logs

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- see wiki *Debugging*.  Learn to observe the plugin logs in `logcat` to see why the plugin is doing what you observe.

**Comment by christocracy** [comment]
With *WhenInUse* permission, you must *manually* engage the tracking state by calling `.changePace(true)` after calling `.start()`.

```javascript
await BackgroundGeolocation.start();
await BackgroundGeolocation.changePace(true);
```

**Comment by discodane** [comment]
I believe from reading the documentation(correct me if i'm wrong) that this will result in a heavy(at least heavier) strain on the battery life. Would it be a net gain to just force the user to do "Always allow" instead?

**Comment by christocracy** [comment]
There are **consequences** to *WhenInUse*.  The plugin cannot automatically engage location-tracking in the background with *WhenInUse*.  You must initiate location-tracking in the foreground via .changePace(true) when the user wishes to have their location-tracked.  Like a Jogging app with a [Start Workout] / [Stop Workout] button.

Config.stopTimeout still applies; when the device remains stationary for stopTimeout minutes, the plugin will automatically turn off location-services (essentially calling .changePace(false) upon itself.).

Only with *Always* authorization are you allowed to simply call .start() and have the plugin automatically track the device whenever it’s detected to be moving.

**Comment by christocracy** [comment]
>that this will result in a heavy(at least heavier) strain on the battery life

False.  Config.stopTimeout still applies.
