### ISSUE TITLE
mph/kph conversion from meters per hour

### ISSUE THREAD

**Issue by williamswebworks** [transistorsoft/react-native-background-geolocation#1506]
Per the API documentation the speed is collected at meters per hour but we are looking for a way to set it to show MPH. Is this a setting or can a setting be added to convert the meters per hour to MPH?

**Comment by christocracy** [comment]
It’s not *meters / hour*, it’s *meters / second*.

This is basic mathematics to convert to mph.  Google it “meters/second to miles/hour”.
