### ISSUE TITLE
No GPS callback if there is not internet

### ISSUE THREAD

**Issue by techteamPA** [transistorsoft/react-native-background-geolocation#1512]
## Your Environment
* Plugin version:4.7.1
* Platform: Android
* OS version: 11
* Device manufacturer / model: Realme 5 pro
* React Native version (`react-native -v`): 0.66.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const onLocation = BackgroundGeolocation.onLocation((location) => {
      console.log('[onLocation]', location);
     // alert("location data :- ",JSON.stringify(location));
      setLocation(JSON.stringify(location, null, 2));
       // API call
      gpsCoordsApi(location);
    }, (error) => {
      console.log("[onLocation] ERROR: ", error);
    });
BackgroundGeolocation.ready({
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter:
          radStatusId == 1
            ? normalGPSConfig != undefined && normalGPSConfig.hasOwnProperty('minmeters')
              ? normalGPSConfig.minmeters
              : 50
            : liveGPSConfig != undefined && liveGPSConfig.hasOwnProperty('minmeters')
            ? liveGPSConfig.minmeters
            : 20,
        // Activity Recognition
        stopTimeout: 5,
        // Permissions
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          title:
            "Allow {applicationName} to access this device's location even when closed or not in use.",
          message:
            'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel',
        },
        disableMotionActivityUpdates : true,
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true,
        enableHeadless: true, // <-- Auto start tracking when device is powered-up.
      })
        .then(state => {
          setEnabled(true);
          console.log(
            '- BackgroundGeolocation is configured and ready: ',
            state,
          );
        })
        .catch(error => {
          console.warn('- BackgroundGeolocation error: ', error);
        });
    }, 300);
```

## Expected Behavior
The application should receive a GPS callback even if there is no internet connectivity.
## Actual Behavior
No logs get logged on the server if there is minimum or no internet connectivity.

## Steps to Reproduce

1. Switch off the internet
2. Start the application to send logs to the server.

## Context

We trying to use the application while traveling on a metro train where there is minimum internet connectivity.
The application was tested in released mode.
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Switch off the internet

How exactly are you “switching off the internet”?

You can’t simulate “switching off the internet” by disabling Wifi.  Disabling wifi will prevent locations being able to be recorded.

I test 12 Android devices without a SIM card.  The plugin tracks fine without a SIM card.

**Comment by techteamPA** [comment]
Yes we know all these parameters or information about the GPS mechanism
However, we just like to know that, no matter if the device is at an outdoor location (or wherever the device can receive the GPS coordinates) the library will provide a callback that can be checked via logs. Right? So that we can rest assured that all these coordinates can be stored in local storage and then an application can try sending the logs to the server if the app is in connectivity

**Comment by christocracy** [comment]
> So that we can rest assured that all these coordinates can be stored in local storage and then an application can try sending the logs to the server if the app is in connectivity

Read the api docs “HTTP Guide”.

this plugin was originally developed for a disaster response app, tracking emergency workers in earthquakes in an environment where the cellular network is assumed to be destroyed.  It is designed to work in “offline” environments, persisting each recorded location to its own SQLite database, uploading those queued locations when a network connection is restored.

**Comment by techteamPA** [comment]
> Read the api docs “HTTP Guide”.
> 
> this plugin was originally developed for a disaster response app, tracking emergency workers in earthquakes in an environment where the cellular network is assumed to be destroyed. It is designed to work in “offline” environments, persisting each recorded location to its own SQLite database, and uploading those queued locations when a network connection is restored.

Thank you for sharing the information that was really helpful. 
Could you please let us know how this offline mechanism works?
Can we fetch the offline data from the SQLite table and upload it to our server as soon as the device is back online.
Or you would suggest relying on the existing in-built mechanism.

**Comment by christocracy** [comment]
See api docs .getLocation()

> Or you would suggest relying on the existing in-built mechanism.

Why you *not* provide the plugin a Config.url and let the plugin manage http uploads using its pure native http service?  It’s far more reliable than rolling your own in JavaScript.

**Comment by techteamPA** [comment]
>Why do you not provide the plugin a Config.url and let the plugin manage HTTP uploads using its pure native HTTP service? It’s far more reliable than rolling your own in JavaScript.

Thank you for sharing the information that was really helpful.
Could you please confirm that the plugin will work in kill state on iOS/Android?

**Comment by christocracy** [comment]
> Could you please confirm that the plugin will work in kill state on iOS/Android?

Yes, that’s why there exists the option Config.stopOnTerminate (and Config.startOnBoot).  See the api docs.
