### ISSUE TITLE
onHeartbeat stops reporting when the device starts moving

### ISSUE THREAD

**Issue by alexander126** [transistorsoft/react-native-background-geolocation#1513]
onHearbeat callback is not invoked if the device starts moving
## Your Environment
* Plugin version: 4.8.1
* Platform: iOS
* OS version: Any version above 13.3.1
* Device manufacturer / model: iPhone 7, iPhone 11 Pro
* React Native version (`react-native -v`): 0.67.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
//Config
export const geolocationConfig = {
  heartbeatInterval: 60, // Time between heartbeats, in seconds
  preventSuspend: true,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  distanceFilter: 0,
};
//Init functions
export const configGeolocation = async () => {
  await BackgroundGeolocation.ready(geolocationConfig);
};

export const startGeolocationTracking = async () => {
  await BackgroundGeolocation.start();
};
export const initialiseBackgroundTracking = async () => {
  try {
    console.log('start');
    await configGeolocation();
    await startGeolocationTracking();
  } catch (e) {
    fireNotification(
      `Initialisation error`,
      `${e.message}
  }`,
    );
  }
};

//onHeartbeat listener in main screen

  useEffect(() => {
    const subscription = BackgroundGeolocation.onHeartbeat((event) => {
      console.log('[onHeartbeat] ', event);
     // custom function that utilises  BackgroundGeolocation.getCurrentPosition()
      getCurrentPosition(
        store.getState().locations,
        dispatch,
        true,
        'onHeartbeat',
      );
    });

    return () => subscription;
    // eslint-disable-next-line react-hooks/exhaustive-deps -- componentDidMount
  }, []);
```

## Expected Behavior
The heartbeat should run every 60 seconds, regardless if the device is moving around slow or fast or being stationary

## Actual Behavior
onHearbeat callback is invoked only when the device is stationary in the initial location it has been started

## Steps to Reproduce

1. Run the app
2. Start driving/walking around
3. Expect onHeartbeat event to be called

## Context
We are trying to get user's location every 15 minutes (the config is set to 60 seconds for testing purposes) and store it locally regardless if they are moving or not

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It is by design that heartbeat stops when device is moving.

there is no longer a need for periodic timer to run when the app is awake and recording location.

this will not change.

**Comment by alexander126** [comment]
@christocracy what would be the best way to implement functionality that updates the location periodically (15-30 mins intervals) that also takes into account the battery life?

**Comment by christocracy** [comment]
Use background-fetch, already installed as a dependency.
