### ISSUE TITLE
iOS issue - 'onGeofence' doesn't get triggered if geofence is around the user's current location

### ISSUE THREAD

**Issue by jagrajSidhu** [transistorsoft/react-native-background-geolocation#152]
I am using following code -
bgGeo.onGeofence(function(geofence, taskId) {
console.log('Geofence Triggered', geofence);
}
Well! it works fine on android.

**Comment by christocracy** [comment]
Correct.  iOS doesn't have the ability to  trigger a geofence if device is already in it.  The Android geofencing API allows this to be configurable (the plugin hardcodes this to trigger)

Someone on the Cordova plugin wants this too.  I'm looking into it.

**Comment by christocracy** [comment]
Ok, I've got a solution working for iOS.  Should be posted today, in addition to new `@config {Boolean} geofenceInitialTriggerEntry [true]`.

**Comment by jagrajSidhu** [comment]
Thanks :-)
