### ISSUE TITLE
Is `allowsbackgroundlocationupdates` set to true in `CLLocationManager` on iOS?

### ISSUE THREAD

**Issue by elly0t** [transistorsoft/react-native-background-geolocation#1520]
## Your Environment
* Plugin version: `4.7.1`
* Platform: iOS
* OS version: iOS 15 in general
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): `0.63.4`
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        await BackgroundGeolocation.ready({
          locationAuthorizationRequest: 'Always',
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          stationaryRadius: 5,
          showsBackgroundLocationIndicator: true,
          stopOnTerminate: false,
          heartbeatInterval: 60,
          startOnBoot: true,
          enableHeadless: true,
          isMoving: true,
          // ios
          preventSuspend: true,
        });
```

## Expected Behavior
Constant location updates in the background on iOS

## Actual Behavior
Sometimes location updates went missing on iOS. We are seeking potential reasons.

## Steps to Reproduce
Kick start the app and subscribe to location updates with this library, then put in background

## Context
We develop a location tracking app and at times on iOS no background location updates were provided, when the app is put the in the background. We are looking at possible reasons and the `allowsbackgroundlocationupdates` config is one of them.

I saw there is a `TSLocationManager` in the source code which I reckon handles all location stuffs. Just wondering if [allowsbackgroundlocationupdates](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620568-allowsbackgroundlocationupdates) is set to `true` in the library's `CLLocationManager`? We've dug through the documents and this repo's source code but had no luck confirming that.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Just wondering if [allowsbackgroundlocationupdates](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620568-allowsbackgroundlocationupdates) is set to true in the library's CLLocationManager?

yes, of course.

I’m not new to this.  I’ve been working on this plugin full time since iOS 7.

**Comment by elly0t** [comment]
Cheers man. Just wanna confirm as we have only partial access to the source code, your library rocks btw :)
