### ISSUE TITLE
Building fails on IOS with Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by dlavrantonis** [transistorsoft/react-native-background-geolocation#1525]
## Your Environment
* Plugin version:4.8.2
* Platform: iOS
* OS version: iOS 15.6
* Device manufacturer / model: iphone 8
* React Native version (`react-native -v`):0.68.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Actual Behavior
building on xcode for actual device fails with:

Undefined symbols for architecture arm64:
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_RNFusedLocation in RNFusedLocation.o
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      type metadata for react_native_geolocation_service.RNFusedLocation in RNFusedLocation.o
  "_RCTMakeAndLogError", referenced from:
      react_native_geolocation_service.checkPlistKeys(Swift.String) -> () in LocationUtils.o
  "_RCTRegisterModule", referenced from:
      _initialize_RNFusedLocation in RNFusedLocationBridge.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Steps to Reproduce
build on xcode for actual device.

## Context
build on xcode for actual device.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>react_native_geolocation_service.RNFusedLocation in RNFusedLocation.o

Your problem is with some plugin named `react_native_geolocation_service`, not background-geolocation.

**Comment by dlavrantonis** [comment]
duh apologies
