### ISSUE TITLE
I'm unable run the library while application in is background state

### ISSUE THREAD

**Issue by AsH-RN** [transistorsoft/react-native-background-geolocation#1528]
How to run the library when application is in background state. I've tried to run it with certain background library, whenever application goes in background at that I'm unable to get any out in logs. So if there any solution regarding this please let me know.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You have provided no information from the issue template and no logs.

this is not optional, it’s required,

> Plugin version:
Platform: iOS or Android
OS version:
Device manufacturer / model:
React Native version (react-native -v):
Plugin config
