### ISSUE TITLE
Library installed working on Foreground, Not working on background

### ISSUE THREAD

**Issue by premadinfotech** [transistorsoft/react-native-background-geolocation#1529]
No Warning is shown

The library is installed successfully in my app and I am getting geolocation coordinates on the Foreground state. But when I take my application on background then nothing is displayed...no warning and even no coordinates.
## Your Environment
* Plugin version: 3.2.0 
* Platform: Android
* OS version: 11
* Device manufacturer / model: Redmi Note 11 
* React Native version (`react-native -v`): 0.64.1
* Plugin config: demo version

Integrated same as mentioned in the doc. Please suggest/help us to resolve this issue.

**Comment by christocracy** [comment]
You have not provided the plugin Config you’re using, as requested in the issue template.

Nor have you provided any logs.  See wiki *Debugging* to learn how to observe plugin logs in `adb logcat`

**Comment by christocracy** [comment]
Show logs of your app booting then moving to background.

**Comment by premadinfotech** [comment]
Hello,

[image: WhatsApp Image 2022-08-29 at 5.13.14 PM.jpeg]
PFA


----------------------------------
Lokesh Garg
Senior Software Developer
Premad Software Solution Pvt Ltd
+91-7210797932
*www.premad.in <http://www.premad.in>*

**Comment by christocracy** [comment]
Don’t post images of logs, post *text*

**Comment by premadinfotech** [comment]
I have followed the same way to register headlessJs service in android.

Used this link:
***@***.***/introduction-to-react-natives-headless-js-90e87dee0ab4

then I try to put your code ***@***.*** library) but still not executing
anything or calling anything in the background.

I am getting perfect data in the foreground.

Kindly help us. We are stuck in this part and no solution is applying.


----------------------------------
Lokesh Garg
Senior Software Developer
Premad Software Solution Pvt Ltd
+91-7210797932
*www.premad.in <http://www.premad.in>*

**Comment by christocracy** [comment]
See wiki *Debugging* and learn to fetch logs from the plugin using `.emailLog(yourEmail)` method.

**Comment by christocracy** [comment]
>Plugin version: 3.2.0

The latest version of the plugin is [4.8.2](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md)

[3.2.0 is over three years old](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#320---2019-08-16), from before *Android 11* even existed.
