### ISSUE TITLE
Still Showing Licence Validation Failure after purchasing key

### ISSUE THREAD

**Issue by premadinfotech** [transistorsoft/react-native-background-geolocation#1531]
We have put the key in manifest.xml and when we run the app then it is showing LICENCE VALIDATION FAILURE. Why ? Please help us. Its urgent.

**Comment by premadinfotech** [comment]
Fixed

**Comment by christocracy** [comment]
In the future, don’t ignore the issue template.

You are unlikely to get support when you do that
