### ISSUE TITLE
Unable to create release build

### ISSUE THREAD

**Issue by premadinfotech** [transistorsoft/react-native-background-geolocation#1533]
We have purchased your library and when we put it in manifest.xml and try to create the release build then it is showing error. Unable to create release build. You can check the attached image for the error. 

Kindly suggest us.

![WhatsApp Image 2022-08-30 at 11 56 11 AM](https://user-images.githubusercontent.com/65611735/187382074-27572d2c-f084-43a4-b4e6-ca0527e2a9aa.jpeg)

## Your Environment
* Plugin version: 3.2.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: IQOO (Vivo)
* React Native version (`react-native -v`): 0.64.1
* Plugin config

## Expected Behavior
Should not have any issue while creating release build

## Actual Behavior
getting error while creating release build

## Steps to Reproduce
1) Integrated your library
2) Put the Licence Key in manifest.xml under the section of application tag in meta data

**Comment by christocracy** [comment]
> Plugin version: 3.2.0

Version 3.2.0 is over 3 years old.  It is incompatible with newer gradle versions.

upgrade to latest 4.8.1

**Comment by christocracy** [comment]
See the changelog
