### ISSUE TITLE
Android 13 - Notification permission requested on boot

### ISSUE THREAD

**Issue by JorenVos** [transistorsoft/react-native-background-geolocation#1534]
After adding the `react-native-background-geolocation` package to our project, the user has to grant permission on boot. You don't have to call any functionality, just installing the package is enough to encounter this issue.

## Your Environment
* Plugin version: 4.8.2
* Platform: Android
* OS version: 13
* Device manufacturer / model: Google Pixel 6a
* React Native version: 0.64.2
* Plugin config: _Not important, installing library is enough to encounter this issue_

## Expected Behavior
When booting an application on Android 13 that has `react-native-background-geolocation` installed, users will see the native notification permission request. In our code, no interaction with any RN Background Geolocation-functionality is done. It should not be requested on boot without any RN Background Geolocation-interaction.

## Actual Behavior
The library should not request notification permission

## Steps to Reproduce
1. Add the library to your project
2. Boot the app
3. (Eventually, kill and boot again)
4. Notification permission is requested

**Comment by christocracy** [comment]
I have not yet tested in Android 13

**Comment by JorenVos** [comment]
This is a UX-blocker for us in production, it's not the way we want to request permissions from our users. Is it possible to get yourself an Android 13 device and test/reproduce/fix this issue?

**Comment by christocracy** [comment]
I’ll be installing Android 13 soon.

**Comment by christocracy** [comment]
After a fresh install of Android 13 on my Pixel 6, I don’t notice anything unusual and the demo app operates exactly as before.

I will try now with a fresh install of demo app.

**Comment by christocracy** [comment]
After fresh install of demo app on Android 13, terminate app, reboot app:  I don't see anything about a "*Notification permission requested*".

I'm using:
```gradle
    compileSdkVersion   = 33
    targetSdkVersion    = 33
```

**Comment by JorenVos** [comment]
I did a fresh install of the app from the Play Store and the first thing I see is: Notification permission request.

It's in Dutch, but it's really strange that you don't see the notification popup.

https://user-images.githubusercontent.com/10380088/187535210-997861d0-bcce-4aed-9572-f55e5f11e4ec.mp4

**Comment by christocracy** [comment]
Create for me simple *Hello World* app which reproduces this for me.  Share it in a public GitHub repo.

**Comment by JorenVos** [comment]
Followed the setup instructions to add the library to a clean project. Same behavior happens after a restart of the app.

[SampleProject.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/9459894/SampleProject.zip)

https://user-images.githubusercontent.com/10380088/187632169-7a18b8ab-44bf-4c24-b6ce-565010d3dc12.mp4

**Comment by christocracy** [comment]
> When setting compileSdkVersion and targetSdkVersion to 33, the problem is indeed resolved.

Correct.  This is what you have to do.  See [Notification Permission Exemptions](https://developer.android.com/develop/ui/views/notifications/notification-permission#exemptions):

<img width="960" alt="Screen Shot 2022-08-31 at 9 50 44 AM" src="https://user-images.githubusercontent.com/14999/187695065-a218a6d9-f9d8-4204-a97e-c2e6ab9454ee.png">

I *am* using `targetSdkVersion 33 / compileSdkVersion 33` locally here.  This is why I didn't see the runtime permission.  When I downgrade to `targetSdkVersion 31`, I do experience the behaviour you describe.

**Comment by christocracy** [comment]
Also  see the [*Best Practices*](https://developer.android.com/develop/ui/views/notifications/notification-permission#best-practices) section:  *Updates your app's target SDK version*

<img width="954" alt="Screen Shot 2022-08-31 at 10 06 24 AM" src="https://user-images.githubusercontent.com/14999/187698733-8a396a96-5ed6-46fe-828d-74e4811c99e5.png">

**Comment by JorenVos** [comment]
In my opinion, it still needs a fix. `react-native-background-geolocation` should not ask for notification permissions because these are only used for debugging purposes. Everyone who's using this package and has not updated their `targetSdkVersion` or `compileSdkVersion` will have to deal with the notification permission package. 

It might be useful to create the notification channels only when debugging is on. Otherwise, everyone will have a notification channel for debugging this library, even end-users who will never see notifications from `react-native-background-geolocation`.

**Comment by christocracy** [comment]
>should not ask for notification permissions because these are only used for debugging purposes

No.  This is **not** for debugging purposes, at all.  This is the [*Required Persistent Notification for Foreground Services*](https://developer.android.com/guide/components/foreground-services). 

<img width="946" alt="Screen Shot 2022-08-31 at 11 14 15 AM" src="https://user-images.githubusercontent.com/14999/187714549-813ed81d-92a8-452f-ac15-ae309aa8afb7.png">

The Android plugin does *not* use notifications for debugging.

**Comment by JorenVos** [comment]
It should not request the permission **before** a `config` or `init` of the library is called. The fact that this library can cause a permission request on boot is unwanted.

**Comment by christocracy** [comment]
It's wrong in the first place for Android 13 to request run-time permission for foreground-services &mdash; `targetSdkVersion 33` fixes that wrong.
