### ISSUE TITLE
Background Location API Hits on Server ??

### ISSUE THREAD

**Issue by premadinfotech** [transistorsoft/react-native-background-geolocation#1536]
Can you please let me know how many APIs hit if our application move in a car? I want to know this because the API is hit so constantly and all our resources on the server are exhausted. API is hitting like 3000 times in just 1 KM.

## Your Environment
* Plugin version: 3.10.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Vivo (IQOO Z5)
* React Native version (`react-native -v`): 0.64.1
* Plugin config

## Context
Regarding server API hits

**Comment by christocracy** [comment]
> Plugin config

How can I know?  You’ve not provided the Config you’re using.

**Comment by premadinfotech** [comment]
**Config:**

`BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: true, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      enableHeadless: true,
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title:
          'AapniTaxi Driver wants to access of device location permission in the background?',
        message:
          "In order to access location in the background, please enable 'Allow all the time' permission",
        positiveAction: 'Change to Allow all the time',
        negativeAction: 'Cancel',
      },
    });`

**Comment by christocracy** [comment]
Please learn to [syntax highlight multi line code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by premadinfotech** [comment]
> Please learn to [syntax highlight multi line code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

Sorry for sending the message in a hurry. 

````
```
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: true, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      enableHeadless: true,
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title:
          'AapniTaxi Driver wants to access of device location permission in the background?',
        message:
          "In order to access location in the background, please enable 'Allow all the time' permission",
        positiveAction: 'Change to Allow all the time',
        negativeAction: 'Cancel',
      },
    });
```
````

**Comment by christocracy** [comment]
You can **EDIT** existing messages instead of polluting the thread with **bunch of extra noise**.

<img width="924" alt="Screen Shot 2022-08-30 at 3 08 54 PM" src="https://user-images.githubusercontent.com/14999/187522928-22c39694-7746-445d-a988-1c547b19a9f5.png">

**Comment by christocracy** [comment]
> distanceFilter: 10

The rate that locations are recorded is controlled by `distanceFilter`.  Increase it to record fewer locations.

- See API docs "*HTTP Guide*".
- See API docs `Config.batchSync`
- See API docs `Config.autoSyncThreshold`.
