### ISSUE TITLE
Can background fetch plugin improve geofence trigger ?

### ISSUE THREAD

**Issue by iamshengfu** [transistorsoft/react-native-background-geolocation#1537]
## Your Environment
* Plugin version:    "react-native-background-geolocation": "4.4.6","react-native-background-fetch": "4.0.5",
    
* Platform: Android
* OS version: Android 12
* Device manufacturer / model: Samsung Galaxy A42 5G (SM-A4260)
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onGeofence(...)

BackgroundGeolocation.ready({
    geofenceModeHighAccuracy: true,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    fastestLocationUpdateInterval: 1000,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    disableLocationAuthorizationAlert: true,
    disableMotionActivityUpdates: true, 
    stopOnTerminate: false, 
    startOnBoot: true, 
    enableHeadless: true,
});


BackgroundFetch.configure(
    {
      minimumFetchInterval: 15,
      stopOnTerminate: false,
      startOnBoot: true,
      forceAlarmManager: true,
      enableHeadless: true,
    },
    (taskId) => onGeofenceHeartbeatEventHandle(taskId),
    (taskId) => onGeofenceHeartbeatTimeoutHandle(taskId),
);



function registerHeadlessTask() {
  BackgroundGeolocation.registerHeadlessTask(geolocationHeadlessTask);
  BackgroundFetch.registerHeadlessTask(heartBeatHeadlessTask);
}


File: index.js
AppRegistry.registerComponent(appName, () => App);
registerHeadlessTask();

inside App.js after user provided permissions
call BackgroundGeolocation.onGeofence(), ready() and start(), BackgroundFetch.configure()
```

## Expected Behavior

background fetch plugin can wake the App periodically to in case OS kill the App, and Geofence event should trigger more consistently after using the background fetch plug in.
## Actual Behavior

Geofence event sometimes did not trigger. It appears that geofence event happen shortly (1-2 mins) after the background fetch event can trigger, but if user traveled through a Geofence about 10 minutes after the background fetch task, it could miss. User still can trigger geofence again later on. 
Suspect that the OS killed the App in between background fetches.
## Steps to Reproduce

drive across geofences

## Context

I was hoping to imporve the Geofence trigger consistency and prevent OS kill App by using the background fetch plugin to get location in background regularly.

## Debug logs

Unfortunately I was not aware of the SDK send log feature during field testing. We were using firebase to log those events.

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
The background fetch was triggered at 21:12
The geofence event happened at 21:13 and 21:14 can be recorded
But the  geofence event happened at 21:19 and 21:21 was missing, while we can find these 2  geofence event in iOS device travelling together.
The next background fetch is at 21:27
Then the geofence event happened at 21:29 can be recorded again
```

</details>

**Comment by christocracy** [comment]
>Can background fetch plugin improve geofence trigger

I doubt it.  But there's certainly no harm in implementing `background-fetch` anyway.
