### ISSUE TITLE
TSBackgroundFetch/TSBackgroundFetch.h is not found, but only in release 

### ISSUE THREAD

**Issue by bmmanson** [transistorsoft/react-native-background-geolocation#154]
The framework works when in xCode I go to Scheme >> Edit Scheme and have the build configuration set to debug. But when it's set to release and I attempt a build, the build fails and I get the error "TSBackgroundFetch/TSBackgroundFetch.h is not found". I installed background fetch manually. How can I fix this?

**Comment by christocracy** [comment]
I just tried the same with the [demo app](https://github.com/transistorsoft/rn-background-geolocation-demo) and had no issues.

What version of `react-native-background-geolocation` are you using?

**Comment by bmmanson** [comment]
1.5.0

**Comment by christocracy** [comment]
Walk through the [installation instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md) and verify everything.

In particular, make sure you've set **Framework Search Paths** for *both* **Debug** and **Release**.
![](https://www.dropbox.com/s/gcfwu5dzsjrctou/Screenshot%202016-10-28%2010.00.50.png?dl=1)

**Comment by bmmanson** [comment]
Hmm, ok. One problem is that there isn't a TSBackgroundFetch.framework the react-native-background-fetch folder in my node modules folder. However, inside react-native-background-geolocation, there is a node-modules folder, and it contains TSBackgroundFetch.framework. Is this expected?

**Comment by bmmanson** [comment]
Nevermind, unrelated problem. Thanks for the quick reply!
