### ISSUE TITLE
Not getting location update in background and killed mode (android 12)

### ISSUE THREAD

**Issue by vandana87** [transistorsoft/react-native-background-geolocation#1542]
## Your Environment
* Plugin version:4.0.0
* Platform:  Android
* Android version:12
* Device manufacturer / model:
* React Native version (`react-native -v`):0.63.4
* Plugin config

## Actual Behavior

</details>

**Comment by christocracy** [comment]
The Config you’re providing to the .ready method, which the issue template asked you to provide, is highly relevant.

also see wiki “*Debugging*”.
