### ISSUE TITLE
Random location objects are fetched from GPS library

### ISSUE THREAD

**Issue by techteamPA** [transistorsoft/react-native-background-geolocation#1545]
## Your Environment
* Plugin version: 4.7.1
* Platform: iOS or Android
* OS version: 16
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`): 0.66.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter:
          radStatusId == 1
            ? normalGPSConfig != undefined &&
              normalGPSConfig.hasOwnProperty('minmeters')
              ? normalGPSConfig.minmeters
              : 50
            : liveGPSConfig != undefined &&
              liveGPSConfig.hasOwnProperty('minmeters')
            ? liveGPSConfig.minmeters
            : 20,
        // Activity Recognition
        stopTimeout: 5,
        // Permissions
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          title:
            "Allow {applicationName} to access this device's location even when closed or not in use.",
          message:
            'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
          positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
          negativeAction: 'Cancel',
        },
        disableMotionActivityUpdates: false,
        disableElasticity: true,
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true,
        enableHeadless: true, // <-- Auto start tracking when device is powered-up.
        url: COORD2,
        autoSync: true,
        batchSync: true,
        maxBatchSize: 5,
        headers: {
          Accept: 'application/json',
        },
        params: {
          apikey: API_KEY,
          appvers: user.version,
          client: clientID,
          bookingID: bookingApiData[0].bookingData.bookingID,
          mo: radStatusId == undefined ? 1 : radStatusId,
          tz: new Date().getTimezoneOffset(),
        },
        extras: {
          mo: radStatusId == undefined ? 1 : radStatusId,
        },
        locationsOrderDirection: 'DESC',
        maxDaysToPersist: 14,
      })
        .then(state => {
          setEnabled(true);

          console.log(
            '- BackgroundGeolocation is configured and ready: ',
            state,
          );
        })
        .catch(error => {
          console.warn('- BackgroundGeolocation error: ', error);
        });
```

## Expected Behavior
No random location object to be logged apart from the route taken

## Actual Behavior
It has been observed that sometime a random location object fetched from gps and that same object has been stored on server.  Details are as follows:

The long distance filed testing has been performed and library does fetched the location at desired interval but there was few random location which are totally away from the route taken. The file has been attached for your reference. It cleary shows that Pin 247, 257, 319 are quite far from actual location. Similarly, there are few duplicate location object for PIN number 246 & 247 with a long difference and then again it starts fetching the proper values.

Could please share your thoughts and guide us about the different reasons this could have happened.
Similarly, what can be done to fix this kind of issues.

## Steps to Reproduce

1. Travel for long route with some in between halts.

## Context

We are trying to get all the route logs on map while traveling from one location to another with some halts. 

## Debug logs

<details><summary>Please find attached screenshot of the map with all the route logs. </summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
![Screenshot 2022-09-12 at 5 54 57 PM](https://user-images.githubusercontent.com/107607360/189688437-16c365a6-6873-47de-9fb0-cd291c85fc8c.png)

</details>

**Comment by christocracy** [comment]
You are expected to filter you data as desired.

see location.coords.accuracy

**Comment by techteamPA** [comment]
Could you let us know what is the accuracy level range to get accurate location. 
like is eg below 
["coords"]: {
"speed_accuracy": -1,
"speed": -1,
"longitude": 72.91782172503153,
"floor": null,
"heading_accuracy": -1,
"latitude": 19.110456594879363,
"accuracy": 44,
"altitude_accuracy": 15.3,
"altitude": 38.1,
"heading": -1
},
here we got accuracy as 44 so what should be the value/range to identify accurate location for mapping.

**Comment by christocracy** [comment]
A geolocation is not a simple point in space.

it is a circle of radius `accuracy`.

when location comes from gps, the accuracy is typically 5-10 meters.  GPS works only outdoors with an unobstructed view of the sky.

from wifi (Eg: while indoors), typically 40-100 meters.

from cellular, 1000+ meters.

**Comment by christocracy** [comment]
>but, isn't it an oblate spheroid, when you also consider altitude and altitude accuracy?

Yes, it's actually 3 dimensional.  In most cases, people aren't concerned with `altitude`.

**Comment by kulbir22** [comment]
Hi @christocracy , I have purchased your API and I have 2 queries.
1. I have successfully configured "enableHeadless", now even when I terminate my app locations are still being fetched. But, once the app enters "STATIONARY_STATE" after 5 minutes, the app resumes fetching location only after I have travelled somewhere between 1-2 Km(s). Battery optimisation is disabled for my One Plus 6 device.

2. How can I send only those locations to my server whose accuracy is less than 40 meters ?

`
this.subscriptions.push(BackgroundGeolocation.onConnectivityChange((event) => {
            console.log("[onConnectivityChange] ", event, Toast);
            if(event.connected){
                //alert('You are connected to internet')
                Toast.show({
                    type: 'success',
                    text1: 'You are connected to internet'
                })
            }else{
                Toast.show({
                    type: 'error',
                    text1: 'No internet connectivity'
                })
            }
        }))

        this.subscriptions.push(BackgroundGeolocation.onLocation(async(location) => {
            // BackgroundGeolocation.logger.emailLog('xeam.kulbir@gmail.com').then((success) => {
            //     console.log('[emailLog] SUCCESS', success);
            // }).catch((error) => {
            //     console.log('[emailLog] ERROR: ', error);
            // });
            BackgroundGeolocation.logger.getLog().then((log) => {
                // Warning:  this string could be several megabytes.
                console.log("[log] success: ", log);
            });
            console.log('[onLocation]', location);
            this.setState({location, distance: (location.odometer/1000).toFixed(2)})
            this.props.storeCoordinates(location);
            //alert(`Latitude: ${location.coords.latitude}\nLongitude: ${location.coords.longitude}`)
        }, (error) => {
            console.log('[onLocation] ERROR:', error);
        }))
    
        this.subscriptions.push(BackgroundGeolocation.onMotionChange((event) => {
            console.log('[onMotionChange]', event);
        }))
    
        this.subscriptions.push(BackgroundGeolocation.onActivityChange((event) => {
            //console.log('[onActivityChange]', event);
        }))
    
        this.subscriptions.push(BackgroundGeolocation.onHeartbeat((event) => {
            console.log('[onHeartbeat]', event);
        }))

        this.subscriptions.push(BackgroundGeolocation.onEnabledChange(isEnabled => {
            //console.log("[onEnabledChanged] isEnabled? ", isEnabled);
            this.setState({enabled: isEnabled});
        }));

        this.subscriptions.push(BackgroundGeolocation.onHttp(response => {
            try{
                const parsedData = JSON.parse(response.responseText);
                console.log("[http] response: ", response.success, response.status, response.responseText);
                if(response.success){
                    //alert(parsedData.status);
                    console.warn(parsedData.status);
                    //alert('Success');
                }else{
                    if(parsedData.hasOwnProperty("validation_error")){
                        let message = '';
                        const errorKeys = Object.keys(parsedData.validation_error);
                        errorKeys.forEach((item, index) => {
                            message += `- ${parsedData.validation_error[item]}${(index < (errorKeys.length - 1))? "\n" : ''}`
                        })
                        //Alert.alert("Validation Error", message)
                        console.warn("Validation Error", message)
                    }else{
                        alert(parsedData.status)
                    }
                }
            }catch(error){
                console.log(error);
            }
        }));

        BackgroundGeolocation.removeGeofences();

        const currentDate = moment().format("YYYY-MM-DD-HH:mm");
        //const nextDate = `${moment().add(propValues.schedulerMinutes, 'minutes').format("YYYY-MM-DD-HH:mm")}`;
        const nextDate = `${moment().format("YYYY-MM-DD")}-${propValues.schedulerEndTime}`;
        console.log('^^^ CURRENT DATE-TIME ^^^ ', `${currentDate} ${nextDate}`);
        
        BackgroundGeolocation.ready({
            // Geolocation Config
            locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"distance":<%= odometer %>}',
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            locationAuthorizationRequest: 'Always',
            foregroundService: true,
            geofenceProximityRadius: 10,
            backgroundPermissionRationale: {
                message: "This app collects location data to enable recording your trips to work and calculate distance-travelled."
            },
            fastestLocationUpdateInterval: 5000,
            distanceFilter: 25,
            stationaryRadius: 25,
            desiredOdometerAccuracy: 30,
            stopOnStationary: false,
            persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
            preventSuspend: true,
            debug: debug, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            enableHeadless: true,
            stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
            // HTTP / SQLite config
            httpTimeout: 5000,
            method: "POST",
            url: `${baseURL}/travel-coordinates/store`,
            batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.,
            autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
            autoSyncThreshold: 5,
            headers: {              // <-- Optional HTTP headers
                "Authorization": `Bearer ${secretToken}`
            },
            params: {
                coordinates: JSON.stringify(coordinates)
            }
        }).then(({enabled, params, locationTemplate, schedulerEnabled }) => {
            this.setState({enabled}, async() => {
                const { enabled } = this.state;
                if(enabled){
                    // BackgroundGeolocation.changePace(false);
                    // BackgroundGeolocation.stop();
                    // BackgroundGeolocation.resetOdometer().then((location) => {
                    //     // This is the location where odometer was set at.
                    //     console.log("[setOdometer] success: ", location);
                    // });
                    // await BackgroundGeolocation.stopSchedule();
                    // await BackgroundGeolocation.startSchedule();
                }else{
                    BackgroundGeolocation.start().then((response) => {
                        console.log("### [state] ", response.isMoving);
                        if(!response.isMoving){
                            BackgroundGeolocation.changePace(true);
                        }
                    });
                    // console.log("- BackgroundGeolocation is configured and ready: ", enabled, params, locationTemplate, schedulerEnabled);
                    // BackgroundGeolocation.startSchedule().then((state) => {
                    //     console.log("@@@ START SCHEDULER: ", state.enabled, state.isMoving)
                    //     if(!state.isMoving && state.enabled){
                    //         BackgroundGeolocation.changePace(true);
                    //     }
                    // });
                }
            });
        })
`

**Comment by kulbir22** [comment]
> You are expected to filter you data as desired.
> 
> see location.coords.accuracy

@christocracy 
Even I'm also getting random location objects. 
I just wanted to know by filtering `location.coords.accuracy`, do you mean to filter via accuracy at my server end after completing the `http` request or to filter before the location object being pushed to the server via `http` request ???

**Comment by christocracy** [comment]
> do you mean to filter via accuracy at my server

yes

**Comment by kulbir22** [comment]
> > do you mean to filter via accuracy at my server
> 
> yes

Is there a way we could filter via accuracy first and then decide if we want to `POST` specific `coords` to the server ?

**Comment by christocracy** [comment]
There is an undocumented way to do this in the Native code in the iOS `AppDelegate` and Android `MainApplication` file:

### `MainApplication.java`

```java
import com.transistorsoft.locationmanager.adapter.BackgroundGeolocation;


public class MainApplication extends Application implements ReactApplication {
    @Override
    public void onCreate() {
        .
        .
        .
        // Adding a custom beforeInsertBlock.  If your callback returns null, the insert into the plugin's SQLite db
        // will be cancelled.  If there is no record inserted into SQLite, there will be no HTTP request.

        BackgroundGeolocation.getInstance(this).setBeforeInsertBlock(new TSBeforeInsertBlock() {
            @Override
            public JSONObject onBeforeInsert(TSLocation tsLocation) {
                boolean doInsert = true;
                //
                // Your logic here
                //
                // For example, you could do something like this:
                //
                // Location location = tsLocation.getLocation();
                // if (location.getAccuracy() >= 10) {
                //     doInsert = false;
                // }
                //
                return (doInsert) ? tsLocation.toJson() : null;
            }
        });
    }
}

```

### `AppDelegate.m`

```Obj-c

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {    
    .
    .
    .
    /**
     * Undocumented feature:  This is a native hook for each location recorded by background-geolocation.
     * Return null to cancel the SQLite insert (and corresponding HTTP request)
     */
    TSLocationManager *bgGeo = [TSLocationManager sharedInstance];
        
    bgGeo.beforeInsertBlock = ^NSDictionary* (TSLocation *location) {
        NSLog(@"[BackgroundGeolocation] beforeInsertBlock: %@", location);
        BOOL doInsert = YES;
        //
        // Your logic here
        //
        return (doInsert) ? [location toDictionary] : nil;
    };
    .
    .
    .
    return YES;
}
```

**Comment by kulbir22** [comment]
> ```java
> return (doInsert) ? tsLocation.toJson() : null;
> ```

This would serve my purpose, but now this sends entire json block to the SQLite database. I've managed to pulled out the required details:
```
Location location = tsLocation.getLocation();
           JSONObject json = new JSONObject();
           try {
               json.put("latitude", location.getLatitude());
               json.put("longitude", location.getLongitude());
               json.put("accuracy", location.getAccuracy());
               json.put("timestamp", tsLocation.getTimestamp());
               json.put("uuid", tsLocation.getUUID());
               //json.put("distance", tsLocation.);
           } catch (JSONException e) {
               e.printStackTrace();
           }
```
But, I am not sure how to get distance ?

**Comment by christocracy** [comment]
tsLocation.odometer

**Comment by kulbir22** [comment]
> tsLocation.getOdometer()

I've tried but it says `Cannot resolve method 'getOdometer' in 'TSLocation'`

**Comment by christocracy** [comment]
Hmm...seems I forgot to implement a public `getOdometer()` for that one.

You can get it from `TSConfig`

```java
TSConfig config = TSConfig.getInstance(context);
float odometer = config.getOdometer();
```

**Comment by kulbir22** [comment]
> ```java
> public class MainApplication extends Application implements ReactApplication {
>     @Override
>     public void onCreate() {
>         .
>         .
>         .
>         // 1.  Get TSConfig instance here.
>         final TSConfig config = TSConfig.getInstance(this);
> 
>         // Adding a custom beforeInsertBlock.  If your callback returns null, the insert into the plugin's SQLite db
>         // will be cancelled.  If there is no record inserted into SQLite, there will be no HTTP request.
> 
>         BackgroundGeolocation.getInstance(this).setBeforeInsertBlock(new TSBeforeInsertBlock() {
>             @Override
>             public JSONObject onBeforeInsert(TSLocation tsLocation) {
>                 boolean doInsert = true;
>                 
>                 // 2.  Fetch odometer here.
>                 float odometer = config.getOdometer();
>                 
>                 return (doInsert) ? tsLocation.toJson() : null;
>             }
>         });
>     }
> }
> ```

Thanks a million. It worked like a charm. You are a life saviour.

**Comment by kulbir22** [comment]
@christocracy 
I'm witnessing a weird behaviour in the app. At times, the coordinates that are fetched as soon as the tracking starts are being sent to the server later. Could you please advise how do I fix this ?

```
"data": [
        {
            "id": 503130,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "23658.31",                       `<---------`
            "latitude": "25.9752697",
            "longitude": "76.2905266",
            "created_at": "2022-10-13T04:18:10.000000Z",
            "updated_at": "2022-10-13T04:18:10.000000Z"
        },
        {
            "id": 503131,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "23761.05",                       `<---------`
            "latitude": "25.9747661",
            "longitude": "76.2896651",
            "created_at": "2022-10-13T04:18:11.000000Z",
            "updated_at": "2022-10-13T04:18:11.000000Z"
        },
        .
        .
        .
        {
            "id": 503171,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "0.00",                                    // Inital Distance                       `<---------`       
            "latitude": "26.1701599",                         // Initial Location
            "longitude": "75.8027222",                     // Initial Location
            "created_at": "2022-10-13T04:19:11.000000Z",
            "updated_at": "2022-10-13T04:19:11.000000Z"
        },
        {
            "id": 504223,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "58.75",                       `<---------`
            "latitude": "26.1702232",
            "longitude": "75.8021934",
            "created_at": "2022-10-13T04:51:22.000000Z",
            "updated_at": "2022-10-13T04:51:22.000000Z"
        },
        {
            "id": 504225,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "109.46",                       `<---------`
            "latitude": "26.170285",
            "longitude": "75.8017067",
            "created_at": "2022-10-13T04:51:23.000000Z",
            "updated_at": "2022-10-13T04:51:23.000000Z"
        },
        {
            "id": 504226,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "7788.86",                       `<---------`
            "latitude": "26.118111",
            "longitude": "75.7511468",
            "created_at": "2022-10-13T04:51:23.000000Z",
            "updated_at": "2022-10-13T04:51:23.000000Z"
        },
        {
            "id": 504227,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "7930.94",                       `<---------`
            "latitude": "26.1170485",
            "longitude": "75.7503513",
            "created_at": "2022-10-13T04:51:24.000000Z",
            "updated_at": "2022-10-13T04:51:24.000000Z"
        }
              ]
```
