### ISSUE TITLE
background geolocation httpevent.success shows  false, and httpEvent.status shows 0 on ios

### ISSUE THREAD

**Issue by bilal-prog** [transistorsoft/react-native-background-geolocation#1548]
"react-native-background-geolocation": "^4.8.2",

**Comment by christocracy** [comment]
You don’t have a network connection.

**Comment by christocracy** [comment]
Also, you ignored the issue template, which asked you to provide your Config, among a bunch of other information.

**Comment by bilal-prog** [comment]
Okay I will check the network connection

**Comment by bilal-prog** [comment]
thanks for answering me @christocracy ,the ios has connection ,ma bad for ignoring the template i just purchase a licence this plugin didn't work on ios as expected

**Comment by christocracy** [comment]
I suggest you install the SampleApp, linked in the readme.

this is not a plugin issue.  It’s an issue on your device.

**Comment by bilal-prog** [comment]
ma bad ,i will delete the issue ,but please is this config ok for bg tracking i'm doing an a uber like so app for tracking the driver on the client app ,thanks in advance:
import storage from 'lib/storage';
import BackgroundGeolocation from 'react-native-background-geolocation';
import displayToast from 'lib/interactions';
import CONFIG from 'config/api';
import configureStore from '../store';
import {emitEvent} from 'services/socket';
const {store} = configureStore();

const {BASE_URL} = CONFIG;

export default class TrackingService {
  trackingInstance;

  constructor(socket) {
    //send localisation for the first time

    //init tracking to be ready to send coords on start() methode
    this.initTracking();
  }
  initTracking = () => {
    try {
      //loging the http respence
      BackgroundGeolocation.onHttp((httpEvent) => {
        console.log(
          '[httpsssss] ',
          httpEvent.success + ' / ' + httpEvent.status,
        );
      });
      //to get the cookie
      storage.getSession().then((cookie) => {
        console.log('fffffffffffffffff:', cookie);
        //The following configuration options are used to configure the BgTracking  SDK
        BackgroundGeolocation.ready({
          //The minimum distance (measured in meters) a device must move horizontally before an update event is generated.
          distanceFilter: 10,
          //disable automatic speed-based distanceFilter elasticity. eg: When device is moving at highway speeds, locations are returned at ~ 1 / km.
          disableElasticity: true,
          //indicating whether the status bar changes its appearance when an app uses location services in the background with Always authorization.
          showsBackgroundLocationIndicator: true,
          //The Android plugin will ignore a received location when it is identical to the last location. Set true to override this behaviour and record every location, regardless if it is identical to the last location.
          allowIdenticalLocations: true,
          //The number of minutes to wait before turning off location-services after the ActivityRecognition System (ARS) detects the device is STILL
          stopTimeout: 5,
          //Set false to continue tracking after user terminates the app.
          stopOnTerminate: false,
          //Set to true to enable background-tracking after the device reboots.
          startOnBoot: true,
          //Default: 60. Rate in seconds to fire BackgroundGeolocation.onHeartbeat events.
          //heartbeatInterval: 60,
          //Enable this to prevent iOS from suspending your app in the background while in the stationary state. Must be used in conjunction with a heartbeatInterval.
          preventSuspend: true,
          //Set true to make the plugin mostly immune to OS termination due to memory pressure from other apps.
          foregroundService: true,
          // Set to true to enable "Headless" mode when the user terminates the application. In this mode, you can respond to all the plugin's events in the native Android environment. For more information, see the wiki for Android Headless Mode
          //  enableHeadless: true,
          //TODO notification	Notification	Configures the required persistent Notification of the foreground service.

          //TODO Default: false. When enabled, the plugin will emit sounds & notifications for life-cycle events of background-geolocation
          debug: true,
          logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
          //IOS ACTIVITY TYPE
          activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
          //PERMISSION messages
          locationAuthorizationRequest: 'Always',
          backgroundPermissionRationale: {
            title:
              'Autoriser COSMIND DELIVERY à accéder à la position de cet appareil en arrière-plan ?',
            message:
              'Afin de suivre votre activité en arrière-plan, veuillez activer {backgroundPermissionOptionLabel} autorisation de localisation',
            positiveAction: 'Passer à {backgroundPermissionOptionLabel}',
            negativeAction: 'Annuler',
          },
          //When you configure the plugin locationAuthorizationRequest Always or WhenInUse and the user changes the mode in the app's location-services settings or disabled location-services, the plugin will display an Alert dialog directing the user to the Settings screen. locationAuthorizationAlert allows you to configure all the Strings for that Alert popup and accepts an {} containing the following keys:
          locationAuthorizationAlert: {
            titleWhenNotEnabled:
              'les services de localisation ne sont pas activés',
            titleWhenOff: 'services de localisation désactivés',
            instructions:
              "Vous devez activer 'Toujours' dans les services de localisation",
            cancelButton: 'Annuler',
            settingsButton: 'Réglages',
          },
          //Specify the desired-accuracy of the geolocation system. NOTE : Only DESIRED_ACCURACY_HIGH uses GPS. speed, heading and altitude are available only from GPS.
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          //Defaults to false. Set true to disable automatic, speed-based distanceFilter auto-scaling. By default, the SDK automatically increases distanceFilter as speed increases (and decreases it as speed decreases) in order to record fewer locations and conserve energy.
          disableElasticity: true,
          //Controls the rate (in seconds) the BackgroundGeolocation.onHeartbeat event will fire.
          //  heartbeatInterval: 60,
          //android===> to be able to trigger the notifs
          notification: {
            title: 'Localisation en background',
            text: 'Cliquez pour ouvrir',
          },
          // stopOnStationary: true,
          url: `
          https://dev.api.cosmind.co/api/v1/livreurs/me/location`,
          autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
          //AUTHORISATION HEADER with cookie
          // headers: {
          //   Accept: 'application/json',
          //   'Content-Type': 'application/json',
          //   cookie: cookie,
          // },
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
            Authorization: 'Bearer ' + cookie,
          },

          //AUTHORISATION HEADER with token
        }).then((state) => {
          console.log(
            '[ready] BackgroundGeolocation is configured and ready to use',
            state?.enabled,
          );
          BackgroundGeolocation.start().then((res) => {
            console.log('@@@@the start  methode : ', res);
          });
        });
      });
    } catch (err) {
      displayToast('TRACKING ERROR : ' + err || '');
      console.log('TRACKING Ready  ERR : ', err);
    }
  };
  // static stop = () => {
  //   try {
  //     BackgroundGeolocation.stop().then((res) => {
  //       console.log('@@@@the stop methode : ', res);
  //     });
  //   } catch (err) {
  //     displayToast('TRACKING NOT STOPING : ' + err || '');
  //     console.log('TRACKING STOP ERR : ', err);
  //   }
  // };
  // static start = () => {
  //   try {
  //     BackgroundGeolocation.start().then((res) => {
  //       console.log('@@@@the start  methode : ', res);
  //     });
  //   } catch (err) {
  //     displayToast('TRACKING NOT STARTING : ' + err || '');
  //     console.log('TRACKING start  ERR : ', err);
  //   }
  // };
  static getInstance = () => {
    if (!this.trackingInstance) {
      this.trackingInstance = new TrackingService();
    }
    return this.trackingInstance;
  };
}





# i use the getInstance() in my useeffect in the  tracking map view

**Comment by christocracy** [comment]
Please learn to [syntax highlight codeblocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by bilal-prog** [comment]
```


import storage from 'lib/storage';
import BackgroundGeolocation from 'react-native-background-geolocation';
import displayToast from 'lib/interactions';
import CONFIG from 'config/api';
import configureStore from '../store';
import {emitEvent} from 'services/socket';
const {store} = configureStore();

const {BASE_URL} = CONFIG;

export default class TrackingService {
  trackingInstance;

  constructor(socket) {
    //send localisation for the first time

    //init tracking to be ready to send coords on start() methode
    this.initTracking();
  }
  initTracking = () => {
    try {
      //loging the http respence
      BackgroundGeolocation.onHttp((httpEvent) => {
        console.log(
          '[httpsssss] ',
          httpEvent.success + ' / ' + httpEvent.status,
        );
      });
      //to get the cookie
      storage.getSession().then((cookie) => {
        console.log('fffffffffffffffff:', cookie);
        //The following configuration options are used to configure the BgTracking  SDK
        BackgroundGeolocation.ready({
          //The minimum distance (measured in meters) a device must move horizontally before an update event is generated.
          distanceFilter: 10,
          //disable automatic speed-based distanceFilter elasticity. eg: When device is moving at highway speeds, locations are returned at ~ 1 / km.
          disableElasticity: true,
          //indicating whether the status bar changes its appearance when an app uses location services in the background with Always authorization.
          showsBackgroundLocationIndicator: true,
          //The Android plugin will ignore a received location when it is identical to the last location. Set true to override this behaviour and record every location, regardless if it is identical to the last location.
          allowIdenticalLocations: true,
          //The number of minutes to wait before turning off location-services after the ActivityRecognition System (ARS) detects the device is STILL
          stopTimeout: 5,
          //Set false to continue tracking after user terminates the app.
          stopOnTerminate: false,
          //Set to true to enable background-tracking after the device reboots.
          startOnBoot: true,
          //Default: 60. Rate in seconds to fire BackgroundGeolocation.onHeartbeat events.
          //heartbeatInterval: 60,
          //Enable this to prevent iOS from suspending your app in the background while in the stationary state. Must be used in conjunction with a heartbeatInterval.
          preventSuspend: true,
          //Set true to make the plugin mostly immune to OS termination due to memory pressure from other apps.
          foregroundService: true,
          // Set to true to enable "Headless" mode when the user terminates the application. In this mode, you can respond to all the plugin's events in the native Android environment. For more information, see the wiki for Android Headless Mode
          //  enableHeadless: true,
          //TODO notification	Notification	Configures the required persistent Notification of the foreground service.

          //TODO Default: false. When enabled, the plugin will emit sounds & notifications for life-cycle events of background-geolocation
          debug: true,
          logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
          //IOS ACTIVITY TYPE
          activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
          //PERMISSION messages
          locationAuthorizationRequest: 'Always',
          backgroundPermissionRationale: {
            title:
              'Autoriser COSMIND DELIVERY à accéder à la position de cet appareil en arrière-plan ?',
            message:
              'Afin de suivre votre activité en arrière-plan, veuillez activer {backgroundPermissionOptionLabel} autorisation de localisation',
            positiveAction: 'Passer à {backgroundPermissionOptionLabel}',
            negativeAction: 'Annuler',
          },
          //When you configure the plugin locationAuthorizationRequest Always or WhenInUse and the user changes the mode in the app's location-services settings or disabled location-services, the plugin will display an Alert dialog directing the user to the Settings screen. locationAuthorizationAlert allows you to configure all the Strings for that Alert popup and accepts an {} containing the following keys:
          locationAuthorizationAlert: {
            titleWhenNotEnabled:
              'les services de localisation ne sont pas activés',
            titleWhenOff: 'services de localisation désactivés',
            instructions:
              "Vous devez activer 'Toujours' dans les services de localisation",
            cancelButton: 'Annuler',
            settingsButton: 'Réglages',
          },
          //Specify the desired-accuracy of the geolocation system. NOTE : Only DESIRED_ACCURACY_HIGH uses GPS. speed, heading and altitude are available only from GPS.
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          //Defaults to false. Set true to disable automatic, speed-based distanceFilter auto-scaling. By default, the SDK automatically increases distanceFilter as speed increases (and decreases it as speed decreases) in order to record fewer locations and conserve energy.
          disableElasticity: true,
          //Controls the rate (in seconds) the BackgroundGeolocation.onHeartbeat event will fire.
          //  heartbeatInterval: 60,
          //android===> to be able to trigger the notifs
          notification: {
            title: 'Localisation en background',
            text: 'Cliquez pour ouvrir',
          },
          // stopOnStationary: true,
          url: `
          `,
          autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
          //AUTHORISATION HEADER with cookie
          // headers: {
          //   Accept: 'application/json',
          //   'Content-Type': 'application/json',
          //   cookie: cookie,
          // },
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
            Authorization: 'Bearer ' + cookie,
          },

          //AUTHORISATION HEADER with token
        }).then((state) => {
          console.log(
            '[ready] BackgroundGeolocation is configured and ready to use',
            state?.enabled,
          );
          BackgroundGeolocation.start().then((res) => {
            console.log('@@@@the start  methode : ', res);
          });
        });
      });
    } catch (err) {
      displayToast('TRACKING ERROR : ' + err || '');
      console.log('TRACKING Ready  ERR : ', err);
    }
  };
  // static stop = () => {
  //   try {
  //     BackgroundGeolocation.stop().then((res) => {
  //       console.log('@@@@the stop methode : ', res);
  //     });
  //   } catch (err) {
  //     displayToast('TRACKING NOT STOPING : ' + err || '');
  //     console.log('TRACKING STOP ERR : ', err);
  //   }
  // };
  // static start = () => {
  //   try {
  //     BackgroundGeolocation.start().then((res) => {
  //       console.log('@@@@the start  methode : ', res);
  //     });
  //   } catch (err) {
  //     displayToast('TRACKING NOT STARTING : ' + err || '');
  //     console.log('TRACKING start  ERR : ', err);
  //   }
  // };
  static getInstance = () => {
    if (!this.trackingInstance) {
      this.trackingInstance = new TrackingService();
    }
    return this.trackingInstance;
  };
}



```

**Comment by christocracy** [comment]
You can **edit your own post**.  You don’t have to add extra noise to the thread by reposting the same thing.

**Comment by bilal-prog** [comment]
Okay as you said
