### ISSUE TITLE
Rare behaviour white screen after some time / relaunch app with geofence listeners

### ISSUE THREAD

**Issue by robmoorman** [transistorsoft/react-native-background-geolocation#155]
When using the module with geofences enabled we experience strange behaviour with the React Native bridge. After intensive testing, we have a build without this module which doesn't show a white screen.

After some time (can be minutes, hours or even days, app in background or closed) when relaunching the app / putting the app back to the foreground somethings happens which forces React Native to remove the rootView content. We can't see exactly what is happening in the logs, but we almost certain it's caused by something ran in the background with geofences on.

Now we see a fix (https://github.com/transistorsoft/react-native-background-geolocation/commit/a0fa32d9f71cb056b46f436717bfa17ee5cc743a) which has something to do with these threads.
Can it be you experienced behaviour like this (users ends up with a white screen, which is actually the rootView with RN's white default backgroundColor)?

``` javascript
BackgroundGeolocation.configure({
  activityType: 'Other',
  debug: false,
  disableStopDetection: true,
  disableMotionActivityUpdates: false,
  distanceFilter: 20,
  desiredAccuracy: 10,
  license: ...,
  locationAuthorizationRequest: 'Always',
  maxDaysToPersist: 5,
  maxRecordsToPersist: 10,
  stationaryRadius: 10,
  stopOnTerminate: false,
  startOnBoot: true,
})
```

We use version 1.4.3, now trying with the latest version.

**Comment by robmoorman** [comment]
Testcase still applies with version 1.5.2 with a singe geofence. When re-opening the app after some time (can be a couple of hours).

The only relevant log on the system is 'SystemUI unknown identifier: '<my_app_namespace>'.
Somehow this behaviour only occurs with geofences when the app is forced quit by the user.

**Comment by christocracy** [comment]
Try implementing a `componentWillUnmount` phase and remove any event-listeners on `BackgroundGeolocation`

```Javascript
  // You must remove listeners when your component unmounts
  componentWillUnmount() {
    // Remove BackgroundGeolocation listeners
    BackgroundGeolocation.un('location', this.onLocation);
    BackgroundGeolocation.un('error', this.onError);
    BackgroundGeolocation.un('motionchange', this.onMotionChange);
    BackgroundGeolocation.un('activitychange', this.onActivityChange);
    BackgroundGeolocation.un('providerchange', this.onProviderChange);
  }
```

**Comment by robmoorman** [comment]
Will give it a try, thnx.
In the meanwhile we experiences some keychain access problems as well, keep you posted!

**Comment by robmoorman** [comment]
Ok, we found the "solution". It's not the geofence mechanisme.
However it was, after locking your iPhone, triggered by the geofence which stores (after some time) a new JWT token in our store (encrypted with a secretKey from the KeyChain). This particular KeyChain item couldn't be accessed while in background-fetch. With the option `kSecAttrAccessibleAfterFirstUnlock` set, this is case is fixed for us (with a security breach left thought...).
