### ISSUE TITLE
Maximum number of geofencing entries in database and efficient querying of geofencing database

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1552]
## Your Environment
* Plugin version: 4.8.2
* Platform: iOS and Android
* OS version: iOS: 15.5, Android API 28
* React Native version (`react-native -v`): 0.66.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready({
      desiredAccuracy: BACKGROUND_TRACKING_ACCURACY_LEVEL_MAPPING[accuracy],
      stationaryRadius: 25,
      disableLocationAuthorizationAlert: true,
      stopOnTerminate: true,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: true, // enable to hear debug sounds
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // ios
      showsBackgroundLocationIndicator: true,
      // android
      allowIdenticalLocations: true,
      foregroundService: true,
      // location permissions
      locationAuthorizationRequest: 'WhenInUse',
      backgroundPermissionRationale: {
        ...
      },
      locationAuthorizationAlert: {
       ...
      },
    });
```

## Expected Behavior
I need to be able to handle ~500.000 Geofences. There is no need to monitor ~500.000 Geofences at the same time. But ideally I am able to insert them all into the database and then monitor a subset. A subset might have the size of ~25.000. Further, is there a more efficient way to identify the Geofences which should me monitored. The way I understand, a geofence is identified by its name porperty. I can group them by type, giving them an a number as identifier (1: Sweden, 2: USA, 3: Poland, ...) Is there a way to query the database efficiently by using the type (i.e. creating an index on the type) and then querying the geofences by their name?

## Actual Behavior
Can the SDK handle 500.000 Geofences in its database? Can the SDK monitor as many as 250.000 Geofences? Can one query the geofence database by something else then name and create an index on the queried column?

## Steps to Reproduce
I might be able to add and remove the geofences to the SDK's database, depending on what is monitored. This would reduce the 500.000 geofences in the database down to ~5.000, which then in turn are all monitored. But, this would a) bloat my app, because I have to store the geofences in two places (and its an offline first app) and b) will introduce loading time (when the data is loaded and removed from the geofences database) which is not desired.

## Context
What is the maximum number of geofences the SDK can handle in its database and the maximum number of geofences the SDK can monitor, in a reasonable amount of time. Can one query the geofences database by something else then the name property and can one create an index on the queried column.

**Comment by christocracy** [comment]
Do not attempt to put 500k geofences into the database.  That will take over 10 minutes just to do all the SQLite INSERTs in some devices.  Not a good experience for the user’s device.

you need to filter down your set (Eg by city).
