### ISSUE TITLE
getting location coordinates on configured URL even if the app is terminated or not but distance is always 0(zero)

### ISSUE THREAD

**Issue by kulbir22** [transistorsoft/react-native-background-geolocation#1553]
## Your Environment
* Plugin version: 4.7.1
* Platform: Android
* OS version: Android 11
* Device manufacturer / model: One Plus 6
* React Native version (`react-native -v`): 0.68.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
this.subscriptions.push(BackgroundGeolocation.onConnectivityChange((event) => {
            console.log("[onConnectivityChange] ", event, Toast);
            if(event.connected){
                //alert('You are connected to internet')
                Toast.show({
                    type: 'success',
                    text1: 'You are connected to internet'
                })
            }else{
                Toast.show({
                    type: 'error',
                    text1: 'No internet connectivity'
                })
            }
        }))

        this.subscriptions.push(BackgroundGeolocation.onLocation(async(location) => {
            console.log('[onLocation]', location);
            this.setState({location, distance: (location.odometer/1000).toFixed(2)})
            this.props.storeCoordinates(location);
            //alert(`Latitude: ${location.coords.latitude}\nLongitude: ${location.coords.longitude}`)
        }, (error) => {
            console.log('[onLocation] ERROR:', error);
        }))
    
        this.subscriptions.push(BackgroundGeolocation.onMotionChange((event) => {
            console.log('[onMotionChange]', event);
        }))
    
        this.subscriptions.push(BackgroundGeolocation.onActivityChange((event) => {
            //console.log('[onActivityChange]', event);
        }))
    
        this.subscriptions.push(BackgroundGeolocation.onHeartbeat((event) => {
            console.log('[onHeartbeat]', event);
        }))

        this.subscriptions.push(BackgroundGeolocation.onEnabledChange(isEnabled => {
            //console.log("[onEnabledChanged] isEnabled? ", isEnabled);
            this.setState({enabled: isEnabled});
        }));

        this.subscriptions.push(BackgroundGeolocation.onHttp(response => {
            try{
                const parsedData = JSON.parse(response.responseText);
                console.log("[http] response: ", response.success, response.status, response.responseText);
                if(response.success){
                    //alert(parsedData.status);
                    console.warn(parsedData.status);
                    //alert('Success');
                }else{
                    if(parsedData.hasOwnProperty("validation_error")){
                        let message = '';
                        const errorKeys = Object.keys(parsedData.validation_error);
                        errorKeys.forEach((item, index) => {
                            message += `- ${parsedData.validation_error[item]}${(index < (errorKeys.length - 1))? "\n" : ''}`
                        })
                        //Alert.alert("Validation Error", message)
                        console.warn("Validation Error", message)
                    }else{
                        alert(parsedData.status)
                    }
                }
            }catch(error){
                console.log(error);
            }
        }));

        BackgroundGeolocation.removeGeofences();
        
        BackgroundGeolocation.setConfig({
            // Geolocation Config
            locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"distance":<%= odometer %>}',
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            locationAuthorizationRequest: 'Always',
            foregroundService: true,
            geofenceProximityRadius: 10,
            backgroundPermissionRationale: {
                message: "This app collects location data to enable recording your trips to work and calculate distance-travelled."
            },
            fastestLocationUpdateInterval: 5000,
            distanceFilter: 25,
            stationaryRadius: 25,
            desiredOdometerAccuracy: 30,
            stopOnStationary: false,
            persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
            preventSuspend: true,
            debug: debug, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            enableHeadless: true,
            stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
            // disableStopDetection: true,
            // pausesLocationUpdatesAutomatically: false,
            // HTTP / SQLite config
            httpRootProperty:".",
            httpTimeout: 5000,
            method: "POST",
            url: `${baseURL}/travel-coordinates/store`,
            batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.,
            autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
            autoSyncThreshold: 5,
            headers: {              // <-- Optional HTTP headers
                "Authorization": `Bearer ${secretToken}`
            },
            params: {
                coordinates: JSON.stringify(coordinates)
            }
        })

        BackgroundGeolocation.getState().then(({enabled, params, locationTemplate, schedulerEnabled }) => {
            this.setState({enabled}, async() => {
                const { enabled } = this.state;
                if(enabled){

                }else{
                    BackgroundGeolocation.start().then((response) => {
                        console.log("### [state] ", response.isMoving);
                        if(!response.isMoving){
                            BackgroundGeolocation.changePace(true);
                        }
                    });
                }
            });
        })
```

## Expected Behavior

The app should send "lat, long, distance" as per specified "locationTemplate" to the configured "URL" even if the app is terminated or is running in the background.

## Actual Behavior

I am able to receive "lat: some value, long: some value and distance: 0" on the configured URL. Sometimes I get the distance travelled, but there are times when distance is 0 (zero). I have checked and attached the verbose logs via the shared link. However, in the said logs odometer value is constantly being updated. I am super confused and not sure how do I get this issued fixed. 

*** Please help, I have purchased your API. Besides, I have a project to deliver to my client. ***

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
[https://drive.google.com/file/d/1mR_biTg-LrPVD8VY1mV2nxBhLrD7OWbQ/view?usp=sharing](url)
```

</details>

**Comment by christocracy** [comment]
> and I am calling BackgroundGeolocation.ready in App.js

So you’re hoping that your posted code runs in the headless state?

I don’t understand.

show me your entire index.js and App.js (separately)

**Comment by kulbir22** [comment]
> > geofenceProximityRadius: 10,
> 
> I don’t think you understand this option. The plugin won’t even allow you to set it that low (it enforces a minimum of 1000 meters) so that you don’t “shoot yourself in the foot”, as you would be doing here.

I had an other issue as well and I was trying to see if it got fixed. My app is working fine when I am simulating location via "Lockito". The other while testing in real world is that, when the app is terminated and the app enters STATIONARY_STATE, I had to travel somewhere between 1-2 Km(s), for the app to start fetching location coordinates.

**Comment by christocracy** [comment]
I suggest you read the api docs about Config.geofenceProximityRadius.  It has nothing to do with Motion-triggering.

**Comment by kulbir22** [comment]
> > and I am calling BackgroundGeolocation.ready in App.js
> 
> So you’re hoping that your posted code runs in the headless state?
> 
> I don’t understand.
> 
> show me your entire index.js and App.js (separately)

================
App.js

`import React, { Component } from 'react';
import {Text, TextInput, Alert} from 'react-native';
import moment from 'moment';
import BackgroundGeolocation from 'react-native-background-geolocation';
import DatePicker from 'react-native-datepicker'
import {Provider} from 'react-redux';
import {createStore} from 'redux';
import reducers from './src/reducers';
import RouterComponent from './src/Router';
import { propValues } from './src/global/variables';

  class App extends Component {

    componentDidMount(){
        BackgroundGeolocation.ready({
            locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"distance":<%= odometer %>}',
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            locationAuthorizationRequest: 'Always',
            foregroundService: true,
            geofenceProximityRadius: 10,
            fastestLocationUpdateInterval: 5000,
            distanceFilter: 25,
            stationaryRadius: 25,
            desiredOdometerAccuracy: 30,
            stopOnStationary: false,
            persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
            preventSuspend: true,
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            enableHeadless: true,
            stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
            // HTTP / SQLite config
            httpRootProperty:".",
            httpTimeout: 5000,
            batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.,
            autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
            autoSyncThreshold: 5,
            // disableStopDetection: true,
            // pausesLocationUpdatesAutomatically: false
        }, async (state) => {
            console.log('@@@### Configure success', state.enabled, state.isMoving);
            if(state.enabled){
                
            }
        });
    }

    render() {
        if (Text.defaultProps == null) Text.defaultProps = {};
        Text.defaultProps.allowFontScaling = false;
        if(TextInput.defaultProps == null ) TextInput.defaultProps = {};
        TextInput.defaultProps.allowFontScaling = false; 
        if(DatePicker.defaultProps == null ) DatePicker.defaultProps = {};
        DatePicker.defaultProps.allowFontScaling = false;  
            return (
                <Provider store={createStore(reducers)}>
                    <RouterComponent />  
                </Provider>
            )
      }
  }

  export default App;`
================


*********************
index.js

`/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
import BackgroundGeolocation from 'react-native-background-geolocation';

AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));

BackgroundGeolocation.registerHeadlessTask(async (event) => {
    let params = event.params;
    console.log("[BackgroundGeolocation HeadlessTask] -", event.name, params);
    // switch (event.name) {
    //     case 'heartbeat':
    //       /**
    //       * Enable this block to execute #getCurrentPosition in headless heartbeat event (will consume more power)
    //       *
    //       // Use await for async tasks
    //       const location = await BackgroundGeolocation.getCurrentPosition({
    //         samples: 1,
    //         persist: false
    //       });
    //       console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
    //       *
    //       */
    //         BackgroundGeolocation.logger.getLog().then((log) => {
    //             // Warning:  this string could be several megabytes.
    //             console.log("[log] success: ", log);
    //         });
    //         break;
    // }
})`
*********************

**Comment by christocracy** [comment]
> I had to travel somewhere between 1-2 Km(s)

Totally depends upon the device.  Test on a variety of devices (I test on 13 different Android devices).  Some are great, some are not.

**Comment by christocracy** [comment]
Please learn to [syntax highlight code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by kulbir22** [comment]
> Please learn to [syntax highlight code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

sorry my bad

**Comment by christocracy** [comment]
> sorry my bad

That’s fine.  Just edit your post

**Comment by christocracy** [comment]
>I am able to receive "lat: some value, long: some value and distance: 0"

Maybe you're doing something wrong on your server?

In the logs, you can see `odometer` is being updated.

>09-27 19:34:21.345 DEBUG [TSLocationManager incrementOdometer] Odometer: 9317.779

I suggest you observe the *raw* `JSON` being sent to your server, before it undergoes any conversion with your server code.

**Comment by kulbir22** [comment]
Ok will do and I'll get back to you.

**Comment by kulbir22** [comment]
> > I had to travel somewhere between 1-2 Km(s)
> 
> Totally depends upon the device. Test on a variety of devices (I test on 13 different Android devices). Some are great, some are not.

Meanwhile could you tell, if there's a way to get the app out of STATIONARY_STATE to MOVING_STATE as soon as the user starts walking.

**Comment by christocracy** [comment]
> as soon as the user starts walking.

That’s exactly what the plugin is designed to do, by listening to the motion api.  

However, the motion api is a “black box” with only an ON/OFF switch.  It’s totally up to the os to fire motion events to the plugin.  The quality of the motion api performance depend upon the quality of the device and the sensors on it (accelerometer, gyroscope, magnetometer).

There is nothing the plugin can do to improve the performance of the motion api.

Also see https://dontkillmyapp.com and test on a variety of devices.

i primarily develop on a Pixel 6 @ Android 13, which operates exactly as the Android api docs say it should.

you can fool the Motion api to think you’re walking by shaking the device vigorously (watch adb logcat while doing so).

**Comment by kulbir22** [comment]
> > I am able to receive "lat: some value, long: some value and distance: 0"
> 
> Maybe you're doing something wrong on your server?
> 
> In the logs, you can see `odometer` is being updated.
> 
> > 09-27 19:34:21.345 DEBUG [TSLocationManager incrementOdometer] Odometer: 9317.779
> 
> I suggest you observe the _raw_ `JSON` being sent to your server, before it undergoes any conversion with your server code.

I just remember that while I'm testing using "Lockito" app, I always get regular distance updates. If there had been some issue at server while handling JSON, then the issue would have been observed in simulation as well. But that's not the case.

**Comment by kulbir22** [comment]
This is observed only during real world testing and I've noticed as soon as the tracking starts the distance would get updated initially but then, if the app is terminated and opened after quiet sometime, the distance would show itself to be zero.

**Comment by christocracy** [comment]
When you reproduce this, I suggest you capture logs demonstrating it and upload them here to this issue.

**Comment by kulbir22** [comment]
> When you reproduce this, I suggest you capture logs demonstrating it and upload them here to this issue.

Could you please guide me, on how to capture JSON logs, I'm sorry if I'm asking too much

**Comment by christocracy** [comment]
I mean plugin debug logs.  See api docs .emailLog.  Also see wiki *Debugging*.

**Comment by kulbir22** [comment]
> I mean plugin debug logs. See api docs .emailLog. Also see wiki _Debugging_.

I've already shared with you the link to the plugin logs
[Plugin Logs](https://drive.google.com/file/d/1mR_biTg-LrPVD8VY1mV2nxBhLrD7OWbQ/view?usp=sharing)

**Comment by christocracy** [comment]
What timestamp are you interested in from the logs?

**Comment by christocracy** [comment]
> access json log

no.  Also, since you’re using a minimal locationTemplate, not including the `uuid` attribute, you won’t even be able to match locations in the logs with those received at your server.

that is the purpose of `uuid` — being able to debug problems.

**Comment by kulbir22** [comment]
> ```js
> params: {
>                 coordinates: JSON.stringify(coordinates)
>             }
> ```
The `params` is always blank "[ ]" as of now, but it should contain an array of objects, where each object should represent the entire JSON data received. I'll be much obliged if you could point me in the right direction on how to do so ?

**Comment by kulbir22** [comment]
> I have no idea what you’re trying to do there.

I'm basically trying to get such data at my server

```
{
"latitude": "30.70938721198",
"longitude": "76.689684230416",
"distance": "33.80",
"coordinates": [
{
// Location JSON Data
},
{
// Location JSON Data
},
]
}
```

**Comment by christocracy** [comment]
In a `params` object that you’ve provided no context for?

**Comment by kulbir22** [comment]
> In a `params` object that you’ve provided no context for?

I tried adding via params, but couldn't do so

**Comment by christocracy** [comment]
Params to *what*??  `.ready(Config)`??

**Comment by kulbir22** [comment]
> Params to _what_?? `.ready(Config)`??

never mind, later I'll create a separate issue, after the current issue is resolved.

**Comment by christocracy** [comment]
I have *years* of historical data from my test devices, many of which I pack into my backpack and take with me every single day.  I see no mysterious cases of `odometer: 0`.

<img width="1346" alt="Screen Shot 2022-09-29 at 9 20 07 AM" src="https://user-images.githubusercontent.com/14999/193043503-74e3c56b-9963-4acd-8baf-d10bc07366b9.png">

**Comment by kulbir22** [comment]
> > "date": "2022-09-29",
> 
> You're only saving the `date` and stripping out the time??
> 
> I have no idea what your problem is but it's certainly on your end. This is not a plugin issue I can solve for you.

The date is set by the server, I've sent only `locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"distance":<%= odometer %>}'`

**Comment by kulbir22** [comment]
> > > "date": "2022-09-29",
> > 
> > 
> > You're only saving the `date` and stripping out the time??
> > I have no idea what your problem is but it's certainly on your end. This is not a plugin issue I can solve for you.
> 
> The date is set by the server, I've sent only `locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"distance":<%= odometer %>}'`

The other team is only concerned with latitude, longitude and distance. That is why I chose to send only `locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"distance":<%= odometer %>}'`

**Comment by christocracy** [comment]
>The other team is only concerned with latitude, longitude and distance

And now you have no way to debug your problems;  to correlate locations on the server with those in the logs.

**Comment by kulbir22** [comment]
> > The other team is only concerned with latitude, longitude and distance
> 
> And now you have no way to debug your problems; to correlate locations on the server with those in the logs.

So, you suggest to include `uuid and timestamp` within my location template. Apart from this, is there any other `property` I might need to include ?

**Comment by kulbir22** [comment]
It seems by adding `uuid and timestamp` within my location template resolves the issue with distance being 0 (zero). But, i'll be testing my app further.

**Comment by kulbir22** [comment]
> you can fool the Motion api to think you’re walking by shaking the device vigorously (watch adb logcat while doing so).

In real world testing, shaking the device vigorously has no effect on the plugin. No matter how hard I shake the device, my app will never transit from STATIONARY_STATE to MOVING_STATE. I still need to move 1-2 Km(s) for the app to cause the trigger. I am using One Plus 6.

Please help.

**Comment by christocracy** [comment]
- see https://dontkillmyapp.com
- Use a different device.

**Comment by kulbir22** [comment]
I'm witnessing a weird behaviour in the app. At times, the coordinates that are fetched as soon as the tracking starts are being sent to the server later. I think this probably happens when there is internet connectivity issue.

Could you please advise how do I fix this ?

```
"data": [
        {
            "id": 503130,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "23658.31",                       `<---------`
            "latitude": "25.9752697",
            "longitude": "76.2905266",
            "created_at": "2022-10-13T04:18:10.000000Z",
            "updated_at": "2022-10-13T04:18:10.000000Z"
        },
        {
            "id": 503131,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "23761.05",                       `<---------`
            "latitude": "25.9747661",
            "longitude": "76.2896651",
            "created_at": "2022-10-13T04:18:11.000000Z",
            "updated_at": "2022-10-13T04:18:11.000000Z"
        },
        .
        .
        .
        {
            "id": 503171,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "0.00",                                    // Initial Distance                       `<---------`       
            "latitude": "26.1701599",                         // Initial Location
            "longitude": "75.8027222",                     // Initial Location
            "created_at": "2022-10-13T04:19:11.000000Z",
            "updated_at": "2022-10-13T04:19:11.000000Z"
        },
        {
            "id": 504223,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "58.75",                       `<---------`
            "latitude": "26.1702232",
            "longitude": "75.8021934",
            "created_at": "2022-10-13T04:51:22.000000Z",
            "updated_at": "2022-10-13T04:51:22.000000Z"
        },
        {
            "id": 504225,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "109.46",                       `<---------`
            "latitude": "26.170285",
            "longitude": "75.8017067",
            "created_at": "2022-10-13T04:51:23.000000Z",
            "updated_at": "2022-10-13T04:51:23.000000Z"
        },
        {
            "id": 504226,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "7788.86",                       `<---------`
            "latitude": "26.118111",
            "longitude": "75.7511468",
            "created_at": "2022-10-13T04:51:23.000000Z",
            "updated_at": "2022-10-13T04:51:23.000000Z"
        },
        {
            "id": 504227,
            "user_id": 15,
            "date": "2022-10-13",
            "coordinates": "[]",
            "distance": "7930.94",                       `<---------`
            "latitude": "26.1170485",
            "longitude": "75.7503513",
            "created_at": "2022-10-13T04:51:24.000000Z",
            "updated_at": "2022-10-13T04:51:24.000000Z"
        }
              ]
```

**Comment by christocracy** [comment]
> getting location coordinates on configured URL even if the app is terminated or not but distance is always 0(zero)

Is this issue fixed?

**Comment by kulbir22** [comment]
> > getting location coordinates on configured URL even if the app is terminated or not but distance is always 0(zero)
> 
> Is this issue fixed?

Yes, thats fixed.

**Comment by kulbir22** [comment]
> I'm witnessing a weird behaviour in the app. At times, the coordinates that are fetched as soon as the tracking starts are being sent to the server later. I think this probably happens when there is internet connectivity issue.
> 
> Could you please advise how do I fix this ?

Can you help me with this ?

**Comment by christocracy** [comment]
If you have an unrelated question, post a new issue.

this issue is closed.

Issues are not open-ended personal tech support threads for every question you have.
