### ISSUE TITLE
When Exiting the GeoFence BackgroundGeolocation.start() not work. 

### ISSUE THREAD

**Issue by SharfMohiuddin** [transistorsoft/react-native-background-geolocation#1558]
Details: I made a GeoFence and in Geofence I don't want any tracking but when I leave or exit the GeoFence it should starts the Background Location but in our case it is not starting the tracking again after exiting the GeoFence. Please help me out! Thanks.

subscribe(
    BackgroundGeolocation.onGeofence((geofence) => {
      console.log("[geofence] ", geofence.identifier, geofence.action);
      if (
        geofence.identifier == " AppleOffice" 
      
      ) {
        if (geofence.action == "ENTER") {
          console.log("I'm in GeoFence");
          BackgroundGeolocation.stop();
        } else if (geofence.action == "EXIT") {
          console.log(" GeoFence exit");
          BackgroundGeolocation.start();
        }
       
      }
    })
  );

BackgroundGeolocation.addGeofence({
    identifier: "AppleOffice",
    radius: 200,
    latitude: 37.334329576054394,
    longitude: -122.0457842,
    notifyOnEntry: true,
    notifyOnExit: true,
    extras: {
      route_id: 1234,
    },
  })
    .then((success) => {
      console.log("[addGeofence] success");
    })
    .catch((error) => {
      console.log("[addGeofence] FAILURE: ", error);
    });

**Comment by christocracy** [comment]
calling .stop() stops **everything**, including geofence monitoring,

you want to call .startGeofences() to engage geofence-only monitoring, not .stop().

**Comment by SharfMohiuddin** [comment]
Thanks for your response, it worked for us. But the problem is that in the demo video the Red marker is exactly on the end of the GeoFence and the Green marker is exactly on the starting of the GeoFence. But in our case, starting marker is fine but when the Geofence ends the next tracking point is far away from the ending of GeoFence as you can see in the attached S.S. Can you please help us out!




![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/111132563/195339137-85d4f8cd-4f2d-411f-81bc-cc274bf5d8ad.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/111132563/195339754-8bd4b697-34f3-48e3-bad4-bc3e018946a9.png)

**Comment by christocracy** [comment]
The plugin is not responsible for firing geofences.  It is the OS which manages firing geofences.  Yes, they can sometimes at least 100 meters outside the geofence (can be more).
