### ISSUE TITLE
Polyline Direction 

### ISSUE THREAD

**Issue by Danish-Wajid** [transistorsoft/react-native-background-geolocation#1560]
We tried to use the heading parameter return by plugin to draw the direction arrow on the polyline but the directions doesn't seem to be right. As we saw in demo video you are able to draw the direction marker accurately. Can you guide us how to do that as you have done in the attached S.S? Thanks in advance.

![CC6FB680-D7EB-48EB-8613-1A38461079D1_4_5005_c](https://user-images.githubusercontent.com/102729412/195531564-7cb7d417-6cfb-4ca8-99ce-82297ed05175.jpeg)

**Comment by christocracy** [comment]
That screenshot is from the Cordova/Ionic version using the web version of Google maps.  The Google maps web api has a nice feature for polyline to automatically draw little white arrows based upon the order of locations in the collection (it’s not based upon heading).

The native maps api used in react-native-maps does not have this feature.
