### ISSUE TITLE
Error building release: Execution failed for task ':background_fetch:verifyReleaseResources'.

### ISSUE THREAD

**Issue by stefanstyles** [transistorsoft/react-native-background-geolocation#1566]
When building the release build I get the following error:

* What went wrong:
Execution failed for task ':background_fetch:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\stefan.styles\.gradle\caches\transforms-3\5e083c06c9925c2309f02468fc66e376\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

* Plugin version: flutter_background_geolocation 4.8.1
* Android
* OS version: Windows 11
* Building in VS Code

## Expected Behavior
Expecting it to build

## Actual Behavior
Build failed

Dependency Tree
Dart SDK 2.18.2
Flutter SDK 3.3.4
s3mobile 0.1.0+1
|-- build_runner 2.3.0
|   |-- analyzer 5.1.0
|   |   |-- _fe_analyzer_shared 49.0.0
|   |   |   '-- meta...
|   |   |-- collection...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- meta...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- pub_semver...
|   |   |-- source_span...
|   |   |-- watcher...
|   |   '-- yaml...
|   |-- args...
|   |-- async...
|   |-- build 2.3.1
|   |   |-- analyzer...
|   |   |-- async...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- logging...
|   |   |-- meta...
|   |   '-- path...
|   |-- build_config 1.1.0
|   |   |-- checked_yaml...
|   |   |-- json_annotation...
|   |   |-- path...
|   |   |-- pubspec_parse...
|   |   '-- yaml...
|   |-- build_daemon 3.1.0
|   |   |-- built_collection 5.1.1
|   |   |-- built_value 8.4.1
|   |   |   |-- built_collection...
|   |   |   |-- collection...
|   |   |   |-- fixnum 1.0.1
|   |   |   '-- meta...
|   |   |-- http_multi_server...
|   |   |-- logging...
|   |   |-- path...
|   |   |-- pool...
|   |   |-- shelf...
|   |   |-- shelf_web_socket...
|   |   |-- stream_transform...
|   |   |-- watcher...
|   |   '-- web_socket_channel...
|   |-- build_resolvers 2.0.10
|   |   |-- analyzer...
|   |   |-- async...
|   |   |-- build...
|   |   |-- crypto...
|   |   |-- graphs...
|   |   |-- logging...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- pool...
|   |   |-- pub_semver...
|   |   |-- stream_transform...
|   |   '-- yaml...
|   |-- build_runner_core 7.2.4
|   |   |-- async...
|   |   |-- build...
|   |   |-- build_config...
|   |   |-- build_resolvers...
|   |   |-- collection...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- graphs...
|   |   |-- json_annotation...
|   |   |-- logging...
|   |   |-- meta...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- pool...
|   |   |-- timing...
|   |   |-- watcher...
|   |   '-- yaml...
|   |-- code_builder 4.3.0
|   |   |-- built_collection...
|   |   |-- built_value...
|   |   |-- collection...
|   |   |-- matcher...
|   |   '-- meta...
|   |-- collection...
|   |-- crypto 3.0.2
|   |   '-- typed_data...
|   |-- dart_style 2.2.4
|   |   |-- analyzer...
|   |   |-- args...
|   |   |-- path...
|   |   |-- pub_semver...
|   |   '-- source_span...
|   |-- frontend_server_client 2.1.3
|   |   |-- async...
|   |   '-- path...
|   |-- glob 2.1.0
|   |   |-- async...
|   |   |-- collection...
|   |   |-- file...
|   |   |-- path...
|   |   '-- string_scanner...
|   |-- graphs 2.1.0
|   |   '-- collection...
|   |-- http_multi_server 3.2.1
|   |   '-- async...
|   |-- io 1.0.3
|   |   |-- meta...
|   |   |-- path...
|   |   '-- string_scanner...
|   |-- js 0.6.4
|   |-- logging...
|   |-- meta...
|   |-- mime 1.0.2
|   |-- package_config 2.1.0
|   |   '-- path...
|   |-- path...
|   |-- pool 1.5.1
|   |   |-- async...
|   |   '-- stack_trace...
|   |-- pub_semver 2.1.2
|   |   |-- collection...
|   |   '-- meta...
|   |-- pubspec_parse 1.2.1
|   |   |-- checked_yaml...
|   |   |-- collection...
|   |   |-- json_annotation...
|   |   |-- pub_semver...
|   |   '-- yaml...
|   |-- shelf 1.4.0
|   |   |-- async...
|   |   |-- collection...
|   |   |-- http_parser...
|   |   |-- path...
|   |   |-- stack_trace...
|   |   '-- stream_channel...
|   |-- shelf_web_socket 1.0.2
|   |   |-- shelf...
|   |   |-- stream_channel...
|   |   '-- web_socket_channel...
|   |-- stack_trace...
|   |-- stream_transform 2.0.1
|   |-- timing 1.0.0
|   |   '-- json_annotation...
|   |-- watcher 1.0.2
|   |   |-- async...
|   |   '-- path...
|   |-- web_socket_channel 2.2.0
|   |   |-- async...
|   |   |-- crypto...
|   |   '-- stream_channel...
|   '-- yaml 3.1.1
|       |-- collection...
|       |-- source_span...
|       '-- string_scanner...
|-- change_app_package_name 1.1.0
|-- convert 3.1.1
|   '-- typed_data 1.3.1
|       '-- collection...
|-- cupertino_icons 1.0.5
|-- currency_text_input_formatter 2.1.7
|   |-- flutter...
|   '-- intl 0.17.0
|       |-- clock...
|       '-- path...
|-- exif 3.1.2
|   |-- args 2.3.1
|   |-- collection...
|   |-- convert...
|   |-- json_annotation...
|   '-- sprintf 6.0.2
|-- flutter 0.0.0
|   |-- characters 1.2.1
|   |-- collection 1.16.0
|   |-- material_color_utilities 0.1.5
|   |-- meta 1.8.0
|   |-- sky_engine 0.0.99
|   '-- vector_math 2.1.2
|-- flutter_background_geolocation 4.8.1
|   |-- background_fetch 1.1.1
|   |   '-- flutter...
|   |-- collection...
|   '-- flutter...
|-- flutter_launcher_icons 0.10.0
|   |-- args...
|   |-- checked_yaml 2.0.1
|   |   |-- json_annotation...
|   |   |-- source_span...
|   |   '-- yaml...
|   |-- cli_util 0.3.5
|   |   |-- meta...
|   |   '-- path...
|   |-- image 3.2.2
|   |   |-- archive 3.3.2
|   |   |   |-- crypto...
|   |   |   '-- path...
|   |   |-- meta...
|   |   '-- xml 6.1.0
|   |       |-- collection...
|   |       |-- meta...
|   |       '-- petitparser 5.0.0
|   |           '-- meta...
|   |-- json_annotation...
|   |-- path...
|   '-- yaml...
|-- flutter_lints 2.0.1
|   '-- lints 2.0.0
|-- flutter_pagewise 2.0.4
|   |-- async...
|   '-- flutter...
|-- flutter_test 0.0.0
|   |-- async...
|   |-- boolean_selector 2.1.0
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- characters...
|   |-- clock 1.1.1
|   |-- collection...
|   |-- fake_async 1.3.1
|   |   |-- clock...
|   |   '-- collection...
|   |-- flutter...
|   |-- matcher 0.12.12
|   |   '-- stack_trace...
|   |-- material_color_utilities...
|   |-- meta...
|   |-- path...
|   |-- source_span 1.9.0
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.10.0
|   |   '-- path...
|   |-- stream_channel 2.1.0
|   |   '-- async...
|   |-- string_scanner 1.1.1
|   |   '-- source_span...
|   |-- term_glyph 1.2.1
|   |-- test_api 0.4.12
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   '-- vector_math...
|-- http 0.13.5
|   |-- async 2.9.0
|   |   |-- collection...
|   |   '-- meta...
|   |-- http_parser 4.0.2
|   |   |-- collection...
|   |   |-- source_span...
|   |   |-- string_scanner...
|   |   '-- typed_data...
|   |-- meta...
|   '-- path...
|-- json_annotation 4.7.0
|   '-- meta...
|-- json_serializable 6.5.1
|   |-- analyzer...
|   |-- async...
|   |-- build...
|   |-- build_config...
|   |-- collection...
|   |-- json_annotation...
|   |-- meta...
|   |-- path...
|   |-- pub_semver...
|   |-- pubspec_parse...
|   |-- source_gen 1.2.6
|   |   |-- analyzer...
|   |   |-- async...
|   |   |-- build...
|   |   |-- dart_style...
|   |   |-- glob...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- source_span...
|   |   '-- yaml...
|   '-- source_helper 1.3.3
|       |-- analyzer...
|       |-- collection...
|       '-- source_gen...
|-- keyboard_actions 4.1.0
|   '-- flutter...
|-- logging 1.1.0
|-- observable 0.24.0
|   |-- collection...
|   |-- dart_internal 0.2.6
|   |-- meta...
|   '-- quiver 3.1.0
|       '-- matcher...
|-- path 1.8.2
|-- path_provider 2.0.11
|   |-- flutter...
|   |-- path_provider_android 2.0.20
|   |   |-- flutter...
|   |   '-- path_provider_platform_interface...
|   |-- path_provider_ios 2.0.11
|   |   |-- flutter...
|   |   '-- path_provider_platform_interface...
|   |-- path_provider_linux 2.1.7
|   |   |-- ffi 2.0.1
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_platform_interface...
|   |   '-- xdg_directories 0.2.0+2
|   |       |-- meta...
|   |       |-- path...
|   |       '-- process 4.2.4
|   |           |-- file...
|   |           |-- path...
|   |           '-- platform...
|   |-- path_provider_macos 2.0.6
|   |   |-- flutter...
|   |   '-- path_provider_platform_interface...
|   |-- path_provider_platform_interface 2.0.5
|   |   |-- flutter...
|   |   |-- platform 3.1.0
|   |   '-- plugin_platform_interface 2.1.3
|   |       '-- meta...
|   '-- path_provider_windows 2.1.3
|       |-- ffi...
|       |-- flutter...
|       |-- path...
|       |-- path_provider_platform_interface...
|       '-- win32 3.0.1
|           '-- ffi...
|-- property_change_notifier 0.3.0
|   '-- flutter...
|-- rxdart 0.27.5
|-- shared_preferences 2.0.15
|   |-- flutter...
|   |-- shared_preferences_android 2.0.14
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_ios 2.1.1
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_linux 2.1.1
|   |   |-- file 6.1.4
|   |   |   |-- meta...
|   |   |   '-- path...
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_linux...
|   |   |-- path_provider_platform_interface...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_macos 2.0.4
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_platform_interface 2.1.0
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- shared_preferences_web 2.0.4
|   |   |-- flutter...
|   |   |-- flutter_web_plugins 0.0.0
|   |   |   |-- characters...
|   |   |   |-- collection...
|   |   |   |-- flutter...
|   |   |   |-- js...
|   |   |   |-- material_color_utilities...
|   |   |   |-- meta...
|   |   |   '-- vector_math...
|   |   '-- shared_preferences_platform_interface...
|   '-- shared_preferences_windows 2.1.1
|       |-- file...
|       |-- flutter...
|       |-- path...
|       |-- path_provider_platform_interface...
|       |-- path_provider_windows...
|       '-- shared_preferences_platform_interface...
|-- sqflite 2.1.0+1
|   |-- flutter...
|   |-- path...
|   '-- sqflite_common 2.3.0
|       |-- meta...
|       |-- path...
|       '-- synchronized 3.0.0+3
|-- wechat_assets_picker 8.1.3
|   |-- extended_image 6.3.1
|   |   |-- extended_image_library 3.4.0
|   |   |   |-- crypto...
|   |   |   |-- flutter...
|   |   |   |-- http_client_helper 2.0.3
|   |   |   |   '-- http...
|   |   |   |-- path...
|   |   |   '-- path_provider...
|   |   |-- flutter...
|   |   '-- meta...
|   |-- flutter...
|   |-- photo_manager 2.4.0
|   |   '-- flutter...
|   |-- provider 6.0.4
|   |   |-- collection...
|   |   |-- flutter...
|   |   '-- nested 1.0.0
|   |       '-- flutter...
|   '-- video_player 2.4.7
|       |-- flutter...
|       |-- html 0.15.0
|       |   |-- csslib 0.17.2
|       |   |   '-- source_span...
|       |   '-- source_span...
|       |-- video_player_android 2.3.9
|       |   |-- flutter...
|       |   '-- video_player_platform_interface...
|       |-- video_player_avfoundation 2.3.7
|       |   |-- flutter...
|       |   '-- video_player_platform_interface...
|       |-- video_player_platform_interface 5.1.4
|       |   |-- flutter...
|       |   '-- plugin_platform_interface...
|       '-- video_player_web 2.0.12
|           |-- flutter...
    |   |-- flutter...
    |   |-- flutter_plugin_android_lifecycle 2.0.7
    |   |   '-- flutter...
    |   '-- quiver...
    |-- camera_platform_interface 2.2.2
    |   |-- cross_file 0.3.3+2
    |   |   |-- js...
    |   |   '-- meta...
    |   |-- flutter...
    |   |-- plugin_platform_interface...
    |   '-- stream_transform...
    |-- flutter...
    |-- path...
    |-- photo_manager...
    '-- video_player...

Build.gradle
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
               maven {
           // [required] flutter_background_geolocation
           url "${project(':flutter_background_geolocation').projectDir}/libs"
       }
       maven {
           // [required] background_fetch
           url "${project(':background_fetch').projectDir}/libs"
       }
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:deprecation"
        }
    }   
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

app/build.gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def flutterMinSdkVersion = localProperties.getProperty('flutter.MinSdkVersion')
if (flutterMinSdkVersion == null) {
    flutterMinSdkVersion = '21'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
// flutter_background_geolocation (must be placed after the lines above)
Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.s3ware.s3mobile"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion flutterMinSdkVersion.toInteger()
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

</details>

**Comment by christocracy** [comment]
> Dart SDK 2.18.2
>Flutter SDK 3.3.4

This is the *React Native* repo.  You seem to be using Flutter.  

The Flutter version is merely one of four different versions of this plugin:
- Cordova
- Capacitor
- React Native
- Flutter

Please post your issue in the correct repo.
