### ISSUE TITLE
Error with Mapbox in the example app

### ISSUE THREAD

**Issue by kevando** [transistorsoft/react-native-background-geolocation#157]
Undefined is not an object evaluating MapboxGLManager.mapStyles
https://i.imgur.com/CShen4F.png

Is there a reason the example app uses this 3rd party map software instead of the native maps?

**Comment by christocracy** [comment]
react-native-maps *is* a 3rd-party component, manage by [AirBnb](https://github.com/airbnb/react-native-maps).

The plugin is not married to any particular map framework.  I simply chose to use Mapbox (which I dislike) at the time of writing because everything else was insufficient for my needs.

The plugin doesn't require a Map component.

**Comment by christocracy** [comment]
The error sounds like you don't have Mapbox GL installed properly.
https://github.com/mapbox/react-native-mapbox-gl/issues/387

**Comment by kevando** [comment]
Thank you @christocracy I did not properly install mapbox. I followed those instructions and I believe it's installed because it's now conflicting with the airbnb plugin (which I already had installed and working in my app) because I am getting this error now..

https://github.com/airbnb/react-native-maps/issues/289

Can mapbox and react-native-maps co-exist on the app?

**Comment by kevando** [comment]
And I have the react-native-maps plugin working really well with my app, so I am going to uninstall mapbox and just try to get the 1 part working that I want. 

I really just want access to the user's location when I send them a push notification, so most of the example app I will not use, so I am no longer going to try and get the example working. 


```// This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.on('location', this.onLocation);
```

I assume this function will fire every time the user moves 300m (for iOS) and I can push the the location object to my firebase database, right? Or is there a different way to grab the user's location when the app is closed. Sorry about my ignorance, I know very very little about native code.

**Comment by christocracy** [comment]
Why are you trying to install MapBox into your app?  Don't do that.

**Comment by kevando** [comment]
I was trying to install it because the example app used it.

**Comment by christocracy** [comment]
When installing the plugin into your own app, forget about the dependencies of the Demo app.

The dependencies of the Demo app have nothing to do with the requirements of the plugin itself.  The plugin does not know or care about a Map.  It provides locations.  What you do with those locations is completely up to you.  If you want to render those locations on a map, you're free to do so with whatever component you wish.

**Comment by christocracy** [comment]
The plugin has 2 states:  **moving** and **stationary**.  The plugin *desires* to be in the **stationary** state, with location-services **OFF**, conserving battery.  While in the stationary-state on iOS, the plugin has created a geofence around the current position.  When your app is in the background in the **stationary** state, iOS has suspend your app and your Javascript is not running.  When the device moves *out* of that "stationary geofence" (typically takes 100-300 meters of movement), iOS will re-awaken your app in the background to service that geofence event.  The plugin will now change state to **moving**, turn **ON** location-services and your app is completely awake in the background, firing the `location` event each time the device moves `distanceFilter` meters.

When the device stops in the same position for `stopTimeout` minutes, the plugin will change state to **stationary**, turn off location-services and iOS will put your app to sleep until the device once again moves out of the "stationary geofence".

**Comment by kevando** [comment]
Sweet! Thanks for all the information. I am building the basic componentDidMount configuration from the main README and hopefully this works.

**Comment by christocracy** [comment]
The simplest way to use the plugin is simply:
```Javascript
import {BackgroundGeolocation} from "react-native-background-geolocation";
componentDidMount() {
  // First listen to your desired events:
  BackgroundGeolocation.on('location', this.onLocation);
  BackgroundGeolocation.on('motionchange', this.onMotionChange);
  .
  .
  .
  BackgroundGeolocation.configure({debug: true}, function(state) {
    console.log('- BackgroundGeolocation is configured and ready to use: ', state.enabled);
    if (!state.enabled) {
      BackgroundGeolocation.start();
    }
  });
}
```

**Comment by kevando** [comment]
Thank you! 

I've added this to my app and I'm to walk to the far Chipotle for lunch and hopefully when I get back there is some new data.

One thing I didn't see a clear example on. Right now `onLocation()` writes to my firebase database so that I can be sure that it works. On the production app, I don't think that's necessary and would prefer to pull the user's location from some local device storage. I think that's possible, but I didn't see any example code.

**Comment by christocracy** [comment]
Configuring `debug: true`, you will **hear** and **see** the plugin working.
