### ISSUE TITLE
Adding GeoFences from Database not working

### ISSUE THREAD

**Issue by Danish-Wajid** [transistorsoft/react-native-background-geolocation#1570]
## Your Environment
* Plugin version: ^4.7.1
* Platform: iOS 
* OS version:15.5
* Device manufacturer / model:13 pro max
* React Native version (`react-native -v`):0.67.3
* Plugin config BackgroundGeolocation.ready(
    { distanceFilter = 6; elasticityMultiplier = 3;

      //activityType: BackgroundGeolocation.ACTIVITY_TYPE_FITNESS,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      disableElasticity: true,
      stopTimeout: 5,
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
      preventSuspend: true,
      headers: {
        "X-FOO": "bar",
      },
      locationAuthorizationRequest: "Always",
      disableLocationAuthorizationAlert: true,
  
    }
 

## Expected Behavior

Adding multiple geofences from Database but it don't detect the geoFence but when we put hardcoded geofence not from the Database the Geofence works. Can you guide us at which point will have to add Geofences that we get from the API? I will be keeping an eye out for your response. Thanks!

**Comment by christocracy** [comment]
The data from your "database" is likely incorrect.

**Comment by Danish-Wajid** [comment]
Thanks for your response,

Data from database is correct we verified after adding we call this method (await BackgroundGeolocation.getGeofences()) and the geoFence is there but while tracking it always cross the GeoFence without detecting.

**Comment by christocracy** [comment]
Show me this data and the exact code you’re using to interact with it.

made you sure you don’t have your lat mixed up with your lng?

**Comment by Danish-Wajid** [comment]
As you can see that we are calling getGeofences() before background location started:

const MainApp = ({ isLoggedIn = false }) => {
  useEffect(() => {
    if (isLoggedIn) {
      getGeofences();
      initBackgroundFetch(); // <-- optional
      initBackgroundGeolocation();

      saveLocations();
    }

Here is the function for API calling:

export const getGeofences = async () => {
  const res = await APIHandler("post", "geoFence/get", { userId });
  if (res) {
    console.log("res", res, "geofences", geofences);
    geofences = res;
    return res;
  }
};

Response of API is: 	id: 8, identifier: "Apple", latitude: "37.33252881",longitude: "-122.05571688”, radius: 200, userId: 123


const onGeofence = ({ action, timestamp, id }) => {
  if (action == "ENTER") {
    BackgroundGeolocation.startGeofences();
    trackGeofence({
      geoFenceId: id,
      geoFenceTrackingId: null,
      entryTimestamp: timestamp,
      exitTimestamp: null,
    });
  } else if (action == "EXIT") {
    BackgroundGeolocation.start();
    trackGeofence({
      geoFenceId: 4,
      geoFenceTrackingId: trackingData.id,
      entryTimestamp: trackingData.entryTimestamp,
      exitTimestamp: timestamp,
    });
  }
};

export const initBackgroundGeolocation = async () => {
  geofences = await getGeofences();
  await BackgroundGeolocation.removeGeofences();
  await BackgroundGeolocation.addGeofences(geofences);

  subscribe(
    BackgroundGeolocation.onGeofence((geofenceData) => {
      reactotron.log("[geofence] ", geofenceData, geofences);

      const {
        action,
        identifier: geofence,
        location: { timestamp },
      } = geofenceData;

      const { id } = geofences.filter((elem) => elem.identifier == geofence)[0];

      onGeofence({ timestamp, action, id });
    })
  );

 subscribe(
    BackgroundGeolocation.onGeofence((event) => {
      reactotron.log("[onGeofence]", event);
    })
  );


  subscribe(
    BackgroundGeolocation.onLocation(
      async (location) => {
        // BackgroundGeolocation.removeGeofences();
        reactotron.log(
          "[onLocation]",
          location,
          await BackgroundGeolocation.getGeofences()
        );
      },
      (error) => {
        reactotron.warn("[onLocation] ERROR: ", error);
      }
    )
  );

**Comment by SharfMohiuddin** [comment]
One thing to add this (trackGeofence) function is actually returns the Entry and Exit from the GeoFence:

const trackGeofence = async (req) => {
  const res = await APIHandler("post", "geoFence/track", req);
  if (res) {
    trackingData = res;
  }
};

**Comment by christocracy** [comment]
- do you know you can [syntax highlight your code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (with optional language)?
- Are you observing the plugin logs when you execute that code?  What do the plugin logs say when your geofences are consumed?

**Comment by Danish-Wajid** [comment]
I just verified that when you remove previous geofences and new ones like in the code given below 

```
    BackgroundGeolocation.removeGeofences();
    BackgroundGeolocation.addGeofences(geofences);
```
The plugin doesn't not trigger geofences. But if i only add geofence without removing previous ones from the plugin  for first time  it doesn't trigger but next time when it will fetch the geofence from it's database added previously it works fine for those geofences. I think plugin is not synchronised with it's database in case of geofences at least. Can you help us with that?

About Plugin Logs, we can not see logs when geofence doesn't trigger because  ##On Geofence method doesn't trigger in this case.

**Comment by christocracy** [comment]
All plugin methods are *asynchronous*, like sending an http request to a server.

you need to **`await`** `removeGeofences` before calling `addGeofencee`

**Comment by christocracy** [comment]
>But what i found is that when i set `notifyOnExit:false` and `notifyOnEntry:false`.

Whey would you expect any geofence to fire when you set both those to false??

**Comment by Danish-Wajid** [comment]
It's an optional property so isn't geofences needs to be tracked even if you don't set them?

**Comment by christocracy** [comment]
They are *all* optional but you **MUST** choose one?

What's the point of registering a geofence that isn't configured to fire any events??

**Comment by Danish-Wajid** [comment]
Got it. I got confused by there optional nature because i'm not specifically setting them and they are false by default. Thanks for your help.
