### ISSUE TITLE
Background Task possible with this plugin?

### ISSUE THREAD

**Issue by iSaBo96** [transistorsoft/react-native-background-geolocation#1573]
Hello,i have a short question about this plugin. Is i possible to detect bluetooth device if an app is complety closed? Does this library works with the internal API from apple?

**Comment by christocracy** [comment]
This is a location-tracking plugin.  It has nothing to do with Bluetooth.

it is designed to track the location of devices even when completely closed.  It implements native location apis for both iOS and Android.
