### ISSUE TITLE
Android - background tracking service not working

### ISSUE THREAD

**Issue by anton654** [transistorsoft/react-native-background-geolocation#1574]
## Your Environment
* Plugin version: 4.8.2
* Platform: Android
* OS version: 10/12
* Device manufacturer / model: Xiaomi Poco x3 / Samsung A73
* React Native version (`react-native -v`): 0.67.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        BackgroundGeolocation.ready({
                distanceFilter = 10;
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                stopTimeout: 5,
                debug: true,
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                stopOnTerminate: false,
                startOnBoot: true,
                batchSync: true,
                maxBatchSize: 20,
                autoSync: true,
                preventSuspend: true,
                locationAuthorizationRequest: "Always",
                heartbeatInterval: 60,
                foregroundService: true,
                notification: notification
        }
```

## Expected Behavior
Tracking location in a background

## Actual Behavior
onLocation fired few times in a row on start and not fired after that (not in foreground & not in background), fired only if I call getCurrentPosition(). "is_moving" flag always false even if location changes (with mock app, I can see the changes in maps app).

## Context

I'm disable all the battery saving features in both devices.

**Comment by christocracy** [comment]
The plugin tracks location when the device **is detected to be physically moving**.

mock location apps do not cause the device to *physically* move.

you can either shake the device vigorously to simulate walking or manually call the method .changePace(true).

also see wiki *Debugging* where there is mention of testing with *Mock* apps.
