### ISSUE TITLE
iOS: blue pill not shown on device, despite appearing on simulator

### ISSUE THREAD

**Issue by savv** [transistorsoft/react-native-background-geolocation#1575]
## Your Environment
* Plugin version: 4.8.2
* Platform: iOS
* OS version: 16.0 (both device and Sim)
* Device manufacturer / model: device: iPhone 13 Pro; Sim: iPhone 14
* React Native version (`react-native -v`): 0.68.2 (`yarn react-native -v` returns "error: unknown option `-v'" for me)
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 20,
  foregroundService: true,

  locationAuthorizationRequest: 'WhenInUse',
  disableLocationAuthorizationAlert: true,
}
```

## Expected Behavior
I expect: a) the blue pill to show up on the top left; b) the library to continue tracking locations into Sqlite.

## Actual Behavior
Both work on the Simulator, with 'City Bicycle Ride': the blue pill shows up (see screenshot [1]) and the location is tracked every few meters [2]. Neither work when I run on my phone: I don't get a blue pill; and there are no locations in getLocations().

## Steps to Reproduce
1. Call ready() with the config above, then start()
2. send the app to the background
3. open it again
4. look at the history from getLocations

## Context
We would like to get GPS line tracks using the users' locations for short amounts of time (5-45 minutes), without having to request the 'Always' permission. Our users are moving along at around 5-15km/h and we want a resolution of 10-20 meters.

## Screenshots

[1]
![image](https://user-images.githubusercontent.com/747519/197739939-58976766-5888-4c49-b3a4-104e5d6aef66.png)

[2]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/747519/197740001-b8331e0f-e5c7-4b6c-b268-5bdd00238d7e.png">

**Comment by christocracy** [comment]
With `WhenInUse` permission, you must engage the *moving* state while your app is in the foreground, like a *Jogging App*'s [Start Workout] button.

```
BackgroundGeolocation.changePace(true)
```

With `WhenInUse` permission, the plugin **cannot** *automatically* track location in the background when the device is detected to be moving.

```
await BackgroundGeolocation.start();
await BackgroundGeolocation.changePace(true);
```

**Comment by savv** [comment]
Thanks a lot, this fixed the initial problem for me. However, I noticed that tracking stopped unexpectedly after a while. I noticed that while cycling the library stopped tracking me (possibly when I stopped at a traffic light?) and it started again only after ~1km, but without capturing points every 20 meters.

 Is there a way to make the change of pace "sticky"? Or what causes this stop? Should we be using the library in a different way, for our use case? (GPS tracks for ~20min at 15m resolution, moving at 10km/h ideally without Always permission).

(Apologies if I missed this in the docs, I did look.)

<img width="158" alt="image" src="https://user-images.githubusercontent.com/747519/198018395-13dcbd37-4dad-43a2-b633-ee075879b1bb.png">

**Comment by christocracy** [comment]
Read the wiki “Philosophy of Operation”.

also read the api docs Config.stopTimeout.

**Comment by savv** [comment]
Re: stopTimeout, I don't I stopped for anything close to 5 min, but I will try to increase it and see if it helps. Also, the "jump" due to the iOS geofence was closer to 1000m rather than 200m.

Thanks again, and sorry for all these questions. I guess it's hard to predict the right combination of options, even after reading all these. I will close this for now, but let me know if there's anything else I missed.
