### ISSUE TITLE
Showing Invalid license key message with the valid license key.

### ISSUE THREAD

**Issue by avijit-ordering** [transistorsoft/react-native-background-geolocation#1579]
I created a valid license key. I have set it into AndroidManifest.xml.

<meta-data android:name="com.transistorsoft.locationmanager.license" android:value="****" />
but still showing the LICENSE VALIDATION error message.

![download (1)](https://user-images.githubusercontent.com/16749307/198100161-f75acee8-689f-48f8-ab26-d2574f095ca8.png)

How can I solve it? Please help me.

"react-native": "^0.64.2",
"react-native-background-fetch": "^4.1.3",
"react-native-background-geolocation": "^4.8.2"

**Comment by christocracy** [comment]
Licensing issues are not handled in public.

email me your Order #, android/app/build.gradle and AndroidManifest
