### ISSUE TITLE
Question - Which code is used for a push notification in the example project?

### ISSUE THREAD

**Issue by iSaBo96** [transistorsoft/react-native-background-geolocation#1580]
Which code in the example project causes a push notification to be triggered? I ask this because before I use the package I want to understand the library better

**Comment by christocracy** [comment]
See api docs Config.debug.

those are “push” notifications, they’re *local* notifications.

**Comment by iSaBo96** [comment]
Thank you, i found something in the docs, but android only, is there for iOS?

**Comment by christocracy** [comment]
I don’t know what you mean.  Setting `debug: true` enables debug sound FX and local notifications on iOS (so you can hear and see the plugin working while out field-testing).

**Comment by iSaBo96** [comment]
That's what I got from the documentation. But where exactly are local notifications sent in the app, or how?

**Comment by christocracy** [comment]
You don’t have access to where the local notifications are sent.  That code is within the compiled library.

Those notifications are for debugging purposes only.  They are not for your production app.

If you want your own local notifications, you must use a 3rd party library specializing in that.

**Comment by iSaBo96** [comment]
Thanks for the info

**Comment by iSaBo96** [comment]
One more question about this. 
I have write a minimal example. I just want to send a local notification if the app (GPS Location changed) was called if the app is complety closed.

Which code will be used for this? 

I understood the documentation to say that no matter what happens in the background, the "ready" function must be called. Can you tell me what I am doing wrong here?

For now, I just want a push notification to be triggered when the location of the phone changes. I also want to do this as I want to better understand the plugin from them. 

Notifications are only triggered when the app is running, but in the background. When I tested your demo application, even when the app is completely closed, a background action is triggered.

I hope you understand what I mean.

Here is my minimal example:

App.tsx
```
import React from 'react';

import {
    Text,
    TouchableOpacity
} from 'react-native';

import PushNotificationIOS from '@react-native-community/push-notification-ios';
import BackgroundGeolocation, {Subscription} from "./src/react-native-background-geolocation";
import BackgroundFetch from "react-native-background-fetch";

const App = ({route, navigation}) => {
    const bgGeoEventSubscriptions:Subscription[] = [];

    const [events, setEvents] = React.useState<any[]>([]);
    const [enabled, setEnabled] = React.useState(false);

    React.useEffect(() => {
        initBackgroundGeolocation();
        return () => {
            unsubscribe();
        }
    }, []);

    const subscribe = (subscription:Subscription) => {
        bgGeoEventSubscriptions.push(subscription);
    }

    const unsubscribe = () => {
        bgGeoEventSubscriptions.forEach((subscription:Subscription) => subscription.remove() );
    }

    const initBackgroundGeolocation = async () => {
        subscribe(BackgroundGeolocation.onProviderChange((event) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onProviderChange',
                title: 'onProviderChange !',
                body: 'onProviderChange',
            });

            console.log('[onProviderChange]', event);
            addEvent('onProviderChange', event);
        }));

        subscribe(BackgroundGeolocation.onLocation((location) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onLocation',
                title: 'onLocation !',
                body: 'onLocation',
            });

            console.log('[onLocation]', location);
            addEvent('onLocation', location);
        }, (error) => {
            console.warn('[onLocation] ERROR: ', error);
        }));

        subscribe(BackgroundGeolocation.onMotionChange((location) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onMotionChange',
                title: 'onMotionChange !',
                body: 'onMotionChange',
            });

            console.log('[onMotionChange]', location);
            addEvent('onMotionChange', location);
        }));

        subscribe(BackgroundGeolocation.onGeofence((event) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onActivityChange',
                title: 'onActivityChange !',
                body: 'onActivityChange',
            });

            console.log('[onGeofence]', event);
            addEvent('onGeofence', event);
        }));

        subscribe(BackgroundGeolocation.onConnectivityChange((event) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onConnectivityChange',
                title: 'onConnectivityChange !',
                body: 'onConnectivityChange',
            });

            console.log('[onConnectivityChange]', event);
            addEvent('onConnectivityChange', event);
        }));

        subscribe(BackgroundGeolocation.onEnabledChange((enabled) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onEnabledChange',
                title: 'onEnabledChange !',
                body: 'onEnabledChange',
            });

            console.log('[onEnabledChange]', enabled);
            addEvent('onEnabledChange', {enabled: enabled});
        }));

        subscribe(BackgroundGeolocation.onHttp((event) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onHttp',
                title: 'onHttp !',
                body: 'onHttp',
            });

            console.log('[onHttp]', event);
            addEvent('onHttp', event);
        }));

        subscribe(BackgroundGeolocation.onActivityChange((event) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onActivityChange',
                title: 'onActivityChange !',
                body: 'onActivityChange',
            });

            console.log('[onActivityChange]', event);
            addEvent('onActivityChange', event);
        }));

        subscribe(BackgroundGeolocation.onPowerSaveChange((enabled) => {
            PushNotificationIOS.addNotificationRequest({
                id: 'onPowerSaveChange',
                title: 'onPowerSaveChange !',
                body: 'onPowerSaveChange',
            });

            console.log('[onPowerSaveChange]', enabled);
            addEvent('onPowerSaveChange', {isPowerSaveMode: enabled});
        }));

        const state = await BackgroundGeolocation.ready({
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            distanceFilter: 10,
            stopOnTerminate: false,
            startOnBoot: true
        });

        addEvent('Current state', state);
        BackgroundGeolocation.start();
    };

    const initBackgroundFetch = async () => {
        await BackgroundFetch.configure({
            minimumFetchInterval: 15,
            stopOnTerminate: true
        }, (taskId) => {
            console.log('[BackgroundFetch] ', taskId);

            BackgroundFetch.finish(taskId);
        }, (taskId) => {
            console.log('[BackgroundFetch] TIMEOUT: ', taskId);
            BackgroundFetch.finish(taskId);
        });
    }

    const addEvent = (name:string, params:any) => {
        let timestamp = new Date();
        const event = {
            expanded: false,
            timestamp: `${timestamp.getMonth()}-${timestamp.getDate()} ${timestamp.getHours()}:${timestamp.getMinutes()}:${timestamp.getSeconds()}`,
            name: name,
            params: JSON.stringify(params, null, 2)
        }
        setEvents(previous => [...previous, event]);
    }

    const onClickEnable = (value:boolean) => {
        if (value) {
            BackgroundGeolocation.start();
        } else {
            BackgroundGeolocation.stop();
        }
    }

    return (
        <TouchableOpacity onPress={() => {
            PushNotificationIOS.addNotificationRequest({
                id: 'gpsTestApp',
                title: 'App.js !',
                body: 'Aufruf in App.js',
            });
            onClickEnable(true);
        }}>
            <Text style={{top: 200, left: 50, color: 'white'}}>Click me for a notification</Text>
        </TouchableOpacity>
    );
}

var PushNotification = require('react-native-push-notification');
PushNotification.configure({
    onRegister: function(token) {
        console.log( 'TOKEN:', token );
    },
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
    },
    permissions: {
        alert: true,
        badge: true,
        sound: true
    },
    popInitialNotification: true,
    requestPermissions: true,
});

export default App;

```

Additional information: I have installed the app (iOS) via TestFlight directly on my phone natively to not simulate this via XCode

**Comment by christocracy** [comment]
Do you see your `console.log('[onHttp]', event);` in the logs?

**Comment by iSaBo96** [comment]
Since the app runs directly on the smartphone, I have no console available. So I added the notificationa to get an output. But I do not get an onHttp output

**Comment by mikehardy** [comment]
You may plug the phone into a computer, open Console.app, and access device logs on real iOS devices that way

**Comment by iSaBo96** [comment]
But I want to test how the app behaves when it is completely closed. I can't test this when the phone is connected to the computer via USB, because I can't change my location from the phone.

I have tried their demo app. It also sends out notifications when the app is completely closed. I set up a TestFlight on my phone so that I could install the app on my phone.

I would just like to test this behavior. Minimal example, that the app sends out a notification when the location of a phone has changed, even if the app is completely closed.

**Comment by christocracy** [comment]
Or boot your app in XCode and look at the logs there.

**Comment by iSaBo96** [comment]
But I can't do that if I have completely closed the app after running it through xcode, can I? Or do I just have a thinking error?

**Comment by christocracy** [comment]
See api docs `Logger`.  You can print messages to the plugin SQLite logs.  Then retrieve them via method `.emailLog(email)`

**Comment by christocracy** [comment]
Also see api docs Config.debug.  The plugin can emit its own local-notification and debug sound FX to let you know when the plugin is working.

**Comment by iSaBo96** [comment]
I will, thank you. But again briefly to the basic question. Does the minimal example code first do everything so that an action is executed even if the app is completely closed?

I don't want to have the debug mode on to test a real presence possibility for me. Therefore it is important for me to send own local notifications. Important is: I repeat myself, sorry that the app was completely closed :)

**Comment by christocracy** [comment]
When an iOS app is terminated, everything is terminated.  When the device moves about 200 meters, the OS relaunches your app in the background and the plugin begins tracking and emitting locations to onLocation event.

you can easily test terminated behaviour in XCode sim with location simulated with *Freeway Drive*.

**Comment by iSaBo96** [comment]
Thank you for the hint, i will test this

**Comment by iSaBo96** [comment]
@christocracy I have test it, i can you the "freeway drive" only on a simulator? Not on a plugged in real device, or?

And does "onLocation" only be fired if the app is on the background or everytime? If this function will fired also if an app is active, how can i check if the app is on the background? Should i use "AppState.currentState" or is there something in the package for this issue?

**Comment by iSaBo96** [comment]
And can i say with a configuration that "onLocation" only be called after 2 Minutes? Or is just 200meter possible?

**Comment by christocracy** [comment]
> Question - Which code is used for a push notification in the example project?

This **closed** issue answered your question.

Issues are not personal support thread for every question you have.

read the api docs.  Read **every** attribute of the `State`.  See wiki *Debugging*.
