### ISSUE TITLE
Long time between the first location data and the second location data

### ISSUE THREAD

**Issue by seongbinyun** [transistorsoft/react-native-background-geolocation#1581]
## Your Environment
* Plugin version: 4.9.3
* Platform: both iOS and Android
* OS version: iOS 15.6.1 android 12
* Device manufacturer / model: iPhone13, galaxy S10
* React Native version (`react-native -v`): `react-native -0.68.2`
* Plugin config
index.tsx
```javascript <!-- Syntax-highlighting:  paste your code below -->
useEffect(() => {
    BackgroundGeolocation.ready(
      {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        disableElasticity: true,
        stopTimeout: 10,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        locationAuthorizationRequest: 'WhenInUse',
        startOnBoot: true,
        preventSuspend: true,
        heartbeatInterval: 60,
        stationaryRadius: 25,
        showsBackgroundLocationIndicator: true,
      }
    );
    return () => {};
  }, []);
```

```javascript <!-- Syntax-highlighting:  paste your code below -->
export const startCollectingLocation = async (pathData: {
  [key: string]: any;
}) => {
  await BackgroundGeolocation.start();
  const {
    carrierId,
    driverId,
    recordId,
    allocationId,
  }: { [key: string]: any } = pathData;
  BackgroundGeolocation.onLocation(
    async (location: { [key: string]: any }) => {
      const tracking = store.getState().user?.tracking;
      if (location && location?.error !== 0 && location?.sample !== true) {
        await firebase
          .app()
          // .database(DATABASE_URL_PRO)
          .database(DATABASE_URL_DEV)
          .ref(
            `/${carrierId}/${driverId}/${recordId}/${allocationId}/${new Date(
              location.timestamp,
            ).getTime()}`,
          )
          .set({
            lat: location.coords.latitude,
            lng: location.coords.longitude,
          })
          .then(() => {
            store.dispatch(setTracking(tracking + 1));
          })
          .catch((error) => console.log('error', error));
      }
    },
    (error) => {
      console.log('error', error);
    },
  );
};

export const stopCollectingLocation = async () => {
  await BackgroundGeolocation.removeListeners();
  await BackgroundGeolocation.stop();
  store.dispatch(setTracking(0));
};
```

```
const tracking = store.getState().user?.tracking;
if (tracking !== 0) {
    await stopCollectingLocation();
}
await startCollectingLocation(pathData);
```

## Expected Behavior

BackgroundGeolocation.start() When started, the location data goes into the Firebase DB with BackgroundGeolocation.onLocation .
The first, second, and third data are entered at regular intervals.

## Actual Behavior

However, after the first data enters, the second data comes in after a long time. After the second data, data enters in a normal cycle.

![스크린샷 2022-11-07 오후 12 27 47](https://user-images.githubusercontent.com/109501902/200220777-d7a6ac94-3f83-4eb6-b55f-349ab3d46ff4.png)

## Steps to Reproduce

1. 
2.
3.
4.

## Context

Android set locationUpdateInterval to 5 seconds, but the interval between the first data and the second data was equally long.
Sometimes it took a few minutes between the first data and the second data, sometimes it took tens of seconds.
After that, data comes in at regular intervals of several seconds.
The user was still moving during BackgroundGeolocation.start() and BackgroundGelocation.stop().

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You need to specify what the `State.isMoving` was with the first location.

mare you aware it can take at least 200 meters of movement before the plugin turns on location-services and begins tracking, as described in the wiki *Philosophy of Operation*?

**Comment by christocracy** [comment]
Also, you should register event-listeners *before* calling .start() or you risk missing initial events.

**Comment by seongbinyun** [comment]
The problem has been resolved.
very thank you
