### ISSUE TITLE
Trying to use a module that is not supported in Expo Go

### ISSUE THREAD

**Issue by dm-appricotsoft** [transistorsoft/react-native-background-geolocation#1583]
## Your Environment
* Plugin version: ^4.9.3
* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.69.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const MoveTest: React.FunctionComponent = () => {
 

    const [enabled, setEnabled] = React.useState(false);
    const [location, setLocation] = React.useState('');

    React.useEffect(() => {
        /// 1.  Subscribe to events.
        const onLocation: Subscription = BackgroundGeolocation.onLocation(
            (location) => {
                console.log('[onLocation]', location);
                setLocation(JSON.stringify(location, null, 2));
            }
        );

        const onMotionChange: Subscription =
            BackgroundGeolocation.onMotionChange((event) => {
                console.log('[onMotionChange]', event);
            });

        const onActivityChange: Subscription =
            BackgroundGeolocation.onActivityChange((event) => {
                console.log('[onMotionChange]', event);
            });

        const onProviderChange: Subscription =
            BackgroundGeolocation.onProviderChange((event) => {
                console.log('[onProviderChange]', event);
            });

        /// 2. ready the plugin.
        BackgroundGeolocation.ready({
            // Geolocation Config
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            // Activity Recognition
            stopTimeout: 5,
            // Application config
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        }).then((state) => {
            setEnabled(state.enabled);
            console.log(
                '- BackgroundGeolocation is configured and ready: ',
                state.enabled
            );
        });

        return () => {
            // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
            // during development live-reload.  Without this, event-listeners will accumulate with
            // each refresh during live-reload.
            onLocation.remove();
            onMotionChange.remove();
            onActivityChange.remove();
            onProviderChange.remove();
        };
    }, []);

    /// 3. start / stop BackgroundGeolocation
    React.useEffect(() => {
        if (enabled) {
            BackgroundGeolocation.start();
        } else {
            BackgroundGeolocation.stop();
            setLocation('');
        }
    }, [enabled]);

    return (
        <View style={{ alignItems: 'center' }}>
            <Text>Click to enable BackgroundGeolocation</Text>
            <Switch value={enabled} onValueChange={setEnabled} />
            <Text style={{ fontFamily: 'monospace', fontSize: 12 }}>
                {location}
            </Text>
        </View>
    );
};
```

## Expected Behavior
use expo start and applications is load

## Actual Behavior
Error 
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/109971288/200577844-d1465c0b-8a41-450b-b7ae-f20ee7c23823.png">

## Steps to Reproduce

1. Install everything by this instruction https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Paste your package.json.

When you paste a screenshot of an error message, it makes it impossible to copy/paste the error for searching.  Don’t do that.  Paste **text**

**Comment by dm-appricotsoft** [comment]
{
  "name": "test-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll",
    "postinstall": "patch-package",
    "lint": "eslint . --ext .ts,.tsx,.js",
    "lint:fix": "npm run lint --fix",
    "prettier": "npx prettier . --check",
    "prettier:fix": "npx prettier . --write",
    "format": "npm run prettier:fix && npm run lint:fix",
    "export:web:analyze": "cross-env BundleAnalyzer=true npx expo export:web"
  },
  "config": {
    "pre-git": {
      "enabled": true,
      "pre-commit": [
        "npx lint-staged"
      ],
      "post-commit": [
        "./scripts/reset-config.sh"
      ]
    }
  },
  "lint-staged": {
    "*.ts": [
      "npm run prettier:fix"
    ],
    "*.tsx": [
      "npm run prettier:fix"
    ],
    "*.js": [
      "npm run prettier:fix"
    ]
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@apollo/client": "^3.6.9",
    "@biswap-org/sdk": "^1.0.3",
    "@ethersproject/shims": "^5.6.0",
    "@expo/config-plugins": "^5.0.0",
    "@expo/ngrok": "^2.4.3",
    "@expo/vector-icons": "^13.0.0",
    "@expo/webpack-config": "^0.17.0",
    "@inline-svg-unique-id/react": "^1.2.3",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-community/netinfo": "9.3.0",
    "@react-native-firebase/app": "~15.4.0",
    "@react-native-masked-view/masked-view": "0.2.7",
    "@react-navigation/bottom-tabs": "^6.3.3",
    "@react-navigation/material-top-tabs": "^6.2.3",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "@react-navigation/stack": "^6.3.1",
    "@sentry/react-native": "4.2.2",
    "@sentry/tracing": "^7.16.0",
    "@svgr/webpack": "^5.5.0",
    "cannon-es": "^0.20.0",
    "cannon-es-debugger": "^1.0.0",
    "crypto-js": "^4.1.1",
    "date-fns": "^2.29.2",
    "dayjs": "^1.11.4",
    "ethers": "^5.7.1",
    "expo": "~46.0.9",
    "expo-apple-authentication": "~4.3.0",
    "expo-application": "~4.2.2",
    "expo-asset": "~8.6.1",
    "expo-auth-session": "~3.7.1",
    "expo-av": "~12.0.4",
    "expo-barcode-scanner": "~11.4.0",
    "expo-blur": "~11.2.0",
    "expo-build-properties": "~0.3.0",
    "expo-camera": "~12.3.0",
    "expo-clipboard": "~3.1.0",
    "expo-constants": "~13.2.4",
    "expo-dev-client": "~1.3.0",
    "expo-device": "~4.3.0",
    "expo-file-system": "~14.1.0",
    "expo-firebase-analytics": "~7.2.0",
    "expo-font": "~10.2.0",
    "expo-gl": "~11.4.0",
    "expo-gradle-ext-vars": "^0.1.1",
    "expo-haptics": "~11.3.0",
    "expo-image-manipulator": "~10.4.0",
    "expo-image-picker": "~13.3.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-linking": "~3.2.2",
    "expo-localization": "~13.1.0",
    "expo-location": "~14.3.0",
    "expo-mail-composer": "~11.3.0",
    "expo-media-library": "~14.2.0",
    "expo-notifications": "~0.16.1",
    "expo-random": "~12.3.0",
    "expo-screen-orientation": "~4.3.0",
    "expo-secure-store": "~11.3.0",
    "expo-sensors": "~11.4.0",
    "expo-sharing": "~10.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-store-review": "~5.3.0",
    "expo-system-ui": "~1.3.0",
    "expo-task-manager": "~10.3.0",
    "expo-three": "^6.2.0",
    "expo-updates": "~0.14.6",
    "expo-web-browser": "~11.0.0",
    "firebase": "^9.10.0",
    "formik": "^2.2.9",
    "fs": "^0.0.1-security",
    "geolib": "^3.3.3",
    "html2canvas": "^1.4.1",
    "i18n-js": "^4.0.0-alpha.14",
    "ignore-warnings": "^0.2.1",
    "lodash": "^4.17.21",
    "lottie-react": "^2.3.1",
    "lottie-react-native": "5.1.3",
    "patch-package": "^6.4.7",
    "path": "^0.12.7",
    "prop-types": "^15.8.1",
    "react": "18.0.0",
    "react-blur": "^1.1.1",
    "react-cropper": "^2.1.8",
    "react-dom": "18.0.0",
    "react-error-overlay": "^6.0.9",
    "react-helmet": "^6.1.0",
    "react-native": "0.69.6",
    "react-native-animation-hooks": "^1.0.1",
    "react-native-background-fetch": "^4.1.5",
    "react-native-background-geolocation": "^4.9.3",
    "react-native-cached-image": "^1.4.3",
    "react-native-countdown-circle-timer": "^3.0.9",
    "react-native-curved-bottom-bar": "^2.1.2",
    "react-native-dotenv": "^3.3.1",
    "react-native-draggable": "^3.3.0",
    "react-native-draggable-flatlist": "^3.1.2",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-fade": "^2.1.1",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-logs": "^5.0.1",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^14.0.0",
    "react-native-pager-view": "5.4.24",
    "react-native-qrcode-svg": "^6.1.2",
    "react-native-read-more-text": "^1.1.2",
    "react-native-reanimated": "~2.9.1",
    "react-native-reanimated-carousel": "^3.0.6",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-shadow-2": "^6.0.6",
    "react-native-size-matters": "^0.4.0",
    "react-native-svg": "12.3.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-svg-web": "^1.0.9",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-toast-message": "^2.1.5",
    "react-native-uuid": "^2.0.1",
    "react-native-view-shot": "3.3.0",
    "react-native-walkthrough-tooltip": "^1.4.0",
    "react-spinkit": "^3.0.0",
    "react-use-intercom": "^2.0.0",
    "resize-observer-polyfill": "^1.5.1",
    "rn-range-slider": "^2.2.2",
    "sentry-expo": "^5.0.3",
    "text-encoding-polyfill": "^0.6.7",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@babel/eslint-parser": "^7.18.9",
    "@babel/preset-typescript": "^7.18.6",
    "@trivago/prettier-plugin-sort-imports": "^3.3.0",
    "@types/lodash": "^4.14.186",
    "@types/react": "~17.0.50",
    "@types/react-dom": "^18.0.6",
    "@types/react-native": "~0.69.1",
    "@types/react-native-read-more-text": "^1.0.1",
    "@types/three": "^0.144.0",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.36.0",
    "@typescript-eslint/parser": "^5.36.0",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.5",
    "babel-plugin-dotenv-import": "^2.2.0",
    "babel-plugin-react-inline-svg-unique-id": "^1.3.1",
    "babel-plugin-react-native-web": "^0.18.9",
    "cannon-es": "^0.20.0",
    "cross-env": "^7.0.3",
    "deep-object-diff": "^1.1.7",
    "deprecated-react-native-prop-types": "^2.3.0",
    "env-file-parser": "^1.0.0",
    "eslint": "8.22.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.0.0",
    "find-config": "^1.0.0",
    "husky": "^8.0.1",
    "jest": "^26.6.3",
    "jest-expo": "^46.0.0",
    "lint-staged": "^13.0.3",
    "pre-git": "^3.17.1",
    "prettier": "2.7.1",
    "react-native-bundle-visualizer": "^3.1.1",
    "typescript": "^4.6.3",
    "url-loader": "^4.1.1",
    "webpack-bundle-analyzer": "^4.6.1"
  },
  "resolutions": {
    "@types/react": "~17.0.50",
    "//comment//react-error-overlay": "See https://github.com/facebook/create-react-app/issues/11773",
    "react-error-overlay": "6.0.9"
  },
  "private": true,
  "release": {
    "analyzeCommits": "simple-commit-message"
  }
}

**Comment by dm-appricotsoft** [comment]
Error 
```
Invariant Violation: Your JavaScript code tried to access a native module that doesn't exist. 

If you're trying to use a module that is not supported in Expo Go, you need to create a development build of your app. See https://docs.expo.dev/development/introduction/ for more info.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.8.113:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

**Comment by christocracy** [comment]
Did you do this?

```
eas build --profile development --platform android
```

**Comment by dm-appricotsoft** [comment]
its running only in build?

**Comment by christocracy** [comment]
The *Setup docs* explicitly directed you to run that.

**Comment by dm-appricotsoft** [comment]
yes, but i try to run it on ios expo

**Comment by dm-appricotsoft** [comment]
its will be work only in dev builds for ios and android, right?

**Comment by christocracy** [comment]
Then I guess you want modify `—platform` as desired.

**Comment by dm-appricotsoft** [comment]
Ok thank you very match for you time and help)
