### ISSUE TITLE
After updating react native to 68 version , it continuosly emitting event,, how to to resolve it , thank you

### ISSUE THREAD

**Issue by Mohd-Areeb-Safvi** [transistorsoft/react-native-background-geolocation#1585]
Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/93810761/200744547-badc2f3b-c948-43e0-9839-d5a48e487dc7.png">
<img width="514" alt="Screenshot 2022-11-09 at 10 46 11 AM" src="https://user-images.githubusercontent.com/93810761/200744723-b6192aff-81b9-46bc-8b28-da06855ea8d2.png">

**Comment by christocracy** [comment]
That’s Not coming from this plugin.
