### ISSUE TITLE
Question for config details

### ISSUE THREAD

**Issue by j1h00** [transistorsoft/react-native-background-geolocation#1587]
## Your Environment
* Plugin version: 4.9.3
* Platform: Android & Ios
* OS version: 12
* React Native version (`react-native -v`): 0.68.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
// config 
BackgroundGeolocation.ready({
  // Geolocation Config
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  // Activity Recognition
  stopTimeout: 5,
  // Application config
  debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
  startOnBoot: false, // <-- Auto start tracking when device is powered-up.

  foregroundService: true,
  showsBackgroundLocationIndicator: true,
})
// ... 
// getCurrentPosition
const location = await BackgroundGeolocation.getCurrentPosition({
  timeout: 5, // 30 second timeout to fetch location
  maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
  desiredAccuracy: 10, // Try to fetch a location with an accuracy of `10` meters.
  samples: 3, // How many location samples to attempt.
});


```

Hi, Thanks for making this awesome library. 

Our team purchased STARTER pack few days ago, and we're building Running tracking app similar to Nike Run. 
We've been trying to figure out proper way to use this library and how to set config values, in order to get more accurate locations and real-time speeds.  

Here's our situation. 
We need to check speed every two seconds, to find out if user's keeping target pace such as (1km/h ~ 6km/h) , 
For android, we use 'react-native-background-timer' to set timer and after `BackgroundGeolocation.ready().then(() => BackgroundGeolocation.start())`, we start timer and call `BackgroundGeolocation.getCurrentPosition()` every two seconds. 
In this way, seems like everything works fine except foreground service + geolocation notification(on status bar) keeps turning on and off. Is this behavior normal and should not call getCurrentPosition every two seconds? 

Also, Is there any example for `.ready()` configs to track accurate real time speed? 

</details>

**Comment by christocracy** [comment]
The iOS native location api is strictly distance-based.

Android allows time-based updates (see Config.locationUpdateInterval) but the Android api docs clearly state that this interval is only a suggestion.  Updates may arrive slower or faster than your desired rate.

there is no need to manually *calculate* speed.  Speed is provided by gps with each location update.

also the lowest possible accuracy of a gps location is ~5m.  If you’re manually calculating distance between two points for your speed calculation, there’s already 10m of error.

**Comment by kevinProground** [comment]
Hi,
We are not calculating speed. We do get the speed provided by your GPS module.
Our method of getting this speed is to call `BackgroundGeolocation.getCurrentPosition()` every two seconds.
We need the speed often because we want to show the current speed of the user.
If they slow down, we want the speed to slow down as fast as possible. (Just like Nike Run)
We are posting this question because...

1. We are not sure whether using `BackgroundGeolocation.getCurrentPosition()` every two seconds is the correct approach.
2. We were playing around with the configs (like the first post, ex. timeout, maximumAge, desiredAccuracy, samples) to find the best combination, but wanted to hear your suggestion.

Thank you!

**Comment by christocracy** [comment]
If you’re tracking a run, then presumably the UI has some sort of [Start Workout] button where you’d call `.changePace(true)` after `.start()`, placing the plugin into the *moving* state with location-services kept on (in addition to the foreground notification).

then calling .getCurrentPosition will not experience the notification oscillating on/off.

see the wiki *Philosophy of Operation*.

**Comment by j1h00** [comment]
Thanks for answering.

We found that speed accuracy returned from `getCurrentPosition` is not accurate in Xiaomi android phones. A post linked below says that Xiaomi doesn't support native Android fused location provider, but use their own package com.xiaomi.location.fused. Is this the reason of inaccuracy and Is there anything we can try?

https://new.c.mi.com/global/post/151132

**Comment by christocracy** [comment]
I don’t know anything about this.

the plugin has no control over the decisions of some particular manufacturer.

this plugin is developed according to the public Android api docs.

**Comment by j1h00** [comment]
Hi @christocracy. 

I have questions. When using getCurrentPosition, iOS always gives accuracy arround 14.2m, which seems pretty low. 

1. When setting Config.desiredAccuracy as DESIRED_ACCURACY_HIGH, which one does this library uses between kCLLocationAccuracyBest and kCLLocationAccuracyNearestTenMeters? 
2. Does getCurrentPosition uses the same Config.desiredAccuracy set by BackgroundGeolocation.ready()?

**Comment by christocracy** [comment]
- kCLLocationAccuracyBest
- no.  It uses kCLLocationAccuracyBest always.
- CurrentPositionRequest.desiredAccuracy is not the same as desiredAccuracy above:  it represents the accuracy you will be satisfied with over multiple samples, where the CurrentPositionRequest can stop sampling and return the current best recorded location.
