### ISSUE TITLE
How can I config to track device location interval time-based on Android

### ISSUE THREAD

**Issue by vandiepbui** [transistorsoft/react-native-background-geolocation#1589]
## Your Environment
* Plugin version: 4.9.3
* Platform: iOS or Android
* OS version: 11
* Device manufacturer / model: Samsung A50s
* React Native version (`react-native -v`): 0.68.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    await BackgroundGeolocation.ready({
      // Debug
      reset: false,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // Geolocation
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 0,
      stopTimeout: 5,
      preventSuspend: true,
      heartbeatInterval: 60,
      locationUpdateInterval: 60000,
      fastestLocationUpdateInterval: 60000,
      stationaryRadius: 0,
      // Permissions
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title:
          "Allow {applicationName} to access this device's location even when closed or not in use.",
        message:
          'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      },
      // Application
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
    });
```

## Expected Behavior

I expect the plugin return device location interval time which configured via `locationUpdateInterval` and `fastestLocationUpdateInterval`. When triggering `BackgroundGeolocation.start()` the plugin should turn ON location service and device location should be returned immediately via `BackgroundGeolocation.onLocation` event listener. And the next location should be returned after interval time-based (1 minute with my situation) until calling `BackgroundGeolocation.stop()`.

## Actual Behavior

The `BackgroundGeolocation.onLocation` event is trigged multiple time in the first time build app (DEBUG mode)
It just works with interval time-based after I call `BackgroundGeolocation.stop()` then call `BackgroundGeolocation.start()` again.

## Steps to Reproduce

1. Open app
2. Accept location permissions
3. Click on Start button which call `BackgroundGeolocation.start()`
4. Wait a few minutes for tracking device locations
5. Click on Stop button which call `BackgroundGeolocation.stop()`

**Comment by christocracy** [comment]
Do you know that the plugin tracks location **only when the device is detected to be moving**?

When the device is sitting stationary, the plugin has turned off location-services to conserve energy.  

Read the wiki [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

**Comment by vandiepbui** [comment]
I know that. I use `changePace` to bypass and onLocation event return device location with `is_moving: true` but the problem is The BackgroundGeolocation.onLocation event is trigged multiple time in the first time build app instead of one time then waiting 1 minute as config.
Here is my code when click on Start button:
  ` BackgroundGeolocation.start().then(
        state => !state.isMoving && BackgroundGeolocation.changePace(true),
      );`

**Comment by christocracy** [comment]
Have you carefully read the api docs for onLocation?

**Comment by vandiepbui** [comment]
I have resolved the issue on Android by ignoring sample locations. thanks so much!
