### ISSUE TITLE
How can I run javascript codes in onLocation callback in background (android/ios)

### ISSUE THREAD

**Issue by geongun20** [transistorsoft/react-native-background-geolocation#1591]
## Your Environment
* Plugin version: 4.9.3
* Platform: Android / iOS
* OS version: 
* Device manufacturer / model: 
* React Native version (`react-native -v`): 0.68.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        BackgroundGeolocation.ready({
          isMoving: true,
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          locationAuthorizationRequest: "WhenInUse",
          disableStopDetection: true,
          pausesLocationUpdatesAutomatically: false,
          preventSuspend: true,
          disableLocationAuthorizationAlert: true,
          heartbeatInterval: 60,
          stopOnTerminate: true,
          distanceFilter: 5,
          stopTimeout: 10000000,
          notification: {
            title: "string",
            text: "string",
          },
        }),
```

## Expected Behavior
callback in onLocation is called

## Actual Behavior
callback in onLocation is not called

....

## Steps to Reproduce
1. run app and register onLocation callback
2. go to background
3. check console.log in metro

## Context

Hi. I am building jogging app.

I have a problem javascript code in onLocation code is not walking when the app is in background mode.

How can I get event from onLocation in background mode?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The issue template is not optional:




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by geongun20** [comment]
@christocracy I edit my issue text!

**Comment by christocracy** [comment]
See API docs `.changePace` and `Config.locationAuthorizationRequest`

Also see Wiki "*Philosophy of Operation*".
