### ISSUE TITLE
Getting notification in every second

### ISSUE THREAD

**Issue by avijit-ordering** [transistorsoft/react-native-background-geolocation#1592]
![IMG_4451](https://user-images.githubusercontent.com/16749307/203219820-9fc117f5-eed4-4c30-94b5-8f99698eaf32.PNG)

I got constant notifications about my location. Like a new notification every second. How can I stop those notifications?

**Comment by christocracy** [comment]
Those are there to assist you during field-testing, so you can see in real-time that the plugin is working.

See api docs Config.debug
