### ISSUE TITLE
Distance-based filtering not work on Android/IOS

### ISSUE THREAD

**Issue by vandiepbui** [transistorsoft/react-native-background-geolocation#1593]
## Your Environment
* Plugin version: 4.9.3
* Platform: iOS/Android
* OS version: Android 11, IOS 16
* Device manufacturer / model: Samsung A50s, Iphone 12
* React Native version (`react-native -v`): 0.68.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    await BackgroundGeolocation.ready({
      // Debug
      reset: false,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // Geolocation
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10, //meters
      disableMotionActivityUpdates: true, //disable request physical activity permission
      disableElasticity: true, //disable auto-scale distance filter by speed
      elasticityMultiplier: 0, //disable auto-scale distance filter by speed
      disableStopDetection: true, //disable detect device state moving/stationary
      pausesLocationUpdatesAutomatically: false, //keep location service IOS turn ON
      stationaryRadius: 0,
      // Permissions
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title:
          "Allow {applicationName} to access this device's location even when closed or not in use.",
        message:
          'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      },
      // Application
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
    });
```

## Expected Behavior

I expect the plugin return device location by distance-based every 10 meters moving which configured via `distanceFilter: 10`.

## Actual Behavior

The `BackgroundGeolocation.onLocation` event return device locations are unstable (not ~10 meters), sometimes the distance is 50, 70 meters. And it still return even when stationary (distance is 0 meter).

## Steps to Reproduce

1. Open app
2. Accept location permissions
3. Click on Start button which call `BackgroundGeolocation.start()`
```
 BackgroundGeolocation.start().then(
        //bypass to keep tracking location when is_moving: false
        state => !state.isMoving && BackgroundGeolocation.changePace(true),
      );
```
4. Walking and wait for tracking device locations (then stand still for a few minutes.)
5. Click on Stop button which call `BackgroundGeolocation.stop()`
6. View logs on onLocation event trigger.

## Note
I test on DEBUG mode by connecting with real devices via wifi IP.

**Comment by christocracy** [comment]
There is no guarantee you’ll receive a location exactly according to distanceFilter.

**Comment by vandiepbui** [comment]
How about time-based? Does the plugin guarantee to return device location exactly according to time-based?

**Comment by christocracy** [comment]
Android does, iOS doesn’t.

**Comment by christocracy** [comment]
See api docs Config.locationUpdateInterval.  It is, of course, *not* exact.

**Comment by ajaygupta0512** [comment]
@christocracy  I apologize for putting a comment on a closed issue.  Is there a technical constraint in implementing time-based filtering in iOS?  That limits our ability to use this plugin for time based filtering.

**Comment by christocracy** [comment]
The native iOS location api does not provide a mechanism for time-based updates.  Android does.

If ever Apple changes their mind and provides such a mechanism, I’ll implement it.
