### ISSUE TITLE
Time-based config is not applied on Android

### ISSUE THREAD

**Issue by vandiepbui** [transistorsoft/react-native-background-geolocation#1595]
## Your Environment
* Plugin version: 4.9.3
* Platform: iOS or Android
* OS version: 11
* Device manufacturer / model: Samsung A50s
* React Native version (`react-native -v`): 0.68.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    await BackgroundGeolocation.ready({
      // Debug
    reset: false,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    // Geolocation
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 0,
    locationUpdateInterval: 180000, //3 minutes
    fastestLocationUpdateInterval: 180000, //3 minutes
    stationaryRadius: 0,
    disableStopDetection: true, //disable detect states moving/stationary
    pausesLocationUpdatesAutomatically: false, //IOS => keep location service turn ON
    disableMotionActivityUpdates: true, //disable request physical activity permission
    // Permissions
    locationAuthorizationRequest: 'Always',
    // Application
    foregroundService: false,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    });
```

## Expected Behavior

I expect the plugin return device location interval time which configured via `locationUpdateInterval` and `fastestLocationUpdateInterval`. Location should be returned after interval time-based (3 minutes as configuration) until calling `BackgroundGeolocation.stop()`.

## Actual Behavior

Location is returned every 1 minute interval instead of 3 minutes.

## Steps to Reproduce

1. Open app
2. Accept location permissions
3. Click on Start button which call `BackgroundGeolocation.start()`
4. Wait a few minutes for tracking device locations
5. Click on Stop button which call `BackgroundGeolocation.stop()`

## Question
Does the plugin limit the maximum interval time value on Android?

**Comment by johnnyrockfort** [comment]
any comments to that one?

**Comment by christocracy** [comment]
> reset: false,

Do you know what this does?  99% of use-cases do not require that.  The default is `true`.

it is the reason for the behaviour you describe.
