### ISSUE TITLE
locationTemplate not used with all the HTTP calls

### ISSUE THREAD

**Issue by BlackJohnny** [transistorsoft/react-native-background-geolocation#1596]
## Your Environment
* Plugin version: 4.9.3
* Platform: Android
* OS version: 9 and 13
* Device manufacturer / model: Samsung S8 and Samsung S21
* React Native version (`react-native -v`): 0.68.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    await BackgroundGeolocation.ready({
      enableHeadless: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopTimeout: 10,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      isMoving: true,
      url: `${baseUrl}...`,
      batchSync: false,
      autoSync: true,
      headers: {
        "Content-Type": "application/json",
        "X-Morfin-Custom-Routing": DEV_ROUTES,
        "Authorization": `${auth}...`
      },
      disableLocationAuthorizationAlert: false,
      locationAuthorizationRequest: "Any",
      backgroundPermissionRationale: {
        message: I18n.t("request_permissions_bk_location"),
        negativeAction: I18n.t("no_label"),
        positiveAction: I18n.t("yes_label")
      },
      locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>, "activity": "<%= activity.type %>"}',
      httpRootProperty: ".",
      notification: {
        smallIcon: "mipmap/ic_notification",
        color: "#02d1bb",
        channelName: TRACKING_CHANNEL_ID
      }
    });
```

## Expected Behavior
The location events to be sent via HTTP using the given `locationTemplate` to the back-end.

## Actual Behavior

It seems that on the backend, NOT ALWAYS, we get the following HTTP requests which do not use the configured template.

When force restart the application the new events events are being sent ok .... until it doesn't again.

We have encountered the same behavior with version **4.8.2**.

```
-----------START HTTP REQUEST-----------
POST http://XXXX
Host: XXXX
X-Morfin-Custom-Routing: {}
Authorization: XXXX
Accept-Encoding: gzip
User-Agent: okhttp/4.9.2
SOME_X_HEADERS
Content-Length: 432
Content-Type: application/json; charset=utf-8

{"is_moving":false,"uuid":"a7af8eb3-da6a-4a56-9d16-4c330bd357ca","timestamp":"2022-11-24T08:10:56.182Z","odometer":1045604736,"coords":{"latitude":XX.XXXXXX,"longitude":X.XXXXXX,"accuracy":17.2,"speed":-1,"speed_accuracy":-1,"heading":-1,"heading_accuracy":-1,"altitude":348.8,"ellipsoidal_altitude":348.8,"altitude_accuracy":1},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":0.15},"extras":{}}

-----------END HTTP REQUEST-----------
```

## Steps to Reproduce

We have not been able to reproduce this behavior on our development devices. We think it may have to do with the `stopTimeout` feature, causing the component to lose the config context.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You have old locations in the plug-in’s SQLite db that were inserted before you implemented locationTemplate.

locations are rendered at the time they’re recorded.  Existing records are not re-rendered.

see api docs .destroyLocations() to clear the queue.

**Comment by BlackJohnny** [comment]
Hmm... we had a version with no `locationTemplate` but months ago. The commit with this feature is 5 months old. I will try to determine if the users somehow installed an older version recently.

**Comment by christocracy** [comment]
If your server returns a 20x response for these,  the plugin will delete those records from its database and no longer post them.

**Comment by christocracy** [comment]
Otherwise, it’s going to keep trying and trying until Config.maxDaysToPersist automatically clears them out.

**Comment by BlackJohnny** [comment]
We asked the users to do an uninstall and a fresh install. This should clear any cache and we should not get those calls anymore. I will keep the issue open until next week to check if this is the reason. Thank you!

**Comment by BlackJohnny** [comment]
> If your server returns a 20x response for these, the plugin will delete those records from its database and no longer post them.

currently it returns 500 unfortunately

**Comment by BlackJohnny** [comment]
... since this issue was not encountered anymore I will close it
