### ISSUE TITLE
App crashes with is library and react-native-beacons-manager and i dont know why

### ISSUE THREAD

**Issue by iSaBo96** [transistorsoft/react-native-background-geolocation#1597]
## Your Environment
* Plugin version: 4.9.3 (react-native-background-fetch Library is 4.1.5)
* Platform: iOS
* OS version: 16.1.1
* Device manufacturer / model: iPhone 11
* React Native version (`react-native -v`): 0.69.0
* Plugin config
```javascript 
const state = await BackgroundGeolocation.ready({
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true
    });
```

## Expected Behavior
I use their library in conjunction with the library "react-native-beacons-manager". The reason is that when the user has completely closed the app, I still want to perform a background action. In this case the tracking of beacons via bluetooth.

So at this point I expect to be able to use your library in conjunction with the react-native-beacons-manager library.

## Actual Behavior
When I create a minimal example using their library, everything works beautifully. Even in the background, when the app is completely closed, I continue to receive information about my current location. Perfect up to this point. So I added the library "react-native-beacons-manager". This is just there to select beacons over bluetooth near me. I didn't write any code for this, but just added this library for now. I then provided the app as TestFlight and installed it on my phone. I did this because I want to test how the app behaves when it is completely closed. I can only test this on a real device and not in Xcode, right? xcode stops responding when the simulator or app is closed on a real device, right? 

Anyway, the app crashes with the message "The app has crashed". If I make the message go away, the app continues as intended. However, since I am not getting a proper error message, I would hereby like to ask you where you might have a clue as to what is causing the app to crash. You are welcome to recreate my behavior if you have the time. I have attached the entire code for this purpose. 

## Steps to Reproduce
1. react-native init myTestApp
2. install your library
3. install the library react-native-beacons-manager (https://github.com/MacKentoch/react-native-beacons-manager )
4. Add the following code to "App.tsx"
```javascript 
import React from 'react';

import {
  Text,
  TouchableOpacity
} from 'react-native';

import PushNotificationIOS from '@react-native-community/push-notification-ios';
import BackgroundGeolocation, {Subscription} from './src/react-native-background-geolocation'; // same content as in your example app
import BackgroundFetch from "react-native-background-fetch";

const App = ({route, navigation}) => {
  const bgGeoEventSubscriptions:Subscription[] = [];

  const [events, setEvents] = React.useState<any[]>([]);
  const [enabled, setEnabled] = React.useState(false);

  React.useEffect(() => {
    initBackgroundGeolocation();
    return () => {
      unsubscribe();
    }
  }, []);

  const subscribe = (subscription:Subscription) => {
    bgGeoEventSubscriptions.push(subscription);
  }

  const unsubscribe = () => {
    bgGeoEventSubscriptions.forEach((subscription:Subscription) => subscription.remove() );
  }

  const initBackgroundGeolocation = async () => {
    subscribe(BackgroundGeolocation.onProviderChange((event) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onProviderChange',
        title: 'onProviderChange !',
        body: 'onProviderChange',
      });

      console.log('[onProviderChange]', event);
      addEvent('onProviderChange', event);
    }));

    subscribe(BackgroundGeolocation.onLocation((location) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onLocation',
        title: 'onLocation !',
        body: 'onLocation',
      });

      console.log('[onLocation]', location);
      addEvent('onLocation', location);
    }, (error) => {
      console.warn('[onLocation] ERROR: ', error);
    }));

    subscribe(BackgroundGeolocation.onMotionChange((location) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onMotionChange',
        title: 'onMotionChange !',
        body: 'onMotionChange',
      });

      console.log('[onMotionChange]', location);
      addEvent('onMotionChange', location);
    }));

    subscribe(BackgroundGeolocation.onGeofence((event) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onActivityChange',
        title: 'onActivityChange !',
        body: 'onActivityChange',
      });

      console.log('[onGeofence]', event);
      addEvent('onGeofence', event);
    }));

    subscribe(BackgroundGeolocation.onConnectivityChange((event) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onConnectivityChange',
        title: 'onConnectivityChange !',
        body: 'onConnectivityChange',
      });

      console.log('[onConnectivityChange]', event);
      addEvent('onConnectivityChange', event);
    }));

    subscribe(BackgroundGeolocation.onEnabledChange((enabled) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onEnabledChange',
        title: 'onEnabledChange !',
        body: 'onEnabledChange',
      });

      console.log('[onEnabledChange]', enabled);
      addEvent('onEnabledChange', {enabled: enabled});
    }));

    subscribe(BackgroundGeolocation.onHttp((event) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onHttp',
        title: 'onHttp !',
        body: 'onHttp',
      });

      console.log('[onHttp]', event);
      addEvent('onHttp', event);
    }));

    subscribe(BackgroundGeolocation.onActivityChange((event) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onActivityChange',
        title: 'onActivityChange !',
        body: 'onActivityChange',
      });

      console.log('[onActivityChange]', event);
      addEvent('onActivityChange', event);
    }));

    subscribe(BackgroundGeolocation.onPowerSaveChange((enabled) => {
      PushNotificationIOS.addNotificationRequest({
        id: 'onPowerSaveChange',
        title: 'onPowerSaveChange !',
        body: 'onPowerSaveChange',
      });

      console.log('[onPowerSaveChange]', enabled);
      addEvent('onPowerSaveChange', {isPowerSaveMode: enabled});
    }));

    const state = await BackgroundGeolocation.ready({
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true
    });

    addEvent('Current state', state);
    BackgroundGeolocation.start();
  };

  const initBackgroundFetch = async () => {
    await BackgroundFetch.configure({
      minimumFetchInterval: 15,
      stopOnTerminate: true
    }, (taskId) => {
      console.log('[BackgroundFetch] ', taskId);

      BackgroundFetch.finish(taskId);
    }, (taskId) => {
      console.log('[BackgroundFetch] TIMEOUT: ', taskId);
      BackgroundFetch.finish(taskId);
    });
  }

  const addEvent = (name:string, params:any) => {
    let timestamp = new Date();
    const event = {
      expanded: false,
      timestamp: `${timestamp.getMonth()}-${timestamp.getDate()} ${timestamp.getHours()}:${timestamp.getMinutes()}:${timestamp.getSeconds()}`,
      name: name,
      params: JSON.stringify(params, null, 2)
    }
    setEvents(previous => [...previous, event]);
  }

  const onClickEnable = (value:boolean) => {
    if (value) {
      BackgroundGeolocation.start();
    } else {
      BackgroundGeolocation.stop();
    }
  }

  return (
      <TouchableOpacity onPress={() => {
        PushNotificationIOS.addNotificationRequest({
          id: 'gpsTestApp',
          title: 'App.js !',
          body: 'Aufruf in App.js',
        });
        onClickEnable(true);
      }}>
        <Text style={{top: 200, left: 50, color: 'white'}}>Hier klicken für eine Notification</Text>
      </TouchableOpacity>
  );
}

var PushNotification = require('react-native-push-notification');
PushNotification.configure({
  onRegister: function(token) {
    console.log( 'TOKEN:', token );
  },
  onNotification: function(notification) {
    console.log( 'NOTIFICATION:', notification );
  },
  permissions: {
    alert: true,
    badge: true,
    sound: true
  },
  popInitialNotification: true,
  requestPermissions: true,
});

export default App;
```
5. I deployed the app after this to TestFlight and run this app on my Phone. I walked a little bit and the crash occurs.

## Context
I tried to update the react-native version, tried other libraries (your library works best), tried to simulate the error in xcode.
Nothing works.

## Debug logs
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
No logs available
```

</details>

I hope you understand my problem and my question. First, I just want to know if there is a possibility for a meaningful error message when the app crashes.

**Comment by christocracy** [comment]
The issue template is not optional.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> I just want to know if there is a possibility for a meaningful error message when the app crashes.

Boot your app within XCode and observe the logs.

**Comment by iSaBo96** [comment]
The app dont crashed if the app is not complety closed. So i cant only boot my app with xcode, right?

**Comment by christocracy** [comment]
Start by editing your original post with the required issue template.

**Comment by iSaBo96** [comment]
I will do that, thanks. I thought I had marked this post as a question.

**Comment by iSaBo96** [comment]
I edited the original post. I created the post on my phone, so the template was not available there. Sorry for that.

**Comment by christocracy** [comment]
Until you provide a stacktrace, there’s no evidence your crash is due to this plugin.

see here:  https://developer.apple.com/news/?id=nra79npr

> I created the post on my phone, so the template was not available ther

![115D17A8-873F-4239-B544-ADE0FC3D2215](https://user-images.githubusercontent.com/14999/204012039-3001164b-170d-496f-a4a4-2d0f4b335207.png)

**Comment by iSaBo96** [comment]
Thanks for the hint

**Comment by iSaBo96** [comment]
Okay, the issue is not with your library. I just posted my question here, because your library is included my problem. 

Thanks for your reply. I will post my question in the beacons-manager library

Stacktrace:

`Incident Identifier: E0CCA4C5-FFA1-4877-AD51-4122203B3743
Hardware Model:      iPhone12,1
Process:             RnBackgroundTest [12670]
Path:                /private/var/containers/Bundle/Application/9A294997-9228-42D3-9302-F47A12B97981/RnBackgroundTest.app/RnBackgroundTest
Identifier:          org.reactjs.native.testapp.RnBackgroundTest
Version:             4.0 (21)
AppStoreTools:       14B44
AppVariant:          1:iPhone12,1:16
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           org.reactjs.native.testapp.RnBackgroundTest [2278]

Date/Time:           2022-11-25 14:16:32.8786 +0100
Launch Time:         2022-11-25 13:50:58.5619 +0100
OS Version:          iPhone OS 16.1.1 (20B101)
Release Type:        User
Baseband Version:    4.00.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1b0a75e88 __exceptionPreprocess + 164 (NSException.m:202)
1   libobjc.A.dylib               	0x1a9daf8d8 objc_exception_throw + 60 (objc-exception.mm:356)
2   CoreFoundation                	0x1b0bea84c -[NSObject(NSObject) doesNotRecognizeSelector:] + 136 (NSObject.m:140)
3   CoreFoundation                	0x1b0a8bfa0 ___forwarding___ + 1592 (NSForwarding.m:3578)
4   CoreFoundation                	0x1b0af4350 _CF_forwarding_prep_0 + 96 (:-1)
5   RnBackgroundTest            	0x1004608ec -[RNiBeacon locationManager:didExitRegion:] + 104 (RNiBeacon.m:272)
6   CoreLocation                  	0x1bc41b094 -[CLLocationManager onClientEventRegion:] + 1596 (CLLocationManager.m:3164)
7   CoreLocation                  	0x1bc3f89d8 -[CLLocationManager onClientEvent:supportInfo:] + 924 (CLLocationManager.m:2680)
8   CoreLocation                  	0x1bc3f50f0 ___Z22CLClientInvokeCallbackP10__CLClient13CLClientEventP11objc_object_block_invoke + 180 (CLClient.mm:731)
9   LocationSupport               	0x1cbc21968 -[CLSilo prepareAndRunBlock:] + 196 (CLSilo.m:255)
10  CoreFoundation                	0x1b0aaf564 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28 (CFRunLoop.c:1805)
11  CoreFoundation                	0x1b0b17d9c __CFRunLoopDoBlocks + 368 (CFRunLoop.c:1847)
12  CoreFoundation                	0x1b0ae81f8 __CFRunLoopRun + 2452 (CFRunLoop.c:3201)
13  CoreFoundation                	0x1b0aeced4 CFRunLoopRunSpecific + 612 (CFRunLoop.c:3418)
14  GraphicsServices              	0x1e9dea368 GSEventRunModal + 164 (GSEvent.c:2196)
15  UIKitCore                     	0x1b2fcb3d0 -[UIApplication _run] + 888 (UIApplication.m:3745)
16  UIKitCore                     	0x1b2fcb034 UIApplicationMain + 340 (UIApplication.m:5335)
17  RnBackgroundTest           	    0x1002b2e40 main + 80 (main.m:8)
18  dyld                          	0x1cf154960 start + 2528 (dyldMain.cpp:1170)

Kernel Triage:
VM - pmap_enter retried due to resource shortage


Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001ed670200 __pthread_kill + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001fdad21ac pthread_kill + 268 (pthread.c:1670)
2   libsystem_c.dylib             	0x00000001b80a9c8c abort + 180 (abort.c:118)
3   libc++abi.dylib               	0x00000001fda12b8c abort_message + 132 (abort_message.cpp:78)
4   libc++abi.dylib               	0x00000001fda02a80 demangling_terminate_handler() + 336 (cxa_default_handlers.cpp:71)
5   libobjc.A.dylib               	0x00000001a9db5d3c _objc_terminate() + 144 (objc-exception.mm:498)
6   libc++abi.dylib               	0x00000001fda11f28 std::__terminate(void (*)()) + 20 (cxa_handlers.cpp:59)
7   libc++abi.dylib               	0x00000001fda14ecc __cxa_rethrow + 148 (cxa_exception.cpp:616)
8   libobjc.A.dylib               	0x00000001a9db16b4 objc_exception_rethrow + 44 (objc-exception.mm:401)
9   CoreFoundation                	0x00000001b0aecf98 CFRunLoopRunSpecific + 808 (CFRunLoop.c:3434)
10  GraphicsServices              	0x00000001e9dea368 GSEventRunModal + 164 (GSEvent.c:2196)
11  UIKitCore                     	0x00000001b2fcb3d0 -[UIApplication _run] + 888 (UIApplication.m:3745)
12  UIKitCore                     	0x00000001b2fcb034 UIApplicationMain + 340 (UIApplication.m:5335)
13  RnBackgroundTest           	    0x00000001002b2e40 main + 80 (main.m:8)
14  dyld                          	0x00000001cf154960 start + 2528 (dyldMain.cpp:1170)

Thread 1:
0   libsystem_pthread.dylib       	0x00000001fdacbb90 start_wqthread + 0 (:-1)

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001ed669b48 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001ed67c008 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001ed67c248 mach_msg_overwrite + 388 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001ed66a08c mach_msg + 24 (mach_msg.c:323)
4   CoreFoundation                	0x00000001b0ae6af0 __CFRunLoopServiceMachPort + 160 (CFRunLoop.c:2622)
5   CoreFoundation                	0x00000001b0ae7d34 __CFRunLoopRun + 1232 (CFRunLoop.c:3005)
6   CoreFoundation                	0x00000001b0aeced4 CFRunLoopRunSpecific + 612 (CFRunLoop.c:3418)
7   Foundation                    	0x00000001aae9a334 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212 (NSRunLoop.m:373)
8   Foundation                    	0x00000001aae9a21c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64 (NSRunLoop.m:420)
9   UIKitCore                     	0x00000001b310033c -[UIEventFetcher threadMain] + 436 (UIEventFetcher.m:1377)
10  Foundation                    	0x00000001aaeb3808 __NSThread__start__ + 716 (NSThread.m:963)
11  libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
12  libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)

Thread 3 name:
Thread 3:
0   libsystem_kernel.dylib        	0x00000001ed669b48 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001ed67c008 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001ed67c248 mach_msg_overwrite + 388 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001ed66a08c mach_msg + 24 (mach_msg.c:323)
4   CoreFoundation                	0x00000001b0ae6af0 __CFRunLoopServiceMachPort + 160 (CFRunLoop.c:2622)
5   CoreFoundation                	0x00000001b0ae7d34 __CFRunLoopRun + 1232 (CFRunLoop.c:3005)
6   CoreFoundation                	0x00000001b0aeced4 CFRunLoopRunSpecific + 612 (CFRunLoop.c:3418)
7   RnBackgroundTest           	    0x0000000100373b28 +[RCTCxxBridge runRunLoop] + 212 (RCTCxxBridge.mm:335)
8   Foundation                    	0x00000001aaeb3808 __NSThread__start__ + 716 (NSThread.m:963)
9   libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
10  libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib        	0x00000001ed66a41c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001fdad306c _pthread_cond_wait + 1232 (pthread_cond.c:636)
2   JavaScriptCore                	0x00000001c410a324 scavenger_thread_main + 1164 (pas_scavenger.c:145)
3   libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
4   libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001ed669b48 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001ed67c008 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001ed67c248 mach_msg_overwrite + 388 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001ed66a08c mach_msg + 24 (mach_msg.c:323)
4   CoreFoundation                	0x00000001b0ae6af0 __CFRunLoopServiceMachPort + 160 (CFRunLoop.c:2622)
5   CoreFoundation                	0x00000001b0ae7d34 __CFRunLoopRun + 1232 (CFRunLoop.c:3005)
6   CoreFoundation                	0x00000001b0aeced4 CFRunLoopRunSpecific + 612 (CFRunLoop.c:3418)
7   CoreFoundation                	0x00000001b0b30d04 CFRunLoopRun + 64 (CFRunLoop.c:3444)
8   CoreMotion                    	0x00000001bc010ec0 CLMotionCore::runMotionThread(void*) + 1208 (CLMotionCore.mm:376)
9   libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
10  libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)

Thread 6:
0   libsystem_pthread.dylib       	0x00000001fdacbb90 start_wqthread + 0 (:-1)

Thread 7:
0   libsystem_pthread.dylib       	0x00000001fdacbb90 start_wqthread + 0 (:-1)

Thread 8:
0   libsystem_pthread.dylib       	0x00000001fdacbb90 start_wqthread + 0 (:-1)

Thread 9:
0   libsystem_pthread.dylib       	0x00000001fdacbb90 start_wqthread + 0 (:-1)

Thread 10 name:
Thread 10:
0   libsystem_kernel.dylib        	0x00000001ed66a41c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001fdad306c _pthread_cond_wait + 1232 (pthread_cond.c:636)
2   JavaScriptCore                	0x00000001c40606a4 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808 (ThreadingPOSIX.cpp:626)
3   JavaScriptCore                	0x00000001c40210fc bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304 (ParkingLot.h:82)
4   JavaScriptCore                	0x00000001c4021578 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248 (Condition.h:77)
5   JavaScriptCore                	0x00000001c4082e5c WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352 (Function.h:82)
6   JavaScriptCore                	0x00000001c40850e4 WTF::wtfThreadEntryPoint(void*) + 16 (ThreadingPOSIX.cpp:242)
7   libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
8   libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)

Thread 11 name:
Thread 11:
0   libsystem_kernel.dylib        	0x00000001ed66a41c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001fdad306c _pthread_cond_wait + 1232 (pthread_cond.c:636)
2   JavaScriptCore                	0x00000001c40606a4 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808 (ThreadingPOSIX.cpp:626)
3   JavaScriptCore                	0x00000001c40210fc bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304 (ParkingLot.h:82)
4   JavaScriptCore                	0x00000001c4021578 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248 (Condition.h:77)
5   JavaScriptCore                	0x00000001c4082e5c WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352 (Function.h:82)
6   JavaScriptCore                	0x00000001c40850e4 WTF::wtfThreadEntryPoint(void*) + 16 (ThreadingPOSIX.cpp:242)
7   libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
8   libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)

Thread 12 name:
Thread 12:
0   libsystem_kernel.dylib        	0x00000001ed66a41c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001fdad306c _pthread_cond_wait + 1232 (pthread_cond.c:636)
2   JavaScriptCore                	0x00000001c40606a4 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808 (ThreadingPOSIX.cpp:626)
3   JavaScriptCore                	0x00000001c40210fc bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304 (ParkingLot.h:82)
4   JavaScriptCore                	0x00000001c4021578 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248 (Condition.h:77)
5   JavaScriptCore                	0x00000001c4082e5c WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352 (Function.h:82)
6   JavaScriptCore                	0x00000001c40850e4 WTF::wtfThreadEntryPoint(void*) + 16 (ThreadingPOSIX.cpp:242)
7   libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
8   libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)

Thread 13 name:
Thread 13:
0   libsystem_kernel.dylib        	0x00000001ed66a41c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001fdad306c _pthread_cond_wait + 1232 (pthread_cond.c:636)
2   JavaScriptCore                	0x00000001c40606a4 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808 (ThreadingPOSIX.cpp:626)
3   JavaScriptCore                	0x00000001c40210fc bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304 (ParkingLot.h:82)
4   JavaScriptCore                	0x00000001c4021578 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248 (Condition.h:77)
5   JavaScriptCore                	0x00000001c4082e5c WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352 (Function.h:82)
6   JavaScriptCore                	0x00000001c40850e4 WTF::wtfThreadEntryPoint(void*) + 16 (ThreadingPOSIX.cpp:242)
7   libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
8   libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)

Thread 14 name:
Thread 14:
0   libsystem_kernel.dylib        	0x00000001ed66a41c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001fdad306c _pthread_cond_wait + 1232 (pthread_cond.c:636)
2   JavaScriptCore                	0x00000001c40606a4 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808 (ThreadingPOSIX.cpp:626)
3   JavaScriptCore                	0x00000001c40210fc bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304 (ParkingLot.h:82)
4   JavaScriptCore                	0x00000001c4021578 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248 (Condition.h:77)
5   JavaScriptCore                	0x00000001c4082e5c WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352 (Function.h:82)
6   JavaScriptCore                	0x00000001c40850e4 WTF::wtfThreadEntryPoint(void*) + 16 (ThreadingPOSIX.cpp:242)
7   libsystem_pthread.dylib       	0x00000001fdacc6cc _pthread_start + 148 (pthread.c:893)
8   libsystem_pthread.dylib       	0x00000001fdacbba4 thread_start + 8 (:-1)


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x00000001fda160f5   x5: 0x000000016fb53060   x6: 0x000000000000006e   x7: 0xffffffff00001400
    x8: 0x3a02ffffb70013a9   x9: 0x3a02fffdb00dcaa9  x10: 0x0000000000000200  x11: 0x000000000000000b
   x12: 0x000000000000000b  x13: 0x00000000001ff800  x14: 0x00000000000007fb  x15: 0x000000008e827835
   x16: 0x0000000000000148  x17: 0x00000002070dd900  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x00000002070dd9e0  x22: 0x00000002084d8580  x23: 0x000000028182c010
   x24: 0x0000000000000001  x25: 0x0000000000000001  x26: 0x0000000000000001  x27: 0x0000000000000000
   x28: 0x00000001d1a20980   fp: 0x000000016fb52fd0   lr: 0x00000001fdad21ac
    sp: 0x000000016fb52fb0   pc: 0x00000001ed670200 cpsr: 0x40000000
   esr: 0x56000080  Address size fault


Binary Images:
0x1002ac000 - 0x1005a7fff RnBackgroundTest arm64  <178e4852e416367597183617b07af3df> /private/var/containers/Bundle/Application/9A294997-9228-42D3-9302-F47A12B97981/RnBackgroundTest.app/RnBackgroundTest
0x1a9d98000 - 0x1a9ddbe1f libobjc.A.dylib arm64e  <ab79707faf643ba588993b711c6cff5c> /usr/lib/libobjc.A.dylib
0x1aae58000 - 0x1ab7a1fff Foundation arm64e  <c431acb6fe043d28b6774de6e1c7d81f> /System/Library/Frameworks/Foundation.framework/Foundation
0x1b0a6c000 - 0x1b0e51fff CoreFoundation arm64e  <5cdc5d9ae5063740b64ebb30867b4f1b> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x1b2c29000 - 0x1b4406fff UIKitCore arm64e  <179501b60fc2344ab969b4e3961ebe10> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x1b8089000 - 0x1b8108ff7 libsystem_c.dylib arm64e  <dad0ce088f353ff4899e43dc44eb65a7> /usr/lib/system/libsystem_c.dylib
0x1bbffd000 - 0x1bc3e9fff CoreMotion arm64e  <84a0807ecd293c3cacb846549fef12f2> /System/Library/Frameworks/CoreMotion.framework/CoreMotion
0x1bc3ea000 - 0x1bc4dffff CoreLocation arm64e  <82a2d4efb2ad3894a0d38d0d08a05200> /System/Library/Frameworks/CoreLocation.framework/CoreLocation
0x1c4014000 - 0x1c54cffff JavaScriptCore arm64e  <d309aa36b4943228be7d44e5674ed663> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
0x1cbc20000 - 0x1cbc52fff LocationSupport arm64e  <70b56c6d902d34b1ab09f818796b9ad7> /System/Library/PrivateFrameworks/LocationSupport.framework/LocationSupport
0x1cf13f000 - 0x1cf1c200f dyld arm64e  <cb3ff411476234d286a4eca13f9fb6c3> /usr/lib/dyld
0x1e9de9000 - 0x1e9df1fff GraphicsServices arm64e  <a633a095122639428f413877660185ee> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x1ed669000 - 0x1ed69fffb libsystem_kernel.dylib arm64e  <ff27fc8f90ba3332ab7ac5bc2d9ca7b1> /usr/lib/system/libsystem_kernel.dylib
0x1fda01000 - 0x1fda18ffb libc++abi.dylib arm64e  <fa871417be083e90b33ca6aa89813f3b> /usr/lib/libc++abi.dylib
0x1fdacb000 - 0x1fdad6fff libsystem_pthread.dylib arm64e  <1aa3a4b6f9e730568c8b4e4dd81312a4> /usr/lib/system/libsystem_pthread.dylib

EOF
`
