### ISSUE TITLE
Stationary update

### ISSUE THREAD

**Issue by DVassilev** [transistorsoft/react-native-background-geolocation#160]
Is it possible to have it trigger the background task every X time even when stationary?

**Comment by christocracy** [comment]
See docs for heartbeat event.

**Comment by VylarLtd** [comment]
@christocracy Checking it now, thanks for prompt response! :)

**Comment by DVassilev** [comment]
@christocracy Thank you :)

**Comment by DVassilev** [comment]
@christocracy I noticed that this requires 'preventSuspending' though and that can be quite battery intensive. Is there any other method?

**Comment by DVassilev** [comment]
I added this to my config options

```
preventSuspend: true,
heartbeatInterval:` 5
```

and a listener for the heartbeat event but it doesn't seem to get triggered anyway.

**Comment by christocracy** [comment]
The nature of iOS is to suspend app in the background when location-services are not activated.  When your app is suspended, obviously you (or I) cannot execute any code.

Your **only** alternative is to listen to `background-fetch` events.  This plugin includes my [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch) plugin.  It's already included so go ahead and import and configure it.

If you're having specific issues with `preventSuspend`, post a separate issue.  Include logs, config and device model / os.

**Comment by DVassilev** [comment]
@christocracy When preventSuspending is off though how do the other location update events work?

**Comment by christocracy** [comment]
Magic.  The plugin detects when the device is moving.  The plugin has 2 states:  stationary & moving.  When the plugin detects the device is moving, it engages location-services **ON**.  When location-services are **ON**, iOS allows an app to remain alive in the background forever.  When teh plugin detects the device is stopped, it turns **OFF** location-services, allowing iOS to put your app to sleep again.

**Comment by DVassilev** [comment]
@christocracy and it isn't possible to tell it to wake up our app every minute like it does when it detects movement?
