### ISSUE TITLE
[Typescript issue?] lastLocationAuthorizationStatus is missing from State type

### ISSUE THREAD

**Issue by mwmcode** [transistorsoft/react-native-background-geolocation#1603]
Hello,

```ts
const state = await BgGeoLocInstance.ready(..config);
console.log(state);
```
logs out `lastLocationAuthorizationStatus: number` but this prop is not on `State` type

My question is, is it safe to use it (lastLocationAuthorizationStatus)?

**Comment by christocracy** [comment]
> lastLocationAuthorizationStatus

That is not meant to be sent to the state.  Pretend you never saw it.  It will be removed.

see api docs .getProviderState()
