### ISSUE TITLE
disableLocationAuthorizationAlert not functioning as expected on Android [demo codebase, video example]

### ISSUE THREAD

**Issue by mwmcode** [transistorsoft/react-native-background-geolocation#1605]
## Your Environment
using the demo codebase https://github.com/transistorsoft/rn-background-geolocation-demo

video below
```
"react-native": "0.68.5",
"react-native-background-fetch": "^4.1.3",
 "react-native-background-geolocation": "^4.9.3",
```
- Android API29
- IOS 16.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
disableLocationAuthorizationAlert: true,
```

## Expected Behavior
(on Android) Authorization alert should **not** display dialog when `disableLocationAuthorizationAlert: true`

## Actual Behavior
Dialog shows on Android 

## Steps to Reproduce
0. src/hello-world/HelloWorldView.tsx set `disableLocationAuthorizationAlert: true,` in  `BackgroundGeolocation.ready({`
1. run demo -> Hello world example -> start plugin (toggle switch top right corner)
2. grant `when in use` permission
3. start plug in (by flicking switch button on top right corner) -- if not done so already
4. go back to home screen
5. refresh app (press `r` on terminal running metro)
6. go back to Hello world example
7. start plugin (flick the top right corner switch again)***
*** Dialog does not show on iOS which is expected✅ behavior but it does show on Android 🫤 

## Context
I have code that checks existing status, if it's `whenInUse` then set `disableLocationAuthorizationAlert: true,` (so we don't bug users with permission requests). It is working fine on iOS but not android (tested on emulators & real devices)

### Video
- _Video shows the 2nd part (after initial start and granting `when in use` for first time, then restart metro_ 
- shows expected/correct behavior on iphone
- shows unexpected behavior on android

https://user-images.githubusercontent.com/13101565/206873247-a3a4df45-a665-463a-9515-5f8be23529d3.mov

**Comment by christocracy** [comment]
Show me a screenshot of which dialog.  You likely misunderstand.

**Comment by mwmcode** [comment]
![Screenshot 2022-12-10 at 3 33 32 PM](https://user-images.githubusercontent.com/13101565/206874241-5509b702-eb9b-4b87-baea-3ab438fd88d9.png)

**Comment by christocracy** [comment]
Post your Config provided to .ready(Config).

the issue template already asked you for this,

**Comment by christocracy** [comment]
Your provided screenshot is not what is controlled by `Config,disableLocationAuthorizationAlert`.

you have misunderstanding.  Have you read the api docs about what that does.

I suggest you also read the api docs for Config.locationAuthorizationRequest.

**Comment by mwmcode** [comment]
Sorry Chris, i thought by saying I'm using the demo codebase, it'd be easy for you to follow what I'm doing 

```javascript
/// Configure the plugin.
    const state = await BackgroundGeolocation.ready({
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      transistorAuthorizationToken: token,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true,
      disableLocationAuthorizationAlert: true, // the only line i changed in demo codebase
    });

```

**Comment by christocracy** [comment]
See api docs Config.locationAuthorizationRequest.

delete disableLocationAuthorizationRequest: true.
