### ISSUE TITLE
Setting values of locationAuthorizationAlert has no effect

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1611]
## Your Environment
* Plugin version: "react-native-background-fetch": "^4.1.0", "react-native-background-geolocation": "^4.8.2",
* Platform: iOS 
* OS version: 16.2
* Device manufacturer / model: iPhone 14
* React Native version (`react-native -v`): "0.66.4",
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready({
      desiredAccuracy: BACKGROUND_TRACKING_ACCURACY_LEVEL_MAPPING[accuracy],
      stationaryRadius: 25,
      disableLocationAuthorizationAlert: true,
      stopOnTerminate: true,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: true, // enable to hear debug sounds
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // ios
      showsBackgroundLocationIndicator: true,
      // android
      allowIdenticalLocations: true,
      foregroundService: true,
      // location permissions
      locationAuthorizationRequest: 'WhenInUse',
      backgroundPermissionRationale: {
        title: "Allow XY to access to this device's location",
        message:
          'Some Description Text.',
        positiveAction: 'Allow',
        negativeAction: 'Cancel',
      },
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'You have not given XY Location Permissions',
        titleWhenOff: 'Location Services turned Off',
        instructions:
          "Some Description Text",
        cancelButton: 'Cancel',
        settingsButton: 'Settings',
      },
      notification: {
        title: 'XY',
        text: 'XY is tracking your location',
      },
    });
```

## Expected Behavior
I want to display the `locationAuthorizationAlert()` text I provided in `BackgroundGeolocation.ready()` or `BackgroundGeolocation.setConfig()`. However, it always displays what I have set in the `Info.plist` file.

```
BackgroundGeolocation.setConfig({
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
          title:
            "Allow XY to access to this device's location in the background",
          message:
            'Some Description',
          positiveAction: 'Change to Always',
          negativeAction: 'Cancel',
        },
        locationAuthorizationAlert: {
          titleWhenNotEnabled:
            'You have not given XY Location Permissions',
          titleWhenOff: 'Location Services turned Off',
          instructions:
            "ISome Description",
          cancelButton: 'Cancel',
          settingsButton: 'Settings',
        },
      });
```

## Actual Behavior
It is showing what I have written in the `Info.plist` description

```
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Some Description.</string>
<key>NSLocationWhenInUseUsageDescription</key>
    <string>Some Description</string>
<key>NSMotionUsageDescription</key>
    <string>Some Description</string>
```

## Steps to Reproduce

Try setting the `locationAuthorizationAlert()` to something different, than set in the `Info.plist` file.

## Context
Giving the user a different `locationAuthorizationAlert()` text, depending on what the user pressed in the App.

**Comment by christocracy** [comment]
I suspect you misunderstand what locationAuthorizationAlert is.  Have you read the api docs about it?

Show me a screenshot of what you *think* locationAuthorozationAlert is.

**Comment by Stophface** [comment]
@christocracy Yes, I always read the docs and try around before asking and thanks for pointing that out. I missunderstood something there. I thought the text used in the dialog is taken from the `JS` side, and not the `Info.plist` file. However, there is still something I do not understand.

I first ask `When In Use`, which uses the Text I provide here `<key>NSLocationWhenInUseUsageDescription</key>`. I *later* (onPress() of a button) use `setConfig` to change` locationAuthorizationRequest` to `Always`. The text shown in the dialog is taken from here `<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>`. So far, so good. 

However, when I use `setConfig` and ask for `Always`, and the user denies always, there is no `[locationAuthorizationAlert](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#locationauthorizationalert)` shown. Shouldn't that appear then?

**Comment by christocracy** [comment]
> However, when I use setConfig and

the next time the plugin requests a location, it will be shown.  Eg .start(), .getCurrenPosition(), .changePace(true), relaunching the app.

**Comment by Stophface** [comment]
@christocracy I understand, thanks a lot!
