### ISSUE TITLE
BackgroundGeolocation.onGeofence executing many time

### ISSUE THREAD

**Issue by ShumGG** [transistorsoft/react-native-background-geolocation#1613]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^4.9.4"
* Platform: Android
* OS version: 12
* Device manufacturer / model: One plus 7 pro
* React Native version (`react-native -v`): "react-native": "0.69.6"
* Plugin config
```

const locations = [
    {
        identifier: "hospital",
        radius: 200,
        latitude:  22.37692688843252,
        longitude: 114.1042368365577,
        notifyOnEntry: true,
        extras: {
            video_id: 107, 
        }
    },
    {
        identifier: "kwung tong plaza",
        radius: 500,
        latitude:  22.311313492798195,
        longitude: 114.22595708211924,
        notifyOnEntry: true,
        extras: {
            video_id: 110, 
        }
    }
];


    React.useEffect(() => {
   
        const onEntering = BackgroundGeolocation.onGeofence(geofence => {
            if (geofence.identifier === "HOME") {
                return;
            }
            if (geofence.action === "ENTER") {
                console.log("enter");
                return;
            }
        });
    
        /// 2. ready the plugin.
        BackgroundGeolocation.ready({
          // Geolocation Config
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            // Activity Recognition
            stopTimeout: 5,
            // Application config
            stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
            enableHeadless: true,
            foregroundService: true,
            heartbeatInterval: 60,
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
            isMoving: true,
            locationAuthorizationRequest: "Always",
            backgroundPermissionRationale: {
                title: "Allow access to this device's location in the background?",
                message: "In order for features",
                positiveAction: "Change to Allow all the time"
            },
            // HTTP / SQLite config
            httpRootProperty: "data",
            disableStopDetection: true,
            pausesLocationUpdatesAutomatically: false,
            url: 'https://api.dl.media/api/v1/locations/sendLocations',
            batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
        }).then((state) => {
          setEnabled(state.enabled)
        });
    
        return () => {
          onEntering.remove();
        }
    
    }, []);

 React.useEffect(() => {
        if (enabled) {
            BackgroundGeolocation.start();
            BackgroundGeolocation.removeGeofences().then(() => {
                BackgroundGeolocation.addGeofences(locations).then((success) => {
                    console.log("[addGeofence] success");
                }).catch((error) => {
                    console.log("[addGeofence] FAILURE: ", error);
                });
                BackgroundGeolocation.registerHeadlessTask(HeadlessTask);
            });
        } else {
            BackgroundGeolocation.start();
            setLocation('');
        }
    }, [enabled]);

```

## Expected Behavior

When entering to one of the locations, the even should fire just once

## Actual Behavior

When entering to one of the locations, the even should fire many times, even when its already in DWELL, it keeps firing ENTER, DWELL AND EXIT at the same time

## Steps to Reproduce
1.
2.
3.
4.

## Context

just want to send a notification when user enters to the location, since its firing many times its sending multiple notifications when user already entered, it keeps firing entered, dwell and exit at the same time

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

This does not belong where you have it.  This can **ONLY** be placed in your `index.js`, as documented.

See wiki *Debugging* and provide logs.  I don't know what you're doing, but you're doing something wrong.

**Comment by christocracy** [comment]
Why are you removing / re-adding the same geofences each time the app is launched?  Geofences do not have to be re-added each time the app boots.  Once a geofence is added, it is monitored forever, automatically.

**Comment by ShumGG** [comment]
oh, those are just for testing, problem is that when lauching for production i will get geofences from the db, and the db may have new geofences everytime, im removing all of them the add them again

**Comment by christocracy** [comment]
>im removing all of them the add them again

It’s a bad idea.  You’re going to cause a geofence that you’re already inside to double fire.  Particularly in iOS, which will relaunch a terminated app to service a geofence event.  Your app will have launched to service a geofence event, the onGeofence event fires, you .destroyGeofences(), re-add geofences and onGeofence immediately fires again.  Don’t do that.

you should only add geofencesp that don’t exist.  I suggest you have a look at all the geofence-related methods available to you, such as `.hasGeofence(identifier)`.

**Comment by ShumGG** [comment]
i see, gonna fine-tune the code then, if i add again a geofence that exists it will automatically replace it? or i need to use ```.hasGeofence(identifier)``` to validate it?

**Comment by christocracy** [comment]
It will automatically replace it and reset the flags that the OS keeps, causing it to re-fire if the device is currently already inside, resulting in a double ENTER being experienced.

**Comment by ShumGG** [comment]
thanks chris, btw, im trying to execute code when the app is killed, i can see the console is printing but when im entering to the location the even doesnt fire

**Comment by christocracy** [comment]
See api docs Config.enableHeadless

**Comment by ShumGG** [comment]
enableHeadless is true, but when entering to the location doesnt fire the ```BackgroundGeolocation.onGeofence``` event, it does if the app is in background but killed - terminated it doesnt

**Comment by ShumGG** [comment]
the events im getting from ```BackgroundGeolocation.registerHeadlessTask(HeadlessTask);``` are **location** and **http** if i terminate the app, doesnt get the event **onEntering** or any other

**Comment by christocracy** [comment]
> BackgroundGeolocation.onGeofence executing many time

Is this issue solved?  If you have unrelated problems, you should post a new issue.

**Comment by ShumGG** [comment]
solved

**Comment by ShumGG** [comment]
sorry, need to open this again, issue still persist in android:

```

BackgroundGeolocation.onGeofence(geofence => {
    if (geofence.action === "ENTER") {
        getNotificationToken().then((token) => {
            const { extras } = geofence;
            NotificationTriggers.sendLocationNotification(token, extras);
            return;
        });
    }
});
```

executes many times even when its DWELL, not executing once as it suppose to

**Comment by christocracy** [comment]
Are you observing the plugin logs in adb logcat when this occurs?  Are you configuring debug: true to hear debug sound FX?

you are likely registering multiple JavaScript onGeofence listeners.

**Comment by ShumGG** [comment]
at the end everytime i enter to a geofence i remove it from the list, only way to stop it executing many times on android, ios works fine, just executes once, if user terminate - kill the app and open again i will add the geofences again

**Comment by christocracy** [comment]
I’ve never heard anyone report anything like this in 8 years.   I monitor an identical set of geofences around my neighborhood on all my Android test devices.  I field test every day.  There is no evidence of this ever happening to me.

I suggest you attempt to reproduce this behaviour in the the demo app on Play Store (linked in readme).  
- use *Advanced app*
- Long press on Map to add geofences.
