### ISSUE TITLE
iOS hourly location tracking

### ISSUE THREAD

**Issue by Rajdeo-Das** [transistorsoft/react-native-background-geolocation#1618]
How to track the hourly location of the device in the background in IOS.
  I need to capture the user's location every hour with or without their movement.

Environment
* Plugin version: ^4.8.1
* Platform: iOS 
* OS version: All iOS iPhone
* Device manufacturer / model: All iPhone.
* React Native version (`react-native -v`):

**Comment by christocracy** [comment]
That is a job for background-fetch, which is already installed.  See it’s readme.  Call .getCurrentPosition() in your BackgroundFetch callback.
