### ISSUE TITLE
The plugin not sendeing coordes when the app in the backgrond (app not killed)

### ISSUE THREAD

**Issue by AhmedTouti** [transistorsoft/react-native-background-geolocation#1620]
## Your Environment
* Plugin version:"^4.8.2"
* Platform:  Android
* OS version:  10 ,11,12,13
* Device manufacturer / model: tested in samsung , redmi ,oppo...
* React Native version :"0.61.5"
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 BackgroundGeolocation.ready({
      disableElasticity: true,
      showsBackgroundLocationIndicator: true,
      allowIdenticalLocations: true,
      stopOnTerminate: false,
      startOnBoot: true,
      preventSuspend: true,
      foregroundService: true,
      pausesLocationUpdatesAutomatically: false,
      isMoving: true,
      disableStopDetection: true,
      disableMotionActivityUpdates:true,
      allowIdenticalLocations: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
      locationAuthorizationRequest: 'Always',
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      url: `${API_BASE_URL}${API_VERSION}`,
      autoSync: true, 
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
    })

```

## Expected Behavior

keep sending coords  post requests to our server in background (app killed & not killed) & phone not moving .
## Actual Behavior
it stops after certain time (app in background not killed)
## Steps to Reproduce

1.lunch app
2.start the plugin 
3.put the app in the background  (not killed)
4.put the fone down in stable state .

## Context

drivers app , the plugin helps me , in our backend new location means the driver is onligne end ready to work (+ the status on ligne of course).
 

please  help ?,it will be appreciated.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Have you read the wiki *Philosophy of Operation*?

The plugin doesn’t record location when the device is in the “stationary” state.  That would needlessly consume the battery.

the plugin only records location when the device is detected to be moving.

**Comment by AhmedTouti** [comment]
Hello @christocracy  thank you for your time,I m aware of the stationary state philosophy, that's why I added these options : 
disableStopDetection: true,
disableMotionActivityUpdates:true,
 allowIdenticalLocations: true,
hoping to overcomes the stationary state , but still not sending ,the solution needed is to force the app to send post requests even if the phone is in the stationary state  to be able to detect the user location in every circumstances ,battery consoming is not an issue here.
Is there any solutions please.

**Comment by christocracy** [comment]
See Config.stopTimeout.  You can set that to a very large number.

also see method .changePace for manually changing state.

> disablemotionactivityupdates:true,

Do you know what this does?

**Comment by AhmedTouti** [comment]
Yes mr @christocracy disablemotionactivityupdates:true  means Disable motion-activity updates ,
I did give more than 1 day in minutes to Config.stopTimeout and kept disablemotionactivityupdates:false ,the updates take 2 hours and stop sending ,what config  you please recommend to fix this

**Comment by christocracy** [comment]
I suggest you observe your logs.  See wiki *Debugging* and learn to use the .emailLog method.
