### ISSUE TITLE
Monitor Geofences while App is in the Background

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1623]
## Your Environment
* Plugin version: "react-native-background-fetch": "^4.1.0", "react-native-background-geolocation": "^4.8.2",
* Platform: iOS 
* OS version: 16.2
* Device manufacturer / model: iPhone 14
* React Native version (`react-native -v`): "0.66.4",
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready({
      desiredAccuracy: BACKGROUND_TRACKING_ACCURACY_LEVEL_MAPPING[accuracy],
      stationaryRadius: 25,
      disableLocationAuthorizationAlert: true,
      stopOnTerminate: true,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: true, // enable to hear debug sounds
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // ios
      showsBackgroundLocationIndicator: true,
      // android
      allowIdenticalLocations: true,
      foregroundService: true,
      // location permissions
      locationAuthorizationRequest: 'WhenInUse',
      backgroundPermissionRationale: {
        title: "Allow XY to access to this device's location",
        message:
          'Some Description Text.',
        positiveAction: 'Allow',
        negativeAction: 'Cancel',
      },
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'You have not given XY Location Permissions',
        titleWhenOff: 'Location Services turned Off',
        instructions:
          "Some Description Text",
        cancelButton: 'Cancel',
        settingsButton: 'Settings',
      },
      notification: {
        title: 'XY',
        text: 'XY is tracking your location',
      },
    });
```

Is there a way to monitor Geofences in the background and somehow tell `react-native` that x-Geofences have been entered, even when the App went to the background for hours? This library provides the [startBackgroundTask](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#startbackgroundtask) but on iOS this method only runs 180s. So after 180s there is no way of knowing, that a Geofence has been crossed/visited/entered. Is there another way how to get this information?

**Comment by christocracy** [comment]
startBackgroundTask is not required for geofence monitoring.  If a geofence fires, the os awakens the app automatically and the plugin will fire the onGeofence event.

this plugin has the word “background” in its name because it’s designed to operate in the background.

**Comment by Stophface** [comment]
@christocracy thanks for the fast reply. Where is that event fired, in which subscription/method? In [onGefence()](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#ongeofence)?

**Comment by christocracy** [comment]
> Where is that event fired, onGeofence?

what do think the answer is?

**Comment by christocracy** [comment]
> locationAuthorizationRequest: 'WhenInUse'

Btw, for geofence monitoring, the OS requires *Always* authorization.

**Comment by Stophface** [comment]
@christocracy I suppose it is :) But I am not getting anything logged to the console when using this

```
BackgroundGeolocation.onGeofence(geofence => {
  console.log('[geofence] ', geofence.identifier, geofence.action);
});
```

eventhough I hear the sound that the module makes, when a Geofence is entered. But then, I am unmounting the component where I set up 

```
BackgroundGeolocation.onGeofence(geofence => {
  console.log('[geofence] ', geofence.identifier, geofence.action);
});
```

So this might be a problem. The location authorizations are all right.

**Comment by Stophface** [comment]
But I assume `BackgroundGeolocation.onGeofence(...)` is a `subscription? So it should not matter if the component is mounted or unmounted where I set it up?

**Comment by christocracy** [comment]
Why would you want an onGeofence subscription to fire in an unmounted component?

**Comment by Stophface** [comment]
I do not want to fire the onGeofence subscription in an unmounted component. I set up the subscription in a component which later then gets unmounted (because its removed from the navigation stack if the user navigates back). I am very new to subscriptions. I thought, once a subscription is set up, its not tied to the component/context/... its set up, but 'runs in the background'?

**Comment by christocracy** [comment]
What you’re subscribing with onGeofence is simply your own callback function that executes when a geofence fires.

must makes no sense to execute a callback function in an unmounted component, where the context of what you’d like to do with that callback no longer exists (Eg placing a map marker on a map which no longer exists).
