### ISSUE TITLE
Location does not change when running android 12

### ISSUE THREAD

**Issue by AndCordeiro** [transistorsoft/react-native-background-geolocation#1629]
## Your Environment
* Plugin version:"^4.9.4"
* Platform: Android
* OS version: 12
* Device manufacturer / model: Samsung Galaxy S21+ 5G 
* React Native version (`react-native -v`): "0.70.4"
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 0,
    disableElasticity: true,
    locationUpdateInterval: 1000,
    fastestLocationUpdateInterval: 60000,
    allowIdenticalLocations: true,
    locationAuthorizationRequest: 'Always',
    locationAuthorizationAlert: {
      titleWhenNotEnabled: translate(
        'home.locationAuthorizationAlert.titleWhenNotEnabled',
      ),
      titleWhenOff: translate('home.locationAuthorizationAlert.titleWhenOff'),
      instructions: translate('home.locationAuthorizationAlert.instructions'),
      cancelButton: translate('home.locationAuthorizationAlert.cancelButton'),
      settingsButton: translate(
        'home.locationAuthorizationAlert.settingsButton',
      ),
    },
    backgroundPermissionRationale: {
      title: translate('home.backgroundPermissionRationale.title'),
      message: translate('home.backgroundPermissionRationale.message'),
      positiveAction: translate(
        'home.backgroundPermissionRationale.positiveAction',
      ),
      negativeAction: translate(
        'home.backgroundPermissionRationale.negativeAction',
      ),
    },
    notification: {
      title: translate('home.notificationGPS.title'),
      text: translate('home.notificationGPS.text'),
      largeIcon: '@mipmap/ic_stat_polivias',
      smallIcon: '@mipmap/ic_stat_polivias',
    },
    pausesLocationUpdatesAutomatically: false,
    stopOnTerminate: false,
    startOnBoot: true,
    foregroundService: true,
    forceReloadOnBoot: true,
    enableHeadless: true,
    disableLocationAuthorizationAlert: true,
  });
  
  
  BackgroundGeolocation.watchPosition(
    location => {
      onSuccess(location);
    },
    () => {},
    {
      interval: 30000,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      persist: true,
      timeout: 60000,
    },
  );
```

## Expected Behavior

Capture device location while in progress.

## Actual Behavior

When the device starts on a highway with greater speed, it always captures the same location, when I reach the desired location, it captures the location correctly again.

## Steps to Reproduce

1.lunch app
2.start the plugin with watchPosition
3.go to the desired location

## Context

app helps monitor driver delivery.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
```

</details>

**Comment by christocracy** [comment]
.watchPosition is meant for short periods of time while your app is in the foreground.  That method is not required for the plug-in’s *Philosophy of Operation* (see the wiki).

All you need to do is call .start().  The plugin will **Automatically** start tracking when the device is detected to be moving.

Also see wiki *Debugging* and api docs for method .changePace

**Comment by christocracy** [comment]
Btw, I primarily develop on a Samsung Android 12 device in addition to a Pixel 6 on Android 13.  I field test daily.

**Comment by AndCordeiro** [comment]
In this case, should I replace watchPosition with onLocation?

No:
```
BackgroundGeolocation.watchPosition(
    location => {
          database()
            .push()
            .set({
              latitude: location.coords.latitude,
              longitude: location.coords.longitude,
              date: format(new Date(location.timestamp), 'yyyy/MM/dd HH:mm:ss'),
            });
        }
      }
    },
    () => {},
    {
      interval: 30000,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      persist: true,
      timeout: 60000,
    },
  );
```

yes: 
```
const onLocation:Subscription = BackgroundGeolocation.onLocation((location) => {
      database()
            .push()
            .set({
              latitude: location.coords.latitude,
              longitude: location.coords.longitude,
              date: format(new Date(location.timestamp), 'yyyy/MM/dd HH:mm:ss'),
            });
    })
```

**Comment by christocracy** [comment]
onLocation is an event-listener which is fired whenever ANY location is recorded, no matter how that location is initiated.

you need to tell the plugin to .start().

the plugin is like a stereo-received.  onLocation is like wiring up a speaker.  .start() / .stop() is the power switch.

forget about .watchPosition(), you don’t need it.

**Comment by AndCordeiro** [comment]
Thank you, I will test.

**Comment by christocracy** [comment]
.changePace(true) / .changePace(false) is the [ play] / [pause] button.

the plugin can detect when the device is moving (typically requires movement of about 200 meters) and *automatically* call .changePace upon itself.

You are not required to manually call .changePace(true) but a *Jogging app* would do so with its [Start Workout] button.

In order to call .changePace (ie “play”), you must first turn the power on (.start()).

**Comment by AndCordeiro** [comment]
I understand. I need to get the coordinates from time to time to send to firebase's raltime database. So I was using watchPosition.

**Comment by christocracy** [comment]
> I need to get the coordinates from time to time to send to firebase'

See api docs .getCurrentPosition.

**Comment by AndCordeiro** [comment]
To use .getCurrentPosition every 2 minutes. do i need to put it inside a settimeout?

**Comment by christocracy** [comment]
I think you mean setInterval.

**Comment by AndCordeiro** [comment]
That's it, sorry I wrote it wrong! Thanks!!!

**Comment by christocracy** [comment]
A more robust and power efficient way to fetch periodic location is use background-fetch, already imported as a dependency.  See it’s readme.
