### ISSUE TITLE
Location Symbol on iOS

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1631]
## Your Environment
* Plugin version: 4.8.2
* Platform: iOS
* OS version: Real Device iOS 16.1.1, Simulator 16.2
* Device manufacturer / model: iPhone 8
* React Native version (`react-native -v`): 9.2.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      desiredAccuracy: BACKGROUND_TRACKING_ACCURACY_LEVEL_MAPPING[accuracy],
      stationaryRadius: 25,
      distanceFilter: 50,
      disableElasticity: true,
      disableLocationAuthorizationAlert: true,
      stopOnTerminate: true,
      stopTimeout: 5,
      debug: false, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // ios
      showsBackgroundLocationIndicator: true,
      // android
      allowIdenticalLocations: true,
      foregroundService: true,
      // location permissions
      locationAuthorizationRequest: 'WhenInUse',
      backgroundPermissionRationale: {...},
    });
```

## Expected Behavior
I would expect the location indicator symbol on the top right corner next to the battery symbol to disappear, once I called
`BackgroundGeolocation.stop(() => {...})`.

## Actual Behavior
This happens on the simulator, but not on a real device. 

## Context
Currently I am taking this module for a spin away from the simulator. It works fine, but there is one thing I that comes unexpected.

# Simulator
When I run `BackgroundGeolocation.start(() => {...})`, there is the location arrow appearing next to the battery symbol. This is expected, because I am tracking the location.

<img width="391" alt="Screenshot 2023-01-27 at 19 58 04" src="https://user-images.githubusercontent.com/8275981/215171801-bd02b4e4-da82-41a0-ba41-95db3d131d0e.png">

When I put the App in the background, a second lcocation arrow is appearing int the middle of the screen.

<img width="379" alt="Screenshot 2023-01-27 at 19 56 53" src="https://user-images.githubusercontent.com/8275981/215171597-8a6963e1-066b-4b11-9ab2-fb6f0a91d697.png">

This is also expected. Now, when I stop tracking via `BackgroundGeolocation.stop(() => {...})` the location arrow in the middle *and*  next to the battery disappears. 

# Real device (release mode of App)
When I run `BackgroundGeolocation.start(() => {...})`, there is the location arrow appearing next to the battery symbol. This is expected, because I am tracking the location. When I put the App in the background, a second lcocation arrow is appearing int the middle of the screen. This is also expected. Now, when I stop tracking via `BackgroundGeolocation.stop(() => {...})` the location arrow in the middle  disappears. However, the location arrow next to the battery symbol stays. I can terminate the App completly, the arrow still persists. Additionally, I got asked by iOS that "The App XY is tracking my location for the last three days, do you want keep it doing it?". 

I would expect the location arrow to disappear, once I stop tracking with `BackgroundGeolocation.stop(() => {...})`.

**Comment by christocracy** [comment]
You can be sure that the plugin turns off all its location-listeners when you call .stop().

If the location icon does not turn off, it is the fault of one of your other components (Eg Map component).

**Comment by christocracy** [comment]
In just verified with the *Sample app*.  Calling .stop() causes the location icon to disappear after about 5s.

**Comment by christocracy** [comment]
This is not the first time over the last 8 years that something has posted a this sort of issue.

It’s never the plug-in’s fault.

**Comment by Stophface** [comment]
Perfect, thanks! I will investigate. Might be the Map in Conjunction with `react-native-navigation`, because that one does not unmount Components in the Navigation Stack.
