### ISSUE TITLE
GPS location works for some devices and not other of the exact same type - iOS

### ISSUE THREAD

**Issue by ajones2k** [transistorsoft/react-native-background-geolocation#1632]
## Your Environment
* Plugin version: 4.8.2
* Platform: iOS 
* OS version: 14.7.2
* Device manufacturer / model: iPad mini Gen 6 (brand new)
* React Native version (`react-native -v`): 0.70.4
* Plugin config
    let distFilter = Platform.OS == 'ios' ? 1 : 0;
    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: distFilter,
      disableElasticity: true,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up
      persistMode: BackgroundGeolocation.PERSIST_MODE_NONE,
      heartbeatInterval: 15,
      //android only
      allowIdenticalLocations : true,
      notification: {
        title: "NetForecast QMap",
        text: "Cellular Coverage Testing in Progress."
      },
      //ios only
      activityType : BackgroundGeolocation.ACTIVITY_TYPE_FITNESS,
      preventSuspend : true,
    }).then((state) => {
      this.setState({gpsEnabled: state.enabled});
    })
  }

## Expected Behavior
The users has 16 identical iPad minis. The app is in the foreground and they walk in a rectangle about 600 ft on a side four times. It is expected that the devices will nearly agree on the path of the devices during usage. The devices are on a cart so that they are not on top of one another. All app remain in the foreground.

## Actual Behavior
Only four of the devices provide a good trace of the path. Three only report one or two updates during the walk. The rest only provide a partial trace of the path (~50%). 

## Steps to Reproduce

1. This appears to happen at certain locations like Dallas and Denver, but works at others like Myrtle Beach or Las Vegas. 
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
This only happens when the customer is in the field. I have not been able to reproduce on my device / emulator. 
```

</details>

**Comment by christocracy** [comment]
See Wiki *Debugging*.  Learn to fetch logs from the plugin using `.emailLog(emailAddress)` method.

**Comment by christocracy** [comment]
Also, are these minis the Cellular or wifi only version?  You’ll have poor performance on wifi only devices.

**Comment by ajones2k** [comment]
I will work on fetching the logs. These are cellular devices. When the app is in the foreground measurements are taken by a timer. (When the app is in the background the measurements are trigger by the plugin). When the timer goes off the app uses the last GPS as stored in the state. I am thinking I am not seeing onLocation events consistantly across all devices.

**Comment by ajones2k** [comment]
I was able to resolve the issue by calling getCurrentPosition if the last position provided by OnLocation was more that 60 seconds old. I take actions based on a timeout between location and activity events. So when I take an action it might be based on an activity change as opposed to a location change.

**Comment by christocracy** [comment]
Is this issue closed?

**Comment by ajones2k** [comment]
Yes, thanks
