### ISSUE TITLE
iOS app crashes in background

### ISSUE THREAD

**Issue by Sharf8351** [transistorsoft/react-native-background-geolocation#1634]
iOS app is crashing on real device again and agin in background when it is killed. But on the simulator it is not crashing. I want to generate logs on real device so I can detect the actual problem. Please tell me how I can save the logs on a real device. Thanks.

**Comment by christocracy** [comment]
The issue template is **not optional — it’s required**:

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki *Debugging**.

**Comment by Sharf8351** [comment]
## Your Environment
* Plugin version:4.9.5
* Platform: iOS or Android: iOS
* OS version: 16.3
* Device manufacturer / model: Apple 13 pro max
* React Native version (`react-native -v`):0.67.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
```
export const initBackgroundGeolocation = async () => {
 
 subscribe(
    BackgroundGeolocation.onProviderChange((event) => {
    
    })
  );

  subscribe(
    BackgroundGeolocation.onLocation(
      (location) => {
 
      },
      (error) => {

      }
    )
  );

  subscribe(
    BackgroundGeolocation.onMotionChange((location) => {
      if (!location.isMoving) {
        //reactotron.log("Api call is being made");
        saveLocations();
      }
      //reactotron.log("[onMotionChange]", location);
    })
  );

  subscribe(
    BackgroundGeolocation.onConnectivityChange((event) => {
      //reactotron.log("[onConnectivityChange]", event);
    })
  );

  subscribe(
    BackgroundGeolocation.onEnabledChange((enabled) => {
      //reactotron.log("[onEnabledChange]", enabled);
    })
  );

  subscribe(
    BackgroundGeolocation.onHttp((event) => {
      //reactotron.log("[onHttp]", event);
    })
  );

  subscribe(
    BackgroundGeolocation.onActivityChange((event) => {
      if (event.activity == "still") {
        saveLocations();
      }
      //reactotron.log("[onActivityChange]", event);
    })
  );

  subscribe(
    BackgroundGeolocation.onPowerSaveChange((enabled) => {
      //reactotron.log("[onPowerSaveChange]", enabled);
    })
  );

  subscribe(
    BackgroundGeolocation.logger
      .emailLog("sharf835@gmail.com")
      .then((success) => {
        console.log("[emailLog] SUCCESS");
      })
      .catch((error) => {
        console.log("[emailLog] ERROR: ", error);
      })
  );

  /// Configure the plugin.
  BackgroundGeolocation.ready(
    {
     

      //activityType: BackgroundGeolocation.ACTIVITY_TYPE_FITNESS,
      stopOnStationary: false,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      disableElasticity: true,
      stopTimeout: 5,
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
      preventSuspend: false,
      headers: {
        "X-FOO": "bar",
      },
      locationAuthorizationRequest: "Always",
      disableLocationAuthorizationAlert: true,
      distanceFilter: distanceFilter,
      elasticityMultiplier: elasticityMultiplier,
    }

  ).then((location) => {
    BackgroundGeolocation.start();
    saveLocations();

  });
};
```

## Expected Behavior
The gps tracking should work in the background when the app is killed

## Actual Behavior
When the app is killed it crashes repeatedly in the background.

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
we are doing 24/7 gps tracking

## Debug logs
{
activityRecognitionInterval = 10000;
activityType = 1;
authorization = {
};
autoSync = 1;
autoSyncThreshold = 0;
batchSync = 0;
debug = 0;
desiredAccuracy = "-1";
desiredOdometerAccuracy = 100;
didDeviceReboot = 0;
didLaunchInBackground = 0;
didRequestUpgradeLocationAuthorization = 1;
disableAutoSyncOnCellular = 0;
disableElasticity = 1;
disableLocationAuthorizationAlert = 1;
disableMotionActivityUpdates = 0;
disableStopDetection = 0;
distanceFilter = 6;
elasticityMultiplier = 3;
enableTimestampMeta = 0;
enabled = 1;
extras = {
};
geofenceInitialTriggerEntry = 1;
geofenceProximityRadius = 2000;
geofenceTemplate = "";
headers = {
"X-FOO" = bar;
};
heartbeatInterval = 60;
httpRootProperty = location;
httpTimeout = 60000;
iOSHasWarnedLocationServicesOff = 0;
isFirstBoot = 0;
isMoving = 1;
lastLocationAuthorizationStatus = 3;
locationAuthorizationAlert = {
cancelButton = Cancel;
instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
settingsButton = Settings;
titleWhenNotEnabled = "Background location is not enabled";
titleWhenOff = "Location services are off";
};
locationAuthorizationRequest = Always;
locationTemplate = "";
locationTimeout = 60;
locationsOrderDirection = ASC;
logLevel = 5;
logMaxDays = 3;
maxBatchSize = "-1";
maxDaysToPersist = 1;
maxRecordsToPersist = "-1";
method = POST;
minimumActivityRecognitionConfidence = 70;
odometer = "8359.275269609136";
params = {
};
pausesLocationUpdatesAutomatically = 1;
persistMode = 2;
preventSuspend = 0;
schedule = (
);
schedulerEnabled = 0;
showsBackgroundLocationIndicator = 0;
startOnBoot = 1;
stationaryRadius = 25;
stopAfterElapsedMinutes = "-1";
stopDetectionDelay = 0;
stopOnStationary = 0;
stopOnTerminate = 0;
stopTimeout = 5;
trackingMode = 1;
url = "";
useSignificantChangesOnly = 0;
}
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->


PASTE_YOUR_LOGS_HERE
```

</details>

[background-geolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/10566442/background-geolocation.log)

**Comment by christocracy** [comment]
What makes you suspect the app is “*crashing*”?  Do you have a stacktrace proving this?  Steps to reproduce?

**Comment by Sharf8351** [comment]
## Steps to Reproduce

1.Open the app
2.Kill the app
3.When moving or some motion change the app crashes in background

**Comment by christocracy** [comment]
If there’s a crash, there’s a stacktrace recorded.  

https://developer.apple.com/news/?id=nra79npr
