### ISSUE TITLE
 FATAL EXCEPTION: pool-21-thread-5

### ISSUE THREAD

**Issue by Vish88781** [transistorsoft/react-native-background-geolocation#1635]
I/flutter (17569): ********* startBackgroundTask: 1
E/AndroidRuntime(17569): FATAL EXCEPTION: pool-21-thread-5
E/AndroidRuntime(17569): Process: package name, PID: 17569
E/AndroidRuntime(17569): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~itAWtDwAr7olrA6oQ9ShHQ==/package name -2rKjSQ0BDOE7dI-qaG6cnw==/base.apk)
E/AndroidRuntime(17569): 	at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:123)
E/AndroidRuntime(17569): 	at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:74)
E/AndroidRuntime(17569): 	at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
E/AndroidRuntime(17569): 	at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
E/AndroidRuntime(17569): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(17569): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(17569): 	at java.lang.Thread.run(Thread.java:923)
D/AppCompatDelegate(17569): Checking for metadata for AppLocalesMetadataHolderService : Service not found
D/AndroidRuntime(17569): Shutting down VM
E/AndroidRuntime(17569): FATAL EXCEPTION: main
E/AndroidRuntime(17569): Process: Package name, PID: 17569
E/AndroidRuntime(17569): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~itAWtDwAr7olrA6oQ9ShHQ==/package name-2rKjSQ0BDOE7dI-qaG6cnw==/base.apk)

**Comment by christocracy** [comment]
The issue template is *not optional*, it’s **required**.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> I/flutter (17569): ********* startBackgroundTask: 1

Also, you seem to be using a *Flutter* app — do you know that this is the *React Native* repo? 

This plugin exists for 4 different frameworks (Cordova, Capacitor, React Native and Flutter).

**Comment by Vish88781** [comment]
I am using your plugin for 2 years with flutter, but just a few days back when i update flutter  3.7.0 ,    gradle version 7.6 , and  JDK --19.0.2the above exception terminate the app.  

Step ------1

Flutter  version detail [√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.2486], locale en-VG)
    • Flutter version 3.7.0 on channel stable at C:\flutter_windows_3.3.10-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (9 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

Step -----2

[flutter_background_geolocation] Purging debug resources in release build
*****************************************************
* [WARNING] background-geolocation requires a maximum googlePlayServicesLocationVersion of 20.0.0 due to breaking changes in v21
* googlePlayServicesLocationVersion has been overridden to 20.0.0
*****************************************************

Step -----3
[requestPermission] authorized Always: 3
I/TSLocationManager( 8251): - Enable: false → true, trackingMode: 1
W/Settings( 8251): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
I/flutter ( 8251): [start] success: [State enabled: true, isMoving: false, trackingMode: 1, desiredAccuracy: 0, distanceFilter: 10.0, odometer: 0.0, schedulerEnabled: false, foregroundService: true]
I/flutter ( 8251): ********* startBackgroundTask: 1

Step--- 4  (exception part)

FATAL EXCEPTION: pool-21-thread-5
E/AndroidRuntime( 8251): Process: Package Name PID: 8251
E/AndroidRuntime( 8251): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~n0waUNnew-vDP6AtRcPjkQ==/Package Name -CkbyWG4_MCPOE9S-swqAXQ==/base.apk)
E/AndroidRuntime( 8251): 	at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:129)
E/AndroidRuntime( 8251): 	at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:78)
E/AndroidRuntime( 8251): 	at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
E/AndroidRuntime( 8251): 	at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
E/AndroidRuntime( 8251): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 8251): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 8251): 	at java.lang.Thread.run(Thread.java:923)
D/AppCompatDelegate( 8251): Checking for metadata for AppLocalesMetadataHolderService : Service not found
D/AndroidRuntime( 8251): Shutting down VM
E/AndroidRuntime( 8251): FATAL EXCEPTION: main
E/AndroidRuntime( 8251): Process: Package Name , PID: 8251

**Comment by christocracy** [comment]
> I am using your plugin for 2 years with flutter

Did you not read what I wrote?  You’re posting at the wrong repo.  It’s like you’re going through to *Burger King* and trying to order a *Big Mac*.

go seek support at the Flutter repo.
