### ISSUE TITLE
Sendbird Chat SDK is not able to make websocket connection while location is updating

### ISSUE THREAD

**Issue by tarkcelk** [transistorsoft/react-native-background-geolocation#1638]
## Your Environment
* Plugin version:4.10.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: Samsung / Galaxy A02s
* React Native version (`react-native -v`): 0.66.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        stationaryRadius: 50,
        distanceFilter: 100,
        startOnBoot: true,
        stopOnTerminate: false,
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        enableHeadless: true,
        stopTimeout: 5,
        notification: {
          title: 'Location Tracking',
          text: 'ACTIVE',
        },
        url: `some endpoint that we send location informations`,
        headers: {
          some headers
        },
        params: {
          platform: Platform.OS,
        },
      }).then((state) => {
         if (!state.enabled) BackgroundGeolocation.start();
      });
```

## Expected Behavior
Successful connection of Sendbird websocket connections.

## Actual Behavior
While location updates happen simultaneously, Sendbird Chat SDK websocket couldn't make connections. 

## Steps to Reproduce

1. Open application and see the notification about the geolocation tracking.
2. Mock location with Fake GPS.
3. Saw the location updates on the logcat.
4. Try to connect sendbird while location update.

## Context
We're using a licensed package called Sendbird Chat SDK, with that package sometime Sendbird Chat SDK is not able to connect despite we call the connection method. The case only happens in android devices and for the release build.  Does this package prevent or block unintentionally other websocket connections or http requests while it's sending location informations simultaneously, are there any method that we can apply to prevent this from happening ? 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
[tslocation_logs_android.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/10682975/tslocation_logs_android.txt)


```

</details>

**Comment by christocracy** [comment]
> Does this package prevent or block unintentionally other websocket 

No,  thousands of others use web sockets in their app with this plugin.

**Comment by christocracy** [comment]
I doubt it is possible for this plugin to disrupt a web socket.

**Comment by ademirtemur** [comment]
while a process is running on plugin, websocket connection is stopping and connection drops and application is freezes.

**Comment by christocracy** [comment]
Create a simple HelloWorld project which reproduces your problem, commit to a public GitHub repo and share it here

**Comment by zeeshan-shabbir** [comment]
@christocracy Is This libary support websockets i:e socket Io? now

**Comment by tarkcelk** [comment]
Hi @christocracy , it was related to Sendbird SDK, we can close the issue.
