### ISSUE TITLE
Log trail missing for generated logs, unable to diagnose the root cause.

### ISSUE THREAD

**Issue by hadikhan-inserito** [transistorsoft/react-native-background-geolocation#1642]
Our app is currently showing a technical problem, that the background service has stopped and there are no logs available. The logs are not being generated, which is making it difficult to determine the cause of the issue with the background service.

## Your Environment

Plugin version:

* Platform: ANDROID

* OS version: : Android 9 / Android 11

* Device manufacturer / model: HUAWEI JKM-LX1 (HUAWEI Y9 2019) / OnePlus BE2029 (OnePlus Nord N10 5G)

* React Native version (`react-native -v`):  9.3.2

* Plugin config

```javascript <!-- Syntax-highlighting:  paste your code below -->

// config

import BackgroundGeolocation from "react-native-background-geolocation";

import { API_URL } from "../utils";

export const config = {

  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,

  debug: true,

  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,

  stopOnTerminate: false,

  batchSync: true,

  autoSyncThreshold: 0,

  startOnBoot: true,

  autoSync: true,

  geofenceModeHighAccuracy: true,

  preventSuspend: true,

  maxDaysToPersist: 90,

  backgroundPermissionRationale: {

    title: "Allow {applicationName} to access to this device's location in the background?",

    message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",

    positiveAction: "Change to {backgroundPermissionOptionLabel}",

    negativeAction: "Cancel",

  },

  locationAuthorizationRequest: 'Always',

  url: `${API_URL}/geofence-event`,

  method: "POST",

}

  
 

// Main DashboardScreen.js

React.useEffect(() => {

  
 

    const onLocation = BackgroundGeolocation.onLocation(location => {

      console.log('[onLocation]', location);

    });

  
 

    const onMotionChange = BackgroundGeolocation.onMotionChange(event => {

      console.log('[onMotionChange]', event);

    });

  
 

    const onActivityChange = BackgroundGeolocation.onActivityChange(event => {

      console.log('[onActivityChange]', event);

    });

  
 

    const onProviderChange = BackgroundGeolocation.onProviderChange(event => {

      console.log('[onProviderChange]', event);

    });

  
 

    const onGeofence = BackgroundGeolocation.onGeofence(geofence => {

      setGeofenceEventMessage(

        `You have ${geofence.action === 'ENTER' ? 'entered' : 'left'} ${geofence.identifier}`,

      );

      setShowGeofenceEvent(true);

    });

  
 

    const onHeartbeat = BackgroundGeolocation.onHeartbeat(event => {

      console.log('[onHeartbeat] ', event);

    });

    /// 2. ready the plugin.

    if (userData?._id) {

      BackgroundGeolocation.ready({

        ...config,

        extras: {

          userId: userData?._id

        },

        headers: {

          "Content-Type": "application/json",

          "Authorization": `Bearer ${userData?.accessToken}`

        },

      }).then(async (state) => {

        setEnabled(state.enabled)

        if (!state.enabled) {

          BackgroundGeolocation.startGeofences();

        } else {

          try {

            const permission = await BackgroundGeolocation.requestPermission();

          } catch (error) {

            console.warn('[requestPermission] FAILURE: ', error);

          }

        }

      });

  
 

      if (userData?.site?.siteName) {

        BackgroundGeolocation.removeGeofences().then(success => {

          console.log('[removeGeofences] all geofences have been destroyed');

          BackgroundGeolocation.addGeofence({

            identifier: userData?.site?.siteName,

            radius: userData?.site?.siteRadius,

            latitude: userData?.site?.siteCoordinates?.lat,

            longitude: userData?.site?.siteCoordinates?.lng,

            notifyOnEntry: true,

            notifyOnExit: true,

          })

            .then(success => {

              console.log(`[addGeofence] ${userData?.site?.siteName} added.`);

            })

            .catch(error => {

              console.log('[addGeofence] FAILURE: ', error);

            });

        });

      }

    }

    return () => {

      onLocation.remove();

      onMotionChange.remove();

      onActivityChange.remove();

      onProviderChange.remove();

      onGeofence.remove();

      onHeartbeat.remove();

    };

  }, [userData]);

  React.useEffect(() => {

    BackgroundGeolocation.getState().then(state => console.log("[state] ", state.enabled, state.trackingMode));

    if (enabled) {

      console.log('STARTED');

    } else {

      console.log('STOPPED');

    }

  }, [enabled]);

```

  
 

## Expected Behavior

The expected behavior of the background service is to run continuously without any interruptions. If the background service has stopped unexpectedly, The lack of logs to diagnose the issue is adding to the problem and making it more difficult to resolve. The goal is to restore the background service to its expected behavior of running continuously and providing a record of its activity through stored logs.

  
 

## Actual Behavior

The actual behavior of the background services is that it has stopped functioning unexpectedly and is not generating logs. This unexpected cessation of activity is causing problems for users who rely on the background service and its log records. You can find the log breaks on the following line number

  
File: shariq-logs - Line : 241529 / 241890
File : josy-logs -   Line : 4724 / 4939
  
  
 

## Context

This issue is recieved from an end user, so we are not able to diagnose it fully as there is a break in log traces.

  
 
Josy - logs

| Test Case   | Device / Platform |  App State | 
|---|---|---|
| 02-17 | 05:01 | finish GeofencingService | - |  4724 |
| 02-20 | 22:31 | TSGeofenceManager monitoring  | INFO |  4939 |
| CheckIn/CheckOut  | HUAWEI JKM-LX1 (HUAWEI Y9 2019)  | unknown  |

Shariq - logs

| Test Case  | Device / Platform  | App State  | 
|---|---|---|
| 02-19 | 23:31 | LocationRequestService   | 
| 02-20 | 08:30 | Cleared logs older than 480 hours  |
| 02-20 | 14:42 | Geofencing Event| 
| CheckIn/CheckOut  |  OnePlus BE2029 (OnePlus Nord N10 5G)  | unknown  |
 

## Steps to Reproduce

1.  

2.  

3.  

  
 

## Debug logs

<details><summary>Logs</summary>

  
 

``` <!-- Syntax highlighting:  DO NOT REMOVE -->

PASTE_YOUR_LOGS_HERE

```

  
[Josy-logs.log](https://github.com/transistorsoft/react-native-background-geolocation/files/10791274/Josy-logs.log)
[Syed-shariq-logs.log](https://github.com/transistorsoft/react-native-background-geolocation/files/10791275/Syed-shariq-logs.log)

 

</details>

**Comment by christocracy** [comment]
See http://dontkillmyapp.com
