### ISSUE TITLE
Prebuild on Android platform fails with the latest Expo SDK (48)

### ISSUE THREAD

**Issue by r-hirsch** [transistorsoft/react-native-background-geolocation#1644]
Upgrading from Expo 47 (where this package works) to 48 and came across an error. Created a new Expo app, installed and setup this package as per the Expo setup instructions and noticed the Expo prebuild command for the Android platform throws an error (see logs). The prebuild for iOS platform is successful. Judging by the error I assume the [Android config plugin](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/expo/plugin/src/androidPlugin.ts) is not compatible with the latest version of Expo.

## Your Environment
* Plugin version: 4.10.0
* Platform: Android
* OS version: MacOS Monterey 12.5.1
* Device manufacturer / model: MacBook Pro
* React Native version (`react-native -v`): 0.71.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
"plugins": [
      [
        "react-native-background-geolocation",
        {
          "license": "YOUR_LICENSE_KEY_HERE"
        }
      ],
      [
        "expo-gradle-ext-vars",
        {
          "googlePlayServicesLocationVersion": "20.0.0",
          "appCompatVersion": "1.4.2"
        }
      ],
      "react-native-background-fetch"
    ]
```

## Expected Behavior
`npx expo prebuild --platform android` builds the Android native code.

## Actual Behavior
An error occurs, see log below.

## Steps to Reproduce
1. [Create a new Expo app](https://docs.expo.dev/get-started/create-a-new-app/)
2. [Follow Expo Setup instructions for React Native Background Geolocation](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md)
3. Run `npx expo prebuild`

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
✖ Config sync failed
Error: [android.projectBuildGradle]: withAndroidProjectBuildGradleBaseMod: Failed to match "/mavenLocal\(\)/" in contents:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '33.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '21')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '33')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '33')
        if (findProperty('android.kotlinVersion')) {
            kotlinVersion = findProperty('android.kotlinVersion')
        }
        frescoVersion = findProperty('expo.frescoVersion') ?: '2.5.0'

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.4.1')
        classpath('com.facebook.react:react-native-gradle-plugin')
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(['node', '--print', "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), '../android'))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(['node', '--print', "require.resolve('jsc-android/package.json')"].execute(null, rootDir).text.trim(), '../dist'))
        }

        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}
```

</details>

**Comment by christocracy** [comment]
My Expo plug-in uses regular expressions to decide where to insert setup code.

It looks like I made assumptions on lines that would exist for a long time but were removed in recent expo.

I will have to upgrade the expo plug-in.

**Comment by t34Virus** [comment]
@christocracy 
I'm running into the same issue. Do you have a recommended workaround?

**Comment by christocracy** [comment]
Rollback to a previous version of Expo.  I'm on vacation until Friday.

**Comment by throwaway34241** [comment]
Which version did you rollback to? I tried until 43, and still got the same error, and have doubts rolling back to an even earlier version.

**Comment by ElpayetSupervan** [comment]
I rolled back to Expo v47, it works fine.

**Comment by christocracy** [comment]
I'm back from vacation.  I'll look into it this week.

**Comment by christocracy** [comment]
Ok, I've reproduced the error.  It's a simple fix for both `react-native-background-geolocation` and `react-native-background-fetch`.

Updates will be released tomorrow.

```diff
newSrc: `\tmaven { url "\${project(":${MODULE_NAME}").projectDir}/libs" }`,
-    anchor: /mavenLocal\(\)/,
-    offset: 1,
+    anchor: /maven\s\{/,
+    offset: 0,
     comment: "//",
   }).contents;
 }
@@ -69,7 +69,7 @@ const applyAppGradle = (buildGradle:string) => {
     tag: `[${MODULE_NAME}]-project`,
     src: buildGradle,
     newSrc: newSrc.join("\n"),
-    anchor: /\"react\.gradle\"\)/,
+    anchor: /android\s\{/,
     offset: 1,
     comment: "//",
   }).contents;
```

**Comment by r-hirsch** [comment]
That's great news, thank you for looking into this and keeping us updated.

**Comment by christocracy** [comment]
Ok, published fixes 
- `react-native-background-fetch@1.1.9`
- `react-native-background-geolocation@4.10.1`

Install both and run `npx expo prebuild`

**Comment by r-hirsch** [comment]
Can confirm the upgraded dependencies resolve this issue! Thank you for the fix and the quick turn around.

Small note: typo in the above message for react-native-background-fetch package version - should be 4.1.9 not 1.1.9.
