### ISSUE TITLE
Not able to get updated data in android emulator

### ISSUE THREAD

**Issue by mansi-acquaintsoft** [transistorsoft/react-native-background-geolocation#1648]
I have no issue with ios, but I am not getting updated data into android during the application is in a kill state. I am using an android emulator for the testing.

Is there any suggestion?

**Comment by christocracy** [comment]
And see wiki "Debugging" and learn to observe the plug-in logs.

**Comment by mansi-acquaintsoft** [comment]
@christocracy , Is there any way to hide/remove notifications from ios?

**Comment by mansi-acquaintsoft** [comment]
@christocracy Sorry to disturb you, but May I know that after releasing an android which methods will not work?

**Comment by christocracy** [comment]
Without a license key, the plug-in will not refuse to initiate tracking in release builds.
