### ISSUE TITLE
Get permission status for Health & Fitness data

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1649]
## Your Environment
* Plugin version: 4.8.2
* Platform: iOS
* OS version: Real Device iOS 16.1.1, Simulator 16.2
* Device manufacturer / model: iPhone 8
* React Native version (`react-native -v`): 9.2.0

## Expected Behavior
Is there a method to get the permissions status for the Health & Fitness Data? I cannot find it in the documentation. 

## Context
Telling the user which permission are given.

**Comment by christocracy** [comment]
>Is there a method to get the permissions status for the Health & Fitness Data? I cannot find it in the documentation.

No.  This permission is not crucial to the plugin's performance.

**Comment by Stophface** [comment]
thanks.
