### ISSUE TITLE
I got this error in Xcode after manually installing and run the project 

### ISSUE THREAD

**Issue by nshung** [transistorsoft/react-native-background-geolocation#165]
![screen shot 2016-11-05 at 20 53 16](https://cloud.githubusercontent.com/assets/7210851/20033282/678c999e-a39d-11e6-977f-baa9e910798f.png)

How can I fix this?

**Comment by christocracy** [comment]
What version of the plugin do you have installed?

I did remove the `CocoaLumberjack` static library from this plugin's `TSLocationManager.framework` in 1.5.3, which I forgot to `npm release`.  I've just released npm version `1.5.4`.

As a result, the manual installation instructions you followed in the master branch were probably for versions `<1.5.2`, which didn't include the extra added step of adding the new `cocoa-lumberjack` project.

I just created a fresh app using `1.5.2` and got the build-errors you reported (as I expected).

Upgrading to latest `1.5.4` then performing the extra installation step fixed my errors and my app boots.

Installing latest from npm (`1.5.4`) should install 2 extra dependencies:
```
$ npm install --save react-native-background-geolocation
└─┬ react-native-background-geolocation@1.5.4
  ├── cocoa-lumberjack@3.0.3
  └── react-native-background-fetch@1.0.0
```

**Comment by christocracy** [comment]
This will be closed soon for lack of feedback.

**Comment by nouveller** [comment]
I've just ran into this exact issue, so will test your fix now.

**Comment by nouveller** [comment]
All good, this resolved the issue for me.
