### ISSUE TITLE
Get information about terminating of Module

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1650]
## Your Environment
* Plugin version: 4.8.2
* Platform: iOS
* OS version: Real Device iOS 16.1.1, Simulator 16.2
* Device manufacturer / model: iPhone 8
* React Native version (`react-native -v`): 9.2.0

## Expected Behavior
This is more of a question than a bug report. I wonder: Is there a way the module can tell us, if the user has quitted and re-opened the app. And by quitted I mean not minimized, but actually (force) killed it. As far as my knowledge goes there is no way to tell that on the JS side. Once the user kills the app, no JS is running anymore. This is cumbersome, because the UI (normally) gives Feedback if the user is tracking the position. However, when `stopOnTerminate`  is set to `true` and the user force kills the app, the UI (upon re-opening the App) still feedbacks "Tracking", eventhough it is not tracking anymore... So I wonder if there is a method or something that the Module provides to tell "Hey, I was force quitted the last time you called `.ready()`" Is there a method to call to check, if the Module is still tracking the location? To get the current operating status of the module?  Or anything comparable? Something where I can derive this information from?

**Comment by christocracy** [comment]
For iOS, you cannot know this.

**Comment by christocracy** [comment]
> when stopOnTerminate is set to true and the user force kills the app, the UI (upon re-opening the App) still feedbacks "Tracking", eventhough it is not tracking anymore

If the user launches your app, it must necessarily have been terminated before.  The app `launch` notification is all you need to know to be confident that your app was terminated.

**Comment by Stophface** [comment]
@christocracy thanks for your fast reply. What is the app launch notification? Could you pin point me into the right direction here?

**Comment by christocracy** [comment]
Search "*react-native LifeCycle*"

**Comment by Stophface** [comment]
Oh dear.... For sure, I can use the Life Cycle Methods for that. I have not thought of that. Thanks a lot @christocracy, I really appreciate your ongoing (quick) support!
