### ISSUE TITLE
locationUpdateInterval: 10000, not sending location to my server

### ISSUE THREAD

**Issue by zahoormohammed** [transistorsoft/react-native-background-geolocation#1657]
locationUpdateInterval: 10000, not sending location to my server every 10 secs, this my code 

BackgroundGeolocation.ready({

      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access to this device's location in the background?",
        message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
        positiveAction: "Change to {backgroundPermissionOptionLabel}",
        negativeAction: "Cancel"
      } ,
      
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      disableElasticity:true,
      // https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#locationupdateinterval
      distanceFilter: 0,
     
      locationUpdateInterval: 10000,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,       
      
      // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      
      url: "https://hrete-qa.henceforthtek.com:9092/tracking/" + empid + "/" + roleIds1,
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "X-FOO": "bar"
      },
      params: {               // <-- Optional HTTP params
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
    }).then((state) => {
      setEnabled(state.enabled)
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
    });

    return () => {
      // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
      // during development live-reload.  Without this, event-listeners will accumulate with
      // each refresh during live-reload.
      onLocation.remove();
      onMotionChange.remove();
      onActivityChange.remove();
      onProviderChange.remove();
    }
  }
  catch (err) {
    console.log(err);
  }
}

i kept distancefilter to 0, because i want to get location even when device is in stationary , i kept distanceelasticity to true, and distancefilter to 0, now it is not giving any sound when i do backgroundlocation.start every 10 seconds, i want this code to send location to my server every 10 seconds even if device is stationary,

**Comment by christocracy** [comment]
The purpose of this plug-in is to conserve energy by only turning on location services when the device is detected to be moving.

when the device is stationary, location-services are off.

what would be the point wasting energy reporting the same location over and over while the device is known to be stationary?

**Comment by christocracy** [comment]
See wiki “Philosophy of Operation”

**Comment by zahoormohammed** [comment]
you are correct mr christocracy, but my company wants your plugin to detect location even when the device is stationary, for testing purpose i kept locationupdateinterval to 10, but my company wants to capture location every 30 mins, even if device is stationary, is there any possiblity of achieving this?

**Comment by christocracy** [comment]
Recording location periodically is precisely what background-fetch is for (already included as a dependency).

see it’s readme.  You are free to call BackgroundGeolocation.getCurrentPosition() in the background-fetch callback.
