### ISSUE TITLE
Tracking location without start the service

### ISSUE THREAD

**Issue by BrianRubioDuran** [transistorsoft/react-native-background-geolocation#1663]
## Your Environment
* Plugin version: 4.11.0
* Platform: iOS
* OS version: 15.x-16.x
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 0.70.7
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 const startBackgroundLocation = useCallback(async () => {
    try {
      setIsSendingLocation(true);
      sleep(2000);

      BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
        logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
        stopOnTerminate: false,
        geofenceInitialTriggerEntry: true,
        activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
        locationAuthorizationRequest: 'Always',
        stopTimeout: 15,
        preventSuspend: true,
        heartbeatInterval: 30,
        pausesLocationUpdatesAutomatically: false,
        allowIdenticalLocations: true,
        distanceFilter: 10,
        elasticityMultiplier: 8,
        showsBackgroundLocationIndicator: true,
      }).then(() => {
        BackgroundGeolocation.changePace(true);
      });
      BackgroundGeolocation.start();
      if (__DEV__) {
        console.log('Start Background Location');
      }
    } catch (error) {
      console.warn('- BackgroundGeolocation error: ', error);
    }
  }, []);

  const stopBackgroundLocation = useCallback(async () => {
    try {
      BackgroundGeolocation.changePace(false);
      await BackgroundGeolocation.removeListeners();
      await BackgroundGeolocation.stop();
    } catch (e) {}
  }, []);

  useEffect(() => {
      BackgroundGeolocation.onLocation(setPosition);
      BackgroundGeolocation.onSchedule(setPosition);
      BackgroundGeolocation.onHeartbeat(() => {
        BackgroundGeolocation.getCurrentPosition({
          samples: 1,
          persist: true,
        }).then((p: any) => {
          setPosition(p);
          sendLocation(p);
        });
      });
      BackgroundGeolocation.getCurrentPosition({
        timeout: 30, // 30 second timeout to fetch location
        persist: true, // Defaults to state.enabled
        maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
        desiredAccuracy: 10, // Try to fetch a location with an accuracy of `10` meters.
        samples: 3, // How many location samples to attempt.
        extras: {
          // Custom meta-data.
          route_id: 123,
        },
      }).then((p: any) => {
        setPosition(p);
        sendLocation(p);
      });
  }, [sendLocation]);
```

## Expected Behavior

We have the start/stop function that it's triggered only when the user press a button and it's working as expected
## Actual Behavior

It looks like the library it's tracking the user even when the user has NEVER pressed on start button, we are registering when the user are starting/stopping the service and in effect, the user are not pressing the start button. We have the indicator enabled and it's no appearing on the affected users phone (what is correct), so this indicates that the service it's not running intentionally.

The problem is what the users are reporting that iOS system dialog of "X APP has been using your location on background" appears,why this could happen? 
## Steps to Reproduce

1. Copy the code on your app.tsx file
2. request and allow the motion usage/ location always
3. wait 
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
any log
```

</details>

**Comment by tchiteu** [comment]
I have the same problem. @christocracy Is it possible that other localization libraries end up interfering?

**Comment by christocracy** [comment]
> Is it possible that other localization libraries end up interfering?

I have no idea.  One thing that is certain:  if you tell *this* plug-in to `.stop()` it is 100% guaranteed that this plug-in is not turning on location-services and recording locations.

you can easily test this in the /example app here in this repo.

**Comment by tchiteu** [comment]
> 
> I have no idea. One thing that is certain: if you tell _this_ plug-in to `.stop()` it is 100% guaranteed that this plug-in is not turning on location-services and recording locations.
> 
> you can easily test this in the /example app here in this repo.

I found the problem, it's nothing with the library. Thank you for your attention.
