### ISSUE TITLE
The GPS is not accurate on the device

### ISSUE THREAD

**Issue by TranNghiaHiep** [transistorsoft/react-native-background-geolocation#1668]
## Your Environment
* Plugin version: 4.9.3
* Platform: Both iOS and Android
* OS version: Android 12
* Device manufacturer / model: a32 - SM-A325F
* React Native version (`react-native -v`): 0.67.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
    preventSuspend: true,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    stopOnTerminate: false,
    forceRequestLocation: true,
    stopTimeout: 999,
    enableHeadless: true,
    distanceFilter: 10,
    autoSync: true,
    isMoving: true,
    heartbeatInterval: 1,
    startOnBoot: true,
    disableLocationAuthorizationAlert: true,
});
```

## Expected Behavior

When the device is not moving, GPS jumps and slides far away from reality.
## Actual Behavior

Is there any issue or solution to limit this issue?
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
```

</details>

**Comment by christocracy** [comment]
Show me what you’re talking about with a map screenshot.

I do not have this problem on my devices.

**Comment by christocracy** [comment]
>forceRequestLocation: true,

what is this?  That is not a recognized option of this plug-in.

> autoSync: true,

I don’t think you know what this option is.  If you don’t provide an `url` in your Config, there’s no server url for the plugin to “sync” with.  Pointless.

**Comment by TranNghiaHiep** [comment]
Although the device is not moving, GPS records as if it is moving, with a distance far from the current location of the device

![Screen Shot 2023-04-13 at 09 30 27](https://user-images.githubusercontent.com/27014665/231632260-83a28b56-04af-41db-82f0-f7347a867088.png)

**Comment by TranNghiaHiep** [comment]
> > forceRequestLocation: true,
> 
> what is this? That is not a recognized option of this plug-in.
> 
> > autoSync: true,
> 
> I don’t think you know what this option is. If you don’t provide an `url` in your Config, there’s no server url for the plugin to “sync” with. Pointless.

Thank you, I will reconsider the url configuration.

**Comment by christocracy** [comment]
> stopTimeout: 999,

Do you know what this does?

do you know that GPS doesn’t work indoors?  When indoors, location comes from WiFi (accuracy 40-100 meters).

go outside for a nice long walk and you see the plug-in tracks perfectly well with accuracy ~5m.
