### ISSUE TITLE
[Question] Android GPS Only & Activity Tracking

### ISSUE THREAD

**Issue by Maxwell2022** [transistorsoft/react-native-background-geolocation#167]
Thanks for the work first, very easy to use plugin!

I'm using the version `2.1.4` of your premium plugin. About my application: The goal is to detect when a user is getting close to predefined location (cities). I'm using a custom build detection, based on a location service. I'm just using the location callback (GPS coordinates) to determine if the user is close enough of a location, or not, to notify him.

I managed to install and use the plugin on Android (>4.4) and iOS but I have 2 questions:

- On Android device, when the location service mode is set to "A-GPS only" the plugin is returning some 408 errors:
```
W/TSLocationManager: [c.t.l.l.TSLocationManager forceAcquireStationaryLocation] 
                       ⚠️  Failed to acquire stationary location from last-known-location
W/TSLocationManager: [c.t.l.a.BackgroundGeolocation onLocationError] 
                       ⚠️  Location error: 408
E/TSLocationManager: location error: 408
```
However as soon as I enable "High accuracy (A-GPS and networks)" it start working. I'm not sure what I can do to fix this. What happens if you don't have 3G or WIFI connection (any network connection)? Is the plugin suppose to work with GPS only?

- On Android when launching the app, it still requires the "Activity Recognition" event tho I disabled it in the configuration `disableMotionActivityUpdates: true`. Full configuration: 
```
bgGeo.configure({
    // Geolocation config
    desiredAccuracy: 0,
    distanceFilter: 200,
    stationaryRadius: 500,
    locationUpdateInterval: 5000, // in ms
    fastestLocationUpdateInterval: 5000, // in ms, Android only

    disableMotionActivityUpdates: true, // Disable activity tracking

    // Activity Recognition config
    activityType: 'AutomotiveNavigation',
    activityRecognitionInterval: 5000,
    stopTimeout: 5,

    // Application config
    debug: true,
    stopOnTerminate: false,
    startOnBoot: true,
}, function() { ... });
```
Also, on iOS, in debug mode I can see motion tracking logs, but it's not requiring it any more when launching the app (it used to required access to fitness data).

Thanks again for your help, 
Maxime

**Comment by christocracy** [comment]
The plugin uses Google Play Services' [FusedLocationProviderAPI](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi).  This API "fuses" all locations providers together to achieve the best possible location.  When you configure: 
`desiredAccuracy: 0`:  that means GPS + Network + Cell.
`desiredAccuracy: 10`: Network + Cell triangulation
`desiredAccuracy: 100`: Network (low power) + Cell
`desiredAccuracy: 1000` Cell only

Native location-services are like a tap of water.  The plugin provides you an API to "adjust the temperateure" (`desiredAccuracy`) and flow-rate (`distanceFilter`).  The water that comes out of the tap (locations) is completely up to your device & network environment.

- `disableMotionActivityUpdates` is an iOS-only config.  This merely disables use of the M7 co-processor (which requires "Motion & Fitness" permission.  The iOS plugin is **highly** optimized to use this so don't disable that.  If you *do*, iOS will use my custom-baked accelerometer-only motion-detection system which isn't nearly as good as [CMMotionActivityManager](https://developer.apple.com/reference/coremotion/cmmotionactivitymanager).

The plugin has 2 states:  **stationary** (location-services OFF) and **moving** (location-services ON).  The plugin's core philosophy is built around "motion detection", detecting when the device is moving and stationary.

**Comment by Maxwell2022** [comment]
Hi Chris, 

Thanks for your quick answers. First I'm sorry but I think I post this issue in the wrong repo (not sure how I ended up in the react-native one), I was meant to post it in `cordova-background-geolocation`. I'm using Ionic for my project, not react-native.

1. The motion detection: I understand that the plugin has been built around it, I just don't want to ask users for permissions that I won't be using (enhance the fact that I disabled it on iOS). This could potentially cause a reject of our app from the app store. If there is no solution to disable it in your plugin then I think I'll leave it like this.

2. A-GPS only: I think I understand what you mean, however I'm not sure what configuration I should use to allow user to use GPS only (No Network & No Cell). My `desiredAccuracy` is set to 0 so from what I understand I let everything pass through the filter. `distanceFilter` is from what I understand how far you need to move from your current location to trigger a location update. Mine is set to 200 meters, this is a value I was using to test my app using iOS driving simulation. On Android it's a bit more tedious to test a location change (coupled with push notifications, so I need a physical device).  Right now I'm using `MockGeoFix` app that requires Location Mode to be set on GPS only.

The issue is that, I feel the plugin is trying to get an update, but the device is not responding (408 error). What Can I do to fix this?

Thanks again

**Comment by christocracy** [comment]
Go post in the correct repo.

**Comment by Maxwell2022** [comment]
It's now here: https://github.com/transistorsoft/cordova-background-geolocation/issues/1022
