### ISSUE TITLE
Stop HTTP post requests are being sent to server.

### ISSUE THREAD

**Issue by akshay02573** [transistorsoft/react-native-background-geolocation#1672]
## Your Environment
* Plugin version: 4.10.1
* Platform: iOS or Android: Both
* OS version: 15.5
* Device manufacturer / model: iPhone 13
* React Native version (`react-native -v`): 0.63.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.stop();
```

## Expected Behavior

Should stop the post request send to server.
## Actual Behavior

It continue send location update on server.

## Steps to Reproduce

1. Start the schedule after setConfig for HTTP request details.
2. Call BackgroundGeolocation.stop(); method on schedule stop. 
3. Observe the onHttp is still called.

## Context

Trying to tracking user location for scheduled time.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by akshay02573** [comment]
@christocracy 
It is still sending request to server after using .destroyLocations();

**Comment by akshay02573** [comment]
@christocracy 
So can you let me know how can we stop the post request to server?

**Comment by christocracy** [comment]
Can you show me the plug-in logs?  Use ..emailLog method
