### ISSUE TITLE
EXPO: No Location when app is crashed, java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger

### ISSUE THREAD

**Issue by Patafix** [transistorsoft/react-native-background-geolocation#1675]
## Your Environment
* Plugin version: 4.11.3
* Platform: Android
* OS version: 12
* Device manufacturer / model: OnePlus
* React Native version (`react-native -v`): 0.71.7
* EXPO SDK : 48.0.15
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
debug: true,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
geofenceModeHighAccuracy: true,
persistMode: BackgroundGeolocation.PERSIST_MODE_GEOFENCE,
stopOnTerminate: false,
url: 'http://localhost:9000/locations',
autoSync: true,
}).then(() => {
BackgroundGeolocation.startGeofences()
}).catch(console.log)
```

## Expected Behavior
When the app is killed, geofencing event is posted to the  url.

## Actual Behavior
When the app is killed, no geofencing event is posted to the  url and we see an error in adb.

## Steps to Reproduce

1. Kill the app
2. Change the location (with fake location)

## Context
We are evaluating the library before purchase and we want only geofence zone. We want to geofence zone even on reboot or app is killed

## Debug logs

<details><summary>Logs</summary>

╠═════════════════════════════════════════════
04-27 14:21:52.676 25325 25325 E TSLocationManager: ╟─ Invalid license key: UNDEFINED
04-27 14:21:52.676 25325 25325 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
04-27 14:21:52.676 25325 25325 E TSLocationManager: ╚═════════════════════════════════════════════
04-27 14:21:52.695 25325 25390 E AndroidRuntime: FATAL EXCEPTION: pool-11-thread-1
04-27 14:21:52.695 25325 25390 E AndroidRuntime: Process: XXX.XXXX.XXXX, PID: 25325
04-27 14:21:52.695 25325 25390 E AndroidRuntime: java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger
04-27 14:21:52.695 25325 25390 E AndroidRuntime:        at com.transistorsoft.locationmanager.logger.TSLog.getRootLogger(Unknown Source:11)
04-27 14:21:52.695 25325 25390 E AndroidRuntime:        at com.transistorsoft.locationmanager.logger.TSLog.access$000(Unknown Source:0)
04-27 14:21:52.695 25325 25390 E AndroidRuntime:        at com.transistorsoft.locationmanager.logger.TSLog$a.run(Unknown Source:0)
04-27 14:21:52.695 25325 25390 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-27 14:21:52.695 25325 25390 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-27 14:21:52.695 25325 25390 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)

</details>

**Comment by Patafix** [comment]
Thank you
[logs.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/11343623/logs.txt)

**Comment by christocracy** [comment]
You have two different components using the same "logging" library that this plugin uses (`org.slf4j`), causing a clash.  As noted in the [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#4113--2023-04-19), the plugin recently upgraded its version, causing the clash.

You will have to manually apply the old logger versions in order to satisfy that other dependency.

```
\--- org.java-websocket:Java-WebSocket:1.5.2
|         \--- org.slf4j:slf4j-api:1.7.25 -> 2.0.7
.
.
.
+--- project :react-native-background-geolocation
.
.
.
|    +--- com.github.tony19:logback-android:3.0.0
|    +--- org.slf4j:slf4j-api:2.0.7
```

In you `android/build.gradle`, modify the `ext` params as follows:

```gradle
buildscript {
    ext {
        .
        .
        .
        logbackVersion = "2.0.1"
        slf4jVersion = "1.7.36"
    }
}
```

**Comment by christocracy** [comment]
If using Expo, you’d add those vars to your `expo-gradle-ext-vars` config in app.json.

**Comment by Patafix** [comment]
Thanks you it's work.

For other user of expo :
`[
  'expo-gradle-ext-vars', {
  googlePlayServicesLocationVersion: '20.0.0',
  appCompatVersion: '1.4.2',
  logbackVersion: '2.0.1',
  slf4jVersion: '1.7.36',
},
],`
