### ISSUE TITLE
Android  LICENSE VALIDATION FAILURE

### ISSUE THREAD

**Issue by donutdonate** [transistorsoft/react-native-background-geolocation#1676]
## Your Environment
* Plugin version: 4.11.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: POCO X4 GT
* React Native version (`react-native -v`): 0.70.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
     desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      heartbeatInterval: 60,
      preventSuspend: true,
      stopTimeout: 5,

      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      batchSync: false,
      autoSync: true,
```

## Expected Behavior

LICENSE VALIDATION SUCCESS
## Actual Behavior

Works fine for iOS version of the App, but LICENSE VALIDATION FAILURE message appears in Android version.
## Steps to Reproduce

1. Add key to AndroidMadifest
2. Open the App
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
╔═════════════════════════════════════════════
║ LICENSE VALIDATION FAILURE: APP_NAME
                                                                                                    ╠═════════════════════════════════════════════
╟─ Invalid license key: LICENSE_KEY
╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
                                                                                                    ╚═════════════════════════════════════════════
```

</details>

**Comment by christocracy** [comment]
Have you purchased a license?

**Comment by donutdonate** [comment]
> Have you purchased a license?

Hello! Yes, of course. It works fine for iOS version of the App. Should we purchase another license for Android version?

**Comment by christocracy** [comment]
Only Android consumes license keys.

the only way license validation can fail is if your Android package name doesn’t match the one the key was generated for.  Login to the Customer Dashboard and compare the package name there with the one in your Android app/build.gradle.  You will find they don’t match.

**Comment by christocracy** [comment]
Review the Setup Instructions.  All lines marked in...
```diff
+green
```
...are **Required**, not *optional*.

**Comment by christocracy** [comment]
I'm talking about *all* the Setup Instructions, particularly those in android/app/build.gradle.

I'm sure you **did enter your key and I'm sure you *are* receiving a "License Validation Error".

**Comment by fragilehm** [comment]
@christocracy I am running the app on Android real device in debug mode, but still getting this issue:
`Failed to find the license key in AndroidManifest.xml` or is this expected also on debug mode on real device if I do not purchase the key?

**Comment by christocracy** [comment]
The plug-in is fully functional in debug builds, in spite of the message.
