### ISSUE TITLE
Following expo tutorial doesn't work 

### ISSUE THREAD

**Issue by miguelmhz** [transistorsoft/react-native-background-geolocation#1680]
## Your Environment
* Plugin version: 4.12
* Platform: expo Android/iOS
* OS version: 
EXPO: 0.4.11
Expo Go 2.28.8  
Android: 12
* Device manufacturer / model: Xiaomi Redmi Note 11
* React Native version (`react-native -v`): 0.70.8
* Plugin config 
the same as the tutorial
```javascript <!-- Syntax-highlighting:  paste your code below -->
"plugins": [
+     [
+       "react-native-background-geolocation", {
+         "license": "YOUR_LICENSE_KEY_HERE"
+       }
+     ],
+     [
+       "expo-gradle-ext-vars", {
+         "googlePlayServicesLocationVersion": "20.0.0",
+         "appCompatVersion": "1.4.2"
+       }
+     ],
+     "react-native-background-fetch"
    ]
```

## Expected Behavior

We expected to run the expo example shown on github 

## Actual Behavior

the interface is displayed but a warning is displayed: 
WARN  - BackgroundGeolocation error:  [TypeError: null is not an object (evaluating 'RNBackgroundGeolocation.stop')]
 WARN  - BackgroundGeolocation error en ready:  [TypeError: null is not an object (evaluating 'RNBackgroundGeolocation.ready')]

## Steps to Reproduce

1.plugin installation with expo
2.expo setup in app.json (https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md)
3.  Configure our license 
4. Follow the tutorial (https://github.com/transistorsoft/react-native-background-geolocation)

## Context

we pay for the license and wanting to test with the tutorial  but it doesn't work

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
WARN  - BackgroundGeolocation error:  [TypeError: null is not an object (evaluating 'RNBackgroundGeolocation.stop')]
 WARN  - BackgroundGeolocation error en ready:  [TypeError: null is not an object (evaluating 'RNBackgroundGeolocation.ready')]
```

</details>

I attached photos of the errors 
![WhatsApp Image 2023-05-08 at 10 34 49](https://user-images.githubusercontent.com/66329160/236880718-30e6fd5d-14bf-4d32-a67e-b0aa0223f99f.jpeg)
![WhatsApp Image 2023-05-08 at 10 34 50](https://user-images.githubusercontent.com/66329160/236880772-c89d2af5-28a7-4b00-b359-b16c0f2d88e3.jpeg)
![WhatsApp Image 2023-05-08 at 10 39 57](https://user-images.githubusercontent.com/66329160/236880983-b709b5e5-b3f3-480d-8a9e-cfd0c59717a9.jpeg)

**Comment by christocracy** [comment]
Post your app.json file

**Comment by miguelmhz** [comment]
`
{
	"expo": {
		"name": "You I App",
		"slug": "you-i-app",
		"version": "1.3.3",
		"owner": "you-i-lab",
		"orientation": "portrait",
		"icon": "./assets/logo.png",
		"userInterfaceStyle": "automatic",
		"splash": {
			"image": "./assets/splashicon.png",
			"resizeMode": "cover",
			"backgroundColor": "#ffffff"
		},
		"updates": {
			"fallbackToCacheTimeout": 0
		},
		"assetBundlePatterns": ["**/*"],
		"ios": {
			"supportsTablet": true,
			"infoPlist": {
				"NSCameraUsageDescription": "Allow $(PRODUCT_NAME) to access your camera",
				"NSLocationAlwaysAndWhenInUseUsageDescription": "This app requires location in the background",
				"NSLocationWhenInUseUsageDescription": "This app requires location while in use",
				"NSMotionUsageDescription": "This app uses motion-detection to determine the motion-activity of the device (walking, vehicle, bicycle, etc)",
				"UIBackgroundModes": ["location", "fetch", "processing", "audio"],
				"BGTaskSchedulerPermittedIdentifiers": ["com.transistorsoft.fetch", "com.transistorsoft.customtask"],
				"NSLocationAlwaysAndWhenInUseUsageDescription": "This app requires location in the background",
				"NSLocationWhenInUseUsageDescription": "This app requires location while in use",
				"NSMotionUsageDescription": "This app uses motion-detection to determine the motion-activity of the device (walking, vehicle, bicycle, etc)",
				"UIBackgroundModes": ["location", "fetch", "processing", "audio"],
				"BGTaskSchedulerPermittedIdentifiers": ["com.transistorsoft.fetch", "com.transistorsoft.customtask"]
			}
		},
		"android": {
			"versionCode": 7,
			"adaptiveIcon": {
				"foregroundImage": "./assets/logo.png",
				"backgroundColor": "#FFFFFF"
			},
			"permissions": ["android.permission.CAMERA"],
			"package": "com.juanjodmz73.youiapp"
		},
		"web": {
			"favicon": "./assets/logo.png"
		},
		"plugins": [
			"react-native-vision-camera",
			"expo-gradle-ext-vars",
			[
				"react-native-background-geolocation",
				{
					"license": "4f026XXXX112c4677f79149317f68eXXXX5f6b09cb02e3076360655edXXXXXXXX"
				}
			],
			[
				"expo-gradle-ext-vars",
				{
					"googlePlayServicesLocationVersion": "20.0.0",
					"appCompatVersion": "1.4.2"
				}
			],
			"react-native-background-fetch"
		],
		"extra": {
			"eas": {
				"projectId": "b82d152e-9e4e-4c5e-8ffe-e8cd43f0xxxx"
			}
		}
	}
}
`

**Comment by miguelmhz** [comment]
`json
{
  "name": "you-i-app",
  "version": "1.2.0",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo-google-fonts/inter": "^0.2.2",
    "@expo-google-fonts/montserrat": "^0.2.2",
    "@expo/webpack-config": "^0.17.2",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/datetimepicker": "6.5.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "9.3.5",
    "@react-native-picker/picker": "^2.4.8",
    "@react-navigation/bottom-tabs": "^6.5.6",
    "@react-navigation/native": "^6.1.5",
    "@react-navigation/native-stack": "^6.9.9",
    "axios": "^1.3.2",
    "expo": "~47.0.14",
    "expo-app-loading": "~2.1.1",
    "expo-camera": "~13.1.0",
    "expo-font": "~11.0.1",
    "expo-gradle-ext-vars": "^0.1.1",
    "expo-image-manipulator": "~11.0.0",
    "expo-location": "~15.0.1",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "~0.15.6",
    "moment": "^2.29.4",
    "radio-buttons-react-native": "^1.0.4",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.8",
    "react-native-a11y-slider": "^1.1.0",
    "react-native-background-fetch": "^4.1.10",
    "react-native-background-geolocation": "^4.12.0",
    "react-native-bouncy-checkbox": "^3.0.7",
    "react-native-date-picker": "^4.2.9",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-modal-datetime-picker": "^14.0.1",
    "react-native-new-snap-carousel": "^3.9.3",
    "react-native-paper": "^5.5.1",
    "react-native-picker-select": "^8.0.4",
    "react-native-popup-menu": "^0.16.1",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-select-dropdown": "^3.3.0",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-svg": "13.4.0",
    "react-native-tailwindcss": "^1.1.11",
    "react-native-vector-icons": "^9.2.0",
    "react-native-vision-camera": "^2.15.4",
    "react-native-web": "~0.18.9",
    "react-navigation": "^4.4.4",
    "sharp": "^0.31.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
`

**Comment by christocracy** [comment]
I have no idea what is wrong.  Have you tried building locally?

**Comment by miguelmhz** [comment]
okay let me try that, thanks

**Comment by miguelmhz** [comment]
unfortunately we tried to build and show this 
![build](https://github.com/transistorsoft/react-native-background-geolocation/assets/66329160/aa926d72-db26-4362-aef9-c71e1997cefc)

**Comment by christocracy** [comment]
I suspect that whatever is preventing your app from building locally is preventing the plug-in from working.

I suggest you continue on with figuring out your local build problems.
