### ISSUE TITLE
Search button does not work on docs page

### ISSUE THREAD

**Issue by likrot** [transistorsoft/react-native-background-geolocation#1689]
## Your Environment
* Plugin version: this issue is about docs web page
* Platform: macOS | chrome browser (113.0.5672.126)
* OS version: -
* Device manufacturer / model: -
* React Native version (`react-native -v`): -
* Plugin config

## Expected Behavior
Searching on the docs page should work.

## Actual Behavior
I can no longer use the search function. I don't know the exact date when that might happen. I see an error message in the developer console. I have no idea if this is related to this problem, I didn't debug it

## Steps to Reproduce

1. Go to the [docs page](https://transistorsoft.github.io/react-native-background-geolocation/)
2. Try to use the search function
3. No effect after clicking search button

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
otstrap.ts:1 Uncaught Error: Module parse failed: Unexpected token (22:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
| 
> const app: Application = new Application();
| 
| Object.defineProperty(window, "app", { value: app });
    at eval (bootstrap.ts:1:7)
    at ./default/assets/js/src/bootstrap.ts (main.js:18:1)
    at main.js:29:70
    at main.js:31:12
e
```

</details>

**Comment by christocracy** [comment]
Thanks, fixed.
