### ISSUE TITLE
IOS:Location updates not received when the app is in the background

### ISSUE THREAD

**Issue by niharSafe** [transistorsoft/react-native-background-geolocation#1694]
## Your Environment
* react-native-background-geolocation : 4.9.5 , react-native-background-fetch: 4.1.0
* Platform: iOS
* OS version: 16
* Device manufacturer / model: Apple iPhone x
* React Native version (`react-native -0.68.5`): 

## Expected Behavior
The transistorsoft/react-native-background-geolocation library should continue to provide accurate and consistent location updates even when the app is running in the background. The library should ensure that the user's location is tracked and updated regularly, allowing the app to accurately monitor the user's movements and perform necessary actions based on the location data received.

## Actual Behavior
When using the transistorsoft/react-native-background-geolocation library, location updates are not received when the app enters the background. Despite correctly configuring the necessary permissions and settings, the library fails to retrieve the user's location during the background mode. As a result, the app is unable to track and update the user's location accurately, hindering the functionality that relies on continuous location updates in the background.

## Steps to Reproduce
1. Install the app on a device or simulator.
2. Launch the app and grant the necessary location permissions.
3. Enable location tracking within the app.
4. Move the app to the background by pressing the home button or switching to another app.
5. Keep the app in the background for a significant amount of time (e.g., several minutes).
6. During this time, move to different locations to trigger location updates.
7. Bring the app back to the foreground.
8. Check if the app successfully received and updated the location data during the background period.
9. Compare the received location data with the actual user's movements to verify the accuracy of the updates.

## Context
**Dear Transistorsoft team**,

I am writing to report an issue regarding the react-native-background-geolocation library. I have encountered a problem where the location updates do not occur when my app is running in the background.

I have noticed that the location updates stop when the app enters the background mode. It seems that the library fails to retrieve the user's location during this state.

I have verified that the necessary permissions and configurations are set correctly in the Info.plist file, and the location services are enabled in the device settings.

To resolve the issue, I have attempted the following steps without success:

Restarting the device and retesting the app.
Checking for any conflicting packages or code that might interfere with the library's functionality.
Reviewing the library's documentation and troubleshooting guides.
Unfortunately, none of these steps have resolved the problem, and I am still unable to receive location updates when the app is in the background.

I kindly request your assistance in investigating this issue and providing guidance on how to resolve it. If there are any workarounds or known solutions, I would greatly appreciate any information you can provide.

Thank you for your attention to this matter, and I look forward to your prompt response.

Sincerely,
[Dev Nihar]
[nihard714@gmail.com]
[UrSafe: Safety & Security App]

**Comment by christocracy** [comment]
Have you read the wiki [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation).

On iOS, you need to move *at least* 200 meters before location-tracking automatically engages.  When the device is sitting stationary with the app in the background, **no location is supposed to recorded**.

**Comment by christocracy** [comment]
Also, you did not provided the requested **Plugin Config** that the issue template requested.
