### ISSUE TITLE
undefined is not an object (evaluating 'BackgroundGeolocationManager.configure')

### ISSUE THREAD

**Issue by furf** [transistorsoft/react-native-background-geolocation#17]
*Warning: I'm brand new to Android development. Please let me know what additional debug info might be useful.*

I'm receiving the following error on Android emulator: `undefined is not an object (evaluating 'BackgroundGeolocationManager.configure')`

Is it curious that the error is referencing RNBackgroundGeolocation.ios.js?

<img width="540" alt="screen shot 2015-10-28 at 10 05 07 am" src="https://cloud.githubusercontent.com/assets/35775/10796489/99c1fbe8-7d5b-11e5-9808-c6a00d7ad863.png">

I created my Android Virtual Device by following the instructions on the [Android Setup](https://facebook.github.io/react-native/docs/android-setup.html) page of the React Native docs.

Do I need to build a new one with Google Play services? (That's the only anomaly I can detect from reading the repo's wiki.)

I'm pretty much using the stock example:

```
componentDidMount() {

  BackgroundGeolocation.configure({
    desiredAccuracy: 0,
    stationaryRadius: 50,
    distanceFilter: 50,
    disableElasticity: false,             // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
    locationUpdateInterval: 5000,
    minimumActivityRecognitionConfidence: 80,   // 0-100%.  Minimum activity-confidence for a state-change
    fastestLocationUpdateInterval: 5000,
    activityRecognitionInterval: 10000,
    stopDetectionDelay: 1,                // <--  minutes to delay after motion stops before engaging stop-detection system
    stopTimeout: 2,                       // 2 minutes
    activityType: 'AutomotiveNavigation',

    // Application config
    debug: false,                         // <-- enable this hear sounds for background-geolocation life-cycle.
    forceReloadOnLocationChange: false,   // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
    forceReloadOnMotionChange: false,     // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
    forceReloadOnGeofence: false,         // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)
    stopOnTerminate: false,               // <-- [Android] Allow the background-service to run headless when user closes the app.
    startOnBoot: true,                    // <-- [Android] Auto start background-service in headless mode when device is powered-up.

    // HTTP / SQLite config
    // url: 'http://posttestserver.com/post.php?dir=cordova-background-geolocation',
    // batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
    // autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
    // maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
    // headers: {
    //   "X-FOO": "bar"
    // },
    // params: {
    //   "auth_token": "maybe_your_server_authenticates_via_token_YES?"
    // }
  });

  // This handler fires whenever bgGeo receives a location update.
  BackgroundGeolocation.on('location', location => {
    console.log('>>> BackgroundGeolocation location');
    this.setLocation(location);
  });

  // This handler fires when movement states changes (stationary->moving; moving->stationary)
  BackgroundGeolocation.on('motionchange', location => {
    console.log('>>> BackgroundGeolocation motionchange');
    this.setLocation(location);
  });

  BackgroundGeolocation.start(() => {
    console.log('>>> BackgroundGeolocation start');

    // Fetch current position
    BackgroundGeolocation.getCurrentPosition(location => {
      console.log('>>> BackgroundGeolocation getCurrentPosition');
      this.setLocation(location);
    }, GEO_CONFIG);
  });

}
```

**Comment by christocracy** [comment]
There is no Android version in this repo.  Only iOS will be free.  Android will require a [paid licence](http://shop.transistorsoft.com/pages/react-native-background-geolocation)

I haven't yet built the bindings for Android yet, though it shouldn't take longer than a week, once I get around to it.

**Comment by furf** [comment]
Thanks for the quick answer. I guess I was fooled by all the references to "Android" in the README. Will keep watching... :)

**Comment by furf** [comment]
Thanks for the quick answer. I guess I was fooled by all the references to "Android" in the README. Will keep watching... :)

**Comment by christocracy** [comment]
It's difficult to maintain 2 separate sets of docs; 1 for iOS-only, another
for premium.  Docs need work.

On Wednesday, October 28, 2015, Dave Furfero <notifications@github.com>
wrote:

> Thanks for the quick answer. I guess I was fooled by all the references to
> "Android" in the README. Will keep watching... :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/17#issuecomment-151917086>
> .
>


-- 
Snet form Gmail Mobile
