### ISSUE TITLE
RemoveGeofence doesn't trigger EXIT event when it has ENTER state, new geofences don't trigger EXIT event

### ISSUE THREAD

**Issue by robmoorman** [transistorsoft/react-native-background-geolocation#170]
When I'm in a geofence (in my case, my home address) and I remove the entered geofence which `removeGeofence` no `EXIT` event is triggered. While adding a geofence does trigger a `ENTER` event when `geofenceInitialTriggerEntry` is set to `true`.

This scenario's pops up when e.g. a user changes his home address (so the old geofence will be removed and a new one will be added). In this use case there is no `EXIT` event triggered and apps see this as 'at home'.

Would it be feasible to fix this in your module or is this something (from your point of view) needs te be implemented in the applications logic.

Pseudo code would be (as I expect to work with `geofenceInitialTriggerEntry` to `true`):

`IF geofence has enter state AND geofence gets removed THEN trigger exit event`

Finally, adding a new geofence also doesn't trigger an `EXIT` event when `geofenceInitialTriggerEntry` is set to `true`.

**Comment by christocracy** [comment]
Sorry missed this.

I don't really understand what you want.

You want to trigger a geofence transition event after `#removeGeofence` is called?  No way is that going to happen.

>Finally, adding a new geofence also doesn't trigger an EXIT event when geofenceInitialTriggerEntry is set to true.

`geofenceInitialTriggerEntry` has nothing to do with `EXIT` events.  Why would you expect it to trigger an `EXIT` event??
