### ISSUE TITLE
Package not working in Expo

### ISSUE THREAD

**Issue by MariamIdeen** [transistorsoft/react-native-background-geolocation#1700]
## Your Environment
* Plugin version: "^4.12.1"
* Platform: Android
* OS version: Android 7, Android 13
* Device manufacturer / model: Xiaomi Redmi Note 4, Oneplus 10R 5G
* React Native version (`react-native -v`): "0.71.8"
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 "plugins": [
     
               "react-native-background-geolocation",
             [
               "expo-gradle-ext-vars", {
                 "googlePlayServicesLocationVersion": "20.0.0",
                 "appCompatVersion": "1.4.2"
               }
             ],
             "react-native-background-fetch"
    ]
```

## Expected Behavior

```Expected to run the expo example shown on github```
 

## Actual Behavior
The interface is displayed but shows warning:
[Unhandled promise rejection: TypeError: Cannot read property 'ready' of null]
[Unhandled promise rejection: TypeError: Cannot read property 'start' of null]
[Unhandled promise rejection: TypeError: Cannot read property 'stop' of null]

## Steps to Reproduce

1. package installation with expo following the link https://github.com/transistorsoft/react-native-background-geolocation
2. To Reproduce: https://github.com/MariamIdeen/geolocation

## Context

Trying to get background location from the app.

## Debug logs

<details><summary> [Unhandled promise rejection: TypeError: Cannot read property 'ready' of null]
at node_modules\react-native-background-geolocation\src\NativeModule.js:null in Promise$argument_0
at node_modules\react-native-background-geolocation\src\NativeModule.js:null in ready
at node_modules\react-native-background-geolocation\src\index.js:null in BackgroundGeolocation.ready
at App.js:null in React.useEffect$argument_0
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitHookEffectListMount
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveMountOnFiber
- ... 20 more stack frames from framework internals

[Unhandled promise rejection: TypeError: Cannot read property 'start' of null]
at node_modules\react-native-background-geolocation\src\NativeModule.js:null in Promise$argument_0
at node_modules\react-native-background-geolocation\src\NativeModule.js:null in start
at node_modules\react-native-background-geolocation\src\index.js:null in BackgroundGeolocation.start
at App.js:null in React.useEffect$argument_0
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitHookEffectListMount
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveMountOnFiber
- ... 19 more stack frames from framework internals

[Unhandled promise rejection: TypeError: Cannot read property 'stop' of null]
at node_modules\react-native-background-geolocation\src\NativeModule.js:null in Promise$argument_0
at node_modules\react-native-background-geolocation\src\NativeModule.js:null in stop
at node_modules\react-native-background-geolocation\src\index.js:null in BackgroundGeolocation.stop
at App.js:null in React.useEffect$argument_0
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitHookEffectListMount
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveMountOnFiber
- ... 19 more stack frames from framework internals
- 
![Screenshot (20)](https://github.com/transistorsoft/react-native-background-geolocation/assets/117250792/7881dac2-3467-48e8-b838-0d409534adb9)

- 
![Screenshot_2023-06-05-15-18-56-67_f73b71075b1de7323614b647fe394240](https://github.com/transistorsoft/react-native-background-geolocation/assets/117250792/d541aec9-c1a5-4396-8f86-a54ea8edf36d)

- </summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->


```

**Comment by christocracy** [comment]
>To Reproduce: https://github.com/MariamIdeen/geolocation

Works for me (building locally).  

<img width="592" alt="Screenshot 2023-06-05 at 9 26 13 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/d273672b-3e32-4348-87a8-70bca8112d97">

Are you *sure* you didn't skip past and *ignore* that important bit [right at the bottom of the Expo Setup Instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md#re-build)

<img width="1065" alt="Screenshot 2023-06-05 at 9 27 37 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/1df666d5-ea23-4736-9e1d-98133d3415dc">

**Comment by MariamIdeen** [comment]
Got this after running npx expo prebuild

![Screenshot (21)](https://github.com/transistorsoft/react-native-background-geolocation/assets/117250792/0e30df37-5176-4d10-88f6-00a89d3687bc)

` eas build -p android --profile preview` run this command to build apk and did not get location details

![Screenshot_2023-06-06-09-50-12-61_99e7066a8229b96df23659c911fb22c4](https://github.com/transistorsoft/react-native-background-geolocation/assets/117250792/ccc9b67f-6c15-4245-98e5-5fff1e4ef21a)

**Comment by MariamIdeen** [comment]
` "Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" ready.
Installing Android SDK Build-Tools 30.0.3 in /home/expo/Android/Sdk/build-tools/30.0.3
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
Checking the license for package Android SDK Platform 33 in /home/expo/Android/Sdk/licenses
License for package Android SDK Platform 33 accepted.
Preparing "Install Android SDK Platform 33 (revision: 2)".
"Install Android SDK Platform 33 (revision: 2)" ready.
Installing Android SDK Platform 33 in /home/expo/Android/Sdk/platforms/android-33
"Install Android SDK Platform 33 (revision: 2)" complete.
"Install Android SDK Platform 33 (revision: 2)" finished.
[stderr] 
FAILURE:
[stderr] 
Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[stderr] 
>
[stderr] 
Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
[stderr] 
>
[stderr] 
Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
[stderr] 
Required by:
[stderr] 
project :app > project :react-native-background-geolocation
[stderr] 
* Try:
[stderr] 
>
[stderr] 
Run with
[stderr] 
--stacktrace
[stderr] 
option to get the stack trace.
[stderr] 
>
[stderr] 
Run with
[stderr] 
--info
[stderr] 
or
[stderr] 
--debug
[stderr] 
option to get more log output.
[stderr] 
>
[stderr] 
Run with
[stderr] 
--scan
[stderr] 
to get full insights.
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 3m 1s
10 actionable tasks: 10 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.`

got this after  'eas build --profile developement' and got build failed

` PS D:\Works\Sample\Geolocation\geolocation> npx expo prebuild
√ Created native project | /android already created | gitignore skipped
√ Updated package.json and added index.js entry point for iOS and Android
› Installing using npm
> npm install
× Config sync failed
Error: [android.dangerous]: withAndroidDangerousBaseMod: Failed to find the instance of sharp used by the global sharp-cli package.
Error: [android.dangerous]: withAndroidDangerousBaseMod: Failed to find the instance of sharp used by the global sharp-cli package.
    at Object.findSharpInstanceAsync (D:\Works\Sample\Geolocation\geolocation\node_modules\@expo\image-utils\build\sharp.js:188:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getSharpAsync (D:\Works\Sample\Geolocation\geolocation\node_modules\@expo\image-utils\build\Image.js:109:17)
    at async resizeAsync (D:\Works\Sample\Geolocation\geolocation\node_modules\@expo\image-utils\build\Image.js:47:19)
    at async generateImageAsync (D:\Works\Sample\Geolocation\geolocation\node_modules\@expo\image-utils\build\Image.js:156:18)
    at async generateIconAsync (D:\Works\Sample\Geolocation\geolocation\node_modules\@expo\prebuild-config\build\plugins\icons\withAndroidIcons.js:350:11)
    at async D:\Works\Sample\Geolocation\geolocation\node_modules\@expo\prebuild-config\build\plugins\icons\withAndroidIcons.js:278:21
    at async Promise.all (index 0)
    at async generateMultiLayerImageAsync (D:\Works\Sample\Geolocation\geolocation\node_modules\@expo\prebuild-config\build\plugins\icons\withAndroidIcons.js:274:3)
    at async setIconAsync (D:\Works\Sample\Geolocation\geolocation\node_modules\@expo\prebuild-config\build\plugins\icons\withAndroidIcons.js:161:3)`

and this after npx expo prebuild

**Comment by christocracy** [comment]
> and this after npx expo prebuild

And what?  You didn’t paste any logs.

**Comment by MariamIdeen** [comment]
This is the log 

 PS D:\Works\Sample\Geolocation\geolocation> npx expo prebuild
√ Created native project | /android already created | gitignore skipped
√ Updated package.json and added index.js entry point for iOS and Android
› Installing using npm

npm install
× Config sync failed
Error: [android.dangerous]: withAndroidDangerousBaseMod: Failed to find the instance of sharp used by the global sharp-cli package.
Error: [android.dangerous]: withAndroidDangerousBaseMod: Failed to find the instance of sharp used by the global sharp-cli package.
at Object.findSharpInstanceAsync (D:\Works\Sample\Geolocation\geolocation\node_modules@expo\image-utils\build\sharp.js:188:15)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async getSharpAsync (D:\Works\Sample\Geolocation\geolocation\node_modules@expo\image-utils\build\Image.js:109:17)
at async resizeAsync (D:\Works\Sample\Geolocation\geolocation\node_modules@expo\image-utils\build\Image.js:47:19)
at async generateImageAsync (D:\Works\Sample\Geolocation\geolocation\node_modules@expo\image-utils\build\Image.js:156:18)
at async generateIconAsync (D:\Works\Sample\Geolocation\geolocation\node_modules@expo\prebuild-config\build\plugins\icons\withAndroidIcons.js:350:11)
at async D:\Works\Sample\Geolocation\geolocation\node_modules@expo\prebuild-config\build\plugins\icons\withAndroidIcons.js:278:21
at async Promise.all (index 0)
at async generateMultiLayerImageAsync (D:\Works\Sample\Geolocation\geolocation\node_modules@expo\prebuild-config\build\plugins\icons\withAndroidIcons.js:274:3)
at async setIconAsync (D:\Works\Sample\Geolocation\geolocation\node_modules@expo\prebuild-config\build\plugins\icons\withAndroidIcons.js:161:3)

**Comment by christocracy** [comment]
> @expo\image-utils\build\sharp.js
 
Why are your logs complaining about some “image utils” in a simple “hello world” app?

**Comment by MariamIdeen** [comment]
I have not installed any other packages

**Comment by christocracy** [comment]
I suggest you completely remove the plug-in and and all its Setup Instructions 

Get prebuild to work without the plug-in, before moving forward with the plug-in

Your app worked for me.  You have something wrong with your local environment.

**Comment by MariamIdeen** [comment]
I got npx expo prebuild successfully and did the following steps as I'm using expo EAS

1. eas build
2. eas build -p android --profile development

and I'm getting a screen like this when I open the apk
![Screenshot_2023-06-09-13-50-03-47_99e7066a8229b96df23659c911fb22c4](https://github.com/transistorsoft/react-native-background-geolocation/assets/117250792/9cdec457-407c-4fba-94d8-816f635983fe)


Is it not possible to run directly as apk without using the steps given in the above screen

**Comment by MariamIdeen** [comment]
In the development build onMotionChange only triggers single time when I run the app, I'm using fakeGPS app to change the location for testing.  Below given is the code I'm using, please correct me if I'm wrong. I would like to get location updates while in motion and in specific interval of time.

`  useEffect(() => {
    const onMotionChange = BackgroundGeolocation.onMotionChange((event) => {
      const clocation = event.location;
      setLocation({
        lat: clocation.coords.latitude,
        long: clocation.coords.longitude,
      });
      ToastAndroid.show(
        "location" + JSON.stringify(clocation.coords),
        ToastAndroid.LONG
      );
      sendLocation(location);
    });
    /// 2. ready the plugin.
    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      enableHeadless: true,
      fastestLocationUpdateInterval: 60000,
      locationUpdateInterval: 120000,
      notification: {
        title: "Parison SFA",
        text: "Background Location Tracking Enabled",
      },
      disableElasticity: false,
      distanceFilter: 5,
      disableLocationAuthorizationAlert: false,
      stopOnTerminate: false,
      stopTimeout: 5,
      disableMotionActivityUpdates: false,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      showsBackgroundLocationIndicator: true,
      allowIdenticalLocations: false,
      foregroundService: true,
      startOnBoot: true,
      locationAuthorizationRequest: "Always",
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
      backgroundPermissionRationale: {
        title: "Allow access to this device's location in the background?",
        message:
          "We use your location to track your journey and monitoring breaches to inclusion/exclusion zones set up or allowed by you even when you are not using the app",
        positiveAction: "Change to allow all the time",
        negativeAction: "I'm not sure about this",
      },
    }).then((state) => {
      setLocationService(state.enabled);
    });

    return () => {
      // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
      // during development live-reload.  Without this, event-listeners will accumulate with
      // each refresh during live-reload.
      onMotionChange.remove();
    };
  }, []);
`

**Comment by christocracy** [comment]
See wiki “Debugging” — there’s a note there about using “Mock Location” apps.

the plug-in does **not** trigger location tracking from Mock Location apps.  The plug-in triggers location-tracking when the motion api (accelerometer, gyroscope, magnetometer) says the device is *physically in-motion*.

**Comment by christocracy** [comment]
Also read wiki “Philosophy of Operation”.

**Comment by MariamIdeen** [comment]
I'm also looking for geofencing and wrote the following code
`  React.useEffect(() => {
    if (enabled) {
      BackgroundGeolocation.addGeofence({
        identifier: "Home",
        radius: 200,
        latitude: 9.992887440601002,
        longitude: 76.57595628757663,
        notifyOnEntry: true,
        notifyOnExit: true,
      })
        .then((success) => {
          console.log("[addGeofence]: " + success);
        })
        .catch((error) => {
          console.log("[addGeofence] FAILURE: ", error);
        });

      // BackgroundGeolocation.startGeofences();
    } else {
      BackgroundGeolocation.removeGeofence("Home")
        .then((success) => {
          console.log("[removeGeofence] success", success);
        })
        .catch((error) => {
          console.log("[removeGeofence] FAILURE: ", error);
        });
      setLocation("");
    }
  }, [enabled]);`

I'm getting undefined in both addGeofence and removeGeofence, is there any mistake in my code?

**Comment by christocracy** [comment]
> I'm getting undefined in both addGeofence and removeGeofence

Undefined what?  Show logs.

**Comment by MariamIdeen** [comment]
```
 LOG  [removeGeofence] success undefined
 LOG  [addGeofence]: undefined
 ```

I'm just getting undefined from the success part.

**Comment by MariamIdeen** [comment]
I did change the latitude and longitude of a point beyond 200 meter radius to view the change and for that too `promise`  `.then( )` was triggered with return value undefined.

**Comment by christocracy** [comment]
I have no idea what you’re talking about.

**Comment by christocracy** [comment]
Are you thinking that the Promise returned by calling .addGeofence() fires when a geofence event triggers?

**Comment by MariamIdeen** [comment]
Yes, I would like to trigger an event when the location is beyond the given radius in .addGeofence( )

**Comment by MariamIdeen** [comment]
```
import { Switch, Text, View, StyleSheet, ToastAndroid } from "react-native";
import React from "react";

import BackgroundGeolocation from "react-native-background-geolocation";

export default function App() {
  const [enabled, setEnabled] = React.useState(false);
  const [location, setLocation] = React.useState("");

  React.useEffect(() => {
    getGeoFencing();
  }, [enabled]);

  const getGeoFencing = async () => {
    if (enabled) {
      await BackgroundGeolocation.addGeofence({
        identifier: "Home",
        radius: 200,
        latitude: 9.992887440601002,
        longitude: 76.57595628757663,
        notifyOnEntry: true,
        notifyOnExit: true,
      })
        .then((success) => {
          getEvent();
        })
        .catch((error) => {});
    } else {
      await BackgroundGeolocation.removeGeofence("Home")
        .then((success) => {})
        .catch((error) => {
          // console.log("[removeGeofence] FAILURE: ", error);
        });
      setLocation("");
    }
  };

  const getEvent = async () => {
    // Listen for geofence events.
    const subscription = BackgroundGeolocation.onGeofence((geofence) => {
      try {
        var identifier = geofence.identifier;
        var action = geofence.action;
        var location = geofence.location;

        console.log("- A Geofence transition occurred"); //console 1
        console.log("  identifier: ", identifier); //console 2
        console.log("  action: ", action); //console 3
        console.log("  location: ", JSON.stringify(location)); //console 4
      } catch (e) {
        console.error("An error occurred in my code!", e); //console 5
      }
    });
    console.log("onGeofence", subscription); //console 6
  };

  return (
    <View style={styles.container}>
      <Text>Click to enable BackgroundGeolocation</Text>
      <Switch value={enabled} onValueChange={setEnabled} />
      <Text style={{ fontFamily: "monospace", fontSize: 12 }}>{location}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

I'm only getting console 6 from the above code as ``` LOG  onGeofence {"remove": [Function anonymous]}``` ,am not getting any other logs from ```try-catch``` block.

**Comment by christocracy** [comment]
Listen to .onGeofence **BEFORE** calling .addGeofence.  

It’s nothing more than an event-listener, like hooking up a speaker to your stereo system. 

Make a geofence around your current position.

it’s not hard.

**Comment by MariamIdeen** [comment]
```
import { Switch, Text, View, StyleSheet, ToastAndroid } from "react-native";
import React from "react";

import BackgroundGeolocation from "react-native-background-geolocation";

export default function App() {
  const [enabled, setEnabled] = React.useState(false);
  const [location, setLocation] = React.useState("");

  React.useEffect(() => {
    if (enabled) {
      getEvent();
    }
  }, [enabled]);

  const getEvent = async () => {
    // Listen for geofence events.
    const subscription = BackgroundGeolocation.onGeofence((geofence) => {
      console.log("[onGeofence]", geofence);
      try {
        var identifier = geofence.identifier;
        var action = geofence.action;
        var location = geofence.location;

        console.log("- A Geofence transition occurred"); //console 1
        console.log("  identifier: ", identifier); //console 2
        console.log("  action: ", action); //console 3
        console.log("  location: ", JSON.stringify(location)); //console 4
      } catch (e) {
        console.error("An error occurred in my code!", e); //console 5
      }
    });
    console.log("onGeofence", subscription); //console 6
    getGeoFencing();
  };

  const getGeoFencing = async () => {
    if (enabled) {
      await BackgroundGeolocation.addGeofence({
        identifier: "Home",
        radius: 200,
        latitude: 9.992887440601002,
        longitude: 76.57595628757663,
        notifyOnEntry: true,
        notifyOnExit: true,
      })
        .then((success) => {
          console.log("[addGeofencing]", success);
        })
        .catch((error) => {});
    } else {
      await BackgroundGeolocation.removeGeofence("Home")
        .then((success) => {})
        .catch((error) => {
          // console.log("[removeGeofence] FAILURE: ", error);
        });
      setLocation("");
    }
  };

  return (
    <View style={styles.container}>
      <Text>Click to enable BackgroundGeolocation</Text>
      <Switch value={enabled} onValueChange={setEnabled} />
      <Text style={{ fontFamily: "monospace", fontSize: 12 }}>{location}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

I called .onGeofence before .addGeofence as you told, still am not getting any consoles other than 

```  
LOG  onGeofence {"remove": [Function anonymous]}
 LOG  [addGeofencing] undefined 
```

**Comment by christocracy** [comment]
See wiki “Debugging”.  Learn to observe native logs from the plug-in with `$ adb logcat`
