### ISSUE TITLE
Question: Why is a marker displayed in the navigation despite geofence?

### ISSUE THREAD

**Issue by iSaBo96** [transistorsoft/react-native-background-geolocation#1701]
## Your Environment
* Plugin version: 4.10.0
* Platform: iOS
* OS version: 16.3.1
* Device manufacturer / model: iPhone 11
* React Native version (`react-native -v`):11.3.1
* Plugin config
```javascript 
BackgroundGeolocation.ready({
        }, state => {
            BackgroundGeolocation.startGeofences();
        })
```

## Expected Behavior
Only a markup (display of GPS icons in the status bar) when I am inside a geofence

## Actual Behavior
Display of GPS icons in the status bar even if I am outside of a geofence

## Steps to Reproduce
1. Add BackgroundGeolocation.ready config
2. Add geofence 
```javascript 
BackgroundGeolocation.addGeofence({
                identifier: 'Geolocation',
                radius: 300,
                latitude: 50.79326756518871,
                longitude: 7.22335821124103,
                notifyOnEntry: true,
                notifyOnExit: true
            }).then((success) => {
                console.log("[addGeofence] success");
            }).catch((error) => {
                console.log("[addGeofence] FAILURE: ", error);
            });
```

## Context
Reading the documentaion

## Debug logs
No logs available for this issue

I understood it to mean that a location marker is only displayed in the statusbar when you are within a geofence. Did I understand that correctly?

**Comment by christocracy** [comment]
It is likely due to some other component you’re using.  Some Map Components turn on location services to show the blue dot representing user’s current location.

Are you observing the plug-in logs to observe what the plug-in is doing?  The plug-in logs everything it does.  See wiki “Debugging”.  See api docs Config.ligLevel

**Comment by christocracy** [comment]
> Is a "distanceFilter" still needed for geofences?

 No

**Comment by christocracy** [comment]
> In your documentation you wrote that the minimum from when to look if someone is found in a geofence returns yes or no every 1000 meters (location change)

Where exactly did you read this?   Geofence enter/exit is completely handled by the OS.  The plug-in does not “query” if a device is inside a geofence.

**Comment by iSaBo96** [comment]
Ok, I see. Thank you. But if more than 20 geofences are defined, it could happen that I am not in a geofence, because every 1000 meters the location is updated or I am asked if I am in a geofence. Or? If the radius is then 100 meters, then this will be skipped. correct?

**Comment by christocracy** [comment]
geofenceProximityRadius determines the geofences that are **currently allowed to be monitored**.  You are not allowed to set geofenceProximityRadius < 1000 (that would break geofence monitoring.  The plug-in enforces a minimum 1000 to prevent you “shooting yourself in the foot”).

**Comment by iSaBo96** [comment]
Ok, thanks for the info. So if there are 2 geofences that happen to overlap, the 1000 meters are not given. So this geofence would not work? Do I understand this correctly?

**Comment by iSaBo96** [comment]
The minimum of what? From which a geofence event is triggered? If the minimum is >= 1000, is there for example no possibility to find a Bluetooth device that is only found at a minimum of 50 meters? Because 1000 meters is of course much more than 50 meters.

**Comment by christocracy** [comment]
> The minimum of what? From which a geofence event is triggered?

**NO!**.  “*geofenceProximityRadius has **nothing to do with geofence events.**”

**Comment by christocracy** [comment]
Read the api docs Config.geofenceProximityRadius.  Look at the picture in there.

**Comment by christocracy** [comment]
> than 50 meters.

The minimum Geofence.radius is ~150 meters.  It’s is impossible the create a Geofence with a radius of 50 meters.  Even if you do create a Geofence of radius 50 meters, the OS will fire events as if it’s 150-200 meters.

Geofence.radius **!=** Config.geofenceProximityRadius.  They are not even remotely related.  They are complete different things.

**Comment by christocracy** [comment]
I have no idea about Bluetooth devices.  I do not test with Bluetooth devices.  You are on your own with BT.

**Comment by iSaBo96** [comment]
Definitely, but from the logic alone it will not work, if only once an event is triggered when entering or leaving.

**Comment by christocracy** [comment]
I have no idea what you are saying.

**Comment by iSaBo96** [comment]
Nevertheless, you have helped me a lot, thank you. I had a clear thinking error in my head. Thank you for this

**Comment by christocracy** [comment]
You don’t have to add that permission.  

If you don’t, then configure disableMotionActivityUpdates: true

**Comment by iSaBo96** [comment]
If i upload the app to iOS, i get the following message:
Info: NSMotionUsageDescription is not available in the Info.plist.

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "XXX" 0.1.137 (137). Please correct the following issues, then upload again.

ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “XXX.app” bundle should contain a NSMotionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: [https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources](https://deref-gmx.net/mail/client/apo2Bwrp860/dereferrer/?redirectUrl=https%3A%2F%2Fdeveloper.apple.com%2Fdocumentation%2Fuikit%2Fprotecting_the_user_s_privacy%2Frequesting_access_to_protected_resources).

Best regards,

The App Store Team
```

**Comment by christocracy** [comment]
Yes, that's why I said you must also `disableMotionActivityUpdates: true`, in order to prevent the plugin **requesting permission for an entry that doesn't exist in your .plist**.

**Comment by iSaBo96** [comment]
Even if I do this, test the app beforehand with XCode on a device, I get this error when uploading the app

**Comment by christocracy** [comment]
You are either calling `.start()` before `.ready(config)` has resolved or **some other plugin** is requesting *Motion* permission.

You are not to call any method  which requests permissions before `.ready(config)` has resolved (eg: `.start()`, `.startGeofences()`, `.getCurrentPosition()`, etc).

**Comment by christocracy** [comment]
Your desired `Config` is not activated until `.ready(config)` has resolved.  That takes some unknown number of milliseconds.

If you execute `.start()` / `.startGeofences()` before the `Config` has arrived from `.ready(config)`, the plugin is going to use its default values.

**Comment by iSaBo96** [comment]
My code is the following:

`const App = ({route, navigation}) => {
    React.useEffect(() => {
        configureBackgroundFetch();
    }, []);

    BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        disableMotionActivityUpdates: true
    }).then(() => {
        registerEventHandlers();
        BeaconSpotter.loadAndAddGeofence();
        
        BackgroundGeolocation.startGeofences();
    });

    const registerEventHandlers = async () => {
        return BackgroundGeolocation.onGeofence(async (geofence) => {
            if (geofence.action == "ENTER") {
                PushNotificationIOS.addNotificationRequest({
                    id: 'onGeofenceEnter',
                    title: 'XXX',
                    body: 'XXX'
                });

                await BeaconSpotter.spotBeaconsAndNotifcate();
            } else if (geofence.action == "EXIT") {
                BeaconSpotter.removeAllExistingListeners();
                BackgroundGeolocation.startGeofences();
            }
        });
    };

    const configureBackgroundFetch = async () => {
       return BackgroundGeolocation.configure({
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          stationaryRadius: 50,
          debug: false,
          startOnBoot: true,
          stopOnTerminate: false,
          geofenceModeHighAccuracy: true,
          disableMotionActivityUpdates: true
      });
    }`
    
    yet I get the above message. I do not call .start(), .startGeofences(), .getCurrentPosition(), etc. until ready is called. 
    Or am I seeing something wrong?

**Comment by christocracy** [comment]
`BackgroundGeolocation.configure` was deprecated in favour of `.ready` about 5 years ago.  `.configure` is **AN ALIAS OF** `.ready` and should not be used.  Get rid of that.

**Comment by iSaBo96** [comment]
My mistake, sorry. It was just a test code.

So is the correct order?

First, register event handler, than configure backgroundfetch (i know, optional, but background should also worked for me), then ready the plugin.

```
... 
const App = ({route, navigation}) => {
    React.useEffect(async () => {
        await registerEventHandlers();
        await configureBackgroundFetch(); // (optional)
        await readyBackgroudGeolocation();
    }, []);

    const readyBackgroudGeolocation = async () => {
        await BackgroundGeolocation.ready({
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            stationaryRadius: 50,
            debug: false,
            startOnBoot: true,
            stopOnTerminate: false,
            geofenceModeHighAccuracy: true,
            disableMotionActivityUpdates: true
        }).then(async () => {
            await BeaconSpotter.loadAndAddGeofence();

            BackgroundGeolocation.startGeofences();
        });
    }

    const registerEventHandlers = async () => {
        return BackgroundGeolocation.onGeofence(async (geofence) => {
            if (geofence.action == "ENTER") {
                PushNotificationIOS.addNotificationRequest({
                    id: 'onGeofenceEnter',
                    title: 'XXX',
                    body: 'XXX'
                });

                await BeaconSpotter.spotBeaconsAndNotifcate();
            } else if (geofence.action == "EXIT") {
                BeaconSpotter.removeAllExistingListeners();
                BackgroundGeolocation.startGeofences();
            }
        });
    };
```

**Comment by iSaBo96** [comment]
Addendum: Yet I get the above message that the NSMotionUsageDescription permission is required. I only get this message when an app is uploaded to iOS, not when validating via Xcode.
