### ISSUE TITLE
Appends empty object to array location template 

### ISSUE THREAD

**Issue by leerman** [transistorsoft/react-native-background-geolocation#1702]
When use a compact [Array] template for `locationTemplate`, empty object has been appended to array. Looks like `extras` has been appended to location in result request (debugged in flipper), but I expect location exactly match template when `extras` not configured

## Your Environment
* Plugin version: 4.12.1
* Platform: iOS (Android not tested)

## Expected Behavior

for configuration 
```
BackgroundGeolocation.ready({
  locationTemplate: '[<%=latitude%>, <%=longitude%>, "<%=event%>", <%=is_moving%>]'
))
```
sends location
```
[
    37.61859382,
    -122.42462539,
    "motionchange",
    false
  ]
```

## Actual Behavior
for configuration 
```
BackgroundGeolocation.ready({
  locationTemplate: '[<%=latitude%>, <%=longitude%>, "<%=event%>", <%=is_moving%>]'
))
```
sends location
```
[
    37.61859382,
    -122.42462539,
    "motionchange",
    false,
    {}
  ]
```

**Comment by christocracy** [comment]
>is there possible to configure plugin not append

There is no way to prevent it via configuration, no.

**Comment by leerman** [comment]
thank you
