### ISSUE TITLE
Get current state of the Module

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1708]
## Your Environment
Plugin version: ^4.12.0
Platform: iOS or Android iOS
OS version: 16.4
React Native version (`react-native -v`): 0.71.7
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
      stationaryRadius: 25,
      disableElasticity: true,
      distanceFilter: 50,
      disableLocationAuthorizationAlert: true,
      maxRecordsToPersist: 1,
      stopOnTerminate: true,
      stopTimeout: STOP_TIMEOUT,
      disableMotionActivityUpdates: true,
      debug: false, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      showsBackgroundLocationIndicator: true,
      allowIdenticalLocations: false,
      foregroundService: true,
      locationAuthorizationRequest: 'WhenInUse',
      ...
    }
```

## Expected Behavior
I want to know, if the module is listening for location changes. 

## Actual Behavior
I am unsure how to get information about the module's state. I know that there is [state object](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/state.html#enabled) with `state.enabled`, which one can access after `BackgroundGeolocation.ready({..})` has been called. However, I am looking for a function/method that I can call from "anywhere", not only after invoking `BackgroundGeolocation.ready({..})`. Is there something like this?

## Context
I want to know if the module is still running or not.

**Comment by christocracy** [comment]
See api docs .getState()

I suggest you have a quick scan of all the available method names in the api docs.
