### ISSUE TITLE
Android:  app is crashing when "Allowing location permission"

### ISSUE THREAD

**Issue by uday8373** [transistorsoft/react-native-background-geolocation#1710]
## Your Environment
* Plugin version: 4.4.4
* Platform:  Android
* OS version: Android 10
* Device manufacturer / model: Redmi 
* React Native version (`react-native -v`): 0.71
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 initDashboard = () => {
    requestPermissions().then(async resolve => {
      console.log('test', resolve)
      if (resolve === 'OK') {
        BackgroundService.initilize()
        const tryLocation = await BackgroundGeolocation.getCurrentPosition({ maximumAge: 5000 })
        if (!tryLocation) {
          this.setState({ loading: false })
        } else {
          const geoLocation = await fetchStateName(null, tryLocation?.coords?.latitude, tryLocation?.coords?.longitude)
          const { state } = geoLocation
          this.setState({ currentLocation: tryLocation?.coords, stateName: state, isIpLocation: false })
          this.props.saveGeoLocation(geoLocation)
          await this.handleUserLocation(tryLocation, state)
          this.getUserLocation(tryLocation)
          this.getProfile()
          BackgroundGeolocation.onLocation(this.onSuccess)
        }
      }
    }).catch(() => {
      console.log("ERROR no LOCATION");
      this.setLocationFromIP()
    })
  }
```

## Expected Behavior
The app is working very well in iOS with same code.

## Actual Behavior
App is crashing on android when allowing location permission.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
06-13 19:59:23.007 15922 15922 E AndroidRuntime: 	... 28 more
06-13 19:59:41.393 15997 16081 E AndroidRuntime: FATAL EXCEPTION: pool-11-thread-4
06-13 19:59:41.393 15997 16081 E AndroidRuntime: Process: com.xoolitdev.xoolit, PID: 15997
06-13 19:59:41.393 15997 16081 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/com.xoolitdev.xoolit-hLK_mi_jAf6dNLfYZiV0AQ==/base.apk!classes6.dex)
06-13 19:59:41.393 15997 16081 E AndroidRuntime: 	at com.transistorsoft.locationmanager.service.ActivityRecognitionService.b(Unknown Source:86)
06-13 19:59:41.393 15997 16081 E AndroidRuntime: 	at com.transistorsoft.locationmanager.service.TrackingService.a(Unknown Source:30)
06-13 19:59:41.393 15997 16081 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$b1.run(Unknown Source:170)
06-13 19:59:41.393 15997 16081 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-13 19:59:41.393 15997 16081 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-13 19:59:41.393 15997 16081 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)

```

</details>

**Comment by uday8373** [comment]
I have the same version of `googlePlayServicesLocationVersion`, here is my android/build.gradle file - 

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        appCompatVersion = "1.4.2" 
        googlePlayServicesLocationVersion = "21.0.1"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
        //Mapbox
        RNMapboxMapsImpl = "mapbox"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.15'
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
    
}

allprojects { 
    repositories {
        maven {
            // react-native-background-fetch
            url("${project(':react-native-background-fetch').projectDir}/libs")
        }
        maven {
           // Required for react-native-background-geolocation
           url("${project(':react-native-background-geolocation').projectDir}/libs")
        }
        maven {
           // Required for react-native-background-fetch
           url("${project(':react-native-background-fetch').projectDir}/libs")
        }

         maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }
    }
}`

**Comment by uday8373** [comment]
It worked ! Thanks for quick reply.

**Comment by uday8373** [comment]
Yeah, I tried editing that comment 3 times and thinking why it was not showing code formatted. Thanks again.

**Comment by vonkanehoffen** [comment]
This is the fix I needed for Expo 50 too, for anyone else searching here. In `app.json`:

```
      [
        "expo-gradle-ext-vars",
        {
          "googlePlayServicesLocationVersion": "21.0.1",
          "appCompatVersion": "1.4.2"
        }
      ],
```

**Comment by chanphiromsok** [comment]
I have a conflict with react-native-maps when I use googlePlayServicesLocationVersion 21.1.0 my google map in android is freeze can not move what should I do? if I use googlePlayServicesLocationVersion 20 google maps can move and geolocation is crashed

**Comment by chanphiromsok** [comment]
@christocracy

**Comment by christocracy** [comment]
If you have a problem with an other plug-in, why are you posting here (on a *closed* issue)?

**Comment by chanphiromsok** [comment]
> If you have a problem with an other plug-in, why are you posting here (on a *closed* issue)?
> 

I wonder if your plugin can use the same 20 but when I try it crashed thx you

**Comment by christocracy** [comment]
You are seeking support on a **closed issue** that has nothing to do with your problem.

**Comment by chanphiromsok** [comment]
> You are seeking support on a **closed issue** that has nothing to do with your problem

incase you have solution that's all

**Comment by abhayciitizen** [comment]
> > Plugin version: 4.4.4
> 
> You need to upgrade to latest version.

my configuration for `play-services-location` API `v21`. Could you please let me know here is talking about which plugin so i can also check.
