### ISSUE TITLE
Module stops tracking location after being stationary for a while

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1712]
I am nearly done with my (private) project. Thanks a lot for the great support with this module Chris. I really appreciate it!!

## Environment
Plugin version: ^4.12.0
Platform: iOS or Android iOS
OS version: 16.4
React Native version (`react-native -v`): 0.71.7
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
export const BACKGROUND_GEOLOCATION_READY_CONFIG = {
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
  stationaryRadius: 25,
  disableElasticity: true,
  distanceFilter: 50,
  disableLocationAuthorizationAlert: true,
  maxRecordsToPersist: 1,
  stopOnTerminate: true,
  stopTimeout: 30,
  disableMotionActivityUpdates: true,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  showsBackgroundLocationIndicator: true,
  allowIdenticalLocations: false,
  foregroundService: true,
};
```

## Expected Behavior
I start the module, put the App into the background and move around. Then I stop moving around for several hours. After several hours, I start moving again. I expect the module to resume tracking when the device moves again, after being still for several hours.

## Actual Behavior
Not tracking after device was being still for several hours.

## Steps to Reproduce
I start tracking, move the App to the background, physically move around and then sit i.e. on my desk for several hours. After several hours, I pick up the phone (I do not open the App again, I do not start the module again) and physically move around a few kilometers. I do not get any notification from iOS that my App is using my location in the background (the blue bar on the top screen) nor can I see that I am actually tracking when I open the app again. 

## Context
I assume that the module goes from `moving`  into `stationary`  as described [here](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation), but I wonder why it does not resume to track, once I start moving again. Yes, I made sure to move more than 200 meters. I am trying this out on my way to the office and back which are a few kilometers on bike. 

Am I assuming right that the module is not tracking after not moving for a long period of time because iOS probably kills my App? Or does this have something to do with me missunderstand how the module works or with my `config`.

**Comment by christocracy** [comment]
I’ve been running my demo app and basically daily field-testing for ~8 years.  It never fails.  It doesn’t matter if you leave your device still for hours or days:  when the device moves about 200 meters, it tracks.

I suggest you install the demo app and compare.

I’m out for a walk currently, as it happens.

![IMG_0737](https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/17fd74b7-bb89-4701-bd63-a108dbe6dbd8)

**Comment by Stophface** [comment]
Hm... I did not think that this is a problem with the module itself, but maybe with my config.
Then, iOS kills my App while being in the background for a while most likely. 

Do you have any ideas how I would debug this? Knowing, why iOS kills my App on a real device? I am bit clueless here.

**Comment by christocracy** [comment]
> Then, iOS kills my App while being in the background for a while most likely.

Yes, it certainly will and it doesn’t matter.  iOS will automatically relaunch your app in the background when the device moves about 200 meters. 

> Do you have any ideas how I would debug this? 

Ensure your app code is **Always** calling `.ready(config)` — no matter what.  Take into account that the OS can **and will** terminate your app in the background when sitting idle, in order to free up memory for the current foreground app.

see wiki *Debugging* and learn how to fetch plug-in logs using .emailLog method.  Also see api docs `Logger`.

install the demo app (linked in the readme) to compare performance.

**Comment by Stophface** [comment]
That

`Yes, it certainly will and it doesn’t matter. iOS will automatically relaunch your app in the background when the device moves about 200 meters.`

was valuable information. I though that when`preventSuspend` is set to false, the module would never fire up again once the App has been suspended.

It works now as I expect it. Thanks Chris

**Comment by christocracy** [comment]
preventSuspend is not required by 99% of use-cases.  The plug-in does not require it for its normal Philosophy of Operation.

**Comment by Stophface** [comment]
I am not using it. From the Philosophy of Operation it was not clear to me, that the plug in re-starts the app, once iOS suspends it. The stationary vs. moving state is very clear, but that the Plug In restarts the App once it has been suspended, that I did not understand from the docs :)
