### ISSUE TITLE
Difference between MotionActivityTypes

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#1717]
According to the [documentation](https://transistorsoft.github.io/react-native-background-geolocation/index.html#motionactivitytype) there are seven Motion Activity Types.

    "unknown" | "still" | "walking" | "on_foot" | "running" | "on_bicycle" | "in_vehicle"

Where is the difference between `walking`  and `on_foot`?

**Comment by christocracy** [comment]
I don’t know.  Both iOS and Android docs do not explain the difference,
