### ISSUE TITLE
Module does give location updates when App is suspended and waked up again

### ISSUE THREAD

**Issue by fourdasheyes** [transistorsoft/react-native-background-geolocation#1719]
## Your Environment
* Plugin version:  "react-native-background-fetch": "^4.0.1", "react-native-background-geolocation": "^4.12.0",
* Platform: iOS
* OS version: 16.4
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 10.2.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
  stationaryRadius: 50,
  disableElasticity: true,
  distanceFilter: 150,
  disableLocationAuthorizationAlert: true,
  maxRecordsToPersist: 2,
  stopOnTerminate: true,
  stopTimeout: 15,
  disableMotionActivityUpdates: true,
  debug: false,
  showsBackgroundLocationIndicator: true,
  allowIdenticalLocations: false,
  foregroundService: true,
};
```

## Expected Behavior
I expect the Module to give location updates, even if the App is in the Background for a long time and the phone has not moved for a while and *then* starts moving again.

## Actual Behavior
I start the module and move around. I get location updates with the App in the forground. Perfect. 
When I bring the App into the background, I get location updates (while moving around). I see the blue bar in iOS telling me that an App is using my location while the App is in the background. Perfect. 
However, when I stop moving around for a long time (i.e. over night, or being at the office for the whole day (without calling `BackgroundGeolocation.stop()`), and then move around again, there are no location updates. No blue bar at the top of my screen. Not perfect. I am not sure why this happens. I suppose iOS suspends the App when it was not opened for a long time. However, from what I understand the Module should start the App again, after changing from `stationary` to `moving`, even if the App has been suspended by iOS, right? In roder for that to work, the `.ready()`  [method must be available to the App when it starts up](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#ready), correct? Additionally, the listeners must be setup, right?

## Steps to Reproduce
Here is the top level component of my App that loads when the App starts. You can see that `BackgroundGeolocation.ready(BG_CONFIG);` is called once in a `useEffect()` hook, when the components mounts. This components mounts every time the App starts. And by start I mean, when it was suspended or terminated, not when it comes from the background to the foreground. The location listener (as well as other listener) I set up in other components which return nothin in their render, but make use of the `useEffect()` hook. I am doing this because I want to separate the logic.

```
const LoadApp = () => {
  const [DatabaseQueue, setDatabaseQueue] = useState(null);
  const {onBoardingDone} = useSelector(state => state.settings.general);

  useEffect(() => {
    setDatabaseQueue(new Queue());
    onBoardingDone &&
      BackgroundGeolocation.ready(BG_CONFIG);
  }, []);

const _selectScreens = () => {
    if (!onBoardingDone) {
      return ...
    } else {
        const database = getDatabase();
        return (
          <DatabaseProvider database={database}>
            {DatabaseQueue && (
              <>
                <BackgroundTrackingModuleState />
                <GeofenceSubscription DatabaseQueue={DatabaseQueue} />
                <LocationSubscription DatabaseQueue={DatabaseQueue} />
                <MotionChangeSubscription DatabaseQueue={DatabaseQueue} />
              </>
            )}
            <PermissionSubscription />
            <Navigation />
            <Notification />
          </DatabaseProvider>
        );
     }
  };

  return _selectScreens();
```

And here is `<LocationSubscription />` (the others look more or less the same)

```
const LocationSubscription = ({DatabaseQueue}) => {
  useEffect(() => {
    const locationSubscription = BackgroundGeolocation.onLocation(
      async location => {
        let {latitude, longitude} = location.coords;
        let {type, confidence} = location.activity;
        ...
        // Add location an associated information to Queue which finally saves the data in a local database for further process
       // its an offline App, so there is no data send to any server
      // its quite some code in here, but this is not important right now I suppose
   })

    return () => locationSubscription.remove();
  }, []);

  return null;
}
```

## Context
I want to continously get location updates. I only want to call `BackgroundGeolocation.start()` once and expect location updates, even when the App has been in the background for lets say a day *and* was suspended by iOS.

**Comment by christocracy** [comment]
I’ve been field testing the plug-in for about 9 years, almost daily.  It doesn’t matter how long the device sits idle (hours, days, weeks) — if the device starts moving about 200 meters, the plug-in will track.

see wiki “Debugging” and learn to fetch logs from the plug-in.

also install the Demo app (linked in readme) to compare performance.

**Comment by christocracy** [comment]
You have to call it **manually**.  Put a temporary button on your UI to execute it.

**Comment by fourdasheyes** [comment]
Sorry @christocracy I am still having some trouble with the module. I thought it resolved itself, but the tracking behaviour stays very inconsistent. Beginning from the `2023-06-26 20:13:08.403` until ~`2023-06-26 21:20:51.810` I can confirm that I have been tracked by the module. iOS showed me the blue bar on the top screen and there are records for my location in my local database. 

However, from the next morning  `2023-06-27 07:03:02.447` onward, I have not seen the hint from iOS that `MyApp` is tracking me in the background. All the way to work (~30-45 Minutes) the blue bar on top where the time is did not appear. Neither are there new records in my database. Also here `2023-06-27 19:39:03.031 ℹ️-[TSDBLogger db_delete] maxAge: 259200`, no blue bar, no tracking at all. There are no records in my local database.

However, I am not sure how to read the logs... May you can pin point me into the right direction? The log is attached

[log.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/11886717/log.txt)

**Comment by christocracy** [comment]
Ensure your app is calling .ready(config) **each and every time** your app launches, even if launched in the background by the OS.

**Comment by christocracy** [comment]
Also, install the *SampleApp* (linked in the readme) onto your device, which I’ve been running on my phones for the last 8 years, which never fails to track me, wherever in the world I go.

**Comment by fourdasheyes** [comment]
I have studied and installed the sample App, but I cannot spot the difference to my setup. Do you mean by "launch" when the App moves from background to foreground/inactive to active or from suspended to running? When you say launch, is the whole App loaded, or only a part of it (i.e. where the use was last?).


I am not sure if I understand these logs here


```
2023-06-27 07:03:02.543 🔵-[TSLocationManager beginStartDetection] 

2023-06-27 07:03:02.543 🎾-[LocationManager requestLocation] ONESHOT

2023-06-27 07:03:02.550 ✅-[BackgroundTaskManager createBackgroundTask] 21

2023-06-27 07:03:02.551 🎾-[SOMotionDetector startShakeDetection:] sample-rate: 0.2 | M7 DISABLED

2023-06-27 07:03:02.553 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:02.553 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:12.550 
📍<+52.48006544,+13.50764518> +/- 12.00m (speed 0.00 mps / course -1.00) @ 27.06.23, 07:03:11 Central European Summer Time

2023-06-27 07:03:12.550 🔴-[LocationManager stopUpdatingLocation] OFF

2023-06-27 07:03:12.550 
╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 1
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:12.562 🔵-[TSLocationManager setPace:] 1

2023-06-27 07:03:12.563 ℹ️-[TSConfig persist] 

2023-06-27 07:03:12.570 🎾-[SOMotionDetector startShakeDetection:] sample-rate: 0.2 | M7 DISABLED

2023-06-27 07:03:12.593 🎾-[TSLocationManager startUpdatingLocation] Location-services: ON

2023-06-27 07:03:12.620 ℹ️+[LocationAuthorization run:onCancel:] status: 3

2023-06-27 07:03:12.621 ✅-[BackgroundTaskManager stopBackgroundTask:]_block_invoke 21 OF (
    21
)

2023-06-27 07:03:12.621 
📍<+52.48006544,+13.50764518> +/- 12.00m (speed 0.00 mps / course -1.00) @ 27.06.23, 07:03:11 Central European Summer Time

2023-06-27 07:03:12.621 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | df: -1.0m | age: 0.7s
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:12.621 ✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+52.48006544,+13.50764518> +/- 12.00m (speed 0.00 mps / course -1.00) @ 27.06.23, 07:03:11 Central European Summer Time

2023-06-27 07:03:12.622 🎾-[TSLocationManager startUpdatingLocation] Location-services: ON

2023-06-27 07:03:12.623 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 38.8

2023-06-27 07:03:12.623 ℹ️-[TSConfig persist] 

2023-06-27 07:03:12.625 🔵-[TSConfig incrementOdometer:] 71346.1

2023-06-27 07:03:12.630 ℹ️+[LocationAuthorization run:onCancel:] status: 3

2023-06-27 07:03:12.634 ℹ️-[LocationDAO shrink:]_block_invoke maxRecordsToPersist: 1

2023-06-27 07:03:12.634 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 897F4FBD-C249-4EAD-94A9-AA8B2E9EC6C0

2023-06-27 07:03:12.634 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:12.634 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:23.597 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:23.597 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:03:23.601 🔵-[TSLocationManager startMotionTriggerTimer] Motion-trigger timer engaged: Stop-detection will trigger in 10 seconds...

2023-06-27 07:03:32.558 🔵-[TSLocationManager endStartDetection] 

2023-06-27 07:03:33.602 🔵-[TSLocationManager beginStopDetection] ⏲Stop-timeout engaged: 480 s...

2023-06-27 07:03:33.605 ✅-[BackgroundTaskManager createBackgroundTask] 24

2023-06-27 07:03:33.605 🎾-[BackgroundTaskManager startKeepAlive] 

2023-06-27 07:03:33.606 🔴-[TSLocationManager stopUpdatingLocation] 

2023-06-27 07:03:34.596 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:34.596 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:03:45.600 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:45.601 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:03:56.601 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | shaking/0 | isMoving: 1
╚═══════════════════════════════════════════════════════════

2023-06-27 07:03:56.602 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 5

2023-06-27 07:03:56.604 🎾-[LocationManager requestLocation] ONESHOT

2023-06-27 07:04:03.411 ℹ️-[TSDBLogger db_save] Log committed

2023-06-27 07:04:06.615 
📍<+52.48015543,+13.50763864> +/- 16.00m (speed 0.00 mps / course -1.00) @ 27.06.23, 07:04:06 Central European Summer Time

2023-06-27 07:04:06.615 🔴-[LocationManager stopUpdatingLocation] OFF

2023-06-27 07:04:06.616 
╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 1
╚═══════════════════════════════════════════════════════════

2023-06-27 07:04:07.601 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:04:07.601 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:04:18.601 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:04:18.601 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:04:29.601 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:04:29.601 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:04:40.601 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:04:40.601 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:04:51.601 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:04:51.601 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:05:02.597 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:05:02.597 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:05:03.710 ℹ️-[TSDBLogger db_save] Log committed

2023-06-27 07:05:13.599 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:05:13.599 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:05:24.601 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:05:24.602 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:05:35.602 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:05:35.602 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:05:46.602 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:05:46.602 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:05:57.602 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:05:57.602 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:06:04.450 ℹ️-[TSDBLogger db_save] Log committed

2023-06-27 07:06:08.602 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2023-06-27 07:06:08.602 🔵-[TSLocationManager createMotionTypeChangedHandler]_block_invoke Shake count: 0

2023-06-27 07:06:19.602 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/0 | isMoving: 0
╚═══════════════════════════════════════════════════════════
```

Do they suggest that the `.ready(config)` function is not called?

**Comment by christocracy** [comment]
> Do you mean by "launch"

When an app is started from a *terminated* state (Eg:  user launching your app by clicking the home-screen icon.).  However, the OS can *and will* terminate apps sitting in the background after a period of time — if the device moves about 200 meters and your app currently *terminated* (either by user or OS), the OS will automatically relaunch your app in the background and the plug-in will resume tracking.

You **must** ensure your app always calls .ready, even if the OS happens to launch your app in the background.

**Comment by fourdasheyes** [comment]
Thanks for coming back. This is loaded every time the App launches. By putting it into the `useEffect()` hook like you are doing it, it is ensured that is only executed once, once the component mounts. This is on launching, and again, after coming from a terminated state (because than everything is unmounted).

```
const LoadApp = () => {
  const [DatabaseQueue, setDatabaseQueue] = useState(null);
  const {onBoardingDone} = useSelector(state => state.settings.general);

  useEffect(() => {
    setDatabaseQueue(new Queue());
    onBoardingDone &&
      BackgroundGeolocation.ready(BG_CONFIG); <-- .ready() method
  }, []);

const _selectScreens = () => {
    if (!onBoardingDone) {
      return ...
    } else {
        const database = getDatabase();
        return (
          <DatabaseProvider database={database}>
            {DatabaseQueue && (
              <>
                <BackgroundTrackingModuleState />
                <GeofenceSubscription DatabaseQueue={DatabaseQueue} />
                <LocationSubscription DatabaseQueue={DatabaseQueue} />
                <MotionChangeSubscription DatabaseQueue={DatabaseQueue} />
              </>
            )}
            <PermissionSubscription />
            <Navigation />
            <Notification />
          </DatabaseProvider>
        );
     }
  };

  return _selectScreens();
```

Which is used in my very top `<App />` component

```
const App: () => React$Node = () => {
  return (
    <>
      <SafeAreaView
        style={{backgroundColor: colors.backgroundColor, flex: 0}}
      />
      <SafeAreaView style={{flex: 1}}>
        <LoadApp />
      </SafeAreaView>
    </>
  );
};
```

export default App;

The only difference between your example and my code is, that I am calling `BackgroundGeolocation.ready(BG_CONFIG);` *before* setting up the `locationListener`. 

```
                <GeofenceSubscription DatabaseQueue={DatabaseQueue} />
                <LocationSubscription DatabaseQueue={DatabaseQueue} />
                <MotionChangeSubscription DatabaseQueue={DatabaseQueue} />
```

Might that be a problem?

**Comment by christocracy** [comment]
You should add event-listeners *before* calling ready.

you can easily tested stopOnTerminate: false in the iOS simulator using debug: true and simulating location with *Freeway Drive*.

**Comment by fourdasheyes** [comment]
I added the listeners before calling .ready() with the same effect. Aber iOS suspends (I assume) the App, it does not track. 

What is interesting is, that I am getting state.enabled = true, even if there are no location updates. Is that expected? 

Would you care to have look at my code (the two files) where I implement your module? I truly cannot Spot the difference between my setup and yours… That would be very kind.

**Comment by christocracy** [comment]
Have you tested in the iOS Sim with debug: true and *Freeway Drive*?

**Comment by fourdasheyes** [comment]
Yes. On the simulator that works - eventhough I cannot simulate a suspended state of the app. I get location updates and I can insert them into my database. 

 It also works on a real device until I leave the phone still for quite some time (overnight, office working time, …). Then the tracking stops. I sometimes get an location arrow in the top right corner next to the battery symbol, but it never goes to the „blue bar“ which tells me „actively tracking“.

**Comment by christocracy** [comment]
> that I am getting state.enabled = true, even if there are no location updates. Is that expected?

Yes.  
- Calling .start() -> State.enabled == true
- Calling .stop() -> State.enabled == false

**Comment by fourdasheyes** [comment]
Hm, thanks. Still the mystery remains why it stops tracking after being suspended.

**Comment by christocracy** [comment]
I suggest you attempt to reproduce in a fresh new *HelloWorld* app using the simple implementation block in the README.

**Comment by fourdasheyes** [comment]
Ill have another look at it :)

**Comment by fourdasheyes** [comment]
One difference I spotted is the following: I made this one

```
BackgroundGeolocation.onLocation(
      async location => {...})
```

`async`. Could this be a problem?

**Comment by christocracy** [comment]
The plug-in tracking performance isn’t affected by event-listeners, such as onLocation.

**Comment by fourdasheyes** [comment]
Do I have to call `.start()` again?  I have a button that executes the `.start()` function. The module tracks. At one point (over night) iOS suspends the app. I ensure that `.ready()` is called when the module wakes up the App. But, do I h ave to call `.start()` again too when the module wakes up the App?

**Comment by christocracy** [comment]
> Do I have to call .start()

Once .start() is called, the plug-in is going to track forever, until .stop() is called.

**Comment by christocracy** [comment]
Wait a second:  look at your Config:

>  stopOnTerminate: true,

That's your problem.

**Comment by fourdasheyes** [comment]
Alright. My setup is the following now

```
const App: () => React$Node = () => {
  const databaseInitialized = useSelector(
    state => state.database.databaseInitialized,
  );
  const DatabaseQueue = new Queue();

  const _setupSubscriptions = () => {
    if (databaseInitialized) {
      const database = getDatabase();
      return (
        <>
          <BackgroundTrackingModuleState />
          <GeofenceSubscription
            database={database}
            DatabaseQueue={DatabaseQueue}
          />
          <LocationSubscription
            database={database}
            DatabaseQueue={DatabaseQueue}
          />
          <AppSettingsSubscription
            database={database}
            DatabaseQueue={DatabaseQueue}
          />
          <MotionChangeSubscription
            database={database}
            DatabaseQueue={DatabaseQueue}
          />
        </>
      );
    }
  };

  return (
    <>
      <SafeAreaView
        style={{backgroundColor: colors.backgroundColor, flex: 0}}
      />
      <SafeAreaView style={{flex: 1}}>
        {_setupSubscriptions()}
        <LoadApp DatabaseQueue={DatabaseQueue} />
      </SafeAreaView>
    </>
  );
};

export default App;
```
`<App />` is my second topmost component. There is only and `index.js` which initializes redux and provides the store.
And `<LoadApp DatabaseQueue={DatabaseQueue} />` (the relevant code) looks like this

```
onst LoadApp = ({DatabaseQueue}) => {
 ...

  useEffect(() => {
    onBoardingDone && _initBackgroundLocation();
  }, []);

  const _initBackgroundLocation = async () => {
    await BackgroundGeolocation.ready(BACKGROUND_GEOLOCATION_READY_CONFIG);
  };

  return <>...</>
```

**Comment by fourdasheyes** [comment]
Why is that? Terminate is something different than suspend? Or is it not?

**Comment by christocracy** [comment]
What do you think "terminate" mean?

**Comment by christocracy** [comment]
If I pull up the Twitter app on my iPhone and **terminate** it, what do you think it means?

**Comment by christocracy** [comment]
And do you know that the OS can **and will** terminate apps sitting suspended in the background after long periods of time, in order to free up memory for the current foreground app.

`stopOnTerminate: true` will cause the plugin to stop tracking if:
1.  The user terminates the app
2. The OS terminates the app.

**Comment by fourdasheyes** [comment]
That you force quit it. Pressing twice (fast) on the home button (old iPhones) and swipe the app to the top. That would be terminating. Then I would expect the module to stop tracking with `stopOnTerminate: true`. 

However, when I put the App into the background and the App then gets suspended by the OS, that wouldn't be terminated.

**Comment by christocracy** [comment]
There is no way to differentiate between user terminating or OS auto-terminating the app.

**Comment by fourdasheyes** [comment]
I read the documentation the following

```
Before an iOS app terminates, the plugin will ensure that a stationary geofence of [stationaryRadius](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#stationaryradius) meters is created around the last known position. When the user moves beyond the stationary geofence (typically ~200 meters), iOS will completely reboot your application in the background, and the plugin will resume tracking. iOS maintains geofence monitoring at the OS level, in spite of application terminate / device reboot.
```

The above mentioned will happen if you set `stopOnTerminate: true`. And I thought it will keep on tracking and thus do not fall into stationary mode if you set `stopOnTerminate: false`. 

That resolves the mystery. Thanks a lot christocracy!
