### ISSUE TITLE
LocationAutorizationAlert not triggered correctly

### ISSUE THREAD

**Issue by Frenor** [transistorsoft/react-native-background-geolocation#172]
Hi,

My settings are the following:
`locationAuthorizationRequest: 'WhenInUse'`
`locationAuthorizationAlert: 'Location is required'`

I believe this should be enough to detect a loss of the location permission, and prompt the user accordingly.

Instead, my app crashes with:

```
🎾-[SOMotionDetector startDetection] 
🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
⚠️-[TSLocationManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=1 "(null)"
🔴-[TSLocationManager stopUpdatingLocation] Location-services: OFF
2016-11-17 15:34:23.058210 GeoTest[4740:1536800] -[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x17006bf80
2016-11-17 15:34:23.058433 GeoTest[4740:1536800] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x17006bf80'
```

**Comment by christocracy** [comment]
The config [`locationAuthorizationAlert`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#param-object-locationauthorizationalert)  requires an `{Object}` not a `String`.

**Comment by Frenor** [comment]
This was actually pretty well documented, my bad!
