### ISSUE TITLE
Location not getting when device in sleep mode or screen lock

### ISSUE THREAD

**Issue by GurjeetLamba** [transistorsoft/react-native-background-geolocation#1721]
## Your Environment
* Plugin version:4.12.1
* Platform: Android
* OS version:
* Device manufacturer / model: OPPO/CPH2095
* React Native version (`react-native -v`): 0.64
* Plugin config

import PushNotification, { Importance } from 'react-native-push-notification';
import { PermissionsAndroid, Alert } from 'react-native';
import RNLocation from 'react-native-location';
import { apiService } from '../../services/api.service';
import RNSettings from 'react-native-settings';
import { AppStorage, key } from '../../services/async-storage';
import moment from 'moment';
import Geolocation from 'react-native-geolocation-service';
import axios from 'axios';
import BackgroundGeolocation, {
  Location,
  Subscription
} from "react-native-background-geolocation"
//import BackgroundGeolocation from '@mauron85/react-native-background-geolocation';
class NotificationHandler {
  async onNotification(notification) {
    console.log("notification received", notification)

    if (notification.data.title === "silent notification") {
      if (Platform.OS === "ios") {
        console.log("Platform", Platform.OS)
      }
      else if (Platform.OS === "android" && notification.data.title == "silent notification") {
        // ============silent notification code============
        const hasBackgroundPermissions = await PermissionsAndroid.check(
          PermissionsAndroid.PERMISSIONS.ACCESS_BACKGROUND_LOCATION,
        );
        const hasforegroundPermissions = await PermissionsAndroid.check(
          PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        );

        let locationSubscription = null;
        let locationTimeout = null;
        if (hasBackgroundPermissions && hasforegroundPermissions) {
          RNSettings.getSetting(RNSettings.LOCATION_SETTING).then(async (result) => {
            if (result == RNSettings.ENABLED) {

              console.log('GPS is on');
              BackgroundGeolocation.ready({
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
           
                stopTimeout: 5,
                // Application config
                debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
                startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
                // HTTP / SQLite config
                url: 'http://yourserver.com/locations',
                batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
                headers: {              // <-- Optional HTTP headers
                  "X-FOO": "bar"
                },
                params: {               // <-- Optional HTTP params
                  "auth_token": "maybe_your_server_authenticates_via_token_YES?"
                }
              }).then(async (state) => {
                // YES -- .ready() has now resolved.
                let locations = await BackgroundGeolocation.getCurrentPosition({
                  timeout: 30,          // 30 second timeout to fetch location
                  persist: true,        // Defaults to state.enabled
                  maximumAge: 5000,     // Accept the last-known-location if not older than 5000 ms.
                  desiredAccuracy: 10,  // Try to fetch a location with an accuracy of `10` meters.
                  samples: 3,           // How many location samples to attempt.
                  extras: {             // Custom meta-data.
                    "route_id": 123
                  }
                });
                BackgroundGeolocation.start();
                console.log("location", locations)
                if (locations.coords.latitude) {
                  console.log("location", locations)
                  let timestamp = new Date();

                  const formatedDate = moment.utc(timestamp).format('YYYY/MM/DD hh:mm:ss A');
                  let respo_storage = await AppStorage.getToken();
                  const requestdata = {
                    ClientId: respo_storage.data.ClientId,
                    Latitude: locations.coords.latitude,
                    Longitude: locations.coords.longitude,
                    TimeStamp: formatedDate,
                    Unique: notification.data.message
                  }
                  console.log("location params in notification handler", requestdata)
                  apiService.post('SAVELOCATION', requestdata).then(
                    (response) => {
                      console.log("updated location response", response)
                      if (response.data.Success) {
                        // BackgroundGeolocation.stop();
                      }
                      else {
                        console.log(response.data.Message)
                      }
                    },
                    (error) => {
                      console.log("Error", error)
                      if (error) {
                        if (error == 'Unauthorized access') {
                          Alert.alert('Warning!', 'Session expired. Please login again', [
                            {
                              text: 'OK',
                              onPress: () => console.log("Session expired"),
                            },
                          ]);
                        } else {
                          Alert.alert('Warning!', error, [
                            {
                              text: 'OK',
                            },
                          ]);
                        }
                      }
                    },
                  );
                }
                else {
                  console.log("location error")
              

                }
              })

              

            } else {
              console.log("Permissoion 1")
              this.sendPermissionStatus();
            }
          });
        }
        else {
          console.log("Permissoion 2")
          this.sendPermissionStatus();
        }
      }

    }

    if (typeof this._onNotification === 'function') {
      this._onNotification(notification);
    }
  }

  sendPermissionStatus = async () => {
    let loginResponse = await AppStorage.getClientId();
    const clientId = loginResponse.data.ClientId;
    let timestamp = new Date();
    const formatedDate = moment.utc(timestamp).format('YYYY/MM/DD hh:mm:ss A');
    console.log("New timestamp parameter handler", formatedDate);
    const data = {
      ClientId: clientId,
      PermissionStatus: "N",
      TimeStamp: formatedDate
    }
    console.log("Location Permission Params", data)
    apiService
      .post('SETLOCATIONPERMISSION',
        data)
      .then(
        (response) => {
          if (response.data.Success) {

          }
        },
        (error) => {
          if (error) {
            Alert.alert('Warning!', error, [
              {
                text: 'OK',
                onPress: () => 'ok pressed',
              },
            ]);
          }
        },
      );
  }
  onRegister(token) {
    console.log("token", token)
    if (typeof this._onRegister === 'function') {
      this._onRegister(token);
    }
  }

  onAction(notification) {
    if (notification.action === 'Yes') {
      PushNotification.invokeApp(notification);
    }
  }

  // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
  onRegistrationError(err) {
    console.log(err);
  }

  attachRegister(handler) {
    this._onRegister = handler;
  }

  attachNotification(handler) {
    console.log("notification handler")
    this._onNotification = handler;
  }
}

const handler = new NotificationHandler();

PushNotification.createChannel(
  {
    channelId: "1", // (required)
    channelName: "My channel", // (required)
    channelDescription: "A channel to categorise your notifications", // (optional) default: undefined.
    playSound: false, // (optional) default: true
    soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
    importance: Importance.HIGH, // (optional) default: Importance.HIGH. Int value of the Android notification importance
    vibrate: true, // (optional) default: true. Creates the default vibration pattern if true.
  },
  (created) => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
);
PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)
  onRegister: handler.onRegister.bind(handler),

  // (required) Called when a remote or local notification is opened or received
  onNotification: handler.onNotification.bind(handler),

  // (optional) Called when Action is pressed (Android)
  onAction: handler.onAction.bind(handler),

  // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
  onRegistrationError: handler.onRegistrationError.bind(handler),

  // IOS ONLY (optional): default: all - Permissions to register.
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },

  // Should the initial notification be popped automatically
  // default: true
  popInitialNotification: true,

  /**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   */
  requestPermissions: true,
});

export default handler;

## Steps to Reproduce

1.
2.
3.
4.

## Context
I am calling Background geolocation code on receive of silent notifications which awake the app in background , It is working fine when screen is not locked , I am getting beep sound everytime location is fetched , but device screen is locked no beep sound and no location update in db

**Comment by christocracy** [comment]
See https://dontkillmyapp.com

**Comment by christocracy** [comment]
Also see wiki “Philosophy of Operation”

**Comment by GurjeetLamba** [comment]
> See https://dontkillmyapp.com

Already tried these steps

**Comment by christocracy** [comment]
I have no idea what is wrong with your device.

**Comment by GurjeetLamba** [comment]
I want to know , Does this library work individually without
react-native-background-fetch , Also I will try testing on another device
but your sample app we used without making any setting changes in device,
How it is uploading location then ?

**Comment by christocracy** [comment]
> Does this library work individually without
react-native-background-fetch

Background-fetch is required to be configured as documented in the Setup Instructions.  Implementing in JavaScript is optional.

See wiki “Debugging” and learn to observe logs from the plug-in.

**Comment by GurjeetLamba** [comment]
Where can I find wiki debugging option? In documentation or I need to
search on google ?

**Comment by christocracy** [comment]
Read the **Wiki** here “Debugging”.  See api docs `Logger`.

**Comment by GurjeetLamba** [comment]
Ok

**Comment by GurjeetLamba** [comment]
Hi ,
Does this library Track location when person is moving only ,Because when
we were still it was not uploading any location ?

**Comment by GurjeetLamba** [comment]
I am writing my Url,Params and token this way , but not getting location in my db Pls suggest what I am doing wrong here 
in http response method getting {"responseText": "{\"success\":true}", "status": 200, "success": true}, In transistorAuthorizationToken I am using the default url https://tracker.transistorsoft.com
const state:State = await BackgroundGeolocation.ready({
      // Debug
      reset: false,
      debug: true,
      url:"http://92.204.135.120:8099/TomAPI/SaveLocationInformation",
      params: {
            ClientId: respo_storage.data.ClientId,
      Latitude: location.coords.latitude,
      Longitude: location.coords.longitude,
      TimeStamp: formatedDate,
      // Unique: notification.data.message
    
      },
      headers: {
        "token":getToken.data.Token
      },
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      transistorAuthorizationToken: token,
      // Geolocation
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10,
      stopTimeout: 5,
      // Permissions
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      // HTTP & Persistence
      autoSync: true,
      maxDaysToPersist: 14,
      // Application
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true
    });

**Comment by GurjeetLamba** [comment]
I have added one more comment on the issue posted yesterday ,Pls check and
respond

**Comment by christocracy** [comment]
`TransistorAuthorizationToken` is only for demo/testing purposes.  When you provide that, the plugin **IGNORES** your provided `url` and automatically sends locations to https://tracker.transistorsoft.com

If you want locations to arrive at your `url:"http://92.204.135.120:8099/TomAPI/SaveLocationInformation"`, then delete this:

```
  transistorAuthorizationToken: token,
```

>Does this library Track location when person is moving only ,Because when
we were still it was not uploading any location ?

It's all explained in the [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation) I told you to read above.  It's pretty clearly stated in the first paragraph.

<img width="928" alt="Screenshot 2023-06-27 at 11 20 04 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/f22d9d85-db08-42be-a48a-9f476bc374d6">

**Comment by GurjeetLamba** [comment]
ok Thanks

**Comment by GurjeetLamba** [comment]
I am getting issue in sending battery level inside location template Can
you please provide one example ,I  have tried. both way with " " and
without quotes, but not working

  locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude
%>,"event":"<%= event %>",isMoving:<%= is_moving %>}'

**Comment by GurjeetLamba** [comment]
I am sending the authentication token but still getting Unauthorised access
const state:State = await BackgroundGeolocation.ready({
// Debug
// reset: false,
// debug: true,
url:"http://92.204.135.120:8099/TomAPI/SaveLocationInformation",
// url:"https://webhook.site/60e38cba-329f-4c49-b5c6-0bfcafd1f373",
locationTemplate: '{"Latitude":<%= latitude %>,"Longitude":<%= longitude
%>,"TimeStamp": "<%= timestamp %>"}',
autoSync:true,
autoSyncThreshold:5,
batchSync:true,
maxBatchSize:50,
params: {
ClientId: respo_storage.data.ClientId,
// Unique: notification.data.message
},
headers: {
//"AUTHENTICATION_TOKEN":getToken.data.Token,
"authorization": "Bearer "+getToken.data.Token,
"X-FOO": "BAR"
},
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
//transistorAuthorizationToken: token,
// Geolocation
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
distanceFilter: 10,
stopTimeout: 5,
// Permissions
locationAuthorizationRequest: 'Always',
backgroundPermissionRationale: {
title: "Allow {applicationName} to access this device's location even when
closed or not in use.",
message: "This app collects location data to enable recording your trips to
work and calculate distance-travelled.",
positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
negativeAction: 'Cancel'
},
// HTTP & Persistence
locationsOrderDirection:"DESC",
maxDaysToPersist: 14,
// Application
stopOnTerminate: false,
startOnBoot: true,
enableHeadless: true
});

**Comment by christocracy** [comment]
GitHub issues are not open-ended support threads for every issue you have.  They are for specific issues according to the subject of the issue *Location not getting when device in sleep mode or screen lock*.  

You are creating a chaotic mess of this issue.  Is your original issue solved?
