### ISSUE TITLE
Jumpy positions recorded

### ISSUE THREAD

**Issue by 0xSwego** [transistorsoft/react-native-background-geolocation#1723]
## Your Environment
* Plugin version: 4.12.1
* Platform: Android
* OS version: _Happened with multiple versions._
* Device manufacturer / model: _Happened with multiple models. More probable with low end phones_
* React Native version (`react-native -v`): 10.2.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        await BackgroundGeolocation.ready({
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            stopTimeout: 5,
            isMoving: false,
            motionTriggerDelay: 30000,
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
            stopOnTerminate: false,
            startOnBoot: true,
            url: `${backendUrl}/location`,
            batchSync: true,
            autoSync: true,
            autoSyncThreshold: 5,
            maxBatchSize: 50,
            params: { userId }
        });
```

## Expected Behavior
Let me tell you that apart from this issue, the plugin works amazingly and we're very happy we have purchased it.

For some users, though, the position accuracy is not good enough. 

I am aware that GPS isn't precise, but, **is there a way to improve it**? I am also open to post-processing solutions, if tweaking the config won't cut it.

## Actual Behavior

The red line is the train track, while the black line is the route recorded for this user. It is jumping from one side to the other and even behaving funnily (see second image).

<img src="https://github.com/transistorsoft/react-native-background-geolocation/assets/21270278/5d53fa9c-aeee-4fb3-bd22-8851ed0a4824" width="600">
<img src="https://github.com/transistorsoft/react-native-background-geolocation/assets/21270278/e510a400-0935-4579-aa11-30c680e090ee" width="600">

</details>

**Comment by christocracy** [comment]
> The position accuracy for some of my users is not good enough. Is there a way to improve it? 

No, there is no way to “improve” it.  You’re expected to filter data as-desired (eg location.coords.accuracy)

**Comment by 0xSwego** [comment]
@christocracy so the best way is just to drop data that has a `location.coords.accuracy > x`?

**Comment by 0xSwego** [comment]
Just FYI, relaying on the `accuracy` was not enough for me. I was still getting some locations that looked very off, in which the accuracy was low.

My solution was to post-process the route by removing outliers. If anyone ends up here and needs more info, just ping me.
