### ISSUE TITLE
License usage

### ISSUE THREAD

**Issue by leerman** [transistorsoft/react-native-background-geolocation#1724]
We have android app which we build with different bundle Ids for store and QA. It is possible to use one license key for two these builds?

**Comment by christocracy** [comment]
The plug-in allows a finite number of suffixes off of the applicationId the key was generated for:
- .qa 
- .staging
- .dev / .development
- .uat
- .test

**Comment by leerman** [comment]
When buying a license, do I need to notify that there will be additional applications with suffixes or it come out of the box?

**Comment by christocracy** [comment]
Out of the box

**Comment by leerman** [comment]
thanks

**Comment by leerman** [comment]
One more question) Do you store any data about application on your side except applicationId?

**Comment by christocracy** [comment]
No.
