### ISSUE TITLE
Getting Unauthorized access (Error code 401)

### ISSUE THREAD

**Issue by GurjeetLamba** [transistorsoft/react-native-background-geolocation#1725]
## Your Environment
Plugin version:4.12.1
Platform: Android
OS version:
Device manufacturer / model: OPPO/CPH2095
React Native version (react-native -v): 0.64
* Plugin config

 const state:State = await BackgroundGeolocation.ready({
     
       url:"http://92.204.135.120:8099/TomAPI/SaveLocationInformation",
      
      locationTemplate: '{"Latitude":<%= latitude %>,"Longitude":<%= longitude %>,"TimeStamp": "<%= timestamp %>"}',
      autoSync:true,
      autoSyncThreshold:5,
      batchSync:true,
      maxBatchSize:50,
      params: {
      ClientId: 69,
      },
      headers: {
     
     "authorization":'Bearer '  + getToken.data.Token ,
        "X-FOO": "BAR"
      },
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
     //transistorAuthorizationToken: token,
      // Geolocation
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10,
      stopTimeout: 5,
      // Permissions
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      // HTTP & Persistence
    locationsOrderDirection:"DESC",
      maxDaysToPersist: 14,
      // Application
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true
    });

**Comment by GurjeetLamba** [comment]
That I will do after making sure I am sending the token in correct way

**Comment by christocracy** [comment]
See [Mozilla MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) for information about *Bearer token*.

**Comment by GurjeetLamba** [comment]
I Use the Bearer token while calling other API's so nothing wrong in that , But should I use the authorization keyword only ?

**Comment by christocracy** [comment]
The `Config.headers` are applied to the http request exactly as provided.  There is nothing unusual about your `authorization` header.

consult with your server logs.

**Comment by GurjeetLamba** [comment]
ok Thanks

**Comment by GurjeetLamba** [comment]
Hi 
I pass a source parameter also inside my header when I call any API ,May be I am getting error due to this , What will be the way to pass source here inside double quotes or with double quotes ?
<img width="829" alt="Screenshot 2023-06-29 at 3 40 53 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/13586101/a368014b-58a1-4989-bdb7-5b9bcc1f2205">

**Comment by christocracy** [comment]
HTTP header values are always of type `String`

**Comment by GurjeetLamba** [comment]
so I should use 
{
"source": "92.204.135.120"
}

?

**Comment by christocracy** [comment]
“HTTP header values are always of type `String`” *implies* that values must *always* be enclosed in quotes.
