### ISSUE TITLE
Background track not working properly on iOS

### ISSUE THREAD

**Issue by marcusvbrabello** [transistorsoft/react-native-background-geolocation#1727]
## Your Environment
* Plugin version: 4.8.2
* Platform: iOS 
* OS version: 16.4
* Device manufacturer / model: iPhone 8 and iPhone 11
* React Native version: 0.68.2
* Plugin config: 
`const initBackgroundGeolocation = async () => {
		reseting();
		subscribe(
			BackgroundGeolocation.onLocation(
				async (location) => manageEventData(location),
				(error) => {
					error === 1 && dispatch(changeEnabledBackground(false));
					console.warn("[onLocation] ERROR: ", error);
				}
			)
		);

		subscribe(
			BackgroundGeolocation.onHeartbeat((event) => {
				BackgroundGeolocation.getCurrentPosition({
					samples: 1,
					persist: true,
				}).then((location) => manageEventData(location));
			})
		);

		await BackgroundGeolocation.destroyTransistorAuthorizationToken(
			"https://tracker.transistorsoft.com"
		);

		/// Get an authorization token from demo server at tracker.transistorsoft.com
		const token =
			await BackgroundGeolocation.findOrCreateTransistorAuthorizationToken(
				user?.subscriptions[
					stepCar
				]?.vehicle?.plateNumber.toLowerCase(),
				user?.subscriptions[
					stepCar
				]?.vehicle?.plateNumber.toLowerCase(),
				"https://tracker.transistorsoft.com"
			);

		/// Configure the plugin.
		BackgroundGeolocation.ready({
			reset: false,
			debug: false,
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
			transistorAuthorizationToken: token,
			desiredAccuracy:
				Platform.OS === "ios"
					? BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION
					: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			distanceFilter: 10,
			locationAuthorizationRequest: "Always",
			backgroundPermissionRationale: {
				title: "Allow {applicationName} to access this device's location even when closed or not in use.",
				message:
					"This app collects location data to enable recording your trips to work and calculate distance-travelled.",
				positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
				negativeAction: "Cancel",
			},
			autoSync: true,
			maxDaysToPersist: 14,
			stopOnTerminate: false,
			startOnBoot: true,
			enableHeadless: true,
			//NO CONTENT DEMO
			heartbeatInterval: 60,
			preventSuspend: true,
			foregroundService: true,
			fastestLocationUpdateInterval: 5000,
			locationUpdateInterval: 5000,
			deferTime: 10000,
			showsBackgroundLocationIndicator: false,
			activityType:
				BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
			stationaryRadius: 200,
			interval: 5000,
		})
			.then((res) => {
				BackgroundGeolocation.start();

				setBgEnabled(res.enabled);
			})
			.catch((err) => console.log(err));
	};`

## Expected Behavior
My app should track my waypoints when the device is in the foreground, background and inactive modes.

## Actual Behavior
When it is in the foreground and background modes it works properly, but when I change to inactive mode, the odometer returns the wrong information about the trip. I want to know what is wrongly configured.

## Debug logs
<details><summary>Logs</summary>
PASTE_YOUR_LOGS_HERE
</details>
[iPhone 8 - log.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/11896416/iPhone.8.-.log.zip)

**Comment by christocracy** [comment]
> Plugin version: 4.8.2

See CHANGELOG and upgrade to latest version.

**Comment by marcusvbrabello** [comment]
I upgraded and this appeared.

![Captura de Tela 2023-06-29 às 15 19 16](https://github.com/transistorsoft/react-native-background-geolocation/assets/99079691/a331e1c9-ff3a-409e-ab2f-be9bb0928291)

![Captura de Tela 2023-06-29 às 15 25 19](https://github.com/transistorsoft/react-native-background-geolocation/assets/99079691/6cc6bdcd-5904-40fa-a35e-b051cbf3c155)

**Comment by christocracy** [comment]
That has nothing to do with the plug-in.

**Comment by marcusvbrabello** [comment]
What is the minor version of react native that I have to use with 4.12.1?

**Comment by christocracy** [comment]
Your stacktrace doesn’t seem related to the plugin (or your RN version)

Your stacktrace seems to reference every plug-in you’re using.
