### ISSUE TITLE
Clarification regarding Android foreground/background services in the library's internals

### ISSUE THREAD

**Issue by savv** [transistorsoft/react-native-background-geolocation#1728]
## Your Environment
* Plugin version: 4.12.1
* Platform: Android
* OS version: 31
* Device manufacturer / model: emulator
* React Native version (`react-native -v`): 0.71.10
* Plugin config
```typescript <!-- Syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BackgroundGeolocation?.DESIRED_ACCURACY_HIGH,
  distanceFilter: 20,
  foregroundService: true,

  locationAuthorizationRequest: 'WhenInUse',
  stopDetectionDelay: 2,
  stopTimeout: 10,
}
```

## Context
[This answer](https://support.google.com/googleplay/android-developer/answer/9799150) clarifies that in certain cases they "approve an app’s use of [foreground service](https://developer.android.com/guide/components/foreground-services), a separate API that lets an app access location information even when the app is minimized and not visible to the user".

This perfectly describes our app, however, I am not sure how the library is implemented internally (although the library's name is quite suggestive in that regard :)) and I haven't been able to understand if there is a config combination that allows this.

- Does react-native-background-location support the use case above ("foreground service")? What config params are needed for this?
- Does `locationAuthorizationRequest: 'WhenInUse'` require `ACCESS_BACKGROUND_LOCATION`?
- Does `locationAuthorizationRequest: 'WhenInUse'` allow to continue tracking the user's location, if the app is in the background, but the process has not been killed?

I have already read this [blog post](https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353) and the API documentation around [locationAuthorizationRequest](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#locationauthorizationrequest).

**Comment by ThibautMT** [comment]
I have the same question.
Does the plugin use ACCESS_BACKGROUND_LOCATION ?
Thanks

**Comment by christocracy** [comment]
> Does the plugin use ACCESS_BACKGROUND_LOCATION ?

Yes, of course.

**Comment by christocracy** [comment]
>Does react-native-background-location support the use case above ("foreground service")? What config params are needed for this?

Yes.  No extra config required.  The plug-in is built around foreground-services for the last 8 years.

>Does locationAuthorizationRequest: 'WhenInUse' require ACCESS_BACKGROUND_LOCATION?

No.

>Does locationAuthorizationRequest: 'WhenInUse' allow to continue tracking the user's location, if the app is in the background, but the process has not been killed?

no.

to continue tracking in the background with WhenInUse, your app must engage location-services while in the foreground with `.changePace(true)`, like a *Jogging App* with its [Start Workout] button.

but once an app with WhenInUse is terminated, it is impossible to continue location-tracking (the app is no longer “in-use”).

there are major consequences to WhenInUse vs Always.

**Comment by savv** [comment]
Thank you for your response. 

> > Yes. No extra config required. The plug-in is built around foreground-services for the last 8 years.

Brilliant. It seems to work well for us in this mode; however, I wanted to clarify in order to avoid getting our app banned from a misunderstanding.

> > Does locationAuthorizationRequest: 'WhenInUse' allow to continue tracking the user's location, if the app is in the background, but the process has **not** been killed?
> 
> no.

From the context below, it sounds like the answer should be yes?

> to continue tracking in the background with WhenInUse, your app must engage location-services while in the foreground with `.changePace(true)`, like a _Jogging App_ with its [Start Workout] button.
> 
> but once an app with WhenInUse **is terminated**, it is impossible to continue location-tracking (the app is no longer “in-use”).
