### ISSUE TITLE
Will using BackgroundFetch.configure in addition to BackgroundGeolocation.onHeartbeat reduce the frequency of force kills in iOS?

### ISSUE THREAD

**Issue by minsoo91** [transistorsoft/react-native-background-geolocation#1729]
## Your Environment
* Plugin version: 4.9.3
* Platform: iOS
* OS version: 16.2
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 0.71.7
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
export const GEO_LOCATION_READY_CONFIG: Config = {
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  // on iOS this will be invoked automatically from info.plist NSLocationAlwaysUsageDescription
  backgroundPermissionRationale: {
    title:
      "Allow *** to access this device's location when you are on an active shift",
    message:
      'Your location is required to let your employer know where you are while you are working. Location is not shared with your employer if you are not clocked in.',
  },
  locationAuthorizationAlert: {
    instructions:
      'Your location is required to let your employer know where you are while you are working. Location is not shared with your employer if you are not clocked in.',
    titleWhenNotEnabled:
      "Allow *** to access this device's location when you are on an active shift",
    titleWhenOff:
      "Allow *** to access this device's location when you are on an active shift",
    cancelButton: 'Cancel',
    settingsButton: 'Settings',
  },
  disableLocationAuthorizationAlert: false,
  showsBackgroundLocationIndicator: true,
  geofenceModeHighAccuracy: false,
  heartbeatInterval: 60, // for testing - should be 300
  stopOnTerminate: false,
  foregroundService: true,
  preventSuspend: true,
  stopTimeout: 1, // for testing - should be 5 (default)
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  persistMode: BackgroundGeolocation.PERSIST_MODE_NONE
};
```

## Expected Behavior
When the phone is stationary and within the stationary geofence, we rely on ```BackgroundGeolocation.onHeartbeat``` to periodically record the current location to our DB. 

We are facing the same issue as ["iOS Background Task Being Forcekilled"](https://github.com/transistorsoft/react-native-background-geolocation/issues/1197)) in iOS. Our use case is also safety related (typical usage pattern is bursts of movement followed by significant periods of stationary over 8-16 hours), so recording the location even when stationary is important to us

We expect adding another heartbeat using background-fetch library will reduce the # of arbitrary Force kills by iOS.

## Actual Behavior
More of a question: Will using both ```BackgroundGeolocation.onHeartbeat``` and ```BackgroundFetch.configure``` reduce the number of force kills in iOS? We wanted to know whether iOS would just kill both tasks at the same time or whether using both would help.

## Steps to Reproduce

1. Start location tracking per library specs
2. Put app in the background
3. When stationary, app emits heartbeat
4. heartbeat arbitrarily killed by iOS. sometimes a few minutes, other times few hours. does not restart until app is brought back to the foreground.

## Context
When the location permission is set to always and the app is in the background, we want the app to collect the location of our users every X minutes for 8-16 hours.

During testing, we saw that gaps in records created by errors such as:
```
2023-06-28 20:34:36.374 ⚠️-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 179, remaining time: 4.005827
```

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
2023-06-29 09:31:58.163 ⚠️-[BackgroundTaskManager createBackgroundTask]_block_invoke FORCE KILL BACKGROUND TASK: 1097, remaining time: 4.121362

2023-06-29 09:31:58.165 ✅-[BackgroundTaskManager stopBackgroundTask:]_block_invoke 1097 OF (
    1097
)
```

</details>

[background-geolocation (3).log](https://github.com/transistorsoft/react-native-background-geolocation/files/11910319/background-geolocation.3.log)

**Comment by christocracy** [comment]
> Will using BackgroundFetch.configure in addition to BackgroundGeolocation.onHeartbeat reduce the frequency of force kills in iOS

No.

**Comment by christocracy** [comment]
iOS heartbeat is fragile and not 100% guaranteed.  It is a hack.

**Comment by christocracy** [comment]
preventSuspend is not required for tracking users.  preventSuspend is not required for 99% of use-cases.  I recommend it be avoided.

**Comment by minsoo91** [comment]
## Our requirements

Our use case requires that the app periodically tracks location even when:
1. The user is stationary for a long period of time
2. The app is in the background
3. Do this at least once every 15 minutes, preferably every 2-5 minutes.
4. Battery lasts more than 2 hours


## What I currently understand as options
Based on reading through some of the previously closed github issues, I see three options:

1. BackgroundFetch.configure. Can occur as frequently as every 15 minutes (though it is possible for iOS to trigger this more often. Impossible to know how often)
2. BackgroundGeolocation.onHeartbeat + preventSuspend (per your comment above, it's fragile + not recommended for indefinite usage bc we don't know when iOS will shut it off)
3. Keeping location service on all the time (by pretending that the user is always on the move) with a combination of ```BackgroundGeolocation.changePace```, ```Config.pausesLocationUpdatesAutomatically```, ```Config.disableStopDetection``` (drains battery life v quickly)

## My Follow-up Questions
1. If you don't recommend BackgroundGeolocation.onHeartbeat + preventSuspend, what do you actually recommend?
2. Do you have an example where preventSuspend is recommended?

**Comment by christocracy** [comment]
This plugin's [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation) is to track location *only* when the device is detected to be moving.  If the device is *not* moving, it's pointless to waste energy constantly recording location (*here I am*...*here I am*...*here I am*) when the device is known to be at the last known location.

If you want periodic location updates, implement `BackgroundFetch` and execute `BackgroundGeolocation.getCurrentPosition(options)` in your `BackgroundFetch` callback.

> Could iOS still Force Kill our app even if we use only use 

You can expect that the OS *will* terminate apps sitting idle in the background for long periods of time.  It *will* 100% certainly happen.  It doesn't matter.  As soon as the device moves about 200 meters, the OS will automatically relaunch your app in the background the the plugin will resume location-tracking.

**Comment by christocracy** [comment]
Another way to get periodic locations is to send a push notification to a particular device.

iOS has introduced a new [Location Push Service](https://developer.apple.com/documentation/corelocation/creating_a_location_push_service_extension?language=objc) mechanism to help with this.  The Setup is **very** complex and cannot be automated by the plugin.  I have a draft [blog entry](https://medium.com/@transistorsoft/creating-an-ios-location-push-service-extension-7f1d58c9d64f) about it (which I've been side-tracked from since February).

**Comment by minsoo91** [comment]
I appreciate the library's Philosophy of Operation. It strikes a good balance between battery efficiency and gathering the only the interesting locations (moving). I agree with you that calling getCurrentPosition on heartbeat is unnecessary, but periodically telling the server that everything is still working as expected by way of some sort of a heartbeat is a useful real world use case. No news is good news.. except tell me periodically that there's no news.

Thanks for sharing your blog post. Running a native iOS instance of BackgroundGeolocation library within the extension seems like a pretty cool way to increase reliability for our app. Managing the APNS push tokens and only sending push requests for specific app states (to be known and managed by our server) seems like a nontrivial lift, but it's definitely interesting and something we'd move to implement as we onboard enterprise customers with specific contract clauses.

Last question: I noticed earlier in your blog that “silent push notifications” ([background notifications](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app)) are no longer reliable. Do you have any knowledge on foreground notifications? Would they reboot /restart background tasks of an app in the background without a specific handler (even if the user does not click on it to bring our app to the foreground)? 

Right now, my proposed solution based on your feedback is:
- Implement ```BackgroundFetch.configure```
- Remove onHeartbeat
- Send a wellness check push notification if we detect that we haven't received a location in X minutes.
