### ISSUE TITLE
[Question] Use react-native-background-geolocation only to get users' current position.

### ISSUE THREAD

**Issue by Saad-Bashar** [transistorsoft/react-native-background-geolocation#1734]
I would like to know if I can use this library only for the purpose of getting user location. No background tracking is needed, only foreground usage. Hence we also do not want the "Give location always" permission. This is a simple use case but we had troubles getting user location properly with other libraries. 

Thanks!

**Comment by christocracy** [comment]
Yes.  See api docs Config.locationAuthorizationRequest.  See method .getCurrentPosition().

you would not call the method .start()

**Comment by Saad-Bashar** [comment]
Thanks for the response. Does this look okay to you? I am getting the location properly with this. But I am getting this warning message "WARN  Sending `location` with no listeners registered." The next question is we still need to buy the license for android to use this, right? Thanks! 

```
<Button
    title="Get Location with Background Geolocation"
    onPress={() => {
      BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
        locationAuthorizationRequest: 'WhenInUse',
      }).then(state => {
        BackgroundGeolocation.getCurrentPosition()
          .then(location => {
            console.log('- getCurrentPosition success: ', location);
          })
          .catch(error => {
            console.log('- getCurrentPosition error: ', error);
          });
      });
    }}
  />
```

**Comment by christocracy** [comment]
**Note**:  Do not *ever* call `.getCurrentPosition(options)` until `.ready(config)` has resolved.
