### ISSUE TITLE
Getting issue in setting interval for locations 

### ISSUE THREAD

**Issue by GurjeetLamba** [transistorsoft/react-native-background-geolocation#1737]
<!--
I want to send location in db after an interval (3 min or 5 min) , I don't want to use distance filter as I want to know in still state also that background location is working  on the device , so I am using locationUpdateInterval, but the db update is not happening exactly after 3 minutes , its is random sometimes 3 min , sometime 2 min , Also while fetching locations library is giving multiple locations at same time or in the difference of seconds 
--
## Your Environment
* Plugin version:0.6.3
* Platform: Android
* OS version: 12
* Device manufacturer and model: OPPO CPH2095
* React Native version: 0.64
* Plugin config
  const state:State = await BackgroundGeolocation.ready({
      url:"https://hkdk.events/9JXddKxb5fnn",
     reset: false,
     debug: true,
      locationTemplate: '{"Latitude":<%= latitude %>,"Longitude":<%= longitude %>,"TimeStamp": "<%= timestamp %>"}',
      autoSync:true,
      deferTime:180000,
   
      params: {
      ClientId:respo_storage.data.ClientId,
     
      },
      headers: { 
     authorization: "Bearer "+getToken.data.Token, 
      source:source
      },
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      locationUpdateInterval:180000,
      allowIdenticalLocations:false,
      stopTimeout: 5,
      fastestLocationUpdateInterval:180000,
   
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      maxDaysToPersist: 14,
     
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
    
    });

## Expected Behavior
Location must be updated in db exactly after 3 min even in still mode or moving 

## Actual Behavior
Location is updating most after 3 min but in rare cases it updates after 2 min , and multiple locations at same time

**Comment by christocracy** [comment]
There’s a required issue template here.  It’s not optional




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by GurjeetLamba** [comment]
added another issue pls check that

**Comment by GurjeetLamba** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/issues/1738
