### ISSUE TITLE
Getting issue in setting the interval for location update in database

### ISSUE THREAD

**Issue by GurjeetLamba** [transistorsoft/react-native-background-geolocation#1738]
## Your Environment
 "react-native-background-fetch": "^4.1.10",
 "react-native-background-geolocation": "^4.12.1",
* Platform: Android
* OS version: 12
* Device manufacturer and model: OPPO CPH2095
* React Native version: 0.64
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  const state:State = await BackgroundGeolocation.ready({
      url:"https://hkdk.events/9JXddKxb5fnn",
     reset: false,
     debug: true,
      locationTemplate: '{"Latitude":<%= latitude %>,"Longitude":<%= longitude %>,"TimeStamp": "<%= timestamp %>"}',
      autoSync:true,
      deferTime:180000,
   
      params: {
      ClientId:respo_storage.data.ClientId,
     
      },
      headers: { 
     authorization: "Bearer "+getToken.data.Token, 
      source:source
      },
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      locationUpdateInterval:180000,
      allowIdenticalLocations:false,
      stopTimeout: 5,
      fastestLocationUpdateInterval:180000,
   
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      maxDaysToPersist: 14,
     
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
    
    });

## Expected Behavior
Location must be updated in db exactly after 3 min even in still mode or moving ## Actual Behavior

Actual Behaviour
Location is updating most after 3 min but in rare cases it updates after 2 min , and multiple locations at same time## Steps to

**Comment by GurjeetLamba** [comment]
This issue is not resolved yet

**Comment by GurjeetLamba** [comment]
This was set to false in Demo Application provided in the library , I didn't get the meaning of it What exactly it is doing

**Comment by christocracy** [comment]
Delete that whole line from your Config `reset: false`.

**Comment by GurjeetLamba** [comment]
ok

**Comment by GurjeetLamba** [comment]
Tried deleting this but Still getting issue with the Accuracy If I use  locationUpdateInterval instead of distance filter , Its our requirement that we need to update location after specific interval  also getting issue still mode , latitude and longitude are not accurate in still mode 
    const state: State = await BackgroundGeolocation.ready({

      url: "http://92.204.135.120:8099/TomAPI/SaveLocationInformation",
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 0,
      locationUpdateInterval: interval,
      stopTimeout: 5,
      locationTemplate: '{"Latitude":<%= latitude %>,"Longitude":<%= longitude %>,"TimeStamp": "<%= timestamp %>"}',
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      headers: {
        authorization: "Bearer " + getToken.data.Token,
        source: source
      },
      params: {
        ClientId: respo_storage.data.ClientId,
      },
      batchSync: true,
      autoSync: true,
      maxDaysToPersist: 14,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true
    });

**Comment by christocracy** [comment]
> latitude and longitude are not accurate in still mode

What makes you suspect that they’re “not accurate”?

**Comment by GurjeetLamba** [comment]
I am showing the lat long on map and it is showing in slightly different position from where I was actually situated

**Comment by christocracy** [comment]
And why are you not show me this map?

**Comment by GurjeetLamba** [comment]
ok I will share the  map screenshot also

**Comment by GurjeetLamba** [comment]
<img width="829" alt="Screenshot 2023-07-05 at 11 47 29 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/13586101/a892250b-e4f7-4546-a688-69753a5ab09f">
As shown in the image the marker showing away is at the time when I was at my home where a group of markers are shown

**Comment by christocracy** [comment]
Do you know that the geolocation accuracy while indoors is 40-60 meters?  GPS only works outdoors (accuracy ~5 meters).

Do you know that a geolocation is not a simple point in space?  It’s a circle of probability of radius `location.coords.accuracy` meters.  The real location of the device is somewhere in that circle.

**Comment by christocracy** [comment]
I suggest you go outside for a nice long test of >1km.

**Comment by GurjeetLamba** [comment]
@christocracy We are facing this issue sometimes during walk also, If I use distance filter accuracy is better, But we need to update location after a time interval in minutes(3 min. or 5 min) thats why I am using locationUpdateInterval , but getting issue in accuracy with it and while in still mode interval also get disturbs location update after random intervals

**Comment by christocracy** [comment]
>Plugin version:0.6.3

There is no such thing as `0.6.3`.  Where do you get this version number from?

**Comment by GurjeetLamba** [comment]
sorry I have updated the version number , I am using the latest version for both the libraries

**Comment by christocracy** [comment]
I have no suggestion for your problem.

it’s recommended to use distanceFilter, it saves energy.  Do you know that iOS doesn’t even allow time based location updates?

**Comment by christocracy** [comment]
Have you read the wiki “Philosophy of Operation”.

do you understand what Config.stopTimeout is?

do you understand when onMotionChange fires?

**Comment by GurjeetLamba** [comment]
yes

**Comment by GurjeetLamba** [comment]
<img width="1202" alt="Screenshot 2023-07-11 at 11 02 14 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/13586101/f40de355-1ca1-4ca5-8b77-22bc66c4db51">
<img width="1169" alt="Screenshot 2023-07-11 at 11 02 42 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/13586101/61212b07-1f91-4d11-8bf6-291224cb069e">

In

**Comment by GurjeetLamba** [comment]
But after 8:15 I got only one location at 8:23 , What could be the reason of that gap ?

**Comment by christocracy** [comment]
I have no idea.  Why don’t you fetch the logs from the plug-in with .emailLog method and see what the plug-in was saying in its logs?

**Comment by christocracy** [comment]
See wiki *Debugging*

**Comment by GurjeetLamba** [comment]
> I have no idea. Why don’t you fetch the logs from the plug-in with .emailLog method and see what the plug-in was saying in its logs?

ok

**Comment by GurjeetLamba** [comment]
[69ce9530-d4e6-41f2-8035-3b90d5653bcf.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/12145345/69ce9530-d4e6-41f2-8035-3b90d5653bcf.gz)

I am not able to read the error from logs , please help me here

**Comment by christocracy** [comment]
The file is *gzipped*.  You need to unzip it.
