### ISSUE TITLE
Allow app to access your physical activity with disabled disableMotionActivityUpdates flag

### ISSUE THREAD

**Issue by DzianisAleshkou** [transistorsoft/react-native-background-geolocation#1746]
## Your Environment
* Plugin version: 4.12.1
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.69.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
export const locationConfig = {
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  stationaryRadius: 15, // <-- Default: 25. When stopped, the minimum distance the device must move beyond the stationary location for aggressive background-tracking to engage.
  distanceFilter: 10, // <-- The minimum distance (measured in meters) a device must move horizontally before an update event is generated.
  title: "App is Running in Background.",
  text: "",
  debug: false,
  startOnBoot: false, // <-- Auto start tracking when device is powered-up.
  stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
  locationAuthorizationRequest: "Always",
  backgroundPermissionRationale: {
    title: "...",
    message: `...`,
    positiveAction: "..."
  },
  locationUpdateInterval: 5000,
  disableMotionActivityUpdates: true
};
```

## Expected Behavior
modal does not appear in app

## Actual Behavior
I see this modal in app with `disableMotionActivityUpdates: true`
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/90327288/abb4fa9b-703c-4c20-a4bb-a7864c9866ca)
and I init service after BG.ready()
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/90327288/e55d4396-75ed-47ce-84ea-79446d28c1e9)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
(Mistake above)

If the plugin is configured with disableMotionActivityUpdates: false (ie: do NOT disable), you will see this in the logs:

07-12 11:54:23.386 13693 13823 I TSLocationManager:   🎾  Start motion-activity updates

**Comment by DzianisAleshkou** [comment]
@christocracy
`2. Configuring the plugin with reset: false`
It works. Thank you. Can be closed

**Comment by christocracy** [comment]
Why were you *hiding* that Config and not showing it here?

**Comment by DzianisAleshkou** [comment]
@christocracy 
Actually `2. Configuring the plugin with reset: false` didn't help. Modal appears if`disableMotionActivityUpdates: true` and `reset: false`.
my config 
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/90327288/ca3751af-2654-4115-b1c3-355f0a4b1942)
this from my app permissions. How can I remove "Physical Activity" permission from app. I do not use another location service.
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/90327288/208a2af3-23fa-4773-bfd0-0a4c2a4a08de)

**Comment by christocracy** [comment]
I don't think you understand what `reset: false` is.  99% of users should not use `reset: false`.  It causes the plugin to **IGNORE** the `Config` provided to `ready(config)`.

**Comment by DzianisAleshkou** [comment]
@christocracy when I do not use 'reset: false' modal with 'physical activity' permission appears if disableMotionActivityUpdates is true

**Comment by DzianisAleshkou** [comment]
@christocracy How can I remove 'Physical Activity' permission on native level

**Comment by christocracy** [comment]
I have no idea what you're doing wrong, but you're doing something wrong.

Create for me a simple *HelloWorld* that reproduces this.  Share your simple *HelloWorld* in a public github repo here.

**Comment by christocracy** [comment]
Do **NOT** use `reset: false`.

**Comment by DzianisAleshkou** [comment]
Why does "Physical Activity" permission display in permissions settings?

**Comment by DzianisAleshkou** [comment]
Can I see it in node_modules?

**Comment by christocracy** [comment]
no.

**Comment by DzianisAleshkou** [comment]
but if app does not use it, why is it important setting?
