### ISSUE TITLE
locationTemplate carrying additional data like provider, getCurrentPosition etc

### ISSUE THREAD

**Issue by mgsbabu** [transistorsoft/react-native-background-geolocation#1747]
## Your Environment
* Plugin version:4.12.1
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):0.68.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>, "timest": "<%= timestamp %>"}', 

Though I configured locationTemplate as above in BackgroundGeolocation.ready() method , but the request is coming is coming with additional properties like "provider".

{"location":[{"lat":17.4830965,"lng":78.3933852,"timest":"2023-07-14T04:56:58.457Z","provider":{"network":true,"gps":true,"enabled":true,"status":3,"accuracyAuthorization":0,"airplane":false}}]}

## Expected Behavior

How can we restrict sending additional variables like "provider", "getCurrentPosition" from the location object. Is there any configuration I am missing to send strictly what is configured in the locationTemplate property

</details>

**Comment by christocracy** [comment]
When the device location-services changes (ie: Disabled in settings, disable wifi, enter airplane mode), the plugin automatically records a `providerchange` location and posts this to your server.  Some people like to know when the state of location-services changes on the device (eg: user disables location).

See API docs [Config.disableProviderChangeRecord](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#disableproviderchangerecord)
