### ISSUE TITLE
Heart Beat Interval is only working when app open .

### ISSUE THREAD

**Issue by GurjeetLamba** [transistorsoft/react-native-background-geolocation#1748]
I  am trying to send location to API in stationary mode , after every heart beat interval , location is updating in db after the mentioned time, but when app  goes to background location updates stop.

## Your Environment
* Plugin version: "^4.12.1"
* Platform: Android
* OS version: 12
* Device manufacturer / model:OPPO CPH2095
* React Native version (`react-native -v`): 0.64
* Plugin config
    this.subscriptions.push(BackgroundGeolocation.onHeartbeat((event)=>{
      console.log("[onHeartbeat] ", event);

      // You could request a new location if you wish.
      BackgroundGeolocation.getCurrentPosition({
        samples: 1,
        persist: true
      }).then((location) => {
        console.log("[getCurrentPosition] ", location);
      });
    }))
    
 const state = await BackgroundGeolocation.ready({

    url: API_URL+API_ENDPOINTS.SAVELOCATION,
    //debug: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 20,
   // locationUpdateInterval: interval,
    stopTimeout: 5,
    locationTemplate: '{"Latitude":<%= latitude %>,"Longitude":<%= longitude %>,"TimeStamp": "<%= timestamp %>"}',
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: {
      title: "Allow {applicationName} to access this device's location even when closed or not in use.",
      message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
      positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
      negativeAction: 'Cancel'
    },
    headers: {
      authorization: "Bearer " + getToken.data.Token,
      source: source
    },
    params: {
      ClientId: respo_storage.data.ClientId,
    },
    batchSync: true,
    autoSync: true,
    maxDaysToPersist: 14,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    heartbeatInterval: 120,
  preventSuspend: true 
  });

## Expected Behavior
Location should update in stationary mode after heart beat interval even when app is in background 

## Actual Behavior
Location updates only when app is open in stationary mode

**Comment by christocracy** [comment]
>Device manufacturer / model:OPPO CPH2095

See https://dontkillmyapp.com

**Comment by GurjeetLamba** [comment]
Does I need to install this app dontkillmyapp along with background location library to use heart beat event,because I have checked in two different android devices it is not working in background in android

**Comment by christocracy** [comment]
> Does I need to install this app dontkillmyapp

No.  You just need to follow the instructions for your device at that website.

**Comment by GurjeetLamba** [comment]
But As my app has many users so that will not be possible to make setting changes in different devices

**Comment by christocracy** [comment]
I suggest you address your complaints to the particular Android device manufacturers you’re concerned with.  Tell them to respect the Android API.

- Google issue tracker:  https://issuetracker.google.com/issues/122098785?pli=1
- http://dontkillmyapp.com/

**Comment by GurjeetLamba** [comment]
Same issue happening in IOS , What would you say for IOS ?

**Comment by christocracy** [comment]
Read the api docs Config.heartbeatInterrval.  Everything about iOS is explained there.

Are you reading the api docs?

**Comment by christocracy** [comment]
iOS preventSuspend **does not work when terminated**.  Die to the nature of the OS,

**Comment by GurjeetLamba** [comment]
So IOS also does not support heartBeat Interval when app terminated ?

**Comment by christocracy** [comment]
Read the api docs Config.stopOnTerminate

**Comment by christocracy** [comment]
> So IOS also does not support heartBeat Interval when app terminated ?

**no**

**Comment by christocracy** [comment]
> So IOS also does not support heartBeat Interval when app terminated ?

That’s exactly what I said:  “*iOS preventSuspend does not work when terminated. Die to the nature of the OS,*”

**Comment by GurjeetLamba** [comment]
> > So IOS also does not support heartBeat Interval when app terminated ?
> 
> That’s exactly what I said: “_iOS preventSuspend does not work when terminated. Die to the nature of the OS,_”

Can you give me some valid reason behind this or from where we can confirm that (If we have to explain someone) IOS does not support background tracking when app terminated and stationary ?

**Comment by christocracy** [comment]
Read the api docs Config.stopOnTerminate **to understand why iOS preventSuspend doesn’t work when the app is terminated**.

**Comment by GurjeetLamba** [comment]
but I moving State right , In stationary  state  we have no possible solution for this ?

**Comment by christocracy** [comment]
On mobile, you don’t always get to do what you want.  You don’t own the user’s device and particularly, their battery.

You don’t get to monitor the user’s position exactly every time you want.  There are limits.

**Comment by christocracy** [comment]
I suggest you research sending server push requests to device when location is required.

that is beyond the scope of the plug-in.
