### ISSUE TITLE
Could do with testing example

### ISSUE THREAD

**Issue by gilescope** [transistorsoft/react-native-background-geolocation#175]
npm test will run some jest tests but these fail with RNBackgroundGeolocation being null.

It would be great to have an example of how to mock the bits out we need so that we can write some tests.

(Love the install guide by the way - perfect!)

**Comment by christocracy** [comment]
I don't personally spend a lot of time within RN.  While I've seen this word "jest" while upgrading to latest version of RN, I have no idea how it operates.

The RN facade portion is completely open and available for you to mess around with.
