### ISSUE TITLE
Question: What is the best way to achieve updates every X minutes on Android even if app is in the background?

### ISSUE THREAD

**Issue by ivosabev** [transistorsoft/react-native-background-geolocation#1751]
I am trying to get one location update every X minutes from the plugin on Android even if the app is in the background, but I am not sure what is the best configuration. Should I use Heartbeat or is it achievable only via the ready() configuration?

**Comment by christocracy** [comment]
This plugin is not designed to record location while in the *stationary* state.

For periodic location updates, implement [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch) (already installed as a dependency) and call `BackgroundGeolocation.getCurrentPosition(options)` in your `BackgroundFetch` callback.

**Comment by gigby** [comment]
@christocracy 
Could you transform this important message to 1 line in index page?
It's very important thing to know before you start using it.

**Comment by christocracy** [comment]
> Could you transform this important message to 1 line in index page?

I don't understand.  What message?

**Comment by gigby** [comment]
@christocracy I'm sorry I forgot to mention it. It's very important. I migrated to your plugin from old and abandoned https://www.npmjs.com/package/@mauron85/react-native-background-geolocation and expected that you support periodical updates in stationary state (as it did my old plugin).
I paid for license, adjusted code, and it appeared that "heartbeat" event actually not firing correctly on Android (for iOS it's working as expected). I start looking for solution and found your comment about the main purpose of this plugin. It was very disappointing for me. I spent a lot of time to learn plugin's API and did read this comment about "not designed".
Could you be more clear and put this important sentence in a very visible place to allow people not spending time.
By the way, you have a super great docs and product as well.

> This plugin is not designed to record location while in the _stationary_ state.

**Comment by christocracy** [comment]
Use background-fetch for periodic location updates while device is stationary.  It's already included as a dependency.

**Comment by christocracy** [comment]
Read the wiki "Philosophy of Operation".

**Comment by gigby** [comment]
> stopTimeout

Thank you!
I'll try to use options you suggested.
And I'll check config from my old mauron85 plugin. It seems that it was configured correctly.
