### ISSUE TITLE
Disable Android Foreground Service

### ISSUE THREAD

**Issue by wmonecke** [transistorsoft/react-native-background-geolocation#1752]
Hey!

Awesome library -  we are on the edge of buying a license, but one thing is stopping us from it.

On Android, you get a sticky notification when the device starts moving (gyroscope detects movement) to get the users location.

Is there any way this can be avoided (i.e. the app never has and Android Foreground Service)?

**Comment by christocracy** [comment]
Foreground services, which require a persistent notification, are crucial to this plugin's implementation.

No, they cannot be disabled.

**Comment by wmonecke** [comment]
Ok thank you!
