### ISSUE TITLE
Location tracking stops after a few minutes when the app is in background

### ISSUE THREAD

**Issue by kush-mish** [transistorsoft/react-native-background-geolocation#1755]
## Your Environment
* Plugin version: ^18.1.0
* Platform: Android
* OS version: Android 10 and 13
* Device manufacturer / model: Xiaomi Redmi Note 7 pro and Samsung A22
* React Native version: 11.2.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 10,
heartbeatInterval: -1,
notification: {
  title: "ABC",
  text: "xyz"
},
enableHeadless: true,
stopOnTerminate: false,
startOnBoot: true,
stopTimeout: 1,
isMoving: true,
```

## Expected Behavior
The foreground process should not end automatically as it is enabled by default and I'm defining the notification in the config.

## Actual Behavior
It tracks and updates the location fine for 10-15 minutes and then stops. The notification for the foreground service also disappears, until the app is reopened and the components are loaded. And this happens when the app is not terminated.

## Context
I'm building an app that continuously tracks the device's location for up to 18 hours. The way I’m implementing it is, after calling ready() and start() I set up the onLocation listener, where I’m saving the location manually to my database. I have also defined a headless task in the index.js file that saves the location to the database on ‘location’ event. I detach the onLocation listener on the ’terminate’ event.

**Comment by christocracy** [comment]
Also explained in the “Philosophy of Operation” is the idea of manually calling .changePace to toggle the plug-in’s tracking state.

also explained there is the Config.stopTimeout, which you’re free to adjust higher as desired.

the plug-in is not `.stop()`-ing, it’s changing state between stationary/moving.

once you call .start(), the plug-in is enabled forever and will track the device everywhere it moves until you call .stop().

**Comment by kush-mish** [comment]
The plugin changing to the stationary state is fine when the device is still.
But there have been cases when it doesn't start tracking even after the device exits this 200-meter geofence.
You can see the straight lines in the attached image:
<img width="1042" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/36705914/10c94568-63b1-4710-af21-0b42b0383d33">

**Comment by christocracy** [comment]
For device-specific issues, see https://dontkillmyapp.com

**Comment by kush-mish** [comment]
When I increased the value of `stopTimeout,`, it keeps running(it is running and it has been running longer than before).
So I don't think it is the OS that is killing the task?
Is there a way, when I can keep invoking the listener occasionally when the device is stationary to keep the whole process alive(though I'm not sure that the foreground task is directly linked with it)?

**Comment by christocracy** [comment]
Are you observing the plug-in logs?  See wiki “Debugging” to learn how to observe the logs.

Also see Config.debug to learn how to enable the plug-in debug sound FX.
