### ISSUE TITLE
Change Permission Text 

### ISSUE THREAD

**Issue by riyasolanki** [transistorsoft/react-native-background-geolocation#1758]
![f1ef89d2-7a8e-4ca6-b409-acf17eae96a6](https://github.com/transistorsoft/react-native-background-geolocation/assets/21073880/b5f2f2c3-3343-42a7-a5ae-a8db303410f4)

How to change permission description ?

**Comment by christocracy** [comment]
See api docs Config.backgroundPermissionRationale
