### ISSUE TITLE
Avoid appearing iOS permission dialog periodically (several times per week)

### ISSUE THREAD

**Issue by aksonov** [transistorsoft/react-native-background-geolocation#177]
Our app requires constant update of user location at the background (only if user is moving, of course). Other apps from App Store (like mapstr, relay, zenly) doesn't show such permission alert periodically (maybe once or twice per month). Is there any way to decrease number of popups?

<img width="363" alt="screen shot 2016-12-01 at 17 27 57" src="https://cloud.githubusercontent.com/assets/1321329/20802370/208d30e0-b7ec-11e6-86ef-29eaa059d4cf.png">

Version 1.4.3
iOS 9

**Comment by christocracy** [comment]
When the device is in **stationary** mode, the plugin has created a geofence around the last known position.  When the device breaks out of this geofence, the plugin changes state to **moving** mode and begins tracking the device.

It's this monitoring of the stationary-geofence which causes this.

No, there's no way to "decrease" the frequency of this, other executing `#stop`.

**Comment by aksonov** [comment]
Strange, why mentioned apps don't have such frequent popups...

**Comment by christocracy** [comment]
Not strange unless those mentioned apps are using my plugin.

**Comment by christocracy** [comment]
Do those apps use "stationary geofence transitions" to determine when the device is moving?

**Comment by aksonov** [comment]
I don't know. All i know that they _tracks_ my location in background in effective way (no big battery consume) and without such popups...

**Comment by christocracy** [comment]
There's no secret, magic trick of the iOS [`CLLocationManager`](https://developer.apple.com/reference/corelocation/cllocationmanager) API that I'm not aware of after 3+ years working with it.

If you want to continuously monitor the location of the device in an aggressive manner with the ability to `startOnBoot: true`, `stopOnTerminate: false`, the only way to that is via geofence-monitoring.

This plugin was designed for tracking first-responders in disaster zones.  Mission-critical stuff.  This use-case tends to applicable to apps such as Fleet-tracking (eg: taxi apps), Fitness apps.

Your "Mapstr" isn't even the same type of app that this plugin was designed for.  It doesn't even request `Always` permission, so *of course* you won't see a warning popup about that.

Apples to Oranges.

**Comment by christocracy** [comment]
Mapstr requests `WhenInUse` permission.
![](https://www.dropbox.com/s/t25dxev1ig0rctt/Screenshot%202016-12-01%2012.49.15.png?dl=1)

**Comment by aksonov** [comment]
@christocracy thank you for the information.

**Comment by christocracy** [comment]
If you want to use `WhenInUse` permission like Mapstr, go ahead and configure this plugin with [`locationAuthorizationRequest: 'WhenInUse'`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#param-string-locationauthorizationrequest-always
) and say good-bye to tracking while your app is in the background.

**Comment by aksonov** [comment]
What about life360? It always tracks location.

Pavel.

**Comment by christocracy** [comment]
It's painfully naīve if you to think you can use some consumer-based/social app that will aggressively track you 24/7 with a distanceFilter and desiredAccuracy: 0 (i.e fleet-tracking / navigation quality).  Impossible.

That cute Life360 app is using significant-changes and you can too with this plugin.

useSignificantChangesOnly: true

**Comment by aksonov** [comment]
Looks like it is what i need, thanks!
