### ISSUE TITLE
Tracking difficulties by devices

### ISSUE THREAD

**Issue by gerald-devlab** [transistorsoft/react-native-background-geolocation#1771]
## Your Environment
* Plugin version: 4.11.3
* Platform: Android
* OS version: 
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.70.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  desiredOdometerAccuracy: 10,
  stopTimeout: 30,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
  stopOnTerminate: true,
  startOnBoot: false,
  preventSuspend: true,
  heartbeatInterval: 60,
  locationAuthorizationRequest: "Always",
  backgroundPermissionRationale: {
    title: "...",
    message: "...",
    positiveAction: "...",
    negativeAction: "...",
  },
  locationAuthorizationAlert: {
    titleWhenNotEnabled: "...",
    titleWhenOff: "...",
    instructions: "...",
    cancelButton: "...",
    settingsButton: "...",
  },
});

```

## Expected Behavior
The GPS should be tracking and returning coordinates every 10 meters or so.
This is the expected behavior ( from "user1" that runs with his friend "user2" ):

![received_283512524369200](https://github.com/transistorsoft/react-native-background-geolocation/assets/127143989/866cb326-34cb-4189-a394-93faa7b717c3)

## Actual Behavior
Most of the time for the majority of the users it runs almost perfectly, but for the others the GPS seems to be taking far too long between each coordinates. Sometimes even kilometers.
This is the actual behavior from "user2"

![received_305502372031790](https://github.com/transistorsoft/react-native-background-geolocation/assets/127143989/a5b78101-8258-4c05-bfde-436b40b50802)

## Context

We paid this plugin to use in our app for sports activities tracking. ( Walk / Run / Bike etc ... )
I have a lot of feeback from my users saying that their GPS isn't tracking them accurately.
The code and configurations are the same for all devices but there seems to be inconsistencies
On most devices it runs great but on some other devices the GPS seems to be returning locations once in a while or not at all.
Do you have any idea how we could improve the experience for our users? Any configuratins we missed?

**Comment by christocracy** [comment]
The problem is almost certainly with some particular device.  You should expect periodic poor results and filter them out yourself.  See api docs Location.Coords.accuracy.

**Comment by christocracy** [comment]
No there’s no way to improve accuracy other than Config.desiredAccuracy.

**Comment by gerald-devlab** [comment]
> 

Thanks for your quick response, what's really bothering me is the lack of coordinates returned for a long period of time, more than the accuracy itself. Any idea?

**Comment by christocracy** [comment]
For particular Android devices, see https://dontkillmyapp.com

**Comment by gerald-devlab** [comment]
Okay, that was what I was afraid of. Thank you for your assistance!
