### ISSUE TITLE
OnLocation is getting called thousands of times and crashes the app

### ISSUE THREAD

**Issue by lniepolski** [transistorsoft/react-native-background-geolocation#1772]
## Your Environment
* Plugin version: 4.11.1
* Platform: iOS
* OS version: A lot. I've seen everything between iOS 15.6.1 to 16.6
* Device manufacturer / model: Mainly iPads
* React Native version (`react-native -v`): 0.71.8
* Plugin config
```
  BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50,
        stopTimeout: 60 * 10,
        debug: false,
        stopOnTerminate: true
      });
```

## Expected Behavior
I expect the callback `BackgroundGeolocation.onLocation` to be called every 50 meters.

## Actual Behavior
Based on our internal logs it sometimes gets executed thousands of times in a matter of seconds. From what've seen, it seems to be mainly happening on iPads.

## Steps to Reproduce
Haven't been able to reproduce it:

My code:

```
  useEffect(() => {
    let onLocation;
    if (trackActivity) {
      onLocation = BackgroundGeolocation.onLocation(location => {
        ...
      });

      BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50,
        stopTimeout: 60 * 10,
        debug: false,
        stopOnTerminate: true
      });
    }
    return () => {
      if (onLocation) onLocation.remove();
    };
  }, []);
```

**Comment by lniepolski** [comment]
`
  useEffect(() => {
    let onLocation;
    if (trackActivity) {
      onLocation = BackgroundGeolocation.onLocation(location => {
        ...
      });

      BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50,
        stopTimeout: 60 * 10,
        debug: false,
        stopOnTerminate: true
      });
    }
    return () => {
      if (onLocation) onLocation.remove();
    };
  }, []);

  useEffect(() => {
    if (trackActivity) {
      if (isActive) {
        BackgroundGeolocation.start();
      } else {
        BackgroundGeolocation.stop();
      }
    }
  }, [isActive]);`

**Comment by christocracy** [comment]
I would check your logic on that `isActive` property.  You are likely doing something unexpected there under some conditions.

**Comment by christocracy** [comment]
Btw, it’s perfectly safe to add event-listeners and call .ready under any circumstances.  You don’t need that logic `if (trackActivity) {`.

calling .ready does not start-tracking and adding event-listeners does nothing more than add a callback function to a List.

**Comment by lniepolski** [comment]
Based on our logs, isActive is changed only once.

Also, what is weird, is that it seems to be happening only on iPads.

![Screenshot 2023-08-08 at 11 14 12](https://github.com/transistorsoft/react-native-background-geolocation/assets/61523256/ebf62ca7-5afc-423c-b968-a86e7894eb87)

**Comment by christocracy** [comment]
The plugin's event-listeners are nothing more than an `Array` of callbacks `function`s  that get iterated when an event occurs.  They have no effect on the performance of the plugin, just as disconnecting the speakers of your stereo system doesn't actually stop the music from playing.

What does your question here have to do with the title of this issue "*OnLocation is getting called thousands of times and crashes the app*"?

**Comment by haiderTkxel** [comment]
> The plugin's event-listeners are nothing more than an `Array` of callbacks `function`s that get iterated when an event occurs. They have no effect on the performance of the plugin, just as disconnecting the speakers of your stereo system doesn't actually stop the music from playing.
> 
> What does your question here have to do with the title of this issue "_OnLocation is getting called thousands of times and crashes the app_"?


If I add the listener and don't remove it then there is a chance of memory leak?
Every time app opens the listener added or overrides the previous listener?

Suppose, request http fails and app was killed by user before request fails then i think this listener should work in the background if stopOnTerminate: false.

If I remove listener on app killed then listener would not be called if request fails.

**Comment by christocracy** [comment]
Do you know that each event-listener method returns a `subscription` object which contains a single method `.remove()`?

See API docs [onLocation](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#onlocation), for example.

```javascript
const subscription = BackgroundGeolocation.onLocation((location) => {
  console.log("[onLocation] success: ", location);
}, (error) => {
  console.log("[onLocation] ERROR: ", error);
});
```

```javascript
React.useEffect(() => {
  let onLocationListener = BackgroundGeolocation.onLocation((location) => {
    console.log('[onLocation]', location);
  });
  
  return () => {
    // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
    // during development live-reload.  Without this, event-listeners will accumulate with
    // each refresh during live-reload.
    onLocationListener.remove();
  }
}, []);
```

**Comment by haiderTkxel** [comment]
@christocracy 
If I remove listener on app killed then listener would not be called if request fails.
Right?

**Comment by christocracy** [comment]
You don't need to worry about listeners on a "killed" app since your app will have been removed from memory.
