### ISSUE TITLE
No task registered for key BackgroundGeolocation, "BackgroundGeolocation.onLocation" not fire

### ISSUE THREAD

**Issue by TranNghiaHiep** [transistorsoft/react-native-background-geolocation#1780]
## Your Environment
* Plugin version: 4.9.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: SM-G885F
* React Native version (`react-native -v`):  0.67.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
export const bgGeoLocationConfig = {
    preventSuspend: true,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    stopOnTerminate: false,
    forceRequestLocation: true,
    stopTimeout: 0,
    enableHeadless: true,
    distanceFilter: 10,
    isMoving: true,
    heartbeatInterval: 1,
    startOnBoot: true,
    disableLocationAuthorizationAlert: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
}

```

## Expected Behavior

App runs android device and sometime an event "onLocation" isn't fired
On console, I see [WARN] "No task registered for key BackgroundGeolocation"
## Actual Behavior

An event "onLocation" is fired
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
[com.waverleysoft.miguards-2023-08-07.0_backgroundgeolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/12318582/com.waverleysoft.miguards-2023-08-07.0_backgroundgeolocation.log)
```
[com.waverleysoft.miguards-2023-08-07.0_backgroundgeolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/12318582/com.waverleysoft.miguards-2023-08-07.0_backgroundgeolocation.log)
</details>

**Comment by christocracy** [comment]
Have you read the api docs for Config.enableHeadless?

**Comment by TranNghiaHiep** [comment]
> 

Thanks, I missing "BackgroundGeolocation.registerHeadlessTask".
If no registerHeadlessTask then event onLocation have fire?

**Comment by christocracy** [comment]
There is no onLocation when Android app is terminated.  Your RN JavaScript App instance no longer exists.
