### ISSUE TITLE
[Question] Location Provider 

### ISSUE THREAD

**Issue by judeProground** [transistorsoft/react-native-background-geolocation#1782]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
I'm sorry, but my question is not related to errors in the library or its usage.
```

## Expected Behavior
I am a developer working on a speed tracking app using this library. I have some questions regarding the app's features, so I'd like to inquire:

1. In "@react-native-community/geolocation," I see that for the location provider option, you can choose between 'playServices' and 'android.' Do you have any plans to support a feature that allows such selection? Some users prefer the speed provided by the simple Android Location API over the speed offered by Google's Fused Location Provider, as it is more stable and accurate in certain cases. Therefore, I would like to provide users with the ability to choose a location provider, similar to what the GPS Status & Toolbox app on the Play Store offers.

2. Or, if a user uses the app with the [Android Settings -> Location -> Location Services -> Google Location Accuracy] turned off, would there be any difference in the information obtained using the GPS provider from the Location API?

3. I apologize for mentioning another app, but in GPS Status & Toolbox, they integrate a third-party developed DDK nav with DDK positioning to provide DDK functionality as a location provider. I don't know much about it myself, but I believe various advanced features are provided for more sophisticated location information. I thought it would be great if these features could also be incorporated into your library. 

Thank you.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Do you have any plans to support a feature that allows such selection? 

No.  I've been using `FusedLocationProvider` for over 8 years with this plugin.  I see no need to use the standard *Location* api.

>Some users prefer the speed provided by the simple Android Location API over the speed offered by Google's Fused Location Provider

There is nothing magical about the play-services `FusedLocationProvider` API.  It merely simplifies fetching locations by automatically selecting the best possible location from all 3 available providers on the device (*Cellular*, *Network* and *GPS*).  When one doesn't use `play-services` `FusedLocationProvider` API, you merely do all that switching yourself, which is a pain-in-the-ass:
- Does the `

When outdoors (GPS only works outdoors), the location provided by `FusedLocationProvider` ultimately come from the standard Location API, whose data is ultimately provided by the GPS chip on the device.  

I see nothing wrong with the accuracy of locations I receive.  Here's the few days worth of bike-riding on four of my Android test devices:

### PIxel 6 @ 14

<img width="1013" alt="pixel6" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/eb141109-5100-4508-a972-babe10195d3b">

### Pixel 3a @ 12

<img width="1051" alt="pixel3a" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/8cee83a2-946f-4dde-a0c3-24b59d4550de">

### Samsung Galaxy S20 @ 13

<img width="1006" alt="samsung-s20" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/520bb301-f2df-4108-b984-78bc4b336f2d">

### OnePlus A5010 @ 9

<img width="1049" alt="OnePlus" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/effd0b10-adbf-4512-8b0d-eceafe3e1d39">

As for accuracy, I see 4-8 meters from GPS typically.

<img width="670" alt="Screenshot 2023-08-14 at 9 52 14 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/d4828c3f-2dfc-490d-8f29-b207f1ca6e3c">

>Or, if a user uses the app with the [Android Settings -> Location -> Location Services -> Google Location Accuracy] turned off, would there be any difference in the information obtained using the GPS provider from the Location API?

I have no idea.

This "DDK" company (I've never heard of it) seems to deal with the *Iridium Satellite Network*, which isn't going to be free.  You'd have to pay for that service.  

<img width="1090" alt="Screenshot 2023-08-14 at 10 15 32 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/8ee71ea7-d616-4b60-a367-9b41dbd2d59b">

**Comment by judeProground** [comment]
Thank you so much for your response :)
