### ISSUE TITLE
OnLocation is not called when app killed and crashes the app.

### ISSUE THREAD

**Issue by skvaghasiya402** [transistorsoft/react-native-background-geolocation#1783]
## Your Environment
* Plugin version: 4.12.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: CPH2381(OnePluse)
* React Native version (`react-native -v`): 0.63.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
                    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                    distanceFilter: 50,
                    stopTimeout: 5,
                    debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                    stopOnTerminate: false,
                    startOnBoot: true,
                    batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                    autoSync: false, // <-- [Default: true] Set true to sync each location to server as it arrives.
                    disableMotionActivityUpdates: true,
                    notification: {
                        title: "Location Tracking is ON",
                        text: "You\'re Punched In!",
                        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH
                    }
                });
```

## Expected Behavior

When app goes from background to foreground works properly
## Actual Behavior

App crashes on splash after some time is background, and OnLocation is not called when app killed.
## Steps to Reproduce

1. start the service 
2. Terminate app
3. Then OnLocation method not called
4. Open again the app, some time the app will crash

## Context

My code in componentDidMount:

import BackgroundGeolocation from "react-native-background-geolocation";

BackgroundGeolocation.onLocation(async (locations) => {
            console.log('[onLocation]', locations);
}, (error) => {
            console.log(error);
});
## Debug logs

<details><summary>Logs</summary>
![Screenshot 2023-08-07 at 10 30 26 PM](https://github.com/transistorsoft/react-native-background-geolocation/assets/30230882/a272551c-005a-47e7-b387-02cece4b0093)

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
FATAL EXCEPTION: pool-13-thread-1
java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger

at com.transistorsoft.locationmanager.logger.TSLog.getRootLogger(Unknown Source:11)
at com.transistorsoft.locationmanager.logger.TSLog.access$000(Unknown Source:0)
at com.transistorsoft.locationmanager.logger.TSLog$a.run(Unknown Source:0)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:920)
```

</details>

**Comment by christocracy** [comment]
Like I said:  "you might find the solution [by searching](https://github.com/transistorsoft/react-native-background-geolocation/issues?q=java.lang.ClassCastException%3A+org.slf4j.helpers.SubstituteLogger+cannot+be+cast+to+ch.qos.logback.classic.Logger)".

Duplicate #1699

**Comment by christocracy** [comment]
> but still this method is not getting called when app killed

This has nothing to do with your original issue.  It is also expected.  You just need to learn about [*Android Headless Mode*](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode) Also see API docs `Config.enableHeadless`.  

Ignore this.  It is expected and harmless.
```
HMSSDK_HMS...ageManager- resolveInfoList is null or empty
HMSSDK_HMS...ageManager- PackagePriorityInfo list is null
HMSSDK_HMS...ageManager - Failed to find HMS apk
```

**Comment by christocracy** [comment]
This **closed issue** is titled “* java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger*”.

issues are not personal support threads for all your questions.
