### ISSUE TITLE
App Crashes on real device when switching between mock location and test app using the SDK

### ISSUE THREAD

**Issue by GuptaAman08** [transistorsoft/react-native-background-geolocation#1785]
## Your Environment
* Plugin version: 4.10.0
* Platform: Android
* OS version: Android 11, Laptop: MacOS ventura 13.3.1
* Device manufacturer / model: Xiaomi 11i
* React Native version (`react-native -v`): 0.71.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      distanceFilter: 50,
      stopOnTerminate: true,
      startOnBoot: false,
      stopTimeout: 20,
      enableHeadless: false,
      heartbeatInterval: 60,
      locationAuthorizationRequest: 'Always',
      disableLocationAuthorizationAlert: false,
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Location services is not enabled',
        titleWhenOff: 'Location services is off',
        instructions:
          "You must enable 'Always' in Location services for tracking to function properly",
        cancelButton: 'Cancel',
        settingsButton: 'Settings',
      },
      backgroundPermissionRationale: {
        title: "Allow access to this device's location in the background?",
        message: "Please enable 'Allow all the time permission",
        positiveAction: 'Change to Allow all the time',
      },
      extras: {},
      url: <server_url>,
      authorization: <function_that_returns_auth_token>,
      autoSync: true
}
```

## Expected Behavior
React Native App using the react-native-background-geolocation should not crash, running on a real mobile device, when switching between different apps, or when coming to the home screen no matter whichever mock location app we use (try switching more than 2-3 times). 

## Actual Behavior
Sample react native app using the react-native-background-geolocation crashes on a mobile device when switching between different apps or when coming to the home screen (try switching more than 2-3 times). When using [this](https://play.google.com/store/apps/details?id=ru.gavrikov.mocklocations&hl=en_IN&gl=US&pli=1) mock location app.

## Steps to Reproduce

1. Initialise the plugin
2. Call the SDK Start Tracking method.
3. Switch between apps or come to home screen

## Context
Location tracking on real device using the mock location app

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
```

</details>

**Comment by christocracy** [comment]
> App Crashes

Where’s your stacktrace?  There’s always a stacktrace in `$ adb logcat`

**Comment by GuptaAman08** [comment]
Hi @christocracy, have mailed you the stack trace....since it exceeds the character limit over here.

**Comment by GuptaAman08** [comment]
Also, i have cloned and ran you sample react-native app using the latest SDK version, there also I am able to replicate this.

**Comment by christocracy** [comment]
>since it exceeds the character limit over here.

I don't need an entire `logcat` stream.  Just find the exception and post the stacktrace.

**Comment by GuptaAman08** [comment]
Ok, will try to search through it. But, in the meantime, can you try once replicating the same at your end? Since, am sure this was replicating with your [demo app](https://github.com/transistorsoft/rn-background-geolocation-demo) as well. Just use the same mock location app as mentioned in the issue above.

**Comment by christocracy** [comment]
This is the only exception matching `com.transistorsoft` and it references the entire Demo app.  There is no error coming from the actual `background-geolocation` SDK.

It is likely a phenomenon caused by the mock location app you're using.  I use an app called `Lockito`.


```
08-20 20:58:07.901  2460  2594 W System.err: android.content.pm.PackageManager$NameNotFoundException: com.transistorsoft.backgroundgeolocation.react
08-20 20:58:07.901  2460  2594 W System.err: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:254)
08-20 20:58:07.901  2460  2594 W System.err: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:214)
08-20 20:58:07.901  2460  2594 W System.err: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:208)
08-20 20:58:07.901  2460  2594 W System.err: 	at android.util.MiuiMultiWindowAdapter.calFreeformSuggestionList(MiuiMultiWindowAdapter.java:610)
08-20 20:58:07.901  2460  2594 W System.err: 	at android.util.MiuiMultiWindowUtils.getFreeformSuggestionList(MiuiMultiWindowUtils.java:2996)
08-20 20:58:07.901  2460  2594 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-20 20:58:07.901  2460  2594 W System.err: 	at com.miui.launcher.utils.ReflectUtils.invokeObject(ReflectUtils.java:78)
08-20 20:58:07.901  2460  2594 W System.err: 	at com.miui.launcher.utils.ReflectUtils.callStaticMethod(ReflectUtils.java:38)
08-20 20:58:07.901  2460  2594 W System.err: 	at com.miui.home.launcher.RecentsAndFSGestureUtils.getSuggestionList(RecentsAndFSGestureUtils.java:276)
08-20 20:58:07.901  2460  2594 W System.err: 	at com.miui.home.recents.views.RecentsContainer.lambda$updateSuggestionList$2$RecentsContainer(RecentsContainer.java:1830)
08-20 20:58:07.901  2460  2594 W System.err: 	at com.miui.home.recents.views.-$$Lambda$RecentsContainer$Vdn0d0-ulpSasIE5O7asKF60YMM.apply(Unknown Source:4)
08-20 20:58:07.901  2460  2594 W System.err: 	at com.miui.home.library.utils.AsyncTaskExecutorHelper$3.doInBackground(AsyncTaskExecutorHelper.java:129)
08-20 20:58:07.901  2460  2594 W System.err: 	at com.miui.home.library.utils.AsyncTaskExecutorHelper$3.doInBackground(AsyncTaskExecutorHelper.java:124)
08-20 20:58:07.901  2460  2594 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-20 20:58:07.901  2460  2594 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-20 20:58:07.901  2460  2594 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-20 20:58:07.901  2460  2594 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-20 20:58:07.901  2460  2594 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by GuptaAman08** [comment]
Weird. Since, earlier (like a couple of months before) it used to work fine when using the same [mock location app](https://play.google.com/store/apps/details?id=ru.gavrikov.mocklocations&hl=en_IN&gl=US&pli=1)

**Comment by christocracy** [comment]
>- Initialise the plugin
>- Call the SDK Start Tracking method.
>- Switch between apps or come to home screen

I do not have a problem performing your reproduction steps while mocking location with [Lockito](https://lockito-app.com)

**Comment by christocracy** [comment]
This issue is is unrelated to the `background-geolocation` SDK.  If anything, it's related strictly to the [demo app](https://github.com/transistorsoft/rn-background-geolocation-demo)

**Comment by GuptaAman08** [comment]
Thanks. 
Correct, this is happening only in the mock location app I am using ([link](https://play.google.com/store/apps/details?id=ru.gavrikov.mocklocations&hl=en_IN&gl=US&pli=1)). Still, @christocracy  by any chance looking at the stack trace do you feel any problem with the Background Geolocation SDK ??

**Comment by christocracy** [comment]
> do you feel any problem with the Background Geolocation SDK ??

I think I was pretty clear above that it isn’t.  Are you not reading my replies??

- “*This issue is is unrelated to the background-geolocation SDK. If anything, it's related strictly to the [demo app](https://github.com/transistorsoft/rn-background-geolocation-demo)*”
- “* There is no error coming from the actual background-geolocation SDK.*”
