### ISSUE TITLE
How to setup a bearer token instead of sending the auth through a body parameter

### ISSUE THREAD

**Issue by andreencar** [transistorsoft/react-native-background-geolocation#179]
* Plugin version: 1.60
* Platform: iOS
* OS version: 10.1
* Device manufacturer / model: iPhone 6
* React Native version (`react-native -v`): 1.2.0
* Plugin config       
params: {               // <-- Optional HTTP params
        "auth_token": ApplicationStateService.applicationState.authentication.token
      }

Is it possible to pass the authentication token through a bearer schema, meaning set headers on the outgoing post?

Thank you very much.

**Comment by christocracy** [comment]
You can set any arbitrary [`headers`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#param-object-headers) you wish on the module's HTTP requests.

**Comment by andreencar** [comment]
My bad, thank you very much.

Amazing plugin ;)
