### ISSUE TITLE
Feature Request: Intercept and Modify Location Events in BackgroundGeolocation

### ISSUE THREAD

**Issue by Perronef5** [transistorsoft/react-native-background-geolocation#1790]
# Feature Request: Intercept and Modify Location Events in BackgroundGeolocation

## Your Environment
- **Plugin version:** `react-native-background-geolocation@4.12.1`
- **Platform:** iOS and Android
- **OS version:** All available versions
- **Device manufacturer / model:** All
- **React Native version:** 0.71.10
- **Plugin Config:**:
``` javascript
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 15,
  stopTimeout: 5,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  stopOnTerminate: false,
  startOnBoot: true,
  enableHeadless: true,
}
```

## Expected Behavior
We expect that the BackgroundGeolocation plugin will provide the capability to intercept and modify Location events before the location event is sent. This will allow us to include critical metadata for each location before sending the request.

## Actual Behavior
Currently, there is no way to intercept and modify location events before the location event is sent by the BackgroundGeolocation plugin.

## Steps to Reproduce
This is a feature request and does not involve reproduction steps.

## Context
We are currently using this in a production app using React Native (version 0.71.10) and utilizing the BackgroundGeolocation plugin (version: react-native-background-geolocation@4.12.1) on both iOS and Android platforms. The plugin serves our needs well, but we require the ability to intercept and modify location events before the location event is sent. This is crucial for us to include critical metadata for each specific location event.

## Debug logs
No debug logs are provided as this is a feature request.

## Additional Information:
We appreciate the effort put into developing the BackgroundGeolocation plugin for React Native. It's been a great tool for our project. However, we've encountered a significant requirement for our application – the ability to intercept and modify location events before the location event is dispatched.

Our team is willing to contribute to this feature's implementation. We understand that currently, only the bindings are open source, but we are eager to collaborate to expedite this process. Given the critical nature of this requirement for our application, an early implementation would be highly beneficial.

For instance, we are looking to achieve something similar to the following code snippet in React Native:
``` javascript
BackgroundGeolocation.preLocation(location => {
  console.log("location", location);
  // modify location
  location.extras = {
  ...location.extras,
  specificLocationMetadata: 'Hi :D'
  }
  // return modified location event before sending to console
  return location
});
```

Thank you for considering our feature request. We believe that adding this capability to the BackgroundGeolocation plugin will greatly enhance its utility for many developers, including our team. We are ready to contribute and collaborate to make this happen.

**Comment by Perronef5** [comment]
@christocracy Your input would be highly appreciated here 🙂

**Comment by christocracy** [comment]
This is never going to be implemented with Javascript.  It would be *far* too complicated and error-prone to implement this two-way communication back-and-forth over the bridge before inserting a record into the database.

The plugin has undocumented hooks you can implement using `Obj-c` and `Java` in `AppDelegate.mm` and `MainActivity.java` respectively.

### iOS

📂 __`AppDelegate.mm`

```obj-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    .
    .
    .
    [TSLocationManager sharedInstance].beforeInsertBlock = ^(TSLocation *location) {
        NSLog(@"********** BEFORE INSERT: %@", location);
        CLLocation *location = tsLocation.location;  // <-- Native CLLocation instance for your convenience.
        // Return any NSDictionary instance or nil to cancel the insert.
        // 
        return [location toDictionary]; 
    };
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

### Android

📂 `MainApplication.java`

:warning: operate upon your Android app code within Android Studio, not within a dumb text-editor.  Android Studio will prompt you to add required imports, eg:

```java
import com.transistorsoft.locationmanager.adapter.BackgroundGeolocation;
import com.transistorsoft.locationmanager.adapter.callback.TSBeforeInsertBlock;
import com.transistorsoft.locationmanager.location.TSLocation;
```

```java
@Override
public void onCreate() {
  super.onCreate();
  
  BackgroundGeolocation.getInstance(getApplicationContext()).setBeforeInsertBlock(new TSBeforeInsertBlock() {
    @Override
    public JSONObject onBeforeInsert(TSLocation tsLocation) {
      Location location = tsLocation.getLocation();  // <-- Native Location instance for your convenience.
      try {
        JSONObject json = tsLocation.toJson();

        return json;
      } catch (JSONException e) {
        return null;
      }
    }
  });
}


```

**Comment by christocracy** [comment]
For iOS/Android returning `nil` / `null` from your block will **cancel** the database `INSERT`

**Comment by christocracy** [comment]
Let me know if you need help setting this up.
