### ISSUE TITLE
Android release build is extreme slow

### ISSUE THREAD

**Issue by jingp-ofload** [transistorsoft/react-native-background-geolocation#1794]
## Your Environment
* Plugin version: 4.13.2
* Platform: Android
* OS version: Linux
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.72.4

## Expected Behavior
./gradlew assembleRelease can be completed within 20-30 mins

## Actual Behavior
It would take 40 mins in average with 

```
Connect to developer.huawei.com:443 [developer.huawei.com/23.61.11.28, developer.huawei.com/23.61.11.31] failed: connect timed out
```

**Comment by jingp-ofload** [comment]
As an temporary option, I would downgrade to 4.11.3 without huawei supports. But I do need the fixes in 4.13.2 I believe. As a feature request, I would like to have option to not include huawei. Many thanks.

**Comment by christocracy** [comment]
It’s is not possible to not include the Huawei lib.  Those symbols are required merely to compile.  Huawei libs are not actually use on Play Services devices,

HMS support is not what’s making the build slow.  It happened when I upgraded RN last week. I’m investigating that.

**Comment by christocracy** [comment]
[installing ccache sped up the demo app release builds](https://reactnative.dev/docs/build-speed#:~:text=Build%20only%20one%20ABI%20during%20development%20(Android%2Donly)%E2%80%8B&text=This%20should%20reduce%20your%20native,to%20the%20run%2Dandroid%20command.) from 15m down to 7m (still too slow).

release builds with Cordova, Capacitor and Flutter take about 1M, so the culprit is not the plug-in, it’s RN.

**Comment by christocracy** [comment]
*5m 9s*, actually.

```
> Task :app:installRelease
Installing APK 'app-release.apk' on 'Pixel 6 - 14' for :app:release
Installed on 1 device.

BUILD SUCCESSFUL in 5m 9s
```

### Flutter
```
$ ./gradlew bundleRelease
...
BUILD SUCCESSFUL in 1m 47s
```

### Capacitor
```
$ ./gradlew bundleRelease
...
BUILD SUCCESSFUL in 45s
```

### Cordova
```
$ ./gradlew bundleRelease
...
BUILD SUCCESSFUL in 3s
```

**Comment by jingp-ofload** [comment]
@christocracy thanks for your fast reaction. I guess it might caused by the CI/CD service couldn't access the maven repo easily or completely banned. I am able to build locally within around 15 mins. Thanks again.
