### ISSUE TITLE
BackgroundGeolocation crashes on Android

### ISSUE THREAD

**Issue by saulokirchmaier** [transistorsoft/react-native-background-geolocation#1795]
## Your Environment
* Plugin version: 4.12.1
* Platform: Android
* OS version: 10 emulated and real device
* Device manufacturer / model: Sansung / J8
* React Native version (`react-native -v`):  0.68.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        autoSync: true,
        distanceFilter: 0,
        stationaryRadius: 5,
        stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true,
        locationUpdateInterval: 36000,
        locationAuthorizationRequest: 'Always',
        url: urls.location,
        params: (e: any) => {
            return {
                lat: e.location.coords.latitude,
                lng: e.location.coords.longitude,
                source: 1,
                device_id: getUniqueId()
            }
        },
        backgroundPermissionRationale: {
            title: i18n.t('softphone.permission.geolocationBackground.title'),
            message: i18n.t('softphone.permission.geolocationBackground.message'),
            positiveAction: i18n.t('softphone.permission.geolocationBackground.positiveButtonTitle'),
        }
    }).then((state: any) => {
        if (!state.enabled) {
            BackgroundGeolocation.start();
        }
    }).catch((error) => {
      console.log("Error", error);
    });
```

## Expected Behavior
The plugin should send a the the location to our backend, to track user positions.

## Actual Behavior
When the function BackgroundGeolocation.start() runs the app just kill don't show any message, even when I try to put a try-catch statement.

## Steps to Reproduce

1.
2.
3.
4.

## Context
This app should send locations to our backend, and the user can se this locations after in the app.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
what is this?  You're providing a `function` to `params` which **REQUIRES AN `{}`**.

```javascript
params: (e: any) => {
            return {
                lat: e.location.coords.latitude,
                lng: e.location.coords.longitude,
                source: 1,
                device_id: getUniqueId()
            }
        },
```

**Comment by christocracy** [comment]
I don't think you understand how this works.

See Wik "Location Data Schema".  See HTTP Docs "HTTP Guide", linked throughout.

**Comment by christocracy** [comment]
When you have an exception, chances are **high** that others have seen it before and have already posted an issue about it.

You would have found your solution had you simply search "*IncompatibleClassChangeError*".

Duplicate #1710

**Comment by christocracy** [comment]
You **MUST** watch the logs with this plugin.
