### ISSUE TITLE
The IOS App Automatically Reopens Even After Being Closed When Background Location Services Are Turned On

### ISSUE THREAD

**Issue by n1developer-ubt** [transistorsoft/react-native-background-geolocation#1800]
The iOS application automatically reopens when we close the app, and this behavior is associated with the background location system enabled by the plugin.

## Your Environment
- Plugin version: 4.13.2
- Platform: iOS
- OS version: iOS 13
- Device manufacturer / model: iPhone 14
- React Native version (`react-native -v`): 0.66.4

```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
    // Geolocation Config
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    notification: {
        text: '',
        title: '',
    },
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,
    startOnBoot: true,
    url: locationUpdate,
    batchSync: true,
    autoSync: true,
    headers: {},
    maxRecordsToPersist: 10,
    params: {
        auth_token: token,
        uid: getDriverId(),
        testing: true,
    },
}).then(state => {
    if (state.enabled) {
        console.log('Location service started');
    } else {
        console.error('Unable to enable location.');
    }
});

BackgroundGeolocation.start();
BackgroundGeolocation.onHttp(r => {
    if (r.status !== 200) {
        console.error('Unable to update location. ', r);
    } else {
        console.log('Location updated', r);
    }
});
```

## Expected Behavior
The expected behavior is that when the app is closed and the background location system is turned on with the plugin, the app should not automatically reopen.

## Actual Behavior
The actual behavior is that the iOS application automatically opens when you close the app, and this behavior is associated with the background location system being enabled with the plugin.

## Steps to Reproduce

1. Install the app on an iOS device.
2. Configure the app with the provided plugin settings.
3. Close the app.
4. Observe that the app automatically reopens.

## Debug logs

<details><summary>No logs are to be provided, this happens in actual devices. </summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
No logs are to be provided, this happens in actual devices. 
```

https://github.com/transistorsoft/react-native-background-geolocation/assets/53445531/9bab60c2-5227-4e1c-8396-6df4dbeb2f6e

</details>

**Comment by n1developer-ubt** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/assets/53445531/b8ce259f-d39e-48d0-a496-6a88482a91d9

**Comment by christocracy** [comment]
>stopOnTerminate: false,

Of course it does.

**Comment by n1developer-ubt** [comment]
So there is no way we can track user location in background without app being opened?

**Comment by christocracy** [comment]
>So there is no way we can track user location in background without app being opened?

I have no idea what you're talking about.

When you terminate an iOS app with the plugin then move about 200 meters, the **OS AUTOMATICALLY RELAUNCHES** your app in the background, just as if launched from the home-screen and tracking resumes.  This is how iOS work.

**Comment by n1developer-ubt** [comment]
> > So there is no way we can track user location in background without app being opened?
> 
> I have no idea what you're talking about.
> 
> When you terminate an iOS app with this plugin enabled (ie: call `.start()`) then move about 200 meters, the **OS AUTOMATICALLY RELAUNCHES** your app in the background, just as if launched from the home-screen and tracking resumes. This is how iOS works.

Understood. Thankyou.

**Comment by christocracy** [comment]
Read the api docs Config.stopOnTerminate for far more information.
