### ISSUE TITLE
rnmapbox user location stops working when react-native-background-geolocation is added to the project

### ISSUE THREAD

**Issue by andrei-tofan** [transistorsoft/react-native-background-geolocation#1802]
## Your Environment
* Plugin version: 4.13.2
* Platform: Android
* OS version: 10
* Device manufacturer / model: Samsung Galaxy A10
* React Native version (`react-native -v`): 0.72.4
* Plugin config
I've just imported the library as in this example
```javascript 
import React from 'react';
import MapboxGL, {Camera, MapView} from '@rnmapbox/maps';
import BackgroundGeolocation from 'react-native-background-geolocation-android';
import {Platform} from 'react-native';

MapboxGL.setWellKnownTileServer(Platform.OS === 'ios' ? 'mapbox' : 'Mapbox');
MapboxGL.setAccessToken('your token');

const mapViewStyle = {
  flex: 1,
};

const App = () => {
  const mapRef = React.useRef<MapboxGL.MapView>(null);
  return (
    <>
      <MapView style={mapViewStyle} ref={mapRef}>
        <Camera
          zoomLevel={8}
          followUserLocation={true}
          followUserMode={'normal'}
          followZoomLevel={14}
        />
        <MapboxGL.UserLocation visible={true} showsUserHeadingIndicator />
      </MapView>
    </>
  );
};

```

## Expected Behavior
The user location should reflect the phone's location as when react-native-background-geolocation is not added to the project.

## Actual Behavior
Started the example app above on an Android phone and walked 300m after 300m the user location was still at the starting point.

## Steps to Reproduce
1. Start example app
2. Walk for a bit
3. Check if the user location is in your location

## Context
We are working on an app where we use rnmapbox to show a map to the user with the current location and react-native-background-geolocation to track the user's location while in the background.

Just to be clear the issue is not that `react-native-background-geolocation` is not reporting location updates.
The problem is when `react-native-background-geolocation` is added to the example app, mapbox stops getting location 
updates.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
2023-09-04 13:20:23.758 28564-28696/com.mymapproject E/TSLocationManager: ╔═════════════════════════════════════════════
    ║ LICENSE VALIDATION FAILURE: com.mymapproject
    ╠═════════════════════════════════════════════
    ╟─ Invalid license key: ***
    ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
    ╚═════════════════════════════════════════════
2023-09-04 13:20:23.960 28564-28727/com.mymapproject D/TSLocationManager: [c.t.l.logger.LoggerFacade$a a] PID: 2
```

</details>

**Comment by christocracy** [comment]
> Start example app

What example app??

**Comment by christocracy** [comment]
What do you expect me to do with this?  I don’t use MapBox.

if you want me to test something; point me to a GitHub repo to clone and run.

**Comment by christocracy** [comment]
```console
$ yarn install
$ npx react-native run-android
```

```console
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':rnmapbox_maps:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':rnmapbox_maps:debugCompileClasspath'.
   > Could not resolve com.mapbox.maps:android:10.15.0.
     Required by:
         project :rnmapbox_maps
      > Could not resolve com.mapbox.maps:android:10.15.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.15.0/android-10.15.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.15.0/android-10.15.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0.
     Required by:
         project :rnmapbox_maps
      > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom'. Received status code 401 from server: Unauthorized
```

**Comment by christocracy** [comment]
***`Received status code 401 from server: Unauthorized`***

**Comment by christocracy** [comment]
```
$ adb logcat

09-04 13:54:17.299 13328 13480 W ReactNativeJS: 'locationManager Error: ', [Error: uid 10105 does not have any of [android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_COARSE_LOCATION].]
09-04 13:54:17.700 13328 13480 E ReactNativeJS: 'Mapbox error', 'Map load failed: {type=style, message=Failed to load style: HTTP status code 401, begin=136965277137}', { level: 'error',
09-04 13:54:17.700 13328 13480 E ReactNativeJS:   tag: 'RCTMGLMapView',
09-04 13:54:17.700 13328 13480 E ReactNativeJS:   message: 'Map load failed: {type=style, message=Failed to load style: HTTP status code 401, begin=136965277137}' }
```

**Comment by christocracy** [comment]
>Regarding the first one I will have to ask one of the rnmapbox maintainers and get back to you

I'm not interested in talking to MapBox maintainers.  I hate MapBox.  I consider it spyware.

>'locationManager Error: ', [Error: uid 10105 does not have any of [android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_COARSE_LOCATION].

You're not going to get any location until your request location permission from the user.

Let me know when you have a functioning example that actually requests location permission.

**Comment by christocracy** [comment]
>If you start a Google Maps route, those locations are delivered "free of battery-blame" to your own app

Those "free" locations will only be delivered to active location-listeners.  ie: when the plugin is in the *moving* state (`State.isMoving == true`).  By calling `.changePace(true)`, for example.  If the plugin is in the *stationary* state (`State.isMoving == false`), locations from other providers *are not* delivered to the plugin.
