### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by andreshsingh** [transistorsoft/react-native-background-geolocation#1804]
## Your Environment
* Plugin version: 4.10.0
* Platform: android
* React Native version (`react-native -v`): 0.64.0

When trying to upgrade the package from 4.10.0 to any of the latest verions including 4.10.1, i get the manifest merger failed error.

## Expected Behavior

should have created a release build

## Actual Behavior

got the manifest merger failed error

## Context

was trying to create a release app

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
* What went wrong:
Execution failed for task ':app:processDevReleaseMainManifest'.
> Manifest merger failed : Attribute service#com.transistorsoft.locationmanager.service.LocationRequestService@foregroundServiceType value=(location) from AndroidManifest.xml:32:95-135
        is also present at [com.transistorsoft:tslocationmanager:3.4.4] AndroidManifest.xml:58:13-87 value=(@integer/foregroundServiceTypeShortService).
        Suggestion: add 'tools:replace="android:foregroundServiceType"' to <service> element at AndroidManifest.xml:32:5-138 to override.
```

</details>

**Comment by christocracy** [comment]
>from AndroidManifest.xml:32:95-135

When you have an error referencing a specific line in your `AndroidManifest.xml`, don't you think it'd be helpful to actually post the referenced file?

Have you even had a look at the referenced `line 32`?

**Comment by andreshsingh** [comment]
> > from AndroidManifest.xml:32:95-135
> 
> When you have an error referencing a specific line in your `AndroidManifest.xml`, don't you think it'd be helpful to actually post the referenced file?
> 
> Have you even had a look at the referenced `line 32`?

    <service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location" />
    <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />
    
    these are the ones from app's manifest

**Comment by christocracy** [comment]
Now what happens when you try searching the [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md) with the text `"<service android:name="com.transistorsoft.locationmanager.service.TrackingService"`?

**Comment by christocracy** [comment]
Version `4.6.0` instructed you to **DELETE** those lines.

<img width="1055" alt="Screenshot 2023-09-04 at 5 22 15 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/d40fecb8-2277-40ba-8de0-4fc88dee6aec">

**Comment by andreshsingh** [comment]
> Now what happens when you try searching the [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md) with the text `"<service android:name="com.transistorsoft.locationmanager.service.TrackingService"`?

the deletion change is mentioned in 4.6.0 but didnt break till 4.10.1, had only searched the changes from 4.10.0 to latest.

thanks, removing the services fixed it. It maybe worth moving the delete info up in changelog for 4.10.1 as it seems to be the breaking point.
