### ISSUE TITLE
Ability to pass licence key in runtime instead of AndroidManifest.xml

### ISSUE THREAD

**Issue by AlexanderMorgos** [transistorsoft/react-native-background-geolocation#1806]
I'm wondering if there is a way to pass license key when calling .config() or something instead of placing key in android manifest file. Or maybe there is a way to use one key for multiple applicationId?

**Comment by christocracy** [comment]
> if there is a way to pass license key when calling .config() or something instead of placing key in android manifest file

no.  That will never happen.

> Or maybe there is a way to use one key for multiple applicationId?

No.  You can configure multiple keys to be inserted into AndroidManifest in your app:build.gradle.
