### ISSUE TITLE
Can i hide notification in android ?

### ISSUE THREAD

**Issue by Kang-minjae999** [transistorsoft/react-native-background-geolocation#1809]
hello.

Interface Notification
[Android only] The Android operating system requires a persistent notification when running a foreground service.

can i hide this ?

thank you.

**Comment by christocracy** [comment]
> The Android operating system _requires_  a persistent

See the [dictionary definition of the word [“Requires”](https://dictionary.cambridge.org/dictionary/english/require)

The answer is “no”.
