### ISSUE TITLE
App crashes on Android 13 when using react-native-background-geolocation

### ISSUE THREAD

**Issue by XchHarutyunyan** [transistorsoft/react-native-background-geolocation#1811]
## Your Environment
* Plugin version: 4.13.3
* Platform: Android
* OS version: 13
* React Native version (`react-native -v`): 0.72.4

I tried installing the [rn-background-geolocation-demo](https://github.com/transistorsoft/rn-background-geolocation-demo) but the same.
I tried different versions of react-native, tried different versions of react-native-background-geolocation but the problem remained.

**Comment by christocracy** [comment]
You've provided *zero* evidence of a crash.  Where's your stacktrace??

**Comment by XchHarutyunyan** [comment]
> Вы не предоставили _никаких_ доказательств крушения. Где твой стек??

I don't get any error.

**Comment by christocracy** [comment]
If there’s a “crash” there’s **always** a stacktrace printed to `$ adb logcat`.  Always.

**Comment by socheatleang** [comment]
Hey @christocracy . There is the same problem while on the release mode with android 13.

**Comment by socheatleang** [comment]
@XchHarutyunyan   How you deal with this issue?

**Comment by christocracy** [comment]
> There is the same problem 

Same "*what*" problem?  Nobody in this thread has provided any evidence **with a stacktrace** that this plugin is responsible for any crash.

**Comment by XchHarutyunyan** [comment]
> @XchHarutyunyan How you deal with this issue?

I haven't solved the problem yet, work on the project is suspended until I find an answer.
Let me know when you solve the problem.

**Comment by christocracy** [comment]
Does nobody know how to fetch the stacktrace from `$ adb logcat`??   The **FIRST** thing you do when you experience a crash on Android is launch `$ adb logcat` in your terminal and look for the stacktrace.

**Comment by christocracy** [comment]
Until somebody *proves* your crash is related to this plugin by providing a stacktrace referencing the plugin's namespace (`com.transistorsoft`), your crash is **NOT** related to this plugin.
