### ISSUE TITLE
Is there a way in which we can reduce drain on users battery and frequency of requests

### ISSUE THREAD

**Issue by jmcelroy99** [transistorsoft/react-native-background-geolocation#1815]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs Config,distanceFilter.  Also see api docs “HTTP Guide” to learn how to batch and/or queue http requests to run periodically rather than with each recorded location.
