### ISSUE TITLE
Geofences Log Messages

### ISSUE THREAD

**Issue by wafisher** [transistorsoft/react-native-background-geolocation#182]
Do you mind explaining what the following two log messages mean? I'm using the latest version (1.6.0) on iOS 10.2 with the demo app.

```
🔵 -[TSLocationManager onGeofence:action:] 📢 EXIT Geofence: MGLLocationManagerRegionIdentifier.fence.center
```

Which geofence does this refer to? I get this message a lot when working with geofences, though I've not set one with that ID.

And this:
```
ℹ️ -[TSLocationManager queue:type:] Found an activated geofence.  Attaching current location
```

This doesn't correspond to `geofenceschange` so I'm a little lost.

**Comment by christocracy** [comment]
That's MapboxGL's own geofence.  They create a stationary geofence too.  They track the device to mine information and don't provide a way to turn it off.  A map component should be a map component.  

I hate Mapbox.

**Comment by christocracy** [comment]
It seems I forgot to filter-out geofences not owned by the plugin.  I'll fix this.

**Comment by wafisher** [comment]
Any updates on this fix? Thanks!

**Comment by christocracy** [comment]
Yes, I've posted a fix to the premium version.  The fix will come to free version in the future when I post the latest stable release.

**Comment by christocracy** [comment]
I see you've just purchased, thanks.  You'll want to now use the premium repo you've just been granted access to.  You'll have to completely re-install the iOS from that repo.  You **no longer** use *this* repo.

The premium repo is currently suffixed with `-android`.  This will be renamed in the near future to `-premium`.  It *does* contain both iOS *and* Android.

Chat me if you have any issues re-installing iOS from the premium repo.
