### ISSUE TITLE
How do I keep tracking system awake in background if users selects "only while using" the app?

### ISSUE THREAD

**Issue by jmcelroy99** [transistorsoft/react-native-background-geolocation#1823]
Currently the tracking system turns off after about 20 minutes from the app being used in the foreground. 

## Your Environment
* Plugin version:
* Platform: iOS or Android : both
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):"0.72.3",
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

export const BackgroundLocationConfig = {
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOWEST,
  distanceFilter: 50,
  heartbeatInterval: 60 * 20,
  preventSuspend: true,
  stopTimeout: 5,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  disableMotionActivityUpdates: true,
  showsBackgroundLocationIndicator: true,
  locationAuthorizationRequest: 'Any',
  backgroundPermissionRationale: {
    title: "Allow {applicationName} to access to this device's location in the background?",
    message: "Allow us to access your location all the time so we can share your location to your friends.",
    positiveAction: "Change to {backgroundPermissionOptionLabel}",
    negativeAction: "Cancel"
  },
  stopOnTerminate: true,
  startOnBoot: false,
  batchSync: false,
  autoSync: false,
};
///////////'

const GroupsStackComponent = ({ navigation }) => {
  const { url, processing } = useInitialURL();
  const { locationEnabled, setLocationEnabled, userDetails } = useFrienzyStore();

  useEffect(() => {
    var urlParams = new Url(url, true);
    const groupId = urlParams.hash.slice(1);
    addUserToGroup(groupId, userDetails);
  }, [url]);

  useEffect(() => {

    const onLocation = BackgroundGeolocation.onLocation((event) => {
      console.log('[onLocation]', event.coords);
      const location = event.coords;
      const time = event.timestamp;
      saveUserLocation(location, time);
    });

    const onHeartbeat = BackgroundGeolocation.onHeartbeat((event) => {
      console.log('[onHeartbeat]', event);
      const location = event.location.coords;
      const time = event.location.timestamp;
      saveUserLocation(location, time);
    });

    const onProviderChange = BackgroundGeolocation.onProviderChange((event) => {
      console.log('[onProviderChange]', event);
      switch(event.status) {
        case BackgroundGeolocation.AUTHORIZATION_STATUS_DENIED:
          // Android & iOS
          setLocationEnabled(LOCATION_DENIED);
          console.log("- Location authorization denied");
          break;
        case BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS:
          // Android & iOS
          setLocationEnabled(LOCATION_AUTHORIZED);
          console.log("- Location always granted");
          break;
        case BackgroundGeolocation.AUTHORIZATION_STATUS_WHEN_IN_USE:
          // iOS only
          setLocationEnabled(LOCATION_WHEN_IN_USE);
          console.log("- Location WhenInUse granted");
          break;
      }
    });
    
    console.log("Location permission status: ", locationEnabled);
    if (locationEnabled == LOCATION_DENIED) {
       return;
    }
    BackgroundGeolocation.ready(BackgroundLocationConfig).then((state) => {
      if (locationEnabled != null) {
        BackgroundGeolocation.start();
      }
      console.log('- BackgroundGeolocation is configured and ready: ', state.enabled);
    });

    return () => {
      // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
      // during development live-reload.  Without this, event-listeners will accumulate with
      // each refresh during live-reload.
      onLocation.remove();
      onProviderChange.remove();
      onHeartbeat.remove();
    };
  }, []);

## Expected Behavior
I want the users location to update in the background consistently without the user having to bring the app to the foreground. I also don't want to request the user's location too frequently. 

## Actual Behavior
The user location stops updating after 20 minutes of being in the background. 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Ignored issue template.  Edit your issue and provide the required information.

**Comment by jmcelroy99** [comment]
should be updated

**Comment by christocracy** [comment]
What do you think are the consequences of WhenInUse vs Always?

**Comment by jmcelroy99** [comment]
Is there a way to bypass this and keep the app awake, I though I read something about a way to allow minimal location tracking in background that won't kill the user battery and it works in when in use? Most of our users don't allow us to 'always' track so trying to figure out a way to keep their location updated.

**Comment by christocracy** [comment]
With *WhenInUse*, your app functionality is reduced to that of a "*Jogging App*", where the user explicitly clicks some sort of button, like "[Start Tracking]*.  Your app code will then call `.changePace(true)`, putting the plugin into the *moving* state.  After the device is detected to be stationary, the plugin will initiate the `Config.stopTimeout` timer (which you've configure to `5` minutes).  When the `stopTimeout` timer expires, the plugin toggles into the *stationary* state, turns off location-services and your app goes to sleep until the user brings your app to the foreground and clicks the "[Start Tracking]" button once again.

There are major consequences to *WhenInUse* vs *Always* and it's not just a minor nuisance to be simply waved away with some magic config option.

And btw, these options are ignored with on iOS with *WhenInUse* authorization:
```
heartbeatInterval: 60 * 20,
preventSuspend: true,
```

**Comment by christocracy** [comment]
And do not even consider thinking about calling `.changePace(true)` with a super long `Config.stopTimeout`:  you will kill the user's battery (if they don't delete your app from their device first).
