### ISSUE TITLE
Background job stops after a few hours still, not kicking in back again. iOS & Android

### ISSUE THREAD

**Issue by trne** [transistorsoft/react-native-background-geolocation#1832]
## Your Environment
* Plugin version: 4.14.0
* Platform: iOS & Android
* OS version: iOS 17, Android 13
* Device manufacturer / model: iPhone, Samsung Galaxy S22 5G
* React Native version (`react-native -v`): 10.0.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 5,
        debug: true,
        logLevel: BackgroundGeolocation['LOG_LEVEL_VERBOSE'],
        stopOnTerminate: false,
        startOnBoot: true,
        url: `custom url`,
        batchSync: true,
        autoSync: false,
        disableLocationAuthorizationAlert: true,
}).then(state => {
        if (!state.enabled) {
            BackgroundGeolocation.start()
        }
})
```

## Expected Behavior

After a few hours of the phone being still, the app resumes tracking after moving 200 meters from the last known position.

## Actual Behavior

I need to restart the phone for the background geolocation feature to start tracking again.

## Steps to Reproduce

1. Start the app with these configs
2. Move around then stop and leave the phone still for a few hours
3. Jump to the car and drive half a mile
4. The app won't track, you will need to restart the phone.

## Context

I'm just trying to get the background geolocation plugin to work consistently 24/7

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki “Debugging” and api docs `Logger`.  Learn how to fetch the plug-in logs with .emailLog

**Comment by trne** [comment]
Thank you for your response yesterday @christocracy.
I managed to get some logs now, and this is an iOS one for one of our users from whom we received all data well in the morning, but not in the afternoon. For some reason the background job is not sending data to the server in the afternoon.

https://gist.github.com/trne/06de5dc400b5c5bd53d9c0e389b340e8

**Comment by christocracy** [comment]
What particular timestamp(s) are you interested in?

**Comment by trne** [comment]
sorry I updated that gist cause it cut off the timestamp I was interested on which is around 19:21:41.646

https://gist.github.com/trne/db373478ed886fdb51fa1945e11fb8e2#file-gistfile1-txt-L12861

which is approximately when the user finished the journey.

I can't tell weather the data has been sent to the backend or not, cause I don't see it in the backend.

**Comment by christocracy** [comment]
> which is around 19:21:41.646

There is **NO** `19:21` in your logs.

**Comment by trne** [comment]
sorry `19:29:41.646` the one that I highlighted on that last gist link
