### ISSUE TITLE
Use only notification module

### ISSUE THREAD

**Issue by pixelkoduje** [transistorsoft/react-native-background-geolocation#1835]
There is also a fee to use only the local notifications module?

**Comment by christocracy** [comment]
I have no idea what you're talking about.  I don't offer a "local notification module".

**Comment by pixelkoduje** [comment]
https://transistorsoft.github.io/react-native-background-geolocation/interfaces/notification.html

**Comment by christocracy** [comment]
This plugin has **nothing to do with** local-notifications.  You misunderstand the API docs.

That is the configuration for [notification required by the plugin's foreground-services](https://developer.android.com/guide/components/foreground-services).
