### ISSUE TITLE
[SOLVED] Plugin starts auto tracking even when not calling .start() function and with startOnBoot as false

### ISSUE THREAD

**Issue by christian-hess-94** [transistorsoft/react-native-background-geolocation#1839]
## Your Environment
* Plugin version: 4.13.3
* Platform: Android
* OS version: 12
* Device manufacturer / model: Google Emulator
* React Native version (`react-native -v`): 0.72.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const locationTrackingConfig: Config = {
    // Geolocation Config
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 100,
    useSignificantChangesOnly: true,
    // Activity Recognition
    stopTimeout: 5,
    disableMotionActivityUpdates: true,
    // Application config
    debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
    startOnBoot: false, // <-- Auto start tracking when device is powered-up.
    // HTTP / SQLite config
    url: 'https://eo8y96bwprs1sa5.m.pipedream.net',
    batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
    autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
    headers: {
      // <-- Optional HTTP headers
      from_where: Platform.OS,
    },
    params: {
      // <-- Optional HTTP params
      from_where: Platform.OS,
    },
  };
```

## Expected Behavior

The app should't execute any of the events being set in the useEffect step:
```javascript
React.useEffect(() => {
    // BackgroundGeolocation.requestPermission(); //remove asking for the activity permission
    const onLocation: Subscription = BackgroundGeolocation.onLocation(
      location => {
        console.log(
          '[onLocation]',
          location.coords.latitude,
          location.coords.longitude
        );
      }
    );
    const onMotionChange: Subscription = BackgroundGeolocation.onMotionChange(
      event => console.log('[onMotionChange]', event)
    );

    const onHttp: Subscription = BackgroundGeolocation.onHttp(event => {});

    const onActivityChange: Subscription =
      BackgroundGeolocation.onActivityChange(event =>
        console.log('[onActivityChange]', event)
      );
    const onProviderChange: Subscription =
      BackgroundGeolocation.onProviderChange(event =>
        console.log('[onProviderChange]', event)
      );
    BackgroundGeolocation.ready(locationTrackingConfig).then(state => {
      console.log(
        '- BackgroundGeolocation is configured and ready: ',
        state.enabled
      );
    });

    return () => {
      // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
      // during development live-reload.  Without this, event-listeners will accumulate with
      // each refresh during live-reload.
      onLocation.remove();
      onMotionChange.remove();
      onActivityChange.remove();
      onProviderChange.remove();
      onHttp.remove();
    };
  }, []);
```
## Actual Behavior

The onProviderChange event is called when the screen pops into existence. I verified this via the log that appears in the console:
[onProviderChange] {"accuracyAuthorization": 0, "enabled": true, "gps": true, "network": true, "status": 3}

## Steps to Reproduce

1. I'm using the default code snippet from the repo, if a reproducible repo is necessary please let me know
2. The screen pops and the useEffect hook is called, which calls the ready() function. The start() function is not called anywhere in the page.

## Context

I want to have the plugin ready to be started when the screen pops up. However the plugin should only start tracking after an use interacts with a button on the page
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
[onProviderChange] {"accuracyAuthorization": 0, "enabled": true, "gps": true, "network": true, "status": 3}
//no other logs appear
```

</details>

**Comment by christocracy** [comment]
>[onProviderChange] {"accuracyAuthorization": 0, "enabled": true, "gps": true, "network": true, "status": 3}
//no other logs appear

This is not location-tracking.

**Comment by christian-hess-94** [comment]
oh ok so that gets called regardless of running start or not then?
I ask because the first time I noticed thie behaviour the plugin requested for Physical Activity permission (Android), but the option is disabled in the plugin config. I reinstalled the debug app and that permission pop-up did not appear again, so I wondered if it was being automatically trigger and that had something to do with it

**Comment by christocracy** [comment]
`onProviderChange` event fires no matter what, giving you a chance to learn the current state of location-services.

**Comment by christian-hess-94** [comment]
got it, thanks for clarifying! Will close this issue out!
