### ISSUE TITLE
In android location updates stop in background after 3 to 5 minutes

### ISSUE THREAD

**Issue by Mukthayar1** [transistorsoft/react-native-background-geolocation#1841]
In android location updates stop in background after 3 to 5 minutes

**Comment by christocracy** [comment]
See api docs Config.stopTimeout.

Also see wiki "Philosophy of Operation".

**Comment by christocracy** [comment]
And you've ignored the required issue template.

**Comment by Mukthayar1** [comment]
@christocracy 
Please see my configuration.
 BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50,
        stopTimeout: 5,
        debug: false,
        isMoving:true,
        logLevel: BackgroundGeolocation['LOG_LEVEL_VERBOSE'],
        stopOnTerminate: false,
        preventSuspend: true,
        startOnBoot: true,
        method: 'POST',
        batchSync: true,
        autoSync: true,
        autoSyncThreshold: 20,
        headers: { Authorization: '' },
        enableTimestampMeta: true,
        enabledHeadless:true,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: {
            title: "Allow to access to this device's location in the background?",
            message:
                'Required location',
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel',
        },
        notification: {
            title: "Background tracking engaged",
            text: "My notification text"
        },
        reset: false,
        disableLocationAuthorizationAlert: false,
        enableHeadless: true,
        foregroundService: true,
        showsBackgroundLocationIndicator: true,
        disableStopDetection: true,
        disableMotionActivityUpdates: true,
    }).then((state) => {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
    });
    

still location updates stop in background after 3 to 5 minutes.
I think its happening due to app get rest while in background how to stop that ?
