### ISSUE TITLE
Location Stop on android after 3 to 4 minitues

### ISSUE THREAD

**Issue by Mukthayar12** [transistorsoft/react-native-background-geolocation#1842]
@christocracy
Please see my configuration.
BackgroundGeolocation.ready({
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 50,
stopTimeout: 5,
debug: false,
isMoving:true,
logLevel: BackgroundGeolocation['LOG_LEVEL_VERBOSE'],
stopOnTerminate: false,
preventSuspend: true,
startOnBoot: true,
method: 'POST',
batchSync: true,
autoSync: true,
autoSyncThreshold: 20,
headers: { Authorization: '' },
enableTimestampMeta: true,
enabledHeadless:true,
locationAuthorizationRequest: 'Always',
backgroundPermissionRationale: {
title: "Allow to access to this device's location in the background?",
message:
'Required location',
positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
negativeAction: 'Cancel',
},
notification: {
title: "Background tracking engaged",
text: "My notification text"
},
reset: false,
disableLocationAuthorizationAlert: false,
enableHeadless: true,
foregroundService: true,
showsBackgroundLocationIndicator: true,
disableStopDetection: true,
disableMotionActivityUpdates: true,
}).then((state) => {
console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
});

 location updates stop in background after 3 to 5 minutes.
even headless task stop after 4 to 3 minutes.
I think its happening due to app get rest while in background how to stop that ?

**Comment by christocracy** [comment]
Ignored issue template.  The issue template is not optional, it's required.
