### ISSUE TITLE
`onLocation` callback is firing multiple times with less accuracy

### ISSUE THREAD

**Issue by aanjan123** [transistorsoft/react-native-background-geolocation#1845]
## Description

The `onLocation` callback is sending multiple data updates even when a distance filter of 12 meters has been set. Is there any way we can configure it to only send a callback when the user has moved more than the defined distance filter?

Additionally, when checking the callback data, I found that the accuracy is sometimes more than 14 meters. In real-time scenarios, 14 meters of accuracy is too high to consider. I am currently using `DESIRED_ACCURACY_NAVIGATION` for iOS, but I am still facing this issue.

## Your Environment

- **Plugin version:4.14.2
- **Platform:** iOS
- **OS version: 17.0.1
- **Device manufacturer / model: iPhone 12
- **React Native version (`0.67.4`):**
- **Plugin configuration:**
  ```javascript
  BackgroundGeolocation.ready({
      preventSuspend: true,
      heartbeatInterval: 60,
      distanceFilter: 12,
      disableMotionActivityUpdates: true,
      locationAuthorizationRequest: 'Always',
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      stopOnTerminate: true,
      startOnBoot: false,
      stationaryRadius: 5,
      notification: {
        title: 'Background tracking',
        text: 'enabled',
      },
      debug: false,
      showsBackgroundLocationIndicator: false,
      disableStopDetection: false,
      pausesLocationUpdatesAutomatically: false,
      allowIdenticalLocations: true
    });
    
```

## Expected Behavior
I expect to receive a location change event only when the user has moved more than 12 meters, and all the data should have accuracy values of 5 meters or less.

## Actual Behavior
Currently, I'm receiving multiple location change events even for slight changes in location, and the accuracy values are always greater than 14 meters. I'm looking for a way to configure the plugin to meet the expected behavior.

**Comment by christocracy** [comment]
The issue template is not optional:

> Plugin version:
>OS version:
> React Native version (react-native -v):

**Comment by aanjan123** [comment]
updated

**Comment by christocracy** [comment]
> Is there any way we can configure it to only send a callback when the user has moved more than the defined distance filter?

No

> In real-time scenarios, 14 meters of accuracy is too high to consider. I am currently using

The plug-in does not *manufacture* the location data.  It simply relays them to you exactly as provided by the native location api.  There is no possible way to get higher accuracy.  This is due to the laws of physics.

**Comment by aanjan123** [comment]
In that case what significance does `distanceFilter` params consist in configuration?
We have that parameter there, what difference will be there with the value of  5 or 500?

**Comment by christocracy** [comment]
Read about it at the iOS API docs:  https://developer.apple.com/documentation/corelocation/cllocationmanager/1423500-distancefilter

**Comment by christocracy** [comment]
Have you considered that you might have multiple `onLocation` events registered?  Are you observing the `locaiton.uuid`?  Is it the same or different?  Are you observing the plugin logs?

**Comment by witehound** [comment]
> Have you considered that you might have multiple `onLocation` events registered? Are you observing the `locaiton.uuid`? Is it the same or different? Are you observing the plugin logs?

This is not related to this issue. Please is there a way to know always show location on iOS anytime there’s a change in location!

**Comment by christocracy** [comment]
I have never heard this issue expressed in 8 years.

I don't see any issue.  I suggest you see the wiki "Debugging", learn to fetch logs with .emailLog method.

**Comment by witehound** [comment]
> I have never heard this issue expressed in 8 years.
> 
> I don't see any issue. I suggest you see the wiki "Debugging", learn to fetch logs with .emailLog method.

Looks like I made grammatical errors what I meant is current I’m running a development build anytime location changes I always get a notification, but I don’t want this behavior I’m just looking for a way to disable it.

**Comment by christocracy** [comment]
See api docs Config.debug

**Comment by witehound** [comment]
> See api docs Config.debug

Thank you very much! Hate to extend this issue with more unnecessary comments! But right now I can’t actually dispatch background accounts on iOS when app is terminated tho I know the application actually tracks the location! Any help

**Comment by christocracy** [comment]
> dispatch background accounts 

I have no idea what that means.  If you have an unrelated problem, post a new issue.  Issues are not personal support threads.

**Comment by aanjan123** [comment]
@christocracy i am receiving different `uuid` every time i get a callback

```

  const locationListener = useRef();

 if (locationListener.current) {
      locationListener.current.remove();
      locationListener.current = null;
    }

    locationListener.current = BackgroundGeolocation.onLocation(location => {
      console.log(JSON.stringify({ updatedlocation: location }))
    });
    
    return () => {
          locationListener.current.remove();
}


```
