### ISSUE TITLE
Issue with Polygonal Geofencing on iOS

### ISSUE THREAD

**Issue by aanjan123** [transistorsoft/react-native-background-geolocation#1846]
## Your Environment
* Plugin version: 4.14.2
* Platform: iOS 
* OS version: 17.0.1 
* Device manufacturer / model: iPhone 12 & Also tested in simulator with manually updating location 
* React Native version (`0.67.4`):
* Plugin config
```javascript 

  BackgroundGeolocation.onGeofence(geofence => {
      console.log("[geofence] ", { geofence });
    })

BackgroundGeolocation.addGeofence({
      identifier: 'Home',
      notifyOnEntry: true,
      notifyOnExit: true,
      vertices: [
        [27.672427, 85.345839],
        [27.672424, 85.345855],
        [27.672439, 85.345825],
        [27.672446, 85.345845],
        [27.672411, 85.345822],
        [27.672483, 85.345762],
        [27.672520, 85.345708]
      ]
    }).then(()=>{    
              BackgroundGeolocation.startGeofences();
});

    
```

## Expected Behavior
I expected to receive callbacks upon entering and exiting a polygonal geofence region on the iOS platform, similar to the behavior I observed with circular geofencing.

## Actual Behavior
However, when I transitioned to implementing polygonal geofencing, I did not receive any callbacks upon entering or exiting the region, despite following the example in the documentation.

I also have a question regarding the need to purchase a specific feature for iOS. Do we require a purchase for iOS as well? Will this feature not work in a debug build without purchasing it? It's important to note that I am currently only testing this on the iOS platform.

**Comment by christocracy** [comment]
When I plot your `vertices` on a map, this is what your polygon looks like.  Order of `vertices` **matters**.

Make a better polygon.  Start with a simple square.

<img width="1184" alt="Screenshot 2023-10-10 at 12 49 12 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/b7c5b420-5b3f-4424-b8df-abbb9ed4838f">

**Comment by aanjan123** [comment]
ah Okay, but when I try to use the example values in the simulator updating location lat long manually, I was receiving callback in the case of circular geofencing but not in the case of polygonal geofencing. 

`BackgroundGeolocation.addGeofence({
  identifier: 'Home',
  notifyOnEntry: true,
  notifyOnExit: true,
  vertices: [
    [45.518947279987714, -73.6049889209514],  // <-- [lat, lng]
    [45.5182711292279, -73.60338649600598],
    [45.517082240237634, -73.60432670908212],
    [45.51774871402813, -73.60604928622278]
  ]
});`

**Comment by christocracy** [comment]
Your Polygon shape is highly abnormal.  Fix it.

**Comment by aanjan123** [comment]
updated my polygon geofencing vertices, still not receiving any callbacks

current verticies is given below

```
    BackgroundGeolocation.addGeofence({
      identifier: 'Home',
      notifyOnEntry: true,
      notifyOnExit: true,
      vertices: [
        [27.67254431189224, 85.34567377546588],
        [27.67265580548456, 85.34571645120293],
        [27.672523525017997, 85.3459234291403],
        [27.672426204385992, 85.34583167609148]
      ]
    })
    
    ```

**Comment by yonkahlon** [comment]
Hi @aanjan123 

If you close the polygon, i.e. copy coord 1 to the end like so:

```
BackgroundGeolocation.addGeofence({
      identifier: 'Home',
      notifyOnEntry: true,
      notifyOnExit: true,
      vertices: [
        [27.67254431189224, 85.34567377546588],
        [27.67265580548456, 85.34571645120293],
        [27.672523525017997, 85.3459234291403],
        [27.672426204385992, 85.34583167609148].
        [27.67254431189224, 85.34567377546588]
      ]
    })
```

It may work.

On Android, if I test with an open polygon (your example) I didn't get any events. When I closed the polygon I got ENTER events. Maybe this will work for you on iOS as well.

I'm not getting EXIT events though, and I'm not sure why yet.

**Comment by christocracy** [comment]
You don't need to "close" a polygon by duplicating vertices.

The plug-in prints valuable logs to its log database when it evaluates polygons.  You should be observing your logs.

**Comment by christocracy** [comment]
The Order of `vertices` matters and polygons are automatically "closed".  I suggest you experiment using the [Demo App](https://github.com/transistorsoft/rn-background-geolocation-demo), which includes a polygon geofence designer.

### Good Polygon

![IMG_0021](https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/0d050fa0-c689-4370-b155-c90b03b744c6)

### Bad Polygon

![IMG_0022](https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/b8bd8d93-efc7-4f95-b8c6-abe06eab7f52)

**Comment by christocracy** [comment]
It's like a pencil drawing a line to connect the `vertices` in the order provided.

Here is [a video of creating a polygon in the Demo app](https://www.dropbox.com/scl/fi/mmag9jpx2g52ezz8czrkx/polygon-geofence-designer.mov?rlkey=xbry6ohv0nq4qglmjdzqv09na&dl=0)

**Comment by SrikanthEnuguru** [comment]
For circular geofencing, minimum reliable radius is 200m to receive entry and exit events.

Are there any such limitations for polygon geofencing too?

Since a polygon will be converted to a minimum enclosing circle, is 200m radius limitation applies to polygon geofencing too?

We observed that listeners are not being triggered for small polygons. When we increased the size of the polygon, geofencing worked as expected.

**Comment by christocracy** [comment]
Polygons depend upon the accuracy of the location and will work best outdoors where location accuracy is typically ~5m.

Indoor location accuracy is typically ~40m.

Don't test polygons while sitting indoors.  Go outside to test them.

**Comment by christocracy** [comment]
> for small polygons.

A small polygon to me is like a square or triangle having sides of 50m.  I don't know what your idea of small is.
