### ISSUE TITLE
"activity_type": "unknown" on every record.

### ISSUE THREAD

**Issue by trne** [transistorsoft/react-native-background-geolocation#1847]
## Your Environment
* Plugin version: 6.9.4
* Platform: iOS
* OS version: iOS 17
* Device manufacturer / model: iPhone 14
* React Native version (`react-native -v`): 10.0.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 5,
        debug: debug,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        transistorAuthorizationToken: token,
        batchSync: true,
        autoSync: false,
        disableLocationAuthorizationAlert: true
}
```

## Expected Behavior
I'd like to send to the backend only records for `"activity_type": "in_vehicle"` and I'd like each object to have the right `activity_type`

## Actual Behavior
I get every single motion record object sent to the backend and everyone has `"activity_type": "unknown"`.

```
{
  "id": 171335710,
  "company_id": 18561,
  "company_token": "xxxx",
  "device_id": 63046,
  "device_model": "iPhone14,5",
  "created_at": "2023-10-10T18:44:51.767Z",
  "framework": "react-native",
  "version": "17.0.2",
  "updated_at": "2023-10-10T18:44:52.383Z",
  "activity_type": "unknown",
  "activity_confidence": 100,
  "battery_level": 0.699999988079071,
  "battery_is_charging": false,
  "extras": {},
  "is_moving": true,
  "age": 46,
  "odometer": 53872.6,
  "uuid": "D8043896-A29B-4651-AAEE-5C75930C498C",
  "timestamp": "2023-10-10T17:25:25.000Z",
  "speed_accuracy": 1.19,
  "speed": 2.59,
  "longitude": -0.117734895697123,
  "ellipsoidal_altitude": 115.5,
  "floor": null,
  "heading_accuracy": 18.77,
  "latitude": 51.3354121563826,
  "accuracy": 4.8,
  "altitude_accuracy": 3.2,
  "altitude": 70.9,
  "heading": 218.03,
  "recorded_at": "2023-10-10T17:25:25.000Z"
}
```

## Steps to Reproduce

1. Follow this post [Background Geolocation Console](https://transistorsoft.medium.com/background-geolocation-console-45796532c2ee) to make sure all data from the app goes to the testing backend.
2. Jump into a car, train, bus and let the plugin record and send the data to the backend.
3. Check every row that you get on the backend.

## Context
I'm trying to tell records apart because I'm only interested on records that have `"activity_type": "in_vehicle"`

## Debug logs

[Logs](https://gist.github.com/trne/4290887644976cbe8bd5ae5a85033ce2)

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Either you're using the iOS Simulator or you've denied the "motion" permission.

**Comment by trne** [comment]
This is a real device, and I have granted all permissions to the app.

![IMG_0491](https://github.com/transistorsoft/react-native-background-geolocation/assets/115544783/05452b51-378c-493c-9bec-ca14a672b175)

**Comment by christocracy** [comment]
Restart your device.  The plug-in is not responsible for the quality of data returned by the native motion api.  It's either ON or OFF.  There is nothing to be done to "fix" it if undesirable data is being returned.

**Comment by trne** [comment]
closing this issue as the issue was actually not with this plugin but with the device's sensor as suggested by @christocracy 
just restarting the phone solved it.
