### ISSUE TITLE
location not updating

### ISSUE THREAD

**Issue by shubhlumber** [transistorsoft/react-native-background-geolocation#1852]
## Your Environment
* Plugin version:^4.14.2
* Platform: iOS or Android Android
* OS version: 14
* Device manufacturer / model: Pixel 7 Emulatorexpo
* React Native version (`react-native -v`): 0.72.5 
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->useEffect(() => {
    const onLocation: Subscription = BackgroundGeolocation.onLocation((location) => {
      console.log('[onLocation]', location);
      console.log(location.coords.latitude);
      console.log(location.coords.longitude);
      setLatitude(location.coords.latitude);
      setLongitude(location.coords.longitude);
    });

    BackgroundGeolocation.ready({
      heartbeatInterval: 600,
      preventSuspend: true,
      stopOnTerminate: false,
      startOnBoot: true,
    });

    return () => {
      onLocation.remove();
    };
  }, [status]);

  useEffect(() => {
    if (locationEnabled && status === 'CLOCKED_IN') {
      console.log('Location ON');
      BackgroundGeolocation.start();
    } else {
      console.log('Location OFF');
      BackgroundGeolocation.stop();
    }
  }, [status, locationEnabled]);
```

## Expected Behavior
Able to get location

## Actual Behavior
location not updating

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>
10-13 00:05:04.828 17196 17229 D TSLocationManager: [c.t.l.logger.LoggerFacade$a a] ℹ️   Persist config, dirty: []
10-13 00:07:43.721 17410 17450 D TSLocationManager: [c.t.l.l.TSSQLiteAppender$c run] 
10-13 00:07:43.721 17410 17450 D TSLocationManager:   ℹ️  Cleared logs older than 72 hours
10-13 00:07:43.721 17410 17443 I TSLocationManager: [c.t.l.logger.LoggerFacade$a a] 
10-13 00:07:43.721 17410 17443 I TSLocationManager: ╔═════════════════════════════════════════════
10-13 00:07:43.721 17410 17443 I TSLocationManager: ║ TSLocationManager version: 3.5.1 (430)
10-13 00:07:43.721 17410 17443 I TSLocationManager: ╠═════════════════════════════════════════════
10-13 00:07:43.721 17410 17443 I TSLocationManager: ╟─ Google sdk_gphone64_arm64 @ 14 (react)
10-13 00:07:43.721 17410 17443 I TSLocationManager: {
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "activityRecognitionInterval": 10000,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "allowIdenticalLocations": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "authorization": {},
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "autoSync": true,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "autoSyncThreshold": 0,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "backgroundPermissionRationale": {
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "message": "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "negativeAction": ""
10-13 00:07:43.721 17410 17443 I TSLocationManager:   },
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "batchSync": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "configUrl": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "debug": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "deferTime": 0,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "desiredAccuracy": 0,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "desiredOdometerAccuracy": 100,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "disableAutoSyncOnCellular": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "disableElasticity": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "disableLocationAuthorizationAlert": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "disableMotionActivityUpdates": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "disableProviderChangeRecord": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "disableStopDetection": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "distanceFilter": 10,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "elasticityMultiplier": 1,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "enableHeadless": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "enableTimestampMeta": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "extras": {},
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "fastestLocationUpdateInterval": -1,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "foregroundService": true,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "geofenceInitialTriggerEntry": true,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "geofenceModeHighAccuracy": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "geofenceProximityRadius": 1000,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "geofenceTemplate": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "headers": {},
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "heartbeatInterval": 600,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "httpRootProperty": "location",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "httpTimeout": 60000,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "isMoving": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "locationAuthorizationRequest": "Always",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "locationTemplate": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "locationTimeout": 60,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "locationUpdateInterval": 1000,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "locationsOrderDirection": "ASC",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "logLevel": 0,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "logMaxDays": 3,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "maxBatchSize": -1,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "maxDaysToPersist": 1,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "maxMonitoredGeofences": 97,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "maxRecordsToPersist": -1,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "method": "POST",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "minimumActivityRecognitionConfidence": 75,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "motionTriggerDelay": 0,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "notification": {
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "layout": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "title": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "text": "Location Service activated",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "color": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "channelName": "TSLocationManager",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "channelId": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "smallIcon": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "largeIcon": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "priority": -1,
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "sticky": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "strings": {},
10-13 00:07:43.721 17410 17443 I TSLocationManager:     "actions": []
10-13 00:07:43.721 17410 17443 I TSLocationManager:   },
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "params": {},
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "persist": true,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "persistMode": 2,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "schedule": [],
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "scheduleUseAlarmManager": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "speedJumpFilter": 300,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "startOnBoot": true,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "stationaryRadius": 25,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "stopAfterElapsedMinutes": 0,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "stopOnStationary": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "stopOnTerminate": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "stopTimeout": 5,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "url": "",
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "useSignificantChangesOnly": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "enabled": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "schedulerEnabled": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "trackingMode": 1,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "odometer": 0,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "isFirstBoot": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "didLaunchInBackground": false,
10-13 00:07:43.721 17410 17443 I TSLocationManager:   "didDeviceReboot": false
10-13 00:07:43.721 17410 17443 I TSLocationManager: }
10-13 00:12:10.886 19147 19190 D TSLocationManager: [c.t.l.l.TSSQLiteAppender$c run] 
10-13 00:12:10.886 19147 19190 D TSLocationManager:   ℹ️  Cleared logs older than 72 hours
10-13 00:12:33.020 19294 19328 I TSLocationManager: [c.t.l.logger.LoggerFacade$a a] 
10-13 00:12:33.020 19294 19328 I TSLocationManager: ╔═════════════════════════════════════════════
10-13 00:12:33.020 19294 19328 I TSLocationManager: ║ TSLocationManager version: 3.5.1 (430)
10-13 00:12:33.020 19294 19328 I TSLocationManager: ╠═════════════════════════════════════════════
10-13 00:12:33.020 19294 19328 I TSLocationManager: ╟─ Google sdk_gphone64_arm64 @ 14 (react)
10-13 00:12:33.020 19294 19328 I TSLocationManager: {
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "activityRecognitionInterval": 10000,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "allowIdenticalLocations": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "authorization": {},
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "autoSync": true,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "autoSyncThreshold": 0,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "backgroundPermissionRationale": {
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "message": "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "negativeAction": ""
10-13 00:12:33.020 19294 19328 I TSLocationManager:   },
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "batchSync": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "configUrl": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "debug": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "deferTime": 0,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "desiredAccuracy": 0,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "desiredOdometerAccuracy": 100,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "disableAutoSyncOnCellular": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "disableElasticity": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "disableLocationAuthorizationAlert": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "disableMotionActivityUpdates": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "disableProviderChangeRecord": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "disableStopDetection": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "distanceFilter": 10,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "elasticityMultiplier": 1,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "enableHeadless": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "enableTimestampMeta": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "extras": {},
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "fastestLocationUpdateInterval": -1,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "foregroundService": true,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "geofenceInitialTriggerEntry": true,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "geofenceModeHighAccuracy": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "geofenceProximityRadius": 1000,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "geofenceTemplate": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "headers": {},
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "heartbeatInterval": 600,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "httpRootProperty": "location",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "httpTimeout": 60000,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "isMoving": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "locationAuthorizationRequest": "Always",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "locationTemplate": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "locationTimeout": 60,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "locationUpdateInterval": 1000,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "locationsOrderDirection": "ASC",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "logLevel": 0,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "logMaxDays": 3,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "maxBatchSize": -1,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "maxDaysToPersist": 1,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "maxMonitoredGeofences": 97,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "maxRecordsToPersist": -1,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "method": "POST",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "minimumActivityRecognitionConfidence": 75,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "motionTriggerDelay": 0,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "notification": {
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "layout": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "title": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "text": "Location Service activated",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "color": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "channelName": "TSLocationManager",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "channelId": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "smallIcon": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "largeIcon": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "priority": -1,
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "sticky": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "strings": {},
10-13 00:12:33.020 19294 19328 I TSLocationManager:     "actions": []
10-13 00:12:33.020 19294 19328 I TSLocationManager:   },
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "params": {},
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "persist": true,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "persistMode": 2,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "schedule": [],
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "scheduleUseAlarmManager": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "speedJumpFilter": 300,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "startOnBoot": true,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "stationaryRadius": 25,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "stopAfterElapsedMinutes": 0,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "stopOnStationary": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "stopOnTerminate": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "stopTimeout": 5,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "url": "",
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "useSignificantChangesOnly": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "enabled": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "schedulerEnabled": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "trackingMode": 1,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "odometer": 0,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "isFirstBoot": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "didLaunchInBackground": false,
10-13 00:12:33.020 19294 19328 I TSLocationManager:   "didDeviceReboot": false
10-13 00:12:33.020 19294 19328 I TSLocationManager: }

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki "Debugging".
