### ISSUE TITLE
Reseting plugin with new configuration requests motion activity tracking even when flag is false

### ISSUE THREAD

**Issue by christian-hess-94** [transistorsoft/react-native-background-geolocation#1854]
## Your Environment
* Plugin version: 4.13.3
* Platform: iOS & Android
* OS version: 16 (iOS) & 33 (Android)
* Device manufacturer / model: Apple Iphone 12
* React Native version (`react-native -v`): 0.72.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const config: BackgroundGeolocation.Config = {
    // Geolocation Config
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 100,
    useSignificantChangesOnly: true,
    // Activity Recognition
    stopTimeout: 5,
    disableMotionActivityUpdates: true,
    // Application config
    debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
    startOnBoot: false, // <-- Auto start tracking when device is powered-up.
    // HTTP / SQLite config
    url: 'https://eo8y96bwprs1sa5.m.pipedream.net',
    batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
    autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
    headers: {
      // <-- Optional HTTP headers
      from_where: Platform.OS,
    },
    params: {
      // <-- Optional HTTP params
      from_where: Platform.OS,
    },
  }
```

## Expected Behavior

We have a specific moment in our app flow that we need to disable the useSignificantChangesOnly (it is true by default as per the config above). We are using the reset() function and passing it a new config object with the flag off. When we call the function it should just reset the plugin and use the new config object.
## Actual Behavior

It seems the reset function is subtituting the config object but for whatever reason it asks for the Motion Actiivy updates even though both config object have the disableMotionActivityUpdates flag set to false. We do not intend to ask the users for Motion Activities
## Steps to Reproduce

1. Call ready() function with above config object
2. Star the plugin
3. When user clicks on button, call reset({...config, useSignificantChangesOnly: false}) to set the flag to false
4. When the above is called, it requests for the motion activities permission even though disableMotionActivityUpdates: true,

## Context

We are implementing a feature where the user can opt into having a more precise background location tracking. By default the tracking in the background happens very occasionally, so we have the useSignificantChangesOnly flag to true. When they opt in, we set that flag to false so that even if they background the app we'll still get updates more often until they opt out of it again. We are using the reset() function to achieve this functionality
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
No logs are available
```

</details>

**Comment by christian-hess-94** [comment]
Here's a quick video showing what happens when the user clicks the button. The "accept job" button is what trigger the call to the reset() function

https://github.com/transistorsoft/react-native-background-geolocation/assets/34290680/a9b5b652-b8a8-4982-a257-d503af5cf7f1

**Comment by christocracy** [comment]
Why not use .setConfig instead of .reset?

**Comment by christian-hess-94** [comment]
oh I can give that a try thanks!

**Comment by christian-hess-94** [comment]
it worked thanks! I had thought we needed to flush the entire plugin for it to accept a new configuration
