### ISSUE TITLE
Always geo permission state

### ISSUE THREAD

**Issue by superyarik** [transistorsoft/react-native-background-geolocation#1858]
## Your Environment
* Plugin version: 4.14.2
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung s21fe SM-G990B
* React Native version (`react-native -v`): 0.71.13
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 50,
            fastestLocationUpdateInterval: 30000,
            locationUpdateInterval: 30000,
            stopTimeout: 5,
            maxDaysToPersist: 60,
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,
            startOnBoot: true,
            heartbeatInterval: 60 * 5,
            notification: {
                title: 'EDITED',
                text: 'EDITED',
                channelName: 'EDITED',
                channelId: 'EDITED',
            },
            showsBackgroundLocationIndicator: true,
            foregroundService: true,
            enableHeadless: true,
            url: 'EDITED',
            allowIdenticalLocations: false,
            disableProviderChangeRecord: true,
            locationAuthorizationRequest: 'Any',
            disableLocationAuthorizationAlert: true,
            locationAuthorizationAlert: {
                titleWhenNotEnabled: 'Yo, location-services not enabled',
                titleWhenOff: 'Yo, location-services OFF',
                instructions: "You must enable 'Always' in location-services, buddy",
                cancelButton: 'Cancel!1',
                settingsButton: 'Settings!1',
            },
            backgroundPermissionRationale: {
                negativeAction: 'EDITED',
                title: 'EDITED',
                message:
                    'EDITED',
                positiveAction: 'EDITED',
            },
            batchSync: true,
            autoSync: true,
            autoSyncThreshold: 1,
        }
```

## Actual Behavior

Strange behavior experienced with the request for location permission is likely due to the initial setting of "Always" permission and later manual change to "WhenInUse" permission in the system settings. When you start the app and call `.ready()` with `locationAuthorizationRequest: Any` set, the app prompts you to "change to Always".

This is a normal case for users who are allowed to choose not to set the permission to "Always". However, it seems that you are unable to cancel this request to "change to Always" from within the app on each startup. It feels like the library is maintaining the state of "Always" and you're unable to change it without reinstalling the app.

Also each time the app is launched (after completing the `.ready()`), I execute `.stop()`, and then, if necessary, I ask the user to go to the settings, set the required permission level, and then I possibly change the `locationAuthorizationRequest` parameter through `setConfig()` and execute `.start()`. However, in the described case, it remains as "WhenInUse" between .stop and .start.

## Expected Behavior

Calling `.ready()` with `locationAuthorizationRequest: Any` should not result in a request to "change to Always", even if the app previously had such a permission but now has a different one.

**Comment by christocracy** [comment]
> should not result in a request to "change to Always"

The plug-in *must* request "Change to Always" with `Any`.

**Comment by superyarik** [comment]
But how to avoid the "Change to Always" request if it is not needed? 

If I choose "wheninuse" on .start and "Any" is set in the config, then when restarting the application during .ready, I am not prompted to "Change to Always." However, now we set "Always" in the settings for the application, restart the application, there is a .stop .start calls, then we go back to the settings, set it to "wheninuse" again, and restart the application twice - and voila, on the second restart, .ready now leads to "Change to Always". I find this behavior strange.

**Comment by christocracy** [comment]
If you don't want "Change to Always", then configure `WhenInUse`.  This seems obvious to me.

**Comment by superyarik** [comment]
That's correct, for some reason I had a wrong understanding of how "Any" works. Thank you!
