### ISSUE TITLE
Typo in Android timestamp metadata: systemClockElaspsedRealtime

### ISSUE THREAD

**Issue by ascherkus** [transistorsoft/react-native-background-geolocation#1859]
## Your Environment
* Plugin version: 4.12.1
* Platform: Android
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  enableTimestampMeta: true,
  locationTemplate: `{ "timestampMetadata": <%= timestampMeta %> }`,
}
```

## Expected Behavior
`systemClockElapsedRealtime` key on Android matches that of iOS

## Actual Behavior
The Android SDK has a typo (extra "s" in "elapsed"): systemClockEla***s***psedRealtime

Example iOS log:
```json
"timestampMetadata": {
    "systemTime": 1697668688780,
    "time": 1697668688773,
    "systemClockElapsedRealtime": 6305610000
}
```

Example Android log:
```json
"timestampMetadata": {
    "time": 1697669333265,
    "systemTime": 1697669333311,
    "systemClockElaspsedRealtime": 51993,
    "elapsedRealtime": 51946
}
```

## Steps to Reproduce

1. Enable `enableTimestampMeta` and template, if necessary
2. Start background geolocation tracking
3. Log the JSON results

## Context
I was trying to write backend code that parses timestamp metadata and noticed Android was dropping `systemClockElapsedRealtime` and I tracked it down to the typo.

Said typo is present in the documentation as well.

**Comment by christocracy** [comment]
Weird.  

Whatever you're doing with timestampMeta, you might be able to use the new location.age instead.
