### ISSUE TITLE
Selective Record Sending Based on Activity Type

### ISSUE THREAD

**Issue by trne** [transistorsoft/react-native-background-geolocation#1861]
## Your Environment
* Plugin version: 6.9.4
* Platform: iOS
* OS version: iOS 17
* Device manufacturer / model: iPhone 14
* React Native version (`react-native -v`): 10.0.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 5,
        debug: debug,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        transistorAuthorizationToken: token,
        batchSync: true,
        autoSync: false,
        disableLocationAuthorizationAlert: true
}
```

## Expected Behavior
I want to send only records with activity_type values of 'unknown,' 'still,' and 'in_vehicle' to the backend, while excluding any records with 'walking,' 'on_foot,' 'running,' and 'on_bicycle' as their activity_type.

## Actual Behavior
The app sends every motion record object to the backend, regardless of the activity type.

```
{
  "id": 171314370,
  "company_id": 18561,
  "company_token": "trne",
  "device_id": 63046,
  "device_model": "iPhone14,5",
  "created_at": "2023-10-10T07:41:54.184Z",
  "framework": "react-native",
  "version": "17.0.2",
  "updated_at": "2023-10-11T12:41:40.474Z",
  "activity_type": "unknown",
  "activity_confidence": 100,
  "battery_level": 0.949999988079071,
  "battery_is_charging": false,
  "extras": {},
  "is_moving": true,
  "age": 45,
  "odometer": 168.3,
  "uuid": "09A81DD3-0D94-4278-B65E-4C6F86632F75",
  "timestamp": "2023-10-10T06:51:30.000Z",
  "speed_accuracy": 0.62,
  "speed": 1.77,
  "longitude": -76.73106589336492,
  "ellipsoidal_altitude": 114.1,
  "floor": null,
  "heading_accuracy": 20.85,
  "latitude": 64.1257498406627,
  "accuracy": 4.7,
  "altitude_accuracy": 3.5,
  "altitude": 67,
  "heading": 7.42,
  "recorded_at": "2023-10-10T06:51:30.000Z"
}

```

## Steps to Reproduce

1. Follow this post [Background Geolocation Console](https://transistorsoft.medium.com/background-geolocation-console-45796532c2ee) to make sure all data from the app goes to the testing backend.
2. Jump into a car, train, bus, then have a walk, cycle or run for a bit, and let the plugin record and send the data to the backend.
3. Check every row that you get on the backend.

## Context
I'm sending only records with the 'in_vehicle' activity type to the backend, while excluding records from 'walking' activity types due to privacy concerns. The primary focus is on 'in_vehicle' activity.

## Debug logs

[Logs](https://gist.github.com/trne/4290887644976cbe8bd5ae5a85033ce2)

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by trne** [comment]
@christocracy is this even possible?

**Comment by christocracy** [comment]
No

**Comment by trne** [comment]
and is that due to a limitation on the native APIs @christocracy ?

**Comment by trne** [comment]
@christocracy what would you think if onLocation we just nullify the `url` if the type of movement is not the one we are interested on? I tried that out and works, but seems to me a bit odd. I'd rather just not send it and have that control at a native level than triggering a void post every now and again. I'm just unsure of the technical limitations.

**Comment by christocracy** [comment]
Won't work.  Listen to onMotionChange:  when the activity type is undesirable, call .changePace(false) to place the plug-in back into stationary state.

**Comment by trne** [comment]
closing as the last message on this thread solves the problem.
