### ISSUE TITLE
[EXPO] android eas always build fail with :app:checkDebugDuplicateClasses

### ISSUE THREAD

**Issue by socheatleang** [transistorsoft/react-native-background-geolocation#1863]
After upgrade to the latest version **4.14.3**, For android, I got error while build with eas. iOS is working fine.

## Your Environment
* Plugin version: 4.14.3
* Platform: Android
* EXPO version: 48.0.0
* EXPO Build: eas
* React Native version (`react-native -v`):  0.71.8
* Package.json config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.8",
    "expo": "^48.0.0",
    "react-native-background-fetch": "^4.2.1",
    "react-native-background-geolocation": "^4.14.3",
```

## Expected Behavior

Upgrade to the latest version and build successfully with all platforms.
## Actual Behavior

Our current version was **^4.12.1**, We upgraded to the latest version(^4.14.3) of react-native-background-geolocation. Unfortunately, we can't past the android's build. We are using eas build. Then we tried to change to several version of the react-native-background-geolocation, we still got the same error with android. Then we roll back to our previous version **^4.14.3**, it says the same error. 

## Steps to Reproduce

1.  `eas build --profile development`
2.
3.
4.

## Context

We also tried to build with clear cache option
`eas build --profile development --clear-cache`

## Debug logs

<details><summary>Exception</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

-----------

* What went wrong:

Execution failed for task ':app:checkDebugDuplicateClasses'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable

   > Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)

     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)

     

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

==============================================================================

2: Task failed with an exception.

-----------

* What went wrong:

java.lang.StackOverflowError (no error message)

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 56s
```

</details>

**Comment by superyarik** [comment]
i use "4.14.2" version with SDK48 and my devbuilds works fine.

my build profile:
```
"development": {
    "developmentClient": true,
    "distribution": "internal",
    "channel": "staging",
    "android": {
        "buildType": "apk"
    }
},
```

**Comment by socheatleang** [comment]
@superyarik Thanks for replied. My config is the same you. 
@christocracy Do you have any input ?

**Comment by andreirat** [comment]
I'm having the same issue.

`Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
`

**Comment by christocracy** [comment]
This plugin [imports `workmanager`](https://github.com/transistorsoft/react-native-background-geolocation/blob/285e6080b944ecff50f7095cf842f4d7fbc70988/android/build.gradle#L100). One of your *other* plugins *also* imports `workmanager`.

This plugin's default `workmanager` version is [`2.8.1](https://github.com/transistorsoft/react-native-background-geolocation/blob/285e6080b944ecff50f7095cf842f4d7fbc70988/android/build.gradle#L27)

You can control the version this plugin uses with the `ext` var [`workVersion`](https://github.com/transistorsoft/react-native-background-geolocation/blob/285e6080b944ecff50f7095cf842f4d7fbc70988/android/build.gradle#L98)

**Comment by christocracy** [comment]
- [`2.8.1` is the latest stable version](https://maven.google.com/web/index.html?q=work#androidx.work:work-runtime), released on `3/22/2023`
- [`2.7.1` was released 11/17/2021](https://maven.google.com/web/index.html?q=work#androidx.work:work-runtime:2.7.1)

**Comment by socheatleang** [comment]
@christocracy  thanks for your respond. Now we downgrade for 2.7.1 by using workversion. 

However if we downgraded it, is there anything effect to the performance of the background geolocation lib?

**Comment by andreirat** [comment]
@christocracy Thank you for your help, it fixed the problem.

**Comment by christocracy** [comment]
> is there anything effect to the performance of the background geolocation lib?

I have no idea.  I doubt it.  If you're concerned about it, I suggest you discover which other module is requiring the older version then take it up with them.
