### ISSUE TITLE
Stopped tracking after a day.CLarity on How to track location 24/7 all time in any app state till app is unistalled, which method and how exactly can i get this

### ISSUE THREAD

**Issue by Vijay-CareAllianz** [transistorsoft/react-native-background-geolocation#1865]
## Your Environment
* Plugin version: ^4.14.3
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
  async function BackGroundLocation2 () {
    //works even when phone is locked 
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH, 
      distanceFilter: 10,
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    }).then(state => {
      // console.log('- BackgroundGeolocation is ready: ', state);
      BackgroundGeolocation.start();
      BackgroundGeolocation.getCurrentPosition().then((res)=>{
        console.log('res',res.coords)
        updateinDB(res.coords.latitude,res.coords.longitude)
      })
    }).catch(error => {
      console.warn('- BackgroundGeolocation error: ', error);
    });
  }
  useEffect(()=>{
    const getPermissions = async () => {
      const backgroundgranted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_BACKGROUND_LOCATION,
        {
          title: 'Background Location Permission',
          message:
            'We need access to your location ' +
            'so you can get live quality updates.',
          // buttonNeutral: 'Ask Me Later',
          // buttonNegative: 'Cancel',
          // buttonPositive: 'OK',
        },
      );
      if (backgroundgranted === PermissionsAndroid.RESULTS.GRANTED) {
        //do your thing!
        ReactNativeForegroundService.add_task(
          () => {
            // BackgroundGeolocation1();
            BackGroundLocation2();
          },
          {
            delay: 300000,
            onLoop: true,
            taskId: 'taskid',
            onError: (e) => console.log('Error logging:', e),
          },
        );
      }
    }
    getPermissions();
  },[]) 
```
## Expected Behavior

Should track every 5 mins (or given frequency) in any app state(app killed, app in background or phone locked) for unlimited time 
## Actual Behavior

Stopped working after 1 day ( 12 hrs to be precise)

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
When you call .start(), the plug-in will track the device forever, until told to .stop().

The plug-in only tracks when the device is detected to be moving.

Read the wiki "Philosophy of Operstion".

**Comment by christocracy** [comment]
Also see wiki "Debugging".  For device-specific issues, see https://dontkillmyapp.com

**Comment by DeveloperMCD** [comment]
The website you posted doesn't seem to exist. Are you saying it's not something we developers can control? I'm on iOS and it seems iOS is pausing the app's execution about 5 min. after it's sent to the background. Can we do something about this, or not?

**Comment by christocracy** [comment]
>The website you posted doesn't seem to exist.

It works fine for me.

>Are you saying it's not something we developers can control?

Yes.

> I'm on iOS and it seems iOS is pausing the app's execution about 5 min. after it's sent to the background. Can we do something about this, or not?

I carry a number of devices around with me everywhere I go, for *years*.  I do not have a problem with my devices tracking me.  

### iPhone 15 Pro @ 17.0.3

<img width="872" alt="Screenshot 2023-10-30 at 2 35 44 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/594e3345-2984-422c-a7ef-b0cfbb4ce791">


### Google Pixel 6 @ 14

<img width="1080" alt="Screenshot 2023-10-30 at 2 36 17 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/f9ce68ec-6284-4735-8c69-13e7537167f0">

**Comment by christocracy** [comment]
Have you read the wiki "Philosophy of Operation"?  This plug-in tracks the device only when the device is detected to be moving.  When the device is stationary, there is no location recorded.
