### ISSUE TITLE
Sometimes the geofence service stops. (I'm not sure. I'm guessing.) I have to restart the phone for it to work.

### ISSUE THREAD

**Issue by cuneytmedetoglu** [transistorsoft/react-native-background-geolocation#1869]
We create a geofence for an area where we provide latitude, longitude and radius information. It works fine for a while. However, there is a problem that we do not know what it is. After the problem occurs, it cannot be solved without restarting the phone. Even if we delete and create Geofence again, it is not resolved. It gets fixed after restarting the phone. We do not know whether we are creating this problem or whether it is related to the Android operating system. Can you help with the issue?
**Note:** We are sure that we have made all the necessary settings for the application to run in the background. https://dontkillmyapp.com/

## Your Environment
* Plugin version: 4.12.0
* Platform: Android
* OS version: Android 10
* Device manufacturer / model: OnePlus / OnePlus 5T
* React Native version (`react-native -v`): 0.66.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // Geolocation
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10,
      locationAuthorizationRequest: 'Always',
      autoSync: true,
      maxDaysToPersist: 14,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      preventSuspend: true,
      disableMotionActivityUpdates: true,
      foregroundService: true,
      httpRootProperty: '.',
      geofenceTemplate:
        '{"transition":"<%= geofence.action %>", "endpoint":"<%= geofence.identifier %>" }',
      notification: {
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
      },
      url: provider.configs.environments[appConfig.env] + apiUrls.endpointClients.handleTransition,
      headers: {
        authorization: 'Bearer ' + accessToken,
      },
```

## Expected Behavior
What needs to happen is that geofence actions can continue to work without the need to restart the phone.

## Actual Behavior
Geofence actions not working without restarting the phone.

## Steps to Reproduce

1.We don't know how the problem occurs. That's why we can't tell you the steps to repeat.

## Debug logs

We could not reproduce the problem in a way that we could get a log. We were able to observe that it occurs on the phones we use daily. The problem does not always occur.

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
We don't have any logs yet.
```

</details>

**Comment by christocracy** [comment]
I've been testing geofences on a variety of devices for years.  I often don't interact with these devices for weeks / months and geofences continue to fire.

Geofences don't get "stale".
