### ISSUE TITLE
Crash on android: com.transistorsoft.locationmanager.service.GeofencingService.a

### ISSUE THREAD

**Issue by andreshsingh** [transistorsoft/react-native-background-geolocation#1872]
We are experiencing crash on android when geofencing is active and the app is in background.

## Your Environment
* Plugin version:
   "react-native-background-fetch": "^4.2.1",
    "react-native-background-geolocation": "^4.14.3",
* Platform: Android
* OS version: android 14
* Device manufacturer / model: google pixel 7
* React Native version (`react-native -v`): 0.72.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready({
      // Geolocation Config
      startOnBoot: true,
      preventSuspend: true,
      stopOnTerminate: false,
      geofenceModeHighAccuracy: true,
      locationAuthorizationRequest: 'Always',
      disableLocationAuthorizationAlert: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      backgroundPermissionRationale: {
        title: "{applicationName} needs access to location data to enable the GPS tracking feature even when the app is closed or not in use",
        message: "Your location is only tracked while you are on the clock. Please enable {backgroundPermissionOptionLabel} location permission",
        positiveAction: "Change to {backgroundPermissionOptionLabel}",
        negativeAction: "Cancel"
      },
      notification: {
        largeIcon: 'drawable/ic_notification',
        smallIcon: 'drawable/ic_notification'
      },
    })
```

## Expected Behavior

Expected the app to record geofencing and function properly.

## Actual Behavior

The app crashes in background.

## Steps to Reproduce

1. Start geofences
2. Use another app when the app is in background

## Context

So the way we use this plugin is tracking the geofences and read the exit/entry events to create more geofences. So the app is supposed to track the user's exit on a geofence and create another circular geofence.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
com.transistorsoft.locationmanager.service.GeofencingService.a
java.lang.NullPointerException - Attempt to invoke virtual method 'boolean com.transistorsoft.locationmanager.geofence.TSGeofence.isPolygon()' on a null object reference
```

</details>

**Comment by Mike-Becatti** [comment]
This appears to be happening on a Pixel 7 too, but we haven't captured the error in Crashlytics yet for that device.  It seems to happen when stationary after a period of movement.  It doesn't happen very consistently but enough that we are delaying the release of our app.  We will continue to try and gather more information for you.

**Comment by christocracy** [comment]
I have a fix for this in the [private repo](https://github.com/transistorsoft/react-native-background-geolocation-android), branch `release-4.14.4`.

**Comment by andreshsingh** [comment]
do you have plans to release it any time soon ? @christocracy

**Comment by christocracy** [comment]
Customers should be using the private repo for access to latest updates instead of installing from npm.

**Comment by andreshsingh** [comment]
ok i'll work on using the private repo, thanks!

**Comment by onizam95** [comment]
@christocracy how can i access the private-repo my organisation has license.

**Comment by christocracy** [comment]
Ask the product admin to login to the Customer Dashboard and grant you access.
