### ISSUE TITLE
Getting some old location's coordinates occasionally, While tracking a vehicle

### ISSUE THREAD

**Issue by General-user** [transistorsoft/react-native-background-geolocation#1878]
<img width="595" alt="Screenshot 2023-11-13 at 8 55 26 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/72902599/efab42ba-7660-427b-8824-d5927114cbee">

Above is the screenshot of incorrect polylines on google map due to this plugin giving old (wrong locations) updates accidentally.

## Your Environment
* Plugin version: 4.4.6
* Platform: iOS or Android
* OS version: any
* Device manufacturer / model: any
* React Native version (`react-native -v`): 0.66.3
* Plugin config :
const state: State = await BackgroundGeolocation.ready({
      // Debug
      reset: true,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      geofenceModeHighAccuracy: true,
      geofenceProximityRadius: 8000,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      disableElasticity: true,
      stopTimeout: 5,
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title:"Allow {applicationName} to access this device's location even when closed or not in use.",
        message:'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      },
      url: `${configObject?.API_URL}/api/Tracking/RawLocationDetail`,
      // HTTP & Persistence
      autoSync: true,
      maxDaysToPersist: 14,
      batchSync: false,
      // Application
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,

      authorization: {
        strategy: 'JWT',
        accessToken: token,
      },

      params: {
        // <-- Optional HTTP params
        loadID_lng: loadID_ids,
        loadPhoneNumber_chr: driverPhoneNumber_chr,
        calling_UserID_chr: 'admin',
        isEnteredInPickupGeoFence_ysn: isEnteredInPickUp,
      },
    });

    setOdometer(state.odometer);
    setEnabled(state.enabled);
    setIsMoving(state.isMoving || false); // <-- TODO re-define @prop isMoving? as REQUIRED in State
  };
## Expected Behavior
I want each location's coordinates updates exactly like my vehicle moving (same route)

## Actual Behavior
but in some cases, I am getting old location coordinates accidentally... pleases help me on this.

## Steps to Reproduce
I do not know how to reproduce it.

## Context
To Track my vehicle with its actual coordinates, and then i am drawing polylines on google map

**Comment by christocracy** [comment]
I do not understand what your screenshot means.

> Plugin version: 4.4.6

See the CHANGELOG to learn about the latest version.

> Platform: iOS or Android
> OS version: any
> Device manufacturer / model: any

This is unhelpful and lazy information.

**Comment by christocracy** [comment]
> plugin started giving me some old locations coordinates 

From *where* are these "old" coordinates witnessed?  Locally on the device via `onLocation` or data at your server?

**Comment by General-user** [comment]
I am having distanceFilter: 50, so after every ping of .onLocation() I am saving this data (with coordinates of course) in my database.

so i think, its happening Locally on the Device via onLocation.

*This issue is not happening with each and every Tracking, Only for some Trackings occasionally.

please help or suggest something. @christocracy

**Comment by christocracy** [comment]
I have no idea what your problem is.  I don't suspect this is a problem of the plugin.

**Comment by Vivek-100** [comment]
Hello Chris,

Issue is we are getting geolocation coordinates from the plugin after specific interval.
And plugin provides correct coordinates most of the time, but randomly we get coordinates of previous location ( user was at that location at some other time but not at that specific time). And we use these coordinates to draw the path and when we get previous coordinates it causes the path the be distorted in the map.

So our suspicion is may be plugin is sending the coordinates correctly but sometimes if it misses to send the coordinates for specific time, it caches it and try again and other time, which causes the coordinates to come out of order to us. We want to know is there something like can happen.|

Please let me know if that helps.

Thank you!

**Comment by christocracy** [comment]
I have no idea what your problem is.  Nobody else is reporting this.

**Comment by Vivek-100** [comment]
Well we are getting this a lot. 
Is there anything in the plugin which re-try to resend the coordinates if those are missed at first place?

**Comment by christocracy** [comment]
The plug-in always attempts to upload records found in its SQLite database until Config.maxDaysPersist causes them to be destroyed.

The timestamp of persisted records does not change.
