### ISSUE TITLE
BackgroundGeolocation.onHttp() and the related POST to server stops running

### ISSUE THREAD

**Issue by uppersap** [transistorsoft/react-native-background-geolocation#1879]
Plugin version: "^4.13.1"
Platform: Android
Android version: 12
Device manufacturer / model: Samsung A13
React Native version (react-native -v): "~0.70.8"
Plugin config

const initBackground = async () => {

        const onHttp = BackgroundGeolocation.onHttp((event) => {
            console.log('[onHttp]', event);
        });

        const onActivityChange = BackgroundGeolocation.onActivityChange((event) => {
            console.log('[onActivityChange]', event);
        });

        const onGeofence = BackgroundGeolocation.onGeofence((event) => {
            console.log('[onGeofence]', event);
        });

        let oCSRFT = await CSRV2.gCSRFT(`${H_U}/TEST/odata/SAP/ZGWY_GEOLOCATABLE_OBJECT_SRV/geolocatableObjects`),
            aStartedTrip = JSON.parse(await getStorageStartedTrip()),
            sCookies = await Cklib2.bldCkHdr(); 

        let body = {
            objectNumber: aStartedTrip[0].transportKey,
            time: `\/Date(${Date.now()})\/`
        };

        // console.log('cookies tracking: ', { 'x-csrf-token': oCSRFT.data, 'cookiesFinal': sCookies })
        // console.log('oParameters.geolocationFrecuency: ', oParameters.geolocationFrecuency);
        // console.log('cookies bldCkHdr : ', sCookies);

        /// 2. ready the plugin.
        BackgroundGeolocation.ready({
            // Debug
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            // Geolocation
            desiredAccuracy: Platform.OS === 'android' ? BackgroundGeolocation.DESIRED_ACCURACY_HIGH : BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: Number(oParameters.geolocationFrecuency),
            stopTimeout: Number(oParameters.reactivateAppAfterPeriod),
            // HTTP & Persistence
            batchSync: false,
            autoSync: true,
            locationTemplate: '{"latitude": "<%= latitude %>","longitude":"<%= longitude %>"}',
            method: "POST",
            // url: `https://53b4-45-189-108-72.ngrok-free.app/locations`,
            params: body,
            headers: {
                "Accept": "application/json",
                "Content-Type": "application/json",
                "Cookie": sCookies,
                "x-csrf-token": oCSRFT.data,
            },
            locationAuthorizationRequest: 'Always',
            autoSyncThreshold: 1,
            httpRootProperty: ".",
            persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
            disableProviderChangeRecord: true,
            // Application
            notification: {
                sticky: true,
                title: 'Chofer',
                text: 'Seguimiento por GPS activado'
            },
            stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true,     // <-- Auto start tracking when device is powered-up.
            enableHeadless: true,
            // preventSuspend: true
        }).then(async (state) => {
            console.log('state bg: ', state);
            if (!state.enabled) {
                console.log('activar start bg');
                BackgroundGeolocation.start();
            }
        });

        return () => {
            onHttp.remove();
            onActivityChange.remove();
            onGeofence.remove();
        };
    }; ### 

Additional index.js

let HeadlessTask = async (event) => {
   console.log('HeadlessTask : ', event);
    switch (event.name) {
        case 'location': 

            break;
        case 'http':
            console.log('[HTTP] :', event);
            break;
    }
}

BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

### **Expected Behavior**
I would expect [onHttp] to keep running and the change in location to keep getting posted to the server.

### **Actual Behavior**
After a while, I keep seeing the console.log("[location] ", location); when debugging in the simulator, but the console.log("[onHttp] ", response); stops, and as far as I can tell nothing is being sent to the server BE anymore.

### **Steps to Reproduce**
1. Start tracking
2. let it run logging
3. put app in the background as intended ( I just opened settings in the simulator for this test)
4. Wait ( I started this test at 16PM it ran fine for 40 minutes, after 40 minutes in the index.js, the HeadlessTask stopped printing the [http] response, when you finish and restart the backgroundgelocation, I start showing the query returning the http. It is required to know how to avoid or what steps to do so that at all times continues to send the coordinates to the [HTTP] server.

**### Context**
Trying to track a phone in the background. While drivers and other people are using it for other things.

It works great for a while, then for whatever reason, the phone seems to know the location to send, but the background task locks up and stops posting it to the server which defeats the whole point.

Toggling tracking on and off fixes this, but again the point is to track during a whole shift or run of things.

**Comment by christocracy** [comment]
See wiki "Debugging".  Learn to observe the plug-ins incredibly verbose logs.  Also search api docs "Logger".

**Comment by uppersap** [comment]
but it doesn't show me any error in the console, it just stops sending the posts to the server, after about 40 min it doesn't make a post and in the headlessTask it only prints the event.name of location and no longer of http.

**Comment by christocracy** [comment]
I don't care about your console.log.

I only care about the plug-ins own native logs.  Do as I said and learn to observe the plug-ins logs.
