### ISSUE TITLE
getCurrentPosition falls into success even if Location permission is off

### ISSUE THREAD

**Issue by siaxia** [transistorsoft/react-native-background-geolocation#1883]
## Your Environment
* Plugin version: 4.14.4
* Platform: iOS or Android: Android
* OS version: 11
* Device manufacturer / model: Samsung / Galaxy A50
* React Native version (`react-native -v`): 0.72.7
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1000000,
      stopTimeout: 15,
      isMoving: true,
      foregroundService: true,
      showsBackgroundLocationIndicator: true,
      stopOnTerminate: true,
      startOnBoot: false,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      locationAuthorizationRequest: 'WhenInUse',
      disableLocationAuthorizationAlert: true,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    });
```

## Expected Behavior
returns `failure` when `getCurrentPosition` is called with the **location** permission off 

## Actual Behavior
returns `success` with last location informations

![Screenshot_20231116-210028_Settings](https://github.com/transistorsoft/react-native-background-geolocation/assets/71017035/d12f3366-c143-4914-b672-495a2f475cf8)

`Location: {"extras":{},"battery":{"level":0.39,"is_charging":true},"activity":{"confidence":100,"type":"still"},"is_moving":true,"age":1429581,"uuid":"b49681ef-2b63-41ec-bd8b-015da08fe6b4","odometer":248.3000030517578,"coords":{"age":1429591,"ellipsoidal_altitude":57.7,"altitude":57.7,"altitude_accuracy":31.7,"heading_accuracy":10,"heading":352.36,"speed":0.48,"accuracy":18.1,"longitude":sameLongitude,"speed_accuracy":20,"latitude":sameLatitude},"timestamp":"2023-11-16T10:51:55.414Z"}
 LOG  Location: {"extras":{},"battery":{"level":0.39,"is_charging":true},"activity":{"confidence":100,"type":"still"},"is_moving":true,"age":1431256,"uuid":"e7575c13-fa2c-481f-bae1-4d1aba776390","odometer":248.3000030517578,"coords":{"age":1431259,"ellipsoidal_altitude":57.7,"altitude":57.7,"altitude_accuracy":31.7,"heading_accuracy":10,"heading":352.36,"speed":0.48,"accuracy":18.1,"longitude":sameLongitude,"speed_accuracy":20,"latitude":sameLatitude},"timestamp":"2023-11-16T10:51:55.414Z"}
 LOG  Location: {"extras":{},"battery":{"level":0.39,"is_charging":true},"activity":{"confidence":100,"type":"still"},"is_moving":true,"age":1433233,"uuid":"43d18b68-62e9-4974-b8de-3b8e46cea127","odometer":248.3000030517578,"coords":{"age":1433238,"ellipsoidal_altitude":57.7,"altitude":57.7,"altitude_accuracy":31.7,"heading_accuracy":10,"heading":352.36,"speed":0.48,"accuracy":18.1,"longitude":sameLongitude,"speed_accuracy":20,"latitude":sameLatitude},"timestamp":"2023-11-16T10:51:55.414Z"}
`

## Steps to Reproduce

1. I migrated my project into RN 0.72.6 from 0.68
2. And I upgraded version of react-native-background-geolocation 4.14.4 from 4.9.5
3. Expected behavior came out in former environment
4. Here's my code (I didn't change any of other logics of BackgroundGeolocation including this code after migration)
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.getCurrentPosition(
      {
        timeout: 10, // 30 second timeout to fetch location
        maximumAge: 0, // Accept the last-known-location if not older than 5000 ms.
        desiredAccuracy: 10, // Try to fetch a location with an accuracy of `10` meters.
        samples: 1, // How many location samples to attempt.
        // persist: false, // Defaults to state.enabled
      },
      (location: Location) => {
        console.log('Location: ' + JSON.stringify(location));
        location.mock && handleGPSAbuse('FAKE');
      },
      (error) => {
        console.log('ERROR: ' + error);
        error === 1 && handleGPSAbuse('PERMISSION');
      },
    );
```

**Comment by christocracy** [comment]
> returns success with last location informations

What's wrong with that?  See api docs Location.age to determine how old the location is.

**Comment by siaxia** [comment]
I mean, In my project
Location permission status was checked by getCurrentPosition - error(`LocationError`) code: 1
and it worked as I expected.

```javascript <!-- Syntax-highlighting:  paste your code below -->
/**
	* When native location API fails to fetch a location, one of the following error-codes will be returned.
	*
	* | Code  | Error                       |
    * |-------|-----------------------------|
    * | 0     | Location unknown            |
    * | 1     | Location permission denied  |  <--- this
    * | 2     | Network error               |
    * | 3     | Attempt to initiate location-services in background with WhenInUse authorization |
    * | 408   | Location timeout            |
    * | 499   | Location request cancelled  |
	*/
	type LocationError = 0 | 1 | 2 | 3 | 408 | 499;
```

but when I upgraded Library version from 4.9.5 to 4.14.4,
method returns success with old location without any error, even Location permission is off

I set options(`CurrentPositionRequest`)
maximumAge : 0
persist : false

I want to know that was expected behavior on this version(4.14.4).

**Comment by christocracy** [comment]
The new expected behaviour is to always return *at least* the last known location.  Use `Location.age` to determine the `age` in milliseconds of the returned location.

Listen to `onProviderChange` event to learn about location-provider changes (eg: location disabled, wifi disabled, etc).

**Comment by siaxia** [comment]
Oh, I understood.
I should change my code with `onProviderChange`.
thanks a lot ☺️
