### ISSUE TITLE
Google play store review raised Prominent disclosure not found

### ISSUE THREAD

**Issue by jingp-ofload** [transistorsoft/react-native-background-geolocation#1884]
We did add `backgroundPermissionRationale` in the config. But google review said `Prominent disclosure not found`.
## Your Environment
* Plugin version: 4.14.4
* Platform: Android
## Expected Behavior
Google review passes

## Actual Behavior
Google asked `Your app must display a prominent disclosure in a dialog that appears before your app’s location runtime permission. `

## Steps to Reproduce
1. Build app
2. Publish to google play store

**Comment by jingp-ofload** [comment]
I just saw the Alert.alert in demo repo. Sry for disturbing. Close this.

**Comment by christocracy** [comment]
You are responsible for "prominent disclosure".

See my blog:  https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353
