### ISSUE TITLE
The location state doesn't change from stationary to isMoving

### ISSUE THREAD

**Issue by alikargar1993** [transistorsoft/react-native-background-geolocation#1885]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 12 & 13
* Device manufacturer / model: Motorola & Xiaomi
* React Native version: 0.72.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 0,
    stopTimeout: 14,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,
    startOnBoot: true,
    batchSync: false,
    locationUpdateInterval: 1000,
    fastestLocationUpdateInterval: 1000,
    triggerActivities: 'in_vehicle, on_bicycle',
    isMoving: true,
    // disableStopDetection: true,
    allowIdenticalLocations: false,
    enableHeadless: true,
```

## Expected Behavior
The device is moving it works fine, then stops for several minutes(10 minutes or more). the device starts to move, the "stationary" should change to "isMoving" and I should be able to track the location again.

## Actual Behavior
The device is moving it works fine, then stops for several minutes(10 minutes or more). the device starts to move, but the location does not change. I have to reopen the App or move it to the foreground to be able to track the location.

## Steps to Reproduce

1. call `BackgroundGeolocation.start();`
2. call `BackgroundGeolocation.changePace(true);`
3. close/move the app to the background
4. start to move the device
5. stop moving the device
6. wait for 10 minutes or more
7. track the location, which does not update on the map

## Context
This App is for tracking some vehicles and we are trying to find where they stop and then start to move. Drivers can't work with the App while driving. they can just enable it at first and stop it at the end
I used "enableHeadless", which improves the condition, but the issue remains.
I have purchased the license key.

**Comment by christocracy** [comment]
> debug: false,

Set `true`.  Learn to listen to debug sound fx.

See wiki "Debugging" and learn to observe the plug-in's incredibly verbose logs.  Also search api docs "Logger".

**Comment by alikargar1993** [comment]
Hi, @christocracy. Sorry, I didn't get you. This is the release version. should also be enabled in release mode?

**Comment by christocracy** [comment]
So build a debug build and go field test.

**Comment by alikargar1993** [comment]
Ok, I will test it.
another question:
What will happen if I use `disableStopDetection: true`?
I read the doc and it says it affects the battery usage. Can it help to solve the issue?

**Comment by christocracy** [comment]
> Can it help to solve the issue?

No.  Your issue is likely specifically related to your device.  

Go outside and field-test.  Analyze your logs.

**Comment by alikargar1993** [comment]
The Battery optimization is off in all devices, I also checked it with Samsun A32, and the result is the same

**Comment by christocracy** [comment]
See https://dontkillmyapp.com.

Go outside and field test.  Analyze your logs.

**Comment by alikargar1993** [comment]
Can I use socket.io in the headless task to send the locations? when the App is closed?

**Comment by alikargar1993** [comment]
BTW, When I tried to export the logs, I faced this error:
[Android:java.lang.OutOfMemoryError: Failed to allocate a 23970828 byte allocation with 2097152 free bytes](https://stackoverflow.com/questions/32244851/androidjava-lang-outofmemoryerror-failed-to-allocate-a-23970828-byte-allocatio)

**Comment by alikargar1993** [comment]
11-21 10:17:46.252 25248 25248 D TSLocationManager: [c.t.l.service.AbstractService f] 
11-21 10:17:46.252 25248 25248 D TSLocationManager:   ⚙️︎  TrackingService.stopSelfResult(173): true
11-21 10:17:46.253 25248 25248 D TSLocationManager: [c.t.l.service.AbstractService onDestroy] 
11-21 10:17:46.253 25248 25248 D TSLocationManager:   🔴  TrackingService stopped

**Comment by alikargar1993** [comment]
> 11-21 10:17:46.252 25248 25248 D TSLocationManager: [c.t.l.service.AbstractService f] 11-21 10:17:46.252 25248 25248 D TSLocationManager: ⚙️︎ TrackingService.stopSelfResult(173): true 11-21 10:17:46.253 25248 25248 D TSLocationManager: [c.t.l.service.AbstractService onDestroy] 11-21 10:17:46.253 25248 25248 D TSLocationManager: 🔴 TrackingService stopped

it happened without touching the phone

**Comment by alikargar1993** [comment]
By opening the App starts to tracking:
11-21 10:19:38.597 25248 25398 W TSLocationManager: [c.t.r.RNBackgroundGeolocationModule ready] 
11-21 10:19:38.597 25248 25398 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
11-21 10:19:38.599 25248 25395 W ReactNativeJS: "default" is not a valid color or brush
11-21 10:19:38.599 25248 25398 D TSLocationManager: [c.t.l.u.LocationAuthorization withBackgroundPermission] 
11-21 10:19:38.599 25248 25398 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
11-21 10:19:38.624 25248  1699 I TSLocationManager: - Enable: false → true, trackingMode: 1
11-21 10:19:38.625 25248  1699 I TSLocationManager: [c.t.l.g.TSGeofenceManager start] 
11-21 10:19:38.625 25248  1699 I TSLocationManager:   🎾  Start monitoring geofences
11-21 10:19:38.628 25248  1699 D TSLocationManager: [c.t.l.http.HttpService startMonitoringConnectivityChanges] 
11-21 10:19:38.628 25248  1699 D TSLocationManager:   🎾  Start monitoring connectivity changes
11-21 10:19:38.632 25248  1699 D TSLocationManager: [c.t.l.device.DeviceSettings startMonitoringPowerSaveChanges] 
11-21 10:19:38.632 25248  1699 D TSLocationManager:   🎾  Start monitoring powersave changes
11-21 10:19:38.635 25248  1699 I TSLocationManager: [c.t.l.s.ActivityRecognitionService start] 
11-21 10:19:38.635 25248  1699 I TSLocationManager:   🎾  Start motion-activity updates
11-21 10:19:38.636 25248 25398 W TSLocationManager: [c.t.r.RNBackgroundGeolocationModule ready] 
11-21 10:19:38.636 25248 25398 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
11-21 10:19:38.640 25248 25395 W ReactNativeJS: "default" is not a valid color or brush
11-21 10:19:38.640 25248 25311 D TSLocationManager: [c.t.l.http.HttpService a] 
11-21 10:19:38.640 25248 25311 D TSLocationManager: ╔═════════════════════════════════════════════
11-21 10:19:38.640 25248 25311 D TSLocationManager: ║ 📶  Connectivity change: connected? true
11-21 10:19:38.640 25248 25311 D TSLocationManager: ╠═════════════════════════════════════════════
11-21 10:19:38.644 25248  1699 I TSLocationManager: [c.t.l.service.HeartbeatService stop] 
11-21 10:19:38.644 25248  1699 I TSLocationManager:   🔴  Stop heartbeat
11-21 10:19:38.653 25248  1699 I TSLocationManager: [c.t.l.service.TrackingService changePace] 
11-21 10:19:38.653 25248  1699 I TSLocationManager:   🔵  setPace: true → true
11-21 10:19:38.671 25248 25248 D TSLocationManager: [c.t.l.service.AbstractService a] 
11-21 10:19:38.671 25248 25248 D TSLocationManager:   🎾  START [TrackingService  startId: 1, eventCount: 1]
11-21 10:19:38.671 25248 25248 I TSLocationManager: [c.t.l.service.TrackingService k] 
11-21 10:19:38.671 25248 25248 I TSLocationManager: ╔═════════════════════════════════════════════
11-21 10:19:38.671 25248 25248 I TSLocationManager: ║ TrackingService motionchange: true
11-21 10:19:38.671 25248 25248 I TSLocationManager: ╠═════════════════════════════════════════════
11-21 10:19:38.672 25248 25248 D TSLocationManager: [c.t.l.service.AbstractService a] 
11-21 10:19:38.672 25248 25248 D TSLocationManager:   ⚙️︎   FINISH [TrackingService startId: 1, eventCount: 0, sticky: true]
11-21 10:19:38.687 25248 25398 W TSLocationManager: [c.t.r.RNBackgroundGeolocationModule ready] 
11-21 10:19:38.687 25248 25398 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
11-21 10:19:38.691 25248 25248 I TSLocationManager: [c.t.l.l.TSLocationManager a] 
11-21 10:19:38.691 25248 25248 I TSLocationManager: ╔═════════════════════════════════════════════
11-21 10:19:38.691 25248 25248 I TSLocationManager: ║ motionchange LocationResult: 5 (108267ms old)
11-21 10:19:38.691 25248 25248 I TSLocationManager: ╠═════════════════════════════════════════════
11-21 10:19:38.691 25248 25248 I TSLocationManager: ╟─ 📍  Location[fused 34.779123,48.518802 hAcc=21.6 et=+5d11h56m35s123ms alt=1911.800048828125 vAcc=3.3961225 vel=0.020403804], time: 1700549270424
11-21 10:19:38.692 25248 25248 D TSLocationManager: [c.t.l.l.TSLocationManager a] Median accuracy: 22.331
11-21 10:19:38.698 25248 25248 D TSLocationManager: [c.t.l.u.LocationAuthorization withPermission] 
11-21 10:19:38.698 25248 25248 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
11-21 10:19:38.739 25248 25248 D TSLocationManager: [c.t.l.service.AbstractService a] 
11-21 10:19:38.739 25248 25248 D TSLocationManager:   🎾  START [LocationRequestService  startId: 1, eventCount: 1]
11-21 10:19:38.742 25248  1699 I TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation] 
11-21 10:19:38.742 25248  1699 I TSLocationManager:   🔵  [SingleLocationRequest start, action: 1, requestId: 5]
11-21 10:19:38.744 25248  1699 D TSLocationManager: [c.t.l.service.AbstractService a] 
11-21 10:19:38.744 25248  1699 D TSLocationManager:   ⚙️︎   FINISH [LocationRequestService startId: 1, eventCount: 0, sticky: true]
11-21 10:19:38.787 25248 25398 W TSLocationManager: [c.t.r.RNBackgroundGeolocationModule ready] 
11-21 10:19:38.787 25248 25398 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
11-21 10:19:38.819 25248 25395 W ReactNativeJS: "default" is not a valid color or brush
11-21 10:19:38.869 25248 25248 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot] 
11-21 10:19:38.869 25248 25248 I TSLocationManager:   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
11-21 10:19:38.880 25248 25398 W TSLocationManager: [c.t.r.RNBackgroundGeolocationModule ready] 
11-21 10:19:38.880 25248 25398 W TSLocationManager:   ⚠️  #ready already called.  Redirecting to #setConfig
11-21 10:19:38.882 25248  1699 I TSLocationManager: [c.t.l.service.HeartbeatService stop] 
11-21 10:19:38.882 25248  1699 I TSLocationManager:   🔴  Stop heartbeat

**Comment by alikargar1993** [comment]
When the App is foreground I send data with socket.io to backend
and when the App is closed I use the headless task to do the same

**Comment by christocracy** [comment]
> TSLocationManager: ⚠️ #ready already called. 

.ready(config) is meant to be called only once, each time your app boots.  It's a signal to the plug-in that your App has launched and is "ready" to receive events from the plug-in.  

Why are you calling it multiple times?

> TSLocationManager: 🔴 TrackingService stopped

This is not unusual to see.  The plug-in tracks location when the motion api detects the device is in-motion.  When the device is stationary, location-services are turned off to conserve energy.

**Comment by alikargar1993** [comment]
It stops by itself.

**Comment by alikargar1993** [comment]
I mean it stops tracking the location after 10 minutes that I'm still and does not change to a moving state after I move the device. Yes, I have read it.

**Comment by christocracy** [comment]
Learn to use .emailLog and grab several days worth of logs.
