### ISSUE TITLE
Allow use_frameworks within Podfile

### ISSUE THREAD

**Issue by aksonov** [transistorsoft/react-native-background-geolocation#189]
It could be useful if app contains Swift-related code and/or other components that require use_framework option (like iOS XMPP Framework)

**Comment by jcity** [comment]
We have our own fork but I figured I'd post this for anyone else trying to do the same.

Changing the `RNBackgroundGeolocation.podspec` to the following seems to do the trick for us:

```ruby
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name                = 'RNBackgroundGeolocation'
  s.version             = package['version']
  s.summary             = package['description']
  s.description         = <<-DESC
    Cross-platform background geolocation module for React Native with
    battery-saving circular stationary-region monitoring and stop detection.
  DESC
  s.homepage            = package['homepage']
  s.license             = package['license']
  s.author              = package['author']
  s.source              = { :git => 'https://github.com/transistorsoft/react-native-background-geolocation-android.git', :tag => s.version }
  s.platform            = :ios, '8.0'

  s.dependency 'React'
  s.dependency 'RNBackgroundFetch'
  s.dependency 'CocoaLumberjack', '~> 3.0'
  s.preserve_paths      = 'docs', 'CHANGELOG.md', 'LICENSE', 'package.json', 'RNBackgroundGeolocation.js'
  s.source_files        = 'ios/RNBackgroundGeolocation/*.{h,m}'
  s.libraries           = 'sqlite3'
  s.vendored_frameworks = 'ios/RNBackgroundGeolocation/TSLocationManager.framework'

  s.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/../../node_modules/react-native-background-fetch/ios/RNBackgroundFetch"' }
end
```

Its probably not safe to assume `RNBackgroundFetch` is in the same place for everyone but maybe it is considering this is a React Native specific module.

**Comment by nevir** [comment]
Note the main thing here is that `React` and `RNBackgroundFetch` need to be made explicit dependencies in order for RNBG to compile as a framework - but it appears like `TSLocationManager` depends on `TSBackgroundFetch`, and it's not clear how to express that (private) dependency via cocoapods

**Comment by christocracy** [comment]
@nevir Correct.  `TSLocationManager` needs to see the symbol `TSBackgroundFetch`.
