### ISSUE TITLE
On iOS, is is possible to determine the state of the "Precise Location" toggle in the app location settings?

### ISSUE THREAD

**Issue by neilljordan** [transistorsoft/react-native-background-geolocation#1896]
## Your Environment
* Plugin version:
* Platform: iOS 
* OS version: 
* Device manufacturer / model: iPhone 13 mini / 17.1.2
* React Native version (`react-native -v`): 0.68.5
* Plugin config
```javascript
      BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
        distanceFilter: 10,
        preventSuspend: true,
        disableLocationAuthorizationAlert: true,
        reset: true,
        stopOnTerminate: false,
        startOnBoot: true,
        showsBackgroundLocationIndicator: false,
        debug: false,
        backgroundPermissionRationale: {
          message: '',
        },
      }
```

## Expected Behavior

Would like to be able to determine whether precise accuracy is enabled.

## Actual Behavior

I don't know how to determine whether precise accuracy is enabled.

**Comment by christocracy** [comment]
Yes.  See api docs event onProviderChange.

In fact, familiarize yourself with all 13 events.
