### ISSUE TITLE
in ios app does not give location ping in killed state 

### ISSUE THREAD

**Issue by Sarveshwins** [transistorsoft/react-native-background-geolocation#1898]
## Your Environment
OS: macOS 13.0
CPU: (8) arm64 Apple M2
Memory: 78.91 MB / 8.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
Yarn: 1.22.21 - ~/Documents/GitHub/alt-tomrex-app/node_modules/.bin/yarn
npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
Android SDK: Not Found
IDEs:
Android Studio: 2023.1 AI-231.9392.1.2311.11076708
Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
Languages:
Java: 15.0.2 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1
react-native: ^0.64.0 => 0.64.4
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

* Plugin version: ^4.12.1
* Platform: iOS 
* OS version:
* Device manufacturer / model: iphone 13 pro max 
* React Native version (`react-native -v`): ^0.64.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
after kill the app covering 250 meters it should have give location coordinates frequently

## Actual Behavior
but after covering 250 meters it has given only few corodinates in 1 km you can say only 4-5 point 

## Steps to Reproduce
just kill the app and start convering distance (iphone)

## Context
track location with precision

<img width="1240" alt="Screenshot 2023-12-18 at 11 18 42 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/82214917/91444352-cbbf-47ae-930b-321bed2db030">

**Comment by vonkanehoffen** [comment]
Have you checked what location permissions you have granted? If the app's killed, it would need "Always" to carry on receiving updates

**Comment by Sarveshwins** [comment]
> Have you checked what location permissions you have granted? If the app's killed, it would need "Always" to carry on receiving updates

yes i have given "allow all the time" location permission

**Comment by christocracy** [comment]
See wiki "Debugging".  Learn to fetch logs from the plug-ins database using .emailLog.  Also search API docs "Logger".

**Comment by prabhash-c** [comment]
Did you get this to work? 

@Sarveshwins 
@christocracy 

I am facing a similar issue. Any help is appreciated, happy to pay for your time or anyone else who can help me fix this issue. Urgent for me.
