### ISSUE TITLE
Check location services permission on iOS

### ISSUE THREAD

**Issue by jenshandersson** [transistorsoft/react-native-background-geolocation#190]
## Your Environment
* Plugin version: 1.6.0
* Platform: iOS
* OS version: 10.2
* Device manufacturer / model: iOS Simulator iPhone 6
* React Native version (`react-native -v`): 0.38.0
* Plugin config: 
```
const config = {
  desiredAccuracy: 100,
  stationaryRadius: 100,
  distanceFilter: 50,
  useSignificantChangesOnly: false,
  disableMotionActivityUpdate: true,
  stopTimeout: 1,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  stopOnTerminate: false,
  startOnBoot: true,
};
```

## Expected Behavior
If a user approves location permissions on iOS and then goes to Settings and removes the permission the app shows this alert on every startup:
![simulator screen shot 13 jan 2017 12 01 24](https://cloud.githubusercontent.com/assets/1150467/21929458/7a8e307c-d988-11e6-8630-87434b845bdf.png)

## Steps to Reproduce

1. User allows location services (always)
2. User goes to Settings and removes the permission
3. User is always shown the Alert box

## Context
Since location services is optional in our app we don't want to force them to enable it. How can I go about this problem? Is there any way to check if the user has allowed or disallowed the location permissions?

**Comment by christocracy** [comment]
The plugin shows this alert whenever *you* ask the plugin to get the location.

If you don't want the alert, stop asking the plugin to get the location.

**Comment by jenshandersson** [comment]
Yes I get that, my question is if I can check if the user somehow has allowed/disallowed location services? I don't know to stop asking because they allowed it and they disallowed it.

**Comment by christocracy** [comment]
The solution will be to listen to the `providerchange` event.  However, the event `param` doesn't express the result of the `CLAuthorizationStatus`.  This information [*is* provided](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/ios/RNBackgroundGeolocation/RNBackgroundGeolocation.m#L454) to the `RNBackgroundGeolocationModule` from `TSLocationManager` so it's an easy task to provide this information.

**Comment by christocracy** [comment]
Try listening to the [`providerchange`](https://github.com/transistorsoft/cordova-background-geolocation/tree/master/docs#onproviderchangecallbackfn-failurefn)  event.

```Javascript
bgGeo.on('providerchange', function(event) {
  alert('providerchange, enabled: ' + event.enabled);
  if (event.enabled) {
    bgGeo.start();
  } else {
    bgGeo.stop();
  }
});
```

**Comment by christocracy** [comment]
There's probably one little hitch with this idea.  The plugin will still popup the Location-services alert.  I can simply add a method to *hide* the alert if you call `#stop`.

**Comment by jenshandersson** [comment]
Thanks @christocracy, I will check it out. One suggestion would be to include the authorization status in the state? Thanks for the help!
