### ISSUE TITLE
Dynamic value on `extras`

### ISSUE THREAD

**Issue by premdasvm** [transistorsoft/react-native-background-geolocation#1905]
## Your Environment
* Plugin version: 4.14.2
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung Galaxy S22
* React Native version (`react-native -v`): 0.72.5 / Expo 49
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
await BackgroundGeolocation.ready({
  /// Debug
  reset: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,

  /// Geolocation
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
  distanceFilter: 50,
  stopTimeout: 5,

  /// Application
  stopOnTerminate: false,
  startOnBoot: true,
  enableHeadless: true,

  /// Notification
  notification: {
    title: "Field Sync",
    text: "Field Sync app is tracking your location in background.",
  },

  /// Permissions
  locationAuthorizationRequest: "Always",
  backgroundPermissionRationale: {
    title: "Allow {applicationName} to access this device's location even when closed or not in use.",
    message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
    positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
    negativeAction: "Cancel",
  },

  // // HTTP & Persistence
  url: `${Env.API_URL}v1/location`,
  autoSync: true,
  autoSyncThreshold: 5,
  batchSync: true,
  headers: {
    Authorization: `Bearer ${useAuth.getState().token?.access}`,
  },
  extras: {
    shift_id: useUser.getState().currentShift?.shift.id || 0,
  },
});

return state;

```

## Expected Behavior
Pass a dynamic value on the `extras` object to the backend service.

## Actual Behavior
Only the value passed in while initialising the plugin get sent to backend.

## Steps to Reproduce

1. App with the above config calls `start()` then `changePace(true)`
2. New location gets send to backend, but the `shift_id` in extras stays the same. 

## Context
I need to send the `shift_id` dynamically, if the user has 2 shifts, when he `CheckIn` i start the background service, when he `CheckOut` i stop the service, then when he is starting his second shift, the `shift_id` changes, when he `CheckIn` on the second shift, i need the id of second shift to be passed on `shift_id` object.

**Comment by premdasvm** [comment]
@christocracy Got it, thanks for the quick reply! I missed that detail in the API doc earlier.

**Comment by premdasvm** [comment]
Quick question, @christocracy: Although I've included the notification object in my config, my app doesn't display the background running notification. Here's what I've used:

```js
notification: {
    title: "Field Sync",
    text: "Field Sync app is tracking your location in background.",
},
```
Could I be missing a step? i'm using `expo-dev-client`

**Comment by christocracy** [comment]
The notification is activated only when the device is detected to be moving, which typically takes about 200 meters of movement.

You can manually change to the moving state by calling .changePace(true), as described in the wiki here "Philosophy of Operation".

**Comment by premdasvm** [comment]
@christocracy I do call `.changePace(true)` for testing purposes, i'm using lockito app for mocking location changes.

**Comment by christocracy** [comment]
Check the notification settings in Android settings.
