### ISSUE TITLE
how to increase location accuracy in ios

### ISSUE THREAD

**Issue by Sarveshwins** [transistorsoft/react-native-background-geolocation#1906]
## Your Environment

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 80.98 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.21 - ~/Documents/GitHub/alt-tomrex-app/node_modules/.bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11076708
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.64.0 => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

* Plugin version: ^4.12.1
* Platform: iOS or Android: iOS
* Device manufacturer / model: iphone 13 pro max
* React Native version (`react-native -v`): ^0.64.0

## Expected Behavior
as im walking with app open  i want as much as possible  accurate location of the device 

## Actual Behavior
as im walking on the tarace of this building with app open but it should have given me the location of where im walking but it also have given me near by place as well this is not expected to occur as you can see in this img .
<img width="804" alt="Screenshot 2023-12-21 at 12 04 33 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/82214917/e61a647d-49e6-40c6-ba85-4ec1c4f528d8">

## Steps to Reproduce
make app foreground and walk 

## Context
i want get as much as possible accurate location the device . how can i improve the location accuracy in iphone .  
 And if there is a difference in actual location and the location it provide by any chance then how the difference range is ??

**Comment by christocracy** [comment]
Go outside for a 1km walk **away from the building.**
