### ISSUE TITLE
Clarity on distance filter to optimise the battery

### ISSUE THREAD

**Issue by batchuramesh** [transistorsoft/react-native-background-geolocation#1907]
## Your Environment
* Plugin version: Demo App (React Native Background Geolocation)
* Platform:  Android
* OS version: 11
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

By increasing the distance filter value device's location in the most battery-efficient manner

## Actual Behavior

By applying various distance filter values tested (https://tracker.transistorsoft.com/Techcraft) on the Demo app (https://play.google.com/store/apps/details?id=com.transistorsoft.backgroundgeolocation.react) however unable to understand the right value that provides the most battery-efficient settings. Noticed that increasing the distance filter when the person is in. motion hasn't reduced the battery consumption. The attached image has the test observation hence request you to tell us what the recommended distance filter value is to be used in the App for better battery consumption. 

<img width="790" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/136320233/68bfb017-420b-464e-be39-8a9a526a28e0">

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
distanceFilter has little effect upon power consumption.  The location radios (wifi, gps, cellular) remain powered up constantly -- distanceFilter merely controls the rate that locations are plucked out of the radio streams.

What does have more effect upon power are http requests, which consume more energy/second than gps (it takes more energy to generate a carrier wave on the cellular radio to about upstream than it does to power a radio receiver to listen to a gps radio stream).  If you make an http request with each location, you will consume more power with a low distanceFilter vs high.

Read the api docs "HTTP Guide" to learn about queuing http request with Config.autoSync, Config.batchSync and Config.maxBatchSize
