### ISSUE TITLE
Obtaining the current location sometimes taking 5-10 minutes after the retrieval of the previous location.

### ISSUE THREAD

**Issue by SurajMohanty02** [transistorsoft/react-native-background-geolocation#1908]
Obtaining the current location may take 5-10 minutes after the retrieval of the previous location.

## Your Environment
* Plugin version: 4.14.5
* Platform: iOS or Android Android
* OS version: 10
* Device manufacturer / model: Oppo
* React Native version (`react-native -v`): 0.67.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 const st = await BackgroundGeolocation.ready({
    distanceFilter: 50,
    debug: true,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    locationUpdateInterval: 30000,
    stopOnTerminate: false,
    isMoving: true,
    stopOnStationary: false,
    persistMode: BackgroundGeolocation.PERSIST_MODE_NONE,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    // stopTimeout: 1440,

  })
  for (let i = 0; BackgroundService.isRunning(); i++) {

 BackgroundGeolocation.getCurrentPosition({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      samples: 4,
      persist: false,

    }).then(async (pos) => {
      // console.log(pos, "pos")

 let last_timestamp = await getData("recent-timestamp");
      if (last_timestamp == pos.timestamp) {
        let event = await BackgroundGeolocation.getState();
        if (!event.isMoving) {
          // console.log("chekcing state")
          await BackgroundGeolocation.setConfig({ isMoving: true, stopOnStationary: false, });

        }
      }
      await setData("recent-timestamp", pos.timestamp);

  ).catch(async er => {
      
    })


    await sleep(delay);
  }
```

## Expected Behavior

It should give coordinate each 30 sec and it should be unique
## Actual Behavior

It is not giving coordinate each 30sec and sometime there is a gap of 5-10 minutes between previous and latest coordinate even foreground service is running.
## Steps to Reproduce

1.Travel a distance of at least 30 km+
2.Upon reaching your destination Leave the device idle for 2 continuous hours
3.After that turn on your screen and remain idle for 15 to 30 minutes
4.Return to your home location or travel to a different location (at least 30 km away)

## Context

I'm trying to track user location each 30 sec even screen is off and should get unique coordinates each time while user is travelling.
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
{
"date": "2023-12-26",
"ui_created_on": "2023-12-26 17:57:05.641",// plugin timestamp
"battery_level": 0.36,
"latitude": "21.3917639",
"accuracy": "High",
"sample": false,
"speed": 2.65,
"mode": "Online",
"created_on": "Dec 26, 2023 6:22:04 PM",// Backend timestamp
"provider": "",
"activity_type": "still",
"accuracy_in_meters": 10.3,
"mock": false,
"operation": "",
"username": "devratna_s",
"longitude": "79.3070601",
"is_moving": true
},
{
"date": "2023-12-26",
"ui_created_on": "2023-12-26 17:57:05.641",
"battery_level": 0.36,
"latitude": "21.3917639",
"accuracy": "High",
"sample": false,
"speed": 2.65,
"mode": "Online",
"created_on": "Dec 26, 2023 6:19:55 PM",
"provider": "",
"activity_type": "still",
"accuracy_in_meters": 10.3,
"mock": false,
"operation": "",
"username": "devratna_s",
"longitude": "79.3070601",
"is_moving": true
},
{
"date": "2023-12-26",
"ui_created_on": "2023-12-26 17:57:05.641",
"battery_level": 0.36,
"latitude": "21.3917639",
"accuracy": "High",
"sample": false,
"speed": 2.65,
"mode": "Online",
"created_on": "Dec 26, 2023 6:17:29 PM",
"provider": "",
"activity_type": "still",
"accuracy_in_meters": 10.3,
"mock": false,
"operation": "",
"username": "devratna_s",
"longitude": "79.3070601",
"is_moving": true
},

```

</details>

**Comment by christocracy** [comment]
The plug-in is not interested in fetching location while in the stationary state.

The plug-in is only interested in tracking location when the device is detected to be moving.

You should not trust timers while the plug-in is in the stationary state (or your odd `for` loop where your calling `.sleep()`.  While in the stationary state, your app is subject to doze mode of the OS.

If you want periodic location updates while the the device is stationary, use background-fetch (already imported as a dependency).  See its readme.

**Comment by mgravindran** [comment]
@christocracy - We have a capacitor app using the capacitor-background-geolocation to fetch current location (in stationary mode) as well real time location tracking and geofencing. We have been facing a similar issue with fetching current location (in stationary mode) - either it takes very long or fails.
Do you recommend to a use an alternate approach to fetch current location or use this plugin only for live location tracking ?

**Comment by christocracy** [comment]
Use background-fetch for any kind of periodic tasks, such as calling .getCurrentPosition

background-fetch is already installed.  See its readme.
