### ISSUE TITLE
Appstore Rejected my app due to UIbackgroundModes, Need help

### ISSUE THREAD

**Issue by zahoormohammed** [transistorsoft/react-native-background-geolocation#1913]
Appstore review rejected my app due to UIBackgroundModes in info.plist, i need help i spoke with apple support they said they can't help me , the only option is to reply back to rejected mail, i replied back still it got reject, how to make it approve help me please, 

**************************************************
Hello,

The issues we previously identified still need your attention.

If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know. 

Guideline 2.5.4 - Performance - Software Requirements

We noticed that your app declares support for location in the UIBackgroundModes key in your Info.plist file but we are unable to locate any features besides employee tracking that require persistent location. 

Using the location background mode for the sole purpose of tracking employees is not appropriate on the App Store.

Next Steps

If your app has a feature besides tracking employees that requires persistent location, reply to this message and let us know how to locate this feature. Otherwise, it would be appropriate to revise your app to include additional features for your users that require the persistent use of real-time location updates while the app is in the background.

If tracking your employees' locations is your only intended use of background location, it would be appropriate to review the other distribution options available for apps designed for specific businesses or organizations and choose a distribution option that works for your app and users. You can review these [app distribution options on Apple Developer](https://support.apple.com/guide/deployment/intro-to-content-distribution-depe1553f932/web).

**Comment by christocracy** [comment]
Apple does not feel that your app's use-case *deserves* the checkbox `[x] Location` to be enabled in XCode's *Signing & Capabilities* section.  It's up to you to prove to Apple that their determination is false.

<img width="1064" alt="Screenshot 2024-01-09 at 10 56 19 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/c7236b96-74c7-4c6c-9251-9605f73ef07b">

If you cannot convince Apple that your app deserves that checkbox to be enabled, then you must disable it and configure the plugin with `useSignificantChangesOnly: true` (search the API docs for more information).

Your app will then receive a location only about every 1000 meters.

**Comment by christocracy** [comment]
BTW, what *exactly* is your app's use-case?  Post some screenshots of your UI.

**Comment by zahoormohammed** [comment]
we are tracking employee location in background who will be on field during there shift hours, they tracking will start when the employee clock In and stop when they clockout , and this is available only for our clients not for every users. like if employee works in backoffice there tracking will disable for them. in android app got approved and working as expected, last time when i uploaded ios app with this plugin it got approved, this time they have rejected and not accepting at all even when i try to convince them, it seems like some software is testing app and not reading my message here is the screenshot of ui
![1704869407319](https://github.com/transistorsoft/react-native-background-geolocation/assets/52659168/2080e995-c5b8-4eb8-9120-95aad7788102)

**Comment by christocracy** [comment]
It looks like an acceptable location for UIBackgroundModes location.  I suggest you continue appealing your case with Apple and attempt to communicate with an actual human.

**Comment by ganeshmohane** [comment]
@zahoormohammed  Did your app approved by Apple?
plz respond as I am also facing same problem? Our App is also related to Attendance & Location Tracking

**Comment by ganeshmohane** [comment]
> we are tracking employee location in background who will be on field during there shift hours, they tracking will start when the employee clock In and stop when they clockout , and this is available only for our clients not for every users. like if employee works in backoffice there tracking will disable for them. in android app got approved and working as expected, last time when i uploaded ios app with this plugin it got approved, this time they have rejected and not accepting at all even when i try to convince them, it seems like some software is testing app and not reading my message here is the screenshot of ui ![1704869407319](https://github.com/transistorsoft/react-native-background-geolocation/assets/52659168/2080e995-c5b8-4eb8-9120-95aad7788102) ![1704869716688](https://github.com/transistorsoft/react-native-background-geolocation/assets/52659168/3e7baa61-bd41-4d61-bd3d-8477d50a96c2)

apple does not use bots to test app unlike google

**Comment by teammitchell** [comment]
@zahoormohammed I would also be curious to get an update on this since I am in a similar predicament
