### ISSUE TITLE
Mock location / Fake GPS Question

### ISSUE THREAD

**Issue by sanduluca** [transistorsoft/react-native-background-geolocation#1914]
Hi. 
We are using this library to track location of our drivers.
We want to protect our business from location spoofing.
```json
"react-native-background-fetch": "^4.2.0",
"react-native-background-geolocation": "^4.12.1",
```
I saw that this library provides a `mock` property that show if location was generated by a "Fake Location" application or simulator. I was wondering how exactly it works ? 

Also I found this library https://github.com/jpudysz/react-native-turbo-mock-location-detector that detects fake gps / mock.

Will this library give same results as `mock` property ? Does it has any sense to use them both or maybe one of them will give more accurate results ?

**Comment by christocracy** [comment]
The native location api provides this information.

**Comment by christocracy** [comment]
No, you don't need any other plug-in to detect this.

**Comment by christocracy** [comment]
That plug-in does the same thing that background-geolocation does:  it queries the native location api to ask if the location is mocked.
