### ISSUE TITLE
[Feature request] Introduce isMockingLocation Method

### ISSUE THREAD

**Issue by sanduluca** [transistorsoft/react-native-background-geolocation#1915]
### Request
Provide a method `isMockingLocation` to allow developers to check if the device's location is being mocked.

### Context
Currently, the only available method to determine if the location is mocked is to call getCurrentPosition. However, in certain scenarios, fetching the user's position is unnecessary. Introducing isMockingLocation as a standalone method would offer a more efficient way for developers to ascertain whether the device's location is being mocked without the need for unnecessary location updates.

### Additional Information
- **Use Case:** This feature is particularly valuable for applications that do not require real-time location updates but need to verify if the device's location is genuine or being simulated.
- **Enhanced Efficiency:** By providing a dedicated method for checking mocked location, developers can optimize resource usage and improve overall application performance.
- **Simplified Implementation:** Having a specific method for this purpose streamlines the code and enhances readability, making it easier for developers to incorporate location mocking checks into their applications.

**Comment by christocracy** [comment]
No matter what, the implementation would do the exact same thing:  execute a location request and call [`Location.isMock()`](https://developer.android.com/reference/android/location/Location#isMock()) (as well as the iOS equivalent).  It would merely be semantic sugar.

```javascript
  const location = await BackgroundGeolocation.getCurrentPosition();
  if (location.mock) {
    // IS mock.
  } else {
    // NOT mock
  }
```

You could simply implement your own custom `isMockingLocation` that wraps the code above.
