### ISSUE TITLE
`Undefined symbols:   _OBJC_CLASS_$_TSBackgroundFetch` when compiling with Rosetta 2 Xcode to x86 iOS Simulator

### ISSUE THREAD

**Issue by noway** [transistorsoft/react-native-background-geolocation#1917]
## Your Environment
* Plugin version: 4.13.2
* Platform: iOS
* OS version: iOS 17.3
* Device manufacturer / model: iOS Simulator
* React Native version (`react-native -v`): 0.68.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
not relevant
```

## Expected Behavior
Compilation to succeed

## Actual Behavior
Compilation fails on link step

## Steps to Reproduce
1. use an Apple Silicon Mac
2. `bundle exec pod repo update && bundle exec pod install`
3. `arch -x86_64 /Applications/Xcode.app/Contents/MacOS/Xcode`
4. set target to an iOS Simulator device (e.g. iPad)
5. click Run

## Context
- I'm trying to use the package with x86 iOS Simulator through Rosetta 2.
- The package compiles fine when building from Arm to Arm (Apple Silicon Mac to iPhone).
- Tried both `arch -x86_64 bundle exec pod repo update && arch -x86_64 bundle exec pod install` and `bundle exec pod repo update && bundle exec pod install` - same error.
- clean build doesn't help
- `use_frameworks!` is NOT used
- we can't use Arm iOS Simulator unfortunately because other packages are broken in it. 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
ld: warning: ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz'
ld: warning: ignoring file '/Users/ilia/stqry/stqry-rn/node_modules/react-native-background-fetch/ios/RNBackgroundFetch/TSBackgroundFetch.xcframework/ios-arm64_armv7/TSBackgroundFetch.framework/TSBackgroundFetch': fat file missing arch 'x86_64', file has 'arm64,armv7'
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: Undefined symbols:
  _OBJC_CLASS_$_TSBackgroundFetch, referenced from:
       in RNBackgroundFetch+AppDelegate.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

</details>

**Comment by noway** [comment]
I can reproduce this on version 4.14.6 of react-native-background-geolocation as well.

**Comment by christocracy** [comment]
I'll have a look at xcframework build-script.

**Comment by noway** [comment]
This issue is not stale and still affects us.

**Comment by noway** [comment]
@christocracy sorry for bugging you, but is there any way to get this fixed? We use Rosetta 2 iOS Simulator on our Apple Silicon machines to create screenshots. We can't use ARM64 iOS Simulator since some of our other react-native packages are broken on ARM64 iOS Simulator. But on Rosetta 2 iOS Simulator, only `react-native-background-geolocation` is broken.

It's a big workflow friction point for us.

**Comment by akinlekan28** [comment]
@noway How were you able to compile at all, I am also having this issue and I can't seem to compile both on my physical device and simulator.

**Comment by akinlekan28** [comment]
> @akinlekan28 youre using Rosetta 2?

Yes

**Comment by christocracy** [comment]
How are you running with Rosetta 2?  I'm able to launch my demo app in a simulator *iPhone 15 Pro (Rosetta, 17.2)*.

<img width="1600" alt="Screenshot 2024-05-23 at 10 08 33 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/746b0819-f257-431a-9ad4-eaa1e5f4c93e">

<img width="996" alt="Screenshot 2024-05-23 at 10 12 20 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/52bdb82d-79db-4f83-a520-344c2b920b35">

**Comment by akinlekan28** [comment]
> How are you running with Rosetta 2? I'm able to launch my demo app in a simulator _iPhone 15 Pro (Rosetta, 17.2)_.
> 
> <img alt="Screenshot 2024-05-23 at 10 08 33 AM" width="1600" src="https://private-user-images.githubusercontent.com/14999/333216912-746b0819-f257-431a-9ad4-eaa1e5f4c93e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzYwMzUsIm5iZiI6MTcxNjQ3NTczNSwicGF0aCI6Ii8xNDk5OS8zMzMyMTY5MTItNzQ2YjA4MTktZjI1Ny00MzFhLTlhZDQtZWFhMWU1ZjRjOTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE0NDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNDI2YjQ3NjVlYTAxOWM2NDE1YzFiYzQ4NGZkZWUwNTFhOTU1MDJlNDc0OTI4ZTBiNTE0ZGRiYjQ5YzUzZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZvnlYOvrIqoJitGvuyQiZL51PXKuLuEQA_M7tP3lAb0"> <img alt="Screenshot 2024-05-23 at 10 12 20 AM" width="996" src="https://private-user-images.githubusercontent.com/14999/333217411-52bdb82d-79db-4f83-a520-344c2b920b35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzYwMzUsIm5iZiI6MTcxNjQ3NTczNSwicGF0aCI6Ii8xNDk5OS8zMzMyMTc0MTEtNTJiZGI4MmQtNzlkYi00ZjgzLWE1MjAtMzQ0YzJiOTIwYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE0NDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YTU3ZjU2ZWJiNTNjOTI1ODUyZmY1YWVhOTBiNTFmZjUwODdhOTUzMzYxNmFkYjYxZjhkYTBlM2YwZTk3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a3woVuATBmpM3btjUv3eD5IAI7JP4hskDEbY4q4F8D8">

<img width="1024" alt="Screenshot 2024-05-23 at 15 48 28" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/15618006/bbc269f4-3a04-4265-a06e-6ecf502551e1">
Here's me trying to run it with rosetta

**Comment by noway** [comment]
@akinlekan28 what's your React Native version?

@christocracy I'm opening Xcode and selecting a Rosetta simulator.
<img width="1512" alt="Screenshot 2024-05-23 at 11 56 52 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/2031472/edf8567e-ad01-4499-8ea7-2ecadb3a7033">
Here's my Xcode:
<img width="529" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/2031472/2aba4db4-c6cc-47f4-a746-02043bc44927">
I'm using React Native 0.70.15 at the moment.

**Comment by akinlekan28** [comment]
> @akinlekan28 what's your React Native version?
> 
> @christocracy I'm opening Xcode and selecting a Rosetta simulator. <img alt="Screenshot 2024-05-23 at 11 56 52 AM" width="1512" src="https://private-user-images.githubusercontent.com/2031472/333258960-edf8567e-ad01-4499-8ea7-2ecadb3a7033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODAzNDQsIm5iZiI6MTcxNjQ4MDA0NCwicGF0aCI6Ii8yMDMxNDcyLzMzMzI1ODk2MC1lZGY4NTY3ZS1hZDAxLTQ0OTktOGVhNy0yZWNhZGIzYTcwMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTYwMDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ2YzAwYjg0N2ZjYjM4NWI1MTA3M2M0NGViNTkyYzlmMDg0MzE2YzI5OTE4MzM0NjliMTRhY2U3OTk5YjEzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aOYEmnz6XUWMJ1HcKNhwT8Rv08h6rVjnv0eSeK8oStw"> Here's my Xcode: <img alt="image" width="529" src="https://private-user-images.githubusercontent.com/2031472/333259042-2aba4db4-c6cc-47f4-a746-02043bc44927.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODAzNDQsIm5iZiI6MTcxNjQ4MDA0NCwicGF0aCI6Ii8yMDMxNDcyLzMzMzI1OTA0Mi0yYWJhNGRiNC1jNmNjLTQ3ZjQtYTc0Ni0wMjA0M2JjNDQ5MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTYwMDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU3MGExN2UzMTc1N2JmNGJiZDdhM2M3YzRmZjkxNjk2Yjg0ZTljNGZjZWI3ODk5ZjA3NjFlNDgwMGFjZmE5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4Z48hQxi38c5GIeAOyodaPaWmVkPDitdBanZyIBKXSM"> I'm using React Native 0.70.15 at the moment.

`0.74.1`

**Comment by christocracy** [comment]
My [*demo* app](https://github.com/transistorsoft/rn-background-geolocation-demo) uses `react-native @ 0.73.0`

I'm using XCode 15.3.

**Comment by noway** [comment]
@akinlekan28 do you have `__apply_Xcode_12_5_M1_post_install_workaround` enabled in your Podfile?

**Comment by akinlekan28** [comment]
> @akinlekan28 do you have `__apply_Xcode_12_5_M1_post_install_workaround` enabled in your Podfile?

I removed it since it's not needed for newer version of RN

**Comment by christocracy** [comment]
I updated to *XCode 15.4*.  *Demo App* runs fine with Simulator *iPhone 15 Pro (Rosetta, 17.4)*.

I suggest you try testing in a freshly generated, simple *hello-world*.

<img width="1377" alt="Screenshot 2024-05-23 at 12 19 58 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/d3cc052f-a954-44cf-8735-e37c7859350d">

**Comment by akinlekan28** [comment]
> I updated to _XCode 15.4_. _Demo App_ runs fine with Simulator _iPhone 15 Pro (Rosetta, 17.4)_.
> 
> I suggest you try testing in a freshly generated, simple _hello-world_.
> 
> <img alt="Screenshot 2024-05-23 at 12 19 58 PM" width="1377" src="https://private-user-images.githubusercontent.com/14999/333266559-d3cc052f-a954-44cf-8735-e37c7859350d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTc4NzMsIm5iZiI6MTcxNjQ5NzU3MywicGF0aCI6Ii8xNDk5OS8zMzMyNjY1NTktZDNjYzA1MmYtYTk1NC00NGNmLTg3MzUtZTM3Yzc4NTkzNTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDIwNTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZjA3NzFiZTE3YTkyODcwYzg1YTMyNzE2YjExMDg3NTUzMjIzYzFmYzQ2NTUzYjRiMWFmYTA5YzFlYjU3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pA971O3Xour1XnSjmcwR9CEOABczRffRzIuucLHpZwQ">

I've been able to get this to work on both the simulator and physical device. I had to create a new app though.

**Comment by noway** [comment]
Ok, got it to work too. Seems like `RNBackgroundFetch+AppDelegate.m` is not (no longer?) needed and `react-native-background-fetch` has to be present in `package.json`.

**Comment by christocracy** [comment]
> Seems like RNBackgroundFetch+AppDelegate.m is not (no longer?)

[Read about it here](https://github.com/transistorsoft/react-native-background-fetch/blob/master/docs/INSTALL-AUTO-IOS.md#backgroundfetch-appdelegate-extension)

> and react-native-background-fetch has to be present in package.json.

As directed [by the Setup Instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md#ios-auto-linking-installation)

**Comment by noway** [comment]
@christocracy oh I see, `RNBackgroundFetch+AppDelegate.m` is deprecated, not fully removed. I added it back and the build still works!

It looks like merely doing `yarn add react-native-background-fetch@^4.2.1` is enough. 

Thank you!

**Comment by christocracy** [comment]
Unfortunately, RN doesn’t auto-link transitive dependencies of a plugin.

even though background-fetch is declared as a dependency within package.json, you’re forced to manually `yarn add` it in order for it to be auto-linked.
