### ISSUE TITLE
Location services automatically turn off when booting with "While Using the App"

### ISSUE THREAD

**Issue by nouveller** [transistorsoft/react-native-background-geolocation#192]
> Firstly, thanks again @christocracy for your help with https://github.com/transistorsoft/react-native-background-geolocation/issues/183, this issue is sort of related.

Booting the app with the location permission set to "Always" works perfectly (location tracking working in all instances), while keeping the app open and changing permission to "While Using the App", this also works as expected (location tracking continues just to work in the foreground, blue bar appears elsewhere).

However, closing the app and reopening causes the issue to occur. No blue bar, no tracking being logged.

## Your Environment
* Plugin version: 2.3.1
* Platform: iOS
* OS version: 10.0
* Device manufacturer / model: Simulator
* React Native version (`react-native -v`): 0.36.1
* Plugin config

```js
debug: true,
desiredAccuracy: 100,
distanceFilter: 100,
autoSync: false,
stopOnTerminate: false,
disableMotionActivityUpdates: true,
```

## Expected Behavior
When the app is booted up from being closed, with the location permission set to "While Using the App", the tracking should continue to log while the app is open, and the blue bar should appear while outside of the app (it's in the background). Upon closing the app, the tracking is stopped.

## Actual Behavior
With the app completely closed, going into location services and changing the permission to "While Using the App", opening the app, location services turn on, log a stationary position and turn off.

Here are the logs.

<img width="819" alt="screen shot 2017-01-17 at 16 25 18" src="https://cloud.githubusercontent.com/assets/713128/22029187/abef1e00-dcd1-11e6-9de5-474cccf4d443.png">

However, if booted from cold, location services set to "Always", then switch to "While Using the App" and switching back to the app, it works as expected. The problem occurs only when booting from cold.

## Steps to Reproduce

Code is essentially... run inside the main App component, e.g. `AppRegistry.registerComponent('MyApp', () => App);`

```js
componentWillMount() {
  BackgroundGeolocation.configure({
    debug: true,
    desiredAccuracy: 100,
    distanceFilter: 100,
    autoSync: false,
    stopOnTerminate: false,
    disableMotionActivityUpdates: true,
  });

  BackgroundGeolocation.on('location', (location) => {
    console.log(location);
  });

  BackgroundGeolocation.on('providerchange', function({ status }) {
    const status = (function(status) {
      switch(status) {
        case BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS:
          return 'Always';
        case BackgroundGeolocation.AUTHORIZATION_STATUS_WHEN_IN_USE:
          return 'WhenInUse';
        default:
          return undefined;
    })(status);
    
    if (status) {
      BackgroundGeolocation.start();
    } else {
      BackgroundGeolocation.stop();
    }
  });
}
```

**Comment by christocracy** [comment]
Since you haven't configured a `locationAuthorizationRequest', the plugin defaults to `Always`.  

`locationAuthorizationRequest` represents the setting the plugin *expects*.  You need to set this accordingly, if you allow the user to operate in either mode.

eg:
```Javascript
BackgroundGeolocation.setConfig({locationAuthorizationRequest: 'WhenInUse'});
```

**Comment by nouveller** [comment]
Hmm... I did follow your original example to the letter.

I've tried adding `locationAuthorizationRequest: 'WhenInUse',` to the initial `configure` call. No luck.

And also modifying the more dynamic `setConfig` call as well.

```js
BackgroundGeolocation.on('providerchange', function({ status }) {
  const status = (function(status) {
    switch(status) {
      case BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS:
        return 'Always';
      case BackgroundGeolocation.AUTHORIZATION_STATUS_WHEN_IN_USE:
        return 'WhenInUse';
      default:
        return undefined;
  })(status);
  
  if (status) {
    BackgroundGeolocation.setConfig({
      locationAuthorizationRequest: status,
    });
    BackgroundGeolocation.start();
  } else {
    BackgroundGeolocation.stop();
  }
});
```

And again no luck. I may try make a separate RN project that's clean to see if it's reproducible without any other stuff going on.

Sorry to bother you Chris.

**Comment by nouveller** [comment]
@christocracy I've made a fresh project to try and isolate the issue/my misunderstanding. If you have time to take a look, that would be amazing.

https://github.com/nouveller/BackgroundLocationTest (the only code you should need to bother with is within these lines https://github.com/nouveller/BackgroundLocationTest/blob/master/index.ios.js#L17-L59)

I receive these logs when my privacy settings are set to and configured within the app for "WhenInUse".

<img width="607" alt="screen shot 2017-01-18 at 08 49 55" src="https://cloud.githubusercontent.com/assets/713128/22057109/31ee42c2-dd5b-11e6-8260-21412ba52e67.png">

I then receive no further location updates, using the custom location in the debugger to change location or one of the car/cycle routes.

Changing this line to "Always", and setting my privacy settings for the all to "Always", everything works as expected.

https://github.com/nouveller/BackgroundLocationTest/blob/master/index.ios.js#L18

Maybe I'm just misunderstanding...

**Comment by christocracy** [comment]
The problem you're experiencing is [due to this](https://github.com/nouveller/BackgroundLocationTest/blob/master/index.ios.js#L56)

You must not execute **any** API method (aside from adding event-listeners with `#on`) until the callback to `#configure` has executed.

**Comment by nouveller** [comment]
Thanks for that comment (https://github.com/nouveller/BackgroundLocationTest/commit/f36f2fd722ff99858009ef5791b49fbd4b637ae9#commitcomment-20521686) @christocracy, that makes sense but I have just updated the code so it does the following...

1. Adds two buttons to start/stop tracking
2. These buttons are only shown once the configuration callback is made by setting an enabled flag in the state.

Here's a video demo of what's happening. 

https://www.dropbox.com/s/53zi013abhkcj7m/locations.mov?dl=0

Or maybe I'm still doing it wrong 🤔

**Comment by christocracy** [comment]
I did no know this about `WhenInUse` (the plugin is primarily designed for `Always`), but iOS forbids geofence monitoring while in `WhenInUse` mode.  The plugin uses geofence-monitoring to detect when the device is moving.

From Apple docs for [requestWhenInUseAuthorization](https://developer.apple.com/reference/corelocation/cllocationmanager/1620562-requestwheninuseauthorization)

> If the user grants “when-in-use” authorization to your app, your app can start most (but not all) location services while it is in the foreground. **(Apps cannot use any services that automatically relaunch the app, such as region monitoring or the significant location change service.)**

The plugin **cannot** automatically trigger tracking while in `WhenInUse` mode.  This may have been a recent change to the API in iOS `9.x`

The only way to engage tracking while in `WhenInUse` mode is to manually execute:
```Javascript
BackgroundGeolocation.changePace(true);
```

Btw, it's much easier to test by simulating location with **City Drive** rather than editing **Custom Location**.

**Comment by christocracy** [comment]
If you were making a Jogging app and you wanted to use `WhenInUse` authorization (to display the "blue bar"), you would have to add buttons on your UI to execute `#changePace`:

**[Start Workout]  [Stop Workout]**

There is no way to automatically engage tracking with `WhenInUse` authorization.

**Comment by nouveller** [comment]
@christocracy Perfect, that clear it up. Merely a misunderstanding of how the tracking should work when in When In Use mode.

Thank-you _again_.

**Comment by peterlau** [comment]
Ran into this 'WhenInUse' issue just now. Was pulling my hair out over why my location updates fire fine when the location permission is changed from `always` and changed to `when-in-use` mid-use, but do not work at all when `start()` is called while the permission is already at the `when-in-use` level.

Here's my solution (using the `react-native-permissions` library)

    BackgroundGeolocation.start().then(() => {
      Permissions.check('location', { type: 'always'}).then(perm => {
        if(perm !== 'authorized'){
          console.log('WhenInUse permission only.  Force motion to running')
          BackgroundGeolocation.changePace(true);
        }
      })
    })

Thanks to the author's helpful suggestion here. However I respectfully disagree with his assessment in another thread elsewhere that `when-in-use` is for 'the rare 1% of cases'. Unfortunately, the iOS 11 regime prohibits an always-or-nothing request, instead forcing `when-in-use` to be offered at all times. Consumer facing apps can easily find <20% conversion in getting the `always` permission granted.

I think it is quite unlikely that an app author would want their app to fail silently in those 80% of cases where the user chooses the 'middle' option. 

Would it be a good idea for `start()` to automatically set the pace to `moving` in this eventuality? The GPS would be running all the time using power but I feel this would be a well understood consequence.

**Comment by christocracy** [comment]
I suggest you communicate with your user via alert, explaining your case to them:

>"For the app to work properly, we *really* need you to select 'Always'".

Your method of `#changePace` will be a fragile hack and isn't going to work when the user terminates the app, reboots their device or when iOS terminates your app due to memory pressure from *other* apps, since `WhenInUse` authorization disables background APIs crucial to re-launching the plugin when device is detected to be moving (particularly Geofence API; the plugin uses a geofence around the last known position &mdash; when that geofence is exited while the app is terminated, iOS will re-launch the app to service that event and tracking resumes, but only with `Always` permission.

Btw, you don't need to use `Permissions` module, just listen to the plugin's [`providerchange`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#providerchange) event.
