### ISSUE TITLE
Not allowed to use USE_EXACT_ALARM.

### ISSUE THREAD

**Issue by xtl-geiger** [transistorsoft/react-native-background-geolocation#1921]
I changed the permissions according to 4.13.1 — 2023-08-24 Update to include `android.permission.USE_EXACT_ALARM`.
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/35232135/04de0ef5-6eca-447b-a974-9457d789be4c)

I got an email warning from Google as follows:

> Hello Google Play Developer,
> This is a reminder that the policy restricting the use of USE_EXACT_ALARM was effective as of [July 31, 2023](https://notifications.google.com/g/p/ANiao5oyKuxhuZK8JC2Pw2xoSU8mlsVm0LJSfiEBylGDkE-1OwezwfwPEzZrZ4_KsXFbYM40VEio5FB4TP8bkaxdtwGjJriBv7rpf7fs_7KXNQGscMWCvYMD45280_3KWOq3SAhWCGA2bYOiDqI72vM3WQNlneP_fC8lHeAOUvz0ekIszHDYZRjKWFpIbrSVT1PsAt1QX8bp6T1yjSWrhWPU602WAy7BBFCHl4qiD5kzGIIKjVXa-0OrThlC5MEccsZ_mkwcpsB3YQl5vWbM0pUfiTsaXuLtEWALBOFZAUfZ7OH8ljbkp0KvcquNQ3Ja-9N7OFUBr1p7Ojin724gWqEmbwqa_P4TfPUkua6O96cvVUIS0y_xI7yNfuCQ65Z275cF-2A5Kxrx_CdWjBDsZbuKRA8g_g) and apps are expected to be in compliance. We are aware that you have declared this sensitive permission and recommend ensuring your app qualifies. Apps that declare this restricted permission are subject to review, and disallowed use cases or features not needing an exact alarm may be subject to further enforcement action, including possible removal from Google Play.
> As a reminder, acceptable use cases for the USE_EXACT_ALARM permission involve your app’s core, user facing functionality requiring precisely-timed actions, such as:
> 
>     App is an alarm or timer app
>     App is a calendar app that shows event notifications
> 
> If you need to provide exact alarm functionality but don’t meet the policy criteria, you should evaluate using SCHEDULE_EXACT_ALARM as an alternative.
> Please consult the [Exact Alarm Permission policy](https://notifications.google.com/g/p/ANiao5rw9t7hu9ukqrEQxwKx-CMb-4iVXXphaHoJ8qZDAZpS6aFexLJIqQqucwdgjGlP5k_d_PeF35eEutrjR5l73vWv91AnjDeRjvxZAQ8IvNX5qM9bxBNDOAaswtGEGoRc13CLPqZ0XDpUGkQiHiU7PAvV66a82qp8dqXhmLqnf4_RWSZMvCbbuA9L9s3bi2L1CZG26s-fJbM__nnV_ZvUf5QJ7Ebf6Mc3U893FCFry0p_Mw_9-zAZYseXfDxKoj7qX56SLJ4jdruMzmi_S5HmpXfoSiUzUn5ls9JDOXKuVDA2lfyf4tXUEQ_txh0mJN4pvViK0IstE-shTT8) and [Exact Alarms overview](https://notifications.google.com/g/p/ANiao5qzZwUTpSk13Tz27n3syIjlIWCkexmYZzL5am1ENNcyIFg2YVTt6G40F783OaO-37NtKLr4HPNQGPUy_OUTVG-uOzVBnUG69VptHfdNY_F117EFTyB5X4XHmcOguXFULBEdwx-dtmxtGNhPwegaY_3mz0nLMPUs4LTnmsoYQuJMQGGXornzxGUDjHxh_doFxlTgoX23lhVh0wgK9nUB6_QyLc3k8FYPWckakJVxquocz5554x7rTYkE_C5jQK87JSNOJSSOwL0bd3zY_PLO5w) for more information.
> Thank you for continuing to partner with us to make Google Play a trustworthy platform for you and your users.

Is there a newer version that switched to SCHEDULE_EXACT_ALARM already?

## Your Environment
* Plugin version: 4.14.3
* Platform: Android
* OS version: -
* Device manufacturer / model: -
* React Native version (`react-native -v`): 0.72.6
* Plugin config

## Expected Behavior
App should be in permission compliance.

## Actual Behavior
App is not in in permission compliance.

**Comment by christocracy** [comment]
Have you read the CHANGELOG and the latest Setup Instructions?

**Comment by xtl-geiger** [comment]
Sorry, did not see the part about changing the permission in 4.13.1 — 2023-08-24 changelog to `SCHEDULE_EXACT_ALARM` . I already changed it to `SCHEDULE_EXACT_ALARM` after I received the mail. 
I assumed that if the changelog still said `USE_EXACT_ALARM` in that place, the info to change it was simply missing. 

I would have expected this info to be either in the changelog of the next version, or already corrected or changed in the code snippet setting the permission or as a hint in the same place.

**Comment by christocracy** [comment]
The plug-in contains all the permissions it requires within its own AndroidManifest.  You are not expected to add your own custom permission in support of the plug-in to *your* AndroidManifest.

The latest Setup Instructions instruct you how to manually add USE_EXACT_ALARM *optionally*.

**Comment by walterholohan** [comment]
Hey @xtl-geiger , we just got the same rejection from Google. Still confused by the changelog, do we simply replace it with `SCHEDULE_EXACT_ALARM`. Or what did you do in your case?

**Comment by hieuminh1810** [comment]
we just got the same rejection from Google
"Your app uses the USE_EXACT_ALARM permission. If your app's core functionality is not 'calendar' or 'alarm clock', you're not eligible to use this permission and must remove it from your app, across all tracks."
@christocracy how can we resolve it?
