### ISSUE TITLE
iOS Battery Level Issue with `react-native-device-info` (-1 Value) until `BackgroundGeolocation.start()`

### ISSUE THREAD

**Issue by sanduluca** [transistorsoft/react-native-background-geolocation#1922]
## Your Environment
* Plugin version: 4.12.1
* Platform: iOS 
* OS version: 17.2.1
* Device manufacturer / model: iPhone XR
* React Native version (`react-native -v`): 0.72.4
* Plugin config

## Actual Behavior
We use `react-native-device-info` plugin, version `10.8.0`. We need to get battery level so we use https://github.com/react-native-device-info/react-native-device-info?tab=readme-ov-file#getbatterylevel api, but it returns -1. In their documentation its says to add this `[UIDevice currentDevice].batteryMonitoringEnabled = true;` to AppDelegate, but i still get -1 level on a real device. But i found that as soon as i call `BackgroundGeolocation.start()`, the `getBatteryLevel` returns the real device battery level and I dont get the `Battery monitoring is not enabled. You need to enable monitoring with [UIDevice currentDevice].batteryMonitoringEnabled = TRUE` warning

## Steps to Reproduce
1. Install `react-native-device-info` on an real iOS device. Also install `react-native-background-geolocation`.
2. Try get battery level or power state using `react-native-device-info`

## Context
```tsx
useEffect(() => {
  BackgroundGeolocation.start()
    .then(() => {
      console.log("Started geolocation");
      isBatteryCharging().then((isCharging) =>
        console.log("isBatteryCharging()", isCharging)
      );
      getPowerState().then((state) => console.log("getPowerState()", state));
      getBatteryLevel()
        .then((level) => {
          console.log("getBatteryLevel1", level);
        })
        .catch((e) => {
          console.log("error on getBatteryLevel", e);
        });
    })
    .catch((e) => console.log("Error starting", e));

  return () => {
    BackgroundGeolocation.stop();
  };
}, []);

```

**Comment by christocracy** [comment]
You dont need another plug-in to get the battery level.  Background Geolocation provides the battery-level to each recorded location.

**Comment by sanduluca** [comment]
> You dont need another plug-in to get the battery level. Background Geolocation provides the battery-level to each recorded location.

We use this library not only for battery api, but in our case we need user battery level outside of user location context.

**Comment by christocracy** [comment]
>currentDevice].batteryMonitoringEnabled 

This is a global property of the OS.

**Comment by sanduluca** [comment]
Will this be a good solution for you to implement so you do not reset this global property ?
```java
class Geolocation {
  
  private bool canChangeBatteryMonitoringProperty = false

  public function start(){
    if (! batteryMonitoringEnabled){
      batteryMonitoringEnabled = true
      canChangeBatteryMonitoringProperty = true
    }
  }

  public function stop(){
    ...
    if (canChangeBatteryMonitoringProperty){
      batteryMonitoringEnabled = false
      canChangeBatteryMonitoringProperty = false
    }
    ...
  }

}

**Comment by sanduluca** [comment]
@christocracy is the above proposal a good solution for you to implement ?

**Comment by sanduluca** [comment]
Up

**Comment by sanduluca** [comment]
Up
