### ISSUE TITLE
Invalid License Key Popup Concern

### ISSUE THREAD

**Issue by GuptaAman08** [transistorsoft/react-native-background-geolocation#1923]
## Your Environment
* Plugin version: 4.10.0
* Platform: iOS
* OS version: iOS 16, Laptop: MacOS ventura 13.4.1
* Device manufacturer / model: iPhone 14 (Real Device)
* React Native version (`react-native -v`):  0.71.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      distanceFilter: 50,
      stopOnTerminate: true,
      startOnBoot: false,
      stopTimeout: 20,
      enableHeadless: false,
      heartbeatInterval: 60,
      locationAuthorizationRequest: 'WhenInUse',
      disableMotionActivityUpdates: true,
      disableLocationAuthorizationAlert: false,
      extras: {},
      url: <server_url>,
      authorization: <function_that_returns_auth_token>,
      autoSync: true
}
```

## Expected Behavior
Prevent showing the **Invalid License Key.......** when app launches.

## Actual Behavior
Wanted to confirm few things here:
1. Whenever we install this sdk and dont have a valid license key, it shows a pop up at the time of App launch saying **Invalid License Key ........**.
2. Asking specifically this since, even if we haven't initialised OR called any other method of the sdk we are getting that pop up. That seems to be a pretty unusual experience for Users.

Is that the default check even if we haven't used any sdk utility OR there is some way to avoid this until we use any sdk method ?

## Steps to Reproduce

1. Install the SDK package.
2. Run a android build 
3. Invalid License Key in the `<meta-data android:name="com.transistorsoft.locationmanager.license" android:value="<Invalid_License_Key OR No_License_Key>" />`
4. Observe the error on app launch

## Context
Avoid the popup at App launch

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> OR there is some way to avoid this until we use any sdk method ?

The plug-in is fully functional in debug builds so you can try before you buy.

You're not expected to include this plugin in a released app without purchasing a license.

To make the warning go away, you must purchase a license.
