### ISSUE TITLE
expo prebuild config plugin not work on Expo SDK50 RN 0.73

### ISSUE THREAD

**Issue by chanphiromsok** [transistorsoft/react-native-background-geolocation#1928]
`react-native-background-geolocation`  in** app.config expo not working anymore
`react-native-background-fetch` also had error with regex
![Screenshot 2024-01-25 at 1 40 15 in the afternoon](https://github.com/transistorsoft/react-native-background-geolocation/assets/65760336/5572aeb0-f794-4d02-aa91-e8abe3eb243c)

**Comment by nemoneph** [comment]
Hello,
I saw this issue some days ago (when tested sdk 50 beta).

There is an error with the prebuild command on Andoid (seem fine in IOS) on react-native-background-geolocation / react-native-background-fetch expo plugin

It linked to the tag lines in : 
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/expo/plugin/src/androidPlugin.ts#L114
(multiple times in this file)

And here: 
https://github.com/transistorsoft/react-native-background-fetch/blob/master/expo/plugin/src/androidPlugin.ts

Don't really know why, but after removing  "[" and "]" in all tag it was working.

Ex:  tag: `[${MODULE_NAME}]-project`, =>  tag: `${MODULE_NAME}-project`,




After that. Prebuild was OK.

But got another error when building (sorry, I have not kept the stacktrace but something about "FusedLocation".
I didn't dig and goback to SDK 49).

**Comment by christocracy** [comment]
Confirmed.  I've removed the `[` and `]` characters from the Expo-generated `// comment-tags` for both `background-fetch` (v4.2.2) and `background-geolocation` (v4.14.6).

**Comment by chanphiromsok** [comment]
BackgroundGeolocation.ready is null when call is expo sdk 50 android

**Comment by christocracy** [comment]
I just tested with v50 and it's fine.

If BackgroundGeolocation is null, you have a problem with the Setup.  Go back to Setup instructions and try again in a simple "HelloWorld" app.

**Comment by chanphiromsok** [comment]
let me check again

**Comment by chanphiromsok** [comment]
it works now IDK why can close
