### ISSUE TITLE
app can't get the location data on iOS at the requested interval.

### ISSUE THREAD

**Issue by suha-pragmasoft** [transistorsoft/react-native-background-geolocation#1931]
* Plugin version: 4.4.4
* Platform: iOS
* OS version: 16.7.4
* Device manufacturer / model: iPhone X
* React Native version (`react-native -v`): 0.66.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  const startTracking = async (objectId) => {
    try {
      const state = await BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50,
        stopOnTerminate: false,
        stopTimeout: 0,
        backgroundPermissionRationale: {
          title: "Allow {applicationName} to access to this device's location when closed or not in use?",
          message:
            "xyz message.",
          positiveAction: 'Change to {backgroundPermissionOptionLabel}',
          negativeAction: 'Cancel',
        },
      });
```

## Expected Behavior
The application should update the user's location in the set interval as if the application were in the foreground, even when running in the background. (android version is updating successfully while on background)

## Actual Behavior
when application goes to background, we can't get its location even the user goes to more than 50 meter. The location sometimes gets updated randomly in 3 to 10 minutes. When it is on foreground, the application updates location successfully. We are doing tests via using car.

## Steps to Reproduce
1.
2.
3.
4.

## Context
This is a location based application and its important to update user's locations on foreground and background.

</details>

**Comment by christocracy** [comment]
See wiki "Debugging" and learn to fetch logs using `.emailLog` method.  Also search API docs "Logger".

**Comment by christocracy** [comment]
>even the user goes to more than 50 meter.

Also read the Wiki here "Philosophy of Operation".  iOS devices need to travel *at least* **200 meters** before tracking engages.  Go outside for a walk of >= 1000 meters.
