### ISSUE TITLE
Previous locations sent to server with new config after setConfig

### ISSUE THREAD

**Issue by stharvey** [transistorsoft/react-native-background-geolocation#1934]
## Your Environment
* Plugin version:    4.14.5,
* Platform:  Android (maybe unconfirmed on iOS)
* OS version: Android 14
* Device manufacturer / model: Google Pixel 8 @ 14 (react)
* React Native version (`react-native -v`): react-native-cli: 2.0.1   react-native: 0.72.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {},
  "autoSync": false,
  "autoSyncThreshold": 0,
  "backgroundPermissionRationale": {
    "title": "Allow access to this device's location in the background?",
    "message": "In order to track your journey please enable \"{backgroundPermissionOptionLabel}\" location permission",
    "positiveAction": "Change to {backgroundPermissionOptionLabel}",
    "negativeAction": "Cancel"
  },
  "batchSync": true,
  "configUrl": "",
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 10,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": true,
  "disableProviderChangeRecord": false,
  "disableStopDetection": true,
  "distanceFilter": 10,
  "elasticityMultiplier": 1,
  "enableHeadless": false,
  "enableTimestampMeta": false,
  "extras": {
    "live": 0,
    "trans": "hike3",
    "leg": "1706702476-leg-2043edec50a7a060-54780",
    "offset": 0
  },
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
  "heartbeatInterval": 180,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "{\"lat\":<%= latitude %>,\"lng\":<%= longitude %>,\"elev\":\"<%= altitude %>\",\"speed\":\"<%= speed %>\",\"acc\":\"<%= accuracy %>\",\"time\":\"<%= timestamp %>\"}",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": 500,
  "maxDaysToPersist": 730,
  "maxMonitoredGeofences": 97,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "Pebbls - Location Tracking",
    "text": "Pebbls is currently tracking your leg: West coast Wednesday",
    "color": "#FF9000",
    "channelName": "TSLocationManager",
    "channelId": "",
    "smallIcon": "drawable\/notification_icon",
    "largeIcon": "",
    "priority": -1,
    "sticky": true,
    "strings": {},
    "actions": []
  },
  "params": {
    "token": "XXXXXXXXXXXXXX"
  },
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 15,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "https:\/\/workers.pebbls.com\/location_auth\/",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 21865.779296875,
  "isFirstBoot": false,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
```
I realise this will be an issue with my code, so bear with me - I would just like some advice on where to start looking to identify the cause of the issue.

## Expected Behavior

The app is a journey tracking app.  While tracking is enabled the user can specify their current transport type which is saved with each location by doing this:

```
  await BackgroundGeolocation.setConfig({
    extras: {
      trans: currentTransport,
    },
  });
```

The user can update transport type as they travel and this updates the currentTransport and fires setConfig.

The app periodically syncs the location data to my server.

I expect to see unique location points received to the server with the current transport type for the time at which the location point is created.

## Actual Behavior

Mostly this works very well, however from time to time (i've seen it a few times) the user begins a journey in one transport type (e.g. 'bicycle') and then a while later they change to another (e.g. 'hike3') - while using the initial transport type the data is received by the server correctly, then at some point after changing transport type a number of previous locations, which have already been received by the server, are sent to the server again but with the new transport type.

I'm not sure if this only happens when changing transport type, or it it happens anyway - I wouldn't have noticed if this occurs with identical points were sent with the same transport type set.

I haven't been able to determine exactly which part of the process is causing this to happen.

Every time data is sent to the server I write it to a log before processing - I've attached this raw log:

[location_post_log-saved1.log](https://github.com/transistorsoft/react-native-background-geolocation/files/14114459/location_post_log-saved1.log)

If you search for the timestamp "2024-01-31T12:38:24.279Z" you will see there are 2 location points in the logs, one received by the server at 13:10:23 with the correct transport type 'bicycle' and then another identical location (with that same previous timestamp) received by the server at 13:44:08 with the new transport type of 'hike3'.

Do you know what conditions might cause this to happen? 

## Steps to Reproduce

The app is quite large and complex - are there any particular parts of the code that would be useful for you to see?

## Context
Journey tracking with user-selected transport type.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
I've attached the log file from the module: 

[logfile_2024-01-31_14-23-00-saved.log](https://github.com/transistorsoft/react-native-background-geolocation/files/14114361/logfile_2024-01-31_14-23-00-saved.log)

</details>

**Comment by christocracy** [comment]
>Plugin version: 3.5.3 (432)

This is not the right version.  You need to provide the `react-native-background-geolocation` version (from your `package.json`.

It's not `timestamp` which makes a location unique, it's the `uuid` field which marks it as unique. 

The OS can provide a "stale" location multiple times which happens to have the same `timestamp`.  The plugin contains a new `Location.age` property (available only in `v4.14.+`) which you can use to determine the "stale-ness" of the location at that time

**Comment by stharvey** [comment]
Ah, sorry - correct plugin version:   

`"react-native-background-geolocation": "^4.14.5"`

**Comment by stharvey** [comment]
Thanks Chris,

I'm not sure I understand though - why would it provide stale data so long later even though location tracking as supplied many fresh locations in the meantime?

Thanks

**Comment by christocracy** [comment]
The plugin does not modify any existing records inserted into SQLite.  If there happens to be queued records in the plugin's database which have not yet been uploaded to your server, the CANNOT be modified (eg: changed `extras` using `.setConfig`.

Once a record from the plugin's database is uploaded to your server and your server returns `200` response, that record is deleted.  The plugin maintains no memory of previously recorded locations.

**Comment by christocracy** [comment]
When a record is inserted into the plugin's database, the `Config.extras` are stamped upon it **at that moment in time**.  They will *never* be modified and reposted if your `Config.extras` change.

**Comment by christocracy** [comment]
>So I should be keeping a record of all UUID 

It would allow you to definitively determine if a location is a duplicate from the plugin.  Without that information, there's no way to say "they are duplicate".

**Comment by stharvey** [comment]
Thanks Chis - I'll do some testing.

Are you able to confirm that a stale location data will have the same uuid as when it was previously received.

I had initially assumed this was a unique identifier that was assigned as the plugin assigned - but it sounds like this comes from location services - is that correct?

**Comment by christocracy** [comment]
No recorded location has the same `uuid`.   The plugin stamps a unique `uuid` upon each location it receives from the OS.

**Comment by christocracy** [comment]
The purpose of `uuid` is primarily for debugging issues precisely like yours.  It allows to compare data received at your server with information found in the the plugin's logs.

For example:
```
I/TSLocationManager(11111):   ✅  INSERT: c1ed5a71-8a13-4a1d-96e8-15593e6130d7
I/TSLocationManager(11111): [c.t.l.http.HttpService flush]
I/TSLocationManager(11111): ╔═════════════════════════════════════════════
I/TSLocationManager(11111): ║ HTTP Service (count: 1)
I/TSLocationManager(11111): ╠═════════════════════════════════════════════
D/TSLocationManager(11111): [c.t.l.d.s.SQLiteLocationDAO first]
D/TSLocationManager(11111):   ✅  Locked 1 records
I/TSLocationManager(11111): [c.t.l.http.HttpService a]
I/TSLocationManager(11111):   🔵  HTTP POST: c1ed5a71-8a13-4a1d-96e8-15593e6130d7
I/TSLocationManager(11111):   🔵  Response: 200
D/TSLocationManager(11111): [c.t.l.d.s.SQLiteLocationDAO destroy]
D/TSLocationManager(11111):   ✅  DESTROY: c1ed5a71-8a13-4a1d-96e8-15593e6130d7
```

**Comment by stharvey** [comment]
Ok, so I'm lost again.

How would it have been possible to have received 2 locations, with identical timestamp, identical coordinates, etc  but different setconfig option an hour or so apart from each other?

I was in contact with the user while this data was being recorded - they didn't backtrack on themselves.

**Comment by christocracy** [comment]
> How would it have been possible to have received 2 locations, with identical timestamp, identical coordinates, etc but different setconfig 

I have no idea.  You would have to observe the plugin logs and compare that to information found at your server.

**Comment by christocracy** [comment]
>Surely because these 2 points were both inserted separately into the plugin DB they will have had different uuids?

They should yes.  Then you would say "these are not identical locations".

**Comment by stharvey** [comment]
Ok sorry, that was bad wording on my part - the timestamp and location coordinates are identical - I can see no way on the server of identifying which one is the correct location to use.

Is it possible somehow (maybe after app restart, or crash, or phone restart) for the background location plugin to be running multiple instances?

**Comment by christocracy** [comment]
>multiple instances?

Absolutely not.  The native libraries are Singletons.

**Comment by stharvey** [comment]
Ok, cheers,

Do you have any hypothesis as to how this might be occurring?

I don't see this very often and I don't know what conditions would be required to reproduce it so I haven't been able to monitor logcat to get full logs.

**Comment by christocracy** [comment]
>How would it have been possible to have received 2 locations

> Do you have any hypothesis as to how this might be occurring?

You're asking the same question.  Like I said above:  "*I have no idea*".

**Comment by stharvey** [comment]
My current plan is to create a new unique identifier based on user ID and the location timestamp - this will enable me to filter out duplicates on the server - but it feels a bit makeshift.

**Comment by stharvey** [comment]
I'll do some more testing and send through logcat logs when I get them.  Thanks for your quick responses.
