### ISSUE TITLE
Android [CHANGEME] This App... Change text

### ISSUE THREAD

**Issue by iSaBo96** [transistorsoft/react-native-background-geolocation#1935]
## Your Environment
* Plugin version: 4.14.5
* Platform: Android
* OS version: 12
* Device manufacturer / model: SAMSUNG Galaxy S10
* React Native version (`react-native -v`): 11.3.1
* Plugin config
```
await BackgroundGeolocation.ready({
            locationAuthorizationRequest: 'Always',
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            backgroundPermissionRationale: {
                title: "Allow {applicationName} to access to this device's location in the background?",
                message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
                positiveAction: "Change to {backgroundPermissionOptionLabel}",
                negativeAction: "Cancel"
            },
            reset: false,
            stationaryRadius: 50,
            debug: false,
            startOnBoot: true,
            stopOnTerminate: false,
            geofenceModeHighAccuracy: true,
            disableMotionActivityUpdates: true
        }).then(async () => {
            await BeaconSpotter.loadAndAddGeofence();

            BackgroundGeolocation.startGeofences();
        });
```

## Expected Behavior
Change permission (backgroundPermissionRationale) text

## Actual Behavior
Permission text is always to "[CHANGEME] This app..."

## Tried to
- Install App new
- Search for solutions in the issues
- Changed reset: false to true

i read the documentations about backgroundPermissionRationale. 
I do not run a start() before. What do i wrong?

**Comment by christocracy** [comment]
Do you know what reset: false does?

The plug-in is not aware of backgroundPermissionRationale you provide to the plug-in until .ready(config) resolves.

If you tell the plug-in to do something that invokes a permission request **before your config has been consumed** (eg .start(), .getCurrentPosition(), .requestPermission, etc, etc), then you will see the default values appear (ie "CHANGEME").

**Comment by iSaBo96** [comment]
I am not 100% sure what reset:false does. As you wrote in another post, I had also set this with : true. The configuration (i.e. ready) is the first thing that is called. Nevertheless I get the CHANGEME message. So do I do this exactly as you wrote or am I misunderstanding something?

**Comment by christocracy** [comment]
> I am not 100% sure what reset:false

Then don't use it.

I suggest you first learn to use the plug-in in a simple "hello-world" app, isolated from your main app.

**Comment by iSaBo96** [comment]
Of course, I first made a minimal example app. Nevertheless, I don't understand the behavior and need a little "thought-provoking impulse" for the

**Comment by christocracy** [comment]
> need a little "thought-provoking impulse" for the

If you tell the plug-in to do something that invokes a permission request before your config has been consumed (eg .start(), .getCurrentPosition(), .requestPermission, etc, etc), then you will see the default values appear (ie "CHANGEME").

**Comment by christocracy** [comment]
See wiki "Debugging" and learn to observe the plug-ins incredibly verbose native logs, which report everything it does,

**Comment by iSaBo96** [comment]
Works, thank you for your food for thought :)
