### ISSUE TITLE
[HELP WANT] background-location with background fetch is not work when app terminate IOS only

### ISSUE THREAD

**Issue by chanphiromsok** [transistorsoft/react-native-background-geolocation#1937]
## Your Environment
* Plugin version: 
* Platform: iOS or Android
* OS version:
* Device manufacturer/model: iPhone 8-Plus OS16.2
* React Native version (`react-native 0.72.6`):

## Package Version

```json
 "react-native": "0.72.6",
 "react-native-background-fetch": "^4.2.1",
 "react-native-background-geolocation": "^4.13.3"
```

## Expected Behavior
IOS when the app is minimized in the background I want to broadcast to the server every 15 minutes with background fetch but it only fires one time after 15 minutes it stops working do you have another solution for this? this issue occurs when the user is not moving so I want users pushing their location at intervals of 15mn with background fetch for android it works fine whereas ios is not work as I expected 
- when user is not move it will broadcast to server every 15mn
- when user move if base on m configuration like above

## My Configuration background-gelocation config 
```js
const backgroundLocationCommonConfigs: Config = {
  url: undefined,
  debug: false, //__DEV__,
  isMoving: true,
  autoSync: true,
  enableHeadless: true,
  startOnBoot: true,
  preventSuspend: true,
  distanceFilter: 60,
  disableElasticity: true,
  batchSync: true,
  maxBatchSize: 2,
  speedJumpFilter: 50,
  maxRecordsToPersist: 2,
  disableAutoSyncOnCellular: false,
  allowIdenticalLocations: false,
  persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  heartbeatInterval: 60,
  backgroundPermissionRationale: {
    message:
      'Your location will be traced at frequent intervals and stored in database of app for showing your availability to users in their location and when you in-route for service.',
  },
  notification: {
    title: 'NHAM24 Driver',
    text: 'Waiting for job',
    sticky: true,
  },
  stopTimeout: Platform.select({
    android: 15,
    ios: 30,
  }),
};
```

## My Config BackgroundFetch
```js
 await BackgroundFetch.configure(
      {
        minimumFetchInterval: 15, // <-- minutes (15 is minimum allowed)
        stopOnTerminate: false,
        enableHeadless: true,
        startOnBoot: true,
        // Android options
        forceAlarmManager: false, // <-- Set true to bypass JobScheduler.
        requiredNetworkType: BackgroundFetch.NETWORK_TYPE_NONE, // Default
        requiresCharging: false, // Default
        requiresDeviceIdle: false, // Default
        requiresBatteryNotLow: false, // Default
        requiresStorageNotLow: false, // Default
      },
      async (taskId) => {
        console.log('[js] Received background-fetch event: ', taskId);
        BackgroundGeolocation.getCurrentPosition({
          persist: true,
          extras: { headless: false },
        });
        MmkvStorage.addEvent(taskId, true);
        BackgroundFetch.finish(taskId);
      },
      (error) => {
        console.log('[js] RNBackgroundFetch failed to start', error);
      }
    );
```

## My Config in index.js

```js
import AsyncStorage from '@react-native-async-storage/async-storage';
import messaging from '@react-native-firebase/messaging';
import { registerRootComponent } from 'expo';
import 'fast-text-encoding';
import { DeviceEventEmitter, Platform } from 'react-native';
import BackgroundFetch from 'react-native-background-fetch';
import BackgroundGeolocation from 'react-native-background-geolocation';
import 'react-native-gesture-handler';
import App from './App';
import API from './src/commons/http/API';

registerRootComponent(App);
BackgroundGeolocation.onHeartbeat(() => {
  BackgroundGeolocation.startBackgroundTask(async (taskKey) => {
    await API.post('http://localhost:4000/location/create', {
      event: 'heartbeat-out',
    }).finally(() => {
      BackgroundGeolocation.stopBackgroundTask(taskKey);
    });
  });
});
onBackgroundNotification();
// this event is trigger only when app killed, when it go to foreground this service will auto killed
const BackgroundGeolocationHeadlessTask = async () => {
  // HEARTBEAT
  BackgroundGeolocation.onHeartbeat(() => {
    BackgroundGeolocation.startBackgroundTask(async (taskKey) => {
      await API.post('http://localhost:4000/location/create', {
        event: 'heartbeat-in',
      }).finally(() => {
        BackgroundGeolocation.stopBackgroundTask(taskKey);
      });
    });
  });

  // MOTIONCHANGE
  BackgroundGeolocation.onMotionChange((event) => {
    BackgroundGeolocation.startBackgroundTask(async (taskKey) => {
      await API.post('http://localhost:4000/location/create', {
        event: 'motion-change-in',
      }).finally(() => {
        BackgroundGeolocation.stopBackgroundTask(taskKey);
      });
    });
  });
};

BackgroundGeolocation.registerHeadlessTask(BackgroundGeolocationHeadlessTask);
const registerHeadlessTask = async (event) => {
  if (event.timeout) {
    console.log('[BackgroundFetch] 💀 HeadlessTask TIMEOUT: ', event.taskId);
    BackgroundFetch.finish(event.taskId);
    return;
  }
  const state = await BackgroundGeolocation.getState();
  console.log('[BackgroundFetch] 💀 HeadlessTask: ', event.taskId, state);
  await BackgroundGeolocation.setConfig({
    ...state,
    extras: {
      ...state.extras,
      headless: true,
    },
  });
  await BackgroundGeolocation.getCurrentPosition({ persist: true, extras: { headless: true } });
  MmkvStorage.addEvent(event.taskId, true); // <-- true means "Headless" TESTING ONLY
  BackgroundFetch.finish(event.taskId);
};
BackgroundFetch.registerHeadlessTask(registerHeadlessTask);
```

I have started `BackgroundGeolocation.ready` and `BackgroundFetch.configure` in my App.ts as the configuration shown above and also I have run `BackroundFetch.start` after calling `BackgroundFetch.configure`

## Steps to Reproduce

1. open app
2. start background fetch
3. minimize the app (IOS)
4. waiting for logger to my local server is how only one time I after that no more push location from ios device

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
2024-02-08 10:15:45.112936+0700 Go24Driver[1772:736730] [TSBackgroundFetch load]: (
)
2024-02-08 10:15:45.113856+0700 Go24Driver[1772:736730] [TSBGAppRefreshSubscriber load]: {
    TSLocationManager = "<TSBGAppRefreshSubscriber identifier=TSLocationManager, executed=0, enabled=1>";
    "react-native-background-fetch" = "<TSBGAppRefreshSubscriber identifier=react-native-background-fetch, executed=0, enabled=1>";
}
2024-02-08 10:16:45.952663+0700 Go24Driver[1772:736730] [TSBackgroundFetch start] (null)
2024-02-08 10:17:29.271864+0700 Go24Driver[1772:736730] [BackgroundTask] Background Task 130 ("Called by Go24Driver, from -[BackgroundTaskManager createBackgroundTask]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

```

</details>

**Comment by christocracy** [comment]
That's right.  There's no such thing as stopOnTerminate: false for iOS.

iOS does not allow background-fetch events to occur after app terminate.  It is impossible on iOS to have a location every 15 minutes after app terminate.

The only thing that can reawaken a terminated iOS app is to physically move at least 200 meters from the last known location.

**Comment by chanphiromsok** [comment]
> That's right. There's no such thing as stopOnTerminate: false for iOS background-fetch
> 
> iOS does not allow background-fetch events to occur after app terminate. It is impossible on iOS to have a location every 15 minutes after app terminate.
> 
> The only thing that can reawaken a terminated iOS app is to physically move at least 200 meters from the last known location.

how about minimized a is possible on iOS to have a location every 15 minutes ?

**Comment by christocracy** [comment]
"Minimized" is another word for "background", which my plug-ins purposely use *in their name* (**background**-fetch, **background**-geolocation).

**Comment by chanphiromsok** [comment]
could you provide it context more clear as what I expect it to be ? if I minimize the app can it keep pushing location to server in every 15mn ?

**Comment by christocracy** [comment]
Let me re-phrase your sentence:  "*If I [put the app in the background], can it keep pushing location to server every 15 minutes?*".

The iOS `background-fetch` API is designed to execute a task periodically when an app is operating in the background (what you call "minimized").

Why don't you try it yourself by simulating tasks as documented in the README?  Place your app in the background then simulate a task.  place a `console.log` into your callback and observe the logs in XCode.

**Comment by chanphiromsok** [comment]
> Let me re-phrase your sentence: "_If I [put the app in the background], can it keep pushing location to server every 15 minutes?_".
> 
> The iOS `background-fetch` API is designed to execute a task periodically when an app is operating in the background (what you call "minimized").
> 
> Why don't you try it yourself by simulating tasks as documented in the README? Place your app in the background then simulate a task. place a `console.log` into your callback and observe the logs in XCode.

Thanks you  I have archived it in IOS now and one more question I really wonder How does Zenly work although I kill the app ? do you have any advice ?

**Comment by christocracy** [comment]
What is "Zenly"?

**Comment by chanphiromsok** [comment]
> What is "Zenly"?

It's tracking app but it just shutdowns location it very accurate on both android and ios without heating battery

**Comment by christocracy** [comment]
Mine doesn't "heat" my battery.

The native location APIs are not a mystery.  Every app uses the same APIs.  There's no secret magic.

This plug-in uses the same location APIs as this "Zenly" and the same APIs as Google / Apple maps native apps.

**Comment by christocracy** [comment]
> it very accurate on both android and ios 

Mine is very accurate too.  I typically see accuracy ~5 meters while outdoors, good enough see detect which side of the street.  But again, it's the same location apis as any native app.

You're aware that you get high accuracy outdoors, right?  GPS only works outdoors.

**Comment by chanphiromsok** [comment]
> > it very accurate on both android and ios 
> 
> Mine is very accurate too.  I typically see accuracy ~5 meters while outdoors, good enough see detect which side of the street.  But again, it's the same location apis as any native app.
> 
> You're aware that you get high accuracy outdoors, right?  GPS only works outdoors.

Your package is good I used it on prod almost 2years  but the configuration but I just raised an issue from the driver report when he didn't make any movement it doesn't broadcast to server
- my server is tracking driver if he doesn't move within 15mn we will set driver to offline so he can't accept the trip that is the problem and now I have fixed it using schedule with background fetch as you said thx you so much please add it to the docs too
