### ISSUE TITLE
"Waiting for previous start action to complete"

### ISSUE THREAD

**Issue by JasimKotai** [transistorsoft/react-native-background-geolocation#1940]
i am getting Warn "Waiting for previous start action to complete" how to fix this..
also can somebody tell me what should i have to add for to run geofence even app is terminated.. this is my app.js code
useEffect(() => {
BackgroundGeolocation.ready(
{
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 10,
// url: 'http://your.server.com/locations',
autoSync: true,
stopOnTerminate: false,
startOnBoot: true,
},
state => {
BackgroundGeolocation.start();
BackgroundGeolocation.startGeofences();
},
);

const addGeofences = async () => {
  try {
    await BackgroundGeolocation.addGeofences(geofences);
    console.log('Geofences added successfully');
  } catch (error) {
    console.error('Error adding geofences:', error);
  }
};
addGeofences();
BackgroundGeolocation.onGeofence(geofence => {
  console.log('[geofence] ', geofence.identifier, geofence.action);
  if (geofence.action === 'ENTER') {
    PushNotification.localNotification({
      channelId: 'test-channel',
      title: geofence.identifier,
      message: `you have reached ${geofence.identifier}`,
      invokeApp: true,
    });
    BackgroundGeolocation.startGeofences();
    console.log('Enter this locayion ', geofence.identifier);
  } else if (geofence.action === 'EXIT') {
    PushNotification.localNotification({
      channelId: 'test-channel',
      title: geofence.identifier,
      message: `you are out of ${geofence.identifier}`,
      invokeApp: true,
    });
    console.log('exit from this locayion ', geofence.identifier);
    BackgroundGeolocation.startGeofences();
    BackgroundGeolocation.start();
  }
});
}, []);

**Comment by christocracy** [comment]
You ignored the issue template containing all kinds of information you were asked to provide.

Try again.
