### ISSUE TITLE
Question: Test the app in a internal test (ANDROID)

### ISSUE THREAD

**Issue by iSaBo96** [transistorsoft/react-native-background-geolocation#1942]
Hello,

i want to test the app in the android google play internal test. But in this section i need a valid location key.
Local i dont need one.

I uploaded the app to google play internal test section. In this i get the message "LOCATION KEY FAILURE".
I know, for production i need a valid key. But can i say the app in the internal test section, the app run in test mode? Like local.  
If yes, how?

I looked in the documentation but I have not found anything in this regard.

Thanks for your help

**Comment by christocracy** [comment]
You don't need to upload the app to Play Store to test the plug-in.

Test locally with a debug build.  Email the .apk to others that need to install the debug build.

**Comment by iSaBo96** [comment]
Thanks. Which .apk file should i send to others? the app_debug.apk? But with this file the server should be run (react-native start)

**Comment by iSaBo96** [comment]
Thank you. But can i create a debug build and send the .apk to others without start the metro server? Other people are not in the same network

**Comment by christocracy** [comment]
1.  Create assets Directory:
```
mkdir ./android/app/src/main/assets/
```

2.  Create bundle output file
```
touch ./android/app/src/main/assets/index.android.bundle
```
3.  Bundle app

```
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```

4.  Create Android debug build
```
cd android && ./gradlew assembleDebug
```

- Your `.apk` exists at `./android/app/build/outputs/apk/debug/app-debug.apk`.  Email that to other users.
- Or manually install onto your usb-connected device:
```
adb install /path/to/app-debug.apk
```

**Comment by iSaBo96** [comment]
Thank you :)
