### ISSUE TITLE
Question: requestPermission always triggers a red debug push notification

### ISSUE THREAD

**Issue by iSaBo96** [transistorsoft/react-native-background-geolocation#1947]
Hello,

if i trigger "await BackgroundGeolocation.requestPermission()" and allow this permission, after this always the red dot in the notification bar is shown. Although "debug: false" is.
Question: Why is this the case? This happens on Android but not on iOS? 
What else triggers a debug?

Excerpt from "BackgroundGeolocation.ready":

```
await BackgroundGeolocation.ready({
            locationAuthorizationRequest: 'Always',
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            backgroundPermissionRationale: {
                title: "{applicationName} benötigt deinen Standort.",
                message: "Bitte erlaube {applicationName} auf deinen Standort mit '{backgroundPermissionOptionLabel}'. Nur so kann ein Angebot im Hintergrund gefunden werden.",
                positiveAction: "Ändern zu {backgroundPermissionOptionLabel}",
                negativeAction: "Abbrechen"
            },
            stationaryRadius: 50,
            debug: false,
            startOnBoot: true,
            stopOnTerminate: false,
            geofenceModeHighAccuracy: true,
            disableMotionActivityUpdates: true
        })

**Comment by christocracy** [comment]
A "push notification" is a notification *pushed* from a **server to a device**.

**Comment by christocracy** [comment]
> the red dot in the notification bar is shown

I have no idea what a "red dot" is.

**Comment by iSaBo96** [comment]
Sorry, I expressed myself incorrectly. What I mean is that there is always a red dot with the app name in the notification bar when "debug: true" is displayed.

**Comment by christocracy** [comment]
Since you **ignored** the issue template, which asked you to provide all sorts of information, I have no idea if you're talking about Android or iOS.

**Comment by iSaBo96** [comment]
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/40924536/a745208f-6eed-4977-88ac-480a6d11fc1b)

**Comment by christocracy** [comment]
Why don't you post a screenshot of what you're talking about?

**Comment by iSaBo96** [comment]
I add a screenshot about the question

**Comment by christocracy** [comment]
The Android version uses ["foreground-services"](https://developer.android.com/develop/background-work/services/foreground-services) in order to operate.  An Android foreground-service **requires** a persistent notification.

No, there's nothing you can do to hide it.  You can only *customize it*, via Config.notification.

**Comment by iSaBo96** [comment]
Thank you for the information
