### ISSUE TITLE
App is not getting the location when app is in killed state

### ISSUE THREAD

**Issue by Muizz12** [transistorsoft/react-native-background-geolocation#1948]
## Your Environment
]
* Platform: iOS or Android
* React Native version (`react-native -0.71.7"`):
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 5,
        heartbeatInterval: 60,
        preventSuspend: true,
        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        // HTTP / SQLite config
        url: 'http://yourserver.com/locations',
        batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
        headers: {
          // <-- Optional HTTP headers
          'X-FOO': 'bar',
        },
        params: {
          // <-- Optional HTTP params
          auth_token: 'maybe_your_server_authenticates_via_token_YES?',
        },
      });
```

## Expected Behavior
App should get the location when app is closed

## Actual Behavior
App is not the getting location when app is closed

## Steps to Reproduce

1.Close the App an if you hear the bing sound then you are getting the location else you are not

**Comment by christocracy** [comment]
> Plugin version
> Platform: iOS or Android

You did not provide answer for (or deleted) required items in the issue template.

**Comment by Muizz12** [comment]
> > Plugin version
> > Platform: iOS or Android
> 
> You did not provide answer for (or deleted) required items in the issue template.

how would i get the access of background location when app is close ?? 
thanks for the response

**Comment by christocracy** [comment]
>Plugin version
>Platform: iOS or Android

You did not provide answer for (or deleted) required items in the issue template.
