### ISSUE TITLE
FOREGROUND_SERVICE_HEALTH

### ISSUE THREAD

**Issue by irvinsingGitHub** [transistorsoft/react-native-background-geolocation#1953]
## Your Environment
* Plugin version: 4.14.6
* Platform: Android
* OS version: 13
* Device manufacturer / model: 
* React Native version (`react-native -v`): 72.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
Issue not related directly to code. More a query.
```

## Expected Behavior

FOREGROUND_SERVICE_LOCATION was identified when uploading bundle to Google Play Console.

## Actual Behavior

"Your app uses the following undeclared foreground service permissions...
FOREGROUND_SERVICE_HEALTH
 FOREGROUND_SERVICE_LOCATION..."
I'm guessing FOREGROUND_SERVICE_HEALTH was required by your plugin?
Google is requesting an explanation for have that in the app.
So that I know how to answer them, could you please explain the reason for having FOREGROUND_SERVICE_HEALTH in the plugin?

## Steps to Reproduce

Not relevant.

## Context

Upload Android bundle to Google Play store.

## Debug logs

<details><summary>Not relevant</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>I'm guessing FOREGROUND_SERVICE_HEALTH was required by your plugin?

Yes.  The plugin uses the Motion API (which comes under the umbrella of "Health") in order to automatically toggle location-tracking when the device is determined to be moving / stationary.

**Comment by christocracy** [comment]
You have to record a video and explain to Play Store that your app uses the "Activity Transition API" to automatically track location when the device is detected to be in-motion, in order to conserve battery power when the device is detected to be stationary".

**Comment by christocracy** [comment]
I cannot say what you should show them.  You need to record a video of your app and explain to them why you need to use the "Motion Transition API" to automatically trigger location tracking when devices are detected to be in-motion, and to turn off location-tracking when devices are detected to be stationary in order to conserve battery power.

**Comment by irvinsingGitHub** [comment]
> @irvinsingGitHub Mine is also getting rejected, did you manage to solve it?

@hisothreed I wasn't using the motion detector in our app. So i decided to remove that permission from the Android manifest, and ultimately didn't have to face the issue right now.

**Comment by hiso3d** [comment]
@TNAJanssen Yes it was accepted

**Comment by TNAJanssen** [comment]
@hiso3d what did you end up using as the reason and the notifing of the user?

**Comment by christocracy** [comment]
For years, this plugin has used the [`ActivityTransistionApi`](https://developer.android.com/develop/sensors-and-location/location/transitions) from `play-services` to know when a device is *moving* (`in_vehicle`, `on_bicycle`, `on_foot`, `running`) or stationary (`still`).  This allows the plugin to intelligently turn on location-services **only when required** and conserving energy when the device is *stationary*.

With Android 14, in order for `ActivityTransition` events to trigger in the background, this API now requires the permission `FOREGROUND_SERVICE_HEALTH`.

So, when providing a reason for usage of `FOREGROUND_SERVICE_HEALTH`, you should say something like:

>We use the Activity Transition API to intelligently enable location-tracking when the app is in the background only when the device is determined to be moving ("on bicycle", "in vehicle", "walking", etc) and to save energy by turning off location-updates when the device is determined to be stationary.

If you *do* remove the `FOREGROUND_SERVICE_HEALTH` permission from your `AndroidManifest`, the plugin will still monitor a geofence around the last known position (what I call "the stationary geofence"), the exit of which will signal that the device is in-motion (this typically requires movement of about 200 meters from the last known location).

To remove `FOREGROUND_SERVICE_HEALTH` from you `AndroidManifest`, all the following element:

```xml
<manifest>
  <uses-permission
    android:name="android.permission.FOREGROUND_SERVICE_HEALTH"
    tools:node="remove" />
  .
  .
  . 
</manifest>
```

Removing this permission will cause your app to have a longer delay initiating location-tracking.  Where tracking might occur within a few meters of movement will now take at least 200 meters.

**Comment by jingp-ofload** [comment]
@christocracy Is there way to optimise this. I've got reject from google.
<img width="747" alt="Screenshot 2024-04-23 at 9 22 30 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/137013304/369d37a4-33d1-46c5-95c6-5e02abd297af">

**Comment by christocracy** [comment]
“Optimize” what?

**Comment by jp928** [comment]
use WorkManger instead?   or stop using health motion apis?

**Comment by christocracy** [comment]
You don’t understand what WorkManager is.

Did you not read the comment above yours?

**Comment by UnderTheMoonspell** [comment]
Our app also started to be rejected although it was already in prod with the lib

**Comment by UnderTheMoonspell** [comment]
@christocracy i had, i edited my post with that info. We are trying to increase the precision of the data collected, this is a step back for us

**Comment by christocracy** [comment]
Then it’s up to you to follow the instructions requested by the Play Store and prove to them why you need that permission.

**Comment by christocracy** [comment]
I’m soon going to completely remove this permission from the plug-in, turning it from an *opt-out* to an *opt-in*.

**Comment by TNAJanssen** [comment]
We got accepted with the reason @christocracy gave us. So when describing it correctly they do allow it

**Comment by UnderTheMoonspell** [comment]
@TNAJanssen we got rejected even with that reason

**Comment by TNAJanssen** [comment]
For us what helped was a permission screen in between asking for permission where we state why we need the health permission.

**Comment by UnderTheMoonspell** [comment]
@TNAJanssen we have the "same" screen, we uploaded a video sending a user to that screen and from there asking for the permissions. Still denied. I think as usual with the stores, it really depends on who checks, theres no golden rule, you just got lucky

**Comment by christocracy** [comment]
> we have the "same" screen, we uploaded a video sending a user to that screen 

Show us your video.

**Comment by jingp-ofload** [comment]
> “Optimize” what?

@christocracy I am sorry if I confused you. What I meant was if by any chance this library could be optimised or bypass the health motion related APIs.

**Comment by christocracy** [comment]
Did you [read this](https://github.com/transistorsoft/react-native-background-geolocation/issues/1953#issuecomment-2027358035)?

**Comment by Glareous** [comment]
i did this...

<manifest>
  <uses-permission
    android:name="android.permission.FOREGROUND_SERVICE_HEALTH"
    tools:node="remove" />
  .
  .
  . 
</manifest>

but the app still ask for Health Permissions...

**Comment by Glareous** [comment]
i did [this.](https://github.com/transistorsoft/react-native-background-geolocation/issues/1953#issuecomment-2027358035)..  

but the app is still asking for health permissions..

**Comment by SchneiderOr** [comment]
We're facing the same issue, it seems like this library using `FOREGROUND_SERVICE`, the suggested fix is not suitable for our needs since we need percise location tracking in bg. 
We couldn't find the appropriate place in google play console to declare this permission, we do tried to add it to the AndroidManifest but no success, any suggestions here?

**Comment by christocracy** [comment]
Also see my blog:  https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a

**Comment by SchneiderOr** [comment]
> See the [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#4163--2024-06-12)

We're using the latest module version
we upgraded from 4.12.1 to 4.16.5 and the error started to appear, no migration or changes seemed to be needed to be taken care of when upgrading, and we still getting this android playsotre api error.

**Comment by christocracy** [comment]
> still getting this android playsotre api error.

What “error”, specifically?

**Comment by SchneiderOr** [comment]
`[!] Google Api Error: Invalid request - You must let us know whether your app uses any Foreground Service permissions.`
It dosent provide any additional details, but this error started since our upgrade from 4.12.1 > 4.16.5

**Comment by christocracy** [comment]
Read my blog, log in to Play Store Console and provide the required information as documented in my blog.

**Comment by SchneiderOr** [comment]
> Read my blog, log in to Play Store Console and provide the required information as documented in my blog.

Thanks, i was finally been able to declare the Foreground permissions in play store, it wasnt showed under app content and i had to search specifically for it within the search in play console.
