### ISSUE TITLE
When sharing background-location it takes more than 1000 meters to share location every time

### ISSUE THREAD

**Issue by Dany-Rolon** [transistorsoft/react-native-background-geolocation#1955]
## Your Environment
* Plugin version: 4.14.6
* Platform: iOS
* OS version: 17.3.1
* Device manufacturer / model: Iphone14Plus
* React Native version (`react-native -v`): 0.72.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      disableLocationAuthorizationAlert: true,
      disableElasticity: true,
      disableStopDetection: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10,
      stopTimeout: 5,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      url,
      batchSync: false,
      autoSync: true,
      preventSuspend: true,
      heartbeatInterval: 60,
      headers: {
        authorization: `Bearer ${user.token}`,
      }
    })
```

## Expected Behavior

When sharing location in background the distance between each location should be smaller, like in Android

## Actual Behavior

In iOS devices, locations are far apart from each other, and during a car trip, it takes more than 1000 meters to share each location.
We cannot observe any stable pattern, as sometimes it takes 500 meters between each location, other times it takes 100, 300, or 1000 meters to share the location. On Android, it works totally differently, and the routes are clearly identifiable.
This happens to us when sharing the location in the background, as it is shared correctly in the foreground.

## Context

Here is a picture that shows how Android and IOS devices tracks my car trip when are in background. 
Yellow line are locations from an Android device, is very accurate, but IOS (red line) for a similar trip just sends 10 locations. 
There are more than 200 meters between some points, enought distance to turn on location services on IOS and start tracking, but unfortunately we are getting just a few locations.

![evidence](https://github.com/transistorsoft/react-native-background-geolocation/assets/77019173/c936370a-bddd-4e22-8b5a-0f6b92cbb37a)

These are another tests, where we cannot observe any stable pattern between each locations, when sharing in background

![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/77019173/cbe65815-1164-418c-9f5d-8437d5391a5e)
![image (1)](https://github.com/transistorsoft/react-native-background-geolocation/assets/77019173/196b5245-66ab-4202-83b2-fc3e6f0e8636)

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- See wiki "Debugging".
- See API docs `Config.debug`.
- Learn to fetch the plugin's incredibly verbose logs.  See API docs `.emailLog`.
- Also learn how to use the plugin's debugging server.  See API docs `Config.transistorAuthorizationToken`.
