### ISSUE TITLE
watchPosition and getCurrentPosition gives back timestamp in different timezones

### ISSUE THREAD

**Issue by peterbodo** [transistorsoft/react-native-background-geolocation#1957]
## Your Environment
* Plugin version: 4.14.6
* Platform: both
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.72.5
* Plugin config
not relevant

## Expected Behavior

watchPosition is used for constant tracking, while at stopping it we send the server a new location with an extra "END" property to let start processing.
The last location is collected immediately after stopping watchPosition by getCurrentPosition.
We expect equal or higher timestamp.

## Actual Behavior

While the last watchPosition-location and the getCurrentPosition is usually the same, the timestamp of getCurrentPosition is 1 hour earlier.
e.g.
last watchPosition location timestamp :  2024-02-26 13:26:54.109
getCurrentPosition timestamp: 2024-02-26 12:26:54.109

The behaviour is replicable.

## Steps to Reproduce

1. await stopWatchPosition
2. getCurrentPosition
3. check timestamps

</details>

**Comment by christocracy** [comment]
Why are you using .watchPosition?  That method is meant for short periods of use while your app is in the background.  It is not meant to be used in the background.

You are not required to use that method.

**Comment by peterbodo** [comment]
We are identifying transport modes, such as walking, cycling, but also need to differentiate public transport from other vehicle modes. 
(Municipalities reward users for sustainable transport mode through our app).
Our algorythm needs frequent data, even when in the background. Also automatic activity recognition is not good enough, but we can improve that using frequent location data.

Nevertheless, the reported issue is still an issue, regardless whether we need or need not use watchPosition.

**Comment by christocracy** [comment]
You only need to call .start().

The plug-in automatically turns on aggressive location updates according to your configured .distanceFilter when the device is detected to be moving.  If you wish to manually engage the tracking state, use .changePace(true).

Read the wiki "Philosophy of Operation".  Also read carefully the api docs .getCurrentPosition and understand what "samples" and location.sample means.

You do not need .watchPosition for your use-case.

**Comment by chanphiromsok** [comment]
`watchPosition` is not working well on android in short period time in foreground it stop sendEvent

**Comment by christocracy** [comment]
> it stop sendEvent

Your problem is unrelated to this issue.

**Comment by chanphiromsok** [comment]
> > it stop sendEvent
> 
> Your problem is unrelated to this issue.

I will open new so
