### ISSUE TITLE
Detecting activity with the closed application

### ISSUE THREAD

**Issue by alejandromizraji** [transistorsoft/react-native-background-geolocation#196]
Hello, I wanted to know if the activitychange and location events execute code even with the application being closed. What i want to do, is to detect if the user parked. So if the activity changes from car to foot it parked and if it changes from foot to car is because he left. All this needs to happen with the app being closed. Is that possible?

sorry for my English.

**Comment by christocracy** [comment]
Read [this](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

**Comment by alejandromizraji** [comment]
Thank you very much that information was very useful !
