### ISSUE TITLE
Pod install - Searching for inspections failed: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by iSaBo96** [transistorsoft/react-native-background-geolocation#1960]
## Your Environment
* Plugin version: 4.15.0
* Platform: iOS
* OS version: 17
* Device manufacturer / model: iPhone 11
* React Native version (`react-native -v`): 12.3.6 - but in the package.json (react-native: 0.73.5 and react: 18.2.0
* Plugin config: Nothing

## Expected Behavior
- running successfull pod install

## Actual Behavior
Get the error "Searching for inspections failed: undefined method `map' for nil:NilClass" after "pod install"

## Steps to Reproduce
1. npx react-native init myTest
2.npm --save i react-native-background-geolocation
3. cd ios
4. pod install

## Context
Delete Podfile.lock and Pods

**Comment by christocracy** [comment]
Did you try searching"undefined method `map' for nil:NilClass"?  It's the first thing *I* did...

https://stackoverflow.com/questions/67443265/error-regarding-undefined-method-map-for-nilnilclass-for-flutter-app-cocoap

**Comment by iSaBo96** [comment]
I have to run the "arch -x86_64 gem install ffi" command with "--user-install". After this, works fine. Thank you. Can be closed :)

**Comment by christocracy** [comment]
You opened the issue:  you can close it.
