### ISSUE TITLE
Background Geolocation Fails to Fetch Location in Background or Locked Screen

### ISSUE THREAD

**Issue by socheatleang** [transistorsoft/react-native-background-geolocation#1961]
Location Permission Re-prompt on Resume from Background/Lock Screen Hinders Activity Data Retrieval. Has anyone else encountered this issue, or is it specific to my device?

## Your Environment
* Plugin version: ^4.14.3
* Platform: iOS or Android: android & ios
* OS version: iOS (17.2) & Android (11)
* Device manufacturer / model: Oneplus 6T
* React Native version (`react-native`): 0.71.14
* Expo (`react-native`): ^48.0.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      disableElasticity: true,
      stopTimeout: 2,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: true,
      startOnBoot: true,
      batchSync: false,
      autoSync: false,
      locationAuthorizationRequest: 'WhenInUse',
    });
```

## Expected Behavior

With the ** WhenInUse**'s permission, The app should continuously fetch and record the user's location in the background, even when the screen is locked or when the app is not actively in use. There should not be any need for the user to re-allow permissions once they have been granted initially, ensuring a seamless tracking experience.

## Actual Behavior

When the app goes into the background or when the phone's screen is locked, the location tracking sometimes prompts the user to allow location permissions again upon resuming. Additionally, the app fails to fetch or record the location data while running in the background or on a locked screen. This issue happens only sometimes. Not all the time

## Steps to Reproduce

1. Start location tracking with the app.
2. Allow location with ** WhenInUse**'s permission
3. Send the app to the background or lock the phone screen.
4. After some time (20-30mn), resume the app.
5. Notice the permission prompt reappears randomly and the location data isn't fetched while in the background or on a locked screen.

## Context

I am sure that: 
* I keep moving with the device when the activity has started 
* I won't interact with any app when my app is in background mode
* The battery is in normal mode. No power save mode or under 20%. 
* 
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
With WhenInUse permission, did you know that you must *manually* engage location-tracking while your app is in the foreground by calling `.changePace(true)` (after calling `.start()`?

**Comment by socheatleang** [comment]
Hi @christocracy . Thanks for respond. 

Yeah, I have managed to trigger `.changePace(true)` after calling `.start()`

    await BackgroundGeolocation.start();
    await BackgroundGeolocation.changePace(true);
    BackgroundGeolocation.watchPosition(
      (location) => {},
      (errorCode) => {
        console.log('[watchPosition] ERROR -', errorCode);
      },
      {
        interval: 2000,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      }
    );

**Comment by ltgreen123** [comment]
For us the app fails to fetch and post the location when the app is in the background or the screen is locked.  Nothing to do with a permission prompt.  This is only the case for iOS however.  with Android there is no issue.

**Comment by christocracy** [comment]
Without showing the Config you're using or plugin logs (see wiki "Debugging"), there's no way to even speculate.
