### ISSUE TITLE
Geofence ENTER events being triggered outside the geofence

### ISSUE THREAD

**Issue by UnderTheMoonspell** [transistorsoft/react-native-background-geolocation#1971]
## Your Environment
* Plugin version: 4.14.3
* Platform: iOS 
* OS version: 17.2
* Device manufacturer / model: Simulator
* React Native version (`react-native -v`): 0.72.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
         url: ******,
         headers: {
            ...getGlobalDefaultHeaders(),
         },
         autoSync: true,
        geofenceModeHighAccuracy: true, // <-- consumes more power; default is false.
        debug: false, // NOTE: if true it will request the notification permissions
        reset: false,
        logLevel: __DEV__
          ? BackgroundGeolocation.LOG_LEVEL_VERBOSE
          : BackgroundGeolocation.LOG_LEVEL_OFF,
        stopOnTerminate: false,
        startOnBoot: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        disableLocationAuthorizationAlert: true,
        locationAuthorizationRequest: 'Always',
        disableMotionActivityUpdates: true,
        backgroundPermissionRationale: strings.screen.geolocationIntro.androidPermissionsDialog,
        params: {
          user_id: userId,
          device_id: deviceId || undefined,
        },
}
```

## Expected Behavior
Geofence ENTER events should be triggered inside the geofence

## Actual Behavior
Some of our users have ENTER events outside the geofence (sometimes even like 3km away) while the accuracy reported is the same as for events that are good.

We have some users that have EXIT events quite far from the geofence, but according to [this](https://github.com/transistorsoft/react-native-background-geolocation/issues/1939) it is to be expected, so thats fine. We have a bigger issue though, which is our users having ENTER events outside the geofence like shown in the screenshots:

<img width="1096" alt="Screenshot 2024-03-21 at 12 04 50" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/10156878/2517b49b-3ed6-4457-b74b-cdb0335c893f">
<img width="1183" alt="Screenshot 2024-03-21 at 12 06 18" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/10156878/4219d786-44a0-4622-b3de-a50a5577b963">

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Have you reproduced this yourself?

**Comment by UnderTheMoonspell** [comment]
@christocracy no, not yet, but I assume that unlike the EXIT events far away, these ENTER events should not be happening right?
