### ISSUE TITLE
Customizing Alert shown on Android

### ISSUE THREAD

**Issue by mohankyro22** [transistorsoft/react-native-background-geolocation#1975]
![shared image](https://github.com/transistorsoft/react-native-background-geolocation/assets/103193315/a321896f-975f-47c2-b484-b3cd862c9e81)
<img width="315" alt="Screenshot 2024-03-25 at 7 35 15 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/103193315/d05c7367-4729-4f9f-b5bc-8a0af61f3869">

How to customize the Message shown on this. Anything on this @christocracy

**Comment by mohankyro22** [comment]
In Android it is working fine.

**Comment by christocracy** [comment]
See API docs `Config.backgroundPermissionRationale`

**Comment by mohankyro22** [comment]
I found this strange,

The Android APK when I tested before adding the License key - I got the current location update in abour 2 seconds or at max 3 second. 

But when I add License key and test It takes 10 seconds to get the current location. 

Was that expected or is there any way I can solve it.

**Comment by mohankyro22** [comment]
But the same code I could experience the above.

**Comment by mohankyro22** [comment]
Would it be better If I share the code ? @christocracy

**Comment by christocracy** [comment]
I suggest you post a new issue.

**Comment by mohankyro22** [comment]
Closing this issue for now as the discussion got completed
