### ISSUE TITLE
Location getting delayed when I add License key to Android app

### ISSUE THREAD

**Issue by mohankyro22** [transistorsoft/react-native-background-geolocation#1977]
Location getting delayed when I add License key to Android app

Is there any way I can overcome the above.

## Your Environment
* Platform: iOS or Android: Android
* OS version: 
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.70.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    useEffect(() => {
        BackgroundGeolocation.ready({
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10,
          stopTimeout: 1000,
          debug: false,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: false,
          startOnBoot: true,
        })
      }, [])

    const fetchCurrentLocation = async () => {
      try {
        BackgroundGeolocation.start()
        setIsLoading(true)
        await BackgroundGeolocation.getCurrentPosition({
          persist: true,
          samples: 2,
          timeout: 1000,
          maximumAge: 10000,
          extras: {
            getCurrentPosition: true,
          },
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        }).then((location: Location) => {
          const { longitude, latitude, altitude, accuracy } = location.coords
          const locationDetails = {
            longitude,
            latitude,
            altitude,
            accuracy,
            timestamp: new Date(),
          }
    
          if (setFieldValue && fieldName) {
            setFieldValue(fieldName, JSON.stringify(locationDetails))
            setIsLoading(false)
          }
        }).catch((err) => {
          console.error('Location fetching Inner Catch Error', err)
        })
      } catch (error) {
        console.warn('[getCurrentPosition] error: ', error)
        // Handle error appropriately (e.g., show error message)
      } finally {
        BackgroundGeolocation.stop()
      }
    }
```

## Expected Behavior
To get location quicker when license key is added. 

## Actual Behavior
Significantly there is delay in getting the current location when I added the License key to the Android App.
Before adding the License key it was about 2 or 3 seconds to get the currentLocation but after adding License key it is taking about 10 seconds.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> there is delay in getting the current location when I added the License key to the Android App.

It can only be a coincidence.  Adding the license key cannot possibly affect the time retrieving a location.

- Set `debug: true`.  
- Observe the logs with `$ adb logcat *:S TSLocationManager:V`.
- Go outside to test.  GPS only works outdoors.

**Comment by mohankyro22** [comment]
Will check and update.

**Comment by mohankyro22** [comment]
Hey @christocracy,

I got a question. 

We use 3 different env's for our RN application. When I add the License key to AndroidManifest main file. 

The key validation failure message is not been shown on dev and prod but showing up on the stage. 

Is there anything on it ?

**Comment by mohankyro22** [comment]
we use as .stage.

**Comment by mohankyro22** [comment]
Doesn't the plugin allow that ?

**Comment by christocracy** [comment]
>Doesn't the plugin allow that ?

No.  The only known suffixes are listed above.  The plugin is not aware of the suffix `.stage`.  Rename yours to `.staging` and it will work.

**Comment by mohankyro22** [comment]
Ok thanks.

![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/103193315/5e6675c6-4b1d-433b-88a9-8e8e7a12f441)

For now we are only using getCurrentPosition. Is the above alert will mandatorily show. Is there a way to disable this.

**Comment by mohankyro22** [comment]
We aren't making use of background location fetching as of now.

**Comment by christocracy** [comment]
See API docs `Config.disableMotionActivityUpdates`.

**Comment by mohankyro22** [comment]
LOG_LEVEL_VERBOSE

Do we have to use this in the config ? Can this be removed ?

**Comment by christocracy** [comment]
> LOG_LEVEL_VERBOSE

This is for developer debugging and testing only.  Released app should have LOG_LEVEL_NONE

**Comment by mohankyro22** [comment]
Ok thanks

**Comment by mohankyro22** [comment]
If we disable using Config.disableMotionActivityUpdates as true. 
We need not mention **NSMotionUsageDescription** in the info.plist

**Comment by Manikandan-saminathan** [comment]
we are getting an app rejection with following message:
```
ITMS-90683: Missing purpose string in Info.plist. 
Your app’s code references one or more APIs that access sensitive user 
data, or the app has one or more entitlements that permit such access. 
The Info.plist file for the "{app-bundle-path}" bundle should contain a 
NSLocationWhenInUseUsageDescription key with a user-facing purpose string 
explaining clearly and completely why your app needs the data.
If you’re using external libraries or SDKs, they may reference APIs that 
require a purposeful string. While your app might not use these APIs, a 
purpose string is still required. For details, visit: 
https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.
```

**Comment by mohankyro22** [comment]
<img width="1235" alt="Screenshot 2024-03-28 at 6 13 06 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/103193315/dcb542da-895a-4f60-a72e-f9e00dfba863">
We are getting like this when app is submitted for play store. 


As per the your docs on Android Manifest file we have to add the License key alone right ?

But on this https://github.com/transistorsoft/react-native-background-geolocation/issues/1149#issuecomment-726295227

I could see some of ACCESS_BACKGROUND_LOCATION permission and all. 

We are only using current position request as of now. 

@christocracy will be happy to hear from you asap.

**Comment by christocracy** [comment]
See [my blog about this](https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353).  Pay particular attention to the *final paragraph*, showing you how to manually remove a requested permission.

**Comment by christocracy** [comment]
>So do we have to add this to AndroidManifest file ?

That is *exactly* what is says, no?

<img width="740" alt="Screenshot 2024-03-28 at 10 15 01 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/917d00f3-f44f-48e2-9001-08d5667b3cf4">

**Comment by mohankyro22** [comment]
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/103193315/23062b06-b33c-4f41-9533-73ca06a1a55c)


We are seeing this on the Play store submission.

Do we have to set,

<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

or

<uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" />
 <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />
 
 @christocracy  ?

**Comment by Manikandan-saminathan** [comment]
> ![image](https://private-user-images.githubusercontent.com/103193315/317831413-23062b06-b33c-4f41-9533-73ca06a1a55c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODQ2ODcsIm5iZiI6MTcxMTY4NDM4NywicGF0aCI6Ii8xMDMxOTMzMTUvMzE3ODMxNDEzLTIzMDYyYjA2LWIzM2MtNGY0MS05NTMzLTczY2EwNmExYTU1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwMzUzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTYzMGRmOGRmMzMzOTg4ZGE1NmIwZTkwYzZkNzU3MGZlYTExMmE5NDBmOGVlOWFiMDRkOTdiZDI5MTk5MDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WJDaiXSO6-NTH70oyk5AAzdgHU7QEvc6zZz8uHxzJeY)
> 
> We are seeing this on the Play store submission.
> 
> Do we have to set,
> 
> `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />`
> 
> or
> 
> `<uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" /> <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />`
> 
> @christocracy ?

Any update on this @christocracy

**Comment by Manikandan-saminathan** [comment]
I was also removed from the below permission using ```tools:remove``` option
```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" tools:node="remove" />
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" tools:node="remove" />
  
```

**Comment by mohankyro22** [comment]
Do we have to execute

```
useEffect(() => {
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      locationAuthorizationRequest: 'WhenInUse',
      disableMotionActivityUpdates: true,
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
```

this on all the screens wherever the location is being fetched ?
