### ISSUE TITLE
Random Chinese Character E-Mail after we bought an API Key

### ISSUE THREAD

**Issue by milan2sky** [transistorsoft/react-native-background-geolocation#1979]
## Your Environment
* Plugin version: we bought an api key
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

A normal E-Mail (For example in English)

## Actual Behavior

After I activated the API Key I got some strange E-Mail where the content was in some Chinese. But it seemed to be random. I could not get a clue with google translate, but it detected Chinese mainland.
I think it might be related to some encoding on your side???
**This is NOT a Joke.**

(today `20:21:09 MEZ`)

## Steps to Reproduce

1. Buy the starter plan for `react-native-background-geolocation`
2. Connect with an GitHub account
3. Create an API Key in the dashboard
4. Check your E-Mail client for a strange Chinese character mix email. The subject of the mail was `[Transistor Software] License
Key: my-top-secret-package-name`. The content of the Email was this strange Chinese mix.

## Context
<!--- What were you trying to do? ⟶
I 
## Debug logs
<!-- include iOS / Android logs
- ios Xcode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
⟶
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE ⟶ 
I am willing to redirect @christocracy the email that we received.
```

</details>

**Comment by christocracy** [comment]
My server sends 20-50 emails / day (for years) and I get a bcc of each.  Whatever the problem is, it’s *very rare*.

**Comment by christocracy** [comment]
Please forward the email to info@transistorsoft.com

**Comment by milan2sky** [comment]
My client has forwarded the Mail.
He used the iOS Apple Mail App.
