### ISSUE TITLE
Can schedule be used on iOS as well?

### ISSUE THREAD

**Issue by JAStanton** [transistorsoft/react-native-background-geolocation#198]
Can #schedule method be used on iOS?
If so what's happening under the covers to wake up the app?
When schedule runs will the entire JS boot up? 

I switch between two configs "active" and "passive". Where "passive" config is set up to track location less frequently, and "active" at a much higher rate. This is a truck fleet situation where sometimes the driver will be on a job, sometimes they wont. I know when they will be and would like to schedule when the app wakes up and changes it's config. Is this a good use case for `schedule`?

**Comment by christocracy** [comment]
I return from vacation next week.

**Comment by JAStanton** [comment]
Hey @christocracy I filed 3 issues last couple of days. PLEASE don't look at them until you're off vacation :) enjoy and relax!

**Comment by christocracy** [comment]
The Android scheduler is much more precise than iOS.  Android uses `AlarmManager` to schedule wake-ups and generally fires on-the-minute.

iOS, however, is much more strict with background operation.  The iOS scheduler relies on [background-fetch](https://github.com/transistorsoft/react-native-background-fetch) events, whose frequency is completely determined by iOS but typically fire often even 15 minutes.  The iOS plugin will evaluate the schedule:
- Whenever a fetch event occurs.
- App is brought to foreground / moved to background.
- Whenever a location is recorded.
