### ISSUE TITLE
onMotionChange doesn't trigger properly with stopTimeout

### ISSUE THREAD

**Issue by socheatleang** [transistorsoft/react-native-background-geolocation#1982]
**onMotionChange** doesn't trigger when with the configuration with stopTimeOut. 

## Your Environment
* Plugin version: ^4.14.3
* Platform: iOS & Android
* OS version: iOS(17.2), Android(11)
* Device manufacturer / model: iOS(iPhone 13pro), Android(Onplus 6T)
* React Native version (`react-native -v`): 0.71.14
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
   BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5,
      stopTimeout: 10,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: true,
      startOnBoot: true,
      batchSync: false,
      autoSync: false,
      locationAuthorizationRequest: 'WhenInUse',
      locationUpdateInterval: 2000,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
    }).ready();
```

## Expected Behavior

When I use **stopTimeout** with a value of 10, I expect the onMotionChange to be triggered if the user doesn't move for 10 minutes.

## Actual Behavior

**onMotionChange** hit only I trigger changePace. 

## Steps to Reproduce

1. Start the service
2. Go out and walk with physical device for 40mn and stop move for 15mn. 
3. And continue to walk

## Context

I am sure that I subscribed to the motion after **.ready()**. I try to put the phone on the desk without movement, the onMotionChange still doesn't hit. 
</details>

**Comment by christocracy** [comment]
Delete the following items from your Config then go test again:

> disableStopDetection: true,
> pausesLocationUpdatesAutomatically: false,

**Comment by socheatleang** [comment]
@christocracy  Thanks.

**Comment by christocracy** [comment]
Read those two config options to yourself:  It should become obvious why deleting those options is the solution.
