### ISSUE TITLE
Persistent Beeping and Inaccurate Location Data Despite Disabling Debug Mode

### ISSUE THREAD

**Issue by vjgpt** [transistorsoft/react-native-background-geolocation#1987]
## Your Environment
* Plugin version: 4.16.0
* Platform: iOS
* OS version: 17.4.1
* Device manufacturer / model: Apple iPhone 15 pro
* React Native version (`react-native -v`): 2.0.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    await BackgroundGeolocation.ready({
      // Debug
      reset: false,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      // Geolocation
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10,
      stopTimeout: 5,
      geofenceInitialTriggerEntry: true,
      // Permissions
      locationAuthorizationRequest: "Always",
      // HTTP & Persistence
      autoSync: true,
      maxDaysToPersist: 14,
      // Application
      stopOnTerminate: false,
      stopDetectionDelay: 0,
      stopOnStationary: true,
      startOnBoot: true,
      enableHeadless: true,
      preventSuspend: true,
      notification: {
        title: "Proto is running in the background",
        text: "Proto is using your location for trips and checkins.🎉",
      },
    }).then((state) => {
      if (!state.enabled) {
        console.log(BackgroundGeolocation.getCurrentPosition({
          persist: true, maximumAge: 5000,
          desiredAccuracy: 10,
          samples: 3
        }));
        BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior

- The application should not emit debug sounds once movement is detected if the debug mode is off.
- GPS data should be stable and accurate, without random jumps when the device is stationary.
- The system should avoid sending location data points that are significantly inaccurate, especially those suggesting movements over large distances that didn't actually occur.

## Actual Behavior

- Despite having debug mode turned off, the application continues to emit a beeping sound with every background location update, indicating that debug sounds are not being disabled as expected.
- The quality and accuracy of GPS data have significantly deteriorated, with the device reporting locations miles away from the actual position of the user, including some data points suggesting movements between 20km to 4000km away from the true location.
- The GPS also inaccurately indicates movement when the device is stationary, leading to unreliable location tracking.

I've attached screenshots. Please let us know what you think, and if in case we are doing something wrong.

![IMG_6287](https://github.com/transistorsoft/react-native-background-geolocation/assets/22372476/c1e8a531-9ae5-46a3-930f-fee47637e3a5)
![IMG_6288](https://github.com/transistorsoft/react-native-background-geolocation/assets/22372476/d3702ecf-5e50-48ca-84fd-37c48f19319b)
![IMG_6289](https://github.com/transistorsoft/react-native-background-geolocation/assets/22372476/fb944007-39b9-4418-88a0-4ba17d596742)

[trip_raw_anamoly_tp_3443.csv](https://github.com/transistorsoft/react-native-background-geolocation/files/14895686/trip_raw_anamoly_tp_3443.csv)
("look at the gap between 1397227 and 1397226 id")
[trip_raw_anamoly_ay_3424.csv](https://github.com/transistorsoft/react-native-background-geolocation/files/14895687/trip_raw_anamoly_ay_3424.csv)
("look at the gap between 1396422 and 1396423 id")

## Steps to Reproduce

we are just recording the data points coming from the SDK with initialisation(refer to above code)

## Context

We want to track the location data of user wherever he travels and where does he stops accurately

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
> Persistent Beeping 

Do you n is what `reset: false` does?  Why are you using that?

your images are useless because you’re not showing location markers, only a polyline.

**Comment by vjgpt** [comment]
It appears that the team initially adopted the `reset: false` configuration from a sample application and later adjusted the settings to fit our specific needs. This detail likely went unnoticed during the process. 

I've also uploaded two CSV files containing relevant data points, which should be useful for our discussion.
