### ISSUE TITLE
Getting inconsistent behavior regarding activity regocnition

### ISSUE THREAD

**Issue by andreydiskin** [transistorsoft/react-native-background-geolocation#1988]
## Your Environment
* Plugin version: 4.16.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: Galaxy S 21 Ultra /  Galaxy S 23 Ultra / Xiaomi 13T (high-end sensor rich devices)
* React Native version (`react-native -v`): 11.3.7, package: `0.72.5`
* Plugin config
```ts <!-- Syntax-highlighting:  paste your code below -->
export const BACKGROUND_GEOLOCATION_CONFIG: Config = {
  desiredAccuracy: isIos
    ? BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION
    : BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  locationAuthorizationRequest: 'Always',
  backgroundPermissionRationale: {
    title: "some title",
    message:
      "If you would like to use the app then you'll need to enable {backgroundPermissionOptionLabel} location permission",
    positiveAction: 'Change to {backgroundPermissionOptionLabel}',
    negativeAction: 'Cancel',
  },
  distanceFilter: 10,
  // Activity Recognition
  stopTimeout: 5,
  // Application config
  debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: true, // <-- Allow the background-service to continue tracking when user closes the app.
  startOnBoot: true, // <-- Auto start tracking when device is powered-up.
  batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
  autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
};
```

## Expected Behavior

Correctly update activity and speed 

## Actual Behavior

So the behavior I'm getting is flaky - sometimes activity fails to update, getting stuck on "still" or "walking".
This is solved by phone restart, what makes me think about cleanup related things.

## Steps to Reproduce

No clear reproduction steps - flaky behavior.
Can happen also mobile device restart

## Context

Creating an app that monitors driving, depending on speed and activity monitor

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

# package usage lifecycle

1. Calling BackgroundGeolocation.ready() once, on app initial load
2. holding a flag that indicates success .ready() invocation
3. calling `BackgroundGeolocation.start()` when we know .ready() finished successfully
4. registering a listener to `onActivityChange`
```ts
BackgroundGeolocation.onActivityChange(async (event) => {
            setCurrentActivity(event.activity);
          });
```
6. calling `BackgroundGeolocation.watchPosition()` and getting location, speed, and activity. I have to say coordinates are always correct

**Comment by christocracy** [comment]
The Motion api is provided by Google Play Services.  It is a black box with only an “on/off” switch.  It has no configuration; it cannot be fine-tuned.  It depends completely upon the quality of sensors on the device (accelerometer, gyroscope and magnetometer).

**Comment by andreydiskin** [comment]
@christocracy I think that issue is not in the sensors, since when it works it is accurate.
I thought it might be to initialization/cleanup. 
Is there a way to forcefully cleanup background tasks the package performs and start fresh?

**Comment by christocracy** [comment]
> Is there a way to forcefully cleanup background tasks the package performs and start fresh?

No

**Comment by andreydiskin** [comment]
@christocracy 
Is there anything wrong this my usage of the package? What's mentioned in `package usage lifecycle`

Is this a known issue?

**Comment by christocracy** [comment]
If you’re getting “unusual results” from the ActivityRecognition api, there’s nothing you can do.  There is no config option for the plug-in that affects this.  The Motion api is either ON or OFF — that’s it.
