### ISSUE TITLE
Heartbeat bug: timestamp always the same.

### ISSUE THREAD

**Issue by JAStanton** [transistorsoft/react-native-background-geolocation#199]
Heartbeat timestamps are always the same for Android stationary devices. What I am forced to do is when I receive heartbeat to overwrite the timestamp with current time. Is this safe?

Also I think I'm on an old android RNBG build so maybe this is fixed upstream.

## Your Environment
* Plugin version: 2.2.0
* Platform: iOS or Android: Android
* OS version: Mac OS Sierra 10.12.2 
* Device manufacturer / model: Emulator Nexus 5 SDK 23
* React Native version (`react-native -v`): 0.39.2
* Plugin config: 

This is the callback from configure:
```js
        "enabled": true,
        "trackingMode": "location",
        "foregroundService": false,
        "maxBatchSize": 20,
        "configureInterval": 0,
        "license": "<SECRET>",
        "batchSync": true,
        "autoSyncThreshold": 0,
        "maxDaysToPersist": 1,
        "forceReloadOnHeartbeat": false,
        "activityRecognitionInterval": "10000",
        "forceReloadOnGeofence": false,
        "forceReloadOnMotionChange": false,
        "deferTime": "0",
        "stopAfterElapsedMinutes": 0,
        "fastestLocationUpdateInterval": "60000",
        "geofenceProximityRadius": "1000",
        "disableElasticity": false,
        "autoSync": false,
        "geofenceInitialTriggerEntry": true,
        "startOnBoot": true,
        "method": "POST",
        "desiredAccuracy": 0,
        "notificationText": "Location Service activated",
        "minimumActivityRecognitionConfidence": 75,
        "maxRecordsToPersist": -1,
        "distanceFilter": 0,
        "isMoving": false,
        "persist": true,
        "locationUpdateInterval": "60000",
        "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
        "logMaxDays": 3,
        "disableStopDetection": false,
        "stationaryRadius": 25,
        "forceReloadOnBoot": false,
        "locationTimeout": 60,
        "stopTimeout": "5",
        "schedulerEnabled": false,
        "logLevel": 5,
        "debug": false,
        "stopOnTerminate": false,
        "heartbeatInterval": 60,
        "forceReloadOnLocationChange": false
```

I also set these properties, but I don't see them coming back in `#configure`:
```js
disableMotionActivityUpdates: true, 
preventSuspend: true,
```

## Expected Behavior
Every time I get a heartbeat from `.on('heartbeat')` I expect the timestamp to be the current time.

## Actual Behavior
Timestamp is always the first heartbeat that I received.

## Steps to Reproduce

1. Boot up app with this config
2. dont move the android device
3. log out heartbeat's location timestamp
4. see that timestamp never changes from first heartbeat

## Context
Trying to get heartbeats from a driver that is standing still. 

## Debug logs
```
02-04 10:36:50.742  2923  3879 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
02-04 10:36:50.765  2923  3515 D ReactNativeJS: [native] TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
02-04 10:36:50.774  2923  3515 I ReactNativeJS: [Location] _onHeartbeat HEY! 2017-02-04T18:14:48.000Z

02-04 10:37:51.284  2923  3888 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
02-04 10:37:51.301  2923  3515 D ReactNativeJS: [native] TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
02-04 10:37:51.308  2923  3515 I ReactNativeJS: [Location] _onHeartbeat HEY! 2017-02-04T18:14:48.000Z

02-04 10:38:51.290  2923  3900 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
02-04 10:38:51.308  2923  3515 D ReactNativeJS: [native] TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
02-04 10:38:51.318  2923  3515 I ReactNativeJS: [Location] _onHeartbeat HEY! 2017-02-04T18:14:48.000Z
```
Let me know what additional logs you want.

**Comment by christocracy** [comment]
This isn't a bug.  The plugin's `heartbeat` event does **not** ever request a new location.  The location returned is merely the *last known location*.

If you wish to fetch the current location in your callback, that's your responsibility to do do that with `#getCurrentPosition`.

**Comment by JAStanton** [comment]
What is `timestamp` supposed to represent?

**Comment by christocracy** [comment]
The `timestamp` of the last known location.

**Comment by JAStanton** [comment]
Good, ok so if `timestamp` always reflect the last known location, and heartbeats always gives you the last known location. I would therefore expect that timestamp would always be current and never stale.

Said another way:
If I am getting heartbeats because I am standing still, can I assume that at each heartbeat the user is at the heartbeat's location? If so timestamp should always reflect the time at which I get the heartbeat. If not I should never trust heartbeat to reflect current users location.

**Comment by JAStanton** [comment]
BTW I totally understand your'e returning cached location and not re-requesting from GPS. This is a good assumption if you don't detect any motion activity and I would expect this.

**Comment by christocracy** [comment]
The plugin provides you the last-known location *as a convenience*.  You're free to check the timestamp and make your own assumption about whether the location is too old.  You're free to request another one with `#getCurrentPosition`.  The plugin will **not** modify the `timestamp` as provided by the native location-services.  I would prefer to *not* even provide this "last known location" to the event but the person who paid for this feature wanted it.

The `heartbeat` event only fires when the plugin detects the device is stationary.  When the device is detected to be moving, `heartbeat` stops and the plugin changes state to **moving** mode where it begins recording a location each `distanceFilter` meters.

You should *never* trust `heartbeat` to reflect the current position.

**Comment by JAStanton** [comment]
> You should never trust heartbeat to reflect the current position.

very interesting. Thank you!

**Comment by JAStanton** [comment]
You should put that in the docs if you haven't already

**Comment by christocracy** [comment]
The docs for `heartbeat` could use a re-write.

**Comment by christocracy** [comment]
Be careful with `preventSuspend`.  You shouldn't expect to run that 24/7.  It should only be engaged for a carefully managed period of time.
