### ISSUE TITLE
Location authorization modal texts not updating

### ISSUE THREAD

**Issue by rabbiss** [transistorsoft/react-native-background-geolocation#1991]
## Your Environment
Using the demo app: https://github.com/transistorsoft/rn-background-geolocation-demo
* Plugin version: 4.16.0
* Platform: Android
* OS version: 14
* Device manufacturer / model: Google Pixel 6a
* React Native version (`react-native -v`): 0.73.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    // Ready the SDK and fetch the current state.
    const state:State = await BackgroundGeolocation.ready({
      // Debug
      reset: false,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      transistorAuthorizationToken: token,
      // Geolocation
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10,
      stopTimeout: 5,
      // Permissions
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access this device's location even when closed or not in use.",
        message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel'
      },
      // HTTP & Persistence
      autoSync: true,
      maxDaysToPersist: 14,
      // Application
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true
    });
```

## Expected Behavior
Using the demo app's advanced mode backgroundPermissionRationale texts should be visible in the location authorization modal. Also the locationAuthorizationRequest when set to "whenInUse" should make this modal go away, now it doesn't -> "whenInUse" and "Always" constantly bring up the same modal.

## Actual Behavior
Allow BGGeolocation -modal has the "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y" texts even though backgroundPermissionRationale texts are configured. Also, changing the value of locationAuthorizationRequest between "whenInUse" and "Always" has no effect on the modal. Previously the modal did not appear when set to "whenInUse".

## Steps to Reproduce
1. Select Advanced App
2. Press toggle button in the up right corner.
3. Observer modal
4. Change plugin config's locationAuthorizationRequest from "Always" to "WhenInUse"
5. Retrace steps 1-3

**Comment by christocracy** [comment]
> reset: false,

Do you know what this does?

**Comment by rabbiss** [comment]
If I'm reading the docs correctly it persists any previously set configuration. So changing the value of locationAuthorizationRequest has no effect? I'm curious, what's the use-case for setting this to false?

**Comment by christocracy** [comment]
The use-case is my demo app, which has a comprehensive “Settings” screen to control the plug-in Config.  I don’t want .ready(config) to override the Settings screen changes I’ve set, each time the app is launched.

very few use-cases require reset: false.  

Just **delete** that option from your Config (don’t event set it to `true`)
