### ISSUE TITLE
BackgroundGeolocation onGeofence calling multiple times causing performance issue

### ISSUE THREAD

**Issue by SAPLMobileDev** [transistorsoft/react-native-background-geolocation#1999]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^4.15.2"
* Platform: Android
* OS version: 10, 12
* Device manufacturer / model:
* React Native version (`react-native -v`): "react-native": "0.73.2"
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

useEffect(() => {
    console.log(`subscribe`);
    subscribe(BackgroundGeolocation.onGeofence(setGeofenceEvent));
    return () => {
      // Important for with live-reload to remove BackgroundGeolocation event subscriptions.
      unsubscribe();
      clearMarkers();
    };
  }, []);
 
  useEffect(() => {
    if (!geofenceEvent) return;
    const updatedGeofenceHitEvents = updateGeofenceHitEvents(geofenceEvent);
    if (
      updatedGeofenceHitEvents.length !== geofenceHitEvent.length ||
      !updatedGeofenceHitEvents.every(
        (newItem, index) =>
          newItem.ShopId === geofenceHitEvent[index].ShopId &&
          newItem.Action === geofenceHitEvent[index].Action,
      )
    ) {
      setGeofenceHitEvent(updatedGeofenceHitEvents);
    }
  }, [geofenceEvent]);
```

## Expected Behavior
Same geofence identifier event should not trigger again.

## Actual Behavior
same geofence identifier event getting called multiple times.

## Steps to Reproduce

1.
2.
3.
4.

## Context
We are first subscribing to the geofence events then we are applying our business logic into that but geofenceHitEvent getting update many times that causes useEffect to re render multiple time and causing performance issue 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->

```

</details>

**Comment by christocracy** [comment]
Observe the plugin's native logs with `$ adb logcat *:S TSLocationManager:V`.

Ensure the *native* geofence event fires just *once*.  If it does, then the problem is within your own Javascript.

```
04-17 09:37:13.992 19996 14041 I TSLocationManager: [c.t.l.s.GeofencingService a]
04-17 09:37:13.992 19996 14041 I TSLocationManager: ╔═════════════════════════════════════════════
04-17 09:37:13.992 19996 14041 I TSLocationManager: ║ Geofencing Event: ENTER
04-17 09:37:13.992 19996 14041 I TSLocationManager: ╠═════════════════════════════════════════════
04-17 09:37:13.992 19996 14041 I TSLocationManager: ╟─ Home
04-17 09:37:13.992 19996 14041 I TSLocationManager: ╚═════════════════════════════════════════════
```

**Comment by SAPLMobileDev** [comment]
Yes, we checked as you said but event is triggerd 8 times and 12 times

![image (2)](https://github.com/transistorsoft/react-native-background-geolocation/assets/120235337/800fc8be-80ae-48a0-8ebf-e779993eeb9f)
![image (3)](https://github.com/transistorsoft/react-native-background-geolocation/assets/120235337/9d6a952a-c2a8-4dc0-b48a-e49e9a2f7e52)

**Comment by christocracy** [comment]
Show me more of your code.  Where you’re adding/removing geofences and the specific attributes you’re providing your geofences.

**Comment by SAPLMobileDev** [comment]
this are referance files,
usegeofence :- custom hook
Goefence:- first screen registration done from here for the library  its a separate screen
Plotgeofence:-  screen where in db operation done and then passed to hook to register geofence

[Plotgeofence.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/15028947/Plotgeofence.txt)

[Usegeofence.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/15028949/Usegeofence.txt)

[Geofence.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/15028948/Geofence.txt)

**Comment by hasanal95** [comment]
any updates here, i have same issue
