### ISSUE TITLE
Couple of Questions

### ISSUE THREAD

**Issue by rt2zz** [transistorsoft/react-native-background-geolocation#2]
This module looks awesome! couple of questions:
1) Is this module free to use? I see it is licensed MIT but I also see on your page that you sell a similar product?
2) You mention android in the docs, but react-native android is not out yet. Are these just placeholders for how it will work once react-native android is released?

**Comment by christocracy** [comment]
1.  Only iOS will be free.  I'll be [selling Android](http://shop.transistorsoft.com/pages/react-native-background-geolocation#plans) (On sale until React-Native Android support is released with promo-code `react-native-sale`)

2. Once React releases Android support, I'll quickly whip up the required facade.  As you can see from the [iOS facade](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/RNBackgroundGeolocation/RNBackgroundGeolocation.m) (which is mostly complete), it doesn't take much code to wire up.

**Comment by rt2zz** [comment]
thanks :)
