### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by ct-jeffweinberg** [transistorsoft/react-native-background-geolocation#2000]
The template is not relevant to this request. 

Please add the excellent documentation from (locationAuthorizationRequest)[https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#3--locationauthorizationrequest-39any39] in the generated API docs to a section in the Home page of the Wiki, or to the Philosophy of Operation section.  

While this was my own experience and the best step would have been to thoroughly read the type annotations or the API docs, I found it hard to find relevant information on the idiosyncrasies of iOS location permissions and spent a good amount of time having to read through issues to find what I was looking for. I think that this is an important topic and worthy of its own place in the wiki as the content is already written in a convenient how to guide with code examples. 

Thanks for your consideration.

**Comment by jrweinb** [comment]
Its also worth adding this to the Using the Plugin guide in the Readme:

From the generated docs [here](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#ready):

Warning: You must call #ready once and only once, each time your app is launched.
Do not hide the call to #ready within a view which is loaded only by clicking a UI action. This is particularly important for iOS in the case where the OS relaunches your app in the background when the device is detected to be moving. If you don't ensure that #ready is called in this case, tracking will not resume.

This is easy to miss and not doing it causes subtle bugs that are hard to find as the plugin still mostly works.

**Comment by christocracy** [comment]
Thanks for the feedback.

**Comment by christocracy** [comment]
- Added *[Location Authorization: WhenInUse vs Always](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation#location-authorization--wheninuse-vs-always)* section to Wiki *Philosophy of Operation*.
- Added **two** links to [read the api docs](https://github.com/transistorsoft/react-native-background-geolocation?tab=readme-ov-file#large_blue_diamond-example) in the README.
