### ISSUE TITLE
[Android] Health apps requirement for accessing the ACTIVITY_RECOGNITION permission

### ISSUE THREAD

**Issue by PaitoAnderson** [transistorsoft/react-native-background-geolocation#2003]
<img width="920" alt="Screenshot 2024-04-19 at 3 25 51 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/4108718/8b395a62-01c7-4051-84f8-59c884982239">

## Your Environment
* Plugin version: 4.14.3
* Platform: Android
* OS version: N/A
* Device manufacturer / model: N/A
* React Native version (`react-native -v`): 0.72.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
No issues in Play Store

## Actual Behavior
Received this message in the Play Store

> Your app uses the android.permission.ACTIVITY_RECOGNITION permission and must meet [Health apps policy requirements](https://support.google.com/googleplay/android-developer/answer/13996823). If you don't have any health features in your app, remove this permission from your app's manifest.

## Steps to Reproduce

1. Add `react-native-background-geolocation` to App
2. Publish on Play Store

## Context
Publish on Play Store

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Yes, the plug-in uses the Motion API to automatically triggger location-tracking in the background.  The Motion API comes under the umbrella of “Health”.  The Play Store has become more strict about this permission, requiring you explain in detail why you’re using the motion API, which is to automatically trigger location-tracking in the background. 

This is an accepted exemption for foreground-service launches.

see “Exemptions from background start restrictions“ in the [Android Docs](https://developer.android.com/develop/background-work/services/foreground-services#background-start-restriction-exemptions)

![IMG_0770](https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/3ddd3ed6-1915-4d33-9526-7efa2cda665c)

**Comment by christocracy** [comment]
The plug-in can, of course, operate without the motion api (it uses a Geofence around the last known position to detect movement).  Your app will take longer distances to engage location-tracking (requiring movement of at least 200 meters)

**Comment by PaitoAnderson** [comment]
Is there a way to include `react-native-background-geolocation` without that permission? In our use case requiring a movement of at least 200 meters is OK.

The Play Store Health form isn't great, and doesn't let you explain why you need it sadly, it's just an Other checkbox:
<img width="639" alt="Screenshot 2024-04-19 at 3 58 05 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/4108718/8ee6ec25-8616-4736-8371-5748269940d5">

Thanks for the quick reply @christocracy

**Comment by christocracy** [comment]
See the last paragraph of my blog [here](https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353) to learn how to remove specific permissions from your app.

**Comment by stharvey** [comment]
Hello.  Is it possible to remove this permission in Expo/EAS workflow?

**Comment by christocracy** [comment]
See my [latest blog-post about this](https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a)
