### ISSUE TITLE
Describing use of required reason for specific iOS APIs leveraged

### ISSUE THREAD

**Issue by GuptaAman08** [transistorsoft/react-native-background-geolocation#2005]
## Your Environment
* Plugin version: 4.10.0
* Platform: Android
* OS version: android 13
* Device manufacturer / model:  iOS Phone
* React Native version (`react-native -v`): 0.71.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      distanceFilter: 50,
      stopOnTerminate: true,
      startOnBoot: false,
      stopTimeout: 20,
      enableHeadless: false,
      heartbeatInterval: 60,
      locationAuthorizationRequest: 'WhenInUse',
      disableMotionActivityUpdates: false,
      extras: {},
      url: <server_url>,
      authorization: <function_that_returns_auth_token>,
      autoSync: true
}
```
Hey, @christocracy 
Just have a concern related to citing the required reasons for the use of specific iOS APIs. Since failing to do so can cause our app to be rejected on App Store Connect. The due date is 1st May 2024. FYR - [link](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

Are there any specific changes that need to be performed from your library integration standpoint on our side? 
I am trying to gauge any action items on our end so that no failure happens at the time of deployment.

**Comment by christocracy** [comment]
I’m well aware of the new *Privacy Manifest*.

See the updated iOS Setup Instructions linked in the readme.

**Comment by GuptaAman08** [comment]
Hi Chris, I read the apple doc for the required reasons API and the integration steps you mentioned in your ReadMe. 

But, I had a doubt here on the integration front, the stuff I need to do as mentioned in the [link](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md#privacy-manifest). As per apple all these integrations needs to be done on the third party SDK side which actually uses the API and not in the App. 
So, don't you think this should be present in your library? 

![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/31820923/87277d04-1a25-4c1c-82e4-74457adf75d1)

Please correct me if I am wrong !!

**Comment by GuptaAman08** [comment]
Hi @christocracy , any comment on the above ??
