### ISSUE TITLE
App not opening after debug install

### ISSUE THREAD

**Issue by ncpanigrahy** [transistorsoft/react-native-background-geolocation#2006]
Dear Team,
I follow as per the installation guide and after installation of the debug apk i am getting this error not sure how can i resolve as per document to use in release version purchase is required but not in debug mode and anyway after testing it properly, we go with release mode.

![WhatsApp Image 2024-04-25 at 19 04 17_ec31f8f6](https://github.com/transistorsoft/react-native-background-geolocation/assets/7733606/b0381be1-96d1-4734-8641-f4b6cd88174d)

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Duplicate https://github.com/transistorsoft/rn-background-geolocation-demo/issues/137
