### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by adi-436** [transistorsoft/react-native-background-geolocation#2009]
I have configured everything for iOS according to the documentation for installation but code is not working . The Same code works fine for android devices. Also i have tried to use the example code in the iOS device still it doesn't work,  can anyone help?

**Comment by christocracy** [comment]
See wiki “Debugging” and learn to observe the logs in XCode.

**Comment by adi-436** [comment]
My functionality is that i have to send the current location of the user through socket.io event if the app is in foreground or background . But this is working fine in android but not in IOS. can you please that what can be the reason for the same @christocracy

**Comment by adi-436** [comment]
@christocracy

**Comment by christocracy** [comment]
The plug-in has nothing to do with your application code, including Socket.io.

the plug-in fires events.  What you do in those event-handlers is your own responsibility.

also, see api docs .startBackgroundTask.

**Comment by adi-436** [comment]
I know , but my point is that i have followed every step to initialise your sdk in my app , but my functions works in android , but not even getting the location in iOS in foreground mode also please help.
and also in iOS app i get these notification ,how can i disable them


![Image](https://github.com/transistorsoft/react-native-background-geolocation/assets/115211259/e86a16a3-a1f9-4f43-989e-66f9f87f3497)

**Comment by christocracy** [comment]
See api docs Config.debug.  Those notifications are helpful when debugging and fieldtesting,

see wiki “Debugging” also.

**Comment by christocracy** [comment]
The issue template is not *optional* -- it's required.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by adi-436** [comment]
How can i disable the notification i receive from your library, as i downloaded the app from testflight still i recieve notification please help. @christocracy

**Comment by adi-436** [comment]
**This is my code** 

configureBackgroundGeolocation = () => {
    BackgroundGeolocation.configure({
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 50,
      distanceFilter: 50,
      notificationTitle: 'Background tracking',
      notificationText: 'enabled',
      debug: false,
      startOnBoot: true,
      stopOnTerminate: true,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 10000,
      fastestInterval: 5000,
      activitiesInterval: 10000,
      stopOnStillActivity: false,
      notification: false,
    });

    BackgroundGeolocation.onLocation(this.onLocation);
  };

  onLocation = location => {
    if (this.sendLocationUpdates) {
      // Send location update to server
      console.log('Sending location update to server:', location);
      if (store.getState().HomeReducer.savedactivejobid) {
        socket.emit('update_location', {
          latitude: location.coords.latitude,
          longitude: location.coords.longitude,
          order_id: store.getState().HomeReducer.savedactivejobid,
          user_id: store.getState().HomeReducer.savedmyuserid,
        });
      }
    }
  };

  startTrackingLocation = () => {
    this.watchId = BackgroundGeolocation.start();
  };

  stopTrackingLocation = () => {
    if (this.watchId !== null) {
      BackgroundGeolocation.stop();
      this.watchId = null;
    }
  };

  setSendLocationUpdates = shouldSend => {
    this.sendLocationUpdates = shouldSend;
  };
  
  **In App.js**
   LocationService.startTrackingLocation();
    LocationService.setSendLocationUpdates(true);
    
    
    
    But this is working fine in android not in iOS please help @christocracy

**Comment by christocracy** [comment]
Learn to [syntax highlight code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks).

also, you’ve still not provided all the requested information from the issue template.
