### ISSUE TITLE
With debug turned on and the plugin in a stopped state still getting CLVisit log notifications

### ISSUE THREAD

**Issue by kevinmanncito** [transistorsoft/react-native-background-geolocation#2011]
## Your Environment
* Plugin version: 4.16.1
* Platform: iOS
* OS version: 17.4.1
* Device manufacturer / model: Apple iPhone Mini 13
* React Native version: 0.73.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 15,
  stopTimeout: 5,
  preventSuspend: false,
  isMoving: true,
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  stopOnTerminate: false,
  startOnBoot: false,
  stationaryRadius: 25,
  locationAuthorizationRequest: 'Always',
  foregroundService: true,
  backgroundPermissionRationale: {
    title: `${APP_NAME} Location Permission`,
    message: `Allow ${APP_NAME} to track your location in the background to provide alerts when nearing points of interest`,
    positiveAction: 'OK',
    negativeAction: 'Cancel',
  },
  locationAuthorizationAlert: {
    titleWhenNotEnabled: 'Location Permission Required',
    titleWhenOff: 'Location Services Required',
    instructions:
      "You must enable 'Always' in location-services for location alerts to work",
    cancelButton: 'Cancel',
    settingsButton: 'Settings',
  },
  batchSync: false,
  autoSync: false,
})
```

## Expected Behavior

When the plugin is in a stopped state there should be no gps access happening in the background.

## Actual Behavior

As I move around throughout the day I keep getting CLVisit log notifications on my ios device. I can't seem to find anywhere in the docs explaining what a CLVisit is and why it would be happening in a stopped state.

![IMG_84F74A2BE4D4-1](https://github.com/transistorsoft/react-native-background-geolocation/assets/2521298/17fd6f06-6be7-4964-acae-fdc7eb62d633)

## Steps to Reproduce

1. Turn on the plugin for tracking
2. Turn off the plugin (`BackgroundGeolocation.stop()`)
3. Debug notifications that indicate gps access is happening continue to happen throughout the day

## Context

With the plugin turned off it appears the gps is still getting turned on occasionally. I would expect no gps access to be happening in the stopped state.

## Debug logs

<details><summary>Logs - N/A</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plugin does not initiate the iOS "Visits" api `CLLocationManager startMonitoringVisits`.

I had experimented with this API *9 years* ago but the code to initiate the "Visits API" remains commented-out.

<img width="1077" alt="Screenshot 2024-04-30 at 10 15 15 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/0afac8d8-e2bb-4fe8-a222-4559ef74366c">

A delegate method `didVisit` still exists, which does nothing more than show a debug notification.

<img width="990" alt="Screenshot 2024-04-30 at 10 17 04 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/2047b98c-879c-4236-89aa-9e8f42c3fa8f">

You have *some other plugin* installed in your app which is initiating the "Visits API" (calling `locationManager startMonitoringVisits`, which is globally causing every `CLLocationManager` instance, including my plugin's own delegate-method, to respond.

I have *never* seen this debug notification appear in my own demo app, nor have I heard anyone else report this in over 9 years.

**Comment by christocracy** [comment]
> should be no gps 

Btw, the [iOS Visits API](https://developer.apple.com/documentation/corelocation/clvisit?language=objc) doesn't use GPS, it operates by reporting connections to a familiar Wifi SSID, firing an event with the location of that Wifi endpoint.

Nevertheless, you need to audit your other plugins to find out which plugin is calling [`CLLocationManager startMonitoringVisits`](https://developer.apple.com/documentation/corelocation/cllocationmanager/1618692-startmonitoringvisits?language=objc) and learn how to tell that plugin to call [`CLLocationManager stopMonitoringVisits`](https://developer.apple.com/documentation/corelocation/cllocationmanager/1618693-stopmonitoringvisits?language=objc)

**Comment by kevinmanncito** [comment]
Thanks for the prompt response! I was getting very confused when I couldn't find anything in the docs about this but I was sure the notification was coming from the plugin.
