### ISSUE TITLE
app stops detecting location if motion timer is interrupted 

### ISSUE THREAD

**Issue by sirusbaladi** [transistorsoft/react-native-background-geolocation#2014]
## Your Environment
* Plugin version:   4.16.0
* Platform: iOS 
* OS version: 17.4.1
* Device manufacturer / model: Iphone 13 pro
* React Native version (`react-native -v`):  "0.71.14
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

  const bgGeoEventSubscriptions = [];
  const currentGeofence = useRef(null);

  const unsubscribe = () => {
    bgGeoEventSubscriptions.forEach((subscription) => subscription.remove());
  };

  const subscribe = (subscription) => {
    bgGeoEventSubscriptions.push(subscription);
  };

  useEffect(() => {
    initBackgroundGeolocation();
    // registerTransistorAuthorizationListener(navigation);

    return () => {
      unsubscribe();
    };
  }, []);

  useEffect(() => {
    if (user && user?.uid && user?.photoURL && user?.displayName) {
      initGeofences();
    }
  }, [user]);

  const initGeofences = async () => {
    // const cachedInGeofence = retrieveData("inGeofence");

    // inGeofence.current = cachedInGeofence !== null ? cachedInGeofence : false;
    // previousGeofence.current = retrieveData("previousGeofence");

    const geofences = await getGeofences(user.uid);
    // const geofences = await getGeofences("4dyWdQzWDPg0ljrv3SG5COgKqqu1");

    BackgroundGeolocation.removeGeofences().then((success) => {
      BackgroundGeolocation.addGeofences(geofences)
        .then((success) => {
          console.log("Successfully added geofences", success);
        })
        .catch((error) => {
          console.error("Error adding geofences", error);
        });
    });
  };

  const initBackgroundGeolocation = async () => {
    // Listen to events.  Each BackgroundGeolocation event-listener returns a subscription instance
    // with a .remove() method for removing the event-listener.  You should collect a list of these
    // subcribers and .remove() them all when the View is destroyed or refreshed during dev live-reload.
    subscribe(
      BackgroundGeolocation.onProviderChange((event) => {
        // console.log("[onProviderChange]", event);
      })
    );

    subscribe(
      BackgroundGeolocation.onLocation(
        (location) => {
          // console.log("[onLocation]", location);
        },
        (error) => {
          console.warn("[onLocation] ERROR: ", error);
        }
      )
    );

    subscribe(
      BackgroundGeolocation.onMotionChange((event) => {
        try {
          console.log("[onMotionChange]", event);

          // retrive the last known motion state from cache
          // we add the ?? true so that at first opening it will still pass.
          // if at first opening is at home, currentGeofence.current will be 'home' and not make the if pass anywyay.
          const lastIsMoving = retrieveData("lastIsMoving") ?? true;

          // store the current 'isMoving' state into cache
          storeData("lastIsMoving", event.isMoving);

          if (event.isMoving) {
            Notifications.scheduleNotificationAsync({
              content: {
                title: `Moving mode activated`,
                body: `${user?.displayName}`,
              },
              trigger: null,
            });
          }

          // Create location post
          // Case when we are not in a geofence already and we were moving before stopping
          if (
            !event.isMoving &&
            currentGeofence.current === null &&
            lastIsMoving === true
          ) {
            // Creating Location Post
            BackgroundGeolocation.startBackgroundTask()
              .then(async (taskId) => {
                console.log("Sending notification for being stationary.");

                Notifications.scheduleNotificationAsync({
                  content: {
                    title: `Started checking where you are`,
                    body: `${user?.displayName}, please wait`,
                  },
                  trigger: null,
                });

                let currentPosition =
                  await BackgroundGeolocation.getCurrentPosition({
                    timeout: 120,
                    persist: true,
                    maximumAge: 0,
                    desiredAccuracy: 1,
                    samples: 10,
                  });

                notifyStationary(
                  user,
                  currentPosition.coords.latitude,
                  currentPosition.coords.longitude
                );
                BackgroundGeolocation.stopBackgroundTask(taskId);
              })
              .catch((error) => {
                // Add a semicolon here
                // Be sure to catch errors:  never leave you background-task hanging.
                console.error(error);
                BackgroundGeolocation.stopBackgroundTask();
              });
          }
        } catch (error) {
          console.error(error);
        }
      })
    );

    subscribe(
      BackgroundGeolocation.onGeofence((event) => {
        // Update global variabel so that is in geoFence onMotionChange doesn't update post when stationary
        try {
          currentGeofence.current =
            event.action == "EXIT" ? null : event.identifier;

          if (event.action === "EXIT") {
            deleteCache("lastGeofenceNotExited");
          }

          const lastGeofenceNotExited = retrieveData("lastGeofenceNotExited");

          Notifications.scheduleNotificationAsync({
            content: {
              title: `currentGeofence variable is`,
              body: `${currentGeofence.current}`,
            },
            trigger: null,
          });

          if (lastGeofenceNotExited === event.identifier) {
            Notifications.scheduleNotificationAsync({
              content: {
                title: "still in same geofence, not making post on DWELL",
                body: `${lastGeofenceNotExited}`,
              },
              trigger: null,
            });
          }

          if (
            event.action === "DWELL" &&
            event.identifier !== "home" &&
            lastGeofenceNotExited !== event.identifier
          ) {
            BackgroundGeolocation.startBackgroundTask()
              .then(async (taskId) => {
                storeData("lastGeofenceNotExited", currentGeofence.current);
                Notifications.scheduleNotificationAsync({
                  content: {
                    title: `You are in geofence, making post`,
                    body: "Please wait",
                  },
                  trigger: null,
                });

                createPostLocation({
                  placeName: event.extras.placeName,
                  placeId: event.extras.placeId,
                  placeType: event.extras.placeType,
                  longitude: event.location.coords.longitude,
                  latitude: event.location.coords.latitude,
                  utcOffset: event.extras.utcOffset,
                  formattedAddress: event.extras.formattedAddress,
                  user: user,
                });

                BackgroundGeolocation.changePace(false).then(() => {
                  console.log(
                    "[BackgroundGeolocation] to stationary state given Geofence DWELL event"
                  );
                });

                BackgroundGeolocation.stopBackgroundTask(taskId);
              })
              .catch((error) => {
                console.error(error);
                BackgroundGeolocation.stopBackgroundTask();
              });
          } else if (event.action === "DWELL") {
            storeData("lastGeofenceNotExited", currentGeofence.current);

            Notifications.scheduleNotificationAsync({
              content: {
                title: "DWELL event, not making post.",
                body: `${lastGeofenceNotExited}`,
              },
              trigger: null,
            });

            BackgroundGeolocation.changePace(false).then(() => {
              console.log(
                "[BackgroundGeolocation] to stationary state given Geofence DWELL event"
              );
            });
          }
        } catch (error) {
          console.error(error);
        }
      })
    );

    subscribe(
      BackgroundGeolocation.onConnectivityChange((event) => {
        // console.log("[onConnectivityChange]", event);
      })
    );

    subscribe(
      BackgroundGeolocation.onEnabledChange((enabled) => {
        // console.log("[onEnabledChange]", enabled);
      })
    );

    subscribe(
      BackgroundGeolocation.onHttp((event) => {
        // console.log("[onHttp]", event);
      })
    );

    subscribe(
      BackgroundGeolocation.onActivityChange((event) => {
        // console.log("[onActivityChange]", event);
      })
    );

    subscribe(
      BackgroundGeolocation.onPowerSaveChange((enabled) => {
        // console.log("[onPowerSaveChange]", enabled);
      })
    );

    /// Get an authorization token from demo server at tracker.transistorsoft.com
    const token =
      await BackgroundGeolocation.findOrCreateTransistorAuthorizationToken(
        "sirus",
        "tester"
      );

    /// Configure the plugin.
    BackgroundGeolocation.ready({
      showsBackgroundLocationIndicator: false,
      stopTimeout: 15,
      debug: true,
      stationaryRadius: 100,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      logMaxDays: 1,
      transistorAuthorizationToken: token,
      distanceFilter: 10,
      stopOnTerminate: false,
      startOnBoot: true,
    }).then((state) => {
      BackgroundGeolocation.start();

      // used for debugging
      // BackgroundGeolocation.changePace(true).then(() => {
      //   console.log("[BackgroundGeolocation] is in the moving state");
      // });
    });
  };
```
## Issues related to this:
https://github.com/transistorsoft/react-native-background-geolocation/issues/1864
https://github.com/transistorsoft/react-native-background-geolocation/issues/1764
https://github.com/transistorsoft/react-native-background-geolocation/issues/2007

## Expected Behavior

1. If the user walks, then stops for less than the stopTimeout (in this case 15), and moves again the app should immediately recognize that the user is moving, show the debugging notifications and update the server with the location.
2. Often, since the app sleeps before the stopTimeout hits, even if the user is not moving for a long time, the app doesn't change motion to stationary (unless the user manually opens the app)

## Actual Behavior

1. The app at some point within the stopTimeout sleeps and the user has to move substantially for it to reboot. 
2. The app should always or almost always recognize when the user goes into stationary mode without having the user opening the app manually 

## Steps to Reproduce

1. set stoptimeout to 15
3. walk for a while, then stop for 10 minutes then keep walking. Repeat.

**Comment by christocracy** [comment]
> walk for a while, then stop for 10 minutes then keep walking. Repeat.

I just took a walk to my local park.  Everything worked properly.

sat on bench.  Set stopwatch for 10 min.  Set phone down flat on bench.

after stopwatch expired, picked up phone then walked.  Plug-in halted stopTimeout timer and resumed tracking after a few meters walking.

I’ve been testing this functionality almost daily for 10 years and it never fails.

**Comment by sirusbaladi** [comment]
> > walk for a while, then stop for 10 minutes then keep walking. Repeat.
> 
> I just took a walk to my local park. Everything worked properly.
> 
> sat on bench. Set stopwatch for 10 min. Set phone down flat on bench.
> 
> after stopwatch expired, picked up phone then walked. Plug-in halted stopTimeout timer and resumed tracking after a few meters walking.
> 
> I’ve been testing this functionality almost daily for 10 years and it never fails.

that's a great news. Do you see any problem in my js code?

I've been trying to make this work for the past 2 weeks.

**Comment by sirusbaladi** [comment]
> sat on bench. Set stopwatch for 10 min. Set phone down flat on bench.

btw. in my test I did not use or open the phone at all, so the stopwatch ideally would have not been the phone one but an external one. but I believe you when you say that it works, I just don't understand why I can't make it work, testing it in multiple devices.

**Comment by christocracy** [comment]
> so the stopwatch ideally would have not been the phone one but an external one

It doesn’t matter.  I know exactly how these APIs work and I’ve been doing this same type of test almost every day, as I said, for over 10 years.  I run the demo app on my phone 24x7.

**Comment by sirusbaladi** [comment]
> > so the stopwatch ideally would have not been the phone one but an external one
> 
> It doesn’t matter. I know exactly how these APIs work and I’ve been doing this same type of test almost every day, as I said, for over 10 years. I run the demo app on my phone 24x7.

I finally found the issue and now the app works perfectly, at least in my most recent tests.

Believe it or not, the issue is in: **showsBackgroundLocationIndicator: false**.
When setting it to true, it works otherwise it has issues as described in above and in https://github.com/transistorsoft/react-native-background-geolocation/issues/2007 and probably in the other issues mentioned above. 

This is weird as that setting should only affect the phone visually but apparently without it the app will start sleeping at some point even when it shouldn't. 

This is a problem as having the indicator on constantly when the user moves is going to annoy my users. 

Could you let me know if there's a fix for this?

**Comment by christocracy** [comment]
> showsBackgroundLocationIndicator: false

**Don’t do this**.  Recent versions of iOS changed the behaviour of this, encouraging you to always show the location identifier.

**Comment by sirusbaladi** [comment]
> > showsBackgroundLocationIndicator: false
> 
> **Don’t do this**. Recent versions of iOS changed the behaviour of this, encouraging you to always show the location identifier.

The documentation should be updated as people might spent a lot of time trying to figure this one out. 

I know competitor apps that have constant location monitoring and work perfectly without showing the location identifier, so is this something we could have too with this library?

**Comment by jessicazu** [comment]
>I know competitor apps that have constant location monitoring and work perfectly without showing the location identifier, so is this something we could have too with this library?

I would like to know too.

**Comment by jessicazu** [comment]
@christocracy 
Thank you for the response.
I believe the basis for the operation in the background without the indicator, when `distanceFilter: 0` is set, can be found in this post by an Apple engineer on the forum:
https://forums.developer.apple.com/forums/thread/726945



> `allowsBackgroundLocationUpdates` must be set to TRUE or YES
> `distanceFilter` must not be set, or set to `kCLDistanceFilterNone`
> `desiredAccuracy` must be `kCLLocationAccuracyHundredMeters` or better. If you’re using numeric values, it must be set to less than 1000 meters

I cannot be certain that these conditions are met in this library, as the implementation is not public. Moreover, I have replicated the issue where location updates do not resume in the background (even when moving beyond a geofence).

The current settings are as follows:

```ts
await BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      showsBackgroundLocationIndicator: false,
      stationaryRadius: 1,
      stopTimeout: 5,
      debug: false,
      logLevel: isProductionAppEnv
        ? BackgroundGeolocation.LOG_LEVEL_OFF
        : BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
    })
```

Do these settings meet the above conditions?

As a premise, we have purchased this library and are operating it in a production environment.
