### ISSUE TITLE
Library doesn't work properly with showsBackgroundLocationIndicator: false

### ISSUE THREAD

**Issue by sirusbaladi** [transistorsoft/react-native-background-geolocation#2015]
## Your Environment
* Plugin version:   4.16.0
* Platform: iOS 
* OS version: 17.4.1
* Device manufacturer / model: Iphone 13 pro
* React Native version (`react-native -v`):  "0.71.14
* Plugin config: showsBackgroundLocationIndicator: false

## Why this issue
Given the importance of this feature, the fact that competitors app don't have this issue,  and the big churn of users that not having this would cause, I believe this should be addressed with priority.

If not in the free version of the library, this should be fixed at least in the paid version of it as I don't feel comfortable releasing an app to prod without this working. 

## Issues related to this:
https://github.com/transistorsoft/react-native-background-geolocation/issues/1864
https://github.com/transistorsoft/react-native-background-geolocation/issues/1764
https://github.com/transistorsoft/react-native-background-geolocation/issues/2007
https://github.com/transistorsoft/react-native-background-geolocation/issues/2014

## Expected Behavior
The library should work regardless of showsBackgroundLocationIndicator: false or true. 

## Actual Behavior
At random times, the library sleeps, logs as well as motion changes and locations are not tracked anymore unless the user opens the app manually.

## Steps to Reproduce

1. set showsBackgroundLocationIndicator: false
2. set a 15 minutes stopTimeout
3. walk around, stopping and interrupting the timeout and stopping without interrupting it.

**Comment by christocracy** [comment]
> showsBackgroundLocationIndicator: false

Don’t use this.  If you insist on it, you must use distanceFilter: 0 and deal with a massive amount of location data.

this is due to a choice by Apple.

**Comment by sirusbaladi** [comment]
> > showsBackgroundLocationIndicator: false
> 
> Don’t use this. If you insist on it, you must use distanceFilter: 0 and deal with a massive amount of location data.
> 
> this is due to a choice by Apple.

I feel like this won't solve it completely as the app will still be suspended by apple while waiting for stopTimeout to hit as it happened many times before. 


For my particular application I don't really need to keep track the location of users while moving, but I only need a snapshot of their location when motion changes from moving to stationary. Do you see any way to do this?

Related to the above, is there a way to keep the app open in the background only with the motion api active? In that case the blue icon won't be needed too.

**Comment by christocracy** [comment]
> Do you see any way to do this?

No.

> is there a way to keep the app open in the background only with the motion api active?

No.  It’s the location api being turned on which allows the OS to keep an app alive in the background, allowing the motion api to keep running.  Turning on the location api gives an app **special priority** to remain running in the background (how else would a Maps app be able to do turn-by-turn driving instructions?).

there is **no possible way** to keep an app alive in the background to run the Motion API only.  Well, there is another way which would be less applicable:  enabling the “Background Audio” capability and starting an audio stream.  Apple will, of course, heavily scrutinize and likely reject that use-case.
