### ISSUE TITLE
`changePace` true -> true seems to interrupt `getCurrentLocation`

### ISSUE THREAD

**Issue by curtisy1** [transistorsoft/react-native-background-geolocation#2016]
## Your Environment
* Plugin version: 4.14.4
* Platform: Android
* OS version: 13
* Device manufacturer / model: OPPO Find X2 Pro / PDEM30
* React Native version (`react-native -v`): 0.73.6
* Plugin config
```javascript 
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  reset: true,
  stopTimeout: 1,
  distanceFilter: 1000,
  heartbeatInterval: 60,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: true,
  startOnBoot: false,
  url: baseUrl + "/api/v1/position",
  batchSync: true,
  autoSync: false
```

## Expected Behavior
Setting `changePace` to `true` when it is already set to `true` should do nothing or at least not interrupt `getCurrentPosition`

## Actual Behavior
It seems that setting `changePace` to `true` when it is already set to `true` interrupts `getCurrentPosition`, resulting in a 499 error.

## Steps to Reproduce
It's a little hard to reproduce for me but I can reliably reproduce after waiting a few minutes with something like this.

```javascript
const onHeartbeat = async (event: HeartbeatEvent) => {
    const taskId = await BackgroundGeolocation.startBackgroundTask();
    await BackgroundGeolocation.changePace(true);
    await BackgroundGeolocation.stopBackgroundTask(taskId);
};

const backgroundTimerTick = () => {
	await BackgroundGeolocation.getCurrentPosition({
          timeout: 10,
          samples: 10,
          persist: true,
    });
}

BackgroundGeolocation.onHeartbeat(onHeartbeat);

BackgroundTimer.runBackgroundTimer(backgroundTimerTick, 30 * 1000);
```

## Context
We manually send locations to our server at a specified interval (default, 30s). For this, we get the current location in a timer. Since this timer runs every 30 seconds, it sometimes overlaps with the heartbeat which forces aggressive tracking via `changePace(true)`

## Debug logs
Logs were collected via `BackgroundGeolocation.logger.emailLog()`. Since I couldn't run into it until a few minutes passed, I created a gist (it's set to verbose so it's quite huge). If you'd rather want me to paste it here, let me know!
[Log](https://gist.github.com/curtisy1/e16c3e64e26ddd1422e1740b401adc6e)

**Comment by christocracy** [comment]
Why would you call `.changePace(true)` in `onHeartbeat`?

**Comment by christocracy** [comment]
you know that `onHeartbeat` fires only if the plugin is in the stationary state, right?

I would do that in `onMotionChange` instead.

```dart
BackgroundGeolocation.onMotionChange((isMoving) {
  if (!isMoving) {
    BackgroundGeolocation.changePace(true);
  }
});
```

Also, surrounding that code in a `.startBackgroundTask` is pointless.
```dart
const taskId = await BackgroundGeolocation.startBackgroundTask();
    await BackgroundGeolocation.changePace(true);
    await BackgroundGeolocation.stopBackgroundTask(taskId);
```

**Comment by curtisy1** [comment]
Thank you for the swift reply! That's a lot of useful and valuable tips, I'll take a more detailed look tomorrow when at work but here's a quick rundown of our use-case if you're interested

> Why would you call .changePace(true) in onHeartbeat?

You answered this yourself in your next reply :grin:. Our use case is keeping location tracking running in the background forever i.e. until manually stopped after an 8 hour work day. I don't know the full details of why it was done that way but it's probably legacy cruft.

>  just set a very high stopTimeout and call .changePace(true) when your app launches.

This sounds exactly like what we need. Thank you for that!

> Also, surrounding that code in a .startBackgroundTask is pointless.

Oh? I actually got that idea from the [changelog](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#4131--2023-08-24). I'm guessing that's only for long-running tasks like `getCurrentPosition` then?

Thanks again for taking the time to provide such useful insights and ideas, it's greatly appreciated!

**Comment by curtisy1** [comment]
The suggestions you provided seem to do the trick and I can no longer reproduce the issue.
Closing this as it's solved. Thanks again for your help!
