### ISSUE TITLE
Does IOS need to purchase the lisense? 

### ISSUE THREAD

**Issue by 111Tashmo** [transistorsoft/react-native-background-geolocation#2017]
I just want to comfirm that should I buy the lisense to get the key so that I can the document mean that only android need to purchase, but It seems both of them need key to use.

**Comment by christocracy** [comment]
Are you making an iOS-only app?

**Comment by 111Tashmo** [comment]
yes
oh sorry my mistake , the key only need to write in android file, didn't notice hhhhh
