### ISSUE TITLE
Feature request: minimum threshold for stopTimeout to get interrupted

### ISSUE THREAD

**Issue by sirusbaladi** [transistorsoft/react-native-background-geolocation#2018]
Hi, sometimes the user is within the same location but does some movements.

Examples
- user is at a bar and keeps moving within 15 / 20 meters within the bar.
- user is at a shoe store and keeps walking to try new shoes within a very small radius
- user is at the gym 
 
In cases like the above the stopTimeout keeps getting interrupted and the app never reaches stationary state while it should causing all sorts of problem such as battery drainage and user annoyance for having the indicator icon on. 

Any way to set a minimum threshold of movement for timer to interrupted? if no, could we have this in a future version?

Thanks.

**Comment by sirusbaladi** [comment]
Any update on this?

**Comment by sirusbaladi** [comment]
Hi, kindly any update on this?

It appears to be less of an edge than it seems and quite frequent actually.

**Comment by christocracy** [comment]
I have no update.

**Comment by sirusbaladi** [comment]
> I have no update.

what I meant by "update" is if it's planned to be worked on, if there's any time estimate. It's a very needed feature.

**Comment by sirusbaladi** [comment]
how to reopen?
