### ISSUE TITLE
Extras not returned with `getGeofences`

### ISSUE THREAD

**Issue by jcity** [transistorsoft/react-native-background-geolocation#202]
The data I supply in the `extras` field when adding a geofences is not returned with the geofence when I call `getGeofences`

Also `notifyOnExit`, `notifyOnEntry`,  `notifyOnDwell`, `loiteringDelay` are not returned. 

## Your Environment
* Plugin version: 2.4.1
* Platform: iOS
* OS version: 10.2
* Device manufacturer / model: Apple 
* React Native version (`react-native -v`): 0.39.2
* Plugin config:
```js
        "enabled": true,
        "trackingMode": "location",
        "foregroundService": false,
        "maxBatchSize": 20,
        "configureInterval": 0,
        "license": "<SECRET>",
        "batchSync": true,
        "autoSyncThreshold": 0,
        "maxDaysToPersist": 1,
        "forceReloadOnHeartbeat": false,
        "activityRecognitionInterval": "10000",
        "forceReloadOnGeofence": false,
        "forceReloadOnMotionChange": false,
        "deferTime": "0",
        "stopAfterElapsedMinutes": 0,
        "fastestLocationUpdateInterval": "60000",
        "geofenceProximityRadius": "1000",
        "disableElasticity": false,
        "autoSync": false,
        "geofenceInitialTriggerEntry": true,
        "startOnBoot": true,
        "method": "POST",
        "desiredAccuracy": 0,
        "notificationText": "Location Service activated",
        "minimumActivityRecognitionConfidence": 75,
        "maxRecordsToPersist": -1,
        "distanceFilter": 0,
        "isMoving": false,
        "persist": true,
        "locationUpdateInterval": "60000",
        "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
        "logMaxDays": 3,
        "disableStopDetection": false,
        "stationaryRadius": 25,
        "forceReloadOnBoot": false,
        "locationTimeout": 60,
        "stopTimeout": "5",
        "schedulerEnabled": false,
        "logLevel": 5,
        "debug": false,
        "stopOnTerminate": false,
        "heartbeatInterval": 60,
        "forceReloadOnLocationChange": false
```

## Expected Behavior
The data supplied to `extras` and other fields mentioned above is returned.

## Actual Behavior
I only receive `identifier`, `latitude`, `location`, and `radius`

## Steps to Reproduce
1. Register a geofence with some extra data
2. Retrieve geofences with `getGeofences`
3. Observe missing data

**Comment by christocracy** [comment]
I'm trying to verify this now.

**Comment by christocracy** [comment]
I don't see a problem here.

```Javascript
BackgroundGeolocation.getGeofences(function(rs) {
  console.log(rs);
});
.
.
.
[{ radius: 200,
    extras: { geofence_extras: '------- extras ------' },
    longitude: -122.03119982454734,
    identifier: 'EXTRAS1',
    latitude: 37.332182120330984,
    notifyOnExit: 0,
    notifyOnEntry: 1 }]
```

**Comment by christocracy** [comment]
You're using a very old version, basically [1.2.2](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#122---2016-08-01)

The docs you see on **master** reference the latest version.  Geofence `extras` were added quite recently.

You need to upgrade.

**Comment by christocracy** [comment]
Also, the Geofencing system has been significantly refactored since the version you're using.

You'll want to have a look at [this](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/geofencing.md)

**Comment by christocracy** [comment]
Here's [an animation](http://www.transistorsoft.com/shop/products/assets/images/background-geolocation-infinite-geofencing.gif) of how the new "Infinite Geofencing" system operates.

**Comment by jcity** [comment]
Thanks for the quick reply @christocracy I'll try upgrading

Also, how can I get access to the android repo (my company has a license)

**Comment by christocracy** [comment]
Ask your Product Manager to add you as a member in the Dashboard.

The "android repo" now contains both Android & iOS.  This public repo now contains only the latest stable release.

You'll want to view the README once you're granted access and re-install both platforms from the private repo.

**Comment by jcity** [comment]
Thanks!
