### ISSUE TITLE
Feature request: onGeofence event to return default long and lat 

### ISSUE THREAD

**Issue by sirusbaladi** [transistorsoft/react-native-background-geolocation#2022]
Hi, 

The onGeofence event right now returns within the location field the longitude and latitude of where the user is within the geofence. 
It would be nice if it also returned the longitude and latitude of the geofence center itself.   

Having this would make the object more complete and would help in making the code cleaner. I have some use-cases where I exactly need this. 

Thanks.

**Comment by christocracy** [comment]
See api docs .getgeofence(identifier) to fetch the desired geofence info.

**Comment by sirusbaladi** [comment]
> See api docs .getGeofence(identifier) to fetch the desired geofence info.

it makes a lot of sense to add it in the object returned by onGeofence. For now, I'm adding it in the extra field of the object.

**Comment by christocracy** [comment]
It is not inefficient to simply use .getGeofence.

I don’t plan on providing the geofence to the event.

**Comment by christocracy** [comment]
You’re always free to add *any* arbitrary meta data to the geofence event via `Geofence.extras`, including the geofence lat/lng.  It’s what I do in the demo app.

**Comment by sirusbaladi** [comment]
> You’re always free to add _any_ arbitrary meta data to the geofence event via `Geofence.extras`, including the geofence lat/lng. It’s what I do in the demo app.

> For now, I'm adding it in the extra field of the object.

Yes that's what I've ended up doing. I think it cleaner that calling getGeofence again. Still think that should come within the geofence field in event  but it works. - > event : {...,  geofence {object}}

**Comment by christocracy** [comment]
> Still think that should come within the geofence field

It doesn’t matter.  There are multiple ways to get the desired information required by a minority of users.

**Comment by sirusbaladi** [comment]
still important

**Comment by sirusbaladi** [comment]
should be reopened
