### ISSUE TITLE
Not getting notification in Android while application in background

### ISSUE THREAD

**Issue by aakashy85** [transistorsoft/react-native-background-geolocation#2025]
## Your Environment
Plugin version: 4.16.0
Platform: Android
OS version: Emulator, v10(Q) API 29. Galaxy 20, OS v10
Device manufacturer / model: Samsung Galaxy 20+
React Native version (react-native -v): 0.73.1
Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const config = {
  debug: false,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
  disableMotionActivityUpdates: false,
  distanceFilter: 10,
  enableHeadless: true,
  foregroundService: true,
  geofenceInitialTriggerEntry: false,
  geofenceModeHighAccuracy: true,
  geofenceProximityRadius: 304.8,
  locationUpdateInterval: 1000,
  locationAuthorizationRequest: 'Always',
  stopDetectionDelay: 0,
  activityType:1,
  logLevel: 5,
  stopOnTerminate: false,
  didRequestUpgradeLocationAuthorization: true,
  stopTimeout: 5,
  startOnBoot: true, 
  useSignificantChangesOnly: false,
  heartbeatInterval:60,
  backgroundPermissionRationale: {
    title: "Allow to access to this device's location in the background?",
    message:
    'Required location',
    positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
    negativeAction: 'Cancel',
    },
    notification: {
      title: "The Notification Title", 
      text: "The Notification Text"
  },
    notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,

};
```

## Expected Behavior
Notification should come in background and foreground

## Actual Behavior
Notification coming only in foreground. I am also check local notification its not work in background.

**Comment by christocracy** [comment]
Test on a real device with real movement.  Go outside for a walk of ~1km with `debug: true` and listen to the plugin debug Sound FX.

**Comment by aakashy85** [comment]
Thanks for quick response, 
I am working in saucelabs, We got headlessTask console successfully.
`
const BackgroundFetchHeadlessTask = async event => {
  console.log('[BackgroundFetch HeadlessTask] start', event.taskId);

  if (event.taskId == 'react-native-background-fetch') {
  }

  console.log('[BackgroundFetch HeadlessTask] finished');

  BackgroundFetch.finish(event.taskId);
};
`

**Comment by aakashy85** [comment]
Also wanted to know, we don't need to add custom notification with this library, Right?

**Comment by christocracy** [comment]
Where do you get the impression a custom notification should be required?

**Comment by aakashy85** [comment]
We not seen notification from this library till now, So that's why i asking to you.
Any other things I need to add for get notification from this library.
Please guide me if i missed anythings.

**Comment by christocracy** [comment]
The notification is required by Android foreground services.  The plug-in’s foreground service is launched when the plug-in toggles to its “moving” state.  Go outside and walk about 200 meters and the plug-in will toggle to the moving state.

or manually change state via method .changePace(true).

or call .getCurrentPosition.

when the foreground service is complete, it terminates, along with the notification.

read the wiki “Philosophy of Operation”.

**Comment by aakashy85** [comment]
What steps are necessary to receive notifications when the app is running in the background or has been terminated?

**Comment by christocracy** [comment]
> receive notifications 

From what?

**Comment by aakashy85** [comment]
I need to display notifications when the user enters the geofence radius.
What is the necessary steps for do this.

**Comment by christocracy** [comment]
See the api docs for the notification plug-in you’re using.  The plug-in is not involved in showing notifications.

**Comment by aakashy85** [comment]
Thanks,
I was supposed this plug-in can display notifications both in the background and foreground.

**Comment by christocracy** [comment]
No.  The plug-in is not involved with showing local-notifications.

**Comment by aakashy85** [comment]
Then what is the use of this config
```
notification: {
      title: "The Notification Title", 
      text: "The Notification Text"
  },
```

**Comment by christocracy** [comment]
That’s for the required persistent notification of Android foreground-services.  Android foreground services require a notification to be present when a foreground service is active.
