### ISSUE TITLE
watchposition is not a supported event type

### ISSUE THREAD

**Issue by t-harps** [transistorsoft/react-native-background-geolocation#203]
## Your Environment
* Plugin version: 2.4.3
* Platform: iOS
* OS version: 8.0
* Device manufacturer / model: iPhone 6 (sim)
* React Native version (`react-native -v`): 0.36.1
* Plugin config: 
```
    distanceFilter: 0,
    stopOnTerminate: false,
    startOnBoot: false,
    maxDaysToPersist: 100,
    pausesLocationUpdatesAutomatically: false,
    disableElasticity: true,
```

## Expected Behavior
Expect the module to trigger my callback every x seconds using the backgroundGeolocation watchPosition method with a locationUpdateInterval of x seconds.

## Actual Behavior
Get the following error every few seconds
```
[tid:com.facebook.react.RNBackgroundGeolocationQueue][RCTEventEmitter.m:79] `watchposition` is not a supported event type for RNBackgroundGeolocation. Supported events are: `location`, `providerchange`, `motionchange`, `activitychange`, `geofenceschange`, `error`, `http`, `schedule`, `geofence`, `sync`, `heartbeat`
```
## Steps to Reproduce
```
BackgroundGeolocation.configure({
    distanceFilter: 0,
    stopOnTerminate: false,
    startOnBoot: false,
    maxDaysToPersist: 100,
    pausesLocationUpdatesAutomatically: false,
    disableElasticity: true,
  }, (state) => {
    console.log('- Configure success.  Current state: ', state);
  });
BackgroundGeolocation.watchPosition((location) => {
      callback(location, true); // callback that posts location to my database
    }, (error) => {
      console.log('- Watch position error: ', error);
    }, {
      locationUpdateInterval: 10000,
    });
BackgroundGeolocation.start(()=> console.log("- Time start check-in success"));
```

## Context
Trying to POST location every 10 seconds to my server using watchPosition method.

## Debug logs
🔵-[Settings init] Settings loaded
ℹ️__21-[LocationDAO unlock]_block_invoke UNLOCKED ALL RECORDS
ℹ️-[GeofenceDAO init] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, extras TEXT)
ℹ️-[GeofenceDAO init] CREATE index IF NOT EXISTS identifier ON geofences (identifier);CREATE index IF NOT EXISTS latitude ON geofences (latitude);CREATE index IF NOT EXISTS longitude ON geofences (longitude);CREATE index IF NOT EXISTS sin_latitude ON geofences (sin_latitude);CREATE index IF NOT EXISTS cos_latitude ON geofences (cos_latitude);CREATE index IF NOT EXISTS sin_longitude ON geofences (sin_longitude);CREATE index IF NOT EXISTS cos_longitude ON geofences (cos_longitude);
ℹ️-[TSGeofenceManager addGeofencesChangeListener:] 
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[TSLocationManager locationManager:didChangeAuthorizationStatus:] status 3
2017-02-13 09:49:43.715 [warn][tid:main][RCTEventEmitter.m:54] Sending `providerchange` with no listeners registered.
🔵-[BackgroundTaskManager locationManager:didChangeAuthorizationStatus:] 3
🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 3
2017-02-13 09:49:43.899126 CopoApp[80584:2726264] [] __nw_connection_get_connected_socket_block_invoke 7 Connection has no connected handler
2017-02-13 09:49:43.929 [warn][tid:main][RCTEventEmitter.m:54] Sending `websocketFailed` with no listeners registered.
2017-02-13 09:49:44.165 [info][tid:main][RCTRootView.m:239] Running application CopoApp ({
    initialProps =     {
    };
    rootTag = 1;
})
2017-02-13 09:49:44.168 [info][tid:com.facebook.react.JavaScript] Running application "CopoApp" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
🎾-[LocationManager watchPosition:] START
✅ [BackgroundTaskManager createBackgroundTask]: 4
⚠️-[Settings load:] WARNING: The plugin's accelerometer-based stop-detection system is not permitted in conjunction with #pausesLocationUpdatesAutomatically.  The plugin's accelerometer-based stop-detection system has been automatically DISABLED.  You should typically not need to specify #pausesLocationUpdatesAutomatically unless you mean to completely disable automatically turning off location-services when the device is detected to be stopped.  If you do specify pausesLocationUpdatesAutomatically: true, location-services will automatically turn off after exactly 15min stationary, #stopTimeout will be ignored, and the plugin's accelerometer-based stop-detection system will be disabled.

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager setConfig:] 
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = 0;
    disableElasticity = 1;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 1;
    distanceFilter = 0;
    enabled = 0;
    extras = 0;
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    headers = 0;
    heartbeatInterval = 60;
    isMoving = 0;
    locationAuthorizationRequest = Always;
    locationTimeout = 60;
    logLevel = 18446744073709551615;
    maxBatchSize = "-1";
    maxDaysToPersist = 100;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    params = 0;
    pausesLocationUpdatesAutomatically = 0;
    preventSuspend = 0;
    schedule = 0;
    schedulerEnabled = 0;
    startOnBoot = 0;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnTerminate = 0;
    stopTimeout = 300;
    trackingMode = location;
    url = 0;
    useSignificantChangesOnly = 0;
}
╚═══════════════════════════════════════════════════════════
ℹ️-[LocationDAO purge:] maxDaysToPersist: 100
2017-02-13 09:49:57.249 [warn][tid:main][RCTEventEmitter.m:54] Sending `providerchange` with no listeners registered.
ℹ️+[LocationAuthorization run:] status: 3
🎾-[LocationManager onWatchPositionTimer:] ONESHOT

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager start] 
╚═══════════════════════════════════════════════════════════
2017-02-13 09:49:57.258 [info][tid:com.facebook.react.JavaScript] '- Configure success.  Current state: ', { autoSyncThreshold: 0,
  distanceFilter: 0,
  maxDaysToPersist: 100,
  pausesLocationUpdatesAutomatically: false,
  debug: false,
  startOnBoot: false,
  headers: false,
  maxRecordsToPersist: -1,
  disableStopDetection: true,
  maxBatchSize: -1,
  extras: false,
  url: false,
  disableElasticity: true,
  stopTimeout: 300,
  locationAuthorizationRequest: 'Always',
  params: false,
  schedule: false,
  activityRecognitionInterval: 10000,
  preventSuspend: false,
  useSignificantChangesOnly: false,
  geofenceProximityRadius: 1000,
  locationTimeout: 60,
  activityType: 1,
  stationaryRadius: 25,
  method: 'POST',
  disableMotionActivityUpdates: false,
  batchSync: false,
  stopAfterElapsedMinutes: -1,
  stopOnTerminate: false,
  desiredAccuracy: 0,
  isMoving: false,
  stopDetectionDelay: 0,
  heartbeatInterval: 60,
  geofenceInitialTriggerEntry: true,
  enabled: false,
  minimumActivityRecognitionConfidence: 70,
  logLevel: 18446744073709552000,
  trackingMode: 'location',
  schedulerEnabled: false,
  autoSync: true }
🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
2017-02-13 09:49:57.271 CopoApp[80584:2726164] - TSBackgroundFetch addListener: TSLocationManager
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
2017-02-13 09:49:57.272 CopoApp[80584:2726164] - TSBackgroundFetch started
🔴-[LocationManager stopUpdatingLocation] OFF

<+37.70569093,-122.47085796> +/- 5.00m (speed 32.33 mps / course 16.88) @ 2/13/17, 9:49:57 AM Greenwich Mean Time

╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 1
╚═══════════════════════════════════════════════════════════
2017-02-13 09:49:57.278 [error][tid:main][RCTEventEmitter.m:46] `watchposition` is not a supported event type for RNBackgroundGeolocation. Supported events are: `location`, `providerchange`, `motionchange`, `activitychange`, `geofenceschange`, `error`, `http`, `schedule`, `geofence`, `sync`, `heartbeat`
```

**Comment by christocracy** [comment]
I'll check it out.

 Are you aware of what  `pausesLocationUpdatesAutomatically: false` means?  This is a very unusual mode, not required in 99% of cases.

**Comment by t-harps** [comment]
Thanks, my understanding was that it means location-tracking is never turned off. We allow the user to start/stop location tracking themselves and set a time based interval. So even if they are not moving and have set an interval of 10 seconds, their location will still be posted every 10 seconds indefinitely. 

Figured I needed that setting set to false in order to allow this.

**Comment by christocracy** [comment]
That's correct.  As long as you're carefully managing that / user is
responsible.

And btw, avoid executing api methods (aside from adding event listeners),
until callback to #configure fires.

Eg, move #start, #watchPosition to within that callback.


-- 
Snet form Gmail Mobile

**Comment by t-harps** [comment]
Understood, will change that now.

**Comment by christocracy** [comment]
In your XCode project, edit `RNBackgroundGeolocation.m` and add`EVENT_WATCHPOSITION` to [this Array](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/ios/RNBackgroundGeolocation/RNBackgroundGeolocation.m#L79).

**Comment by t-harps** [comment]
That fixed the previous error and my callback is successfully called, I now get the following error. Might be something I need to fix on my side? Wasn't getting this error when I was using version 1.5.4 of your plugin however so not sure.

```
2017-02-13 11:01:14.615 [error][tid:com.facebook.react.JavaScript] The callback watchPosition() exists in module RNBackgroundGeolocation, but only one callback may be registered to a function in a native module.
2017-02-13 11:01:14.618 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: The callback watchPosition() exists in module RNBackgroundGeolocation, but only one callback may be registered to a function in a native module.
```

**Comment by christocracy** [comment]
Yes, I see the issue here.  I changed the native callback mechanism to `#watchPosition` while working on the Cordova side.  Cordova allows callbacks to be called multiple times.  I was aware of this with React but didn't properly integrate this change.  I'm fixing this now.

**Comment by christocracy** [comment]
I broke it [here](https://github.com/transistorsoft/react-native-background-geolocation/commit/8a83b470b4691cd6bc52e0206f408568833b789d#diff-7d63b7d073c06bd75ac4c00c34ca71d8L209).

**Comment by christocracy** [comment]
Try installing from the branch [ios-watchPosition](https://github.com/transistorsoft/react-native-background-geolocation/tree/ios-watchPosition)

Also, there was a bug [in the docs](https://github.com/transistorsoft/react-native-background-geolocation/blob/ios-watchPosition/docs/README.md#watchpositionsuccessfn-failurefn-options)

It's `interval` -- not `locationUpdateInterval`.

```
@param {Integer millis} interval [1000] Location update interval
@param {Integer} desiredAccuracy [0]
@param {Boolean} persist [true] Whether to persist location to database
@param {Object} extras [undefined] Optional extras to append to each location
```

**Comment by t-harps** [comment]
Installing from ios-watchPosition branch fixes all my issues. Have changed back to using interval. Thanks for your help.
