### ISSUE TITLE
Unable to get the user location at regular intervals when app in background using onHeartbeat 

### ISSUE THREAD

**Issue by kopposh** [transistorsoft/react-native-background-geolocation#2032]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^4.14.6",
* Platform: iOS and Android
* OS version: Android >=9, iOS >= 15
* Device manufacturer / model: Tested on iPhone 15 pro, Mi A1
* React Native version (`react-native -v`): Expo 50.0.18
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
defaultReadyOptions: Config = {
  // Debug
  heartbeatInterval: 60 * 14,
  stopTimeout: 60,
  preventSuspend: true,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  distanceFilter: 0,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  stopOnTerminate: false,
  startOnBoot: true,
  stopOnStationary: false,
  disableAutoSyncOnCellular: false,
  useSignificantChangesOnly: false,
}

const subscription = BackgroundGeolocation.onHeartbeat((event) => {
        BackgroundGeolocation.getCurrentPosition({
          samples: 1,
          persist: true,
        }).then((location) => {
            insertLocation({
              latitude: `${location?.coords?.latitude}`,
              longitude: `${location?.coords?.longitude}`,
           });
        });
      });

defaultLocationConfig: CurrentPositionRequest = {
  timeout: 30, 
  maximumAge: 1000, 
  desiredAccuracy: 1, 
  samples: 1,
  persist: false,
};


async (event: GeofenceEvent) => {
  let source = "";
  if (
    event.action === EGeolocationEvent.ENTER ||
    event.action === EGeolocationEvent.EXIT
  ) {
    source = event.action;
  }
  if (source) {
 
    const location = await BackgroundGeolocation.getCurrentPosition({
      ...defaultLocationConfig,
      extras: {
        ...event.extras,
        source,
      },
    });
  
      await insertLocation({
        latitude: `${location?.coords?.latitude}`,
        longitude: `${location?.coords?.longitude}`,
       
      });
  
    }
  }
};


```

## Expected Behavior

Need to capture user location at 14 mins interval for longer durations like 8-9 hours. On both android and iOS. And save to app local storage. There is high possibility for the device to be stationary (left on desk) for longer durations. that means, the app should get data in background mostly and I am also using geoFence in addition to it. Any additional suggestions to achieve the above helps
## Actual Behavior

App provides location values ones or twice while in background not more than that. later i think the app is terminated and geoFence isn't giving consistent enter/exit. At times I see records and at times I don't, with the same app on multiple tests.

**Comment by christocracy** [comment]
Periodic event-handling is precisely what the background-fetch plugin is for.  See its readme.

heartbeat should be avoided.

**Comment by kopposh** [comment]
We have tried background-fetch initially but it didn't give any output in testing phase. 

and also in the readme it says:
"iOS can take days before Apple's machine-learning algorithm settles in and begins regularly firing events. Do not sit staring at your logs waiting for an event to fire. If your [simulated events](https://www.npmjs.com/package/react-native-background-fetch#debugging) work, that's all you need to know that everything is correctly configured.
If the user doesn't open your iOS app for long periods of time, iOS will stop firing events."

Hence we were doubtful about getting locations regularly. I will retry and share the implementation today.

**Comment by christocracy** [comment]
Read the readme for background-fetch and learn how to *simulate* events.  When simulated events fire, that’s all you need to know, that everything is operating correctly.

It works fine; no need to “doubt”.

**Comment by kopposh** [comment]
I have gone through the readme. I don't see anything mentioned for android similar to simulate events in iOS. Do we have something to test on android as well?

**Comment by christocracy** [comment]
https://github.com/transistorsoft/react-native-background-fetch?tab=readme-ov-file#android-1

![IMG_1135](https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/cf3c170f-55df-4713-bf67-1b332b1a8741)

**Comment by kopposh** [comment]
I am initializing background fetch on start of application. followed the steps provided in readme file and tired to simulate events. but couldn't see any events fired. 

const status = await BackgroundFetch.configure(
      {
        minimumFetchInterval: 20,
        enableHeadless: true,
      },
      async (taskId) => {
        try {
            insertLocation({
              latitude: `${location?.coords?.latitude}`,
              longitude: `${location?.coords?.longitude}`,
            });
          }
        } catch (err) {
         console.log(
            "BackgroundGeolocation.initBackgroundFetch error", err
          );
        }
        BackgroundFetch.finish(taskId);
      },
      async (taskId) => {
        BackgroundFetch.finish(taskId);
      }
    );

<img width="1022" alt="Screenshot 2024-05-23 at 4 27 44 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/166544723/beda3bdf-6033-4410-b9b0-be76321bdb93">

few questions:
1. So, should "com.transistorsoft.fetch" be same or the identifier of app? I tried with the same identifier
2. does the simulated events fire immediately or at the interval mentioned with minimumFetchInterval
3. can we try on iPhone simulator or do we need to test on real devices only?

**Comment by christocracy** [comment]
1. Yes
2. Immediately
3. Simulated iOS events don’t work in simulator, as warned in the readme.  Use a real device.

**Comment by kopposh** [comment]
I have registered a headless task in my index.js to run when app is terminated on android along with BackgroundFetch.configure(code shown below) and receiving the below warning message.

 **WARN  No task registered for key BackgroundFetch**

useEffect(()=>{
    BackgroundFetch.registerHeadlessTask(BGHeadlessTask);
},[])

const BGHeadlessTask = async (event: { taskId: any; timeout: any }) => {
    let taskId = event.taskId;
    let isTimeout = event.timeout;
    if (isTimeout) {
      BackgroundFetch.finish(taskId);
      return;
    }
    try {
      const location = await BackgroundGeolocation.getCurrentPosition({
         timeout: 30,
  maximumAge: 1000,
  desiredAccuracy: 1,
  samples: 1,
  persist: false,
      });
      if (location && location?.coords) {
        await insertLocation({
          latitude: `${location?.coords?.latitude}`,
          longitude: `${location?.coords?.longitude}`,
          source: LOCATION_BG_TRACKING,
        });
      }
      BackgroundFetch.finish(taskId);
    } catch (err) {
      BackgroundFetch.finish(taskId);
    }
  }

const status = await BackgroundFetch.configure(
{
minimumFetchInterval: 20,
 enableHeadless: true,
 stopOnTerminate: false,
},
async (taskId) => {
try {
   const location = await BackgroundGeolocation.getCurrentPosition({
         timeout: 30,
  maximumAge: 1000,
  desiredAccuracy: 1,
  samples: 1,
  persist: false,
      });
insertLocation({
latitude: ${location?.coords?.latitude},
longitude: ${location?.coords?.longitude},
});
}
} catch (err) {
console.log(
"BackgroundGeolocation.initBackgroundFetch error", err
);
}
BackgroundFetch.finish(taskId);
},
async (taskId) => {
BackgroundFetch.finish(taskId);
}
);

screenshot when app is terminated for a while and opened again after receiving the warning:
<img width="1340" alt="Screenshot 2024-05-28 at 1 27 52 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/166544723/7aaec53b-1cfc-429a-8b1e-7b9555dd5f66">

**Comment by christocracy** [comment]
If you have a question about background-fetch, please seek support by posting an issue there.

Also, please learn to syntax highly [“fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)
