### ISSUE TITLE
 [onLocation] {"error": 1}

### ISSUE THREAD

**Issue by 111Tashmo** [transistorsoft/react-native-background-geolocation#2034]
xcode log: 
⚠️-[TSLocationManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=1 "(null)"

I have followed the steps to add privacies in xcode, and in the setting of my-app here are all the permissions. why my-app just can't get the location?
![IMG_9973](https://github.com/transistorsoft/react-native-background-geolocation/assets/112067237/afa89f80-60b8-4a5d-828e-04c3f1c5ab4c)

**Comment by christocracy** [comment]
Choose WhenInUse

**Comment by 111Tashmo** [comment]
just forgot to mention that's all I have in location...
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/112067237/dc274b8f-be13-4df0-bc87-4e148ed7e268)
and in xcode:
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/112067237/ec05876d-af1c-481c-9246-7d3c7c9226f8)

**Comment by christocracy** [comment]
Go back to the Setup Instructions and carefully follow them.  You did not add the required .plist strings.

**Comment by 111Tashmo** [comment]
<img width="972" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/112067237/d8d93d41-96f3-45c7-8e68-f1adadbd95aa">
try again but still...copy paste so definately nothing wrong.
should I add all 6 of them?
<img width="1088" alt="截屏2024-05-27 23 52 45" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/112067237/a80dd491-a1e5-4e19-b461-2bacf2f86dd4">

**Comment by christocracy** [comment]
There are not 6, there are 3.

**Comment by 111Tashmo** [comment]
ok so I think I did right this part at least. I surely added 3...

**Comment by christocracy** [comment]
The permissions your app has available to it is determined by the Strings available to it in your Info.plist.

if those permissions are not seen in your app settings, then you added incorrect strings to your .plist.

**Comment by 111Tashmo** [comment]
so you mean still the typing issue...
by the way ... I have anothor plugin need location so additionally, I have this...does it affect?
<img width="880" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/112067237/baaefca6-1091-4c4c-977e-ee962e569b47">

**Comment by 111Tashmo** [comment]
would it work If I remove the 4th one?

**Comment by christocracy** [comment]
Location Always Usage Description [has been obsolete for *years*](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysusagedescription), since iOS 10.

**Comment by christocracy** [comment]
Why don’t you try it and see?

**Comment by 111Tashmo** [comment]
Omg You were right lol, hhhhhhh, I really make a stypid mistake in typing, actually the third one should be 'When In Use', whild I typed 'When in Use', just a one letter[try out]. I am really new on xcode. Thanks for your help sir, your are really a patient developer and contributor, and also you reply super fast... I really appreciate. Have a nice day man!
