### ISSUE TITLE
cannot open Product Dashboard 

### ISSUE THREAD

**Issue by jajamoa** [transistorsoft/react-native-background-geolocation#2042]
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/5111614/afa19469-4dcf-4766-af57-93c672bed4be)
 this showed up when accessing https://www.transistorsoft.com/shop/customers as application owner

**Comment by christocracy** [comment]
Dashboard support is not handled publicly at the GitHub repo.

send an email.
