### ISSUE TITLE
Question about License

### ISSUE THREAD

**Issue by souzadeveloper** [transistorsoft/react-native-background-geolocation#2048]
From what I understand, to use the library with IOS it is not necessary to purchase a license, but in the case of Android yes... can I generate an APK for Android using the expo Build to validate the library before purchasing the license? Will I have any limitations in this case?

**Comment by christocracy** [comment]
The plugin is fully functional in DEBUG builds so you can try before you buy.

**Comment by souzadeveloper** [comment]
Good afternoon Chris, firstly thanks for the quick response, I need to be sure that it will work in my project before purchasing the plugin, so sorry for insisting on some questions:

1 - Debug would be when I set debug equal to true in the plugin or when I am in debug mode running through Expo (npx expo start)?

2 - Is the plugin compatible with Expo SDK 48 or higher?

3 - Can I use "Managed Workflow" or do I have to use "Bare Workflow"?

Thanks!

**Comment by christocracy** [comment]
>1 - Debug would be when I set debug equal to true in the plugin or when I am in debug mode running through Expo (npx expo start)?

This has nothing to do with the plugin config `Config.debug`.  This is purely an Android Application gradle build thing.  There are two main types of Android APK build:  `debug` and `release`.

>2 - Is the plugin compatible with Expo SDK 48 or higher?

Yes.

>3 - Can I use "Managed Workflow" or do I have to use "Bare Workflow"?

Managed.

**Comment by souzadeveloper** [comment]
Thanks Chris!
