### ISSUE TITLE
  "_OBJC_CLASS_$_TSBackgroundFetch", referenced from:    "_OBJC_CLASS_$_TSLocationManager", referenced from:

### ISSUE THREAD

**Issue by JUnderwood1991** [transistorsoft/react-native-background-geolocation#205]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior

I'm expecting it to compile...
## Actual Behavior

Its throwing a linker error
## Steps to Reproduce

1. Follow the install steps and try to build...
2.
3.
4.

## Debug logs

  "_OBJC_CLASS_$_TSBackgroundFetch", referenced from:

  "_OBJC_CLASS_$_TSLocationManager", referenced from:

**Comment by JUnderwood1991** [comment]
Nevermind. I put the Frameworks into copy bundle resources instead of link libraries -__-

**Comment by christocracy** [comment]
Yup, I was just going to say that.
