### ISSUE TITLE
how to fetch location with specific interval

### ISSUE THREAD

**Issue by keerthanaMol** [transistorsoft/react-native-background-geolocation#2051]
i have pizza delivery application when order taken i need  to start process each 5 minute interval i need get location is it possible with this library ?

my react native version 0.72.5
react-native-background-geolocation 4.16.2
react-native-background-fetch 4.2.5

what are parameters i need give inside BackgroundGeolocation.ready

**Comment by christocracy** [comment]
iOS is strictly distance-based.  For Android, see Config.locationUpdateInterval.

you don’t save any battery with an update interval of 10s vs 5min.

**Comment by keerthanaMol** [comment]
@christocracy thanks for your quick response

**Comment by christocracy** [comment]
I suggest you just use distanceFilter with a reasonable value, such as 100 or 200 meters.

You don’t need time-based updates.

read the api docs Config.distanceFilter

**Comment by keerthanaMol** [comment]
@christocracy actual my requirement is for office purpose not for pizza delivery. some employee requested for work from home option we recored there location then hr will understand employe is working properly any support from you

**Comment by christocracy** [comment]
Read the wiki “Philosophy of Operation”.

when the device moves about 200 meters from the last known location, the plug-in will begin tracking and you will know.  Otherwise, the device is at the last known location.  I suggest you see the api docs Config.useSignificantChangesOnly, as well.

also research sending server push requests to a device.  In your push request callback, you are free to interact with the plug-in to call .getCurrentPosition.

you could also implement background-fetch (already included as a dependency; see its readme) to call .getCurrentPosition.

**Comment by FazilMuhammed** [comment]
there is important issue

some time our employe will disable gps or location then I think fetching location is will stop then company will understand employee is working from their given location or sometime they migrating from some location.thats why I am asking is possible get location with 15 min interval 

please help @christocracy I am in trouble

**Comment by christocracy** [comment]
The user has full control to hide from you if they wish.

listen to event .onProviderChange to learn when device location is disabled.

use background-fetch (already included as a dependency; read its readme) to implement a periodic callback which you can use to execute .getCurrentPosition),

**Comment by FazilMuhammed** [comment]
thank you for your replay

**Comment by haiderTkxel** [comment]
@christocracy If device is not moving then send the location to configured url after specific interval of time.
Is this possible?

I tried with locationUpdateInterval for android but it's not send location after specific interval of time when device is not moving.

**Comment by christocracy** [comment]
The plug-in does not record location while in the stationary state.

use background-fetch, already included as a dependency, to execute periodic callbacks.  See its readme.  Call .getCurrentPosition in your fetch callback.
