### ISSUE TITLE
Tests Android Emulator

### ISSUE THREAD

**Issue by souzadeveloper** [transistorsoft/react-native-background-geolocation#2052]
## Your Environment
* Plugin version: latest
* Platform: Android
* OS version: Windows 11
* Device manufacturer / model: Emulator
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
React.useEffect(() => {
    const onLocation = BackgroundGeolocation.onLocation((location) => {
      console.log('[onLocation]', location);
      setLocation(JSON.stringify(location, null, 2));
    });

    const onMotionChange = BackgroundGeolocation.onMotionChange((event) => {
      console.log('[onMotionChange]', event);
    });

    const onActivityChange = BackgroundGeolocation.onActivityChange((event) => {
      console.log('[onActivityChange]', event);
    });

    const onProviderChange = BackgroundGeolocation.onProviderChange((event) => {
      console.log('[onProviderChange]', event);
    });

    const onHeartbeat = BackgroundGeolocation.onHeartbeat((event) => {
      console.log("[onHeartbeat] ", event);
    
      BackgroundGeolocation.getCurrentPosition({
        samples: 1,
        persist: false
      }).then((location) => {
        console.log("[getCurrentPosition] ", location);
        setLocation(location);
      });
    });

    BackgroundGeolocation.ready({
      //Common Options
      locationAuthorizationRequest: "Always",
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1,
      stopTimeout: 3,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      //heartbeatInterval: 60,

      //Only Android
      foregroundService: true,
      enableHeadless: false,
      //locationUpdateInterval: 60000, 
      allowIdenticalLocations: false,

      //Only iOS
      showsBackgroundLocationIndicator: true,
      preventSuspend: true
    }).then((state) => {
      setEnabled(state.enabled);
      console.log("BackgroundGeolocation is configured and ready: ", state.enabled);
    });

    return () => {
      //Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
      //during development live-reload.  Without this, event-listeners will accumulate with
      //each refresh during live-reload.
      onLocation.remove();
      onMotionChange.remove();
      onActivityChange.remove();
      onProviderChange.remove();
      onHeartbeat.remove();
    }
  }, []);

  React.useEffect(() => {
    if (!enabled) { 
      BackgroundGeolocation.start();
    }
  }, []);
```

## Steps to Reproduce

1. open Android emulator
2. npx expo run:android
3. create a route in the emulator to simulate movement
4. 

## Context
Hello Chris, now I'm getting serious about testing the plugin to evaluate the license purchase and I'm very confused about some things. Would you help me?

I'm using the Android emulator to do the Tests... My goal is to look for the location in the Foreground, Background and even when the application is closed.

1 - At times it is showing an invalid license alert. Is this a problem or just a warning?

2 - Can I generate a fully functional build for iOS to test on TestFlight without having the license?

3 - I'm confused with Location Search, because sometimes it works and sometimes it doesn't. I created a route in the Android emulator and left it running. When the application starts, it catches some of the events but does not start localization. Then I do some Reloads and then suddenly the location starts working out of nowhere... I noticed the false value in "is_moving" for the "onMotionChange" event. I don't know if it's related to the License that I don't have yet or if it's because of the emulator...

4 - I don't understand if I really need to start or if it is automatic. When I leave the code that does the start, the message below sometimes appears:

Possible Unhandled Promise Rejection (id: 0):
"Waiting for previous start action to complete"

5 - When I execute BackgroundGeolocation.ready() am I already starting the location or just configuring it? I ask because soon after I receive some events such as onLocation and onMotionChange.

6 - If I remove Subscribers as you suggest below, when the user closes the application will I not stop hearing onLocation?

return() => {
 //Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
 //during development live-reload. Without this, event-listeners will accumulate with
 //each refresh during live-reload.
 onLocation.remove();
 onMotionChange.remove();
 onActivityChange.remove();
 onProviderChange.remove();
 }

7 - What settings are important in my case where I want to search for location in the background even with the application closed? Do I have to do anything else?

8 - How can I search for location by time instead of distance for both environments (iOS and Android)? Why for Android we have the "locationUpdateInterval" setting but for iOS we don't have something equivalent. I tried using heartbeat but it didn't work, because getCurrentPosition is always returning the same location every 1 minute. Would using heartbeat in this case be recommended for what I want to do? I didn't quite understand when to use heartbeat...

9 - In the case of iOS, as I want to get the location even with the application closed, do I need to set "preventSuspend: true"? I didn't understand why because the documentation says: Enable this to prevent iOS from suspending your app in the background while it is stopped. But from what I understand, if I'm stopped, it's not to get the location... or am I wrong?

10 - Can I use the plugin to get the current location at any time using getCurrentPosition when I am in the foreground? Today I use "expo-location" but as I want to buy the plugin, I would like to do everything through it.

Thank you very much!

**Comment by christocracy** [comment]
The plug-in is fully functional in debug builds, in spite of license warning.

you cannot fully experience the true nature of this plug-in in the Android emulator.  It will not automatically trigger location-tracking.

you need to go outside with a real device with real movement.  Go for a 1km walk.

also see wiki “Debugging” and “Philosophy of Operation”.  learn about the .changePace method (search api docs).

**Comment by souzadeveloper** [comment]
Chris, can you answer the other questions?

From what I understand, in the case of iOS it only recognizes movement from 200 meters? that's right?

**Comment by christocracy** [comment]
> in the case of iOS it only recognizes movement from 200 meters? that's right?

iOS requires the device move at least 200 meters before tracking engages.

Many of your questions are moot until you go outside and test with a real device.

**Comment by souzadeveloper** [comment]
Can you answer at least these two below?

8 - How can I search for location by time instead of distance for both environments (iOS and Android)? Why for Android we have the "locationUpdateInterval" setting but for iOS we don't have something equivalent. I tried using heartbeat but it didn't work, because getCurrentPosition is always returning the same location every 1 minute. Would using heartbeat in this case be recommended for what I want to do? I didn't quite understand when to use heartbeat...

9 - In the case of iOS, as I want to get the location even with the application closed, do I need to set "preventSuspend: true"? I didn't understand why because the documentation says: Enable this to prevent iOS from suspending your app in the background while it is stopped. But from what I understand, if I'm stopped, it's not to get the location... or am I wrong?

**Comment by christocracy** [comment]
The iOS Location API is strictly *distance-based*.  There are no time-based location updates for iOS.  

> In the case of iOS, as I want to get the location even with the application closed, do I need to set "preventSuspend: true"?

99% of apps should **NOT** use `preventSuspend: true`.  Avoid this and forget you ever learned about "preventSuspend".   The only thing you need is `stopOnTerminate: false` (Read the API docs about this).

**Comment by christocracy** [comment]
The best way to test is to go outside for a 1km walk with `debug: true` configured.

**Comment by souzadeveloper** [comment]
Ok Chris! Thank you very much!
