### ISSUE TITLE
Android (Samsung) forces minimum radius to 150

### ISSUE THREAD

**Issue by UnderTheMoonspell** [transistorsoft/react-native-background-geolocation#2054]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 4.14.3
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.72.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
The radius returned "should" be the same for iOS and Android

## Actual Behavior
We fetch locations from our API, and then create geofences with that data. With the same user, and the same set of coordinates (with radius of 50 and 200), if, after we create the geofences, we read them using BackgroundGeolocation.getGeofences(), we will get radius of 150 (when it should be 50). This happens on Android (Samsung Galaxy S23), although the Android guidelines clearly state that "For best results, the minimum radius of the geofence should be set between 100 - 150 meters. When Wi-Fi is available location accuracy is usually between 20 - 50 meters."

Logs (After transforming the geofence array result from getGeofences function to an object):

IOS:
```
{
   "5e8401d6-2dce-4e4a-9b4e-1e122876d3e8":{
      "latitude":38.794933,
      "longitude":-9.218946,
      "radius":200
   },
   "bd47099e-b537-4aa1-974a-b0b684aa9302":{
      "latitude":39.12783342,
      "longitude":-86.52936843,
      "radius":50
   },
   "cd00ea4e-702c-45c4-abc8-7ce8438d5b50":{
      "latitude":38.782,
      "longitude":-9.0947,
      "radius":50
   },
   "cf676d36-be4b-4b67-b90c-dadc3654826b":{
      "latitude":38.7987,
      "longitude":-9.2192,
      "radius":200
   }
}
```

Android:
```
{
   "5e8401d6-2dce-4e4a-9b4e-1e122876d3e8":{
      "latitude":38.794933,
      "longitude":-9.218946,
      "radius":200
   },
   "bd47099e-b537-4aa1-974a-b0b684aa9302":{
      "latitude":39.12783342,
      "longitude":-86.52936843,
      "radius":150
   },
   "cd00ea4e-702c-45c4-abc8-7ce8438d5b50":{
      "latitude":38.782,
      "longitude":-9.0947,
      "radius":150
   },
   "cf676d36-be4b-4b67-b90c-dadc3654826b":{
      "latitude":38.7987,
      "longitude":-9.2192,
      "radius":200
   }
}
```

## Steps to Reproduce

1. Create geofences with radius less than 150
2. Read geofences

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The lowest radius the native APIs respond to is 150-200 meters.

Setting a geofence radius of 50 responds the same as 150.

**Comment by UnderTheMoonspell** [comment]
So what about the info in the [Android Docs](https://developer.android.com/develop/sensors-and-location/location/geofencing#choose-the-optimal-radius-for-your-geofence).

And in the source code, the only check for radius is ">0": [Geofence.java](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/location/Geofence.java?q=geofence&ss=android%2Fplatform%2Fsuperproject%2Fmain)
