### ISSUE TITLE
Basic Doubts

### ISSUE THREAD

**Issue by souzadeveloper** [transistorsoft/react-native-background-geolocation#2058]
Hi Chris, I made a lot of progress in testing with your tips, but I have a few more questions:

1 - To use preventSuspend, is it mandatory to implement the Heartbeat event?

2 - Is there any configuration so that the location search only starts after BackgroundGeolocation.start()? Because I noticed that sometimes the plugin starts right after ready().

3 - getCurrentPosition returns the current position if I am in a Moving state and the last known position when I am in a stationary state? Any settings to return the most accurate position possible?

4 - How do I know if users have granted the necessary permissions for the plugin to fetch the location?

Thanks!!!

**Comment by souzadeveloper** [comment]
Hi Chris, we purchased the License, I await your responses so we can move forward. Thanks!

**Comment by christocracy** [comment]
1.  Implementing *any* event-listener is *optional*.  Just like wiring up speakers to your stereo system is *optional*.

>2. Because I noticed that sometimes the plugin starts right after ready().

When you call `.start()`, the plugin is enabled *forever* until you call `.stop()` (see `State.enabled`).  The plugin persists its state in permanent storage.  Calling `.ready(config)`. restores the last known `State.enabled`.

>3 - getCurrentPosition returns the current position if I am in a Moving state and the last known position when I am in a stationary state? Any settings to return the most accurate position possible?

Observe your logs in `$ adb logcat` for warnings (se Wiki "Debugging").  Android does not always allow your app to turn on location-serves when the app is in the background with the plugin in the stationary state.

> 4.  How do I know if users have granted the necessary permissions for the plugin to fetch the location

See API docs `.onProviderChange`.

**Comment by souzadeveloper** [comment]
Chris,

1 - So if I enable preventSupend for iOS and don't implement hearbeat, iOS will continue to respond to the onLocation event normally when the application is closed?

3 - The objective is to use getCurrentPosition only in the Foreground. In this case, is the position real regardless of whether the state is moving or stationary?

Thanks!

**Comment by christocracy** [comment]
>So if I enable preventSupend for iOS and don't implement hearbeat, iOS will continue to respond to the onLocation event normally when the application is closed?

99% of use-cases do **NOT** require `preventSuspend`.  You probably don't need `preventSuspend`.  I don't think you understand what it is.  It's not some magic feature.  `preventSuspend` does **NOT** work when the app is terminated.  I suggest you forget you ever heard of `preventSuspend`.

See the API docs `Config.stopOnTerminate`.  iOS is fully capable of continuing to track location after app terminate (once the device moves at least 200 meters).  There is no way to overcome the "200 meter requirement".

>The objective is to use getCurrentPosition only in the Foreground. In this case, is the position real regardless of whether the state is moving or stationary?

There is no issue with `.getCurrentPosition` in the foreground.  Are you reading the API docs?

**Comment by souzadeveloper** [comment]
Ok Chris Thanks!

**Comment by christocracy** [comment]
I already [told you to forget about `preventSuspend`](https://github.com/transistorsoft/react-native-background-geolocation/issues/2052#issuecomment-2163436001)
