### ISSUE TITLE
Expo integration

### ISSUE THREAD

**Issue by Namec999** [transistorsoft/react-native-background-geolocation#2059]
Hello,

using Expo SDK51 with android.

after creating a new expo project, and setting up everything as mentioned in the docs
then trying the functional example who is found in the Readme file

i am stuck with getting BackgroundGeolocation.ready

when i use BackgroundGeolocation.start() or BackgroundGeolocation.stop() i get : cannot read property 'start' of null

i thing there is some permissions that are missing if the library is not setting them up automatically

all help will be appreciated

let the force be with you

**Comment by Namec999** [comment]
i'll restart the process.

it's quite simple also i am runing the regular npx expo start with Expo Go App

**Comment by christocracy** [comment]
Use `$ npx run:android` or `run:iOS`

**Comment by Namec999** [comment]
my App.js 

`
import React from 'react';
import {
  Switch,
  Text,
  View,
} from 'react-native';

import BackgroundGeolocation, {
  Location,
  Subscription
} from "react-native-background-geolocation";

const App = () => {
  const [enabled, setEnabled] = React.useState(false);
  const [location, setLocation] = React.useState('');


  React.useEffect(() => {
    console.log('[App] useEffect 001');
    /// 1.  Subscribe to events.
    const onLocation = BackgroundGeolocation.onLocation((location) => {
      console.log('[onLocation]', location);
      setLocation(JSON.stringify(location, null, 2));
    })

    const onMotionChange = BackgroundGeolocation.onMotionChange((event) => {
      console.log('[onMotionChange]', event);
    });

    const onActivityChange = BackgroundGeolocation.onActivityChange((event) => {
      console.log('[onActivityChange]', event);
    })

    const onProviderChange = BackgroundGeolocation.onProviderChange((event) => {
      console.log('[onProviderChange]', event);
    })
    console.log('[App] useEffect 002');
    /// 2. ready the plugin.
    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,            // Must be 0 or locationUpdateInterval is ignored!
      locationUpdateInterval: 5000,  // Get a location every 5 seconds
      // Activity Recognition
      stopTimeout: 500,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'http://yourserver.com/locations',
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSyncThreshold: 5,
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "X-FOO": "bar"
      },
      params: {               // <-- Optional HTTP params
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
    }).then((state) => {
      console.log('[App] useEffect 003');
      setEnabled(state.enabled)
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
    });

    return () => {
      console.log('[App] useEffect Return');
      // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
      // during development live-reload.  Without this, event-listeners will accumulate with
      // each refresh during live-reload.
      onLocation.remove();
      onMotionChange.remove();
      onActivityChange.remove();
      onProviderChange.remove();
    }
  }, []);

  /// 3. start / stop BackgroundGeolocation
  React.useEffect(() => {
    if (enabled) {
      BackgroundGeolocation.start();
    } else {
      BackgroundGeolocation.stop();
      setLocation('');
    }
  }, [enabled]);

  return (
    <View style={{alignItems:'center'}} className="mt-50">
      <Text>Click to enable BackgroundGeolocation</Text>
      <Switch value={enabled} onValueChange={setEnabled} />
      <Text style={{fontFamily:'monospace', fontSize:12}}>{location}</Text>
    </View>
  )
}

export default App;`

and my package.json

`{
  "name": "tr02",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~51.0.14",
    "expo-gradle-ext-vars": "^0.1.2",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "0.74.2",
    "react-native-background-fetch": "^4.2.5",
    "react-native-background-geolocation": "^4.16.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
`

**Comment by Namec999** [comment]
do i need to eject my expo app

currently using expo for all our apps because of the dev workflow

**Comment by Namec999** [comment]
now every thing is OK

it's working only with expo-dev-client not with the regular expo Go app

thanks for your support

you'll hear a lot from me in the next few hours :-) sorry for that lol
