### ISSUE TITLE
Is it possible to prevent persistence? - Question

### ISSUE THREAD

**Issue by vessp** [transistorsoft/react-native-background-geolocation#206]
## Your Environment
* Plugin version: 2.4.1
* Platform: iOS
* OS version: 10
* Device manufacturer / model: Apple iPhone 6
* React Native version (`react-native -v`): 0.41.2

## Context

Sorry if I missed this in the docs but I am wondering if there is a config option to prevent locations from being persisted in the database? 

Sometimes I do not require the locations to be saved or synched so there is no reason to save them at all.  I could just use **watchPosition** or **getCurrentPosition** with **{persist:false}** but I still want to make use of the config options to preserve battery life.  I am trying to optimize my app, so the motivation for not saving them is simply to limit needless processing.  

Edit: I found a commit for the **maxRecordsToPersist** config parameter, but this isn't listed in the API Documentation, I suppose setting this to **0** would do the trick?

Thankyou

**Comment by christocracy** [comment]
See #maxRecordsToPersist.  Set it to 0.
