### ISSUE TITLE
Post Payload Optimization 

### ISSUE THREAD

**Issue by Namec999** [transistorsoft/react-native-background-geolocation#2060]
Currently using Expo SDK 51 and everything is working like a charm
i am wondering if there is any way to reduce the size of the payload by renaming some of the features like 'speed' to 'sp', 

and also remove completely some features from the payload like :  "activity": {"confidence": 100, "type": "walking"}, and so on

**Comment by christocracy** [comment]
Read the API docs "HTTP Guide".  it's linked throughout.  Scan through and read *all* the headings of that document.  You might find one particularly interesting, called "*Custom JSON Schema*".

<img width="648" alt="Screenshot 2024-06-17 at 3 24 34 PM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/ba0bc163-19a5-410f-803e-6ec023259869">

**Comment by Namec999** [comment]
my bad,

you really achieved a great work

no more questions until i'll check all the docs
