### ISSUE TITLE
Permissions in Background Tracking

### ISSUE THREAD

**Issue by souzadeveloper** [transistorsoft/react-native-background-geolocation#2061]
## Your Environment
* Plugin version: 4.16.2
* Platform: Android
* OS version: Android 13
* Device manufacturer / model: Motorola Edge
* React Native version (`react-native -v`): 0.71.14
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      locationAuthorizationRequest: "Always",
      backgroundPermissionRationale: {
        title: "Permitir que SitraMobile acesse a sua Localização em Segundo Plano?",
        message: "Para acessar a sua Localização em Segundo Plano, ative a permissão Permitir o Tempo Todo.",
        positiveAction: "Alterar para Permitir o Tempo Todo",
        negativeAction: "Cancelar"
      },
      locationAuthorizationAlert: {
        titleWhenNotEnabled: "Os Serviços de Localização estão desativados.",
        titleWhenOff: "Os Serviços de Localização estão desligados.",
        instructions: "Você deve habilitar a permissão Permitir o Tempo Todo para os Serviço de Localização.",
        cancelButton: "Cancelar",
        settingsButton: "Configurações"
      },
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      stopTimeout: 3,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false,
      startOnBoot: true,
      allowIdenticalLocations: false,
      enableHeadless: true,
      showsBackgroundLocationIndicator: true
    }
```

## Steps to Reproduce

1.
2.
3.
4.

## Context
Hi Chris, I'm a little confused on how to handle permissions... I'm simulating cases where the user denies permission to Location Services. I noticed that if I try to call start() without permission, a Permission Denied Alert occurs. I still don't understand if this also occurs when I call stop().

I have two situations:

- In the first case, the Application can now start without permissions. In this case, the modal appears requesting permissions and the user denies it once again. In this case I can manage not to call start and the monitoring will stop

- In the second case, let's say that everything was fine with the permissions and location monitoring works perfectly, but the user decides to go to the settings and remove the permissions. In this case I was lost on how to proceed...

Calling requestPermission() appears to only work once after the user makes their choice. After that he would have to manually go to the settings to activate the permissions again.

Would you help me?

Thanks.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Calling requestPermission() appears to only work once after the user makes their choice. After that he would have to manually go to the settings to activate the permissions again.

That’s correct.  The OS gives you one shot to show the native permission dialog provided by the OS.  The OS will not spam the user.  If the user denies your request, it’s up to you to produce your own dialog and ask the user to “pretty please” enable desired permissions in your app Settings.

listen to .onProviderChange event to learn the current state of permissions.

**Comment by christocracy** [comment]
> if the permission is denied, could I call stop()?

Why don’t you try it and see?

**Comment by souzadeveloper** [comment]
ok, I'll do some tests. Thanks!

**Comment by souzadeveloper** [comment]
Hi Chris, based on your experience with the plugin, if the user removes permissions when tracking is in progress in the background or with the application closed, it is better to call stop() to stop tracking or I can wait until it starts again location permissions? I'm worried if the connected plugin will consume battery even when it's without permissions.

Thanks!

**Comment by souzadeveloper** [comment]
Hi Chris, Can you answer my question?

Thanks!

**Comment by souzadeveloper** [comment]
Hi Chris, based on your experience with the plugin, if the user removes permissions when tracking is in progress in the background or with the application closed, it is better to call stop() to stop tracking or I can wait until it starts again location permissions? I'm worried if the connected plugin will consume battery even when it's without permissions.

Thanks!
