### ISSUE TITLE
Start Tracking on Closed Application

### ISSUE THREAD

**Issue by souzadeveloper** [transistorsoft/react-native-background-geolocation#2062]
## Your Environment
* Plugin version: 4.16.2
* Platform: Android
* OS version: Android 13
* Device manufacturer / model: Motorola Edge
* React Native version (`react-native -v`): 0.71.14
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      locationAuthorizationRequest: config?.capturaLocalizacao ? "Always" : "WhenInUse",
      backgroundPermissionRationale: {
        title: "Permitir que SitraMobile acesse a sua Localização em Segundo Plano?",
        message: "Para acessar a sua Localização em Segundo Plano, ative a permissão Permitir o Tempo Todo.",
        positiveAction: "Alterar para Permitir o Tempo Todo",
        negativeAction: "Cancelar"
      },
      locationAuthorizationAlert: {
        titleWhenNotEnabled: "Os Serviços de Localização estão desativados.",
        titleWhenOff: "Os Serviços de Localização estão desligados.",
        instructions: "Você deve habilitar a permissão Permitir o Tempo Todo para os Serviço de Localização.",
        cancelButton: "Cancelar",
        settingsButton: "Configurações"
      },
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      stopTimeout: 3,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false,
      startOnBoot: true,
      allowIdenticalLocations: false,
      enableHeadless: true,
      showsBackgroundLocationIndicator: true
    }

My HeadlessJS code:

const headlessLocationTask = async (event) => {
  switch (event.name) {
    case 'location':
      console.log('[onLocation HeadlessTask] -', event.name, event.params);
      await processLocation(event.params);
      break;
  }
}

BackgroundGeolocation.registerHeadlessTask(headlessLocationTask);
```

## Steps to Reproduce

1.
2.
3.
4.

## Context
Hi Chris, today I did a test, I left the application closed and soon after I started moving with my vehicle. The Plugin played the sounds that it was getting the locations but did not register any. If I start the movement with the application open and then close it, then the locations are obtained. Do I need to do anything else besides HeadlessJS?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>The Plugin played the sounds that it was getting the locations but did not register any

If the plugin plays the sounds, that means locations *were* registered, 100% guaranteed.

See Wiki "Debugging" and observe your logs.  Search api docs "emailLog".

**Comment by souzadeveloper** [comment]
Hi Chris, sorry, it was my fault as I put the HeadlessJS Registry in a Context. I switched to my index.js and now my HeadlessJS function is being called correctly.

The logs helped identify this issue.

Thanks

**Comment by theCoderrrr** [comment]
> Merhaba Chris, arkadaşım, HeadlessJS Registry'yi bir Context'e koyduğum için hata verdi. Index.js'imi geçtim ve şimdi HeadlessJS fonksiyonum doğru şekilde çağrılıyor.
> 
> Günlükler bu sorunun belirlenmesine yardımcı oldu.
> 
> Şerefsizler

Hello, I have the same problem. How did you solve it? Can you help me?

**Comment by souzadeveloper** [comment]
> > Merhaba Chris, arkadaşım, HeadlessJS Registry'yi bir Context'e koyduğum için hata verdi. Index.js'imi geçtim ve şimdi HeadlessJS fonksiyonum doğru şekilde çağrılıyor.
> > Günlükler bu sorunun belirlenmesine yardımcı oldu.
> > Şerefsizler
> 
> Hello, I have the same problem. How did you solve it? Can you help me?

Hello, explain your problem better or provide some part of your code so I can help you.

**Comment by theCoderrrr** [comment]
> > > Merhaba Chris, arkadaşım, HeadlessJS Registry'yi bir Context'e koyduğum için hata verdi. Index.js'imi geçtim ve şimdi HeadlessJS fonksiyonum doğru şekilde çağrılıyor.
> > > Günlükler bu sorunun belirlenmesine yardımcı oldu.
> > > Şerefsizler
> > 
> > 
> > Hello, I have the same problem. How did you solve it? Can you help me?
> 
> Hello, explain your problem better or provide some part of your code so I can help you.

Should I post it here? If you're using Discord, let's talk there.

**Comment by souzadeveloper** [comment]
> > > > Merhaba Chris, arkadaşım, HeadlessJS Registry'yi bir Context'e koyduğum için hata verdi. Index.js'imi geçtim ve şimdi HeadlessJS fonksiyonum doğru şekilde çağrılıyor.
> > > > Günlükler bu sorunun belirlenmesine yardımcı oldu.
> > > > Şerefsizler
> > > 
> > > 
> > > Hello, I have the same problem. How did you solve it? Can you help me?
> > 
> > 
> > Hello, explain your problem better or provide some part of your code so I can help you.
> 
> Should I post it here? If you're using Discord, let's talk there.

I believe this is a good place to continue the subject as it can be useful for other developers and even Chris can help us. Then post it right here.

**Comment by theCoderrrr** [comment]
> > > > > Merhaba Chris, arkadaşım, HeadlessJS Registry'yi bir Context'e koyduğum için hata verdi. Index.js'imi geçtim ve şimdi HeadlessJS fonksiyonum doğru şekilde çağrılıyor.
> > > > > Günlükler bu sorunun belirlenmesine yardımcı oldu.
> > > > > Şerefsizler
> > > > 
> > > > 
> > > > Hello, I have the same problem. How did you solve it? Can you help me?
> > > 
> > > 
> > > Hello, explain your problem better or provide some part of your code so I can help you.
> > 
> > 
> > Should I post it here? If you're using Discord, let's talk there.
> 
> I believe this is a good place to continue the subject as it can be useful for other developers and even Chris can help us. Then post it right here.

I added headlesstask to my code, but I cannot get updated output. When I want to get debug output, it always gives the old output.

**Comment by souzadeveloper** [comment]
> > > > > > Merhaba Chris, arkadaşım, HeadlessJS Registry'yi bir Context'e koyduğum için hata verdi. Index.js'imi geçtim ve şimdi HeadlessJS fonksiyonum doğru şekilde çağrılıyor.
> > > > > > Günlükler bu sorunun belirlenmesine yardımcı oldu.
> > > > > > Şerefsizler
> > > > > 
> > > > > 
> > > > > Hello, I have the same problem. How did you solve it? Can you help me?
> > > > 
> > > > 
> > > > Hello, explain your problem better or provide some part of your code so I can help you.
> > > 
> > > 
> > > Should I post it here? If you're using Discord, let's talk there.
> > 
> > 
> > I believe this is a good place to continue the subject as it can be useful for other developers and even Chris can help us. Then post it right here.
> 
> I added headlesstask to my code, but I cannot get updated output. When I want to get debug output, it always gives the old output.

BackgroundGeolocation.registerHeadlessTask(headlessLocationTask) must be called necessarily in your index.js. Remove the call from anywhere other than index.js. Without your code I can't help.
