### ISSUE TITLE
Background Location not detecting on few devices like Oneplus , Apple Iphone 15 pro

### ISSUE THREAD

**Issue by c-info** [transistorsoft/react-native-background-geolocation#2066]
## Your Environment
* Plugin version: 4.16.2
* Platform: Android Oneplus 8Pro 
* OS version: 13
* Device manufacturer/model: LineageOS version 20-20230217-microG-instantnoodlep
* React Native version 0.71.3
* Plugin config

```
BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      locationUpdateInterval: 1000,
      distanceFilter: 2,
      isMoving: true,
      stopTimeout: 10,
    })
      .then(state => {
        if (!state.enabled) {
          BackgroundGeolocation.start();
        }
      })
      .catch(err => {
        console.log('Error', err);
      });

BackgroundGeolocation.getState().then(state => {
      setIsLocationEnabled(state.enabled);
    });

    const onLocationChange = BackgroundGeolocation.onLocation(
      region => {
          setCurrentRegion(region);
      },
      error => {
        console.warn('[onLocation] ERROR: ', error);
      },
    );

    const onMotionChange =
      BackgroundGeolocation.onMotionChange(setMotionChangeEvent);

    const onEnabledChange =
      BackgroundGeolocation.onEnabledChange(setIsLocationEnabled);
```

## Expected Behavior
1) Background location should update on location change constantly 
2) It should return updated locations constantly similar to Google map in walking mode

## Actual Behavior
1) Background location is not working on a few devices ie. Oneplus, Apple iPhone 15 Pro

## Steps to Reproduce
1. Setup basic project and run on devices given above

## Context
1) We need to show the updated user location on a map similar to the Google Maps application

**Comment by christocracy** [comment]
I’ve been field-testing daily on a number of devices almost daily for over 9 years and it never fails.  My latest iOS device is an iPhone 15 Pro.

see wiki Philosophy of Operation and Debugging.  Learn to observe the plug-ins incredibly verbose logs.  Learn to capture the logs using .emailLog method (search the APi docs)

**Comment by amittri** [comment]
i have same issue with iqoo phone..

[background-geolocation.log.gz](https://github.com/user-attachments/files/15955051/background-geolocation.log.gz)
i have attached the log file.

**Comment by c-info** [comment]
@christocracy Kindly help me to resolve this issue as it creates a pain point and I cannot move further from this task my main goal is to show real-time location to the user.

**Comment by christocracy** [comment]
@c-info youve provided no context (see the original post of this issue),  post your own issue.

**Comment by c-info** [comment]
See the attached screenshot it clearly shows that location is not updating on real-time
![2](https://github.com/transistorsoft/react-native-background-geolocation/assets/71883031/6b59b2d7-acd7-4be5-954b-155213041394)
 
![1](https://github.com/transistorsoft/react-native-background-geolocation/assets/71883031/033ce91b-2005-4802-829a-0024ed7379cc)

**Comment by christocracy** [comment]
Post **a new issue!**

**Comment by christocracy** [comment]
Sorry, I meant @amittri post a new issue, who came here to hijack this issue.

**Comment by christocracy** [comment]
> LineageOS 

Try with a standard Android device.
