### ISSUE TITLE
java.lang.IncompatibleClassChangeError upon update from Expo SDK 49 to 51

### ISSUE THREAD

**Issue by zach-gard-tech** [transistorsoft/react-native-background-geolocation#2070]
## Your Environment
* Plugin version: 4.12.1
* Platform: Android
* OS version: Android 14.0
* Device manufacturer / model: Google Pixel 3a API 34
* React Native version (`react-native -v`): 0.74.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

```

## Expected Behavior
We should be able to login to our app and access the map without problems.

## Actual Behavior
Upon logging in, we get the crash.

## Steps to Reproduce

1.
2.
3.
4.

## Context
We were just trying to login to the app after upgrading from SDK 49 to 51 through Android. With iOS, there are no issues.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Your app just crashed. See the error below.
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com. google.android gms.location.ActivityRecognitionClient' appears in <censored>base.apk!classes6.dex)
com.transistorsoft.xms.g.location.ActivityRecognitionClient.requestActivityUpdates(Unknown Source:50)
com.transistorsoft.locationmanager.service.ActivityRecognitionService.start(Unknown Source:78)
com.transistorsoft.locationmanager.service.TrackingService.start(Unknown Source:49)
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:146)
java.util. concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util. concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
java. lang.Thread. run (Thread.java: 1012)
```

</details>

**Comment by christocracy** [comment]
Search issues](https://github.com/transistorsoft/react-native-background-geolocation/issues?q=IncompatibleClassChangeError) **BEFORE** posting.

Duplicate #1710
