### ISSUE TITLE
The operation couldn’t be completed. Background procssing task was not registered in AppDelegate didFinishLaunchingWithOptions.  See iOS Setup Guide.

### ISSUE THREAD

**Issue by imGanesh7357** [transistorsoft/react-native-background-geolocation#2071]
How to fix this error

The operation couldn’t be completed. Background procssing task was not registered in AppDelegate didFinishLaunchingWithOptions.  See iOS Setup Guide.

my AppDelegate.m +++++++++++++++++++++++++++

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <Firebase.h>
#import <TSBackgroundFetch/TSBackgroundFetch.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"siddhiananta";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.

  // [REQUIRED] Register BackgroundFetch
  [[TSBackgroundFetch sharedInstance] didFinishLaunching];
  [application setMinimumBackgroundFetchInterval:UIApplicationBackgroundFetchIntervalMinimum];

  self.initialProps = @{};
  [FIRApp configure];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

**Comment by christocracy** [comment]
Post your Info.plist

**Comment by christocracy** [comment]
You are posting about background-fetch (this is the background-geolocation repo) on a closed issue.
