### ISSUE TITLE
Strange background location indicator - can't turn off

### ISSUE THREAD

**Issue by felipemelendez** [transistorsoft/react-native-background-geolocation#2073]
## Your Environment
* Plugin version: 4.16.2
* Platform: iOS and Android
* OS version: Android : 13 & iOS : 17.5.1
* Device manufacturer / model: All
* React Native version (`react-native -v`): 0.74.2
* Plugin config
```javascript
{
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
                geofenceModeHighAccuracy: true,
                distanceFilter: distanceFilter,
                stationaryRadius: 25,
                startOnBoot: true,
                enableHeadless: true,
                stopOnTerminate: false,
                locationUpdateInterval: 1000,
                fastestLocationUpdateInterval: 500,
                disableLocationAuthorizationAlert: true,
                showsBackgroundLocationIndicator: false,
            },
```

## Expected Behavior
The background location indicator should not appear, especially when the app is active - I have turned off `showsBackgroundLocationIndicator` to shake this off.

## Actual Behavior
When the app is active I sometimes see strange text where the location indicator belongs.
I'm sharing a screenshot of it - there are two versions, sometimes it has a `K` and sometimes something that looks like an `t it!` :shrug:
![IMG_7310](https://github.com/transistorsoft/react-native-background-geolocation/assets/86751220/5443b158-5cf7-4e3c-81e4-f3c4db00ec2a)

![IMG_7311](https://github.com/transistorsoft/react-native-background-geolocation/assets/86751220/e9857790-f6cc-4a89-98aa-99b6e508d4e1)

That's weird, how can I get rid of that? Or is that a remnant of something that should have been removed?

Thanks in advanced for any insight shared.

**Comment by christocracy** [comment]
I have no idea what it is.  I’ve never heard if it before.  It’s not from this plug-in.

**Comment by felipemelendez** [comment]
ok, I figured out where the letters are coming from but I have no idea how they got there, all I know is that they made their way up to the location indicator after I installed this plug-in.

I have alerts that offer information to the user, in one the close button says "Got it!" and in the other one it says "OK".

**Comment by christocracy** [comment]
I suggest you consult with the api docs of the plug-in you use for notifications.

**Comment by felipemelendez** [comment]
> I suggest you consult with the api docs of the plug-in you use for notifications.

ok, thanks, but it's just the React Native `alert`.
