### ISSUE TITLE
updating location while terminated

### ISSUE THREAD

**Issue by felipemelendez** [transistorsoft/react-native-background-geolocation#2076]
## Your Environment
* Plugin version: 4.16.2
* Platform: iOS and Android
* OS version: Android : 13 & iOS : 17.5.1
* Device manufacturer / model: All
* React Native version (`react-native -v`): 0.74.2
* Plugin config

For BackgroundGeolocation
```javascript
BackgroundGeolocation.ready(
    {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 5,
        stationaryRadius: 25,
        startOnBoot: true,
        enableHeadless: true,
        stopOnTerminate: false,
        locationUpdateInterval: 1000,
        fastestLocationUpdateInterval: 500,
        disableLocationAuthorizationAlert: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        debug: true,
    },
    (state) => {
        if (!state.enabled) {
            BackgroundGeolocation.start();
        }
    }
);
```

For BackgroundFetch
```javascript
BackgroundFetch.configure(
{
    minimumFetchInterval: 15,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    requiresCharging: false,
    requiresDeviceIdle: false,
    requiresBatteryNotLow: false,
    requiresStorageNotLow: false,
},
onEvent,
onTimeout
);
```

## Expected Behavior
The app should update the location of children continuously, even if the app is terminated - like `Life360` does.

## Actual Behavior
The child has to walk 200 meters before the app updates the location

## Context
Life360 can update users' locations almost immediately after the app is terminated on both iOS and Android. Users do not need to walk 200 meters before the app updates their location.

You insist that this is an iOS limitation, but that cannot be true—Life360 does not require such movement.

Like Life360, I am developing an app to allow parents to monitor their children's locations.

Is this API capable of handling location updates without requiring a person to move 200 meters? 
I initially thought `preventSuspend` would help, but you advised against using it. Now I am uncertain. 
This API works great for fleets of vehicles, but can it offer a great experience for families? 
If so, please help us understand how. Thanks.

**Comment by christocracy** [comment]
> You insist that this is an iOS limitation, but that cannot be true—Life360 does not require such movement.

There is no iOS API that allows an app to continuously monitor a terminated iOS app after terminate.

The only way to do that is via your server sending server push requests to the device and the plug-in has nothing to do with that.

**Comment by christocracy** [comment]
See my blog about this.  I provide no direct support for this and it’s *really* complicated to set up.

https://transistorsoft.medium.com/7f1d58c9d64f
