### ISSUE TITLE
Unable to track user location continuously with shorter intervals using heartbeat or background fetch

### ISSUE THREAD

**Issue by Venkatech** [transistorsoft/react-native-background-geolocation#2077]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Need to track user location continuously with shorter intervals like 5min or 10min
## Actual Behavior

 Unable to achieve the above as heart beat will only execute when device is stationary and with background fetch there is a limitation of minimum 15 min interval for iOS 
## Steps to Reproduce

1.
2.
3.
4.

## Context

Need to track user location continuously with shorter intervals like 5min or 10min even in background. Need not to track when app is killed.
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>We want to implement one use case like need to track user location continuously with short intervals like 5 or 10 min 

Not possible.  See API docs `Config.useSignificantChangesOnly`.  That will record a location about each 500-1000 meters.  `Config.distanceFilter` will be ignored.
 
>we used heartbeat but when device moving, It stops. 

That's right.  There's no need for a heartbeat when the device is detected to be moving, since the plugin will now be recording a location each `Config.distanceFilter` meters.
 
>even tried background fetch but even 15min interval is not guranteed in ios. 

That's right.  The OS uses a machine-learning algorithm to determine the rate that events fire.  If the user doesn't open your app for long periods of time, the OS will not frequently execute background-fetch events.

**Comment by Venkatech** [comment]
@christocracy  is there any limit on minimum distance filter for android or ios Thank you.

**Comment by christocracy** [comment]
0 is the lowest

**Comment by Venkatech** [comment]
Thanks for the prompt reply. A quick question does fusedLocationProvider client will have any effect due to Non stationary hotspots? Library working excellent in other scenarios. We are unable to figure out only in scenarios when connected to mobile hotspot we are not getting logs for android using distanceFilter. Could you please share some details if you have any idea? Thank you

**Comment by christocracy** [comment]
I’m unaware of any affect of “non stationary hotspots” on FusedLocationProvider.  If the device is outdoors, the location comes from GPS satellites.

**Comment by Venkatech** [comment]
Thank you. As far I know FusedLocationProvider will get either of GPS/Internet Provider. In other scenarios it worked perfectly but don't know only with mobile hotspot didn't get any logs even GPS turned on so I suspected like that.
