### ISSUE TITLE
Question about License Key

### ISSUE THREAD

**Issue by bjoxiah** [transistorsoft/react-native-background-geolocation#2078]
Hi, @christocracy, thanks for this library, I have played around in the debug mode and have gone ahead to purchase a license but haven't gotten the keys and it's delaying our work, have sent several emails and have not gotten any feedback, can you look into this pls. I know this is not the right place as I saw in your response to someone who had a similar issue. I need to know the status of my purchase.

**Comment by christocracy** [comment]
**YOUR MAIL SERVER IS BROKEN**.  IT'S BOUNCING EVERY EMAIL I SEND IT!!**.

Fix your mail server.

<img width="952" alt="Screenshot 2024-07-02 at 10 43 16 AM" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/50716790-2128-4a75-ab4f-326b5255468c">

**Comment by bjoxiah** [comment]
Oh, I just noticed the issue, currently working to resolve it.

**Comment by bjoxiah** [comment]
Thanks @christocracy, just created the license key.
