### ISSUE TITLE
getCurrentPosition not working

### ISSUE THREAD

**Issue by souzadeveloper** [transistorsoft/react-native-background-geolocation#2079]
## Your Environment
* Plugin version: ^4.16.2
* Platform: iOS
* OS version: 13
* Device manufacturer / model: Iphone 13
* React Native version (`react-native -v`): 0.71.14
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      locationAuthorizationRequest: "Always",
      backgroundPermissionRationale: {
        title: "Permitir que SitraMobile acesse a sua Localização em Segundo Plano?",
        message: "Para acessar a sua Localização em Segundo Plano, ative a permissão Permitir o Tempo Todo.",
        positiveAction: "Alterar para Permitir o Tempo Todo",
        negativeAction: "Cancelar"
      },
      locationAuthorizationAlert: {
        titleWhenNotEnabled: "Os Serviços de Localização estão desativados.",
        titleWhenOff: "Os Serviços de Localização estão desligados.",
        instructions: "Você deve habilitar a permissão Permitir o Tempo Todo para os Serviço de Localização.",
        cancelButton: "Cancelar",
        settingsButton: "Configurações"
      },
      notification: {
        title: "SitraMobile",
        text: "Os Serviços de Localização em Segundo Plano estão em execução!"
      },
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5,
      stopTimeout: 2,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      logMaxDays: 1,
      stopOnTerminate: false,
      startOnBoot: true,
      allowIdenticalLocations: true,
      enableHeadless: true,
      showsBackgroundLocationIndicator: true,
      foregroundService: true
    }

My getCurrentPosition confiuration:

const currentPosition = await BackgroundGeolocation.getCurrentPosition({
    timeout: 30,
    maximumAge: 1000,
    desiredAccuracy: 2,
    samples: 3,
    persist: false
  });
```

## Expected Behavior
Expected to capture the user's real location accurately.

## Actual Behavior
Sometimes the plugin captures the user's position at a distance of approximately 200 meters.

## Steps to Reproduce

1. call ready(config)
2. call getCurrentPosition()
3. wait a while
4. call getCurrentPosition()
5. and so on

## Context
Hi Chris, we have a tracking system where we are using the plugin to give us the position of the delivery person. As soon as it starts the application I run ready(config) to configure the plugin.

Before start() I get the delivery person's current position using getCurrentPosition().

Right after that I execute start() and the tracking starts recording the positions every 5 meters.

Whenever the delivery person makes a delivery through our application, I run getCurrentPosition() again to get the delivery person's current position, considering that this method will return the exact position of the delivery person, because if I use the location in the background it could be that is still outdated due to the geofence issue and knowing that in the case of iOS it will only start after 1 kilometer on average, as you suggest in the tests.

It turns out that I'm doing tests while stopped, that is, without leaving my position and after calling getCurrentPosition() a few times simulating deliveries here, even when stopped, sometimes the plugin returns the correct position and sometimes it returns a location very different from where I am... and if we stop to analyze it, it is almost 200 meters from my current position....

This is normal? I can't explain this abnormal behavior to my Customer because he wants the position to be exact or at least with a very small difference and not 200 meters.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> almost 200 meters from my current position

Are you calling this while indoors or outside?  GPS only works outside with a cleaner view of the sky and satellites in space.

**Comment by souzadeveloper** [comment]
Actually, I'm in the office, I know that the GPS can face interference problems among others, but what worries me is the difference is very big. If I look at maps I always see my position correctly. Is there any way to improve this experience with the plugin?

**Comment by christocracy** [comment]
Test outside.  Location indoors has a minimum accuracy of 40 meters.  There is absolutely no GPS available while indoors.

**Comment by souzadeveloper** [comment]
Ok, so I don't think it will be a problem...
