### ISSUE TITLE
Updating state in onLocation major lag when screen off

### ISSUE THREAD

**Issue by RemiHin** [transistorsoft/react-native-background-geolocation#2080]
## Your Environment
* Plugin version: 4.16.3
* Platform: Android (and iOS aswell)
* OS version: Android 14
* Device manufacturer / model: Samsung Galaxy S21 5G
* React Native version (`react-native -v`): 0.74.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      disableElasticity: false,
      elasticityMultiplier: 2,
      showsBackgroundLocationIndicator: true,
      preventSuspend: true,
      heartbeatInterval: 30,
      // Activity Recognition
      stopTimeout: 5,
      locationAuthorizationRequest: 'always',
      foregroundService: true,
      notification: {
        title: 'Wandeling aan het opnemen',
        text: 'App neemt je wandeling op',
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
        channelName: 'WalkingApp',
      },
      backgroundPermissionRationale: {
        title:
          "Allow {applicationName} to access this device's location even when closed or not in use.",
        message:
          'This app collects location data to enable recording your trips to work and calculate distance-travelled.',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      },
      enableHeadless: true,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
    }).then(state => {
      setEnabled(state.enabled);
      console.log(
        '- BackgroundGeolocation is configured and ready: ',
        state.enabled,
      );
    });
```

## Expected Behavior
In the onLocation listener my app appends the new location to the recordedRoute state, thus eventually creating a route:
```
const onLocation = BackgroundGeolocation.onLocation(location => {
      const truncated = truncate(
        {
          type: 'Point',
          coordinates: [
            location.coords.longitude,
            location.coords.latitude,
            location.coords.altitude,
          ],
        },
        {precision: 5, coordinates: 3},
      );

      const event = {
        coordinates: truncated.coordinates,
        speed: location.coords.speed,
        timestamp: location.timestamp,
      };

      setRecordedRoute(prevState => [...prevState, event]);
    });
```

## Actual Behavior
This works fine when the screen is on, also when you have the screen off temporarily, but last weekend I went on a 10+ km hike having the screen off the entire time. When i turned it on, the state updates were alle queued and started processing. It took almost 20 minutes for all the state updates to complete.
Also the app becomes very slow to respond to any other actions.

## Context
I want to record walks locally, because we often walk through areas without cell service. Using a server isn't an option. Also i want to show the current recorded route on my map, so i need access to the currently recorded route.

## Options (?)
Is there a way to get all the locations that were fired during the screen off when i turn the screen back on? Thus skipping all the state updates, and doing 1 update with all the recorded locations?
Is there a way to update the state while the app is in the background?
In the documentation there are multiple references to the plugins sqlite database, is there a way to keep them there and read from it?
Other solutions?

**Comment by RemiHin** [comment]
@christocracy is there anything wrong with my issue? or any other information i could provide to receive help with this?

**Comment by christocracy** [comment]
The plug-in is not involved with React State.

my demo app (linked in the readme), has been drawing markers on the Map (react-native-map) for years.  I’ve never had a “lag” issue.

I think the problem is in your own code or other dependencies.

**Comment by RemiHin** [comment]
You might be right, but maybe i didnt explain well.

To me it looks like the "onLocation" event isn't being fired in the background, only when the app goes to the resumed state it seems to be trying to catch up on all "onLocation" events that happened while the app was in the background, but werent processed.

Does that still seem like an issue not linked to the plug-in to you? If so, i'll try to find it elsewhere, but this felt like the place to start to me
