### ISSUE TITLE
Background geolocation not working

### ISSUE THREAD

**Issue by theCoderrrr** [transistorsoft/react-native-background-geolocation#2081]
I use the library, but when the application is closed, it keeps track and a notification sound is heard, but it does not save it to the database. Do I need to buy it for this? I did not buy it because I am testing it right now.If the problem is that I don't buy it, can you share a code sample?

**Comment by christocracy** [comment]
The plug-in is fully functional in debug builds.  I have no idea what could be wrong as you ignored the issue template which asked you to provide all sorts of information, including plug-in version, plugin Config, code, etc.
