### ISSUE TITLE
background location not working

### ISSUE THREAD

**Issue by theCoderrrr** [transistorsoft/react-native-background-geolocation#2082]
* Plugin version: 4.16.3
* Platform: Android
* OS version: 11
* Device manufacturer / model: Xiaomi redmi 9
* React Native version (`react-native -v`): 0.74.2
* Plugin config
```BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopTimeout: 1,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      method: 'POST',
      url: 'https://api.xxxx.com/add-post',
      batchSync: false,
      autoSync: true,
      maxBatchSize: 50,
      params: {
        foo: 'bar'
      },
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
    });
```

## Expected Behavior
I want the application to receive location information when it is closed.

## Actual Behavior
When the application is closed, a location sound is heard, but there is no request to the server, it disappears when the application is opened.
## Steps to Reproduce

1.
2.
3.
4.

## Context
background location tracker

**Comment by christocracy** [comment]
> a location sound is heard, but there is no request to the server

The answer is in the plug-in logs.  See wiki “Debuggjng” and search api docs “emailLog”.

**Comment by theCoderrrr** [comment]
### 

> > bir konum sesi duyuluyor ancak sunucuya herhangi bir istekte bulunulmuyor
> 
> Cevap eklenti günlüklerindedir. Wiki “Debuggjng”e bakın ve api belgelerinde “emailLog”u arayın.

I looked but that's not exactly what I mean.

**Comment by theCoderrrr** [comment]
> > a location sound is heard, but there is no request to the server
> 
> The answer is in the plug-in logs.  See wiki “Debuggjng” and search api docs “emailLog”.

I think you misunderstood me, what I mean is that when the application is closed, the request does not go to the API.

**Comment by christocracy** [comment]
I understand completely and the answer will be written in the logs.  Fetch your logs and observe them.

**Comment by theCoderrrr** [comment]
> I understand completely and the answer will be written in the logs.  Fetch your logs and observe them.

I don't quite understand what logs

**Comment by christocracy** [comment]
> I don't quite understand what logs

Then you haven’t done anything I said

> The answer is in the plug-in logs. See wiki “Debuggjng” and search api docs “emailLog”.

developing with this plugin and not observing your logs is like a blind man searching for treasure in a dark forest.

learn to observe the plug-ins incredibly verbose logs.
