### ISSUE TITLE
Polgon Geofence licence can't be applied via Expo config plugin

### ISSUE THREAD

**Issue by vonkanehoffen** [transistorsoft/react-native-background-geolocation#2085]
## Your Environment
* Plugin version: 4.16.2
* Platform: Android
* OS version: Any
* Device manufacturer / model: Any
* React Native version (`react-native -v`): 0.74.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      locationAuthorizationRequest: 'Any',
      disableMotionActivityUpdates: true,

      backgroundPermissionRationale: {
        title: "Allow access to this device's location in the background?",
        message:
          "In order to log your commuting activity automatically, please enable 'Allow all the time permission",
        positiveAction: 'Change to Allow all the time',
      },
      foregroundService: true,
      notification: {
        title: 'Mobilityways commute journal',
        text: 'Location tracking on',
      },

      // Application config
      debug: false, 
      logLevel: __DEV__
        ? BackgroundGeolocation.LOG_LEVEL_VERBOSE
        : BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false,
      enableHeadless: true,
      // HTTP / SQLite config
      url: `${config.apiUrl}/v2/liftshare/location-data`,
      batchSync: false, 
      autoSync: true, 
      headers: {
        authorization: `Bearer ${tokens?.token}`,
      },
      extras: {
        org: 'mobilityways',
      },
```

## Expected Behavior

When I buy a licence for the polygon geofence add-on I should be able to apply it via the Expo config plugin

## Actual Behavior

I bought a licence, but the only fields available in [the plugin](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/expo/plugin/src/index.ts) are `licence` and `hmsLicence`. Looking at the docs [here](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-AUTO.md#polygon-geofencing-add-on) it says the polygon add-on licence needs applying via `AndroidManifest` like:
```
<meta-data android:name="com.transistorsoft.locationmanager.polygon.license" android:value="YOUR_POLYGON_LICENCE_KEY_HERE" />
```
which is not possible to add if it's an Expo project using CNG.
...so for now we just have to create our own custom plugin? Or did we miss something?

## Steps to Reproduce

1. Buy licence
2. Activate licence key
3. Fail to find anywhere to put it ;-) 

## Context

Trying to enable polygon geofencing via the config plugin in an Expo app

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Polygon Geofencing is a relatively new add-on.  I'd neglected to implement Expo license support for it.  I've just added it now.

See [Expo Setup](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md#polygon-geofencing-support)

You must use the version `4.16.4`, published moments ago.

**Comment by alex-trofimov** [comment]
> Polygon Geofencing is a relatively new add-on. I'd neglected to implement Expo license support for it. I've just added it now.
> 
> See [Expo Setup](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md#polygon-geofencing-support)
> 
> You must use the version `4.16.4`, published moments ago.

I think it might be relevant to this: using `4.16.4` without a polygon geofencing license causes a `LICENSE VALIDATION FAILURE (com.transistorsoft.locationmanager.polygon.license: UNDEFINED)` prompt to be displayed. We aren't using that plugin in our app 🤔

**Comment by sirusbaladi** [comment]
> > Polygon Geofencing is a relatively new add-on. I'd neglected to implement Expo license support for it. I've just added it now.
> > See [Expo Setup](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md#polygon-geofencing-support)
> > You must use the version `4.16.4`, published moments ago.
> 
> I think it might be relevant to this: using `4.16.4` without a polygon geofencing license causes a `LICENSE VALIDATION FAILURE (com.transistorsoft.locationmanager.polygon.license: UNDEFINED)` prompt to be displayed. We aren't using that plugin in our app 🤔

updates on this?

**Comment by christocracy** [comment]
See CHANGELOG.
