### ISSUE TITLE
Facing issues in Real devices

### ISSUE THREAD

**Issue by Venkatech** [transistorsoft/react-native-background-geolocation#2086]
In some android devices not getting location coordinates and sometimes some logs are missing 

## Your Environment
* Plugin version: 4.16.3
* Platform: Android & Iphone
* OS version: Android 13, 14
* Device manufacturer / model: Samsung, Oneplus, Redmi, iPhone
* React Native version (`react-native -v`): 0.73.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    heartbeatInterval: 60,
    locationAuthorizationRequest: 'Always',
    locationAuthorizationAlert: {
      titleWhenNotEnabled: "Allow access to this device's location in the background",
      titleWhenOff: "Allow access to this device's location in the background",
      instructions:
        'In order to allow location tracking in the background, please enable Allow all the time permission',
      cancelButton: 'Cancel',
      settingsButton: 'Settings',
    },
    preventSuspend: true,
    distanceFilter: 200,
    disableElasticity: true,
    allowIdenticalLocations: false,
    disableProviderChangeRecord: true,
    backgroundPermissionRationale: {
      title: "Allow access to this device's location in the background",
      message: 'In order to allow location tracking, please enable Allow all the time permission',
      positiveAction: 'Settings',
    },
    notification: {
      title: 'Background location tracking started',
      text: 'Pronto Serv tracking your location',
      channelName: 'Location Tracker',
      priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
      sticky: true,
    },
  })
```

## Expected Behavior

In some of the android devices with new android versions like android 14 coordinates not getting hit in offline and some times online as well using distance filter. Some logs are missing even the gap is more than  1km when 200 meters of distance filter. 
Note: In Production builds and given all **battery** related settings mentioned in **dontkillmyapps** site
## Actual Behavior

We are at same location but still after some time we are getting records even distance filter is 200meters
<img width="387" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/96418892/b6940318-8dc7-4f52-88b9-093f103d50f1">

We travelled more than 5 to 10km but still we got few records for distance filter 200meters [ even app is in foreground]
<img width="380" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/96418892/5557f729-9731-4e31-8d70-9d0a0c4bdfdb">

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You omitted some items from the issue template:

>Plugin version:
>Platform: iOS or Android
>OS version:
>Device manufacturer / model:

**Comment by Venkatech** [comment]
Updated

**Comment by Venkatech** [comment]
@christocracy  Could you please look into the issue once
