### ISSUE TITLE
It does not get the position clearly and therefore the polyline does not draw smooth lines.

### ISSUE THREAD

**Issue by theCoderrrr** [transistorsoft/react-native-background-geolocation#2088]
The tracking process works successfully, but when it comes to displaying it, it does not work properly, the lines constantly pass over the buildings, in short, they are distorted. 
## Your Environment
* Plugin version: 4.16.3
* Platform: android 
* OS version: 12.0.3
* Device manufacturer / model: xiaomi redmi 9
* React Native version (`react-native -v`): 0.74.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 7,
      stopTimeout: 1,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      method: 'POST',
      url: 'https://api.tesdt.com/add-post',
      batchSync: false,
      autoSync: true,
      maxBatchSize: 50,
      params: {
        foo: 'bar'
      },
    }, async (state) => {
```

## Expected Behavior
I want it to get the location clearly and draw the lines properly.

## Actual Behavior
![WhatsApp Görsel 2024-07-12 saat 15 56 01_27181f79](https://github.com/user-attachments/assets/b78fa277-f711-4162-9b12-e9a1038a56db)

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
It’s up to you to filter as-desired.  Observe your location.coords.accuracy.

A location is not a dimensionless point in space — it’s a circle of radius `accuracy`.  Outdoors, radius is typically ~5 meters.  Indoors, ~40-100 meters.  If you’re not satisfied with a location’s accuracy, don’t add it to your map.

**Comment by christocracy** [comment]
That translucent, large blue circle you see around your location on a Map app is a representation of the `accuracy`:

![IMG_1655](https://github.com/user-attachments/assets/9cad1e87-c2b5-4ba5-88a9-8b64c8d3b6ef)

![IMG_1658](https://github.com/user-attachments/assets/397c09a9-a716-4b75-934d-f5a701feb5f3)

**Comment by theCoderrrr** [comment]
I understand what you mean, but how can I solve this problem? Is there a way to avoid deviations? 
      stationaryRadius: 50,
 I added this. Will this be a solution?

**Comment by christocracy** [comment]
I say again:

> It’s up to you to filter as-desired. Observe your location.coords.accuracy.

> If you’re not satisfied with a location’s accuracy, don’t add it to your map.

The plug-in does *not* do any kind of filtering.  stationaryRadius has nothing to do with filtering locations.

**Comment by christocracy** [comment]
> stationaryRadius: 5,

The effective minimum stationaryRadius is 200.  Setting it less than that is pointless.

**Comment by theCoderrrr** [comment]
So, I'm asking if there is a solution to this. There is a haversine formula, but it doesn't work.

**Comment by christocracy** [comment]
> So, I'm asking if there is a solution to this

the solution is in your hands.  “If you’re not satisfied with a location’s accuracy, don’t add it to your map.”

**Comment by theCoderrrr** [comment]
The location is correct but it is not on the road, for example it is on the house, it should actually be on the road

**Comment by christocracy** [comment]
What is the accuracy?  The plug-in is only the mailman, delivering locations to you exactly as provided by the native location api.

**Comment by theCoderrrr** [comment]
Then my phone gets the wrong location

**Comment by christocracy** [comment]
**again, I ask:** *What is the accuracy?*

**Comment by theCoderrrr** [comment]
It gets clear in some locations and gets confused in others. I have stated the ratio in the code above.

**Comment by christocracy** [comment]
I don’t think you understand what location accuracy is.  You have **NOT** shown me any information about the location.coords.accuracy of a problematic location.  Every location has an `location.coords.accuracy`

**Comment by theCoderrrr** [comment]
Sorry, I just remembered that it was returning a float type value. I can solve my problem with this.

**Comment by christocracy** [comment]
> Sorry, I just remembered

6 times in this issue, I told you about location.coords.accuracy.

**Comment by theCoderrrr** [comment]
I just tested your application and it works exactly as I want. I don't know why because the application remains open, but it works exactly as I want.

**Comment by theCoderrrr** [comment]
> I just tested your application and it works exactly as I want. I don't know why because the application remains open, but it works exactly as I want.

But when the application is open and closed, the service stops in your application.
