### ISSUE TITLE
New Feature:  HTTP JSON Templates

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/react-native-background-geolocation#209]
After three tries at this over the past year, you can *finally* define your own HTTP JSON schema for the plugin's HTTP requests, eg:

```javascript
locationTemplate: '{"lat":<%= latitude %>, "lng":<%= longitude %>, "event":"<%= event %>"}'
```

This feature is super new and the tag-API is likely to change as I get more feedback.  There could be some simple template-logic available in the future.

**Comment by dasmikko** [comment]
Would it possible to pass extra data to the template like 'apikey' ?

**Comment by christocracy** [comment]
Yes, they're automatically merged onto the rendered template:

```
bgGeo.configure({
  url: 'http://my_url',
  httpRootProperty: 'data',
  params: {
    myParams: {foo: 'bar'}
  },
  locationTemplate: '{ "lat":<%= latitude %>, "lng":<%= longitude %> }',
  extras: {
    "location_extra_foo": "extra location data"
  }
});
```
```
POST /my_url
{
  "data": {
    "lat": 45.5192657,
    "lng": -73.6169116,
    "location_extra_foo": "extra location data"
  },
  "myParams": {
    "foo": "bar"
  }
}
```

**Comment by dasmikko** [comment]
Ahh cool!

Would this setup be possible too?

```
POST /myurl
{
    "contract": "x",
    "username": "x",
    "position": {"lat": "x", "lng": "x"}
}
```

basically, without the root property.

**Comment by christocracy** [comment]
Yes, with [`"httpRootProperty":"."`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/http.md#httprootproperty-); `"."` as in `pwd` (present working directory).

```javascript
bgGeo.configure({
  url: 'http://my_url',
  httpRootProperty: '.',
  locationTemplate: '{ "position":{"lat":<%= latitude %>, "lng":<%= longitude %>} }',
  extras: {
    "contract": "x",
    "username": "x"
  }
});
```

**Comment by sobanarshad85** [comment]
{
    "latitude":55.71364,
    "longitude":12.535033
}
My server is accepting this way,

<img width="1266" alt="Screenshot 2020-10-05 at 12 26 24 PM" src="https://user-images.githubusercontent.com/22500153/95051039-05985680-0706-11eb-8f35-b394ad9c3fdb.png">

I have updated locationTemplate as

**Comment by sobanarshad85** [comment]
@christocracy can you please look into it?

**Comment by sobanarshad85** [comment]
@dasmikko was your issue resolved?

**Comment by dasmikko** [comment]
> @dasmikko was your issue resolved?

Oh damn, i've completely forgotten about this. I don't work at the company where i had this issue, so I can't say sadly.

**Comment by christocracy** [comment]
>But still its not working.

Define "not working".
