### ISSUE TITLE
Manually request motion permissions

### ISSUE THREAD

**Issue by sirusbaladi** [transistorsoft/react-native-background-geolocation#2098]
Hi, 

I'm aware that there's a method to manually trigger location permissions, is there a similar way to trigger the permission for the motion sensors?

The expo library to do so seems to not work and I like to request the permission during user onboarding one by one. 

thank you

**Comment by sirusbaladi** [comment]
bump

**Comment by sanduluca** [comment]
I guess you can use https://github.com/zoontek/react-native-permissions and ask for 
`PERMISSIONS.IOS.MOTION`
`PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION`

**Comment by MufeedaFi** [comment]
Yes, we can manually request using https://github.com/zoontek/react-native-permissions but is there a way to disable the default pop-up for "Motion&Fitness" permission within package?

**Comment by christocracy** [comment]
>is there a way to disable the default pop-up for "Motion&Fitness" permission within package?

do you understand the consequences of the plug-in not having motion permission?  They are not minor.

**Comment by christocracy** [comment]
See API docs `Config.disableMotionActivityUpdates`.  Set it to false.  Once you have Motion Permission, set it to `true` using `.setConfig`.

**Comment by MufeedaFi** [comment]
> See API docs `Config.disableMotionActivityUpdates`. Set it to false. Once you have Motion Permission, set it to `true` using `.setConfig`.

Hey, don't really understand.

My requirement is that, the "Motion and fitness" permission should only be asked only when user clicks a button "Enable permission" and it should NOT be asked implicitly so as I use the package. And the way to disable the one from package is to set `disableMotionActivityUpdates: true.`
And then I can request that permission manually using react-native-permissions as required on the button click. 

So, my question is, will this approach has any consequences of the plug-in not having motion permission?

**Comment by christocracy** [comment]
>will this approach has any consequences of the plug-in not having motion permission?

no.  The plugin doesn't care *how* permission is achieved.  Permissions are granted to **your app**.

**Comment by MufeedaFi** [comment]
> > will this approach has any consequences of the plug-in not having motion permission?
> 
> no. The plugin doesn't care _how_ permission is achieved. Permissions are granted to **your app**.

Ok, so this approach is fine I think. Thank you!

**Comment by mikehardy** [comment]
https://github.com/zoontek/react-native-permissions?tab=readme-ov-file#ios

> By default, no permissions are available

(followed by *lots* of detailed setup instructions - I'm guessing something is missed)
