### ISSUE TITLE
getLocations type error

### ISSUE THREAD

**Issue by emoreno-94** [transistorsoft/react-native-background-geolocation#2099]
This is a eslint problem, for this reason I don't provide more information about my environment 

## Your Environment
* Plugin version: 4.16.5
* Platform: -
* OS version: -
* Device manufacturer / model: -
* React Native version (`react-native -v`): 0.73.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
-
```

## Expected Behavior
Assign Location type correctly to mi variable when I use `await BackgroundGeolocation.getLocations()`

## Actual Behavior
I get a type error

## Steps to Reproduce

1. Assign type to `await BackgroundGeolocation.getLocations()`
2. This show this error 
<img width="961" alt="image" src="https://github.com/user-attachments/assets/c22a6d6d-3b87-4223-8603-b31fd70cfca9">

3. The app comple, and works, this is only a eslint problem
4.

## Context

```
import BackgroundGeolocation, { Config, Location as BGLocation } from 'react-native-background-geolocation';

...
const someFun = async () => {
  const coords: BGLocation[] = await BackgroundGeolocation.getLocations();
}
...
```

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Type 'Object[]' is not assignable to type 'Location[]'.
  The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
    Type 'Object' is missing the following properties from type 'Location': timestamp, age, odometer, is_moving, and 4 more.t
```

</details>

**Comment by christocracy** [comment]
The records from .getLocations cannot be coerced into a `Location` type since there’s no guarantee of their nature due to Config.locationTemplate.
