### ISSUE TITLE
Locations recorded correctly on device, but HTTP POSTs are not reliably firing.

### ISSUE THREAD

**Issue by rbaron** [transistorsoft/react-native-background-geolocation#210]
## Your Environment
* Plugin version: 2.4.3
* Platform: iOS
* OS version: 10.2.1
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 0.41.2
* Plugin config: 

```
{
      desiredAccuracy: 0,
      stationaryRadius: 25,
      distanceFilter: 10,
      stopTimeout: 10,
      debug: false,
      stopOnTerminate: false,
      startOnBoot: true,
      url: url,
      autoSync: true,
      batchSync: true,
      headers: {
        'Authorization': `jwt ${accessToken}`,
      }
}
```

## Expected Behavior
I expect locations to be HTTP POSTed on a best-effort fashion, given the documentation for `autoSync`: "If you've enabeld HTTP feature by configuring an #url, the plugin will attempt to upload each location to your server as it is recorded."
 
## Actual Behavior
As soon as I start the plugin and go for a drive, a few locations are POSTed (both single locations and in batch). After a couple of hours, locations _are_ recorded on my device, but no HTTP requests are issued. I set up a location counter on my app, using `.getCount()`, so I can tell they are being recorded -- they amount to ~400 a day. If I stop/start the plugin, they're immediately successfully POSTed, and they look perfect on the map.

## Steps to Reproduce
1. Build the app on the device with the aforementioned config;
2. Walk/drive around the city for a whole day;
3. Check that locations are recorded locally but no more HTTP requests are made.

## Context
I'd like to set up the plugin so I can keep tracking locations in the background and POSTing locations to the server on a best-effort fashion at every new location that is saved locally.

**Comment by christocracy** [comment]
The plugin is **very** verbose with persistence and http.  Are you monitoring the logs?

```
<+37.74114269,-122.40754282> +/- 5.00m (speed 23.74 mps / course 15.12) @ 2/22/17, 6:00:09 PM GMT-05:00

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: 0.0
╚═══════════════════════════════════════════════════════════
- Median location accuracy: 5.0
🔵-[Settings incrementOdometer:] 329130.6
✅ INSERT: 3B475DF0-8180-4514-BDA1-17005A312924

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush] 
╚═══════════════════════════════════════════════════════════
✅ LOCKED: 3B475DF0-8180-4514-BDA1-17005A312924
🔵-[TSHttpService doPost:] HTTP Response: 200
✅ DESTROY: 3B475DF0-8180-4514-BDA1-17005A312924

```

**Comment by rbaron** [comment]
Hi @christocracy. Thanks for the quick answer. Logs are a little tricky to get since the problem only happens after running and on a real device for a long time. Both behavior and logs look good when I'm debugging on my computer. I will try and collect better logs from my device and post relevant parts here.

Just to make it clear, it is expected for the POST to work like I expected with my config, right? in other words, I wouldn't necessarily have to rely on something like `.watchPosition()`, correct?

**Comment by christocracy** [comment]
Not tricky at all.  The plugin logs 3 days worth of logs to its database.

[:small_blue_diamond `getLog`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#getlogcallbackfn)

**Comment by christocracy** [comment]
You do **not** need to use `#watchPosition`.  That method is just an added convenience, designed for use while app is in the foreground.

I'm pretty sure the logs will show your server isn't returning **`200`**.

**Comment by rbaron** [comment]
Thanks @christocracy. I've been looking through the logs and I think I extracted the relevant parts.

1. Initial service `start()` call (http://pastebin.com/HhWFkdia)

It seems like it POSTs only once (line 150). And then it starts showing the following pattern over and over (with no traces of HTTP in between):

```
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: 10.0
╚\342\225═══════════════════════════════════════════════════════════
 
2017-02-22 09:15:45.644 - Updated distanceFilter, new: 30.000000, old: 10.000000
 
2017-02-22 09:15:45.670 - Median location accuracy: 65.0
 
2017-02-22 09:15:45.670 🔵-[Settings incrementOdometer:] 614.7
 
2017-02-22 09:15:45.700 ✅ INSERT: B6E80309-63B8-4ACF-9BF2-CDE17034A40C
 
2017-02-22 09:15:48.498
<-23.56449190,-46.64124965> +/- 30.00m (speed 9.91 mps / course 350.51) @ 2/22/17, 09:15:48 Brasilia Standard Time
 
2017-02-22 09:15:48.498
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: 30.0
╚═══════════════════════════════════════════════
```

It goes on for a long time.

2. Second time I `stop()` and `start()` the service (http://pastebin.com/LV4yJREc):

It recognizes it has 459 locations saved locally and then proceed to batch POST them (line 88):

```
2017-02-22 19:35:36.723 🔵-[TSHttpService postBatch:] 459 records

...


2017-02-22 19:35:42.126
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush]
╚═══════════════════════════════════════════════════════════
 
2017-02-22 19:35:42.126 ⚠️-[TSHttpService flush] Busy with previous request
 
2017-02-22 19:35:42.316 🔵-[TSHttpService doPost:] HTTP Response: 200
 
2017-02-22 19:35:42.316 🔵-[LocationDAO destroyAll:] DESTROY: 64631E76-4A51-44E6-9952-653964D2E868
 
2017-02-22 19:35:42.316 🔵-[LocationDAO destroyAll:] DESTROY: 75A7D29A-2417-498F-942C-E078EDB9F312
 
2017-02-22 19:35:42.316 🔵-[LocationDAO destroyAll:] DESTROY: 49AC5A0B-A054-48FB-98C1-D9A3AF2CE0C2
 
2017-02-22 19:35:42.317 🔵-[LocationDAO destroyAll:] DESTROY: B6E80309-63B8-4ACF-9BF2-CDE17034A40C
 
2017-02-22 19:35:42.317 🔵-[LocationDAO destroyAll:] DESTROY: E54E555D-AFE1-49CC-841D-CE06B6D2B9FC
 
2017-02-22 19:35:42.317 🔵-[LocationDAO destroyAll:] DESTROY: 5004EEE5-0FB7-4BA9-A13C-567E352857E3

...
```

Let me know if I can offer more info -- pastebin won't let me post the whole log. Thanks once again for your attention.

**Comment by christocracy** [comment]
Are you *sure* your Javascript is calling the `#configure` method *every time* the app boots?

iOS can terminate your app when under memory pressure and reboot it again due to stationary-exit or background-fetch.

You need to be prepared for the OS booting your in addition to the *user* booting your app.

**Comment by rbaron** [comment]
@christocracy, since the service _did keep_ running at all times, I never thought that running `.configure()` was mandatory. I will run this test today. Thanks.

**Comment by christocracy** [comment]
The plugin has some legacy behaviour which needs to be addressed.  In the old days, you used to provide your `locationCallback`, `locationFailure` callbacks to `#configure`, so it was *necessary* to call `#configure` in order to register your `location` event-listener.

```javascript
bgGeo.configure(function(location) {
  console.log("- Location: ", location);
}, function(errorCode) {
  console.log("- Location error: ', errorCode);
});
```

Later, when I expanded the Event API, it became:

```javascript
bgGeo.on('location', function(location) {
  console.log('- Location: ', location);
}, function(errorCode) {
  console.log('- Location error: ', errorCode);
});

bgGeo.configure(function(state) {
  console.log('- Configure success, state: ', state);
});
```

So, when your app boots, the plugin loads all its default values.  If you don't call `#configure`, the plugin is going to continue to run in its default state, eg:
```
{
  url: null,
  autoSync: false,
  stopOnTerminate: true,
  startOnBoot: false,
  .
  .
  .
}
```

The plugin *does* persist the `config` you provide to `#configure`.  I'm going to have a look at this "initial state" behaviour", but for now, ensure you *always* call configure when your app boots.

**Comment by rbaron** [comment]
Hi @christocracy. It's been a little over 2 days and it seems to be working as I expected now. Calling `configure()` every time the app boots works. Thank you!

**Comment by christocracy** [comment]
The plugin doesn't know when your application has booted.  `#configure`, in addition to providing your config options, is a signal to the plugin that your app is booted and ready to start listening to events.

If this weren't the case, the plugin would start tracking and firing events before you'd even registered listeners to it.
