### ISSUE TITLE
Problem in handling permissions using onProviderChange. Two scenarios I am facing the issue

### ISSUE THREAD

**Issue by Venkatech** [transistorsoft/react-native-background-geolocation#2100]
I was able to handle permissions using onProviderChange. Only 2 scenarios I am facing issue

1. when user denied permission 2 times in android, the permission denied permanently and unable to show dialog using the library. Working fine in iOS
2. When we show Background location permission dialog when user clicked cancel there is no way we can handle that scenario in both android and ios
<img width="435" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/96418892/a14f4ea1-db17-495b-8a10-abef82a8db8a">

_Originally posted by @Venkatech in https://github.com/transistorsoft/react-native-background-geolocation/issues/2037#issuecomment-2212966808_

**Comment by HoseinHaqiqian** [comment]
For the second one, you can check again if permission isGranted or not, if not granted, then user clicked on cancel or dismissed the process anyway.
