### ISSUE TITLE
`- BackgroundGeolocation is configured and ready` never logs true in the example code

### ISSUE THREAD

**Issue by alfredvaa** [transistorsoft/react-native-background-geolocation#2101]
I would like a clarification on the purpose of the ready.then() method. In the example code it looks like it at some point should log that state.enabled changes to true but that never happens. It logs false once when the app starts and that is it. To actually start getting locations I need to click the button that manually sets enabled to true. Is this how it is supposed to work? What is the purpose of `setEnabled(state.enabled);` if not to execute once the library is ready? I would like it to activate automatically as soon as it is ready.

## Your Environment
* Plugin version: 4.16.5
* Platform: iOS
* OS version: 17.5
* Device manufacturer / model: Iphone 15 Pro
* React Native version (`react-native -v`):0.74.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 1,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
```

## Expected Behavior

It should activate when ready

## Actual Behavior

It did not

## Steps to Reproduce

1. Just run the example code

## Context

Run the example code and activate without the button

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plug-in is like an electronic device, a stereo receiver, for example.

- .ready(config) is like plugging in the AC cord.  You do it once each time your app is launched.
-  .start() / .stop() is like the [POWER] button, toggling State.enabled.  The plug-in persists State.enabled throughout app launches.

**Comment by christocracy** [comment]
In the example app, the toggle button on top toolbar is the “POWER] button.

**Comment by alfredvaa** [comment]
Thanks, makes sense 👍 

I experience a slight lag between the two first locations that is logged and the following ones. There is two locations logged instantly when I start up, and then it takes a few seconds before it continous to output one location per second. Why is that? Is there some event that I can listen to to know when it starts for real? Or is there an issue with my setup perhaps?

**Comment by christocracy** [comment]
> experience a slight lag between the two first locations

The plug-in doesn’t accept only the first location when turned ON, it gathers multiple samples in a hunt for the most accurate location as the GPS chip connects to the satellites it sees in space.

see api docs Location.sample.

also see the wiki “Philosophy of Operation”.

**Comment by christocracy** [comment]
It’s the same thing that happens in a typical Maps app when you see your location progressively improving, witnessed by the translucent blue circle around your current location, which represents the location accuracy, growing / shrinking in radius.

**Comment by alfredvaa** [comment]
Right, thanks for the quick response 👍

**Comment by christocracy** [comment]
> Is there some event that I can listen to

There are a total of 13 events you can subscribe to.  It doesn’t take much effort to read the description of each in the API docs, which people tell me are quite excellent and comprehensive after 10 years of progressively writing them.
