### ISSUE TITLE
Can not debug on android 

### ISSUE THREAD

**Issue by Bob-JZhao** [transistorsoft/react-native-background-geolocation#2103]
## Your Environment
* Plugin version:  4.14.0
* Platform:  Android
* OS version: 13
* Device manufacturer / model: Pixel 3a, api 34
* React Native version (`react-native -v`): 0.72.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

it should work under debug model without LICENCE_KEY
## Actual Behavior

Got error Invalid license key: YOUR_LICENCE_KEY_HERE, and can not start the app at all
## Steps to Reproduce

1. Generate a debug apk
2. Install on emulator and run the app
3. Get error because of the LICENCE_KEY and can not even get app running

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See wiki “Debugging” and learn to observe your logs.

**Comment by christocracy** [comment]
See the [Android section](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging#android) of Wiki "Debugging".  Learn how to observe your native device logs with `adb logcat`.

**Comment by Bob-JZhao** [comment]
Hi @christocracy , I got this error every time when start the app,.Can you please help? Thanks
![WX20240803-104725](https://github.com/user-attachments/assets/f1873d0a-2d67-4a87-afbf-7e1dfb88e67d)

**Comment by christocracy** [comment]
It’s not an error, it’s a warning message.  Did you read exactly what it says?

**Comment by Bob-JZhao** [comment]
> It’s not an error, it’s a warning message. Did you read exactly what it says?

@christocracy well, here is all errors I have, just don't understand what's wrong. 
![WX20240803-134205@2x](https://github.com/user-attachments/assets/b5b0a62a-ca48-4f52-abca-fe9815a62499)

**Comment by christocracy** [comment]
Your error is from react-native and has nothing at all to do with the plug-in.

**Comment by Bob-JZhao** [comment]
OK thanks I'll check
