### ISSUE TITLE
Background location didn't respond if I stops for certain minutes and then moving again 

### ISSUE THREAD

**Issue by aniappgambit** [transistorsoft/react-native-background-geolocation#2107]
## Your Environment
* Plugin version:4.16.3
* Platform: Android
* OS version: Android 12
* Device manufacturer / model:samsung SM-M215F 
* React Native version (`react-native -v`):0.66.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      // Activity Recognition
      stopTimeout: 10,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url:{API_URL},
      method: 'POST',
      foregroundService:true,
      extras: data,
      autoSync: true,
      autoSyncThreshold: 2,
      batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      headers: headerWithCookie,
      // params: data
      // params: {               // <-- Optional HTTP params
      //   "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      // }
    }
```

## Expected Behavior

-  It should shows me a latlong whenever i am moving in background as well as on foreground as per the cofiguration
- Give consistency in data
## Actual Behavior

- It gives me an inconsistent lat long 
-  Some times it stops if I am still in between the route and then plugin took long time to awake again.
## Debug logs
[background-geolocation.2.log](https://github.com/user-attachments/files/16509944/background-geolocation.2.log)

</details>

**Comment by christocracy** [comment]
> plugin took long time to awake again.

Define “long time” in terms of *distance*.

**Comment by christocracy** [comment]
The plug-in uses a geofence around the last known position in addition to listening to the motion api to determine when the device is moving.

Both these APIs are managed by the OS — when the OS fires and event on one of those APIs, the plug-in acts.

there’s nothing the plug-in can do to make those APIs fire any quicker on some particular device in some particular environment.

I just travelled all around France for over two weeks with iPhone 15 Pro and Pixel 6 using the *Demo app* linked in the readme.

https://www.transistorsoft.com/lab/france

also see https://dontkillmyapp.com

**Comment by aniappgambit** [comment]
So, then what can i do in terms of setting in backgroundlocation config to decrease this geofence?

**Comment by dhavaln** [comment]
Hey Chris, I understand we will do more testing with other devices and confirm.
