### ISSUE TITLE
Discussion: Time-based Tracking and backgrounded app

### ISSUE THREAD

**Issue by sanduluca** [transistorsoft/react-native-background-geolocation#2109]
## Your Environment
* Plugin version: 4.16.4
* Platform: iOS and Android
* OS version: all
* Device manufacturer / model: all
* React Native version (`react-native -v`): 0.74.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
	heartbeatInterval: 60,
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
	preventSuspend: true,
	debug: false,
	foregroundService: true,
	enableTimestampMeta: true,
	backgroundPermissionRationale,
	disableLocationAuthorizationAlert: true,
	logMaxDays: 1,
	notification: {
		smallIcon: 'drawable/ic_notification',
		color: 'red',
		sticky: true,
	},
}
```

## Context

**How can we achieve a time based tracking on both platforms ?** 

I have read the Philosophy documentation and saw that you cant have that for iOS .

We were trying to achieve this using a JS setInterval, but later found out that serInterval is not running on Android when app is in background, but it is running in background on iOS. To synchronize the behavior, we used `react-native-background-timer` and now we have the timer running in background for both platforms. 

I have read the issues on this repo about the `react-native-background-timer` saying that its not working, watched the [video](https://youtu.be/q6UMmLMnLl8?t=659) on youtube about this. All of this are comments and info from 6 years ago. I wonder if something changed from back then ?

After we implemented the `react-native-background-timer` seemed that we solved the problem, but found out that on Android devices that are not plugged and have the screen off we dont have locations. I guess its because of [Android Doze mode](https://developer.android.com/training/monitoring-device-state/doze-standby). Now I'm searching for a solution on how can i get the user location when the app is in background with the screen off. To note that if the phone is plugged with screen off we see that the timer is running and we get the locations.

Also found this library that says that is working in background and solves some problems the `react-native-background-timer` has. https://www.npmjs.com/package/react-native-background-timer-android

<details><summary>Code example we have in  our app</summary>

```ts
import BackgroundTimer from "react-native-background-timer";
import BackgroundGeolocation, {
  Location,
  Subscription,
  BackgroundGeolocationConfig,
} from "react-native-background-geolocation";

const FETCH_LOCATION_OPTIONS = {
  desiredAccuracy: 5,
  samples: 1,
};

const BACKGROUND_GEOLOCATION_CONFIG = (
	backgroundPermissionRationale?: Record<string, string>,
): BackgroundGeolocationConfig => ({
	heartbeatInterval: 60,
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
	preventSuspend: true,
	debug: false,
	foregroundService: true,
	enableTimestampMeta: true,
	backgroundPermissionRationale,
	disableLocationAuthorizationAlert: true,
	logMaxDays: 1,
	notification: {
		smallIcon: 'drawable/ic_notification',
		color: 'red',
		sticky: true,
	},
});

const isAuthenticated = useAppSelector((state) => state.auth.isAuthenticated);
const user = useAppSelector((state) => state.account.user);
const isUserActive = isAuthenticated && user.active;

useEffect(() => {
  if (!isAuthenticated) return;

  // Warning: You must call .ready(confg) once and only once, each time your app is launched. (for details, see docs)
  if (!ready.current) {
    const rationale = {};

    BackgroundGeolocation.ready(BACKGROUND_GEOLOCATION_CONFIG(rationale))
      .then(() => {
        ready.current = true;
      })
      .catch(() => {});
  }
}, [isAuthenticated]);



useEffect(() => {
  if (!isUserActive) return;
  function handleLocation(location: Location) {
    // send to server
  }

  const locationSubscription = BackgroundGeolocation.onLocation(handleLocation);
  const heartSubscribtion = BackgroundGeolocation.onHeartbeat(() => {
    console.log("Heartbeat");
    BackgroundGeolocation.getCurrentPosition(FETCH_LOCATION_OPTIONS);
  });

  const interval = BackgroundTimer.setInterval(async () => {
    try {
      console.log("get current position via timer!");
      await BackgroundGeolocation.getCurrentPosition(FETCH_LOCATION_OPTIONS);
    } catch (e) {
      console.log("timer sample fetch failed!");
    }
  }, 15000);

  BackgroundGeolocation.start()
    .then(() => {
      console.log("Started geolocation");
    })
    .catch((e) => console.log("Error starting", e));

  return () => {
    interval && BackgroundTimer.clearInterval(interval);
    locationSubscription?.remove();
    heartSubscribtion?.remove();
    BackgroundGeolocation.stop();
  };
}, [isUserActive]);

```

</details>

Refferences:
https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation
https://github.com/transistorsoft/react-native-background-geolocation/issues/311
https://github.com/ocetnik/react-native-background-timer
https://dontkillmyapp.com/

**Comment by christocracy** [comment]
For time-based location updates, implement background-fetch, already included as a dependency.

the background geolocation plugin is not concerned with time-based location updates.  It tracks location according to Config.distanceFilter when the device is detected to be moving.
