### ISSUE TITLE
Access state in onLocation and Firebase

### ISSUE THREAD

**Issue by MichaelKonnerup** [transistorsoft/react-native-background-geolocation#211]
I would like to access either the components state or redux state. When i try to reach the state in the onLocation function i get an "undefined". I am using Firebase and to my believe the HTTP function doesn't support that?, so since I dont have "autoSyncThreshold" available I need to use the state instead to buffer location. Isn't it possible to use the state and if not is there a working around so onLocation only is fired e.g. each 30 seconds with an array of locations.

Thx in advance

## Your Environment
* Plugin version: 2.6.0
* Platform: iOS 
* OS version: 10.1
* Device manufacturer / model: iPhone 7 (sim)
* React Native version (`react-native -v`): 0.41.2
* Plugin config

desiredAccuracy: 0
stationaryRadius: 25
distanceFilter: 10

## Expected Behavior
I want to print the state in the log

## Actual Behavior
Get an undefined is not an object in the simulator

**Comment by christocracy** [comment]
The plugin doesn't maintain "state" in the traditional React manner.  It's not designed to work in views.  

See the docs for #getState method

**Comment by MichaelKonnerup** [comment]
Yeah ok. To my understanding do getState only return the plugins state. Is there any workaround to get buffered locations or is the only option to use Firebase each time onLocation is called? Any other solution is also very appreciated.

**Comment by christocracy** [comment]
Yes, I have many customers using Firebase.  The plugin supports a configurable HTTP [`method`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#config-string-method-post), precisely at the request of Firebase users (who use, `PUT` or `OPTIONS`, I believe).

It sounds like you haven't had much of a look [at the docs](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#small_blue_diamond-http--persistence-methods)

**Comment by MichaelKonnerup** [comment]
Hi again and thanks for the fast responses. Solved the issue by using HTTP. 
The thing is that my "token" expires after 1 hour and I need the plugin to run for 2 hours or more.
Do you suggest scheduling the timeframe and then using heartbeat to reconfigure the HTTP settings with a new token?

**Comment by christocracy** [comment]
That would be a problem on Android if the user terminates the app since
only the plugin's native background service is running.  You have no
Javascript app alive to even receive events / request new tokens.

**Comment by MichaelKonnerup** [comment]
Yeah I saw that in another post. It is an issue since I also need to build my application for Android. Do I have any other option.

**Comment by christocracy** [comment]
You have no option involving your own application code executing an HTTP request in that case since your code is not running.

What is the `#url` that needs to be hit and what is the nature of the response containing the new token?

**Comment by MichaelKonnerup** [comment]
https://securetoken.googleapis.com/v1/token?key=myApiKey
x-www-form-urlencoded
refresh_token=**myRefreshToken**?grant_type=refresh_token

Response in json

{
  "access_token": "myNewToken",
  "expires_in": "3600",
  "token_type": "Bearer",
  "refresh_token": "theRefreshToken",
  "id_token": "idToken",
  "user_id": "id",
  "project_id": "projectId"
}

**Comment by christocracy** [comment]
I implemented [this](https://github.com/transistorsoft/cordova-background-geolocation/issues/1202) with your use-case in mind.

**Comment by MichaelKonnerup** [comment]
hmm. Get an 404 on the link

**Comment by christocracy** [comment]
Ah, yes.  It's only available in the [Premium Version](http://www.transistorsoft.com/shop/products/react-native-background-geolocation) currently.   The following will mention "Cordova" and "Cordova Plugin" but it's not important.  The same idea applies to React Native.  React Native won't require a 3rd-party plugin.  You'll just add the required block to your `AndroidManifest.xml` and add a new Java file `EventReceiver.java` as follows:

The Android plugin now broadcasts all its events to the Android [`BroadcastReceiver`](https://developer.android.com/guide/components/broadcasts.html) mechanism.

**What does this mean?**

It means you can implement your own custom Android `BroadcastReceiver` to receive events from `BackgroundGeolocation`, even when your foreground Javascript app **has been terminated**.

However, these events are received in the native Android environment -- **not** in your Javascript app.  There is no Javascript in this context -- only pure native Java.  If you want to implement handlers for these events, you're going to have to write some Java code.

**How do I implement a "BroadcastReceiver"?**

I've created a new Cordova plugin [`cordova-background-geolocation-broadcast-receiver`](https://github.com/transistorsoft/cordova-background-geolocation-broadcast-receiver).  This plugin will add a Java file [EventReceiver.java](https://github.com/transistorsoft/cordova-background-geolocation-broadcast-receiver/blob/master/src/android/EventReceiver.java) and add the necessary wiring in your [`AndroidManifest.xml`](https://github.com/transistorsoft/cordova-background-geolocation-broadcast-receiver/blob/master/plugin.xml#L22) to hook it up and receive `BackgroundGeolocation` events.

:warning: The `cordova-background-geolocation-broadcast-receiver` plugin is meant for you to **fork** and implement your own custom functionality.  The existing implementation of [EventReceiver.java](https://github.com/transistorsoft/cordova-background-geolocation-broadcast-receiver/blob/master/src/android/EventReceiver.java) is just a "stub" meant for you to **override**.  You should treat your fork as **private application code** not shared with the public.

**I still don't get it**

If you've configured `BackgroundGeolocation` for `{stopOnTerminate: false}`, and the user terminates your app, your Javascript code is no longer running.  Only the plugin's native background-service is running.  If you need to react to some event in this state, you've had no possible way to do that, other than using the [`forceReloadOnXXX`](https://github.com/transistorsoft/cordova-background-geolocation/tree/master/docs#config-boolean-forcereloadon-false) config options, to reboot your Javascript app.

With this new "Broadcast" mechanism, you can subscribe to any of the following events from `BackgroundGeolocation`:
```xml
<action android:name="com.transistorsoft.locationmanager.event.BOOT" />
<action android:name="com.transistorsoft.locationmanager.event.TERMINATE" />
<action android:name="com.transistorsoft.locationmanager.event.HEARTBEAT" />
<action android:name="com.transistorsoft.locationmanager.event.MOTIONCHANGE" />
<action android:name="com.transistorsoft.locationmanager.event.LOCATION" />
<action android:name="com.transistorsoft.locationmanager.event.GEOFENCE" />
<action android:name="com.transistorsoft.locationmanager.event.HTTP" />
<action android:name="com.transistorsoft.locationmanager.event.SCHEDULE" />
<action android:name="com.transistorsoft.locationmanager.event.ACTIVITYCHANGE" />
<action android:name="com.transistorsoft.locationmanager.event.PROVIDERCHANGE" />
<action android:name="com.transistorsoft.locationmanager.event.GEOFENCESCHANGE" />
```

The event-data provided to these events is identical to those provided to the Javascript events [as documented](https://github.com/transistorsoft/cordova-background-geolocation/tree/master/docs#zap-events).  The only difference is you're writing code in the Java environment, rather than Javascript.

Perhaps you're in a situation where your server end-point requires renewing an authentication token every hour.  How do you manage that when your Javascript app is no longer running?  The solution is to implement your own `BroadcastReceiver` and request a new auth-token by executing  an HTTP request to your server using Android HTTP API.  In this situation, you might implement a custom [`onHttp`](https://github.com/transistorsoft/cordova-background-geolocation-broadcast-receiver/blob/master/src/android/EventReceiver.java#L140) handler to check for HTTP status `401 UNAUTHORIZED` and request a new token at that time.

```java
public class EventReceiver extends BroadcastReceiver {
  private void onHttp(Context context, Intent intent) {
    int status = intent.getIntExtra("status", -1);
    if (status == 401) {
      // Execute an HTTP request to request new auth token
      String myNewToken = getNewTokenFromServer();
      .
      .
      .
      // Re-configure BackgroundGeolocation
      JSONObject headers = new JSONObject();
      headers.put("Authentication", "Bearer " + myNewToken);

      JSONObject config = new JSONObject();
      config.put("headers", headers);
      
      // Same idea as the Javascript API
      adapter.setConfig(config);
    }
  }
}
```

Even if you don't know anything about Java programming, it's not that difficult to perform a simple task such as this.  It would probably only require about 10-15 lines of Java code.  If you're **really lost**, you can pay me an hour or two to do it for you.

**Comment by MichaelKonnerup** [comment]
Ok. Thank you for the detailed answer. I am quite familiar with Java so I should hopefully figure that out. 

Just so I understand you correctly; by implementing this to Android by writing Java code, it makes it possible to fetch new tokens when the app is terminated?

Is it possible to implement something like this on iOS? As I understand the heartbeat doesn't run on iOS when the app is terminated.

**Comment by christocracy** [comment]
This is standard Android [Broadcast Receiver](https://developer.android.com/guide/components/broadcasts.html) mechanism.  Your custom broadcast-receiver will receive broadcasts as long as the plugin's background-service is alive to broadcast them.

iOS has no such mechanism, nor is it required, as iOS always boots your Javascript app.  It's completely up to you to manage your tokens on iOS as you see fit.  I would personally listen to the `http` event for `status === 301`

**Comment by MichaelKonnerup** [comment]
Ok. Ofcourse, should have thought of that earlier. I runned into another issue. If you want me to open another topic I can do that instead but the tracking seems to be a bit unstable. It works fine on the simulator, but I have tried this on the three different phones. Maybe it is my configuration. 

Anyway my config in "componentWillMount" is this:

     BackgroundGeolocation.configure({
            desiredAccuracy: 0,
            stationaryRadius: 25,
            distanceFilter: 10,
            stopTimeout: 5,
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false, 
            startOnBoot: true,    
            url: 'https://xxx.com/xxx.json',
            batchSync: false,  
            autoSync: true,     
            autoSyncThreshold: 20,

        }, function(state) {
            console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

            if (!state.enabled) {
                BackgroundGeolocation.start(function() {
                    console.log("- Start success");
                });
            }
        });


Cannot get the emailLog to work but this is from the log in Xcode:
The plugin should kick in from 09:25 - 09:35 (walking). The thing is that on my way back it kicked in after a 400-500 meter walk. Is this my config or some other issue?

**Your help is very appreciated**

'2017-03-23 09:11:53.811 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:11:58.313 ✅ BG time remaining: 34 | Total tasks: 1',
        '',
        '2017-03-23 09:12:23.304 🔵-[BackgroundTaskManager onPreventSuspendTimer:] Prevent-suspend timer fired!',
        '',
        '2017-03-23 09:12:23.308 🔵-[TSLocationManager endStartDetection] ',
        '',
        '2017-03-23 09:12:23.355 ✅ [BackgroundTaskManager stopBackgroundTask] 8',
        '',
        '2017-03-23 09:12:23.358 ℹ️+[LocationAuthorization run:] status: 3',
        '',
        '2017-03-23 09:12:23.358 ✅ [BackgroundTaskManager stopBackgroundTask] 8 OF (',
        ')',
        '',
        '2017-03-23 09:20:55.380 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager startMonitoringBackgroundFetch]_block_invoke Background fetch received',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:20:55.380 🔵-[TSLocationManager beginStartDetection] ',
        '',
        '2017-03-23 09:20:55.382 ✅ [BackgroundTaskManager createBackgroundTask]: 10',
        '',
        '2017-03-23 09:20:55.575 ⋯-[TSDBLogger db_save] Log committed',
        '',
        '2017-03-23 09:20:55.575 ⋯-[TSDBLogger db_delete] maxAge: 604800',
        '',
        '2017-03-23 09:20:55.775 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:21:00.451 ✅ BG time remaining: 34 | Total tasks: 1',
        '',
        '2017-03-23 09:21:24.981 ⋯-[TSDBLogger db_delete] maxAge: 604800',
        '',
        '2017-03-23 09:21:25.462 🔵-[BackgroundTaskManager onPreventSuspendTimer:] Prevent-suspend timer fired!',
        '',
        '2017-03-23 09:21:25.512 🔵-[TSLocationManager endStartDetection] ',
        '',
        '2017-03-23 09:21:25.513 ✅ [BackgroundTaskManager stopBackgroundTask] 10',
        '',
        '2017-03-23 09:21:25.524 ℹ️+[LocationAuthorization run:] status: 3',
        '',
        '2017-03-23 09:21:25.525 ✅ [BackgroundTaskManager stopBackgroundTask] 10 OF (',
        ')',
        '',
        '2017-03-23 09:44:18.167 🔵__21-[TSHttpService init]_block_invoke Network: Cellular | Flags: WR -t-----',
        '',
        '2017-03-23 09:44:18.240 🔵-[TSLocationManager setPace:] 1',
        '',
        '2017-03-23 09:44:18.270 ⋯-[TSDBLogger db_save] Log committed',
        '',
        '2017-03-23 09:44:18.271 ⋯-[TSDBLogger db_delete] maxAge: 604800',
        '',
        '2017-03-23 09:44:18.274 🎾-[TSLocationManager startUpdatingLocation] Location-services: ON',
        '',
        '2017-03-23 09:44:18.398 ℹ️+[LocationAuthorization run:] status: 3',
        '',
        '2017-03-23 09:44:18.421 ',
        '<+55.58608398,+12.97134568> +/- 165.00m (speed -1.00 mps / course -1.00) @ 23/03/2017 09.44.17 Centraleuropæisk normaltid',
        '',
        '2017-03-23 09:44:18.421 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: -1.0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:18.421 - Acquiring motion (0 / 4)',
        '',
        '2017-03-23 09:44:18.426 ',
        '<+55.58608398,+12.97134568> +/- 165.00m (speed -1.00 mps / course -1.00) @ 23/03/2017 09.44.18 Centraleuropæisk normaltid',
        '',
        '2017-03-23 09:44:18.426 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: -1.0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:18.426 - Acquiring motion (1 / 4)',
        '',
        '2017-03-23 09:44:18.429 ',
        '<+55.58088325,+12.97434580> +/- 65.00m (speed -1.00 mps / course -1.00) @ 23/03/2017 09.26.23 Centraleuropæisk normaltid',
        '',
        '2017-03-23 09:44:18.429 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: -1.0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:18.433 ',
        '<+55.58608398,+12.97134568> +/- 165.00m (speed -1.00 mps / course -1.00) @ 23/03/2017 09.44.18 Centraleuropæisk normaltid',
        '',
        '2017-03-23 09:44:18.433 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: -1.0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:18.433 - Acquiring motion (2 / 4)',
        '',
        '2017-03-23 09:44:18.434 ',
        '<+55.58608398,+12.97134568> +/- 165.00m (speed -1.00 mps / course -1.00) @ 23/03/2017 09.44.18 Centraleuropæisk normaltid',
        '',
        '2017-03-23 09:44:18.434 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: -1.0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:18.434 - Acquiring motion (3 / 4)',
        '',
        '2017-03-23 09:44:18.435 - Median location accuracy: 115.0',
        '',
        '2017-03-23 09:44:18.456 ',
        '<+55.58088325,+12.97434580> +/- 65.00m (speed -1.00 mps / course -1.00) @ 23/03/2017 09.26.23 Centraleuropæisk normaltid',
        '',
        '2017-03-23 09:44:18.456 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: 10.0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:18.471 ✅ INSERT: 5748096D-5522-4EFA-A609-E8EF7E82472C',
        '',
        '2017-03-23 09:44:18.471 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSHttpService flush] ',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:18.482 ✅ LOCKED: 5748096D-5522-4EFA-A609-E8EF7E82472C',
        '',
        '2017-03-23 09:44:19.567 🔵-[TSHttpService doPost:] HTTP Response: 200',
        '',
        '2017-03-23 09:44:19.587 ✅ DESTROY: 5748096D-5522-4EFA-A609-E8EF7E82472C',
        '',
        '2017-03-23 09:44:19.587 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSHttpService finish:] Success: 1',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:20.267 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:20.268 - Motion-trigger timer engaged: Stop-detection will trigger in 10 seconds...',
        '',
        '2017-03-23 09:44:24.545 ',
        '<+55.58608098,+12.97137093> +/- 165.00m (speed -1.00 mps / course -1.00) @ 23/03/2017 09.44.24 Centraleuropæisk normaltid',
        '',
        '2017-03-23 09:44:24.546 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | distanceFilter: 10.0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:24.546 - Median location accuracy: 165.0',
        '',
        '2017-03-23 09:44:24.569 ✅ INSERT: CE044C74-EA51-45BD-B33C-7B3A09517B9D',
        '',
        '2017-03-23 09:44:27.166 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:29.741 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:30.404 🔴-[TSLocationManager stopUpdatingLocation] ',
        '',
        '2017-03-23 09:44:30.539 ✅ [BackgroundTaskManager createBackgroundTask]: 12',
        '',
        '2017-03-23 09:44:35.352 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:35.353 ✅ BG time remaining: 176 | Total tasks: 1',
        '',
        '2017-03-23 09:44:48.985 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:52.159 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:53.113 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '',
        '2017-03-23 09:44:55.956 - Tasks: 1',
        '',
        '2017-03-23 09:44:55.956 🔵-[TSLocationManager onResume:] enabled? 1',
        '',
        '2017-03-23 09:44:55.960 ℹ️-[LocationDAO purge:] maxDaysToPersist: 1',
        '',
        '2017-03-23 09:44:55.995 ⋯-[TSDBLogger db_save] Log committed',
        '',
        '2017-03-23 09:44:57.825 ',
        '╔═══════════════════════════════════════════════════════════',
        '║ __51-[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0',
        '╚═══════════════════════════════════════════════════════════',
        '' ],

**Comment by christocracy** [comment]
["Headless JS" support coming soon.](https://github.com/transistorsoft/react-native-background-geolocation/issues/239)
