### ISSUE TITLE
Enter/exit geofence is not detected in trackingMode Geofences only (iOS)

### ISSUE THREAD

**Issue by jakub-oone** [transistorsoft/react-native-background-geolocation#2113]
Hello, 

I am using BGGeolocation demo app.
In **Geofences only** tracking mode on **iOS** - entering geofence won't even trigger in the foreground. 
Please see attachments. There is no green arrow on map.
It is working on Android, but not on iOS. What I have noticed is that "IS MOVING" parameter is always false in that geofence only mode. 
The configuration parameters are set to default values.

Please help me figure out what I'm missing that polygon geofence entry/exit was not detected in the BGGeolocation demo app?

We want to use geofence only mode in our SmartGuide app to save battery drain when app is on background.

Thank you.

Jakub
SmartGuide

<img width="1564" alt="Screenshot 2024-08-14 at 13 14 58" src="https://github.com/user-attachments/assets/67711040-9542-4ae8-bcb2-b7a5d06ebcf1">
https://tracker.transistorsoft.com/SmartGuide

![IMG_5078](https://github.com/user-attachments/assets/66b21919-94ae-4cfe-b393-0b6e19a537d3)

[background-geolocation.log.gz](https://github.com/user-attachments/files/16612283/background-geolocation.log.gz)

**Comment by christocracy** [comment]
The issue template is **required**, not optional:




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Buthrakaur** [comment]
Hello @christocracy , did you have a chance to look into this please? We'd like to use geofencing-only (`startGeofences`) in our app on background to save the battery as we don't need to get a precise location and just listen on geofence enter events (including smaller polygon geofences as supported by the paid add-on) but as @jakub-oone posted this works for us only on Android and not on iOS when we gave it a try in the demo app. Could you please provide instructions how to set the iOS config in the demo app to make this work?

**Comment by sirusbaladi** [comment]
Same issue for me. This is related to https://github.com/transistorsoft/react-native-background-geolocation/issues/2015

So here's why this happens, it will help @christocracy releasing an update if he wants to. 

startGeofences is not triggering showsBackgroundLocationIndicator even if set to true. 
If the app doesn't activate the blue IOS icon, that it will simply not work on the background. Starting the plugin with startGeofences  instead of start, make the plugin not detect motion change and trigger the showsBackgroundLocationIndicator hence all geofences will be missed unless the app is active. 

A simple workaround is to use start instead of startGeofences have very large values for settings like distanceFilter to reduce battery usage. 

Ideally @christocracy will release an update to make this work.

**Comment by Buthrakaur** [comment]
Thanks @sirusbaladi for the workaround suggestion. Could you please provide your point of view @christocracy ? I feel there're at least two options but it should be clear what is the final/accepted one:
1. it's a known limitation => I think there should be a mention about it in the docs and ideally some warning in the log when the app tries to use `startGeofences` in background
2. it's a bug => I think the library may be updated to perform the workaround suggested by @sirusbaladi when the tracking was started using `startGeofences` and app is switched to background to keep geofencing alive even on background.
I'd personally prefer #2 as other features in this library e.g. the polygon geofencing perform similar automagic silently for us.

**Comment by christocracy** [comment]
>So here's why this happens...startGeofences is not triggering showsBackgroundLocationIndicator

@sirusbaladi is wrong.  It has **nothing to do with** `showsBackgroundLocationIndicator`.

I'm testing this in the iOS simulator and I've found a minor **logic bug** related to polygon-geofencing and `.startGeofences`.

A solution will be released this week.

**Comment by christocracy** [comment]
specifically, the logic bug is incorrectly evaluating the following `if` statement to `true` in geofence-only mode:

```obj-c
if ((!config.isMoving && [StateChange empty] && (locationSamples >= 3)) || ![self isMonitoringPolygons]) {
        [self stopUpdatingLocation];
}
```

It needs to be changed as follows:
```obj-c
if ((!config.isMoving && [config isLocationTrackingMode] && [StateChange empty] && (locationSamples >= 3)) || ![self isMonitoringPolygons]) {
        [self stopUpdatingLocation];
}

```

**Comment by theCoderrrr** [comment]
I have a similar problem. When I close the application on Android, the entry and exit events do not work.

**Comment by christocracy** [comment]
This issue is specifically related to polygon geofences on iOS.

**Comment by theCoderrrr** [comment]
> This issue is specifically related to polygon geofences on iOS.
So what is the solution to this problem on Android? I have searched a lot but I could not find it. The application does not detect entry or exit to the area when it is closed.

**Comment by christocracy** [comment]
After solving the logic bug, an inexplicable issue was exposed with keeping location-services on in the background in geofences-only mode.

I use multiple instances of `CLLocationManager` in this SDK, and the Polygon geofence evaluator uses its own distinct instance.  For some unknown reason, I could only keep location-services on in the background (witnessed by the blue location-indicator in the statusbar) by also registering that `CLLocationManager` instance for significant-changes ([`[locationManager startMonitoringSignificantLocationChanges]`](https://developer.apple.com/documentation/corelocation/cllocationmanager/startmonitoringsignificantlocationchanges()?language=objc)).  Mystifying and senseless.  That took 4.5 days to figure that out.  

Polygon geofence-monitoring in geofences-only mode is working.

I will post to a branch in the private repo for you to test.

**Comment by sirusbaladi** [comment]
> I will post to a branch in the private repo for you to test.

How to get access to that? I have the polygon license but not access to the private repo

**Comment by christocracy** [comment]
> but not access to the private repo

Why not?  You didn’t purchase a license for background-geolocation?

**Comment by sirusbaladi** [comment]
> > but not access to the private repo
> 
> Why not? You didn’t purchase a license for background-geolocation?

no, as I'm only using on IOS for now

**Comment by christocracy** [comment]
Purchase a background-geolocation license to gain access to the private repo for latest updates.

**Comment by sirusbaladi** [comment]
> Purchase a background-geolocation license to gain access to the private repo for latest updates.

when will that update be available on here? 

it's easier for me to buy the background-geolocation license in a few months when I make the android version too

**Comment by christocracy** [comment]
> when will that update be available on here?

Unknown.  The public version is mirrored from the private version about every 3 months.

**Comment by sirusbaladi** [comment]
> > when will that update be available on here?
> 
> Unknown. The public version is mirrored from the private version about every 3 months.

even if i have the polygon license?

**Comment by christocracy** [comment]
> even if i have the polygon license?

Yes

**Comment by sirusbaladi** [comment]
got it, 

with this latest fix, startGeofence works properly even with blue location-indicator in the statusbar **off**?

**Comment by sirusbaladi** [comment]
@christocracy

**Comment by sirusbaladi** [comment]
> got it,
> 
> with this latest fix, startGeofence works properly even with blue location-indicator in the statusbar **off**?

can I get an answer on this please? @christocracy

**Comment by christocracy** [comment]
>with this latest fix, startGeofence works properly even with blue location-indicator in the statusbar off?

Yes.

**Comment by theCoderrrr** [comment]
> Purchase a background-geolocation license to gain access to the private repo for latest updates.

I bought it, how do I access the private repo?

**Comment by christocracy** [comment]
I've pushed a fix now to the private repo branch `#polygon-geofencing`.  To install from the private repo, you  must uninstall the public version [and re-install from the private repo](https://github.com/transistorsoft/react-native-background-geolocation-android/tree/master?tab=readme-ov-file#large_blue_diamond-setup-guides).  The Setup Instructions are similar; you just need to change a few paths from `react-native-background-geolocation` -> `react-native-background-geolocation-android`.

Install the plugin using git-url, appending `#polygon-geofencing` branch-name.
```
yarn add https://github.com/transistorsoft/react-native-background-geolocation-android.git#polygon-geofencing
```

@theCoderrrr Talk with the admin for your order.  They can `[Add]` your Github account to the private repo by access the Customer Dashboard (where license keys are managed).

**Comment by theCoderrrr** [comment]
> I've pushed a fix now to the private repo branch `#polygon-geofencing`. To install from the private repo, you must uninstall the public version [and re-install from the private repo](https://github.com/transistorsoft/react-native-background-geolocation-android/tree/master?tab=readme-ov-file#large_blue_diamond-setup-guides). The Setup Instructions are similar; you just need to change a few paths from `react-native-background-geolocation` -> `react-native-background-geolocation-android`.
> 
> Install the plugin using git-url, appending `#polygon-geofencing` branch-name.
> 
> ```
> yarn add https://github.com/transistorsoft/react-native-background-geolocation-android.git#polygon-geofencing
> ```
> 
> @theCoderrrr Talk with the admin for your order. They can `[Add]` your Github account to the private repo by access the Customer Dashboard (where license keys are managed).

https://github.com/transistorsoft/react-native-background-geolocation-android/tree/master?tab=readme-ov-file#large_blue_diamond-setup-guides

**Comment by christocracy** [comment]
> I click on this link but I get a page not found error. 

Yes, because you're not a member of the private repo.  Talk to the person who registered your Order and ask them to add you as a member (like I said above).  Once you become a member, that url will no longer be 404.

>Can I track geofecne entry and exit events more precisely with this special repo

This issue is about solving a problem with iOS failing to monitor **polygon geofences** in geofences-only mode (ie: `.startGeofences`).  If you're not using **polygon geofences**, this branch will do nothing different for you.

**Comment by theCoderrrr** [comment]
> > I click on this link but I get a page not found error.
> 
> Yes, because you're not a member of the private repo. Talk to the person who registered your Order and ask them to add you as a member (like I said above). Once you become a member, that url will no longer be 404.
> 
> > Can I track geofecne entry and exit events more precisely with this special repo
> 
> This issue is about solving a problem with iOS failing to monitor **polygon geofences** in geofences-only mode (ie: `.startGeofences`). If you're not using **polygon geofences**, this branch will do nothing different for you.

I am a member but it still does not appear

**Comment by christocracy** [comment]
Email me your Order #.  `info@transistorsoft.com`

**Comment by sirusbaladi** [comment]
> I've pushed a fix now to the private repo branch `#polygon-geofencing`. To install from the private repo, you must uninstall the public version [and re-install from the private repo](https://github.com/transistorsoft/react-native-background-geolocation-android/tree/master?tab=readme-ov-file#large_blue_diamond-setup-guides). The Setup Instructions are similar; you just need to change a few paths from `react-native-background-geolocation` -> `react-native-background-geolocation-android`.
> 
> Install the plugin using git-url, appending `#polygon-geofencing` branch-name.
> 
> ```
> yarn add https://github.com/transistorsoft/react-native-background-geolocation-android.git#polygon-geofencing
> ```
> 
> @theCoderrrr Talk with the admin for your order. They can `[Add]` your Github account to the private repo by access the Customer Dashboard (where license keys are managed).

is it normal that in my package.json I see:
 "undefined": "https://github.com/transistorsoft/react-native-background-geolocation-android.git#polygon-geofencing" ?

**Comment by christocracy** [comment]
No.  Never heard of that.  No idea.

**Comment by sirusbaladi** [comment]
> No. Never heard of that. No idea.

I installed it following the instructions:

`npx expo install https://github.com/transistorsoft/react-native-background-geolocation-android.git#polygon-geofencing`

am I doing something wrong?

**Comment by sirusbaladi** [comment]
> `npx expo install https://github.com/transistorsoft/react-native-background-geolocation-android.git#polygon-geofencing`

I also got: 

Skipping config plugin check: Failed to resolve plugin for module "react-native-background-geolocation-android" relative to "C:\my_codebase"

**Comment by christocracy** [comment]
I guess expo doesn’t like installing from git urls.

**Comment by sirusbaladi** [comment]
> I guess expo doesn’t like installing from git urls.

any solution to this? I just bought the premium version just for this bug and I'm using expo...

**Comment by christocracy** [comment]
> any solution to this?

Not currently.  I don’t have a lot of experience with expo.  I suggest you google “expo install package git url”.

**Comment by sirusbaladi** [comment]
> expo install package git url

already googled it and it apparently it's not possible. I have an idea, I'm going to email you.

**Comment by jakub-oone** [comment]
@christocracy We did our first quick testing with this version 4.17.0-beta.3 and it looks good on iOS. It works as we expected :-) Thank you!

**Comment by Buthrakaur** [comment]
Hello @christocracy , we just realized the issue occurs also on Android 14 when using "geofences only" tracking mode on background (even with `geofenceModeHighAccuracy`). It looks very similar to the iOS issue which you were able to fix already - the `isMoving` flag stays `false` (even when I switched the app to foreground) and also there's no notification for a foreground service. When I switch the mode to "Location + Geofences" the notification appears and all starts working on background. After switching back to "geofences only" the background seems to keep working - probably thanks to the notification which stays. I tested again on the demo app but the same issue occurs even in our app which uses the version `4.17.0-beta.3` so this doesn't seem to be fixed in this version. Could you please look into this on Android 14?
![image](https://github.com/user-attachments/assets/66dfed9a-02aa-45d1-b68a-d52495886b42)
![image](https://github.com/user-attachments/assets/657b398f-0b36-4b1a-a7ad-787763961a29)
![image](https://github.com/user-attachments/assets/7c82bac2-f965-4140-8683-d0be84958dc7)
![image](https://github.com/user-attachments/assets/241b53e5-93e5-45ca-a589-daea9b36ee85)
![image](https://github.com/user-attachments/assets/07bd94bc-1afd-4512-acb9-267af98dc7e5)
