### ISSUE TITLE
DWELL / loiteringDelay is not detected for Polygon Geofences IOS 

### ISSUE THREAD

**Issue by sirusbaladi** [transistorsoft/react-native-background-geolocation#2121]
## Your Environment
* Expo
* Plugin version:   4.16.5
* Platform: iOS 
* OS version: 17.4.1
* Device manufacturer / model: Iphone 13 pro
* React Native version (`react-native -v`):  "0.71.14
* Plugin config

## Expected Behavior

When I go into a polygon geofence I should receive geofence: DWELL

## Actual Behavior

I do receive geofence: DWELL for my radius geofences.

For polygon Geofences it only detecs enter / exit. 

## Steps to Reproduce

1. add a polygon geofence 
2. walk in it
3. I'm using debug mode with no license in expo.

**Comment by christocracy** [comment]
> DWELL / loiteringDelay

It’s not implemented yet.

**Comment by sirusbaladi** [comment]
> > DWELL / loiteringDelay
> 
> It’s not implemented yet.

Any timeline? 

We are launching the app this saturday and I was convinced that polygon geofence had dwell. It's a core feature.

**Comment by christocracy** [comment]
> Any timeline?

 No.  This winter perhaps.

**Comment by christocracy** [comment]
You’re free to run your own timers in the onGeofence enter event.

**Comment by sirusbaladi** [comment]
> You’re free to run your own timers in the onGeofence enter event.

Would you say something like this will work? In the if statement with event.vertices to make it happen only for polygon geofences. 

I wonder if an 8 minutes times is okay. 

```javascript
BackgroundGeolocation.onGeofence((event) => {
  if (event.action === "ENTER" && event.vertices) {
    BackgroundGeolocation.startBackgroundTask().then((taskId) => {
      setTimeout(() => {
        console.log("DWELL");
        BackgroundGeolocation.stopBackgroundTask(taskId);
      }, 8 * 60 * 1000); // 8 minutes in milliseconds
    }).catch((error) => {
      console.error("Error starting background task:", error);
    });
  }
});
```

**Comment by sirusbaladi** [comment]
or do you have a better way while waiting for the proper plugin implementation?

**Comment by christocracy** [comment]
You should keep a reference to your timerId so you can cancel it if EXIT occurs before timer expires.  You’d need to keep a Hash of timers keyed on geofence.identifier.

8 min is kind of long.

```JavaScript 
const timerId = setTimeout(…)
DWELL_TIMERS[identifer] = timerId
```

**Comment by sirusbaladi** [comment]
I see, thank you. 

But I wonder if this will work at all. In the documentation it says that startBackgroundTask() will only work for 180 seconds and my timer is 8 minutes. 

For non polygon geofences setting loiteringDelay to 8 minutes works great and never failed.

**Comment by christocracy** [comment]
When the plug-in enters the containing geofence of a polygon, it turns ON location-services.

when location-services are ON, your app is completely alive in the background, just as if it were in the foreground.

there’s no need for background-tasks.

**Comment by sirusbaladi** [comment]
> When the plug-in enters the containing geofence of a polygon, it turns ON location-services.
> 
> when location-services are ON, your app is completely alive in the background, just as if it were in the foreground.
> 
> there’s no need for background-tasks.

even if .startGefence?

**Comment by sirusbaladi** [comment]
> > When the plug-in enters the containing geofence of a polygon, it turns ON location-services.
> > when location-services are ON, your app is completely alive in the background, just as if it were in the foreground.
> > there’s no need for background-tasks.
> 
> even if .startGefence?

can I get an answer on this please? @christocracy

**Comment by christocracy** [comment]
>even if .startGefence?

Yes.  But since I've been working on polygon-geofencing for the last week+, I've decided to implement `notifyOnDwell` for polygon geofences.

**Comment by sirusbaladi** [comment]
> > even if .startGefence?
> 
> Yes. But since I've been working on polygon-geofencing for the last week+, I've decided to implement `notifyOnDwell` for polygon geofences.

oh awesome! and is this already released? how to get it?

**Comment by christocracy** [comment]
I’ll let you know when it’s pushed to the private repo.

**Comment by christocracy** [comment]
See #2113 ([this comment](https://github.com/transistorsoft/react-native-background-geolocation/issues/2113#issuecomment-2315290251))
