### ISSUE TITLE
Getting undefined for location coordinates.

### ISSUE THREAD

**Issue by fragilehm** [transistorsoft/react-native-background-geolocation#2127]
## Your Environment
* Plugin version: 4.16.2
* Platform: iOS
* OS version: 17.5.1
* Device manufacturer / model: iPhone 15 Pro max
* React Native version (`react-native -v`):

```
/**
 * This should called initialized when the application starts,
 * the purpose of this hook is to get the background location services ready.
 */
const useBackgroundLocation = () => {
  const setReady = useBackgroundLocationStore(store => store.setReady);
  useEffect((): (() => void) | void => {
    const onLocation: Subscription = BackgroundGeolocation.onLocation(
      (location: Location): void => {
        if (!location.sample) {
          sendLocation({
            longitude: location.coords.longitude,
            latitude: location.coords.latitude,
            timestamp: location.timestamp,
            sample: location.sample,
          });
        }
      },
    );

    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5,
      stopTimeout: 10,
      isMoving: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      disableLocationAuthorizationAlert: true,
    }).then((_state: State): void => {
      setReady(true);
    });

    return (): void => {
      // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
      // during development live-reload.  Without this, event-listeners will accumulate with
      // each refresh during live-reload.
      onLocation.remove();
    };
  }, [setReady]);
};

export default useBackgroundLocation;
```

## Expected Behavior
When receiving a location update, the coordinates should be defined.

## Actual Behavior
When receiving a location update, the location coordinates are undefined.
<img width="806" alt="image" src="https://github.com/user-attachments/assets/4f7b46c8-a8e8-4f0a-bc79-46753a7ba169">

## Steps to Reproduce

1. Start the app,
2. Allow background location tracking
3. Allow fitness tracking
4. Move to trigger location update.

**Comment by christocracy** [comment]
The `.onLocation` event takes a 2nd callback `failure` callback.  If you don't provide the 2nd `failure` callback, then `LocationError` is sent to the 1st callback.

You can easily see this by `console.log(location)` to see that you're receiving a `LocationError`.

See the API docs for [`.onLocation`](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#onlocation)

**Provide a 2nd arg** `failure` callback to your `.onLocation(success, failure)`.

**Comment by christocracy** [comment]
You would have been seeing a ⚠️ in the logs about that too.
