### ISSUE TITLE
new NativeEventEmitter() requires a non-null argument

### ISSUE THREAD

**Issue by petertoth-dev** [transistorsoft/react-native-background-geolocation#2129]
## Your Environment
* Plugin version: 4.16.5
* Platform: iOS
* OS version: 17.5.1
* Device manufacturer / model: iPhone15 Pro
* React Native version (`react-native -v`): 0.72.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.ready(
      {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 5,
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true,
      }
    ).then((state) => {
      // YES -- .ready() has now resolved.
      BackgroundGeolocation.getCurrentPosition({});
      BackgroundGeolocation.start();
    });
```
default

## Expected Behavior

It should work

## Actual Behavior

The App can't even start up, it throws:
`new NativeEventEmitter() requires a non-null argument` error.

## Steps to Reproduce

1. Install the package with npm
2. Add basic example code
3. See the result
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Try to reproduce in freshly generated “hello-world” app.
