### ISSUE TITLE
try to get location tracking in android app in all states, but not getting location based on time interval

### ISSUE THREAD

**Issue by nipundixit2016** [transistorsoft/react-native-background-geolocation#2130]
// index.js 

import React, {useEffect} from 'react';
import {
  Alert,
  AppRegistry,
  Linking,
  PermissionsAndroid,
  Platform,
} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';
import {DefaultTheme, Provider as PaperProvider} from 'react-native-paper';
import RNAndroidLocationEnabler from 'react-native-android-location-enabler';

// Initialize Geocoder (if used in BackgroundTask)
import Geocoder from 'react-native-geocoding';
import {GOOGLE_MAPS_API_KEY} from './src/utils/urls';
import BackgroundGeolocation from 'react-native-background-geolocation';

Geocoder.init(GOOGLE_MAPS_API_KEY);

// Ensure location services are enabled on Androidf
const ensureLocationServicesEnabled = async () => {
  if (granted === PermissionsAndroid.RESULTS.GRANTED) {
    console.log('Location permission granted');
    if (!granted) {
      try {
        await RNAndroidLocationEnabler.promptForEnableLocationIfNeeded({
          interval: 10000,
          fastInterval: 5000,
        })
          .then(data => {
            console.log('Location services enabled:', data);
          })
          .catch(err => {
            console.error('Error enabling location services:', err);
          });
      } catch (error) {
        console.error('Error in ensureLocationServicesEnabled:', error);
      }
    } else {
      return true;
    }
  } else {
    console.log('Location permission denied');
    Alert.alert(
      'Permission Denied',
      'Location permission is required for check-in and check-out. Please enable it in the settings.',
      [
        {
          text: 'Go to Settings',
          onPress: () => Linking.openSettings(),
        },
        {
          text: 'Cancel',
          style: 'cancel',
        },
      ],
    );
    return false;
  }
};

const lightTheme = {
  colors: {
    ...DefaultTheme.colors,
    primary: 'blue',
    background: 'white',
  },
};

// Main component
const Main = () => {
  useEffect(() => {
    // Ensure location services are enabled
    ensureLocationServicesEnabled();

    // BackgroundFetch.configure(
    //   {
    //     minimumFetchInterval: 15, // 15 minute
    //     stopOnTerminate: false,
    //     startOnBoot: true,
    //     enableHeadless: true,
    //     requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY,
    //     requiresBatteryNotLow: false,
    //     requiresCharging: false,
    //     requiresDeviceIdle: false,
    //     requiresStorageNotLow: false,
    //     // forceAlarmManager: true,
    //   },
    //   async taskId => {
    //     console.log('[BackgroundFetch] taskId:', taskId);
    //     await BackgroundTask(taskId); // Call BackgroundTask
    //   },
    //   error => {
    //     console.log('[BackgroundFetch] failed to start:', error);
    //   },
    // );

    // Start BackgroundFetch
    // BackgroundFetch.start();

    // Run BackgroundTask in the foreground
    // const intervalId = setInterval(async () => {
    //   console.log('Running BackgroundTask in the foreground');
    //   await BackgroundTask('foreground-task');
    // }, 15 * 60 * 1000); // Run every 15 minutes

    // return () => clearInterval(intervalId); // Clean up the interval on unmount
  }, []);

  return (
    <PaperProvider theme={lightTheme}>
      <App />
    </PaperProvider>
  );
};

BackgroundGeolocation.registerHeadlessTask(async event => {
  // await BackgroundTask(event.taskId);
});

// Register the main app component
AppRegistry.registerComponent(appName, () => Main);

export default Main;

<===================== BackgroundTask.js =========================>

//BackgroundGeolocation.ts

import BackgroundGeolocation from 'react-native-background-geolocation';
import axios from 'axios';
import Geocoder from 'react-native-geocoding';
import {BASE_URL, GOOGLE_MAPS_API_KEY} from './urls';
import {getFromLocalStorage, saveToLocalStorage} from './helpers';

Geocoder.init(GOOGLE_MAPS_API_KEY);

const fetchLocationAndSend = async location => {
  console.log('Fetching location...');
  const salesEmployeeCode = await getFromLocalStorage('SalesEmployeeCode');

  try {
    const {latitude, longitude} = location.coords;
    console.log(location, 'location');
    let positionsArray = [];

    positionsArray = await getFromLocalStorage('positionsArray');
    if (positionsArray.length > 0) {
      positionsArray = JSON.parse(positionsArray); // Parse the stored JSON string
    }

    // Add the new position to the array
    const geocodeResponse = await Geocoder.from(latitude, longitude);
    const address = geocodeResponse.results[0].formatted_address;
    const currentDate = new Date();
    const date = currentDate.toISOString().split('T')[0];
    const time = currentDate.toLocaleTimeString();

    const newPosition = {
      SalesEmployeeCode: salesEmployeeCode,
      Latitude: latitude.toString(),
      Longitude: longitude.toString(),
      Address: address,
      Create_Date: date,
      Create_Time: time,
    };
    positionsArray.push(newPosition);
    console.log('bhupendra', positionsArray.length);

    // Save the updated array back to local storage
    await saveToLocalStorage('positionsArray', JSON.stringify(positionsArray));

    console.log('Position saved to local storage:', newPosition);
  } catch (error) {
    console.error('Error in fetchLocationAndSend:', error);
  }
};

const BackgroundTask = async taskId => {
  console.log('[BackgroundTask] start');

  try {
    // Initialize BackgroundGeolocation
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0, // Adjust the distance filter as necessary
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true, // <-- Enable for debug purposes
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      locationUpdateInterval: 120000, // 2 minutes
      fastestLocationUpdateInterval: 120000, // Minimum time between updates
    })
      .then(state => {
        console.log('- BackgroundGeolocation is ready: ', state);

        if (!state.enabled) {
          // BackgroundGeolocation.start(); // Start tracking if not already started
        }

        // Listen to location updates
        BackgroundGeolocation.onLocation(fetchLocationAndSend, error => {
          console.error('[onLocation] ERROR:', error);
        });
      })
      .catch(error => {
        console.warn('- BackgroundGeolocation error: ', error);
      });
  } catch (error) {
    console.error('Error in background task:', error);
  }
};

export default BackgroundTask;

**Comment by christocracy** [comment]
- ignored issue template.
- Failed to syntax highlight code 
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by christocracy** [comment]
You must provide all the information requested in the issue template, not just delete it all.

![IMG_2113](https://github.com/user-attachments/assets/2b7face6-c963-4897-b7cf-c8cd0639a10a)




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
