### ISSUE TITLE
Unable to fetch location in background on regular interval

### ISSUE THREAD

**Issue by nipundixit2016** [transistorsoft/react-native-background-geolocation#2131]
## Your Environment
* Plugin version: 4.16.5
* Platform: Android
* OS version: <9
* Device manufacturer / model: any Android device
* React Native version (`react-native -v`):0.74.0
* Plugin config

```javascript
BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0, // Adjust the distance filter as necessary
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true, // <-- Enable for debug purposes
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      locationUpdateInterval: 120000, // 2 minutes
      fastestLocationUpdateInterval: 120000, // Minimum time between updates
      // heartbeatInterval: 60,
      allowIdenticalLocations: false,
      locationAuthorizationRequest: 'Always',
    })
```

```javascript
//BackgroundGeolocation.ts

import BackgroundGeolocation from 'react-native-background-geolocation';
import axios from 'axios';
import Geocoder from 'react-native-geocoding';
import {BASE_URL, GOOGLE_MAPS_API_KEY} from './urls';
import {getFromLocalStorage, saveToLocalStorage} from './helpers';

Geocoder.init(GOOGLE_MAPS_API_KEY);

const fetchLocationAndSend = async location => {
console.log('Fetching location...');
const salesEmployeeCode = await getFromLocalStorage('SalesEmployeeCode');

try {
const {latitude, longitude} = location.coords;
console.log(location, 'location');
let positionsArray = [];

positionsArray = await getFromLocalStorage('positionsArray');
if (positionsArray.length > 0) {
  positionsArray = JSON.parse(positionsArray); // Parse the stored JSON string
}

// Add the new position to the array
const geocodeResponse = await Geocoder.from(latitude, longitude);
const address = geocodeResponse.results[0].formatted_address;
const currentDate = new Date();
const date = currentDate.toISOString().split('T')[0];
const time = currentDate.toLocaleTimeString();

const newPosition = {
  SalesEmployeeCode: salesEmployeeCode,
  Latitude: latitude.toString(),
  Longitude: longitude.toString(),
  Address: address,
  Create_Date: date,
  Create_Time: time,
};
positionsArray.push(newPosition);
console.log('bhupendra', positionsArray.length);

// Save the updated array back to local storage
await saveToLocalStorage('positionsArray', JSON.stringify(positionsArray));

console.log('Position saved to local storage:', newPosition);
} catch (error) {
console.error('Error in fetchLocationAndSend:', error);
}
};

const BackgroundTask = async taskId => {
console.log('[BackgroundTask] start');

try {
// Initialize BackgroundGeolocation
BackgroundGeolocation.ready({
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 0, // Adjust the distance filter as necessary
stopOnTerminate: false,
startOnBoot: true,
debug: true, // <-- Enable for debug purposes
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
locationUpdateInterval: 120000, // 2 minutes
fastestLocationUpdateInterval: 120000, // Minimum time between updates
})
.then(state => {
console.log('- BackgroundGeolocation is ready: ', state);

    if (!state.enabled) {
      // BackgroundGeolocation.start(); // Start tracking if not already started
    }

    // Listen to location updates
    BackgroundGeolocation.onLocation(fetchLocationAndSend, error => {
      console.error('[onLocation] ERROR:', error);
    });
  })
  .catch(error => {
    console.warn('- BackgroundGeolocation error: ', error);
  });
} catch (error) {
console.error('Error in background task:', error);
}
};

export default BackgroundTask;
```

## Expected Behavior
Return location each 2min while app is foreground , background or killed state

## Actual Behavior
only getting once when BackgroundGeoLoaction.start()

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

</details>

**Comment by christocracy** [comment]
When you post a block of code, you **MUST** syntax highlight it.  I’ve told you this at least 4 times.  It is not hard.  You surround your code in triple-backticks (+optional language):

![IMG_2114](https://github.com/user-attachments/assets/e114eb67-2734-4b84-8aa2-cb67e5520046)

**Comment by nipundixit2016** [comment]
i have updated

**Comment by christocracy** [comment]
1. When you register event-listeners (such as `.onLocation`), you do do **BEFORE** calling `.ready(config)`, not within the `Promise` resolution.

```javascript
// Register listeners HERE <-------------------------
BackgroundGeolocation.onLocation((location) => {
  console.log('[onLocation]', location);
});

BackgroundGeolocation.ready(config).then((state) => {
  // DO NOT REGISTER EVENT-LISTENERS HERE.

});
```

2.  Learn how this plugin operates by *carefully* reading the Wiki ["Philosophy of Operation"](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

This plugin does **not** track location while the device is sitting stationary on your desk.  The plugin tracks location **ONLY** when the device is detected to be **moving** (typically requires movement of at least 200 meters).

Go outside for a nice long walk of at least 1km.  With `debug: true`, the plugin will emit debugging sound-effects to let you it's working.  To leran what these debugging sound-effects mean, read the API docs [`Config.debug`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#event-debug-sound-effects).  The *searchable* API docs are conveniently linked in the README in the [Table of Contents](https://github.com/transistorsoft/react-native-background-geolocation?tab=readme-ov-file#contents)

<img width="1102" alt="Screenshot 2024-08-31 at 4 43 36 PM (1)" src="https://github.com/user-attachments/assets/24aba990-7063-44d0-a338-b486ae4cb235">

**Comment by christocracy** [comment]
About "wiring up event-listeners", the [Example](https://github.com/transistorsoft/react-native-background-geolocation?tab=readme-ov-file#large_blue_diamond-example) in the README clearly states the process.  You need to stop "throwing crap at the wall" and carefully *read* and *understand* how this plugin works.

<img width="905" alt="Screenshot 2024-08-31 at 4 47 50 PM (1)" src="https://github.com/user-attachments/assets/ae633637-df80-45f1-9437-9be35d63366f">

**Comment by christocracy** [comment]
If you want *periodic* location updates (eg: about every 15 minutes) , you can so by calling `.getCurrentPosition` in your  `BackgroundFetch` callback.

```javascript
  BackgroundFetch.configure({
      minimumFetchInterval: 15,  // <-- every 15 minutes is the fastest you'll get.
      enableHeadless: true,
      stopOnTerminate: false
    }, async (taskId) => {
      console.log('[BackgroundFetch]', taskId);
      const location = await BackgroundGeolocation.getCurrentPosition({
        samples: 3 // record 3 locations and return the most accurate of the three
      });
      console.log('[getCurrentPosition]', location);
      BackgroundFetch.finish(taskId);
    }, async (taskId) => {
      console.log('[BackgroundFetch] TIMEOUT:', taskId);
      BackgroundFetch.finish(taskId);
    });
```

**Comment by nipundixit2016** [comment]
By periodic time everything working properly but when creating release build. it not working in that build.

**Comment by christocracy** [comment]
> `await saveToLocalStorage('positionsArray', JSON.stringify(positionsArray));`

You don't need to store locations in `localStorage`.  This plugin has its own built-in SQLite database.

Those recorded locations can be retrieved via [`.getLocations()`](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#getlocations) and the database cleared via [`.destroyLocations()`](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#destroylocations).

The plugin also hosts its own built-in HTTP service.  See API docs [HTTP Guide](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/httpevent.html) for more information on all the plugin's HTTP Features.

**Comment by christocracy** [comment]
>By periodic time everything working properly but when creating release build. it not working in that build.

You were not using `BackgroundGeolocation` before.  You were using some *other* plugin named `Geolocation`.

If you have a problem, see Wiki [Debugging](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging) and learn how to fetch the plugin's logs via [`.emailLog`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/logger.html#emaillog)

**Comment by nipundixit2016** [comment]
I am replacing Geolocation by BackgroundGeolocation hoping it works in release build.

**Comment by christocracy** [comment]
>I am replacing Geolocation by BackgroundGeolocation hoping it works in release build.

Do not "*hope*" -- test it yourself with a local `realease` build on your own device **FIRST**.

With your device plugged into USB:
```
$ npx react-native run-android --mode=release
```

**Comment by christocracy** [comment]
and when running locally, ALWAYS observe `$ adb logcat *:S TSLocationManager:V` to view realtime logs from the plugin.

This plugin's logging system is *incredibly* verbose and prints absolutely everything that it's doing:

<img width="1262" alt="Screenshot 2024-08-31 at 5 09 24 PM" src="https://github.com/user-attachments/assets/1754dcc8-191c-4d59-ace1-dbcc3787b86a">

**Comment by christocracy** [comment]
If you don't know how to use `adb logcat`, [learn how to](https://developer.android.com/tools/logcat)

**Comment by christocracy** [comment]
And *of course* you probably didn't read how to [*simulate* Android `background-fetch`](https://github.com/transistorsoft/react-native-background-fetch?tab=readme-ov-file#android-1) tasks in a terminal window with `adb shell`

```console
adb shell cmd jobscheduler run -f <your.application.id> 999
```

**Comment by nipundixit2016** [comment]
// replace GeoLocation by BackgroundGeolocation , now working in signed apk but not working when app in background or close state

[1:02 am, 1/9/2024] Durgesh React Native Cinntra: import BackgroundFetch from 'react-native-background-fetch';
import BackgroundGeolocation from 'react-native-background-geolocation';

import axios from 'axios';
import Geocoder from 'react-native-geocoding';
import {BASE_URL, GOOGLE_MAPS_API_KEY} from './urls';
import {getFromLocalStorage, saveToLocalStorage} from './helpers';

Geocoder.init(GOOGLE_MAPS_API_KEY);

const fetchLocationAndSend = async () => {
  console.log('Fetching location...');
  const salesEmployeeCode = await getFromLocalStorage('SalesEmployeeCode');
  try {
    BackgroundGeolocation.getCurrentPosition(
      {enableHighAccuracy: false, timeout: 15000}, // Options object as the first argument
      async position => {
        try {
          const {latitude, longitude} = position.coords;
…
[1:04 am, 1/9/2024] Durgesh React Native Cinntra: import React, {useEffect} from 'react';
import {
  Alert,
  AppRegistry,
  Linking,
  PermissionsAndroid,
  Platform,
} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';
import {DefaultTheme, Provider as PaperProvider} from 'react-native-paper';
import BackgroundTask from './src/utils/BackgroundTask';
import BackgroundFetch from 'react-native-background-fetch';
import RNAndroidLocationEnabler from 'react-native-android-location-enabler';

// Initialize Geocoder (if used in BackgroundTask)
import Geocoder from 'react-native-geocoding';
import {GOOGLE_MAPS_API_KEY} from './src/utils/urls';
import BackgroundGeolocation from 'react-native-background-geolocation';

Geocoder.init(GOOGLE_MAPS_API_KEY);

// Ensure location services are enabled on Androidf
const ensureLocationServicesEnabled = async () => {
  if (granted === PermissionsAndroid.RESULTS.GRANTED) {
    console.log('Location permission granted');
    if (!granted) {
      try {
        await RNAndroidLocationEnabler.promptForEnableLocationIfNeeded({
          interval: 10000,
          fastInterval: 5000,
        })
          .then(data => {
            console.log('Location services enabled:', data);
          })
          .catch(err => {
            console.error('Error enabling location services:', err);
          });
      } catch (error) {
        console.error('Error in ensureLocationServicesEnabled:', error);
      }
    } else {
      return true;
    }
  } else {
    console.log('Location permission denied');
    Alert.alert(
      'Permission Denied',
      'Location permission is required for check-in and check-out. Please enable it in the settings.',
      [
        {
          text: 'Go to Settings',
          onPress: () => Linking.openSettings(),
        },
        {
          text: 'Cancel',
          style: 'cancel',
        },
      ],
    );
    return false;
  }
};

const lightTheme = {
  colors: {
    ...DefaultTheme.colors,
    primary: 'blue',
    background: 'white',
  },
};

// Main component
const Main = () => {
  useEffect(() => {
    // Ensure location services are enabled
    ensureLocationServicesEnabled();

    // Configure BackgroundFetch
    BackgroundFetch.configure(
      {
        minimumFetchInterval: 15, // 15 minute
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresDeviceIdle: false,
        requiresStorageNotLow: false,
        // forceAlarmManager: true,
      },
      async taskId => {
        console.log('[BackgroundFetch] taskId:', taskId);
        await BackgroundTask(taskId); // Call BackgroundTask
      },
      error => {
        console.log('[BackgroundFetch] failed to start:', error);
      },
    );

    
  }, []);

  return (
    <PaperProvider theme={lightTheme}>
      <App />
    </PaperProvider>
  );
};


// BackgroundGeolocation.registerHeadlessTask(async event => {
BackgroundFetch.registerHeadlessTask(async event => {
  console.log('[BackgroundFetch HeadlessTask] start', event.taskId);
  // await BackgroundTask(event.taskId);
});

// Register the main app component
AppRegistry.registerComponent(appName, () => Main);

export default Main;

**Comment by christocracy** [comment]
### What the hell is wrong with you.  I’ve warned you five times about syntax highlighting.  It is NOT hard.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by nipundixit2016** [comment]
'''

import React, { useEffect } from 'react';
import { AppRegistry, Platform, Alert } from 'react-native';
import App from './App';
import { name as appName } from './app.json';
import BackgroundGeolocation from 'react-native-background-geolocation';

const MainApp = () => {
  useEffect(() => {
    // Define a callback for location updates
    const onLocation = (location) => {
      console.log('[onLocation] -', location);
      // Handle location update
    };

    // Define a callback for errors
    const onError = (error) => {
      console.warn('[onError] -', error);
      // Handle error
    };

    // Define a callback for the state change
    const onStateChange = (state) => {
      console.log('[onStateChange] -', state);
      // Handle state changes
    };

    // Define a callback for geofence events
    const onGeofence = (geofence) => {
      console.log('[onGeofence] -', geofence);
      // Handle geofence events
    };

    // Set up event listeners
    BackgroundGeolocation.onLocation(onLocation, onError);
    // BackgroundGeolocation.onError(onError);
    // BackgroundGeolocation.onStateChange(onStateChange);
    BackgroundGeolocation.onGeofence(onGeofence);

    // Configure BackgroundGeolocation
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10, // Minimum distance (in meters) before update
      stopOnTerminate: false, // Continue tracking when the app is terminated
      startOnBoot: true, // Start tracking on device boot
      enableHeadless: true, // Enable headless mode for background tasks
      locationUpdateInterval: 60000, // Update interval in milliseconds
      notificationTitle: "Background Tracking",
      notificationText: "Enabled",
    }).then((state) => {
      if (!state.enabled) {
        // Start tracking if not already enabled
        BackgroundGeolocation.start();
      }
    }).catch((error) => {
      console.error('Error configuring BackgroundGeolocation:', error);
    });

    return () => {
      // Clean up listeners on unmount
      BackgroundGeolocation.removeListeners();
    };
  }, []);

  return <App />;
};

AppRegistry.registerComponent(appName, () => MainApp);

'''

**Comment by christocracy** [comment]
The [`] backtick character is not the [‘] single-quite.

https://superuser.com/questions/254076/how-do-i-type-the-tick-and-backtick-characters-on-windows

**Comment by christocracy** [comment]
I suggest you Google how to find the [`] backtick character for your keyboard.
