### ISSUE TITLE
geofence does not work in the background and does not detect entrances and exits

### ISSUE THREAD

**Issue by theCoderrrr** [transistorsoft/react-native-background-geolocation#2133]
I have 2 screens, one of them starts the location tracking codes in the background, this file works without any problems, my other screen is geofence, it works when I log in to that page, but it does not work when the application is closed, can this be why there is BackgroundGeolocation.ready({
on both screens?

## Your Environment
* Plugin version: 4.16.3
* Platform: iOS or Android android 
* OS version: 10
* Device manufacturer / model:  xiaomi redmi 9
* React Native version (`react-native -v`): 0.74.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You’ve not posted an Config, code or logs.

search api docs “.emailLog” to learn how to fetch the plug-in logs.

**Comment by theCoderrrr** [comment]
> You’ve not posted an Config, code or logs.
> 
> search api docs “.emailLog” to learn how to fetch the plug-in logs.

Will this solve my problem?

**Comment by christocracy** [comment]
It’s a start.

**Comment by theCoderrrr** [comment]
Another friend of mine is using this library and it works for him, but I have a problem.

**Comment by christocracy** [comment]
And the problem will illuminated in the Config, code and logs.  Stop wasting time.

**Comment by theCoderrrr** [comment]
.email log what is it for? does it send logs via e-mail?

**Comment by christocracy** [comment]
Why don’t you consult the app docs, try the method and see what happens?

**Comment by theCoderrrr** [comment]
Okay, I'll try it out, I hope my problem will be solved.

**Comment by theCoderrrr** [comment]
let Logger = BackgroundGeolocation.logger;
I think you are saying this but I don't quite understand what this does

**Comment by christocracy** [comment]
There’s an example right there in the api docs.  I don’t understand how you can’t understand.

https://transistorsoft.github.io/react-native-background-geolocation/interfaces/logger.html#emaillog

It’s a simple method requiring one parameter.

![IMG_2116](https://github.com/user-attachments/assets/c0126312-48ef-4705-8604-660bea950080)
