### ISSUE TITLE
Android 14 Tracking Issue

### ISSUE THREAD

**Issue by alihasan21987** [transistorsoft/react-native-background-geolocation#2137]
## Your Environment
* Plugin version: 4.16.5
* Platform: Android
* OS version: 14
* Device manufacturer / model: Google Pixel 5
* React Native version (`react-native -v`): 0.70.6
* Plugin config
BackgroundGeolocation.ready({
    debug: false,
    locationAuthorizationRequest: 'Always',
    showsBackgroundLocationIndicator: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: desiredAccuracy
      ? desiredAccuracy
      : BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: distanceFilter === 9 ? 30 : distanceFilter,
    startOnBoot: true,
    enableHeadless: true,
    heartbeatInterval: 10,
    stopOnTerminate: false,
    elasticityMultiplier: 3,
    disableMotionActivityUpdates: true,
    locationAuthorizationAlert: {
      titleWhenNotEnabled: t('title_when_not_enabled'),
      titleWhenOff: t('title_when_off'),
      instructions: t('location_auth_alert_instructions'),
      cancelButton: t('location_auth_alert_cancel'),
      settingsButton: t('location_auth_alert_settings'),
    },
    stopTimeout: 5,
    desiredOdometerAccuracy: 10,
    backgroundPermissionRationale: {
      title: 'Allow "App" to use your location?',
      message:
        'Please select "Change to Always Allow" below so App can access your location even when you are not using the app.',
      positiveAction: 'Change to "Always Allow"',
      negativeAction: 'Cancel',
    },
  })

## Expected Behavior
Not getting any location updates in foreground & Background State & also not getting any location's data from SDK's SQLite database by calling BackgroundGeolocation.getLocations().

## Actual Behavior
In Android 14, I want to receiving locations updates but I am not receiving in android 14 in foreground & Background State & also not getting any location's data from SDK's SQLite database by calling BackgroundGeolocation.getLocations().

## Steps to Reproduce

1.Used above mentioned Plugin Settings and not receiving any location updates in Android 14
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
[background-geolocation (10).log](https://github.com/user-attachments/files/16905986/background-geolocation.10.log)

</details>

**Comment by christocracy** [comment]
What are the plug-in’s logs saying?  See wiki “Debugging”.
