### ISSUE TITLE
how to use patch method in server request

### ISSUE THREAD

**Issue by NadeemKhanFh** [transistorsoft/react-native-background-geolocation#2138]
Hello

url: "http://my.server.com",
  params: {
    "user_id": 123
  },
  headers: {
    "my-auth-token":"secret-key"
  }

 i have a rest api to update rider location

const updateRiderInfo = ({body}: {body: any}) => {
  return new Promise((resolve, reject) => {
    NetWorkService.Patch({
      url: `riders/updateByRider`,
      body: body,
    })
      .then((res) => resolve(res))
      .catch((error) => reject(error));
  });
};

is there any so that i can set Patch method and  body:{lat:0, long:0} in the config?

**Comment by christocracy** [comment]
See the api docs `Config` to see all the options available to you beginning with the word “`http`”.
