### ISSUE TITLE
Public method to check geofence status according identifier / extend geofences with status

### ISSUE THREAD

**Issue by robmoorman** [transistorsoft/react-native-background-geolocation#214]
As we have some problems with listening to the geofence events when the app is in suspended mode (React Native seems to miss events sometimes for undiscovered reason, probably startup time over threads) there should be a method to get the statuses of current geofences.

It would be nice to have a public method available were we can get the geofence status from:
``` javascript
instance.getGeofence('myid', (state)) => {
   // state.status ENTER/EXIT
});
```
or extend the `getGeofences()` method's response with the status ENTER/EXIT included.

With this method we can ensure the status is correct in our app when we miss a geofence event (due execution time / errors, etc.).

Currently we read the ENTER/EXIT state from the reverse log via `getLog()` which is definitely bad practice but seems to work perfectly for test purposes.

**Comment by christocracy** [comment]
are you setting up your event-listeners *before* calling `#configure`?

```javascript
BackgroundGeolocation.on('geofence', onGeofence);
BackgroundGeolocation.configure(config, function(state) {
  console.log('- Configure success');
});
```

**Comment by christocracy** [comment]
Try putting it before.  The plugin may be firing the event *before* you've listened to it.

**Comment by robmoorman** [comment]
Ok, I'll give it a try, thanks.
Still the method / extend the status of the geofences responses would be acceptable I guess.

**Comment by christocracy** [comment]
Is it a history of "hits" on the geofence you're looking for?  I had considered this briefly when designing the database.

Eg:
```javascript
{
  "identifier": "home",
  "events": [
    {"timestamp": "2017-03-10T13:30:00.123Z", "transition": "ENTER"},
   {"timestamp": "2017-03-10T14:30:00.123Z", "transition": "EXIT"},
  ]
}
```
This seems like information you should query from your server.
