### ISSUE TITLE
Invalid license Key

### ISSUE THREAD

**Issue by dalexmolina** [transistorsoft/react-native-background-geolocation#2147]
## Your Environment
* Expo version: 51.0.32
* Plugin version: 4.17.1
* Platform:  Android
* OS version: 13
* Device manufacturer / model: Samsung S20 FE 5G / SM-G780G
* React Native version (`react-native -v`): 0.76.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

useEffect(() => {

        BackgroundGeolocation.ready({

            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 30,
            //locationUpdateInterval: 5000,
            disableElasticity: true,
            stopTimeout: 5,
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: true,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: false,        // <-- Auto start tracking when device is powered-up.
            notification: {
                title: "Seguimiento de ruta",
                text: "Se esta compartiendo su posición"
            }

        }).then((state) => {

            if (!state.enabled) {
                setEnabledLocationService(true)
                console.log('=== SE CARGO SERVICIO ===')
            }

        }).catch(error => {
            console.warn('- BackgroundGeolocation error: ', error);
        });;

    }, []);


	=== app.json ====
	
	
"plugins": [
      "@react-native-firebase/app",
           [
               "react-native-background-geolocation", {
                 "license": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
               }
           ],
           [
               "expo-gradle-ext-vars", {
                 "googlePlayServicesLocationVersion": "21.1.0",
                 "appCompatVersion": "1.4.2"
              }
           ],
             "react-native-background-fetch"
    ]

```

## Expected Behavior
N/A

## Actual Behavior
Shows a notification with the error of "invalid license key"

![ImportedPhoto_1726752964367](https://github.com/user-attachments/assets/22bc6daf-a8f6-4192-898d-081014ef3633)

## Steps to Reproduce
Everytime the app starts

</details>

**Comment by christocracy** [comment]
Are you *sure* the license key you generated matches the Android `package` name defined in your `app.json`?

Did you completely follow the Setup Instructions and [Re-build](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md#re-build)?

After running `npx expo prebuild`, you *must* run your Android app as follows:

```
npx expo run:android
```

See the Expo docs for [Prebuild](https://docs.expo.dev/workflow/prebuild/)

**Comment by dalexmolina** [comment]
Yes, the name of the package was correct, but i'm using Expo EAS for the builds, also i follow the instructions..

**Comment by christocracy** [comment]
You're building development builds with `eas build`?

so you ran this?
```
 eas build --profile development
```

**Comment by dalexmolina** [comment]
Yes, also created a production build **( eas build --profile production )** and published it in an appstore for testing purposes and the message persists.

**Comment by christocracy** [comment]
I suggest you first build locally:

```
$ npx expo prebuild
$ npx expo run:android
```

**Comment by dalexmolina** [comment]
I tried locally but the problem persists

**Comment by christocracy** [comment]
Post the following files:
- android/build.gradle
- Android/app/build.gradle
- AndroidManifest.xml
