### ISSUE TITLE
Configurations are not persisted when changing them via BackgroundGeolocation.setConfig()

### ISSUE THREAD

**Issue by Stophface** [transistorsoft/react-native-background-geolocation#2149]
* Plugin version: 4.12.0
* Platform: iOS
* OS version: 17
* React Native version (`react-native -v`): 0.73.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  stationaryRadius: 25,
  desiredOdometerAccuracy: 10,
  disableElasticity: true,
  distanceFilter: 50,
  disableLocationAuthorizationAlert: true,
  maxRecordsToPersist: 0,
  stopOnTerminate: false,
  stopTimeout: 8,
  disableMotionActivityUpdates: true,
  debug: false,
  startOnBoot: false,
  isMoving: true,
  forceReloadOnBoot: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  showsBackgroundLocationIndicator: true,
  allowIdenticalLocations: false,
  foregroundService: true,
  locationAuthorizationRequest: 'WhenInUse',
```

## Expected Behavior
I want to change the configuration of the Plug In after the `.ready()` method hast been called. I want to to change these two props

```
BackgroundGeolocation.setConfig({
     startOnBoot: true,
     forceReloadOnBoot: true,
});
```

## Actual Behavior
When I log the configuration with 

```
const state = await BackgroundGeolocation.getState();
console.log(state)
```

right after I updated the configuration, I see that `"startOnBoot": true`. However, when I reload the App and I `console.log` the state where I call the `.ready()` method, it logs `"startOnBoot": false`. The Plug ins settings are not persisted? Interestingly, this prop `forceReloadOnBoot` is not shown in the result of `BackgroundGeolocation.getState()`.

## Steps to Reproduce

1. Change `startOnBoot` and `forceReloadOnBoot` to true
2. Reload the app
3. Log the plug ins state right after the `.ready()` method

## Context
Change the Plug Ins config.

**Comment by christocracy** [comment]
See `reset: false` in Config provided to .ready(config)

**Comment by Stophface** [comment]
thanks
