### ISSUE TITLE
[iOS 18] Authorization dialogs do not open because of deprecated API

### ISSUE THREAD

**Issue by ItaGuy** [transistorsoft/react-native-background-geolocation#2151]
* Plugin version: 4.17.1
* Platform: iOS
* OS version: 18
* Device manufacturer / model: Simulator, any model
* React Native version (`react-native -v`): 13.6.9 -> this is the output of the command but it refers to react-native-community/cli-tools, the react-native module version is 0.74.5
* Plugin config
```
{
    locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Please enable location services',
        titleWhenOff: 'Please activate location services',
        instructions: 'Please ensure location services are active and enable "Always" option to make sure the app works as expected',
        cancelButton: 'Cancel',
        settingsButton: 'Settings'
    },
    locationAuthorizationRequest: "WhenInUse",  // "Always" requested right after .start
    // Geolocation Config
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
    distanceFilter: distance,
    // Activity Recognition
    stopTimeout: 5,
    // Application config
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,
    startOnBoot: true,
    preventSuspend: true,
    heartbeatInterval: heartbeat,
    disableElasticity: true,
    // http/sqlite config
    url: BASE_URL + 'save',
    method: 'POST',
    headers: {
        'Content-Type': 'application/json'
    },
    locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>, "timestamp": "<%= timestamp %>"}',
    httpRootProperty: '.',
    batchSync: false, 
    autoSync: true
}
```

## Expected Behavior
Authorization dialogs should open normally

## Actual Behavior
Authorization dialogs do not open. The issue is related to the use of the deprecated method UIApplication.openURL.

## Steps to Reproduce
1. Setup the plugin using a config which includes locationAuthorizationAlert
2. Launch the app
3. give permissions then change them in settings or disable location services
4. Go back to the app to let the dialog open, then try to open the settings by clicking its "settings" button

## Context
Open the settings to update permissions/services when not available using the dialogs

## Debug logs
<details><summary>Logs</summary>

```
[UIKitCore] BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).
```

</details>

**Comment by christocracy** [comment]
This is fixed in latest version `v4.17.4`
