### ISSUE TITLE
My API endpoint is https://api.com/api/admin/add/dummy/data.  I need to send latitude and longitude to this API whether the app is closed, in the background, or running.  I need the code for this in React Native

### ISSUE THREAD

**Issue by ramkrushan-kaito** [transistorsoft/react-native-background-geolocation#2153]
import React, { useEffect } from 'react';
import { Switch, Text, View } from 'react-native';
import BackgroundGeolocation from 'react-native-background-geolocation';

const App = () => {
  const [enabled, setEnabled] = React.useState(false);
  const [location, setLocation] = React.useState('');

  // Function to send the location manually to the API
  const callApiWithLocation = (loc) => {
    // Check if loc is already an object
    const coords = loc.coords;  // Use loc directly if it's already an object
  
    const latitude = coords?.latitude;
    const longitude = coords?.longitude;
  
    console.log('latitude', latitude);
    console.log('longitude', longitude);
  
    // Prepare headers and body for the API request
    const myHeaders = new Headers();
    myHeaders.append("Content-Type", "application/json");
  
    const raw = JSON.stringify({
      "latitude": latitude.toString(), // Convert to string if needed
      "longitude": longitude.toString(), // Convert to string if needed
      "device": 'android',
      "address": 'TEST'
    });
  
    const requestOptions = {
      method: "POST",
      headers: myHeaders,
      body: raw,
      redirect: "follow"
    };
  
    // Make the API call
    fetch("https://bfsi.staypinc.com/api/admin/add/dummy/data", requestOptions)
      .then((response) => response.text())
      .then((result) => console.log(result))
      .catch((error) => console.error('Error:', error));
  };
  
  useEffect(() => {
    // 1. Subscribe to events.
    const onLocation = BackgroundGeolocation.onLocation((loc) => {
      console.log('[onLocation]', loc);
      setLocation(JSON.stringify(loc, null, 2));

      // Call your API manually with the location.
      callApiWithLocation(loc);
    });

    const onMotionChange = BackgroundGeolocation.onMotionChange((event) => {
      console.log('[onMotionChange]', event);
    });

    const onActivityChange = BackgroundGeolocation.onActivityChange((event) => {
      console.log('[onActivityChange]', event);
    });

    const onProviderChange = BackgroundGeolocation.onProviderChange((event) => {
      console.log('[onProviderChange]', event);
    });

    // 2. Ready the plugin with background settings.
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1,  // Update location as frequently as possible
      stopTimeout: 5,
      debug: true, // Enable debugging sounds for lifecycle events.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // Continue tracking when app is closed.
      startOnBoot: true, // Auto start tracking when the device is powered up.
      url: 'https://yourserver.com/api/locations', // Your server endpoint for location updates.
      batchSync: false, // Set true to sync locations in a single request.
      autoSync: true, // Automatically sync each location as it arrives.
      headers: {
        "Content-Type": "application/json",
        "Authorization": "Bearer YOUR_TOKEN" // Optional HTTP headers for authentication.
      },
      params: {
        "device_id": "your-device-id" // Optional params to be sent with each location.
      }
    }).then((state) => {
      setEnabled(state.enabled);
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
    });

    // Cleanup event subscriptions on component unmount.
    return () => {
      onLocation.remove();
      onMotionChange.remove();
      onActivityChange.remove();
      onProviderChange.remove();
    };
  }, []);

  // 3. Start/stop BackgroundGeolocation based on the enabled state.
  useEffect(() => {
    if (enabled) {
      BackgroundGeolocation.start();
    } else {
      BackgroundGeolocation.stop();
      setLocation('');
    }
  }, [enabled]);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Click to enable BackgroundGeolocation</Text>
      <Switch value={enabled} onValueChange={setEnabled} />
      <Text style={{ fontFamily: 'monospace', fontSize: 12 }}>{location}</Text>
    </View>
  );
};

export default App;

**Comment by christocracy** [comment]
The issue template is not optional, it’s required.  You’re supposed enter all that info requested in the pre populated text in the text box, not just delete it all.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
also, when posting code, learn to syntax highlight “fenced code blocks”, it’s easy.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by ramkrushan-kaito** [comment]
My API endpoint is https://demo.demo.com/api/admin/add/dummy/data.

I need to send latitude and longitude to this API whether the app is closed, in the background, or running.

I need the code for this in React Native

**Comment by christocracy** [comment]
I am waiting for you to provide all the requested info from the issue template and syntax highlight your code.

**Comment by ramkrushan-kaito** [comment]
const callApiWithLocation = (loc) => {
    const coords = loc.coords; 
  
    const latitude = coords?.latitude;
    const longitude = coords?.longitude;
  
    console.log('latitude', latitude);
    console.log('longitude', longitude);
  
    // Prepare headers and body for the API request
    const myHeaders = new Headers();
    myHeaders.append("Content-Type", "application/json");
  
    const raw = JSON.stringify({
      "latitude": latitude.toString(), // Convert to string if needed
      "longitude": longitude.toString(), // Convert to string if needed
      "device": 'android',
      "address": 'TEST'
    });
  
    const requestOptions = {
      method: "POST",
      headers: myHeaders,
      body: raw,
      redirect: "follow"
    };
  
    // Make the API call
    fetch("https://api.com/api/admin/add/dummy/data", requestOptions)
      .then((response) => response.text())
      .then((result) => console.log(result))
      .catch((error) => console.error('Error:', error));
  };
  
    const onLocation = BackgroundGeolocation.onLocation((loc) => {
      console.log('[onLocation]', loc);
      setLocation(JSON.stringify(loc, null, 2));

      // Call your API manually with the location.
      callApiWithLocation(loc);
    });

**Comment by ramkrushan-kaito** [comment]
I need to send latitude and longitude to my API continuously every 1 km, whether the app is closed, in the background, or in the foreground.
