### ISSUE TITLE
Accuracy random to 2000

### ISSUE THREAD

**Issue by chanphiromsok** [transistorsoft/react-native-background-geolocation#2154]
## Your Environment
* Plugin version: ^4.15.0
* Platform:  Android
* OS version:  N/A
* Device manufacturer / model: N/A
* React Native version (`react-native -0.73.6`):

## Expected Behavior

if this is from sensor phone GPS should I filter this out? I am not sure why accuracy to 2000 for every accuracy 2000 lat/long is not correct compare to current location

## Actual Behavior

 accuracy random to 2000 in the background broadcast to the server and it causes the location wrong between the current location
you can see the bottom image accuracy is 2000 and it caused the wrong latitude and longitude save on the server
![telegram-cloud-photo-size-5-6327589650511805954-y](https://github.com/user-attachments/assets/3a52ea4c-3f38-4cec-a12c-917dcfbab373)
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The `accuracy` information comes from the native Android Location API [`Location.getAccuracy()`](https://developer.android.com/reference/android/location/Location#getAccuracy())

**Comment by chanphiromsok** [comment]
> The `accuracy` information comes from the native Android Location API [`Location.getAccuracy()`](https://developer.android.com/reference/android/location/Location#getAccuracy())
when the accuracy is 2000 it cause the location jump like this
![telegram-cloud-photo-size-5-6327589650511805965-x](https://github.com/user-attachments/assets/75dac905-4778-42ef-bc03-d11afdf2b172)

**Comment by christocracy** [comment]
yes, that's not surprising to see a periodic "jump" when a poor accuracy location arrives.  It's up to you to filter your data as-desired.  

No location is a dimensionless point in space.  each location is a circle of radius `accuracy`.

- A location with good accuracy is a *small* circle (typical radius (`accuracy`) of 5 meters.
- A location with poor accuracy (eg: 2000 meters) is a *big* circle.

**Comment by chanphiromsok** [comment]
so it means that accuracy is the meter that location accurate around that circle ,one more question does background geolocation have an filter option before send to server ?

**Comment by christocracy** [comment]
>one more question does background geolocation have an filter option before send to server

No.  You're expected to filter at the server.

**Comment by chanphiromsok** [comment]
thank you the issue can close now

**Comment by christocracy** [comment]
You can close your own issues.
