### ISSUE TITLE
BackgroundGeolocation.onGeofence is not working on Android in Killed State

### ISSUE THREAD

**Issue by alihasan21987** [transistorsoft/react-native-background-geolocation#2160]
## Your Environment
* Plugin version:4.16.5
* Platform: Android
* OS version: 13
* Device manufacturer / model: Samsung S22 plus
* React Native version (`react-native -v`):0.70.6
* Plugin config
BackgroundGeolocation.ready({
    debug: false,
    locationAuthorizationRequest: 'Always',
    showsBackgroundLocationIndicator: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: desiredAccuracy
      ? desiredAccuracy
      : BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    deferTime: 0,
    startOnBoot: true,
    enableHeadless: true,
    preventSuspend: false,
    stopOnTerminate: false,
    elasticityMultiplier: 1,
    foregroundService: true,
    disableElasticity: false,
    enableTimestampMeta: false,
    disableStopDetection: false,
    geofenceModeHighAccuracy: true,
    useSignificantChangesOnly: false,
    disableAutoSyncOnCellular: false,
    disableMotionActivityUpdates: false,
    distanceFilter: distanceFilter ?? 9,
    disableLocationAuthorizationAlert: false,
    activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
    locationAuthorizationAlert: {
      titleWhenNotEnabled: t('title_when_not_enabled'),
      titleWhenOff: t('title_when_off'),
      instructions: t('location_auth_alert_instructions'),
      cancelButton: t('location_auth_alert_cancel'),
      settingsButton: t('location_auth_alert_settings'),
    },
    stopTimeout: 5,
    desiredOdometerAccuracy: 10,
    backgroundPermissionRationale: {
      title: 'Allow "App" to use your location?',
      message:
        'Please select "Change to Always Allow" below so "App" can access your location even when you are not using the app.',
      positiveAction: 'Change to "Always Allow"',
      negativeAction: 'Cancel',
    },
  })

## Expected Behavior
BackgroundGeolocation.onGeofence should work on Android in Killed State

## Actual Behavior
BackgroundGeolocation.onGeofence is not working on Android in Killed State

## Steps to Reproduce

1.Add Above-mentioned Config for Android Device
2. Move Android Device to killed State
3.geofence event will not trigger for Android in killed State

## Debug logs
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {},
  "autoSync": true,
  "autoSyncThreshold": 0,
  "backgroundPermissionRationale": {
    "title": "Allow \"App\" to use your location?",
    "message": "Please select \"Change to Always Allow\" below so App can access your location even when you are not using the app.",
    "positiveAction": "Change to \"Always Allow\"",
    "negativeAction": "Cancel"
  },
  "batchSync": false,
  "configUrl": "",
  "crashDetector": {
    "enabled": false,
    "accelerometerThresholdHigh": 20,
    "accelerometerThresholdLow": 4.5,
    "gyroscopeThresholdHigh": 20,
    "gyroscopeThresholdLow": 4.5
  },
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 10,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableProviderChangeRecord": false,
  "disableStopDetection": false,
  "distanceFilter": 9,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": true,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 5,
  "logMaxDays": 3,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxMonitoredGeofences": 97,
  "maxRecordsToPersist": -1,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "channelId": "",
    "smallIcon": "",
    "largeIcon": "",
    "priority": -1,
    "sticky": false,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 4757.9638671875,
  "isFirstBoot": true,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
<details><summary>Logs</summary>
[background-geolocation (20).log](https://github.com/user-attachments/files/17231194/background-geolocation.20.log)
</details>

**Comment by christocracy** [comment]
>BackgroundGeolocation.onGeofence is not working on Android in Killed State #2160

Do you know that your React Native App no longer exists when an Android app is terminated (including your event-listener `BackgroundGeolocation.onGeofence`)?

- See API docs `Config.enableHeadless`
- See Wiki ["Android Headless Mode"](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode)
- When having issues, enable `debug: true` so that you can *hear* Debug SoundFX (geofence events play a unique debug sound-effect, proving the geofence event did indeed fire).

**Comment by mshehzad1** [comment]
Hi @christocracy 

Kindly let us know if the Geo Fence will work on Kill State in Android or not?

Thanks,

**Comment by christocracy** [comment]
> Geo Fence will work on Kill State in Android or not?

Everything in this plug-in can work in the Android terminated state.

**Comment by alihasan21987** [comment]
Plugin Version: 4.16.5
OS: Android
React Native Version: 0.70.6
Device Modal: Samsung S22+

Plugin Configuration:
BackgroundGeolocation.ready({
    debug: false,
    locationAuthorizationRequest: 'Always',
    showsBackgroundLocationIndicator: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    desiredAccuracy: desiredAccuracy
      ? desiredAccuracy
      : BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    deferTime: 0,
    startOnBoot: true,
    enableHeadless: true,
    preventSuspend: false,
    stopOnTerminate: false,
    elasticityMultiplier: 1,
    foregroundService: true,
    disableElasticity: false,
    enableTimestampMeta: false,
    disableStopDetection: false,
    geofenceModeHighAccuracy: true,
    useSignificantChangesOnly: false,
    disableAutoSyncOnCellular: false,
    disableMotionActivityUpdates: false,
    distanceFilter: distanceFilter ?? 9,
    disableLocationAuthorizationAlert: false,
    activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
    locationAuthorizationAlert: {
      titleWhenNotEnabled: t('title_when_not_enabled'),
      titleWhenOff: t('title_when_off'),
      instructions: t('location_auth_alert_instructions'),
      cancelButton: t('location_auth_alert_cancel'),
      settingsButton: t('location_auth_alert_settings'),
    },
    stopTimeout: 5,
    desiredOdometerAccuracy: 10,
    backgroundPermissionRationale: {
      title: 'Allow "App" to use your location?',
      message:
        'Please select "Change to Always Allow" below so App can access
your location even when you are not using the app.',
      positiveAction: 'Change to "Always Allow"',
      negativeAction: 'Cancel',
    },
  })

BackgroundGeolocation.onGeofence(async (geofence) => {
  console.log('[onGeofence]  ');
});

@christocracy <https://github.com/christocracy>
I am not getting any log inside my geo-fence event on Android. Can you
please consider the above settings and tell me what I am doing wrong??

**Comment by christocracy** [comment]
1.  Listen to events **before** calling .ready(config).
2. you’re not providing the geofence attributes.
3. See wiki “Debugging” and learn to observe the plug-in logs.  Use `debug: true`
4. Create a geofence around the current location.
5. Test on a real device, not emulator or mock location.

**Comment by alihasan21987** [comment]
Hi @christocracy <https://github.com/christocracy>,

I have just tested the Android Device (on Real Device) with Kill and
background State and I have got all notifications when app was in
background state, but I didn't get any notification in kill state.

**Comment by christocracy** [comment]
>but I didn't get any notification in kill state.

Post your code which you're expecting to execute in the *terminated* state.

**Comment by alihasan21987** [comment]
Hi @christocracy <https://github.com/christocracy>,

Here I am mentioning my code that runs in terminated state

if (event.name === 'geofence') {
console.log('[Headless Geofence Triggered ] :')
}

**Comment by abhayciitizen** [comment]
Background service running properly i can see in ADB logcat. but ` BackgroundGeolocation.onGeofence((geofence) => {` not showing anything in console when app is closed/terminated. also my api not getting called for this in background mode.

```
const configureBackgroundGeolocation = () => {
    BackgroundGeolocation.onGeofence((geofence) => {
      console.log('Geofence event:', geofence);
      sendNotificationApi(devicetoken, `${JSON.stringify(geofence.identifier)} event Name ${geofence.action}` )
    });

    BackgroundGeolocation.onLocation(
      location => {
        console.log('Location mil gaya: ', location);
        // sendNotificationApi(devicetoken, JSON.stringify(location))
      },
      error => {
        console.error('[ERROR] BackgroundGeolocation location error: ', error);
      }
    );

    BackgroundGeolocation.ready({
      reset: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stationaryRadius: 10,
      debug: true,
      activityRecognitionInterval: 1000,
      stopTimeout: 60,
      disableMotionActivityUpdates: false,
      disableElasticity: true,
      startOnBoot: true,
      heartbeatInterval: 60,
      enableHeadless: true,
      stopOnTerminate: false,
      desiredOdometerAccuracy: 10,
      allowIdenticalLocations: false,
      autoSync: true,
      autoSyncThreshold: 0,
      batchSync: true,
      maxBatchSize: 10,
      maxDaysToPersist: 2,
      foregroundService: true,
      locationAuthorizationRequest: 'Always',
      geofenceInitialTriggerEntry: true,
      geofenceModeHighAccuracy: true,
    })
      .then((state) => {
        if (!state.enabled) {
          console.log('BackgroundGeolocation state:', state);
          BackgroundGeolocation.start().then(() => {
            BackgroundGeolocation.changePace(true)
            BackgroundGeolocation.startGeofences();
          })


        }
      })
      .catch((error) => {
        console.error("BackgroundGeolocation error: ", error);
      });

    pharmacies.forEach((pharmacy) => {
      BackgroundGeolocation.addGeofence({
        identifier: pharmacy.name,
        radius: 200,
        latitude: pharmacy.latitude,
        longitude: pharmacy.longitude,
        notifyOnEntry: true,
        notifyOnExit: true,
      })
        .then(() => {
          console.log(`Geofence added for ${pharmacy.name}`);
        })
        .catch((error) => {
          console.error(`Failed to add geofence for ${pharmacy.name}:`, error);
        });
    });

    BackgroundFetch.configure(
      { minimumFetchInterval: 1, stopOnTerminate: false, startOnBoot: true, enableHeadless: true },
      async (taskId) => {
        console.log('[BackgroundFetch] taskId:', taskId);
        try {
          const location = await BackgroundGeolocation.getCurrentPosition({ persist: false });
          console.log("Fetched Location:", location);
          BackgroundGeolocation.sync();
        } catch (error) {
          console.error("Error fetching location:", error);
        } finally {
          BackgroundFetch.finish(taskId);
        }
      },
      (error) => {
        console.error("Failed to start BackgroundFetch:", error);
      }
    );
  };
```
Also registered `HeadlessTask` on `index.js`.

getting below logs when app in background.
```
[BackgroundGeolocation HeadlessTask] - connectivitychange {"connected": true}
 LOG  [BackgroundGeolocation HeadlessTask] - providerchange {"accuracyAuthorization": 0, "airplane": false, "enabled": true, "gps": true, "network": true, "status": 3}
 
 LOG  [BackgroundGeolocation HeadlessTask] - heartbeat {"location": {"activity": {"confidence": 100, "type": "still"}, "age": 92382, "battery": {"is_charging": false, "level": 1}, "coords": {"accuracy": 5, "age": 92405, "altitude": 5, "altitude_accuracy": 0.5, "ellipsoidal_altitude": 5, "heading": -1, "heading_accuracy": -1, "latitude": 37.4219983, "longitude": -122.084, "speed": 0, "speed_accuracy": 0.5}, "event": "heartbeat", "extras": {}, "is_moving": false, "odometer": 0, "timestamp": "2024-10-04T23:16:23.766Z", "uuid": "286ad744-73f8-4aca-abb2-094a25983df0"}}
 LOG  [BackgroundGeolocation HeadlessTask] - location {"activity": {"confidence": 100, "type": "still"}, "age": 93289, "battery": {"is_charging": false, "level": 1}, "coords": {"accuracy": 5, "age": 93291, "altitude": 5, "altitude_accuracy": 0.5, "ellipsoidal_altitude": 5, "heading": -1, "heading_accuracy": -1, "latitude": 37.4219983, "longitude": -122.084, "speed": 0, "speed_accuracy": 0.5}, "extras": {}, "is_moving": false, "odometer": 0, "timestamp": "2024-10-04T23:16:23.766Z", "uuid": "b6cb9551-a3ae-47c5-bb4d-64917dc7ad4d"}
 
 LOG  [BackgroundGeolocation HeadlessTask] - geofenceschange {"off": [], "on": [{"identifier": "inner 100 saiyaa", "latitude": 26.542859596060282, "loiteringDelay": 0, "longitude": 81.82117611431354, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 150, "vertices": [Array]}, {"identifier": "100 Saiyaa", "latitude": 26.542985215887246, "loiteringDelay": 0, "longitude": 81.8218620541008, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 150, "vertices": [Array]}, {"identifier": "100 meter ahead 100 Saiyaa", "latitude": 26.542487, "loiteringDelay": 0, "longitude": 81.82434, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 150, "vertices": [Array]}, {"identifier": "Pharmacy A", "latitude": 37.33233141, "loiteringDelay": 0, "longitude": -122.0312186, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 150, "vertices": [Array]}, {"identifier": "mera room", "latitude": 26.54319315813604, "loiteringDelay": 0, "longitude": 81.8208408691654, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "Pharmacy Aabch", "latitude": 37.33233141, "loiteringDelay": 0, "longitude": -122.0312186, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "Pharmacy B", "latitude": 37.4219983, "loiteringDelay": 0, "longitude": -122.084, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "cms house", "latitude": 26.54321539903931, "loiteringDelay": 0, "longitude": 81.8216463768402, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "jodhu place", "latitude": 26.54285509587527, "loiteringDelay": 0, "longitude": 81.82116903895884, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "meraaaaaaaaa room", "latitude": 26.54319315813604, "loiteringDelay": 0, "longitude": 81.8208408691655, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "main 100 saiyaa", "latitude": 26.542646030550664, "loiteringDelay": 0, "longitude": 81.82235243912886, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "kirana dookan", "latitude": 26.55332044551055, "loiteringDelay": 0, "longitude": 81.83806277101311, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "khandasa mod", "latitude": 26.551466898647583, "loiteringDelay": 0, "longitude": 81.83932450409736, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "right  side  uppcl", "latitude": 26.545710607440256, "loiteringDelay": 0, "longitude": 81.8299889966165, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}, {"identifier": "uppcl left side", "latitude": 26.545863450894544, "loiteringDelay": 0, "longitude": 81.82995622732385, "notifyOnDwell": false, "notifyOnEntry": true, "notifyOnExit": true, "radius": 200, "vertices": [Array]}]}
 
 LOG  [BackgroundGeolocation HeadlessTask] - getCurrentPosition: {"activity": {"confidence": 100, "type": "still"}, "age": 93289, "battery": {"is_charging": false, "level": 1}, "coords": {"accuracy": 5, "age": 93291, "altitude": 5, "altitude_accuracy": 0.5, "ellipsoidal_altitude": 5, "heading": -1, "heading_accuracy": -1, "latitude": 37.4219983, "longitude": -122.084, "speed": 0, "speed_accuracy": 0.5}, "extras": {}, "is_moving": false, "odometer": 0, "timestamp": "2024-10-04T23:16:23.766Z", "uuid": "b6cb9551-a3ae-47c5-bb4d-64917dc7ad4d"}
```
Please suggest where i am doing wrong.

**Comment by christocracy** [comment]
Are you actually going outside and moving into / out of geofences to test?

are you configuring the plug-in with debug: true so you can *hear* the geofence events?

**Comment by abhayciitizen** [comment]
yes, debug is true and also moving into / out of geofences. I didn't saw any request of my notification api call but it worked in app running state.

**Comment by christocracy** [comment]
See https://dontkillmyapp.com 

are you observing your logs?  See wiki “Debugging”.

**Comment by abhayciitizen** [comment]
`See wiki “Debugging”.` I think i am able to hear `tun sound` when reach geofencing but not sure it's for geofencing because i am not receiving any notification (my api not got hit which i am calling firebase rest api for notification on geofencing). Could you please confirm can a make rest api call for geofencing in background ?

**Comment by christocracy** [comment]
See api docs Config.debug to learn what the debug sound fx mean.

**Comment by abhayciitizen** [comment]
sure will go through. Could you pls also reply on this if possible `Could you please confirm can 
i make rest api call for geofencing in background ?`

**Comment by christocracy** [comment]
You’re free to do whatever you wish in your event-handlers.  The plug-ins responsibility ends when your event-handler has been executed.

**Comment by christocracy** [comment]
And in the Android terminated state, your event handler IS your registered HeadlessTask.

**Comment by abhayciitizen** [comment]
below is my HeadlessTask code on index.js

```
let HeadlessTask = async (event) => {
  let params = event.params;
  console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);

  switch (event.name) {
    case 'geofence':
      const geofence = event.params;
      console.log('Headless Geofence event:', geofence);
      sendNotificationApi(geofence.identifier, `You have entered ${geofence.identifier}`);
      break;
    case 'heartbeat':
      // Use await for async tasks
      let location = await getCurrentPosition();
      let geofencee = await getgeofence()
      console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
      console.log('[BackgroundGeolocation HeadlessTask Geofence] - GeFencess :', geofencee);
      break;
  }
}
let getCurrentPosition = () => {
  return new Promise((resolve) => {
    BackgroundGeolocation.getCurrentPosition(
      {
        samples: 1,
        persist: false
      },
      (location) => {
        resolve(location);
      }, (error) => {
        resolve(error);
      });
  });

  
};
let getgeofence= () => {
  return new Promise((resolve) => {
    BackgroundGeolocation.onGeofence((geofence) => {
      resolve(geofence);
      console.log('Geofence event:', geofence);
    });
  });

  
};
BackgroundGeolocation.registerHeadlessTask(HeadlessTask);
```

Please see if anything wrong here.

**Comment by christocracy** [comment]
What is this??  Delete it.  It does not belong in index.js:

```
let getCurrentPosition = () => {
  return new Promise((resolve) => {
    BackgroundGeolocation.getCurrentPosition(
      {
        samples: 1,
        persist: false
      },
      (location) => {
        resolve(location);
      }, (error) => {
        resolve(error);
      });
  });

  
};
let getgeofence= () => {
  return new Promise((resolve) => {
    BackgroundGeolocation.onGeofence((geofence) => {
      resolve(geofence);
      console.log('Geofence event:', geofence);
    });
  });

```

**Comment by abhayciitizen** [comment]
I am keep receiving below logs only in ADB Logcat.
```
2024-10-05 23:51:22.866  4483-7581  ReactNativeJS           com.firebase.honest                  I  '[BackgroundGeolocation HeadlessTask] -', 'heartbeat', { location: 
                                                                                                       { extras: {},
                                                                                                         battery: { level: 1, is_charging: false },
                                                                                                         activity: { confidence: 100, type: 'still' },
                                                                                                         is_moving: false,
                                                                                                         uuid: 'e3ec0a6f-0eec-4a1d-b7f9-3e22252c02b8',
                                                                                                         age: 114486,
                                                                                                         coords: 
                                                                                                          { age: 114489,
                                                                                                            ellipsoidal_altitude: 5,
                                                                                                            altitude: 5,
                                                                                                            altitude_accuracy: 0.5,
                                                                                                            heading_accuracy: -1,
                                                                                                            heading: -1,
                                                                                                            speed: -1,
                                                                                                            accuracy: 5.1,
                                                                                                            longitude: -122.084,
                                                                                                            speed_accuracy: 0.5,
                                                                                                            latitude: 37.4219983 },
                                                                                                         timestamp: '2024-10-05T18:19:28.304Z',
                                                                                                         odometer: 0,
                                                                                                         event: 'heartbeat' } }
```

```
2024-10-05 23:49:37.751  4483-4573  ReactNativeJS           com.firebase.honest                  I  '[BackgroundGeolocation HeadlessTask] -', 'location', { extras: {},
                                                                                                      battery: { level: 1, is_charging: false },
                                                                                                      activity: { confidence: 100, type: 'still' },
                                                                                                      is_moving: false,
                                                                                                      age: 9442,
                                                                                                      uuid: '3a01686b-f366-429f-a07e-2c31aa119cf9',
                                                                                                      odometer: 0,
                                                                                                      coords: 
                                                                                                       { age: 9443,
                                                                                                         ellipsoidal_altitude: 5,
                                                                                                         altitude: 5,
                                                                                                         altitude_accuracy: 0.5,
                                                                                                         heading_accuracy: -1,
                                                                                                         heading: -1,
                                                                                                         speed: -1,
                                                                                                         accuracy: 5.1,
                                                                                                         longitude: -122.084,
                                                                                                         speed_accuracy: 0.5,
                                                                                                         latitude: 37.4219983 },
                                                                                                      timestamp: '2024-10-05T18:19:28.304Z' }
```

not for `geofence`

**Comment by abhayciitizen** [comment]
When i switched from killed mode to open App getting below log from below code.
```
BackgroundGeolocation.onGeofence((geofence) => {
      console.log('Geofence event:', geofence);
      sendNotificationApi(devicetoken, `${JSON.stringify(geofence.identifier)} event Name ${geofence.action}`)
    });
``` 

 LOG  Geofence event: 
 ```
 {"action": "ENTER", "identifier": "meraaaaaaaaa room", "location": {"activity": {"confidence": 100, "type": "still"}, "age": 140, "battery": {"is_charging": false, "level": 0.4}, "coords": {"accuracy": 22.8, "age": 143, "altitude": -1, "altitude_accuracy": -1, "ellipsoidal_altitude": -1, "heading": -1, "heading_accuracy": 45, "latitude": 26.5432954, "longitude": 81.8206723, "speed": -1, "speed_accuracy": 1.5}, "event": "geofence", "extras": {}, "geofence": {"action": "ENTER", "identifier": "meraaaaaaaaa room", "timestamp": "2024-10-05T19:00:26.694Z"}, "is_moving": false, "odometer": 18045.19921875, "timestamp": "2024-10-05T19:00:26.552Z", "uuid": "438b69f3-14ee-425b-aac4-d76861d3f1ca"}, "timestamp": "2024-10-05T19:00:26.694Z"}
 ```
 but no log on killed mode. Basically this the the my requirement which help me decide to go with pro or not.
 Pls help me to fix this.

**Comment by abhayciitizen** [comment]
I think i found the the reproduce steps. Basically it's status getting change where i can see `moving activities`  to `"on_foot", "walking"`. but now console.log printing for below codes when app is killed or background state.

```
BackgroundGeolocation.onGeofence((geofence) => {
      console.log('Geofence event:', geofence);
    });
```

 
```
BackgroundGeolocation.onLocation(
      location => {
        console.log('Location mil gaya: ', location);
      },
      error => {
        console.error('[ERROR] BackgroundGeolocation location error: ', error);
      }
    );
```

**Comment by christocracy** [comment]
See https://dontkillmyapp.com my

**Comment by abhayciitizen** [comment]
> See https://dontkillmyapp.com my

Already followed this as per your previous comment.

**Comment by christocracy** [comment]
I suggest you install the demo app front the play store.  It post results to a server for you to view.

the demo app install link is at the top of this repo’s readme.

Select “advanced app” after install.  Long-press on map to add geofences.

**Comment by abhayciitizen** [comment]
I have downloaded the demo App from play store selected Advance app and created points. And visited locations on bike. During travel i heard the same sound what i hear from my App. Can check tracker info [here](https://tracker.transistorsoft.com/23bytes). I am not sure why my app not working(Api not getting called). Could you pls help me fix this. Basically i want make an api call when user enter in geofences. Let me know where i am doing wrong.

**Comment by christocracy** [comment]
The only thing I care about is the debug sound-effect signalling the plug-in responded to a geofence and a log-entry from your registered headlessTask.

The plug-in is not involved with showing notifications.

**Comment by abhayciitizen** [comment]
that's fine. my question is, is there any way to make api call from your plugin when user enter y geofences.
The my main motive of planning/testing to this plugin to notify an user when they enter to geofences.
Also want to let you know api getting called in foreground mode.
So please see if can help

**Comment by christocracy** [comment]
Thousands of people make api calls with this plug-in.

The plug-in is not involved with what you do in your HeadlessTask.  I suggest you seek support with whatever plugin you’re using to “make api calls”.

or implement the plugin’s own built-in http service and let it do it for you.  See api docs Config.url.
