### ISSUE TITLE
LICENSE VALIDATION FAILURE

### ISSUE THREAD

**Issue by linhkiubo98** [transistorsoft/react-native-background-geolocation#2164]
![image](https://github.com/user-attachments/assets/b8b051d8-6869-4536-9623-4799c2d2d6f2)

I have this issue, please help me
    "react-native-background-geolocation": "^4.17.2",

**Comment by christocracy** [comment]
Review the Android Setup Instructions.  Do NOT omit anything.

**Comment by linhkiubo98** [comment]
I have read your guide very carefully and appreciate it. I have also looked through the bugs in the bug list myself. But I really cannot fix it. Do you have any other advice for me?

**Comment by christocracy** [comment]
Post the following files:
1.  android/build.gradle
2. android/app/build.gradle

**Comment by linhkiubo98** [comment]
thank you for helping me

**Comment by linhkiubo98** [comment]
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.24"
        googlePlayServicesLocationVersion = "21.0.1"  
    }
    repositories {
        google()
        mavenCentral()
      maven { url("${project(':react-native-background-geolocation').projectDir}/libs") }
      maven { url("${project(':react-native-background-fetch').projectDir}/libs") }

    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
}

apply plugin: "com.facebook.react.rootproject"
allprojects {
    repositories {
        google()
        mavenCentral()
       maven { url("${project(':react-native-background-geolocation').projectDir}/libs") }
      maven { url("${project(':react-native-background-fetch').projectDir}/libs") }
    }
}

**Comment by christocracy** [comment]
What is your Order #?

**Comment by linhkiubo98** [comment]
I don't know much about English, can you help me get rid of the above error? Please.

**Comment by christocracy** [comment]
What is your Order #?

**Comment by linhkiubo98** [comment]
Sorry, I'm don't understand :(

**Comment by christocracy** [comment]
When a license is purchased, an email is received with proof of purchase and an “Order #”.  I need that order #.

**Comment by christocracy** [comment]
If you are not the person who purchased the license, then you need to talk your client.

**Comment by linhkiubo98** [comment]
<img width="351" alt="image" src="https://github.com/user-attachments/assets/3589430d-d47c-4c20-938d-e535d7b1f7b3">


I have registered the api key on google cloud console. But I don't see any mail. And I see this function still works fine when I run on develop environment

**Comment by christocracy** [comment]
The license key is not related to Google.

where did you get this license key you’re using?

**Comment by linhkiubo98** [comment]
https://developers.google.com/maps/documentation/android-sdk/get-api-key



I have react-native-maps and I followed the instructions at the following link to get the key, and I used that key for the library you provided.

**Comment by christocracy** [comment]
License keys for this plug-in are purchased [here](https://www.transistorsoft.com/shop/products/react-native-background-geolocation)

**Comment by linhkiubo98** [comment]
My AndroidManifest.xml have this


<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="my_key"/>
          <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="my_key" />
          <meta-data android:name="com.transistorsoft.locationmanager.polygon.license" android:value="my_key" />

**Comment by linhkiubo98** [comment]
Ok I will buy it, but if I don't buy it then it can only run on dev environment right? I need to explain to my client

**Comment by christocracy** [comment]
That’s correct.
