### ISSUE TITLE
stopOnTerminate name is misleading

### ISSUE THREAD

**Issue by farshid1** [transistorsoft/react-native-background-geolocation#217]
In the Doc, `stopOnTerminate`'s note says **"Set `true` to continue tracking after user terminates the app."** This is misleading because if you set `stopOnTerminate` to `true` then the app shouldn't continue tracking after user terminates the app (logically speaking).

**Comment by christocracy** [comment]
Reported already from the [Cordova folks](https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/296).  It's fixed on my local machine.

**Comment by farshid1** [comment]
Then just to double check, I have to set `stopOnTerminate` to `true` if I want the location to be tracked even when the user terminates the app?

**Comment by christocracy** [comment]
No.

- If you *want* the plugin to "stop on terminate", you would say `true`.
- If you do *NOT* want the plugin to "stop on terminate", you would say 'false`.

It's perfectly logical.  There is no ambiguity in the naming of this param.

**Comment by farshid1** [comment]
You are right. I guess you and I are looking at this from different ends. It is perfectly logical until the doc throws you off.

**Comment by christocracy** [comment]
When in doubt, read the config params like a sentence.  The docs were
recently had a significant refactor.  There are a few bugs.
-- 
Snet form Gmail Mobile
