### ISSUE TITLE
[DOC] :: request to include what you change in each release version

### ISSUE THREAD

**Issue by chanphiromsok** [transistorsoft/react-native-background-geolocation#2173]
![image](https://github.com/user-attachments/assets/b155ac1c-d81d-4c07-be50-a9bcdced9875)
 it is not easy when to upgrade plugin and we don't know what changed in each release

**Comment by mikehardy** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md

**Comment by christocracy** [comment]
@mikehardy !

**Comment by chanphiromsok** [comment]
that fun hahah I did't noticed the changelod in readme
