### ISSUE TITLE
HTTP response status is 0 instead of 401

### ISSUE THREAD

**Issue by JonasWho** [transistorsoft/react-native-background-geolocation#218]
## Your Environment
* Plugin version: 2.6.1
* Platform: iOS
* OS version: 10.2.1 (14D27)
* React Native version: 0.41.2
* Plugin config
```
{
    desiredAccuracy: 0,
    stationaryRadius: __DEV__ ? 1 : 15,
    distanceFilter: __DEV__ ? 1 : 10,
    stopDetectionDelay: 5,
    stopTimeout: 10, 
    preventSuspend: true,
    heartbeatInterval: 600,
    forceReload: true,
    forceReloadOnHeartbeat: true,
    forceReloadOnMotionChange: true,
    forceReloadOnLocationChange: true,
    forceReloadOnBoot: true,
    stopOnTerminate: false,
    startOnBoot: true, 
    debug: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    url: 'http://myurl.com/path',
    method: 'POST',
    autoSync: true,
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      'Authorization': 'Bearer xxx',
    },
  },
```

## Expected Behavior
`BgGeo.onHttp(succesFn, failureFn)` should use failureFn for everything else than status codes in the 200's.

## Actual Behavior
`failureFn` is never called, always `successFn` and always with status=0. Only 404 is returned correctly. Even is I type in a complete nonsense url, I still get `successFn` with status 0.

## Steps to Reproduce
Send expired (or empty) token to server-url in Authorization header.
Could it be related to this: http://stackoverflow.com/questions/2188099/nshttpurlresponse-statuscode-is-returning-zero-when-it-should-be-401

**Comment by christocracy** [comment]
Confirmed.  Fix will be posted to the premium repo today.  Why are you still using the Public repo?  You're a customer.  This repo now hosts only the latest stable release, typically updated every 1-3 months.  You need to start using the Private repo for both iOS & Android.

**Comment by JonasWho** [comment]
@christocracy Great! I know, it's a bit weird, but I work freelance for two different companies that both use your plugin, one is a customer, the other is not (yet) :)

**Comment by JonasWho** [comment]
@christocracy is it also fixed for other status codes than 401? Like I described, I never get any hits in my failureFn

**Comment by christocracy** [comment]
`401` is a special-case for iOS.  Following all work:

```javascript
res.send({success: true});
res.status(401).send("Unauthorized");
res.status(403).send("Forbidden");
res.status(201).send({success: true});
res.status(201).send({success: true});
res.status(427).send("Too many requests");
res.status(500).send("Internal Server Error");
res.status(404).send("Not Found");
res.status(408).send("Timeout");
```
