### ISSUE TITLE
I would like to receive location information periodically (1 minute).

### ISSUE THREAD

**Issue by lane4-wiz** [transistorsoft/react-native-background-geolocation#2181]
## Your Environment
* Plugin version: 4.17.1
* Platform: Android
* OS version: 10
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.72.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

heartbeatInterval: 60,

BackgroundGeolocation.onHeartbeat(event => {
        console.log('[onHeartbeat] ', dayjs().format('YYYY-MM-DD HH:mm:ss'), event);
        BackgroundGeolocation.getCurrentPosition({
          timeout: 30,
          maximumAge: 5000,
          samples: 1,
        }).then(location => {
          console.log('[getCurrentPosition] ', location);
        });
      }),
```

## Expected Behavior

It was implemented to receive location information every minute using heartbeat, but there are many cases where location information cannot be received within 1 minute.

Is there a way to receive location information with less error every minute?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by lane4-wiz** [comment]
Does heartbeat accuracy increase when the scheduleUseAlarmManager option is specified?

**Comment by lane4-wiz** [comment]
@christocracy Please check.

**Comment by christocracy** [comment]
> Does heartbeat accuracy increase when the scheduleUseAlarmManager option is specified?

No

**Comment by lane4-wiz** [comment]
@christocracy So, is there a way to periodically receive location information?

**Comment by christocracy** [comment]
>is there a way to periodically receive location information?

Yes, that's what [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch) is for (already included as a dependency).  See its README.

In your `BackgroundFetch` callback `function`, you're free to do anything you want, including `BackgroundGeolocaiton.getCurrentPosition(options)`.

**Comment by christocracy** [comment]
You'll never get a location "*every minutes*" while the device is stationary.

**Comment by Deepanshi09** [comment]
@christocracy but is it possible - Location updates occur every two minutes?

**Comment by christocracy** [comment]
While stationary, the best you’ll get is every 15 minutes, using background-fetch
