### ISSUE TITLE
Need Help when app is closed

### ISSUE THREAD

**Issue by Sameer98700** [transistorsoft/react-native-background-geolocation#2187]
Hi,

We are trying to integrate your React Native Background Geolocation Package in our project and facing below challenges -

1. When the user app is closed, then we need to send the current location of the user from android and iOS. We are only able to track the user but not able to receive the current location. Can you please guide which package or function we need to use in react native background geolocation package.

2. When the user is ideal and the app is closed then we are unable to track that user. After that once the user starts moving then also we are unable to track as the starting user was unable to track. Please guide me on how to solve this issue.

3. We added a geo facing function, when the user is away from the 50 meter radius then when the app is closed, we are unable to receive the log. But as soon as the app is open, we receive the logs. Need solution for this as well.

Facing both above uses majorly on iOS devices.

Kindly help us with the above query and give a solution to it.

**Comment by christocracy** [comment]
The issue template is **required**, not *optional*:




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Sameer98700** [comment]
Plugin version: 4.1.1
Platform: iOS or Android both
OS version: Mac OS 15.0.1 (24A348)
Device manufacturer / model: 15-inch, M2, 2023
React Native version (react-native -v): 0.74.4
Plugin config ----

**Comment by christocracy** [comment]
Also, your code is wrong.

```javascript
// Configure BackgroundGeolocation
    BackgroundGeolocation.ready({
      .
      .
      .
    }).then(state => {
      // Start the Scheduler
      BackgroundGeolocation.startSchedule();
    });
  };

  // Listen to #onSchedule events:
  BackgroundGeolocation.onSchedule(state => {
    let enabled = state.enabled;
    console.log('[onSchedule] - enabled? ', enabled);
  });

  // Or modify the schedule with usual #setConfig method
  BackgroundGeolocation.setConfig({
    schedule: [
      '1-7 9:00-10:00',
      '1-7 11:00-12:00',
      '1-7 13:41-13:44',
      '1-7 15:00-16:00',
      '1-7 17:00-18:00',
      '2,4,6 19:00-22:00',
    ],
  });
```

You're calling `.startSchedule()` before a schedule is guaranteed to have even been applied via `.setConfig`.   You need to add your `schedule` to the `Config` provided to `.ready(config)` or call `.setConfig` when `.ready(config)` has resolved.

Plugin method calls take an **unknown amount of time to execute.**  That's why they return a `Promise`.  It *could* happen that the `.ready(config)` method resolves *before* `.setConfig` or *after* -- it's unknown.  That's why you must use `await` or `.then()` and chain your method calls accordingly.

```javascript
BackgroundGeolocation.ready({
    .
    .
    .
    schedule: [
      '1-7 9:00-10:00',
      '1-7 11:00-12:00',
      '1-7 13:41-13:44',
      '1-7 15:00-16:00',
      '1-7 17:00-18:00',
      '2,4,6 19:00-22:00',
    ]
}).then((state) => {
  // Here, the Promise of the .ready method has RESOLVED.  Only now has the Config been applied.
  BackgroundGeolocation.startSchedule()
});

// It is unknown if the Promise of the .ready method has resolved yet.
// If .ready(config) resolves first, you will be calling `.startSchedule()` with an empty schedule.
BackgroundGeolocation.setConfig(config);

```

**Comment by christocracy** [comment]
I have a feeling you're just copy/pasting code with no understanding of how it actually works.

Also see Wiki "Debugging" and "Philosophy of Operation".

```
BackgroundGeolocation.logger
      .getLog()
      .then(log => {
        console.log('log', log);
      })
      .catch(error => {
        console.error('Error getting log:', error);
      });
```
It's pretty crazy how your console.log the plugin's `getLog` each time your app launches.  That log con be several megabytes.  Put a temporary button on your UI to execute `.emailLog` instead.

**Comment by Sameer98700** [comment]
How to turn off bg sound and continuously receive notifications
![Simulator Screenshot - iPhone 16 Pro - 2024-10-26 at 09 46 49](https://github.com/user-attachments/assets/bac2c05a-b955-47ff-8de2-5fee094d1f3c)

**Comment by Sameer98700** [comment]
Hey,

I updated to the latest version 4.17.4 in Android, and it is working fine
but in ios BackgroundGeoLocation.onLocation function does not fire when the
app is closed.
previously version 4.1.1 BackgroundGeoLocation.onLocation worked in ios

Note -- I added in the index.js file

**Comment by christocracy** [comment]
>Note -- I added in the index.js file

You added *what* in the `index.js` file?

**Comment by Sameer98700** [comment]
BackgroundGeoLocation.onLocation

**Comment by Sameer98700** [comment]
This is for android
what we do for ios?

**Comment by christocracy** [comment]
iOS terminated behaviour is easily tested in the iOS simulated with location simulated with *Freeway Drive*.

<img width="722" alt="Screenshot 2024-10-28 at 10 44 35 AM" src="https://github.com/user-attachments/assets/9b7e461d-d937-44ef-9275-11ca93ed17ab">

**Comment by christocracy** [comment]
>what we do for ios?

iOS will automatically relaunch your app in the background when the device is detected to be moving, just as if launched by the user from the foreground.

**Comment by Sameer98700** [comment]
Yes I know but when app is terminated then how to show updated location
logs and which function provide me a logs

**Comment by christocracy** [comment]
> then how to show updated location

on iOS, every recorded location is sent to your `.onLocation` event-listener.

**Comment by christocracy** [comment]
Search API docs "emailLog"

**Comment by Sameer98700** [comment]
This is not working for me

**Comment by christocracy** [comment]
"what" is not working for you?

**Comment by Sameer98700** [comment]
How it works?

**Comment by christocracy** [comment]
How "what" works?

**Comment by christocracy** [comment]
Are you testing your app in the iOS Simulator, simulating location with *Freeway Drive*?

**Comment by Sameer98700** [comment]
Yes

**Comment by christocracy** [comment]
Show me logs of your app launching in the iOS simulator.
