### ISSUE TITLE
iOS BackgroundGeoLocation.onLocation not working when app is closed

### ISSUE THREAD

**Issue by Sameer98700** [transistorsoft/react-native-background-geolocation#2190]
## Your Environment
* Plugin version: 4.17.4
* Platform: iOS
* OS version: Mac OS 15.0.1 (24A348)
* Device manufacturer / model: iPhone 16 pro simulator
* React Native version (`react-native -v`):  0.74.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```
React.useEffect(() => {

    BackgroundGeolocation.deviceSettings.showIgnoreBatteryOptimizations();

    // Setup geofence event listener
    BackgroundGeolocation.onGeofence(async geofence => {
      console.log('Geofence event:', geofence);

      // Check if exiting Geofence A
      if (geofence.action === 'EXIT' && geofence.identifier === 'GEOFENCE_A') {
        console.log('Exiting Geofence A. Sending location to server...');

        // Get the current location
        const location = await BackgroundGeolocation.getCurrentPosition({
          timeout: 30,
          maximumAge: 10000,
          persist: true,
          extras: {event: 'geofence-exit'},
        });

        // Send location to your server
        sendLocationToServer(location);

        // Remove Geofence A
        BackgroundGeolocation.removeGeofence('GEOFENCE_A');

        // Add new geofence
        addNewGeofence(location);
      }
    });

    // Listen to location updates
    BackgroundGeolocation.onLocation(handleLocationUpdate, error => {
      console.log('[BackgroundGeolocation] Location error:', error);
    });

    // Initialize background geolocation and fetch
    initBackgroundGeolocation();
    initBackgroundFetch();

    // Cleanup on unmount
    return () => {
      // BackgroundGeolocation.removeListeners();
    };
  }, []);

  const initBackgroundGeolocation = async () => {
   
    BackgroundGeolocation.ready({
      reset: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      stationaryRadius: 50,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      debug: true,
      activityRecognitionInterval: 1000,
      stopTimeout: 60,
      disableMotionActivityUpdates: false,
      disableElasticity: true,
      startOnBoot: true,
      heartbeatInterval: 60,
      enableHeadless: true,
      stopOnTerminate: false,
      desiredOdometerAccuracy: 10,
      allowIdenticalLocations: false,
      autoSync: true,
      autoSyncThreshold: 0,
      batchSync: true,
      maxBatchSize: 10,
      maxDaysToPersist: 2,
      foregroundService: true,
      locationAuthorizationRequest: 'Always',
      geofenceInitialTriggerEntry: true,
      geofenceModeHighAccuracy: true,
      notification: {
        title: 'Location Tracking',
        text: 'Tracking location in the background',
        color: '#ff00ff',
      },
    }).then(state => {
      BackgroundGeolocation.start();
    });
  };

## Steps to Reproduce

1.
2.
3.
4.

## Context

I updated to the latest version 4.17.4 in Android it is working fine but in ios BackgroundGeoLocation.onLocation function does not fire when the app is closed.
previously version 4.1.1 BackgroundGeoLocation.onLocation worked in ios

Note -- I added in the index.js file

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you testing in the iOS simulator with “Freeway Drive”?

**Comment by Sameer98700** [comment]
Yess

**Comment by christocracy** [comment]
And you’re saying you don’t see debug notifications appear after terminating the app while simulating location with “Freeway Drive”?

**Comment by Sameer98700** [comment]
Yes, previously it is working fine in 4.1.1

**Comment by christocracy** [comment]
Show me logs of your app launching in XCode.

**Comment by Sameer98700** [comment]
Please check


<img width="1710" alt="Screenshot 2024-10-28 at 10 22 37 AM" src="https://github.com/user-attachments/assets/25855696-420a-4f9c-ba29-969fb5329c74">
<img width="1710" alt="Screenshot 2024-10-28 at 10 23 19 AM" src="https://github.com/user-attachments/assets/770d3561-becb-4856-b456-c63e29d484df">
<img width="1705" alt="Screenshot 2024-10-28 at 10 24 07 AM" src="https://github.com/user-attachments/assets/ce364e9d-96c4-4688-a58f-7a89176470e5">

**Comment by christocracy** [comment]
Post text of logs, not screenshots

**Comment by Sameer98700** [comment]
objc[21870]: Class AKAlertImageURLProvider is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AuthKitUI.framework/AuthKitUI (0x149b55820) and /Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AuthKit.framework/AuthKit (0x123041738). One of the two will be used. Which one is undefined.
objc[21870]: Class AKBiometricRatchetUtility is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AuthKitUI.framework/AuthKitUI (0x149b55898) and /Library/Developer/CoreSimulator/Volumes/iOS_22A3351/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AuthKit.framework/AuthKit (0x123042e30). One of the two will be used. Which one is undefined.
[TSBackgroundFetch load]: (
)
[TSBGAppRefreshSubscriber load]: {
    TSLocationManager = "<TSBGAppRefreshSubscriber identifier=TSLocationManager, executed=0, enabled=1>";
    "react-native-background-fetch" = "<TSBGAppRefreshSubscriber identifier=react-native-background-fetch, executed=0, enabled=1>";
}
10.29.0 - [FirebaseMessaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
[RNVoipPushNotificationManager] voipRegistration enter
10.29.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.29.0 started
10.29.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[TSBackgroundFetch registerForTaskWithIdentifier: com.transistorsoft.customtask
10.29.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
nw_connection_copy_connected_local_endpoint_block_invoke [C1] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C1] Connection has no local endpoint
Running application hiappy ({
    initialProps =     {
        concurrentRoot = 0;
    };
    rootTag = 1;
})
10.29.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
10.29.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
[RNCallKeep][init]
+[RNFBAppModule getCustomDomain:] [Line 239] authDomains: (null)
<Warning>: You haven't set a value for FacebookAdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results.
<Warning>: The value for FacebookAdvertiserIDCollectionEnabled is currently set to FALSE so you're sending app events without collecting Advertiser ID. This can affect the quality of your advertising and analytics results.
[RNVoipPushNotificationManager] didUpdatePushCredentials credentials.token = {length = 80, bytes = 0x804d041a 1537bb58 7a59b0b9 33b3ba94 ... 4784dede 078d0ed6 }, type = PKPushTypeVoIP
nw_connection_copy_connected_local_endpoint_block_invoke [C1] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C5] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C5] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C6] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C6] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C7] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C7] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C5] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C6] Connection has no local endpoint
FBSDKLog: starting with Graph API v2.4, GET requests for /528432449554410/model_asset should contain an explicit "fields" parameter
FBSDKLog: starting with Graph API v2.4, GET requests for /528432449554410/ios_skadnetwork_conversion_config should contain an explicit "fields" parameter
nw_connection_copy_connected_local_endpoint_block_invoke [C7] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C12] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C12] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C13] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C13] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C14] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C14] Connection has no local endpoint
nw_socket_handle_socket_event [C18.1.1:1] Socket SO_ERROR [61: Connection refused]
nw_endpoint_flow_failed_with_error [C18.1.1 '00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01'.8097 in_progress socket-flow (satisfied (Path is satisfied), interface: lo0)] already failing, returning
nw_socket_handle_socket_event [C18.1.2:1] Socket SO_ERROR [61: Connection refused]
nw_endpoint_flow_failed_with_error [C18.1.2 16777343:8097 in_progress socket-flow (satisfied (Path is satisfied), interface: lo0)] already failing, returning
nw_endpoint_flow_failed_with_error [C18.1.2 16777343:8097 cancelled socket-flow ((null))] already failing, returning
nw_connection_get_connected_socket_block_invoke [C18] Client called nw_connection_get_connected_socket on unconnected nw_connection
TCP Conn 0x600000126800 Failed : error 0:61 [61]
nw_connection_copy_connected_local_endpoint_block_invoke [C13] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C14] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C12] Connection has no local endpoint
Session replay disabled via configuration
Unbalanced calls start/end for tag 19
Running "hiappy" with {"rootTag":1,"initialProps":{"concurrentRoot":false}}
-[RNFBMessagingModule signalBackgroundMessageHandlerSet] [Line 104] signalBackgroundMessageHandlerSet called
-[RNFBMessagingAppDelegate signalBackgroundMessageHandlerSet] [Line 74] signalBackgroundMessageHandlerSet sharedInstance.backgroundMessageHandlerSet was NO
nw_connection_copy_connected_local_endpoint_block_invoke [C24] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C24] Connection has no local endpoint
[GESTURE HANDLER] Initialize gesture handler for view <RCTRootContentView: 0x30bd2d530; frame = (0 0; 402 874); gestureRecognizers = <NSArray: 0x60000325dde0>; layer = <CALayer: 0x60000302d1e0>> reactTag: 1; frame = {{0, 0}, {402, 874}}; layer = <CALayer: 0x60000302d1e0>
🔑 Found cached TransistorAuthorizationToken for host tracker.transistorsoft.com
[TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
[TSBackgroundFetch] BGTaskScheduler failed to register fetch-task and will fall-back to old API.  This is likely due to running in the iOS Simulator (Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)")
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
'[BackgroundGeolocation] Location error:', 0
'[BackgroundGeolocation] Location error:', 0
nw_connection_copy_connected_local_endpoint_block_invoke [C36] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C36] Connection has no local endpoint
Google Maps SDK for iOS version: 7.4.0.0
New version of Google Maps SDK for iOS available: 9.1.1.0
Possible Unhandled Promise Rejection (id: 0):
No iOS Implementation

**Comment by Sameer98700** [comment]
I posted on git please check

**Comment by christocracy** [comment]
> '[BackgroundGeolocation] Location error:', 0

Do you know what that means?

> logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE

are you sure that the config you posted to this issue is the one you’re actually using??  There should be more logs from the plug-in.

**Comment by Sameer98700** [comment]
> > '[BackgroundGeolocation] Location error:', 0
> 
> Do you know what that means?
> 
> > logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
> 
> are you sure that the config you posted to this issue is the one you’re actually using?? There should be more logs from the plug-in.

[BackgroundGeolocation] Location error:', 0 
Yes, I know this when you not moving or not running that's why this log shows

 are you sure that the config you posted to this issue is the one you’re actually using?? There should be more logs from the plug-in.

Yes I sure there no extra logs

**Comment by christocracy** [comment]
> Yes, I know this when you not moving or not running

That’s not what it means.  It means the device’s native location api failed to provide a location.  One way this can happen is you haven’t granted your app location permission.  Or you’re in a place where location is not possible (eg a tunnel).

you should see much more logs from the plug-in in Xcode.

**Comment by Sameer98700** [comment]
> > Yes, I know this when you not moving or not running
> 
> That’s not what it means. It means the device’s native location api failed to provide a location. One way this can happen is you haven’t granted your app location permission. Or you’re in a place where location is not possible (eg a tunnel).
> 
> you should see much more logs from the plug-in in Xcode.
<img width="416" alt="Screenshot 2024-10-29 at 9 53 50 AM" src="https://github.com/user-attachments/assets/dfeed97f-7bb2-43f8-8734-58b7df38344a">


Location permission has been given also if I haven’t granted app location permission then it will not work with maps and will not update the location. when turning on the freeway drive it is working fine background.onLocation function but the app was killed, and then it not work

**Comment by christocracy** [comment]
Launch your app in XCode.  Show me the logs shown.
