### ISSUE TITLE
iOS devices throwing INVALID_TASK_ID exception

### ISSUE THREAD

**Issue by mcottingham** [transistorsoft/react-native-background-geolocation#2194]
## Your Environment
* Plugin version: 4.17.2
* Platform: iOS
* OS version: 17.6.1
* Device manufacturer / model: iPhone SE, 12, 13, 14
* React Native version (`react-native -v`): 0.74.5
* Plugin config
```javascript

  /* _layout.js */

    const activityListener = useRef();
    const locationListener = useRef();
    const heartbeatListener = useRef();
    const geofenceListener = useRef();
    const motionListener = useRef();
    const [bgGeolocationReady, setBGGeolocationReady] = useState(false);

    useEffect(() => {
        activityListener.current = BackgroundGeolocation.onActivityChange(event => store.dispatch(setStatus({ activity: event.activity, activityConfidence: event.confidence })));
        geofenceListener.current = BackgroundGeolocation.onGeofencesChange(event => console.log("Geofence change", event));
        motionListener.current = BackgroundGeolocation.onMotionChange(event => store.dispatch(setStatus({ motion: event.isMoving ? 'MOVING' : 'STOPPED' })))

        locationListener.current = BackgroundGeolocation.onLocation(onLocation);
        heartbeatListener.current = BackgroundGeolocation.onHeartbeat(async (event) => {
            store.dispatch(setStatus({ heartbeat: moment(event.location?.timestamp).format("hh:mm:ss") }))
            await onLocation()
        });

        BackgroundGeolocation.ready({
            //Debug
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,

            //GeoLocation
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            preventSuspend: true,
            stationaryRadius: 25,
            heartbeatInterval: 60,
            showsBackgroundLocationIndicator: true,

            //Application
            startOnBoot: true,
            stopOnTerminate: false,
            enableHeadless: true,

            //Notification
            foregroundService: true,
            notification: {
                title: "Be Safe - On Shift",
                text: "Be Safe is monitoring your location, keeping you safe.",
                color: theme.palette.green,
                sticky: true,
            },

            locationAuthorizationRequest: "Always",
            backgroundPermissionRationale: {
                title: "Allow Be Safe - Work Alone to access this device's location in the background?",
                message: "In order to track your activity in the background, please enable Allow all the time location permission",
                positiveAction: "Change to Allow all the time",
                negativeAction: "Cancel",
            }
        }).then(state => {
            console.log("Initialized successfully", "enabled", state.enabled);
            setBGGeolocationReady(true);
        }).catch(ex => console.log("Failed to ready geolocation", ex));

        return () => {
            (async () => {
                try {
                    console.log("cleaning up");
                    await activityListener.current?.remove();
                    await locationListener.current?.remove();
                    await heartbeatListener.current?.remove();
                    await motionListener.current?.remove();
                    await geofenceListener.current?.remove();
                    console.log("clean up complete");
                } catch (ex) {
                    console.log("failed to clean up", ex);
                }
            })()
        };
    }, []);

```

### Android headless task registration
```javascript
/* _layout.js */

BackgroundGeolocation.registerHeadlessTask(async (event) => {
    if (event.name === 'heartbeat') {
        await onLocation();
    }
});
```

### onLocation handler
```javascript

/* _layout.js */

const onLocation = async (l) => {
    let taskId = await BackgroundGeolocation.startBackgroundTask();
    try {
        let location = l;
        const { attributes: { email: userEmail } } = await Auth.currentAuthenticatedUser();
        if (!location) {
            location = await BackgroundGeolocation.getCurrentPosition({ desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION, samples: 3 })
        }
        await store.dispatch(updateStatus({ email: userEmail, location: toAWSLocation(location.coords), timestamp: location.timestamp }))
    } catch (ex) {
        console.log("Failed to process location", ex);
    } finally {
        await BackgroundGeolocation.stopBackgroundTask(taskId);
    }
}
```

We are using expo-router.  We have registered / setup the BackgroundGeolocation library inside our main _layout.js file.

## Expected Behavior
* The app sends consistent location updates per "Philosophy of Operation"

## Actual Behavior
* The app throws this exception and location updates cease until the app is restarted
![image](https://github.com/user-attachments/assets/d6781cb6-b99d-43ee-b255-43069e2d9834)

Some example breadcrumb trails..
![image](https://github.com/user-attachments/assets/cda59b43-ed9b-40fe-995a-89ad4e574a65)
![image](https://github.com/user-attachments/assets/7b8dd7e9-cda8-42f9-91bc-645df473a619)
* We originally thought that perhaps the user was operating in a low signal area, but across different days, we see different areas of the map filled in.

## Steps to Reproduce
1.  Looks like this issue is triggered when a user enters a low signal area.

**Comment by mcottingham** [comment]
We weren't seeing this error before we added background-geolocation.  Also, seems to correspond to when the app stops sending location updates.

**Comment by christocracy** [comment]
Do you have a stacktrace?

**Comment by mcottingham** [comment]
![image](https://github.com/user-attachments/assets/89015e28-9364-4c88-9764-d2eba662a24b)

Error: INVALID_TASK_ID: 0
  at onUnhandled(/node_modules/promise/setimmediate/rejection-tracking.js:71:28)
  at apply(native)
  at setTimeout(/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:213:23)
  at _callTimer(/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:111:15)
  at callTimers(/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:359:17)
  at apply(native)
  at __callFunction(/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:433:34)
  at __guard$argument_0(/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:26)
  at __guard(/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:11)
  at callFunctionReturnFlushedQueue(/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:17)

Unfortunately it's not super helpful

**Comment by christocracy** [comment]
> at setTimeout(/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:213:23)

What this about?

**Comment by mcottingham** [comment]
Not really sure.  If I recall correctly these kinds of logs appear when the app is waiting for a Promise to resolve that isn't actually a promise.

**Comment by christocracy** [comment]
I see in the Javascript API the text [`INVALID_TASK_ID`](https://github.com/transistorsoft/react-native-background-geolocation/blob/095feaaca8db0b4baae42361394620c2b83b579c/src/NativeModule.js#L316).  This is a "soft" `Promise` rejection if the `taskId` provided to `.stopBackgroundTask` evaluates as `undefined`, `null` or `0`.

I suggest you check the value of `taskId` before calling `.stopBackgroundTask(taskId)` or catch errors on it.

```javascript
if (taskId > 0) {
  BackgroundGeolocation.stopBackgroundTask(taskId);
}
```

I've never heard of `.startBackgroundTask` *not* returning an integer `> 0` but maybe you've used up all your background-time and the OS returns `taskId: 0`.

**Comment by christocracy** [comment]
The Javascript code doesn't actually need that `if (!taskId) { ... }` check since the native Obj-c code doesn't complain if you try to stop an iOS background-task with `taskId: 0`.

**Comment by mcottingham** [comment]
Ah interesting.  I guess this begs the question as to why I'm getting `0` as a taskId back from `.startBackgroundTask`

My `onLocation` handler is quite simple, as you can see.  It grabs the current authenticated user.  It checks, did we get a location in the call to `onLocation` if so, call `updateStatus` which essentially just does an API call to our backend.  If we didn't receive a location (ie. heartbeat event) then we request the latest location and then `updateStatus`.

Any idea how many background tasks that are allowed to coexist?  I believe that the issue is triggered when users enter low signal areas, so it's possible that we have multiple background tasks alive at the same time until the API times out.

**Comment by christocracy** [comment]
See iOS API docs [`beginBackgroundTaskWithExpirationHandler:`](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio)

>Any idea how many background tasks that are allowed to coexist?

There is no limit.  These are not strictly a "task running in a thread".  They are more like a post-it note posted on the operating-system's "fridge".  They are just a note to the OS for when it comes time to put your app to sleep -- the existence of an outstanding `taskId` will tell the OS to pause for a finite length of time, allowing one to finish doing their work.

<img width="1038" alt="Screenshot 2024-10-28 at 4 20 38 PM" src="https://github.com/user-attachments/assets/c1b51230-7d38-4200-8947-9ad172ea7f79">

If you receive a `taskId ==. 0`, don't do any work and don't call `.stopBackgroundTask`.

If the OS returns `taskId == 0`, you have not been granted any background-time.

**Comment by mcottingham** [comment]
Thank you, I added that check and I see that devices are no longer throwing that exception.
