### ISSUE TITLE
Request activity information at any given point

### ISSUE THREAD

**Issue by craigcoles** [transistorsoft/react-native-background-geolocation#220]
## Your Environment
* Plugin version: 2.6.1
* Platform: iOS
* OS version: 10.2
* React Native version: 0.42.0

### Question

In the documentation, I can see there are `Activity Recognition Options`, but I was wondering if there was a way to request activity information at any time, which would return the activity type and the confidence level? At the moment, it will only return the data if the activity has changed via `activitychange`.

**Comment by christocracy** [comment]
The native `ActivityRecognitionAPI` is asynchronous.  You cannot query it.  However, the plugin only fires *changes* in the `type` -- it does not fire on changes in `confidence`.  

What's your purpose?

**Comment by craigcoles** [comment]
The purpose is to collect the users activity data every minute, and then send a collection of the users activity data to the server every 30 minutes. Ideally, we would send the activity type and the confidence (we would send the most confident choice).

**Comment by christocracy** [comment]
You *do* get the most recent activity data (including `confidence`) with each recorded location.  This is not enough?

**Comment by craigcoles** [comment]
We need to get the activity data, even if the location does not change. We are less reliant on the location data, and more reliant on the activity data.

**Comment by christocracy** [comment]
How do you plan to get activity-data in the background?

**Comment by craigcoles** [comment]
Is it not possible to get activity-data in the background via this plugin, or is it an iOS restraint?

**Comment by christocracy** [comment]
It is **not** possible to get activity-data in the background *unless* the plugin is in the **moving** state (ie: location-services are **on**).  This is an iOS constraint.

**Comment by craigcoles** [comment]
Just to clarify, for us to determine what the users activity was in the background, the user would have to be moving? Is this the same for Android?

**Comment by christocracy** [comment]
>for us to determine what the users activity was in the background, the user would have to be moving? 

Yes.

>Is this the same for Android?

No.
