### ISSUE TITLE
Location permission manual request not always works

### ISSUE THREAD

**Issue by Crysp** [transistorsoft/react-native-background-geolocation#2201]
Option `disableLocationAuthorizationAlert` doesn't work as expected. Permission is requested at app startup.

## Your Environment
* Plugin version: 4.16.2
* Platform: iOS
* OS version: 18.0.0
* Device manufacturer / model: iPhone 15
* React Native version (`react-native -v`): 0.75.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  reset: true,
  stopOnTerminate: false,
  disableLocationAuthorizationAlert: true,
  locationAuthorizationRequest: 'Any',
}
```

## Standalone component to reproduce
```jsx
import React, { useCallback, useEffect, useState } from 'react';
import { Button } from 'react-native';
import RNBG from 'react-native-background-geolocation';

export const BugReportExample = () => {
  const [enabled, setEnabled] = useState(false);
  const onStart = useCallback(() => {
    RNBG.start(state => {
      setEnabled(state.enabled);
    });
  }, []);
  const onStop = useCallback(() => {
    RNBG.stop(state => {
      setEnabled(state.enabled);
    });
  }, []);

  useEffect(() => {
    RNBG.ready({
      reset: true,
      stopOnTerminate: false,
      disableLocationAuthorizationAlert: true,
      locationAuthorizationRequest: 'Any',
    }).then(state => {
      setEnabled(state.enabled);
    });
  }, []);

  return (
    <Button
      title={enabled ? 'Stop' : 'Start'}
      onPress={enabled ? onStop : onStart}
    />
  );
};
```

## Expected Behavior
If some requirement is missed (for proper plug-in work) and I tell that I manually controlling requests (`disableLocationAuthorizationAlert: true`), there should be some warning or error during plug-in preparation (inside `ready`).

## Actual Behavior
If location permission is missed (for "permanent" mode), plug-in will request it at app startup.

## Steps to Reproduce

1. Plug-in works in "permanent" mode (launches in background)
2. Revoke all app permissions
3. Launch the app
4. Location permission appears at app startup

## Context
I want to request location permission my own no matter the plug-in state is

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> disableLocationAuthorizationAlert

This option doesn’t do what you think it does.  Read about it in the api docs.

if you do not want the plug-in to request permission, don’t tell it to .start().  Calling .start() always requests permission.

listen to .onProviderChange event to learn about changes in permission.

**Comment by Crysp** [comment]
No, you probably didn't understand me. Permission request at `start` is ok and pretty transparent.

Steps:
1. Call `start`
2. Grant necessary permission
3. Plug-in works in "permanent" mode
4. Terminate the app
5. Revoke permission
6. Launch the app
7. **Permission appears at app startup (without any actions)**

**Comment by christocracy** [comment]
The plugin's `State.enabled` is persisted throughout app restarts / device reboots.  
- Calling `.start()` sets `State.enabled == true`
- Calling `.stop()` sets `State.enabled == false`.
- When you call `.ready(config)`, if the plugin finds `State.enabled == true`, it will call `.start()` upon itself.
- Calling `.start()` automatically requests permission.

Therefore, before calling `.ready(config)`, you must analyze the current state of permissions using [`.getProviderState()`](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#getproviderstate).

```javascript
var providerState = await BackgroundGeolocation.getProviderState();

if (!providerState.enabled) {
  // If you find location-services is disabled, you must tell the plugin to .stop() (which sets State.enabled -> false)
  BackgoundGeolocation.stop();
}
.
.
.
BackgroundGeolocation.ready(config)
```

**Comment by Crysp** [comment]
It doesn't work as you write. Request still appears at app startup

```jsx
import React, { useCallback, useEffect, useState } from 'react';
import { Button } from 'react-native';
import RNBG from 'react-native-background-geolocation';

export const BugReportExample = () => {
  const [enabled, setEnabled] = useState(false);
  const onStart = useCallback(() => {
    RNBG.start(state => {
      setEnabled(state.enabled);
    });
  }, []);
  const onStop = useCallback(() => {
    RNBG.stop(state => {
      setEnabled(state.enabled);
    });
  }, []);

  useEffect(() => {
    RNBG.getProviderState().then(async providerState => {
      if (providerState.enabled) {
        await RNBG.stop();
      }

      RNBG.ready({
        reset: true,
        stopOnTerminate: false,
        disableLocationAuthorizationAlert: true,
        locationAuthorizationRequest: 'Any',
      }).then(state => {
        setEnabled(state.enabled);
      });
    });
  }, []);

  return (
    <Button
      title={enabled ? 'Stop' : 'Start'}
      onPress={enabled ? onStop : onStart}
    />
  );
};
```

**Comment by christocracy** [comment]
> It doesn't work as you write

That’s not how I wrote it.

The plug-in API is *asynchronous*.  You need to `await` the call to .getProviderState(), guaranteeing it executes *before* calling .ready.

**Comment by Crysp** [comment]
I'm calling `ready` inside `getProviderState` promise resolve callback. So I think code is identical

**Comment by christocracy** [comment]
Compare your logic:

```javascript
if (providerState.enabled)
```

with mine:
```javascript
if (!providerState.enabled) {
```

if NOT enabled.  If location-services are disabled, then .stop().

**Comment by Crysp** [comment]
Ah, thx. But permission still requesting 🤷‍♂️

**Comment by Crysp** [comment]
Provider state resolves to
```json
{
  "accuracyAuthorization": 0,
  "enabled": false,
  "gps": true,
  "network": true,
  "status": 0
}
```
I think there is some logic in native code that requests permission

**Comment by christocracy** [comment]
The plugin only requests permission if the plugin is `State.enabled`.

Are you observing the plugin logs in `$ adb logcat`?  See Wiki "Debugging".
