### ISSUE TITLE
App freezes whne the location permission is denied on IOS

### ISSUE THREAD

**Issue by suprith-lumber** [transistorsoft/react-native-background-geolocation#2207]
## Your Environment
* Plugin version: 14.7.5
* Platform: iOS
* OS version: 16 / 17
* Device manufacturer / model: Iphone
* React Native version (`react-native -v`): 0.73.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  useEffect(() => {
    if (Platform.OS !== 'web' && locationEnabled) {
      BackgroundGeolocation.start();
      const onLocation: Subscription = BackgroundGeolocation.onLocation(
        (location) => {
          console.log('[onLocation] location: ', location);
          setLongitude(location?.coords.longitude);
          setLatitude(location?.coords.latitude);
        },
        (error) => {
          console.log('[onLocation] ERROR: ', error);
        }
      );
      return () => {
        onLocation.remove();
      };
    }
  }, []);

  useEffect(() => {
    const locationPermission = async () => {
        if (locationEnabled && status !== 'CLOCKED OUT') {
          BackgroundGeolocation.start();
          let location = await BackgroundGeolocation.getCurrentPosition(options);
          setLatitude(location.coords.latitude);
          setLongitude(location.coords.longitude);
        } else {
          BackgroundGeolocation.stop();
        }
      }
    locationPermission();
  }, [locationEnabled, status]);
  
        const onLocation: Subscription = BackgroundGeolocation.onLocation(
        (location) => {
          setLongitude(location?.coords.longitude);
          setLatitude(location?.coords.latitude);
        },
        (error) => {
          console.log('[onLocation] ERROR: ', error);
        }
      );
```

## Expected Behavior
App should work normally irrespective of  location permission is provided or denied

## Actual Behavior
When location permission is denied app freezes and no actions work

## Steps to Reproduce
1. Ask for location permission on IOS
2. Deny the location permission
3. App freezes
4.If location permission is provided, app runs normally

## Context
Track location co-ordinates, as discussed in issue https://github.com/transistorsoft/react-native-background-geolocation/issues/2193

## Debug logs

<img src="https://github.com/user-attachments/assets/11d3a2fa-bd8f-424f-8614-33f2c4304224" alt="image" width="300"/>Can I know what permission the user chooses finally, Don't Allow OR Always Allow OR Allow when using this App. How do I know that?

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
 LOG  [onLocation] {"error": 1} ```

</details>

**Comment by christocracy** [comment]
>Plugin version: 14.7.5

This version does not exist.

**Comment by christocracy** [comment]
Duplicate #2202

**Comment by suprith-lumber** [comment]
> > Plugin version: 14.7.5
> 
> This version does not exist.

I mean 4.17.5

**Comment by christocracy** [comment]
I don’t think it’s true you were running 4.17.5.

**Comment by christocracy** [comment]
Or you didn’t `pod install` after updating.

**Comment by suprith-lumber** [comment]
Hi, I did pod install.
When I use `BackgroundGeolocation.start();` it asks for the  `Location Services are turned off` `Settings` and `Cancel` modal popup. 
Can I instead of that show my own modal just with my own message. Because clicking on cancel is what causing trouble. And lets not show `Cancel` at all ??

**Comment by christocracy** [comment]
See api docs Config.disableLocationAuthorizationAlert

**Comment by suprith-lumber** [comment]
Also one more help, can you tell me whats wrong in the code, if I remove BackgroundGeoLocation.start(); then neither the modal pops up nor app freezes:
```
  useEffect(() => {
    const locationPermission = async () => {
      if (Platform.OS !== 'web' && locationEnabled) {
        BackgroundGeolocation.start()
          .then((state) => {
            console.log('[start] success - ', state);
          })
          .catch((error) => {
            console.log('[start] failed - ', error);
          });
        const onLocation: Subscription = BackgroundGeolocation.onLocation(
          (location) => {
            console.log('[onLocation] location: ', location);
            setLongitude(location?.coords.longitude);
            setLatitude(location?.coords.latitude);
          },
          (error) => {
            console.log('[onLocation] ERROR: ', error);
          }
        );
        return () => {
          onLocation.remove();
        };
      } else {
        BackgroundGeolocation.stop();
      }
    };
    locationPermission();
  }, []);
```

**Comment by suprith-lumber** [comment]
Hi @christocracy I am using 
```
        BackgroundGeolocation.getProviderState().then((state) => {
          if (state.status === 3) {
            // do something
          }
        });
```
Assuming staus === 3 means the location permission is set to `Always`.
Can I rely on this method to determine that permission sis set to `Always` ?
In all the IOS devices and OS versions ?

**Comment by christocracy** [comment]
Yes
