### ISSUE TITLE
Eas Build Development Android

### ISSUE THREAD

**Issue by syedmumersajjad** [transistorsoft/react-native-background-geolocation#2208]
I have setup the project according to guide but it fails on build development. Without using this library eas build works fine.
Libraries i am using:
 "@expo/config-plugins": "^8.0.8",
    "@expo/metro-config": "~0.18.1",
    "@expo/vector-icons": "^14.0.0",
    "@gorhom/bottom-sheet": "^4.6.4",
    "@mapbox/mapbox-sdk": "^0.16.0",
    "@mapbox/polyline": "^1.2.1",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/netinfo": "11.3.1",
    "@react-navigation/bottom-tabs": "^6.5.0",
    "@react-navigation/drawer": "^6.5.4",
    "@react-navigation/native": "^6.1.0",
    "@react-navigation/native-stack": "^6.9.5",
    "@reduxjs/toolkit": "^1.9.7",
    "@rnmapbox/maps": "10.1.29",
    "@sentry/react-native": "~5.24.3",
    "@stripe/stripe-react-native": "0.37.2",
    "@turf/helpers": "^7.0.0",
    "@turf/turf": "^7.0.0",
    "@youssefhenna/expo-mapbox-navigation": "^1.0.0",
    "base-64": "^1.0.0",
    "dotenv": "^16.4.5",
    "expo": "~51.0.39",
    "expo-application": "~5.9.1",
    "expo-av": "~14.0.7",
    "expo-build-properties": "~0.12.1",
    "expo-constants": "~16.0.1",
    "expo-dev-client": "~4.0.29",
    "expo-device": "~6.0.2",
    "expo-file-system": "~17.0.1",
    "expo-font": "~12.0.9",
    "expo-gradle-ext-vars": "^0.1.2",
    "expo-haptics": "~13.0.1",
    "expo-image-picker": "~15.0.7",
    "expo-insights": "~0.7.0",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-location": "~17.0.1",
    "expo-notifications": "~0.28.19",
    "expo-print": "~13.0.1",
    "expo-sharing": "~12.0.1",
    "expo-splash-screen": "~0.27.7",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-task-manager": "~11.8.2",
    "expo-tracking-transparency": "~4.0.2",
    "expo-updates": "~0.25.27",
    "firebase": "^10.6.0",
    "geolib": "^3.3.4",
    "moment": "^2.29.4",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-animatable": "^1.3.3",
    "react-native-background-fetch": "^4.2.5",
    "react-native-background-geolocation": "^4.17.6",
    "react-native-elements": "^3.4.3",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-get-random-values": "^1.11.0",
    "react-native-gifted-chat": "^2.4.0",
    "react-native-google-places-autocomplete": "^2.5.1",
    "react-native-maps": "1.14.0",
    "react-native-maps-directions": "^1.9.0",
    "react-native-paper": "^5.1.0",
    "react-native-qrcode-svg": "^6.3.12",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-web": "~0.19.10",
    "react-native-webview": "13.8.6",
    "react-redux": "^8.1.3",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "typescript": "~5.3.3"
    
    [
            "react-native-background-geolocation", {
                "license": "product key"
            }
        ],
        [
            "expo-gradle-ext-vars", {
                "googlePlayServicesLocationVersion": "21.1.0",
                "appCompatVersion": "1.4.2"
            }
        ],
        "react-native-background-fetch",
        

 "expo-build-properties",
            {
                android: {
                    manifestProperties: {
                        'android:largeHeap': 'true',
                        "minSdkVersion": 23,
                        "compileSdkVersion": 33,
                        "targetSdkVersion": 33,
                        "buildToolsVersion": "33.0.0"
                    },
                },
                ios: {
                    "deploymentTarget": "14.0",
                    "useFrameworks": "static"
                },
            }
            
Build issue is only for android

**Comment by christocracy** [comment]
> Without using this library eas build works fine.

What makes you think it “doesn’t build fine”?

**Comment by syedmumersajjad** [comment]
i have just uninstall the library react-native-background-geolocation and it's configurations and it build as expected. see the file 
[text-BC7B89830B00-1.txt](https://github.com/user-attachments/files/17782653/text-BC7B89830B00-1.txt)

**Comment by christocracy** [comment]
Is there some particular error in a log file that is interesting to you?

**Comment by syedmumersajjad** [comment]
i am failed to find maybe it is conflicting with the other libraries which i am using. this should not behave because i have tested with the 
android: {
manifestProperties: {
'android:largeHeap': 'true',
"minSdkVersion": 23,
"compileSdkVersion": 31,
"targetSdkVersion": 31,
"buildToolsVersion": "31"
}, while ago and it works

**Comment by christocracy** [comment]
Do you have some particularly interesting error to look at?

> "targetSdkVersion": 31,

why??  You don’t know that’s lower than the  minimum required version?

https://developer.android.com/google/play/requirements/target-sdk

let me know if you have something interesting for me to look at.

**Comment by christocracy** [comment]
right at the end of your build log:

```
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
> Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1.aar -> work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1.aar -> work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1.aar -> work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1.aar -> work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
```

You have multiple plugins requesting two different versions of `androidx.work:work-runtime`:  `2.8.1` and `2.7.1`

This plugin *does* import this dependency, with a [default version of `2.8.1`](https://github.com/transistorsoft/react-native-background-geolocation/blob/bc9a76904b1b32de0bd938361508cd64eacf0839/android/build.gradle#L27)

You can control the version this plugin uses via `gradle-ext-vars` plugin in your `app.json` with the `workVersion` variable:

```
[
        "expo-gradle-ext-vars", {
            "googlePlayServicesLocationVersion": "21.1.0",
            "appCompatVersion": "1.4.2",
             "workVersion": "2.7.1" // <------------ ADD THIS
        }
],

**Comment by christocracy** [comment]
You can generate a dependency tree for you Android app to see which plugins are importing which dependencies:

```
$ cd android
$ ./gradlew app:dependencies
```

**Comment by syedmumersajjad** [comment]
thank you so much man it works now
