### ISSUE TITLE
iOS Defaulting to "When In Use" in Release

### ISSUE THREAD

**Issue by JUnderwood1991** [transistorsoft/react-native-background-geolocation#221]
## Your Environment
* Plugin version:  2.6.1
* Platform: iOS
* OS version: 10.3 Beta 4
* Device manufacturer / model: iPhone 6s plus
* React Native version (`react-native -v`): 0.41.2
* Plugin config

```
    BackgroundGeolocation.getState((state) => {
      if ( state.enabled == false ) {
        console.log("DEBUG: Attemping to configure plugin..." );
        BackgroundGeolocation.configure({
          desiredAccuracy: 0,
          distanceFilter: 50,
          stationaryRadius: 25,
          locationUpdateInterval: 1000,
          locationAuthorizationRequest: 'Always',
          debug: true,
        }, function(newState) {
          if ( newState.enabled == false ) {
            BackgroundGeolocation.start();
          }
        });
      }
```

## Expected Behavior

Expected to default to "Always" when initial install triggers Permissions Request
## Actual Behavior

Whether I include locationAuthorizationRequest: 'Always' or not it _always_ sets Location to While Using. This only happens when I deploy from Xcode with the Release scheme.
## Steps to Reproduce

1. Set scheme to release
2. Deploy to Device
3. Accepting Permissions Prompt
4. Note "While In Use" for  Privacy -> Location Services -> App Name -> Location

## Debug logs

> {
>    activityRecognitionInterval = 10000;
>    activityType = Other;
>    autoSync = 1;
>    autoSyncThreshold = 0;
>    batchSync = 0;
>    debug = 1;
>    desiredAccuracy = 0;
>    desiredOdometerAccuracy = 100;
>    disableElasticity = 0;
>    disableMotionActivityUpdates = 0;
>    disableStopDetection = 0;
>    distanceFilter = 50;
>    enabled = 0;
>    extras =    {
>    };
>    geofenceInitialTriggerEntry = 1;
>    geofenceProximityRadius = 1000;
>    geofenceTemplate = "";
>    headers =    {
>    };
>    heartbeatInterval = 60;
>    httpRootProperty = location;
>    isHeartbeatEnabled = 0;
>    isMoving = 0;
>    locationAuthorizationAlert =    {
>        cancelButton = Cancel;
>        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
>        settingsButton = Settings;
>        titleWhenNotEnabled = "Background location is not enabled";
>        titleWhenOff = "Location services are off";
>    };
>    locationAuthorizationRequest = Always;
>    locationTemplate = "";
>    locationTimeout = 60;
>    logLevel = 0;
>    logMaxDays = 7;
>    maxBatchSize = "-1";
>    maxDaysToPersist = 1;
>    maxRecordsToPersist = "-1";
>    method = POST;
>    minimumActivityRecognitionConfidence = 70;
>    odometer = "9.863428925281335";
>    params =    {
>    };
>    pausesLocationUpdatesAutomatically = 1;
>    preventSuspend = 0;
>    schedule =    (
>    );
>    schedulerEnabled = 0;
>    startOnBoot = 0;
>    stationaryRadius = 25;
>    stopAfterElapsedMinutes = "-1";
>    stopDetectionDelay = 0;
>    stopOnTerminate = 1;
>    stopTimeout = 5;
>    trackingMode = 1;
>    url = "";
>    useSignificantChangesOnly = 0;
> }

**Comment by JUnderwood1991** [comment]
The zip file contains a recording from my iPhone...if interested.

[WhileInUseDemoTiny.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/832691/WhileInUseDemoTiny.zip)

**Comment by JUnderwood1991** [comment]
Logs. 

[background-geolocation.log.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/832694/background-geolocation.log.zip)

**Comment by christocracy** [comment]
I will attempt to duplicate this with the demo app

**Comment by JUnderwood1991** [comment]
Okay.

Xcode 8.3 beta (8W132p) just in case...

**Comment by christocracy** [comment]
No problem here with my App.

![](https://www.dropbox.com/s/8zfcg8vjth0ek8p/Screenshot%202017-03-09%2021.22.30.png?dl=1)

**Comment by christocracy** [comment]
I see nothing changed for `CoreLocation` in `10.3 best 5`

**Comment by christocracy** [comment]
I've just published `2.7.0`.  This had some modifications to initial-state of Settings manager.  

You can now build Android for `DEBUG` builds too without a license.

**Comment by JUnderwood1991** [comment]
Figured it out. 

Info.plist contained this key value pair

Privacy - Location When In Use Usage Description 

Even though I also had "Privacy - Location Always Usage Description"

It seemed to go with When In Use. Simply removing the aforementioned key resolved this issue. Apologies.

**Comment by JUnderwood1991** [comment]
Yeah. Not sure why I had that in the Info.plist. I just didn't want to leave the thread unresolved. Hopefully if someone else experiences this they will see this.
