### ISSUE TITLE
background location tracking is not running in few devices

### ISSUE THREAD

**Issue by anandsharmaautovyn** [transistorsoft/react-native-background-geolocation#2216]
## Your Environment
* Plugin version: 4.17.6
* Platform: Android
* OS version: 11, 12, 14,
* Device manufacturer / model: VIVO v29(AV=>14), OPPO A79(AV=>14)
* React Native version (`react-native -v`): 0.72.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  const locationTracking = async () => {
    setIsTracking(true);
    if (!track || track == 'null') {
      try {
        BackgroundGeolocation.start(async () => {
          let newLatLng = await BackgroundGeolocation.getCurrentPosition({
            timeout: 30,
            maximumAge: 5000,
            desiredAccuracy: 10,
            samples: 3,
            extras: {
              "route_id": 123
            }
          })
          if (!storage.getBoolean('startDate')) {
            storage.set('startDate', moment().format("DD-MM-YYYY hh:mm a"));
            storage.set('startLocation', JSON.stringify(newLatLng));
          }
          storage.set('tracking', `${itemData?.leadID}`);
          tracking && setIsTracking(false);
          setTrack(itemData?.leadID);
        })
      } catch (err) {
        console.log('error in location tracking', err);
      }
    } else if (track == itemData?.leadID) {
      try {
        const checkEnabled = await isLocationEnabled();
        if (checkEnabled) {
          await submitLocationDetails();
        } else {
          setIsTracking(false);
          Alert.alert('Permission Denied', 'Location permission is required for tracking.');
        }
      } catch (err) {
        console.warn(err);
      }
    } else {
      setIsTracking(false);
      Alert.alert(`Another lead's location tracking is in progress!`, `Please complete that first!`);
    }
  };

  const submitLocationDetails = async () => {
    let totalDistance = await BackgroundGeolocation.getOdometer();
    totalDistance = (totalDistance / 1000).toFixed(2);
    let endLocation = await BackgroundGeolocation.getCurrentPosition({
      timeout: 30,
      maximumAge: 5000,
      desiredAccuracy: 10,
      samples: 3,
      extras: {
        "route_id": 123
      }
    })
    let startLocation = storage.getString('startLocation')
    startLocation = JSON.parse(startLocation)
    let payload = {
      latitudStart: startLocation?.coords?.latitude?.toString(),
      longitudeStart: startLocation?.coords?.longitude?.toString(),
      latitudeEnd: endLocation?.coords?.latitude?.toString(),
      longitudeEnd: endLocation?.coords?.longitude?.toString(),
      distance: `${totalDistance} KM`,
      startLocationDate: storage.getString('startDate'),
      endLocationDate: moment().format("DD-MM-YYYY hh:mm a"),
    }
    try {
      const res = #APICALL#
      BackgroundGeolocation.stop()
      BackgroundGeolocation.resetOdometer()
      Alert.alert("Distance Traveled", payload?.distance);
      storage.set('tracking', '')
      storage.set('startLocation', '')
      storage.set('startDate', '')
      storage.set('endDate', '')
      setTrack('');
      setIsTracking(false);
      return res?.data;
    } catch (error) {
      console.log("error", error)
      Alert.alert("There is an error at our end but you travelled", payload?.distance)
      BackgroundGeolocation.stop()
      BackgroundGeolocation.resetOdometer()
      return error?.message;
    }
  };

```
## Expected Behavior

the method getOdometer() should return distance travelled by the user
## Actual Behavior

it always returns 0.0 KM
## Steps to Reproduce

1. cd android && ./gradlew clean && ./gradlew assembleRelease
2. start the app and give the necessary permissions (i.e: Location: allow all the time, physical activity)
3. start the location tracking travel for a distance the stop the tracking
4. it will show 0.0 KM

## Context

I am trying to calculate an approximate distance travelled by the user
## Debug logs
 none
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by anandsharmaautovyn** [comment]
I've also added required changes to necessary files
android/build.gradle

allprojects {
    repositories {
        jcenter()
        // Required for react-native-background-geolocation
        maven { url("${project(':react-native-background-geolocation').projectDir}/libs") }
        maven { url 'https://developer.huawei.com/repo/' }
        // Required for react-native-background-fetch
        maven { url("${project(':react-native-background-fetch').projectDir}/libs") }
    }
}

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            shrinkResources false
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro", "${background_geolocation.projectDir}/proguard-rules.pro"
            crunchPngs false // or true
        }
    }

android/app/build.gradle
Project background_geolocation = project(':react-native-background-geolocation')
apply from: "${background_geolocation.projectDir}/app.gradle"
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        appCompatVersion    = "1.4.2"
        googlePlayServicesLocationVersion = "21.3.0"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    }
manifest.xml
<uses-permission android:minSdkVersion="34" android:name="android.permission.USE_EXACT_ALARM" /> and
<meta-data android:name="com.transistorsoft.locationmanager.license" android:value="YOUR_LICENCE_KEY_HERE" />

**Comment by christocracy** [comment]
> Device manufacturer / model: VIVO v29(AV=>14), OPPO A79(AV=>14)

Some of the worst offenders.  See https://dontkillmyapp.com 

> jcenter()

Not related but read this about this deprecated repository:  https://developer.android.com/build/jcenter-migration

**Comment by anandsharmaautovyn** [comment]
Thank you for the resolution it is working as expected but I've a question can i get the address from the longitude and latitude?

**Comment by christocracy** [comment]
> can i get the address from the longitude and latitude?

That’s called “reverse geocoding”.  No, the plug-in does not do reverse geocoding.  You usually have to pay a provider for that service (eg google).  It involves sending an http request to a service.

IMO, reverse geocoding is best done at the server, rather than on the device.
