### ISSUE TITLE
App being rejected due to not meeting compliance [Health - Other]

### ISSUE THREAD

**Issue by perotem7** [transistorsoft/react-native-background-geolocation#2217]
## Your Environment
* Plugin version: 4.17.6
* Platform: Android
* OS version: NA
* Device manufacturer / model: NA
* React Native version (`react-native -v`): 0.75.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    // Geolocation Config
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    stopTimeout: 5,
    debug: false, 
    logLevel: BackgroundGeolocation.LOG_LEVEL_WARNING,
    stopOnTerminate: false,  
    startOnBoot: false,      
}
```

## Expected Behavior
App approved by google and released on the store.

## Actual Behavior
The app gets rejected for not meeting compliance requirements.

I reviewed the issues section of this repo and read [2031](https://github.com/transistorsoft/react-native-background-geolocation/issues/2031) and [1953](https://github.com/transistorsoft/react-native-background-geolocation/issues/1953) as well as your blog [post](https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a), but it seams that the issue we're facing is a bit different.

Upon installation we display a very descriptive dialog explaining why we require the FOREGROUND permissions. 

We've tried your recommendations for the blog post, adding several versions of declaration text and video, with no help. 

Google are complaining for 3 reasons:

1. Issue found: Service interruption or deferment of functionality does not have material user impact
We found that one or more of the declared use cases is not compliant with how [foreground service permission](https://notifications.google.com/g/p/ANiao5rgXn9c4ffqZJJqgx4NMKWIknkkVmF7gmzSH5bhiaI57WkSwPcYt-hZuII38vaCh8OkUH6nykNrl8clf8i_5Nk0itPgR3YMEm0hY_3x69a2siFPJN6lyRHsvUShHMEVexREBRQTYL3phLm9-Ow1ZBh9zc76yBF0uDnsvOh-sMlBc7dUb9PkEoWgQI37El54YhCquEEk1EF5jJ5TWtT3_1kusfUdZ5u0UOsQXyVCgk9aX1qYePATyOUI0WVW34BllsfTRPWibn6DYaEUCI0dgXdKhNywTA7A-5cdJaAhxx_KCZSGaw) is allowed to be used. Specifically, the declared use case(s) can be interrupted or deferred by the system without creating a negative user experience. Your app is using foreground service to Health - Other when it is not required to do so.

2. Issue found: Permission use is either not declared or incorrectly declared
We found that one or more of the use cases utilizing the [foreground service permission](https://notifications.google.com/g/p/ANiao5rgXn9c4ffqZJJqgx4NMKWIknkkVmF7gmzSH5bhiaI57WkSwPcYt-hZuII38vaCh8OkUH6nykNrl8clf8i_5Nk0itPgR3YMEm0hY_3x69a2siFPJN6lyRHsvUShHMEVexREBRQTYL3phLm9-Ow1ZBh9zc76yBF0uDnsvOh-sMlBc7dUb9PkEoWgQI37El54YhCquEEk1EF5jJ5TWtT3_1kusfUdZ5u0UOsQXyVCgk9aX1qYePATyOUI0WVW34BllsfTRPWibn6DYaEUCI0dgXdKhNywTA7A-5cdJaAhxx_KCZSGaw) in your app has either been incorrectly submitted or is missing from your Console declaration.
Your app is utilizing foreground service to Health - Other, but you have not disclosed this in your declaration or it is not required.

3. Issue found: Functionality is not initiated by or perceptible to the user
We found that one or more of the declared use cases is not compliant with how [foreground service permission](https://notifications.google.com/g/p/ANiao5rgXn9c4ffqZJJqgx4NMKWIknkkVmF7gmzSH5bhiaI57WkSwPcYt-hZuII38vaCh8OkUH6nykNrl8clf8i_5Nk0itPgR3YMEm0hY_3x69a2siFPJN6lyRHsvUShHMEVexREBRQTYL3phLm9-Ow1ZBh9zc76yBF0uDnsvOh-sMlBc7dUb9PkEoWgQI37El54YhCquEEk1EF5jJ5TWtT3_1kusfUdZ5u0UOsQXyVCgk9aX1qYePATyOUI0WVW34BllsfTRPWibn6DYaEUCI0dgXdKhNywTA7A-5cdJaAhxx_KCZSGaw) is allowed to be used. Specifically, the user is not made aware of functionality requiring permission when active. Use of FGS is not perceptible to the user when performing Health - Other functionality.

If you or anyone have any guidance that may help us go past this hurdle it would be highly appreciated.

**Comment by ReiDx** [comment]
Same issue, any update?

**Comment by christocracy** [comment]
Follow my blog linked above.  It’s what I used to publish the demo app.  

It’s completely between you and the Play Store,

**Comment by perotem7** [comment]
We got the app approved 😀🎉

In case anyone else encounters this issue, this is what we did:
- We filed an appeal through play console. This resulted with a mail thread which enabled asking questions and getting clarifications.
- We then realized that the main complaint by Google was that they couldn't understand why our specific use case required foreground services (see complain #1 above).
- We then explained in details (over mail) why we do require foreground services.
- At this point google approved the app, requesting that we remove "Health - other" from our declarations.
- App got approved.

**Comment by christocracy** [comment]
> At this point google approved the app, requesting that we remove "Health - other" from our declarations.

Can you explain more about how exactly you “removed Health (Other)”?

**Comment by ademirtemur** [comment]
this works, add these lines.

<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" tools:node="remove" />
 <uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" tools:node="remove" />

**Comment by ademirtemur** [comment]
this works, add these lines.

`
<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" tools:node="remove" />
 <uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" tools:node="remove" />
`
