### ISSUE TITLE
Can we use free license for trial

### ISSUE THREAD

**Issue by patilrahul9923** [transistorsoft/react-native-background-geolocation#2219]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plug-in is fully functional in debug builds so you can try before you buy. 

There is no such thing a trial licenses.
