### ISSUE TITLE
Plugin inoperable on iPhone 5

### ISSUE THREAD

**Issue by JUnderwood1991** [transistorsoft/react-native-background-geolocation#222]
## Your Environment
* Plugin version: 2.6.1
* Platform: iOS
* OS version: 10.1.1
* Device manufacturer / model: iPhone MD656LL/A
* React Native version (`react-native -v`): 0.41.2
* Plugin config

```
    BackgroundGeolocation.getState((state) => {
      if ( state.enabled == false ) {
        console.log("DEBUG: Attemping to configure plugin..." );
        BackgroundGeolocation.configure({
          desiredAccuracy: 0,
          distanceFilter: 50,
          stationaryRadius: 25,
          locationUpdateInterval: 1000,
          locationAuthorizationRequest: 'Always',
          debug: true,
        }, function(newState) {
          if ( newState.enabled == false ) {
            BackgroundGeolocation.start();
          }
        });
      }
```
## Expected Behavior

Plugin should track user location and provide debugging prompts
## Actual Behavior

When the app is shifted to the background, a single "Continue Stationary" P/N is shown. At this point no matter how far I travel I never receive any additional debugging info and geofences are never triggered.

## Steps to Reproduce

1. Install App
2. Note that Location Services request appears but Motion Tracker request does not
3. Establish Fence
4. Conduct Movement

## Context

Its worth noting that this occurs in release mode

## Debug logs

```
{
   activityRecognitionInterval = 10000;
   activityType = Other;
   autoSync = 1;
   autoSyncThreshold = 0;
   batchSync = 0;
   debug = 1;
   desiredAccuracy = 0;
   desiredOdometerAccuracy = 100;
   disableElasticity = 0;
   disableMotionActivityUpdates = 0;
   disableStopDetection = 0;
   distanceFilter = 50;
   enabled = 1;
   extras =    {
   };
   geofenceInitialTriggerEntry = 1;
   geofenceProximityRadius = 1000;
   geofenceTemplate = "";
   headers =    {
   };
   heartbeatInterval = 60;
   httpRootProperty = location;
   isHeartbeatEnabled = 0;
   isMoving = 0;
   locationAuthorizationAlert =    {
       cancelButton = Cancel;
       instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
       settingsButton = Settings;
       titleWhenNotEnabled = "Background location is not enabled";
       titleWhenOff = "Location services are off";
   };
   locationAuthorizationRequest = Always;
   locationTemplate = "";
   locationTimeout = 60;
   logLevel = 0;
   logMaxDays = 7;
   maxBatchSize = "-1";
   maxDaysToPersist = 1;
   maxRecordsToPersist = "-1";
   method = POST;
   minimumActivityRecognitionConfidence = 70;
   odometer = "2642.26595704622";
   params =    {
   };
   pausesLocationUpdatesAutomatically = 1;
   preventSuspend = 0;
   schedule =    (
   );
   schedulerEnabled = 0;
   startOnBoot = 0;
   stationaryRadius = 25;
   stopAfterElapsedMinutes = "-1";
   stopDetectionDelay = 0;
   stopOnTerminate = 1;
   stopTimeout = 5;
   trackingMode = 1;
   url = "";
   useSignificantChangesOnly = 0;
}
```

p.s. if this means i just need too use the significantChangeAPI just say so. But it worked on previous versions of the plugin o.0

**yes, location permissions are set to always**

**Comment by JUnderwood1991** [comment]
There are tons of threads on iPhone 5/5s motion sensors being faulty. It could just as possibly be that...

**Comment by christocracy** [comment]
I have an iPhone 5.  It works fine.  The plugin doesn't require motion-detection for initial trigger.

The plugin is 100% guaranteed to work with iPhone 5

**Comment by JUnderwood1991** [comment]
I am going to install the demo app to test

**Comment by christocracy** [comment]
No problem here with my App.

![](https://www.dropbox.com/s/8zfcg8vjth0ek8p/Screenshot%202017-03-09%2021.22.30.png?dl=1)

**Comment by JUnderwood1991** [comment]
You're also using 10.2 it's possible that 10.3 beta 3/4/5 implemented changes

**Comment by JUnderwood1991** [comment]
^ that comment was meant for the when in use thread

**Comment by obionoview** [comment]
@JUnderwood1991, @christocracy I'm facing a similar issue but with all iPhone versions. It was working before (maybe stopped working after the recent Xcode update)

I'm getting a single "Continue stationary" when running in debug mode and no more update (simulator running in "Freeway Drive" mode.)
