### ISSUE TITLE
google play console Health - Other issue

### ISSUE THREAD

**Issue by ademirtemur** [transistorsoft/react-native-background-geolocation#2226]
## Your Environment
* Plugin version: 4.17.3
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 72.
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
               desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
               stationaryRadius: 0,
               distanceFilter: 5,
               startOnBoot: true,
               stopOnTerminate: false,
               stopOnStationary: false,
               locationUpdateInterval: appEnv.locationInterval,
               fastestLocationUpdateInterval: appEnv.fastestLocationUpdateInterval,
               pausesLocationUpdatesAutomatically: false,
               locationAuthorizationRequest: "Always",
               autoSync: true,
               disableElasticity: false,
               heartbeatInterval: 60,
               preventSuspend: true,
               locationTimeout: 65,
               activityRecognitionInterval: 10000,
               disableStopDetection: true,
               autoSyncThreshold: 0,
               batchSync: false,
               showsBackgroundLocationIndicator: false,
               disableMotionActivityUpdates: true,
               disableAutoSyncOnCellular: false,
               enableHeadless: true,
               triggerActivities: "on_foot, walking, running, on_bicycle, in_vehicle",
               stopTimeout: 15,
               useSignificantChangesOnly: false,
               reset: true,
               maxDaysToPersist: 1,
               debug: false,
               logMaxDays: 1,
               enableTimestampMeta: true
          }
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by ademirtemur** [comment]
Previously approved versions are not approved now. Application contents (health and foreground services) are defined, I shot a video and added it. I upgraded the version of the plugin, but it rejected it again. What is wrong here? How can I do it. 

We found that one or more of the use cases utilizing the [foreground service permission](https://support.google.com/googleplay/android-developer/answer/13392821?hl=en&sjid=5928478178588015754-NA) in your app has either been incorrectly submitted or is missing from your Console declaration.
Your app is utilizing foreground service to Health - Other, but you have not disclosed this in your declaration or it is not required.

**Comment by christocracy** [comment]
See my blog:  https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a

**Comment by ademirtemur** [comment]
Yes, I did this, it was going through review, but it rejects my last submissions.

**Comment by christocracy** [comment]
See here:  https://github.com/transistorsoft/capacitor-background-geolocation/issues/289#event-15380412097

**Comment by ademirtemur** [comment]
I did it but there was no change, Google rejected it, is there a problem with the config I made?

**Comment by christocracy** [comment]
It’s between you and Google.  There’s nothing wrong with your Config.  Google doesn’t feel your app deserves these permissions.  It’s up to you to object to them and prove why your app deserves those permissions.

My blog entries document how to remove those permissions.

**Comment by ademirtemur** [comment]
I added key and huawei maven repo to the apk so that the plugin can work on Huawei. Could it be that we are being rejected for this reason? What do you know about this?

**Comment by christocracy** [comment]
Why don’t you share exactly what the rejection email says?

**Comment by ademirtemur** [comment]
<img width="403" alt="Screenshot 2024-12-12 at 07 50 30" src="https://github.com/user-attachments/assets/9596e9f4-9193-4618-8f9b-1e5e6c0aaef7" />
<img width="406" alt="Screenshot 2024-12-12 at 07 50 55" src="https://github.com/user-attachments/assets/631830c3-6546-4461-9fd4-f9266865e112" />
<img width="406" alt="Screenshot 2024-12-12 at 07 51 20" src="https://github.com/user-attachments/assets/c4842a4d-d8c2-41b0-8820-e7b91cc44549" />

**Comment by christocracy** [comment]
Your issue has nothing to do with any kind of dependency (eg huawei).  It completely related to my blog entry.

you need to get in personal contact with a reviewer.

**Comment by ademirtemur** [comment]
bu blogdan mı bahsediyorsun? Burdaki her adımı uyguladım. https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a

"react-native-background-fetch": "^4.1.10",
"react-native-background-geolocation": "^4.17.3",

<img width="473" alt="Screenshot 2024-12-12 at 10 08 31" src="https://github.com/user-attachments/assets/c935622e-cd4b-444e-8a1f-3f78de66d3aa" />

<uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
  <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>
  <uses-permission android:minSdkVersion="33" android:name="android.permission.SCHEDULE_EXACT_ALARM" />
  <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
  <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <uses-permission android:name="com.google.android.c2dm.permission.SEND" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" tools:node="remove" />

**Comment by christocracy** [comment]
My blog entry documents my experience submitting the Demo app.  It’s not a guaranteed method to get every app submitted.  Every case is different.

see here for [this guy’s successful experience](See here: https://github.com/transistorsoft/capacitor-background-geolocation/issues/289#event-15380412097)

**Comment by ademirtemur** [comment]
this works, add these lines.

<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" tools:node="remove" />
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" tools:node="remove" />

**Comment by ademirtemur** [comment]
this works, add these lines.

`<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" tools:node="remove" />`
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" tools:node="remove" />`
