### ISSUE TITLE
Manually request Motion & Fitness Activity

### ISSUE THREAD

**Issue by dougschurman** [transistorsoft/react-native-background-geolocation#2229]
## Your Environment
* Plugin version: 4.17.4
* Platform: iOS
* OS version: 18.1.1
* Device manufacturer / model: iPhone 14 Pro
* React Native version (`react-native -v`): 76
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
			// Geolocation Config
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
			stopOnTerminate: false, // Allow the background-service to continue tracking when user closes the app.
			enableHeadless: true, // Allow android tracking when app is terminated stopOnTerminate must be false
			startOnBoot: true, // Auto start tracking when device is powered-up.
			preventSuspend: true,
			elasticityMultiplier: 10,
			distanceFilter: 200,
			stopTimeout: 15, // change state to stationary after 15 minutes of no movement
			heartbeatInterval: 15 * 60, // Every 15 minutes trigger to wake up and get location
			notification: {
				title: 'MySpot Driver Mobile',
				text: 'Currently tracking Shipment progress.',
			},
		}).then(() => {
			console.log('- BackgroundGeolocation is configured and ready');
		});
```

## Context
I have implemented this package in our production app and it works perfectly. However, we have situations where we do not need to track a user until a condition is met. We track this by having an interval in the background that periodically checks the condition then calls await BackgroundGeolocation.start(). Normally, this would be called after a user logs in and the start method requests permission for Motion & Fitness Activity. As motion activity is very important to the effectiveness of  tracking, we want to be able to request this permission before the user even logs in and starts tracking. We currently do with with Expo-Location for location permission first thing after the app is downloaded an opened. We would like to do the same for motion activity, but using the Expo recommended method in the Expo-Sensor package seems to always return a status of GRANTED and doesn't request on app open. See https://github.com/expo/expo/issues/30571. 

I would like to know if there's a way we can use this plugin to request motion activity permission similar to the existing BackgroundGeolocation.requestPermission().

</details>

**Comment by christocracy** [comment]
No.

see api docs Config.disableMotionActivityUpdates.

then use your own 3rd party permissions package to request any desired permission you wish.
