### ISSUE TITLE
Question: How to prevent the plugin from requesting background location?

### ISSUE THREAD

**Issue by ca057** [transistorsoft/react-native-background-geolocation#227]
I am currently using the plugin to watch the location while using the app and at the moment I do not need the location while the app is in the background. I'm only requesting the location "WhileInUse" and configured the plugin accordingly. But when I now start the app and request the location permission, I get an alert for around a second, stating that the Background Location is not enabled. I do not want to show this alert to the user as I am not using the location in the background at the moment. Is there any possibility to turn this alert off? I read through the documentation but cannot find a hint where to turn this off.

Thanks in advance for your help.

## Your Environment
Besides the configuration below, I do not enable Background Capabilities and removed the BackgroundFetch-library, as I do not need these features.

* Plugin version: 2.6.1
* Platform: iOS
* OS version: iOS 10.2 (Simulator)
* Device manufacturer / model: iPhone 6 (Simulator)
* React Native version (`react-native -v`): 0.39.2
* Plugin config:
```
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  disableMotionActivityUpdates: true,
  stopOnTerminate: true,
  autoSync: false,
  maxDaysToPersist: 0,
  maxRecordsToPersist: 0,
  logMaxDays: 0,
  locationAuthorizationRequest: 'WhenInUse',
  locationAuthorizationAlert: { /* custom UI texts */ },
}
```

## Expected Behavior
I do not want to have an alert warning the user that Background Location is not enabled when I am not using them.

## Actual Behavior
The mentioned alert is shown.

## Steps to Reproduce

1. Only request 'WhenInUse'
2. Do not enable any Background Capabilites

**Comment by christocracy** [comment]
Show me the Javascript you're executing.

**Comment by ca057** [comment]
The strange thing is that this alert does not appear every time I reinstall the app.

I setup my wrapper (to combine it with other libraries and to have a similar API on Android) around your library like this:
```
class GeoLocationService {
  init(options = {}) {
    return new Promise((initSuccess, initError) => {
      BackgroundGeolocation.configure(
        {
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          disableMotionActivityUpdates: true,
          stopOnTerminate: true,
          autoSync: false,
          maxDaysToPersist: 0,
          maxRecordsToPersist: 0,
          logMaxDays: 0,
          locationAuthorizationRequest: 'WhenInUse',
          locationAuthorizationAlert,
          ...options,
        },
        ({ enabled }) => {
          if (!enabled) {
            BackgroundGeolocation.start(initSuccess, initError);
          } else {
            initSuccess();
          }
        },
        initError,
      );
    });
  }

  watchPosition(success, error) {
    return Promise.resolve().then(() => {
      BackgroundGeolocation.watchPosition(success, error, {
        persist: false,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
      });
    });
  }

  clearWatch() {
    return new Promise(BackgroundGeolocation.stopWatchPosition).then(BackgroundGeolocation.stop);
  }

  getCurrentPosition(onSuccess, onError) {
    return Promise.resolve().then(
      () => new Promise((resolve, reject) => {
          BackgroundGeolocation.getCurrentPosition(
            position => {
              onSuccess(position);
              resolve();
            },
            error => {
              onError(error);
              reject(error);
            },
            {
              timeout: 30,
            },
          );
      }),
    );
  }

}
```

When I start the app, I request the permission to use the location When In Use from the user. After a positive response, I basically do the following:
```
// only if we have the permission for the location
const geoService = new GeoLocationService();

geoService.init()
  .then(() => geoService.getCurrentPosition(successHandler, errorHandler))
  .then(() => geoService.watchPosition(successHandler, errorHandler));
```

**Comment by christocracy** [comment]
If you don't want the plugin to automatically track the device, don't call `#start`.
