### ISSUE TITLE
Why it's only paid for Android developers?

### ISSUE THREAD

**Issue by anaibol** [transistorsoft/react-native-background-geolocation#23]
Hi, I only wanted to ask if there is a reason why only Android developers have to pay for that plugin.
Thanks!

**Comment by christocracy** [comment]
People typically make an app for multiple platforms (especially iOS
+ Android).  As well, developers tend to create the iOS version first,
before moving on to Android.  Isn't that what Facebook did with React
Native?

I wanted to provide one platform free so devs could experience and develop
using iOS.  When they're confident with the performance of iOS, they
purchase Android and it all just works.

Finally, which platform is most important?  Most of the people on Earth use
and Android phone -- not iPhones.

That's why iOS is free.

On Sunday, November 1, 2015, Juan Anibal Micheli <notifications@github.com>
wrote:

> Hi, I only wanted to ask if there is a reason why only Android developers
> have to pay for that plugin.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/23>
> .
>


-- 
Snet form Gmail Mobile

**Comment by anaibol** [comment]
I see.. bad news for Android first hybrid developers :(
Thanks anyway!

**Comment by christocracy** [comment]
I'm able to sell cheaper single-app licenses now.

Haven't priced it yet.  Maybe $250.  The cost is really all about covering
support.

The Android side is alive now.  Needs a bit more wiring is all.  Should be
ready in a few days.

On Sunday, November 1, 2015, Juan Anibal Micheli <notifications@github.com>
wrote:

> I see.. bad news for Android first hybrid developers :(
> Thanks anyway!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/23#issuecomment-152859868>
> .
>


-- 
Snet form Gmail Mobile

**Comment by anaibol** [comment]
Good to know!

**Comment by cooperka** [comment]
Hi @christocracy, I appreciate your work on this library, but charging a license fee for using your code really rubs me the wrong way. I understand charging for a service or a website, but charging for the use of open-source code? I've honestly never seen this before. It certainly doesn't make me want to contribute, and I can't afford the high fees 😞

Why have you chosen to do this?

**Comment by christocracy** [comment]
This plugin *is* a service.  I support it full time.

I have over 1000 paying and happy customers and the plugin generates *a lot* of revenue.  So much that I've devoted the last 3 years of my life to supporting it *full time*.  I do nothing else but innovate this plugin *every day*.

This is not some simple little wrapper around native location APIs.  It's 20k lines of Obj-c and Java.  This is essentially a headless native app.  If you want to make this yourself, it'll cost you > $80k in time.

**Comment by christocracy** [comment]
Btw, the library is not open source.  The library is a compiled binary for both iOS and Android.  There's little for you to contribute *to*.

**Comment by christocracy** [comment]
@cooperka your point-of-view is expected but is the minority.  The feedback to this plugin is *overwhelmingly* positive.

Here's my all time Chat feedback report (93% positive)

![](https://dl.dropboxusercontent.com/s/t2h8rwyoebklyvj/Screenshot%202017-09-13%2011.47.15.png?dl=1)

**Comment by cooperka** [comment]
> Have you ever seen a plugin which offers up a chat box to the author?

Yes, besides regular GitHub issues, a good number of open-source libraries also have Gitter, Slack, IRC, or Riot channels :smile: 

> 93% positive

Perhaps most of the users who end up contacting you through support are those who are willing to pay, and thus the sample is biased? It's a nice metric though, I don't doubt you have a lot of happy customers.

Thanks for the info and your perspective. I still disagree philosophically but that's okay, I just wanted get your thoughts. I'll move along now, cheers!

**Comment by anaibol** [comment]
What is doing this on github?

**Comment by AdamLenda** [comment]
@cooperka,

I make my living writing code. I charge my clients by the hour for the work do. There is no question that buying this library saved me time and my clients money. Chris even spent 2.5 hours on the phone with me debugging a build issue. 

When guy goes this far, and provides this level of support, yeah... he should totally be getting paid for it.

If you are a hobbits just hacking for fun, then yeah, this library might not be the one for you. There are other, inferior and free, options that are maintained by people who only work on it when they have time to spare.

However, if your building something you are serious about, then there is a very clear return on investment here.

**Comment by jeffreymendez1993** [comment]
Whats stopping someone from using it with out a license on android lol?  You know someone could just bring in the library and remove the part that requires a license. Yeah you should never charge someone for something that is OPEN-SOURCE. Go make a website that offers a service instead. Legit ruining the open source part of a library since your allowing it to be free for one platform.

**Comment by christocracy** [comment]
@jeffreymendez1993 the only reason I now publish the Android binary publicly, allowing you to try before you buy, is that I’ve mitigated against that.

**Comment by jeffreymendez1993** [comment]
@christocracy  going to try this out. My java experience is minimal so if I can convince my company for the license that will save time which is money. I saw a url option in the configuration I guess that is a constant socket request to the servers api endpoint. Is that required?

**Comment by christocracy** [comment]
Not for sockets.  It’s going to upload locations via http request.  Sockets are not feasible for long-term operation in the background.

**Comment by AdamLenda** [comment]
@jeffreymendez1993 hopefully.... Character and Ethics :D
