### ISSUE TITLE
changePace - Question

### ISSUE THREAD

**Issue by vessp** [transistorsoft/react-native-background-geolocation#230]
## Your Environment
* Plugin version: 2.4.1
* Platform: iOS
* OS version: 10
* Device manufacturer / model: Apple iPhone 6
* React Native version (`react-native -v`): 0.41.2

## Context

Hello, in my app I call **changePace(true)** when the user presses the Start Tracking button.  My question is: In order to preserve battery life, do I need to make sure to manually call **changePace(false)** later to ensure that Location Services return to normal operations or will it return to normal operations by itself once stop detection signals that the user has stopped?

Thanks

**Comment by christocracy** [comment]
The plugin **strongly** desires to be in the stationary state.  When the MotionActivity API says the device is still at a confidence >= #minimumActivityRecognitionConfidence, the #stopTimeout timer will initiate, the expiration of which, will cause location services to toggle off

**Comment by vessp** [comment]
Ok Thankyou
