### ISSUE TITLE
Error: Native module cannot be null

### ISSUE THREAD

**Issue by oluckyman** [transistorsoft/react-native-background-geolocation#231]
## Your Environment
* Plugin version: 2.7.0
* Platform: iOS
* OS version: 10.2
* Device manufacturer / model: iOS Simulator iPhone 6
* React Native version (`react-native -v`): 0.42.0
* Plugin config
None / Default

## Expected Behavior

The app should run without errors

## Actual Behavior

Red Screen Of Death:
![image](https://cloud.githubusercontent.com/assets/642673/24056348/9da567f0-0b43-11e7-8be3-6f6f3caec9a9.png)

## Steps to Reproduce

1. Walk thru instruction: https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md
*NOTICE* that instruction has ambiguity here: https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md#build-phases--link-binary-with-libraries
![image](https://cloud.githubusercontent.com/assets/642673/24056701/0780a152-0b45-11e7-8fe0-5c526c0e69e9.png)

2. in `index.ios.js` file add this line:
```
global.BackgroundGeolocation = require('react-native-background-geolocation');
```

## Context
At least make the app run without errors.

## Debug logs
Not sure which logs are needed..

**Comment by christocracy** [comment]
Is this your first time installing it?

**Comment by christocracy** [comment]
Try
```javascript
import BackgroundGeolocation from 'react-native-background-geolocation';

global.BackgroundGeolocation = BackgroundGeolocation;
```

**Comment by oluckyman** [comment]
Yep, first time. `import` does not help.  
Could you please clarify ['Build Phases'](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md#build-phases--link-binary-with-libraries) step, should I add 3 static libs `libRNBackgroundGeolocation.a libRNBackgroundFetch.a libCocoaLumberjack.a` or only two of them?
I’ll try to rollback and walk thru instructions again.

**Comment by christocracy** [comment]
It is as the image says:  3

**Comment by oluckyman** [comment]
I did as the image said. Ok will try again

**Comment by christocracy** [comment]
What is your XCode version?

**Comment by christocracy** [comment]
You restarted dev server after installing it?

**Comment by oluckyman** [comment]
My XCode version is 8.2.1
I’ve rolled back and went thru [instructions steps](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md) once again very carefully. Now it does not throw any error. 
Thanks for support and sorry for bothering you
