### ISSUE TITLE
Error in android build: Could not find :tslocationmanager:.

### ISSUE THREAD

**Issue by timLoewel** [transistorsoft/react-native-background-geolocation#232]
## Your Environment
* Plugin version: 
    "react-native-background-geolocation": "^2.7.0",
* Platform: iOS or Android
Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
react-native-cli: 2.0.1
react-native: 0.42.0

* Plugin config
N.A.
## Expected Behavior
install the plugin, compile the app
## Actual Behavior
failure to build.

## Steps to Reproduce

1. npm install react-native-background-geolocation --save
2. react-native link react-native-background-geolocation
3. react-native run-android
4. 
```
➜ ✗ react-native run-android 
Scanning 834 folders for symlinks in /../node_modules (21ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find :tslocationmanager:.
     Required by:
         sites:app:unspecified > sites:react-native-background-geolocation:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.885 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```
## Context
When comparing to the demo app, I see there is a repositories section in the build.gradle 
`repositories {
    flatDir {
        dirs "../../node_modules/react-native-background-geolocation/android/libs"
    }
}```

**When I add this `repositories` section to my build.gradle, the build succeeds.**

I guess, this should be added by the `react-native link`?

**Comment by christocracy** [comment]
Did you perform the required manual step in the [rnpm setup guide](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md)

**Comment by christocracy** [comment]
If I could script that required manual step, I would.  There's probably a way.

**Comment by timLoewel** [comment]
Oh Chris, I am so sorry. 
I am so used to `react-native link` doing all the work, that I only read the first paragraph, and (foolishly) assumed the rest of the description to be part of the 

**With older versions of React Native**

section.

Thanks!
