### ISSUE TITLE
Plugin spams url regardless of distanceFilter or locationUpdateInterval

### ISSUE THREAD

**Issue by jmeyers91** [transistorsoft/react-native-background-geolocation#234]
## Your Environment
* Plugin version: 2.6.0
* Platform: iOS
* OS version: 10.2
* Device manufacturer / model: iPhone 6
* React Native version (`react-native -v`): 0.41.2 (cli version 2.0.1)
* Plugin config

```
        desiredAccuracy: 0,
        distanceFilter: 10,
        debug: false,
        logLevel: bgGeo.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        url: `${config.server}/api/updateLocation`,
        autoSync: true,
        disableElasticity: true,
        headers: {
            Authorization: `Bearer ${userAuthToken.access_token}`
        }
```

## Expected Behavior

The module should send a POST request to the server containing the user's location every 10 meters.
## Actual Behavior

The module sends tens of POST requests per second immediately after starting regardless of whether the user is moving. I should note that I'm testing in the iOS simulator. I've received this result with the iOS debuggers location setting set to "City Run" and "Apple".

## Steps to Reproduce

```
function start(userAuthToken) {
    const options = {
        desiredAccuracy: 0,
        distanceFilter: 10,
        debug: false,
        logLevel: bgGeo.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        url: `${config.server}/api/updateLocation`,
        autoSync: true,
        disableElasticity: true,
        headers: {
            Authorization: `Bearer ${userAuthToken.access_token}`
        }
    };

    bgGeo.onHttp(
        (response) => {
            console.log('location post success response', response);
        },
        (response) => {
            console.log('location post fail response', response);
        }
    );

    return new Promise((resolve) => {
        bgGeo.configure(options, (a) => {
            console.log('bgGeo.configure callback', a);
            bgGeo.start(resolve);
        });
    });
}

start();
```

## Context

I'm trying to send location updates to my server when the user moves at least 10 meters.

**Comment by christocracy** [comment]
Nothing I can do.  The native location API thinks you're moving 10 meters.  Increase distanceFilter or set an autoSyncThreshold >0

**Comment by jmeyers91** [comment]
Thanks for the quick response. It's helpful enough just knowing the issue is with the simulator.
