### ISSUE TITLE
stopOnTerminate false doesn't prevent plugin from stopping on app termination.

### ISSUE THREAD

**Issue by jmeyers91** [transistorsoft/react-native-background-geolocation#236]
## Your Environment
* Plugin version:
* Platform: iOS
* OS version: 10.2
* Device manufacturer / model: iPhone 5
* React Native version (`react-native -v`): 0.41.2 (cli 2.0.1)
* Plugin config

```
{
        preventSuspend: false,
        disableStopDetection: false,
        stationaryRadius: 1,
        desiredAccuracy: 0,
        distanceFilter: 3,
        debug: true,
        logLevel: bgGeo.LOG_LEVEL_OFF,
        stopOnTerminate: false,
        startOnBoot: false,
        url: `${config.server}/api/updateLocation`,
        autoSync: true,
        headers: {
            Authorization: `Bearer ${userAuthToken.access_token}`
        }
 }
```

## Expected Behavior
The app should continue sending POST requests to the server after I terminate it.

## Actual Behavior
The app stops sending POST requests to the server after I terminate it.

## Steps to Reproduce
1. Run app on device through xCode
2. Confirm the server is receiving location updates
3. Close the app

Here is the code that handles configuring, starting, and listening to the plugin:

```
export function start(userAuthToken) {
    const options = {
        preventSuspend: false,
        disableStopDetection: false,
        stationaryRadius: 1,
        desiredAccuracy: 0,
        distanceFilter: 3,
        debug: true,
        logLevel: bgGeo.LOG_LEVEL_OFF,
        stopOnTerminate: false,
        startOnBoot: false,
        url: `${config.server}/api/updateLocation`,
        autoSync: true,
        headers: {
            Authorization: `Bearer ${userAuthToken.access_token}`
        }
    };

    bgGeo.onHttp(
        (response) => {
            let notes;
            try {
                notes = JSON.parse(response.responseText).body;
            } catch(error) {
                console.log('Failed to parse notes', response);
            }
            if(notes) store.dispatch(receiveNotes(notes));
        },
        (response) => {
            console.log('location post fail response', response);
        }
    );

    return new Promise((resolve, reject) => {
        bgGeo.configure(options, () => {
            bgGeo.start(() => {
                bgGeo.changePace(true, resolve, reject);
            },  reject);
        });
    });
}
```

## Context
I'm trying to send push notifications depending on the user's location while the app is closed.

## Debug logs
I'm not really sure how to get logs after I close the app.

**Comment by christocracy** [comment]
Watch [this video](https://youtu.be/rFNDIQLEouo?t=70).

Yes, your iOS is **fully terminated** when user terminates the app.  However, when the device moves ~200 meters, it *will* reboot in the background and continue tracking.  

This is easy to observe in the iOS simulator.

**Comment by jmeyers91** [comment]
@christocracy I'm unable to test in the simulator due to [this issue](https://github.com/transistorsoft/react-native-background-geolocation/issues/234) and the lack of push notification support.

Thank you for the response. It probably wasn't sending requests because I was only walking around the office, so I wasn't moving 200 meters.
