### ISSUE TITLE
Problems installing related to LumberJack

### ISSUE THREAD

**Issue by fozzarelo** [transistorsoft/react-native-background-geolocation#237]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^2.7.0"
* Platform: iOS
* OS version: pre-build
* Device manufacturer / model: pre-build
* React Native version (`react-native -v`): 0.42.0
* Plugin config pre-build

Hi: I am trying to run my podsfile and I am finding an unmet

- `CocoaLumberjack` required by `Podfile`
- `CocoaLumberjack (~> 3.0)` required by `RNBackgroundGeolocation (2.7.0)`

I guess I need to include it too, but what's the path?

**Comment by christocracy** [comment]
Pod CocoaLumberjack  is already in this plugin's [podspec](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/RNBackgroundGeolocation.podspec#L21)

**Comment by fozzarelo** [comment]
Thanks Chris:

That means you podspec ran when I added:
"pod 'RNBackgroundGeolocation', :path => 'my_path" 
to my podfile, right? Nothing extra to do on my part. 

I wonder about this error then.. 
I think It's a version issue. I think im getting CocoaLumberjack v2.4 by default.  My lock stays at 2.4.0 even when I update. There doesnt seem to be much support or documentation on how to migrate to V.3 In their docs it literally says: to be determined. 

My lock:
  - CocoaLumberjack (2.4.0):
    - CocoaLumberjack/Default (= 2.4.0)
    - CocoaLumberjack/Extensions (= 2.4.0)
  - CocoaLumberjack/Core (2.4.0)
  - CocoaLumberjack/Default (2.4.0):
    - CocoaLumberjack/Core
  - CocoaLumberjack/Extensions (2.4.0):
    - CocoaLumberjack/Default
  - Crashlytics (3.8.4):
    - Fabric (~> 1.6.3)

**Comment by christocracy** [comment]
One of your dependencies is requesting an old version of `CocoaLumberjack` @ `2.4.0`.

Mine requests [latest @ `3.0.0`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/RNBackgroundGeolocation.podspec#L21)

**Comment by fozzarelo** [comment]
Yup.. correct.. Is v3 a must for you? Do I get it manually? Look's like it's installing 2.4 by default.

**Comment by christocracy** [comment]
I doubt my plugin will work with `< 3.0.0`.

**Comment by christocracy** [comment]
Check your dependencies.  Go ask them why they're not keeping up with latest Lumberjack.

**Comment by fozzarelo** [comment]
Sounds good,
Thank you Chris.

**Comment by christocracy** [comment]
Ok, I got it working.  Took me an hour, including initial Expo setup.

See [this comment](https://github.com/transistorsoft/react-native-background-geolocation/issues/184#issuecomment-290735292)

**Comment by christocracy** [comment]
I posted an issue to [ExpoKit](https://github.com/expo/expo/issues/100)

**Comment by christocracy** [comment]
ExpoKit will [fix this](https://github.com/expo/expo/issues/100#issuecomment-290772544) in their next version.
