### ISSUE TITLE
Background Geolocation with Expo

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/react-native-background-geolocation#238]
With my first experience with [Exponent](https://docs.expo.io/versions/v15.0.0/index.html), it took me about an hour, including initial Exponent setup, to get `BackgroundGeolocation` running.

You will have, of course, have to ["detach"](https://docs.expo.io/versions/v15.0.0/guides/detach.html) your Expo app in order to use the plugin.

Once detached, I basically followed this plugin's [Cocoapod Setup](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS-COCOAPODS.md)

The only hiccup I had was a dependency issue on `CocoaLumberjack` (my plugin uses latest) but `ExpoKit` relies upon `2.3.0`.  I've [posted an issue](https://github.com/expo/expo/issues/100) to ExpoKit about this (**update**: they quickly responded and [will be fixed](https://github.com/expo/expo/issues/100#issuecomment-290772544) in their next version)

I simply edited `.expo-source/ios/ExpoKit.podspec` and modified the dependency to `~> 3.0`.

```diff
+s.dependency 'CocoaLumberjack', '~> 3.0'
```

After that, I edited my Expo app's `main.js`:

```javascript
import Expo from 'expo';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import BackgroundGeolocation from "react-native-background-geolocation";

class App extends React.Component {
  componentDidMount() {

    BackgroundGeolocation.on('motionchange', (event) => {
      console.log('motionchange', event);
    });
    BackgroundGeolocation.on('location', (location) => {
      console.log('location', location);
    });
    BackgroundGeolocation.on('providerchange', (provider) => {
      console.log('providerchange', provider);
    });
    BackgroundGeolocation.configure({debug: true, logLevel: 5}, (state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start();
      }
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Open up main.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

Expo.registerRootComponent(App);
```

Do a restart in **Expo XDE**, then Run the project.  Simulate location in Simulator with City Drive and the plugin starts talking.

![](https://www.dropbox.com/s/ydn3xzzeonvm95u/Screenshot%202017-03-31%2010.55.58.png?dl=1)

**Comment by fozzarelo** [comment]
Expo has updated their podspec since. So this isnt an issue anymore.
