### ISSUE TITLE
Ton of warnings in TSLocationManager when generating dSYM

### ISSUE THREAD

**Issue by nevir** [transistorsoft/react-native-background-geolocation#24]
https://gist.github.com/nevir/cec22cb528dbe9c970c3

https://forums.developer.apple.com/thread/17921 or https://github.com/Appboy/appboy-ios-sdk/issues/30 might be relevant, but unsure

**Comment by christocracy** [comment]
Yes, I noticed this as well.  I found that link as well.  I'll get that
silenced soon.

On Tuesday, November 3, 2015, Ian MacLeod <notifications@github.com> wrote:

> https://gist.github.com/nevir/cec22cb528dbe9c970c3
>
> https://forums.developer.apple.com/thread/17921 might be relevant, but
> unsure
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/24>
> .
>


-- 
Snet form Gmail Mobile

**Comment by nevir** [comment]
Awesome, thanks!

**Comment by christocracy** [comment]
Warnings should be suppressed now

**Comment by nevir** [comment]
I'm [still seeing them](https://gist.github.com/nevir/84109a6fae2a749cea61) as of `0.1.0` :(

**Comment by christocracy** [comment]
I'll install the app from scratch and see what's up

**Comment by christocracy** [comment]
I'll go through booting iOS sample app from scratch tomorrow.

On Tuesday, November 10, 2015, Ian MacLeod <notifications@github.com> wrote:

> I'm still seeing them <https://gist.github.com/nevir/84109a6fae2a749cea61>
> as of 0.1.0 :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/24#issuecomment-155625265>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
I booted up a fresh new app and followed the install steps.  No warnings.  Try removing the TSLocationManager.framework then re-add.  @see [Installation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Installation)
