### ISSUE TITLE
Problem with current location and controlling when to locate the user 

### ISSUE THREAD

**Issue by Hudhud** [transistorsoft/react-native-background-geolocation#240]
Hello,

I am facing some issues, which doesn't make sense for me. I have been trying to find out how to control when to locate, but without luck. I have tried to uncomment the line bgGeo.start() as it doesn't write to the console BackgroundGeolocation ready. I have the exact same code as the posted. Furthermore I have trying to let it check if the Location is enabled, but it doesn't react on an if statement. I have tested it by letting it write to the console log.

This is the code

    `BackgroundGeo() {

    function onDeviceReady() {
    // Get a reference to the plugin.
    var bgGeo = ( < any > window).BackgroundGeolocation;

    //This callback will be executed every time a geolocation is recorded in the background.
    var callbackFn = function(location, taskId) {
        var coords = location.coords;
        var lat = coords.latitude;
        var lng = coords.longitude;
        console.log('- Location: ', JSON.stringify(location));

        // Must signal completion of your callbackFn.
        bgGeo.finish(taskId);
    };

    // This callback will be executed if a location-error occurs.  Eg: this will be called if user disables location-services.
    var failureFn = function(errorCode) {
        console.warn('- BackgroundGeoLocation error: ', errorCode);
    }

    // Listen to location events & errors.
    bgGeo.on('location', callbackFn, failureFn);
    // Fired whenever state changes from moving->stationary or vice-versa.
    bgGeo.on('motionchange', function(isMoving) {
        console.log('- onMotionChange: ', isMoving);
    });
    // Fired whenever a geofence transition occurs.
    bgGeo.on('geofence', function(geofence) {
        console.log('- onGeofence: ', geofence.identifier, geofence.location);
    });
    // Fired whenever an HTTP response is received from your server.
    bgGeo.on('http', function(response) {
        console.log('http success: ', response.responseText);
    }, function(response) {
        console.log('http failure: ', response.status);
    });

    // BackgroundGeoLocation is highly configurable.
    bgGeo.configure({
        // Geolocation config
        desiredAccuracy: 0,
        distanceFilter: 10,
        stationaryRadius: 25,
        // Activity Recognition config
        activityRecognitionInterval: 10000,
        stopTimeout: 5,
        // Application config
        debug: true, // <-- Debug sounds & notifications.
        stopOnTerminate: false,
        startOnBoot: true,
        // HTTP / SQLite config
        url: "http://your.server.com/locations",
        method: "POST",
        autoSync: true,
        maxDaysToPersist: 3,
        /*   headers: {  // <-- Optional HTTP headers
               "X-FOO": "bar"
           },
           params: {   // <-- Optional HTTP params
               "auth_token": "maybe_your_server_authenticates_via_token_YES?"
           }*/
    }, function(state) {
        // This callback is executed when the plugin is ready to use.
        console.log("BackgroundGeolocation ready: ", state);
        if (!state.enabled) {
            bgGeo.start();
        }
      });
     }

    }

* Plugin version: 2.4.2
* Platform: iOS or Android: Android
* OS version: Windows 8.1
* Device manufacturer / model: Samsung
* React Native version (`react-native -v`): Don't know and commands is not recognized

**Comment by christocracy** [comment]
Dude, you are seriously confused.  This is the **React Native** version of the plugin.   You are not using React Native -- You're using **Cordova**.

Go to the [Cordova version](https://github.com/transistorsoft/cordova-background-geolocation-lt)

**Comment by christocracy** [comment]
And have you look at [the docs](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#small_blue_diamond-core-api-methods)

There's a `#start` method and a `#stop` method.
