### ISSUE TITLE
Attaching more metadata to events?

### ISSUE THREAD

**Issue by mattiaslinnap** [transistorsoft/react-native-background-geolocation#243]
Is it possible to attach more metadata to events before they are stored locally in SQLite and later sent to the server? Or perhaps even completely custom events?

For example, I would like to add current user profile or privacy preferences to locations, to allow switching between private, limited and public tracking on the go. And some custom events, like "save this location".

These metadata or extra events have to be synchronized to the GPS locations, so using the existing storage and upload system would be much more convinient than having a parallel database and linking data by timestamps.

**Comment by christocracy** [comment]
See HTTP & Persistemce section in docs.

See #extras config option

**Comment by mattiaslinnap** [comment]
These extras are attached at http request time, not persist time, right?

Ideally I would like to attach metadata to each location before it is persisted. The device might be offline, and the user might change settings at any time during tracking. Then later when uploading locations, each location gets sent with unique metadata.

If this is not possible, it's fine, just wondering if it can be done directly via the upload module or needs a separate database and sync.

**Comment by christocracy** [comment]
`#extras` are attached when location is persisted.
