### ISSUE TITLE
[autosync] Add a Header in the HTTP POST

### ISSUE THREAD

**Issue by apinango92** [transistorsoft/react-native-background-geolocation#245]
Hi, 
I cannot find in the documentation how to add a Header in the HTTP request.
I need to add the header Content-Type=application/json

Thank you!

**Comment by christocracy** [comment]
The docs are conveniently organized by category.  [`#headers`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-object-headers) exists in the ["HTTP & Persistence"](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#wrench-http--persistence-options) section.

```javascript
bgGeo.configure({
  headers: {foo: 'bar'}
});
```

**Comment by apinango92** [comment]
Hi, Thank you for the early response

It's not working I don't know what It's wrong.

I have to send this type of JSON:

{
	"bulk": [
		{
			"id": "550e8400-e29b-41d4-a716-446655440000",
			"latitude":-33.448890,
			"longitude":-70.669265,
			"timestamp":"1491308853",
			"type": "background"
		},		
		{
			"id": "550e8400-e29b-41d4-a716-446655440000",
			"latitude":-33.448890,
			"longitude":-70.669265,
			"timestamp":"1491308853",
			"type": "background"
		}
	],
}


So I put this in my code:
BackgroundGeolocation.configure({
          httpRootProperty: 'bulk',
          headers: {Content-Type: 'application/json'},
          locationTemplate: '{"id":"<%= uuid %>","latitude":<%= latitude %>,"longitude":<%= longitude %>,"timestamp":"<%= timestamp %>"}',
          extras: {
            "type": "background",
          }
});

What am I doing wrong?. The problem is n the header apparently

Thank you!

**Comment by christocracy** [comment]
- The plugin automatically sets the header `content-type: "application/json"`.
- If you need to send an `Array` of locations, you need to set `batchSync: true`.

**Comment by christocracy** [comment]
and btw, learn to use markdown for your code snippets.   there's a helpful link right on this page.

![](https://www.dropbox.com/s/mtif7jjqdiu836s/Screenshot%202017-04-20%2017.41.35.png?dl=1)

**Comment by christocracy** [comment]
Here's what the default headers look like without providing any (as you can see, `content-type` is already provided)

![](https://www.dropbox.com/s/4nvnylfcnj0856v/Screenshot%202017-04-20%2017.44.07.png?dl=1)

**Comment by apinango92** [comment]
Great, thank you very much for all your help!
