### ISSUE TITLE
Emit namespaced events over the bridge

### ISSUE THREAD

**Issue by JAStanton** [transistorsoft/react-native-background-geolocation#25]
I'm particularly concerned about `error` event colliding with my app.  I think a better event name might be `geolocation:error`

**Comment by christocracy** [comment]
Will do.

On Wednesday, November 4, 2015, Jonathan Stanton <notifications@github.com>
wrote:

> I'm particularly concerned about error event colliding with my app. I
> think a better event name might be geolocation:error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/25>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
But wait:  are these events not scoped to the BackgroundGeolocation API?

On Wednesday, November 4, 2015, Chris Scott <christocracy@gmail.com> wrote:

> Will do.
>
> On Wednesday, November 4, 2015, Jonathan Stanton <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I'm particularly concerned about error event colliding with my app. I
>> think a better event name might be geolocation:error
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/react-native-background-geolocation/issues/25>
>> .
>>
>
>
> --
> Snet form Gmail Mobile
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Oh, no they're not.  I'll have the js API automatically append a prefix so
you won't have to change the code.

On Wednesday, November 4, 2015, Chris Scott <christocracy@gmail.com> wrote:

> But wait:  are these events not scoped to the BackgroundGeolocation API?
>
> On Wednesday, November 4, 2015, Chris Scott <christocracy@gmail.com
> <javascript:_e(%7B%7D,'cvml','christocracy@gmail.com');>> wrote:
>
>> Will do.
>>
>> On Wednesday, November 4, 2015, Jonathan Stanton <
>> notifications@github.com> wrote:
>>
>>> I'm particularly concerned about error event colliding with my app. I
>>> think a better event name might be geolocation:error
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/transistorsoft/react-native-background-geolocation/issues/25>
>>> .
>>>
>>
>>
>> --
>> Snet form Gmail Mobile
>>
>
>
> --
> Snet form Gmail Mobile
>


-- 
Snet form Gmail Mobile
