### ISSUE TITLE
'motionchange' event fires object, not boolean

### ISSUE THREAD

**Issue by dandelany** [transistorsoft/react-native-background-geolocation#250]
## Your Environment
* Plugin version: 2.8.0
* Platform: iOS
* OS version: 10.0.2
* Device manufacturer / model: Apple iPhone 6S
* React Native version (`react-native -v`): 43.3

## Expected Behavior
When I subscribe to the `motionchange` event, I expect the first argument to the listener to be a boolean `isMoving`, per documentation here: https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#motionchange

## Actual Behavior
The `motionchange` callback is called with a single object argument of the shape: `{isMoving: true, location: {...}}`

## Steps to Reproduce
```
BackgroundGeolocation.on('motionchange', function(isMoving, location, taskId) {
  console.log('got motion change:', isMoving, location, taskId);
});
```

## Debug logs
```
'got motion change:', { isMoving: true,
  location: 
   { coords: 
      { speed: -1,
        longitude: -73.99387897337888,
        latitude: 40.73993421017166,
        accuracy: 65,
        altitude_accuracy: 10,
        altitude: 16.3,
        heading: -1 },
     extras: {},
     is_moving: true,
     event: 'motionchange',
     odometer: 33199.9,
     uuid: '31F59B4A-EA51-460F-B67F-450E13141D34',
     activity: { type: 'still', confidence: 100 },
     battery: { level: 1, is_charging: true },
     timestamp: '2017-05-10T19:20:17.055Z' } }, undefined, undefined
```

**Comment by christocracy** [comment]
Unfortunately, in my attempt to control the documentation of all the plugin versions (Cordova, React Native, NativeScript), I used the Cordova docs for everyone.

You're finding a few cases where the docs differ from the React Native reality.

The docs are incorrect for React Native in this case.  For React Native, the plugin is supposed to return an `{}`.

**Comment by dandelany** [comment]
Gotcha, thanks for the quick response 👍

**Comment by christocracy** [comment]
The signature has been changed to `MotionChangeEvent` object.
