### ISSUE TITLE
'taskId' param is undefined in event callbacks

### ISSUE THREAD

**Issue by dandelany** [transistorsoft/react-native-background-geolocation#251]
## Your Environment
* Plugin version: 2.8.0
* Platform: iOS
* OS version: 10.0.2
* Device manufacturer / model: Apple iPhone 6S
* React Native version (`react-native -v`): 43.3
* Plugin config:
```
{
  desiredAccuracy: 0,
  distanceFilter: 10,
  stationaryRadius: 25,
  stopTimeout: 1,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  maxRecordsToPersist: 0,
  preventSuspend: true,
  heartbeatInterval: 60 * 10
};
```

## Expected Behavior
The docs for 'location' and 'motionchange' events say that the last argument for the listener callbacks is a `taskId` that should be passed to `BackgroundGeolocation.finish`. From the docs:

```
// The plugin runs your callback in a background-thread:
// you MUST signal to the native plugin when your callback is finished so it can halt the thread.
// IF YOU DON'T, iOS WILL KILL YOUR APP
BackgroundGeolocation.finish(taskId);
```

## Actual Behavior
In testing, when I log `taskId`, I've noticed that the last argument for both of these callbacks seems to always be `undefined`.

## Steps to Reproduce
```
BackgroundGeolocation.getCurrentPosition((location, taskId) => {
  console.log('location: ', location, 'taskId':, taskId);
  BackgroundGeolocation.finish(taskId);
});
```

## Debug logs
above code logs:
```
location: {...} taskId: undefined
```

**Comment by dandelany** [comment]
whoops accidentally submitted this before filling out the form - will edit to add information.

**Comment by dandelany** [comment]
Updated to add details. Let me know if you need any more info. Thanks!

**Comment by christocracy** [comment]
Again, same issue with common docs.  `taskId` applies on to Cordova.

No React Native callback receives a `taskId`.  If you want to perform a long-running task in your callback, you're responsible for creating your own `taskId`.

```
BackgroundGeolocation.startBackgroundTask(function(taskId) {
  console.log('start long running task');
  BackgroundGeolocation.finish(taskId);
});
```

**Comment by dandelany** [comment]
Ah OK, thanks @christocracy. Just to clarify, is this (wrapping in `startBackgroundTask`) something I *should* be doing in my `location` listener, if I'm eg. manually POSTing locations to a server? Or is it OK to just POST directly from the callback and not call `startBackgroundTask`/`finish`?

**Comment by christocracy** [comment]
you should wrap *any* long-running task in `startBackgroundTask`.

However, you should let the plugin manage posting location to your server.  It's very good at it (it has auto-retry on server failure).

It's particularly important for Android, if you care about `stopOnTerminate: false`, since your Javascript app gets killed if user (or OS) terminates your app.  Only the plugin's native background service remains alive, tracking with the ability to post using its own HTTP service.

**Comment by dandelany** [comment]
OK 👍 I'll try to use the plugin's built-in syncing, but our API is super-picky about the message format, especially for batched messages, so not sure if I will be able to get it to work with the current `template` setup. Will see what I can do. Thanks for your help :)

**Comment by christocracy** [comment]
The plugin provides full control to define your own [JSON schema](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/http.md), including batch requests.
