### ISSUE TITLE
Geofencing without background location updates

### ISSUE THREAD

**Issue by chrise86** [transistorsoft/react-native-background-geolocation#256]
This is more of a question than an issue, but I'm struggling to grasp something...

After reading [this post](https://stackoverflow.com/questions/25992990/ios-app-rejected-due-to-use-of-background-location-mode-for-geofence?noredirect=1&lq=1 ) it appears as though you don't need to add `Location updates` to `UIBackgroundModes` if you are only using geofences.

My app needs to run a function when the device enters a geofence - can I remove that background entitlement and use `BackgroundGeolocation.startGeofences` without it? When I do remove the entitlement, I get a crash on app boot:

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient)'
```

**Comment by christocracy** [comment]
The problem is, when a geofence triggers, the iOS geofence API provides only the geofence which triggered -- not the location where the geofence triggered.  So in the background, the plugin needs to manually perform a `#getCurrentPosition`.

I was thinking about this the other day.  `CLLocationManager` does have a public `location` property populated with the last known location.  I'll have to experiment with that to see if they happen to update that property when a geofence triggers without having to `requestLocation`.

**Comment by chrise86** [comment]
In my case I think this would actually be fine.

Would the geofence would be one related to only this app, or any geofence from the location manager? I would assume manager launches only the app that set the geofence?

The triggered geofence would have an identifier, so that could alway be used to check the relevance in the callback, right?

**Comment by christocracy** [comment]
>Would the geofence would be one related to only this app

Only your app

>The triggered geofence would have an identifier, so that could alway be used to check the relevance in the callback, right?

Relevance of what?

**Comment by christocracy** [comment]
The plugin will fire the `geofence` event only for those geofences for which you `#addGeofences`

**Comment by chrise86** [comment]
What I mean by relevance is; if I was running a function when a device enters/leaves a geofence, surely checking the fence identifier would be enough to work out where they are, rather than having to do a location lookup? At least it would be fine for my use-case.

**Comment by christocracy** [comment]
I'll add some code to check for `background location` capability and see what can be done to satisfy the current API.

It'll be implemented in the Premium Version first before it arrives here in the Free version.  I'll keep you posted.

**Comment by chrise86** [comment]
👍

**Comment by christocracy** [comment]
Ok, I had a look at this.  This is a bug.  There was some new code I added recently where I forget to check if the background "location" capability is enabled before executing a particular method.

It's perfectly ok for the plugin to request the current position when a geofence triggers, regardless of whether the background "location" capability is enabled.

This fix will appear here in the public version when I next roll out the latest stable release.

**Comment by christocracy** [comment]
I recorded this field-test today with the bug fix and Background "location" capability disabled.  All geofences triggered and triggering location was recorded:

green dot = entry
yellow dot = dwell
red dot = exit

![](https://www.dropbox.com/s/vzpckldq15rz725/Screenshot%202017-05-24%2014.03.57.png?dl=1)

**Comment by chrise86** [comment]
Awesome! Eagerly awaiting the next release 🙂

**Comment by christocracy** [comment]
It could be up to 2-3 months from now.

**Comment by chrise86** [comment]
Oh ok... Is it still likely to hit premium before it hits public? We are looking to purchase a premium license, but this bug is a blocker currently.

**Comment by christocracy** [comment]
It is available now in premium.

**Comment by chrise86** [comment]
Great, thanks!
