### ISSUE TITLE
Heartbeat working on sims, but not on ios devices?

### ISSUE THREAD

**Issue by fozzarelo** [transistorsoft/react-native-background-geolocation#257]
Heartbeat working on sims, but not on devices?

Plugin version: "react-native-background-geolocation": "^2.7.0"
Platform: iOS
OS version: pre-build
Device manufacturer / model: pre-build
React Native version (react-native -v): 0.42.0
Plugin config pre-build

Hi:
Can you think of a reason my heartbeat would work on sims but not on devices?

My configure looks like this:
BackgroundGeolocation.configure(
      {
        desiredAccuracy: 0,
        stationaryRadius: 10,
        distanceFilter: 15, // Activity Recognition
        stopTimeout: 30, // Application config
        heartbeatInterval: 10,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        preventSuspend: true,
        stopOnTerminate: false,   // Continue tracking when user closes the app.
        locationAuthorizationRequest: 'Always',
        locationAuthorizationAlert: {
          titleWhenNotEnabled: 'location-services not enabled, im telling..',
          titleWhenOff: 'location-services OFF, turn them back on please.',
          instructions: "You must enable 'Always' in location-services, boss said so.",
          cancelButton: 'Cancel',
          settingsButton: 'Settings',
          debug: true, // enable this hear sounds for background-geolocation life-cycle.
        },
      }
    )

My listener:
BackgroundGeolocation.on('heartbeat', loc => {
      console.log('Heartbeat...', loc.location )......

I checked my location services on the phone.. they are on.  
BackgroundGeolocation.getCurrentPosition, for example, works fine.. so I don't think it's the installation.

**Comment by christocracy** [comment]
When you test on device, is the device plugged into power?

If not, try plugging into power and see if it works then.

this has been reported by one of the Cordova customers.  I'm working on this right now.

**Comment by fozzarelo** [comment]
Yup..
I tried both: unplugged or TestFlight and also plugged a run through XCode. 
kk, thanks. awesome.. I'm going to leave it for now cause I'm running out of ideas. 
Please let me know if you find anything.

**Comment by christocracy** [comment]
Show me Xcode logs of your app booting and running in the background for a few minutes

**Comment by fozzarelo** [comment]
sure..where do you want them sent?

**Comment by fozzarelo** [comment]
they'll have some app semi-sensitive data, nothing too serious, but not for a public forum.. also it's long.

**Comment by christocracy** [comment]
Github allows you to attach a file to an issue.

See bottom of text area:  "Attach files by dragging & dropping"

**Comment by christocracy** [comment]
Email it.  See contact info on my website

Htttp://transistorsoft.com

**Comment by christocracy** [comment]
Dude:  you haven't `#start`ed the plugin.

**Comment by fozzarelo** [comment]
Feeling dumb... 
:-/
Weird how it was working on the simulator. 
Thanks Chris

**Comment by christocracy** [comment]
The plugin *persists* its `enabled` state between reboots.  When you `#configure` the plugin it will automatically `#start` itself if it finds it is supposed to be `enabled`.
