### ISSUE TITLE
Duplicate symbol _runOnMainQueueWithoutDeadlocking

### ISSUE THREAD

**Issue by pencilcheck** [transistorsoft/react-native-background-geolocation#258]
## Your Environment
* Plugin version: 2.8.1
* Platform: iOS
* OS version: 10.0
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 0.44
* Plugin config

## Expected Behavior

The xcode build should pass

## Actual Behavior

Since GPUImage is a dependency in some pods, getting a compile error (see logs below for more detail)

## Steps to Reproduce

1. In Podfile, include both React or GoogleMaps and also react-native-background-geolocation
2. Run `pod install`
3. Open xcode project and try to compile target
4. Sees error

## Context

Building a expo detached project to run on iOS

## Debug logs

```
duplicate symbol _runOnMainQueueWithoutDeadlocking in:
    /Users/pencilcheck/Library/Developer/Xcode/DerivedData/project-eimlyycqhpqzbkhcrwxzpnzqujbh/Build/Products/Debug-iphonesimulator/GPUImage/libGPUImage.a(GPUImageOutput.o)
    /Users/pencilcheck/Library/Developer/Xcode/DerivedData/project-eimlyycqhpqzbkhcrwxzpnzqujbh/Build/Products/Debug-iphonesimulator/libRNBackgroundGeolocation.a(RNBackgroundGeolocation.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by christocracy** [comment]
[runOnMainQueueWithoutDeadlocking](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/ios/RNBackgroundGeolocation/RNBackgroundGeolocation.m#L486) is a method in `RNBackgroundGeolocationModule.m`.

It looks like the people who wrote `GPUImageOutput` found the same [Stackoverflow post](https://stackoverflow.com/questions/5225130/grand-central-dispatch-gcd-vs-performselector-need-a-better-explanation/5226271#5226271) that I did.

I'll have to prefix mine.

**Comment by pencilcheck** [comment]
Thanks!

Do you have any recommendations on what I can do as a quick workaround for this problem?
The Pods are all generated and I prefer not to change files manually.

**Comment by christocracy** [comment]
Fork this repo.  In the file [RNBackgroundGeolocationModule.m](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/ios/RNBackgroundGeolocation/RNBackgroundGeolocation.m), find replace: `runOnMainQueueWithoutDeadlocking` -> `tsRunOnMainQueueWithoutDeadlocking`

**Comment by christocracy** [comment]
This is now prefixed to `tsRunOnMainQueueWithoutDeadlocking` in the premium version.

Fix will come when latest stable release is next published.
