### ISSUE TITLE
Foreground tracking only (config and/or permissions)

### ISSUE THREAD

**Issue by tywoodpav** [transistorsoft/react-native-background-geolocation#261]
I have a project that uses `react-native-background-geolocation`.

I will use the background services in a future build but currently my app does not implement them.

In order to comply with App Review, my app requires a reason to ask for background geolocation permissions, but it doesnt have one (yet).

Also it is possible to use my app without background location (it definitely improves the experience) but every time I open it when permissions are set to "When in use" it gives me an annoying alert.

How to I disable the package so it only runs in foreground and how do I get rid of that pesky alert?

I know it kind of defeats the purpose of BACKGROUND geolocation, but this saves me time by not having to rewrite it twice to use `react-native` location services and makes you $349.

**Comment by christocracy** [comment]
[locationAuthorizationRequest: 'WhenInUse'](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-string-locationauthorizationrequest-always)

**Comment by tywoodpav** [comment]
My middle name must be Jester because Im a fool.

Switching my info.plist key to NSLocationWhenInUseUsageDescription and reading the documentation fixed the problem.

Thanks to @christocracy for the space distorting reply time.
