### ISSUE TITLE
How to ask questions?

### ISSUE THREAD

**Issue by idibidiart** [transistorsoft/react-native-background-geolocation#262]
> *****************************************************************
> * WARNING:  If you ignore this template, so too will your issue
> *****************************************************************

That seems very stern. 

How does one ask questions? Do you have a Slack channel?

My first question is about the existence of an example where geofence lat/lon coordinates are read from an external system/db and created on the fly. I assume this module stores geofence coordinates and radius somewhere local on the device, and if that's the case then can we easily add/remove geofence coordinates?

If the above question makes no sense it is because there is no general intro to this awesome-sounding module. It jumps straight into the details, and I can't justify parsing the details before I have an idea of the general architecture (how this thing works)

Can you help? :)

**Comment by christocracy** [comment]
I'm forced to be stern like this in order to focus my support upon those who are best able to help themselves.  You are clearly one of those so you have nothing to worry about by asking general questions such as this.

Have a look at the docs and observe how the config params and methods are categorized.

Read the Philosophy of Operation in the Wiki.

I'm not really awake currently; I'll have a look at this in the morning

**Comment by christocracy** [comment]
See if the Geofencing Guide doesn't answer some of your questions:

https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/geofencing.md

**Comment by christocracy** [comment]
Do the above docs clarify anything?

**Comment by idibidiart** [comment]
Hi Chris

Will take a look on the plane this evening. Travelling right now. Thank you and I'm excited to get into it.

**Comment by idibidiart** [comment]
Ok, so let's say I added 7000 geofences at once and later I need to update that list with a delta of new unqiue geofences. Is the bulk add method smart enough such that if I give it a new list of geofences it can workout the diff and only add the dya instead of adding everything again? Or how do you recommend as a the best way to do differential bulk updates?

**Comment by idibidiart** [comment]
I guess beat way is if we can get an array of stored geofences we can easily remove duplicates before updating. we can find unique ones easily and append to what was stored previously. Any thoughts on doing it that way?

**Comment by christocracy** [comment]
There's little intelligence with adding geofences.  If you attempt to add a geofence whose `identifier` already exists in the database, the existing geofence will be destroyed and the new one added.

**Comment by idibidiart** [comment]
Thanks for explaining that part. 

Is there a way to get an array of all existing geofences including lat, lon and identifier? This way I can figure out the unique geofences (by identifier) and append those.

**Comment by christocracy** [comment]
The docs are conveniently categorized by type.  See [Geofencing Methods](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#small_blue_diamond-geofencing-methods)

**Comment by idibidiart** [comment]
What is the performance of getGeofences? Does it send the info from native to React Native via the bridge? An array of 10,000+ geofences would be realistic to fetch in under 2-3 seconds?

**Comment by christocracy** [comment]
I just did a test with the Cordova version (just because it's easier to manipulate with Web Console; it's the same binary library).

Android is **significantly** slower than iOS in every way.

**`addGeofenes` (10k)**
- Android:  ~42000ms
- iOS: ~4000ms

** `getGeofences`
- Android: ~12800ms
- iOS: ~500ms

- Android Pixel @ 7.1.1
- iPhone 6s @ 10.3.1
- `logLevel: 0` to prevent logging inflating response times.

**Comment by idibidiart** [comment]
Is the React Native Bridge the bottleneck here? I mean are you serializing an array of objects and sending that over the native<->JS bridge? Is it possible to use the filesystem? Would that be faster than going thru the bridge. I'm assuming the create and get calls are serializing the array and sending via the bridge.

My requirement is like this:

There may be hundreds of thousands of geofences on the server but the user only needs to get those in his radius at any given time. I can control the max radius so that we're dealing with so the app would have to persist and fetch a maximum of 100 or so geofences at a time. same thing with differential updates.

I'll implement all the smarts on my end, but it might still be a good idea if you could find a way to speed up bulk entry and lookup.

Thank you very much. Closing this now as we have a very specific enhancement request to track at this point.

**Comment by christocracy** [comment]
I suspect the bottleneck is the database on Android.  I'll be looking into this more.

**Comment by christocracy** [comment]
If I were you, I'd fetch geofences from the server for a radius of a city, say 10-20km.
