### ISSUE TITLE
Background location POST with AWS - body required for Auth signature

### ISSUE THREAD

**Issue by woodpav** [transistorsoft/react-native-background-geolocation#268]
I am using AWS to log the users location on the backend.

AWS requires the Authorization header to be signed with the body meaning that the `headers` option in the Background geolocation needs to have access to the HTTP body.

I am using https://github.com/leimd/react-native-aws-signature to generate the signature. (Note the `body` field). 

Here are the relevant AWS docs: http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html 

Under step 6: 

> Use a hash (digest) function like SHA256 to create a hashed value from the payload in the body of the HTTP or HTTPS request.

**Comment by christocracy** [comment]
I'll research this.

**Comment by woodpav** [comment]
@christocracy Any updates? No rush.

**Comment by christocracy** [comment]
>IMO the inclusion of HTTP in this library seems ancillary and I'd urge to split.

No updates.

The problem is Android in the terminated case where only the plugin's background-service is running.  The HTTP service must be married intimately with the plugin.
