### ISSUE TITLE
Application is killed by jetsam overnight?

### ISSUE THREAD

**Issue by JakeCasey** [transistorsoft/react-native-background-geolocation#269]
## Your Environment
* Plugin version: 
* Platform: iOS
* OS version: iOS 9.3.5
* Device manufacturer / model: iPhone 4s
* React Native version (`react-native -v`): 0.44.0
* Plugin config

## Expected Behavior

Application should awake (due to significant change API in my understanding) and continue monitoring speed even after long periods of inactivity. 

## Actual Behavior

What I *think* is happening is the application is killed by the iOS jetsam system sometime in the middle of the night. This only seems to happen on device, and I cannot recreate it in the simulator. It does happen every night, and I'm not entirely certain how to reproduce it faster for easier testing.

## Steps to Reproduce

1. Application works fine during the day.
2. After a long period of no usage it seems that the application is being killed by Jetsam
3. Upon moving again (significant change api?) background geolocation then dies and I receive no more updates, debug or otherwise built into the application.

## Context

Basically it's attempting to monitor the speed of the user constantly, and when it passes a certain threshold it should post to a server, however I want it to be unintrusive, so having the user have to constantly restart the app is.. not ideal.

I'm quite new to React-Native so I'm fairly certain that this issue is something to do with what I'm doing and probably not the plugin itself, but I have no where else to turn.

My understanding is that Jetsam kills processes that are using memory beyond what they should be using. It also doesn't seem to produce crash reports. In the simulator I can't make memory usage go above 65mb, and I've done pretty long testing using the Leaks panel in Instruments, with it picking up no memory leaks.

It was also my understanding that the significant change API wakes my app back up to provide it with location change information, but I suppose if the app has already been killed by Jetsam it has nothing to wake up.

I'm currently looking at receiving memory warnings in React-Native but there doesn't seem to be a ton of documentation with respect to RN. My app really holds no information in state besides the speed, lat/lon and the UID of the user, so I have no idea how I'm supposed to reduce that memory footprint further on request of the OS. My thoughts is releasing the views themselves, but that's also something that I have no idea how to go about doing.

I'm just completely at a loss of where to go with this.

Thanks for your time, I'd appreciate any direction even if it's 'read the documentation better' or something. 

## Debug logs

http://imgur.com/a/qiWms

The above is the output of the debug alerts I believe when the background geolocation has started up, but realizes the application itself has died.

`Jun 13 17:55:34 Jakes-iPhone MobileSMS[2930] <Warning>: Received memory warning.
Jun 13 17:55:34 Jakes-iPhone SpringBoard[48] <Warning>: UNNotificationRegistrarConnectionListener connection invalidated
Jun 13 17:55:34 Jakes-iPhone SpringBoard[48] <Warning>: UNNotificationSchedulerConnectionListener connection invalidated
Jun 13 17:55:34 Jakes-iPhone mediaserverd[43] <Notice>: '' com.apple.mobilesms.notification(pid = 2960) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
Jun 13 17:55:34 Jakes-iPhone SpringBoard[48] <Warning>: Application 'UIKitApplication:com.reddit.Reddit[0x9937]' was killed by jetsam.
Jun 13 17:55:34 Jakes-iPhone SpringBoard[48] <Warning>: Application 'UIKitApplication:com.apple.mobilesms.notification[0xf75f]' was killed by jetsam.
Jun 13 17:55:34 Jakes-iPhone SpringBoard[48] <Warning>: Application 'UIKitApplication:com.apple.MobileSMS[0xad97]' was killed by jetsam.
Jun 13 17:55:34 Jakes-iPhone UserEventAgent[23] <Warning>: 2220935440771: id=com.apple.MobileSMS pid=2930, state=0
Jun 13 17:55:34 Jakes-iPhone SpringBoard[48] <Warning>: Application 'UIKitApplication:org.reactjs.native.example.safetyios[0x416b]' was killed by jetsam.`

The last line seems to be where my application is killed, but that's the only time I've been able to catch it actually being killed in the console.

**Comment by JakeCasey** [comment]
BackgroundGeolocation.configure({
      desiredAccuracy: 10,
      stationaryRadius: 50,
      distanceFilter: 5,
      locationTimeout: 30,
      activityType: 'AutomotiveNavigation',
      debug: true,
      interval: 10000,

    }, function(state){
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          //console.log("- Start success");
        });
      }

    });

**Comment by christocracy** [comment]
There's no such config option as `interval`.  Perhaps you mean `locationUpdateInterval` (Android-only; ignored when `distanceFilter > 0`)

**Comment by JakeCasey** [comment]
Ok. I've removed that. Could something like that cause what I'm seeing? Obviously it can't help. But I'm here if you need any other information!

**Comment by christocracy** [comment]
The OS can and will terminate an app in the background when memory is required.

If you want your app to keep tracking in spite of termination, you need to configure [`stopOnTerminate: false`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-boolean-stoponterminate-true).

**Comment by christocracy** [comment]
No, `interval` has nothing to do with it.  `stopOnTerminate` **certainly** is your problem.

**Comment by JakeCasey** [comment]
> Before an iOS app terminates, the plugin will ensure that a stationary geofence is created around the last known position. When the user moves beyond the stationary geofence (typically ~200 meters), iOS will completely reboot your application in the background, including your Javascript application and the plugin will resume tracking. iOS maintains geofence monitoring at the OS level, in spite of application terminate / device reboot.

So it will reboot everything and any RN stuff will run as normal, including the fetch post to server on breaking the speed threshold? I'll test this today/tonight.

 If this one config fixes it I'll probably throw my computer out the window.

**Comment by christocracy** [comment]
>So it will reboot everything and any RN stuff will run as normal, including the fetch post to server on breaking the speed threshold? I'll test this today/tonight.

Yes.  But it's not "breaking the speed threshold", it's exiting the geofence monitored around the last-known position.  iOS persists geofence listeners at the OS level.  When a geofence transition occurs, iOS kindly reboots the app to service that geofence event.

In addition, *when the OS terminates your app*, the `background-fetch` plugin too will cause your app to reboot in the background.

**Comment by christocracy** [comment]
You can see in your debug notifications the message "Stopped on terminate".  Your app *was* rebooted, it was the plugin that refused to start since you told it to `stopOnTerminate: true` (The default value)

**Comment by JakeCasey** [comment]
Unfortunately the result was the same. I haven't had a whole lot of time this morning, but over the next few days I'll attempt to `getLog` and have more information for us soon.

**Comment by christocracy** [comment]
There's no doubt the issue is stopOnTerminate

**Comment by christocracy** [comment]
Update?

**Comment by JakeCasey** [comment]
I have no idea why, but the first night it still crashed in the morning, but has been working fine since then. Thank you so much for all your help!!
