### ISSUE TITLE
Location callback on iOS simulator doesn't work

### ISSUE THREAD

**Issue by tywoodpav** [transistorsoft/react-native-background-geolocation#271]
I am using `BackgroundGeolocation.on('location', cb)` listen to the users location.

When I set the Simulator to a custom GPX file or to city bike ride (or other default ones), `cb` does not run until I call `BackgroundGeolocation.getCurrentPosition()`.

This is the log output when I call `BackgroundGeolocation.getCurrentPosition()`.

    - updateCurrentPosition: {
    }
    🎾-[LocationManager startUpdatingLocation] ON
    ℹ️+[LocationAuthorization run:] status: 4
    🔴-[LocationManager stopUpdatingLocation] OFF

    <+37.33023599,-122.02367007> +/- 10.00m (speed 7.35 mps / course 89.39) @ 6/22/17, 12:02:26 PM Pacific Daylight Time

    ╔═══════════════════════════════════════════════════════════
    ║ -[LocationManager locationManager:didUpdateLocations:] Sample 3 of 3
    ╚═══════════════════════════════════════════════════════════
    - Median location accuracy: 10.0
    ✅ INSERT: 80EF76C4-8F0C-4F97-BC8B-D5D4C7A158ED

Simply letting it run gives me the output 

    2017-06-22 12:10:21.525327-0700 MyProj[89829:14013221] []     
    nw_connection_get_connected_socket_block_invoke 69 Connection has no connected handler
    2017-06-22 12:10:23.576631-0700 MyProj[89829:14013314] [] 
    nw_connection_get_connected_socket_block_invoke 70 Connection has no connected handler

Here's the config:

    {

        // Geolocation Config
        desiredAccuracy: 0,
        stationaryRadius: 25,
        distanceFilter: 10,

        // Activity Recognition
        stopTimeout: 1,

        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: false,        // <-- Auto start tracking when device is powered-up.

        locationAuthorizationRequest: 'WhenInUse',

    }

**Comment by christocracy** [comment]
Show me logs of app booting.

Are you not executing #start method?

**Comment by tywoodpav** [comment]
I am running

    BackgroundGeolocation.configure({}, , state => {

        console.log('GPS configured', state.enabled);

        if (!state.enabled) {
          BackgroundGeolocation.start(() => {
            console.log('GPS started');
          });
        }

     });

Startup logs:

    🔵-[Settings init] Settings loaded
    🔵-[Settings setOdometer:] 68461
    ℹ️__21-[LocationDAO unlock]_block_invoke UNLOCKED ALL RECORDS
    ℹ️-[GeofenceDAO init] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, extras TEXT)
    ℹ️-[GeofenceDAO init] CREATE index IF NOT EXISTS identifier ON geofences (identifier);CREATE index IF NOT EXISTS latitude ON geofences (latitude);CREATE index IF NOT EXISTS longitude ON geofences (longitude);CREATE index IF NOT EXISTS sin_latitude ON geofences (sin_latitude);CREATE index IF NOT EXISTS cos_latitude ON geofences (cos_latitude);CREATE index IF NOT EXISTS sin_longitude ON geofences (sin_longitude);CREATE index IF NOT EXISTS cos_longitude ON geofences (cos_longitude);
    ℹ️-[TSGeofenceManager addGeofencesChangeListener:] 
    2017-06-22 12:25:57.871174-0700 MyProj[91740:14036249] [MC] System group container for systemgroup.com.apple.configurationprofiles path is ...
    2017-06-22 12:25:57.875891-0700 MyProj[91740:14036249] [MC] Reading from private effective user settings.
    🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 4
    🔵-[TSLocationManager locationManager:didChangeAuthorizationStatus:] status 4
    2017-06-22 12:25:57.886 [warn][tid:main][RCTEventEmitter.m:54] Sending `providerchange` with no listeners registered.
    🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 4
    🔵-[BackgroundTaskManager locationManager:didChangeAuthorizationStatus:] 4
    🔵-[LocationManager locationManager:didChangeAuthorizationStatus:] 4
    ℹ️+[LocationAuthorization run:] status: 4
    2017-06-22 12:25:58.012 [info][tid:main][RCTBatchedBridge.m:77] Initializing <RCTBatchedBridge: 0x6080001bf100> (parent: <RCTBridge: 0x6080000d3080>, executor: RCTWebSocketExecutor)
    2017-06-22 12:25:58.016 [warn][tid:com.facebook.react.RCTBridgeQueue][RCTModuleData.mm:285] Required dispatch_sync to load constants for RCTAppState. This may lead to deadlocks
    ℹ️-[TSGeofenceManager addGeofencesChangeListener:] 
    2017-06-22 12:26:00.333 [info][tid:main][RCTRootView.m:295] Running application MyProj ({
        initialProps =     {
        };
        rootTag = 1;
    })
    2017-06-22 12:26:00.366913-0700 MyProj[91740:14036573] [] nw_connection_get_connected_socket_block_invoke 8 Connection has no connected handler
    2017-06-22 12:26:02.566658-0700 MyProj[91740:14036589] [] nw_connection_get_connected_socket_block_invoke 12 Connection has no connected handler
    - updateCurrentPosition: {
    }
    🎾-[LocationManager startUpdatingLocation] ON
    🔴-[LocationManager stopUpdatingLocation] OFF

    <+37.33020222,-122.02525428> +/- 10.00m (speed 7.68 mps / course 91.08) @ 6/22/17, 12:22:22 PM Pacific Daylight Time

    ╔═══════════════════════════════════════════════════════════
    ║ -[LocationManager locationManager:didUpdateLocations:] Sample 3 of 3
    ╚═══════════════════════════════════════════════════════════
    - Median location accuracy: 10.0
    ✅ INSERT: A23D5B78-D2F0-4100-A717-A657381FBE55

    ╔═══════════════════════════════════════════════════════════
    ║ -[Settings load:] 
    {
        activityRecognitionInterval = 10000;
        activityType = Other;
        autoSync = 1;
        autoSyncThreshold = 0;
        batchSync = 0;
        debug = 1;
        desiredAccuracy = 0;
        desiredOdometerAccuracy = 100;
        disableElasticity = 0;
        disableMotionActivityUpdates = 0;
        disableStopDetection = 0;
        distanceFilter = 10;
        enabled = 1;
        extras =     {
        };
        geofenceInitialTriggerEntry = 1;
        geofenceProximityRadius = 10000;
        geofenceTemplate = "";
        headers =     {
        };
        heartbeatInterval = 60;
        httpRootProperty = location;
        isHeartbeatEnabled = 0;
        isMoving = 0;
        locationAuthorizationAlert =     {
            cancelButton = Cancel;
            instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
            settingsButton = Settings;
            titleWhenNotEnabled = "Background location is not enabled";
            titleWhenOff = "Location services are off";
        };
        locationAuthorizationRequest = WhenInUse;
        locationTemplate = "";
        locationTimeout = 60;
        logLevel = 5;
        logMaxDays = 7;
        maxBatchSize = "-1";
        maxDaysToPersist = 1;
        maxRecordsToPersist = "-1";
        method = POST;
        minimumActivityRecognitionConfidence = 70;
        odometer = "68461.10528957511";
        params =     {
        };
        pausesLocationUpdatesAutomatically = 1;
        preventSuspend = 0;
        schedule =     (
        );
        schedulerEnabled = 0;
        startOnBoot = 0;
        stationaryRadius = 25;
        stopAfterElapsedMinutes = "-1";
        stopDetectionDelay = 0;
        stopOnTerminate = 0;
        stopTimeout = 5;
        trackingMode = 1;
        url = "";
        useSignificantChangesOnly = 0;
    }
    ╚═══════════════════════════════════════════════════════════
    ℹ️-[LocationDAO purge:] maxDaysToPersist: 1

    ╔═══════════════════════════════════════════════════════════
    ║ -[TSLocationManager start] 
    ╚═══════════════════════════════════════════════════════════
    🔵-[TSLocationManager setPace:] 0
    🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
    🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
    2017-06-22 12:26:02.828 MyProj[91740:14036249] - TSBackgroundFetch addListener: TSLocationManager
    2017-06-22 12:26:02.831 MyProj[91740:14036249] - TSBackgroundFetch started
    ℹ️+[LocationAuthorization run:] status: 4

    <+37.33020222,-122.02525428> +/- 10.00m (speed 7.68 mps / course 91.08) @ 6/22/17, 12:22:22 PM Pacific Daylight Time

    ╔═══════════════════════════════════════════════════════════
    ║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | distanceFilter: -1.0
    ╚═══════════════════════════════════════════════════════════
    - Acquiring stationary location (1 / 5)
    ⚠️-[TSLocationManager locationManager:didFailWithError:] Error Domain=kCLErrorDomain Code=0 "(null)"
    ⚠️-[TSLocationManager onStationaryLocationTimeout:] 
    ✅ Using last-known location <+37.33020222,-122.02525428> +/- 10.00m (speed 7.68 mps / course 91.08) @ 6/22/17, 12:22:22 PM Pacific Daylight Time
    - Median location accuracy: 10.0

    ╔═══════════════════════════════════════════════════════════
    ║ -[TSGeofenceManager evaluate:] Found 2 / 2 within 10000 m
    ╚═══════════════════════════════════════════════════════════
    🎾__30-[TSGeofenceManager evaluate:]_block_invoke MONITORING fence1
    🎾__30-[TSGeofenceManager evaluate:]_block_invoke MONITORING fence2
    🔵-[TSLocationManager startMonitoringStationaryRegion:] Radius: 25
    🔴-[TSLocationManager stopUpdatingLocation] 
    ✅ INSERT: 1AD73225-2184-4665-A3B8-569D22D3825E
    ℹ️+[LocationAuthorization run:] status: 4
    2017-06-22 12:26:04.707616-0700 MyProj[91740:14036611] [] nw_connection_get_connected_socket_block_invoke 20 Connection has no connected handler
    2017-06-22 12:26:06.884399-0700 MyProj[91740:14036601] [] nw_connection_get_connected_socket_block_invoke 21 Connection has no connected handler
    2017-06-22 12:26:08.951516-0700 MyProj[91740:14036623] [] nw_connection_get_connected_socket_block_invoke 22 Connection has no connected handler
    2017-06-22 12:26:11.068302-0700 MyProj[91740:14036619] [] nw_connection_get_connected_socket_block_invoke 23 Connection has no connected handler

**Comment by christocracy** [comment]
You've set `locationAuthorizationRequest: 'WhenInUse'`

Set it to `Always` and it will work.

**Comment by tywoodpav** [comment]
Thanks. That worked. 

Why is that the case? Should it not work `WhenInUse`?

**Comment by christocracy** [comment]
iOS location services features are seriously degraded with WhenInUse.  Geofences don't fire.  The plugin relies on geofence exit to determine when device is moving

**Comment by tywoodpav** [comment]
Hmm, interesting. Its weird how finicky some of this stuff can be given how intrinsic location services are to mobile.

**Comment by christocracy** [comment]
The default is Always.  WhenInUse is not recommended to be used with this plugin.  It's for special 1% use-cases
