### ISSUE TITLE
[Question] Proactive Tracking

### ISSUE THREAD

**Issue by rexlow** [transistorsoft/react-native-background-geolocation#274]
## Your Environment
* Plugin version: 2.8.1
* Platform: Android
* OS version: 5.1
* React Native version (`react-native -v`): 0.44.0
* Plugin config

```
desiredAccuracy: 0, //highest power
  stationaryRadius: 0,
  distanceFilter: 0, // locationUpdateInterval is ignored!
  locationTimeout: 30,
  notificationTitle: "App",
  notificationText: "Location services enabled",
  locationProvider:
    BackgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER
```

## Expected Behavior

I am trying to build an app that can track where I have been, proactively. Meaning for every step I take, I want the GPS to return the coords. 

## Actual Behavior

The library only returns coords every few seconds (after some distances walked), sometimes even longer. What is the correct configuration to achieve what I want?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
I see you're using config related to Mauron85's fork of this project.  Are you sure you're commmenting on the correct repo?



Location sample rate is controlled by distanceFilter, which is automatically elastically reconfigured based upon speed, disabled with

**Comment by christocracy** [comment]
You cannot have a location for "every step".

Location sampling is controlled with distanceFilter.  Setting distanceFilter: 0 will record locations at the fastest possible rate.

**Comment by christocracy** [comment]
Closing for lack of feedback.
