### ISSUE TITLE
Location in logs is not what ends up being POST'd by http service

### ISSUE THREAD

**Issue by scottwilson312** [transistorsoft/react-native-background-geolocation#275]
## Your Environment
* Plugin version: 2.8.1
* Platform:  Android
* OS version: 7.0
* Device manufacturer / model: Moto G4
* React Native version (`react-native -v`): 0.42
* Plugin config

{
             activityRecognitionInterval:60000,
              minimumActivityRecognitionConfidence:1,
              desiredAccuracy: 0,
              distanceFilter: 0,
              locationUpdateInterval:60000,
              fastestLocationUpdateInterval:60000,
              // Activity Recognition
              stopTimeout: 0,
              // Application config
              debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
              logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
              stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
              startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
              // HTTP / SQLite config
              url: GlobalSettings.api_base + '/api/location/record',
              batchSync: false,    
              autoSync: true,    
              headers: {    
                "X-FOO": "bar"
              },  
              params: {               // <-- Optional HTTP params
                "user_id": this.user.user_id,
                "fromhttpshit":1
              }   
}

## Expected Behavior

I expect the most recent coordinates - the ones I see listed in the log to be sent to my HTTP server 
## Actual Behavior

It seems that inaccurate coordiantes are being sent, and I believe they are old. Plotting them on the map, they are coordinates that I was at about 10 minutes prior, although that could just be a coincidence.

## Steps to Reproduce

1. Turn on app
2. Drive around
3. Look at logs in logcat and compare to my http logs
4.

## Context

I am trying to accurately record my coordinated as I drive or walk around. Stuff things to work perfectly sometimes, and then other times it seems that the coordinates don't get updated properly.

## Debug logs
Below are logcat logs from when around I arrived at my destination after driving. The line with Location[fused 42.131923,-87.859512], are the correct coordinate that represent my physical location at 16:50.
 

6-23 16:50:54.871   TSLocationManager: ╔═════════════════════════════════════════════
06-23 16:50:54.871   TSLocationManager: ║ LocationService: location
06-23 16:50:54.871   TSLocationManager: ╠═════════════════════════════════════════════
06-23 16:50:54.871   TSLocationManager: ╟─ 📍  Location[fused 42.131923,-87.859512 acc=19 et=+3d14h22m25s405ms]
06-23 16:50:54.885   TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
06-23 16:50:54.885   TSLocationManager: ╔═════════════════════════════════════════════
06-23 16:50:54.885   TSLocationManager: ║ Process LocationResult
06-23 16:50:54.885   TSLocationManager: ╠═════════════════════════════════════════════
06-23 16:50:54.892   TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] 20.727 
06-23 16:50:54.899   TSLocationManager: [c.t.l.l.TSLocationManager incrementOdometer] 24324.605
06-23 16:50:54.937   TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO persist] 
06-23 16:50:54.937  I TSLocationManager:   ✅  INSERT: d0b95f58-a7ea-43d8-81bf-0d746ff55819
06-23 16:50:54.953   TSLocationManager: [c.t.l.http.HttpService flush] 
06-23 16:50:54.953   TSLocationManager: ╔═════════════════════════════════════════════
06-23 16:50:54.953   TSLocationManager: ║ HTTP Service
06-23 16:50:54.953   TSLocationManager: ╠═════════════════════════════════════════════
06-23 16:50:54.967   TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO first] 
06-23 16:50:54.967   TSLocationManager:   ✅  Locked 1 records
06-23 16:50:54.972 1  TSLocationManager: [c.t.l.http.HttpService createRequest] 
06-23 16:50:54.972 1 TSLocationManager:   🔵  POST: 5aed0430-658b-4787-a238-b3d9943adca5
06-23 16:50:55.142  TSLocationManager: [c.t.l.http.HttpRequest parseNetworkResponse] 
06-23 16:50:55.142  TSLocationManager:   🔵  Response: 200
06-23 16:50:55.156   TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO destroy] 
06-23 16:50:55.156   TSLocationManager:   ✅  DESTROY: 5aed0430-658b-4787-a238-b3d9943adca5
06-23 16:50:55.176   TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO first] 
06-23 16:50:55.176   TSLocationManager:   ✅  Locked 1 records
06-23 16:50:55.183  TSLocationManager: [c.t.l.http.HttpService createRequest] 
06-23 16:50:55.183  TSLocationManager:   🔵  POST: 6b48a435-2f30-4499-97dc-54481c66203e
06-23 16:50:55.309   TSLocationManager: [c.t.l.http.HttpService onRequestError] 
06-23 16:50:55.309   TSLocationManager:   ⚠️  HTTP Response: 500; {"message": "Internal Server Error"}
06-23 16:50:55.321   TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO unlock] 
06-23 16:50:55.321   TSLocationManager:   ✅  UNLOCKED: 6b48a435-2f30-4499-97dc-54481c66203e
06-23 16:52:02.332  TSLocationManager: [c.t.l.LocationService onLocation] 

From the same time (ignore the timezone difference), here are the logs from my HTTP server. It is just dumping out the POST request. You can see that the latitude and longitude are fairly off from the location logged above (42.131923,-87.859512). When I put the coordinates that the HTTP server got into google maps, they are coordinates that I was at ~10 minutes prior. The (42.131923,-87.859512) coordinates from the TSLocationManager logs never end up making it to my HTTP server (nor do coordinates that are close to those one).

I assume that perhaps I have a misunderstanding of how the HTTP server works. 

NFO: 2017-06-23 21:49:45,517 : record_location.py :  {u'user_id': 42, u'location': {u'is_moving': True, u'uuid': u'08a8f3af-5833-4f2f-972d-c013f5a10684', u'battery': {u'is_charging': False, u'level': 0.7}, u'timestamp': u'2017-06-23T21:19:35.000Z', u'odometer': 21561.7, u'extras': {}, u'coords': {u'altitude': 168, u'longitude': -87.8777172, u'latitude': 42.1266986, u'speed': 0, u'heading': -1, u'accuracy': 12.1}, u'activity': {u'confidence': 69, u'type': u'on_foot'}}, u'fromhttpshit': 1}

INFO: 2017-06-23 21:49:45,744 : record_location.py :  {u'user_id': 42, u'location': {u'is_moving': True, u'uuid': u'5aed0430-658b-4787-a238-b3d9943adca5', u'battery': {u'is_charging': False, u'level': 0.7}, u'timestamp': u'2017-06-23T21:20:39.540Z', u'odometer': 21611.5, u'extras': {}, u'coords': {u'altitude': -1, u'longitude': -87.8781905, u'latitude': 42.1264215, u'speed': -1, u'heading': -1, u'accuracy': 19.6}, u'activity': {u'confidence': 61, u'type': u'on_foot'}}, u'fromhttpshit': 1}

INFO: 2017-06-23 21:50:55,213 : record_location.py :  {u'user_id': 42, u'location': {u'is_moving': True, u'uuid': u'5aed0430-658b-4787-a238-b3d9943adca5', u'battery': {u'is_charging': False, u'level': 0.7}, u'timestamp': u'2017-06-23T21:20:39.540Z', u'odometer': 21611.5, u'extras': {}, u'coords': {u'altitude': -1, u'longitude': -87.8781905, u'latitude': 42.1264215, u'speed': -1, u'heading': -1, u'accuracy': 19.6}, u'activity': {u'confidence': 61, u'type': u'on_foot'}}, u'fromhttpshit': 1}

INFO: 2017-06-23 21:50:55,382 : record_location.py :  {u'user_id': 42, u'location': {u'is_moving': True, u'uuid': u'6b48a435-2f30-4499-97dc-54481c66203e', u'battery': {u'is_charging': False, u'level': 0.7}, u'timestamp': u'2017-06-23T21:21:48.616Z', u'odometer': 21701.6, u'extras': {}, u'coords': {u'altitude': -1, u'longitude': -87.8779221, u'latitude': 42.1272077, u'speed': -1, u'heading': -1, u'accuracy': 21}, u'activity': {u'confidence': 65, u'type': u'on_foot'}}, u'fromhttpshit': 1}

Thanks for the help. Let me know if there is anything I can clarify or any other info I can provide.

**Comment by christocracy** [comment]
Are you observing this?
```
06-23 16:50:55.309 TSLocationManager: ⚠️ HTTP Response: 500; {"message": "Internal Server Error"}
```

When the plugin sees an HTTP error response, it keeps trying to sync that until your server returns 200.

**Comment by scottwilson312** [comment]
I am indeed. I will resolve the 500 error and see if that resolves my issue. Thanks!

**Comment by christocracy** [comment]
Closed for lack of feedback.
