### ISSUE TITLE
Possible to directly access the SQLite database

### ISSUE THREAD

**Issue by ramsestom** [transistorsoft/react-native-background-geolocation#279]
Can the SQLite database be directly requested with a module like this: https://github.com/andpor/react-native-sqlite-storage in case we want to perform specific queries (like querying if a specific position exist in the history)?
If yes, what is the name of the SQLite database and is there a scheme of it's tables architecture somewhere?

**Comment by christocracy** [comment]
The plugin stores its data in the db as blobs of JSON.  Locations cannot be queried.

**Comment by ramsestom** [comment]
OK Thanks. Will switch to another module that allows it then ;)

**Comment by christocracy** [comment]
Mauron85's version is a fork of this from over 3 years ago.  This one has been completely rebuilt over the last 2+ years and has a superior set-of-features. 

This one evolves daily backed by full time support.

**Comment by ramsestom** [comment]
Mauron85's version might be a fork of your original version from 3 years ago, it is still actively maintained.
As for the superior set of features, I agree but the one in Mauron85's version seems to be enaugh for my use case for now. And as Mauron85's version is completely open source, implement new features if necessary is easy anyway (and I prefer that than having to ask for it and hope to see it implemented soon in a closed module like yours).
As for the possibility to directly query the SQLite database, after a first quick look at the java source code, it looks like Mauron85's version stores locations history in usual SQLite tables so it should be pretty straightforward (so, in a sense, Mauron85's version is superior to your version for people necessiting this kind of feature ;) )
