### ISSUE TITLE
Error: RNBackgroundGeolocation.getLocations is not a function

### ISSUE THREAD

**Issue by jabm111** [transistorsoft/react-native-background-geolocation#28]
Using v0.1.0, when I  try to call BackgroundGeolocation.getLocations:

![screen shot 2015-11-10 at 6 46 59 pm](https://cloud.githubusercontent.com/assets/10445424/11079573/80f68ba8-87db-11e5-8f0b-46c7cd0f99c7.png)

**Comment by christocracy** [comment]
Please try out this branch before I merge.
https://github.com/transistorsoft/react-native-background-geolocation/pull/29

Also, be aware of new "background task" mechanism:  if you're going to perform a long-running, asynchronous XHR within the #sync or #getLocations callback, you should wrap your requests in a "background-task".  iOS provides exactly 180s of background running-time with these background-tasks.

This is important for when the app is in stationary-mode.  When the user suspends the app while in stationary-mode, iOS will **immediately** stop your app from running.  If you were in the middle of performing an XHR request to your server, the HTTP request would effectively be terminated.

eg:

```
bgGeo.beginBackgroundTask(function(taskId) {
  // this taskId will prevent your app from being suspended even if user puts app in background.
  // for exactly 180s.
  bgGeo.getLocations(function(locations) {
    setTimeout(function() {  // <-- simulate a 1 minute long-running task.
       bgGeo.finish(taskId);  // <-- signal to iOS that your task is complete.
    }, 60000);
  });
});

If you fail to `#finish` a background-task within 180s, iOS will force-kill your app and log a crash like so `has active assertions beyond permitted time: `:

```
Incident Identifier: DE6FEDA3-B397-4DF3-BF04-5F1CA8611D99
CrashReporter Key:   7d5ec51e0211e60c628762cc762b6b328ec71b5d
Hardware Model:      iPhone8,1
Process:             Messenger [5445]
Path:                /var/mobile/Containers/Bundle/Application/5FA7FD56-4288-4598-A6F9-0DD8D49BA0C6/Messenger.app/Messenger
Identifier:          com.facebook.Messenger
Version:             15313520 (37.0)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2015-11-05 14:41:06.06 -0500
Launch Time:         2015-11-05 10:15:03.03 -0500
OS Version:          iOS 9.1 (13B143)
Report Version:      105

Exception Type:  00000020
Exception Codes: 0x000000008badf00d
Exception Note:  SIMULATED (this is NOT a crash)
Highlighted by Thread:  10

Application Specific Information:
<BKNewProcess: 0x12ee48700; com.facebook.Messenger; pid: 5445; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x12ed51cb0> id: 4373-6D0B4096-6281-4244-8545-E951BF41F45F name: com.apple.UIKit.KeyboardManagement.message process: <BKNewProcess: 0x12ee48700; com.facebook.Messenger; pid: 5445; hostpid: -1> permittedBackgroundDuration: 40.000000 reason: finishTaskAfterBackgroundContentFetching owner pid:4373 preventSuspend  preventThrottleDownCPU  preventThrottleDownUI  preventSuspendOnSleep ,
    <BKProcessAssertion: 0x12ed34570> id: 4373-4F0F1B10-9741-4394-81E2-AA162197A05C name: Background Content Fetching (395) process: <BKNewProcess: 0x12ee48700; com.facebook.Messenger; pid: 5445; hostpid: -1> permittedBackgroundDuration: 30.000000 reason: backgroundContentFetching owner pid:4373 preventSuspend  preventThrottleDownUI  preventIdleSleep  preventSuspendOnSleep 
)}
```

**Comment by jabm111** [comment]
Awesome, it's working. Thanks for the quick fix and the tip!
