### ISSUE TITLE
Redeveloping App using React Native

### ISSUE THREAD

**Issue by Mahaswami** [transistorsoft/react-native-background-geolocation#281]
We are updating our app to use React Native. Currently our licensed version app is using Cordova/Phonegap. Can you please share the steps we need to follow to access your licensed React Native app version? FYI, the App ID will be same for the new app

## Your Environment 
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Just purchase a license for the React Native version.

**Comment by christocracy** [comment]
Send me an email and I'll generate a coupon to [purchase react-native version](https://www.transistorsoft.com/shop/products/react-native-background-geolocation) with a discount.
