### ISSUE TITLE
Adding functionality to iOS background fetch

### ISSUE THREAD

**Issue by ground5hark** [transistorsoft/react-native-background-geolocation#285]
## Your Environment
* Plugin version: 2.8.3
* Platform: Android
* OS version: 6.0
* Device manufacturer / model: Pixel 5 Emulator
* React Native version (`react-native -v`): 0.45
* Plugin config: https://pastebin.com/rAsP0jDy

## Expected Behavior

The background fetch handler should be triggered every ~15 minutes or so.

## Actual Behavior

Only triggers once when the app is first ran via the Run schema in Xcode.

## Steps to Reproduce
Use a simulator, add a breakpoint to the `performFetchWithCompletionHandler` method, observe it does not get triggered.

## Context

Attempting to add more functionality on the `performFetchWithCompletionHandler` delegate hook. The idea is that we'd load more geofences on this hook, either via native ObjC/Swift or after the app starts up in the background using JS using `BackgroundFetch.configure`

**Comment by christocracy** [comment]
Background-fetch issues should be posted at its own repo: [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch)

**Comment by christocracy** [comment]
Background-fetch is notoriously unpredictable.  The frequency of fetch events is not a steady 15 min.  The frequency is based upon a secret Apple algorithm which likely includes how long and when the user uses the app.

It can take several days before you see regular 15 min intervals and these intervals can change throughout the day.

**Comment by christocracy** [comment]
And anyway, why would attempt to use the native api to add geofences?

Just implement your own Javascript [background-fetch](https://github.com/transistorsoft/react-native-background-fetch#example) callback as documented at the background-fetch repo.
