### ISSUE TITLE
getCurrentPosition always triggers the locationAuthorizationAlert (when useSignificantChangesOnly is true)

### ISSUE THREAD

**Issue by blaues0cke** [transistorsoft/react-native-background-geolocation#288]
* Plugin version: ^2.8.1
* Platform: iOS
* OS version: 10.3.2 (14F89)
* Device manufacturer / model: iPhone7 (MN8X2ZD/A)
* React Native version (`react-native -v`): 0.42.0
* Plugin config: 
```
BackgroundGeolocation.configure({
            // Auto http post
            autoSync:         true,
            url:              apiLocationTrackingPostUrl,
            httpRootProperty: 'geoLocation',
            method:           'POST',
            locationTemplate: '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, "radiusInM": <%= accuracy %> }',
            headers:          {
                                  'Authorization': 'Bearer ' + api._core.getJWT()
                              },

            // Geolocation Config
            desiredAccuracy:           0,
            distanceFilter:            25,
            stationaryRadius:          25,
            useSignificantChangesOnly: true,
            locationUpdateInterval:    1000 * 60 * 5,
            locationAuthorizationRequest: 'Always',
            locationAuthorizationAlert: {
                titleWhenNotEnabled: I18n.t('locationPromptTitleNotEnabled'),
                titleWhenOff:        I18n.t('locationPromptTitleOff'),
                instructions:        I18n.t('locationPromptText'),
                cancelButton:        I18n.t('locationPromptCancel'),
                settingsButton:      I18n.t('locationPromptSettings')
            },

            // Other
            stopTimeout:     1,
            stopOnTerminate: false,
            startOnBoot:     true,

            // Debug
            debug: __DEV__,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        }
```

## Expected Behavior
The `locationAuthorizationAlert` appears once until the app is closed/terminated.

## Actual Behavior
The `locationAuthorizationAlert` also appears after every call of `getCurrentPosition` (regardless whether the user selected "Never", "When in use" or "Always" in the iOS settings).

## Steps to Reproduce
1. Initialize the plugin with `locationAuthorizationRequest: 'Always'`
2. Optional: Call `BackgroundGeolocation.setConfig()` with `{ locationAuthorizationRequest: 'WhenInUse' }`
3. Call `BackgroundGeolocation.getCurrentPosition()` within `window.setInterval()`
4. The `locationAuthorizationAlert` now appears everytime the interval is fired

## Context
I set `useSignificantChangesOnly` to `true` on iOS. But I have to get the current position in some cases using `getCurrentPosition()`. I think this has to do with `useSignificantChangesOnly: true`.

**Comment by christocracy** [comment]
`locationAuthorizationRequest` doesn't *change* the location-settings.  This config is used to tell the plugin *what value to expect from the user*.

When you say `locationAuthorizationRequest: 'WhenInUse'`, you're saying to the plugin:

>I expect the user to have selected "When In Use".  If the user sets it to anything other than "When In Use", complain about it.

And btw, `useSignificantChangesOnly: true` doesn't work with `WhenInUse`.  It only works when user has selected `Always` in `Privacy -> Location`

**Comment by blaues0cke** [comment]
Thanks for your answer. I got this. So the primary problem is: The dialog is displayed over and over again, everytime I call this:

```
BackgroundGeolocation.getCurrentPosition(function(location, taskId) {
    self.locationChanged(location);

  BackgroundGeolocation.finish(taskId);
}, function(errorCode) {

}, {
  timeout: 30,
  maximumAge: 5000,
  desiredAccuracy: 25,
  samples: 1,
});
```

Is there a way to disable the dialog at all (since I only want it to get displayed when the app is started, not when I call `getCurrentPosition` in my code)

**Comment by christocracy** [comment]
Yes, configure locationAuthorizationRequest to match the value requested the user selected.  If user selects "When in use", set locationAuthorizationRequest: "WhenInUse" and vice versa.
