### ISSUE TITLE
Timestamp configuration option

### ISSUE THREAD

**Issue by pr-rojan** [transistorsoft/react-native-background-geolocation#289]
## Your Environment
* Plugin version: 2.8.1
* Platform: iOS and Android
* OS version:
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`): 0.44.0
* Plugin config

## Expected Behavior

Timestamp should be current timestamp Date.now();

## Actual Behavior

Timestamp gives me in GMT

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
This is correct and documented.  There will not be configurable.  Convert timestamp from location into whatever format you desire.
