### ISSUE TITLE
HeartBeats not working as expected on Android

### ISSUE THREAD

**Issue by mtflud** [transistorsoft/react-native-background-geolocation#291]
## Your Environment
* Plugin version: 2.8.4
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Samsung Galaxy 6 Edge
* React Native version (`react-native -v`): 0.46.1
* Plugin config

```javascript
{
        desiredAccuracy: 0,
        stationaryRadius: 25,
        distanceFilter: 0,
        stopTimeout: 0,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: true,
        startOnBoot: true,
        batchSync: false, 
        autoSync: false, 
        locationUpdateInterval: 5000,
        heartbeatInterval: 15, 
        preventSuspend: true,
        foregroundService: true,
}
```

## Expected Behavior
HeartBeats event gets fired when the device is stationary every *n* seconds configured with `heartbeatInterval` option.

## Actual Behavior
Plugin ignores this configuration parameter and instead uses the default 60 seconds.

## Steps to Reproduce
1. Configure plugin with provided configuration
2. Attach listeners

```javascript
BackgroundGeolocation.on('location', this._reportLocationFromLocation.bind(this));
BackgroundGeolocation.on('heartbeat', this._reportLocationFromHeartBeat.bind(this));
```
3. Configure listener functions (we'll use alerts for now)

```
javascript
_reportLocationFromHeartBeat(lastLocation) {
        alert(JSON.stringify(lastLocation));
}

_reportLocationFromLocation(location) {
    alert(JSON.stringify(location));
}
```
 

## Context
I want to send location updates to a back-end service, regardless if the device is stationary or not.
iOS Works as expected.

**Comment by christocracy** [comment]
The minimum `heartbeatInterval` for Android is `60` seconds.
