### ISSUE TITLE
Android: AbstractMethodError

### ISSUE THREAD

**Issue by Mahaswami** [transistorsoft/react-native-background-geolocation#293]
## Your Environment
* Plugin version: 2.8.4
* Platform: Android
* OS version: Android 6.x
* Device manufacturer / model: Motorola Play G
* React Native version (`react-native -v`): 0.45.1
* Plugin config

Nothing special
## Expected Behavior

Should launch the app first.

## Actual Behavior

Throws an error and app crashes.

## Steps to Reproduce

1.
2.
3.
4.

## Context

Build setup

    compile( project(':react-native-background-geolocation')){
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }

    compile 'com.google.android.gms:play-services-base:10.2.4'
    compile 'com.google.android.gms:play-services-maps:10.2.4'
    compile 'com.google.android.gms:play-services-gcm:10.2.4'
    compile 'com.google.android.gms:play-services-location:10.2.4'

## Debug logs

07-25 20:50:43.523 22068 22068 E AndroidRuntime: FATAL EXCEPTION: main
07-25 20:50:43.523 22068 22068 E AndroidRuntime: Process: com.cloudscann.vic2.four, PID: 22068
07-25 20:50:43.523 22068 22068 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzq, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter(RNBackgroundGeolocationModule.java:973)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.initializeLocationManager(RNBackgroundGeolocationModule.java:968)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostResume(RNBackgroundGeolocationModule.java:82)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:187)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:556)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:589)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:811)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:109)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$4$2.run(ReactInstanceManager.java:771)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:746)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5459)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
07-25 20:50:43.523 22068 22068 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
07-25 20:50:43.525  1860  8376 W ActivityManager:   Force finishing activity com.cloudscann.vic2.four/.MainActivity

**Comment by Mahaswami** [comment]
Somewhere I read that similar stack trace means the code is expecting google play services version level 9.8 or something. The latest is already 11.0 and most people should be running 10.2.x

**Comment by Mahaswami** [comment]
btw we are paid users of the Cordova version looking to migrate to react-native

**Comment by christocracy** [comment]
You're using some other components which are including mismatched `play-services` dependencies.

See my [Demo App](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/app/build.gradle#L149) for hints on how to resolve these.

**Comment by Mahaswami** [comment]
btw, our env needs to run on Android OS 5+ onwards. Perhaps your demo runs on 7?

**Comment by Mahaswami** [comment]
I have also read somewhere that the issue also doesn't happen on Android 7

**Comment by christocracy** [comment]
I test on a variety of device, from a Galaxy Nexus @ 4.3 to Google Pixel run 7.x.  This is not related to the Android os version.

>I have also read somewhere that the issue also doesn't happen on Android 7

False.  It's related to multiple components including different versions of `play-services` dependencies.  You'll have to go through all your components to determine which are using `play-services` dependencies and `exclude` / `force` them as shown in my Demo app's `build.gradle` above.

**Comment by Mahaswami** [comment]
We did that exclude for all comps. In our context, Airbnb's mapview is also using google play services. We have excluded that. And we override with the below

compile 'com.google.android.gms:play-services-base:10.2.4'
compile 'com.google.android.gms:play-services-maps:10.2.4'
compile 'com.google.android.gms:play-services-gcm:10.2.4'
compile 'com.google.android.gms:play-services-location:10.2.4'

**Comment by Mahaswami** [comment]
Here is the complete dependencies section

dependencies {
    compile project(':react-native-push-notification') 
    compile project(':react-native-maps')
    compile( project(':react-native-background-geolocation')){
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile project(':react-native-thumbnail')
    configurations.all { resolutionStrategy.force 'com.squareup.okhttp3:okhttp:3.4.1' }
    compile project(':react-native-background-upload')
    compile project(':bugsnag-react-native')
    compile project(':react-native-video')
    compile(project(':react-native-push-notification')){
      exclude group: 'com.google.android.gms', module: 'play-services-gcm'
    }

    compile(project(':react-native-maps')){
            exclude group: 'com.google.android.gms', module: 'play-services-base'
            exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }

    compile 'com.google.android.gms:play-services-base:10.2.4'
    compile 'com.google.android.gms:play-services-maps:10.2.4'
    compile 'com.google.android.gms:play-services-gcm:10.2.4'
    compile 'com.google.android.gms:play-services-location:10.2.4'


    compile project(':react-native-vector-icons')
    compile project(':react-native-permissions')
    compile project(':react-native-image-picker')
    compile(name: 'tslocationmanager', ext: 'aar')
    compile(name:'com.wowza.gocoder.sdk', ext:'aar')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    
}

I will also run the demo app and check

**Comment by Mahaswami** [comment]
oops. sorry just noticing that there is a bug in react-native links that keep putting back the stuff without exclusions. let me check that again to see if it affects in some way

**Comment by Mahaswami** [comment]
Sorry my mistake. I overlooked the re-generated code. Closing the issue

**Comment by ameeee** [comment]
I am receiving this error tho i applied many changes as mentioned. i should keep my gradle version 4.x because some dependencies wont work 


A problem occurred configuring project ':geolocation'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

Any help plz!

**Comment by christocracy** [comment]
This closed issue is nearly 3 years old and likely has nothing to do with the plugin, whose name is `react-native-background-geolocation`.  You seem to be having an issue with a plugin named `geolocation`

**Comment by ameeee** [comment]
Yes, I thought someone might have had a similar issue here. Been trying to fix it for long

**Comment by christocracy** [comment]
react-native Android of today (0.60+) bears little resemblance to that 2.5 years ago (0.45).

**Comment by ameeee** [comment]
i opened a new issue right here https://github.com/ameeee/Geolocation/issues/1 @christocracy
