### ISSUE TITLE
Android Status Bar Icon no longer showing after upgrade from 2.8.3 to 2.8.4

### ISSUE THREAD

**Issue by ferdicus** [transistorsoft/react-native-background-geolocation#295]
The android status bar was showing a small app icon when using version 2.8.3.
However after upgrading to 2.8.4 this icon is missing.

Not quite sure if this is linked to the `notificationIcon` value.

Previously I didn't even set these properties `(notification-Icon | -SmallIcon | -LargeIcon)` and it was showing the icon shown in the attached image.

## Your Environment
* Plugin version: 2.8.4
* Platform: Android 7
* OS version: OS X 10.12.5
* Device manufacturer / model: AVD
* React Native version (`react-native -v`): 0.46.4
* Plugin config

```
  return {
    enabled: false,
    desiredAccuracy: 0,
    stationaryRadius: 25,
    distanceFilter: 1,
    stopTimeout: 15,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: true,
    foregroundService: true,
    notificationTitle: 'MyApp',
    notificationText: 'Location service activated',
    notificationIcon: "drawable/icon",
    notificationSmallIcon: "drawable/icon",
    notificationLargeIcon: "drawable/icon",
    notificationColor: 'red',
    startOnBoot: false,
    url: locationEndpoint,
    batchSync: false,
    autoSync: true
  }
```

## Expected Behavior
Icon is showing in status bar, like it did in 2.8.3

## Actual Behavior
Icon is not showing in 2.8.4

## Steps to Reproduce
1. Add the `foregroundService: true` to your config 
2. Notice the missing status bar icon which was there in previous version

## Context
Upgrading from version 2.8.3 > 2.8.4 when noticing this issue

2.8.3:
<img width="411" alt="screen shot 2017-07-27 at 16 48 48" src="https://user-images.githubusercontent.com/26439946/28677380-a6d68054-72ed-11e7-8d49-cdcbf3999685.png">

2.8.4:
<img width="412" alt="screen shot 2017-07-27 at 16 52 00" src="https://user-images.githubusercontent.com/26439946/28677389-aca5acb2-72ed-11e7-81ac-c7c44f22b28b.png">

**Comment by christocracy** [comment]
This is correct.  I found a way to hide the notification-bar icon (which most people complained about).

However, I've made it configurable now with new option `notificationPriority`.  This is only available in the Premium version currently.  It will appear here when I next post the latest-stable release here to the public repo.

**Comment by ferdicus** [comment]
Who would complain about such a cool feature! :)

Thanks for the quick reply - I'll wait than.
