### ISSUE TITLE
App crashes and seizes working after using sample snippet

### ISSUE THREAD

**Issue by RobTS** [transistorsoft/react-native-background-geolocation#299]
* Plugin version: 2.8.4
* Platform: iOS for now, Android probably affected as well
* OS version: 10.3.3
* Device manufacturer / model: iPhone 5S
* React Native version (`react-native -v`): 0.46.4
* Plugin config: Not relevant here, I guess

## Expected Behavior

When executing the following snippet found in the wiki, a point should be added with some extra information.

```
BackgroundGeolocation.getCurrentPosition(function(location, taskId) {
  location.extras = {foo: 'bar'}; // <-- add some arbitrary extras-data

  // Insert it.
  BackgroundGeolocation.insertLocation(location, function() {
    BackgroundGeolocation.finish(taskId);
  });
});
```

## Actual Behavior

Instead, the app crashes and will crash on startup every time after until the database is removed by uninstalling. Error message: 

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: uuid)'
```

Reason is most probably the fact that the location already has a UUID set and something messes up with the DB constraints.

## Steps to Reproduce

Execute code

## Context

Fetching the current location, then waiting for user input and persisting the location when he started the interaction with his input to the DB.

## Debug logs

Shown above

**Comment by christocracy** [comment]
While it shouldn't crash here, the plugin *already* persists every location it records (unless you explicitly provide `{persist: false}` to `getCurrentPosition` arguments.

You don't need to `#insertLocation` here.  If it didn't crash, you'd have the same position recorded twice.

**Comment by christocracy** [comment]
I've found and fixed this in the Premium version.  Fix will arrive here when latest stable release is next posted.  In the meantime, try ensuring you provide a `uuid` to the location-data you send to `#insertLocation`.  It can be any string you like.

**Comment by RobTS** [comment]
Before I forget: Works like a charm!

**Comment by christocracy** [comment]
You're a customer, are you not?  you should use the private repo for latest updates.  This repo gets only latest stable releases.
