### ISSUE TITLE
Implement Geofence APIs

### ISSUE THREAD

**Issue by rushidesai** [transistorsoft/react-native-background-geolocation#3]
Looks like this is not yet done. Only documented?

**Comment by christocracy** [comment]
Correct.  There's not much to it though, just wiring it up.  Hardest
part is wiring up the UI in the demo app.  MapboxGL for
react-native doesn't yet support adding circles to the map.

Getting the actual module to work is trivial.  Prob a couple hours work.

On Thursday, August 20, 2015, Rushi Desai <notifications@github.com> wrote:

> Looks like this is not yet done. Only documented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/3>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
If you want a taste, you can try my Cordova Android demo.  It's the same library that'll be used when react-native Android support comes online.  I don't have an iOS demo submitted.
https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic

**Comment by rushidesai** [comment]
Is TSLocationManager open sourced?

Later,
Rushi

**Comment by christocracy** [comment]
No.

On Friday, August 21, 2015, Rushi Desai <notifications@github.com> wrote:

> Is TSLocationManager open sourced?
>
> Later,
> Rushi
>
> On Thu, Aug 20, 2015 at 3:13 PM, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > If you want a taste, you can try my Cordova Android demo. It's the same
> > library that'll be used when react-native Android support comes online. I
> > don't have an iOS demo submitted.
> >
> >
> https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/transistorsoft/react-native-background-geolocation/issues/3#issuecomment-133194429
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/3#issuecomment-133279278>
> .
>


-- 
Snet form Gmail Mobile
