### ISSUE TITLE
License bug!

### ISSUE THREAD

**Issue by rumax** [transistorsoft/react-native-background-geolocation#301]
The project claims that the license is MIT, but readme states:

> The Android module requires purchasing a license. 

The license should be changed, because MIT (https://opensource.org/licenses/MIT) clearly states that:

```
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software")
```

**Comment by christocracy** [comment]
That doesn't apply to the compiled binary.

The React Native module is free and open to modify.

**Comment by rumax** [comment]
You are wrong, if you claim that your package is **MIT** anyone should be able to use it as **MIT**. Otherwise you are limiting our right and do not follow the MIT license.

Moreover this is a documentation:

```
Using the plugin:

import BackgroundGeolocation from "react-native-background-geolocation";
```

Where is the `Android module` which `requires purchasing a license`? How can I remove it and still use your MIT package only?
