### ISSUE TITLE
Getting geolocation status

### ISSUE THREAD

**Issue by cosmith** [transistorsoft/react-native-background-geolocation#31]
Hi, is there a way to tell if the plugin is currently working (getting positions)?

I want to have a settings screen where the user can disable the tracking, so I'd like to be able to get the current status. It could be as simple as an item in `.getState()`, that would return `{active: true|false}`.

Thanks!

**Comment by christocracy** [comment]
Yes.  #getState

https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/api.md#getstatecallbackfn

On Tuesday, November 24, 2015, Corentin Smith <notifications@github.com>
wrote:

> Hi, is there a way to tell if the plugin is currently working (getting
> positions)?
>
> I want to have a settings screen where the user can disable the tracking,
> so I'd like to be able to get the current status. It could be as simple as
> an item in .getState(), that would return {active: true|false}.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/31>
> .
>


-- 
Snet form Gmail Mobile

**Comment by cosmith** [comment]
Hm sorry I hadn't realized that `enabled` was already in there...
