### ISSUE TITLE
Upgrade from 2.9.0 to 2.9.2 causes error in Xcode

### ISSUE THREAD

**Issue by joegoodall1** [transistorsoft/react-native-background-geolocation#310]
## Your Environment
* Platform: iOS 
* React Native version: 0.47.1

## Expected Behavior
Successful build
## Actual Behavior
Build failed with error shown below
## Steps to Reproduce
Upgrade to 2.9.2 and try to build

NB. Previous builds were successful

<img width="1280" alt="screen shot 2017-08-23 at 16 25 07" src="https://user-images.githubusercontent.com/8888799/29624480-16f76504-8821-11e7-86a7-7e92a06dc4c9.png">

**Comment by christocracy** [comment]
Yes, I had to [make a change](https://github.com/transistorsoft/react-native-background-fetch/commit/b46a5a135f1c0064441e6de75745f601532a9b00#diff-8335617f08bd25873d185a1dd7d49518R19) to `react-native-background-fetch`.  You need `react-native-background-fetch@2.1.0`

**Comment by christocracy** [comment]
`2.9.1` [*does* request](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/package.json#L46) `react-native-background-fetch@2.1.0` but I imagined there *would* be issues.

**Comment by joegoodall1** [comment]
Hi @christocracy, have you made any progress with this?

I've tried installing `react-native-background-fetch@2.1.0` separately but this doesn't seem to fix the above.

**Comment by christocracy** [comment]
There's nothing to progress upon.  Your app dependencies are mixed up.

npm uninstall / re-install

**Comment by joegoodall1** [comment]
Not sure I understand.

If there's nothing to progress upon why did you say [yesterday](https://github.com/transistorsoft/react-native-background-geolocation/issues/310#issuecomment-324375701) you thought there would be issues?

The npm uninstall / re-install is something we tried previously and doesn't seem to fix the problem (at least for us).

As I noted earlier, we had no problems with previous versions of react-native-background-geolocation. Not sure what is going on with 2.9.2.

**Comment by christocracy** [comment]
>you thought there would be issues?

I thought there would be *dependency* issues.  Your app has an old version of `react-native-background-fetch` in your project.  You need to completely remove it and re-install it.

**Comment by christocracy** [comment]
>we had no problems with previous versions of react-native-background-geolocation. Not sure what is going on with 2.9.2.

Of course you didn't.  2.9.2 references a new version of `react-native-background-fetch`, containing a *very* important bug fix which prevents your app from crashing.

**Comment by christocracy** [comment]
Update?

**Comment by joegoodall1** [comment]
1) Uninstalled and unlinked react-native-background-geolocation. 
2) Searched the xcodeproj file and manually removed any reference to react-native-background-geolocation and react-native-background-fetch. 
3) Reinstalled react-native-background-geolocation. 

Everything works now with no errors.
