### ISSUE TITLE
Android heartbeatInterval is being ignored

### ISSUE THREAD

**Issue by Metroninja** [transistorsoft/react-native-background-geolocation#311]
## Your Environment
* Plugin version: 2.9.2
* Platform:  Android (with a license)
* OS version: OSX
* Device manufacturer / model: Simulator
* React Native version (`react-native -v`): 47.2
* Plugin config
```
{
      // Geolocation Config
      desiredAccuracy: 0,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,     // <-- Auto start tracking when device is powered-up.
      preventSuspend: true,
      heartbeatInterval: 15,

    }
```
## Expected Behavior
It should fire on the interval value

## Actual Behavior
it fires after 60 seconds

## Steps to Reproduce
1.  Use the config above and set a listener on the heartbeat event.  it will fire every 60 seconds
2.
3.
4.

## Context
Monitor heartbeat events at a lower interval than 60 seconds.

**Comment by christocracy** [comment]
Minimum interval is 60

**Comment by Metroninja** [comment]
How come iOS works lower than 60?  (please don't fix that)

**Comment by christocracy** [comment]
Because the Android mechanism generating heartbeat, AlarmManager, doesn't fire any quicker.  It's impossible.

What's the point of such a fast heartbeat?  Do you like killing the user's battery?

**Comment by Metroninja** [comment]
Security response dispatching.  Shifts can last up to 8 hours, and we can't guarantee the responder will have the app open 100% of the time.  If the phone goes to sleep we need to not only continually monitor their location for dispatching priority but also need to regularly check for dispatch events at a much quicker clip as the SLA is <12 minutes.

**Comment by Metroninja** [comment]
I was using this library for iOS and https://github.com/ocetnik/react-native-background-timer for android but assumed this one would heartbeat at parity with iOS  (`react-native-background-timer` would fire every 10 seconds without issue on android).  I guess I don't need an android license after all...

**Comment by christocracy** [comment]
`react-native-background-timer` uses [`postDelayed`](https://www.google.ca/search?q=android+postDelayed+not+firing&oq=android+postDelayed+not+firing&aqs=chrome..69i57.8100j0j4&sourceid=chrome&ie=UTF-8)

You'll find your [timer not firing consistently after a period of time](https://www.google.ca/search?q=android+postDelayed+not+firing&oq=android+postDelayed+not+firing&aqs=chrome..69i57.8100j0j4&sourceid=chrome&ie=UTF-8) and when the device goes into [Doze Mode](https://stackoverflow.com/questions/17324587/will-a-handler-postdelayed-not-being-fired-when-cpu-sleeps/17381211#17381211)

I've been doing this for over 4 years.  I've seen it all.

**Comment by christocracy** [comment]
And with the upcoming changes to [Background Execution](https://developer.android.com/about/versions/oreo/background.html) in Oreo, it's going to be even more difficult to rely on `#postDelayed`.

See here if you care to educate yourself on [`AlarmManager` vs `postDelayed`](https://www.google.ca/search?q=postDelayed+vs+alarmManager&oq=postDelayed+vs+alarmManager&aqs=chrome..69i57j0.5703j0j4&sourceid=chrome&ie=UTF-8)

**Comment by Metroninja** [comment]
Thanks @christocracy appreciate the insight!

**Comment by christocracy** [comment]
Also, `react-native-background-timer` doesn't run as a Service.  This plugin *does*, with the option of running as a "foreground service", making the service far less likely to be killed when the OS is under memory pressure:

- [Background Service to work even after app is killed](https://github.com/ocetnik/react-native-background-timer/issues/7)
- [Does not work](https://github.com/ocetnik/react-native-background-timer/issues/49)
- [Description of underlying system used](https://github.com/ocetnik/react-native-background-timer/issues/3)
- [Stopped when locked](https://github.com/ocetnik/react-native-background-timer/issues/39)
- [Stop working when phone is locked](https://github.com/ocetnik/react-native-background-timer/issues/15)

**Comment by martijnplaat** [comment]
Currently I use react-native-background-geolocation heartbeat for iOS and react-native-background-timer for Android to send the GPS coordinates to a remote server in background mode.

However, reading the comments here (and on transistorsoft/react-native-background-geolocation#311 (comment)) I have the feeling my current implementation is not really future proof.

Am I correct? What is a future proof solution with React Native to automatically send GPS coordinates in background mode? Could I better invest in a solution using Native Modules?

**Comment by christocracy** [comment]
Yes, React-Native-background-timer is a bad idea for long-term tracking.

This plugin's Android module is over 4 years old, supported full time and evolves constantly.

This plugin was designed for tracking first-responders in disaster zones, where it must continue tracking in spite of no network, app terminate and device reboot.

It runs with latest Android 8 without any issues.

**Comment by christocracy** [comment]
@metroninja 

>Security response dispatching

This plugin was designed for a disaster-response company in Florida.  It was designed to track first-responders in hurricanes, where network is likely destroyed (this is why the plugin always first persists all its locations to its own database:  so they can be uploaded to server once the device acquires a network connection).  It's designed to track devices as if life depended on it.

> If the phone goes to sleep we need to not only continually monitor their location

The Android plugin is constantly monitoring the ActivityRecognition system.  If device movement is detected, the plugin is going to start tracking, no matter what.

Read [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

>but also need to regularly check for dispatch events at a much quicker clip as the SLA is <12 minutes.

Your app should not be *polling* for events -- your *server* should be *pushing* events (ie: server push requests).

**Comment by Metroninja** [comment]
Thanks again @christocracy - that's what I ended up doing.  I was trying to do a client side workaround while we waited for the backend to implement push notifications but after your initial post I got tired of wasting my time and went ahead and implemented them myself.  We are still using your app for sending location updates and it works fantastic

**Comment by ParthBarot-BoTreeConsulting** [comment]
I will try this, i am also using the `BackgroundTimer` and facing similar issue while tracking gps and other data every few minutes.
