### ISSUE TITLE
Erratic HeartBeat events

### ISSUE THREAD

**Issue by mishravarun** [transistorsoft/react-native-background-geolocation#315]
## Your Environment
* Plugin version: 2.9.2
* Platform: iOS
* OS version: 10.3.3
* Device manufacturer / model: iPhone 7
* React Native version (`react-native -v`): 0.36.1
* Plugin config
```javascript
             desiredAccuracy: 1000,
             distanceFilter: 10,
             stopTimeout: 5,
             debug: false,
             logLevel: BackgroundGeolocation.LOG_LEVEL_NONE,
             stopOnTerminate: true, 
             startOnBoot: false,      
             preventSuspend: true,
             heartbeatInterval: 60
```
## Expected Behavior

Ideally the `onHeartBeat(params)` should be called every 60 seconds.

## Actual Behavior

I wrote code to log the event trigger times to a .txt file, so that I can view the logs after running the app for several hours. While the phone is connected to the mac, I see that the event is triggered perfectly every 60 second. After I disconnect the the phone and use it regularly for a few hours, there seems to be an erratic behavior in the way the HeartBeat events are triggered. Sometimes the events are fired within a few minutes of the previous one, whereas sometimes it just doesn't trigger for 20-30 minutes. I have copied the log below. Background Fetch, and location updates are enabled in the app 'Background Modes' and location always use is added to info.plist.

```
02.09.17 16:45:01 -- HB 
02.09.17 16:46:01 -- HB
02.09.17 16:47:01 -- HB
02.09.17 16:48:01 -- HB
02.09.17 16:49:01 -- HB
02.09.17 16:50:03 -- HB
02.09.17 16:53:42 -- HB
02.09.17 17:02:06 -- HB
02.09.17 17:12:00 -- HB
02.09.17 17:21:58 -- HB
02.09.17 17:25:58 -- HB
02.09.17 17:37:07 -- HB
02.09.17 17:46:58 -- HB
02.09.17 17:53:28 -- HB
02.09.17 18:02:58 -- HB
02.09.17 18:12:58 -- HB
02.09.17 18:25:05 -- HB
02.09.17 18:28:00 -- HB
02.09.17 18:39:40 -- HB
02.09.17 18:40:40 -- HB
02.09.17 18:46:59 -- HB
02.09.17 18:51:57 -- HB
02.09.17 18:57:00 -- HB
02.09.17 19:05:00 -- HB
02.09.17 19:13:00 -- HB
02.09.17 19:22:43 -- HB
02.09.17 19:27:24 -- HB
02.09.17 19:33:04 -- HB
02.09.17 19:34:15 -- HB 
02.09.17 20:22:56 -- HB
``` 

## Steps to Reproduce

1. Copy the plugin configuration 
2. Save system time to a file when `onHeartBeat` is called (alternately, change the log level and view the sqlite file).

## Context
I am trying to make a background sensing application. The plugin provides with location updates, and also helps in keeping the app alive in the background, so the the app can monitor device lock-unlock state, battery level, accelerometer logging, etc. The logging for precise location, accelerometer happens for 1 minute every 3 minutes, so the heartbeat events are necessary to time the recordings. Battery life is not a major factor right now.

Not sure if I am missing something, because it seems that the application is being woken up periodically, but is not up continuously.

**Comment by christocracy** [comment]
Unfortunately, when the device is in background and unplugged from power with screen off, iOS freezes timers from executing in spite of holding a backgroundTask id.

As soon as screen is activated or device motion occurs, iOS will unfreeze timers for about 2-3 minutes.

No way around this limitation, I tried for days.  iOS is strict about this.

**Comment by christocracy** [comment]
Btw, you know the plugin stores its logs to its own database?

You don't have to write logs to a txt file.  Just execute method #getLog.  See config options #logLevel and #logMaxDays

**Comment by christocracy** [comment]
And if you want to write your own log message from JavaScript API, see docs for BackgroundGeolocation.logger

**Comment by mishravarun** [comment]
Thanks for the tip! Yes, I'm aware that the plugin logs to its own database. I have some native ios code logging to the txt file, so thought it would be convenient to have all of it together.

**Comment by mishravarun** [comment]
@christocracy : I noticed a similar behavior in Android as well. I set the heartbeat interval for 5 minutes, and noticed that the heart beat events are not being triggered correctly. Sometimes its being triggered once every couple of hours (like at night), while sometimes its working fine. Is it because of Doze mode that the AlarmManager is not able to trigger the events?

Here is the event log-
```
Oct 16, 2017 15:53:29-----HB
Oct 16, 2017 15:58:49-----HB
Oct 16, 2017 16:12:24-----HB
Oct 16, 2017 16:56:40-----HB
Oct 16, 2017 17:02:15-----HB
Oct 16, 2017 17:06:09-----HB
Oct 16, 2017 17:12:46-----HB
Oct 16, 2017 17:17:06-----HB
Oct 16, 2017 17:23:08-----HB
Oct 16, 2017 17:26:06-----HB
Oct 16, 2017 18:17:24-----HB
Oct 16, 2017 18:22:40-----HB
Oct 16, 2017 18:26:46-----HB
Oct 16, 2017 18:32:42-----HB
Oct 16, 2017 18:38:19-----HB
Oct 16, 2017 19:26:36-----HB
Oct 16, 2017 21:18:27-----HB
Oct 16, 2017 21:29:52-----HB
Oct 16, 2017 21:35:30-----HB
Oct 16, 2017 21:40:30-----HB
Oct 16, 2017 21:45:31-----HB
Oct 16, 2017 21:49:32-----HB
Oct 16, 2017 21:55:34-----HB
Oct 16, 2017 22:00:35-----HB
Oct 16, 2017 22:04:30-----HB
Oct 16, 2017 22:10:38-----HB
Oct 16, 2017 22:14:30-----HB
Oct 16, 2017 22:19:42-----HB
Oct 16, 2017 22:24:30-----HB
Oct 16, 2017 22:30:45-----HB
Oct 16, 2017 22:35:52-----HB
Oct 16, 2017 22:39:43-----HB
Oct 16, 2017 22:44:30-----HB
Oct 16, 2017 22:50:05-----HB
Oct 16, 2017 22:54:31-----HB
Oct 16, 2017 23:00:11-----HB
Oct 16, 2017 23:04:30-----HB
Oct 16, 2017 23:11:34-----HB
Oct 16, 2017 23:14:30-----HB
Oct 16, 2017 23:20:32-----HB
Oct 16, 2017 23:27:30-----HB
Oct 16, 2017 23:30:45-----HB
Oct 16, 2017 23:36:37-----HB
Oct 16, 2017 23:42:15-----HB
Oct 16, 2017 23:54:10-----HB
Oct 16, 2017 23:59:30-----HB
Oct 17, 2017 00:04:31-----HB
Oct 17, 2017 00:09:33-----HB
Oct 17, 2017 00:14:34-----HB
Oct 17, 2017 00:19:38-----HB
Oct 17, 2017 00:24:38-----HB
Oct 17, 2017 01:18:09-----HB
Oct 17, 2017 03:09:00-----HB
Oct 17, 2017 07:01:08-----HB
Oct 17, 2017 09:48:50-----HB
Oct 17, 2017 09:54:25-----HB
Oct 17, 2017 09:58:51-----HB
Oct 17, 2017 10:05:30-----HB
Oct 17, 2017 10:35:50-----HB
Oct 17, 2017 10:41:02-----HB
Oct 17, 2017 10:46:02-----HB
Oct 17, 2017 10:50:54-----HB
```

**Comment by christocracy** [comment]
Yes, it will be Doze mode.  Doze mode exists *for a reason*.

**Comment by mishravarun** [comment]
Yes, but I thought that using a ForegroundService can bypass the Doze mode?

**Comment by christocracy** [comment]
Nope.

**Comment by Tchaikovsky1114** [comment]
@christocracy 

hello
first, thank you for your great plug-in.
i have some question that seem to be related it

Is this restriction still in plug-in?

i want to check user's location every 5 minuet, 
but onHeartbeat doesn't seem to be working properly because of this limitation.

**Comment by christocracy** [comment]
For periodic location requests, implement background-fetch, already included as a dependency.  See its readme for implementation details.

**Comment by Tchaikovsky1114** [comment]
i really appreciate your rapidly answer..!
thank you! thank you! 😂
