### ISSUE TITLE
HTTP service stop reporting positions and calls to `sync()` return 'HTTPService is busy'

### ISSUE THREAD

**Issue by alexandrevoilab** [transistorsoft/react-native-background-geolocation#316]
## Your Environment
* Plugin version: 2.9.2
* Platform: Android
* OS version: 6.0
* Device manufacturer / model: Wiko Sunny
* React Native version (`react-native -v`): react-native-cli: 2.0.1 / react-native: 0.47.1
* Plugin config see logs

## Expected Behavior
HTTP service should report positions event without user interaction for my hours. With a reasonable delay (not 2h later).

## Actual Behavior
Randomly HTTP service stop reporting positions to the remote server. Sometimes as soon as the first positions, sometimes after many minutes / hours of tracking. Positions are correctly recorded in the database but not send by HTTP service. Each calls to `.sync()` return an error `HTTPService is busy`. As soon as the user unlock the device *and* put the app on foreground, the HTTP service kicks in and send all recorded positions to the server.

I understand that sometimes `HTTPService is busy` is normal behaviour. But I don't expect it to be busy for 30 min straight and suddenly stop being busy only on user interaction.

## Context
Component logs and server logs are attached. The server logs are UTC and component UTC+2. (sorry)
There is 30 min of logs form the app.
At 22:22 UTC I started the tracking from the app.
At 23:51 UTC I unlocked with the app on foreground.
At 23:52 UTC I stop the tracking from the app.
As can be seen on the logs, only one position is sent at 22:22 UTC. After that there is a 30 min gap on the server logs. Then at 23:51 UTC, when I unlock the device, every positions are reported on the same request to the server (`batchSync` is set to `true`).

I should point out that the device had Wifi and 3G access all the time.

## Debug logs

[Master_2017-09-06T23_52_32.585Z.log.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1283069/Master_2017-09-06T23_52_32.585Z.log.txt)
[server.log.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1283070/server.log.txt)

**Comment by christocracy** [comment]
In the premium version, I replaced the Android HTTP lib Volley with the more modern OkHttp3.  I had a couple of others report a similar issues with *some* devices on *some* servers.

Try installing branch [okhttp](https://github.com/transistorsoft/react-native-background-geolocation/tree/okhttp)

**Comment by alexandrevoilab** [comment]
Hi Chris,

Thanks you, I'll try that and keep you updated.

I'll be out until next week, I'll try when I'm back.

**Comment by christocracy** [comment]
Update?

**Comment by alexandrevoilab** [comment]
Hi Chris,

I ran some tests this week. It's noticeably better. Still some logs saying `HTTPService is busy` but very few and they seems quite normal.
Devices now track for much longer time.

I still have problems with tracking stopping randomly and not starting after boot. But that will be for another ticket when I have enough logs.

I'll close that ticket as your branch resolve it and I'll be switching to premium.
I'll be away three weeks, I'll get back to you for the premium then.

Thanks again

**Comment by christocracy** [comment]
It’s perfectly normal to “HTTP service is busy”.

The http service operates in a loop, selecting records from the database and posting each to server.

If another record is inserted while the “HTTPService is busy”, it will be selected and immediately posted in the next iteration of the loop.

The HTTservice loops iterates until the database is empty or an Http response returns non 20x

**Comment by gtaylor44** [comment]
Was this branch ever merged into master? I’m seeing a lot of the same type of error in our logs with some devices essentially blocked completely. I will be implementing bulk upload of positions to see if this will help.

**Comment by christocracy** [comment]
Yes, nearly 2 years ago.  Post a new issue, this one is closed.
