### ISSUE TITLE
backgroundGeolocation.start() takes a while to start tracking positions

### ISSUE THREAD

**Issue by gianpieroc** [transistorsoft/react-native-background-geolocation#319]
Plugin version: 2.9.2
Platform: iOS or Android: iOS
OS version: 10.3
Device manufacturer / model: multiple models
React Native version (react-native -v): 0.47.2
Plugin config: // Geolocation Config
desiredAccuracy: 10,
distanceFilter: 10,
stationaryRadius:0,
disableElasticity: true,
locationUpdateInterval: 1000,
fastestLocationUpdateInterval: 500,
// Activity Recognition
stopTimeout: 1,
// Application config
debug: false,
logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
stopOnTerminate: true,
startOnBoot: this.state.tracking,
url: 'http://server.com/locations',
batchSync: false,
autoSync: true,
headers: {
'x-user-token': 'Bearer token'
}
Expected Behavior

Track when backgroundLocation.start() is triggered 

Actual Behavior

when backgroundLocation.start() is triggered takes some seconds to start tracking locations 

Steps to Reproduce

 BackgroundGeolocation.un('location', this.onLocation);
onLocation = location => {
return this.addCoords(location);
};

addCoords = location => {
this.setState({
coordinates: [
...this.state.coordinates,
{
latitude: location.coords.latitude,
accuracy: location.coords.accuracy,
heading: location.coords.heading,
longitude: location.coords.longitude,
speed: location.coords.speed
}
],
currentSpeed: location.coords.speed
});
};

**Comment by christocracy** [comment]
This is normal behaviour.  See [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

Also watch this [demo video](https://youtu.be/aR6r8qV1TI8?t=48)
