### ISSUE TITLE
[Feature Request] Adjustable DistanceFilter Elasticity Factor/Power/Thresholds

### ISSUE THREAD

**Issue by wbattel4607** [transistorsoft/react-native-background-geolocation#320]
## Your Environment
* Plugin version: 2.9.2
* Platform: iOS & Android
* OS version: iOS 10+ & Android 6+
* Device manufacturer / model: irrelevant
* React Native version (`react-native -v`): 0.45.1+
* Plugin config: `disableElasticity: false, distanceFilter: 20 ...`

## Current Behavior
As speed increases through hard-coded thresholds, the distanceFilter is given a multiplier to reduce location updating to more reasonable frequencies. This makes perfect sense, but it would be even better if we could control the multiplier.

## Desired Feature
Add a config option(s) to change how `distanceFilter` scales with speed.

## Additional Context
As it is right now, if my `distanceFilter` is set to `20` then the elasticity factor increases `distanceFilter` by `20` at each respective threshold.

I don't know (and couldn't yet find) the exact values, but it seems to be roughly:
- 00 - 10 m/s = 1 x distanceFilter
- 10 - 20 m/s = 2 x distanceFilter
- 20 - 30 m/s = 3 x distanceFilter
- 30 - 40 m/s = 4 x distanceFilter

An example of what I'd prefer for my app is, for example, by changing the factors:
- 00 - 10 m/s = 1 x distanceFilter
- 10 - 20 m/s = 2 x distanceFilter
- 20 - 30 m/s = 4 x distanceFilter
- 30 - 40 m/s = 8 x distanceFilter

Or even better, if it were possible to, instead of changing the factors, changing the speed thresholds:
- 00 - 05 m/s = 1 x distanceFilter
- 05 - 15 m/s = 2 x distanceFilter
- 15 - 25 m/s = 3 x distanceFilter
- 25 - 35 m/s = 4 x distanceFilter
- 35+ m/s = 5 x distanceFilter

Best case scenario for my app would be this:
- 00 - 05 m/s = 1 x distanceFilter
- 05 - 15 m/s = 5 x distanceFilter
- 15 - 25 m/s = 10 x distanceFilter
- 25+ m/s = 25 x distanceFilter

This concept would make more or less sense depending on the app but I know for mine, where we only care for the most recent location, we want to have more control over the frequency of recorded locations at higher speeds. At walking speed we'd like a `distanceFilter` of 20m, and at highway speed we'd prefer a `distanceFilter` of 500m. The library I migrated from to this one had `distanceFilter` related *exponentially* to speed, which made a lot of sense in my opinion- though again it will vary from app to app.

Also, I know that I *could* do this manually since the speed is returned with the location. I *could* reconfigure every time the speed passes through thresholds. But it seems counterintuitive to handle speed on the client externally from the plugin- especially to constantly `setConfig`

**Comment by christocracy** [comment]
What would be the name of these config option(s) in order to satisfy all the cases?

**Comment by christocracy** [comment]
The current calculator does this:
```obj-c
-(float) calculateDistanceFilter:(float)speed
{
    if (settings.disableElasticity == YES) {
        return settings.distanceFilter;
    }
    float newDistanceFilter = settings.distanceFilter;
    float roundedSpeed = (5.0 * floorf(fabsf(speed) / 5.0 + 0.5f));
    float multiplier = roundedSpeed / 5.0;
    if (multiplier < 1) { multiplier = 1; }
    newDistanceFilter = multiplier * settings.distanceFilter;
    return newDistanceFilter;
}
```
Basically, every 5 m/s change, another `distanceFilter` is added.

**Comment by christocracy** [comment]
Feel free to design your desired function in Javascript.  If it's acceptable, I can easily translate the result to Obj-c / Java.

**Comment by wbattel4607** [comment]
I'll see about whipping something up this weekend in JavaScript.

**Comment by christocracy** [comment]
I notice you're [maintaining a fork of the Mauron85](https://github.com/wbattel4607/react-native-background-geolocation/commit/36614f92b3e71c24cad11e69386fd16c103be24c) version.

Are you using that version or this one now?

**Comment by wbattel4607** [comment]
We're migration *from* Mauron85's repo. Our latest release build still uses his but our dev version has made the migration- except for modifying the server to handle the different location schema this repo posts. His repo has exponential elasticity.

**Comment by christocracy** [comment]
Yea, [I wrote that](https://github.com/christocracy/cordova-plugin-background-geolocation/commit/8949787b65c8a4134f8f6ac4613c315858200300) back in 2014.

**Comment by wbattel4607** [comment]
Huh. I didn't expect that. It served its purpose but this repo seems much more reliable.

**Comment by christocracy** [comment]
Comparing the scale of commits over a year (to this lib's private repo, where all commits land first) to Mauron85's, there's no comparison.  

**Transistorsoft**:  commits in 44/52 weeks
![](https://dl.dropboxusercontent.com/s/ose1dp3dz8ktse7/Screenshot%202017-09-14%2015.51.20.png?dl=1)

**Mauron 85**:  commits in 5/52 weeks.
![](https://dl.dropboxusercontent.com/s/7fwyf1txc4wliou/Screenshot%202017-09-14%2015.53.43.png?dl=1)

**Comment by wbattel4607** [comment]
Yeah... I was already sold when I tried this one for the first time yesterday.

**Comment by wbattel4607** [comment]
I think I've figured out how to go about this.

My suggestion is to add a new config option: `elasticityMultiple: [Float]` (Default: 1) where we can set how `distanceFilter` scales with speed. The `elasticityMultiple` can be any non-negative number.

The current functionality, if it had this config option, would have `elasticityMultiple: 1` as each speed increment increases the DF by DF • 1. Setting this to 2 would increase the DF by DF • 2.

For a visual explanation, this is how DF currently scales with speed:

![DF = 1](https://i.imgur.com/ADiRwv4.png)

Shown by the Locations/Minute column, you can see that while the distanceFilter scale is linear, the rate of location updates is not. For linear location update rates, the `elasticityMultiple` must be 2:

![DF = 2](https://i.imgur.com/VAwH1UU.png)

For navigation apps and similar, it would make sense to use an `elasticityMultiple` of 2 or less, but for some apps, mine included, a higher value would be better. Developers can set any non-negative value they please that will tailor the rate of location updates to their type of app.

![DF = 3](https://i.imgur.com/XPq4Q4R.png)

![DF = 5](https://i.imgur.com/BcqDX6y.png)

![DF = 10](https://i.imgur.com/g2bkUDG.png)

Implementing this in JavaScript would be very simple. If you'd like, I can write the function and post it here.

**Comment by christocracy** [comment]
It would be named `elasticityMultiplier`.

Yes, please provide sample js function

**Comment by wbattel4607** [comment]
This is the function you provided above that I have updated to incorporate `elasticityMultiplier`

```
-(float) calculateDistanceFilter:(float)speed
{
    if (settings.disableElasticity == YES) {
        return settings.distanceFilter;
    }
    float newDistanceFilter = settings.distanceFilter;
    float roundedSpeed = (5.0 * floorf(fabsf(speed) / 5.0 + 0.5f));
    float speedMultiplier = roundedSpeed / 5.0;
    if (speedMultiplier < 0) { speedMultiplier = 0; }
    newDistanceFilter = settings.distanceFilter + (settings.distanceFilter * settings.elasticityMultiplier * speedMultiplier)
    return newDistanceFilter;
}
```

I've also changed the name of the variable `speedMultiplier` (formerly `multiplier`) to decrease ambiguity with this new multiplier.

**Comment by christocracy** [comment]
Looks easy.  Prob an hour of work for both iOS and Android.

You haven't yet purchased a license?  This new feature will land first in the customers-only private repo.

It won't arrive here until I next push the latest stable release here.  Might be a while since I just pushed a release here a few days ago.

**Comment by wbattel4607** [comment]
I have not yet purchased a license but I plan to do so in the next week or so. We were trying it out on iOS and, based on how well it has worked, I expect us to commit with Android.

**Comment by wbattel4607** [comment]
I've purchased a license, and am looking forward to seeing this implemented at your convenience! :)

Feel free to close this issue at your leisure- I decided not to close it myself yet to avoid confusion.

**Comment by christocracy** [comment]
Great.  You should no longer use this repo then.  Use the private repo `react-native-background-geolocation-android` now.  You'll find `elasticityMultiplier` in `master`.
