### ISSUE TITLE
[QUESTION] Is there a way to detect mock locations with this module?

### ISSUE THREAD

**Issue by Jose4gg** [transistorsoft/react-native-background-geolocation#326]
I don't want that my final users use apps like Lockito or any other fake location. So, Is There a way on your package to do that?

**Comment by christocracy** [comment]
See [Location Data Schema](https://github.com/transistorsoft/cordova-background-geolocation/wiki/Location-Data-Schema) in Wiki.

```
{
    "timestamp":     [Date],     // <-- Javascript Date instance
    "event":         [String],   // <-- motionchange|geofence|heartbeat|providerchange
    .
    .
    .
    "mock":          [Boolean],  // <-- Present only when location came from a Mock provider
    .
    .
    .    
}
```

**Comment by Jose4gg** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/wiki/Location-Data-Schema I didn't see that in the react-native wiki, but now I'm testing and when I log the object I can't see any mock field.

**Comment by christocracy** [comment]
I just booted Lockito:
![](https://dl.dropboxusercontent.com/s/kohnqdwf3ix3tm4/Screenshot%202017-09-26%2010.09.58.png?dl=1)

**Comment by Jose4gg** [comment]
I can confirm, mock does not come when is `false` but yes, it's working, thanks!

**Comment by christocracy** [comment]
>"mock": [Boolean],  // <-- Present only when location came from a Mock provider

**Comment by Jose4gg** [comment]
Exactly 👍 my bad there, thanks so much!

**Comment by kriptonhaz** [comment]
I tried with One Plus Android 6.0.1 and there's no showing mock on the result, here is what I got

```
[Info] 03-23 15:23:30.501  8221  9563 I ReactNativeJS: '- [event] location: ', { battery: { level: 0.06, is_charging: true },

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   coords: 

03-23 15:23:30.501  8221  9563 I ReactNativeJS:    { heading: -1,

03-23 15:23:30.501  8221  9563 I ReactNativeJS:      speed: -1,

03-23 15:23:30.501  8221  9563 I ReactNativeJS:      accuracy: 17.1,

03-23 15:23:30.501  8221  9563 I ReactNativeJS:      longitude: 106.7994693,

03-23 15:23:30.501  8221  9563 I ReactNativeJS:      altitude: 44.9,

03-23 15:23:30.501  8221  9563 I ReactNativeJS:      latitude: -6.200157 },

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   odometer: '0.0',

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   timestamp: '2018-03-23T08:23:30.232Z',

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   uuid: '435a1ccd-9f0e-4969-b4c1-8367d3440b0c',

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   activity: { confidence: 100, type: 'still' },

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   is_moving: false,

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   extras: {},

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   provider: { status: 3, gps: true, enabled: true, network: true },

03-23 15:23:30.501  8221  9563 I ReactNativeJS:   event: 'providerchange' }
```

**Comment by willmcclellan** [comment]
I'm looking into the same thing with the iOS Simulator and not getting a `mock` property on location. Unless the simulator isn't classed as a mock provider but that's the behaviour I would expect.

**Comment by christocracy** [comment]
iOS has no such detection.  The Android API has specific mechanisms for mocking locations that iOS does not have.

If you want to detect if your app is running on a simulator, you can detect that via device-info.

**Comment by willmcclellan** [comment]
@christocracy That make sense, thanks for the fast reply 👍

**Comment by v1pu2** [comment]
> iOS has no such detection. The Android API has specific mechanisms for mocking locations that iOS does not have.
> 
> If you want to detect if your app is running on a simulator, you can detect that via device-info.

How to get faked location with device-info? can you plz describe more?

**Comment by christocracy** [comment]
> How to get faked location 

This is unclear:  you want to simulate your location *for testing* or you want to *detect* if your *Users* are using fake location?

>with device-info?

I don’t understand what you mean about this.  What kind of device info?
