### ISSUE TITLE
Geofence event can't launch iOS app if terminated

### ISSUE THREAD

**Issue by gchiacchio** [transistorsoft/react-native-background-geolocation#327]
## Your Environment
* Plugin version: 2.7.0
* Platform: iOS
* OS version: iOS 10.0, iOS 10.3.3
* Device manufacturer / model: iPhone 6, iPhone SE
* React Native version (`react-native -v`): 
react-native-cli: 2.0.1
react-native: 0.43.4
* Plugin config
```
        // 1.  Wire up event-listeners
        BackgroundGeolocation.on('geofence', this.onGeofence);

        // 2.  #configure the plugin (just once for life-time of app)
        BackgroundGeolocation.configure(
            {
                // Geolocation Config
                desiredAccuracy: 0,
                distanceFilter: 10,
                // Activity Recognition
                stopTimeout: 1,
                // Application config
                debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                // Allow the background-service to continue tracking when user closes the app.
                stopOnTerminate: false,
                startOnBoot: true // <-- Auto start tracking when device is powered-up.
            },
            state => {
                console.log('- BackgroundGeolocation is configured and ready: ', state.enabled);

                if (!state.enabled) {
                    // 3. Start tracking!
                    // Geofences-only mode
                    BackgroundGeolocation.startGeofences(state1 => {
                        console.log('- Start geofences: ', state1);
                    });
                }
            },
            () => console.log('set config success'),
            () => console.log('failed to setConfig')
        );
```
## Expected Behavior

After te geofence event is fired, the app should launch and execute the configured handler.

## Actual Behavior

The geofence event is fired but the app can't be launched.

## Steps to Reproduce

1. Configure a geofence
2. Simulate movement enough to fire the geofence event
3. Wait forever for the app to be launched

## Context

I'm trying to set up a geofence and launch a notification when conditions are met. (i.e. the geofence event is fired and the date matches a user selected list of dates/times).

## Debug logs

POST http://localhost:8082/create_session net::ERR_EMPTY_RESPONSE
ExceptionsManager.js:71 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8082/create_session'.
    at makeRequest (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:63480:18)
    at sendRequest (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:63503:20)
    at Object.createSession (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:63325:17)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:63018:41
    at loadModuleImplementation (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:109:5)
    at guardedLoadModule (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:70:12)
    at _require (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:54:60)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:62792:28
    at loadModuleImplementation (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:109:5)
    at guardedLoadModule (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:70:12)
reactConsoleErrorHandler @ ExceptionsManager.js:71
(anonymous) @ index.js:204
loadModuleImplementation @ require.js:173
guardedLoadModule @ require.js:125
_require @ require.js:109
(anonymous) @ index.js:104
loadModuleImplementation @ require.js:173
guardedLoadModule @ require.js:125
_require @ require.js:109
(anonymous) @ index.js:3
loadModuleImplementation @ require.js:173
guardedLoadModule @ require.js:125
_require @ require.js:109
(anonymous) @ index.js:5
loadModuleImplementation @ require.js:173
guardedLoadModule @ require.js:125
_require @ require.js:109
(anonymous) @ index.ios.js:3
loadModuleImplementation @ require.js:173
guardedLoadModule @ require.js:118
_require @ require.js:109
(anonymous) @ index.js:42
executeApplicationScript @ RNDebuggerWorker.js:1
t @ RNDebuggerWorker.js:1
ExceptionsManager.js:63 Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:125
reportFatalError @ error-guard.js:44
guardedLoadModule @ require.js:120
_require @ require.js:109
(anonymous) @ index.js:42
executeApplicationScript @ RNDebuggerWorker.js:1
t @ RNDebuggerWorker.js:1
RCTLog.js:38 Running application lifeXTApp ({
    initialProps =     {
    };
    rootTag = 1;
})
ExceptionsManager.js:63 Module AppRegistry is not a registered callable module (calling runApplication)
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:125
reportFatalError @ error-guard.js:44
guard @ MessageQueue.js:48
callFunctionReturnFlushedQueue @ MessageQueue.js:107
t @ RNDebuggerWorker.js:1
ExceptionsManager.js:71 Unhandled JS Exception: Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.
reactConsoleErrorHandler @ ExceptionsManager.js:71
logIfNoNativeHook @ RCTLog.js:38
__callFunction @ MessageQueue.js:244
(anonymous) @ MessageQueue.js:108
guard @ MessageQueue.js:46
callFunctionReturnFlushedQueue @ MessageQueue.js:107
t @ RNDebuggerWorker.js:1
ExceptionsManager.js:71 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)
reactConsoleErrorHandler @ ExceptionsManager.js:71
logIfNoNativeHook @ RCTLog.js:38
__callFunction @ MessageQueue.js:244
(anonymous) @ MessageQueue.js:108
guard @ MessageQueue.js:46
callFunctionReturnFlushedQueue @ MessageQueue.js:107
t @ RNDebuggerWorker.js:1

**Comment by christocracy** [comment]
There is no plugin issue here.  You seem to have a JavaScript exception according to your JavaScript log

**Comment by christocracy** [comment]
It looks like you built your app for Debug and your app is attempting to reconnect with the dev server when the geofence event relaunches your app but can’t communicate with it.

**Comment by gchiacchio** [comment]
So in order to launch the App from geofence events, it should be built for release then? I'll give it a try and let you know. Thanks.

**Comment by christocracy** [comment]
That's what I do when field-testing.

**Comment by gchiacchio** [comment]
Thanks, it worked in release.
