### ISSUE TITLE
Tracking stops when movement starts

### ISSUE THREAD

**Issue by jsyvanen** [transistorsoft/react-native-background-geolocation#329]
## Your Environment
* Plugin version: 2.9.4
* Platform: iOS
* OS version: 9.3.2
* Device manufacturer / model: Apple ng4j2zd/a (iPhone 6)
* React Native version (`react-native -v`): 0.47.2
* Plugin config: 
* `license: 'XXXXXXX',
    url: '${configuration.API_BASE_URL}/path/to/api',
    autoSync: true,
    desiredAccuracy: 0,
    distanceFilter: 5,
    preventSuspend: true,
    heartbeatInterval: 15,
    maxRecordsToPersist: 300,
    logMaxDays: 1,
    logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG`

## Expected Behavior

Tracking should continue seamlessly. 
## Actual Behavior

Tracking stops completely for ~ 2000 meters.
## Context

We do fleet tracking & management with the plugin and need continuous tracking locations in order to power our dashboards and internal systems. We have however struggled to avoid very large gaps in tracking locations during the stop-and-go movements of our couriers. We've tried several configs now. Once stopped the device can sometimes travel hundreds or even a few thousand meters before starting tracking again despite good network conditions.

We have been conducting tests recently to try and replicate this behaviour and indeed are able to go distances measured in Km (possibly indefinitely if we didn't stop) without tracking at all. The above ENV is from one phone in a 2 phone test where we had identical config of the plugin in both. One phone tracked seamlessly from walking onto a train platform, being stationary for just a moment, and getting on a train and moving a few Km (in good network coverage). The other phone (mentioned in the ENV) stopped tracking at the station and did not track until walking recommenced at another station over 2 Km away. The dataset from around the time of the tracking gap is here (see around 14:05:00 timestamp for the "gap"):

[bad_tracking.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1341657/bad_tracking.txt)

How do we prevent this?

More generally we would like any suggestions to keep the distances between tracking locations as close to `distanceFilter` values as possible (allowing of course for the speed elasticity feature), in particular in transitions between stationary and moving states of the device. 

Thanks in advance.

**Comment by tutts** [comment]
Also for reference, we've seen this in iOS 10.3.3 and 11.0.0 too. This is using the paid version of the plugin `react-native-background-geolocation-android`

Thanks!

**Comment by christocracy** [comment]
Please post logs from a device.

**Comment by jsyvanen** [comment]
These logs are from a period where we had a gap in tracking of ~ 2220 meters between `2017-09-29T08:04:06.979000` and `2017-09-29T08:07:30.978000`:

[tsoft_logs_no_tracking.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1345114/tsoft_logs_no_tracking.txt)

Thanks

**Comment by christocracy** [comment]
The results from `CMMotionActivity` thinks the device is `stationary` that whole time.

```
2017-09-29 08:04:23.991 ℹ️-[SOMotionDetector calculateMotionType:vectorSum:] motionActivity: CMMotionActivity @ 41556.140702,<startDate,2017-09-29 07:04:23 +0000,confidence,2,unknown,0,stationary,1,walking,0,running,0,automotive,0,cycling,0>
```

Show me the logs *before* this where the plugin entered stationary-mode.

The plugin doesn't fully rely upon `CMMotionActivityManager` to detect movement (it's just a secondary trigger).  The primary motion-detection trigger is the stationary-geofence around the last known location.

**Comment by jsyvanen** [comment]
Thanks for the info. Something to do with movement detection seems to fit the pattern of gaps which we see.

Attached are extended logs from before the gap. Before the few TL's we got prior to the gap in question there was another multi-km gap in the tracking during which many of the logs were recorded.

[bad_tracking_tsoft_extended.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1345878/bad_tracking_tsoft_extended.txt)

We have more data & logs from other examples if needed.

**Comment by christocracy** [comment]
Give me a date range(s) in log to look at.

**Comment by jsyvanen** [comment]
Take a look at between say `2017-09-29 07:36:53.804` and `2017-09-29T08:04:06.979000`. 

Between the latter TS ^^^ and `2017-09-29T08:07:30.978000` I didn't track for ~2200 km as I mentioned.

For reference: during the time of the generated logs I walked onto a train, got off a train, and got on another train. I got only sporadic TL's despite moving many Kms. I had good network coverage for at least 80+ % of the journey.

**Comment by christocracy** [comment]
Trains *can* be problematic.  They can act like Faraday Cages blocking network signals.

It’s obviously a big enough problem to attract [Siemens to pour R&D into it](https://m.siemens.com/en/press/pressreleases/pressrelease.php?detail=https://www.siemens.com/press/en/pressrelease/2016/mobility/pr2016060315moen.htm).

**Comment by christocracy** [comment]
I still don’t see your last stationary location in that log.  I want to see the last period where the device was moving (or booted) and entered stationary mode.

**Comment by jsyvanen** [comment]
You have everything from over 4 hours before the period in question -- is there no indication of what is wrong? Do you not see what you are looking for there? The device did track my walk to the train station, which is entirely contained in that 4 hr period.

Here are the full logs available from the device for the period:
[bad_tracking_tsoft_logs_full.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1346671/bad_tracking_tsoft_logs_full.txt)

Here are the tracking locations we received from the device over the AM hours of the 29th:
[bad_tracking_tsoft_coords.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1346673/bad_tracking_tsoft_coords.txt)

You can use the `meters_since_last` and `sec_since_last` in the tracking locations file to find the large gaps.

Regarding the possible faraday cage effects of trains: I doubt that to be a factor here for several reasons --> 1) It is an overground train in central London with 3g and 4g coverage nearly everywhere. One is easily able to stream videos and do many bandwidth intensive activities onboard. 2) I have regularly checked my google maps tracking and it keeps my "dot" moving with a fairly tight accuracy radius throughout the route where the plug-in took very sparse tracking locations. 

Thanks

**Comment by christocracy** [comment]
Location services are like a tap of water.  There is only one tap in the village (your phone).

All apps receive locations from the same tap, whether google maps or the plugin.  No app has a private tap with “better tasting water”.

The issue in your case is the automated “motion-detection”.  Your motion sensor on your device, for whatever reason, is reporting your device as “stationary”, aparrantly.  There’s little to do in that case, but test with a variety of devices.

**Comment by danhawkins** [comment]
So on the train motion detection may say you are stationary because relative to the train, you are. But the train is moving and distance is being covered, in this case surely there should be an override of motion detection, because you have travelled distance beyond the distance filter

**Comment by christocracy** [comment]
No, CMMotionActivityManager api should be smarter than that. It’s not just an accelerometer:  it’s fusing multiple sensors (eg gyroscope, magnetometer) into a machine-learning model.  This is a high level “black box” api which simply spits out answers.

You can google “CMMotionActivityManager train” for more info about this.

Anyway, like I said: motion-activity triggering is a secondary mechanism.  The primary mechanism is a “stationary geofence” around the last known position.

**Comment by christocracy** [comment]
Have you tested the devices in other scenarios (eg car, walking)?  Other trains?

**Comment by jsyvanen** [comment]
We have hundreds of couriers out in the field daily using bikes, scooters and cars. We see these jumps in tracking throughout the fleet. A few follow up questions: why does the stationary geofence not trigger tracking when moving beyond it in the case I have provided? Is there a config you can recommend to get rid of this issue?

**Comment by christocracy** [comment]
Geofence triggering is handled at the OS level.  It’s a black box.  The OS presumably uses WiFi / cell-tower change events to evaluate geofences.

There’s really no config that affects stationary geofence triggering, other than stationaryRadius, but the minimum stationaryRadius iOS will respond to is ~200 meters.

**Comment by christocracy** [comment]
Show me some mapping of these jumps?

Are you sending server Push requests to your fleet for communicating “orders”.  Server push is a great way to control the plugin, eg, when a guy is on a job, you could immediately trigger the plugin to tracking state (ie changePace(true)), increase stopTimeout, etc.

**Comment by danhawkins** [comment]
We have stopDetection disabled, and we are seeing these jumps happen, we disabled stopDetection because we did not want this ~200 m activation, but the changePace method could be something we could use. Should we have to though if we have stopDetection off?

**Comment by danhawkins** [comment]
In the config above stopDetection is enabled, what I meant is we tried with stopDetection disabled previously and still saw issues, if we turn it off should we stop seeing the gaps?

**Comment by christocracy** [comment]
>like I said: motion-activity triggering is a **secondary** mechanism. The primary mechanism is a “stationary geofence” around the last known position.

No, it will solve nothing.

**Comment by danhawkins** [comment]
How can we control that stationary geofence, like what if we just wanted to turn that off, can we? We had a native iOS version before react native where we just kept on tracking and had a time based rule to filter the data sent to the server, using a distance based rule would be even better, thats basically what we want to achieve with the plugin, but with the extra goodies like motion data, battery level etc.

**Comment by christocracy** [comment]
See #changePace and #pausesLocationUpdatesAutomatically.

Have you read every available config option?

**Comment by jsyvanen** [comment]
> Show me some mapping of these jumps?

<img width="1392" alt="screen shot 2017-10-02 at 10 14 21" src="https://user-images.githubusercontent.com/15344902/31072363-7a28e776-a75f-11e7-8b67-1cda8349ff69.png">

Journey shown in red. There is only one break in service for a tunnel near the middle of the journey where it says "Hampstead".

We'll test with `pausesLocationUpdatesAutomatically` today.

Could you confirm that my understanding is correct in the following scenario re: how the plugin should behave:

I am moving, and tracking every `distanceFilter` meters. I completely stop for a while, and then I start moving again. When will I receive the next location update?

- If I have `preventSuspend` enabled, the plugin will update my location on **either** the next update from `CMMotionActivityManager` or iOS reports that the stationary geofence has been breached. If `CMMotionActivityManager` fails to detect my movement the plugin waits for iOS to report the stationary geofence as breached (which is then subject to ~ 200 meter minimum geofence thumb-rule and/or any of the other idiosyncrasies of how the OS evaluates the geofences).

- If I have `pausesLocationUpdatesAutomatically` location will updated when I exceed `distanceFilter` meters from where I stopped.

Thanks.

**Comment by christocracy** [comment]
@jsyvanen That's one device.  Show me more.

**Comment by christocracy** [comment]
>If I have preventSuspend enabled, the plugin will update my location on either the next update 

No.  The plugin does is not involved with updating location in `heartbeat` event.

>or iOS reports that the stationary geofence has been breached. 

Yes.

>If I have pausesLocationUpdatesAutomatically

Imagine location-services is a light switch.  The switch is turned on in the following ways:
- Stationary geofence exit.
- `CMMotionActivityManager`
- Manually execute method:  `changePace(true)`

Now that the light is **ON**,  `pausesLocationUpdatesAutomatically: false` will prevent the light switch being turned off again when `CMMotionActivityManager` detects the device is `still`.  Location-services will stay on **forever** until you manually execute `changePace(false)`.

**Comment by jsyvanen** [comment]
Can post some more maps later. 

But for reference here is the same journey as my original map ^^^, but with `pausesLocationUpdatesAutomatically: false` in the config:

<img width="1177" alt="screen shot 2017-10-03 at 11 26 59" src="https://user-images.githubusercontent.com/15344902/31120883-f66da47e-a82d-11e7-84a3-58c4b780aefc.png">

This is the quality we need, so thank you for your help on that. Unfortunately I guess we have now turned off many of the battery saving features of the app. We'll be testing some wrappers around the plugin to try and initiate some battery savings from our side manually.

Before collecting our own data do you have any guidance on how much battery we could expect to save with `distanceFilter` set to (say) 15 instead of 5 (all else being equal)?

Thanks.

**Comment by christocracy** [comment]
If you use `pausesLocationUpdatesAutomatically: false`, you will have turned on location-services 24 hours / day.  If you do that, you'll kill the battery in *hours*.

You should be using server Push requests to re-configure the plugin only when a device is required to track so aggressively, like when a device is performing a delivery, and scaling back when the delivery is completed.
