### ISSUE TITLE
getCurrentPosition with error 100

### ISSUE THREAD

**Issue by twelvearrays** [transistorsoft/react-native-background-geolocation#33]
I have an iPhone 5 with No service I am using to test my app along with several beta tester with iPhone 5s. I do not receive an failure callback in the designated timeout.  I do however receive an error 100 randomly after this call anywhere between 1 minute and up to 8 minutes usually till indefinitely.  I have also written another simple location library that gets the current location of the device and that works.  Meaning that the GPS does have a current location.  Seems like the timeout for the error 100 isn't timing out?

BackgroundGeolocation.getCurrentPosition({
    persist: true,
    timeout: 10, // 30 second timeout to fetch location
    maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
    minimumAccuracy: 50, // Fetch a location with a minimum accuracy of `10` meters.
    }, function(location) {
    // This location is already persisted to plugin’s SQLite db.
    // If you’ve configured #autoSync: true, the HTTP POST has already started.
    console.log('- Current position received: ', location);
}, function(errorCode) {
    alert('An location error occurred: ' + errorCode + ' ');
  });

**Comment by christocracy** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/wiki/Error-Codes

I'm getting rid of the minimimAccuracy filtering

On Tuesday, November 24, 2015, twelvearrays <notifications@github.com>
wrote:

> I have an iPhone 5 with No service I am using to test my app along with
> several beta tester with iPhone 5s. I do not receive an failure callback in
> the designated timeout. I do however receive an error 100 randomly after
> this call anywhere between 1 minute and up to 8 minutes usually till
> indefinitely. I have also written another simple location library that gets
> the current location of the device and that works. Meaning that the GPS
> does have a current location. Seems like the timeout for the error 100
> isn't timing out?
>
> BackgroundGeolocation.getCurrentPosition({
> persist: true,
> timeout: 10, // 30 second timeout to fetch location
> maximumAge: 5000, // Accept the last-known-location if not older than 5000
> ms.
> minimumAccuracy: 50, // Fetch a location with a minimum accuracy of 10
> meters.
> }, function(location) {
> // This location is already persisted to plugin’s SQLite db.
> // If you’ve configured #autoSync: true, the HTTP POST has already started.
> console.log('- Current position received: ', location);
> }, function(errorCode) {
> alert('An location error occurred: ' + errorCode + ' ');
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/33>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Get rid of your minimumAccuracy

On Tuesday, November 24, 2015, twelvearrays <notifications@github.com>
wrote:

> I have an iPhone 5 with No service I am using to test my app along with
> several beta tester with iPhone 5s. I do not receive an failure callback in
> the designated timeout. I do however receive an error 100 randomly after
> this call anywhere between 1 minute and up to 8 minutes usually till
> indefinitely. I have also written another simple location library that gets
> the current location of the device and that works. Meaning that the GPS
> does have a current location. Seems like the timeout for the error 100
> isn't timing out?
>
> BackgroundGeolocation.getCurrentPosition({
> persist: true,
> timeout: 10, // 30 second timeout to fetch location
> maximumAge: 5000, // Accept the last-known-location if not older than 5000
> ms.
> minimumAccuracy: 50, // Fetch a location with a minimum accuracy of 10
> meters.
> }, function(location) {
> // This location is already persisted to plugin’s SQLite db.
> // If you’ve configured #autoSync: true, the HTTP POST has already started.
> console.log('- Current position received: ', location);
> }, function(errorCode) {
> alert('An location error occurred: ' + errorCode + ' ');
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/33>
> .
>


-- 
Snet form Gmail Mobile

**Comment by twelvearrays** [comment]
Let me know when you have an update with this removed.  Be happy to test. As always thanks for the quick response!

**Comment by christocracy** [comment]
Probably tonight

On Tuesday, November 24, 2015, twelvearrays <notifications@github.com>
wrote:

> Let me know when you have an update with this removed. Be happy to test.
> As always thanks for the quick response!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/33#issuecomment-159450528>
> .
>


-- 
Snet form Gmail Mobile

**Comment by twelvearrays** [comment]
I have noticed turning my wifi on or off forces the getCurrentPosition call to complete and return successfully.

**Comment by christocracy** [comment]
You definitely want to keep Wifi ON when attempting to track a user's
position.  Native geolocation (on any platform; iOS, Android) aggregates 3
sources together to achieve the best possible accuracy.

- GPS
- Wifi triangulation
- Cell-tower triangulation



On Wed, Nov 25, 2015 at 9:20 AM, twelvearrays <notifications@github.com>
wrote:

> I have noticed turning my wifi on or off forces the getCurrentPosition
> call to complete and return successfully.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/33#issuecomment-159620221>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by twelvearrays** [comment]
Good to know! I will put a check in my code if wifi is enabled.  Still get the weird timeout times with error 100 though even with wifi on. Thanks for the insight.

**Comment by christocracy** [comment]
The library currently throws out any received location having accuracy >
1000.  When it sees a low-accuracy location like this, it fires the error
code 100.

This merely means you're receiving poor-accuracy locations.  When I post
the latest version, you'll no longer see error code 100 -- you'll see
really poor accuracy locations instead.

On Wed, Nov 25, 2015 at 9:39 AM, twelvearrays <notifications@github.com>
wrote:

> Good to know! I will put a check in my code if wifi is enabled. Still get
> the weird timeout times with error 100 though even with wifi on. Thanks for
> the insight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/33#issuecomment-159625768>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by twelvearrays** [comment]
Ok sounds good! Look forward to the update.

**Comment by christocracy** [comment]
Try out my new [Android Demo App](https://play.google.com/store/apps/details?id=com.transistorsoft.rnbackgroundgeolocationsample)

**Comment by twelvearrays** [comment]
Did 0.1.2 get rid of minimumAccuracy?

**Comment by christocracy** [comment]
yes


On Fri, Nov 27, 2015 at 11:59 AM, twelvearrays <notifications@github.com>
wrote:

> Did 0.1.2 get rid of minimumAccuracy?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/33#issuecomment-160175514>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by twelvearrays** [comment]
Awesome! As always, great work and fast response! Thanks
