### ISSUE TITLE
App crashed on Android when adopting bk-geolocation

### ISSUE THREAD

**Issue by ZackCao** [transistorsoft/react-native-background-geolocation#333]
## Your Environment
* Plugin version: react-native-background-geolocation: 2.9.4
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Nexus 6P
* React Native version (`react-native -v`): 0.48.4
* Plugin config

## Expected Behavior

Should open my app

## Actual Behavior
 
when open my app with bk-geolocation installed, it briefly says "License validation failure, BkLocation is running on evaluation mode" and then crash.

## Steps to Reproduce

1. Just open my app. 
2.
3.
4.

## Context

Just  open my app, my app already installed react-native-background-geolocation following instructions and hasn't adopt it yet in any of my code

## Debug logs

[logcat.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1377637/logcat.txt)

**Comment by christocracy** [comment]
I see no crash in your logs.  The plugin looks happy in that log.

**Comment by christocracy** [comment]
If your app is crashing, just run $ adb logcat and copy the exception stack trace.

I don’t need to see megabytes worth of logs for that.

**Comment by ZackCao** [comment]
Thanks for the quick response. 
I put the google play services in build.gradle and the problem resolved:
