### ISSUE TITLE
Warnings on not implementing `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by Palisand** [transistorsoft/react-native-background-geolocation#336]
## Your Environment
* Plugin version: 2.9.4
* Platform: iOS 11
* OS version: OS X 10.12.6 (Sierra)
* Device manufacturer / model: Apple / iPhone 6S
* React Native version: 0.49.3
* Plugin config: default

## Expected Behavior
No warnings.

## Actual Behavior
The following warnings are reported:

> Module RNBackgroundFetch requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

> Module RNBackgroundGeolocation requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

## Steps to Reproduce
Add this module to an app using RN 0.49.+

## Context
Basic usage; just starting out with this module.

## Debug logs
NA (see Actual Behavior)

**Comment by christocracy** [comment]
I'm aware.  I received a pull-request at [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch/pull/54) earlier today.  This will be suppressed soon.

**Comment by christocracy** [comment]
Implemented in premium version.  Will arrive here with next stable release.
