### ISSUE TITLE
I want to send locations in bulk  at certain intervals

### ISSUE THREAD

**Issue by dbyilmaz** [transistorsoft/react-native-background-geolocation#339]
## Your Environment
* Plugin version: ^2.9.4
* Platform:  Android
* OS version: 7.1.1
* Device manufacturer / model: GM
* React Native version (`react-native -v`):  0.49.3
* Plugin config
            locationUpdateInterval: 5000,
            foregroundService: true,
            notificationTitle:"Title",
            notificationText:"Text",
            notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
            // Geolocation Config
            desiredAccuracy: 0,
            distanceFilter: 1,
            // Activity Recognition
            stopTimeout: 1,
            // Application config
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate:false,
            startOnBoot: true,        
            batchSync: true,    
            autoSync: false,        
            autoSyncThreshold: 5,
            url: 'https://myapi.execute-api.eu-central-1.amazonaws.com/dev/test',
            httpTimeout: 3000,
            heartbeatInterval: 60,
            schedule: [
                '2-7 9:16-17:00',  // Mon-Fri: 9:00am to 5:00pm
            ]

## Expected Behavior
The heartbeat is running when the application terminated.

## Actual Behavior

The heartbeat is running while the application is in the foreground. But it is not running when the application terminated.
## My Code

```
  componentWillMount(){
        console.log(AppState.currentState);
        BackgroundGeolocation.configure({
            locationUpdateInterval: 5000,
            foregroundService: true,
            notificationTitle:"Title",
            notificationText:"Text",
            notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
            // Geolocation Config
            desiredAccuracy: 0,
            distanceFilter: 1,
            // Activity Recognition
            stopTimeout: 1,
            // Application config
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate:false,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
            batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: false,         // <-- [Default: true] Set true to sync each location to server as it arrives.
            autoSyncThreshold: 5,
            url: 'myapi.execute-api.eu-central-1.amazonaws.com/dev/test',
            httpTimeout: 3000,
            heartbeatInterval: 60,
            schedule: [
                '2-7 9:16-17:00',  // Mon-Fri: 9:00am to 5:00pm
            ]
        }, (state) => {

            BackgroundGeolocation.startSchedule(function() {
                BackgroundGeolocation.start();
            });
            if(state.enabled){
            BackgroundGeolocation.on('heartbeat',  function(params) {
                BackgroundGeolocation.sync((success) => {console.log(success)}, (fail) => {console.log(fail)});
                console.log('- hearbeat');
            });
        });

    }
```
## Debug logs

`10-19 15:49:13.869 29498  1366 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 15:49:22.719 29498  1366 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (54%)
10-19 15:49:22.740 29498  1366 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 15:49:31.623 29498  1366 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (85%)
10-19 15:49:31.666 29498  1366 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 15:49:52.304 29498  1457 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:50:52.477 29498  1542 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:51:52.652 29498  1651 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:52:38.670 29498  1733 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (83%)
10-19 15:52:38.697 29498  1733 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 15:52:52.799 29498  1746 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:54:11.347 29498  1837 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:54:52.864 29498  1866 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:55:41.165 29498  1920 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
10-19 15:55:41.183 29498  1920 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 15:56:23.287 29498  1986 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:56:52.907 29498  2022 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:58:23.280 29498  2098 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 15:58:45.129 29498  2181 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
10-19 15:58:45.146 29498  2181 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 15:59:35.218 29498  2289 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 16:00:11.164 29498  2355 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 16:00:51.983 29498  2387 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 16:01:45.852 29498  2463 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
10-19 16:01:46.025 29498  2463 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 16:02:10.697 29498  2515 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
10-19 16:02:47.328 29498  2564 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
10-19 16:02:47.353 29498  2564 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 16:02:48.617 29498  2564 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
10-19 16:02:48.644 29498  2564 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-19 16:03:06.019 29498  2654 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
`

**Comment by mishravarun** [comment]
But will the ```location``` callback work?
```
BackgroundGeolocation.on('location',  function(params) {
                console.log('- new location');
            });
```

**Comment by christocracy** [comment]
Imagine all your Javascript is written on a chalkboard.

When your Android app is terminated, **ALL** your javascript is erased.  It is no longer running.  None of it.

**Comment by christocracy** [comment]
Just set `autoSync: true`

**Comment by dbyilmaz** [comment]
@christocracy  there is no other possibility?
