### ISSUE TITLE
Determine if GPS is allowed

### ISSUE THREAD

**Issue by normanrz** [transistorsoft/react-native-background-geolocation#34]
Is there a way to quickly determine if GPS is available to use?
Something like [CLLocationManager/locationServicesEnabled](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/clm/CLLocationManager/locationServicesEnabled) and [CLLocationManager/authorizationStatus](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/clm/CLLocationManager/authorizationStatus)?

**Comment by christocracy** [comment]
If they were available, what would you want to do with them?

On Wednesday, November 25, 2015, Norman Rzepka <notifications@github.com>
wrote:

> Is there a way to quickly determine if GPS is available to use?
> Something like CLLocationManager/locationServicesEnabled
> <https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/clm/CLLocationManager/locationServicesEnabled>
> and CLLocationManager/authorizationStatus
> <https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/clm/CLLocationManager/authorizationStatus>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/34>
> .
>


-- 
Snet form Gmail Mobile

**Comment by normanrz** [comment]
I have an app where the user starts and stops tracking explicitly. I want to give the user feedback on the availability of the GPS status as soon as they enter the app (ie. before they try to start tracking).

**Comment by christocracy** [comment]
Ok, those look easy enough to implement.

**Comment by cosmith** [comment]
+1 on this!

**Comment by gunters63** [comment]
+1 on this.

**Comment by ecjs** [comment]
Would love to see this! +1

**Comment by christocracy** [comment]
What do you hope to did with this information?  Why GPS specifically?  This
isn't even possible on iOS.  I wonder if you're misusing the word "GPS"
instead of "location services"?


On Sunday, April 3, 2016, Mark Harrell <notifications@github.com> wrote:

> Would love to see this! +1
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/34#issuecomment-205036632>
>


-- 
Snet form Gmail Mobile

**Comment by ecjs** [comment]
^^ For me, that is definitely the case. Location services.  Although to achieve this I ended up using this:
https://github.com/joshblour/react-native-permissions

**Comment by ecjs** [comment]
Basically, I wanted some user feedback in case they accidentally denied permissions..I have already seen a few users to this and wonder why the app wasn't recording location :sob:

**Comment by christocracy** [comment]
Just listen to the plugin's location errorCallback.  You're provided an
error code, one of which means "location access denied"

On Sunday, April 3, 2016, Mark Harrell <notifications@github.com> wrote:

> Basically, I wanted some user feedback in case they accidentally denied
> permissions..I have already seen a few users to this and wonder why the app
> wasn't recording location [image: :sob:]
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/34#issuecomment-205039566>
>


-- 
Snet form Gmail Mobile

**Comment by ecjs** [comment]
Ahh, that works for me.  Thanks!

**Comment by christocracy** [comment]
See wiki for error codes
https://github.com/transistorsoft/react-native-background-geolocation/wiki/Error-Codes


On Sunday, April 3, 2016, Mark Harrell <notifications@github.com> wrote:

> Ahh, that works for me. Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/34#issuecomment-205039748>
>


-- 
Snet form Gmail Mobile

**Comment by ecjs** [comment]
Lets say we get an error code back of 1, we know that permission is denied, and we change some state that identifies that the users permission is denied.  Once the user changes their permissions to allow access...how would you recommend accessing that? 

My thoughts are:
Change the permission state to false on error code 1.
If the current state is false, and we get a positive location change to true.

Seems basic enough, my only thoughts here are that we may not get a user location if they are stationary.

**Comment by christocracy** [comment]
This is implemented now by listening to `providerchange` event.
