### ISSUE TITLE
Geolocation after application removed from recently

### ISSUE THREAD

**Issue by doniyor2109** [transistorsoft/react-native-background-geolocation#341]
After app closed and removed from recently, I changed location with fake location.

## Your Environment
* Plugin version: 2.9.4
* Platform: Android
* OS version: API 23
* Device manufacturer / model: Xiomi
* React Native version (`react-native -v`):0.44
* Plugin config
![carbon](https://user-images.githubusercontent.com/14192979/31819660-133869f4-b5b7-11e7-8c3b-a77036c1411e.png)

## Expected Behavior

App should send location information to server
## Actual Behavior

Nothing is sent

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
The plugin doesn't care if the location changes from simulation.  If the device is sitting still, the plugin *isn't listening*.

See [Debugging Android](https://github.com/transistorsoft/react-native-background-geolocation-android/wiki/Debugging#android-1)

- When the plugin receives on of the "moving" activities (e.g.: "on_foot", "in_vehicle") location-updates will be initiated.

- You can easily simulate the on_foot state by **shaking the device vigorously** until the next #activityRecognitionInterval ticks over). You'll hear the sound "doodly-doo" when location-updates are initiated.
