### ISSUE TITLE
Query periodically whether user is STILL

### ISSUE THREAD

**Issue by lashae** [transistorsoft/react-native-background-geolocation#342]
We are going to implement `react-native-background-geolocation` for a fleet tracking app. We have decided to use it in `autoSync="true"` mode. Library is supposed to send location changes to our server. So far so good.

However, there exists one issue. When user stops somewhere on his track, since location is not changing, server doesn't know why it doesn't receive any location updates: Is it due to user is not moving or a network issue is present and updates will come as soon as network is available.

To distinguish this ambiguity, "we dream to" query `react-native-background-geolocation` to learn the active activity type of the user "at that moment". 

Say, library fetched the last location at 03:00PM, sent it to our server and user stopped moving. We can implement a periodic task (out of the scope of this react-native-background-geolocation library) which runs every 5 minutes and talk to `react-native-background-geolocation` somehow, grab the active activity type and if user is STILL (not moving) it will call one of our API's that **user last location has not changed**. 

This flow will enable us to aggregate the user stop-points with how much time he spent there (ie. user spent his 53 minutes at this geolocation point), on our server and other users will have the ability to see this data **realtime** on their dashboards. 

However, reading through the docs multiple times we couldn't find the exact point to use in "react-native-background-geolocation".

First question: Is it possible to accomplish what I have outlined above with react-native-background-geolocation?

Second one: If it is possible; will querying active activity type involve GPS interaction under the hoods which will drain user's battery?

And last one: Does it sound the correct way of handling the "aggregation of user stop-points with how much time spent there"? Or is there a better way to implement this requirement by using this library?

Thanks in advance

**Comment by christocracy** [comment]
>To distinguish this ambiguity, "we dream to" query react-native-background-geolocation to learn the active activity type of the user "at that moment".

Listen to [`activitychange`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#activitychange) event.

When device becomes stationary, the [`motionchange`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#motionchange)  Event will fire.  The posted location will contain the meta-data `{"event":"motionchange", "is_moving": false}`

You might want to read about the [`heartbeat`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#heartbeat) Event.

**Comment by lashae** [comment]
Since `activitychange` is tied to a Javascript callback, I suppose receiving activitychange events and sending to server is impossible when app is terminated. Am I wrong?

If it is so, is it possible to send these activity change events to the server via your library like or with-in `autosync`?

**Comment by christocracy** [comment]
There is an experimental way:
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/RNBackgroundGeolocationEventReceiver.java#L27

**Comment by lashae** [comment]
What should I understand from being "experimental"? Does it mean it is not (enough) tested to be stable? Or should I understand, "experiment with this intent filter"?

**Comment by christocracy** [comment]
Try it

**Comment by lashae** [comment]
With your quick and prompt responses, this github issue turned out to be a delightful conversation. We will definitely go with it. Keep up the good and passionate work Chris! 

Greetings from Turkey.

**Comment by christocracy** [comment]
If you haven’t yet read the Philosophy of Operation in the wiki, do so.
