### ISSUE TITLE
Can’t see tracking data 

### ISSUE THREAD

**Issue by alamrezoanul** [transistorsoft/react-native-background-geolocation#344]
Can’t see tracking data in tracker.transistorsoft.com

**Comment by christocracy** [comment]
This plugin is not directly involved with `tracker.transistorsoft.com`.  It's just the [demo app](https://github.com/transistorsoft/rn-background-geolocation-demo) which is configured to post locations to my test-server.

This plugin knows nothing of `tracker.transistorsoft.com`.

If you wish to `configure` the plugin to post locations to my test-server, you must configure the `#params` config as [shown in the demo app](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/components/lib/BGService.js#L212), supplying a custom `company_token` of your choice.

Then you would browse to `http://tracker.transistorsoft.com/company_token`

This is purely up to you.  This has nothing at all to do with the plugin.

**Comment by christocracy** [comment]
Or you simply install the Demo app and execute `$npm run open` as [documented at the demo repo](https://github.com/transistorsoft/rn-background-geolocation-demo#testing-server)

**Comment by alamrezoanul** [comment]
Let me check. Btw thank you!
-- 
Sincerely,
Rezoanul Riad.
(Please excuse my brevity & typo as it is from mobile device)

**Comment by alamrezoanul** [comment]
Following error I get when I use the command "$ npm run open" ...

sh: babel-node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! RNBackgroundGeolocationSample@2.9.4 open: `babel-node scripts/openConsole.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the RNBackgroundGeolocationSample@2.9.4 open script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by christocracy** [comment]
If you’re having problems with demo app, post an issue there.

**Comment by alamrezoanul** [comment]
done!
