### ISSUE TITLE
Temporary license for Android

### ISSUE THREAD

**Issue by SkyzohKey** [transistorsoft/react-native-background-geolocation#348]
Hey guy,

Thanks for the epic effort you put in that awesome library. I'm using it for a company app that tracks moves and driving speed of technicians (car is furnished by the company) and checks if the technician got to the client dispatchers tell them to. Also to check if max speed authorized on the road wasn't overpassed.

I worked on the app for 2 months now and it's time to show a demo to the CEO of the company. Problem: I don't have a license nor the monney to pay one. Company is willing to pay that license if I can prove them that the application works fine (which it does in my tests, all done in DEV mode).

So my question here is : Would it be possible to get a "temporary license" for 1 month, during the test phase after what you revoke the license and the company buy one from you ? It would really help me to finish and deploy the app while you would be paid too.

You can contact me at skyzohkey@protonmail.com or via Wire; SkyzohKey

Thanks in advance for the consideration, didn't find a better place to ask this, sorry if I didn't respected the issue template but this is not a bug report nor a feature request.

**Comment by christocracy** [comment]
Sorry, not possible to issue temp keys.

Build a DEBUG apk and email it or place on server for others to click/install.

**Comment by SkyzohKey** [comment]
Yep but the debug apk contains debug info + is not available if the packager is not running, etc. :x

**Comment by christocracy** [comment]
https://stackoverflow.com/a/36961021

**Comment by SkyzohKey** [comment]
Yep but the issue here is that I'm using CodePush to handle the bundle location :x

**Comment by SkyzohKey** [comment]
@christocracy Up? Cannot you revoke the license yourself once the test month is passed? Almost 3 months of development and the app is not demoable without a license. :/

It would be really nice, and you can be assured to get paid then for the license guy :x

**Comment by christocracy** [comment]
No, licenses cannot be revoked.

**Comment by SkyzohKey** [comment]
@christocracy Oh, I see :/
