### ISSUE TITLE
App does not send location information after closing and removing from recenlty

### ISSUE THREAD

**Issue by doniyor2109** [transistorsoft/react-native-background-geolocation#350]
## Your Environment
* Plugin version:2.9.4
* Platform: iOS and Android
* OS version: Android API 23 and IOS 10
* Device manufacturer / model: Xiomi and Apple
* React Native version (`react-native -v`):  0.44.2
* Plugin config
```
{
      // Geolocation Config
      desiredAccuracy: 0,
      distanceFilter: 100,
      preventSuspend: true,
      heartbeatInterval: 200,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      forceReloadOnBoot: true,
      foregroundService: true,
      // HTTP / SQLite config
      url: `${API_URL}${moduleSync}${query}`,
      batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        'X-FOO': 'bar'
      },
      params: {               // <-- Optional HTTP params
        'auth_token': 'maybe_your_server_authenticates_via_token_YES?'
      }
    }
```

## Expected Behavior

After closing app and removing it from recently tasks, app should send location information after moving 100 meters.
## Actual Behavior

Phone does not send any location information after moving 100 meters.

**Comment by christocracy** [comment]
Have you tried this in the iOS simulator?
Are you overerving logs.

Yes, it does work.  You’re doing something wrong.

**Comment by sirstevensu** [comment]
+1
i have same issue

**Comment by christocracy** [comment]
Logs

**Comment by doniyor2109** [comment]
I have tested it on Iphone 6 device also. I realized that I did not turned on Background permission to Always in Iphone settings. But when I did that it started to track but it does not track all location that phone is moved. 
I have attached track image in our app. It tracks correctly but you can see from image, the location between 16:14 and 16:23  is not tracked.

![map1](https://user-images.githubusercontent.com/14192979/32566783-e15d0fc4-c4da-11e7-869f-31b804f98d4a.jpg)
![map2jpg](https://user-images.githubusercontent.com/14192979/32566785-e310b050-c4da-11e7-8b5c-e13c82d3a1ac.jpg)

**Comment by christocracy** [comment]
Your battery is below 50%.  Your OS may have engaged power management, disabling some services.

Check your power management settings:
- Settings -> Battery -> Power Saving Mode
- Settings -> Battery -> Battery Optimization

**Comment by doniyor2109** [comment]
But as you can see from attached images battery percentages 6700% means(67%) and 6800% means (68%)

**Comment by doniyor2109** [comment]
But as you can see from attached images battery percentages 6700% means(67%) and 6800% means (68%)

**Comment by christocracy** [comment]
Battery:  44%
![](https://dl.dropboxusercontent.com/s/t8ffhuqivz0p5o8/Screenshot%202017-11-08%2013.37.28.png?dl=1)

There's really little to speculate about with images alone.  You need to provide corresponding logs.

**Comment by doniyor2109** [comment]
The image shows the history of location of another phone from my application. How can I get logs for you?

**Comment by christocracy** [comment]
See the Wiki [Debugging](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging)

**Comment by doniyor2109** [comment]
I have used emailLog method and this is the mailed log

[background-geolocation.log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/1455157/background-geolocation.log.gz)

**Comment by doniyor2109** [comment]
I used emailLog method and this is the mailed log

[background-geolocation.log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/1455162/background-geolocation.log.gz)

**Comment by christocracy** [comment]
What particular time are interested in from that log?

**Comment by doniyor2109** [comment]
This log is taken from android device. My phone. Today 08.11.2017, is not tracked yet.

**Comment by doniyor2109** [comment]
I am interested for Today

**Comment by christocracy** [comment]
Is there a problem which occurred within that log?

**Comment by doniyor2109** [comment]
I could not understand logs and could not find the problem

**Comment by christocracy** [comment]
What time in the logs corresponds to the time period where you experienced a tracking problem?

**Comment by doniyor2109** [comment]
From 13:00 until 22:00

**Comment by christocracy** [comment]
Why are you still configuring this:
```
"params": {
    "auth_token": "maybe_your_server_authenticates_via_token_YES?"
  },
  "headers": {
    "X-FOO": "bar"
  },
```
Those are just supposed to be *example* data.  You not actually supposed to use that.

**Comment by doniyor2109** [comment]
Yes, the application is not fully on production that is why I have not refactored yet

**Comment by christocracy** [comment]
You have 3 days worth of logs here.  `13:00-22:00` on *which day*?

**Comment by doniyor2109** [comment]
For 08.11.2017

**Comment by christocracy** [comment]
```
11-08 13:41:05.362 INFO [HttpService createRequest] 
  🔵  HTTP POST batch (2)
11-08 13:40:43.373 WARN [HttpService$a onFailure] 
  ⚠️  Response: 0, Hostname kasper.uz not verified:
    certificate: sha256/rmLuC7tdCPlarTlIURLZKijzNi0dVp4UcylyWqmwRLs=
    DN: CN=*.wiut.uz,OU=Domain Control Validated
    subjectAltNames: [*.wiut.uz, wiut.uz]
.
.
.
11-08 13:43:01.501 WARN [HttpService$a onFailure] 
  ⚠️  Response: 0, failed to connect to kasper.uz/83.69.138.253 (port 443) after 10000ms: isConnected failed: ETIMEDOUT (Connection timed out)
.
.
.
11-08 13:43:50.925 WARN [SingleLocationRequest finish] 
  ⚠️  timeout: 1002
11-08 13:43:51.038 WARN [TSLocationManager onLocationTimeout] 
  ⚠️  TSLocationManager received location timeout
11-08 13:43:51.106 WARN [BackgroundGeolocation _onLocationError] 
  ⚠️  Location error: 408
.
.
.
11-08 13:45:22.975 WARN [SingleLocationRequest finish] 
  ⚠️  timeout: 1003
11-08 13:45:23.054 WARN [TSLocationManager onLocationTimeout] 
  ⚠️  TSLocationManager received location timeout
11-08 13:45:23.184 WARN [BackgroundGeolocation _onLocationError] 
  ⚠️  Location error: 408
.
.
.
11-08 13:51:00.925 WARN [HttpService$a onFailure] 
  ⚠️  Response: 0, Unable to resolve host "kasper.uz": No address associated with hostname

```

**Comment by doniyor2109** [comment]
Yes, I went to study and connected to their wifi. Their proxy did not allow to access our domain.

**Comment by christocracy** [comment]
And mysteriously, it looks like the OS decided to terminate the background-service:
```
11-08 14:10:04.667 WARN [LocationService onHandleIntent] 
  ⚠️  LocationService found nobody to talk to.  Stopping...
```

**Comment by doniyor2109** [comment]
What do you think, why it could happen?

**Comment by christocracy** [comment]
Memory pressure from other apps.

**Comment by doniyor2109** [comment]
I have used only one application during that time. It was for chatting only. I have 2 GB RAM in my phone. It takes 300 MB of memory. There was 400 MB memory free.

**Comment by doniyor2109** [comment]
What do you advice in this situation. App should track all movement of phone otherwise our clients do not use this app

**Comment by christocracy** [comment]
I suggest you build the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo) onto this device and attempt to reproduce the problem why *my* code on *your* device.

**Comment by doniyor2109** [comment]
I did not understand: why my code on your device?

**Comment by christocracy** [comment]
Just go [here](https://github.com/transistorsoft/rn-background-geolocation-demo) and build my sample app onto your device and attempt to reproduce the problem.

**Comment by doniyor2109** [comment]
I have built demo application as you told and tested today from home to work. I have installed it yesterday at night. I left home about 11:00 and arrived about 11:56 to work. As you can see through my history it did not track location between my home and work. It started tracking when I turned on internet and opened your demo application. I have posted link for my phone's bg-console.
http://bg-console.herokuapp.com/1d69e670?device=ReactNative-392d2acea5650bfb&end=2017-11-9&start=2017-11-9%202%3A30

**Comment by christocracy** [comment]
send me the corresponding logs from SampleApp.

**Comment by doniyor2109** [comment]
How can I get logs from demo app?

**Comment by christocracy** [comment]
See settings screen.  There's an [Email Log] button along with text input for email address.

**Comment by christocracy** [comment]
Try installing on another device.  I think your issues are device-specific.

**Comment by doniyor2109** [comment]
Hello
We have tested your library on other phones recently. It works on IOS devices but it does not track sometimes however it does not work on android devices. We have installed our application to 3 android phones. They are Huawei CUN-U29, Samsung Galaxy J3 and Samsung GT 9192. their configuration were same as mentioned above. When devices are moved for longer distance, no request is coming to our server. I think the issues is not device specific.

**Comment by doniyor2109** [comment]
Is there any difference with private and public library. We have used public library with licence key.

**Comment by christocracy** [comment]
The private version is merely latest updates.

- You need to provide logs of each device.
- Ensure device settings->location is set to High Accuracy.

**Comment by doniyor2109** [comment]
Yes all phones had "High Accuracy" mode.
Here are their logs:
[background-geolocation (8).log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/1488754/background-geolocation.8.log.gz)
[background-geolocation (9).log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/1488755/background-geolocation.9.log.gz)
[background-geolocation (10).log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/1488756/background-geolocation.10.log.gz)
[background-geolocation (11).log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/1488757/background-geolocation.11.log.gz)

**Comment by doniyor2109** [comment]
Right
Here is log which I have moved my device
[background-geolocation.log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/1502355/background-geolocation.log.gz)

**Comment by christocracy** [comment]
You have 3 days of logs in that file.  What particular time interval are you interested in?

**Comment by doniyor2109** [comment]
I have walked for 3 days. You can choose any of them

**Comment by christocracy** [comment]
I see plenty of happy tracking there.

**Comment by christocracy** [comment]
Let me know what time interval you're interested in.

**Comment by doniyor2109** [comment]
Let's test today, from 9am untill now

**Comment by doniyor2109** [comment]
Our server received only 4 requests between 23:00 and 23:50. It sent locations only when I opened application

**Comment by christocracy** [comment]
```
11-23 21:44:07.056 WARN [LocationService onHandleIntent] 
  ⚠️  LocationService found nobody to talk to.  Stopping...  <-- Service was killed by OS
.
.
.
11-24 23:02:02.203 INFO [Sensors print] 
```

**Comment by doniyor2109** [comment]
It stopped only at 21:44:07?

**Comment by doniyor2109** [comment]
How about other times of day?

**Comment by christocracy** [comment]
You know you can look at your log too.

**Comment by doniyor2109** [comment]
I tried a lot configuring your library with our application, but still it doesn't work.
We have decided not to use your library and android license. Can you give back the money we have paid?

**Comment by christocracy** [comment]
This is not the place to discuss refunds.

**Comment by doniyor2109** [comment]
I have looked at logs, it sent location information only when application is opened

**Comment by doniyor2109** [comment]
Can we revoke the licence?

**Comment by christocracy** [comment]
Email me.
