### ISSUE TITLE
Detect what user chose, when prompted with "Always" and "When in use"

### ISSUE THREAD

**Issue by deehuey** [transistorsoft/react-native-background-geolocation#359]
Hey there! 

We want to respect our users' decision wether they choose to allow us to use the app in the background, or not. 

Unfortunately, if they choose "Only when in use." (on ios anyways), every time they re-open the application (And my BackgorundGeolocation.start() gets triggered, unless this is where my problem is, and I need to only call .start() once in the app), then it prompts them with locationAuthorizationAlert settings config. I'd like to just ignore this pop-up entirely, and only use it in use if that's what my users want. (But also want 'always' if they allow it.)

Essentially I'd need to know what they chose, but can't seem to find that.

Sorry for ignoring the template, this isn't a bug, simply a question.

**Comment by christocracy** [comment]
See providerchange event.

**Comment by deehuey** [comment]
Fantastic! Documentation made this sound like when they manually change it, but this is what i was looking for ! :)
