### ISSUE TITLE
Getting location to work when app is killed

### ISSUE THREAD

**Issue by cosmith** [transistorsoft/react-native-background-geolocation#36]
Hi,

Everything seems to be working fine on Android but I can't figure out how to make my app keep track of the position after it has been killed (double press home + swipe). Is it possible or am I mistaken? I couldn't get it to work either on device nor in the emulator with "Freeway drive".

This is my initialization code:

```js
var startBgGeoloc = function () {
    Storage.getUserProperty("token").then(token => {
        var options = {
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.

            // common
            desiredAccuracy: 10,
            distanceFilter: 100,
            stopOnTerminate: false,
            activityRecognitionInterval: 10000,
            stopTimeout: 2, // 2 minutes

            // iOS
            stationaryRadius: 100, // restart tracking after the user has moved 100m
            activityType: "AutomotiveNavigation",
            useSignificantChangesOnly: false,

            // Android
            startOnBoot: true,
            locationUpdateInterval: 5 * 60 * 1000,
            fastestLocationUpdateInterval: 60 * 1000,
            forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
            forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
            forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)

            // HTTP / SQLite config
            url: Server.SERVER_URL + "/tracking-locations/",
            batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
            maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin"s SQLite database when HTTP fails
            headers: {
                "Authorization": `Token ${token}`
            },
            params: {
            }
        };

        BackgroundGeolocation.configure(options);
        BackgroundGeolocation.setOptions(options);

        BackgroundGeolocation.start(() => {
            Log.debug("[BackgroundGeolocation] started successfully");

            // Fetch current position
            BackgroundGeolocation.getCurrentPosition({timeout: 30}, (location) => {
                Log.debug("[BackgroundGeolocation] received current position: ", JSON.stringify(location));
            }, (error) => {
                alert("Location error: " + error);
            });
        });
    });
};
```

**Comment by christocracy** [comment]
stopOnTerminate: false

You need to boot the app with that setting false

On Thursday, November 26, 2015, Corentin Smith <notifications@github.com>
wrote:

> Hi,
>
> Everything seems to be working fine on Android but I can't figure out how
> to make my app keep track of the position after it has been killed (double
> press home + swipe). Is it possible or am I mistaken? I couldn't get it to
> work either on device nor in the emulator with "Freeway drive".
>
> This is my initialization code:
>
> var startBgGeoloc = function () {
>     Storage.getUserProperty("token").then(token => {
>         var options = {
>             debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
>
>             // common
>             desiredAccuracy: 10,
>             distanceFilter: 100,
>             stopOnTerminate: false,
>             activityRecognitionInterval: 10000,
>             stopTimeout: 2, // 2 minutes
>
>             // iOS
>             stationaryRadius: 100, // restart tracking after the user has moved 100m
>             activityType: "AutomotiveNavigation",
>             useSignificantChangesOnly: false,
>
>             // Android
>             startOnBoot: true,
>             locationUpdateInterval: 5 * 60 * 1000,
>             fastestLocationUpdateInterval: 60 * 1000,
>             forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
>             forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
>             forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)
>
>             // HTTP / SQLite config
>             url: Server.SERVER_URL + "/tracking-locations/",
>             batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
>             autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
>             maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin"s SQLite database when HTTP fails
>             headers: {
>                 "Authorization": `Token ${token}`
>             },
>             params: {
>             }
>         };
>
>         BackgroundGeolocation.configure(options);
>         BackgroundGeolocation.setOptions(options);
>
>         BackgroundGeolocation.start(() => {
>             Log.debug("[BackgroundGeolocation] started successfully");
>
>             // Fetch current position
>             BackgroundGeolocation.getCurrentPosition({timeout: 30}, (location) => {
>                 Log.debug("[BackgroundGeolocation] received current position: ", JSON.stringify(location));
>             }, (error) => {
>                 alert("Location error: " + error);
>             });
>         });
>     });
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/36>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Wait, are you talking about iOS?

iOS needs to travel some distance before it triggers again

On Thursday, November 26, 2015, Corentin Smith <notifications@github.com>
wrote:

> Hi,
>
> Everything seems to be working fine on Android but I can't figure out how
> to make my app keep track of the position after it has been killed (double
> press home + swipe). Is it possible or am I mistaken? I couldn't get it to
> work either on device nor in the emulator with "Freeway drive".
>
> This is my initialization code:
>
> var startBgGeoloc = function () {
>     Storage.getUserProperty("token").then(token => {
>         var options = {
>             debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
>
>             // common
>             desiredAccuracy: 10,
>             distanceFilter: 100,
>             stopOnTerminate: false,
>             activityRecognitionInterval: 10000,
>             stopTimeout: 2, // 2 minutes
>
>             // iOS
>             stationaryRadius: 100, // restart tracking after the user has moved 100m
>             activityType: "AutomotiveNavigation",
>             useSignificantChangesOnly: false,
>
>             // Android
>             startOnBoot: true,
>             locationUpdateInterval: 5 * 60 * 1000,
>             fastestLocationUpdateInterval: 60 * 1000,
>             forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
>             forceReloadOnMotionChange: false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
>             forceReloadOnGeofence: false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)
>
>             // HTTP / SQLite config
>             url: Server.SERVER_URL + "/tracking-locations/",
>             batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
>             autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
>             maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin"s SQLite database when HTTP fails
>             headers: {
>                 "Authorization": `Token ${token}`
>             },
>             params: {
>             }
>         };
>
>         BackgroundGeolocation.configure(options);
>         BackgroundGeolocation.setOptions(options);
>
>         BackgroundGeolocation.start(() => {
>             Log.debug("[BackgroundGeolocation] started successfully");
>
>             // Fetch current position
>             BackgroundGeolocation.getCurrentPosition({timeout: 30}, (location) => {
>                 Log.debug("[BackgroundGeolocation] received current position: ", JSON.stringify(location));
>             }, (error) => {
>                 alert("Location error: " + error);
>             });
>         });
>     });
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/36>
> .
>


-- 
Snet form Gmail Mobile

**Comment by cosmith** [comment]
Yes this is about iOS, but it doesn't seem to work even if I move significantly, with the device or the emulator (1+km). Does it work for you in the emulator?

**Comment by cosmith** [comment]
Find my problem, I wrote `BackgroundGeolocation.setOptions(options);` instead of `BackgroundGeolocation.setConfig(options);`

**Comment by bajrangsharma-burrp** [comment]
Unable to fetch location after kill the App in Android...How can we fetch?...Suggest me, How can we fetch continuous location even if App is closed...for Android...

**Comment by bajrangsharma-burrp** [comment]
How can we run a service on OS level not an App level to fetch the location after closed the App by swipe?...suggest me...

**Comment by christocracy** [comment]
Do you realize you’re posting to a **closed** issue which was posted nearly 3 years ago.  Post a new issue.

(The plugin already *runs a service* “at the OS level”)
