### ISSUE TITLE
Location template replaced with Geofence template after GeoFence event

### ISSUE THREAD

**Issue by kris905** [transistorsoft/react-native-background-geolocation#360]
## Your Environment
* Plugin version: 2.9.4
* Platform:  Android
* OS version: 7.0
* Device manufacturer / model: Moto G5
* React Native version (`react-native -v`): 0.41.2
* Plugin config
```
╔═════════════════════════════════════════════
║ BackgroundGeolocation Settings
╠═════════════════════════════════════════════
{
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": "location",
  "distanceFilter": 10,
  "desiredAccuracy": 0,
  "desiredOdometerAccuracy": 100,
  "locationUpdateInterval": 1000,
  "fastestLocationUpdateInterval": 10000,
  "locationTimeout": 60,
  "deferTime": 0,
  "disableElasticity": false,
  "activityRecognitionInterval": 10000,
  "minimumActivityRecognitionConfidence": 75,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "disableStopDetection": false,
  "stationaryRadius": 25,
  "stopTimeout": 10,
  "stopOnStationary": false,
  "url": "http:\/\/urlhere.ca:5056",
  "method": "POST",
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "maxBatchSize": -1,
  "headers": {},
  "extras": {
    "token": "497ac6be-6e8e-4a5e-b337-99c5346d50e6",
    "id": "TEST"
  },
  "httpRootProperty": ".",
   "locationTemplate" :  '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, "altitude":<%= altitude %> , "speed": <%= speed%>,  "heading": <%= heading%>,  "accuracy": <%= accuracy%>, "batt": <%= battery.level%> }';
  "persist": true,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": -1,
  "locationsOrderDirection": "ASC",
  "httpTimeout": 3000,
  "geofenceProximityRadius": 1000,
  "geofenceInitialTriggerEntry": true,
  "stopOnTerminate": false,
  "startOnBoot": true,
  "heartbeatInterval": 60,
  "foregroundService": true,
  "notificationLargeIcon": "drawable\/notification_large_icon",
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnBoot": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnSchedule": false,
  "stopAfterElapsedMinutes": 0,
  "schedule": [],
  "configureUrl": "",
  "configureInterval": -1,
  "debug": false,
  "logLevel": 5,
  "logMaxDays": 3
```
## Expected Behavior

HTTP posts should always be sending location POST payload as per the defined locationTemplate.

## Actual Behavior
Location POSTs occur as expected until a geofence is encountered. When a geofence is encountered, the POST template switches to the GeoFence template for every subsequent post. This happens even after the device moved out of the GeoFence. Every post after the geofence hit sends the Geofence template JSON.

![screen shot 2017-11-15 at 9 38 58 pm](https://user-images.githubusercontent.com/3480243/32871159-72add9fa-ca4d-11e7-9f8b-94cd716a4981.jpg)

Server log screenshot attached as evidence

## Steps to Reproduce

1. Configure App to post to server with location template
2. Configure a GeoFence along the way
3. Observe the POST payload before and after the Geofence event
4.

**Comment by christocracy** [comment]
I'll check it out.

**Comment by christocracy** [comment]
Each location has a unique `uuid` identifier.  These unexpected locations with `geofence` data attached:  

- Do they have the same `uuid`?
- Do they have the same `timestamp`?

**Comment by kris905** [comment]
I will do one more field testing to confirm the uuid.  What has been happening is that, after the Geofence event, the JSON posted has the default GeoFence structure. I havent configured geoFenceTemplae in configuration, so i believe this is the default template

`{"odometer":7671.9,"activity":{"confidence":62,"type":"still"},"test":"1","geofence":{"identifier":"Go","action":"ENTER"},"extras":{"id":"KRISHTEST1","token":"497ac6be-6e8e-4a5e-b337-99c5346d50e6"},"battery":{"level":0.73,"is_charging":false},"uuid":"1730d32d-d721-4499-8064-7b90ea2cd381","event":"geofence","device":{"framework":"ReactNative","model":"Moto G (5)","version":"7.0","uuid":"95beed78be0b8f69","platform":"Android","manufacturer":"motorola"},"coords":{"altitude":154,"heading":278,"latitude":43.59704911708832,"accuracy":5,"speed":1.46,"longitude":-79.75527584552765},"is_moving":true,"timestamp":"2017-11-15T23:45:40.000Z","company_token":""}`

This is the tail from server log just tested. I am far away from geoFence now. But it is stuck here from the geofence event yesterday. When I say stuck, it is sending all attributes from the geofence and not the real ones (including lat, lon, altitude, course etc)

If I re install the app, it will fall back to normal locationTemplate as below and continue working normally until i hit the geofence.

`{"altitude":162,"batt":0.84,"test":"1","heading":-1,"latitude":43.5822805,"accuracy":18.7,"id":"KRISHTEST1","device":{"framework":"ReactNative","model":"Moto G (5)","version":"7.0","uuid":"95beed78be0b8f69","platform":"Android","manufacturer":"motorola"},"speed":-1,"longitude":-79.7540516,"token":"bb05132a-28f6-4352-926a-9ee82f5dc6a2","company_token":""}`

Hope this helps. Please let me know if you require further info

**Comment by kris905** [comment]
Yes all posts after the geofence has the same `uuid` and `timestamp` after geofence event

**Comment by christocracy** [comment]
Are using the `heartbeat` event and `#insertLocation`?

**Comment by kris905** [comment]
No, just listening to location and geofence events

**Comment by christocracy** [comment]
Can you reproduce this consistently at your desk?

**Comment by kris905** [comment]
Yes I can, I have server logs from last 5 days where location updates stop at geofence. They stop because server returns http 400, since it is not the expected payload. But I can see that the http post happens at location event, just that it posts stale data.

I will test again after removing all code from geofence event listener `onGeofence`.

**Comment by christocracy** [comment]
If your server returns `400`, the plugin is going to keep attempting to send the same location over and over again.  When the first HTTP request returns an error, the plugin gives up.  It will not select the next record in the database.

You'll find the plugin is accumulating locations in its database.

What is your current `count`?
```javascript
BackgroundGeolocation.getCount(count) {
  console.log('- count: ', count);
});
```

**Comment by kris905** [comment]
That makes sense. I can see count accumilating after the geofence event. 
If I define a geoFence template same as location template, so server return 200 at geofence, the plugin can proceed with updates? Will that be the right approach?

**Comment by christocracy** [comment]
yes.

**Comment by kris905** [comment]
Thanks for your help. Closing issue.
