### ISSUE TITLE
No request to backend

### ISSUE THREAD

**Issue by phuongit0301** [transistorsoft/react-native-background-geolocation#361]
My backend has an url..., everything is ok when i get data from postman,  However, server can not receive request from library when i config url from android app. Can you help me solve this problem? 

Thanks so much.

![screen shot 2017-11-17 at 7 14 20 pm](https://user-images.githubusercontent.com/3425152/32946935-2131fdd8-cbcc-11e7-97f4-437fd180e22c.png)
![screen shot 2017-11-17 at 6 41 29 pm](https://user-images.githubusercontent.com/3425152/32946936-215dfc80-cbcc-11e7-8df3-0e67e12b8d40.png)

**Comment by christocracy** [comment]
Adb logs

**Comment by phuongit0301** [comment]
Yes, christocracy

[logcat.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1482258/logcat.txt)

**Comment by christocracy** [comment]
Sorry, missed your logs.  I don't see anywhere in the logs attempting an HTTP request.  You know you're using `autoSync: false`, right?  It's up to you to manually execute the plugin's `#sync` method when you want the plugin to upload locations.

**Comment by christocracy** [comment]
Closed for lack of feedback.
