### ISSUE TITLE
Android studio- Is there a way to integrate Geolocation without react-native

### ISSUE THREAD

**Issue by talasilasrikanth** [transistorsoft/react-native-background-geolocation#364]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by talasilasrikanth** [comment]
Is there a way to integrate geolocation without using react native.
Can you please help us. we are license user

**Comment by christocracy** [comment]
I’m not sure what you mean.

**Comment by talasilasrikanth** [comment]
Sorry, i have edited my question:
I want to integrate geo location library to android studio(native android).
Can you please suggest me ways to integrate.
