### ISSUE TITLE
onLocation stops being executed 

### ISSUE THREAD

**Issue by AmyNgithub** [transistorsoft/react-native-background-geolocation#366]
## Your Environment
* Plugin version: 2.10.1 
* Platform: iOS 
* OS version: 11.1
* Device manufacturer / model: Apple / iPhone 7 on simulator and actual device
* React Native version (`react-native -v`): react-native-cli: 2.0.1, react-native: 0.49.5
* Plugin config:
```
BackgroundGeolocation.configure({
      // Geolocation Config
      desiredAccuracy: 0,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, //true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE, //Only in development //BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.         
}(state) => {
      console.log('- BackgroundGeolocation config: ', state.enabled);

      if (!state.enabled) {
        // 3. Start tracking!
        BackgroundGeolocation.start(function () {
          console.log('- Start success');
        });
      }
 });
```

## Context
I'm trying to create an app which shows the geopositions during a bus trip.

So the user press the start button when boarding the bus and the following code is run:
```
    BackgroundGeolocation.on('location', this.onLocation.bind(this));

    // This handler fires whenever bgGeo receives an error
    BackgroundGeolocation.on('error', this.onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.on('motionchange', this.onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.on('activitychange', this.onActivityChange.bind(this));

    // This event fires when the user toggles location-services
    BackgroundGeolocation.on('providerchange', this.onProviderChange);

    // 2.  #configure the plugin (just once for life-time of app)
    BackgroundGeolocation.configure({
      // Geolocation Config
      desiredAccuracy: 0,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, //true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE, //Only in development //BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    }, (state) => {
      console.log('- BackgroundGeolocation config: ', state.enabled);

      if (!state.enabled) {
        // 3. Start tracking!
        BackgroundGeolocation.start(function () {
          console.log('- Start success');
        });
      }
    });
```

Where onLocation, onError etc. are defined as follows:

```
 onLocation(location) {
    console.log('- [js]location: ', JSON.stringify(location));
    this.setState({ longitude: location.coords.longitude, latitude: location.coords.latitude })
  }
  onError(error) {
    const type = error.type;
    const code = error.code;
    bugsnag.notify(error);
    alert(type + ' Error: ' + code);
  }
  onActivityChange(activityName) {
    console.log('- Current motion activity: ', activityName);  // eg: 'on_foot', 'still', 'in_vehicle'
    console.log(activityName.activity);
    this.setState({ activity: activityName.activity });
  }
  onProviderChange(provider) {
    console.log('- Location provider changed: ', provider.enabled);  
  }
  onMotionChange(location) {
    console.log('- [js]motionchanged: ', JSON.stringify(location));
  }
```

When the bus trip has ended the user press the stop button and the following code is run:

```
    BackgroundGeolocation.stop();
    BackgroundGeolocation.un('location', this.onLocation);
    BackgroundGeolocation.un('error', this.onError);
    BackgroundGeolocation.un('motionchange', this.onMotionChange);
    BackgroundGeolocation.un('activitychange', this.onActivityChange);
    BackgroundGeolocation.un('providerchange', this.onProviderChange);
```

The code to the app can be found here: [https://github.com/AmyNgithub/TestRNBackgroundGeolocation](https://github.com/AmyNgithub/TestRNBackgroundGeolocation) 
## Expected Behavior

onLocation should be called regularly so that this.state.latitude and this.state.longitude is updated. 

## Actual Behavior

onLocation stops being called, hence this.state.latitude and this.state.longitude is not updated.

## Steps to Reproduce

1. The user taps the start button.
2. The app runs for a while and the locations are continuously shown on the screen.
3. The user taps the stop button.
4. The location stops being updated on the screen.
5. The user taps the start button again to start a second trip.
6. The app runs for a while but the locations does not update.

## Debug logs

What I have noticed is in the log is that at the start of the first trip the following lines appear:
ℹ️-[TSLocationManager on:success:failure:] location
ℹ️-[TSLocationManager on:success:failure:] motionchange
ℹ️-[TSLocationManager on:success:failure:] activitychange
ℹ️-[TSLocationManager on:success:failure:] providerchange

While at the start of the second trip these lines appear:
ℹ️-[TSLocationManager on:success:failure:] motionchange
ℹ️-[TSLocationManager on:success:failure:] providerchange

So activity and location does not appear. However I'm not sure what this means. Another thing I found strange is that the following line appears on both trips:
📍<+37.60144184,-122.42557665> +/- 5.00m (speed 33.85 mps / course 317.11) @ 11/30/17, 1:06:03 PM Central European Standard Time

So the position is retrieved during the second trip as well somewhere... I just don't know where.
But onLocation is not run which is where I set this.sate.longitude/latitude. 

[Logsovertwotripserror.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1517686/Logsovertwotripserror.txt)

## Question
So, what should I do to make sure that the location is updated on the second trip as well? Do I need to force onLocation somehow? or move the code which updates the location? If so where should I place the code instead?

**Comment by christocracy** [comment]
You don't need to remove listeners all the time.  Just call `#stop`.  When you turn off your stereo, you don't need to disconnect the speaker wires.  When the power is off, no music will flow into the speakers.

Also, you're only supposed to call the `#configure` method *once* when your app boots.  You do not call it *twice*.


```javascript
class Foo extends Component {
  componentDidMount() {
  	// Add listeners once
  	BackgroundGeolocation.on('location', this.onLocation.bind(this));
  	.
  	.
  	.
  	// Configure once
  	BackgroundGeolocation.configure(config, (state) => {

  	});
  }

  startBusTrip() {
  	// Start tracking
  	BackgroundGeolocation.start();
  }

  stopBusTrip() {
  	// Stop tracking
    BackgroundGeolocation.stop();
  }
  /**
  * @event location
  */
  onLocation(location) {
  	console.log('- location: ', location);
  }
}
```

**Comment by christocracy** [comment]
As for the listener problem, you're not removing the old listener.  You have to be careful here with `bind`.  Observe what you've done:  you've bound your `onLocation.bind(this)` but not `onMotionChange.

```javascript
BackgroundGeolocation.on('location', this.onLocation.bind(this));  
BackgroundGeolocation.on('motionchange', this.onMotionChange);
```

The javascript method `bind` returns a **NEW** function instance.

```
let fn_unbound = function() {};
let fn_bound = fn_unbound.bind(this);
console.log(fn_unbound === fn_bound);
>false
```

So, when you attempt to `BackgroundGeolocation.un('location', this.onLocation)`, that's not going to work:  you're not providing the *identical* callback function *instance*.

You'd have to do this:
```javascript

this.onLocation = this.onLocation.bind(this);
BackgroundGeolocation.on('location', this.onLocation);
.
.
.
// Now it will work.
BackgroundGeolocation.un('location', this.onLocation);
```

What does the [Javascript `#bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) method do, essentially?
```javascript
bind(callback, scope) {
  return function() {  // <-- returns a NEW function instance
    callback.apply(scope, arguments);
  }
}
```

**Comment by AmyNgithub** [comment]
Thank you @christocracy! This solved my issue!

**Comment by christocracy** [comment]
You're *highly* recommended to modify your code according to my [first comment](https://github.com/transistorsoft/react-native-background-geolocation/issues/366#issuecomment-348193196).

**Comment by AmyNgithub** [comment]
That's what I did :) I trust your code more than mine!

**Comment by christocracy** [comment]
Notice in my [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/components/HomeView.js#L310) how I "pre-bind" all my event-listeners so that I may have the *option* of `#un`ing them.
