### ISSUE TITLE
On iOS, setting the heartbeat interval to -1 causes the heartbeat to fire as fast as possible

### ISSUE THREAD

**Issue by dorthwein** [transistorsoft/react-native-background-geolocation#369]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS
* OS version: 10.xx.xx
* Device manufacturer / model: Simulator iPhone SE
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior
The heartbeat should not fire

## Actual Behavior
The heartbeat fires constantly

## Steps to Reproduce
Set config for heartbeat to -1 on iOS

## Context
Turn off heartbeat on iOS

**Comment by christocracy** [comment]
Sorry, missed this issue.  I'll check it out.  Customers should post issues to the private repo.  They'll get more attention.
