### ISSUE TITLE
Add #clear and #setExtras methods

### ISSUE THREAD

**Issue by jabm111** [transistorsoft/react-native-background-geolocation#37]
Hi Chris,

It would be great to have a #clear method to allow us to clear the local DB without syncing to the server.

Also, it would be nice to have a method (like #setExtras) that allow's us to add extra custom properties to the location markers before they are stored to the local DB.

The use case for me would be storing data for multiple trips, and being able to view that data separately on the device even if the user doesn't have a connection to the server.  Also, users without accounts may not have the ability to store a trip history, but they could track one trip at a time (and therefore would need to clear the DB without syncing to the server).

Thanks again!

James

**Comment by christocracy** [comment]
Will do.  Should take ~3 hours

**Comment by kaffeeguru** [comment]
Hi I would need that feature too.
