### ISSUE TITLE
Adding Geofences database SIGABRT Error

### ISSUE THREAD

**Issue by leonmagee** [transistorsoft/react-native-background-geolocation#370]
## Your Environment
* Plugin version: 2.9.4
* Platform: iOS Simulator, debug mode
* OS version: iOS 11.1
* Device manufacturer / model: iPhone 8 on iOS Simulator
* React Native version (`react-native -v`): 0.49.3
* Plugin config

```
import React, {Component} from 'react'
import {connect} from 'react-redux'
import api from '../Utils/api'
import bgGeo from 'react-native-background-geolocation'
import PushController from './PushController'
import PushNotification from 'react-native-push-notification'

import {View} from 'react-native';


class BackgroundGeofences extends Component {

  constructor(props) {
    super(props)
  }

  componentDidMount() {

    bgGeo.on('geofenceschange', this.onGeoFenceChange)

    const myConfig = {
      desiredAccuracy: 0,
      distanceFilter: 10,
      stopTimeout: 1,
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,
      maxDaysToPersist: 0
    }

    bgGeo.configure(myConfig, (state) => {
      if (!state.enabled) {
        bgGeo.startGeofences();
      }
    });

    api.getMenus().then((res) => {
      this.props.setRestData(res)

      const myGeoFences = res.map((item, index) => {
        if (item.coordinates.latitude && item.coordinates.longitude) {
          return ({
            identifier: item.name,
            radius: 50,
            latitude: item.coordinates.latitude,
            longitude: item.coordinates.longitude,
            notifyOnEntry: true,
            notifyOnExit: true
          })
        }
      })

     bgGeo.addGeofences(myGeoFences);
    })
  }

  componentWillUnmount() {
    bgGeo.un('geofenceschange', this.onGeoFenceChange)
  }

  onGeoFenceChange(event) {
    if (event.on.length) {

      event.on.map((event) => {
        PushNotification.localNotificationSchedule({
          message: `Your are now inside the radius of ${event.identifier}`, // (required)
          date: new Date(Date.now()), // send notification now
        });
      })

    }
    if (event.off.length) {

      event.off.map((event) => {
        PushNotification.localNotificationSchedule({
          message: `Your are now outside the radius of ${event}`, // (required)
          date: new Date(Date.now()), // send notification now
        });
      })
    }
  }

  render() {
    return (
      <View></View>
    )
  }
}

mapActionsToProps = (dispatch) => ({
  setRestData(results) {
    dispatch({type: 'SET_DATA_VALUE', payload: results})
  }
})

module.exports = connect(null, mapActionsToProps)(BackgroundGeofences)
```

## Expected Behavior

Geofences should be created and then trigger notifications on entry and exit.  It was working fine at first.

## Actual Behavior

App freezes with an error in Xcode relating to the database:
 -[TSDatabaseQueue inDatabase:]:  
0x10f902969 <+168>: movq   0x28(%rbx), %rdi  Thread 549: signal SIGABRT 
I've attached the ios simulator log and a text file of the error from xcode. 
The error happens when it gets to the line `bgGeo.addGeofences(myGeoFences);`. 
I don't think I can use the getLog method since everything freezes when the error happens. There is no error displayed in the ios simulator - it just stops working and I can't refresh or do anything. 
I tried removing the geofences that were already present but that didn't make a difference. 

## Steps to Reproduce

1.
2.
3.
4.

## Context

Send push notifications when a user is inside or outside of a geofence. 

## Debug logs

[xcode-database-error.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1533892/xcode-database-error.txt)
[ios-simulator-log.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/1533893/ios-simulator-log.txt)

**Comment by christocracy** [comment]
Thanks, I’ll attempt to reproduce.  How many geofences are you feeding it?

Btw, minimum reliable geofence radius is 150 meters.

**Comment by leonmagee** [comment]
Right now there are only 6 geofences but the number will vary in the future. 

I was going to ask about the radius, the 50 didn't seem to work when I tested on a device. 

Thanks

**Comment by christocracy** [comment]
Try moving your `#addGeofences` (and associated `api.getMenus` into the callback of `#configure`

**Comment by leonmagee** [comment]
I got the same notice. 

` bgGeo.configure(myConfig, (state) => {
      if (!state.enabled) {
        bgGeo.startGeofences();
      }

      api.getMenus().then((res) => {
        this.props.setRestData(res)
  
        const myGeoFences = res.map((item, index) => {
          if (item.coordinates.latitude && item.coordinates.longitude) {
            return ({
              identifier: item.name,
              radius: 150,
              latitude: item.coordinates.latitude,
              longitude: item.coordinates.longitude,
              notifyOnEntry: true,
              notifyOnExit: true
            })
          }
        })
  
       bgGeo.addGeofences(myGeoFences);
      })
      
    })`

**Comment by christocracy** [comment]
I tried adding my City Drive test-geofences (224 of them) in my Demo app in `#configure` callback.  I couldn't reproduce the problem.

<details>
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 1
╚═══════════════════════════════════════════════════════════
🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
2017-12-06 11:43:01.110 [info][tid:com.facebook.react.JavaScript] '[event] location: ', { coords: 
   { heading: -1,
     accuracy: 5,
     altitude_accuracy: -1,
     longitude: -122.0312186,
     altitude: 0,
     latitude: 37.33233141,
     speed: 0 },
  sample: true,
  battery: { is_charging: false, level: -1 },
  extras: {},
  is_moving: false,
  activity: { confidence: 100, type: 'unknown' },
  odometer: 178559.5,
  uuid: 'E8819FDD-7A41-4151-8C16-8611B3D10F3D',
  timestamp: '2017-12-06T16:43:01.107Z' }
2017-12-06 11:43:01.109965-0500 BGGeolocation[83461:77921728] '[event] location: ', { coords: 
   { heading: -1,
     accuracy: 5,
     altitude_accuracy: -1,
     longitude: -122.0312186,
     altitude: 0,
     latitude: 37.33233141,
     speed: 0 },
  sample: true,
  battery: { is_charging: false, level: -1 },
  extras: {},
  is_moving: false,
  activity: { confidence: 100, type: 'unknown' },
  odometer: 178559.5,
  uuid: 'E8819FDD-7A41-4151-8C16-8611B3D10F3D',
  timestamp: '2017-12-06T16:43:01.107Z' }
2017-12-06 11:43:01.120 [info][tid:com.facebook.react.JavaScript] '[event] providerchange', { status: 3, enabled: true, gps: true, network: true }
2017-12-06 11:43:01.120341-0500 BGGeolocation[83461:77921728] '[event] providerchange', { status: 3, enabled: true, gps: true, network: true }

📍<+37.33233141,-122.03121860> +/- 5.00m (speed 0.00 mps / course -1.00) @ 12/6/17, 11:43:00 AM GMT-05:00

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 0.4s
╚═══════════════════════════════════════════════════════════
✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+37.33233141,-122.03121860> +/- 5.00m (speed 0.00 mps / course -1.00) @ 12/6/17, 11:43:00 AM GMT-05:00
🔵-[Settings incrementOdometer:] 178559.5
🔵-[TSLocationManager startMonitoringStationaryRegion:] Radius: 25
🔴-[TSLocationManager stopUpdatingLocation] 
🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 5.0
🎾-[TSLocationManager startMonitoringSignificantLocationChanges] 
✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 9C50C878-F686-46A9-80ED-476749FE4398

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:error:] 
╚═══════════════════════════════════════════════════════════
✅-[BackgroundTaskManager createBackgroundTask] 1
✅-[TSHttpService schedulePost:] LOCKED: 9C50C878-F686-46A9-80ED-476749FE4398
🔵-[TSLocationManager addGeofences:success:failure:] 
ℹ️-[GeofenceDAO doInsert:params:] city_drive_1
ℹ️-[GeofenceDAO doInsert:params:] city_drive_2
ℹ️-[GeofenceDAO doInsert:params:] city_drive_3
ℹ️-[GeofenceDAO doInsert:params:] city_drive_4
ℹ️-[GeofenceDAO doInsert:params:] city_drive_5
ℹ️-[GeofenceDAO doInsert:params:] city_drive_6
ℹ️-[GeofenceDAO doInsert:params:] city_drive_7
ℹ️-[GeofenceDAO doInsert:params:] city_drive_8
ℹ️-[GeofenceDAO doInsert:params:] city_drive_9
ℹ️-[GeofenceDAO doInsert:params:] city_drive_10
ℹ️-[GeofenceDAO doInsert:params:] city_drive_11
ℹ️-[GeofenceDAO doInsert:params:] city_drive_12
ℹ️-[GeofenceDAO doInsert:params:] city_drive_13
ℹ️-[GeofenceDAO doInsert:params:] city_drive_14
ℹ️-[GeofenceDAO doInsert:params:] city_drive_15
ℹ️-[GeofenceDAO doInsert:params:] city_drive_16
ℹ️-[GeofenceDAO doInsert:params:] city_drive_17
ℹ️-[GeofenceDAO doInsert:params:] city_drive_18
ℹ️-[GeofenceDAO doInsert:params:] city_drive_19
ℹ️-[GeofenceDAO doInsert:params:] city_drive_20
ℹ️-[GeofenceDAO doInsert:params:] city_drive_21
ℹ️-[GeofenceDAO doInsert:params:] city_drive_22
ℹ️-[GeofenceDAO doInsert:params:] city_drive_23
ℹ️-[GeofenceDAO doInsert:params:] city_drive_24
ℹ️-[GeofenceDAO doInsert:params:] city_drive_25
ℹ️-[GeofenceDAO doInsert:params:] city_drive_26
ℹ️-[GeofenceDAO doInsert:params:] city_drive_27
ℹ️-[GeofenceDAO doInsert:params:] city_drive_28
ℹ️-[GeofenceDAO doInsert:params:] city_drive_29
ℹ️-[GeofenceDAO doInsert:params:] city_drive_30
ℹ️-[GeofenceDAO doInsert:params:] city_drive_31
ℹ️-[GeofenceDAO doInsert:params:] city_drive_32
ℹ️-[GeofenceDAO doInsert:params:] city_drive_33
ℹ️-[GeofenceDAO doInsert:params:] city_drive_34
ℹ️-[GeofenceDAO doInsert:params:] city_drive_35
ℹ️-[GeofenceDAO doInsert:params:] city_drive_36
ℹ️-[GeofenceDAO doInsert:params:] city_drive_37
ℹ️-[GeofenceDAO doInsert:params:] city_drive_38
ℹ️-[GeofenceDAO doInsert:params:] city_drive_39
ℹ️-[GeofenceDAO doInsert:params:] city_drive_40
ℹ️-[GeofenceDAO doInsert:params:] city_drive_41
ℹ️-[GeofenceDAO doInsert:params:] city_drive_42
ℹ️-[GeofenceDAO doInsert:params:] city_drive_43
ℹ️-[GeofenceDAO doInsert:params:] city_drive_44
ℹ️-[GeofenceDAO doInsert:params:] city_drive_45
ℹ️-[GeofenceDAO doInsert:params:] city_drive_46
ℹ️-[GeofenceDAO doInsert:params:] city_drive_47
ℹ️-[GeofenceDAO doInsert:params:] city_drive_48
ℹ️-[GeofenceDAO doInsert:params:] city_drive_49
ℹ️-[GeofenceDAO doInsert:params:] city_drive_50
ℹ️-[GeofenceDAO doInsert:params:] city_drive_51
ℹ️-[GeofenceDAO doInsert:params:] city_drive_52
ℹ️-[GeofenceDAO doInsert:params:] city_drive_53
ℹ️-[GeofenceDAO doInsert:params:] city_drive_54
ℹ️-[GeofenceDAO doInsert:params:] city_drive_55
ℹ️-[GeofenceDAO doInsert:params:] city_drive_56
ℹ️-[GeofenceDAO doInsert:params:] city_drive_57
ℹ️-[GeofenceDAO doInsert:params:] city_drive_58
ℹ️-[GeofenceDAO doInsert:params:] city_drive_59
ℹ️-[GeofenceDAO doInsert:params:] city_drive_60
ℹ️-[GeofenceDAO doInsert:params:] city_drive_61
ℹ️-[GeofenceDAO doInsert:params:] city_drive_62
ℹ️-[GeofenceDAO doInsert:params:] city_drive_63
ℹ️-[GeofenceDAO doInsert:params:] city_drive_64
ℹ️-[GeofenceDAO doInsert:params:] city_drive_65
ℹ️-[GeofenceDAO doInsert:params:] city_drive_66
ℹ️-[GeofenceDAO doInsert:params:] city_drive_67
ℹ️-[GeofenceDAO doInsert:params:] city_drive_68
ℹ️-[GeofenceDAO doInsert:params:] city_drive_69
ℹ️-[GeofenceDAO doInsert:params:] city_drive_70
ℹ️-[GeofenceDAO doInsert:params:] city_drive_71
ℹ️-[GeofenceDAO doInsert:params:] city_drive_72
ℹ️-[GeofenceDAO doInsert:params:] city_drive_73
ℹ️-[GeofenceDAO doInsert:params:] city_drive_74
ℹ️-[GeofenceDAO doInsert:params:] city_drive_75
ℹ️-[GeofenceDAO doInsert:params:] city_drive_76
ℹ️-[GeofenceDAO doInsert:params:] city_drive_77
ℹ️-[GeofenceDAO doInsert:params:] city_drive_78
ℹ️-[GeofenceDAO doInsert:params:] city_drive_79
ℹ️-[GeofenceDAO doInsert:params:] city_drive_80
ℹ️-[GeofenceDAO doInsert:params:] city_drive_81
ℹ️-[GeofenceDAO doInsert:params:] city_drive_82
ℹ️-[GeofenceDAO doInsert:params:] city_drive_83
ℹ️-[GeofenceDAO doInsert:params:] city_drive_84
ℹ️-[GeofenceDAO doInsert:params:] city_drive_85
ℹ️-[GeofenceDAO doInsert:params:] city_drive_86
ℹ️-[GeofenceDAO doInsert:params:] city_drive_87
ℹ️-[GeofenceDAO doInsert:params:] city_drive_88
ℹ️-[GeofenceDAO doInsert:params:] city_drive_89
ℹ️-[GeofenceDAO doInsert:params:] city_drive_90
ℹ️-[GeofenceDAO doInsert:params:] city_drive_91
ℹ️-[GeofenceDAO doInsert:params:] city_drive_92
ℹ️-[GeofenceDAO doInsert:params:] city_drive_93
ℹ️-[GeofenceDAO doInsert:params:] city_drive_94
ℹ️-[GeofenceDAO doInsert:params:] city_drive_95
ℹ️-[GeofenceDAO doInsert:params:] city_drive_96
ℹ️-[GeofenceDAO doInsert:params:] city_drive_97
ℹ️-[GeofenceDAO doInsert:params:] city_drive_98
ℹ️-[GeofenceDAO doInsert:params:] city_drive_99
ℹ️-[GeofenceDAO doInsert:params:] city_drive_100
ℹ️-[GeofenceDAO doInsert:params:] city_drive_101
ℹ️-[GeofenceDAO doInsert:params:] city_drive_102
ℹ️-[GeofenceDAO doInsert:params:] city_drive_103
ℹ️-[GeofenceDAO doInsert:params:] city_drive_104
ℹ️-[GeofenceDAO doInsert:params:] city_drive_105
ℹ️-[GeofenceDAO doInsert:params:] city_drive_106
ℹ️-[GeofenceDAO doInsert:params:] city_drive_107
ℹ️-[GeofenceDAO doInsert:params:] city_drive_108
ℹ️-[GeofenceDAO doInsert:params:] city_drive_109
ℹ️-[GeofenceDAO doInsert:params:] city_drive_110
ℹ️-[GeofenceDAO doInsert:params:] city_drive_111
ℹ️-[GeofenceDAO doInsert:params:] city_drive_112
ℹ️-[GeofenceDAO doInsert:params:] city_drive_113
ℹ️-[GeofenceDAO doInsert:params:] city_drive_114
ℹ️-[GeofenceDAO doInsert:params:] city_drive_115
ℹ️-[GeofenceDAO doInsert:params:] city_drive_116
ℹ️-[GeofenceDAO doInsert:params:] city_drive_117
ℹ️-[GeofenceDAO doInsert:params:] city_drive_118
ℹ️-[GeofenceDAO doInsert:params:] city_drive_119
ℹ️-[GeofenceDAO doInsert:params:] city_drive_120
ℹ️-[GeofenceDAO doInsert:params:] city_drive_121
ℹ️-[GeofenceDAO doInsert:params:] city_drive_122
ℹ️-[GeofenceDAO doInsert:params:] city_drive_123
ℹ️-[GeofenceDAO doInsert:params:] city_drive_124
ℹ️-[GeofenceDAO doInsert:params:] city_drive_125
ℹ️-[GeofenceDAO doInsert:params:] city_drive_126
ℹ️-[GeofenceDAO doInsert:params:] city_drive_127
ℹ️-[GeofenceDAO doInsert:params:] city_drive_128
ℹ️-[GeofenceDAO doInsert:params:] city_drive_129
ℹ️-[GeofenceDAO doInsert:params:] city_drive_130
ℹ️-[GeofenceDAO doInsert:params:] city_drive_131
ℹ️-[GeofenceDAO doInsert:params:] city_drive_132
ℹ️-[GeofenceDAO doInsert:params:] city_drive_133
ℹ️-[GeofenceDAO doInsert:params:] city_drive_134
ℹ️-[GeofenceDAO doInsert:params:] city_drive_135
ℹ️-[GeofenceDAO doInsert:params:] city_drive_136
ℹ️-[GeofenceDAO doInsert:params:] city_drive_137
ℹ️-[GeofenceDAO doInsert:params:] city_drive_138
ℹ️-[GeofenceDAO doInsert:params:] city_drive_139
ℹ️-[GeofenceDAO doInsert:params:] city_drive_140
ℹ️-[GeofenceDAO doInsert:params:] city_drive_141
ℹ️-[GeofenceDAO doInsert:params:] city_drive_142
ℹ️-[GeofenceDAO doInsert:params:] city_drive_143
ℹ️-[GeofenceDAO doInsert:params:] city_drive_144
ℹ️-[GeofenceDAO doInsert:params:] city_drive_145
ℹ️-[GeofenceDAO doInsert:params:] city_drive_146
ℹ️-[GeofenceDAO doInsert:params:] city_drive_147
ℹ️-[GeofenceDAO doInsert:params:] city_drive_148
ℹ️-[GeofenceDAO doInsert:params:] city_drive_149
ℹ️-[GeofenceDAO doInsert:params:] city_drive_150
ℹ️-[GeofenceDAO doInsert:params:] city_drive_151
ℹ️-[GeofenceDAO doInsert:params:] city_drive_152
ℹ️-[GeofenceDAO doInsert:params:] city_drive_153
ℹ️-[GeofenceDAO doInsert:params:] city_drive_154
ℹ️-[GeofenceDAO doInsert:params:] city_drive_155
ℹ️-[GeofenceDAO doInsert:params:] city_drive_156
ℹ️-[GeofenceDAO doInsert:params:] city_drive_157
ℹ️-[GeofenceDAO doInsert:params:] city_drive_158
ℹ️-[GeofenceDAO doInsert:params:] city_drive_159
ℹ️-[GeofenceDAO doInsert:params:] city_drive_160
ℹ️-[GeofenceDAO doInsert:params:] city_drive_161
ℹ️-[GeofenceDAO doInsert:params:] city_drive_162
ℹ️-[GeofenceDAO doInsert:params:] city_drive_163
ℹ️-[GeofenceDAO doInsert:params:] city_drive_164
ℹ️-[GeofenceDAO doInsert:params:] city_drive_165
ℹ️-[GeofenceDAO doInsert:params:] city_drive_166
ℹ️-[GeofenceDAO doInsert:params:] city_drive_167
ℹ️-[GeofenceDAO doInsert:params:] city_drive_168
ℹ️-[GeofenceDAO doInsert:params:] city_drive_169
ℹ️-[GeofenceDAO doInsert:params:] city_drive_170
ℹ️-[GeofenceDAO doInsert:params:] city_drive_171
ℹ️-[GeofenceDAO doInsert:params:] city_drive_172
ℹ️-[GeofenceDAO doInsert:params:] city_drive_173
ℹ️-[GeofenceDAO doInsert:params:] city_drive_174
ℹ️-[GeofenceDAO doInsert:params:] city_drive_175
ℹ️-[GeofenceDAO doInsert:params:] city_drive_176
ℹ️-[GeofenceDAO doInsert:params:] city_drive_177
ℹ️-[GeofenceDAO doInsert:params:] city_drive_178
ℹ️-[GeofenceDAO doInsert:params:] city_drive_179
ℹ️-[GeofenceDAO doInsert:params:] city_drive_180
ℹ️-[GeofenceDAO doInsert:params:] city_drive_181
ℹ️-[GeofenceDAO doInsert:params:] city_drive_182
ℹ️-[GeofenceDAO doInsert:params:] city_drive_183
ℹ️-[GeofenceDAO doInsert:params:] city_drive_184
ℹ️-[GeofenceDAO doInsert:params:] city_drive_185
ℹ️-[GeofenceDAO doInsert:params:] city_drive_186
ℹ️-[GeofenceDAO doInsert:params:] city_drive_187
ℹ️-[GeofenceDAO doInsert:params:] city_drive_188
ℹ️-[GeofenceDAO doInsert:params:] city_drive_189
ℹ️-[GeofenceDAO doInsert:params:] city_drive_190
ℹ️-[GeofenceDAO doInsert:params:] city_drive_191
ℹ️-[GeofenceDAO doInsert:params:] city_drive_192
ℹ️-[GeofenceDAO doInsert:params:] city_drive_193
ℹ️-[GeofenceDAO doInsert:params:] city_drive_194
ℹ️-[GeofenceDAO doInsert:params:] city_drive_195
ℹ️-[GeofenceDAO doInsert:params:] city_drive_196
ℹ️-[GeofenceDAO doInsert:params:] city_drive_197
ℹ️-[GeofenceDAO doInsert:params:] city_drive_198
ℹ️-[GeofenceDAO doInsert:params:] city_drive_199
ℹ️-[GeofenceDAO doInsert:params:] city_drive_200
ℹ️-[GeofenceDAO doInsert:params:] city_drive_201
ℹ️-[GeofenceDAO doInsert:params:] city_drive_202
ℹ️-[GeofenceDAO doInsert:params:] city_drive_203
ℹ️-[GeofenceDAO doInsert:params:] city_drive_204
ℹ️-[GeofenceDAO doInsert:params:] city_drive_205
ℹ️-[GeofenceDAO doInsert:params:] city_drive_206
ℹ️-[GeofenceDAO doInsert:params:] city_drive_207
ℹ️-[GeofenceDAO doInsert:params:] city_drive_208
ℹ️-[GeofenceDAO doInsert:params:] city_drive_209
ℹ️-[GeofenceDAO doInsert:params:] city_drive_210
ℹ️-[GeofenceDAO doInsert:params:] city_drive_211
ℹ️-[GeofenceDAO doInsert:params:] city_drive_212
ℹ️-[GeofenceDAO doInsert:params:] city_drive_213
ℹ️-[GeofenceDAO doInsert:params:] city_drive_214
ℹ️-[GeofenceDAO doInsert:params:] city_drive_215
ℹ️-[GeofenceDAO doInsert:params:] city_drive_216
ℹ️-[GeofenceDAO doInsert:params:] city_drive_217
ℹ️-[GeofenceDAO doInsert:params:] city_drive_218
ℹ️-[GeofenceDAO doInsert:params:] city_drive_219
ℹ️-[GeofenceDAO doInsert:params:] city_drive_220
ℹ️-[GeofenceDAO doInsert:params:] city_drive_221
ℹ️-[GeofenceDAO doInsert:params:] city_drive_222
ℹ️-[GeofenceDAO doInsert:params:] city_drive_223
ℹ️-[GeofenceDAO doInsert:params:] city_drive_224
2017-12-06 11:43:01.236 [info][tid:com.facebook.react.JavaScript] '[event] motionchange: ', undefined, { timestamp: '2017-12-06T16:43:00.749Z',
  battery: { level: -1, is_charging: false },
  uuid: '9C50C878-F686-46A9-80ED-476749FE4398',
  odometer: 178559.5,
  event: 'motionchange',
  activity: { type: 'unknown', confidence: 100 },
  is_moving: false,
  extras: {},
  coords: 
   { speed: 0,
     latitude: 37.33233141,
     altitude: 0,
     longitude: -122.0312186,
     altitude_accuracy: -1,
     accuracy: 5,
     heading: -1 } }
2017-12-06 11:43:01.235991-0500 BGGeolocation[83461:77921728] '[event] motionchange: ', undefined, { timestamp: '2017-12-06T16:43:00.749Z',
  battery: { level: -1, is_charging: false },
  uuid: '9C50C878-F686-46A9-80ED-476749FE4398',
  odometer: 178559.5,
  event: 'motionchange',
  activity: { type: 'unknown', confidence: 100 },
  is_moving: false,
  extras: {},
  coords: 
   { speed: 0,
     latitude: 37.33233141,
     altitude: 0,
     longitude: -122.0312186,
     altitude_accuracy: -1,
     accuracy: 5,
     heading: -1 } }
2017-12-06 11:43:01.272 [info][tid:com.facebook.react.JavaScript] '[event] location: ', { coords: 
   { heading: -1,
     accuracy: 5,
     altitude_accuracy: -1,
     longitude: -122.0312186,
     altitude: 0,
     latitude: 37.33233141,
     speed: 0 },
  extras: {},
  is_moving: false,
  activity: { confidence: 100, type: 'unknown' },
  event: 'motionchange',
  odometer: 178559.5,
  uuid: '9C50C878-F686-46A9-80ED-476749FE4398',
  battery: { is_charging: false, level: -1 },
  timestamp: '2017-12-06T16:43:00.749Z' }
2017-12-06 11:43:01.271985-0500 BGGeolocation[83461:77921728] '[event] location: ', { coords: 
   { heading: -1,
     accuracy: 5,
     altitude_accuracy: -1,
     longitude: -122.0312186,
     altitude: 0,
     latitude: 37.33233141,
     speed: 0 },
  extras: {},
  is_moving: false,
  activity: { confidence: 100, type: 'unknown' },
  event: 'motionchange',
  odometer: 178559.5,
  uuid: '9C50C878-F686-46A9-80ED-476749FE4398',
  battery: { is_charging: false, level: -1 },
  timestamp: '2017-12-06T16:43:00.749Z' }
ℹ️+[LocationAuthorization run:] status: 3
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
2017-12-06 11:43:01.460919-0500 BGGeolocation[83461:77921466] [TSBackgroundFetch addListener]: TSLocationManager
2017-12-06 11:43:01.461048-0500 BGGeolocation[83461:77921466] [TSBackgroundFetch start]
🔵-[TSHttpService doPost:] HTTP Response: 200
✅-[TSHttpService post:error:] DESTROY: 9C50C878-F686-46A9-80ED-476749FE4398

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 1
╚═══════════════════════════════════════════════════════════
2017-12-06 11:43:01.559522-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 2.2.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.560018-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 2.3.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.562 [info][tid:com.facebook.react.JavaScript] - http 200
2017-12-06 11:43:01.561871-0500 BGGeolocation[83461:77921728] - http 200
2017-12-06 11:43:01.563954-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 0.2.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.564 [info][tid:com.facebook.react.JavaScript] {"success":true}
2017-12-06 11:43:01.564234-0500 BGGeolocation[83461:77921728] {"success":true}
2017-12-06 11:43:01.564681-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 1.2.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.565258-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 1.3.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.565632-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 0.3.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.567563-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 2.1.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.568911-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 1.1.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.569313-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 0.1.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
✅-[BackgroundTaskManager stopBackgroundTask:]_block_invoke 1 OF (
    1
)
2017-12-06 11:43:01.601707-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 2.1.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.606113-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 1.1.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)
2017-12-06 11:43:01.607068-0500 BGGeolocation[83461:77921466] [VKDefault] Tile 0.1.3 (128) in current unloaded state for 0.01 seconds - Raster Overlays Above Labels - Failed to decode (terminal) (0.01 sec)

╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager evaluateProximity:] Found 5 / 224 within 1000 m
╚═══════════════════════════════════════════════════════════
🎾-[TSGeofenceManager startMonitoringGeofence:] city_drive_2
🎾-[TSGeofenceManager startMonitoringGeofence:] city_drive_1
🎾-[TSGeofenceManager startMonitoringGeofence:] city_drive_3
🎾-[TSGeofenceManager startMonitoringGeofence:] city_drive_4
🎾-[TSGeofenceManager startMonitoringGeofence:] city_drive_5

</details>

**Comment by leonmagee** [comment]
I might have updated Xcode.

**Comment by leonmagee** [comment]
Also, on transistorsoft.com your snippet here doesn't work without putting the object in an array:
`// Add a geofence
bgGeo.addGeofences({
  identifier: 'HOME',
  radius: 200,
  latitude: 45.51818958022214,
  longitude: -73.61409989192487,
  notifyOnEntry: true,
  notifyOnExit: true
});`

**Comment by christocracy** [comment]
That's a docs bug.  `#addGeofences` (plural) requires an `[{}, {}, ... ]`

**Comment by leonmagee** [comment]
I modified the code to add the geofences one at a time rather than passing an array to `addGeofences` and it's not giving me the error for now:

`        const myGeoFences = res.map((item, index) => {
          if (item.coordinates.latitude && item.coordinates.longitude) {
            bgGeo.addGeofences([{
              identifier: item.name,
              radius: 150,
              latitude: item.coordinates.latitude,
              longitude: item.coordinates.longitude,
              notifyOnEntry: true,
              notifyOnExit: true
            }]);
          }
        })`

**Comment by christocracy** [comment]
Select the **Advanced** app when running the demo.

**Comment by leonmagee** [comment]
I ran the demo app previously and it worked fine. I'm going to test this on a device and see if it works, but at least for now I'm not getting the error.

**Comment by christocracy** [comment]
Also, show me the JSON of your geofences you're adding.

**Comment by leonmagee** [comment]
Here's what I'm adding now:
```
[{"notifyOnDwell":0,"radius":150,"longitude":-122.055747,"loiteringDelay":0,"identifier":"San Fran Driving","notifyOnExit":1,"latitude":37.332503,"notifyOnEntry":1},{"notifyOnDwell":0,"radius":150,"longitude":-117.146523,"loiteringDelay":0,"identifier":"Lestats On Park","notifyOnExit":1,"latitude":32.760146,"notifyOnEntry":1},{"notifyOnDwell":0,"radius":150,"longitude":-117.155404,"loiteringDelay":0,"identifier":"Coffee Bean and Teal Leaf","notifyOnExit":1,"latitude":32.767743,"notifyOnEntry":1},{"notifyOnDwell":0,"radius":150,"longitude":-117.130787,"loiteringDelay":0,"identifier":"Holsem Coffee","notifyOnExit":1,"latitude":32.748409,"notifyOnEntry":1}]
```

**Comment by christocracy** [comment]
I tried using your geofences.  They're good.

**Comment by christocracy** [comment]
What's the status on this?

**Comment by leonmagee** [comment]
After I changed the code to add the geofences one at a time that error stop appearing. I didn't get an opportunity to test it much more after that.
