### ISSUE TITLE
Use Library in native Android App

### ISSUE THREAD

**Issue by vaniakerer** [transistorsoft/react-native-background-geolocation#371]
## Your Environment
* Plugin version: i take this https://goo.gl/aKE1uf and this https://goo.gl/Hprnu1
* Platform: Android
* OS version: 5.0
* Device manufacturer / model: HTC One m7
* React Native version (`react-native -v`): 
* Plugin config

## Expected Behavior
I trying to use library in native Android app. I import all dependencies and tslocationmanager.aar, currently I have access to all classes. I need to resolve request and handle location changes and display distance betwen all coordinates. As I know - I need to create an instance of BackgroundGeolocation, then configure it, then call method start() and in BrodcastReceiver handle locations

## Actual Behavior
But in Failure callback from method start() I handle "Waiting for previous start action to complete". I tried call method BackgroundGeolocation.onLocation() in success calback from BackgroundGeolocation.configure(), and receive locations, but they come rarely, and then do not come at all. 

## Steps to Reproduce

1. Create native project
2. Import all needed librarys.
3. Use my source code

## Sourse code
  final BackgroundGeolocation backgroundGeolocation = BackgroundGeolocation.getInstance(this, new Intent());
        backgroundGeolocation.configure(getConfig(), new TSCallback() {
            @Override
            public void onSuccess() {
                Log.d(TAG, "onSuccess");
                backgroundGeolocation.start(new TSCallback() {
                    @Override
                    public void onSuccess() {
                        Log.d(TAG, "onSuccess Start");

                    }

                    @Override
                    public void onFailure(String s) {
                        Log.d(TAG, "onFailure Start: " + s);
                    }
                });
            }

            @Override
            public void onFailure(String s) {
                Log.d(TAG, "onFailure: " + s);

            }
        });

        backgroundGeolocation.onLocation(new TSLocationCallback() {
            @Override
            public void onLocation(TSLocation tsLocation) {
                Log.d("NEW_LOCATION", "onLocation : " + new Gson().toJson(tsLocation));
            }

            @Override
            public void onError(Integer integer) {
                Log.d(TAG, "onError : " + integer);

            }
        });

 private JSONObject getConfig() {
        JSONObject config = new JSONObject();
        try {
            config.put("distanceFilter", 1);
            config.put("debug", true);
        } catch (JSONException e) {
            e.printStackTrace();
        }

        return config;
    }

## Debug logs
12-07 00:43:06.348 11798-11798/berof.virtuscode.com.myapplication I/TSLocationManager: ╔═════════════════════════════════════════════
                                                                                       ║ License Validation Failure
                                                                                       ╠═════════════════════════════════════════════
                                                                                       ╟─ BackgroundGeolocation is running in evaluation mode.
12-07 00:43:06.358 11798-11798/berof.virtuscode.com.myapplication E/SensorManager: uid = 10873
12-07 00:43:06.358 11798-11798/berof.virtuscode.com.myapplication E/SensorManager: uid = 10873
12-07 00:43:06.368 11798-11798/berof.virtuscode.com.myapplication E/SensorManager: uid = 10873
12-07 00:43:06.368 11798-11798/berof.virtuscode.com.myapplication E/SensorManager: uid = 10873
12-07 00:43:06.368 11798-11798/berof.virtuscode.com.myapplication E/SensorManager: uid = 10873
12-07 00:43:06.368 11798-11798/berof.virtuscode.com.myapplication E/SensorManager: uid = 10873
12-07 00:43:06.368 11798-11798/berof.virtuscode.com.myapplication E/SensorManager: uid = 10873
12-07 00:43:06.368 11798-11798/berof.virtuscode.com.myapplication E/SensorManager: uid = 10873
12-07 00:43:06.388 11798-11798/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.util.Sensors print] 
                                                                                       ╔═════════════════════════════════════════════
                                                                                       ║ DEVICE SENSORS
                                                                                       ╠═════════════════════════════════════════════
                                                                                       ╟─ ✅  ACCELEROMETER: {Sensor name="BOSCH BMA250 3-axis Accelerometer", vendor="BOSCH", version=1, type=1, maxRange=39.2266, resolution=0.038307227, power=0.1, minDelay=10000}
                                                                                       ╟─ ✅  GYROSCOPE: {Sensor name="R3GD20 Gyroscope sensor", vendor="ST Group Ltd.", version=1, type=4, maxRange=34.906586, resolution=0.0012217305, power=6.1, minDelay=10000}
                                                                                       ╟─ ✅  MAGNETOMETER: {Sensor name="AK8963 3-axis Magnetic field sensor", vendor="Asahi Kasei Microdevices", version=1, type=2, maxRange=4915.2, resolution=0.06, power=0.28, minDelay=10000}
                                                                                       ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="BOSCH BMA250 Signifcant Motion Sensor", vendor="BOSCH", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.1, minDelay=-1}
                                                                                       ╚═════════════════════════════════════════════
12-07 00:43:06.438 11798-11798/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                                                       ╔═════════════════════════════════════════════
                                                                                       ║ BackgroundGeolocation adapter
                                                                                       ╠═════════════════════════════════════════════
12-07 00:43:06.478 11798-11798/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                                                         ✅  Google Play Services: connected (version code:11717000)
12-07 00:43:06.528 11798-11798/berof.virtuscode.com.myapplication D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO dbh] 
                                                                                         ✅  Opened database
12-07 00:43:06.578 11798-11798/berof.virtuscode.com.myapplication D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO prune] 
                                                                                         ℹ️  PRUNE -1 days
12-07 00:43:06.888 11798-11798/berof.virtuscode.com.myapplication D/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO dbh] 
                                                                                         ✅  Opened database
12-07 00:43:06.928 11798-11798/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                                                         ��  Connecting to GooglePlayServices...
12-07 00:43:06.988 11798-11798/berof.virtuscode.com.myapplication D/Atlas: Validating map...
12-07 00:43:07.008 11798-11824/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.settings.Settings print] 
                                                                                       ╔═════════════════════════════════════════════
                                                                                       ║ BackgroundGeolocation Settings
                                                                                       ╠═════════════════════════════════════════════
                                                                                       {
                                                                                         "isMoving": false,
                                                                                         "enabled": true,
                                                                                         "odometer": 441.87152,
                                                                                         "schedulerEnabled": false,
                                                                                         "trackingMode": "location",
                                                                                         "distanceFilter": 1,
                                                                                         "desiredAccuracy": 0,
                                                                                         "desiredOdometerAccuracy": 100,
                                                                                         "locationUpdateInterval": 1000,
                                                                                         "fastestLocationUpdateInterval": 10000,
                                                                                         "locationTimeout": 60,
                                                                                         "deferTime": 0,
                                                                                         "disableElasticity": false,
                                                                                         "elasticityMultiplier": 1,
                                                                                         "activityRecognitionInterval": 10000,
                                                                                         "minimumActivityRecognitionConfidence": 75,
                                                                                         "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                                         "disableStopDetection": false,
                                                                                         "stationaryRadius": 25,
                                                                                         "stopTimeout": 5,
                                                                                         "stopOnStationary": false,
                                                                                         "url": "",
                                                                                         "method": "POST",
                                                                                         "autoSync": true,
                                                                                         "autoSyncThreshold": 0,
                                                                                         "batchSync": false,
                                                                                         "maxBatchSize": -1,
                                                                                         "params": {},
                                                                                         "headers": {},
                                                                                         "extras": {},
                                                                                         "httpRootProperty": "location",
                                                                                         "locationTemplate": "",
                                                                                         "geofenceTemplate": "",
                                                                                         "persist": true,
                                                                                         "maxDaysToPersist": 1,
                                                                                         "maxRecordsToPersist": -1,
                                                                                         "locationsOrderDirection": "ASC",
                                                                                         "httpTimeout": 60000,
                                                                                         "geofenceProximityRadius": 1000,
                                                                                         "geofenceInitialTriggerEntry": true,
                                                                                         "stopOnTerminate": true,
                                                                                         "startOnBoot": false,
                                                                                         "heartbeatInterval": -1,
                                                                                         "foregroundService": false,
                                                                                         "notificationPriority": 0,
                                                                                         "notificationTitle": "",
                                                                                         "notificationText": "Location Service activated",
                                                                                         "notificationColor": "",
                                                                                         "notificationIcon": "",
                                                                                         "notificationSmallIcon": "",
                                                                                         "notificationLargeIcon": "",
                                                                                         "forceReloadOnLocationChange": false,
                                                                                         "forceReloadOnMotionChange": false,
                                                                                         "forceReloadOnGeofence": false,
                                                                                         "forceReloadOnBoot": false,
                                                                                         "forceReloadOnHeartbeat": false,
                                                                                         "forceReloadOnSchedule": false,
                                                                                         "stopAfterElapsedMinutes": 0,
                                                                                         "schedule": [],
                                                                                         "configureUrl": "",
                                                                                         "configureInterval": -1,
                                                                                         "debug": true,
                                                                                         "logLevel": 5,
                                                                                         "logMaxDays": 3
                                                                                       }╚═════════════════════════════════════════════
12-07 00:43:07.068 11798-11825/berof.virtuscode.com.myapplication I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020 - CR771817 ()
                                                                                OpenGL ES Shader Compiler Version: E031.25.03.06
                                                                                Build Date: 03/04/15 Wed
                                                                                Local Branch: 
                                                                                Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020
                                                                                Local Patches: NONE
                                                                                Reconstruct Branch: NOTHING
12-07 00:43:07.078 11798-11832/berof.virtuscode.com.myapplication I/TSLocationManager: - Enable: true → true, trackingMode: location
12-07 00:43:07.239 11798-11798/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.BackgroundGeolocationService onStartCommand] 
                                                                                       ╔═════════════════════════════════════════════
                                                                                       ║ BackgroundGeolocation Service started
                                                                                       ╠═════════════════════════════════════════════
12-07 00:43:08.410 11798-11798/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.BackgroundGeolocationService b] 
                                                                                         ��  Start activity updates: 10000
12-07 00:43:09.010 11798-11798/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.BackgroundGeolocationService a] 
                                                                                         ��  setPace: null → false
12-07 00:43:09.070 11798-11798/berof.virtuscode.com.myapplication D/TEST_LOCATION_LIB: onSuccess
12-07 00:43:09.080 11798-11798/berof.virtuscode.com.myapplication D/TEST_LOCATION_LIB: onFailure Start: Waiting for previous start action to complete
12-07 00:43:09.080 11798-11798/berof.virtuscode.com.myapplication I/Choreographer: Skipped 110 frames!  The application may be doing too much work on its main thread.
12-07 00:43:09.241 11798-11844/berof.virtuscode.com.myapplication D/TSLocationManager: [c.t.l.LocationService onLocation] 
                                                                                       ╔═════════════════════════════════════════════
                                                                                       ║ LocationService: location:1001
                                                                                       ╠═════════════════════════════════════════════
                                                                                       ╟─ ��  Location[fused 48.392236,25.637632 acc=20 et=+1d6h27m7s298ms], age: 44ms
12-07 00:43:09.281 11798-11844/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
                                                                                         ��  Acquired motionchange position, isMoving: false
12-07 00:43:09.301 11798-11828/berof.virtuscode.com.myapplication D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
12-07 00:43:09.301 11798-11844/berof.virtuscode.com.myapplication D/TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] 20.1
12-07 00:43:09.331 11798-11828/berof.virtuscode.com.myapplication D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] YES
12-07 00:43:09.401 11798-11832/berof.virtuscode.com.myapplication I/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO persist] 
                                                                                         ✅  INSERT: 798d4cb2-95f6-4f42-9d57-f80500d60a98
12-07 00:43:09.601 11798-11798/berof.virtuscode.com.myapplication D/TEST_LOC: received location{"coords":{"accuracy":20.1,"altitude":-1.0,"heading":-1.0,"latitude":48.3922355,"longitude":25.637632,"speed":-1.0},"event":"motionchange","is_moving":false,"odometer":441.9,"timestamp":"2017-12-06T22:43:09.192Z","uuid":"798d4cb2-95f6-4f42-9d57-f80500d60a98"}
12-07 00:43:09.651 11798-11798/berof.virtuscode.com.myapplication D/TEST_LOC: received location{"coords":{"accuracy":20.1,"altitude":-1.0,"heading":-1.0,"latitude":48.3922355,"longitude":25.637632,"speed":-1.0},"event":"motionchange","is_moving":false,"odometer":441.9,"timestamp":"2017-12-06T22:43:09.192Z","uuid":"798d4cb2-95f6-4f42-9d57-f80500d60a98"}
12-07 00:43:09.651 11798-11798/berof.virtuscode.com.myapplication D/TEST_LOC: received location finish
12-07 00:43:09.731 11798-11828/berof.virtuscode.com.myapplication D/NEW_LOCATION: onLocation : {"accuracy":20.1,"activityConfidence":100,"activityName":"still","altitude":-1.0,"batteryIsCharging":true,"batteryLevel":0.65,"event":"motionchange","extras":{"nameValuePairs":{}},"heading":-1.0,"isMock":false,"isMoving":false,"isSample":false,"json":{"nameValuePairs":{"event":"motionchange","is_moving":false,"uuid":"798d4cb2-95f6-4f42-9d57-f80500d60a98","timestamp":"2017-12-06T22:43:09.192Z","odometer":441.9,"coords":{"nameValuePairs":{"latitude":48.3922355,"longitude":25.637632,"accuracy":20.1,"speed":-1.0,"heading":-1.0,"altitude":-1.0}},"activity":{"nameValuePairs":{"type":"still","confidence":100}},"battery":{"nameValuePairs":{"is_charging":true,"level":0.65}},"extras":{"nameValuePairs":{}}}},"latitude":48.3922355,"longitude":25.637632,"mLocation":{"mExtras":{"mAllowFds":true,"mFdsKnown":true,"mHasFds":false,"mClassLoader":{"packages":{"com.android.org.conscrypt":{"implTitle":"Unknown","implVendor":"Unknown","implVersion":"0.0","name":"com.android.org.conscrypt","specTitle":"Unknown","specVendor":"Unknown","specVersion":"0.0"}},"proxyCache":{}},"mMap":{"options":"{\"samples\":10}","battery_level":0.65,"isMoving":false,"uuid":"798d4cb2-95f6-4f42-9d57-f80500d60a98","event":"motionchange","requestId":1001,"is_charging":true,"odometer":441.87152}},"mProvider":"fused","mResults":[0.0,0.0],"mAccuracy":20.1,"mAltitude":0.0,"mElapsedRealtimeNanos":109627298000000,"mLat1":0.0,"mLat2":0.0,"mLatitude":48.3922355,"mLon1":0.0,"mLon2":0.0,"mLongitude":25.637632,"mTime":1512600189192,"mBearing":0.0,"mDistance":0.0,"mHasAccuracy":true,"mHasAltitude":false,"mHasBearing":false,"mHasSpeed":false,"mInitialBearing":0.0,"mIsFromMockProvider":false,"mSpeed":0.0},"mProvider":{"gpsEnabled":false,"networkEnabled":true,"permission":0,"status":3},"odometer":441.9,"speed":-1.0,"timestamp":"2017-12-06T22:43:09.192Z","uuid":"798d4cb2-95f6-4f42-9d57-f80500d60a98"}

PS. Thantks @christocracy for help with setuping project and

**Comment by christocracy** [comment]
Congrats, the plugin looks happy.

Now go for a walk / car ride and listen to the plugin tracking.

See the Wiki for Philosophy of Operation
