### ISSUE TITLE
Getting weird error message every now and then

### ISSUE THREAD

**Issue by pencilcheck** [transistorsoft/react-native-background-geolocation#372]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Galaxy Nexus
* React Native version (`react-native -v`): detached expo 1.15.2, expo said in package.json that it belongs to sdk 21.0.2
* Plugin config: 
```
{
      stationaryRadius: 100,

      foregroundService: true,
      locationUpdateInterval: 30000, // with distanceFilter = 0, set the interval = 30s

      distanceFilter: Platform.OS === 'ios' ? 10 : 0,
      desiredAccuracy: Platform.OS === 'ios' ? BackgroundGeolocation.DESIRED_ACCURACY_LOW : BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      locationAuthorizationAlert: {
        titleWhenNotEnabled: "Location services are not enabled",
        titleWhenOff: "Location services are OFF",
        instructions: "You must enable 'Always' for location services in the device Settings",
        cancelButton: "Cancel",
        settingsButton: "Settings"
      }
    }
```

## Expected Behavior

No errors

## Actual Behavior

Getting error such as
`TypeError: undefined is not an object (evaluating 'n.frames')
  at _currentSubscription`

## Steps to Reproduce

1. Let it run for awhile
2.
3.
4.

## Context

I don't know, just keep it running

**Comment by christocracy** [comment]
This doesn’t look related to the plugin.

The word “frames” seems to deal with some sort of view rendering mechanism.  The plugin isn’t involved with views.

**Comment by pencilcheck** [comment]
I'm getting this error from the onError callback from geolocation library. That's why I'm confused. I just wonder if you know anything about it.

**Comment by christocracy** [comment]
There is no *documented* error listener.  See [Events](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#zap-events) for a list of supported events.

**Comment by christocracy** [comment]
Show me how you're listening to this `onError` callback.

**Comment by pencilcheck** [comment]
```BackgroundGeolocation.on('location', this.onLocation, this.onError)```


Also

```
    BackgroundGeolocation.getCurrentPosition(this.onLocation, this.onError, {
      timeout: 30,      // 30 second timeout to fetch location
      maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
      desiredAccuracy: Platform.OS === 'ios' ? BackgroundGeolocation.DESIRED_ACCURACY_LOW : BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,  // Try to fetch a location with an accuracy of `10` meters.
      samples: 3,       // How many location samples to attempt.
    });
```

**Comment by christocracy** [comment]
What's the status on this?

**Comment by pencilcheck** [comment]
Still showing up in sentry, I still don't know why it is appearing.
