### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by honzababarik** [transistorsoft/react-native-background-geolocation#373]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: HUAWEI P10
* React Native version (`react-native -v`): 0.46.0
* Plugin config
```
const configuration = {
    // debug: true,
    // logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,
    preventSuspend: false,
    fastestLocationUpdateInterval: 2000,
    desiredAccuracy: 0, // highest accuracy
    distanceFilter: 25 // in meters distance between calls
  }
```

## Expected Behavior
Get location from Android device to be as quick as getting location on iOS Device.

## Actual Behavior
Getting location on Android is significantly slower.

## Steps to Reproduce
1. Use getCurrentPosition and wait for the result on both iOS and Android and compare the speed of both requests

## Context
We are trying to get users accurate location on screen view, since we display distance information to the object. 

This is getting the location, you see no extra options.

```
export const getCurrentLocation = (onLocation, onError) => {
  BackgroundGeolocation.getCurrentPosition((location) => {
    const locationData = getLocationData(location)
    onLocation(locationData)
  }, onError)
}
```

Works great on iOS, Android just seems slow. I am not quite sure whether it applies to all Android devices and versions, we did not do sufficient research to blame a specific version or combo. I still did want to ask if you'd think there might be some improvement we can do with the code to make Android quicker.

The use case is to get objects from server closest to the user and while we are getting the location from device and load data from server, the user sees spinner and that takes literally seconds till its finished, where as the server response is the quick part of it, getting the location is slower.

## Debug logs
--- 

I believe I might have missed something specific to Android configuration that might be the cause of this and could speed things up so I am more looking for advisory here.

Kudos for a great product! Saved us a lot of developer pain already!

**Comment by christocracy** [comment]
Yes, iOS Location-services is superior to Android.

You can set `{samples: 1}` in the options object provided to [`#getCurrentPosition`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-integer-samples-3-sets-the-maximum-number-of-location-samples-to-fetch--the-plugin-will-return-the-location-having-the-best-accuracy-to-your-successfn--defaults-to-3--only-the-final-location-will-be-persisted)

**Comment by christocracy** [comment]
Btw, please use a more descriptive issue title than "Android" in the future.

**Comment by honzababarik** [comment]
Thank you @christocracy , this was incredibly quick help :-) I thought it might have to do something with samples, amazing!

**Comment by scarlac** [comment]
Thanks for that gem, Chris. Also just debugged an issue where I saw 22s delay on Android but after setting `samples: 1` I got it down to 2s. I assume this potentially decreases accuracy but may be worth it for many folks.
