### ISSUE TITLE
How to implement the renewal of expired access token (JWT) via refresh token for the sync method

### ISSUE THREAD

**Issue by lashae** [transistorsoft/react-native-background-geolocation#374]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS or Android
* OS version: Ubuntu 16.04 
* Device manufacturer / model: GM5 and Emulator
* React Native version (`react-native -v`): 0.49.5
* Plugin config ---->
            foregroundService: true,
            notificationTitle: 'Title',
            notificationColor: '#f3f3f3',
            notificationText: 'Some notification text.',
            notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MAX,
            desiredAccuracy: 10,
            distanceFilter: 20,
            elasticityMultiplier: 3,
            stopOnTerminate: false,
            startOnBoot: true,
            forceReloadOnSchedule: true,
            forceReloadOnBoot: true,
            batchSync: true,
            autoSync: true,
            autoSyncThreshold: 20,
            url: 'http://...',
            debug: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            headers : { Authorization: 'Bearer .....' },

## Background
Our API implements JWT as a stateless authentication solution. As you might already know, JWT standard advises the usage of a "short lived access token" and "a long lived refresh token". 

When a user logins via our mobile application, an access token and a refresh token are issued and delivered to the client in the response. Mobile app saves those two tokens and uses the access token on the header of the upcoming request to authenticate. When access token expires, mobile app issues a token renewal request to our API with the refresh token it has saved before and gets the new access token along with the new refresh token.

## What we can do now
As of now, with the addition of `headers : { Authorization: "Bearer ${token}" },` configuration to the react-native-background-geolocation plugin (the plugin), we can embed a variable to the request header and eventually request is authenticated/authorized for every sync request made by the plugin.

## The Issue
Since access token is short lived, it expires (after 60 minutes in our implementation) and clients are required to get a new access token with the refresh token they have. 

The challenge is; since react-native projects are living on the javascript engine and this engine is terminated whenever the application is sent to background; we need to solve this issue right before each sync request of the plugin.

So we need to;
- Hook somewhere/some-event of the plugin,
- Make an async request to our server to renew our access token if it is about to expire,
- The plugin should wait in the meanwhile,
- **After the completion of this async request** we will be able to tell the plugin which header is going to be included within the sync request. 
- And the plugin will issue the sync request to our server.

Question is: How to implement this? Other solution outlines or any other advices would be highly appreciated as well.

**Comment by lashae** [comment]
May I kindly ask for your support for this issue? Is there any possibility to have a callback implemented at the header level? Like:

```
foregroundService: true,
notificationTitle: 'Title',
// ...
headers : SomeService.getHeaders(),
// ...
```

Or is `heartBeat` the only way to renew the access token I have explained in the original post?

**Comment by jpudysz** [comment]
I have the same issue. Our `AccessToken` last for 60 min and after this time it will return 401 for any API request.

**Comment by lashae** [comment]
@christocracy Any chance you can advise?

**Comment by christocracy** [comment]
Why don't you listen to the [`http`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#http) event.  When you get 401, refresh your tokens.

**Comment by lashae** [comment]
Assume we listen to the `http` event and detect that we got 401. We refresh the token on the event listener and assigned it to the variable used in the `headers` configuration of the plugin; is it possible to retry to sync right after the variable assignment?

**Comment by christocracy** [comment]
You're free to execute the [`#sync`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#syncsuccessfn-failurefn) method any time you wish.

**Comment by lashae** [comment]
This totally makes sense! Thank you very much.

@jpudysz If you are OK with the result, I would like to close the issue.

**Comment by thienban** [comment]
Hi,
I refresh my token in each `http` error.  I call `setConfig` in the refresh function to change the `url`.
But the config is not change.
My example : 
`export function refreshToken() {
	return function(dispatch, getState) {
		let bgGeo = window.BackgroundGeolocation;
			if(bgGeo) {
				let settings = getState().settings;
				let serverApi = settings.trackingServer;
				let appkey =settings.trackingServerAppKey;
				let appToken = settings.trackingServerAppToken;
				dispatch(fetchGcLocation(serverApi, appkey, appToken))
				.then((token)=> {
						setConfigBglocation(serverApi, token);
						console.log("- setConfigBglocation");
				});
			}
	};
}
function setConfigBglocation(serverURL, token) {
	let bgGeo = window.BackgroundGeolocation;
	bgGeo.setConfig({
		url: serverURL+"record?token="+token
	  }, function(){
		console.log("- setConfig success");
	  }, function(){
		console.warn("- Failed to setConfig");
	  });
}`

**Comment by christocracy** [comment]
**Syntax highlighting**
- 1 back-tick = inline 
- 3 back-tick = multi-line.

**Comment by christocracy** [comment]
@thienban 
```
let bgGeo = window.BackgroundGeolocation
```
This is Cordova.  This is the **React Native** version.  You're not in the right place.

**Comment by thienban** [comment]
Sorry, i will search the topic in Cordova section.
