### ISSUE TITLE
'React/RCTEventEmitter.h' file not found during build

### ISSUE THREAD

**Issue by seaware** [transistorsoft/react-native-background-geolocation#377]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS
* OS version: 11.2
* Device manufacturer / model: iPhone 6 (simulated)
* React Native version (`react-native -v`): 0.49.3
* Plugin config

## Expected Behavior

Expected build to be successful.

## Actual Behavior

Xcode v9.2 reported build failure.

## Steps to Reproduce

1. Followed installation steps at https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md but build failed.
2. Tried doing a clean build (shift-command-K) but this didn't help.
3. I noticed the problem is nearly the same as this closed issue, but the versions are more recent: https://github.com/transistorsoft/rn-background-geolocation-demo/issues/37

## Context

Trying to install/build/run the background geolocation component for the first time.

## Debug logs

```
In file included from /Users/frankcanova/ReactNative/GeoLocationSampleApp-0/node_modules/react-native-background-geolocation/ios/RNBackgroundGeolocation/RNBackgroundGeolocation.m:8:
/Users/frankcanova/ReactNative/GeoLocationSampleApp-0/node_modules/react-native-background-geolocation/ios/RNBackgroundGeolocation/RNBackgroundGeolocation.h:18:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import <React/RCTEventEmitter.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by christocracy** [comment]
Something is incorrectly configured in your project.  The plugin isn't finding `React`.

See if any of [these links](https://www.google.ca/search?q=%27React%2FRCTEventEmitter.h%27+file+not+found&oq=%27React%2FRCTEventEmitter.h%27+file+not+found&aqs=chrome..69i57j0j69i60j69i61l3.886j0j4&sourceid=chrome&ie=UTF-8) helps.  

You're not using Pods, I assume?

Try installing installing the plugin into a fresh react-native app.  You'll probably find you don't have the issue in a new project.

**Comment by seaware** [comment]
Thanks. I think I've traced it to when I'm creating a fresh react-native app. This is my order...
```
react-native init Foo
cd Foo
npm install react-native-background-geolocation --save
```
From this point forward, ```react-native -v``` reports that the native version is missing. What's the proper sequence to initialize both react-native and the new geolocation component? I'm normally following the steps in ```https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md``` after this point. Sorry for the newbie issue here.

**Comment by christocracy** [comment]
Why don't you use the [`react-native link` instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS-RNPM.md)?

**Comment by seaware** [comment]
In those instructions, the ```react-native link...``` steps need to be done inside a react-native project. If I use ```react-native init Foo``` before those instructions to create the project, the first step of the instructions ```npm install --save react-native-background-geolocation``` removes lots of the packages so react-native doesn't run any longer. I get this message:
```
+ react-native-background-geolocation@2.10.1
added 4 packages, removed 889 packages and updated 14 packages in 13.865s
```
I must be missing something obvious. What's the proper sequence to initialize both react-native and the new geolocation component?

**Comment by christocracy** [comment]
```
$ react-native init Foo
$ cd Foo
$ npm install react-native-background-geolocation

$ react-native link react-native-background-geolocation
$ react-native link react-native-background-fetch
$ react-native link cocoa-lumberjack
```
