### ISSUE TITLE
Email from apple: "Your app appears to register with the Apple Push Notification service"

### ISSUE THREAD

**Issue by markrickert** [transistorsoft/react-native-background-geolocation#379]
## Your Environment
* Plugin version: 
* Platform: iOS or Android
* OS version: 2.10.1
* Device manufacturer / model: Apple iPhone 6
* React Native version (`react-native -v`): `react-native-cli: 2.0.1` / `react-native: 0.42.3`
* Plugin config:

```js
{
      // Geolocation Config
      desiredAccuracy: 0, // Highest accuracy
      distanceFilter: 5, // Get a location every 5 meters
      stopTimeout: 0, // in minutes. The time to wait before turning off location services completely
      stopAfterElapsedMinutes: 0,
      stopOnStationary: false,

      // Geofencing and tracking option
      stationaryRadius: 25, // Start aggressively tracking location after 25 meters of change.
      activityRecognitionInterval: 1000, // Recognize activity changes every second instead of the default 10 seconds

      // Application config
      debug: false, // Hear sounds for background-geolocation life-cycle.
      logLevel: __DEV__ ? BackgroundGeolocation.LOG_LEVEL_VERBOSE : BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false, // Allow the background-service to continue tracking when user closes the app.
      startForeground: false // Setting for android to not show notifications
}
```

## Expected Behavior

After uploading a build to testflight, we get an email from apple:

> Dear developer,
>
> We have discovered one or more issues with your recent delivery for "App Name". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
> Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
>
> After you've corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
>
> Regards,
>
> The App Store team

## Actual Behavior

If debug mode is explicitly `false`, the code to spin up the logging notifications shouldn't run.

## Steps to Reproduce
1. install plugin and implement
2. compile in release mode and upload to testflight
3. you'll get an email from apple

## Context

I really would like to make sure that after implementing this plugin that it's not going to try and ask the user permission for push notifications on the app's behalf.

**Comment by christocracy** [comment]
The plugin has nothing to do with push notifications.  The plugin is not responsible here.

Check your own config.

**Comment by markrickert** [comment]
Sorry, I got the logging local notifications confused with push notifications. I think i found the culprit - `react-native-permissions`. :/
