### ISSUE TITLE
Access to motion and fitness data

### ISSUE THREAD

**Issue by normanrz** [transistorsoft/react-native-background-geolocation#38]
When I start my app it asks for a permission to access motion and fitness data. Why is this necessary? Is there a way to avoid it?

**Comment by christocracy** [comment]
[disableMotionActivityUpdates: true](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/api.md#param-boolan-disablemotionactivityupdates-false)

You will no longer receive the `activity` data in your [recorded locations](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Location-Data-Schema)

**Comment by normanrz** [comment]
Thanks, I somehow missed that in the docs!

**Comment by ejswenson15** [comment]
For me it is for MOTION access asking the FIRST time the app is installed, but not AGAIN after that.

**Comment by ejswenson15** [comment]
WITH disableMotionActivityUpdates: true
