### ISSUE TITLE
App store submission issue

### ISSUE THREAD

**Issue by doananh234** [transistorsoft/react-native-background-geolocation#385]
Hi! Transistorsoft Team.

I upload the new app to app store. But Apple  reject it.

> 
> Since your iTunes Connect status is Rejected, a new binary will be required. Make the desired metadata changes when you upload the new binary.
> 
> Guideline 2.5.1 - Performance - Software Requirements
> 
> Your app uses the HealthKit or CareKit APIs but does not indicate integration with the Health app in your app description and clearly identify the HealthKit and CareKit functionality in your app's user interface.
> 
> Next Steps
> 
> To resolve this issue, please revise your app description to specify that your app integrates with the Health app.
> 
> Guideline 2.5.4 - Performance - Software Requirements
> 
> Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not have any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to include features that require the persistent use of real-time location updates while the app is in the background.
> 
> If your app does not require persistent real-time location updates, please remove the "location" setting from the UIBackgroundModes key. You may wish to use the significant-change location service or the region monitoring location service if persistent real-time location updates are not required for your app features.

 I don't use heartbeat, and motion. When i remove NSMotionUsageDescription key, always receive issue:

> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data.

**My config:**
```
BackgroundGeolocation.configure({
        desiredAccuracy: 0,
        distanceFilter: 1,
        stopTimeout: 1,
        disableMotionActivityUpdates: true,
        geofenceProximityRadius: 1000,
        geofenceInitialTriggerEntry: true,
        debug: false, 
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, 
        startOnBoot: true,
      }, (state) => {
        BackgroundGeolocation.getCurrentPosition((data) => {}, (errorCode) => {
          switch (errorCode) {
            case 0:
              break;
            case 1:
              Tools.showGoToSettingPopUp(null, "Please enable location service in order to get notifications.", 'Airbrows requires your location.');
              break;
            case 2:
              break;
            case 408:
              break;
          }
        })
        this.addGeofences(this.props.nearByBusiness);
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

        if (!state.enabled) {
          BackgroundGeolocation.startGeofences(function(state) {
          });
        } else {
        }
      });
```
Can you help me?

**Comment by christocracy** [comment]
>I don't use heartbeat, and motion. When i remove NSMotionUsageDescription key, always receive issue:

You may not, but the plugin *does*.  The plugin uses `MotionActivityManager` optimize detecting when the device is moving / stationary.

If you don't want to use it, [`disableMotionActivityUpdates: true`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#activity-recognition-ios-options)

>If your app does not require persistent real-time location updates, please remove the "location" setting from the UIBackgroundModes key

If Apple doesn't allow your app to use background location capability, you must un-check `[x] Location` and configure the plugin with `useSignificantChangesOnly: true` -- you will receive a location about every **1000 meters**.
![](https://dl.dropboxusercontent.com/s/z0ueht1hviwjngl/Screenshot%202018-01-16%2008.57.11.png?dl=1)
