### ISSUE TITLE
using background location on iOS without asking for healthkit/fitness permission?

### ISSUE THREAD

**Issue by blackorchidz** [transistorsoft/react-native-background-geolocation#386]
## Your Environment
* Plugin version: Latest
* Platform: iOS
* OS version: 11
* Device manufacturer / model: All iphone
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior
Should only ask for Background location, should not ask to access healtkit.

## Actual Behavior
When we install the App its asking for Health Kit (motion and fitness  data)

## Steps to Reproduce
Opening the app.

## Debug logs
N/A

**Comment by christocracy** [comment]
The plugin is highly optimized to use [`CMMotionActivityManager`](https://developer.apple.com/documentation/coremotion/cmmotionactivitymanager) for determining when device is stationary / moving, as well as recording the motion-activity (eg: `on_foot`, `in_vehicle`).

If you don't want this, [`disableMotionActivityUpdates: true`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#activity-recognition-ios-options)

**Comment by blackorchidz** [comment]
Thank you for the Very Quick answer. Is this going to be updated in the feature? Native asp does not require fitness data for Geofencing?

**Comment by christocracy** [comment]
I don't see a need to update anything.  `disableMotionActivityUpdates: true` will tell the plugin not to use `CMMotionActivityManager` and Health & Fitness permission will not be requested.

**Comment by blackorchidz** [comment]
Will i still have access to the users location? When there enter the area and leave the area?

**Comment by christocracy** [comment]
Yes, `CMMotionActivityManager` has nothing to do with that.

**Comment by blackorchidz** [comment]
ok thanks for this :)

**Comment by BenBach** [comment]
If we disable this will it drain the battery? For now, we just need to use enter and exit geofence events. We don't need to track the way between the geofences.
Thank you very much in advance

**Comment by christocracy** [comment]
No, it’ll be fine
