### ISSUE TITLE
Feature request - requestPermissions

### ISSUE THREAD

**Issue by mckn** [transistorsoft/react-native-background-geolocation#388]
* Plugin version: n/a
* Platform: iOS and Android
* OS version: n/a
* Device manufacturer / model: n/a
* React Native version (`react-native -v`): n/a
* Plugin config: n/a

## Expected Behavior
It would be pretty handy to have a function that you can call to requestPermissions for location services. Then it would be easier to control the permission alerts and also you would not need a dependency on another library to have that functionality.

## Actual Behavior
n/a

## Steps to Reproduce
n/a

## Context
Control when the permissions dialog appear in the app.

## Debug logs
n/a

**Comment by christocracy** [comment]
Dealing with permissions in Android is not fun.

**Comment by mckn** [comment]
Okay, meaning that you don't this this is a good idea?

**Comment by christocracy** [comment]
I'd like to avoid dealing with permissions in the plugin.  What's wrong with PermissionsAndroid.  I don't mind using this dependency.
