### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by romanwroclawski** [transistorsoft/react-native-background-geolocation#390]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS
* OS version: 9.3 (Deployment Target)
* Device manufacturer / model: Simulator
* React Native version (`react-native -v`): 0.52.0
* Plugin config: Example Usage
* Xcode Version: 8.3.1 (8E1000a)

## Expected Behavior
* Project should build with module

## Actual Behavior
* When running the project after following the https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md directions, I get a Apple Mach-O Linker Error "Linker command failed with exit code 1.

## Steps to Reproduce
1. Install package using npm command
2. Follow: https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS.md directions
3. Run project

**Comment by christocracy** [comment]
Show me the full error.  You should find info on this tab:
![](https://dl.dropboxusercontent.com/s/390pqypdvg7p4uh/Screenshot%202018-01-18%2017.56.16.png?dl=1)

**Comment by romanwroclawski** [comment]
@christocracy thank you for the reply. Below is a screenshot of the error I see on that screen. I thought the following might be the culprit, but no luck with it either: https://stackoverflow.com/questions/45994854/xcode-8-3-framework-not-found-fileprovider-for-architecture-armv7

Based on that link, do you think my version of XCode might be the issue?
![screen shot 2018-01-19 at 11 45 23 am](https://user-images.githubusercontent.com/3969849/35168576-453d1dfc-fd0e-11e7-9a70-5d58f707cec5.png)

**Comment by christocracy** [comment]
Always use the latest version of XCode, *always*.  This 100% certainly your problem.
