### ISSUE TITLE
Configuration Question: Stop on Movement

### ISSUE THREAD

**Issue by ntomallen** [transistorsoft/react-native-background-geolocation#391]
## Your Environment
* Plugin version: 2.10.1
* Platform: All
* OS version: All
* Device manufacturer / model: All
* React Native version (`react-native -v`): 0.50.1

## Expected Behavior
I have a question about configuration, being new to the plugin. I've been pouring over the documentation, but with the plethora of options, I thought I'd check for input. Let me know if there is a better forum for this!

My usecase: I want to detect when a user has visited a location for, say, 5 minutes. I don't need location updates while the user is traveling, and if possible I'd like to only receive the geolocation once the user has stopped moving. One thought I had was using on motion change, but I'm not sure what the ideal configuration should be for that. 

## Actual Behavior
n/a

## Steps to Reproduce
n/a

## Context
Detecting when a user visits any location for several minutes.

## Debug logs
n/a

**Comment by christocracy** [comment]
Sorry I missed this question.  You could [`#addGeofence`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#addgeofenceconfig-successfn-failurefn) with `notifyOnDwell: true, loiteringDelay: 1000*60*5}`.
