### ISSUE TITLE
Cancelling locationAuthorizationAlert alerts

### ISSUE THREAD

**Issue by ejkkan** [transistorsoft/react-native-background-geolocation#393]
The lib triggers system alerts for users when changing Location permissions for the app.
Could be configured with locationAuthorizationAlert.

But we do not want this behavior when changing permissions. We want to cancel the alerts.

## Your Environment
* Plugin version: 2.9.4
* Platform: iOS
* OS version:
* Device manufacturer / model: all
* React Native version (`react-native -v`): 0.51.0
* Plugin config

## Expected Behavior

Go in to app settings, change Location permissions between Whilte Using and Always.
No systemalert should have to appear.

## Actual Behavior
Go in to app settings, change Location permissions between Whilte Using and Always.
System alert appears telling user that permissions have been changed.

## Steps to Reproduce
N/A

## Context
We want to be able to configure the locationAuthorizationAlert to not show at all. This is not explained the in the docs

**Comment by christocracy** [comment]
Duplicate #183
