### ISSUE TITLE
IOS notifications on position and permission change

### ISSUE THREAD

**Issue by mckn** [transistorsoft/react-native-background-geolocation#394]
## Your Environment
* Plugin version: 2.9.4
* Platform: iOS
* OS version: iOS 11
* Device manufacturer / model: simulator 
* React Native version: 0.50
* Plugin config

## Expected Behavior
No notifications appear from the app

## Actual behaviour 
Sometimes it seems like we receive local notifications from the app when we put the app in background and goes to the settings and change location permissions for the app.

Is it possible to turn that behaviour off?

## Steps to Reproduce
1. Open the app and config it to use background location.
2. Go into settings and toggle off the location permissions.
3. A notification will appear regarding the permission change.

## Context
N/A

## Debug logs
N/A

**Comment by christocracy** [comment]
What sort of local notification?

**Comment by mckn** [comment]
The once appearing at the top of the screen. Like a ordinary notification. I will see if I can get a screenshot.

**Comment by em222iv** [comment]
<img width="490" alt="skarmavbild 2018-01-23 kl 15 37 54" src="https://user-images.githubusercontent.com/5379414/35281720-f02aac28-0053-11e8-8852-fccd081c3d9b.png">
<img width="452" alt="skarmavbild 2018-01-23 kl 15 37 59" src="https://user-images.githubusercontent.com/5379414/35281721-f0474b8a-0053-11e8-94c1-e8e858098918.png">
<img width="420" alt="skarmavbild 2018-01-23 kl 15 38 01" src="https://user-images.githubusercontent.com/5379414/35281722-f0693b1e-0053-11e8-9e28-42db1b160ca2.png">
<img width="417" alt="skarmavbild 2018-01-23 kl 11 41 41" src="https://user-images.githubusercontent.com/5379414/35281723-f0846c36-0053-11e8-8861-f34f61e96958.png">

Also one displaying when one changes Location Permissions saying for example: 
Authorization changed to level 3

**Comment by christocracy** [comment]
See [`@config debug`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#wrench-logging--debug-options).  Those are there to assist you during development.

**Comment by mckn** [comment]
Okay, thanks for the quick reply @christocracy 👍
