### ISSUE TITLE
[Android/Bug] Error 408 - timed out when running in emulator

### ISSUE THREAD

**Issue by mckn** [transistorsoft/react-native-background-geolocation#395]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 25
* Device manufacturer / model: Emulator
* React Native version 0.51.0
* Plugin config:  {} // default

## Expected Behavior
I should be able to get a location in the Android Emulator

## Actual Behavior
I have tried to change the desiredAccurancy, timeout, maxAge etc. but it doesnt seem to work. When we request a location via `getCurrentPosition()` it takes some time but then we get a timeout.

## Steps to Reproduce
1. Start application
2. Enable location permissions
3. Ask for current position
4. wait...
5. Error 408, timeout will occur.

## Context
I was trying to get the current location

## Debug logs
N/A

**Comment by christocracy** [comment]
408 = timeout.  the device failed to return a location and the location-manager gave up.

This could happen for a number of reasons, including driving through a concrete tunnel.

[See docs](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#failurefn-paramters)

**Comment by mckn** [comment]
@christocracy well, that I understand but should it work in the android emulator? I tried to set/send the gps coordinates to the emulator but without any success.

**Comment by mckn** [comment]
Also, it seems to work when I use the navigator.geolocation service.

**Comment by christocracy** [comment]
Many people use the plugin in the simulator, yes.  I don't use the Android simulator myself.  The plugin relies on motion-detection APIs and the simulator has poor support for this.

Location-services are like a tap of water.  The plugin turns the taps on and provides you the water that flows out.

The plugin turned the taps on but no water came out.

See [Debugging](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging)

**Comment by UnSket** [comment]
@christocracy Are there any tips to solve this?

**Comment by UnSket** [comment]
I mean when problem on real devices

**Comment by christocracy** [comment]
This issue is not about *real* devices, it's about "Error 408 - timed out when running **in emulator**".

Error 408 means the device's location API failed to return a location.  This can happen for a number of reasons:
- User has configured their Settings->Location->Mode->"Device Only" (ie: GPS only) and the device is sitting in side a building where GPS is impossible.
- User has disabled Wifi
- Device is inside a tunnel or subway.
- Driving through mountains.
etc, etc, etc.

It's like turning on your water tap and no water flows out.

**Comment by UnSket** [comment]
Ok, thanks

**Comment by christocracy** [comment]
I often choose HTTP-type error codes.  I chose 408 because in HTTP, it means [408 Request Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408)
