### ISSUE TITLE
Notifications when entering a geofence area do not work

### ISSUE THREAD

**Issue by josianeReis** [transistorsoft/react-native-background-geolocation#398]
## Your Environment
* Plugin version:
* Platform: iOS
* OS version: MacOS Sierra v12.10.6
* Device manufacturer / model: Iphone 7
* React Native version (`react-native -v`): v0.44.3
* Plugin config

## Expected Behavior

I want to create areas of geofence within my application and cause when the user goes through these areas, your phone receives push notifications with certain information.

## Actual Behavior

I created two areas of geofence in my application both with a radius of 100 meters, when I start the application even though I am already in the first area I get the notification that I entered it, but when I move and enter the second area, nothing happens even when I put the notifyOnEntry to true

## Steps to Reproduce

```
import BackgroundGeolocation from 'react-native-background-geolocation'
const startMock = () => {
  alert('start')
  BackgroundGeolocation.configure({
    desiredAccuracy: 0,
    distanceFilter: 5,
    stationaryRadius: 25,
    locationUpdateInterval: 1000,
    foregroundService: false,
    stopOnTerminate: false,
    startOnBoot: true,
  }, (state) => {
  // Add some geofences.
  alert('state ' + JSON.stringify(state))
  console.log('state ', state)
    BackgroundGeolocation.addGeofences([
      {
        identifier: 'ZONE_OF_INTEREST',
        notifyOnEntry: true,
        notifyOnExit: true,
        radius: 150,
        latitude: -18.891566,
        longitude: -48.257813,
      },
      {
        identifier: 'ZONE_OF_EXIT',
        notifyOnEntry: true,
        notifyOnExit: true,
        radius: 150,
        latitude: -18.895700,
        longitude: -48.259236,
      },
    ])

    if (!state.enabled) {
      BackgroundGeolocation.startGeofences((inState) => {
        console.log('- Geofence-only monitoring started', inState.trackingMode)
      })
    }
  })

  // Listen to geofences
  BackgroundGeolocation.on('geofence', function(params) {
    if (params.identifier === 'ZONE_OF_INTEREST') {
      alert('entrei')
    }
    if (params.identifier === 'ZONE_OF_EXIT') {
      alert('eu sai')
    }
  })
}

export { startMock }
```
This is what I did with the setup, I believe I'm using it the wrong way, so can you give me a hand?

**Comment by christocracy** [comment]
Minimum reliable geofence radius is 150 meters.

**Comment by josianeReis** [comment]
I tested with the radius> 150 and create 3 different areas of geofence, but I only get notification of one of them, even though I entered the others, I used the following code:

```
bgGeo.on('geofence', (geofence) => {
    if (geofence.action === 'ENTER') {
      alert(`voce entrou na area ${geofence.identifier}`)
    }
    if (geofence.action === 'EXIT') {
      alert(`voce saiu da area ${geofence.identifier}`)
    }
  })
```
Is it correct to do the verification this way, or should I use another method?

**Comment by christocracy** [comment]
Increase radius to `200`.  I test every day with geofences of 200 meters and they *never* fail.

**Comment by josianeReis** [comment]
It worked, thanks.
