### ISSUE TITLE
Incorrect wiki link in README.md

### ISSUE THREAD

**Issue by dalhundal** [transistorsoft/react-native-background-geolocation#4]
In `README.md`, under the heading *'Help, It doesn't work!'* there is an incorrect link.

*'See the wiki'* points to
    
    https://github.com/transistorsoft/cordova-background-geolocation/wiki

whereas, it should be

    https://github.com/transistorsoft/react-native-background-geolocation/wiki

**Comment by christocracy** [comment]
Thanks

On Friday, August 28, 2015, Dal Hundal <notifications@github.com> wrote:

> In README.md, under the heading *'Help, It doesn't work!'* there is an
> incorrect link.
>
> *'See the wiki'* points to
>
> https://github.com/transistorsoft/cordova-background-geolocation/wiki
>
> whereas, it should be
>
> https://github.com/transistorsoft/react-native-background-geolocation/wiki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/4>
> .
>


-- 
Snet form Gmail Mobile
