### ISSUE TITLE
Followed installation instructions and got 'Lexical Preprocessor Issue'

### ISSUE THREAD

**Issue by stevepeart** [transistorsoft/react-native-background-geolocation#40]
I followed the iOS installation guide and received the following build failure errors:

/my_project/node_modules/react-native-background-geolocation/<module-includes>:1:1: Umbrella header for module 'TSLocationManager' does not include header 'Settings.h'

/steve/Roadwayz/node_modules/react-native-background-geolocation/<module-includes>:1:1: Umbrella header for module 'TSLocationManager' does not include header 'TSLogger.h'

Either there's something wrong with the component, or there's something not made clear in the installation instructions, I have no real experience with obj-c in iOS, so I don't know where to go from here.

**Comment by christocracy** [comment]
I need to push an update.

On Tuesday, December 1, 2015, stevepeart <notifications@github.com> wrote:

> I followed the iOS installation guide and received the following build
> failure errors:
>
> /my_project/node_modules/react-native-background-geolocation/:1:1:
> Umbrella header for module 'TSLocationManager' does not include header
> 'Settings.h'
>
> /steve/Roadwayz/node_modules/react-native-background-geolocation/:1:1:
> Umbrella header for module 'TSLocationManager' does not include header
> 'TSLogger.h'
>
> Either there's something wrong with the component, or there's something
> not made clear in the installation instructions, I have no real experience
> with obj-c in iOS, so I don't know where to go from here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/40>
> .
>


-- 
Snet form Gmail Mobile

**Comment by stevepeart** [comment]
I updated to the latest and removed/re-ran through the installation instructions, now I am receiving this:

duplicate symbol _llvm.cmdline in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
duplicate symbol _llvm.embedded.module in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
duplicate symbol _llvm.cmdline in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
duplicate symbol _llvm.embedded.module in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
duplicate symbol _llvm.cmdline in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
duplicate symbol _llvm.embedded.module in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
duplicate symbol _llvm.cmdline in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
duplicate symbol _llvm.embedded.module in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
duplicate symbol _llvm.cmdline in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
duplicate symbol _llvm.embedded.module in:
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
    ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
ld: 10 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by christocracy** [comment]
I'll check it out

On Tuesday, December 1, 2015, stevepeart <notifications@github.com> wrote:

> I updated to the latest and removed/re-ran through the installation
> instructions, now I am receiving this:
>
> duplicate symbol _llvm.cmdline in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
> duplicate symbol _llvm.embedded.module in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
> duplicate symbol _llvm.cmdline in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
> duplicate symbol _llvm.embedded.module in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
> duplicate symbol _llvm.cmdline in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
> duplicate symbol _llvm.embedded.module in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
> duplicate symbol _llvm.cmdline in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
> duplicate symbol _llvm.embedded.module in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
> duplicate symbol _llvm.cmdline in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
> duplicate symbol _llvm.embedded.module in:
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>
> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
> ld: 10 duplicate symbols for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/40#issuecomment-161080534>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
I just spawned a fresh new RN app and followed the directions.  Everything
is fine.

On Tue, Dec 1, 2015 at 4:19 PM, Chris Scott <christocracy@gmail.com> wrote:

> I'll check it out
>
> On Tuesday, December 1, 2015, stevepeart <notifications@github.com> wrote:
>
>> I updated to the latest and removed/re-ran through the installation
>> instructions, now I am receiving this:
>>
>> duplicate symbol _llvm.cmdline in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
>> duplicate symbol _llvm.embedded.module in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(SOMotionDetector.o)
>> duplicate symbol _llvm.cmdline in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>> duplicate symbol _llvm.embedded.module in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(Settings.o)
>> duplicate symbol _llvm.cmdline in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
>> duplicate symbol _llvm.embedded.module in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(LocationDAO.o)
>> duplicate symbol _llvm.cmdline in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
>> duplicate symbol _llvm.embedded.module in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSReachability.o)
>> duplicate symbol _llvm.cmdline in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
>> duplicate symbol _llvm.embedded.module in:
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLogger.o)
>>
>> ../node_modules/react-native-background-geolocation/RNBackgroundGeolocation/TSLocationManager.framework/TSLocationManager(TSLocationManager.o)
>> ld: 10 duplicate symbols for architecture x86_64
>> clang: error: linker command failed with exit code 1 (use -v to see
>> invocation)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/react-native-background-geolocation/issues/40#issuecomment-161080534>
>> .
>>
>
>
> --
> Snet form Gmail Mobile
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
