### ISSUE TITLE
React Project could not find logback-android-classic.jar

### ISSUE THREAD

**Issue by FelipePaiva1992** [transistorsoft/react-native-background-geolocation#400]
Application stopped building in debug or production.
Show me the message `Could not find logback-android-classic.jar (com.github.tony19:logback-android-classic:1.1.1-6)`

## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 8.0.1
* Device manufacturer / model: Google Pixel XL
* React Native version (`react-native -v`): 0.50.0
* Plugin config

## Expected Behavior

The react native app should compiling on the Device

## Actual Behavior

The react native crash when try to compiling

`
What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-background-geolocation'.
      > Could not find logback-android-classic.jar (com.github.tony19:logback-android-classic:1.1.1-6).
        Searched in the following locations:
            https://jcenter.bintray.com/com/github/tony19/logback-android-classic/1.1.1-6/logback-android-classic-1.1.1-6.jar
`

## Steps to Reproduce

1. Just run 'react-native run-android'

## Context

I'am try to compiling the react native project.
I had the same problem runs the Demo App

## Debug logs

n/a

**Comment by christocracy** [comment]
Are you still having this issue?  Someone in another project was having a similar issue.

**Comment by christocracy** [comment]
I deleted my `.gradle/caches` and rebuilt my app from scratch.  I have no issue fetching the `logback-android-classic` dependency [required by the plugin](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/build.gradle#L33).

**Comment by christocracy** [comment]
If you click the link [https://jcenter.bintray.com/com/github/tony19/logback-android-classic/1.1.1-6/logback-android-classic-1.1.1-6.jar](https://jcenter.bintray.com/com/github/tony19/logback-android-classic/1.1.1-6/logback-android-classic-1.1.1-6.jar), `logback-android-classic-1.1.1-6.jar *is* served to me.

**Comment by FelipePaiva1992** [comment]
I think at some point the download of this file has corrupted, so the problem was happening. 
With your solution, deleting `.gradle/cache`,  the problem has been solved. 

Thank you for the quick return

**Comment by ronal2do** [comment]
Same problem with `logback-android-core-1.1.1-6.pom`

**Comment by FelipePaiva1992** [comment]
Try clean all .gradle/cache folder

**Comment by ronal2do** [comment]
It did not work for me.

**Comment by xSmoggeRx** [comment]
Any solution here? I have the same problem..

**Comment by christocracy** [comment]
@xSmoggeRx This issue is closed.  Post the following information in addition to the error message.

## Your Environment
### Plugin version: 
### Platform: 
### OS version: 
### Device manufacturer / model: 
### React Native version (react-native -v):
