### ISSUE TITLE
[New Feature] Android "Headless Mode"

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/react-native-background-geolocation#402]
On Android, when you terminate your app with the **`BackgroundGeolocation`** plugin configured with **`stopOnTerminate: false`**, your Javascript code *is completely terminated* &mdash; only the plugin's native Android background service continues running.  If you've configured the plugin with an **`#url`**, its Android background Service will continue posting locations to your server.

But what if you need to implement some custom business logic in this "headless" state, such as posting a local-notification or executing **`#getCurrentPosition`** in a **`heartbeat`** event?

The **`BackgroundGeolocation`** plugin for now provides a mechanism for you to implement your own custom code to handle all the plugin's events while in the "Headless" state (`heartbeat, location, motionchange, geofence`, etc).

For more information, see the Wiki [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode).

**Comment by seanmorton** [comment]
This is fantastic! I will be adding this functionality to my Android app shortly. Thank you for supporting this.

Quick question: I know HeadlessJS is only available for Android, but I just want to double check that  this functionality is not yet available in iOS at all. Is it true that even with `preventSuspend: true` configured, iOS will not execute JS logic if the app is terminated (swiped up by the user)? Or should this be possible with `preventSuspend`?

**Comment by christocracy** [comment]
It doesn't make sense to talk of "Headless" in the context of iOS.

It's like introducing a new component for diesel engines (ie: Android) that makes them burn cleaner.

iOS doesn't run on diesel, nor does it have the concept of "background services" that continue running after the app is terminated.

iOS *does* in fact have background-services, but they're not publicly available to us.  For example, when you monitor a geofence, this geofence will continue to be monitored in spite of app terminate.  When a transition event occurs with that geofence, iOS will reboot your *entire* app (including your Javascript) in the background to service that event.  The significant-changes API operates in the same manner.

It's this "stationary-geofence" that the plugin monitors around the device's last-known location which is key to the iOS plugin's ability to continue tracking in spite of app terminate.

**Comment by christocracy** [comment]
> if the app is terminated (swiped up by the user)? Or should this be possible with preventSuspend?

On iOS, when the user terminates the app, *everything* is terminated.  Only the geofences (especially the "stationary geofence") the plugin registered (in addition to significant-changes API) continue to be monitored automatically by the OS.

**Comment by seanmorton** [comment]
Makes sense, so the only way to continue executing _anything_ in an iOS app after it has been terminated is to subscribe to one of these background services that will reboot the entire app upon an event firing. 

Thanks for the detailed response!

**Comment by christocracy** [comment]
>so the only way to continue 

The plugin already does this for you.  All you need to do is configure stopOnTerminate: false.
