### ISSUE TITLE
Does this framework support android 8.0? background geo

### ISSUE THREAD

**Issue by dustturtle** [transistorsoft/react-native-background-geolocation#404]
We know that something has changed with the background stuffs on android 8.0. RT. Thanks a lot.

**Comment by christocracy** [comment]
Yes.  foregroundService: true is enforced on Android 8.

https://shop.transistorsoft.com/blogs/news/android-oreo-version-8

**Comment by christocracy** [comment]
foregroundService: true is the most robust mode anyway for long-term device tracking.  Makes it highly unlikely to be terminated by OS due to memory pressure from other apps.

**Comment by andwaal** [comment]
@christocracy is it possible to run the plugin on Android8 without _ foregroundService: true_ if only geofences is used?

**Comment by christocracy** [comment]
@andwaal No.

**Comment by juhana** [comment]
Does the OS enforce `foregroundService: true` when the plugin is used with geofences only? That is, is it technically even possible to have geofences in the background without using a foreground service?

**Comment by christocracy** [comment]
The plugin’s *needs* to run as a foreground-service to periodically run its geospatial query to load geofences within the `geofenceProximityRadius`

You cannot use geofences-only mode without a foreground service
