### ISSUE TITLE
Need info about Android fusedlocationprovider

### ISSUE THREAD

**Issue by manju-ms** [transistorsoft/react-native-background-geolocation#407]
I need a information about whether this plugin is using FusedLocationProvider of android to get the position information. As per my knowledge we can get the location from android in 2 ways by using "navigator.getlocation" and  "fusedlocationproviderClient". Whether this plugin is using either one of these two or is there any other way to get the users location?

**Comment by christocracy** [comment]
Yes, Android uses `FusedLocationProviderClient', in addition to `ActivityRecognitionClient` (for detecting when device is moving / stationary as a trigger to engage location-services).
