### ISSUE TITLE
Multiple notifications sent when the user is on the move, rather than one.

### ISSUE THREAD

**Issue by josianeReis** [transistorsoft/react-native-background-geolocation#408]
## Your Environment
* Plugin version: Latest
* Platform: iOS
* OS version: MacOs Sierra 10.12.6
* Device manufacturer / model: Iphone 7
* React Native version (`react-native -v`): v0.44.3
* Plugin config

## Expected Behavior
I want to trigger push notifications when the user of my application enters a geofence area defined in my settings.

## Actual Behavior
I am currently using the following method to monitor when the user enters the geofence area, however several notifications are being given while the user is moving within the geofence area defined, I wanted only one notification when entering and one when leaving the geofence.

```
bgGeo.on('geofence', (geofence) => {
          PushNotification.localNotification({
            message: `Area ${geofence.identifier}`, 
            playSound: false,
            repeatType: 'day', 
          })
        })
```

## Steps to Reproduce

1.
2.
3.
4.

## Context
I want to know if I'm using the wrong method, or should I do some different configuration.

This is the code where I configure the geofence areas and send the notifications.

```
const geofencingConfig = {
  desiredAccuracy: 0,
  distanceFilter: 10,
  stopTimeout: 1,
  debug: false,
  stopOnTerminate: false,
  startOnBoot: true,
  maxDaysToPersist: 0,
}

export const getCampaigns = () => (
  (dispatch) => {
    GeofencingService
    .getCampaigns()
    .then((data) => {
      const campaigns = _get(data, 'value', false)
      if (campaigns) {
        bgGeo.configure((geofencingConfig), (state) => {
          if (!state.enabled) {
            bgGeo.startGeofences()
          }
        })
        const allCampaigns = JSON.parse(campaigns).map(item => ({
          identifier: item.id,
          radius: item.radius,
          latitude: item.center.lat,
          longitude: item.center.long,
          notifyOnEntry: true,
          notifyOnExit: true,
        }))
        bgGeo.addGeofences(allCampaigns,
          () => console.log('Geofences adicionadas'),
          error => console.warn('Falha ao adicionar Geofences', error),
        )
        bgGeo.on('geofence', (geofence) => {
          PushNotification.localNotification({
            message: `Area ${geofence.identifier}`, 
            playSound: false,
            repeatType: 'day', 
          })
        })
        dispatch(createAction(types.GET_GEOFENCING_CAMPAIGNS)(campaigns))
      }
    })
    .catch((err) => {
      logError(err)
    })
  }
)
```

**Comment by christocracy** [comment]
What's your geofence radius?

**Comment by josianeReis** [comment]
I tested with two different, one with 200m and one with 400m

**Comment by christocracy** [comment]
well, if the device is sitting for a while near a geofence boundary, it *can* fire multiple times.  The OS is completely in charge of geofences.

**Comment by josianeReis** [comment]
In case, the device was moving within the geofence, but instead of just notifying when it entered or exited the geofence, it was notifying all the time. Is the geofence.on ('location') method correct for doing what I'm trying to do?

In the picture below is the example of what I'm talking about, it should have only been shown an incoming notification and an outgoing notification, but several appear while I move within the geofence.

![img_5094](https://user-images.githubusercontent.com/17270553/35989196-ae7073d0-0ce7-11e8-93cf-6f11f7067cb9.PNG)

**Comment by christocracy** [comment]
It looks like you're executing `#getCampaigns` **multiple times**, thus accumulating `geofence` listeners each time.  Don't do that.

You only execute the `#configure` method **once**, when the app boots.  And just set up your listeners *once*.

Think of event-listeners like adding adding a speaker to your stereo.  You don't add a new set of speakers every time your turn the stereo on.  You have one set of speakers.  When you don't want to listen to the stereo any more, you turn the power off (ie: `BackgroundGeolocation.stop()`).

When you want to listen to music, you turn the power on.  Music flows out of your single set of speakers (ie: `BackgroundGeolocation.start()`).

**Comment by josianeReis** [comment]
I understood, I'm going to change the way it's done and test it if it works, thank you very much for your help.
