### ISSUE TITLE
Need info about FusedLocationProviderClient

### ISSUE THREAD

**Issue by manju-ms** [transistorsoft/react-native-background-geolocation#409]
This plugin is using FusedLocationProviderClient of android to get the location updates or is there any different way this plugin getting the location updates? In Android we can get the location updates in 2 ways   by using navigator.getLocation which does not give accurate results or FusedLocationProviderClient which gives accurate results. Which one this plugin is using?

**Comment by christocracy** [comment]
Yes. Fused.  Only Fused
