### ISSUE TITLE
react-native link not working

### ISSUE THREAD

**Issue by itcurves** [transistorsoft/react-native-background-geolocation#411]
## Your Environment
* Plugin version: ^2.11.0
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.53.0
* Plugin config

## Actual Behavior
Please file an issue here: https://github.com/facebook/react-native/issues

## Steps to Reproduce

trying to run react-native link but it keep failing after plugin installation.

Did try manual setup as well but still app failing to run.
Also do I have to buy a license even I am not using the map functionality, just trying to call get location?
Thanks

**Comment by christocracy** [comment]
Are you using latest XCode 9?  What platform are you on?  npm / node -v?

This plugin is not involved with maps.  You need a license to unlock Android.

**Comment by itcurves** [comment]
ok I am on windows for now and trying to test on android. 

npm 5.5.1
node 9.2

after running react-native link , now my project giving me error , and honestly I am not sure how to get back to running version now

**Comment by adamhaney** [comment]
What is the error output of react-native link?

**Comment by itcurves** [comment]
right now when I run react-native link it says already linked.
![rn1](https://user-images.githubusercontent.com/1397397/36104858-264fcc56-0fe1-11e8-966c-a7a3e2b10662.PNG)
but this is the error when I try to run it.
![rn2](https://user-images.githubusercontent.com/1397397/36104859-26642e94-0fe1-11e8-9257-4a3a465f1944.PNG)

sorry I am not too much into react native but project was fine before linking this plugin

**Comment by adamhaney** [comment]
so that's showing that it's already linked (even though something may have gone wrong)

try running
react-native unlink react-native-background-geolocation
and then re-running
react-native link react-native-background-geolocation

and then post the output of that.

**Comment by christocracy** [comment]
Thanks for helping out @adamhaney

**Comment by itcurves** [comment]
for unlink
![image](https://user-images.githubusercontent.com/1397397/36109647-fdaa9008-0fed-11e8-84cc-45bbf43cdb2b.png)
for link again
![image](https://user-images.githubusercontent.com/1397397/36109976-180a0f04-0fef-11e8-9eec-d9ea33d7f2b4.png)

after link when try to run: react-native run-android
![image](https://user-images.githubusercontent.com/1397397/36110010-3d854988-0fef-11e8-8a88-6a2402118141.png)

remember I am not trying to use it right now, it just happen right after link.

And thanks for quick replies, I really appreciate your help here

**Comment by christocracy** [comment]
`$ npm uninstall react-native-background-geolocation`

Re-install it from scratch.

**Comment by adamhaney** [comment]
It looks like installing/linking this library caused you to use a different android SDK than you've previously used and that you need to accept the terms for that SDK. You can either fire up Android Studio and accept terms/permissions for SDK Build Tools version 26.0.2 or from the cli
`yes | sdkmanager "build-tools;26.0.2"` should do the trick

**Comment by itcurves** [comment]
ok I did not had 26.0.2 installed, installing that make it work.

Thank you so much and you can close it now.

**Comment by itcurves** [comment]
ok one more question:
![image](https://user-images.githubusercontent.com/1397397/36339464-8ece5ee4-1394-11e8-8f74-5b53c1687a5a.png)

I understand I have to buy a license if I am using it in android. But what if I have a project for android and iphone and only using this library in iphone.

should this pop up come up even I am not using it?

How I can remove this component only for android?

**Comment by christocracy** [comment]
Why would you only use the plugin for one platform?

The behavior between iOS / Android version would radically different.

**Comment by itcurves** [comment]
well I have to launch it for iPhone first with location support, but on android we are not going to use in first version. Now as I add this it start showing this message.

What I am looking for I do all code for now, and launch it on both and on android we are not going to use the location thing.

I believe it should not show this message until that component use in the screen, or in the background.

Thank you

**Comment by christocracy** [comment]
Remove the plugin module from your MainApplicstion.java and don’t reference the JavaScript api BackgroundGeolocation in your app.
