### ISSUE TITLE
How to check if module is running

### ISSUE THREAD

**Issue by AlexandreMaistret** [transistorsoft/react-native-background-geolocation#413]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS or Android: Android
* OS version: 7.0.1
* Device manufacturer / model: Wiko
* React Native version (`react-native -v`): 0.51.0
* Plugin config

        {
        // Geolocation Config
        desiredAccuracy: 10,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: true, 
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   closes the app.
        startOnBoot: true,        

        //IOS
        preventSuspend: true,

        //ANDROID
        foregroundService: true, //SI true, une barre de notif reste activé, mais l'apply fonctionne toujours
        notificationTitle: 'MYAPPNAME',
        notificationText: 'running',
        notificationColor: '#21c064',

        // HTTP / SQLite config
        url: 'URL OF MY SERVER,
        batchSync: false,      
        autoSync: true,        
        locationTemplate: '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, "timestamp":"<%= timestamp %>" }',
        autoSyncThreshold: 0,
        maxDaysToPersist: 10
      }

## Expected Behavior
I would like to know if the plugin is running or has been killed by the OS or by the User, but I don't find the good API method which give back the state of the plugin.

## Actual Behavior
I've tried with `BackgroundGeolocation.getState()`, but it just give me the parameters of the plugin, not if the plugin is actually running.

## Steps to Reproduce
Indeed, when I launch the plugin, I have set `foregroundService` to `true` just to get the persistent notification to know that the plugin is running.

However, if I kill the app in the device parameters, so everything is killed, and the persistent notification doesn't show anymore (meaning for me that the pluging is not running anymore and I have checked that no geolocation updates are sent to my server), the method `BackgroundGeolocation.getState()` still gives me the parameters of the plugin, but doesn't say if it is running (the `enable` state says `true`, even if the plugin is not runing)

**Comment by christocracy** [comment]
Sure It does.  `state.enabled`.  Just like [as shown in the Example](https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-example)

```javascript
BackgroundGeolocation.configure({
      .
      .
      .
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
      .
      .           
    });
```
