### ISSUE TITLE
Not tracking on iOS

### ISSUE THREAD

**Issue by grahamyesfit** [transistorsoft/react-native-background-geolocation#416]
* Plugin version: 2.11.0
* Platform: iOS
* OS version: 11.2
* Device manufacturer / model: iOS Emulator for iPhone 6 and iPhone 5 device
* React Native version: 0.49.5
* Plugin config
{
    activityRecognitionInterval = 10000;
    activityType = Other;
    autoSync = 0;
    autoSyncThreshold = 0;
    batchSync = 1;
    debug = 0;
    desiredAccuracy = 0;
    desiredOdometerAccuracy = 100;
    disableElasticity = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 5;
    elasticityMultiplier = 1;
    enabled = 0;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =     {
        Authorization = "Bearer xxx";
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    isHeartbeatEnabled = 0;
    isMoving = 0;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 7;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = 0;
    params =     {
        key = "xxxx";
    };
    pausesLocationUpdatesAutomatically = 1;
    preventSuspend = 0;
    schedule =     (
    );
    schedulerEnabled = 0;
    startOnBoot = 0;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 1;
    trackingMode = 1;
    url = "https://xxx/tracker";
    useSignificantChangesOnly = 0;
}
## Expected Behavior
1. I expect Location event method to be called every few seconds with location updates
2. BackgroundGeolocation.sync method should send locations to my server
3. BackgroundGeolocation.getLocations should return locations
4. BackgroundGeolocation.getCount should return the number of locations

## Actual Behavior
1. Location event method is never called
2. BackgroundGeolocation.sync does not send any locations to my server
3. BackgroundGeolocation.getLocations returns an empty array
4. BackgroundGeolocation.getCount returns 0

## Steps to Reproduce
NOTE: The same code works on Android. Also, I've tried this in an iPhone 6 emulator and on an iPhone 5 device

1. I call BackgroundGeolocation.configure with default settings when the App is mounted
2. When the user authenticates, I call BackgroundGeolocation.setConfig with some updated settings (e.g. their bearer token for authentication to my API)
2. Then I call BackgroundGeolocation.on and pass my location event method
3. Then I call BackgroundGeolocation.resetOdometer and then BackgroundGeolocation.start, and then (if __DEV__) I call BackgroundGeolocation.changePace(true)
2. The first time I ran this, I was prompted for permission for location updates
3. In Xcode, I start simulating movement (the GPX file has hundreds of locations in it), and I wait.
4. Expected behavior does not occur

*NOTE: I installed the plugin using Cocoa pods.

## Context
I'm adding fitness tracking to my App and I want to use this library. But only if I can get iOS working.

## Debug logs
ℹ️-[TSLocationManager removeListeners] 
ℹ️-[TSLocationManager removeListeners] 
⚠️-[TSLocationManager configure:] Already configured.  Redirecting to #setConfig.
ℹ️-[TSLocationManager on:success:failure:] location
🔵-[TSLocationManager setOdometer:success:failure:] 
🔵-[TSLocationManager getCurrentPosition:success:failure:] updateCurrentPosition: {
║ -[TSLocationManager start] 
🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
2018-02-24 12:20:44.986511-0500 yesfitclient[2501:78078] [TSBackgroundFetch addListener]: TSLocationManager
🔵-[TSLocationManager changePace:] isMoving: 1
🔵-[TSLocationManager setPace:] 1
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON

**Comment by christocracy** [comment]
The plugin logs show the plugin is happy.

I’m thinking likely a problem with your simulating of location.

Try using Simulator->Debug->Location->Freeway Drive

**Comment by grahamyesfit** [comment]
Thanks Chris, it looked happy to me, too. I've tried all different GPX
files, and I get the same behavior for each. I use the same GPX file that I
use for my Android emulator, which works. I also installed the App on my
device and walked around for 15 minutes, with no location updates.

I just tried the Freeway drive and still no location updates.

The only difference that I can determine is in my pod file, I have platform
:ios set to '9.0', as I have a library that requires that. Would that make
a difference?
​

**Comment by christocracy** [comment]
You don't have an install problem.  The plugin is printing logs.  It is alive.  Show me entire XCode logs of your app booting from scratch.

**Comment by grahamyesfit** [comment]
Can I upload the log to you in a private location? I don't want to paste it
here in full view.​

**Comment by christocracy** [comment]
as you wish.  chris@transistorsoft.com

**Comment by grahamyesfit** [comment]
Sent.​

**Comment by christocracy** [comment]
```
2018-02-24 13:23:48.074134-0500 yesfitclient[4152:133965] This app has attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain both NSLocationAlwaysAndWhenInUseUsageDescription and NSLocationWhenInUseUsageDescription keys with string values explaining to the user how the app uses this data
```

Add `Privacy - When in Use Usage Description` to you plist.  The Cocoapod setup doc needs to be updated.

**Comment by christocracy** [comment]
Sorry:  `Privacy - Always and When in Use Usage Description`

**Comment by christocracy** [comment]
The required plist strings are in the [react-native-link](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS-RNPM.md#xcode-configuration) instructions

**Comment by grahamyesfit** [comment]
Yes, that was it. Thank you so much for figuring this out so quickly.

I think the required plist strings aren't quite right in your react-native-link
instructions
<https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS-RNPM.md#xcode-configuration>
(which I had followed, but I had a typo). You state these are required:

NSLocationAlwaysUsageDescription
NSLocationAlwaysAndWhenInUseUsageDescription
NSMotionUsageDescription

However, you don't mention NSLocationWhenInUseUsageDescription (which you
did mention in this thread). My code wouldn't work without it. I wonder if
the first in the list (NSLocationAlwaysUsageDescription) should actually be
NSLocationWhenInUseUsageDescription?

But thanks again for your expert assistance. Future customer here (very
near future).
​

**Comment by christocracy** [comment]
`NSLocationAlwaysUsage` was deprecated with IOS 11.  It's only required for iOS < 11

The required strings for iOS < 11
- `NSLocationWhenInUseUsageDescription`
- `NSLocationAlwaysUsageDescription'

The required strings for iOS 11+:
- `NSLocationWhenInUseUsageDescription`
- `NSLocationAlwaysAndWhenInUseUsageDescription`

`NSMotionUsageDescription` is required for all versions of iOS.

**Comment by grahamyesfit** [comment]
Understood, thank you.

But I don't see NSLocationWhenInUseUsageDescription mentioned in your
instructions
<https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS-RNPM.md#xcode-configuration>.
You list 4 above, but only 3 in the table on that page. Am I being daft?
​

**Comment by BenBach** [comment]
@grahamyesfit I guess I have the same problem. Were you able to figure this out?

**Comment by christocracy** [comment]
@BenBach did you add the required permissions noted above?
