### ISSUE TITLE
General guidance for batchSync and autoSync

### ISSUE THREAD

**Issue by grahamyesfit** [transistorsoft/react-native-background-geolocation#417]
* Plugin version: 2.11.0
* Platform: iOS and Android
* OS version: All
* Device manufacturer / model: All
* React Native version: 0.49.5

I need some general guidance on batchSync, autoSync and their respective sizes and how they work together. 

I would like to track a user's workout, but if they're working out for hours, I don't want hundreds of locations stored in the local database and subsequently posted to the API. I'd like for the locations to be posted in batches as they occur.

Here are some tentative values I'm trying out:

batchSync: true
maxBatchSize: 100
autoSync: true
autoSyncThreshold: 100

Does this configuration mean that for every 100 received locations, the plugin posts 100 locations at a time, and deletes them from the local database?

When the user stops their workout, do I also need to do a sync and destroyLocations in order to flush and remove the remaining < 100 locations from the local db?

A related question: I'd like to set a limit on the length of the workout to, say, 2 hours. When the limit is reached, how do I detect that so that I can do the final flush (if necessary) for the locations that haven't been batched yet?

And one more related question: if I set a params value in the config, does that value survive if the app is killed and restarted?

**Comment by christocracy** [comment]
Btw, these new changes will only be available in the private repo for for the time being.  You might want to get used to using the private repo instead of this public repo which only receives updates about every 3 months.

**Comment by grahamyesfit** [comment]
Thanks Chris, this is good stuff.

I tried to use the new repo but ran into ssh issues. I can probably solve
them for my development environment, but I'm not sure how to make it work
on my CI server (I'm using BuddyBuild to build and deploy to the stores).
Do you have any ideas on that?

**Comment by christocracy** [comment]
>but I'm not sure how to make it work
on my CI server

Easy.  Github Personal Access Token

![](https://dl.dropboxusercontent.com/s/ittcq2dd2m6wzk0/Screenshot%202018-02-26%2020.09.26.png?dl=1)

```
npm install git+https://<access-token>@github.com:transistorsoft/react-native-background-geolocation-android.git
```

**Comment by grahamyesfit** [comment]
I'm likely doing something wrong, but when I create a public access token
for my username (grahamyesfit) and include it in the npm install command as
shown, I receive the "Permission denied (publickey)" error. My settings for
the access token are as shown in your screenshot.

Wouldn't this access token only apply to my own private repositories? How
do I make it apply to transistorsoft?

Going back to my previous questions. Just to clarify, if I'm using
autosync, when I call stop(), will the final locations that have been
created since the last autosync be automatically synced and removed from
the local db? There's no need for me to do that manually?

Is your new enableChange event already in the private repo?
​

**Comment by christocracy** [comment]
Have you [setup ssh for Github](https://help.github.com/articles/connecting-to-github-with-ssh/)?

>when I call stop(), will the final locations that have been
created since the last autosync be automatically synced and removed from
the local db

No.  You will have to manually execute `#sync`.  The plugin will not `autoSync` while disabled.  It assumes, for example, that the user has logged out.

See #403 posted minutes ago to master.

**Comment by grahamyesfit** [comment]
Chris, this might help me to connect from my local machine, but how do I
configure a 3rd party build server to? I don't have access to them. The
only option they give is for me to provide them with SSH keys into *my*
source control, not that of a package in my project.​

**Comment by christocracy** [comment]
People using 3rd party build services provide a repo url with personal access token.

**Comment by grahamyesfit** [comment]
I  generated a personal access token for grahamyesfit (as described in your
earlier post). When I execute this command:

npm install git+https://<access-token>@github.com:
transistorsoft/react-native-background-geolocation-android.git

(subbing in my new token) I get "Permission denied (publickey)".

This made me wonder if the personal access token that I generated gives me
access to my own repos, not yours. I know I'm missing something here.

**Comment by grahamyesfit** [comment]
I changed the command from:

npm install git+https://<access-token>@github.com:
transistorsoft/react-native-background-geolocation-android.git

to

npm install git+https://grahamyesfit:<access-token>@github.com/
transistorsoft/react-native-background-geolocation-android.git

and it worked. I added in my  <username>: before the access token and
changed "github.com:" to "github.com/"
​

**Comment by grahamyesfit** [comment]
Actually, that syntax works without the username.​

**Comment by grahamyesfit** [comment]
Are the new changes you mentioned in this thread (the 'enabledchange' event
and the ready method) available in the premium branch now?​

Is it okay for me to point my prod environment at the latest branch (I
notice it has "beta" in it), or is it somewhat unstable?

**Comment by grahamyesfit** [comment]
Thanks, that's good to know.​

**Comment by grahamyesfit** [comment]
When I build my Android App with the new rnbGeo repo, I get an error
regarding tsbackgroundfetch:

* What went wrong:
21:01:00.468 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred
configuring project ':app'.
21:01:00.469 [ERROR] [org.gradle.BuildExceptionReporter] > Could not
resolve all dependencies for configuration ':app:_debugApkCopy'.
21:01:00.470 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not
find :tsbackgroundfetch:.
21:01:00.470 [ERROR] [org.gradle.BuildExceptionReporter]      Required by:
21:01:00.470 [ERROR] [org.gradle.BuildExceptionReporter]
app:app:unspecified > app:react-native-background-fetch:unspecified

I looked through the Android install docs and I can't find a mention of
this library.
​

**Comment by grahamyesfit** [comment]
Okay, I got it to build. I added these to my app/build.gradle

repositories {
   flatDir {
       dirs "../../node_modules/react-native-background-fetch/android/libs"
   }
}

and

dependencies {
    //compile(name: 'tslocationmanager', ext: 'aar')
    compile(name: 'tsbackgroundfetch', ext: 'aar')
   ...
}

I commented out the compile for tslocationmanager because I don't think
it's needed anymore. Your Android documentation steps don't include this.
To add to my confusion, the demo app contains compiles for
tslocationmanager and tsbackgroundfetch. Can you confirm these changes are
correct? Are there any other changes I should be aware of?

**Comment by grahamyesfit** [comment]
And now I'm getting "Can't find variable: BackgroundGeoLocation" in my
module. My import is:

import BackgroundGeolocation from
"react-native-background-geolocation-android";

I've followed all the steps in the Android setup (including my new ones
above). This all worked when I was pointing at the other repository. I've
been testing it for a week.
​

**Comment by grahamyesfit** [comment]
Sorry, ignore that last one.​ That was a typo on my part.

**Comment by grahamyesfit** [comment]
Is there a way to reset the counter that applies
to stopAfterElapsedMinutes, without doing a complete config reset? I would
like this value to only apply to each tracking session. It seems to persist
across "start" calls. I would like to reset it when the Geo starts again.​

**Comment by christocracy** [comment]
Please stay on-topic.  The topic is:

>General guidance for batchSync and autoSync

**Comment by christocracy** [comment]
>I commented out the compile for tslocationmanager because I don't think
it's needed anymore. Your Android documentation steps don't include this.

If you're going to roll-back to a previous version, you must follow the directions [*on that version*](https://github.com/transistorsoft/react-native-background-geolocation-android/blob/2.11.0/docs/INSTALL-ANDROID-RNPM.md#gradle-configuration) -- not from those those found in *master*.

`compile(name: 'tsbackgroundfetch', ext: 'aar')` is only required when using `flatDirs`.  It's no longer required with latest version using `maven url`

**Comment by grahamyesfit** [comment]
I'm not rolling back to a previous version. As i indicated earlier in this
thread, i get a build error (on the latest version):

When I build my Android App with the new rnbGeo repo, I get an error
regarding tsbackgroundfetch:

* What went wrong:
21:01:00.468 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred
configuring project ':app'.
21:01:00.469 [ERROR] [org.gradle.BuildExceptionReporter] > Could not
resolve all dependencies for configuration ':app:_debugApkCopy'.
21:01:00.470 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not
find :tsbackgroundfetch:.
21:01:00.470 [ERROR] [org.gradle.BuildExceptionReporter]      Required by:
21:01:00.470 [ERROR] [org.gradle.BuildExceptionReporter]
app:app:unspecified > app:react-native-background-fetch:unspecified

I looked through the Android install docs and I can't find a mention of
this library.

The snippet you pasted was a line i said i commented out. The line i added
was this one, in an attempt to resolve my build error. I even state in my
post that it's not in the documentation:

compile(name: 'tsbackgroundfetch', ext: 'aar')

If that's not how to fix the build error, then how?

**Comment by christocracy** [comment]
Using `flatDirs` implies rolling back to previous version, because `flatDirs` is replaced by `maven url` in latest.

**Comment by grahamyesfit** [comment]
These are my maven URLs:

        maven {
            url "https://maven.google.com"
        }
        maven {
           url "$rootDir/../node_modules/react-native-background-
geolocation-android/android/libs"
        }
        maven {
           url "$rootDir/../node_modules/react-native-background-fetch/
android/libs"
        }

​*Without* the flatdirs entry, I get the error "Could not find
:tsbackgroundfetch".

What am I missing?

**Comment by christocracy** [comment]
what version of `background-fetch` do you have installed?

**Comment by grahamyesfit** [comment]
I don't have it installed.​

**Comment by christocracy** [comment]
It's declared [as a dependency](https://github.com/transistorsoft/react-native-background-geolocation-android/blob/master/package.json#L42) of `background-geolocation`.

It should be installed automatically.

**Comment by grahamyesfit** [comment]
I have a react-native-background-fetch at version 2.3.0.​

**Comment by christocracy** [comment]
This is the problem.  Only `fetch@2.4.0` uses new `maven url`

```
$ npm install react-native-background-geolocation`
```

**Comment by christocracy** [comment]
When I implemented the new `maven url`, I did so for both `background-geolocation@2.12.0` and `background-fetch@2.4.0`.

**Comment by grahamyesfit** [comment]
Do you mean I should do this?

npm install react-native-background-fetch
​

**Comment by grahamyesfit** [comment]
That fixed it for me, thanks Chris.​

**Comment by christocracy** [comment]
Awesome.
