### ISSUE TITLE
Error when building and installing

### ISSUE THREAD

**Issue by l0ge0001** [transistorsoft/react-native-background-geolocation#421]
## Your Environment
* Plugin version:
* Platform: iOS or Android: Android
* OS version: 7.0
* Device manufacturer / model: Samsung Active 7
* React Native version (`react-native -v`):
react-native-cli: 2.0.1
react-native: 0.53.3

* Plugin config

## Expected Behavior

When I testing your component, I got this: 

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find :tslocationmanager:.
     Required by:
         Livell:app:unspecified > Livell:react-native-background-geolocation:unspecified

What might be the problem?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Review the [Gradle configuration](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md#gradle-configuration).

You forgot to add the `flatDirs` bit.

**Comment by l0ge0001** [comment]
That solve my problem. Thanks.

Wherever I run my app, it will crashed after the license warning. Can I make test without licensing?

Thanks

**Comment by christocracy** [comment]
Android will work as long as it's built for DEBUG (eg: `react-native run-android`).

If an app crashes, the **FIRST** thing you do is capture the stacktrace from `$ adb logcat`.  There is always a stacktrace when an app crashes.  If you're not watching `$ adb logcat`, you're driving with a blindfold.
