### ISSUE TITLE
Timestamps have one hour jumps between what real happends

### ISSUE THREAD

**Issue by cayrolmdq** [transistorsoft/react-native-background-geolocation#422]
The plugin is sending GPS with diferents timestamps for the same phone.
Sometimes end with one hour of diference, here some examples. 

Example: 
**"timestamp":"2018-02-14T12:37:52.000Z"** BAD TS was 13:37:52
"timestamp":"2018-02-14T13:38:36.268Z"
**"timestamp":"2018-02-14T12:39:46.000Z"** BAD TS was 13:39:46
"timestamp":"2018-02-14T13:41:07.728Z"
**"timestamp":"2018-02-14T12:41:42.000Z"** BAD TS was 13:41:42

The sequence we got the gps request are ok, but the time should  13 not 12, all the wrong timestamps ends with ".000Z"

## Your Environment
* Plugin version: 2.11.00 bug we saw the same with older version and new phones
* Platform: Android
* OS version: 4.2.2
* Device manufacturer / model: Coship
* React Native version (`react-native -v`): react-native-cli: 2.0.1  react-native: 0.52.2
* Plugin config: Default as Demo apps have.

## Expected Behavior
Timestamps are correct

## Actual Behavior
Randomly we got sequential capture gps different timestamps

## Steps to Reproduce
1. Run the react-natvice-demo app
2. Default config
3. Capture points, walking

## Context
We are implementing a new app on react native, we are customers since 2015, we identified ugly draws on our gps tracking visualization app. we discover inconsistency between timestamps vs creation times,
we use the timestamps to draw lines in our map viewer , and we figure out that for some customers the draws do a lot of jumping s, and strange behavior , but if we sort by creation day (in our database) the draws are better, but we need the time of the GPS was capture, becase we do a lot of calculations based on that timestamp, so we need that timestamp correctly captured. 

## Debug logs
Attached 
[10425_14_Feb.log](https://github.com/transistorsoft/react-native-background-geolocation/files/1775578/10425_14_Feb.log)
This are BODY content that we receive in our servers. the sequence is the sequence we receive the POST from our servar, and fits with what we don on street, but you will find that some timestamps have an hour of difference.

**Comment by cayrolmdq** [comment]
Guys? Ideas?

**Comment by christocracy** [comment]
It's not a problem with the timestamp, the plugin is sending  you the *same* location over and over again.  Make sure you return an HTTP success response (eg: `200`) to let the plugin know your server has received the location.  Otherwise it'll keep attempting to send the same location.

You'll find your server is not returning HTTP 200.

**Comment by christocracy** [comment]
Update?

**Comment by cayrolmdq** [comment]
Server is returing 200 in all the cases, the plugin is sending that timestamp.

**Comment by christocracy** [comment]
Post logs from the plugin reproducing this

**Comment by cayrolmdq** [comment]
Ok, let look that and reply. i will need a couple of days

**Comment by cayrolmdq** [comment]
ok

**Comment by cayrolmdq** [comment]
Check this: http://tracker.transistorsoft.com/cayrolmdq?device=ReactNative-a2ded114d9e95cb&end=2018-4-3&start=2018-4-3

This point
{
  "id": 1697793,
  "company_token": "cayrolmdq",
  "uuid": "bdd70b87-2837-44e3-b920-00be178eecb2",
  "device_id": "ReactNative-a2ded114d9e95cb",
  "device_model": "CipherLab RS30 (ReactNative)",
  "latitude": -33.3976,
  "longitude": -70.6168,
  "accuracy": 10,
  "altitude": 650.2,
  "speed": 10.37,
  "heading": 294,
  "odometer": 5226.5,
  "event": null,
  "activity_type": "in_vehicle",
  "activity_confidence": 95,
  "battery_level": 0.94,
  "battery_is_charging": false,
  "is_moving": true,
  "geofence": null,
  "provider": null,
  "extras": {},
  "recorded_at": "2018-04-03T13:16:26.000Z",
  "created_at": "2018-04-03T14:16:39.156Z"
}


Location
close
{
  "id": 1697794,
  "company_token": "cayrolmdq",
  "uuid": "fd6653d9-2562-431d-9ccc-128b42e4dcaf",
  "device_id": "ReactNative-a2ded114d9e95cb",
  "device_model": "CipherLab RS30 (ReactNative)",
  "latitude": -33.3976,
  "longitude": -70.6168,
  "accuracy": 24,
  "altitude": -1,
  "speed": -1,
  "heading": -1,
  "odometer": 5226.5,
  "event": null,
  "activity_type": "in_vehicle",
  "activity_confidence": 95,
  "battery_level": 0.94,
  "battery_is_charging": false,
  "is_moving": true,
  "geofence": null,
  "provider": null,
  "extras": {},
  "recorded_at": "2018-04-03T14:16:29.170Z",
  "created_at": "2018-04-03T14:16:39.779Z"
}

If you see the drawing you will see that are jumps but in reality is a wrong timestamp

**Comment by losnikitos** [comment]
Hi!

I have a similar issue: most timestamps grow monotonically, but some of them jump back by 1, 4 or 5 hours:

![2018-08-01 13 55 37](https://user-images.githubusercontent.com/5237443/43517819-aa4e3f9c-9592-11e8-818d-f0a9f926e943.jpg)
![2018-08-01 13 55 34](https://user-images.githubusercontent.com/5237443/43517821-aa6b5bcc-9592-11e8-80d6-326037793de3.jpg)
![2018-08-01 13 55 29](https://user-images.githubusercontent.com/5237443/43517822-aa8911da-9592-11e8-979f-c7dadc463760.jpg)
![2018-08-01 13 55 25](https://user-images.githubusercontent.com/5237443/43517823-aaa5c884-9592-11e8-8af3-0f4ddca7723f.jpg)

My best guess is that some locations come from GPS provider and have correct timestamp (from the satellite), and some locations from WiFi/Cellular and use device time, which is wrong. Device time can be wrong if user has wrong timezone setup, but adjusts his UTC time instead — that explains why the jumps are exactly N hours.

@christocracy, how does the plugin get timestamps of locations? The docs says [Location.getTime() is not reliable](https://developer.android.com/reference/android/location/Location#getTime()), it's better to use [getElapsedRealtimeNanos()](https://developer.android.com/reference/android/location/Location#getElapsedRealtimeNanos()).

Our config:
```js
{
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
    distanceFilter: 10
    fastestLocationUpdateInterval: 1000
    locationUpdateInterval: 10000
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    stopOnTerminate: false,
    startOnBoot: true,
    foregroundService: true,
    notificationTitle: 'Yandex.Courier',
    notificationText: 'Using GPS',
    maxRecordsToPersist: 100,
    maxDaysToPersist: 1,
    url: '...',
    autoSync: true,
    batchSync: true,
    httpRootProperty: 'positions',
    locationTemplate:
        '{ "accuracy": <%= accuracy %>, "latitude":<%= latitude %>, "longitude":<%= longitude %>, "time": "<%= timestamp %>" }',
    headers: {
        Authorization: `Auth ${token}`,
        'User-Agent': `com.yandex.courier v${pkg.version}`
    }
}
```

**Comment by losnikitos** [comment]
> I added an un-documented config option for someone else experiencing on Android

Thank you, I'll give it a try.

> What is your Android device manufacturer, model and OS? What country are you in?

We see it on different devices. Here's breakdown by device model:
```
Samsung SM-T285             11
BeelinBeeline Smart 3       7
TCL 5017D                   3
Xiaomi Redmi 4X             3
Ginzzu S4020                3
Samsung SM-J510FN           3
```

And by Android versions:
```
5.1.1    12
4.4.2     7
5.1       6
7.1.1     5
7.0       4
6.0.1     3
7.1.2     2
4.2.2     1
```

I'm in Russia.

**Comment by christocracy** [comment]
Closed for lack of feedback.

**Comment by HananeAlSamrout** [comment]
thank you! systemTime in timestampMeta is accurate

**Comment by losnikitos** [comment]
@christocracy Hi! How do I use `timestampMeta` in `locationTemplate`?
I tried `<%= timestampMeta.systemTime %>` in my template, but I get error:
```
IllegalArgumentException: Unknown template variable: timestampMeta
```

**Comment by christocracy** [comment]
@losnikitos you can’t.

**Comment by losnikitos** [comment]
@christocracy If I need `timestampMeta`, the only option I have is to support the default location JSON format in my API, right? It will be hard to adapt our API to new format, because it's supported by another team and the API is used by other clients.

Maybe you can consider adding `<%= systemTime %>` to `locationTemplate`? I believe other customers might find it useful.

**Comment by christocracy** [comment]
Why don’t you add a proxy action on the server that modifies the plugin’s default format then relays to your existing route?

Templating for timeStampMeta is not easy because the formats are vastly different between Android / iOS.

timeStampMeta isn’t even documented.  It was added for debugging purposes.

**Comment by losnikitos** [comment]
@christocracy You are right, proxy would help. It was worth trying though :)

**Comment by christocracy** [comment]
@losnikitos Thanks.

**Comment by losnikitos** [comment]
@christocracy can I use `timestampMeta` in production? Since it's not documented, can I be sure format won't change and it won't be removed in future versions?

**Comment by christocracy** [comment]
Yes

**Comment by losnikitos** [comment]
@christocracy one more question about `timeStampMeta.deviceTime`: does it contain device time, when location was **recorded** or when it was **uploaded** to server?

**Comment by christocracy** [comment]
There's no such attribute, on either iOS or Android, `deviceTime`

**Comment by losnikitos** [comment]
@christocracy Sorry I meant `systemTime`

**Comment by christocracy** [comment]
`systemTime` is the current time at the instant the location was received by the plugin *from* the native location API.

```obj-c
long long systemTime = (long long)([[NSDate date] timeIntervalSince1970] * 1000.0);
```

**Comment by UnSket** [comment]
Hi, @christocracy. We have strange situation with times. If we will look at timestampMeta.system prop it gradually growing, but 'time' prop jumping. How is it possible?

Batch example: 
```javascript 
[
  {
    "is_moving": true,
    "uuid": "473ed285-70cc-408b-bd29-aa5972c91dfe",
    "timestamp": "2020-01-28T08:35:07.000Z",
    "timestampMeta": {
      "time": 1580200505086,
      "systemTime": 1580200505086,
      "systemClockElaspsedRealtime": 316577287,
      "elapsedRealtime": 316576741
    },
    "odometer": 3103987,
    "coords": {
      "latitude": 55.7323382,
      "longitude": 37.3925081,
      "accuracy": 28.8,
      "speed": 0.17,
      "heading": 154.79,
      "altitude": 196
    },
    "activity": {
      "type": "in_vehicle",
      "confidence": 100
    },
    "battery": {
      "is_charging": true,
      "level": 0.95
    },
    "extras": {
    }
  },
  {
    "is_moving": true,
    "uuid": "47e457fd-0833-4765-a4cc-a1baf8860a58",
    "timestamp": "2020-01-28T07:55:55.654Z",
    "timestampMeta": {
      "time": 1580198155654,
      "systemTime": 1580200514568,
      "systemClockElaspsedRealtime": 316586766,
      "elapsedRealtime": 314225913
    },
    "odometer": 3103987,
    "coords": {
      "latitude": 55.7523739,
      "longitude": 37.5679753,
      "accuracy": 11.9,
      "speed": 0.01,
      "heading": 39.42,
      "altitude": 145.7
    },
    "activity": {
      "type": "still",
      "confidence": 100
    },
    "battery": {
      "is_charging": true,
      "level": 0.95
    },
    "extras": {
    }
  },
  {
    "is_moving": true,
    "uuid": "d360a118-1b0c-49ae-9022-f298f428a28c",
    "timestamp": "2020-01-28T07:56:08.000Z",
    "timestampMeta": {
      "time": 1580198168000,
      "systemTime": 1580200514735,
      "systemClockElaspsedRealtime": 316586933,
      "elapsedRealtime": 314237758
    },
    "odometer": 3104028.8,
    "coords": {
      "latitude": 55.7522696,
      "longitude": 37.5686145,
      "accuracy": 28.1,
      "speed": 5.29,
      "heading": 106.35,
      "altitude": 145.7
    },
    "activity": {
      "type": "still",
      "confidence": 100
    },
    "battery": {
      "is_charging": true,
      "level": 0.95
    },
    "extras": {
    }
  }
]
```

If we will look at positions, it look's like timestampMeta.time - is more realistic

**Comment by christocracy** [comment]
I have no idea.  Timestamps are provided to the plugin from the device.  The plugin does not *create* timestamps.

**Comment by tuckernuck** [comment]
What do the timestamps represent, though?  

Elapsed time from phone device boot until GPS fix received?
Or, 
Elapsed time from when GPS fix received until returned by device API?

And is the ns timestamp that of the GPS chip - or of the phone?

**Comment by christocracy** [comment]
For Android, the plugin gets its `timestamp` from the received [`android.location.Location#getTime`](https://developer.android.com/reference/android/location/Location#getTime())

**Comment by tuckernuck** [comment]
OK, so my understanding is that getTime will return local device(phone) time of *fix", which is different from the UTC timestamp sent as part of the location object (and as timestampMeta.time).  If we want to estimate the current time on the satellites' clocks, we have to add 1) 66ms for transmit time at speed C, to earth.  2) elapsed time from fix until retrieval.  

If the ms time is 'received' via the locationServices API callback, it can be inaccurate by many ms.    So, I assume you mean this plugin calls getTime() in synchronous/threadsafe native code, then passes that via the plugin callback, in addition to the timestampMeta.time, which is what the cordova geoLocation plugin sends.   

So, please confirm my understanding:
 timestampMeta": {
"time": 1580198168000,   //this is the satellites' clock in epoch ms, also returned as UTC string 
"systemTime": 1580200514735, //this is local phone device (not GPS chip clock) time in ns
}

Therefore, if we wish to estimate the current satellite time in ms, ignoring the 66ms transmit constant, use:

timestampMeta.time + (performance.now()/1000 -timestampMeta.systemTime);  
//satellite ms plus elapsed 

Is that correct?

**Comment by christocracy** [comment]
I have no idea.

**Comment by tuckernuck** [comment]
OK.  How might I find out?  Sorry to be precise, but it's important for my app.

**Comment by christocracy** [comment]
The OP specified `Platform: Android`.  You seem to be talking about iOS.

The plugin has nothing to do with "satellite clock" or "gps time".  It provides the `timestamp` as provided in the [`CLLocation timestamp`](https://developer.apple.com/documentation/corelocation/cllocation/1423589-timestamp?language=objc) 

The iOS `enableTimestampMeta` implementation looks like this:

```obj-c
if (config.enableTimestampMeta) {
        long long systemTime = (long long)([[NSDate date] timeIntervalSince1970] * 1000.0);
        long long locationTime = (long long)([_location.timestamp timeIntervalSince1970] * 1000.0);
        long long uptime = (long long) [self.class uptime] * 1000;
        
        NSDictionary *timestampMeta = @{
            @"time": @(locationTime),
            @"systemTime": @(systemTime),
            @"systemClockElapsedRealtime": @(uptime)
        };
        [geolocation setObject: timestampMeta forKey:@"timestampMeta"];
    }
```

**Comment by tuckernuck** [comment]
The CClocation timestamp linked above doesn't say which "time"  it's talking about - 
could be phone device clock,  satellite clock, or GNSS chip clock: https://developer.android.com/reference/android/location/GnssClock, 

I'm assuming they are referring to GNSS chip clock, not "system" time, which sounds like phone device clock.   And, it's all about the satellite time - much critical infrastructure relies on the precision of the synchronized cesium clocks aboard each GPS satellite.  The chips have same data on Ios or android phones.

I'm just trying to figure out which data this plugin is actually providing and how to use it; I realize there's a dearth of detail on these APIs and it's been hard to find an expert who can explain it, which is why I'm resorting to hacking.

Maybe you can answer these:

Is your plugin's location.timestamp string representing the same value as its timestampMeta.time ?

Can you have the metadata return the GNSS clock Bias, on android it's: 
https://developer.android.com/reference/android/location/GnssClock#getFullBiasNanos()

**Comment by christocracy** [comment]
The iOS `timestamp` comes from [`CLLocation.timestamp`](https://developer.apple.com/documentation/corelocation/cllocation/1423589-timestamp?language=objc)

**Comment by christocracy** [comment]
>Can you have the metadata return the GNSS clock Bias, on android it's:

From *where* is a `GnssClock` instance to come from?

**Comment by tuckernuck** [comment]
it looks like you're already using it, by calling this method:

https://developer.android.com/reference/android/location/GnssClock#getElapsedRealtimeNanos()

**Comment by tuckernuck** [comment]
Here are some android resources...

https://sites.google.com/view/gnsstutorial
https://developer.android.com/guide/topics/sensors/gnss
https://play.google.com/store/apps/details?id=com.google.android.apps.location.gps.gnsslogger

I think you may already be returning the info I need... I'm just trying to
figure out whether it is, and how to get it..

**Comment by christocracy** [comment]
>it looks like you're already using it, by calling this method:

No.  If that were the case, I wouldn't have asked how to get an instance.

`elapsedRealtimeMeta` comes from [`android.location.Location#getElapsedRealtimeNanos`](https://developer.android.com/reference/android/location/Location#getElapsedRealtimeNanos())

Android implementation of `timestampMeta`

```java
                JSONObject timestampMeta = new JSONObject();

                timestampMeta.put("time", getTime(mLocation));
                timestampMeta.put("systemTime", System.currentTimeMillis());
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                    timestampMeta.put("systemClockElaspsedRealtime", SystemClock.elapsedRealtimeNanos()/1000000);
                    timestampMeta.put("elapsedRealtime", mLocation.getElapsedRealtimeNanos()/1000000);
                } else {
                    // TODO do something here for < JELLY_BEAN_MR1?
                }
                data.put("timestampMeta", timestampMeta);
            }
```

**Comment by christocracy** [comment]
This plugin does *not* interact with GPS *directly*.  It uses [FusedLocationProviderClient](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient) from `play-services:location`, which *abstracts* the 3 location-providers (GPS, Wifi, Cellular) into a simple black box.  The `FusedLocationProviderClient` does all the work to determine the best available location and provides that to the plugin.

**Comment by tuckernuck** [comment]
I'm aware of the 'fused' location service, but thought it exposed which
provider it was using
also...

Anyway, the android timeStampMeta code clarifies some things, thanks.

   timestampMeta.put("systemClockElaspsedRealtime",
SystemClock.elapsedRealtimeNanos()/1000000);
   timestampMeta.put("elapsedRealtime",
mLocation.getElapsedRealtimeNanos()/1000000);

I think I know what SystemClock refers to, but mLocation - is that the
time value from the location service, as opposed to the phone device
time?

As to instantiating GNSS object, looks like maybe it's a first-class
under lang.Object?

https://developer.android.com/reference/android/location/GnssClock

At any rate, I don't mean to take up all your time with this; I had
thought it would be much simpler to access GPS time given the many
applications of accurate shared time source.   I got the plugin
installed and doing a callback on android, now I just need to enable
the metadata and I'll experiment to see what's possible.

Like this?

backgroundGeoLoc.ready({   enableTimeStampMeta: true,

     thanks

**Comment by christocracy** [comment]
> but mLocation

`mLocation` is an instance of `android.location.Location`

**Comment by tuckernuck** [comment]
Good catch, thanks!

This looks promising;  I should know more soon.  It's been surprising to me
that I can use watch callbacks on android and
the phones run cool, but give flakey GPS timestamps - while on IOS, the
timestamps seem more accurate but using GPS smokes the phones in short
order..!   I'm hoping your plugin solves both issues.

[location] Mon Mar 01 2021 15:56:19 GMT-0500 (Eastern Standard Time)

   1. Object
      1. elapsedRealtime: 442290672
      2. systemClockElaspsedRealtime: 442290907
      3. systemTime: 1614632179098
      4. time: 1614632179000
