### ISSUE TITLE
want to build stopwatch

### ISSUE THREAD

**Issue by ryanpram** [transistorsoft/react-native-background-geolocation#425]
## Your Environment
* Plugin version:2.11.0
* Platform:  Android
* OS version:7.1.1
* Device manufacturer / model: OPPO A71
* React Native version (`react-native -v`):0.53.0
* Plugin config

## Expected Behavior

want to make stopwatch

## Actual Behavior

not find way to make stopwatch

## Steps to Reproduce

1.
2.
3.
4.

## Context

i want to make an stopwatch, there an function to make that?

**Comment by ryanpram** [comment]
@christocracy

**Comment by christocracy** [comment]
This a plugin designed for long-term tracking of devices.  Do not attempt to use this plugin as a "stopwatch".
