### ISSUE TITLE
Timezone of the Schedule configuration

### ISSUE THREAD

**Issue by lashae** [transistorsoft/react-native-background-geolocation#426]
I will kindly ask a general question; what is the supposed timezone of the schedule configuration?

If I configure plugin as follows:

```
BackgroundGeolocation.setConfig({
  schedule: [
    '1-7 9:00-18:00'
  ]
});
```

Does it mean that the plugin will start on *09:00 **UTC*** or will start on *09:00* at **device's timezone**?

**Comment by christocracy** [comment]
Device's timezone.

**Comment by lashae** [comment]
Thank you for the information. 

Just a kind proposal, documentation is awesome but it just lacks this timezone related bits, updating it accordingly may really make sense.
