### ISSUE TITLE
Stop tracking in background mode

### ISSUE THREAD

**Issue by evscan** [transistorsoft/react-native-background-geolocation#427]
I would like to track location only app is running.
It wastes my battery.
I am not sure if I can do this with configuration.
Any answers are appreciated.

**Comment by lashae** [comment]
What do you mean by "only app is running"? 

If you would like to track location except application is not terminated, which means app is running however it may be either foreground or background. Then using,

````
  "stopOnTerminate": true,
```

is sufficient.

**Comment by christocracy** [comment]
Ignored issue template.
