### ISSUE TITLE
Is it possible to get Major/Minor in returned Geo-Location when used in conjunction with beacons?

### ISSUE THREAD

**Issue by MossP** [transistorsoft/react-native-background-geolocation#43]
I noticed that this plugin takes over the geo-location perimeter for beacons also when it is installed. Is it possible to get the major/minor for those beacons or should I still manually range the beacons temporarily to get this information?

**Comment by christocracy** [comment]
I don't deal at all with beacons.  You still manually range the beacons.

**Comment by MossP** [comment]
Thanks for the info. I just wasn't sure if that data was in the perimeter info. Thank you.
