### ISSUE TITLE
[iOS] Prevent permissions alert to appear when starting app

### ISSUE THREAD

**Issue by mckn** [transistorsoft/react-native-background-geolocation#432]
Hello,

We are using the paid version of this library and have a scenario where we can't control the background geolocation in the app. When we are starting up the app in this scenario a permissions alert is displayed during the splash-screen.

Scenario:

1. Open the app.
2. Press a button that activates the background geolocation.
2. Enable permissions for background geolocation.
4. Close the app (kill it).
5. Go to settings.
6. Disable the permissions to track background geolocation.
7. Open the app.
8. During the splash-screen the app is asking for background geo permissions.

We would like to turn this behavior off so we later can prompt the user for permissions, if it still is needed. If its not needed then we just want the background geolocation to be turned off.

## Your Environment
* Plugin version: 2.10.1
* Platform: iOS
* OS version: iOS 11
* Device manufacturer / model: iphone X, iphone 7, iphone 7 plus
* React Native version (`react-native -v`): 0.51.0
* Plugin config

`{
    desiredAccuracy: 0,
    distanceFilter:  50,
    locationUpdateInterval: 1000,
    fastestLocationUpdateInterval: 60000,
    enabled: true,
    heartbeatInterval: 300,
    foregroundService: true,
    notificationTitle: "text",
    notificationText: "text",
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    notificationSmallIcon: "drawable/ic_stat_ac_unit",
    stopOnTerminate: false,
    locationAuthorizationRequest: "Always"
  }`

## Expected Behavior

We would like to start the app without being asked for permissions. Then we should like to be able to start the background geolocation from our code and before that prompt the user for permissions.

*or*

The user should be prompted after the application have been started. Not during the splash-screen.

## Actual Behavior
The permissions alert was displayed during startup of the application.

![example](https://image.ibb.co/b6mJxx/1.png)

## Steps to Reproduce
1. Open the app.
2. Press a button that activates the background geolocation.
2. Enable permissions for background geolocation.
4. Close the app (kill it).
5. Go to settings.
6. Disable the permissions to track background geolocation.
7. Open the app.
8. During the startup, the app is asking for background geo permissions.

## Context
Get a seemless app that works in all scenarios.

## Debug logs
N/A

**Comment by christocracy** [comment]
Listen to [`providerchange`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#providerchange) event *before* you execute `#configure`.

If you find that location permission is disabled, `#stop` the plugin.

**Comment by mckn** [comment]
Well, we don't run `#configure` when we start the app. 

And we tried to add a listener to the `providerchange` event but it is not fired since the app is killed/not running when we disable the permissions.

Sorry, any more idéas?

**Comment by christocracy** [comment]
You *need* to call `#configure` as soon as your app boots.  The plugin does a bunch of one-time initialization when you call `#configure`.

Executing `#configure` will *cause* an initial `providerchange` event to fire.

**Comment by mckn** [comment]
Okay, I will try that and see if that resolves the issue. I will get back to you.

Thanks for quick replies! :)

**Comment by mckn** [comment]
Hello again,

I just tried the trick above without any luck. I tried to call stop at the first line of js code but the permissions alert is still displayed. I guess that the native code runs before the js code.

Would it be possible to add a another `locationAuthorizationRequest` that would be `off` or something similar that would not prompt for permissions and just stop the service if permissions is missing?

**Comment by ahmetilhann** [comment]
Hello, I have the same problem. 
I am glad, if you help me

![ekran resmi 2018-03-16 12 35 36](https://user-images.githubusercontent.com/5680957/37513633-a7df85e2-2916-11e8-81c6-7ee0366d6910.png)

This is the application permit

![ekran resmi 2018-03-16 12 35 55](https://user-images.githubusercontent.com/5680957/37513646-b246b154-2916-11e8-8aa5-7629cbcb092a.png)

**Comment by christocracy** [comment]
@ahmetilhann You're missing the `Always and When in Use Usage Description` in your `.plist`.  Add that key.

![](https://dl.dropboxusercontent.com/s/lv2jz3qi1jcrbyr/Screenshot%202018-03-16%2008.28.04.png?dl=1)

**Comment by mckn** [comment]
@christocracy any idea how to proceed with this one? is there any way to do it with the current code base or should we wait for a new release? Thanks for the quick responses!

**Comment by christocracy** [comment]
I have reproduced this.  I fix will be available in the next `beta` release today or tomorrow.

**Comment by mckn** [comment]
Awesome, thanks! @christocracy

**Comment by christocracy** [comment]
That "next beta release" won't land *here* soon though.  It will only be available in the private repo.   This repo is the "public version" which gets updates only every 3 months.

**Comment by christocracy** [comment]
[`2.12.0-beta.1`](https://github.com/transistorsoft/react-native-background-geolocation/issues/442) is released.

**Comment by leonardogutierrezh** [comment]
I keep getting this error with the private version in 2.14.2
