### ISSUE TITLE
How can get current location?

### ISSUE THREAD

**Issue by ahmetilhann** [transistorsoft/react-native-background-geolocation#433]
How can I get the user's current location without starting when the app is opened? 
For example "Position before the user starts walking"

## Environment
* Plugin version: 2.11.0
* Platform: iOS or Android: IOS
* OS version: 8
* Device manufacturer / model: Iphone 6 emulator
* React Native version (`react-native -v`): 0.53.3

**Comment by christocracy** [comment]
It’s a good idea to quickly scan the docs for every method available to you.

You will find the method `#getCurrentPosition`
