### ISSUE TITLE
Push Notification Customization Question

### ISSUE THREAD

**Issue by leofontes** [transistorsoft/react-native-background-geolocation#436]
## Your Environment
* Plugin version: 2.11.0
* Platform: All
* OS version: All
* Device manufacturer / model: All 
* React Native version (`react-native -v`): 0.49.3
* Plugin config

## Expected Behavior

The app fires Push Notifications whenever the user moves or stops, when it interacts a GeoFence, etc. 

However I can't find on the documentation where I should configure these notifications to suit my needs, ie:
- Customize the geofences notifications
- Configure which notifications should fire or not

Where can I find this information, or how should I do it? Which file, etc.

## Actual Behavior
N/A

## Steps to Reproduce
N/A

## Context
Notify the user whenever it enters a Geofence so that he/she will enter the app to interact.

## Debug logs
N/A

Also, great job on this lib! Waiting to hear from you, I intend to buy the license in a couple of months ;)

**Comment by christocracy** [comment]
These aren’t push notifications, they’re *local* notifications, and there’s no api to use them.  They’re only shown when you enable `debug: true`.  They’re just for development feedback.

If you want to show your own, simply use some dedicated notification module.

**Comment by leofontes** [comment]
@christocracy sorry I used the wrong term my bad, but still, is it possible to customize them and use the ones you already implemented?

**Comment by christocracy** [comment]
It’s not possible.  Use a dedicated module.
