### ISSUE TITLE
iOS defaults to "When in Use" instead of "Always"

### ISSUE THREAD

**Issue by EsdrasEtrenne** [transistorsoft/react-native-background-geolocation#437]
## Your Environment
* Plugin version: 2.11
* Platform: iOS
* OS version: Mac OS High Sierra
* Device manufacturer / model: Any iPhone version
* React Native version (`react-native -v`): .54
* Plugin config:
```
      desiredAccuracy: 0,
      distanceFilter: 5,
      disableElasticity: true,
      activityRecognitionInterval: 500,
      elasticityMultiplier: 0.5,
      stopTimeout: 400,
      activityType: "AutomotiveNavigation",
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF ,
      stopOnTerminate: true,
      preventSuspend: true,
      heartbeatInterval: 60,
      startOnBoot: true,
      foregroundService: true,
      locationAuthorizationRequest: "Always",
      schedule: [
        '1-7 10:30-21:30',   // Sunday-Sat: 10:30am-9:30pm
      ]
```

## Expected Behavior
When App loads it should ask user for "Always Use" permission

## Actual Behavior
App asks for "When in Use" permission. User has to leave app and go to settings and turn it on manually.

## Steps to Reproduce
Following installation instruction. In info.plist I added:
-Privacy When in Use 
-Privacy Always
-Privacy Always and When in Use

I think this is similar to #282

**Comment by christocracy** [comment]
You’re using a map component (eg react-native-maps), right?

What does that map component do when it happens to be the *first* component to request location authorization from the user?  It requests “When in Use”.

**Comment by EsdrasEtrenne** [comment]
Ok, I see that there is an open pull request on react-native-maps with a similar problem:

https://github.com/react-community/react-native-maps/pull/1184

**Comment by christocracy** [comment]
It's not a *problem*, really.  Just make sure you don't set the `MapView` property [`showsUserLocation`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/src/simple-map/SimpleMap.js#L255) until [after you've told the `BackgroundGeolocation` plugin to `#start`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/src/simple-map/SimpleMap.js#L94).

**Comment by EsdrasEtrenne** [comment]
Oh ok, I havent used that key before. I will try it out. Thank you
