### ISSUE TITLE
How to Hook for Unique Locations which are also POST'ed to Database

### ISSUE THREAD

**Issue by njho** [transistorsoft/react-native-background-geolocation#439]
## Your Environment
- Plugin version: 2.11
- Platform: Android
- OS version: 7.0
- Device manufacturer / model: Samsung Galaxy S8
- React Native version (react-native -v): 0.48.4
- Plugin config

## Expected Behavior
No bugs

## Actual Behavior
No bugs

## Steps to Reproduce
No bugs

## Context
I am trying to call a function for every `location` **that is _unique_ AND _persisted to database_.** In effect, every location that my server application sees as a real event.

This function will post additional data to my server which cannot be put in the `EXTRAS`. I believe this would correspond with all data which is valid to be persisted to the SQLite db.

**Current problems I'm bumping into:**
1. **Cannot solely rely on `Location` event:** `Location` events are not ALL posted to HTTP, so I may be collecting and posting extraneous data.
2. **Cannot solely rely on `HTTP` event:** Should phone be out of network, the `HTTP` event will still be triggered, but there will be no reference to the UUID, or `location` it was trying to POST, making it difficult to sync info with my `function(uuid)`...

Possible Solutions Being Considered
1. Collect Information for every `location` event - which would cause some extra bloat on app, then, upload to database for every successful `HTTP` event that contains uuid. 
2. Create some sort of database, that can somehow cross-reference whether a `location` is also an `http` event.

Is there some sort of better solution for this? What I'm considering seems to be less than ideal :)

Thanks Christocracy

**Comment by njho** [comment]
Accidentally referenced the issue :/

**Comment by christocracy** [comment]
Closed / stale.
