### ISSUE TITLE
more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by arunkumarcap91** [transistorsoft/react-native-background-geolocation#440]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-background-geolocation:processReleaseResources'.
Error: more than one library with package name 'com.google.android.gms.license'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by christocracy** [comment]
I’ve seen you post this issue at three separate and unrelated projects. 

Are you a complete **idiot**?
