### ISSUE TITLE
watchPosition method returns two success callbacks at once with same location

### ISSUE THREAD

**Issue by tiramesu55** [transistorsoft/react-native-background-geolocation#443]
## Your Environment
* Plugin version: 2.10.1
* Platform: iOS and Android
* OS version: iOS 1O or 11, Android 6 and up 
* React Native version: 0.51.0
* Plugin config: {
      stationaryRadius: 10, 
      desiredAccuracy: 0,
      distanceFilter: 25, 
      stopTimeout: 0,  
      debug: false, 
      logLevel: 'LOG_LEVEL_OFF',
      stopOnTerminate: true,    
      startOnBoot: true,  
}

## Expected Behavior
One callback

## Actual Behavior
Two callbacks

## Context
I tested my app on real devices and had the same issue.

My code: 
```
initGeolocation() {  
	BackgroundGeolocation.configure(
		configure, 
		() => this.onAppResume(),  
		() => this.onAppSuspend()  
	);     
}

onAppResume() {    
	BackgroundGeolocation.watchPosition((location) => {  
            console.log(" \n \n Callback ---------- ");
	    
	}, (errorCode) => { 
	  this.onAppSuspend();
	}, {
	  interval: 2000,    
	  persist: false,    
	});   
}   
```   
 
Result: 

![mar-22-2018](https://user-images.githubusercontent.com/8151201/37780512-94d4229c-2df7-11e8-944e-5eb79d5e2a6e.gif)

**Comment by christocracy** [comment]
You're saying this occurs for **both** Platform: iOS and Android??

**Comment by tiramesu55** [comment]
Yep, we collected location points in realtime on real devices and got lots of duplicate.

**Comment by christocracy** [comment]
are you calling `#stopWatchPosition` when your app suspends?

**Comment by tiramesu55** [comment]
Yes, sure. Also when I clean my build and recreate it on another simulator like IOS (7, 8 etc.) I get the same issue at start.

**Comment by christocracy** [comment]
Show me your `AppState` `change` listener

**Comment by tiramesu55** [comment]
I don't have any listeners I use watchPosition only

**Comment by christocracy** [comment]
You must have an AppState change listener to drive onAppStateChange?

**Comment by tiramesu55** [comment]
You mean this: https://facebook.github.io/react-native/docs/appstate.html

**Comment by christocracy** [comment]
Yes, surely you’ve implemented an AppState change listener?

**Comment by tiramesu55** [comment]
No, I also use WatchPosition method in background mode because it provides high accuracy, but I think it's a topic for another conversation. The main question is why it fires twice.

**Comment by christocracy** [comment]
I must be firing twice because you're calling `onAppResume` *twice*.

Be careful with `#watchPosition` in the background:  it's basically an `ON` switch for location-services.  It will keep your app alive in the background and drain the battery *very* quickly.  It provides no more higher accuracy than the plugin's default tracking behaviour.

**Comment by tiramesu55** [comment]
Hi Chriss,
 I was testing BackgroundGeolocation in the live app and was observing that it would collect points for some period of time then "stop" collecting and then starts again. Originally I thought that I was loosing satellite view.    Few days later I was collecting data with iOS and Android at the same time and each devise would have "breaks" at different time.  At a closer look I found that each devise collects "same" point multiple times, so I made a very simple test app and switched from start to watchPosition attempting to collect every 3 sec (I know this might drain device battery, but this is not a concern at the moment). 
[App.js.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/1849270/App.js.zip)

The console log log is below.  I tried it on the iPhone with virtually same results.  As you can see the component reports same point multiple times:
 
 Callback ---------- 2018-03-26T19:25:39.562Z
2018-03-26 15:26:36.387863-0400 gpsbackground[11517:217164]  
 
 Callback ---------- 2018-03-26T19:25:39.562Z
2018-03-26 15:26:39.390 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:25:39.562Z
2018-03-26 15:26:39.389920-0400 gpsbackground[11517:217164]  
 
 Callback ---------- 2018-03-26T19:25:39.562Z
2018-03-26 15:26:42.765 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:26:42.753Z
2018-03-26 15:26:42.765203-0400 gpsbackground[11517:217164]  
 
 Callback ---------- 2018-03-26T19:26:42.753Z
2018-03-26 15:26:45.389 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:26:42.753Z
2018-03-26 15:26:45.389536-0400 gpsbackground[11517:217164]  
 
 Callback ---------- 2018-03-26T19:26:42.753Z
2018-03-26 15:26:48.391 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:26:45.383Z
2018-03-26 15:26:48.390753-0400 gpsbackground[11517:217164]  
 
 Callback ---------- 2018-03-26T19:26:45.383Z
2018-03-26 15:26:51.389 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:26:46.753Z
2018-03-26 15:26:51.389352-0400 gpsbackground[11517:217164]  
 
 Callback ---------- 2018-03-26T19:26:46.753Z
2018-03-26 15:26:54.389 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:26:46.753Z
2018-03-26 15:26:54.388750-0400 gpsbackground[11517:217164]  
 
 Callback ---------- 2018-03-26T19:26:46.753Z
2018-03-26 15:26:57.389 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:26:46.753Z
2018-03-26 15:26:57.388969-0400 gpsbackground[11517:217164]  
 
 Callback ---------- 2018-03-26T19:26:46.753Z

**Comment by tiramesu55** [comment]
Hi Chris,
I was running live app with BackgrooundGeoLocation on iPhone and observed that it had "breaks" in data collection. I thought that I was losing a satellite view, but next day I was using iPhone and Android simultaneously and had "breaks" at different time. I reviewed collected points more closely and found that the BackgroundGeolocation at some point records "cached" coordinate multiple times, then records new locations for some time and then again records same location multiple times. 
I built a simple component to test this hypothesis (I switched from start method to watchPosition) and it seemed to "cache" even the timestamp. I tested on the emulator and on the device.  Here is console log from the emulator and the code.
Thank you
Alec
[App.js.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/1849332/App.js.zip)
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:14.015159-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:17.018 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:17.017789-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:20.015 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:20.015292-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:23.162 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:23.150Z
2018-03-26 15:59:23.161988-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:23.150Z
2018-03-26 15:59:26.015 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:23.150Z
2018-03-26 15:59:26.014795-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:23.150Z
2018-03-26 15:59:29.014 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:26.008Z
2018-03-26 15:59:29.014339-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:26.008Z
2018-03-26 15:59:32.014 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:27.150Z
2018-03-26 15:59:32.014500-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:27.150Z
2018-03-26 15:59:35.014 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:27.150Z
2018-03-26 15:59:35.014344-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:27.150Z

**Comment by tiramesu55** [comment]
Hi Chris,
I was running live app with BackgrooundGeoLocation on iPhone and observed that it had "breaks" in data collection. I thought that I was losing a satellite view, but next day I was using iPhone and Android simultaneously and had "breaks" at different time. I reviewed collected points more closely and found that the BackgroundGeolocation at some point records "cached" coordinate multiple times, then records new locations for some time and then again records same location multiple times. 
I built a simple component to test this hypothesis (I switched from start method to watchPosition) and it seemed to "cache" even the timestamp. I tested on the emulator and on the device.  Here is console log from the emulator and the code.
Thank you
Alec
[App.js.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/1849332/App.js.zip)
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:14.015159-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:17.018 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:17.017789-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:20.015 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:20.015292-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:58:20.122Z
2018-03-26 15:59:23.162 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:23.150Z
2018-03-26 15:59:23.161988-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:23.150Z
2018-03-26 15:59:26.015 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:23.150Z
2018-03-26 15:59:26.014795-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:23.150Z
2018-03-26 15:59:29.014 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:26.008Z
2018-03-26 15:59:29.014339-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:26.008Z
2018-03-26 15:59:32.014 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:27.150Z
2018-03-26 15:59:32.014500-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:27.150Z
2018-03-26 15:59:35.014 [info][tid:com.facebook.react.JavaScript]  
 
 Callback ---------- 2018-03-26T19:59:27.150Z
2018-03-26 15:59:35.014344-0400 gpsbackground[11995:231706]  
 
 Callback ---------- 2018-03-26T19:59:27.150Z

**Comment by tiramesu55** [comment]
I might sent you several copies of my response, because I did not see an indication that the post was successful.  Sorry if that was the case.

Alec

**Comment by christocracy** [comment]
Are you aware that `#watchPosition` is not the primary mechanism for location-tracking?  `#watchPosition` was designed for use in the foreground, for the case where you might want temporary high-frequency updates for the user's current position on a map.

The plugin's [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation) is to automatically toggle location-services and track the position  when the device is detected to be moving.

You do not need to use `#watchPosition`.

**Comment by tiramesu55** [comment]
Thanks for the reply.  Ill try the recommended background method some more and will let youo know.

Alec

**Comment by christocracy** [comment]
Update?

**Comment by tiramesu55** [comment]
Chris,
I do not monitor this account too often.  Almost done building a test app
that I can send you.  Tomorrow will take 2 phones to the test and then send
you app and data.

Thanks,
Alec

**Comment by christocracy** [comment]
Update?

**Comment by christocracy** [comment]
Closed for lack of feedback.

**Comment by ansarikhurshid786** [comment]
you thread help to identify issue in my code. my code also request 2 times watchPosition then 2 time get call success. 

Thankyou
