### ISSUE TITLE
Android notification always visible even when foregroundService: false on Android 8

### ISSUE THREAD

**Issue by AlexandreMaistret** [transistorsoft/react-native-background-geolocation#445]
## Your Environment
* Plugin version: 2.11.0
* Platform:  Android
* OS version: 8.0.0
* Device manufacturer / model: SONY Xperia Compact X
* React Native version (`react-native -v`):  0.51.0
* Plugin config: 

        desiredAccuracy: 10,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: true, 
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   
        startOnBoot: true,        

        //IOS
        preventSuspend: true,

        //ANDROID
        foregroundService: false, 

        // HTTP / SQLite config
        url: 'https://myawesomeproject.com',
        batchSync: false,       
        autoSync: true,         
        locationTemplate: '{ "latitude":<%= latitude %>, "longitude":<%= longitude %>, "timestamp":"<%= timestamp %>" }',
        autoSyncThreshold: 0,
        maxDaysToPersist: 10

## Expected Behavior
On my app, I've set up the background-geolocation module to not show notification "Location service activated" when this module is running (with foregroundService: false). 

## Actual Behavior
This notification is shown on my device which runs android 8, and also when the app is killed, my app still works in background which is normal since the background-geolocation module is working, but it uses a lot of RAM, (200 mo). I have tried my app without the background-geolocation module running, and nothing is running in background, meaning that all this RAM must be used by the background-geolocation module.

I have tried on another device (Android 6.0.1 SONY Xperia Z3 compact) and everything works fine. The notification doesn't show up, and it does not use a lot of RAM when the app is killed (20 mo).

## Steps to Reproduce
Try the module on a android 8 device

## Context
I want to get the position of the user even if the app is not running and whitout a notification shown to him.

**Comment by christocracy** [comment]
foregroundService is enforced for Android 8 due to strict new Background Execution limits of Android 8.   There is no way to hide it on Android 8.

**Comment by AlexandreMaistret** [comment]
Ok I understand for the notification, but why on Android 8 the background-geolocation module uses a lot of RAM (200mo-250mo) when it is running in background ? Is it still due to Android 8 ? Because it uses way more battery...

On android 6 and 7, it uses only 20mo of ram when it runs in background.

**Comment by christocracy** [comment]
Here's a blank react-native app run as-is (no `react-native-background-geolocation`
```
$ react native init MemTest
$ cd MemTest
$ react-native run-android
```
I let it run for 20 min with app in foreground:

![](https://dl.dropboxusercontent.com/s/ju8cc7xgkkrvnwq/Screenshot%202018-03-26%2011.26.09.png?dl=1)

**Comment by AlexandreMaistret** [comment]
So I have create that blank app and that is what I'm having on my android profiler : 
![memtest 8](https://user-images.githubusercontent.com/14938428/37920007-eb8a9022-3125-11e8-8779-cfcfcbb005ea.PNG)
The memory doesn't go too up just like on your phone.

And this, it is the android profiler when I'm running my app with the react-native-background-geolocation module : 

![blinky 8 2](https://user-images.githubusercontent.com/14938428/37920604-9a0c9540-3127-11e8-9668-4b1d08b8b72d.PNG)

The app still runs and uses a lot of memory when I kill the app  on my android 8 device when I have launched the react-native-background-geolocation module 

On my android 6 it is totally killed in the android profiler and in the dev parameters of the device I can see that a service is still running in background which I assume it is the react-native-background-geolocation module  since positions are sent to my server. 

On the same app, when I don't launch the react-native-background-geolocation module, the app is totally killed and no service is running.

**Comment by christocracy** [comment]
The app process *will* still remain running running when you configure `stopOnTerminate: false`.  If you don't want to continue tracking after terminating you app, set `stopOnTerminate: true`.

**Comment by AlexandreMaistret** [comment]
Ok thanks for all theses informations !

**Comment by itsyogesh** [comment]
Hi Chris,

So I are facing the same issue, and since you mentioned that there is no way you can remove the notification in android 8, I am looking into an alternative method by using `background-geolocation`'s `#getCurrentPosition`. 

But I can't seem to wrap my head around not executing the `background-geolocation`'s `#start` method and the using the `#getCurrentPosition`. If the start function is never executed, how would we get the current location. 

One idea could be that `react-native-background-geolocation` registers a service when the app starts, but I am not quite sure if that's the case. Could you shed some light on this.

Cheers
