### ISSUE TITLE
App(release) Android  crash when start background geolocation (Android Oreo)

### ISSUE THREAD

**Issue by nhatdotranminh** [transistorsoft/react-native-background-geolocation#448]
## Your Environment
* Plugin version:
* Platform:  Android
* OS version: 8.0(Oreo)
* Device manufacturer / model: Nokia 6
* React Native version (`react-native -v`):0.53.3
* Plugin config 
Googleplay services 11.8.0

## Expected Behavior

When i start background geolocation, app crash

## Actual Behavior

I am running through the install flow for android and the app now crashes on startup.

## Steps to Reproduce

1.Run through the setup flow for android with same configs
2.When start up it crash
3.
4.

## Context

Trying to build background location for Android app
## Debug logs

03-27 00:52:26.780 32756 32756 E AndroidRuntime: FATAL EXCEPTION: main
03-27 00:52:26.780 32756 32756 E AndroidRuntime: Process: com.movecrop, PID: 32756
03-27 00:52:26.780 32756 32756 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
03-27 00:52:26.780 32756 32756 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1775)
03-27 00:52:26.780 32756 32756 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-27 00:52:26.780 32756 32756 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-27 00:52:26.780 32756 32756 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6548)
03-27 00:52:26.780 32756 32756 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-27 00:52:26.780 32756 32756 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-27 00:52:26.780 32756 32756 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-27 00:52:27.045 31377 31377 E STBMonitorReceiver: dropboxTag:data_app_crash;dropboxTime:1522086746932
03-27 00:52:27.076 31377 31377 E STBIntentService: Service Started..

**Comment by nhatdotranminh** [comment]
Oh, sorry my bad, but you sure that's the reason? Tks you

**Comment by christocracy** [comment]
💯% sure

**Comment by nhatdotranminh** [comment]
Tks you, pls close this issue, i will try again with a license

**Comment by martwetzels** [comment]
I ran into this issue as well after having to initialize a new RN project after upgrading. I give at a different name and forgot that the license was coupled to the package name. Perhaps this issue can be made a bit more explicit in the logs? It was difficult to debug.

**Comment by christocracy** [comment]
License failure in release builds is silent by design.

**Comment by martwetzels** [comment]
Why is that? For debug I can imagine, but I don't understand why it makes the app crash without being explicit about what is wrong? The effect of the silent failure isn't silent, so might as well make the cause clear (it is due to license failure). I'm interested in your decision out of curiosity, no critique.

**Comment by christocracy** [comment]
I’m not going to discuss this in the public repo.

**Comment by mikehardy** [comment]
I just purchased but haven't configured yet, and on android I have a super-obvious persistent toast telling me I have a license validation failure, on 3.0-beta.4 at least. No crash. I also understand if even this is unwanted and you wish to delete, discussion-wise but thought it might be helpful for future folks. Cheers

**Comment by christocracy** [comment]
Did you see the Android setup doc and paste your key into the AndroidManifest?

**Comment by mikehardy** [comment]
> Did you see the Android setup doc and paste your key into the AndroidManifest?

Oh definitely - clear instructions. I have not done my part yet to finish setup. Just was saying that if someone - like me currently - has not done their part the error is a very clear toast now. No confusion as to what is wrong when you see a toast saying "LICENSE VALIDATION ERROR"

**Comment by christocracy** [comment]
Now that you’re a customer, you should post questions to the private repo.
