### ISSUE TITLE
Could not find :tslocationmanager: in project :react-native-background-geolocation

### ISSUE THREAD

**Issue by Moveonit** [transistorsoft/react-native-background-geolocation#452]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android  (iOS works perfectly)
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.51.0
* Plugin config

## Actual Behavior
I can't exec gradle and run the application, it's like if the project "react-native-background-geolocation" wouldn't process this line of his gradle "compile(name:'tslocationmanager', ext:'aar')" 

## Steps to Reproduce
I have followed the steps of the Wiki

## Context
I have tried to follow the solutions of every similiar issues find here without success and I have retried many times from the start.

## Debug logs
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find :tslocationmanager:.
     Required by:
         project :app > project :react-native-background-geolocation

Thanks for the support

**Comment by christocracy** [comment]
If you're following the setup steps linked from master, those are referencing the latest version of the plugin `2.12.0`.  You're using `2.11.0`.

The setup steps changed in `2.12.0`

**Comment by christocracy** [comment]
Update?

**Comment by kermopajula** [comment]
Is this correct that "compile(name: 'tslocationmanager', ext: 'aar')" line should be removed from android/app/build.gradle when upgrading to 2.12.0 version?

**Comment by christocracy** [comment]
Yes.  You only need to provide the `maven url` now.

**Comment by christocracy** [comment]
Closed for lack of feedback.
