### ISSUE TITLE
NotificationChannel issue in Android O

### ISSUE THREAD

**Issue by joterr** [transistorsoft/react-native-background-geolocation#453]
## Your Environment
* Plugin version: 2.11.2
* Platform: only Android
* OS version: 8.1 (Oreo) - API 27
* Device manufacturer / model: Google Pixel 2
* React Native version (`react-native -v`): 0.53.3
* Plugin config

```
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 1,
elasticityMultiplier: 8,
activityRecognitionInterval: 500,
minimumActivityRecognitionConfidence: 25,
stopTimeout: 30,
stationaryRadius: 25,
debug: debugEnabled,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
stopOnTerminate: false,
startOnBoot: true,
autoSync: true,
enableHeadless: false,
foregroundService: true,
notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
notificationSmallIcon: "drawable/custom_notification_small_icon",
notificationText: "XXXXXX",
preventSuspend: true,
heartbeatInterval: 30,
fastestLocationUpdateInterval: 1000,
forceReloadOnBoot: true,
forceReloadOnMotionChange: true,
forceReloadOnHeartbeat: true,
forceReloadOnLocationChange: true,
url: .........,
httpRootProperty: '.',
params: .........,
locationTemplate: ........
```

## Expected Behavior
According to the documentation there should be a notification icon in the notification bar. It's working perfectly on all other android devices lower Android O.

## Actual Behavior
An error occurs (a toast pops up for dev and a logcat entry appears). There is no notification in notification bar.

I found a solution on Stackoverflow -    https://stackoverflow.com/questions/46990995/on-android-8-1-api-27-notification-does-not-display

## Steps to Reproduce
1. configure and start BackgroundGeolocation.

## Context
Just starting BackgroundGeolocation.

## Debug logs

No Channel found for pkg=XXXX, channelId=null, id=9942585, tag=null, opPkg=XXXX, callingUid=10132,userId=0, incomingUserId=0, notificationUid=10132, notification=Notification(channel=null pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE)

Thank you!

**Comment by christocracy** [comment]
This error is not coming from the plugin.

Show me your `android/app/build.gradle`

**Comment by joterr** [comment]
Here it is:

apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId 'XXXX'
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 60
        versionName "0.6.0"
        multiDexEnabled true
        ndk {
           abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    productFlavors {
    }
}

repositories {
    flatDir {
        dirs "../../node_modules/react-native-background-geolocation/android/libs"
    }
}

dependencies {
    compile project(':react-native-video')
    compile project(':react-native-uuid-generator')
    compile project(':react-native-push-notification')
    compile project(':react-native-pdf')
    compile project(':react-native-network-info')
    compile project(':react-native-maps')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-background-geolocation')
    compile project(':react-native-background-fetch')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile(name: 'tslocationmanager', ext: 'aar')
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-location:11.8.0'
    compile ('com.google.android.gms:play-services-gcm:11.8.0') {
        force = true
    }
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:11.8.0'
    compile 'com.google.android.gms:play-services-maps:11.8.0'
    // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

**Comment by christocracy** [comment]
add to your `dependencies`

```
compile "com.android.support:appcompat-v7:26.1.0"
```

Btw, the latest version `2.12.0` beta has improvements for [aligning `play-services` version](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Solving-Android-Gradle-Conflicts) so you don't have to do all that `exclude group` / `force` stuff.

`react-native-maps` understands these Gradle Properties as well.

**Comment by joterr** [comment]
That's it - thank you!
