### ISSUE TITLE
check provider on Headless Task

### ISSUE THREAD

**Issue by atifaziz1** [transistorsoft/react-native-background-geolocation#455]
How to check provider when enableHeadless is true?
I want provider callback or any solution to check that internet or gps is enable or not on headless js task.

* Plugin version: 2.11.0
* Platform: Android
* OS version: Lollypop
* Device manufacturer / model: Motorola / moto G
* React Native version : 0.50.4

**Comment by christocracy** [comment]
`providerchange` events should fire into Headless Task.  Try it yourself:  Go to Settings->Location and disable Location service or change the mode (*Device only*, *High Accuracy*).

`connectionchange`, `enabledchange` do not currently fire into Headless task.  These are 2 new events recently added and I forget to add logic to fire in Headless mode.

**Comment by atifaziz1** [comment]
ok @christocracy thanks (Y)

**Comment by atifaziz1** [comment]
@christocracy how can i hit request in Headless?

**Comment by christocracy** [comment]
Yes, you can execute `#getCurrentPosition` in Headless mode.

**Comment by christocracy** [comment]
However, you'll probably receive an error if you attempt `#getCurrentPosition` in HeadlessTask when BackgroundGeolocation is currently disabled.  I've just fixed this in premium version.

**Comment by christocracy** [comment]
The fix for `#getCurrentPosition` in Headless mode while plugin is disabled will be posted in next beta release.

**Comment by atifaziz1** [comment]
@christocracy I am using plugin 2.11.0 , I am registering headless task on index.js.
I have many screen on app. let say Screen (A,B,C,D)
 I am configuring BackgroundLocation on screen-A , and move from A to any other screens and then kill or destroy the application , headless task doesn't work. If I kill or destroy app when screen-A is in foreground then headless task does work.In short , headless task works on screen-A and nothing from other screens. Please guide me what's the issue is?

**Comment by christocracy** [comment]
You should configure `BackgroundGeolocation` in your root application component, not in some screen which may or may not render.  Your root application component is *always* rendered.

```javascript
AppRegistry.registerComponent('MyApp', () => App);  
```

The code in your "screens" are each free to independently interact with the plugin's API methods after your `App` component has configured it.  Configuring the plugin does not imply `#start`ing the plugin.

**Comment by atifaziz1** [comment]
@christocracy headless is not working on background , this is my configuration 
BackgroundGeolocation.configure({
      desiredAccuracy: 0,
      distanceFilter: 1000,
      stopTimeout: 1,
      debug: true, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      enableHeadless: true,
      stopOnTerminate: false, 
      startOnBoot: true, 
      locationUpdateInterval:5000,
      }, (state) => {
        
          console.log('- Configure success');
         
      });

**Comment by christocracy** [comment]
Show me `$ adb logcat -s TSLocationManager` of your app booting from scratch and being terminated.

**Comment by atifaziz1** [comment]
![screen shot 2018-04-04 at 6 46 52 pm](https://user-images.githubusercontent.com/37400835/38311540-e1f1f1b2-3838-11e8-88cb-cb59a2e09a00.png)

you mean this one?

**Comment by christocracy** [comment]
Yes, but show me the raw text and execute it from console, filtered with `-s TSLocationManager` so I don't see all the other noise.

**Comment by atifaziz1** [comment]
I/TSLocationManager(20275): [c.t.l.util.Sensors print] 
I/TSLocationManager(20275): ╔═════════════════════════════════════════════
I/TSLocationManager(20275): ║ DEVICE SENSORS
I/TSLocationManager(20275): ╠═════════════════════════════════════════════
I/TSLocationManager(20275): ╟─ ✅  ACCELEROMETER: {Sensor name="LIS3DH 3-axis Accelerometer", vendor="ST Micro", version=1, type=1, maxRange=39.24, resolution=0.009810001, power=0.25, minDelay=10000}
I/TSLocationManager(20275): ╟─ ⚠️  GYROSCOPE:  none.  Motion-detection system performance will be degraded
I/TSLocationManager(20275): ╟─ ✅  MAGNETOMETER: {Sensor name="AK8963 3-axis Magnetic field sensor", vendor="Asahi Kasei", version=1, type=2, maxRange=2000.0, resolution=0.0625, power=6.8, minDelay=20000}
I/TSLocationManager(20275): ╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
I/TSLocationManager(20275): ╚═════════════════════════════════════════════
I/TSLocationManager(20275): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(20275): ╔═════════════════════════════════════════════
I/TSLocationManager(20275): ║ TSLocationManager version: 2.11.2
I/TSLocationManager(20275): ╠═════════════════════════════════════════════
I/TSLocationManager(20275): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(20275):   ✅  Google Play Services: connected (version code:11910000)
D/TSLocationManager(20275): [c.t.l.d.s.SQLiteLocationDAO dbh] 
D/TSLocationManager(20275):   ✅  Opened database
D/TSLocationManager(20275): [c.t.l.d.s.SQLiteLocationDAO prune] 
D/TSLocationManager(20275):   ℹ️  PRUNE -1 days
D/TSLocationManager(20275): [c.t.l.data.sqlite.GeofenceDAO dbh] 
D/TSLocationManager(20275):   ✅  Opened database
I/TSLocationManager(20275): [c.t.l.a.BackgroundGeolocation <init>] 
I/TSLocationManager(20275):   ??????  Connecting to GooglePlayServices...
I/TSLocationManager(20275): [c.t.l.settings.Settings print] 
I/TSLocationManager(20275): ╔═════════════════════════════════════════════
I/TSLocationManager(20275): ║ BackgroundGeolocation Settings
I/TSLocationManager(20275): ╠═════════════════════════════════════════════
I/TSLocationManager(20275): {
I/TSLocationManager(20275):   "isMoving": false,
I/TSLocationManager(20275):   "enabled": false,
I/TSLocationManager(20275):   "odometer": 95.353714,
I/TSLocationManager(20275):   "schedulerEnabled": false,
I/TSLocationManager(20275):   "trackingMode": "location",
I/TSLocationManager(20275):   "distanceFilter": 1000,
I/TSLocationManager(20275):   "desiredAccuracy": 0,
I/TSLocationManager(20275):   "desiredOdometerAccuracy": 100,
I/TSLocationManager(20275):   "locationUpdateInterval": 5000,
I/TSLocationManager(20275):   "fastestLocationUpdateInterval": 10000,
I/TSLocationManager(20275):   "locationTimeout": 60,
I/TSLocationManager(20275):   "deferTime": 0,
I/TSLocationManager(20275):   "disableElasticity": false,
I/TSLocationManager(20275):   "elasticityMultiplier": 1,
I/TSLocationManager(20275):   "allowIdenticalLocations": false,
I/TSLocationManager(20275):   "activityRecognitionInterval": 10000,
I/TSLocationManager(20275):   "minimumActivityRecognitionConfidence": 75,
I/TSLocationManager(20275):   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
I/TSLocationManager(20275):   "disableStopDetection": false,
I/TSLocationManager(20275):   "stationaryRadius": 25,
I/TSLocationManager(20275):   "stopTimeout": 1,
I/TSLocationManager(20275):   "stopOnStationary": false,
I/TSLocationManager(20275):   "url": "http:\/\/demo.workforcecity.com:8081\/api\/location",
I/TSLocationManager(20275):   "method": "POST",
I/TSLocationManager(20275):   "autoSync": true,
I/TSLocationManager(20275):   "autoSyncThreshold": 0,
I/TSLocationManager(20275):   "batchSync": false,
I/TSLocationManager(20275):   "maxBatchSize": -1,
I/TSLocationManager(20275):   "params": {
I/TSLocationManager(20275):     "dateTime": "2018-03-30 12:46",
I/TSLocationManager(20275):     "lon": 35.2,
I/TSLocationManager(20275):     "lat": 70.45,
I/TSLocationManager(20275):     "dutyId": 979
I/TSLocationManager(20275):   },
I/TSLocationManager(20275):   "headers": {},
I/TSLocationManager(20275):   "extras": {},
I/TSLocationManager(20275):   "httpRootProperty": "location",
I/TSLocationManager(20275):   "locationTemplate": "",
I/TSLocationManager(20275):   "geofenceTemplate": "",
I/TSLocationManager(20275):   "persist": true,
I/TSLocationManager(20275):   "maxDaysToPersist": 1,
I/TSLocationManager(20275):   "maxRecordsToPersist": -1,
I/TSLocationManager(20275):   "locationsOrderDirection": "ASC",
I/TSLocationManager(20275):   "httpTimeout": 60000,
I/TSLocationManager(20275):   "geofenceProximityRadius": 1000,
I/TSLocationManager(20275):   "geofenceInitialTriggerEntry": true,
I/TSLocationManager(20275):   "stopOnTerminate": false,
I/TSLocationManager(20275):   "startOnBoot": true,
I/TSLocationManager(20275):   "heartbeatInterval": -1,
I/TSLocationManager(20275):   "foregroundService": false,
I/TSLocationManager(20275):   "notificationPriority": 0,
I/TSLocationManager(20275):   "notificationTitle": "",
I/TSLocationManager(20275):   "notificationText": "Location Service activated",
I/TSLocationManager(20275):   "notificationColor": "",
I/TSLocationManager(20275):   "notificationIcon": "",
I/TSLocationManager(20275):   "notificationSmallIcon": "",
I/TSLocationManager(20275):   "notificationLargeIcon": "",
I/TSLocationManager(20275):   "forceReloadOnLocationChange": false,
I/TSLocationManager(20275):   "forceReloadOnMotionChange": false,
I/TSLocationManager(20275):   "forceReloadOnGeofence": false,
I/TSLocationManager(20275):   "forceReloadOnBoot": false,
I/TSLocationManager(20275):   "forceReloadOnHeartbeat": false,
I/TSLocationManager(20275):   "forceReloadOnSchedule": false,
I/TSLocationManager(20275):   "stopAfterElapsedMinutes": 0,
I/TSLocationManager(20275):   "schedule": [],
I/TSLocationManager(20275):   "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",
I/TSLocationManager(20275):   "enableHeadless": true,
I/TSLocationManager(20275):   "configureUrl": "",
I/TSLocationManager(20275):   "configureInterval": -1,
I/TSLocationManager(20275):   "debug": true,
I/TSLocationManager(20275):   "logLevel": 5,
I/TSLocationManager(20275):   "logMaxDays": 3
I/TSLocationManager(20275): }╚═════════════════════════════════════════════
D/TSLocationManager(20275): [c.t.l.http.HttpService flush] 
D/TSLocationManager(20275): ╔═════════════════════════════════════════════
D/TSLocationManager(20275): ║ HTTP Service
D/TSLocationManager(20275): ╠═════════════════════════════════════════════

**Comment by christocracy** [comment]
Fine, that's your app booting.  `enableHeadless: true`.  Now terminate the app and show me the logs of that.

**Comment by atifaziz1** [comment]
after terminating nothing is showing in logs

**Comment by christocracy** [comment]
Then you are **not terminating**.  You are merely placing your app into *background*.  This is what terminating the app logs:
```
04-04 09:59:18.290  4566  4566 D TSLocationManager: [c.t.l.a.BackgroundGeolocation c]
04-04 09:59:18.290  4566  4566 D TSLocationManager:   🔴  Cleared callbacks
04-04 09:59:18.300  4566  5994 D TSLocationManager: [c.t.l.a.BackgroundGeolocation c]
04-04 09:59:18.300  4566  5994 D TSLocationManager:   🔴  Cleared callbacks
04-04 09:59:18.307  4566  4566 I TSLocationManager: [c.t.l.a.BackgroundGeolocation onActivityDestroy]
04-04 09:59:18.307  4566  4566 I TSLocationManager: ╔═════════════════════════════════════════════
04-04 09:59:18.307  4566  4566 I TSLocationManager: ║ MainActivity was destroyed
04-04 09:59:18.307  4566  4566 I TSLocationManager: ╠═════════════════════════════════════════════
04-04 09:59:18.307  4566  4566 I TSLocationManager: ╟─ stopOnTerminate: false
04-04 09:59:18.307  4566  4566 I TSLocationManager: ╟─ enabled: true
04-04 09:59:18.324  4566  4566 D TSLocationManager: [c.t.l.a.BackgroundGeolocation c]
04-04 09:59:18.324  4566  4566 D TSLocationManager:   🔴  Cleared callbacks
04-04 09:59:18.332  4566  4566 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
04-04 09:59:18.509  4566  4566 D TSLocationManager: [c.t.r.HeadlessTask <init>] 💀  event: terminate
```

**Comment by atifaziz1** [comment]
@christocracy I am terminating app by pressing home button on android and also killing app from stack.
But nothing shows like above you mentioned .

**Comment by christocracy** [comment]
show unfiltered `$ adb logcat` of termination.

**Comment by atifaziz1** [comment]
I/MotoNetwCtrlr( 1377): onReceive: Received intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
I/MotoNetwCtrlr.MotoWifiSignalCtrlr( 1377): handleBroadcast: Entered: Intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
I/MotoNetwCtrlr.MotorolaWifiSignalController( 1377): isDirty: returns false
I/MotoNetwCtrlr.MotoWifiSignalCtrlr( 1377): handleBroadcast: Completed
I/MotoNetwCtrlr( 1377): onReceive: Completed intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
W/ResourceType( 1377): No package identifier when getting value for resource number 0x00000000
E/FastThread(  277): did not receive expected priority boost
V/msm8974_platform(  277): platform_get_output_snd_device: enter: output devices(0x2)
V/msm8974_platform(  277): platform_get_output_snd_device: exit: snd_device(speaker)
D/audio_hw_primary(  277): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
D/hardware_info(  277): hw_info_append_hw_type : device_name = speaker
V/msm8974_platform(  277): platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)
W/PackageManager( 1377): Failure retrieving resources for com.workforcecity.employee: Resource ID #0x0
I/ActivityManager(  851): START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10009 on display 0
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
D/Sensors (  851): AccelerationSensor: set delay 200
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
I/LaunchCheckinHandler(  851): Displayed com.android.systemui/.recents.RecentsActivity,wp,wa,145
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
D/TaskStackView( 1377): onTaskViewDismissed: task = Task (1416): com.workforcecity.employee [com.android.systemui.recents.model.Task@2f60d1c2] index = 0 focused = false
D/ReactNative(25819): ReactInstanceManager.detachViewFromInstance()
I/ActivityManager(  851): Killing 25819:com.workforcecity.employee/u0a231 (adj 9): remove task
D/ConnectivityService(  851): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=1402, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@fb7bf70)
D/ConnectivityService(  851): releasing NetworkRequest NetworkRequest [ id=1402, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
I/WindowState(  851): WIN DEATH: Window{2bfa7910 u0 com.workforcecity.employee/com.workforcecity.employee.MainActivity}
E/ConnectivityService(  851): RemoteException caught trying to send a callback msg for NetworkRequest [ id=1402, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
I/SFPerfTracer(  260):      triggers: (rate: 0:105) (77146 sw vsyncs) (0 skipped) (139:2009068 vsyncs) (141:2203591)
I/ActivityManager(  851): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.android.launcher/com.android.launcher2.Launcher} from uid 10009 on display 0
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
D/TaskPersister(  851): removeObsoleteFile: deleting file=1416_task.xml
D/TaskPersister(  851): removeObsoleteFile: deleting file=1416_task_thumbnail.png
V/WindowManager(  851): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  851): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false

this one?

**Comment by atifaziz1** [comment]
It's may happen problem due to headless task is not registering ?

I am registering headless task like this where app is registering.

let HeadlessTask = async (event) => {
    let params = event.params;
    
    console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);
   
    
    switch (event.name) {
      case 'heartbeat':
        // Use await for async tasks
        let location = await getCurrentPosition();
    console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location.coords);
        break;
    }
  }

  let getCurrentPosition = () => {
    return new Promise((resolve) => {
      BackgroundGeolocation.getCurrentPosition((location) => {
        resolve(location);
      }, (error) => {
        resolve(error);
      }, {
        samples: 1,
        persist: false
      });
    });
  };

  BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

**Comment by christocracy** [comment]
You need to **enable** the plugin by calling `#start` for Headless to work.  From you logs above:

```
I/TSLocationManager(20275): ╔═════════════════════════════════════════════
I/TSLocationManager(20275): ║ BackgroundGeolocation Settings
I/TSLocationManager(20275): ╠═════════════════════════════════════════════
I/TSLocationManager(20275): {
I/TSLocationManager(20275): "enabled": false,
```

**Comment by christocracy** [comment]
`enabled` is not a documented configuration parameter.  It's a **read-only** state property.

You *enable* the plugin by executing `#start` method.

```javascript
BackgroundGeolocation.configure(config, (state) => {
  if (!state.enabled) {
    BackgroundGeolocation.start();
  }
});
```

**Comment by atifaziz1** [comment]
@christocracy thank you so much problem has been solved just one problem is location is coming frequently , I want location after 5 sec , for that I put locationUpdateInterval:5000, but its not working

**Comment by christocracy** [comment]
If you have unrelated issues to Headless task, post a new issue.

**Comment by atifaziz1** [comment]
@christocracy ok
