### ISSUE TITLE
[2.12.0-beta.3] Listeners don't catch anything on Android

### ISSUE THREAD

**Issue by kermopajula** [transistorsoft/react-native-background-geolocation#456]
## Your Environment
* Plugin version:2.12.0-beta.3
* Platform: Android
* OS version: All
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.51.0
* Plugin config: Default

## Expected Behavior
Location/error/provider listeners should catch events

## Actual Behavior
No events seem to be fired

## Steps to Reproduce

1. 
``` js
BackgroundGeolocation.on(
            'location',
            this.onLocation.bind(this),
            this.onError.bind(this)
        );
```
2. 
``` js
BackgroundGeolocation.ready({}, state => {
            if (!state.enabled) {
                BackgroundGeolocation.start();
            }
        });
```
3. Nothing is caught in the location/error/provider callback

## Context
Everything worked fine when using the previous version and I followed all the steps in the updated installation guide when upgrading to the new version (I'm upgrading because my app crashed on Android 8 when the user had turned the GPS off on the phone)

## Debug logs
adb logcat -s TSLocationManager used to have long and colorful output, but in this beta version all I get when I navigate to the view where the steps mentioned in Steps to Reproduce are executed is: "TSLocationManager: - Enable: true → true, trackingMode: 1"

**Comment by christocracy** [comment]
You're not providing any config to `#ready` so you *won't* see any logs (logLevel defaults to `OFF`).

```javascript
BackgroundGeolocation.ready({
  reset: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  debug: true
}, (state) => {
  console.log('- ready: ', state);
});
```

**Comment by kermopajula** [comment]
Thanks. I can see now the location is acquired and "[c.t.l.LocationService onLocation]" is printed out which seems like it's the one calling my onLocation handler? But still, no location, error or providerchange events are caught by my listeners.

I have them set up before calling .ready() and .start():
```js
        BackgroundGeolocation.on(
            'location',
            this.onLocation.bind(this),
            this.onError.bind(this)
        );
        BackgroundGeolocation.on(
            'providerchange',
            this.onProviderChange.bind(this)
        );
```

**Comment by kermopajula** [comment]
Found the problem, closing the issue: I did .removeListeners() before setting my listeners with .on() just in case to prevent having multiple listeners, but in this version it doesn't work like that anymore. Probably because of the use of promises?

**Comment by christocracy** [comment]
All the plugin's methods are *asynchronous*, they take time to execute. 

Imagine a timing-diagram:  what if `#removeListeners` takes just a *wee* bit longer to execute than the following `#on` executions?  What's going to happen to those listeners registered with `#on`?
```javascript
BackgroundGeolocation.removeListeners();
BackgroundGeolocation.on('location', onLocation);
BackgroundGeolocation.on('providerchange', onProviderChange);
```

```                                     ________
removeListeners():         _|            |_____
                                           ____
on('location', ...):            _ |     |_________
                                             ____
on('providerchange', ...)___|      |__________
```
