### ISSUE TITLE
Advice: Background location configuration for our use case

### ISSUE THREAD

**Issue by honzababarik** [transistorsoft/react-native-background-geolocation#461]
I was hoping we could ask to review our code and make sure we are doing everything right, because we are seeing issues in production use and we'd like to make sure its not caused by our way of using the library.

## Your Environment
* Plugin version: 2.11.0
* Platform: iOS+Android
* OS version: iOS11/Android 5
* Device manufacturer / model: Various models
* React Native version (`react-native -v`): 0.53.0
* Plugin config - will provide lower

## Expected Behavior
We turn on and off the user tracking using a silent push notification to the device. The prerequirements by the user is to have push notifications enabled and have location enabled as Always. Once the push is received, we process it and launch the Background tracking in three different modes:
- significant location change every 25 meters (we call this autotrack)
- device to send us a location every 30 minutes
- device to send us a location every 1 hour

## Actual Behavior
In perfect condition and stationary (good connection, reliable and easy to obtain GPS) everything seems to be working fine, but we are experiencing issues when the sending will just stop working and won't work for some time or will stop working completely. This we are experiencing on both IOS and Android. Once the application is in foreground we don't have a problem retrieving the location using manual call of the method. However in background the behavior is inconsistent.

Example: we had a user (ios11 device) walking around the city, first we enabled the autotrack and that didnt work at all (while previously, same device, different location, different network, it worked). Then we enabled sending us location every 30 seconds on heartbeat and that was working for several minutes till it all of a sudden stopped. Even after physically returning to those areas we didnt get the device to do anything any more. Resending the activation push made the device work, but just once, afterwards didnt work anymore, even after resending the push. Once we enabled auto tracking after that, it started working correctly on auto tracking, for some reason. Note that all these tests were done in the same location and with app on foreground there was no problem receiving the location.

I am aware the description is quite vague and lacks technical details here, but we dont have proper location tracking logging implemented in our prod app and we cannot offer more details for that reason.

## Context
We do food truck tracking as they move around, the users experiencing these issues are the vendors being on that truck. Though we did experience issues just walking or driving around, or being on a bus when we were doing the testing ourselves.

We were hoping you could review our code and let us know whether theres something wrong we are doing in our configuration:

```javascript
import BackgroundGeolocation from 'react-native-background-geolocation'
import { Platform, Alert, Linking } from 'react-native'
import { enums, startsWith } from '../../../helpers'
import { sendDeviceLocation } from '../../../api/fmAPI'
import Permissions from 'react-native-permissions'
import moment from 'moment'

export const configureLocations = (trackingType) => {
  const configuration = {
    // debug: true,
    // logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,
    preventSuspend: false,
    fastestLocationUpdateInterval: 2000,
    heartbeatInterval: getHeartbeatInterval(trackingType),
    desiredAccuracy: 0, // highest accuracy
    distanceFilter: 25, // in meters distance between calls
  }

  BackgroundGeolocation.configure(configuration, function(state) {
    if (!state.enabled) {
      BackgroundGeolocation.start();
    }
  });
}

export const getHeartbeatInterval = (trackingType) => {
  let heartbeat = 0
  if (trackingType === enums.VENDOR_LOCATION_TRACKING_TYPE_AUTOMATIC_30_MINS) {
    heartbeat = 1800 // 30 minutes
  }
  else if (trackingType === enums.VENDOR_LOCATION_TRACKING_TYPE_AUTOMATIC_HOUR) {
    heartbeat = 3600 // 1 hour
  }
  else if (startsWith(trackingType, 'CUSTOM-')) {
    heartbeat = parseInt(trackingType.split('-')[1])
  }
  return heartbeat
}

// this method gets called from the silent push notification received, tracking type is then provided in the push payload
export const startTrackingLocation = (trackingType) => {
  console.log(`[TRACKING]: Started ${trackingType}`)
  BackgroundGeolocation.removeListeners()
  configureLocations(trackingType)

  const heartbeatInterval = getHeartbeatInterval(trackingType)

  if (trackingType !== enums.VENDOR_LOCATION_TRACKING_TYPE_AUTOMATIC_REAL_TIME) {
    BackgroundGeolocation.setConfig({
      preventSuspend: true,
      heartbeatInterval: heartbeatInterval
    }, function(state) {
      BackgroundGeolocation.on('heartbeat', onHeartbeat)
    })
  }
  else {
    BackgroundGeolocation.setConfig({
      preventSuspend: false,
      heartbeatInterval: heartbeatInterval
    }, function(state) {
      BackgroundGeolocation.on('location', onLocationReceived, onLocationError);
    })
  }

  getCurrentLocation((location) => {
    submitLocation(location.latitude, location.longitude)
  }, (err) => {
    console.log('ERROR getting current location', err)
  }, false)
}

export const cancelTrackingLocation = () => {
  BackgroundGeolocation.removeListeners()
  BackgroundGeolocation.stop()
}

export const getCurrentPosition = (onLocation, onError) => {
  BackgroundGeolocation.getCurrentPosition((location) => {
    const locationData = getLocationData(location)
    onLocation(locationData)
  }, (err) => {
    console.log('ERR WITH GETTING LOCATION')
    if (onError) {
      onError(err)
    }
  })
}

export const getCurrentLocation = (onLocation, onError) => {
  getCurrentPosition(onLocation, onError)
}

export const submitLocation = (latitude, longitude) => {
  console.log(`[TRACKING]: Sending location to server: ${latitude}, ${longitude}`)
  return sendDeviceLocation(latitude, longitude)
    .then((response) => {
      console.log('[TRACKING]: Location sent')
    })
    .catch((error) => {
      if (error.status === enums.DEVICE_STOP_TRACKING_HTTP_STATUS_CODE) {
        console.log('[TRACKING]: Canceled by response')
        cancelTrackingLocation()
      }
      else {
        console.log('[TRACKING]: Location server error', error.status)
      }
    })
}

export const onHeartbeat = (params) => {
  getCurrentLocation(function(location) {
    submitLocation(location.latitude, location.longitude)
  })
}

export const getLocationData = (location) => {
  return {
    latitude: location.coords.latitude,
    longitude: location.coords.longitude
  }
}

export const onLocationReceived = (location) => {
  if (!location.sample) {
    const locationData = getLocationData(location)
    submitLocation(locationData.latitude, locationData.longitude)
  }
}

export const onLocationError = (err) => {
  console.log('Error getting location', err)
  Alert.alert('Error getting location', err)
}

```

**Comment by christocracy** [comment]
Are you observing the plugin logs (see [Debugging](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging wiki)?  You should have a look at the plugin's [logging](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#logger) methods.  These allow you to insert your own log messages into the plugin's log database.

You should insert your own log messages when you receive a push notification, for example.

**Comment by honzababarik** [comment]
@christocracy thank you, didnt know the logging is exposed to be used by own code. We will implement more logging to get more information.

Also I believe I had a wrong understanding of heartbeatInterval, missed the information about heartbeat fired only in stationary. Do I understand correctly that in case the device is moving, the heartbeat interval wont be fired until the device is not moving?

Would you have a suggestion if its possible using your library to fire the location update on period based basis? Say every 10 mins give me a location, no matter if the location hasnt changed. From my understanding scheduler wouldn't help in our use case.

**Comment by christocracy** [comment]
>Do I understand correctly that in case the device is moving, the heartbeat interval wont be fired until the device is not moving?

`heartbeat` event does *not* fire when device is in *moving* state -- only in *stationary* state.

>Would you have a suggestion if its possible using your library to fire the location update on period based basis? Say every 10 mins give me a location

That's what [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch) is for.  `background-fetch` is already included as a dependency.  Just see the docs and implement your own `callbackFn`.

**Comment by honzababarik** [comment]
Thank you @christocracy, we will stop using heartbeat for this then and move on to react-native-background-fetch. Closing the ticket.
