### ISSUE TITLE
Question: plugin + redux

### ISSUE THREAD

**Issue by oferRounds** [transistorsoft/react-native-background-geolocation#462]
Hi,

I’d like to use the plugin's own http layer to manage syncing with my server **only when the app is killed**. As otherwise, I’d like to JS layer to do it, so it will update the app’s Redux/Store, and make the change reflected in the UI.

Is such thing possible? Or would you have any other idea to handle the redux case?

**Comment by christocracy** [comment]
Why don't you just let the plugin manage HTTP always?  It'll be a lot less complex for you.

**Comment by christocracy** [comment]
The plugin's HTTP layer has automatic retry functionality on HTTP failure.  Why re-invent the wheel?  Just let the plugin manage it all.

**Comment by oferRounds** [comment]
Because currently everything is done using Redux’s Actions & Reducers. 

Do I get any callbacks? I need to reflect it on the UI

**Comment by christocracy** [comment]
Of course there are callbacks.  See the [http](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#zap-events-1) event.

**Comment by oferRounds** [comment]
Oh, got you, I missed that as I was looking only the HTTP section. Then cool, that will solve my problem, thanks! :)
