### ISSUE TITLE
Background geolocation not working when moving

### ISSUE THREAD

**Issue by STREETERAPP** [transistorsoft/react-native-background-geolocation#466]
## Your Environment
* Plugin version: 2.11.0
* Platform: Android
* OS version: 6.0.1 / 7.0
* Device manufacturer / model: Samung6 Edge / Google Nexus
* React Native version (`react-native -v`): 0.54.2

## Expected Behavior

We are expecting app should auto update the location info when we are moving, but its not happening. 

## Actual Behavior

we have tried with Wifi and mobile network too. It worked for one time with wifi on samsung6 edge but never worked on Google Nexus.

## Steps to Reproduce

Below is the code:

 BackgroundGeolocation.on('location', this.onLocation, this.onError);
 BackgroundGeolocation.on('motionchange', this.onMotionChange);
 BackgroundGeolocation.ready({
      desiredAccuracy: 0,
      distanceFilter: 1,
      stopTimeout: 1,
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
     stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
 onLocation(location) {
		if(location){
				var plat = location.coords.latitude;
				var plng = location.coords.longitude;
				 axios.get('https://maps.googleapis.com/maps/api/geocode/json?address='+plat+','+plng+'&key='+GMAP_KEY) 
					 .then(response => {
					 var coords = {};
					 coords['address'] = response.data.results[0].formatted_address;
					 coords['latitude'] =  plat;
					 coords['longitude'] = plng;
					  AsyncStorage.setItem('userposition', JSON.stringify(coords));
					  }).catch((error) => { // catch is called after then
						    var coords = {};
							coords['latitude'] =  plat;
							coords['longitude'] = plng;
							AsyncStorage.setItem('userposition', JSON.stringify(coords));
					});
	}
  }
 onMotionChange(location) {
	if(location){
				var plat = location.coords.latitude;
				var plng = location.coords.longitude;
				 axios.get('https://maps.googleapis.com/maps/api/geocode/json?address='+plat+','+plng+'&key='+GMAP_KEY) 
					 .then(response => {
					 var coords = {};
					 coords['address'] = response.data.results[0].formatted_address;
					 coords['latitude'] =  plat;
					 coords['longitude'] = plng;
					  AsyncStorage.setItem('userposition', JSON.stringify(coords));
					  }).catch((error) => { // catch is called after then
						    var coords = {};
							coords['latitude'] =  plat;
							coords['longitude'] = plng;
							AsyncStorage.setItem('userposition', JSON.stringify(coords));
					});
	}
  }
We are able to get the location updates on samsung when the app is in foreground but not in background. On Google Nexus it never worked when moving.

**Comment by christocracy** [comment]
The plugin is posting incredibly verbose logs to its database.  You need to view them.  The answer is in the logs.

See “Debugging” in Wiki.

**Comment by christocracy** [comment]
Update?

**Comment by christocracy** [comment]
Closed for lack of feedback.
