### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_YGNodeClone", referenced from:

### ISSUE THREAD

**Issue by MorcosS** [transistorsoft/react-native-background-geolocation#467]
## Your Environment
* Plugin version:"2.12.0-beta.3"
* Platform: iOS
* OS version: 11.3
* Device manufacturer / model: iphoneX
* React Native version (`0.55.2`):
* Plugin config

## Expected Behavior
the app to build normally
## Actual Behavior
getting errors regarding running the app

## Steps to Reproduce

1. npm install
2. pod install
3. build app from xcode

## Context
build and run ios app

## Debug logs
`ld: warning: object file (/Users/morcoss/Documents/Coding_World/React_Native/ProtoLabz/GoeksApp/goeks_app/ios/TSLocationManager.framework/TSLocationManager(TSResultSet.o)) was built for newer iOS version (8.4) than being linked (8.0)
Undefined symbols for architecture x86_64:
  "_YGNodeClone", referenced from:
      -[RCTShadowView sizeThatFitsMinimumSize:maximumSize:] in libReact.a(RCTShadowView.o)
  "_YGNodeListCount", referenced from:
      _YGNodeGetChildCount in libReact.a(Yoga.o)
      _YGNodelayoutImpl in libReact.a(Yoga.o)
      _YGRoundToPixelGrid in libReact.a(Yoga.o)
      _YGNodeToString in libReact.a(Yoga.o)
  "_YGNodeListDelete", referenced from:
      _YGNodeFree in libReact.a(Yoga.o)
      _YGNodeRemoveChild in libReact.a(Yoga.o)
  "_YGNodeListFree", referenced from:
      _YGNodeFree in libReact.a(Yoga.o)
      _YGNodeReset in libReact.a(Yoga.o)
  "_YGNodeListGet", referenced from:
      _YGNodeGetChild in libReact.a(Yoga.o)
      _YGNodelayoutImpl in libReact.a(Yoga.o)
      _YGZeroOutLayoutRecursivly in libReact.a(Yoga.o)
  "_YGNodeListInsert", referenced from:
      _YGNodeInsertChild in libReact.a(Yoga.o)
  "_YGNodeSetDirtiedFunc", referenced from:
      -[RCTVirtualTextShadowView insertReactSubview:atIndex:] in libRCTText.a(RCTVirtualTextShadowView.o)
      -[RCTVirtualTextShadowView removeReactSubview:] in libRCTText.a(RCTVirtualTextShadowView.o)
  "_YGValueUndefined", referenced from:
      +[RCTConvert YGValue:] in libReact.a(RCTConvert.o)
      -[RCTShadowView init] in libReact.a(RCTShadowView.o)
  "facebook::react::getInspectorInstance()", referenced from:
      getInstance() in libReact.a(RCTInspector.o)
      facebook::react::JSCExecutor::initOnJSVMThread() in libReact.a(JSCExecutor.o)
      facebook::react::JSCExecutor::terminateOnJSVMThread() in libReact.a(JSCExecutor.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
 `
pod file is the same as explained in the installation:
`
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'react-native-maps', path: '../node_modules/react-native-maps/'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'
  pod 'CocoaLumberjack'
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils'

end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end`

also here is the package.json
`{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.3.9",
    "path": "^0.12.7",
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-native-background-fetch": "^2.4.1",
    "react-native-background-geolocation": "^2.12.0-beta.3",
    "react-native-config": "^0.11.5",
    "react-native-device-info": "^0.15.3",
    "react-native-elements": "^0.19.0",
    "react-native-google-places-autocomplete": "^1.3.6",
    "react-native-maps": "^0.21.0",
    "react-native-maps-directions": "^1.4.1",
    "react-native-permissions": "^1.1.1",
    "react-native-simple-radio-button": "^2.7.1",
    "react-native-textinput-effects": "^0.4.2",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.11",
    "react-navigation-redux-helpers": "^1.0.5",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
thanks in advance

**Comment by MorcosS** [comment]
I was having an installation problem.

**Comment by ilkerdogan** [comment]
I am having the same error. I dont understant what do you mean with you had an installation problem. Please let me know what did you forget to install.

**Comment by samermurad** [comment]
@ilkerdogan Try This: 
1. In Xcode, click to edit the scheme you are try to run
2. in the window that opens up, click on Build>Build, you should see the target that is connected to the scheme
3. make sure that the react static lib is visible and all it's options ticked and above you target, if not add it
4. disable "Paralaize build"
5. clean your project and try again
