### ISSUE TITLE
Example Notification Customisation

### ISSUE THREAD

**Issue by AleskiWeb** [transistorsoft/react-native-background-geolocation#468]
Hey there,

This isn't really an issue per se, but I couldn't find anywhere else to ask such a thing so here goes. I was trying to customise the notification in the tray that is persistent if `foregroundService: true` or if on android 8 or above and I had middling success.

I was able to update the title and text from the default but color and icon are still default. I was wondering if you could extend on what you wrote in the documentation? For example, `notificationColor` says it expects a string, but if I pass in `#c6e6f4` it still remains default.

Could you provide an example notification customisation for the documentation that modifies the icon and color? For example, with the icon, do I specify a `{type}` and then `/imageVar` where `imageVar = require('my-icon')`, meaning the whole line would be `notificationSmall: 'drawable/' + imageVar`?

## Expected Behavior
Icon is updated along with a color

## Actual Behavior
Nothing happened

## Context
Trying to modify the defaults for notifications

I omitted the debug information as this isn't really a bug or issue, more of a request.

Thanks,
Aleski

**Comment by christocracy** [comment]
In my SampleApp, I see I have an image in `res/drawable` (placed there by `react-native-navigation`.  I will configure `BackgroundGeolocation` to use this icon.
![](https://dl.dropboxusercontent.com/s/428ag1t27081u4s/Screenshot%202018-04-18%2009.51.07.png?dl=1)
```
{
  notificationColor: '#ff0000`,
  notificationSmallIcon: 'drawable/node_modules_reactnavigation_src_views_assets_backicon',
  notificationLargeIcon: 'drawable/node_modules_reactnavigation_src_views_assets_backicon',
}
```
**Note:**  The config params for icons are [`notificationSmallIcon`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-string-notificationsmallicon-app-icon) and [`notificationLargeIcon`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-string-notificationlargeicon-undefined) -- **not** `notificationSmall`.

**Comment by christocracy** [comment]
Result:

![](https://dl.dropboxusercontent.com/s/rc2wmvw3kecqfdh/Screenshot%202018-04-18%2009.55.48.png?dl=1)
![](https://dl.dropbox.com/s/m3j1fv00xko9yw6/Screenshot%202018-04-18%2009.56.33.png?dl=1)

**Comment by AleskiWeb** [comment]
I have the following file in my application, similar to your example you generously provided (thanks, for some reason I didnt seem to get a notification email that you had)

![image](https://user-images.githubusercontent.com/8318899/39315982-f3be9baa-496f-11e8-88ce-80c6d1981a34.png)

I am able to set the large icon `notificationLargeIcon: 'mipmap/ic_launcher'` however when I use `notifictionSmallIcon: 'drawable/ic_stat_home'` the small icon provided in the taskbar/notification bar is a small square (seems to default to using my app Icon)

I had thought that perhaps this was because the icon was invalid (as it needs to be transparent with a single alpha/white image for example) but I use the same icon in FCM and it populates correctly.

However I did also get the color accent working by passing a hex value into `notificationColor`.

Anyway I could debug this, see if there is an `invalid image used, falling back` being thrown somewhere?
