### ISSUE TITLE
iOS build fails on beta 3

### ISSUE THREAD

**Issue by ntomallen** [transistorsoft/react-native-background-geolocation#469]
## Your Environment
* Plugin version: 2.12.0-beta.
* Platform: iOS
* OS version: 11.3
* Device manufacturer / model: Emulator
* React Native version: 0.53.3
* Plugin config: (Doesn't get to this point)

## Expected Behavior
iOS build should succeed.

## Actual Behavior
iOS build fails.

## Steps to Reproduce

1. Upgrade to beta 3, after having been on v 2.11.0
2. `react-native link react-native-background-geolocation`
3. Run `Product/Clean` and `Product/Clean build folder` from Xcode
4. Attempt to run app via Xcode or via the command line.

## Context
Upgrade to the new `ready` API and use promises instead of callbacks for various commands.

## Debug logs
```
▸ Compiling RNBackgroundGeolocation.m

❌  /Users/ntomallen/Source/zonder-mobile-app/ios/Pods/Headers/Public/RNBackgroundGeolocation/TSLocationManager/TSLocationManager.h:15:9: 'TSConnectivityChangeEvent.h' file not found

#import "TSConnectivityChangeEvent.h"
                       ^

▸ Compiling RNBackgroundGeolocation-dummy.m
** BUILD FAILED **
```

The plugin has been working very well so far for me, and since I was going to be updating a few geolocation-related things today, I decided to update the module to the latest version and take advantage of the new features. I used yarn to upgrade, and then linked to iOS. The build failed at first, so I tried cleaning everything in Xcode, but to no avail. Has anyone had this issue on the new version before? I have it set up to import geolocation with pods, so I'm not sure if the linking would have affected anything. I do believe I tried linking after it failed the first time.

**Comment by christocracy** [comment]
You don’t have the latest TSLocationManager.framework linked.

It’s still using the previous version.  connectivitychange is a new event.

pod install again?

**Comment by ntomallen** [comment]
Good call! Should have guessed. Working now!
