### ISSUE TITLE
on iOS does stationaryRadius do anything when it's less than 500?

### ISSUE THREAD

**Issue by JAStanton** [transistorsoft/react-native-background-geolocation#47]
You mention in your docs
>  it can take as much as 3 city-blocks to 1/2 km before staionary-region exit is detected.

so does anything less than 500m actually do anything? does a value of `0` do anything special?

**Comment by christocracy** [comment]
0 does nothing.  You're at the mercy of Apple and the nature of the cell
network in your environment.

On Thursday, December 17, 2015, Jonathan Stanton <notifications@github.com>
wrote:

> You mention in your docs
>
> it can take as much as 3 city-blocks to 1/2 km before staionary-region
> exit is detected.
>
> so does anything less than 500m actually do anything? does a value of 0
> do anything special?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/47>
> .
>


-- 
Snet form Gmail Mobile
