### ISSUE TITLE
Is there anyway of creating geofenced polygons? 

### ISSUE THREAD

**Issue by michaeljholmes** [transistorsoft/react-native-background-geolocation#471]

**Comment by christocracy** [comment]
The native geofence API for Android and iOS do not support polygon geofences -- only Circular.

**Comment by christocracy** [comment]
I suggest you create a large circular geofence to encompass your desired polygon.  When the device enters this circular geofence, you would engage aggressive tracking (if you aren't already).

Map sdks usually have some method of creating polygons.  You would then "hit-test" each recorded location against the Map polygon.

Are you using geofences-only mode (ie: `#startGeofences`) or location+geofence tracking (ie: `#start`)?

**Comment by christocracy** [comment]
Five years later, the plug-in now supports polygon geofencing.  See api docs `Geofence.vertices`
