### ISSUE TITLE
"Configuration with name 'default' not found" error message while adding dependencies and compiling.

### ISSUE THREAD

**Issue by gaurabguha** [transistorsoft/react-native-background-geolocation#475]
## Your Environment
* Plugin version: 2.3.3
* Platform: Android
* OS version: 7
* Device manufacturer / model: One Plus 3T
* React Native version (`react-native -v`): 0.3.4
* Plugin config

## Expected Behavior
After adding the dependencies ':react-native-background-geolocation' and ':react-native-background-fetch', it should allow the code to be compiled without throwing an error.

## Actual Behavior
After adding the dependencies using the code: 
compile project(':react-native-background-geolocation')
compile project(':react-native-background-fetch')
it is throwing up an error message "Error:Configuration with name 'default' not found."

## Steps to Reproduce

1. Add the below lines in build.gradle file
2. dependencies {
+   compile project(':react-native-background-geolocation')
+   compile project(':react-native-background-fetch')
+   compile "com.android.support:appcompat-v7:$rootProject.supportLibVersion"
}
3. Build the Project
4. Get an error message "Error:Configuration with name 'default' not found."

## Context
We are trying to get a demo app up and running in the debug mode using the instructions provided on the site for evaluating the React Native plugin.

## Debug logs
None

**Comment by christocracy** [comment]
- Open project in Android Studio
- Build -> Clean Project
- Observe errors / warnings in Android Studio.

**Comment by christocracy** [comment]
Have you tried building the [Sample App](https://github.com/transistorsoft/rn-background-geolocation-demo)

**Comment by gaurabguha** [comment]
Hi Chris,

We tried the Clean Project option but still getting the same issue. 

Also, downloaded the Sample App and tried compiling the same but getting the error message - "Could not read script 'E:\VAISHALI\New\rn-background-geolocation-demo-master\node_modules\react-native\react.gradle' as it does not exist". This error is coming because of the line: 

apply from: "../../node_modules/react-native/react.gradle"

in the file: rn-background-geolocation-demo/android/app/build.gradle

Please help.

**Comment by christocracy** [comment]
You say:
>React Native version (react-native -v): 0.3.4

There's no way that's correct.  Here's mine:
```
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.54.2
```

**Comment by gaurabguha** [comment]
My mistake. Since I am a newbie on React Native, didn't look at the right place. My version is given below:

$ react-native -v
react-native-cli: 2.0.1
react-native: 0.54.4

**Comment by christocracy** [comment]
Did you run `$ npm install` when you downloaded the sample app?

**Comment by gaurabguha** [comment]
Getting the following message.

npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-native-background-geolocation@2.12.0-beta.4 requires a peer of react-native@>=0.36.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-background-fetch@2.4.1 requires a peer of react-native@>=0.28.0 but none is installed. You must install peer dependencies yourself.

**Comment by christocracy** [comment]
Ignore `WARN` and carry on.

**Comment by gaurabguha** [comment]
Still getting the "Error:Configuration with name 'default' not found" error message while trying to Build / Clean Project.

**Comment by christocracy** [comment]
```
$ rm -rf node_modules
$ npm install
```

**Comment by gaurabguha** [comment]
My settings.gradle file:

include ':app', ':react.gradle'
include ':react-native-device-information'
project(':react-native-device-information').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-information/android')

include ':react-native-background-geolocation'
project(':react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-geolocation/android')

include ':react-native-background-fetch'
project(':react-native-background-fetch').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-fetch/android/')

include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')

include ':react-native-app-settings'
project(':react-native-app-settings').projectDir = new File(rootProject.projectDir,'../node_modules/react-native-app-settings/android')
project(':react.gradle').projectDir = new File('node_modules/react-native/react.gradle')

My root build.gradle file:

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        mavenLocal()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/node_modules/react-native/android"
        }
        // Google now hosts their latest API dependencies on their own maven  server.
        // React Native will eventually add this to their app template.
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url "$rootDir/node_modules/react-native-background-geolocation/android"
        }
        maven {
            url "$rootDir/node_modules/react-native-background-fetch/android"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
ext {
    compileSdkVersion = 26
    targetSdkVersion = 26
    buildToolsVersion = "26.0.2"
    supportLibVersion = "26.1.0"
    googlePlayServicesVersion = "11.8.0"
}
allprojects {
    repositories {
        jcenter()
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
dependencies {
    implementation project(':react-native-background-fetch')
    implementation project(':react-native-background-geolocation')
    implementation project(':react-native-device-information')
    implementation project(':react-native-maps')
    implementation project(':react-native-app-settings')
    implementation project(':react.gradle')
}

My app build.gradle file:

apply plugin: 'com.android.application'

def DEFAULT_COMPILE_SDK_VERSION     = 26
def DEFAULT_BUILD_TOOLS_VERSION     = "26.0.2"
def DEFAULT_TARGET_SDK_VERSION      = 26
def DEFAULT_PLAY_SERVICES_VERSION   = "11.8.0"
project.ext.react = [
        entryFile: "index.js"
]

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        targetSdkVersion rootProject.targetSdkVersion

        applicationId "net.mzi.reactnativedummy"
        minSdkVersion 15
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven {
        url "$rootDir/node_modules/react-native-background-fetch/android"
    }
    maven {
        url "$rootDir/node_modules/react-native-background-geolocation/android"
    }
}

dependencies {
    def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : "+"

    compile 'com.facebook.react:react-native:+'

    compile "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"

    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile "com.android.support:appcompat-v7:$rootProject.supportLibVersion"
    testCompile 'junit:junit:4.12'

    implementation project(':react-native-background-geolocation')
    implementation project(':react-native-background-fetch')
    implementation project(':react-native-maps')
    compile "com.android.support:appcompat-v7:$rootProject.supportLibVersion"
}
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

My gradle version is 4.4.
 I am getting the Could not find method implementation() for arguments [project ':react-native-background-fetch'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. error message.

Also, when I executed the following command: react-native link react-native-background-geolocation
I got the response:

Scanning folders for symlinks in D:\Mobile Apps\ReactNativeDummy\node_modules (119ms)
rnpm-install ERR! Something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/facebook/react-native/issues

spawn UNKNOWN

I am a newbie to react native. Could you please guide me what all I need to do other than following your instructions as given in your readme file while trying to make your plugin work for me? I am very much interested in using your plugins and wish to implement them in all my apps. Any help from your side would be much appreciated.

**Comment by christocracy** [comment]
If you're new to react native, start by implementing the plugin in isolation of `react-native-maps`.

```
$ react-native init Foo
```

Add BackgroundGeolocation to a simple RN app *without* maps.  Get it to work *there* first.

**Comment by gaurabguha** [comment]
We have made some headway in our code. Now we are stuck up in the MainApplication.java class. We are trying to inherit the ReactApplication class. But in Android Studio, it is showing it as an interface. Please see my MainApplication.java code screenshot attached. Do suggest a way forward.

![issue](https://user-images.githubusercontent.com/38688268/39471990-f6c5ee5a-4d63-11e8-859e-9215b33269c9.png)
.

**Comment by christocracy** [comment]
I have no idea.

**Comment by gaurabguha** [comment]
But in your documentation (refer link https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID.md), you have used ReactApplication as a class.

Screenshot:
![untitled-1](https://user-images.githubusercontent.com/38688268/39472344-5dcc87e2-4d66-11e8-9a24-8c2309cb4d53.gif)

In your demo app though, you have used the following workaround (refer link https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/app/src/main/java/com/transistorsoft/backgroundgeolocation/react/MainApplication.java): 
public class MainApplication extends Application implements ReactApplication {

But when we tried to implement the same, we got the following exception: 
Java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication

Please guide us as to how we may proceed.

**Comment by christocracy** [comment]
Yes, and it's based upon an *old* version of RN.  You are no instructed to change any line except those which are green.
```diff
### :open_file_folder: `android/app/main/java/com/.../MainApplication.java`

```diff
+import com.transistorsoft.rnbackgroundgeolocation.*;
+import com.transistorsoft.rnbackgroundfetch.RNBackgroundFetchPackage;
public class MainApplication extends ReactApplication {
  @Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
+     new RNBackgroundGeolocation(),
+     new RNBackgroundFetchPackage(),
      new MainReactPackage()
    );
  }
}
```

**Comment by gaurabguha** [comment]
Please see screenshot below of our MainApplication.java class. It is as per the documentation provided. Do suggest any changes in this code if required. But as it is, this code is giving an error with the extends keyword and asking us to use the implements keyword instead. The same is visible in the screenshot.

Also, if your code is compatible with an older version of React Native only and not the latest one, then do let us know so that we will install that version to make the code work.

![issue2](https://user-images.githubusercontent.com/38688268/39472846-6b534d12-4d69-11e8-84c6-d67a09b93ae3.png)

Also, as already mentioned, even if we are using the implements keyword, we are getting the error message: Java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication.

**Comment by christocracy** [comment]
**Forget about my code**.

Just generate a hello world RN app and get it to boot!

```
$ react-native init Foo
```

Do not even *think* of using my plugin until you become more familiar with the React Native development ecosystem.

I’m not here to tutor on RN development — I’m here to assist with issues specific to the plugin.

**Comment by gaurabguha** [comment]
There is a misunderstanding. We are not talking about any RN issue. We have got hold of an expert who is assisting us with the code. We have finished the plugin implementation. The issue right now is associated with the code itself. We have shared the screenshot with you. The object ReactApplication is to be used as a class but is actually an interface. This is part of your package. That is why we are asking your help.

**Comment by christocracy** [comment]
It is **NOT** part of my package.

The diff show lines you are to *ADD* to file `ReactApplication.java`.

`ReactApplication` is owned by *YOUR* application.

You are **NOT** instructed to copy / paste the entire contents.

**Comment by gaurabguha** [comment]
We have finally been able to resolve our issue. We needed to add the following lines to the AndroidManifest.xml file.

<application
      android:name=".MainApplication">

**Comment by gaurabguha** [comment]
<application
   android:name=".MainApplication"

**Comment by christocracy** [comment]
That has nothing at all to do with the plugin
