### ISSUE TITLE
Random android crashes with latest version

### ISSUE THREAD

**Issue by mckn** [transistorsoft/react-native-background-geolocation#476]
## Your Environment
* Plugin version: 2.12.0-beta4
* Platform: Android
* OS version: Android 8.0 API 26
* Device manufacturer / model: Nexus 5X
* React Native version (`react-native -v`): 0.55.3
* Plugin config
```
{
    desiredAccuracy: 100, 
    distanceFilter: 500,
    locationUpdateInterval: 1000,
    fastestLocationUpdateInterval: 60000,
    enabled: true,
    heartbeatInterval: 150,
    foregroundService: true,
    notificationTitle: "text",
    notificationText: "text",
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    notificationSmallIcon: "drawable/ic_stat_ac_unit",
    stopOnTerminate: false,
    locationAuthorizationRequest: "Always",
    disableLocationAuthorizationAlert: true
  }
```

## Expected Behavior
The app should not crash

## Actual Behavior
The app crash with the error below.

## Steps to Reproduce
I have not find any specific way to get it to crash. Sometimes it is during startup and other when switching between forground/background.

## Context
Using the app as normal

## Debug logs
```
04-27 09:54:27.756 10355-10355/co.test.com E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.test.com, PID: 10355
    java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.BackgroundGeolocationService@e8f81b9 with Intent { cmp=co.test.com/com.transistorsoft.locationmanager.BackgroundGeolocationService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
        at android.app.PendingIntent.getActivity(PendingIntent.java:340)
        at android.app.PendingIntent.getActivity(PendingIntent.java:303)
        at com.transistorsoft.locationmanager.BackgroundGeolocationService.f(Unknown Source:27)
        at com.transistorsoft.locationmanager.BackgroundGeolocationService.d(Unknown Source:26)
        at com.transistorsoft.locationmanager.BackgroundGeolocationService.onStartCommand(Unknown Source:113)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by christocracy** [comment]
Show me the following files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by mckn** [comment]
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.1'
        classpath 'com.google.gms:google-services:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
           url 'https://maven.google.com'
           name 'Google'
        }
        maven { url "https://jitpack.io" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}

ext {
    googlePlayServicesVersion = "12.0.1"
    androidSupportVersion = "27.1.1"
    supportLibVersion = "27.1.1"
    compileSdkVersion = 27
    buildToolsVersion = "27.0.3"
    targetSdkVersion = 27
    androidMapsUtilsVersion = "0.5+"
}`




`apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    dexOptions {
        javaMaxHeapSize "4g"
    }

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 206
        versionName "1.1.45"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    signingConfigs {
        release {
           // removed
        }
        beta {
           // removed
        }
    }

    flavorDimensions "default"

    productFlavors {
        prod {
            // removed
            dimension "default"
        }
        beta {
            // removed
            dimension "default"
        }
    }
    aaptOptions {
        additionalParameters "--no-version-vectors"
    }
   
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        debug {
            manifestPlaceholders = [excludeSystemAlertWindowPermission: "false"]
        }

        release {
            manifestPlaceholders = [excludeSystemAlertWindowPermission: "true"]
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}
repositories {
    flatDir {
        dirs "../../node_modules/react-native-background-geolocation/android/libs"
    }
}

def playServiceVersion = rootProject.googlePlayServicesVersion
def androidSupportVersion = rootProject.androidSupportVersion

dependencies {
    implementation (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
        exclude group: "com.android.support"
    }
    implementation project(':react-native-picker')
    implementation(project(':react-native-firebase')) {
        transitive = false
        exclude group: "com.google.android.gms", module: "play-services-base"
        exclude group: "com.google.firebase"
    }
    implementation(project(':react-native-background-geolocation')) {
      exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    implementation project(':react-native-background-fetch')
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation(project(':react-native-device-info')) {
        exclude group: 'com.google.android.gms', module: 'play-services-gcm'
    }
    implementation project(':bugsnag-react-native')
    implementation(project(':react-native-fbsdk')) {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
    implementation(project(':react-native-image-crop-picker')) {
        exclude group: "com.android.support", module: 'support-annotations'
    }
    implementation project(':react-native-linear-gradient')
    implementation(project(':react-native-navigation')) {
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'design'
    }
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-appsflyer')
    implementation project(':lottie-react-native')

    implementation "com.google.firebase:firebase-analytics:$playServiceVersion"
    implementation "com.google.firebase:firebase-core:$playServiceVersion"
    implementation "com.google.firebase:firebase-config:$playServiceVersion"
    implementation "com.google.firebase:firebase-auth:$playServiceVersion"
    implementation "com.google.firebase:firebase-database:$playServiceVersion"
    implementation "com.google.firebase:firebase-storage:$playServiceVersion"
    implementation "com.google.firebase:firebase-messaging:$playServiceVersion"
    implementation "com.google.firebase:firebase-crash:$playServiceVersion"
    implementation "com.google.firebase:firebase-perf:$playServiceVersion"
    implementation "com.google.firebase:firebase-ads:$playServiceVersion"
    implementation "com.google.firebase:firebase-firestore:$playServiceVersion"
    implementation "com.google.firebase:firebase-invites:$playServiceVersion"

    implementation "com.google.android.gms:play-services-vision:$playServiceVersion"
    implementation "com.google.android.gms:play-services-location:$playServiceVersion"
    implementation "com.google.android.gms:play-services-analytics:$playServiceVersion"
    implementation "com.google.android.gms:play-services-gcm:$playServiceVersion"
    implementation "com.google.android.gms:play-services-maps:$playServiceVersion"
    implementation "com.google.android.gms:play-services-base:$playServiceVersion"

    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    
    api 'com.android.support:multidex:1.0.3'
    api "com.android.support:appcompat-v7:$androidSupportVersion"
    api "com.android.support:support-annotations:$androidSupportVersion"
    api "com.android.support:design:$androidSupportVersion"
    api "com.android.support:exifinterface:$androidSupportVersion"
    api 'com.facebook.soloader:soloader:0.1.0+'

    api fileTree(dir: "libs", include: ["*.jar"])
    api "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
`

**Comment by mckn** [comment]
Okay, so we need to run the latest version of play-services:location to use the latest version of the background-geolocation library? @christocracy

**Comment by christocracy** [comment]
BackgroundGeolocation requires `play-services >= 11.2.0`.  Latest version is always recommended.

**Comment by christocracy** [comment]
Update?

**Comment by mckn** [comment]
We waited with the update but will soon do a new try. Will get back to you then. Thanks!

**Comment by christocracy** [comment]
Closed for lack of feedback.
