### ISSUE TITLE
'geofence' event listeners are not being removed (`2.12.0-beta.4`)

### ISSUE THREAD

**Issue by DusanDimitric** [transistorsoft/react-native-background-geolocation#479]
## Your Environment

* Plugin version: ***2.12.0-beta.4***
* Platform: ***iOS***
* OS version: ***11.3***
* Device manufacturer / model: ***iPhone 7 (simulator)***
* React Native version (react-native -v): ***0.55.3***
* Plugin config: ***`react-native link`***

## Expected Behavior

`'geofence'` `event listeners` should be able to be removed programmatically using the `un()` or `removeListeners()` methods.

## Actual Behavior

I'm not able to remove `geofence` event listeners in the application I'm building with `react-native-background-geolocation`.

Both `removeListeners()`, and `un()` don't seem to work for removing `'geofence'` event listeners.

Here's an example:

```javascript
1   BackgroundGeolocation.removeListeners()
2     .then(() => {
3       console.dir('Successfully removed all event listeners!')
4     })
5     .catch(console.erorr)
6
7   BackgroundGeolocation.un('geofence', handleGeofenceEvent, () => {
8     console.log('Succesfully removed geofence listener!')
9     BackgroundGeolocation.on('geofence', handleGeofenceEvent)
10  }, e => {
11    console.log('Failed to remove geofence listener:', e)
12  })
```

Lines ***3*** and ***8*** never get executed. The error branches are not executed either.
I've tried both `Promise` and `callback` interfaces on both methods.

```javascript
1  BackgroundGeolocation.removeGeofences()
2    .then(() => {
3      console.dir('Successfully removed all geofences!')
4    })
5    .catch(console.erorr)
```

Removing Geofences works perfectly fine though. In the example above, line ***3*** gets executed, as expected.

## The Problem

What happens here is having same `event listener` registered multiple times.

If you `stop()` and `start()` the plugin 3 times, you will have 3 same event listeners attached. Which is certainly not ideal.

This might be due to the fact that I'm trying to go with ***2.12.0-beta.4***.

Thanks for your support!

**Comment by DusanDimitric** [comment]
In the meanwhile I will try using ***2.11.0*** and testing the `'geofence'` event listener removal.

**Comment by christocracy** [comment]
Show me where you're creating your `handleGeofenceEvent`.

I cannot reproduce this issue.

**Note** [`#un`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#unevent-callbackfn) does not accept `success` / `failure` functions.

**No**
```javascript
BackgroundGeolocation.un('geofence', handleGeofenceEvent, success, failure);
```
**Yes**
```javascript
BackgroundGeolocation.un('geofence', handleGeofenceEvent);
```

**Comment by DusanDimitric** [comment]
Here's how the listener is created:

```javascript
  BackgroundGeolocation.on('geofence', handleGeofenceEvent)

  function handleGeofenceEvent (geofence) {
    var { location, identifier, action } = geofence

    console.log('A geofence has been crossed: ', identifier)
    console.log('ENTER or EXIT?: ', action)
    console.log('geofence: ', JSON.stringify(geofence))
  }
```

It's from the documentation.

**Comment by christocracy** [comment]
Are you *really* defining `handleGeofenceEvent` *after* you listen to it with `#on`?

The `function` should be defined *before* you reference it:
```javascript
function handleGeofenceEvent (geofence) {
    var { location, identifier, action } = geofence

    console.log('A geofence has been crossed: ', identifier)
    console.log('ENTER or EXIT?: ', action)
    console.log('geofence: ', JSON.stringify(geofence))
  }
BackgroundGeolocation.on('geofence', handleGeofenceEvent);
```

And are you removing the listener with `#un` in the same function that created `handleGeofenceEvent` (since you function is a local variable)?

**Comment by DusanDimitric** [comment]
This shouldn't really matter in javascript afaik. Let me check.

**Comment by DusanDimitric** [comment]
So the problem was that the event handler function was being declared in the local function scope, my bad. I moved it so that it is declared globally in the module and that the function reference is being preserved. Now the `.un()` method works. This is enough for me to work with the plugin so I'll close the issue.

Still, the ***`removeListeners()`*** doesn't remove the `'geofence'` listeners. In the code below - none of the callbacks/promise branches are being executed, nor are the actual listeners being removed. I'm not sure why is that the case.

```javascript
  BackgroundGeolocation.removeListeners()
    .then(() => {
      console.log('removed all listeners')
    })
    .catch(e => {
      console.log('Failed to remove all listeners!')
      console.log(e)
    })
  BackgroundGeolocation.removeListeners(() => {
    console.log('Removed all listeners!')
  },
  e => {
    console.log('Failed to remove all listeners!')
    console.log(e)
  })
```

**Comment by christocracy** [comment]
The plugin methods are *asynchronous*.  Perhaps your `on('geofence', callback)` is being executed *after* `#removeListeners` executes.

Think of the plugin like an HTTP server: executing methods upon it are like asynchronous HTTP requests.
