### ISSUE TITLE
Can this be installed with CocoaPods?

### ISSUE THREAD

**Issue by klatchbaldar** [transistorsoft/react-native-background-geolocation#48]

**Comment by christocracy** [comment]
Probably.  It's on my list

**Comment by nevir** [comment]
As of https://github.com/transistorsoft/react-native-background-geolocation/pull/64 it can, if you're not using `use_frameworks!`; and once https://github.com/transistorsoft/react-native-background-geolocation/pull/76 is merged, you can install it when `use_frameworks!` is enabled, too

**Comment by christocracy** [comment]
I'll try and have a look at this tomorrow

On Monday, April 25, 2016, Ian MacLeod <notifications@github.com> wrote:

> As of #64
> <https://github.com/transistorsoft/react-native-background-geolocation/pull/64>
> it can, if you're not using use_frameworks!; and once #76
> <https://github.com/transistorsoft/react-native-background-geolocation/pull/76>
> is merged, you can install it when use_frameworks! is enabled, too
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/48#issuecomment-214590387>
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Cocoa pod and RNPM installation is now available.  see README.
