### ISSUE TITLE
HTTP fires SuccessFn even when status code is 0, 401, etc

### ISSUE THREAD

**Issue by AleskiWeb** [transistorsoft/react-native-background-geolocation#481]
## Your Environment
* Plugin version: 2.12.0-beta.4
* Platform: Android
* OS version: Oreo 8.1
* Device manufacturer / model: Pixel 2
* React Native version (`react-native -v`): 0.52

## Expected Behavior
That if the server responds with 401, it should fire the `ErrorCallbackFn` and not `SuccessCallbackFn`

## Actual Behavior
Success is called, and `console.log(response)` shows error message + `status: 401`

## Steps to Reproduce

1. Toggle geolocation on
2. Wait for the activity change location to trigger
3. See data post, and wait for `.on('http'...` to trigger
4. See that the success function was called

## Context
I want to catch when there is an error with posting. I could just check the response myself in the success function but thought it should call other function

The below code never triggers the `console.log` with `bad` in it, despite the logcat saying `...HttpService$a onFailure`
`BackgroundGeolocation.on('http', function(response) { console.log('good', response) }, function(error) { console.log('bad', error) })`

## Debug logs
Logcat: `05-10 12:36:37.675 12352-13836/com.application-name W/TSLocationManager: [c.t.l.http.HttpService$a onFailure]`

**Also** is there a way to harness the post request, the actual body of the request. I want to debug it sometimes but it involves checking server request logs instead of seeing it in the local application.

Thanks in advance,

**Comment by christocracy** [comment]
It's a documentation error.  There's no `failureFn` for `http` event.  Just a single `callbackFn`.

```javascript
BackgroundGeolocation.on('http', (response) {
  if (response.status == 200) {
    console.log('[http] success - ', response);
  } else {
    console.log('[http] failure - ', response);
  }
});
```

I think I'll add another key to the http event `success` to signal HTTP success / failure, since there are a number of http status codes which can signal "success" (eg: `201`, `204`).  The plugin's native http event already has this `success` property, it's just not transmitting it to the Javascript callback.

**Comment by christocracy** [comment]
In latest version `2.12.0`, I've added `@property {Boolean} success` to the `response`.

```javascript
BackgroundGeolocation.on('http', (response) {
  if (response.success) {
    console.log('[http] success - ', response);
  } else {
    console.log('[http] failure - ', response);
  }
});
```

**Comment by AleskiWeb** [comment]
I'll take it then that there was no way of capturing the post request?

**Comment by christocracy** [comment]
You will see the response from your server only.
