### ISSUE TITLE
Request Permission Status

### ISSUE THREAD

**Issue by luskin** [transistorsoft/react-native-background-geolocation#482]
Hello, and pardon me if this has been documented somewhere but I have looked pretty thoroughly through the documentation and cannot find a method with a location services permission status callback. I see that there is a listener for 'providerchange' which is similar but only fired off when a permission changes. I simply need a callback to inform me of the permission status so that I can redirect the user flow accordingly.

**Comment by christocracy** [comment]
Listen to `providerchange` (Before executing `#ready`/`#configure`.

The plugin will fire a providerchange at boot lettting you know the current state.

**Comment by luskin** [comment]
I need to check it every time the app becomes active. Our app should not be usable if they have disabled or even changed (ios) to When In Use.

**Comment by christocracy** [comment]
Have you *tried* listening to providerchange yet?

**Comment by christocracy** [comment]
It doesn’t need to fire every time.  It only needs to fire when things change.

If you want to know the current value, setState the current value provided to providerchange

**Comment by luskin** [comment]
I understand that, but if the app is closed, then I disable location permissions in settings, on iOS at least, and then re-open the app the call back to providerchange doesn't seem to fire so my app doesn't know that the location service has been unauthorized. I would like to redirect the user to a page requiring them to enable services before using the app any further. Thanks for the quick replies as always Chris.

**Comment by christocracy** [comment]
```javascript
componentDidMount() {
  // listen to providerchange BEFORE #ready.  #read will force fire a providerchange with current state.
  BackgroundGeolocation.on('providerchange', (provider) => {
    console.log('[providerchange] - ', provider);
  });
  BackgroundGeolocation.ready({...your config...}, (state) => {
    console.log('[ready] - providerchange has just fired');
  });
}
```

**Comment by luskin** [comment]
Hey Chris, here is my code. As mentioned previously the log for "Provide Status: _________" is never called, even though I am following your instructions creating the providerchange listener before calling ready, thanks.

`export const start = () => dispatch => {
  BackgroundGeolocation.on('providerchange', provider => {
    console.log('Provider Status: ' + provider.status)
  })
  startTracking()
}

const startTracking = () => {
  BackgroundGeolocation.ready(
    {
      // FOR DEBUG
      reset: false,

      // Geolocation Config
      desiredAccuracy: 0,
      distanceFilter: 500,

      // Activity Recognition
      stopTimeout: 1,

      // Application config
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      heartbeatInterval: 0,
      foregroundService: true,
      forceReloadOnBoot: true,

      // HTTP Settings (Posting locations)
      httpRootProperty: 'location',
      url:
        Platform.OS === 'ios'
          ? 'https://XXXXXXXXXXXXXX'
          : 'https://YYYYYYYYYYYYYYY',
      locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}',
      batchSync: false,
      autoSync: true,

      // Android Always On Location Notification Title/Text
      notificationTitle: '**********',
      notificationText: '******************'
    },
    state => {
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log('- Start success')
        })
      }
    }
  )
}`

**Comment by whozDougie** [comment]
Hi @christocracy, Just following through on this, I'm in a similar situation. What if the app loads, and I don't want to wait for the providerchange event to occur and I just want to know if the app has ("Always") background location access? We've tried to implement the good work you've done in 3.9.2, but the differences in the UX isn't ideal for us to be able to guarantee the app will have background access (too many screens and popups for the user!).

So what we are planning to do is to:
1) Check if the user has background location access. If not, we show a custom prompt, which will take the user to the OS's app settings UI.
2) Otherwise we leave this alone.

Our app needs to run with location access in the background as well, and has background processes - it uses a paid licence of this component to do the geofencing checking.

Do you have any suggestions here for us on how we can check for background location access without request for it? Any ideas are kindly recommended.

**Comment by christocracy** [comment]
Are there no hints of a particular method you might call in the api docs of onProviderChange?

**Comment by whozDougie** [comment]
@christocracy Appreciate the response, yes I found this:
https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#onproviderchange

Is there a certain condition before it fires?

Before I app started, it has no location access, and while it is running, it still doesn't have location access. The code below doesn't seem to fire at all!


    BackgroundGeolocation.onProviderChange((event) => {
      console.log("************************[onProviderChange: ",  event);
      
      switch(event.status) {
        case BackgroundGeolocation.AUTHORIZATION_STATUS_DENIED:
          // Android & iOS
          console.log("- Location authorization denied");
          break;
        case BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS:
          // Android & iOS
          console.log("- Location always granted");
          break;
        case BackgroundGeolocation.AUTHORIZATION_STATUS_WHEN_IN_USE:
          // iOS only
          console.log("- Location WhenInUse granted");
          break;
      }
    });

**Comment by christocracy** [comment]
Did you read the *"See Also: `getProviderState`* method?  Is that not interesting to you?

**Comment by whozDougie** [comment]
Thanks @christocracy I missed that! I'll give it a shot now. Many thanks champ

**Comment by whozDougie** [comment]
@christocracy I gave that a shot and it works. 

 let providerState = await BackgroundGeolocation.getProviderState();
    console.log("============> Provider state: ", providerState);
    console.log("=====>BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS: ", BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS)
    if (providerState !== BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS) {
      this.props.navigation.navigate('LocationAccessRequest');
    } 

The documentation says Android only has two states, but I found on Android 10, it's got more than that.
https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.providerchangeevent.html#status

**Comment by christocracy** [comment]
The docs are not necessarily up-to-date with reality.
