### ISSUE TITLE
App not tracking my progress when in offline mode (no wifi and no data)

### ISSUE THREAD

**Issue by david-code10** [transistorsoft/react-native-background-geolocation#483]
The propose of the app I am creating is to track the user's progress regardless if he/she is in wifi range or have mobile data or not.
It works fine when mobile data is in use or in wifi range however I did a test many times with different configurations to track myself during offline mode but no luck.
In my test, I used two phones (no sims) and both resulted with initial tracking while being in the range of my router but after I leave to walk around for a long time and then come back in range, there is no gps tracking info of my trip.  Only when I enter back in range, I see my current gps co-ordinates and nothing in between.
Can you please help me for I am new to this and don't know how to continue forward.
Thank you in advance. 

## Your Environment
* Plugin version: 2.12.0-beta.3
* Platform: Android
* OS version: 5 and 6
* Device manufacturer / model: Nexus 5 (Android 6) and Samsung Galaxy Note 3 (Android 5)
* React Native version (`react-native -v`): 0.46.1
* Plugin config
{
    "activityRecognitionInterval": 10000,
    "allowIdenticalLocations": false,
    "autoSync": true,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "debug": false,
    "deferTime": 0,
    "desiredAccuracy": 0,
    "desiredOdometerAccuracy": 100,
    "disableElasticity": false,
    "disableStopDetection": false,
    "distanceFilter": 10,
    "elasticityMultiplier": 1,
    "enableHeadless": true,
    "extras": {},
    "fastestLocationUpdateInterval": 10000,
    "forceReloadOnBoot": true,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": true,
    "forceReloadOnMotionChange": true,
    "forceReloadOnSchedule": true,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": true,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {
        "Authorization": "Token token=secret_token0123567890,app_key=\"app_key01234567890\"",
        "Content-Type": "application\/json"
    },
    "headlessJobService": "",
    "heartbeatInterval": 60,
    "httpRootProperty": "gps_position",
    "httpTimeout": 60000,
    "isMoving": false,
    "locationTemplate": "{\"lat\":<%= latitude %>,\"lon\":<%= longitude %>,\"timestamp\":\"<%= timestamp %>\",\"metadata\":{\"speed\":<%= speed %>,\"heading\":<%= heading %>,\"accuracy\":<%= accuracy %>,\"event\":\"<%= event %>\",\"odometer\":<%= odometer %>,\"activity_type\":\"<%= activity.type %>\",\"activity_confidence\":<%= activity.confidence %>,\"battery_level\":<%= battery.level %>,\"battery_is_charging\":<%= battery.is_charging %>,\"version\":\"4.60.77\",\"gps\":\"Y\",\"wifi\":\"Y\",\"mobile_data\":\"N\", \"device_brand\":\"samsung\", \"device_model\":\"SM-N9005\", \"system_name\": \"Android\", \"system_version\":\"5.0\"}, \"user_id\":257, \"type\": \"generic\"}",
    "locationTimeout": 60,
    "locationUpdateInterval": 60000,
    "locationsOrderDirection": "ASC",
    "logLevel": 5,
    "logMaxDays": 3,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": -1,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 75,
    "notificationColor": "",
    "notificationLargeIcon": "",
    "notificationPriority": 0,
    "notificationSmallIcon": "",
    "notificationText": "Location Service activated",
    "notificationTitle": "My App",
    "params": {},
    "persist": true,
    "schedule": [
        "1 1:00-23:00",
        "2 1:00-23:00",
        "3 1:00-23:00",
        "4 1:00-23:00",
        "5 1:00-23:00",
        "6 1:00-23:00",
        "7 1:00-23:00"
    ],
    "startOnBoot": true,
    "stationaryRadius": 5,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": false,
    "stopTimeout": 5,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "https:\/\/test-api.testserver.com:443\/api\/v1\/gps_positions",
    "enabled": true,
    "schedulerEnabled": true,
    "trackingMode": 1,
    "odometer": 1.3741958141326904,
    "isFirstBoot": false
}

## Expected Behavior
Location Tracking is still active and continue to store my progress during offline (out of wifi range and no mobile data).  Until I re-establish connection, all the data of my progress is upload to my server.

## Actual Behavior
I left my area out of the range of my wifi and walked around for about 2 hours and then come back within range.  I only see two or three co-ordinates of my travel which is the start and the end of my travel.  And both were within the range of my wifi.

## Steps to Reproduce

1.  Opened my app on my device (wifi only, no mobile data) and made sure the tracking is active.
2.  Pressed the power button to close the screen.
3.  Walked for more than 20 mins.
4.  Come back into the range of my wifi and check my webpage on my path.

## Context
Trying to track my progress while in offline mode with no internet connection.

**Comment by david-code10** [comment]
[background-geolocation.nexus5.log](https://github.com/transistorsoft/react-native-background-geolocation/files/1998353/background-geolocation.nexus5.log)

Attached Log from my Nexus 5 mobile device.

**Comment by david-code10** [comment]
Attached Log from my Samsung Galaxy Note 3

[background-geolocation.SamsungGN3.log](https://github.com/transistorsoft/react-native-background-geolocation/files/1998354/background-geolocation.SamsungGN3.log)
 mobile device.

**Comment by christocracy** [comment]
Try with latest released `2.12.0`.

**Comment by david-code10** [comment]
Hi Chris,
Thank you for the feedback.
I will update to the latest release and retest.

Cheers!

**Comment by david-code10** [comment]
Hi Chris,
I am still experiencing the same issue.
Is the configuration that I am using looks fine to you?
Just wondering.

Thank you in advance.

**Comment by david-code10** [comment]
Hi Chris,
I think I've might have been still testing the old build.  My bad.

It seems to be working now but I still have some questions for you if you can kindly help here.
Please see map below of my trip.  There are two Tracking Areas (1 and 2) that seems to be a bit of a gap.  I do like to see that I have somewhat turned the corner here and there, therefore I like to see more co-ordinates being tracked.

![my_trip_2018-05-17](https://user-images.githubusercontent.com/14255475/40168979-e7296752-5992-11e8-9af6-02f12ab89c85.jpg)

This is my config which is still the same.

>{
    "activityRecognitionInterval": 10000,
    "allowIdenticalLocations": false,
    "autoSync": true,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "debug": false,
    "deferTime": 0,
    "desiredAccuracy": 0,
    "desiredOdometerAccuracy": 100,
    "disableElasticity": false,
    "disableStopDetection": false,
    "distanceFilter": 10,
    "elasticityMultiplier": 1,
    "enableHeadless": true,
    "extras": {},
    "fastestLocationUpdateInterval": 10000,
    "forceReloadOnBoot": true,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": true,
    "forceReloadOnMotionChange": true,
    "forceReloadOnSchedule": true,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": true,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {
        "Authorization": "Token token=secret_token0123567890,app_key=\"app_key01234567890\"",
        "Content-Type": "application\/json"
    },
    "headlessJobService": "",
    "heartbeatInterval": 60,
    "httpRootProperty": "gps_position",
    "httpTimeout": 60000,
    "isMoving": true,
    "locationTemplate": "{\"lat\":<%= latitude %>,\"lon\":<%= longitude %>,\"timestamp\":\"<%= timestamp %>\",\"metadata\":{\"speed\":<%= speed %>,\"heading\":<%= heading %>,\"accuracy\":<%= accuracy %>,\"event\":\"<%= event %>\",\"odometer\":<%= odometer %>,\"activity_type\":\"<%= activity.type %>\",\"activity_confidence\":<%= activity.confidence %>,\"battery_level\":<%= battery.level %>,\"battery_is_charging\":<%= battery.is_charging %>,\"version\":\"4.61.78\",\"gps\":\"Y\",\"wifi\":\"Y\",\"mobile_data\":\"N\", \"device_brand\":\"samsung\", \"device_model\":\"SM-N9005\", \"system_name\": \"Android\", \"system_version\":\"5.0\"}, \"user_id\":257, \"type\": \"generic\"}",
    "locationTimeout": 60,
    "locationUpdateInterval": 60000,
    "locationsOrderDirection": "ASC",
    "logLevel": 5,
    "logMaxDays": 3,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": -1,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 75,
    "notificationColor": "",
    "notificationLargeIcon": "",
    "notificationPriority": 0,
    "notificationSmallIcon": "",
    "notificationText": "Location Service activated",
    "notificationTitle": "Ryse",
    "params": {},
    "persist": true,
    "schedule": [
        "1 1:00-23:00",
        "2 1:00-23:00",
        "3 1:00-23:00",
        "4 1:00-23:00",
        "5 1:00-23:00",
        "6 1:00-23:00",
        "7 1:00-23:00"
    ],
    "startOnBoot": true,
    "stationaryRadius": 5,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": false,
    "stopTimeout": 5,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "https:\/\/test-api.code10.ca:443\/api\/v1\/gps_positions",
    "enabled": true,
    "schedulerEnabled": true,
    "trackingMode": 1,
    "odometer": 12556.8720703125,
    "isFirstBoot": false
}


And here is my log of this trip.
[background-geolocation.SamsungGN3.log](https://github.com/transistorsoft/react-native-background-geolocation/files/2012538/background-geolocation.SamsungGN3.log)

Can you recommend what I can change to my configuration?  I know there will be some trade offs between battery life vs. more data/accuracy tracking which I accept.

Thank you in advance.

-David

**Comment by david-code10** [comment]
Hi Chris,
I am sorry to bother you.
Just wondering if you can give me a quick insight or something I can move forward to.
Thank you so much in advance.
-David

**Comment by christocracy** [comment]
I see nothing unusual in logs.  The device's location API simply failed to provide locations to the plugin during those periods.  It is as if the device had problems connecting to GPS satellites due to obstruction (bridges, tunnels, tall buildings, etc).

**Comment by christocracy** [comment]
>which line specified that the device's location API failed

There is no line specifying this.

Think of location-services as a tap of water.  The plugin provides you an api to turn the taps on.  Usually water drips consistently out of the taps and the plugin provides these locations to you, straight out of the tap.

In your case, there was simply no water flowing out of the taps.  The taps *were* turned on.

The same behaviour will occur if you drive into a tunnel or walk underground into a subway station.

**Comment by david-code10** [comment]
Thank you Chris!
I love your analogy.
And thank you so much in taking the time to help me.
This experience gave me a better understanding about your plugin.

Cheers!
-David

Closing issue.
