### ISSUE TITLE
Run Geolocation Plugin in the background

### ISSUE THREAD

**Issue by gaurabguha** [transistorsoft/react-native-background-geolocation#488]
## Your Environment
* Plugin version: 2.12.0-beta.4
* Platform: Android
* OS version: 7
* Device manufacturer / model: One Plus 3T
* React Native version (`react-native -v`): 0.55.3
* Plugin config
{
// Geolocation Config
desiredAccuracy: 0,
distanceFilter: 10,
// Activity Recognition
stopTimeout: 1,
// Application config
debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
startOnBoot: true, // <-- Auto start tracking when device is powered-up.
// HTTP / SQLite config
url: 'http://yourserver.com/locations',
batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
headers: { // <-- Optional HTTP headers
"X-FOO": "bar"
},
params: { // <-- Optional HTTP params
"auth_token": "maybe_your_server_authenticates_via_token_YES?"
}
}

## Expected Behavior
The plugin should run in the background.

## Actual Behavior
The plugin is running in the foreground showing captured data on screen.

## Steps to Reproduce
Run the app either from Node.js command prompt using the command react-native run-android.

## Context
Integrate the plugin with our existing app so that it runs in the background.

**Comment by christocracy** [comment]
Are you observing the logs?  See [Debugging](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging)

See real time logs by connecting your device to USB and running:
```
$ adb logcat -s TSLocationManager
```

Also, install latest released version of `2.12.0`.  You're using `2.12.0-beta.4`

**Comment by christocracy** [comment]
Closed for lack of feedback
