### ISSUE TITLE
[iOS]: App stops tracking randomly in background (with logs to prove)

### ISSUE THREAD

**Issue by luskin** [transistorsoft/react-native-background-geolocation#489]
## Your Environment
* Plugin version: 2.12.0-beta.4
* Platform: iOS or Android iOS
* OS version: 11.2.6
* Device manufacturer / model: iPhone X
* React Native version (`react-native -v`): 0.55
* Plugin config

```
BackgroundGeolocation.ready({

      // FOR DEBUG
      reset: false,

      // Geolocation Config
      desiredAccuracy: 0,
      distanceFilter: 500,
  
      // Activity Recognition
      stopTimeout: 1,
  
      // Application config
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      heartbeatInterval: 0,
      foregroundService: true,
      forceReloadOnBoot: true,
  
      // HTTP Settings (Posting locations)
      httpRootProperty: 'location',
      url:
        Platform.OS === 'ios'
          ? ****************
          : ******************,
      locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}',
      batchSync: false,
      autoSync: true,
  
      // Android Always On Location Notification Title/Text
      notificationTitle: 'Bolt Driver',
      notificationText: 'Keep app open for dispatches'
    },
    state => {
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log('[LOCATION]: Began tracking')
        })
      } else {
        console.log('[LOCATION]: Began tracking')
      }
    }
  )
```

## Expected Behavior
App should continue tracking in the background

## Actual Behavior
In los angeles I drove with app closed from west los angeles to near downtown (about 8 miles), the app tracked just fine and posted to our server, all good. Then, at 7:23pm (19:23) we received the last location update, even though a few hours later we drove those 8 miles back to west los angeles, stayed there the night and then drove another 2 miles to work, the app never posted a single location until I got to work, plugged my phone in and booted the app to post the logs so we can see what happened. It looks like at 7:23 (19:23) in the logs the package decided to just shut down with the log `2018-05-15 19:23:12.341 🔴-[LocationManager stopUpdatingLocation] OFF`, then it did not resume again until 9:26am when I launched the app at work.

## Steps to Reproduce
1. Config + Set up app with locations posting and working well
2. Close app and drive around your city
3. Locations post for a certain amount of time then package shuts itself off and does not restart ever

## Context
Background track driving around the city (for a fleet management app where we DO NOT want to preventSuspend).

## Debug logs

[LocationStoppediOS.docx](https://github.com/transistorsoft/react-native-background-geolocation/files/2010025/LocationStoppediOS.docx)

**Comment by christocracy** [comment]
Keep field-testing and keep me updated.

**Comment by luskin** [comment]
@christocracy why did it stop on it's own? Yesterdays test alone proves that this package in fact does NOT continue tracking in the background even after only a few hours of being closed. We've paid for 2 years of license for tracking on our android devices, how should we proceed with iOS?

**Comment by christocracy** [comment]
I have no idea.  Could be an issue with your own app code.

Perform longer term field-testing.

I cannot reproduce this.  I have 2 iOS test devices I carry around regularly with my sample app running without fail for weeks at a time.

**Comment by luskin** [comment]
Are you referring to our own native code? Or JS code? I don't think it could be our JS code because I closed the app (not background) so no JS code should be able to run on iOS. Tracking worked for several hours from about 5:30 to 7:23 then just stopped on it's own with nothing affecting it (as in app was not opened, no push notifications... etc), the phone was simply in my pocket all night.

**Comment by luskin** [comment]
Additionally it does not help us if the app stops tracking for a long period of time and then decides to restart at some unknown time later - we are developing a fleet tracking app (as advertised on your website) so anything more than a half mile to a mile inaccuracy yields the product useless to us.

**Comment by christocracy** [comment]
Keep testing.  Let me know if you have a chronic issue.  Also install my [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo) on your device as well.  It will post its tracking to my test-server at tracker.transistorsoft.com.

**Comment by luskin** [comment]
My concern, and correct me if I'm wrong, but your sampleapp will be collecting those locations locally so when the app does get woken back up it will post them all making it _look_ like the locations were posted at that time but actually were not. It's hard to be constantly monitoring your website while moving about the city.

**Comment by christocracy** [comment]
>but your sampleapp will be collecting those locations locally

?

>making it look like the locations were posted at that time but actually were not

That's what the server's **`created_at`** timestamp is for.

![](https://dl.dropboxusercontent.com/s/ylg6pijk3swwdfi/Screenshot%202018-05-16%2019.13.36.png?dl=1)

> It's hard to be constantly monitoring your website while moving about the city.

You don't have to.  Just let it run for days and check it periodically.

**Comment by christocracy** [comment]
Why don’t you simply encapsulate all your plugin-specific code into your own custom library and signal it to “run” (where you execute the plugin’s `#ready` method) via your App `componentDidMount`?

Also, why don’t write for me a simple test-case app (starting with `react-native init TestApp` which shows me how it is you’re *not* initializing the plugin in a `componentDidMount`?

**Comment by luskin** [comment]
That is exactly what we do, our approach is as follows:

**Launch Component:**
```
  componentDidMount() {
    Services.init()
  }
```

**Services:**
```
export default {
 init: async () => {
    console.log('[SERVICES]: Initializing')

   // Begin Services
    Location.start()
    ....etc
  }
}
```

**Location Service:**
```
export const start = () => {
  ...etc
  if (locationPermissionAuthorized) {
    console.log('[LOCATION]: Permission is authorized, begin tracking')
    startTracking()
  } else {
    console.log('[LOCATION]: Permission is not granted, do not starting tracking')
  }
}
```

and `startTracking()` simply wraps the `BackgroundGeolocation.ready()` initialization posted in my initial comment.

For the sake of understanding all differences we notice that you are also beginning a BackgroundFetch process that gets the current position, we are not using`BackgroundFetch` but we are happy to do so if you think that would make a difference. Lastly, our distanceFilter is 500 where as yours is 10, could 500 simply be too large of a radius?

**Comment by christocracy** [comment]
>we notice that you are also beginning a BackgroundFetch process that gets the current position,

This is not required.  It doesn't make any difference to the behaviour of background-geolocation.

>our distanceFilter is 500

Are you aware that the plugin auto-scales [`distanceFilter`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-integer-distancefilter) based upon speed *by default*?

At highway speed (27 m/s), `distanceFilter: 500` becomes `3000`.

**Comment by luskin** [comment]
Thanks for the quick reply. We have scrapped our code and going to simply copy and paste your config code into our app for testing over the long weekend, although we don't see anything wrong in our configuration, who knows. About the distanceFilter at highway speeds, wouldn't the location be updated when the vehicle would come to a stop for a certain amount of time? For example in the logs, the plugin shut down for unknown reasons, then I drove another 8 miles and it was never booted back up or anything. This has now happened several times.

**Comment by christocracy** [comment]
`distanceFilter` is an *instance* variable -- it's scaled-state is not persisted between boots.  I'm just saying, that at highway speed, you're going to be recording a location every `3000` meters.  I'm not saying it has anything to do with your issue.

When a device is detected to be stationary, the `distanceFilter` is reset back to configured value.

>For example in the logs, the plugin shut down for unknown reasons

iOS can and *will* terminate your app in the background.  You  can expect this.  However, the plugin is monitoring a number of APIs that persist in spite of termination which are capable of rebooting the app to service those events (primarily the stationary geofence).
