### ISSUE TITLE
Logically, what clarifies as an activityType: STILL

### ISSUE THREAD

**Issue by AleskiWeb** [transistorsoft/react-native-background-geolocation#490]
This is a query more than an issue but I don't know another port of call to reach you so I thought I'd ask in here. Basically we are using the plugin to generate `staypoints` based on the activity type of `STILL` being sent from the phone to the server. I was wondering if you could clarify a question for me:

As far as I am aware, when a device hasnt moved more than the `distanceFilter` horizontally, then there wont be any new locations posted from the device. That being said, if I am walking, reach a location and then keep moving around in that location (say, a shopping mall, where I might be walking down the aisles) will my phone provide an activity change of `STILL` even though I am still technically moving around -> because I haven't moved more than the `distanceFilter` value, in meters, horizontally?

**Comment by christocracy** [comment]
This is the place to ask questions.

The motion-api is completely independent of the geolocation system.  The motion API is based upon accelerometer / gyroscope / magnetometer to generate events.

If you are walking, the motion API will report `on_foot`.

**Comment by AleskiWeb** [comment]
Alright. So using the plugin what would be the best implementation for detecting someone has not moved?

Are you saying that I should set the `distanceFilter` to something large enough that nominal movement wont post a new location? And then to decide if they have remained in one location for long enough, just compare the timestamp of where they are now to where they were?

**Comment by christocracy** [comment]
You sound like you're not fully understanding or haven't read the [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

**Comment by christocracy** [comment]
- When the plugin is in the **moving** state, a location will be recorded each `distanceFilter` meters.
- When the device is `still` for `stopTimeout` minutes, the plugin will change state to **stationary**, record a location and fire the `motionchange` event, providing that location.

When you say "geofencing", are you talking about *the plugin's* geofencing API?

**Comment by AleskiWeb** [comment]
>*moving* state
That would be when `is_moving: true` from the plugin right?

So if I understand this, the `is_moving: false` is set if the motionAPI decides that my phone has been `still` for `stopTimeout` minutes (basically as you just said).

When I say geofencing, I just mean loosely trying to group locations, not the API so to speak.

So if I wanted to detect that a user is "stationary", then I should record locations that send `is_moving: false` as that determines that the device has been still for longer than `stopTimeout` minutes.

Edit: What does the motionAPI count as `still` - physically actually still on the device? (on a table/desk etc) and if you were walking around the office, despite the office being in a small area, it would still never post a `is_moving: false`?

**Comment by christocracy** [comment]
>So if I wanted to detect that a user is "stationary", then I should record locations that send 

You don't *need to* detect this.  The plugin does this automatically for you -- simply listen to the [`motionchange`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#motionchange) event.

>What does the motionAPI count as still

The [Motion API](https://developers.google.com/location-context/activity-recognition/) is a black box provided by the `play-services` API.  It aggregates available sensors (eg: accelerometer, gyroscope, magnetometer) with baked-in intelligence from Google Physicists / Mathematicians  to spit out `on_foot`, `still`, `in_vehicle`, etc.

> if you were walking around the office, despite the office being in a small area

"small area" doesn't matter.   As I said, the Motion API is *completely* separate from the geolocation API.  You can simulate `on_foot` by simply sitting in your desk and *shaking* the device vigorously.  When the plugin sees an `ActivityRecognitionResult` for a *moving-type* activity (ie: `on_foot`, `in_vehicle`, etc) with a [`confidence >= minimumActivityRecognitionConfidence`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-integer-millis-minimumactivityrecognitionconfidence) (default 75%), it will change moving state.

Try it:
```
$ adb logcat -s TSLocationManager
```
TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (46%)
TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] on_foot (66%)
TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] on_foot (90%)
TSLocationManager: [c.t.l.BackgroundGeolocationService k]
TSLocationManager:   🔴  Stop heartbeat
TSLocationManager: [c.t.l.BackgroundGeolocationService a]
TSLocationManager:   🔵  setPace: false → true
```

**Comment by AleskiWeb** [comment]
Alright yeah, thanks for the clarification 👍
