### ISSUE TITLE
Geo Location not captured after app killed in Redmi and Le Mobile

### ISSUE THREAD

**Issue by pkumar125** [transistorsoft/react-native-background-geolocation#491]
## Your Environment
* Plugin version: 2.12.13 (269)
* Platform: Android
* OS version: Android 6
* Device manufacturer / model:
Le X526-LeMobile
Redmi 3S-Xiaomi
Redmi 5A-Xiaomi

* React Native version (`react-native -v`): 0.54.2
* Plugin config

## Expected Behavior

I should get geo location i.e. lat and log of device even after killing the app in mobile.

## Actual Behavior

I am not getting get lat and log after killing the app in mobile device. Its working in some device but not working in few android mobile e.g. Le X526-LeMobile, Redmi 3S-Xiaomi, Redmi 5A-Xiaomi

## Steps to Reproduce

1. install apk
2. kill the app
3. check lat and log in database 
4. no data and hit for few device

## Context

I need real time location of our field team members
## Debug logs

05-22 19:07:21.565 17172-17172/? I/art: Late-enabling -Xcheck:jni
05-22 19:07:21.602 17172-17172/? D/TidaProvider: TidaProvider()
05-22 19:07:21.681 17172-17172/com.mouli V/fb-UnpackingSoSource: locked dso store /data/user/0/com.mouli/lib-main
05-22 19:07:21.682 17172-17172/com.mouli I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.mouli/lib-main
05-22 19:07:21.682 17172-17172/com.mouli V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.mouli/lib-main
05-22 19:07:31.684 17172-17191/com.mouli D/EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
05-22 19:07:31.685 17172-17191/com.mouli D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
05-22 19:07:42.101 17172-17203/com.mouli D/EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
05-22 19:07:42.101 17172-17203/com.mouli D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
05-22 19:07:52.389 17172-17252/com.mouli I/TSLocationManager: ╔═════════════════════════════════════════════
                                                              ║ License Validation Failure
                                                              ╠═════════════════════════════════════════════
                                                              ╟─ BackgroundGeolocation is running in evaluation mode.
05-22 19:07:52.389 17172-17252/com.mouli D/EventBus: No subscribers registered for event class com.transistorsoft.locationmanager.event.SettingsFailureEvent
05-22 19:07:52.389 17172-17252/com.mouli D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
05-22 19:07:52.434 17172-17252/com.mouli I/TSLocationManager: [c.t.l.adapter.TSConfig print] 
                                                              ╔═════════════════════════════════════════════
                                                              ║ TSLocationManager version: 2.12.13 (269)
                                                              ╠═════════════════════════════════════════════
                                                              {
                                                                "activityRecognitionInterval": 10000,
                                                                "allowIdenticalLocations": false,
                                                                "autoSync": true,
                                                                "autoSyncThreshold": 10,
                                                                "batchSync": true,
                                                                "debug": false,
                                                                "deferTime": 0,
                                                                "desiredAccuracy": 0,
                                                                "desiredOdometerAccuracy": 100,
                                                                "disableElasticity": false,
                                                                "disableStopDetection": false,
                                                                "distanceFilter": 10,
                                                                "elasticityMultiplier": 1,
                                                                "enableHeadless": false,
                                                                "extras": {},
                                                                "fastestLocationUpdateInterval": 10000,
                                                                "forceReloadOnBoot": false,
                                                                "forceReloadOnGeofence": false,
                                                                "forceReloadOnHeartbeat": false,
                                                                "forceReloadOnLocationChange": false,
                                                                "forceReloadOnMotionChange": false,
                                                                "forceReloadOnSchedule": false,
                                                                "foregroundService": true,
                                                                "geofenceInitialTriggerEntry": true,
                                                                "geofenceProximityRadius": 1000,
                                                                "geofenceTemplate": "",
                                                                "headers": {},
                                                                "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",
                                                                "heartbeatInterval": 60,
                                                                "httpRootProperty": "location",
                                                                "httpTimeout": 60000,
                                                                "isMoving": false,
                                                                "locationTemplate": "",
                                                                "locationTimeout": 60,
                                                                "locationUpdateInterval": 1000,
                                                                "locationsOrderDirection": "ASC",
                                                                "logLevel": 5,
                                                                "logMaxDays": 3,
                                                                "maxBatchSize": 10,
                                                                "maxDaysToPersist": 1,
                                                                "maxRecordsToPersist": -1,
                                                                "method": "POST",
                                                                "minimumActivityRecognitionConfidence": 75,
                                                                "notificationColor": "",
                                                                "notificationLargeIcon": "",
                                                                "notificationPriority": 0,
                                                                "notificationSmallIcon": "",
                                                                "notificationText": "Location Service activated",
                                                                "notificationTitle": "",
                                                                "params": {
                                                                  "device": {
                                                                    "driver_id": "0",
                                                                    "version": "6.0.1",
                                                                    "manufacturer": "Xiaomi",
                                                                    "framework": "ReactNative",
                                                                    "platform": "Android",
                                                                    "model": "Redmi 3S",
                                                                    "uuid": "d716ddbb39c6386b"
                                                                  }
                                                                },
                                                                "persist": true,
                                                                "schedule": [
                                                                  "2-7 8:00-21:00"
                                                                ],
                                                                "startOnBoot": true,
                                                                "stationaryRadius": 25,
                                                                "stopAfterElapsedMinutes": 0,
                                                                "stopOnStationary": false,
                                                                "stopOnTerminate": false,
                                                                "stopTimeout": 5,
                                                                "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                "url": "http:\/\/dev.wowtruck.in\/webservice\/geolocation",
                                                                "enabled": true,
                                                                "schedulerEnabled": false,
                                                                "trackingMode": 1,
                                                                "odometer": 0,
                                                                "isFirstBoot": false
                                                              }
                                                              ╔═════════════════════════════════════════════
                                                              ║ DEVICE SENSORS
                                                              ╠═════════════════════════════════════════════
                                                              ╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DS3 Accelerometer", vendor="STMicroelectronics", version=1, type=1, maxRange=39.22661, resolution=0.0023956299, power=0.9, minDelay=5000}
                                                              ╟─ ✅  GYROSCOPE: {Sensor name="LSM6DS3 Gyroscope", vendor="STMicroelectronics", version=1, type=4, maxRange=34.906586, resolution=0.0012207031, power=0.9, minDelay=5000}
                                                              ╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetometer", vendor="Yamaha", version=35193090, type=2, maxRange=2000.0, resolution=0.30059814, power=0.28, minDelay=10000}
                                                              ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.8999939, minDelay=-1}
                                                              ╚═════════════════════════════════════════════
05-22 19:07:52.544 17172-17252/com.mouli I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                                ✅  Google Play Services: connected (version code:11910000)
05-22 19:07:52.571 17172-17252/com.mouli D/TSLocationManager: [c.t.locationmanager.data.a.c a] 
                                                                ✅  Opened database
05-22 19:07:52.596 17172-17252/com.mouli D/TSLocationManager: [c.t.locationmanager.data.a.c prune] 
                                                                ℹ️  PRUNE -1 days
05-22 19:07:52.645 17172-17252/com.mouli D/TSLocationManager: [c.t.locationmanager.data.a.a f] 
                                                                ✅  Opened database
05-22 19:07:52.707 17172-17252/com.mouli D/TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
05-22 19:07:52.734 17172-17252/com.mouli E/TSLocationManager: [c.t.l.l.TSLocationManager getLastLocation] 
                                                                ‼️  Failed to get last location: com.google.android.gms.tasks.zzn@7fda17a
05-22 19:07:52.752 17172-17252/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:07:52.808 17172-17266/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:02.928 17172-17269/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:13.040 17172-17272/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:22.545 17172-17290/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:32.652 17172-17293/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:42.745 17172-17298/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:52.755 17172-17375/com.mouli D/TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
05-22 19:08:52.779 17172-17375/com.mouli E/TSLocationManager: [c.t.l.l.TSLocationManager getLastLocation] 
                                                                ‼️  Failed to get last location: com.google.android.gms.tasks.zzn@aa7de91
05-22 19:08:52.806 17172-17375/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:52.861 17172-17377/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:09:03.176 17172-17388/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:09:13.286 17172-17392/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:09:23.410 17172-17407/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO

**Comment by christocracy** [comment]
Got some logs?

**Comment by pkumar125** [comment]
05-22 19:07:21.565 17172-17172/? I/art: Late-enabling -Xcheck:jni
05-22 19:07:21.602 17172-17172/? D/TidaProvider: TidaProvider()
05-22 19:07:21.681 17172-17172/com.mouli V/fb-UnpackingSoSource: locked dso store /data/user/0/com.mouli/lib-main
05-22 19:07:21.682 17172-17172/com.mouli I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.mouli/lib-main
05-22 19:07:21.682 17172-17172/com.mouli V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.mouli/lib-main
05-22 19:07:31.684 17172-17191/com.mouli D/EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
05-22 19:07:31.685 17172-17191/com.mouli D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
05-22 19:07:42.101 17172-17203/com.mouli D/EventBus: No subscribers registered for event class com.google.android.gms.location.ActivityRecognitionResult
05-22 19:07:42.101 17172-17203/com.mouli D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
05-22 19:07:52.389 17172-17252/com.mouli I/TSLocationManager: ╔═════════════════════════════════════════════
                                                              ║ License Validation Failure
                                                              ╠═════════════════════════════════════════════
                                                              ╟─ BackgroundGeolocation is running in evaluation mode.
05-22 19:07:52.389 17172-17252/com.mouli D/EventBus: No subscribers registered for event class com.transistorsoft.locationmanager.event.SettingsFailureEvent
05-22 19:07:52.389 17172-17252/com.mouli D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
05-22 19:07:52.434 17172-17252/com.mouli I/TSLocationManager: [c.t.l.adapter.TSConfig print] 
                                                              ╔═════════════════════════════════════════════
                                                              ║ TSLocationManager version: 2.12.13 (269)
                                                              ╠═════════════════════════════════════════════
                                                              {
                                                                "activityRecognitionInterval": 10000,
                                                                "allowIdenticalLocations": false,
                                                                "autoSync": true,
                                                                "autoSyncThreshold": 10,
                                                                "batchSync": true,
                                                                "debug": false,
                                                                "deferTime": 0,
                                                                "desiredAccuracy": 0,
                                                                "desiredOdometerAccuracy": 100,
                                                                "disableElasticity": false,
                                                                "disableStopDetection": false,
                                                                "distanceFilter": 10,
                                                                "elasticityMultiplier": 1,
                                                                "enableHeadless": false,
                                                                "extras": {},
                                                                "fastestLocationUpdateInterval": 10000,
                                                                "forceReloadOnBoot": false,
                                                                "forceReloadOnGeofence": false,
                                                                "forceReloadOnHeartbeat": false,
                                                                "forceReloadOnLocationChange": false,
                                                                "forceReloadOnMotionChange": false,
                                                                "forceReloadOnSchedule": false,
                                                                "foregroundService": true,
                                                                "geofenceInitialTriggerEntry": true,
                                                                "geofenceProximityRadius": 1000,
                                                                "geofenceTemplate": "",
                                                                "headers": {},
                                                                "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",
                                                                "heartbeatInterval": 60,
                                                                "httpRootProperty": "location",
                                                                "httpTimeout": 60000,
                                                                "isMoving": false,
                                                                "locationTemplate": "",
                                                                "locationTimeout": 60,
                                                                "locationUpdateInterval": 1000,
                                                                "locationsOrderDirection": "ASC",
                                                                "logLevel": 5,
                                                                "logMaxDays": 3,
                                                                "maxBatchSize": 10,
                                                                "maxDaysToPersist": 1,
                                                                "maxRecordsToPersist": -1,
                                                                "method": "POST",
                                                                "minimumActivityRecognitionConfidence": 75,
                                                                "notificationColor": "",
                                                                "notificationLargeIcon": "",
                                                                "notificationPriority": 0,
                                                                "notificationSmallIcon": "",
                                                                "notificationText": "Location Service activated",
                                                                "notificationTitle": "",
                                                                "params": {
                                                                  "device": {
                                                                    "driver_id": "0",
                                                                    "version": "6.0.1",
                                                                    "manufacturer": "Xiaomi",
                                                                    "framework": "ReactNative",
                                                                    "platform": "Android",
                                                                    "model": "Redmi 3S",
                                                                    "uuid": "d716ddbb39c6386b"
                                                                  }
                                                                },
                                                                "persist": true,
                                                                "schedule": [
                                                                  "2-7 8:00-21:00"
                                                                ],
                                                                "startOnBoot": true,
                                                                "stationaryRadius": 25,
                                                                "stopAfterElapsedMinutes": 0,
                                                                "stopOnStationary": false,
                                                                "stopOnTerminate": false,
                                                                "stopTimeout": 5,
                                                                "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
                                                                "url": "http:\/\/dev.wowtruck.in\/webservice\/geolocation",
                                                                "enabled": true,
                                                                "schedulerEnabled": false,
                                                                "trackingMode": 1,
                                                                "odometer": 0,
                                                                "isFirstBoot": false
                                                              }
                                                              ╔═════════════════════════════════════════════
                                                              ║ DEVICE SENSORS
                                                              ╠═════════════════════════════════════════════
                                                              ╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DS3 Accelerometer", vendor="STMicroelectronics", version=1, type=1, maxRange=39.22661, resolution=0.0023956299, power=0.9, minDelay=5000}
                                                              ╟─ ✅  GYROSCOPE: {Sensor name="LSM6DS3 Gyroscope", vendor="STMicroelectronics", version=1, type=4, maxRange=34.906586, resolution=0.0012207031, power=0.9, minDelay=5000}
                                                              ╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetometer", vendor="Yamaha", version=35193090, type=2, maxRange=2000.0, resolution=0.30059814, power=0.28, minDelay=10000}
                                                              ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.8999939, minDelay=-1}
                                                              ╚═════════════════════════════════════════════
05-22 19:07:52.544 17172-17252/com.mouli I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                                ✅  Google Play Services: connected (version code:11910000)
05-22 19:07:52.571 17172-17252/com.mouli D/TSLocationManager: [c.t.locationmanager.data.a.c a] 
                                                                ✅  Opened database
05-22 19:07:52.596 17172-17252/com.mouli D/TSLocationManager: [c.t.locationmanager.data.a.c prune] 
                                                                ℹ️  PRUNE -1 days
05-22 19:07:52.645 17172-17252/com.mouli D/TSLocationManager: [c.t.locationmanager.data.a.a f] 
                                                                ✅  Opened database
05-22 19:07:52.707 17172-17252/com.mouli D/TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
05-22 19:07:52.734 17172-17252/com.mouli E/TSLocationManager: [c.t.l.l.TSLocationManager getLastLocation] 
                                                                ‼️  Failed to get last location: com.google.android.gms.tasks.zzn@7fda17a
05-22 19:07:52.752 17172-17252/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:07:52.808 17172-17266/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:02.928 17172-17269/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:13.040 17172-17272/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:22.545 17172-17290/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:32.652 17172-17293/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:42.745 17172-17298/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:52.755 17172-17375/com.mouli D/TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
05-22 19:08:52.779 17172-17375/com.mouli E/TSLocationManager: [c.t.l.l.TSLocationManager getLastLocation] 
                                                                ‼️  Failed to get last location: com.google.android.gms.tasks.zzn@aa7de91
05-22 19:08:52.806 17172-17375/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:08:52.861 17172-17377/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:09:03.176 17172-17388/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:09:13.286 17172-17392/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
05-22 19:09:23.410 17172-17407/com.mouli D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO

**Comment by christocracy** [comment]
That's all you've got?

**Comment by pkumar125** [comment]
Yes, any idea what is the issue ?

**Comment by pkumar125** [comment]
We are about to buy licence please help on this issue.

**Comment by christocracy** [comment]
Show me a full `$ adb logcat` of terminating your app.

The issue is likely due to the manufacturer's [Battery Optimizations](https://stackoverflow.com/questions/47145722/how-to-deal-with-huaweis-and-xiaomis-battery-optimizations)

**Comment by pkumar125** [comment]
Please find the attached logs.
[WithBatteryRestriction.log](https://github.com/transistorsoft/react-native-background-geolocation/files/2038335/WithBatteryRestriction.log)
[NoBatteryRestriction.log](https://github.com/transistorsoft/react-native-background-geolocation/files/2038338/NoBatteryRestriction.log)


Note: After killing the app, logcat is clearing its logs. I manually merged both Before & After killing app logs.

**Comment by dbyilmaz** [comment]
@pkumar125 check this link https://www.gizchina.com/2016/07/01/fix-strava-gps-miui-xiaomi/.

**Comment by christocracy** [comment]
@pkumar125 What happens to the plugin service notification when you terminate the app?  There is both a notification and an icon in the notification bar.  Do these *disappear* when you terminate your app?  They're not supposed to.

Try this:  
- Boot a music player (eg: Play Music).  Start a song playing.  
- Terminate the player.  

The music *should* keep playing.

**Comment by christocracy** [comment]
Closed for lack of feedback.

**Comment by kameswarans** [comment]
@pkumar125 mam u solve the Background location issue? can u send the sample code to call in Background
plz

**Comment by christocracy** [comment]
@kameswarans What is your device model?

**Comment by kameswarans** [comment]
@christocracy Mi 4A 
But this module not work when App is killed. Sir if u have any example for Background Job please send it to me.

**Comment by Udbhav12** [comment]
@christocracy In my Redmi 6A  android device  `Location Service Activated` notification gets dismissed when I kill the app. I am using `react-native-background-geolocation:2.14.2`. That is the foreground service is getting killed,

My auto start setting is on & I have turned off all the Battery optimisations

Any idea what to do?

**Comment by christocracy** [comment]
Launch a music player (eg Play Music):  start a song playing then terminate the player.  

Does the music stop or continue playing?

**Comment by Udbhav12** [comment]
The music stops, but I also have a native app written in JAVA (I am using  IntentService in that) which keeps on running in that phone even after app termination

**Comment by christocracy** [comment]
The music isn’t supposed to stop.  

Try latest 3.0.x

**Comment by Udbhav12** [comment]
I cannot upgrade to 3.0.x as if I understand correctly, in 3.x version Foreground service is active only when the plugin is in moving state.

I want Foreground service at all times (even if plugin is in stationary state)

**Comment by christocracy** [comment]
>I want Foreground service at all times (even if plugin is in stationary state)

Why?
