### ISSUE TITLE
Question: Do `geolocation` configuration options affect the plugin in 'geofence' mode?

### ISSUE THREAD

**Issue by DusanDimitric** [transistorsoft/react-native-background-geolocation#494]
# Configuration options
   
Hi Chris,

We're using `react-native-background-geolocation` in `geofence` mode.

The question is whether the ***geolocation*** configuration options affect the plugin when in `geofence` mode?

Specifically:
* `useSignificantChangesOnly` ?
* `desiredAccuracy` ?
* `distanceFilter` ?
* `stopOnStationary` ?
* `allowIdenticalLocations` ?
* `locationUpdateInterval` ?
* `useSignificantChangesOnly ` ?

Thanks you for your continuous support,
D.D.

**Comment by christocracy** [comment]
No.
