### ISSUE TITLE
Question: Any ways to minimize resource consumption when running the plugin in `geofence` mode?

### ISSUE THREAD

**Issue by DusanDimitric** [transistorsoft/react-native-background-geolocation#495]
Hey Chris, another quick question:

***Are there any ways to minimize resource consumption (therefore - battery drain) when running the plugin in `geofence` mode?***

I suppose a smaller `geofenceProximityRadius` would result in less resource utilization, but I assume that the difference is negligible.

Many thanks,
D.D.

***Side note:*** A FAQ wiki page could be useful for future users.

**Comment by christocracy** [comment]
`geofenceProximityRadius` has a negligible effect on battery consumption and the minimum `1000` meters is *enforced* (you cannot set a value less than this).
