### ISSUE TITLE
Disable alert for location permission at first launch on app update

### ISSUE THREAD

**Issue by cesarm16** [transistorsoft/react-native-background-geolocation#497]
i've an app that uses 'whenInUse' location permission. Now im doing a update that includes this module, my problem is that is asking for permission at the start of the app without starting or getting current position from this module. I think it happens because "disableLocationAuthorizationAlert" in configure() is not applied on the native side at the first launch of the app.

## Your Environment
* Plugin version: 2.12.2
* Platform: iOS 
* OS version: 11.3
* Device manufacturer / model: Iphone 7
* React Native version (`react-native -v`): 0.55.4
* Plugin config {
			httpRootProperty: 'tracking',
			desiredAccuracy: 0,
			distanceFilter: 0,
			locationUpdateInterval: min,
			stopTimeout: 1,
			debug: false,
			logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
			stopOnTerminate: false,
			startOnBoot: true,
			url: 'https://****/api/Trackings/tracking',
			batchSync: true,
			autoSync: true,
			autoSyncThreshold: minUpd,
			maxDaysToPersist: maxDaysRecords,
			disableMotionActivityUpdates: true,
			preventSuspend: false,
			params: {
				device: {
					platform: isAndroid ? 'Android' : 'iOS',
					version: APP_VERSION,
					framework: 'ReactNative'
				}
			},
			extras: {},
			disableLocationAuthorizationAlert: true
		},

## Expected Behavior
Ask for permission when i want

## Actual Behavior
Alert is launched at the start of the app

## Steps to Reproduce
1. Have an app with location permission on 'whenInUse'
2. Install this module (update app)
3. Without uninstalling your app, update to a new version (with this module)
4. Alert is fired at first launch asking for a new permission 'always'

![image uploaded from ios](https://user-images.githubusercontent.com/7118451/40678229-9186f2b2-6345-11e8-9f84-4a0830e79ed1.png)
Alert asking for new location permissions

Sorry for my bad english.

**Comment by christocracy** [comment]
I cannot reproduce this in the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo).

**Config**
```javascript
      disableMotionActivityUpdates: true,
      disableLocationAuthorizationAlert: true,      
      stopOnTerminate: false,
      startOnBoot: true,      
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE      
```

Here is a first boot of the SampleApp ("Hello World" app) in the simulator (after fresh uninstall).

First I'm asked to authorizae "Send You Notifications".  This is normal and is caused by **`debug: true`** so the plugin can post local-notifications:
![](https://dl.dropboxusercontent.com/s/pme3rah471drkpc/Screenshot%202018-05-30%2009.55.14.png?dl=1)

The SampleApp is currently in the `disabled` state (see the toggle switch at top right, which executes `#start` / `#stop` methods).
![](https://dl.dropboxusercontent.com/s/qbjpk1jevh3pnzu/Screenshot%202018-05-30%2009.55.33.png?dl=1)

I now enable the toggle switch (which will execute `#start` method):
![](https://dl.dropboxusercontent.com/s/qu4p2dh9bvjh5ov/Screenshot%202018-05-30%2009.57.18.png?dl=1)

**Now** I'm asked for location authorization.

**Comment by cesarm16** [comment]
[https://vimeo.com/272597124](url)
Here is a video (you can skip from 0:16 to 1:00) showing my app in the App Store, it does not have this module yet. As you can see i use location only when is in use, all good. Then I install an update that has this module, in this update i has commented all functions related to react-native-background-geolocation, nothing is called (I'm sure), is just installed with cocoapods and is asking for location permission at the start of the app. I think is related with the alert "instructions: "You must enable 'Always' in location-services, buddy"", but because is an update my app can ask permissions again and doesn't show the normal alert. configure() isn't applied at the first launch.

**Comment by barbatus** [comment]
Can confirm `disableLocationAuthorizationAlert: true` not working in the last version. Location authorization alert appears at the start of the app.

**Comment by cesarm16** [comment]
I solved using ready() instead configure(), thanks.

**Comment by banduk** [comment]
@christocracy The plugin requests permission when calling `#start` even with this config on iOS?

```
useSignificantChangesOnly: true,
disableMotionActivityUpdates: true,
locationAuthorizationRequest: 'Any',
disableLocationAuthorizationAlert: true,
```

If yes, how can I track location only using significant changes without asking for permission? Is there a way to do that? 
I was planning to use significant changes until the user clicks in a banner which launch the flow that asks for permissions explaining why the permission is important. Is there a way to do that?
I was wondering if when calling `#ready` the plugin starts collecting significant changes.

Thanks

**Comment by christocracy** [comment]
@ Mauricio 

>if yes, how can I track location only using significant changes without asking for permission? Is there a way to do that? I was planning to use significant changes until the user clicks in a banner which tells that would be better to provide location permissions

You don't get to access the user's location unless *they say* you can.  Yes, you **must** request location permission.  You don't get to secretly track a user *ever*.

In order to use significant-changes API, you *must* grant `Always` authorization.

**Comment by vishgoel007** [comment]
@christocracy  That location permission popup is not showing in my app. What could be the reason behind this?

**Comment by christocracy** [comment]
@vishgoel007 Are you watching the logs?  See wiki "Debugging".

**Comment by vishgoel007** [comment]
Thanks, fixed.

**Comment by vishgoel007** [comment]
@christocracy Can i avoid storing location data in sqlite database which this library is using ?

**Comment by christocracy** [comment]
>Can i avoid storing location data in sqlite database which this library is using ?

@vishgoel007
This **closed** issue is titled "Disable alert for location permission at first launch on app update".  Your question has nothing to do with this issue.

If you don't find an answer to your question by *searching* the issues, post a question to a new issue.
