### ISSUE TITLE
Question: How to prevent Motion & Fitness permission on iOS? disableStopDetection: true doesnt seem to be enough

### ISSUE THREAD

**Issue by agmcleod** [transistorsoft/react-native-background-geolocation#498]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS
* OS version: 11.3
* Device manufacturer / model: iPhone X, iPhone 6s
* React Native version (`react-native -v`): 0.54
* Plugin config

```
BackgroundGeolocation.ready({
  // Geolocation Config
  desiredAccuracy: 0,
  stopTimeout: 1,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: false,
  startOnBoot: false,
  disableMotionActivityUpdates: true
}, (state) => {
  if (!state.enabled) {
    BackgroundGeolocation.start()
  }
})
```

## Expected Behavior
We manage when we ask the user for location permission separately, as part of the UX of the app. However, when i let the app sit in the background, and I opened it, I got the motion & fitness permission request. I then set `disableMotionActivityUpdates: true` and expected behaviour was to no longer see it.

## Actual Behavior
After putting in the new setting, I still received that permission dialog. Is there some other config i'm missing here? Thanks so much!

**Comment by christocracy** [comment]
See docs for [`#ready`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#readydefaultconfig-successfn-failurefn)

⚠️ The #ready method only applies the supplied defaultConfig for the first launch of the app — Forever after, the plugin is going to remember every configuration change you apply at runtime (eg: #setConfig) and reload that same config every time your app boots.

**Comment by christocracy** [comment]
The config `{}` you provide to `#ready` is applied *only at first launch* of your app.

Every boot thereafter, it is *ignored*.

**Comment by agmcleod** [comment]
I did consider that, this has been after delete & reinstalls though. We haven't shipped the feature yet, so I haven't leveraged the `reset: true`

**Comment by christocracy** [comment]
After deleting your app from Simulator, show me XCode logs of your app booting in sim.

**Comment by agmcleod** [comment]
It doesn't seem to reproduce in the simulator. Here are the logs from start up: https://pastebin.com/G2ynnp9u

**Comment by christocracy** [comment]
What version of `react-native-background-fetch` do you have installed?

I see no logs from BackgroundGeolocation.

**Comment by agmcleod** [comment]
2.0.8, which is what this package here: https://github.com/jamesisaac/react-native-background-task#ios recommended. We're using that for fetching data over the network. Though i did realize about a month ago we could remove that, and just use `react-native-background-fetch` directly. Just hasn't been a priority in our backlog.

**Comment by christocracy** [comment]
Don't use `react-native-background-task`.  Get rid of it.  It imports *my* `react-native-background-fetch` for its iOS implementation.  `background-fetch` *is a dependency* of `background-geolocation`.

`react-native-background-fetch` has included an Android implementation since February.  There's no reason to use `react-native-background-task`.

The latest version of [`react-native-background-fetch`](https://www.npmjs.com/package/react-native-background-fetch) is `2.4.3`.  This will get rid of all those warnings you see.

**Comment by agmcleod** [comment]
For sure. Any idea if that might be related to the triggering of motion api somehow?

**Comment by agmcleod** [comment]
Ah yep, i did not see that anywhere. Though I also made changes to where the BackgroundGeolocation.start() is called. I do it in app state open listener, and check if the user has given permission & if the state is not already enabled.

**Comment by agmcleod** [comment]
it looks like disableStopDetection: true has fixed it, i haven't seen it come up for a day now. I think that plus handling the start & stop calls more effectively had led to a more consistent setup. Though I agree we need to consolidate our background libs.
