### ISSUE TITLE
req.body showing a ternary expression on express server

### ISSUE THREAD

**Issue by frperezr** [transistorsoft/react-native-background-geolocation#499]
## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: Mac OS High Sierra
* Device manufacturer / model: Samsung
* React Native version (`react-native -v`): 0.55.4
* Plugin config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        locationUpdateInterval: 5000,
        enableHeadless: true,
        heartbeatInterval: 60,
        url: TRACKER_HOST + await AsyncStorage.getItem('token'),
        params: {
          // Required for tracker.transistorsoft.com
          device: {
            uuid: DeviceInfo.getUniqueID(),
            model: DeviceInfo.getModel(),
            platform: DeviceInfo.getSystemName(),
            manufacturer: DeviceInfo.getManufacturer(),
            version: DeviceInfo.getSystemVersion(),
            framework: 'ReactNative',
          },
        },
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
        foregroundService: true,
        notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
        notificationTitle: 'my app',
        notificationText: 'location service enabled',
        notificationColor: '#ffffff',
        notificationSmallIcon: 'mipmap/ic_launcher',
        notificationLargeIcon: 'mipmap/ic_launcher',
        debug: true,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,

## Expected Behavior

On the express server when i console log the req.body i should expect get an object with the location data
## Actual Behavior

the console.log of the server is being a ternary expression with two strings inside an object.
Also on every post the parameter is_moving is false and sometimes the lat and long are duplicated
## Steps to Reproduce

1. Setup an express server
2. Post to the express server with headers content-type application/url-encoded
3. console.log the req.body

## Debug logs

Here is the log of the req.body

{ '{"location":{"is_moving":false,"uuid":"4928df08-0a84-4991-8f01-XXXXXX","timestamp":"2018-06-07T22:16:53.374Z","odometer":0,"mock":true,"coords":{"latitude":-33.428469,"longitude":-70.606205,"accuracy":10,"speed":10,"heading":90,"altitude":1},"activity":{"type":"still","confidence":100},"battery":{"is_charging":true,"level":1},"extras":{}},"device":{"version":"6.0.1","manufacturer":"samsung","framework":"ReactNative","platform":"Android","model":"SM-J510MN","uuid":"4849bXXXXXXXX"}}': '' }

**Comment by christocracy** [comment]
Server issues are not within the scope of the plugin but do you need `bodyParser`?

https://github.com/transistorsoft/background-geolocation-console/blob/master/server.js#L3

**Comment by frperezr** [comment]
Hi!, thanks for your repsonse.

Im using body parser on the server side, here is my config:

`  const app = express();

  app.use(bodyParser.urlencoded({ extended: false }));
  app.use(bodyParser.json());
  app.use(cors());

  app.post('/api/location/:token', (req, res) => {
    const { token } = req.params;
    console.log(token);
    console.log(req.body);
    return res.sendStatus(200);
  });`

im still getting as a response something like { String : '' } instead of an object with the properties.

im missing something?

Greetings

**Comment by christocracy** [comment]
The plugin *automatically* sets the `Content-Type: 'application/json`.  You don't need to touch this.

The plugin doesn't not post forms.  That's for HTML `<form>` elements.  The plugin posts `JSON`
