### ISSUE TITLE
react native ^0.18.0-rc npm i error

### ISSUE THREAD

**Issue by ButuzGOL** [transistorsoft/react-native-background-geolocation#50]
Have this error on installation 

```
➜  spot git:(master) ✗ npm i react-native-background-geolocation       
npm WARN peerDependencies The peer dependency react-native@>=0.8.0 included from react-native-background-geolocation will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "react-native-background-geolocation"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.15
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native@0.18.0-rc does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-background-geolocation@0.3.4 wants react-native@>=0.8.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/butuzgol/Playground/spot/npm-debug.log
```

**Comment by christocracy** [comment]
Perhaps npm doesn't understand that 0.18.0-rc > 0.8.0.

Try using 0.17.0

On Sunday, January 17, 2016, Slava <notifications@github.com> wrote:

> Have this error on installation
>
> ➜  spot git:(master) ✗ npm i react-native-background-geolocation
> npm WARN peerDependencies The peer dependency react-native@>=0.8.0 included from react-native-background-geolocation will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
> npm ERR! Darwin 15.2.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "react-native-background-geolocation"
> npm ERR! node v4.2.4
> npm ERR! npm  v2.14.15
> npm ERR! code EPEERINVALID
>
> npm ERR! peerinvalid The package react-native@0.18.0-rc does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer react-native-background-geolocation@0.3.4 wants react-native@>=0.8.0
>
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/butuzgol/Playground/spot/npm-debug.log
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/50>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Going to assume this issue is obsolete.  Plugin is at `0.19.0` now.
