### ISSUE TITLE
How do I update headers through headless task? 

### ISSUE THREAD

**Issue by theebi** [transistorsoft/react-native-background-geolocation#501]
Thanks for the awesome library.
I'm planning to buy this library for Android. But while running the debug version I'm having some troubles. I have an app which tracks user location continuously in the background (Android). Im sending token in headers, but token gets expired every month. Is there any way I can reset the headers in the background? Is there a callback or something I can get from headless task when POST request fails?

**Comment by christocracy** [comment]
Simply do this: 
```javascript
BackgroundGeolocation.setConfig({
  headers: {
    foo: 'bar'
  }
});
```

It doesn't matter if you do this in your app component or a `HeadlessTask`
