### ISSUE TITLE
Runtime error java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult 

### ISSUE THREAD

**Issue by yanniser** [transistorsoft/react-native-background-geolocation#504]
## Your Environment
* Plugin version:2.10.1
* Platform: Android
* OS version:
* Device manufacturer / model:Emulator
* React Native version (`react-native -v`):0.50.4
* Plugin config
var options = {
desiredAccuracy: 25,
stationaryRadius: 25,
distanceFilter: 25,
disableElasticity: false,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
locationAuthorizationRequest: 'WhenInUse',
trackingMode: 'location',
locationTimeout: 60,
debug: false,
startOnBoot: false,
stopOnTerminate: false,
activityType: 'AutomotiveNavigation'
};

## Expected Behavior
App should work

## Actual Behavior
App Crashes at runtime 

## Steps to Reproduce

1. Install the app 
2.Launch the app

## Context
This is my app/Build.gradle

dependencies {
    compile (project(':react-native-background-geolocation')){
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile ('com.google.android.gms:play-services-location:11.2.0')
    compile project(':react-native-config')
    compile project(':react-native-device-info')
    compile project(':react-native-fcm')
    compile project(':react-native-firebase-analytics')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-sentry')
    compile project(':react-native-svg')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.google.firebase:firebase-core:10.0.1'
    compile(name: 'tslocationmanager', ext: 'aar')
    //compile ('com.google.android.gms:play-services-base:10.2.6'){
    //    force = true;
    //}
    compile ('com.google.android.gms:play-services-maps:11.2.0'){
        force = true;
    }
    debugCompile 'com.facebook.stetho:stetho:1.5.0'
    debugCompile 'com.facebook.stetho:stetho-okhttp3:1.5.0'
}

apply plugin: "com.google.gms.google-services"

## Debug logs
java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult
 	at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
 	at java.lang.Class.getDexCacheType(Class.java:476)
 	at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166)
 	at java.lang.reflect.Method.getParameterTypes(Method.java:170)
 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
 	at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
 	at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter(RNBackgroundGeolocationModule.java:995)
 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.initializeLocationManager(RNBackgroundGeolocationModule.java:990)
 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostResume(RNBackgroundGeolocationModule.java:259)
 	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:184)
 	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:674)
 	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:709)
 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:975)
 	at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:112)
 	at com.facebook.react.ReactInstanceManager$4$2.run(ReactInstanceManager.java:943)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
 	at android.os.Looper.loop(Looper.java:148)
 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
 	at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.ActivityRecognitionResult" on path: DexPathList[[zip file "/data/app/com.zengularity.NomadMobile-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zengularity.NomadMobile-1/lib/x86, /data/app/com.zengularity.NomadMobile-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
 	... 25 more
 	Suppressed: java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult
 		at dalvik.system.DexFile.defineClassNative(Native Method)
 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
 		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
 		... 28 more
 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.location.ActivityRecognitionResult
 		at java.lang.Class.classForName(Native Method)
 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 		... 27 more
 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by christocracy** [comment]
Means your app is including a version of play-services < the minimum `11.2.0`.  Paste following files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by yanniser** [comment]
the 2 files
**build.gradle**

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        // Google now hosts their latest API dependencies on their own maven  server.
        // React Native will eventually add this to their app template.
        maven {
            url 'https://maven.google.com'
        }
        configurations.all {
            resolutionStrategy {
                force 'com.google.firebase:firebase-messaging:11.8.0'
                force 'com.google.android.gms:play-services-gcm:11.8.0'
                force 'com.google.android.gms:play-services-base:11.8.0'
                force 'com.google.android.gms:play-services-basement:11.8.0'
                force 'com.google.android.gms:play-services-tasks:11.8.0'
                force 'com.google.firebase:firebase-analytics:11.8.0'
            }
        }
    }
}



**app/Build.gradle**

dependencies {
compile (project(':react-native-background-geolocation')){
exclude group: 'com.google.android.gms', module: 'play-services-location'
}
compile ('com.google.android.gms:play-services-location:11.2.0')
compile project(':react-native-config')
compile project(':react-native-device-info')
compile project(':react-native-fcm')
compile project(':react-native-firebase-analytics')
compile project(':react-native-linear-gradient')
compile project(':react-native-sentry')
compile project(':react-native-svg')
compile fileTree(dir: "libs", include: ["*.jar"])
compile "com.facebook.react:react-native:+" // From node_modules
compile 'com.google.firebase:firebase-core:10.0.1'
compile(name: 'tslocationmanager', ext: 'aar')
//compile ('com.google.android.gms:play-services-base:10.2.6'){
// force = true;
//}
compile ('com.google.android.gms:play-services-maps:11.2.0'){
force = true;
}
debugCompile 'com.facebook.stetho:stetho:1.5.0'
debugCompile 'com.facebook.stetho:stetho-okhttp3:1.5.0'
}

apply plugin: "com.google.gms.google-services"

**Comment by christocracy** [comment]
See [Android Setup] and provide the "Gradle Configuration Properties".  This plugin (and many others) are aware of these variables and will align their dependencies accordingly, without the new to `exclude` / `force`.

- [`react-native-firebase-analytics`](https://github.com/evollu/react-native-firebase-analytics/blob/master/android/build.gradle) is **NOT** aware of these "Gradle Properties".
- [`react-native-fcm`](https://github.com/evollu/react-native-fcm/blob/master/android/build.gradle#L3-L6) **IS** aware of the Gradle Properties
- [`react-native-device-info`](https://github.com/rebeccahughes/react-native-device-info/blob/master/android/build.gradle#L3-L6) **IS** aware.

Check all your dependencies to which **are** aware of the Gradle Properties.  For those, you can simply:
```
compile project(':react-native-some-project')
```

**Comment by christocracy** [comment]
And you will have to upgrade `background-geolocation` to latest version `2.12.2` to take advantage of these new "Gradle Properties".

You'll also need to check the specific versions of your other dependencies to make sure those specific versions support Gradle Properties and upgrade accordingly.

**Comment by yanniser** [comment]
ok @christocracy , I will try to do that .... I am a real newbie in the gradle domain so , it will take time 
I will keep you update
thx for your quick answer , it is really nice

**Comment by christocracy** [comment]
Gradle dependency issues are by far the biggest Android issue.  The directions above will assist you greatly with a lot of plugins.

**Comment by sarykemmoun** [comment]
I've upgraded your library to the latest version and I get a crash when launching the app.
`Caused by java.lang.ClassNotFoundException
Didn't find class "com.google.android.gms.location.ActivityRecognitionResult" on path: DexPathList[[zip file "/data/app/com.xxx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx-2/lib/arm, /data/app/com.xxx-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]`
I saw a similar issue that you wrote that it caused by a too low version on googlePlayServicesVersion.
In my case, the version is 15.0.0 and up so it isn't the issue.
(Actually, I use react-native-background-geolocation-android. But I don't see this library now)
 **my android/app/buid.gradle  is:**

```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: "com.android.application"
apply plugin: 'io.fabric'
    repositories {
    maven { url 'https://maven.fabric.io/public' }
    }

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "com.closapp"
        minSdkVersion 19
        multiDexEnabled true
        targetSdkVersion 26
        versionCode 20
        versionName "1.0.12"
        vectorDrawables.useSupportLibrary = true

        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

    signingConfigs {
        release {
            storeFile file("XXX.keystore")
            keyAlias "XXX"
            storePassword '$8ypB44+,88{;2w.7]7}73.Awve   7111 bkFb('
            keyPassword '$8ypB44+,88{;2w.7]7}73.Awve   7111 bkFb('
        }
    }
    dexOptions {
      jumboMode true
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

repositories {
    flatDir {
        dirs "../../node_modules/react-native-background-geolocation-android/android/libs"
    }
}

dependencies {
    compile project(':react-native-background-fetch')
    compile project(':react-native-fabric')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-android-location-services-dialog-box')
    compile project(':react-native-i18n')
    
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile(project(':react-native-background-geolocation-android')) {
        exclude group: 'com.squareup.okhttp3'
    }
    compile ('com.squareup.okhttp3:okhttp:3.4.1') 
    compile project(':react-native-fetch-blob')
    compile project(':react-native-vector-icons')
    
    compile project(':react-native-fcm')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.1.0"
    compile "com.google.firebase:firebase-core:15.0.2"
    compile 'com.google.firebase:firebase-messaging:15.0.2'
    compile 'com.google.android.gms:play-services-maps:15.0.0'
    compile 'com.google.android.gms:play-services-base:15.0.0'
    compile ("com.google.android.gms:play-services-maps:15.0.0") {
        force = true;
    } 
    compile "com.google.android.gms:play-services-gcm:15.0.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.facebook.fresco:animated-gif:1.0.1'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
     transitive = true;
    }
}


task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
apply plugin: "com.google.gms.google-services"

```
**My android/build.grade:**

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
                google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.0.0'
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven { url "https://maven.google.com" }
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
           url "$rootDir/../node_modules/react-native-background-geolocation-android/android/libs"
       }
       maven {
           url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
       }
    }
}

```
Thanks!

**Comment by christocracy** [comment]
@sarykemmoun see this comment https://github.com/transistorsoft/react-native-background-geolocation/issues/504#issuecomment-396976363.  Implement the Gradle Properties and apply them in your app/build.gradle

**Comment by sarykemmoun** [comment]
I'll check it.
Just to make sure: this guide is also for react-native-background-geolocation-**android**?

**Comment by sarykemmoun** [comment]
I don't see react-native-background-geolocation-android anymore, and npm install fails to me with
```
ssh://git@github.com/transistorsoft/react-native-background-geolocation-android.git
13 silly fetchPackageMetaData ERROR: Repository not found.
13 silly fetchPackageMetaData fatal: Could not read from remote repository.
```
I wonder if this library still exists.

**Comment by christocracy** [comment]
@sarykemmoun Perhaps your company was removed from private repo for not paying the yearly maintenance fee?
