### ISSUE TITLE
Android app sometimes crashes with `Listener must not be null`

### ISSUE THREAD

**Issue by macrozone** [transistorsoft/react-native-background-geolocation#505]
## Your Environment
* Plugin version: 2.12.0-beta.15
* Platform: Android
* OS version: 7
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior

should not crash

## Actual Behavior

crashes sometimes. Probably when going back to the app from background

## Steps to Reproduce

We have this on staging builds. It's probably related to `BackgroundGeolocation.watchPosition`

## Context

watching the position while the app is in the foreground with `BackgroundGeolocation.watchPosition`

## Debug logs

Crashlog:

```
java.lang.NullPointerException: Listener must not be null
  at com.google.android.gms.common.internal.zzbq.checkNotNull
  at com.google.android.gms.common.api.internal.zzcm.zzb
  at com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates
  at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.h
  at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.a
  at com.transistorsoft.locationmanager.location.TSWatchPositionRequest$1.onPermissionGranted
  at com.transistorsoft.locationmanager.util.b.a
  at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.a
  at com.transistorsoft.locationmanager.location.TSLocationManager.watchPosition
  at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$3.run
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
  at java.lang.Thread.run(Thread.java:764)
```

Under which conditions may this error happen?

**Comment by christocracy** [comment]
How do I reproduce this?

**Comment by macrozone** [comment]
I can't reproduce it locally, it only occures on release builds after some time. What happens at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.h that could lead to this null pointer exception? Any idea?

**Comment by christocracy** [comment]
```java
private void startUpdatingLocation() {
        TSConfig config = TSConfig.getInstance(context);
        if (!Settings.isValid(context)) { return; }

        if (mLocationCallback != null) {
            stop();
        }

        mLocationCallback = new LocationCallback() {
            @Override public void onLocationResult(LocationResult result) {
                StringBuffer buffer = new StringBuffer();
                buffer.append(TSLog.header("WatchPositionRequest"));
                Location location = result.getLastLocation();
                long age = LocationService.locationAge(location);
                buffer.append(TSLog.boxRow(TSLog.ICON_PIN + location.toString() + ", age: " + age + "ms" + ", time: " + location.getTime()));
                EventBus.getDefault().post(new WatchPositionResult(result.getLastLocation()));
                TSLog.logger.debug(buffer.toString());
            }
        };
        LocationRequest request = LocationRequest.create();
        request.setPriority(config.getDesiredAccuracy());
        request.setInterval(this.interval);
        request.setFastestInterval(this.interval);
        request.setSmallestDisplacement(0);
        request.setMaxWaitTime(0);

        FusedLocationProviderClient client = LocationServices.getFusedLocationProviderClient(context);
        try {
            client.requestLocationUpdates(request, mLocationCallback, Looper.getMainLooper());
        } catch (java.lang.SecurityException e) {
            TSLog.logger.error(TSLog.error("SecurityException while attempting to watchPosition: " + e.getMessage()), e);
        }
    }
```

**Comment by christocracy** [comment]
how are you using `#watchPosition`?

**Comment by garyhogarth** [comment]
We are seeing the same error on Android. We are not able to replicate and mainly seems to be happening when the app is switched between background and foreground rapidly. 

> Fatal Exception: java.lang.NullPointerException: Listener must not be null
>        at com.google.android.gms.common.internal.zzbq.zza(Unknown Source:8)
>        at com.google.android.gms.common.api.internal.zzcm.zzb(Unknown Source:2)
>        at com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates(Unknown Source:14)
>        at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.h(Unknown Source:75)
>        at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.a(Unknown Source)
>        at com.transistorsoft.locationmanager.location.TSWatchPositionRequest$1.onPermissionGranted(Unknown Source:42)
>        at com.transistorsoft.locationmanager.util.b.a(Unknown Source:25)
>        at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.a(Unknown Source:7)
>        at com.transistorsoft.locationmanager.location.TSLocationManager.watchPosition(Unknown Source:33)
>        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$3.run(Unknown Source:8)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>        at java.lang.Thread.run(Thread.java:764)

We observe the apps state change using React Native's AppState.

`AppState.addEventListener('change', () => {});`

**On entering active mode (and after initial setup)** 
We check the current state of Background geolocation, stop it if it is running and then run watchPosition in the foreground. We are using watch position as we want greater control over frequency of checks (and due to iOS movement radius).

Code is similar (not identical) to below. I have cleaned and compacted things up for here.

```
BackgroundGeolocation.getState((state) => {
  if (state.enabled) {
    // Stop BG location and start watch position
    BackgroundGeolocation.stop(() => { 
      BackgroundGeolocation.watchPosition(locationChangeFunction, locationErrorFunction, { interval: 500, persist: true, desiredAccuracy: 0 });
    });
  } else {
    // Just start watch position
    BackgroundGeolocation.watchPosition(locationChangeFunction, locationErrorFunction, { interval: 500, persist: true, desiredAccuracy: 0 });
  }
});
```

**On entering background mode** 
Start BG location and stop watching the position
```
BackgroundGeolocation.getState((state) => {
  if (!state.enabled) {
    // Start BG location and stop watch position
    BackgroundGeolocation.start(() => { 
      BackgroundGeolocation.stopWatchPosition();
    });
  } else {
    // Just stop watch position
    BackgroundGeolocation.stopWatchPosition();
  }
});
```

**Comment by vincenzovitale** [comment]
Is mLocationCallback set to null somewhere else?
Looks like a synchronisation issue.

**Comment by macrozone** [comment]
I just disabled `watchPosition` in my case, because it is not strictly needed in our app

**Comment by macrozone** [comment]
changelog mentions that this issue is fixed, so i close it for now
