### ISSUE TITLE
Include the location provider in the location object

### ISSUE THREAD

**Issue by vincenzovitale** [transistorsoft/react-native-background-geolocation#506]
This is more an enhancement request for including the provider the location is coming from. 
For some scenarios some providers are not good enough (e.g. network while driving), that would allow more meaningful messages to the users.

## Your Environment
* Plugin version: 2.12.1
* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.51.0
* Plugin config

## Expected Behavior
Getting the location provider include in the returned location (i.e. gps, wifi, network).

## Actual Behavior
At the moment the provider which has been used to get the location is not supported

## Steps to Reproduce
N/A

## Context
N/A

## Debug logs
N/A

**Comment by christocracy** [comment]
Not possible with play-services [`FusedLocationProviderClient`](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient).  This location client *fuses* all available providers together to provide locations.

The only way you can determine GPS vs Wifi vs Cellular is by the accuracy.

eg: 
- GPS typically < 10 meters
- Wifi: ~40-100 meters
- Cellular: ~1000+ meters

**Comment by christocracy** [comment]
And iOS absolutely does not tell you this information.

**Comment by vincenzovitale** [comment]
Ah ok, thanks I see. 
At least for Android, I wrongly assumed that the Location provided by the FusedLocationProviderClient had the original provider available via get Provider but I'm now reading that it always return "fused", which probably makes sense for such a provider.

Thanks for the fast reply!
