### ISSUE TITLE
Not uploading to server in URL

### ISSUE THREAD

**Issue by cmcaboy** [transistorsoft/react-native-background-geolocation#508]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS or Android
* OS version: Android 8.1.0
* Device manufacturer / model: Google Pixel
* React Native version (`react-native -v`): 0.55.4
* Plugin config
            desiredAccuracy: 100,
            distanceFilter: 100,
            stopTimeout: 5,
            debug: true, 
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,
            startOnBoot: true, 
            url: 'https://us-central1-manhattanmatch-9f9fe.cloudfunctions.net/coords',
            batchSync: false,
            autoSync: true,
            params: { "id" }

## Expected Behavior

I am expecting the location events to be sent to the url in my configuration.

## Actual Behavior

The location events are not getting sent to the url. When I look at the url value in the state parameter in the ready callback, it shows an empty string. 

## Steps to Reproduce

1. Place the following commands in a component's ComponentDidMount function

```
BackgroundGeolocation.on('location', this.onLocation, this.onError);

        BackgroundGeolocation.ready({
            desiredAccuracy: 100,
            distanceFilter: 100,
            stopTimeout: 5,
            debug: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,   
            startOnBoot: true,   
            url: 'https://us-central1-manhattanmatch-9f9fe.cloudfunctions.net/coords',
            batchSync: false,       
            autoSync: true,      
            params: {  
              "id": this.props.id
            }
          }, (state) => {
            console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
            console.log('state: ',state)

            if (!state.enabled) {
              BackgroundGeolocation.start(function() {
                console.log("- Start success");
              });
            }
          });
```

2. Declare the following functions in the component

```
onLocation = (location) => console.log(' - [event] location: ',location)
onError = (e) => console.log(' - [error] location: ',e);
```

3. Build the app: _react-native run-android_

4. Shake the device for 10-20 seconds. I can see a location event recorded, but there is no attempt to persist.

## Context

This is a simple dating app that uses geolocation to find other users in their area. I am trying to feed the longitude and latitude values to my backend where my geolocation logic will reside.

## Debug logs

The "adb logcat -s TSLocationManager" command prints very little output.

```
C:\Users\cmcaboy\Dropbox\GitHub\react\ManhattanMatch>adb logcat -s TSLocationManager
--------- beginning of crash
--------- beginning of system
--------- beginning of main
06-19 06:26:53.212 15030 15467 I TSLocationManager: - Enable: true ΓåÆ true, trackingMode: 1
```

Here is the output of my state variable on the ready callback function:

```
'state: ', { odometer: 24826.47265625,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   schedulerEnabled: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   enabled: true,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   triggerActivities: 'in_vehicle, on_bicycle, on_foot, running, walking',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   stopTimeout: 5,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   stopOnTerminate: true,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   stationaryRadius: 25,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   startOnBoot: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   schedule: [],
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   persist: true,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   trackingMode: 1,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   params: {},
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   notificationTitle: '',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   forceReloadOnLocationChange: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   notificationPriority: 0,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   forceReloadOnBoot: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   isFirstBoot: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   locationTimeout: 60,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   extras: {},
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   notificationSmallIcon: '',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   locationUpdateInterval: 1000,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   distanceFilter: 10,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   forceReloadOnGeofence: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   notificationText: 'Location Service activated',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   forceReloadOnMotionChange: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   stopOnStationary: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   stopAfterElapsedMinutes: 0,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   forceReloadOnSchedule: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   logMaxDays: 3,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   activityRecognitionInterval: 10000,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   deferTime: 0,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   fastestLocationUpdateInterval: 10000,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   elasticityMultiplier: 1,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   headlessJobService: '',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   allowIdenticalLocations: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   heartbeatInterval: -1,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   geofenceInitialTriggerEntry: true,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   autoSyncThreshold: 0,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   geofenceTemplate: '',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   batchSync: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   disableStopDetection: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   method: 'POST',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   disableElasticity: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   debug: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   locationsOrderDirection: 'ASC',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   notificationLargeIcon: '',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   desiredOdometerAccuracy: 100,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   foregroundService: true,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   geofenceProximityRadius: 1000,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   autoSync: true,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   headers: {},
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   maxDaysToPersist: 1,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   httpRootProperty: 'location',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   httpTimeout: 60000,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   desiredAccuracy: 100,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   isMoving: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   locationTemplate: '',
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   **url: '',**
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   logLevel: 0,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   maxBatchSize: -1,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   maxRecordsToPersist: -1,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   minimumActivityRecognitionConfidence: 75,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   enableHeadless: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   forceReloadOnHeartbeat: false,
06-19 06:01:33.901 10923 11214 I ReactNativeJS:   notificationColor: '' }
```

**Comment by cmcaboy** [comment]
Here is a bit more info

### **build.gradle**

_buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:4.0.1'
        //classpath 'com.google.gms:google-services:3.1.2'

    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}

ext {
    compileSdkVersion   = 26
    targetSdkVersion    = 26
    buildToolsVersion   = "26.0.2"
    supportLibVersion   = "27.1.1"
    googlePlayServicesVersion = "15.0.1"
}_

### **app level build.gradle**

_apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

project.ext.vectoricons = [
    iconFontNames: [ 'MaterialIcons.ttf', 'IoniIcons.ttf', 'FontAwesome.ttf' ] // Name of the font files you want to copy
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.compileSdkVersion

    defaultConfig {
        applicationId "com.manhattanmatch"
        minSdkVersion 16
        targetSdkVersion rootProject.targetSdkVersion
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    buildToolsVersion '27.0.3'
}

dependencies {
    implementation project(':react-native-firebase')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-fbsdk')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'com.android.support:cardview-v7:26'
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-background-geolocation')
    implementation project(':react-native-background-fetch')
    implementation "com.android.support:appcompat-v7:$rootProject.supportLibVersion"

    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation 'com.google.firebase:firebase-core:15.0.2'
    implementation 'com.google.firebase:firebase-firestore:17.0.1'
    implementation 'com.google.firebase:firebase-auth:16.0.1'
    implementation "com.google.firebase:firebase-storage:15.0.2"

    implementation project(':react-native-fetch-blob')
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'_

**### MainApplication.java**

_package com.manhattanmatch;

import android.app.Application;

import com.facebook.FacebookSdk;
import com.facebook.CallbackManager;
import com.facebook.appevents.AppEventsLogger;
import com.facebook.react.ReactApplication;
import com.RNFetchBlob.RNFetchBlobPackage;
import com.imagepicker.ImagePickerPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.firestore.RNFirebaseFirestorePackage;
import io.invertase.firebase.storage.RNFirebaseStoragePackage;



import java.util.Arrays;
import java.util.List;

**import com.transistorsoft.rnbackgroundgeolocation.*;
import com.transistorsoft.rnbackgroundfetch.RNBackgroundFetchPackage;**

public class MainApplication extends Application implements ReactApplication {

  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RNFetchBlobPackage(),
            **new RNBackgroundGeolocation(),**
            new RNFirebasePackage(),
            new RNFirebaseAuthPackage(), 
            new RNFirebaseFirestorePackage(),
            new RNFirebaseStoragePackage(),
            **new RNBackgroundFetchPackage(),**
            new ImagePickerPackage(),
            new VectorIconsPackage(),
            new FBSDKPackage(mCallbackManager)
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    AppEventsLogger.activateApp(this);
    SoLoader.init(this, /* native exopackage */ false);
  }
}_

**### settings.gradle**

_rootProject.name = 'ManhattanMatch'
include ':react-native-fetch-blob'
project(':react-native-fetch-blob').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fetch-blob/android')
**include ':react-native-background-geolocation'
project(':react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-geolocation/android')**
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
**include ':react-native-background-fetch'
project(':react-native-background-fetch').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-fetch/android')**
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-fbsdk'
project(':react-native-fbsdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbsdk/android')

include ':app'_

**Comment by cmcaboy** [comment]
Disregard.... I looked back through the documentation and saw the note on the ready function and the reset property. After setting that property to true, my server began receiving requests.

**Comment by christocracy** [comment]
The `#ready` method consumes the supplied config **only at first launch of the app on that device**.  

While developing, if you *change* a config param *after* first launch, the plugin ignores the `{}` provided to `#ready`.  The  plugin persists all config changed at run-time via `#setConfig`.  The next time the plugin launches, it will automatically load the last-known config.

If you supply `reset: true` to `#ready` during development, the plugin will always first reset the configuration to documented defaults (losing any config provided at run-time during last launch) *then* apply your supplied config `{}`.
