### ISSUE TITLE
GoogleMaps not found IOS

### ISSUE THREAD

**Issue by compojoom** [transistorsoft/react-native-background-geolocation#509]
I wanted to experiment with the plugin and ran into issues installing it on ios. Our app users react-native-maps, but we've configured it to also use googleMaps on ios. 

After installing react-native-background-geolocation and running
react-native link ....
we were no longer able to launch the app. The build was failing with GoogleMaps not found 

It turned out that the issue is FRAMEWORK_SEARCH_HEADERS conf added to .xcodeproj

After removing those lines I was able to build. then I just went for the manual installation road with cocoapods and I was able to get our app running again. 

"react-native": "0.55.0",
"react-native-background-geolocation": "^2.12.2",
"react-native-maps": "^0.21.0"

**Comment by christocracy** [comment]
Thanks for the report.  I use react-Native-maps in my SampleApp but with Apple Maps.  I will reproduce and fix.

**Comment by guillermodoghel** [comment]
any news o this?

**Comment by christocracy** [comment]
Yes, react-Native link no longer adds FRAME_SEARCH_PATHS
