### ISSUE TITLE
Method sync callbacks are not called when autoSync is true

### ISSUE THREAD

**Issue by mauron85** [transistorsoft/react-native-background-geolocation#51]
Hi Chris,

just want to point out, that when option autoSync is true and you call method sync in your code, none of callbacks will be called.

**Comment by christocracy** [comment]
Thanks, I'll check it out.

You're in react world, now?

**Comment by mauron85** [comment]
:-D kind of

**Comment by mauron85** [comment]
Seems like error was on my server side, not sending any response. Sorry for false report. Closing.

**Comment by christocracy** [comment]
The `onHttp` event should fire regardless of http status.  I fixed something on the Cordova facade related to this, not sure if I transmitted the fix here to the React facade, so `onHttp` may not fire on errors -- only success currently.

But thanks, always good to know the problem is on the server :)

**Comment by mauron85** [comment]
I've just realised that the issue is really there, I've just commented out lines that did the manual sync. So it seemed to work ok. When you call sync method second time, it will respond with error: 'A sync is already in progress'/

**Comment by christocracy** [comment]
It should be more intuitive but you really don't need to exec #sync if you
configure autoSync:true



On Monday, January 25, 2016, Marián Hello <notifications@github.com> wrote:

> I've just realised that the issue is really there, I've just commented out
> lines that did the manual sync. So it seemed to work ok. When you call sync
> method second time, it will respond with error: 'A sync is already in
> progress'/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/51#issuecomment-174596075>
> .
>


-- 
Snet form Gmail Mobile

**Comment by mauron85** [comment]
Got your point. I mean, it's not show stopper. You can close it if you want.

**Comment by christocracy** [comment]
The API should be complete and predictable.  TBH, I've never thought to try
it.


On Monday, January 25, 2016, Marián Hello <notifications@github.com> wrote:

> Got your point. I mean, it's not show stopper. You can close it if you
> want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/51#issuecomment-174727978>
> .
>


-- 
Snet form Gmail Mobile

**Comment by mauron85** [comment]
To be honest with you. I only implemented manual sync (with autoSync on) for debug purposes.

**Comment by christocracy** [comment]
I'm on vacation next 10 days so won't be addressed soon

On Monday, January 25, 2016, Marián Hello <notifications@github.com> wrote:

> To be honest with you. I only implemented manual sync (with autoSync on)
> for debug purposes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/51#issuecomment-174729150>
> .
>


-- 
Snet form Gmail Mobile

**Comment by mauron85** [comment]
NP. enjoy ;-)

**Comment by christocracy** [comment]
Is this still an issue?  I couldn't confirm this.
