### ISSUE TITLE
use function for locationTemplate?

### ISSUE THREAD

**Issue by compojoom** [transistorsoft/react-native-background-geolocation#510]
According to the docs we are able to specify a location template
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/http.md

My locationTemplate desire seems to be a little more complicated than what is currently possible. I'm posting the data to firebase realtime database REST API & I want to do a multipath update. I want to structure my data like this:
{
"companyID/userID": {position:..., whatver: ...},
"companyID1/userID": {position:..., whatver: ...},
"companyID2/userID": {position:..., whatver: ...},
"companyID3/userID": {position:..., whatver: ...},
}

If I try to send this as locationTemplate:
locationTemplate: '{"companyId/userID":{ "lat":<%= latitude %>, "lng":<%= longitude %> }}',
The app is no longer able to sync I see a 
⚠️-[TSHttpService doPost:] HTTP ERROR: 400
***
* {
  "error" : "Invalid data; couldn't parse JSON object, array, or value."
}

I played around with this idea:

I noticed that if I do this:
```
      locationTemplate: (() => {
        const test = ['companyID1', 'companyID2'].map(company => {

          return {
            [company]: {
              "userId": {
                "lat": "<%= latitude %>",
                "lng": "<%= longitude %>"
              }
            }
          }
        })

        return JSON.stringify(test.reduce((prev,curr) => {
          return {...prev, ...curr}
        }, {}))
      })(),
```
then the data gets sent to the server

But if I do this:
```
      locationTemplate: (() => {
        const test = ['companyID1', 'companyID2'].map(company => {

          return {
            [company+'/userId']: {

                "lat": "<%= latitude %>",
                "lng": "<%= longitude %>"
              
            }
          }
        })

        return JSON.stringify(test.reduce((prev,curr) => {
          return {...prev, ...curr}
        }, {}))
      })(),
```
I get this error:

> ⚠️-[TSHttpService doPost:] HTTP ERROR: 400
> ***
> * {
>   "error" : "Invalid data; couldn't parse key beginning at 1:2. Key value can't be empty or contain $ # [ ] / or ."
> }
> 

Unfortunately for me to do a multipath update I need to have an / in the key. Otherwise everything at that location gets overwritten. 
Am I missing something? Is there a solution to this the way I'm trying to do it?

**Comment by compojoom** [comment]
Also I noticed that setting method: "PATCH", the plugin seems to behave as sending POST. In our case this leads to new entries appended to the collection, instead of updating the specified path.

**Comment by christocracy** [comment]
I will have to make a change to the library to support http-method `PATCH`

**Comment by christocracy** [comment]
Android should support method `PATCH` currently.  Only iOS requires a slight modification.  This fix will first appear in the plugin's private repo (customers only).  It will appear here in the public repo when the next version is released.
