### ISSUE TITLE
Question: IOS 11 blue bar of shame :)

### ISSUE THREAD

**Issue by compojoom** [transistorsoft/react-native-background-geolocation#512]
In our app we don't need to share the user's location, unless that user has selected this option. So, when I start the app - I check whether or not the user wants to share his location and if he doesn't I do:
      BackgroundGeolocation.removeListeners()

      BackgroundGeolocation.stop(() => {
        console.log('turned offf')

      })

in XCode I see this:
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager stop] 
╚═══════════════════════════════════════════════════════════
🔴-[TSGeofenceManager stop] 
🔴-[TSGeofenceManager stopMonitoringGeofences] 
🔴-[TSLocationManager stopUpdatingLocation] 
🔴-[TSLocationManager stopMonitoringBackgroundFetch] BackgroundFetch: OFF
🔴-[TSLocationManager stopMonitoringSignificantLocationChanges] 

but when I switch to a different app I see a blue bar that tells to the user "AppX is using your location" - which is not true.  This only happens when the user selected the permission "when in use". If the user selects "always", than this blue bar doesn't appear. 

Is this normal? What are my options here? For 99% of our users we need just "when in use" permissions & I don't want our app to trigger the blue bar...

**Comment by christocracy** [comment]
The plugin is not responsible.  You are using some *other* component which is using location-services.  Eg:  a map component.

Btw, you don't need to `#removeListeners`.  Think of event-listeners like speakers attached to a stereo system.  `#start` / `#stop` is the power button.

When you turn your stereo off, you just toggle the power button **off** (ie: `#stop`).  You don't disconnect your speaker wires as well.

**Comment by compojoom** [comment]
ok, point taken on the removeListeners.

About the blue bar - we've been using the default navigator.geolocation to watch the user's position. We never had the blue bar up until we added react-native-background-geolocation. 

I'll try to investigate further and see if you are right.

**Comment by christocracy** [comment]
You need no other 3rd party location module in addition to this plugin.  This plugin will do everything you require.

**Comment by compojoom** [comment]
Yep, Yep. I know… We'll switch everything once we get it running the way we need :)

**Comment by compojoom** [comment]
just wanted to confirm for others. You are right @christocracy . Our use of geolocation.watchPosition was triggering the bar.
