### ISSUE TITLE
App Visibly Opening Randomly from Background

### ISSUE THREAD

**Issue by luskin** [transistorsoft/react-native-background-geolocation#513]
## Your Environment
* Plugin version: 2.12.0-beta.4
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Samsung S7
* React Native version (`react-native -v`): 0.55
* Plugin config

```
  // Background Fetch
  BackgroundFetch.configure(
    {
      minimumFetchInterval: 15,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true
    },
    async () => {
      console.log('- BackgroundFetch start')
      try {
        Log(`Background Fetching _(in callback)_ to API Url: ${Config.BoltAPIUrl}`, ':satellite_antenna:')
        let location = await BackgroundGeolocation.getCurrentPosition({
          persist: true,
          samples: 1,
          extras: { context: 'background-fetch-position-callback' }
        })
        console.log('- BackgroundFetch current position: ', location)
      } catch (e) {
        ErrorHandler(e)
      }

      BackgroundFetch.finish(BackgroundFetch.FETCH_RESULT_NEW_DATA)
    },
    error => {}
  )

  BackgroundGeolocation.ready(
    {
      reset: true,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      foregroundService: true,
      autoSync: true,
      url: `${Config.BoltAPIUrl}/user/${userKey}/location`,
      stopOnTerminate: false,
      startOnBoot: true,
      distanceFilter: 50,
      heartbeatInterval: 60,
      enabledHeadless: true,
      allowIdenticalLocations: true,
      params: {
        device: {
          uuid: DeviceInfo.getUniqueID(),
          model: DeviceInfo.getModel(),
          platform: DeviceInfo.getSystemName(),
          manufacturer: DeviceInfo.getManufacturer(),
          version: DeviceInfo.getSystemVersion(),
          framework: 'ReactNative'
        }
      },
      maxDaysToPersist: 7,

      // Android Always On Location Notification Title/Text
      notificationTitle: 'Bolt Driver',
      notificationText: 'Keep app open for dispatches'
    },
    state => {
      console.log('[LOCATION]: State is', state)
      if (!state.enabled) {
        BackgroundGeolocation.start(() => {
          Log('Started Location Tracking', ':round_pushpin:')
          console.log("[LOCATION]: Began tracking because it wasn't started")
        })
      } else {
        console.log('[LOCATION]: Began tracking')
      }
    }
  )
```

## Expected Behavior
The app should not visibly open the app randomly from the background.

## Actual Behavior
This could potentially not be an issue with RNBackgroundGeolocation but it seems quite coincidental since the only background tasks on our app is this package. Many of our drivers on Android are complaining that our app will randomly open up from the background on their phones. i.e. "I was watching youtube on my phone and all of sudden your app popped open". Is this known behavior? I have not been able to recreate this from our test devices but it's clearly affecting a decent number of our drivers. @christocracy anything you can think of? Thanks.

**Comment by christocracy** [comment]
The plugin only does that if you’ve configured one of the forceReload options.

Can you reproduce it and provide logs?

**Comment by luskin** [comment]
Unfortunately I cannot reproduce it myself, only being told this by our network of drivers using the app (we just launched a new version with RNGeo and RNBackgroundFetch and the problem has started since then). We are not using `forceReload` but is it possible that the BackgroundFetch or headless task is responsible for this behavior?

**Comment by christocracy** [comment]
Only forceReload can cause this

**Comment by christocracy** [comment]
Why are you still using a beta version of 2.12.0?  2.12.2 has been released

**Comment by luskin** [comment]
That's what was most recent when we launched the app. I will update now.

**Comment by luskin** [comment]
@christocracy we do not use forceReload anywhere in our app, there must be something else that is causing this behavior. It would make sense it's coming from RNGeo since it's our only background running tasks (at least that we implemented) - is there anything else that could be causing this between the headless tasks, the background tracker, any specific android settings... etc

**Comment by luskin** [comment]
Turned out to be the `react-native-navigation` package that was causing this.

**Comment by kishanj918** [comment]
hello @luskin ,
can you please explain / show code, how you configured android headless task for background location in react-native-navigation?

**Comment by luskin** [comment]
Move your launch logic to a `start()` function wherever you'd like and make your entry point as shown below. Keep in mind this is for `react-native-navigation V1` - our company is in the process of upgrading to `V2` which looks to have the fix built in on app launch:

```
// Headless task will open the app UI with react-native-navigation
// so we need to make sure to only launch the app when it's actually launched
Navigation.isAppLaunched().then(appLaunched => {
  if (appLaunched) {
    startApp()
  }
  new NativeEventsReceiver().appLaunched(startApp)
})

// (Android) Background Notification/Message Handler
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => backgroundNotificationHandler)

// (Android) Background Fetch Headless Task
BackgroundFetch.registerHeadlessTask(backgroundNotificationHandler)
```

```
export const backgroundNotificationHandler = async () => {
  await fetchCurrentLocation()
  return Promise.resolve()
}
```
