### ISSUE TITLE
Add support for CRNA and Expo

### ISSUE THREAD

**Issue by kevinzhangftw** [transistorsoft/react-native-background-geolocation#516]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior
This package is still using react native link! Can we have this package so that it works with CRNA? Reason being expo is taking forever to implement bg location and ejecting out CRNA is really not ideal and slows down development quite a bit. 

## Steps to Reproduce
N/A

**Comment by christocracy** [comment]
>This package is still using react native link

Yes, what's wrong with that?

>Can we have this package so that it works with CRNA? 

I don't understand.  I'm really not interested in Expo or CRNA.

**Comment by christocracy** [comment]
My suggestion is you dump Expo.
