### ISSUE TITLE
Components reload when notification bar icon clicked

### ISSUE THREAD

**Issue by amirey** [transistorsoft/react-native-background-geolocation#517]
I know there's no way to hide the notification bar icon in Android anymore. By default, when the app is put in the background while tracking, and then reloaded, components are being reloaded.

Is there a way to control its functionality, i.e. not reload components when the notification bar icon is tapped?

## Your Environment
* Plugin version: 2.12.0
* Platform: Android
* OS version: 8.1
* Device manufacturer / model: Nexus 5X
* React Native version (`react-native -v`): 0.55
* Plugin config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
      distanceFilter: 0,
      locationUpdateInterval: 5000,
      fastestLocationUpdateInterval: 5000,
      notificationText: "Tap reloads all components",
      allowIdenticalLocations: true,

## Expected Behavior
App should come back to foreground, map shows markers accumulated before and while app was in the background.

## Actual Behavior
Component loads again, calling the constructor and previous markers disappeared.

## Context
Show the geo-location of the device over time, before and while the app was in the background.

**Comment by christocracy** [comment]
This is confirmed.  Looking into it.

**Comment by amirey** [comment]
Any development on this issue, @christocracy ?

**Comment by christocracy** [comment]
Actually I tried this a bit last week and I found it actually doesn’t restart the MainActivity.  I will have to investigate more on other devices.

**Comment by EOdOW** [comment]
Hi @christocracy any details about this? Thanks.

**Comment by christocracy** [comment]
No update
