### ISSUE TITLE
Location Post schema when batchSync is true

### ISSUE THREAD

**Issue by mauron85** [transistorsoft/react-native-background-geolocation#52]
Hi Chris,
location prop seems to be Array instead of object.

According to documentation about HTTP Post Schema, I would expect that in case of batchSync true the schema will look like:

```
[
{
    "location": {
        "coords": {
            "latitude":   [Float],
            "longitude":  [Float]
            "accuracy":   [Float]
            "speed":      [Float],
            "heading":    [Float],
            "altitude":   [Float]
        },
        "activity": {                
            "type": [still|on_foot|walking|running|in_vehicle|on_bicycle],
            "confidence": [0-100%]
        },
        "battery": {
            "level": [Float],
            "is_charging": [Boolean]
        },
        "timestamp": [ISO-8601 UTC], // eg:  "2015-05-05T04:31:54Z"
        "is_moving": [Boolean]       // <-- The motion-state when location was recorded.
    }
}
]
```

But in reality it is:
```
[
{
    "location": [{
        "coords": {
            "latitude":   [Float],
            "longitude":  [Float]
            "accuracy":   [Float]
            "speed":      [Float],
            "heading":    [Float],
            "altitude":   [Float]
        },
        "activity": {                
            "type": [still|on_foot|walking|running|in_vehicle|on_bicycle],
            "confidence": [0-100%]
        },
        "battery": {
            "level": [Float],
            "is_charging": [Boolean]
        },
        "timestamp": [ISO-8601 UTC], // eg:  "2015-05-05T04:31:54Z"
        "is_moving": [Boolean]       // <-- The motion-state when location was recorded.
    }]
} 
]
```

**Comment by christocracy** [comment]
Thanks, will check it out.

On Sunday, January 24, 2016, Marián Hello <notifications@github.com> wrote:

> According to documentation about HTTP Post Schema, I would expect that in
> case of batchSync true the schema will look like:
>
> [
> {
>     "location": {
>         "coords": {
>             "latitude":   [Float],
>             "longitude":  [Float]
>             "accuracy":   [Float]
>             "speed":      [Float],
>             "heading":    [Float],
>             "altitude":   [Float]
>         },
>         "activity": {
>             "type": [still|on_foot|walking|running|in_vehicle|on_bicycle],
>             "confidence": [0-100%]
>         },
>         "battery": {
>             "level": [Float],
>             "is_charging": [Boolean]
>         },
>         "timestamp": [ISO-8601 UTC], // eg:  "2015-05-05T04:31:54Z"
>         "is_moving": [Boolean]       // <-- The motion-state when location was recorded
>     }
> }
> ]
>
> But in reality it is:
>
> [
> {
>     "location": [{
>         "coords": {
>             "latitude":   [Float],
>             "longitude":  [Float]
>             "accuracy":   [Float]
>             "speed":      [Float],
>             "heading":    [Float],
>             "altitude":   [Float]
>         },
>         "activity": {
>             "type": [still|on_foot|walking|running|in_vehicle|on_bicycle],
>             "confidence": [0-100%]
>         },
>         "battery": {
>             "level": [Float],
>             "is_charging": [Boolean]
>         },
>         "timestamp": [ISO-8601 UTC], // eg:  "2015-05-05T04:31:54Z"
>         "is_moving": [Boolean]       // <-- The motion-state when location was recorded
>     }]
> }
> ]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/52>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
This is operating as intended.

The root key containing the data is `location`, regardless of `batchSync`.

**batchSync: true**
```
{
  location: [{Location}, {Location}, ..., {Location}]
}

**batchSync: false**
```
{
  location: {Location}
}
```

```
eg:
{
 	"location": [{
 		"coords": {
 			"speed": 32.72,
 			"longitude": -122.18921084,
 			"latitude": 37.40684142,
 			"accuracy": 5,
 			"heading": 314.65,
 			"altitude": 0,
 			"altitudeAccuracy": -1
 		},
 		"is_heartbeat": false,
 		"is_moving": true,
 		"uuid": "12376330-7A08-4473-B889-02A874D15115",
 		"activity": {
 			"type": "unknown",
 			"confidence": 100
 		},
 		"battery": {
 			"level": -1,
 			"is_charging": 0
 		},
 		"timestamp": "2016-01-24T22:48:42.181Z"
 	}, {
 		"coords": {
 			"speed": 32.48,
 			"longitude": -122.19065295,
 			"latitude": 37.40776758,
 			"accuracy": 5,
 			"heading": 304.45,
 			"altitude": 0,
 			"altitudeAccuracy": -1
 		},
 		"is_heartbeat": false,
 		"is_moving": true,
 		"uuid": "9C708C5C-0CF8-40D6-95E6-E1DE3B23696A",
 		"activity": {
 			"type": "unknown",
 			"confidence": 100
 		},
 		"battery": {
 			"level": -1,
 			"is_charging": 0
 		},
 		"timestamp": "2016-01-24T22:48:47.189Z"
 	}],
 	"device": {
 		"platform": "iPhone OS",
 		"manufacturer": "Apple",
 		"model": "Simulator",
 		"version": "9.2",
 		"uuid": "78551C15-5791-44B8-9BD6-D91F70ABD54D"
 	}
 }
```
