### ISSUE TITLE
multiple okhttp3 error 

### ISSUE THREAD

**Issue by gitsuraj** [transistorsoft/react-native-background-geolocation#524]
## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: Oreo
* Device manufacturer / model: Samgsung SM-G930S
* React Native version (`react-native -v`):  0.55.4
* Plugin config

## Expected Behavior

Should run smoothly 

## Actual Behavior

Conflict with okhttp3 dependency

## Steps to Reproduce

1. Complete all setup and run
2.
3.
4.

## Context

After updating all the configuration I ended up with multiple dependencies as my Expo detached application already contains 

implementation 'com.squareup.okhttp3:okhttp-ws:3.4.1'

I managed to run my application by commenting out 
 compile 'com.squareup.okhttp3:okhttp:3.10.0'
line in react-native-background-geolocation  build.gradle but obviously it's not a proper solution. Any idea how can I manage this issue.

**Comment by christocracy** [comment]
Expo is more trouble than it’s worth when you need to do anything outside their walled garden.

**Comment by mschipperheyn** [comment]
That's not really helpful. I used the same solution but it's not a good one, bc with every node_modules refresh, you have to do it again.
