### ISSUE TITLE
notificationSmallIcon does not appear

### ISSUE THREAD

**Issue by fabiocastrodev** [transistorsoft/react-native-background-geolocation#526]
## Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: 7.0 - 5.1.1
* Device manufacturer / model: Moto G - OS Version: 7.0 and Samsumg Galaxy J1 mini - OS Version 5.1.1
* React Native version: 0.55.4
* Plugin config: 
```
const config = {
  reset: true,

  url: url,
  autoSync: true,
  batchSync: false,

  startOnBoot: false,
  stopOnTerminate: false,

  foregroundService: true,
  notificationTitle: 'Monitorando viagem',
  notificationText: 'Serviço de geolocalização ativo',
  notificationSmallIcon: 'mipmap/ic_launcher',
  notificationLargeIcon: 'mipmap/ic_launcher',
  notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,

  stopTimeout: 1,
  distanceFilter: 2,
  desiredAccuracy: 0,

  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
}
```

## Expected Behavior
The icon should appear in the notification

## Actual Behavior
Small icon does not appear
http://prntscr.com/k67mpu

## Context
The small icon does not appear by specifying it in the configuration or not, notice that the large icon appears and the file is the same

**Comment by christocracy** [comment]
It does appear, you're just not providing a logo with transparency, eg:

![](https://dl.dropboxusercontent.com/s/fczd1lm4ez15dta/Screenshot%202018-07-23%2013.04.59.png?dl=1)
