### ISSUE TITLE
Android Fails to Track Location after App Closed and Reopened

### ISSUE THREAD

**Issue by JackCharb** [transistorsoft/react-native-background-geolocation#527]
## Environment
* Plugin version: 2.12.2
* Platform: Android
* React Native version: 0.55.4

## Expected Behavior
The app should begin tracking location again once the app is reopened.

## Actual Behavior
Location stops being tracked when the app is close (expected) but does not resume when it is reopened.

## Steps to Reproduce

1. Close application
2. Reopen application

## Cofiguration
```javascript
  componentWillMount() {
    // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.on('location', this.onLocation, this.onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.on('motionchange', this.onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.on('activitychange', this.onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.on('providerchange', this.onProviderChange);

    BackgroundGeolocation.ready({
      desiredAccuracy: 10,
      distanceFilter: 10,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: true,
      startOnBoot: false,
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if(!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
  }

  componentWillUnmount() {
    BackgroundGeolocation.removeListeners();
  }
```
My understanding is that the `componentWillMoount()` should call `.ready()` each time the app is reopened, and the configuration will be persisted from the last time the app ran. Once `.ready()` is called it should ultimately also call `.start()` at which point location will be tracked again. Am I missing something here?

**Comment by christocracy** [comment]
`stopOnTerminate` *means* `#stop` on terminate.

The next time the plugin boots, it will boot with `state.enabled == false`.

You must explicitly execute `#start`
