### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by aschambers** [transistorsoft/react-native-background-geolocation#528]
## Your Environment
* Plugin version: 2.12.3-beta.1
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Galaxy S8
* React Native version (`react-native -v`): 0.55.4
* Plugin config

## Expected Behavior

App should not crash on start
## Actual Behavior

App crashes on start
## Steps to Reproduce

1. If I comment out the following in MainApplication.java:
// import com.transistorsoft.rnbackgroundgeolocation.*;
// import com.transistorsoft.rnbackgroundfetch.RNBackgroundFetchPackage;
// new RNBackgroundGeolocation(),
// new RNBackgroundFetchPackage(),
and this code in Android/app/build.gradle file
// compile project(':react-native-background-geolocation-android')
// compile project(':react-native-background-fetch')
the app will not crash
2. If I comment out senderID in pushService.js when using the library (react-native-push-notification), or set requestPermissions: false, app will also not crash on start.
3. (in main build.gradle file)
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        classpath 'com.google.gms:google-services:3.2.1'
    }
    minSdkVersion = 16 
    compileSdkVersion = 26
    targetSdkVersion = 26
    buildToolsVersion = "26.0.2"
    supportLibVersion = "26.1.0"
    playServicesVersion = "11.8.0"
4. gradle-wrapper.properties
    distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

## Context

I'm trying to use this library on Android in conjunction with another library called (react-native-push-notification), and am having trouble. I'd greatly appreciate any help to steer me in the right direction, or steps I'd need to take in order to solve this issue. I'd like to be able to use this library on Android, and be able to send remote push notifications.
## Debug logs

07-14 22:37:49.803 12194 12194 E System  : java.io.FileNotFoundException: File doesn't exist: /system/framework/qcom.fmradio.jar
07-14 22:37:49.803 12194 12194 E System  :      at java.util.zip.ZipFile.<init>(ZipFile.java:212)
07-14 22:37:49.803 12194 12194 E System  :      at java.util.zip.ZipFile.<init>(ZipFile.java:149)
07-14 22:37:49.803 12194 12194 E System  :      at java.util.jar.JarFile.<init>(JarFile.java:160)
07-14 22:37:49.803 12194 12194 E System  :      at java.util.jar.JarFile.<init>(JarFile.java:97)
07-14 22:37:50.083 12256 12256 E libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
07-14 22:37:56.040 12464 12464 E Typeface: Unable to load Family: samsung-sans-num4Lv:null
07-14 22:37:56.076  2876  2876 E audit   : type=1400 audit(1531633076.069:357959): avc:  denied  { read } for  pid=12493 comm="m.facebook.orca" name="vmstat" dev="proc" ino=4026532142 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0 SEPF_SM-G950U1_8.0.0_0007 audit_filtered

**Comment by christocracy** [comment]
Have you searched the issues for similar problem?  Gradle dependency conflicts between multiple packages importing play-services/Firebase dependencies is a very common issue.  Many here are very aware of react-Native-push-notification.

**Comment by christocracy** [comment]
And you should read carefully the setup instructions with regard to the “Gradle Configuration Parameters”.  Implement those exactly as instructed.  *exactly*
