### ISSUE TITLE
Http config not working

### ISSUE THREAD

**Issue by gitsuraj** [transistorsoft/react-native-background-geolocation#531]
## Your Environment
* Plugin version: 2.12.2
* Platform:  Android
* OS version:Oreo
* Device manufacturer / model: Samsung SM-G930S
* React Native version (`react-native -v`): 0.55.2
* Plugin config

## Expected Behavior

Plugin should post location updates to remote url with following setup

      url: 'http://yourserver.com/locations',
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        "X-FOO": "bar"
      },
      params: {               // <-- Optional HTTP params
        "auth_token": "maybe_your_server_authenticates_via_token_YES?"
      }
## Actual Behavior

Api endpoint isn't being called with following config
            startOnBoot: true,
            url:HEART_BEAT,
           headers: {              // <-- Optional HTTP headers
          "Authorization": `bearer ${storeData?storeData.access_token:''}`
        },
        params: {               // <-- Optional HTTP params
           "device":{
             "device_id":Constants.deviceId,
             "device_name":Constants.deviceName,
             "platform":Constants.platform
           }

** onLocation event works though. But I am looking for background implementation as well

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

logcat log
07-25 15:35:47.392 22762-23302/com.rydotechnologies.driverapp I/TSLocationManager: [c.t.l.adapter.TSConfig print] 
    ╔═════════════════════════════════════════════
    ║ TSLocationManager version: 2.12.14 (270)
    ╠═════════════════════════════════════════════
    {
      "activityRecognitionInterval": 10000,
      "allowIdenticalLocations": false,
      "autoSync": true,
      "autoSyncThreshold": 0,
      "batchSync": false,
      "debug": true,
      "deferTime": 0,
      "desiredAccuracy": 0,
      "desiredOdometerAccuracy": 100,
      "disableElasticity": false,
      "disableStopDetection": false,
      "distanceFilter": 10,
      "elasticityMultiplier": 1,
      "enableHeadless": false,
      "extras": {},
      "fastestLocationUpdateInterval": 10000,
      "forceReloadOnBoot": false,
      "forceReloadOnGeofence": false,
      "forceReloadOnHeartbeat": false,
      "forceReloadOnLocationChange": false,
      "forceReloadOnMotionChange": false,
      "forceReloadOnSchedule": false,
      "foregroundService": true,
      "geofenceInitialTriggerEntry": true,
      "geofenceProximityRadius": 1000,
      "geofenceTemplate": "",
      "headers": {
        "Authorization": "bearer undefined"
      },
      "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",
      "heartbeatInterval": -1,
      "httpRootProperty": "location",
      "httpTimeout": 60000,
      "isMoving": false,
      "locationTemplate": "",
      "locationTimeout": 60,
      "locationUpdateInterval": 1000,
      "locationsOrderDirection": "ASC",
      "logLevel": 5,
      "logMaxDays": 3,
      "maxBatchSize": -1,
      "maxDaysToPersist": 1,
      "maxRecordsToPersist": -1,
      "method": "POST",
      "minimumActivityRecognitionConfidence": 75,
      "notificationColor": "",
      "notificationLargeIcon": "",
      "notificationPriority": 0,
      "notificationSmallIcon": "",
      "notificationText": "Location Service activated",
      "notificationTitle": "",
      "params": {
        "device": {
          "platform": {
            "android": {
              "versionCode": 1
            }
          },
          "device_name": "SM-G930S",
          "device_id": "fe889771-9a2c-46a0-ae55-0b9d8f2d1243"
        }
      },
      "persist": true,
      "schedule": [],
      "startOnBoot": true,
      "stationaryRadius": 25,
      "stopAfterElapsedMinutes": 0,
      "stopOnStationary": false,
      "stopOnTerminate": false,
      "stopTimeout": 1,
      "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
      "url": "http:\/\/{{base_url}}\/api\/heartbeat",
      "enabled": true,
      "schedulerEnabled": false,
      "trackingMode": 1,
      "odometer": 0,
      "isFirstBoot": false
    }
    ╔═════════════════════════════════════════════
    ║ DEVICE SENSORS
    ╠═════════════════════════════════════════════
    ╟─ ✅  ACCELEROMETER: {Sensor name="K6DS3TR Acceleration Sensor", vendor="STM", version=1, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.25, minDelay=2000}
    ╟─ ✅  GYROSCOPE: {Sensor name="K6DS3TR Gyroscope Sensor", vendor="STM", version=2, type=4, maxRange=17.453293, resolution=6.1086525E-4, power=6.1, minDelay=2000}
    ╟─ ✅  MAGNETOMETER: {Sensor name="YAS537 Magnetic Sensor", vendor="Yamaha Corporation", version=1, type=2, maxRange=1200.0, resolution=0.1, power=6.0, minDelay=10000}
    ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="SAMSUNG Significant Motion Sensor", vendor="Samsung Inc.", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=-1}
    ╚═════════════════════════════════════════════

**Comment by christocracy** [comment]
Look at the `#url` you're providing the plugin from your `logcat`:

```
"url": "http://{{base_url}}/api/heartbeat",   // <-- base_url?????
```

**Comment by christocracy** [comment]
Yes, but you’re literally providing the text `{{base_url}}`.  It’s not being evaluated to an actual url.

**Comment by gitsuraj** [comment]
Sorry for confusion actual log looks like this 
"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
      "url": "http:\/\/dev.insightdocs.com:8094\/api\/heartbeat",

**Comment by christocracy** [comment]
Now observe `$ adb logcat -s TSLocationManager` while booting the plugin.  The plugin logs every HTTP request / response.

**Comment by gitsuraj** [comment]
0   351   427 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:34:25.901   484   556 I TSLocationManager: 
07-26 11:34:25.901   484   556 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:34:25.901   484   556 I TSLocationManager: ║ License Validation Failure
07-26 11:34:25.901   484   556 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:34:25.901   484   556 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:34:47.377   607   693 I TSLocationManager: 
07-26 11:34:47.377   607   693 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:34:47.377   607   693 I TSLocationManager: ║ License Validation Failure
07-26 11:34:47.377   607   693 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:34:47.377   607   693 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:35:18.787   741   816 I TSLocationManager: 
07-26 11:35:18.787   741   816 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:35:18.787   741   816 I TSLocationManager: ║ License Validation Failure
07-26 11:35:18.787   741   816 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:35:18.787   741   816 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:35:55.703   917   992 I TSLocationManager: 
07-26 11:35:55.703   917   992 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:35:55.703   917   992 I TSLocationManager: ║ License Validation Failure
07-26 11:35:55.703   917   992 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:35:55.703   917   992 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:37:53.659  1067  1143 I TSLocationManager: 
07-26 11:37:53.659  1067  1143 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:37:53.659  1067  1143 I TSLocationManager: ║ License Validation Failure
07-26 11:37:53.659  1067  1143 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:37:53.659  1067  1143 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:38:37.665  1414  1498 I TSLocationManager: 
07-26 11:38:37.665  1414  1498 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:38:37.665  1414  1498 I TSLocationManager: ║ License Validation Failure
07-26 11:38:37.665  1414  1498 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:38:37.665  1414  1498 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:39:00.658  1567  1682 I TSLocationManager: 
07-26 11:39:00.658  1567  1682 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:39:00.658  1567  1682 I TSLocationManager: ║ License Validation Failure
07-26 11:39:00.658  1567  1682 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:39:00.658  1567  1682 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:39:22.931  1763  1849 I TSLocationManager: 
07-26 11:39:22.931  1763  1849 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:39:22.931  1763  1849 I TSLocationManager: ║ License Validation Failure
07-26 11:39:22.931  1763  1849 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:39:22.931  1763  1849 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:39:44.491  1909  1986 I TSLocationManager: 
07-26 11:39:44.491  1909  1986 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:39:44.491  1909  1986 I TSLocationManager: ║ License Validation Failure
07-26 11:39:44.491  1909  1986 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:39:44.491  1909  1986 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:40:06.603  2032  2116 I TSLocationManager: 
07-26 11:40:06.603  2032  2116 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:40:06.603  2032  2116 I TSLocationManager: ║ License Validation Failure
07-26 11:40:06.603  2032  2116 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:40:06.603  2032  2116 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:40:36.916  2873  2983 I TSLocationManager: 
07-26 11:40:36.916  2873  2983 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:40:36.916  2873  2983 I TSLocationManager: ║ License Validation Failure
07-26 11:40:36.916  2873  2983 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:40:36.916  2873  2983 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:40:56.607  3151  3306 I TSLocationManager: 
07-26 11:40:56.607  3151  3306 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:40:56.607  3151  3306 I TSLocationManager: ║ License Validation Failure
07-26 11:40:56.607  3151  3306 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:40:56.607  3151  3306 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:41:13.122  3539  3677 I TSLocationManager: 
07-26 11:41:13.122  3539  3677 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:41:13.122  3539  3677 I TSLocationManager: ║ License Validation Failure
07-26 11:41:13.122  3539  3677 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:41:13.122  3539  3677 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:42:38.392  5694  5856 I TSLocationManager: 
07-26 11:42:38.392  5694  5856 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:42:38.392  5694  5856 I TSLocationManager: ║ License Validation Failure
07-26 11:42:38.392  5694  5856 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:42:38.392  5694  5856 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:43:23.818  6589  6709 I TSLocationManager: 
07-26 11:43:23.818  6589  6709 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:43:23.818  6589  6709 I TSLocationManager: ║ License Validation Failure
07-26 11:43:23.818  6589  6709 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:43:23.818  6589  6709 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:43:55.634  6777  6913 I TSLocationManager: 
07-26 11:43:55.634  6777  6913 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:43:55.634  6777  6913 I TSLocationManager: ║ License Validation Failure
07-26 11:43:55.634  6777  6913 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:43:55.634  6777  6913 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:44:35.937  8066  8171 I TSLocationManager: 
07-26 11:44:35.937  8066  8171 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:44:35.937  8066  8171 I TSLocationManager: ║ License Validation Failure
07-26 11:44:35.937  8066  8171 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:44:35.937  8066  8171 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:47:13.110 10345 10646 I TSLocationManager: 
07-26 11:47:13.110 10345 10646 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:47:13.110 10345 10646 I TSLocationManager: ║ License Validation Failure
07-26 11:47:13.110 10345 10646 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:47:13.110 10345 10646 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:47:34.669 11402 11555 I TSLocationManager: 
07-26 11:47:34.669 11402 11555 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:47:34.669 11402 11555 I TSLocationManager: ║ License Validation Failure
07-26 11:47:34.669 11402 11555 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:47:34.669 11402 11555 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:47:51.282 11671 11750 I TSLocationManager: 
07-26 11:47:51.282 11671 11750 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:47:51.282 11671 11750 I TSLocationManager: ║ License Validation Failure
07-26 11:47:51.282 11671 11750 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:47:51.282 11671 11750 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:48:49.436 13024 13121 I TSLocationManager: 
07-26 11:48:49.436 13024 13121 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:48:49.436 13024 13121 I TSLocationManager: ║ License Validation Failure
07-26 11:48:49.436 13024 13121 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:48:49.436 13024 13121 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:51:06.790 15912 15998 I TSLocationManager: 
07-26 11:51:06.790 15912 15998 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:51:06.790 15912 15998 I TSLocationManager: ║ License Validation Failure
07-26 11:51:06.790 15912 15998 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:51:06.790 15912 15998 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:51:16.201 16129 16211 I TSLocationManager: 
07-26 11:51:16.201 16129 16211 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:51:16.201 16129 16211 I TSLocationManager: ║ License Validation Failure
07-26 11:51:16.201 16129 16211 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:51:16.201 16129 16211 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:51:51.957 16129 16865 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 11:57:04.737 16129 17843 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 11:58:28.087 17955 18052 I TSLocationManager: 
07-26 11:58:28.087 17955 18052 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 11:58:28.087 17955 18052 I TSLocationManager: ║ License Validation Failure
07-26 11:58:28.087 17955 18052 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 11:58:28.087 17955 18052 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 11:58:37.737 17955 18102 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 12:00:18.313 17955 18700 I TSLocationManager: - Enable: false → true, trackingMode: 1
  onLocation(location) {
    this.props.updateApplicationHeartBeat(location.coords);
  }
  onError(error) {
    console.warn("- [event] location error ", error);
   
adb logcat -s TSLocationManager
07-26 12:03:43.740 19555 19673 I TSLocationManager: 
07-26 12:03:43.740 19555 19673 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 12:03:43.740 19555 19673 I TSLocationManager: ║ License Validation Failure
07-26 12:03:43.740 19555 19673 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 12:03:43.740 19555 19673 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 12:03:51.216 19555 19781 I TSLocationManager: - Enable: true → true, trackingMode: 1
                


07-26 12:06:54.371 19555 21568 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 13:46:22.875 10667 10765 I TSLocationManager: 
07-26 13:46:22.875 10667 10765 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 13:46:22.875 10667 10765 I TSLocationManager: ║ License Validation Failure
07-26 13:46:22.875 10667 10765 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 13:46:22.875 10667 10765 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 13:46:43.049 10667 10807 I TSLocationManager: - Enable: true → true, trackingMode: 1
07-26 13:48:09.407 10667 10807 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 13:49:06.241 10667 10807 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 14:06:17.301 10667 12037 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 14:14:01.289 12400 12501 I TSLocationManager: 
07-26 14:14:01.289 12400 12501 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:14:01.289 12400 12501 I TSLocationManager: ║ License Validation Failure
07-26 14:14:01.289 12400 12501 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:14:01.289 12400 12501 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:14:26.556 12590 12663 I TSLocationManager: 
07-26 14:14:26.556 12590 12663 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:14:26.556 12590 12663 I TSLocationManager: ║ License Validation Failure
07-26 14:14:26.556 12590 12663 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:14:26.556 12590 12663 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:15:12.686 12744 12818 I TSLocationManager: 
07-26 14:15:12.686 12744 12818 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:15:12.686 12744 12818 I TSLocationManager: ║ License Validation Failure
07-26 14:15:12.686 12744 12818 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:15:12.686 12744 12818 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:15:35.076 12878 12950 I TSLocationManager: 
07-26 14:15:35.076 12878 12950 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:15:35.076 12878 12950 I TSLocationManager: ║ License Validation Failure
07-26 14:15:35.076 12878 12950 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:15:35.076 12878 12950 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:16:02.734 12999 13084 I TSLocationManager: 
07-26 14:16:02.734 12999 13084 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:16:02.734 12999 13084 I TSLocationManager: ║ License Validation Failure
07-26 14:16:02.734 12999 13084 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:16:02.734 12999 13084 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:16:25.410 13141 13213 I TSLocationManager: 
07-26 14:16:25.410 13141 13213 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:16:25.410 13141 13213 I TSLocationManager: ║ License Validation Failure
07-26 14:16:25.410 13141 13213 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:16:25.410 13141 13213 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:16:53.954 13269 13341 I TSLocationManager: 
07-26 14:16:53.954 13269 13341 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:16:53.954 13269 13341 I TSLocationManager: ║ License Validation Failure
07-26 14:16:53.954 13269 13341 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:16:53.954 13269 13341 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:17:14.369 13386 13462 I TSLocationManager: 
07-26 14:17:14.369 13386 13462 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:17:14.369 13386 13462 I TSLocationManager: ║ License Validation Failure
07-26 14:17:14.369 13386 13462 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:17:14.369 13386 13462 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:17:43.002 13511 13588 I TSLocationManager: 
07-26 14:17:43.002 13511 13588 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:17:43.002 13511 13588 I TSLocationManager: ║ License Validation Failure
07-26 14:17:43.002 13511 13588 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:17:43.002 13511 13588 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:19:56.255 13657 13732 I TSLocationManager: 
07-26 14:19:56.255 13657 13732 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:19:56.255 13657 13732 I TSLocationManager: ║ License Validation Failure
07-26 14:19:56.255 13657 13732 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:19:56.255 13657 13732 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:22:26.317 13833 13920 I TSLocationManager: 
07-26 14:22:26.317 13833 13920 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:22:26.317 13833 13920 I TSLocationManager: ║ License Validation Failure
07-26 14:22:26.317 13833 13920 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:22:26.317 13833 13920 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:22:55.573 13975 14049 I TSLocationManager: 
07-26 14:22:55.573 13975 14049 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:22:55.573 13975 14049 I TSLocationManager: ║ License Validation Failure
07-26 14:22:55.573 13975 14049 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:22:55.573 13975 14049 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:24:43.836 14125 14201 I TSLocationManager: 
07-26 14:24:43.836 14125 14201 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:24:43.836 14125 14201 I TSLocationManager: ║ License Validation Failure
07-26 14:24:43.836 14125 14201 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:24:43.836 14125 14201 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:25:48.619 14262 14343 I TSLocationManager: 
07-26 14:25:48.619 14262 14343 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:25:48.619 14262 14343 I TSLocationManager: ║ License Validation Failure
07-26 14:25:48.619 14262 14343 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:25:48.619 14262 14343 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:26:16.212 14394 14468 I TSLocationManager: 
07-26 14:26:16.212 14394 14468 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:26:16.212 14394 14468 I TSLocationManager: ║ License Validation Failure
07-26 14:26:16.212 14394 14468 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:26:16.212 14394 14468 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:26:45.699 14514 14588 I TSLocationManager: 
07-26 14:26:45.699 14514 14588 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:26:45.699 14514 14588 I TSLocationManager: ║ License Validation Failure
07-26 14:26:45.699 14514 14588 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:26:45.699 14514 14588 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:27:41.005 14644 14718 I TSLocationManager: 
07-26 14:27:41.005 14644 14718 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:27:41.005 14644 14718 I TSLocationManager: ║ License Validation Failure
07-26 14:27:41.005 14644 14718 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:27:41.005 14644 14718 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:28:03.128 14644 14759 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 14:29:07.984 14644 15163 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 14:31:45.348 15274 15350 I TSLocationManager: 
07-26 14:31:45.348 15274 15350 I TSLocationManager: ╔═════════════════════════════════════════════
07-26 14:31:45.348 15274 15350 I TSLocationManager: ║ License Validation Failure
07-26 14:31:45.348 15274 15350 I TSLocationManager: ╠═════════════════════════════════════════════
07-26 14:31:45.348 15274 15350 I TSLocationManager: ╟─ BackgroundGeolocation is running in evaluation mode.
07-26 14:31:52.999 15274 15423 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 14:32:37.142 15274 15423 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 14:35:35.674 15274 15742 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-26 14:37:44.729 15274 15901 I TSLocationManager: - Enable: false → true, trackingMode: 1

**Comment by christocracy** [comment]
I see you've closed this issue without explanation.
