### ISSUE TITLE
How to completely stop the services in foreground?

### ISSUE THREAD

**Issue by vincenzovitale** [transistorsoft/react-native-background-geolocation#533]
## Your Environment
* Plugin version: 2.12.1
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung S7
* React Native version (`react-native -v`): 0.55.4
* Plugin config

BackgroundGeolocation.ready({
      // Common
      activityRecognitionInterval: 0,
      minimumActivityRecognitionConfidence: 25,
      desiredAccuracy: 0,
      distanceFilter: __DEV__ ? 0 : 1,
      heartbeatInterval: 60,
      autoSync: false,
      disableElasticity: true,
      stopOnTerminate: true,
      stopOnStationary: true,
      stopTimeout: 3,
      startOnBoot: false,
      debug: false,
      reset: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_WARNING,
      // iOS Only
      // Android Only
      fastestLocationUpdateInterval: 500,
      // This setting will be ignored when distanceFilter > 0
      locationUpdateInterval: 500,
      foregroundService: true,
      notificationText: 'Running. Tap to open',
      disableLocationAuthorizationAlert: true,
      maxRecordsToPersist: 0
    }, () => {
          ...
    });

## Expected Behavior
When the main app is closed or removed from recent list with a swipe, when I open the app again I should keep receiving location provider changes.

## Actual Behavior
The location provider changes are not received anymore.

## Steps to Reproduce
1. Open the main app, the location provider events are received
2. Swipe out from recent list
3. Open app again
4. Disabling/enabling the location provider doesn't trigger the event

## Context
In general we would like to stop the running foreground services when we want to terminate the application and are not interested to keep them running in the background.
How to do that?

Thanks,
V.

**Comment by christocracy** [comment]
This is fixed in the paid version.  Will be mirrored here in the next release.

**Comment by vincenzovitale** [comment]
Hi Chris, thanks for the fast reply. 
We are a paying customer, and we are using:
git+https://<credentials>@github.com/transistorsoft/react-native-background-geolocation-android.git#2.12.1

is there a more recent one?

**Comment by christocracy** [comment]
Customers should not post issues in the public repo.  Use the private repo.

The fix is in the master branch of the private repo (not `2.12.1`).  See [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation-android/blob/master/CHANGELOG.md)

```
[Fixed] Android issue not firing providerchange on boot when configured with stopOnTerminate: true
```

**Comment by tt-driver-apps** [comment]
ok, sorry for posting here.
How do we stop the foreground services started by the plugin?
