### ISSUE TITLE
Question: is it possible to use geofences within this plugin? (Android)

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#534]
Is it possible to use geofences within this plugin? Does it supported by this library?

**Comment by christocracy** [comment]
Yes.
- [Geofence Features](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Geofence-Features)
- [Infinite Geofencing](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/geofencing.md)
