### ISSUE TITLE
Trigger local notifications on events while app is closed?

### ISSUE THREAD

**Issue by arosca** [transistorsoft/react-native-background-geolocation#537]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS simulator
* OS version: 11.2
* Device manufacturer / model: simulator
* React Native version (`react-native -v`): 0.55.4
* Plugin config

## Question
Using this plugin, is it possible to trigger local notification on location events while the application is closed? For instance, I would like to notify the user if he leaves or enters a geofence area.

## Actual Behavior
I setup listeners in the app, and they work while in foreground or background, but not while the app is closed:
```
    onFence = geofence => {
        const location = geofence.location;
        const identifier = geofence.identifier;
        const action = geofence.action;

        console.log('A geofence has been crossed: ', identifier);
        console.log('ENTER or EXIT?: ', action);
        console.log('geofence: ', JSON.stringify(geofence));

        PushNotification.localNotification({
            title: `FENCE ${action}`, // (optional)
            message: JSON.stringify(location), // (required)
            soundName: 'default' // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
        });
    };
```
```
        BackgroundGeolocation.on('geofence', this.onFence);
        BackgroundGeolocation.startGeofences(() => console.log('Started geofences'));
```
Thanks

**Comment by christocracy** [comment]
I see no problem here.  When my app running in iOS simulator boots in background due to a geofence event, the plugin's debug local-notification appears:

- "ENTER Geofence: Asdfasdfasd"
- "Booted in Background"

![](https://dl.dropboxusercontent.com/s/521h0ar83snwbcm/Screenshot%202018-08-01%2010.52.55.png?dl=1)

**Comment by arosca** [comment]
Thanks for the quick reply. Sorry if i wasn't clear, this isn't a bug report, it's a feasibility question: is it possible to trigger local notifications (not the debugs one) on location events?

**Comment by christocracy** [comment]
If the debug one shows, there's no reason posting one via 3rd-party lib will not work.  It's the same thing.

**Comment by arosca** [comment]
Understood, thanks for the help. It's too bad since i see many potential applications (including our case) for custom local triggered notifications, and it's obviously possible since the debug notifications work.

**Comment by crive80** [comment]
How to customize those notifications then?

**Comment by christocracy** [comment]
There are a number of config options prefixed with the word “notification” in the docs (eg notificationText, notificationTitle, etc).

**Comment by grubstarstar** [comment]
@christocracy I wouldn't mind some clarity on how this works. So are you saying that a geofence event will actually start running the app in the background and so the handler will trigger? I saw that on Android there is a headless mode where you can register a handler, but for iOS does it just start your app and allow your normal `BackgroundGeolocation.onGeofence((geofence) => {})` to fire even if the app was closed? Thanks.

**Comment by christocracy** [comment]
> but for iOS does it just start your app and allow your normal

Yes.

**Comment by nitishpccs89** [comment]
In android Geofences not firing when app is closed. How I can implement Geofences while app is in terminated. I also implement headless for android but it is not working. Please help me out

**Comment by christocracy** [comment]
This issue is a question titled:

> Trigger local notifications on events while app is closed?
