### ISSUE TITLE
location change event stops firing after about 24 hours

### ISSUE THREAD

**Issue by jlebensold** [transistorsoft/react-native-background-geolocation#54]
Hi there,

We've been testing this library on iOS and are configured with preventSuspend: true and a heartbeatInterval of 60. Everything functions as expected for about 24 hours and then the location events stop firing.

Is this because we're using preventSuspend? Have you noticed this when the app is inactive for more than a few days in the background?

Thanks!

**Comment by christocracy** [comment]
I generally don't recommend that feature, unless you're doing something
very specialized.

I haven't done a whole lot of long term testing with this feature.

On Friday, January 29, 2016, Jon Lebensold <notifications@github.com> wrote:

> Hi there,
>
> We've been testing this library on iOS and are configured with
> preventSuspend: true and a heartbeatInterval of 60. Everything functions as
> expected for about 24 hours and then the location events stop firing.
>
> Is this because we're using preventSuspend? Have you noticed this when the
> app is inactive for more than a few days in the background?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/54>
> .
>


-- 
Snet form Gmail Mobile

**Comment by jlebensold** [comment]
Ok so without prevent suspend we shouldn't have this issue of it going
silent after a few days?

**Comment by christocracy** [comment]
No.

On Friday, January 29, 2016, Jon Lebensold <notifications@github.com> wrote:

> Ok so without prevent suspend we shouldn't have this issue of it going
> silent after a few days?
>
> On Friday, 29 January 2016, Chris Scott <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I generally don't recommend that feature, unless you're doing something
> > very specialized.
> >
> > I haven't done a whole lot of long term testing with this feature.
> >
> > On Friday, January 29, 2016, Jon Lebensold <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> >
> > > Hi there,
> > >
> > > We've been testing this library on iOS and are configured with
> > > preventSuspend: true and a heartbeatInterval of 60. Everything
> functions
> > as
> > > expected for about 24 hours and then the location events stop firing.
> > >
> > > Is this because we're using preventSuspend? Have you noticed this when
> > the
> > > app is inactive for more than a few days in the background?
> > >
> > > Thanks!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/transistorsoft/react-native-background-geolocation/issues/54
> > >
> > > .
> > >
> >
> >
> > --
> > Snet form Gmail Mobile
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/transistorsoft/react-native-background-geolocation/issues/54#issuecomment-176802239
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/54#issuecomment-176802559>
> .
>


-- 
Snet form Gmail Mobile

**Comment by jlebensold** [comment]
have you done any testing where an app is the background for many days?

**Comment by christocracy** [comment]
Yes.  It will continue monitoring the device indefinitely until you tell it
to #stop.

On Friday, January 29, 2016, Jon Lebensold <notifications@github.com> wrote:

> have you done any testing where an app is the background for many days?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/54#issuecomment-176890611>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
New version `0.4.0` coming.  I fixed a bunch of issues with `preventSuspend` reported by the Cordova folks.

**Comment by jlebensold** [comment]
Hi Chris,

Thanks for the update. Can you list the bug fixes?

**Comment by christocracy** [comment]
Description of fixes [here](https://github.com/transistorsoft/react-native-background-geolocation/pull/57)

**Comment by christocracy** [comment]
I've had `preventSuspend: true` running on my iPad for over a week.
`boop........................boop..........................boop.......................boop...............`
