### ISSUE TITLE
Need additional dependencies to successfully run-ios (Documentation Suggestion)

### ISSUE THREAD

**Issue by AnsonT** [transistorsoft/react-native-background-geolocation#540]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS 
* OS version: 11
* Device manufacturer / model: iPhone 8plus simulator
* React Native version (`react-native -v`): 0.55.4
* Plugin config

## Expected Behavior
> npm i react-native-background-geolocation
> react-native link
> react-native run-ios
Success

## Actual Behavior
Build fails

## Context
Need to also install:
> npm i cocoa-lumberjack
> npm i react-native-background-fetch
> react-native link
Build succeeds
Suggest adding to the documentation

**Comment by christocracy** [comment]
Did you *read* the [iOS react-native link Setup Docs](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS-RNPM.md)?
