### ISSUE TITLE
Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.

### ISSUE THREAD

**Issue by Del-sama** [transistorsoft/react-native-background-geolocation#541]
## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* React Native version (`react-native -v`):0.51.0
## Expected Behavior

I installed `react-native-background-geolocation`, linked it according to the documentation with react-native link and ran `react-native run-android`. Builds successfully on Ios but build fails on Android.
## Actual Behavior

```FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Required by:
         project :app > project :react-native-background-geolocation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

## Steps to Reproduce

1. react-native unlink react-native-background-geolocation
2. react-native uninstall react-native-background-geolocation
3. yarn add react-native-background-geolocation
4. react-native link react-native-background-geolocation
5. react-native link react-native-background-fetch

## Context

I was trying to set up `react-native-background-geolocation` on an app.

**Comment by christocracy** [comment]
Did you read the Setup docs for react-Native link?

There’s a required manual step with a required maven url

**Comment by Del-sama** [comment]
Works now. I missed the manual setup

**Comment by Sakarisson** [comment]
Hello, @Del-sama. Could you please provide a URL that describes this process? Thanks.

**Comment by christocracy** [comment]
That took a few months.

**Comment by abinayakumaran** [comment]
i have followed the documentation but still i am facing the same issue

**Comment by christocracy** [comment]
What version of plugin?

**Comment by abinayakumaran** [comment]
3.4.2

**Comment by abinayakumaran** [comment]
> What version of plugin?

3.4.2

**Comment by christocracy** [comment]
Create a hello world app and follow the setup instructions.

**Comment by abinayakumaran** [comment]
> Create a hello world app and follow the setup instructions.

ok sure i will try, but it was worked few months ago

**Comment by christocracy** [comment]
You have a setup problem.  Try it in a new hello world app to assure yourself of the setup instructions then compare with your production app to see where you went wrong.

**Comment by Boris0102** [comment]
Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
Required by:
    project :app > project :react-native-background-geolocation

**Comment by Shihaburabbi** [comment]
@christocracy  > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.

**Comment by christocracy** [comment]
Did you read this thread?

**Comment by christocracy** [comment]
See [Android Setup](https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-setup-guides)

**Comment by brandtiwari007** [comment]
i have made a demo project and tried to install library
facing same issue ,I have followed the steps that you provided in the answer for me and other also
 Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - file:/home/raghvendra/projects/locator/fs-locator/Foo/node_modules/react-native/android/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/home/raghvendra/projects/locator/fs-locator/Foo/node_modules/jsc-android/dist/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://www.jitpack.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :react-native-background-fetch

**Comment by christocracy** [comment]
Post your android/build.gradle

**Comment by pacarvalho** [comment]
@abinayakumaran Did it work for you? I can confirm that in my case the required manual setup line in android/build.gradle was removed during an upgrade of react-native which caused this issue.

```
appCompatVersion = "1.1.0"
```

**Comment by christocracy** [comment]
@pacarvalho Post your `android/build.gradle`

**Comment by pacarvalho** [comment]
@christocracy 

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        googlePlayServicesLocationVersion = "19.0.1"
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
        appCompatVersion = "1.1.0" 
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.1")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        // react-native-background-geolocation START
        maven {
            // Required for react-native-background-geolocation
            url("${project(':react-native-background-geolocation').projectDir}/libs")
        }
        maven {
            // Required for react-native-background-fetch
            url("${project(':react-native-background-fetch').projectDir}/libs")
        }
        // react-native-background-geolocation END

        google()
        maven { url 'https://www.jitpack.io' }
    }
}

```

**Comment by christocracy** [comment]
>in my case the required manual setup line in android/build.gradle

Ok, so when you upgraded, the `maven url` were removed and you fixed by adding them back in?

**Comment by agunable** [comment]
hello i got an error:
Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available

here is my gradle
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        appCompatVersion = "1.4.2"
        googlePlayServicesLocationVersion = "20.0.0"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        maven {
           // Required for react-native-background-geolocation
           url("${project(':react-native-background-geolocation').projectDir}/libs")
       }
       maven {
           // Required for react-native-background-fetch
           url("${project(':react-native-background-fetch').projectDir}/libs")
       }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}
`

**Comment by ianharoldonwater** [comment]
hey @christocracy, read through the thread. I have an expired order, I did create and use the key last year. If I'm trying to use the key for another app, do I need to buy a new key?

**Comment by jahanzaibbaloch99** [comment]
@christocracy  Im getting the Same Error. i have reproduced each step you guys are discussing in the thread.

Im using Following Versions.
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-background-fetch": "^4.2.4",
    "react-native-background-geolocation": "^4.16.0"

**Comment by christocracy** [comment]
Post your android/build.gradle

**Comment by jahanzaibbaloch99** [comment]
Hey thanks for quick Response. 
i had debug the Bug and now its seems that error has Gone.
the error was Required version conflict with min Required version of SDK.

**Comment by jahanzaibbaloch99** [comment]
Hey thanks for quick Response.
i had debug the Bug and now its seems that error has Gone.
the error was i had ignored this step 

ℹ️ Note: Some recent versions of the React Native Android template may not include the allprojects section. You should add this manually as a separate section along with the nested repositories section in the same android/build.gradle file.

**Comment by anggakusumap** [comment]
Hi @christocracy, I am facing the same error

> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'. > Could not find any matches for com.transistorsoft:tslocationmanager-v21:+ as no versions of com.transistorsoft:tslocationmanager-v21 are available. Required by: project :app > project :react-native-background-geolocation

This is my android/build.gradle
`buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.22"
        appCompatVersion = "1.7.0"
        googlePlayServicesLocationVersion = "21.3.0"
    }
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven { url("${project(':react-native-background-geolocation').projectDir}/libs") }
        maven { url("${project(':react-native-background-fetch').projectDir}/libs") }
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
}

apply plugin: "com.facebook.react.rootproject"
`

I'm using following version
`   "react": "18.2.0",
    "react-native": "0.74.2",
    "react-native-background-fetch": "^4.2.5",
    "react-native-background-geolocation": "^4.16.3"`

**Comment by christocracy** [comment]
Please learn to [syntax highlight code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)

**Comment by anggakusumap** [comment]
Hi @christocracy , I already updated it. Thank you for the quick response

**Comment by christocracy** [comment]
As usual, a failure to properly follow the Setup Instructions:

![IMG_1303](https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/e0b0ea52-e857-4d8e-b36d-153f6de88e7a)

**Comment by anggakusumap** [comment]
Thank you, it's already working

This is my updated android/build.gradle

```
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.22"
        appCompatVersion = "1.7.0"
        googlePlayServicesLocationVersion = "21.3.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    allprojects {
        repositories {
            mavenLocal()
            maven { url("${project(':react-native-background-geolocation').projectDir}/libs") }
            maven { url("${project(':react-native-background-fetch').projectDir}/libs") }
        }
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
}
apply plugin: "com.facebook.react.rootproject"
```

**Comment by christocracy** [comment]
**`allprojects`**

**Comment by Deepakvermaadequate** [comment]
> Hey thanks for quick Response. i had debug the Bug and now its seems that error has Gone. the error was i had ignored this step
> 
> ℹ️ Note: Some recent versions of the React Native Android template may not include the allprojects section. You should add this manually as a separate section along with the nested repositories section in the same android/build.gradle file.

can you share your build file as I am getting same error

**Comment by stalteri** [comment]
facing same issue 

"react-native": "0.74.3",
"react-native-background-fetch": "4.2.5",
"react-native-background-geolocation": "4.17.3-rc.1",

my build.gradle file: 

```
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.22"
        appCompatVersion 	= "1.4.2"
        googlePlayServicesLocationVersion = "21.0.1"  
    }
    repositories {
        google()
        mavenCentral()

        maven { url 'https://maven.google.com' }
        maven { url "https://www.jitpack.io" }
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${project.ext.kotlinVersion}")
        classpath("com.google.gms:google-services:4.4.2")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()

        // Required for react-native-background-geolocation
        maven { url("${project(':react-native-background-geolocation').projectDir}/libs") }
        maven { url 'https://developer.huawei.com/repo/' }

        // Required for react-native-background-fetch
        maven { url("${project(':react-native-background-fetch').projectDir}/libs") }
    }
}

apply plugin: "com.facebook.react.rootproject"
```
