### ISSUE TITLE
Can't restart scheduling after app was closed

### ISSUE THREAD

**Issue by mactanner** [transistorsoft/react-native-background-geolocation#542]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS
* OS version: 11
* Device manufacturer / model: iPhone 6
* React Native version (`react-native -v`): 0.56.0
* Plugin config
```
      {
        desiredAccuracy: 100,
        distanceFilter: 100,
        stopTimeout: 1,
        activityRecognitionInterval: 10000,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        url: "http://localhost:3030/coords",
        batchSync: false,
        autoSync: true,
        schedule: ["2-6 8:00-20:00"]
      }
```

## Expected Behavior
After the scheduler was stopped and the app was terminated and started again, I should be able to also start scheduling again.

## Actual Behavior
Although a configuration with a schedule is provided, the plugin keeps telling me the following:
`⚠️-[TSScheduler start] Scheduler #start called with an empty schedule!`

## Steps to Reproduce

1. Start scheduling
2. Stop scheduling
3. Close / terminate the app
4. Start app again
5. Start scheduling, see logs.

Can be reproduced with the following component:

```
export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Geolocation Scheduler</Text>
        <Button onPress={e => this.onStartSchedule()} title="Start Schedule" />
        <Button onPress={e => this.onStopSchedule()} title="Stop Schedule" />
      </View>
    );
  }

  onStopSchedule() {
    BackgroundGeolocation.stopSchedule(() => {
      console.info("- Scheduler stopped");
      BackgroundGeolocation.stop();
    });
  }

  onStartSchedule() {
    BackgroundGeolocation.on("location", this.onLocation, this.onError);
    BackgroundGeolocation.ready(
      {
        desiredAccuracy: 100,
        distanceFilter: 100,
        stopTimeout: 1,
        activityRecognitionInterval: 10000,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        url: "http://localhost:3030/coords",
        batchSync: false,
        autoSync: true,
        schedule: ["2-6 8:00-20:00"]
      },
      state => {
        console.log(
          "- BackgroundGeolocation is configured and ready: ",
          state.enabled
        );

        if (!state.enabled) {
          BackgroundGeolocation.startSchedule(function() {
            console.log("- Start success");
          });
        }
      }
    );
  }

  componentWillUnmount() {
    BackgroundGeolocation.removeListeners();
  }
  onLocation(location) {
    console.log("- [event] location: ", location);
  }
  onError(error) {
    console.warn("- [event] location error ", error);
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  }
});
```

## Context
I want to build an app that tracks geolocations usually from 8am to 8pm. But on specific days it should be possible to stop tracking. And of course I want to start the tracking on the subsequent day again.

## Debug logs

> 2018-08-10 13:41:23.416187+0200 baum[16873:4546378] Running application "baum" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
> ℹ️-[TSLocationManager on:success:failure:] location
> 2018-08-10 13:41:24.759 [info][tid:com.facebook.react.JavaScript] '- BackgroundGeolocation is configured and ready: ', false
> 2018-08-10 13:41:24.758662+0200 baum[16873:4546378] '- BackgroundGeolocation is configured and ready: ', false
> ⚠️-[TSScheduler start] Scheduler #start called with an empty schedule!
> 2018-08-10 13:41:24.760 [info][tid:com.facebook.react.JavaScript] - Start success
> 2018-08-10 13:41:24.759893+0200 baum[16873:4546378] - Start success
> ℹ️-[TSDBLogger db_save] Log committed

**Comment by christocracy** [comment]
Read carefully the docs for [`#ready`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#readydefaultconfig-successfn-failurefn)

When you *add or change* a config option to `#ready` *after* the app has been first installed, **it is ignored** unless you tell the plugin to `reset: true`.

**Comment by mactanner** [comment]
Oops, haven't seen that. Thanks for your quick reply.
