### ISSUE TITLE
UPDATE IOS DOCS INSTALLING WITH COCOAPODS

### ISSUE THREAD

**Issue by ManuelJF** [transistorsoft/react-native-background-geolocation#543]
missing key `NSLocationAlwaysAndWhenInUseUsageDescription` in the cocoapods  docs for ios 11.

this is the actual reference:

![screen shot 2018-08-10 at 3 23 10 pm](https://user-images.githubusercontent.com/15016968/43979745-59a74c2a-9cb1-11e8-9c30-0b4b0e646a89.png)

needs to be this:

![screen shot 2018-08-10 at 3 27 23 pm](https://user-images.githubusercontent.com/15016968/43979918-e80e2a06-9cb1-11e8-8cbc-5e7a568f88de.png)

**Comment by christocracy** [comment]
Thanks.  You don’t need to manually do Cococapod set anymore with `react-native link`, which can detect the existence of a Podile` and automatically add the plugin required pods.

The plugin’s install script will automatically add the required permissions keys.
