### ISSUE TITLE
Stops tracking geo-location, accuracy in plugin configuration

### ISSUE THREAD

**Issue by amirey** [transistorsoft/react-native-background-geolocation#545]
## Your Environment
* Plugin version: 2.12.0
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Nexus 5X
* React Native version (`react-native -v`): 0.55.4
* Plugin config
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
  distanceFilter: 0,
  locationUpdateInterval: 5000,
  fastestLocationUpdateInterval: 5000,
  notificationText: "",
  allowIdenticalLocations: true,
  url: TRACKER_HOST + this.state.username,
  params: {
	// Required for tracker.transistorsoft.com
	device: {
	  uuid: DeviceInfo.getUniqueID(),
	  model: DeviceInfo.getModel(),
	  platform: DeviceInfo.getSystemName(),
	  manufacturer: DeviceInfo.getManufacturer(),
	  version: DeviceInfo.getSystemVersion(),
	  framework: 'ReactNative'
	}
  },
  autoSync: true,
  stopOnTerminate: false,
  startOnBoot: true,
  foregroundService: true,
  debug: true,
  logLevel: BackgroundGeolocation.LOG_LEVEL_WARNING,
}

## Expected Behavior
- Plugin should track continuously, unless there are strenuous requirements on the device and the OS needs to free memory
- The accuracy should be very high

## Actual Behavior
- It seems to sporadically stop tracking for a few minutes after a while (we track for hours at a time). It then comes back to life.
- The accuracy is not quite what we think the devices are capable of. We track with the same devices using Strava, to make sure we're not assessing it subjectively.

I read the documentation and have been playing with the configuration of the library, but my best guess is that I missed something, or that it's because we're running in DEBUG mode. It would be great if you could cast your eyes over those and tell me what I'm doing wrong, or if there's an actual issue, or limitation we're ignoring.

## Steps to Reproduce
All we're doing is configuring as such and running for a few hours straight.

**Comment by christocracy** [comment]
I don’t experience this issue on my 5 test devices.  Nexus / Puxel devices are my preferred dev devices.

- Perhaps `notificationPriority` has some drawbacks when use use `_MIN.
- you’ve set  distanceFilter: 0 to use time-based tracking.  I would avoid that.  iOS doesn’t even allow time-based tracking (more battery intensive).
- could be environment problems (tunnels, physical obstructions; tall buildings blocking gps sats.

There will be evidence in the logs.  You’re watching the logs, right?

**Comment by christocracy** [comment]
I develop without a license key in my demo app.  The plugin behaviour has no difference in DEBUG mode.
