### ISSUE TITLE
Failed to resolve: com.transistorsoft:tslocationmanager:+ and Failed to resolve: com.transistorsoft:tsbackgroundfetch:+

### ISSUE THREAD

**Issue by DanthonyPabon** [transistorsoft/react-native-background-geolocation#548]
## Your Environment
* Plugin version:^2.13.0
* Platform: Android
* OS version: 7.1.0
* Device manufacturer / model:Samsung
* React Native version (`react-native -v0.56.0`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
  Searched in the following locations:
      file:/Users/iron/Library/Android/sdk/extras/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/m2repository/com/transistorsoft/tslocationmanager/
      file:/Users/iron/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/
      file:/Users/iron/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/
      file:/Users/iron/.m2/repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/.m2/repository/com/transistorsoft/tslocationmanager/
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/
      file:/Users/iron/Documents/GIT/Mood/picnow-rn/node_modules/react-native/android/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/Documents/GIT/Mood/picnow-rn/node_modules/react-native/android/com/transistorsoft/tslocationmanager/
      https://maven.google.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tslocationmanager/
  Required by:
      project :app > project :react-native-background-geolocation
> Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
  Searched in the following locations:
      file:/Users/iron/Library/Android/sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/Users/iron/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/Users/iron/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/Users/iron/.m2/repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/.m2/repository/com/transistorsoft/tsbackgroundfetch/
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/
      file:/Users/iron/Documents/GIT/Mood/picnow-rn/node_modules/react-native/android/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/Documents/GIT/Mood/picnow-rn/node_modules/react-native/android/com/transistorsoft/tsbackgroundfetch/
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/
  Required by:
      project :app > project :react-native-background-fetch

**Comment by christocracy** [comment]
Post your gradle **files**.

**Comment by DanthonyPabon** [comment]
> android/app/build.gradle


apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
        entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        applicationId "com.picnow"
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-background-geolocation')
    compile project(':react-native-background-fetch')
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:design:26.1.0'
    compile project(':react-native-image-picker')
    compile project(':react-native-fs')
    compile project(':react-native-image-resizer')
    compile project(':react-native-android-location-services-dialog-box')
    compile project(':react-native-orientation')
    compile project(':react-native-vector-icons')
    compile project(':react-native-camera')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:$rootProject.supportLibVersion"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

**Comment by DanthonyPabon** [comment]
> android/build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
        maven { url "$rootDir/../node_modules/react-native-background-fetch/android/libs" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

subprojects { 
     afterEvaluate { 
         project -> if (project.hasProperty("android")) { 
             android { 
                 compileSdkVersion 26 
                buildToolsVersion '26.0.3'
             } 
         } 
     } 
 }

ext {
    compileSdkVersion = 26 
    targetSdkVersion = 26 
    buildToolsVersion = "26.0.3"
    supportLibVersion = "26.1.0" 
    googlePlayServicesVersion = "11.8.0" 
}

**Comment by DanthonyPabon** [comment]
> android/app/proguard-rules.pro

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# BackgroundGeolocation lib tslocationmanager.aar is *already* proguarded
-keep class com.transistorsoft.** { *; }
-dontwarn com.transistorsoft.**

-keep class com.google.**
-dontwarn com.google.**
-dontwarn org.apache.http.**
-dontwarn com.android.volley.toolbox.**

# BackgroundGeolocation (EventBus)
-keepclassmembers class * extends de.greenrobot.event.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}

# logback
-keep class ch.qos.** { *; }
-keep class org.slf4j.** { *; }
-dontwarn ch.qos.logback.core.net.*

**Comment by christocracy** [comment]
Please learn to use syntax highlighting.

You surround your code with 3-backticks

**Comment by DanthonyPabon** [comment]
> android/settings.gradle

`rootProject.name = 'picnow'
include ':react-native-background-fetch'
project(':react-native-background-fetch').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-fetch/android')
include ':react-native-background-geolocation'
project(':react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-geolocation/android')
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')
include ':react-native-fs'
project(':react-native-fs').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fs/android')
include ':react-native-image-resizer'
project(':react-native-image-resizer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-resizer/android')
include ':react-native-android-location-services-dialog-box'
project(':react-native-android-location-services-dialog-box').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-android-location-services-dialog-box/android')
include ':react-native-orientation', ':app'
project(':react-native-orientation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-orientation/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-camera'
project(':react-native-camera').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-camera/android')

include ':app'
`

**Comment by christocracy** [comment]
I just created a new app Foo.  I have no issue.
```
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.56.0
```

1.  Install plugin
```
$ react-native init Foo
$ cd Foo
$ npm install --save react-native-background-geolocation
$ react-native link react-native-background-geolocation
Scanning folders for symlinks in /Users/chris/Documents/workspace/react/background-geolocation/tmp/Foo1/node_modules (10ms)
rnpm-install info Linking react-native-background-geolocation ios dependency
rnpm-install info Platform 'ios' module react-native-background-geolocation has been successfully linked
rnpm-install info Linking react-native-background-geolocation android dependency
rnpm-install info Platform 'android' module react-native-background-geolocation has been successfully linked

$ react-native link react-native-background-fetch
Scanning folders for symlinks in /Users/chris/Documents/workspace/react/background-geolocation/tmp/Foo1/node_modules (16ms)
rnpm-install info Linking react-native-background-fetch ios dependency
rnpm-install info Platform 'ios' module react-native-background-fetch has been successfully linked
rnpm-install info Linking react-native-background-fetch android dependency
rnpm-install info Platform 'android' module react-native-background-fetch has been successfully linked

$ react-native link cocoa-lumberjack
Scanning folders for symlinks in /Users/chris/Documents/workspace/react/background-geolocation/tmp/Foo1/node_modules (15ms)
rnpm-install info Linking cocoa-lumberjack ios dependency
rnpm-install info Platform 'ios' module cocoa-lumberjack has been successfully linked
```

2.  Copy required `maven url`s to `android/build.gradle`
```
allprojects {
    repositories {
        .
        .
        .
        maven {
           url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
           url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}
```

3.  Run it:
```
$ react-native run-android
.
.
.
:app:assembleDebug
:app:installDebug
Installing APK 'app-debug.apk' on 'Pixel - 8.1.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 29.005 secs
Running /Users/chris/Library/Android/sdk/platform-tools/adb -s FA6970312056 reverse tcp:8081 tcp:8081
Starting the app on FA6970312056 (/Users/chris/Library/Android/sdk/platform-tools/adb -s FA6970312056 shell am start -n com.foo1/com.foo1.MainActivity)...
Starting: Intent { cmp=com.foo1/.MainActivity }
```

The app boots successfully.

**Comment by DanthonyPabon** [comment]
I discarded all the changes I had, I cleaned the project in android studio, I did the steps that you put and I got this

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
  Searched in the following locations:
      file:/Users/iron/Library/Android/sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/Users/iron/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/Users/iron/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/Users/iron/.m2/repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/.m2/repository/com/transistorsoft/tsbackgroundfetch/
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/
      file:/Users/iron/Documents/GIT/Mood/picnow-rn/node_modules/react-native/android/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/iron/Documents/GIT/Mood/picnow-rn/node_modules/react-native/android/com/transistorsoft/tsbackgroundfetch/
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/
  Required by:
      project :app > project :react-native-background-fetch
> Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
  Searched in the following locations:
      file:/Users/iron/Library/Android/sdk/extras/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/m2repository/com/transistorsoft/tslocationmanager/
      file:/Users/iron/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/
      file:/Users/iron/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/
      file:/Users/iron/.m2/repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/.m2/repository/com/transistorsoft/tslocationmanager/
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/
      file:/Users/iron/Documents/GIT/Mood/picnow-rn/node_modules/react-native/android/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/iron/Documents/GIT/Mood/picnow-rn/node_modules/react-native/android/com/transistorsoft/tslocationmanager/
      https://maven.google.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tslocationmanager/
  Required by:
      project :app > project :react-native-background-geolocation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

> this is my package.json

```
{
  "name": "DD",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "cwait": "^1.1.1",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-android-location-services-dialog-box": "^2.6.0",
    "react-native-axios": "^0.17.1",
    "react-native-background-geolocation": "^2.13.0",
    "react-native-camera": "^1.1.4",
    "react-native-elements": "^0.19.1",
    "react-native-fs": "^2.10.14",
    "react-native-image-picker": "^0.26.10",
    "react-native-image-resizer": "^1.0.0",
    "react-native-orientation": "^3.1.3",
    "react-native-public-ip": "^1.0.0",
    "react-native-simple-dialogs": "^0.4.0",
    "react-native-slider": "^0.11.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.8.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "^5",
    "jest": "23.4.1",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "author": "Mood-Agency",
  "rnpm": {
    "assets": [
      "src/fonts"
    ]
  }
}
```

**Comment by christocracy** [comment]
Follow my [steps above](https://github.com/transistorsoft/react-native-background-geolocation/issues/548#issuecomment-413862397) and create a simple "Foo" app.  Make it work in isolation of your app first.

**Comment by DanthonyPabon** [comment]
And if you upload your project to a repository? [this](https://github.com/transistorsoft/react-native-background-geolocation/issues/548#issuecomment-413862397)

**Comment by christocracy** [comment]
- Extras foo1.tar.gz
- Be sure to terminate your dev-server

```
$ tar xfvz foo1.tar.gz
$ cd Foo1
$ npm install
$ react-native run-android
```

[foo1.tar.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/2298197/foo1.tar.gz)

**Comment by DanthonyPabon** [comment]
does not run the project, restart the mac and the same problem persists

**Comment by DanthonyPabon** [comment]
the test project that I did put the name of Foo, should not have any problem because of that, the problem is with the library because before adding the library I run it and opened to normal app

**Comment by christocracy** [comment]
Did you follow the directions *exactly* [as above](https://github.com/transistorsoft/react-native-background-geolocation/issues/548#issuecomment-413941508) or not?

**Comment by DanthonyPabon** [comment]
Ready, already is working, thanks!

**Comment by logitechwinwin** [comment]
allprojects {
    repositories {
        .
        .
        .
        maven {
           url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
           url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}

Thanks, but this isn't really a tutorial.

**Comment by christocracy** [comment]
>Thanks, but this isn't really a tutorial.

What you posted is missing required maven urls as-directed in the required Setup Guides linked in the readme.  You just have to follow the instructions.
