### ISSUE TITLE
Is there a way to get location when device moves certain distance?

### ISSUE THREAD

**Issue by JoseVf** [transistorsoft/react-native-background-geolocation#549]
## Your Environment
* Plugin version: `2.13.1`
* Platform: `iOS`
* OS version: `11.4`
* Device manufacturer / model: `iPhone 5s`
* React Native version: `0.56.0`
* Plugin config: `Actually I'm asking for this 🙄`

## Expected Behavior
Get location each _n_ meters, no mattering moving speed.

## Actual Behavior
Currently there's a formula that calculate recording rate based on `distanceFilter` and moving speed (at least that was what I understood 🤔), so if I put `distanceFilter: 50` it won't actually record location each 50 meters.

## Context
The app will have different 'profiles'. Each profile allows user to get different accuracy on route tracking based on distance reporting. Client asked for getting the location each _n_ meters based on profile, no matter if the route is a straight line or have many curves, just get the location each _n_ meters.

**Comment by christocracy** [comment]
Read the docs for [`distanceFilter`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-integer-distancefilter)

![](https://dl.dropboxusercontent.com/s/oepxp806m1pb5y1/Screenshot%202018-08-23%2009.35.08.png?dl=1)

**Comment by christocracy** [comment]
I don't appreciate you taking advantage of my rapid assistance to posted issues then taking knowledge over to Mauron85.
