### ISSUE TITLE
Step 9 Framework Search Path build error

### ISSUE THREAD

**Issue by qasimalbaqali** [transistorsoft/react-native-background-geolocation#55]
After going through all the installation step and doing exactly what have ben instructed I ran into a problem in the last step unfortunately. 
When it is instructed to add `$(PROJECT_DIR)/../node_modules/react-native-background-geolocation` to `Framework Search Paths` which was totaly empty, I added `$(PROJECT_DIR)` and `$(PROJECT_DIR)/../node_modules/react-native-background-geolocation` and have set both to recurisve. But the screenshot that is in the installation guide has 3 properties instead of the one that was told to add to `Framework Search Paths`.  When I try to build, the build success notification pops up but then an error popup message shows up which can be seen in the screenshot below. Any idea what have I done wrong? 

![Image of error](http://i.imgur.com/EajXoUd.png)

**Comment by qasimalbaqali** [comment]
`iOS Simulator -> Reset Contents and Settings... -> Reset` did the trick. It was an error from the simulator, so it's unrelated to the RNBG.

**Comment by christocracy** [comment]
Awesome

On Wednesday, February 3, 2016, Qasim Albaqali <notifications@github.com>
wrote:

> Closed #55
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/55>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/55#event-537518584>
> .
>


-- 
Snet form Gmail Mobile
