### ISSUE TITLE
Scheduler not working and not tracking according to specified distance

### ISSUE THREAD

**Issue by rash6795** [transistorsoft/react-native-background-geolocation#551]
## Your Environment
* Plugin version: **2.12.2**
* Platform: **iOS** 
* OS version: **11.4.1**
* Device manufacturer / model: **iPhone 6 Plus**
* React Native version (`react-native -v`): **0.54.2**
* Plugin config

## Expected Behavior
Start tracking in scheduled time and also track in a reliable distance as mentioned in distance filter 

## Actual Behavior
 I am using scheduled location tracking but it doesn’t seem to work properly.(tracking starts when its installed when scheduler time is over for the day and the next day it doesnt start up ). And according to the distance, I have specified a value of 1000m but it is giving me locations for every 100m and less.

## Steps to Reproduce
This is the configuration i am using 
{
    activityRecognitionInterval = 60000;
    activityType = 1;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    disableElasticity = 1;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 10;
    elasticityMultiplier = 1;
    enabled = 1;
    extras =    {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =    {
    };
    heartbeatInterval = 60;
    httpRootProperty = data;
    httpTimeout = 60000;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =    {
        cancelButton = Cancel;
        instructions = "To use Background Location, you must enable ALWAYS access in Location Services.";
        settingsButton = Settings;
        titleWhenNotEnabled = "Location services are turned OFF";
        titleWhenOff = "Please turn on Location Services ";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 10;
    maxBatchSize = "-1";
    maxDaysToPersist = 10;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "4879.616478891899";
    params =    {
    };
    pausesLocationUpdatesAutomatically = 0;
    preventSuspend = 1;
    schedule =    (
        "2-7 08:00:00-20:00:00"
    );
    schedulerEnabled = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 5;
    trackingMode = 1;
    url = "";
    useSignificantChangesOnly = 0;
}

## Debug logs
[background-geolocation.log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/2326660/background-geolocation.log.gz)

**Comment by christocracy** [comment]
One of my paying customers reported a problem with scheduler today.  I'm awaiting feedback on the fix.

As for `distanceFilter`, you can see from logs that the plugin is configured with a value of:
```
distanceFilter = 10;
```

Read carefully the docs for [`#ready`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#readydefaultconfig-successfn-failurefn)

> ⚠️ The #ready method only applies the supplied defaultConfig for the first launch of the app — Forever after, the plugin is going to remember every configuration change you apply at runtime (eg: #setConfig) and reload that same config every time your app boots.

See the note there about [`reset: true`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#reset-true)

**Comment by christocracy** [comment]
This should be fixed now in `2.13.x` and `2.14.0-beta.3`
