### ISSUE TITLE
[Question] How to detect when user stopped moving?

### ISSUE THREAD

**Issue by lorenc-tomasz** [transistorsoft/react-native-background-geolocation#554]
Could you propose best method to detect when user who drives car stopped moving?

**Comment by christocracy** [comment]
That’s the core [philosophy of the plugin](https://github.com/transistorsoft/react-native-background-geolocation/wiki), detecting when device is moving / stationary.

**Comment by lorenc-tomasz** [comment]
Is there any option to set stopTimeout less than one minute? Based on documentation the minimal value is one minute :( 

 Now I tries to detect when speed is less than 1 km/h for 15 sec, however this approach is not the best one.

**Comment by christocracy** [comment]
No,  

have you read the docs for the `activitychange` event?  Do you realize that the plugin implements native DeviceMotion apis, as desscribed in the Philosophy of Operation above?

**Comment by lorenc-tomasz** [comment]
Hi,

Yes. Now I simply try to achieve good stop detection when user dosen't agree for using the motion data.

**Comment by christocracy** [comment]
When the user denies "Health and Fitness" permission, the plugin reverts to simple accelerometer-based motion-detection.  This is not nearly as good as the `CMMotionActivityManager` API but will reliably detect `still` / `moving`.
