### ISSUE TITLE
App's behaviour when app is destroyed (enableheadless :true)

### ISSUE THREAD

**Issue by Udbhav12** [transistorsoft/react-native-background-geolocation#556]
## Your Environment
* Plugin version:  2.12.2
* Platform:  Android
* OS version: Android 5.1.1
* Device manufacturer / model: Samsung Galaxy J3 Pro 
* React Native version (`react-native -v`):  0.55.4
* Plugin config

## Expected Behavior
Screen A should be launched after app is opened after destroying

## Actual Behavior
Screen C is launched

## Steps to Reproduce

1. Launch app by clicking on app's launcher icon
2. Start Tracking
3. Destroy app by swiping it from app switcher
4. Launch app again by clicking on launcher icon

## Context
I understand that in order for tracking to be work even after app is terminated (killed) by user , we need to set 'stopOnTerminate' as false and 'enableHeadless'  as true in configure options.

Suppose my app has three screens A-> B -> C. 'A' is launcher screen

I was on Screen C when I destroyed my app

Now when I launch the app again by clicking on app's launcher icon,I am again taken to screen C.

Expected behaviour should be that Screen A should be launched.  In short app state is never getting destroyed. I have never seen such behaviour in any native android app

I do not know whether this is a react native bug or not.

**Comment by christocracy** [comment]
When you terminate an app with `stopOnTerminate: false`, only the `MainActivity` is terminated.  The Android `application` instance remains alive.

I do not know what affect this will have on your "screens" but it's not related to the plugin.
