### ISSUE TITLE
watchPosition sync the same location

### ISSUE THREAD

**Issue by inet123** [transistorsoft/react-native-background-geolocation#558]
## Your Environment
* Plugin version: 2.13.3
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Emulatr
* React Native version (`react-native -v`): 0.55.4
* Plugin config
{
        reset: true,
        // Application config
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
        stopOnTerminate: true,
        startOnBoot: false,
        // Notification config
        notificationText: strings('location_notification'),
        // AuthSync
        batchSync: true,
        autoSync: true,
        foregroundService: false,
        url: axios.defaults.baseURL + '/locations',
        params: {
            device_uuid: getDeviceId()
        }
    }

## Expected Behavior
When using watchPosition with an interval I would like the plugin to filter the locations it sends to the server if the user hasn't moved.

## Actual Behavior
It sends the location of the user every interval.

## Steps to Reproduce

1. Open App
2. Start watchPosition
`BackgroundGeolocation.watchPosition(this._setUserLocation, (error) => {
    console.log('- Watch position error: ', error);
}, {locationUpdateInterval: 10000});`

## Context

Updating a marker on a map based on user location

## Debug logs
Not releavant

**Comment by inet123** [comment]
Is it in the roadmap or maybe there is a way to hook the sync function to filter locations before sending them?

**Comment by christocracy** [comment]
No, not on roadmap.  I've never heard of a need for this in 3 years.

No, there's no way to filter locations before HTTP request occurs.
