### ISSUE TITLE
Control when locations logged to database

### ISSUE THREAD

**Issue by Boatly** [transistorsoft/react-native-background-geolocation#559]
Plugin version: 2.13.3
Platform: Android
OS version: 8.0.0
Device manufacturer / model: Emulator
React Native version (react-native -v): 0.55.4

I would like to provide the user with frequent position updates (every 10 meters for instance) but record positions in the database at a lower frequency (every 100m, for example).  

Is there a strategy I can use to achieve this?

**Comment by christocracy** [comment]
You can use `#watchPosition` in the foreground but **be sure** to `#stopWatchPosition` when your app goes to background.
