### ISSUE TITLE
on('location') event not being fired using ios simulator

### ISSUE THREAD

**Issue by ryandury** [transistorsoft/react-native-background-geolocation#56]
Hey there, i'm trying to get this up and running but the BackgroundGeolocation.on('location', function(location) {}); event isn't being fired when using the ios simulator and Debug > Location > 'Freeway Drive' . I am using your [example here](https://github.com/transistorsoft/react-native-background-geolocation#example).  When the component loads I get some initial data (without error) in the debug console but i'm not getting a location update event.  The initial data looks like this:

```
- onMotionChanage: {
    activity =     {
        confidence = 100;
        type = unknown;
    };
    battery =     {
        "is_charging" = 0;
        level = "-1";
    };
    coords =     {
        accuracy = 5;
        altitude = 0;
        altitudeAccuracy = "-1";
        heading = "292.15";
        latitude = "37.41152166";
        longitude = "-122.20187338";
        speed = "34.93";
    };
    "is_heartbeat" = 0;
    "is_moving" = 0;
    timestamp = "2016-02-08T05:21:43.103Z";
    uuid = "6CBCE52E-F7B9-4E33-87BB-2B955BA5C525";
}
RCTLog.js:38 - RCTBackgroundGeoLocation onLocationChanged
Track.js:56 - [js]location:  {"coords":{"speed":34.93,"longitude":-122.20187338,"latitude":37.41152166,"accuracy":5,"heading":292.15,"altitude":0,"altitudeAccuracy":-1},"is_heartbeat":false,"is_moving":false,"uuid":"F06094EC-9798-42A8-AA79-75E455DC2AF1","activity":{"type":"unknown","confidence":100},"battery":{"level":-1,"is_charging":0},"timestamp":"2016-02-08T05:21:43.103Z"}
Track.js:62 - Location: {"coords":{"speed":34.93,"longitude":-122.20187338,"latitude":37.41152166,"accuracy":5,"heading":292.15,"altitude":0,"altitudeAccuracy":-1},"is_heartbeat":false,"is_moving":false,"uuid":"F06094EC-9798-42A8-AA79-75E455DC2AF1","activity":{"type":"unknown","confidence":100},"battery":{"level":-1,"is_charging":0},"timestamp":"2016-02-08T05:21:43.103Z"}
RCTLog.js:38 - onHttpResponse
RCTLog.js:38 - onSyncComplete
```

My component looks like this: http://pastebin.com/Mg2CUrzP

When using the default ios navigator.geolocation.watchPosition(); I receive updates. Any ideas on what might be preventing the update event from firing?

Thank you. This looks like a great component, and i'm excited to integrate further :)

**Comment by christocracy** [comment]
Sorry late here.  I can't reproduce this issue.  However, I'm about to push a new version.

**Comment by joshblour** [comment]
+1 - only location and http Sync only fired once using the ios simulator - freeway drive.

**Comment by christocracy** [comment]
Are you using the latest version?

I don't see a problem.  I see map markers being rendered, which are rendered in the `on('location' callback)`

![](https://www.dropbox.com/s/b7hw9t84q8r1vjd/Screenshot%202016-03-09%2013.27.33.png?dl=1)

**Comment by joshblour** [comment]
yep, I'm using the latest version from npm.

Actually, i just 'nuked' the simulator and reinstalled. now I'm getting the updates! :)

**Comment by christocracy** [comment]
Awesome!

**Comment by lorenc-tomasz** [comment]
Have the same issue with Xcode 10.1.

**Comment by christocracy** [comment]
@lorenc-tomasz It's an iOS 12 simulator bug.   Use iOS 11 simulator.

**Comment by lorenc-tomasz** [comment]
Thank you. It helped :) 👍
