### ISSUE TITLE
How to get latitude & longitude

### ISSUE THREAD

**Issue by chuchden** [transistorsoft/react-native-background-geolocation#564]
## Your Environment
* Plugin version:
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Steps to Reproduce

1. Everything working well. 
2. I just need how to get Lat & Lon param to my server
3.
4.

## Debug logs

![image](https://user-images.githubusercontent.com/3120637/45629464-b2bcb980-bac0-11e8-89d1-4f16a910b3e0.png)

**Comment by christocracy** [comment]
See the guide [HTTP Features](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/http.md)
