### ISSUE TITLE
unable to add custom email body for "EMAIL LOG"

### ISSUE THREAD

**Issue by rash6795** [transistorsoft/react-native-background-geolocation#566]
**Not able to add custom email body** 

## Your Environment
* Plugin version: **2.12.2**
* Platform: **iOS**
* OS version: **11.4**
* Device manufacturer / model:  **iPhone 7**
* React Native version (`react-native -v`): **0.54.2**
* Plugin config: nil

## Expected Behavior

An Additional parameter to include custom email body

## Actual Behavior

No option to add message

## Steps to Reproduce

BackgroundGeolocation.emailLog("support@abc.com")

## Context

I want to add customised message to email body like user information along with the email body

**Comment by christocracy** [comment]
It could be done.  How about an `{}` rendered as JSON above the State?

**Comment by rash6795** [comment]
couldn't get you.
Can you elaborate ?

**Comment by christocracy** [comment]
What don’t you understand?

**Comment by rash6795** [comment]
can't understand 
{} rendered as JSON above the State?

**Comment by christocracy** [comment]
![](https://dl.dropbox.com/s/wd53hfthjrw30we/Screenshot%202018-09-20%2007.11.16.png?dl=1)

So an `{}` rendered *above* state.

```javascript
BackgroundGeolocation.emailLog('foo@bar.com', {
  an: 'object',
  rendered: 'above state'
});
```

**Comment by rash6795** [comment]
cool !!!!
Thanks for the explanation. That's exactly what i want

 Much Awaiting for this enhancement at earliest
