### ISSUE TITLE
FCM not start up when app was kill use with geobackground

### ISSUE THREAD

**Issue by chuchden** [transistorsoft/react-native-background-geolocation#569]
## Your Environment
* Plugin version:
* Platform: Android
* OS version:
* Device Samsung:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior
It should show my debug data

## Actual Behavior
Nothing come

## Steps to Reproduce

1. I setup fcm 
2. send notif 
3. debug ok
4. setup geobackground > send notif (ok if app active)
# Issue when swipe off app debug not see fcm data as before.

**Comment by christocracy** [comment]
No idea.  Show logs.

**Comment by christocracy** [comment]
Closed for lack of feedback.
