### ISSUE TITLE
Triggering events being already inside a geofence

### ISSUE THREAD

**Issue by jmoliugp** [transistorsoft/react-native-background-geolocation#570]
## Your Environment
* Plugin version:  2.13.0
* Platform: iOS & Android
* OS version: 11.0.0 - 6.0.0
* Device manufacturer / model: Emulator
* React Native version (`react-native -v`): 0.55

I do heavy use of geofences and was wondering how i could handle this situation. I want to detect when a user has entered a geofence and X time after that check if the user is still inside. I get that for the first part I listen for geofences events, specifically for the `ENTER` one, but how can I know if the user is still inside it exactly 2 hours after that? I thought about using the `hearbeat`, but it would still need to check if the current position is inside a geofence or not. Does your library provide a way to do this? Do you see an alternative?

**Comment by jmoliugp** [comment]
Would it be possible to expose a service to check if the user is inside an active geofence ?

It would be helpful in this kind of scenarios.

**Comment by christocracy** [comment]
If the `exit` transition hasn't fired, they're still inside.
