### ISSUE TITLE
distance Accuracy issue

### ISSUE THREAD

**Issue by itcurves** [transistorsoft/react-native-background-geolocation#571]
## Your Environment
* Plugin version: ^2.12.0-beta.4
* Platform: iOS 
* OS version: any
* Device manufacturer / model: any 
* React Native version (`react-native -v`): 0.54.4
* Plugin config
{
        reset: true,
        distanceFilter: 10,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        stationaryRadius: 25,        
        stopTimeout: 1,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,  
        startOnBoot: false,       
        autoSync: false,         
      }

## Context
I am using watchPosition with following options:
{
              interval : 60000, distanceAccuracy : 0, presist:false
        }

but the result I am getting the accuracy is not good, it shows users on totally different location from where they are actually.

Any guess?

**Comment by christocracy** [comment]
No idea.  Get logs

**Comment by christocracy** [comment]
Closed for lack of feedback.
