### ISSUE TITLE
HeadlessTask not working

### ISSUE THREAD

**Issue by nos-joel** [transistorsoft/react-native-background-geolocation#573]
* Plugin version: 2.13.3
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Motorola / G6
* React Native version: 57.1
* Plugin config:
      desiredAccuracy: 0,
      distanceFilter: 10,
      stopTimeout: 1,
      debug: true, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      enableHeadless: true,
      startOnBoot: true,

## Expected Behavior
Headless task should start to log events when app is terminated

## Actual Behavior
Nothing is currently being logged in the console. Added event listeners for ActivityChange and heartbeat, but nothing is being triggered by heartbeat or by activityChange when the GPS is being turned on and off.

## Steps to Reproduce
1. By using the example application in : https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-example
1.1 I added a render method to return the location of the device.
2. Follow the steps 1 and 2 as described by transistorsoft instructions for HeadlessTask : https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode
3. Do not use "BackgroundGeolocation.configure" instead, leave as in Step 1 example "BackgroundGeolocation.ready"
4. react-native run-android
5. close the app
6. Should start to see logs in console

## Context
HeadlessTask usage

## Debug logs ( Hope this chunk gives some perspective)
adb logcat

roid.launcher3.CustomizationPanelLauncher#1 (0xae069000): 1:24) 
09-26 14:35:12.852  1561  1561 I EntropyMixer: Writing entropy...
09-26 14:35:12.894  7550  8403 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
09-26 14:35:12.902 14615  8404 D CE-GmsVehicleService: ARC: ActivityRecognitionResult [probableActivities=[DetectedActivity [type=STILL, confidence=100]], timeMillis=1537986912867, elapsedRealtimeMillis=877781988]
09-26 14:35:13.030  7550  7634 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
09-26 14:35:13.103  7550  7634 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
09-26 14:35:16.706  8059  8391 W GCoreFlp: No location to return for getLastLocation()
09-26 14:35:22.987 14615  8415 D CE-GmsVehicleService: ARC: ActivityRecognitionResult [probableActivities=[DetectedActivity [type=STILL, confidence=100]], timeMillis=1537986922960, elapsedRealtimeMillis=877792081]
09-26 14:35:22.988  7550  8414 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
09-26 14:35:23.128  7550  7634 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
09-26 14:35:23.153  7550  7634 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO

-->

**Comment by christocracy** [comment]
Show me logs from `$ adb logcat -s TSLocationManager`

**Comment by nos-joel** [comment]
**reset: true** did the job. The first time I launched the app it didn't have the Headless task configuration. Eventually, when I attempted to perform the HeadlessTask, it read the configuration from the persistent storage, and not the configuration I provided, as expected according to the docs. It is working good.

I understand that there is no headless in iOS. What options to respond to this plugin events are available in iOS for when the app has been terminated? For example, What if I want to do something in particular when the user has entered in a geofence?

Thanks for all the help.

**Comment by christocracy** [comment]
As I suspected.

The nature of iOS is to relaunch the entire app in background when an event needs to be serviced (eg geofence, motionchange, background-fetch).  If you use push notifications, they too can cause an app to launch and service the notification.
