### ISSUE TITLE
Unable to fetch location after kill/closed the App in Android

### ISSUE THREAD

**Issue by bajrangsharma-burrp** [transistorsoft/react-native-background-geolocation#576]
## Plugin version:
"react-native-background-geolocation": "^2.12.1",

## Platform: 
Android

## OS version: 
7.1.1 

## Device manufacturer / model: 
CPH1729

## React Native version (react-native -v):
react-native-cli: 2.0.1
react-native: 0.52.0

## Plugin config:
stopOnTerminate: false,
startOnBoot: true,
locationUpdateInterval: 2 * 1000,
fastestLocationUpdateInterval: 2 * 1000,
forceReloadOnLocationChange: false,
forceReloadOnMotionChange: false,
forceReloadOnGeofence: false,

## Expected Behavior
This should be regularly fetch location after kill the app  

## Actual Behavior
Unable to fetch location after kill the app

## Steps to Reproduce
Above same steps

## Context
Trying with Headless mode

## Debug logs
No logs found

**Comment by bajrangsharma-burrp** [comment]
Thank you so much for your update...

**Comment by bajrangsharma-burrp** [comment]
Can you provide Demo App for this issue...

**Comment by DeepanshiGupta3** [comment]
Does location fetch works after kill/closed the app in Android when using the debug build without the license?

**Comment by christocracy** [comment]
>Does location fetch works after kill/closed the app in Android when using the debug build without the license?

Yes.
