### ISSUE TITLE
How often and how many times in total does the plugin retry posting data to server?

### ISSUE THREAD

**Issue by JohanArup** [transistorsoft/react-native-background-geolocation#578]
## Your Environment
* Plugin version: 2.13.3
* Platform: iOS or Android (both)
* OS version: iOS (10+) & Android (18+)
* Device manufacturer / model: N/A
* React Native version (`react-native -v`): 0.57.1
* Plugin config

As per the title, we'd like to know how often a post is retried for a single record with the following config

Url: https://ourserver...,
autoSync: true,
batchSync:false,
maxDaysToPersist: 30,
maxRecordsToPersist: -1,
stopOnTerminate: false,
startOnBoot: true,

// Android Only
foregroundService: true,

**Comment by christocracy** [comment]
With `maxRecordsToPersist: -1`, never.

**Comment by JohanArup** [comment]
That's confusing, as that is the default value for `maxRecordsToPersist`, which means unlimited records are stored.

> `maxRecordsToPersist` | Integer | -1 | Maximum number of records to persist in plugin's SQLite database.  Defaults to -1 (no limit). To disable persisting locations, set this to 0

Perhaps you thought `maxDaysToPersist` was set to -1.

**Comment by JohanArup** [comment]
To give you some more background, the plugin tracked my location as expected.  I lost internet connectivity (no WiFI nor mobile data, however the GPS was still on).  

It collected my location as expected, 150+ locations were stored (calling length on the results from `BackgroundGeolocation.getLocations()`).  

I eventually regained connected and the plugin didn't immediately sync my locations, which is fair, I imagine there's a scheduled service in the plugin for that.

I am also aware I can force sync using `BackgroundGeolocation.sync()`, however I wanted to understand what the plugins default behaviour is before going down that route.

Thanks.

**Comment by christocracy** [comment]
>With maxRecordsToPersist: -1, never

Yes, I was wrong.  You are correct. 

The plugin attempts sync in many events.
- boot
- suspend / resume
- background-fetch
- whenever a location is recorded.

**Comment by JohanArup** [comment]
Thanks for your help @christocracy.
