### ISSUE TITLE
Can I expect to receive at least one location with `is_moving` == false when transitioning to still?

### ISSUE THREAD

**Issue by david-cako** [transistorsoft/react-native-background-geolocation#579]
## Your Environment
* Plugin version: 2.13.3
* Platform: iOS
* OS version: 12
* Device manufacturer / model: iPhone X
* React Native version (`react-native -v`): 0.55.4
* Plugin config

```
{
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
stopTimeout: 5,
startOnBoot: true,
stopOnTerminate: false,
maxRecordsToPersist: 0,
heartbeatInterval: 60,
preventSuspend: true,
disableElasticity: true,
logLevel: 1
}
```

## Expected Behavior
I am trying to get always-running location reliably giving me 24/7 path data, as well as detecting stops using `is_moving` == false.  

The assumption I have been making is that I will *always* get at least one location entry with `is_moving` == false after the user has been still for 5 minutes.  

Is it possible to stay still for 5 minutes, trigger the activity-detection system, and thus *never* receive a location entry with `is_moving` == false for many hours after?

## Actual behavior
I am getting location entries with `is_moving` == false, but there are instances where I will be somewhere for hours and never record one (possibly the fault of my own logic -- trying to isolate it).

**Unrelated question:**
Is `preventSuspend` necessary for my use case?  I am consuming the locations with the `onLocation` event.  Does the geofencing guarantee that the app will be relaunched and no location data will ever be missed on an always-running, 24/7 basis, even with `preventSuspend` == false?

**Comment by david-cako** [comment]
Toying with stopDetectionDelay too.  Seems like that would give me a `x` minute window to receive `is_moving` == false entries?

**Comment by christocracy** [comment]
>Is it possible to stay still for 5 minutes, trigger the activity-detection system, and thus never receive a location entry with is_moving == false for many hours after?

If the device keeps experiencing movement / shaking, the `stopTimeout` will keep getting reset.

Are you aware of the `motionchange` event?

>Is preventSuspend necessary for my use case? 

No.  Have you read the [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

**Comment by david-cako** [comment]
>No. Have you read the Philosophy of Operation

Yes, I have spent a lot of time making sure I fully understand what's going on.

Is `is_moving` false during `stopDetectionDelay`?  If not, how is it different from `stopTimeout`?

I'm aware of the motionchange event but I'm wondering if it's possible to keep it all in the same pipeline.

**Comment by christocracy** [comment]
>Is `is_moving` false during stopDetectionDelay

No.
