### ISSUE TITLE
 GPS activation status when the GPS is started

### ISSUE THREAD

**Issue by invyctus92** [transistorsoft/react-native-background-geolocation#581]
When I start the gps, I can not control the activation status of the gps, in fact if the gps is disabled from the control panel, the process of the gps starts but obviously does not capture any position
## Your Environment
* Plugin version: 2.13.4
* Platform: Android
* OS version: 7.1.2
* Device manufacturer / model: oneplus x
* React Native version: 0.53.3
* Plugin config

## Expected Behavior
the method ready, reset and start do give the  GPS activation status 

## Actual Behavior
the method ready, reset and start do not give the  GPS activation status but give auth status

**Comment by christocracy** [comment]
Listen to [providerchange](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#providerchange) event *before* you execute `#ready`.

`providerchange` *always* fires at application boot.  It is fired when `#ready` is executed, so that you can learn the current state of location providers.

**Comment by invyctus92** [comment]
I tried but it does not work, it only works if the gps process is started and then gps is disabled. Here is the code, which I execute inside an ActionCreators in order to save the captured positions in the redux state.

`export function start(type, coef, threshold, navigation) {
  // uso getState cosi ho
  // variabili per sapere quante coordinate gps e attivita sono state catturate
  return function(dispatch, getState) {
    BackgroundGeolocation.on("providerchange", function(provider) {
      console.log("- Provider Change: ", provider);
      console.log("  enabled: ", provider.enabled);
      console.log("  gps: ", provider.gps);
      console.log("  network: ", provider.network);
      console.log("  status: ", provider.status);

      switch (provider.status) {
        case BackgroundGeolocation.AUTHORIZATION_STATUS_DENIED:
          // Android & iOS
          console.log("- Location authorization denied");
          dispatch(stop());
          break;
        case BackgroundGeolocation.AUTHORIZATION_STATUS_ALWAYS:
          // Android & iOS
          console.log("- Location always granted");

          break;
        case BackgroundGeolocation.AUTHORIZATION_STATUS_WHEN_IN_USE:
          // iOS only
          console.log("- Location WhenInUse granted");
          break;
      }
      if (!provider.gps) {
        dispatch(stop());
      }
    });

    BackgroundGeolocation.on("connectivitychange", function(event) {
      console.log(event);
      console.log(
        "- connectivitychange, network is connected? ",
        event.connected
      );
    });

    BackgroundGeolocation.ready(
      {
        reset: true,

        // Geolocation Config
        desiredAccuracy: 0,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.

        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.

        desiredAccuracy: 10,
        distanceFilter: 15,
        fastestLocationUpdateInterval: 5000,

        foregroundService: true,

        // ios
        stationaryRadius: 15,
        locationAuthorizationRequest: "Any",
        preventSuspend: true,
        // altro
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: false, // <-- Auto start tracking when device is powered-up.
        // HTTP / SQLite config
        // notificationColor: "#ee3333",

        notificationLargeIcon: "drawable/ic_launcher",
        notificationTitle: "MUV",
        notificationText: "Background tracking",
        saveBatteryOnBackground: false,
        notificationChannelName: "Location Tracker"
      },
      state => {
        console.log(
          "- BackgroundGeolocation is configured and ready: ",
          state.enabled
        );
        console.log(state);

        ////
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(
          function(state) {
            console.log("- Start success");
            console.log(state);

            console.log(
              "[INFO] BackgroundGeolocation service has been started"
            );
            dispatch(starton(type, coef, threshold));

            if (navigation !== null) {
              navigation.navigate("Track");
            }
          },
          () => {
            console.log("non parte");
          }
        );
      }
    );`

**Comment by christocracy** [comment]
`3.0.0` now has `getProviderState` method.
