### ISSUE TITLE
What is uuid in location template

### ISSUE THREAD

**Issue by iamchathu** [transistorsoft/react-native-background-geolocation#585]
## Your Environment
* Plugin version: ^0.24.0
* Platform: iOS
* OS version: 12.0
* Device manufacturer / model: iPhone X Simulator
* React Native version (`react-native -v`): react-native-cli: 2.0.1 / react-native: 0.57.3
* Plugin config: default in readme

## Expected Behavior

Unique ID for the device

## Actual Behavior

Unique ID for each location 

## Context

Get unique id for a device

**Comment by christocracy** [comment]
Have a look at the plugin logs.  You’ll see these uuid being referenced.

It’s a way for you to reference locations that arrived at your server with those in the logs when debugging tracking issues.

Also a way to ensure the plugin never sends you the same location twice (rare chance).

**Comment by iamchathu** [comment]
Thanks, @christocracy Is there a way to have device unique Id to identify the locations of a device?
