### ISSUE TITLE
What is the right way to use with background-fetch.

### ISSUE THREAD

**Issue by niocncn** [transistorsoft/react-native-background-geolocation#587]
What is the right way to use this module with react-native-background-fetch to send periodic locations if device is still mode?

**Comment by christocracy** [comment]
>if device is still mode?

“Mode”?

There’s no “right way”.  The plugin uses fetch for its own internal purposes.

You’re free to use fetch if you wish or not.  You don’t need to use it at all.

**Comment by niocncn** [comment]
i updated issue topic with example. You answered so quick.

**Comment by christocracy** [comment]
You know the plugin has its own http service.  Just give it an `#url` and it will handle uploading to your server automatically.

You’re free to do getCurrentPosition in the fetch callback.  I have no opinion on what you do with your fetch callback.

**Comment by niocncn** [comment]
Plugin will upload location only if device moving, i want periodic fetch locations to the server even if it does not move.

**Comment by christocracy** [comment]
> i want periodic fetch locations to the server even if it does not move.

That's fine.  You're free to do whatever you wish in your fetch callback.  I have no opinion on this.
