### ISSUE TITLE
iOS: Users whom enable "when in user" geo permission do not receive location updates.

### ISSUE THREAD

**Issue by theonetheycallneo** [transistorsoft/react-native-background-geolocation#588]
## Your Environment
* Plugin version:
```
2.13.4
```
* Platform: iOS or Android
```

```
* OS version:
```
iOS 9+
```
* Device manufacturer / model:
```
Any and all iOS devices
```
* React Native version (`react-native -v`):
```
react-native-cli: 2.0.1
react-native: 0.57.1
```
* Plugin config
```
if (!this._isReady) {
      await BackgroundGeolocation.ready({
        disableLocationAuthorizationAlert: true,
        disableMotionActivityUpdates: isAndroid() ? false : true,
        desiredAccuracy: isAndroid() ? 10 : 0,
        ...Platform.select({
          android: {
            distanceFilter: 25,
            stopTimeout: 1,
          },
          ios: {
            disableStopDetection: true,
            pausesLocationUpdatesAutomatically: false,
          }
        }),
        debug: false, // <-- enable hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: true, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: false, // <-- Auto start tracking when device is powered-up.
        batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
        allowIdenticalLocations: true,
        reset: true
      })
```

## Expected Behavior

We expect that users whom enable "when in use" permissions will still receive location updates while the app is open.

## Actual Behavior

Users whom enable "when in use" permissions receive a handful (2-5) location updates when the service is started, then never again while the app session is open.

## Steps to Reproduce

1. Launch app and enable geo permission with "when in use" mode
2. Note: we receive a handful of location updates upon bootstrap of geo plugin:
![img_2490](https://user-images.githubusercontent.com/367806/47044942-665bac80-d146-11e8-9bd7-f02731310239.jpeg)
3. Walk or drive more than 25m (we also have tested ubering across town)
4. Note: we never receive another location update while the app is foregrounded:
![img_2490](https://user-images.githubusercontent.com/367806/47044942-665bac80-d146-11e8-9bd7-f02731310239.jpeg)

## Context

We'd like to support both "always" and "when in use" for location services for our consumers.  We've also purchased the paid version react-native-background-geolocation-android.

## Debug logs

iOS Logs attached:
https://d.pr/free/f/abOnRB

**Comment by theonetheycallneo** [comment]
@christocracy Ok, so if we disable the motion sensor, then we will never receive location updates?

**Comment by christocracy** [comment]
>so if we disable the motion sensor, then we will never receive location updates?

Not true.  The iOS plugin doesn't rely on the motion-sensor.  It uses a Geofence to detect when the device is moving.

**Comment by christocracy** [comment]
And of course, the iOS Geofence-triggering mechanism won't work with `When in Use`.  iOS only monitors geofences in the background with `Always` authorization.

It is **impossible** for the plugin to automatically engage tracking in the background with `When In Use`.

**Comment by theonetheycallneo** [comment]
Closing this issue and moving to private repo.

**Comment by christocracy** [comment]
>Can you attach a working config for iOS "when in use" that will keep emitting location updates when user's travel >25m or whatever can work?

It's impossible.  The **only** way to track in the background with `When in Use` is to manually engage tracking mode while your app is **in the foreground** with `BackgroundGeolocation.changePace(true)`.  Your UI would have to have to UI button `[Start tracking]` that the user clicks.
