### ISSUE TITLE
Device didn't send any location when it back to running after stop for a long time.

### ISSUE THREAD

**Issue by patiphannn** [transistorsoft/react-native-background-geolocation#589]
## Your Environment
* Plugin version: 2.13.4
* Platform: Android
* OS version: 7
* Device manufacturer / model: samsung s5
* React Native version (`react-native -v`): 0.55.1
* Plugin config

// This handler fires whenever bgGeo receives a location update.
BackgroundGeolocation.on('location', this._onLocation);

// This handler fires when movement states changes (stationary->moving; moving->stationary)
BackgroundGeolocation.on('motionchange', this._onMotionChange);

// This event fires when a change in motion activity is detected
BackgroundGeolocation.on('activitychange', this._onActivityChange);

// This event fires when the user toggles location-services authorization
BackgroundGeolocation.on('providerchange', this._onProviderChange);

BackgroundGeolocation.ready({
  // Geolocation Config
  desiredAccuracy: 0,
  distanceFilter: 1,
  locationUpdateInterval: 500,
  fastestLocationUpdateInterval: 500,
  // Activity Recognition
  stopTimeout: 0,
  // Application config
  // debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
  stationaryRadius: 1, //iOS Only
  preventSuspend: true, //iOS Only
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  enableHeadless: true,
  stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
  startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
}, (state) => {
  console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

  if (!state.enabled) {
    ////
    // 3. Start tracking!
    //
    BackgroundGeolocation.start(function() {
      console.log("- Start success");
    });
  }
})

## Expected Behavior

Make it send location when device back to running after stop for a long time.

## Actual Behavior

Device didn't send any location to server when it back to running.

## Context

I try to get location when it back to running after stop for a long time.

**Comment by christocracy** [comment]
Plugin logs, please.

**Comment by christocracy** [comment]
What are you showing me in these 9 seconds of logs?

**Comment by chuchden** [comment]
I have same issue.
after stop long time. it stop tracking

**Comment by christocracy** [comment]
I need logs.  See wiki “Debugging”.  The plugin collect a massive amount of logs which can easily ask it for and attach the file here.

**Comment by christocracy** [comment]
Also see the initial comment for requested device/environment.  “Me too” is useless.

Plugin version: 2.13.4
Platform: Android
OS version: 7
Device manufacturer / model: samsung s5
React Native version (react-native -v): 0.55.1
Plugin config

**Comment by patiphannn** [comment]
This is plugin logs for two hours. https://gist.github.com/patiphannn/9726fdfaeeea2eb04f16f5010de0078d

At 11-14 16:12:19.595 it change from foreground to background, so how to make it to run foreground forever. Because background process its location not smooth and sometime param will be null in the background process ( Example : {"uid":null,"active":null,"email":null,"line":null,"number":null}).

**Comment by christocracy** [comment]
> it change from foreground to background, so how to make it to run foreground forever

The plugin *does* run forever on all my 6 test devices from Nexus 4 @ 4.4.4 -> Pixel @ 9.0.0.

Check your Samsung [Smart Manager](https://www.samsung.com/global/galaxy/what-is/smart-manager/) settings.

**Comment by christocracy** [comment]
@patiphannn You're using [`foregroundService: false`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#foregroundservice).  Set it to `true`.  Read the docs for it.

**Note:** In Android 8+, `foregroundService: true` is **enforced** due to strict new changes to Android's Background Execution Policy.

**Comment by patiphannn** [comment]
I have add foregroundService already but it working until the last line of plugin logs. After that it didn't work anymore.

This is my plugin logs and application config.
https://gist.github.com/patiphannn/017bbcf82b4b61e3a5c81da872f9f095 

BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: 0,
      distanceFilter: 1,
      locationUpdateInterval: 500,
      fastestLocationUpdateInterval: 500,
      // Activity Recognition
      stopTimeout: 0,
      // Application config
      // debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      stationaryRadius: 1, //iOS Only
      preventSuspend: true, //iOS Only
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      enableHeadless: true,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      foregroundService: true,
      autoSync: true,
      params: {
        uid: currentUser.uid,
        email: currentUser.email,
        car,
        pickerLine,
        isDriving,
        rounds
      }
      // disableStopDetection: true
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled)
      if (!state.enabled) {
        ////
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(function() {
          console.log("- Start success")
        })
      }
})

**Comment by christocracy** [comment]
@patiphannn The plugin is configured for [foregroundService: false](https://gist.github.com/patiphannn/9726fdfaeeea2eb04f16f5010de0078d#file-gistfile1-txt-L1769)

Read *carefully* the docs for [`#ready`](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#ready) method, particularly the bit about "`reset: true`".

>⚠️ Note:  The #ready method only applies the supplied Config for the first launch of the app — forever after, the plugin is going to remember every configuration change you apply at runtime (eg: setConfig) and reload that same config every time your app boots. Changes to the Config supplied to ready after first launch will not take effect. During development, it's helpful to provide reset true.
