### ISSUE TITLE
Can't run the application on a device.

### ISSUE THREAD

**Issue by unutranyholas** [transistorsoft/react-native-background-geolocation#59]
I created React Native init project and followed installation instructions. It's worked well on simulator, but when I run on iPhone, Xcode shows error message  "App installation failed. The application does not have a valid signature.". The same story with your demo app. 

It looks like issue with provisioning profiles and related stuff, but I have no idea how to fix it. There weren't any problems with other React Native packages. 

Do you have any idea how can I handle this?

**Comment by christocracy** [comment]
I have no problem here.

**Comment by cosmith** [comment]
Hi @unutranyholas, did you fix this? I have the same issue, can't install on device after adding the plugin.

Logs: 

```
Apr 13 11:22:31 iPhone-de-Ben streaming_zip_conduit[3968] <Warning>: ERROR: MobileInstallationInstallForLaunchServices returned nil
Apr 13 11:22:31 iPhone-de-Ben streaming_zip_conduit[3968] <Warning>: __dispatch_source_read_socket_block_invoke:203: Failed to install application at file:///var/mobile/Media/PublicStaging/Truckfly.app/ : Error Domain=LaunchServicesError Code=0 "The operation couldn’t be completed. (LaunchServicesError error 0.)" UserInfo=0x15e14de0 {Error=ApplicationVerificationFailed, ErrorDetail=-402620391, ErrorDescription=Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.HTl99F/extracted/Truckfly.app/Frameworks/TSLocationManager.framework identifier = com.transistorsoft.TSLocationManager type = 8> : 0xe8008019 (Application signature not valid)}
```
