### ISSUE TITLE
watchPosition Example

### ISSUE THREAD

**Issue by Boatly** [transistorsoft/react-native-background-geolocation#593]
## Your Environment
* Plugin version: 2.13.3
* Platform: iOS & Android
* OS version: 8.0.0
* Device manufacturer / model: Emulator
* React Native version (`react-native -v`): 0.55.4
* Plugin config

## Expected Behavior

n/a

## Actual Behavior

n/a

## Steps to Reproduce

n/a

## Context

I'm looking for some sample code that demonstrates how to correctly use watchPosition i.e. where to call it from, how to call it and how to stop it before the app enters the background.

**Comment by christocracy** [comment]
Use [AppState](https://facebook.github.io/react-native/docs/appstate) to determine when your app is in foreground / background.
