### ISSUE TITLE
Prevent Sending location data if accuracy is not less than a specified value

### ISSUE THREAD

**Issue by Lram90** [transistorsoft/react-native-background-geolocation#596]
## Your Environment
* Plugin version: 2.13.0
* Platform: iOS
* OS version: 12.0.1
* Device manufacturer / model: iPhone SE
* React Native version (`react-native -v`): 0.57.3
* Plugin config

        BackgroundGeolocation.on('location', this.onLocation.bind(this));
        BackgroundGeolocation.on('error', this.onError.bind(this));
        BackgroundGeolocation.on('motionchange', this.onMotionChange.bind(this));
        BackgroundGeolocation.on('activitychange', this.onActivityChange.bind(this));
        BackgroundGeolocation.on('providerchange', this.onProviderChange.bind(this));
        BackgroundGeolocation.on('http', this.onHttp.bind(this));

        BackgroundGeolocation.ready({
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH, // <-- have also tried 10 and DESIRED_ACCURACY_NAVIGATION
            distanceFilter: 10,
            debug: true, 
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,  
            elasticityMultiplier: 5, 
            preventSuspend: true,
            autoSync: true,
            url: 'https://*****************************',
            httpRootProperty: '.', 
            locationTemplate: '{ "lat":<%= latitude %>, "lng":<%= longitude %> }',

## Expected Behavior
Location data is sent to the server only if it meets a specified accuracy.

## Actual Behavior
Location data is sent no matter the accuracy

## Steps to Reproduce
1. Start application on device, or otherwise initialize background geolocation tracking.
2. React-Native-Background-Geolocation sends less accurate locations while GPS narrows down location
3. Any time tracking is stop, then resumes, less accurate locations are sent again

## Context
The Plugin is working fine, I just have a question. Is there a way to prevent location data from being sent to a server if the data is not within a certain level of accuracy?

**Comment by christocracy** [comment]
Not possible.  Filter them at server.
