### ISSUE TITLE
Change notification channel name (Android)

### ISSUE THREAD

**Issue by aikewoody** [transistorsoft/react-native-background-geolocation#597]
## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Nokia 8
* React Native version (`react-native -v`): 0.51.0
* Plugin config:
```
{
      reset: false,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
      distanceFilter: 0,
      stopTimeout: 0,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
      stopOnTerminate: false,
      startOnBoot: true,
      batchSync: false,
      autoSync: false,
      locationUpdateInterval: 60000,
      enableHeadless: false,
      heartbeatInterval: 3600,
      forceReloadOnHeartbeat: true,
}
```

## Expected Behavior
That there is an option, for example in the config, to set the name of the notification channel used in Android.

## Actual Behavior
This is not possible.

## Steps to Reproduce
1. Start the plugin with: `BackgroundGeolocation.ready(config)`
2. Go to the app specific notifications settings page.
3. Observe that there is an entry with the name 'TSLocationManager'.

## Context
The users of our app have the possibility to access the app specific notifications settings page directly from within the app. A lot of questions we get is why there is an entry with the name 'TSLocationManager'. That is why we would like to change this name to e.g. 'Location tracking'.

If it is not clear what settings page I'm talking about, see this screenshot:
![screenshot_20181024-144707_settings](https://user-images.githubusercontent.com/17004429/47618724-bdfb0000-dad6-11e8-9925-262fea429773.jpg)

## Debug logs
Does not apply.

**Comment by christocracy** [comment]
When in doubt, search docs.  eg: "notification".  You would find [`notificationChannelName`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#notificationchannelname)
