### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by machard** [transistorsoft/react-native-background-geolocation#6]
Hi,

I have a doubt about something :
I see it is possible to set up event listeners in the JS code but i was wondering if they would be triggered when the app is not open or when the phone is sleeping.
According to https://github.com/facebook/react-native/issues/1282, i am not so sure :/
What is your experience about it?

Thank you

**Comment by christocracy** [comment]
That doesn't apply here since the plugin uses a UIBackgroundMode
"location", granting the app permission for continuous background running
(while the plugin is in "active state"; ie: while device is moving)

The plugin has a "passive, stationary state", where it turns off continuous
updates.  In this case, what that link says does apply, where as soon as
the app is put in background, iOS immediately suspends the app.

I know exactly how iOS operates in these situations.  This module is not
new.  It was born in the Cordova universe over 2 years ago
attracting thousands of users.

On Monday, September 7, 2015, Matthieu Achard <notifications@github.com>
wrote:

> Hi,
>
> I have a doubt about something :
> I see it is possible to set up event listeners in the JS code but i was
> wondering if they would be triggered when the app is not open or when the
> phone is sleeping.
> According to facebook/react-native#1282
> <https://github.com/facebook/react-native/issues/1282>, i am not so sure
> :/
> What is your experience about it?
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/6>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
I should add, that while the plugin is in stationary state, it keeps a
stationary-geofence monitored, as well as iOS significant changes API
running.

These APis are allowed by iOS to awaken a suspended app when an event
occurs.  My module uses these events as a switching mechanism, toggling to
the active-state.

On Monday, September 7, 2015, Chris Scott <christocracy@gmail.com> wrote:

> That doesn't apply here since the plugin uses a UIBackgroundMode
> "location", granting the app permission for continuous background running
> (while the plugin is in "active state"; ie: while device is moving)
>
> The plugin has a "passive, stationary state", where it turns off
> continuous updates.  In this case, what that link says does apply, where as
> soon as the app is put in background, iOS immediately suspends the app.
>
> I know exactly how iOS operates in these situations.  This module is not
> new.  It was born in the Cordova universe over 2 years ago
> attracting thousands of users.
>
> On Monday, September 7, 2015, Matthieu Achard <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Hi,
>>
>> I have a doubt about something :
>> I see it is possible to set up event listeners in the JS code but i was
>> wondering if they would be triggered when the app is not open or when the
>> phone is sleeping.
>> According to facebook/react-native#1282
>> <https://github.com/facebook/react-native/issues/1282>, i am not so sure
>> :/
>> What is your experience about it?
>>
>> Thank you
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/react-native-background-geolocation/issues/6>
>> .
>>
>
>
> --
> Snet form Gmail Mobile
>


-- 
Snet form Gmail Mobile

**Comment by machard** [comment]
- Ok so i understand that when the app goes in background I should disable the "passive, stationary state" to keep it running. is it possible ?

When i use stopOnTerminate: false and i exit the app i understand events will still be fired by the system and catched by your obj-c plugin. Then you will fire an event to the JS though RN bridge.
So i can be confident that React Native will restore the bridge allowing the JS code to run the registered callbacks ? (this link may represent better what my interrogation is : https://github.com/facebook/react-native/issues/1660).

**Comment by christocracy** [comment]
>
>    - Ok so i understand that when the app goes in background I should
>    disable the "passive, stationary state" to keep it running. is it possible ?
>
> Very bad idea.  You will kill the battery in a few hours.  And unless
you're making an app that requires bg tracking (eg: fleet tracking app,
fitness app) Apple will deny your app.

So i can be confident that React Native will restore the bridge allowing
> the JS code to run the registered callbacks ? (this link may represent
> better what my interrogation is : facebook/react-native#1660
> <https://github.com/facebook/react-native/issues/1660>).
>

That I don't know.  That a framework problem.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/6#issuecomment-138259709>
> .
>


-- 
Snet form Gmail Mobile

**Comment by machard** [comment]
Ok thank you.
Yes indeed I was questionning the framework more than what you did. As you already played with both background geo loc and react native i thought i would ask.

However i don't understand why the bg tracking is allowed when the app is closed but not when it is in background ?

**Comment by christocracy** [comment]
It's not that bg tracking is allowed when app is closed, it's that iOS
persists geofence & significant changes monitoring in spite of app being
"closed".

An iOS app is never really "closed" in the strict sense.

Again, if an event occurs on these 2 APIs, iOS will awaken the app the
receive the event.  My plugin uses these events as a mechanism to change
state to "active monitoring"

On Monday, September 7, 2015, Matthieu Achard <notifications@github.com>
wrote:

> Ok thank you.
> Yes indeed I was questionning the framework more than what you did. As you
> already played with both background geo loc and react native i thought i
> would ask.
>
> However i don't understand why the bg tracking is allowed when the app is
> closed but not when it is in background ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/6#issuecomment-138264623>
> .
>


-- 
Snet form Gmail Mobile
