### ISSUE TITLE
Battery Draining Issue when setting accuracy as 0

### ISSUE THREAD

**Issue by manojkumaraut** [transistorsoft/react-native-background-geolocation#602]
Team, 
I am using  react-native-background-geolocation version ~2.9.4. 

    BackgroundGeolocation.configure({
        **desiredAccuracy: 0,**
        stationaryRadius: 5,
        distanceFilter: 5,
        debug: false,
        startOnBoot: false,
        stopOnTerminate: false,
        locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
        interval: 10000,
        fastestInterval: 5000,
        activitiesInterval: 10000,
        stopOnStillActivity: false,
        geofenceInitialTriggerEntry: false

   Here the desired accuracy as 0,but the battery drains too fast .... do we have any fix to overcome this issue . Thanks and appreciate your help

**Comment by christocracy** [comment]
You're not specifying *Android* or *iOS* (you ignored the issue template, which always annoys me).

Only `desiredAccuracy: 0` enables GPS.  If you need GPS accuracy, you must use `0`.

The biggest consumer of battery tends to be HTTP requests.  Your `distanceFilter: 5` is *very* aggressive.

To conserve battery, make fewer http requests (this goes for your entire app, not just those HTTP requests the plugin makes).

- Increase `distanceFilter`
- Use [`autoSyncThreshold`](https://github.com/transistorsoft/react-native-background-geolocation/tree/2.9.4/docs#config-integer-autosyncthreshold-0) to throttle HTTP uploads.
- Use `batchSync: true` to post multiple queued locations into a single HTTP request.

**Comment by manojkumaraut** [comment]
Thanks Chris, if we upgrade our older version of licensed   react native background geolocation  with below as combination of

React Native : 0.47.0 
react native background geolocation  :2.14.0

Will this react native version affect the app

**Comment by christocracy** [comment]
As I said in chat, I don't know what issues you might have using `2.14.0` with react-native@0.47.0
