### ISSUE TITLE
you have a syntax error in your READ.ME.

### ISSUE THREAD

**Issue by CorentinDupont** [transistorsoft/react-native-background-geolocation#603]
you have a syntax error in your READ.ME, wich will produce error : React native  TypeError: _reactNativeBackgroundGeolocation2.default.oActivityChange is not a function.

Here's a screen : 

![syntax error in read me](https://user-images.githubusercontent.com/25986612/47867536-134e4e80-de02-11e8-8d5a-36dc2852de57.png)

**Comment by christocracy** [comment]
It’s not a syntax error.  It’s assumed you’d implement those functions referenced.
