### ISSUE TITLE
background-geolocation conflict with onesignal silent notification

### ISSUE THREAD

**Issue by chuchden** [transistorsoft/react-native-background-geolocation#606]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 7
* Device manufacturer / model: Samsung
* React Native version (`react-native -v`): 0.57.3
* Plugin config

## Expected Behavior
It  should get object console.log(notif)

## Actual Behavior
No thing out

## Steps to Reproduce

1. Compile (react-native run-android) 
2. send test notif is working fine
3. swipe out app (closed it))
4. reopen 
5. send test notif nothing 

---
* Comment out background geolocation
* Remove app 
* Compile again 
* swipe out app
* reopen
* send test notif working fine without background geo

**Comment by christocracy** [comment]
Logs from `$ adb logcat` are *always* the first thing you observe (for both cases).

The plugin has nothing all to do with any kind of notification dependency.

**Comment by christocracy** [comment]
Closed for lack of feedback.
