### ISSUE TITLE
Call removeGeofence from Firebase Cloud Function

### ISSUE THREAD

**Issue by James-Big-Space** [transistorsoft/react-native-background-geolocation#607]
## Your Environment
* Plugin version: 2.13.3
* Platform: iOS and Android
* OS version: n/a
* Device manufacturer / model: n/a
* React Native version (`react-native -v`): 0.55.4
* Plugin config:
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 50,
    // Activity Recognition
    stopTimeout: 1,
    // Application config
    debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: true, // <-- Allow the background-service to continue tracking when user closes the app.
    startOnBoot: false,

## Expected Behavior
Call the removeGeofence method to remove a geofence of a certain ID. This would be called from a firebase cloud function.

## Actual Behavior
Firebase cloud functions will not deploy due to the import/export statements throughout the code

## Context
I would like to add a geofence from a phone with a scheduled end time. At this time a Firebase cloud function is scheduled to run and delete a certain entry from my firebase database, at this time I would like the cloud function to call the removeGeofence method. Is it possible to install and call this react-native-background-geolocation method from the cloud function node environment? Or is there another way of scheduling this call to take place?

**Comment by christocracy** [comment]
Why don't you send a "silent" push notification from your cloud function.  I tried this myself as a test once and it worked.

Send a message to the device, like:
```
{
  "action": "removeGeofence": 
  "identifier": "GEOFENCE_IDENTIFIER"
}
```

On the client device:
```javascript
onNotification(notification) {
  if (notification.action) {
    let action = notification.action;
    if (action === 'removeGeofence') {
      BackgroundGeolocation.removeGeofence(notification.identifier);
    }
  }
}
```

**Comment by James-Big-Space** [comment]
Thank you, this approach has worked well after setting up background message handlers as well. Closing this issue.

**Comment by christocracy** [comment]
Have you tried my Firebase adapter for the plugin?

https://medium.com/@transistorsoft/new-feature-firebase-adapter-b28361d05560?source=linkShare-cd6de7ea2f98-1541631922

Are you using Firestore?

**Comment by James-Big-Space** [comment]
I am using Firestore and have not yet tried the firebase adaptor. 

I may be confused about how the geofences actually work. If I call addGeofence on 1 phone using the app, is that geofence only active and monitored for that phone or for all phones using the app?

I need it to be monitored for all users of the app if uploaded by 1 user. What would be the best solution for this?

**Comment by christocracy** [comment]
> If I call addGeofence on 1 phone using the app, is that geofence only active and monitored for that phone or for all phones using the app?

The SDK known *only* about the device it's running on.  It has no awareness of any other device.

>I need it to be monitored for all users of the app if uploaded by 1 user. What would be the best solution for this?

You must execute `#addGeofence` for every device.  How you do that is not within the scope of the SDK.  That's an application problem.  Presumably you'd have each device execute an HTTP request to a server asking for geofences.

**Comment by James-Big-Space** [comment]
So I could create a part of Firestore with a list of geofences that I want to be present for all users. If I listen to this data and run addGeofence on all new data and run removeGeofence when a document is removed from the collection then BackgroundGeolocation will be able to monitor all off these geofences? Because there will be more than the max number supported by each platform. Does the module take care of this, and does geofencesChange need to be used at all for this?

**Comment by christocracy** [comment]
>So I could create a part of Firestore with a list of geofences that I want to be present for all users

Yes.

> Does the module take care of this

Yes.  See docs for [Geofencing Guide](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.geofence.html)
