### ISSUE TITLE
IOS - start services with heartbeat only

### ISSUE THREAD

**Issue by rstims** [transistorsoft/react-native-background-geolocation#609]
First off I'd like to thank you for this amazingly comprehensive location plugin, cheers!

This is more of a question.  On iOS, Is there a way to start the plugin with only the heartbeat.  My thought is that I don't want them to have to authorize `Always` allowing location tracking, but `WhenInUse` instead, and then grab their location when a heartbeat event occurs.  This would be so the blue navigation bar wouldn't show constantly while they are using the app normally, but I could still passively obtain their location.

**Comment by christocracy** [comment]
There is no way to execute `heartbeat` events until you've executed `#start`.

Once `#start` is called, permission is requested.

>On iOS, Is there a way to start the plugin with only the heartbeat

No.
