### ISSUE TITLE
BackgroundGeolocation start android activity intent

### ISSUE THREAD

**Issue by chuchden** [transistorsoft/react-native-background-geolocation#614]
## Your Environment
* Plugin version: 0.57.3
* Platform: Android
* OS version: 8
* Device manufacturer / model: Samsung
* React Native version (`react-native -v`): 0.57.3
* Plugin config

## Expected Behavior

Start app from notification receive.
## Actual Behavior

I can hear sound beb... , but app not start
## Steps to Reproduce

1. Closed app / Kill app
2. Send notification from onesignal
3. Hearing sound 
4. Location update to db perfectly
5. Suggest it start app too

## Context

Start app onReceive notification when app closed.
Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_NEW_TASK

**Comment by christocracy** [comment]
If you want to force-launch the `MainActivity`, you must use the plugin's [forceReloadOnXXX](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#forcereloadonboot) config options.

**Comment by chuchden** [comment]
Great thanks. Many many options as I need. Your  plugin done my project 99%.
