### ISSUE TITLE
Android OS killing my app sometime

### ISSUE THREAD

**Issue by chuchden** [transistorsoft/react-native-background-geolocation#615]
## Your Environment
* Plugin version: 0.57.3
* Platform: Android
* OS version: 8
* Device manufacturer / model: Huawei
* React Native version (`react-native -v`): 0.57.3
* Plugin config

## Expected Behavior

Keep my app running in background 24 hours
## Actual Behavior

It killing my app sometime due to background geo tracking
## Steps to Reproduce

1. Start app
2. Give it some time
3. OS kill my app
4. Can't track location (App is dead)

## Context

Keep app running in background without kill.

**Comment by chuchden** [comment]
![46479446_558882751203548_1571553714999656448_n](https://user-images.githubusercontent.com/3120637/48655727-5426a400-ea4d-11e8-876e-a5317714d24b.jpg)

**Comment by christocracy** [comment]
Huawei are well known to have horrible behaviour when it comes to background-services.  See #611
