### ISSUE TITLE
Android geofencing

### ISSUE THREAD

**Issue by Richi2293** [transistorsoft/react-native-background-geolocation#617]
## Your Environment
* Plugin version: 2.14.1
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: OnePlus 3T
* React Native version (`react-native -v`): 
react-native-cli: 2.0.1
react-native: 0.56.0
* Plugin config:

`desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0,
            stationaryRadius: 10,
            foregroundService: true,
            stopTimeout: 1,
            debug: true, 
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            enableHeadless: true,
            stopOnTerminate: false,   
            startOnBoot: true,       
            preventSuspend: true,
            allowIdenticalLocations: true,
            url: 'http://192.168.1.173:3125',
            batchSync: false,      
            autoSync: false,        
            headers: {           
                "X-FOO": "bar"
            },
            params: {               
                "auth_token": "maybe_your_server_authenticates_via_token_YES?"
            },
            disableMotionActivityUpdates: true,
            reset: true`

## Expected Behavior
The app if it is in foreground or in the background must detect when the device enters or exits in certain areas.

## Actual Behavior
Currently it does not seem to work in foreground or in the background, but for a few minutes it worked. I also tried to make more rails of the device.

## Context
The objective is to use only the geofencing function, ie to determine when it exits and enters some dynamically set areas.

## Debug logs
to attach later.

## Other infos
- I have already configured the zone data array and loads it well.
- the headless task is configured well. For example i see the event 'location' and 'activitychange'
- on the battery section of device i disabled the optimize app

As I wrote above, for a few minutes it worked and in the logs I saw the ENTER and EXIT events of the zones.

**I'm trying with Lockito to simulate geolocation. Maybe I should do physical tests without the mock location?**

Example logs:
https://drive.google.com/open?id=1_9440BFK4b5mH2QloUDHSVxrgijLUM6k
https://drive.google.com/open?id=1RCNYqkZVFrXhRE6CZIQummnC5Ftp7jcS

**Comment by christocracy** [comment]
Geofences don't work with mocked location.  Go out in the real world.

**Comment by Richi2293** [comment]
Ok i will try to debug in the real world on android device.
Suggestions on how I could test it better?
That is, I take a ride and then after finish connect the phone to watch the logs on computer?

**Comment by christocracy** [comment]
You can always create a geofence around your current position in the office.

`#stop` then `#start` will fire the geofence.

You can also configure your app to post to my demo server.  It's quite nice for viewing geofence events.

See method [`transistorTrackerParams`](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#transistortrackerparams)

**Comment by Richi2293** [comment]
I did some tests, on android it does not work on ios, even when I try from home it works and I even receive notifications that warn the event ENTER/EXIT region.

Ideas of what could I have done wrong on android?
I will try to do some tests on your demo server

**Comment by christocracy** [comment]
Your configured url is **incorrect**.

Set your `url: "http://tracker.transistorsoft.com/locations/locations/richi93"`

To **VIEW** your tracking in web app, it's
http://tracker.transistorsoft.com/richi93

- You **POST** to `/locations/username`
- You **VIEW** as just `/username`

**Comment by christocracy** [comment]
>I think there is something wrong, on ios it returns this error:
```
[] nw_connection_get_connected_socket 1013 Connection has no connected handler
TCP Conn 0x1c416e1c0 Failed : error 0:61 [61]
```

The plugin has nothing to do with "Sockets".  This is most likely an error from the React Native development server which *does* use sockets.

**Comment by Richi2293** [comment]
Ok thanks for the answers, this is my new configuration:

![image](https://user-images.githubusercontent.com/5848941/48855456-5faefd80-edb4-11e8-9daa-b41952fd3ecb.png)

I tried on ios device simulating the position with xcode and at the address "http://tracker.transistorsoft.com/richi93" you can see anything. 
It may be that only with the "startGeofences" command is the position not continuously drawn?

**Comment by christocracy** [comment]
>It may be that only with the "startGeofences" command is the position not continuously drawn?

`#start` = location tracking + geofence monitoring.
`#startGeofences` = geofence monitoring **ONLY**.

**Comment by Richi2293** [comment]
On iOS it would seem that it doesn't work even if I start with the "start" method. (location tracker on server demo).

On android seems to works (it load one 'motionchange' event on demo server).

So to understand if geofencing works well you suggest me to use the demo server in this way?

**Comment by christocracy** [comment]
You're doing something wrong if you can't get iOS geofences to fire in the simulator.  They 100% work all the time.  

Are you observing running your app in XCode so you can observe the logs?  Show me.

**Comment by KowalskiP** [comment]
I have the same issue with geofence 'ENTER' event triggered twice in a row.
It's appear on iOS and Android both.
Config of plugin:
```
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =    {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didLaunchInBackground = 0;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 100;
    elasticityMultiplier = "0.1";
    enableTimestampMeta = 0;
    enabled = 1;
    encrypt = 0;
    extras =    {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers = {hidden};
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =    {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "3106.715235818895";
    params =    {
    };
    pausesLocationUpdatesAutomatically = 0;
    persistMode = 2;
    preventSuspend = 1;
    schedule =    (
    );
    schedulerEnabled = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 5;
    trackingMode = 1;
    url = "hidden";
    useSignificantChangesOnly = 0;
}
```
Geofence point is installed once.

**Comment by christocracy** [comment]
Where are your logs *from the plugin* showing this?

**Comment by KowalskiP** [comment]
```
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: Item-20438
╚═══════════════════════════════════════════════════════════

2019-12-09 12:03:28.480 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: 03A65908-6B3B-4147-A402-A51264DC1998

2019-12-09 12:03:28.480 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2019-12-09 12:03:28.480 ⚠️-[TSHttpService flush:] Busy with previous request

2019-12-09 12:03:28.481 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: Item-20443
╚═══════════════════════════════════════════════════════════

2019-12-09 12:03:28.482 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: 0110E13B-5685-4717-9222-ED231A8FB8FB

2019-12-09 12:03:28.482 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2019-12-09 12:03:28.482 ⚠️-[TSHttpService flush:] Busy with previous request

2019-12-09 12:03:28.482 ✅-[BackgroundTaskManager createBackgroundTask] 140

2019-12-09 12:03:28.527 ℹ️-[TSLocationManager log:message:] LocationService::onLocation [object Object]

2019-12-09 12:03:28.527 ℹ️-[TSLocationManager log:message:] LocationService::onLocation [object Object]

2019-12-09 12:03:28.536 ℹ️-[TSLocationManager log:message:] LocationService::onGeofence [object Object] Item-20438 ENTER

2019-12-09 12:03:28.593 ℹ️-[TSLocationManager log:message:] LocationService::onGeofence [object Object] Item-20438 ENTER

2019-12-09 12:03:28.746 ℹ️-[TSLocationManager log:message:] LocationService::onGeofence [object Object] Item-20443 ENTER

2019-12-09 12:03:28.808 ✅-[TSHttpService post:]_block_invoke DESTROY: E4DD560D-74E5-45AE-8C30-EA8314179D0C

2019-12-09 12:03:28.809 ✅-[TSHttpService schedulePost] LOCKED: 03A65908-6B3B-4147-A402-A51264DC1998

2019-12-09 12:03:28.843 ℹ️-[TSLocationManager log:message:] LocationService::onGeofence [object Object] Item-20443 ENTER
```
There is only single geofence listener but geofence event comes to JS twice

**Comment by christocracy** [comment]
Those logs show *2 different geofences firing*.

**Comment by KowalskiP** [comment]
Look at Item-20438 - enter geofence is single, but it's appear twice in JS

**Comment by christocracy** [comment]
ENTER Geofence: Item-20438

2 ms later...

ENTER Geofence: Item-20443

**Comment by KowalskiP** [comment]
but
```

2019-12-09 12:03:28.536 ℹ️-[TSLocationManager log:message:] LocationService::onGeofence [object Object] Item-20438 ENTER

2019-12-09 12:03:28.593 ℹ️-[TSLocationManager log:message:] LocationService::onGeofence [object Object] Item-20438 ENTER
```
