### ISSUE TITLE
[Question] When rester odometer may fail?

### ISSUE THREAD

**Issue by lorenc-tomasz** [transistorsoft/react-native-background-geolocation#619]
Hi,
when resetodometer and other mothods connected with odometer may fail?

**Comment by christocracy** [comment]
`resetOdometer` does a `getCurrentPosition` so it can determine the reference location where the odometer was zeroed.

If `getCurrentPosition` fails (ie: the device failed to provide a location), `resetOdometer` will fail.

**Comment by Udbhav12** [comment]
@christocracy Does odometer gets reset when `BackgroundGeolocation.stop()` or `BackgroundGeolocation.removeListeners()` is called ?

**Comment by christocracy** [comment]
The SDK **never** automatically resets the odometer.

**Comment by Udbhav12** [comment]
Ok,If device GPS is turned off & I call 'resetOdometer' then it fails with error as '1'

Is there any way to hard reset odometer irrespective of whether the getCurrentPosition was successfully executed or not ?

**Comment by christocracy** [comment]
>Is there any way to hard reset odometer irrespective of whether the getCurrentPosition was successfully executed or not ?

No.

**Comment by Udbhav12** [comment]
`getOdometer` method computes the distance between the current location and last and maintains the sum.

This distance which is calculated between current location and last is the aerial distance (Calculated using Haversine/Great Circle distance formula) or the actual distance ?

**Comment by christocracy** [comment]
Haversine is pointless for small distances.

The plugin uses native methods on iOS / Android Location classes to calculate distance.

**Comment by Udbhav12** [comment]
Is this plugin using `DistanceMatrix` API ?
