### ISSUE TITLE
Android location permission request on first boot

### ISSUE THREAD

**Issue by Christian-Athom** [transistorsoft/react-native-background-geolocation#620]
## Description
On first boot of the app, a location permission request is displayed for android, before even starting of configuring the service

## Your Environment
* Plugin version: 2.14.2
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung S7
* React Native version (`react-native -v`): 0.56.1
* Plugin config

{
  disableMotionActivityUpdates: true, // To prevent the motion permission
  locationAuthorizationRequest: 'Always',
  debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
  startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
  geofenceInitialTriggerEntry: false,
  enableHeadless: true, //<- android background task
 }

## Expected Behavior
The premission request should only be presented when activating (start / startGeofences) the service

## Actual Behavior
The permission is requested on first boot of the app

**Comment by christocracy** [comment]
The plugin does **not** request permission until you *ask it* fetch a location.
- `#getCurrentPosition`
- `#watchPosition`
- `#start`
- `#startGeofences`

If you're seeing a permission request before executing any of the above methods, it must be due to some other plugin (eg:  a maps component)

**Comment by banduk** [comment]
@christocracy The plugin requests permission when calling `#start` even with this config?

```
useSignificantChangesOnly: true,
disableMotionActivityUpdates: true,
locationAuthorizationRequest: 'Any',
disableLocationAuthorizationAlert: true,
```

If yes, how can I track location only using significant changes without asking for permission? Is there a way to do that? I was planning to use significant changes until the user clicks in a banner which tells that would be better to provide location permissions.

Thanks

**Comment by christocracy** [comment]
@ Mauricio 

>if yes, how can I track location only using significant changes without asking for permission? Is there a way to do that? I was planning to use significant changes until the user clicks in a banner which tells that would be better to provide location permissions

You don't get to access the user's permission unless *they say* you can.  Yes, you **must** request location permission.  You don't get the secretly track a user *ever*.

**Comment by banduk** [comment]
@christocracy Sorry I deleted the message cause I noticed there was a better place for it (https://github.com/transistorsoft/react-native-background-geolocation/issues/497). But to help people that get here I'll post it again. Fell free to delete it.
Thanks again
---------------------------------------------------------------------------
@christocracy The plugin requests permission when calling `#start` even with this config on iOS?

```
useSignificantChangesOnly: true,
disableMotionActivityUpdates: true,
locationAuthorizationRequest: 'Any',
disableLocationAuthorizationAlert: true,
```
If yes, how can I track location only using significant changes without asking for permission? Is there a way to do that?
I was planning to use significant changes until the user clicks in a banner which launch the flow that asks for permissions explaining why the permission is important. Is there a way to do that?
I was wondering if when calling `#ready` the plugin starts collecting significant changes.

Thanks

**Comment by banduk** [comment]
@christocracy could you help me here, please??

**Comment by mikehardy** [comment]
it is my understanding that useSignificantChangesOnly is easier on the battery, and easier to pass app store review, but is *still* location tracking. So you must have permission. https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html#//apple_ref/doc/uid/TP40009497-CH2-SW16

**Comment by christocracy** [comment]
Yes, of course you need permission.

**Comment by mikehardy** [comment]
and I just realized I posted iOS documentation - wrong platform, sorry, but does still apply apparently, thanks :-)
