### ISSUE TITLE
State.enabled is true

### ISSUE THREAD

**Issue by vdongbin** [transistorsoft/react-native-background-geolocation#622]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 6.0
* Device manufacturer / model: nexus 5
* React Native version (`react-native -v`): 0.57
* Plugin config

## Expected Behavior

State.enabled is true. so start method is not working and background onLocation is not working
## Actual Behavior

ready => start => onLocation 
## Steps to Reproduce

1.
2.
3.
4.

## Context

componentWillMount() {
    BackgroundGeolocation.onLocation(this.onLocation, this.onError);

    BackgroundGeolocation.ready(
      {
        reset: true
      },
      state => {
        console.log(
          '- BackgroundGeolocation is configured and ready: ',
          state.enabled
        );

        if (!state.enabled) {
          ////
          // 3. Start tracking!
          //
          BackgroundGeolocation.start(function() {
            console.log('- Start success', state.enabled);
          });
        }
      }
    );
  }

**Comment by christocracy** [comment]
I doubt there’s a problem here; more likely a misunderstanding of the plugin’s Philosophy of Operation.

Are you watching the logs?  See wiki “Debugging”.

**Comment by christocracy** [comment]
Closed for lack of feedback.

**Comment by Jacky9425** [comment]
does it mean that when `state.enabled` is `true`, it is indicating moving state while `false` indicating device/user is at stationary state?

**Comment by christocracy** [comment]
No, that would be state.isMoving.

state.enabled represents whether the power button is on or off.

**Comment by Jacky9425** [comment]
i see, so the block of code under `!state.enabled` means to fire background tracking?
is an instance of tracking already started when `state.enabled === true`?

**Comment by christocracy** [comment]
Executing #start within the callback to #ready is generally not required.  It’s only there for example purposes.

One would normally execute #start programmatically, for some event, like login success, or “beginning a delivery job”, etc.

If you were making a jogging app, you’d offer [start workout] / [stop workout] buttons, where the user would have explicit control to #start / #stop the plugin as they desire.

One the plugin’s #start method is called (ie “pressing the power button on”), state.enabled Is set to true.

The plugin persists its state **throughout app relaunches / device reboots — It will stay enabled forever until you #stop**

When you call #ready, the plugin *automatically* enters its last known state.
