### ISSUE TITLE
[Improvements] Allow to get current state of GPS provider and to request location permissions on demand

### ISSUE THREAD

**Issue by lorenc-tomasz** [transistorsoft/react-native-background-geolocation#623]
Now to get current state of GPS provider we need to listen to onProviderChange event. However sometimes is good to have possibility to get this state ad-hoc without needing of saving the changes provided by onProviderChange event. Also It would be great to have methods that allows us to ask for location permission and get response in Promise / callback - the same for Android and for iOS. e.g.

BackgroundGeolocation.getProviderState(successCallback, errorCallback);
BackgroundGeolocation.requestPermssion(successCallback, errorCallback);

**Comment by christocracy** [comment]
For learning provider state, just listen to `onProviderChange` and `setState`.

For requesting permission, just `#getCurrentPosition` or `#start` the plugin.

**Comment by lorenc-tomasz** [comment]
I know that, those two additional methods will be great improvement. The mentioned solutions are not the "cleanest" ones. More like workarounds.

**Comment by christocracy** [comment]
I don't see a problem with the current implementation.  I think you're just being paranoid.

**Comment by christocracy** [comment]
If you want specific control over permissions, there is an existing module [react-native-permissions](https://github.com/yonahforst/react-native-permissions)

**Comment by lorenc-tomasz** [comment]
More or less not maintained library. BTW, I'm not a paranoid ;) Simple the clear API will be very helpful. For Android we can you the one from RN, but for iOS there is no clear way to do the same. And it's great to be able to make action based on user actions. 

RequestPermssion.then('do A').catch('do B') without additional listeners.

**Comment by lorenc-tomasz** [comment]
Those two methods are the last that will make this library full and complete.

**Comment by christocracy** [comment]
I'll see what I can do.

**Comment by christocracy** [comment]
Try installing latest version.  Added methods `getProviderState`, `requestPermission`

**Comment by lorenc-tomasz** [comment]
Checked, and it works OK :) However don't understand why AUTHORIZATION_STATUS_WHEN_IN_USE is threaded as rejected, but this is not a big deal. Thanks :)

**Comment by christocracy** [comment]
Because you configure locationAuthorization: “Always”.

If you want to accept both, set it to “Any”.  See the docs for that option,

**Comment by akhileshagrhari** [comment]
@lorenc-tomasz. can you please give me an example code of using getProviderState() method. I got stuck on this method.

**Comment by christocracy** [comment]
@akhileshagrhari The method `getProviderState` didn't arrive until [`3.0.0`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#300-beta1---2019-02-27).

Upgrade to latest [3.0.0-rc.5](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#300-rc5---2019-03-31)

**Comment by akhileshagrhari** [comment]
@christocracy  I'm using the latest one i.e 3.0.0-rc.5

**Comment by christocracy** [comment]
Define “I got stuck on this method”.
