### ISSUE TITLE
[Android] Fatal Exception on TSProviderChangeRequest com.transistorsoft.locationmanager.location.TSProviderChangeRequest$SingleLocationRequest$Builder$1.build 

### ISSUE THREAD

**Issue by lorenc-tomasz** [transistorsoft/react-native-background-geolocation#624]
On production we had this fatal Exception mentioned below. To be honest I don't know how to reproduce this bug as it never happened before. 

Crashlytics:
TSProviderChangeRequest
com.transistorsoft.locationmanager.location.TSProviderChangeRequest$SingleLocationRequest$Builder$1.build 

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
com.transistorsoft.locationmanager.location.TSProviderChangeRequest$SingleLocationRequest$Builder$1.build (Unknown Source:27)
com.transistorsoft.locationmanager.location.TSLocationManager.watchPosition (Unknown Source:8)
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$5.run (Unknown Source:8)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
java.lang.Thread.run (Thread.java:764)

## Your Environment
* Plugin version: 2.14.2
* Platform: Android 
* OS version: 8.0
* Device manufacturer / model: Samsung SM-G955F and SM-G950F
* React Native version (`react-native -v`): 0.57.5

**Comment by christocracy** [comment]
Show me your config

**Comment by lorenc-tomasz** [comment]
Here:
`  // [Geolocation] Common Options
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
  distanceFilter: 30,
  // [Geolocation] iOS Options
  stationaryRadius: 30,
  useSignificantChangesOnly: false,
  locationAuthorizationAlert: {
    titleWhenNotEnabled: 'Locatie services niet ingeschakeld',
    titleWhenOff: 'Locatie services staan uit',
    instructions: 'Om gebruik te maken van AutoModus moet ‘Altijd’ ingesteld worden in Locatie services. Dit zodat we ook je kilometers kunnen bijhouden als je navigatie gebruikt.',
    cancelButton: 'Annuleren',
    settingsButton: 'Instellingen',
  },
  preventSuspend: true, // [iOS only] Prevent iOS from suspending your application in the background after location-services have been switched off.
  heartbeatInterval: 120, // seconds
  desiredOdometerAccuracy: 60,
  // [Geolocation] Android Options
  fastestLocationUpdateInterval: 3000,
  deferTime: 0,
  allowIdenticalLocations: true,
  // [Activity Recognition] Common Options
  activityRecognitionInterval: 0,
  stopTimeout: 1,
  minimumActivityRecognitionConfidence: 65,
  stopDetectionDelay: 0,
  disableStopDetection: false, // Disable accelerometer-based Stop-detection System.
  // [Activity Recognition] iOS Options
  // ACTIVITY_TYPE_OTHER 1
  // ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION 2
  // ACTIVITY_TYPE_FITNESS 3
  // ACTIVITY_TYPE_OTHER_NAVIGATION 4
  activityType: 2,
  // [Application] Common Options
  stopOnTerminate: true, // Allow the background-service to cont. tracking when user closes the app.
  startOnBoot: false, // Auto start tracking when device is powered-up.
  debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
  reset: true, // <-- set true to ALWAYS apply supplied config; not just at first launch.
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  stopOnStationary: false,
  // [Application] Android Options
  foregroundService: true,
  notificationText: 'Locatie services ingeschakeld', // Configure the text of the persistent notification in the Notification Bar when running with foregroundService true
  notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MAX,
  notificationChannelName: 'Location',
  notificationColor: '#00BCB2',
  notificationLargeIcon: 'mipmap/ic_launcher',
  notificationSmallIcon: 'drawable/pw_notification',`

**Comment by lorenc-tomasz** [comment]
This bug seems to be Samsung S8  / S8+ specific.

**Comment by lorenc-tomasz** [comment]
Similar: 
 com.transistorsoft.locationmanager.location.TSLocationManager$TSCurrentPositionRequest$Builder.run 

> 
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
com.transistorsoft.locationmanager.location.TSLocationManager$TSCurrentPositionRequest$Builder.run (Unknown Source)
com.transistorsoft.locationmanager.location.TSLocationManager.setOdometer (Unknown Source)
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$13.run (Unknown Source)

**Comment by christocracy** [comment]
These errors are generated after your app was terminated with `stopOnTerminate: true`.  I don't know why.  I've had reports of these in the past.

The stacktrace actually doesn't correspond with the actual error.

**Comment by lorenc-tomasz** [comment]
That's strange. But good to know that it doesn't crash the app when user uses it.

**Comment by christocracy** [comment]
Have you or your company purchased a license?  You are not a member of my Github organization.  Licensed customers are granted access to a private repo for latest updates.

**Comment by lorenc-tomasz** [comment]
Yes, we have purchased the license however I guess only one person have been added to your Github organization.

**Comment by christocracy** [comment]
Talk to that "one person" and ask them to login to the "Product Dashboard" (https://www.transistorsoft.com, click "Customer Login").  Ask them to add you as a member.

**Comment by lorenc-tomasz** [comment]
OK. Thanks.

**Comment by lorenc-tomasz** [comment]
Done.

**Comment by christocracy** [comment]
Post issues in the private repo from now on.

**Comment by lorenc-tomasz** [comment]
OK.

**Comment by lorenc-tomasz** [comment]
The same error even on premium version. No idea why, but it doesn't look like crash for user. So not a big deal but it's on statistics.

**Comment by lorenc-tomasz** [comment]
Today after location permission question on Android:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
com.transistorsoft.locationmanager.location.SingleLocationRequest$TSCurrentPositionRequest.h (Unknown Source)
com.transistorsoft.locationmanager.location.TSLocationManager.watchPosition (Unknown Source)
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$6.run (Unknown Source)

**Comment by christocracy** [comment]
Can you reproduce it?  Are you using watchPosition?

**Comment by lorenc-tomasz** [comment]
Yes, I'm using watch position. I call it within the success callback of ready function.

**Comment by christocracy** [comment]
Why?  That seems dangerous and unnecessary to me.  Show me your code.

**Comment by christocracy** [comment]
Have you [read the warning in `#watchPosition`](https://transistorsoft.github.io/react-native-background-geolocation-android/classes/_react_native_background_geolocation_android_.backgroundgeolocation.html#watchposition)

⚠️ Warning:
watchPosition is not reccommended for long term monitoring in the background — It's primarily designed for use in the foreground only. You might use it for fast-updates of the user's current position on the map, for example. The SDK's primary Philosophy of Operation does not require watchPosition.

**Comment by lorenc-tomasz** [comment]
Yes. 

```
    BackgroundGeolocation.ready(GEOLOCATION_CONFIG, (state) => {
      console.log('- BackgroundGeolocation is configured and ready: ', state.enabled);
      if (!state.enabled) {
        //
        // Start tracking!
        //
        BackgroundGeolocation.start(() => {
          console.log('- Start success');
        });
      }
// Run watch position
      this.getPosition();
    });
```

```
  getPosition() {
    const { status } = this.props;

    if (status === STATUS.STARTED) {
      // Check position to update GPS signal status on starting
      BackgroundGeolocation.watchPosition((location) => {
        console.log('[watchPosition] -', location);
        this.onChange(location);
        if (location.coords.accuracy && location.coords.accuracy < GPSAccuracyLevel.SEARCHING) {
          console.log('-- stopWatchPosition');
          BackgroundGeolocation.stopWatchPosition(() => console.log('-- stopWatchPosition success'), error => console.log('-- stopWatchPosition error: ', error));
        }
      }, (errorCode) => {
        console.log('[watchPosition] ERROR -', errorCode);
        this.onGeolocationError(errorCode);
      }, {
        interval: 5000,
      });
    }
  }
```

**Comment by christocracy** [comment]
Completely unnecessary.  The plugin already has built-in intelligence to sample a number of locations when #start is called, waiting for the GPS to lock on and fetch the best possible location before firing the onMotionChange event.

Get rid of your watchPosition code.

**Comment by christocracy** [comment]
It shouldn’t, and I’ll attempt to reproduce this, but this isn’t a use-case I’ve tested for since it’s pointless to do here.

**Comment by lorenc-tomasz** [comment]
I understand, but for example resting odometer on plugin start may case similar issue.

**Comment by christocracy** [comment]
That *is* a use case which has been tested.

**Comment by lorenc-tomasz** [comment]
Have removed the watchPosition, and so far no crashes. Will observe it further.

**Comment by christocracy** [comment]
Yes, I may have fixed your `watchPosition` NPE.

**Comment by lorenc-tomasz** [comment]
👍
