### ISSUE TITLE
Updating params for http in background and foreground

### ISSUE THREAD

**Issue by mschipperheyn** [transistorsoft/react-native-background-geolocation#626]
## Your Environment
* Plugin version: 2.14.2
* Platform: iOS / Android:
* OS version: 
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.57.7
* Plugin config

## Expected Behavior
This is actually a question. I read in one of the comments that the configuration should be set for the lifetime of the application. In my case, I need to send some `params` to the server that will change over time, particularly a vehicleId. I'm wondering if I can re-apply the settings in a `componentDidUpdate` without ill effect? Is it idempotent?

Secondly. since the vehicleId may change when the app is in the background and is sleeping, I wonder if I can supply a function to geolocation that will lead it to request the current `params` every x minutes, which would be the result of a query.

**Comment by christocracy** [comment]
Read docs for [#ready](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#ready) method.  Pay careful attention to note about **`reset: true`**.

You're always free to `#setConfig` to update persisted configuration.

**Comment by mschipperheyn** [comment]
Thanks for the quick reply. So, reading it *more* carefully I conclude that the answer to the second part of my question is no.

**Comment by christocracy** [comment]
> I wonder if I can supply a function to geolocation that will lead it to request the current params every x minutes, which would be the result of a query.

No.  When you know your `vehicleId` has changed, call `#setConfig`.

```javascript
onChangeVehicleId(newVehicleId) {
  BackgroundGeolocation.setConfig({params: {vehicleId: newVehicleId}});
}
```

**Comment by mschipperheyn** [comment]
Thanks!
