### ISSUE TITLE
ActionButton in foreground notification

### ISSUE THREAD

**Issue by GuilhermeGuiuler** [transistorsoft/react-native-background-geolocation#628]
## Your Environment
* Plugin version: All
* Platform: iOS or Android
* OS version: All
* Device manufacturer / model: All
* React Native version (`react-native -v`): 0.57
* Plugin config

## Expected Behavior
N/A

## Actual Behavior
N/A

## Steps to Reproduce
N/A

## Context

I would like to know how I can put actions button in notification when my application is running in background

## Debug logs

N/A

**Comment by christocracy** [comment]
You can’t.  What actions would you like?

**Comment by GuilhermeGuiuler** [comment]
> You can’t. What actions would you like?

Something like that
![7fd94196-b84a-47f4-bea2-4b1da936d521](https://user-images.githubusercontent.com/10064190/49827838-73c19b80-fd71-11e8-84af-19ba2f5bccc6.jpg)

**Comment by thawankeane** [comment]
> > You can’t. What actions would you like?
> 
> Something like that
> ![7fd94196-b84a-47f4-bea2-4b1da936d521](https://user-images.githubusercontent.com/10064190/49827838-73c19b80-fd71-11e8-84af-19ba2f5bccc6.jpg)

@christocracy is possible to do that ? Custom ActionButtons with callback functions that do something (like stop to tracking). Also would be aweasome if we can do some styles in the notification text (like bold and italic). Is any of this things possible with this package ?

**Comment by christocracy** [comment]
It is not possible.  What you're asking for (styling) would be *very* complex.

There's also the issue how to handle these button-clicks when your app is terminated, since your Javascript callbacks would no longer execute (since the MainActivity is terminated).

This isn't going to happen anytime soon.

**Comment by christocracy** [comment]
I was experimenting with this today.  I have an idea how this could work.

**Comment by GuilhermeGuiuler** [comment]
Heck, that's cool, I even thought you had forgotten ... I hope it works well in your tests and that you implement this in the project, it would be cool for Android and IOS.
I hope everything works soon

Good Job 😄

**Comment by christocracy** [comment]
Ok, I have found a way involving creating a custom android View.

![](https://dl.dropbox.com/s/2tfoscwh2fp5rsm/Screenshot%202019-04-26%2012.45.22.png?dl=1)

![](https://www.dropbox.com/s/xqxo5twia55ei08/Screenshot%202019-04-26%2012.46.09.png?dl=1)

- Clicking the buttons, the plugin can receive these actions:
```
04-26 12:46:28.143 32462 32462 D TSLocationManager: [c.t.l.service.TrackingService onStartCommand] >>> notification_action: notification_action_foo
04-26 12:46:29.430 32462 32462 D TSLocationManager: [c.t.l.service.TrackingService onStartCommand] >>> notification_action: notification_action_bar
```

A theoretical configuration and usage would look like this:
```javascript

BackgroundGeolocation.onNotificationAction((buttonId) => {
  console.log('- Notification button clicked: ', buttonId);
  switch(buttonId) {
    case 'notification_button_foo':
      break;
    case 'notification_button_bar':
      break;
  }
});

BackgroundGeolocation.ready({
  notificationTitle: "The notification title",
  notificationText: "The notification text",
  notificationActions: [  // <-- plugin will add click-listeners to these button ids
    "notification_action_foo",
    "notification_action_bar"
  ]
});
```

**Comment by mikehardy** [comment]
That looks really cool. I'd use this to open a screen explaining the purpose + how we handle the data and imploring users to leave it enabled if possible (we have an opt-in tracking app where they can turn it off but it helps us if they leave it on). So, potentially useful.

**Comment by christocracy** [comment]
@mikehardy I found an interesting side-effect when you cause an exception writing to this notification layout, eg an invalid resource id, it causes Android to let the fg service run anyway, but with no notification rendered!

**Comment by mikehardy** [comment]
Huh 🤔 2 immediate thoughts, 1 - file a bugalyzer bug with google and be prepared to see nothing happen on the issue itself but the bug gets fixed eventually and 2 - this seems like a barn-sized hole in the whole privacy area. I'm consent-based so not interested in playing but I imagine this is used for profit

**Comment by christocracy** [comment]
[Notification](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.notification.html) system refactored in 3.0.4.  Fully custom layouts are now possible.
