### ISSUE TITLE
Passing graphql query in http call (control characters rejected)

### ISSUE THREAD

**Issue by mschipperheyn** [transistorsoft/react-native-background-geolocation#630]
## Your Environment
* Plugin version: 2.14.2
* Platform: iOS
* OS version: 
* Device manufacturer / model: Simulator
* React Native version (`react-native -v`): 057.7
* Plugin config

```
[TSLocationManager init] {
    activityRecognitionInterval = 10000;
    activityType = 1;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 1;
    desiredAccuracy = "-2";
    desiredOdometerAccuracy = 100;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 0;
    elasticityMultiplier = 1;
    enabled = 1;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =     {
        authorization = "Bearer XYZ";
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    isFirstBoot = 0;
    isMoving = 1;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =     {
        instructions = "You must enable 'Always' in location-services";
        titleWhenNotEnabled = "You need to enable background location tracking";
        titleWhenOff = "You need to enable location tracking";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "{ \"id\"=\"UpdatePartnerVehicleMutation\", \"query\": \"mutation UpdatePartnerVehicleMutation(\n  $input: UpdatePartnerVehicleInput!\n) {\n  updatePartnerVehicle(input: $input) {\n    partnerVehicle {\n      id\n      driver {\n        id\n      }\n      lat\n      lng\n    }\n  }\n}\n\", \"variables\": { \"input\": { \"partnerVehicle\": { \"id\": \"7655NwP22QAQ1yXKg48vGB\", \"lat\":<%= latitude %>,\"lng\":<%= longitude %>,\"driver\": { \"id\": \"2ltXaYHfw7XOFbpkK01Jbx\" } } } } }";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = "35604230.91729696";
    pausesLocationUpdatesAutomatically = 0;
    preventSuspend = 0;
    schedule =     (
    );
    schedulerEnabled = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 1;
    trackingMode = 1;
    url = "https://beta.project.com/graphql";
    useSignificantChangesOnly = 0;
```
## Expected Behavior
It should send JSON normally 

## Actual Behavior
I get an error popup: `Unescaped control character around character 88`

## Steps to Reproduce
Apart from the setup, this is pretty vanilla. I removed the setParams in favor of using `reset: true` and hard coding the other parameters in the `locationTemplate`

The location template looks like this
```
locationTemplate = "{ \"id\": \"UpdatePartnerVehicleMutation\", \"query\": \"mutation UpdatePartnerVehicleMutation(\n  $input: UpdatePartnerVehicleInput!\n) {\n  updatePartnerVehicle(input: $input) {\n    partnerVehicle {\n      id\n      driver {\n        id\n      }\n      lat\n      lng\n    }\n  }\n}\n\", \"variables\": { \"input\": { \"partnerVehicle\": { \"id\": \"2ltXaYHfw7XOFbpkK01Jbx\", \"lat\":<%= latitude %>, \"lng\":<%= longitude %> }, \"driver\": { \"id\": \"7655NwP22QAQ1yXKg48vGB\" } } } }";
```

unfortunately, it seems `\n` is not appreciated by the plugin and rejected

## Context
tracking status changes 

## Debug logs
```
════
🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 5.0
‼️-[TSLocation templateError:template:] locationTemplate error: Unescaped control character around character 88.
{ "id": "UpdatePartnerVehicleMutation", "query": "mutation UpdatePartnerVehicleMutation(
  $input: UpdatePartnerVehicleInput!
) {
  updatePartnerVehicle(input: $input) {
    partnerVehicle {
      id
      driver {
        id
      }
      lat
      lng
    }
  }
}
", "variables": { "input": { "partnerVehicle": { "id": "2ltXaYHfw7XOFbpkK01Jbx", "lat":<%= latitude %>, "lng":<%= longitude %> }, "driver": { "id": "7655NwP22QAQ1yXKg48vGB" } } } }

```

**Comment by mschipperheyn** [comment]
Well, unfortunately, graphQL uses line breaks as delimiters. So it's no longer valid if there are no control characters. I would agree that this was a dubious choice on their part

**Comment by christocracy** [comment]
I suggest you post a simpler template (or use default Schema) and post to some other proxy endpoint at your server to transform the data before forwarding to your GraphQL processor.

**Comment by mschipperheyn** [comment]
Ok, I will talk to the api team to see if we can do that. In the meantime I would suggest that this issue is treated as a feature request or bug report. graphQL is on the rise and this should be possible. What the plugin is doing is essentially rejecting a valid JSON format.

**Comment by christocracy** [comment]
Are you explicitly adding these `\n` characters to your `locationTemplate`?  If so, you need to escape those as `\\n`.  See [here](https://stackoverflow.com/questions/39247981/unescaped-control-character-around-character-981-error-while-parsing-json)

**Comment by mschipperheyn** [comment]
You are right. Thanks. I was also wrong about return statement being the delimiter. Any whitespace will do.

The follow up issue I'm having is that I'm getting a 200 statement with a validation error back from the api (graphql tends to send 200 messages back when validation errors occurs (should be 422, but it isn't). This is prob the reason I'm not seeing the failing message. Is there a way to log the messages being sent even if they are 200?

**Comment by christocracy** [comment]
Back from holidays.  What the status here?

**Comment by christocracy** [comment]
I recall someone having a similar issue with GraphQL recently.  The solution was to escape nested `\` with triple-slash `\\\`
