### ISSUE TITLE
Thoughts on Settings for Reconfiguring the Plugin for Battery Levels

### ISSUE THREAD

**Issue by sunilw123** [transistorsoft/react-native-background-geolocation#636]
Our new dev team is reworking the plugin to have different configurations which a user can choose (via a battery settings menu we put in the app) and I wanted to get your take on what we are doing. 
We are planning on reconfiguring the plugin based on the following that I think is best but I wanted to get your thoughts as you know best what we should do.

Here is the existing configuration we have:

config updateWithBlock:^(TSConfigBuilder *builder) {
        builder.debug = YES;   // Enable debug mode for having notifications while moving in location!!!!
        builder.logLevel = tsLogLevelVerbose;
        builder.desiredAccuracy = kCLLocationAccuracyBestForNavigation;
        builder.distanceFilter = 3; // filter for mooving across area. Currently changed to 3 meters
        builder.stopOnTerminate = NO;
        builder.startOnBoot = YES;
        builder.url = urlString;
        builder.method = @"PUT";
        builder.heartbeatInterval = 900;
        builder.stopTimeout = 15;
        builder.preventSuspend = YES;
        builder.disableElasticity = YES;
        builder.autoSync = YES;
        builder.headers = @{@"Content-Type" : @"application/json; charset=utf-8",
                          @"Authorization" : server.token
                          };
    }];

I want to have the following battery settings: Real Time, High, Medium, Low, Groud Travel and Air Travel.

1) Real Time (description to user: Updates every 9 feet)- I think we can use the configuration we have now and as listed above(distancefilter = 3)  as every 3 meters (9 feet it) will update, which seems sufficient.  Is this still a correct implementation and do we need to use this at all: DESIRED_ACCURACY_NAVIGATION?  Also, we have KCLLocationAccuracyBestfor Navigation...does that need to change or is that good to use when we put the distancefilter-3.

2) High (description to user: Updates every 25 feet) - Same as above except we change the distance filter to 25 feet.

3) Medium (description to user: Updates every 150 feet) - Same as above but change distance filter to 150 feet

4) Low (description to user: Updates every 500 feet)- Same as above except change distance filter to 500 feet and preventsuspend=NO

5) Ground Transportation (description to user: Efficient updates based upon speed of travel) - Same as above but PreventSuspend=No; Disable Elasticity - NO

6) Air Travel (description to user: Updates every 15 minutes - Same as above except we configure to do updates every 15 minutes. Should we be using schedule for this?

Please let me know your thoughts.  I want to make sure I do this right the first time.  Thanks Chris.

This will hopefully be the last time I am asking you questions...thx

## Your Environment
* Plugin version:
* Platform: iOS or Android IOS
* OS version: 12.1.2
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
- See docs for [desiredAccuracy](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#desiredaccuracy) and [distanceFilter](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#distancefilter).
- Also see the [HTTP Guide](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.httpevent.html).  HTTP requests consume the most energy.  Take note of `batchSync` and `autoSyncThreshold` for throttling / batching http requests.

**Comment by dante1202** [comment]
@christocracy So, to have updates every 15 minutes we should use distance filter? As example, track every 2000 meters and we can't schedule for periodical time
