### ISSUE TITLE
Debug Mode Notifications not showing up for iphone 6 and 6 plus but working on Iphone X

### ISSUE THREAD

**Issue by sunilw123** [transistorsoft/react-native-background-geolocation#637]
So we are testing a new build and on that build we put it in debug mode so we get the popup notifications working so we can see everything that the plugin is doing.  When I put this on my Iphone X, I get all the notifications.  I guess what I restarted the phone I didn't immediately see the popups working but after a while it started again.  But on the Iphone 6 and 6 plus, the debug notifications are not showing at all and we don't quite know why.  hence the tracking when the app is hard closed also does not work and we are trying to figure out what we are doing wrong and why its only working on the Iphone X and not iphone 6 and 6 plus.  Any thoughts?  Do you need the log files?

## Your Environment
* Plugin version:
* Platform: iOS or Android: IOS
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
Here is the existing configuration we have:

config updateWithBlock:^(TSConfigBuilder *builder) {
        builder.debug = YES;   // Enable debug mode for having notifications while moving in location!!!!
        builder.logLevel = tsLogLevelVerbose;
        builder.desiredAccuracy = kCLLocationAccuracyBestForNavigation;
        builder.distanceFilter = 3; // filter for mooving across area. Currently changed to 3 meters
        builder.stopOnTerminate = NO;
        builder.startOnBoot = YES;
        builder.url = urlString;
        builder.method = @"PUT";
        builder.heartbeatInterval = 900;
        builder.stopTimeout = 15;
        builder.preventSuspend = YES;
        builder.disableElasticity = YES;
        builder.autoSync = YES;
        builder.headers = @{@"Content-Type" : @"application/json; charset=utf-8",
                          @"Authorization" : server.token
                          };
    }];

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Why are you posting issues to the **React Native** repo when you're using the [**Pure Native version**](https://github.com/transistorsoft/background-geolocation-lt)?
