### ISSUE TITLE
how to add a value from the event in location template

### ISSUE THREAD

**Issue by rash6795** [transistorsoft/react-native-background-geolocation#639]
## Your Environment
* Plugin version:2.12.2
* Platform: iOS
* OS version:11.4.1
* Device manufacturer / model: iPhone SE
* React Native version (`react-native -v`): 0.54.2
* Plugin config: 
locationTemplate: '{"trackingarray":[{"locationdate":<%=timestamp%>,"latitude":<%=latitude%>,"longitude":<%=longitude%>,"islocationon":<%=**value_from_onProviderChange**%> }]}'

## Context

Is there any way to get the **event's callback value** to **add** it to the **location template** ???
i need the value of **onProviderChange event's provider.enabled value** to send it to the server

**Comment by christocracy** [comment]
Going through old issues, missed this one:

On iOS, you would have to listen to the `onProviderChange` event and manually post an http request to your server.
