### ISSUE TITLE
Not working when application close

### ISSUE THREAD

**Issue by Goraklogicaldna** [transistorsoft/react-native-background-geolocation#640]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Steps to Reproduce
1. On some device like redmi, vivo, oppo. The application does not work when closing from the task manager
2.
3.
4.

**Comment by christocracy** [comment]
Chinese devices are the worst.  Those manufacturers install a layer on top of Android that kills background services.

You’ll have to consult your particular operating system’s Settings->Battery Settings to disable terminating background services.

**Comment by Goraklogicaldna** [comment]
How I can set permission to autostart. I already pass startOnBoot true but it's not working for VIVo and Xiomi mobile.

**Comment by christocracy** [comment]
Are you unlocking the device after rebooting?  It’s required.

If yes, then see above about manufacturer Battery setting.

Xiomi, Huawei, Vivo are the absolute worst possible devices for violating the Android API behaviour of services.  They are like a nanny state.
