### ISSUE TITLE
Working with the callbacks while the app is backgrounded

### ISSUE THREAD

**Issue by andreimarinescu** [transistorsoft/react-native-background-geolocation#641]
## Your Environment
* Plugin version: *2.12.0-beta.4*
* Platform: iOS or Android *both*
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.54
* Plugin config

## Context
I'm trying to capture some additional data in the background, aside from GPS location. Specifically in this case, Gyro and Accelerometer data

## Debug logs

This is actually a question, hopefully this wasn't already answered. As mentioned above, I'm trying to collect some additional data, like Gyro and Accelerometer when receiving location updates. 

As far as I can tell from the Apple iOS documentation, doing this in the background requires using the `location` background mode anyway. What I'd ideally like to do is hook into the callbacks this plugin provides (for example `onLocation`), use a separate RN plugin for actually collecting the data and managing sync on my own (considering using the `http` callback to trigger my own sync for this data when the plugin sends the stored GPS information).

What is not very clear to me is whether I can rely on these callbacks when the application is in background mode. Should I expect them to be executed always? Judging by your answer in #102, a strategy that might work is using the onLocation callback for iOS and using a HeadlessJS task for Android.

**Comment by christocracy** [comment]
>doing this in the background requires using the location background mode anyway

Correct

>What I'd ideally like to do is hook into the callbacks this plugin provides (for example onLocation),

>and managing sync on my own (considering using the http callback to trigger my own sync for this dat

If you're not configuring the plugin an `#url`, there will be **no** `http` event.  The `http` event fires when your server responds to the plugin's built-in HTTP service.

Why don't you just collect gyro / accelerometer data independently of the location-data.  Send it to your server on its own endpoint.

**Comment by christocracy** [comment]
>What is not very clear to me is whether I can rely on these callbacks when the application is in background mode. Should I expect them to be executed always?

On iOS, your callbacks will always be executed.  On Android, if the app has been terminated, your RN app is no longer alive.  You will have to us HeadlessTask for that case.
