### ISSUE TITLE
General advice for location tracking

### ISSUE THREAD

**Issue by gmasterofnone** [transistorsoft/react-native-background-geolocation#642]
## Your Environment
* Plugin version: 2.14.2
* Platform: iOS 
* OS version: 9
* Device manufacturer / model: iPhone X
* React Native version (`react-native -v`): 0.57.8
* Plugin config

 BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopTimeout: 5,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
    },

## Expected Behavior
onMotionChange event handler fires a post request to our server.

## Actual Behavior
The event listener will fire one time when the app first boots but will not fire again even if I am far outside the 200m fence.

## Steps to Reproduce

1. Load fresh build on device and launch (with debug mode activated)
2. OnMotionChange immediately fires on first load and logs location to our back end.
2. Drive to a location far outside the 200m fence
3. Observe the device notification showing status is STATIONARY
4. OnMotion fires but post request never fires again.

## Context
Hoping for any ideas or context as to why it's not firing our post request in the background.

## Debug logs
Below is a snippet of the relevant code in my component.  Below that is the logs in question:

``` 
 async componentWillMount() {
    await this.linkUser()
    BackgroundGeolocation.onMotionChange(this.onMotionChange);

    BackgroundGeolocation.ready({
      reset: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopTimeout: 2,
      debug: true, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      batchSync: false,
      autoSync: false, 
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
  }
  
  linkUser = async () => {
    const { user } = this.state;
    if (!user) {
      const user =  await API.getUser()
      this.setState( { user } )
    }
  }
  
  onMotionChange = async event => {
    const currentTime = new Date().toLocaleString();
    BackgroundGeolocation.logger.notice(`onMotionChange fired at ${currentTime}`);
    const { latitude, longitude } = event.location.coords;
    if (!event.isMoving) {
      const position = { latitude, longitude }
      await this.linkUser()
      BackgroundGeolocation.logger.ok(this.state.user);
      const response = await API.logCoords(this.state.user, position);
      BackgroundGeolocation.logger.ok(`API fired at ${currentTime}`);
      BackgroundGeolocation.logger.ok(response.userID);
      BackgroundGeolocation.logger.ok(response.latitude);
      BackgroundGeolocation.logger.ok(response.longitude);
    }
  }

  sendLog = () => {
    BackgroundGeolocation.emailLog('g@masterofnone.com')
  }
  
  componentWillUnmount() {
    BackgroundGeolocation.removeListeners();
  }
 ```

Fires our post request on first launch
----------------------------------
2019-01-01 15:16:08.326 ✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+39.76420253,-105.01250252> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/1/19, 3:16:08 PM Mountain Standard Time

2019-01-01 15:16:08.327 🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 25

2019-01-01 15:16:08.328 🔴-[TSLocationManager stopUpdatingLocation] 

2019-01-01 15:16:08.328 🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 65.0

2019-01-01 15:16:08.329 🎾-[TSLocationManager startMonitoringSignificantLocationChanges] 

2019-01-01 15:16:08.339 🔵-[TSLocationManager log:message:] onMotionChange fired at 1/1/2019, 3:16:08 PM

2019-01-01 15:16:08.339 ✅-[TSLocationManager log:message:] 78dc4124-5b7f-4291-b1f0-716848848503

2019-01-01 15:16:08.341 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 16CDC97A-6CF2-4E5D-A656-698B070E9F75

**2019-01-01 15:16:08.848 ✅-[TSLocationManager log:message:] API fired at 1/1/2019, 3:16:08 PM**

2019-01-01 15:16:08.848 ✅-[TSLocationManager log:message:] 78dc4124-5b7f-4291-b1f0-716848848503

2019-01-01 15:16:08.848 ✅-[TSLocationManager log:message:] 39.76473600000001

2019-01-01 15:16:08.848 ✅-[TSLocationManager log:message:] -105.0130414

-----------------------------------------------------------------------

Example log of post request not firing anytime after onMotionChange (!is_moving) fires
----------------------------------

2019-01-01 15:29:53.888 🔵-[TSLocationManager log:message:] onMotionChange fired at 1/1/2019, 3:29:53 PM

2019-01-01 15:29:53.890 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 05D7796B-B430-44C8-A6FA-FC93A7704A47

2019-01-01 15:29:53.891 ✅-[TSLocationManager log:message:] 78dc4124-5b7f-4291-b1f0-716848848503

2019-01-01 15:29:54.565 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

**2019-01-01 15:29:54.698 ✅-[TSLocationManager log:message:] API fired at 1/1/2019, 3:29:53 PM**

2019-01-01 15:30:03.877 
<+39.76899915,-105.01742701> +/- 34.67m (speed 0.00 mps / course 178.52) @ 1/1/19, 3:30:03 PM Mountain Standard Time

2019-01-01 15:30:03.877 🔴-[LocationManager stopUpdatingLocation] OFF

2019-01-01 15:30:03.878 
╔═══════════════════════════════════════════════════════════
║ -[LocationManager locationManager:didUpdateLocations:] Sample 1 of 1
╚═══════════════════════════════════════════════════════════

2019-01-01 15:30:23.875 🔵-[TSLocationManager endStartDetection] 

2019-01-01 15:30:23.875 ✅-[BackgroundTaskManager stopBackgroundTask:]_block_invoke 191 OF (
    191
)

2019-01-01 15:30:48.188 ℹ️-[TSDBLogger db_save] Log committed

2019-01-01 15:30:48.232 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-01-01 15:30:52.883 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/100 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-01-01 15:33:13.252 ℹ️-[TSDBLogger db_save] Log committed

2019-01-01 15:33:13.260 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2019-01-01 15:33:13.306 🔵-[TSLocationManager locationManager:didExitRegion:] Exit stationary region

**Comment by christocracy** [comment]
Have you tested this in the iOS simulator with simulated location?

**Comment by gmasterofnone** [comment]
It's challenging to replicate the desired behavior in the simulator.  For an MVP we just switched to using your HTTP option and running the logic on the backend.  In general could you help me out on a couple broad points?

-  The plugin's event listeners DO fire correctly when the app is in the background but our network requests in the callback do not.  This is probably a limitation in iOS, i.e no background network requests?

- If so, is there a way to configure the logic on the plugin's built-in HTTP method?  We are only looking to post a location to our server if the plugin state moves into STATIONARY.

Other than that the plugin works very well so thank you!

**Comment by christocracy** [comment]
You might be in the method #startBackgroundTask (see the docs)

>We are only looking to post a location to our server if the plugin state moves into STATIONARY.

The plugin already handles this with the `event: “motionchange”, is_moving: Boolean` in the Location Data.

**Comment by gmasterofnone** [comment]
> The plugin already handles this with the event: “motionchange”, is_moving: Boolean in the Location Data.

The event fires but our method _inside_ the callback to post a location to the server does not fire:

`onMotionChange = async event => {
---THIS FIRES CORRECTLY IN THE BACKGROUND---
    const currentTime = new Date().toLocaleString();
    BackgroundGeolocation.logger.notice(`onMotionChange fired at ${currentTime}`);
    const { latitude, longitude } = event.location.coords;
    if (!event.isMoving) {
      const position = { latitude, longitude }
      await this.linkUser()
      BackgroundGeolocation.logger.ok(this.state.user);
--- BUT OUR METHOD TO POST STATIONARY LOCATION DOES NOT FIRE IN THE BACKGROUND ---
      const response = await API.logCoords(this.state.user, position);
---------------------------------------------------------------------------
      BackgroundGeolocation.logger.ok(`API fired at ${currentTime}`);
      BackgroundGeolocation.logger.ok(response.userID);
      BackgroundGeolocation.logger.ok(response.latitude);
      BackgroundGeolocation.logger.ok(response.longitude);
    }
  }`

Is #startBackgroundTask meant to address this?  BTW i could not find it in the API docs.  If you have a link that would be great.

**Comment by christocracy** [comment]
Why are you so concerned with using your own http request?  The plugin as far better at this task than you’ll be (eg auto-retry on server failure / no network connection).

The method #startBackgroundTask is 100% guaranteed documented.  You’re probably looking at the docs for the Config class, which is not where the **methods** are documented.

**Comment by gmasterofnone** [comment]
I found that method, which would address our issue.  I agree that the plugin is better for the task, which is why I was asking if we can configure the plugins network request feature to ONLY post locations to our server if the device is STATIONARY e.g !is_Moving.

Thanks for your help on this.

**Comment by christocracy** [comment]
>can configure the plugins network request feature to ONLY post locations to our server if the device is STATIONARY

No.  Btw, if you're doing that, be sure to configure `maxRecordsToPersist: 1` so that you don't fill up the plugin's SQLite database.  And if you're not interested in tracking locations while `is_moving`, be sure to set a very high `distanceFilter` (eg: `10000`).  You'll need to take care of your HTTP upload.
