### ISSUE TITLE
preventSuspend not working

### ISSUE THREAD

**Issue by Benjamin-Dewey** [transistorsoft/react-native-background-geolocation#643]
## Your Environment
* Plugin version: 2.14.2
* Platform: iOS
* OS version: 12.1.2
* Device manufacturer / model: iPhone 7
* React Native version (`react-native -v`): 0.57.8
* Plugin config:
```
{
  preventSuspend: true,
  disableStopDetection: true,

  reset: true,
  distanceFilter: 1,
  disableElasticity: true,
  url: 'https://ptsv2.com/t/8yw86-1546661811/post',
  activityType: Geolocation.ACTIVITY_TYPE_FITNESS,
  desiredAccuracy: Geolocation.DESIRED_ACCURACY_HIGH,
  logLevel: Geolocation.LOG_LEVEL_VERBOSE,
}
```

## Expected Behavior
When the app is in the background, disengaging and then reengaging location tracking should **not** cause the app to become suspended.

## Actual Behavior
When the app is in the background, disengaging and then reengaging location tracking **causes** the app to become suspended.

## Steps to Reproduce
All the code is in this [App.js](https://pastebin.com/syBjb6VF)
These steps assume you are using a **real** device and not a simulator.
1. Run the app, press the **Toggle On/Off** button to start the plugin and engage location tracking, give any requested permissions
2. Background the app by turning off the device screen
3. Set the device down and wait a few seconds for location tracking to disengage; you can watch the logs to see when this has happened
4. At this point logs should still be flowing; the app is not suspended
5. Pick up the device and shake it to reengage location tracking; you should see a few logs in reaction to this, and then no more
6. The app is now suspended; you can foreground the app again and the code will pick up where it left off starting on line `60` in [App.js](https://pastebin.com/syBjb6VF)

## Context
My goal is this passage from the **Philosophy of Operation**
> Since your app is completely awake in the background with preventSuspend, the plugin is able to constantly monitor the CMMotionActivityManager API and respond quickly to motion-activity changes, allowing the plugin to trigger a state-change to moving without requiring the usual "stationary-geofence" exit (typically 200 meters). While in preventSuspend, iOS can behave just like Android, requiring only a few meters of movement to change state to moving.

If you take a look at my `onActivityChange` handler in [App.js](https://pastebin.com/syBjb6VF) you will see I am using `changePace` to manually toggle location tracking when the device appears to have stopped/started moving. When the app is both stationary and backgrounded, attempting to reengage location tracking causes the app to become suspended with code execution paused on `changePace` until the app is foregrounded again.

## Debug logs
The logs from the plugin when following the **Steps to Reproduce** are [here](https://pastebin.com/c4uavx9V)

**Comment by christocracy** [comment]
I've had `preventSuspend: true` running on my iPhone 6s for about 24 hours (unplugged).  If I pick up the device and shake it, I hear a `heartbeat` event (sound effect *boop*).

Set `debug: true` so you can *hear* the heartbeat event *boop* sound effect.

I see no problem here.

**Comment by christocracy** [comment]
btw, you don't need to do this, the plugin will already automatically `chanagePace(true)` with `preventSuspend: true` when the motion-activity API says the device is moving.

```javascript
// we use onActivityChange to engage/disengage location tracking
    // depending on whether the device has moved from moving to
    // stationary or vice versa
    const onActivityChange = async ({ activity, confidence }) => {
      const stationary = activity === 'still' && confidence === 100;
      const { isMoving } = await Geolocation.getState();
 
      // if isMoving === stationary then isMoving is
      // wrong, so toggle it by calling changePace which
      // in turn will toggle location tracking
      const shouldChangePace = isMoving === stationary;
 
      this.log(`- [event] activity change, isMoving ${isMoving}, stationary ${stationary}, shouldChangePace ${shouldChangePace}`);
 
      if (shouldChangePace) {
        this.log('- [event] attempting to change pace');
 
        // at this point if the app is backgrounded and we
        // are changing the pace from stationary to moving
        // then the app will get suspended; code execution
        // will pause on this line here until the app is foregrounded
        await Geolocation.changePace(!isMoving);
 
        const nextPace = !isMoving ? 'moving' : 'stationary';
        this.log(`- [event] pace changed to ${nextPace}`);
      }
    };
```

**Comment by Benjamin-Dewey** [comment]
>I see no problem here.

So what are you saying? Am I wrong about the app becoming suspended when calling `changePace(true)` in the background?

Anyways, I’ll try making some changes when I get back to my computer.

**Comment by Benjamin-Dewey** [comment]
>With preventSuspend: true, there will be two mechanisms to possibly engage tracking

I know this isn’t really relevant to my issue, but if you will indulge me, what’s the point of using both mechanisms at once? Wouldn’t the motion api with a small `distanceFilter` always trigger movement before the device exits the geogence? Is the geofence just a backup in case the motion api fails?

**Comment by christocracy** [comment]
Stationary geofence is the primary mechanism.  Motion-api is secondary.  Motion api relies upon user actually authorizing the “Health & Fitness” permission popup.

Also, if the app is terminated or device rebooted, there is no Motion API in-action.  However, iOS *always* allows geofence-monitoring to persist.  A fired geofence will cause iOS to relaunch your app to service the event and tracking initiates.

**Comment by Benjamin-Dewey** [comment]
Back to the original issue, I have discovered that with `debug: true` the problem goes away. It is only with `debug: false` that the issue arises. Is this expected behavior?

Also, I tried your suggestion of letting the app run without my `onActivityChange` listener and at first look it does seem to be behaving how I want so maybe the issue is no longer pertinent, but I am still curious as to its cause.

**Comment by Benjamin-Dewey** [comment]
> Also, I tried your suggestion of letting the app run without my `onActivityChange` listener and at first look it does seem to be behaving how I want

On further investigation this is only half true. The plugin does switch to the stationary state when I expect it to but it is not aggressive enough when it comes to switching to the moving state, so I do need to do this manually in `onActivityChange`. I went through the `config` docs to see if I could get the behavior I wanted just by using the `config` but I could not make it work.

I've changed [App.js](https://pastebin.com/qzRH8ZDQ) and the `config` to a setup that does give me the behavior I want without any issues. I did notice that adding `stopTimeout: 0` to the config caused the issue to resurface, but I don't think I need that piece of configuration anyways. Still, the fact remains that under certain conditions calling `changePace(true)` in the background causes the app to become suspended. Any idea as to why that might be?

**Comment by Benjamin-Dewey** [comment]
According to the docs
> the plugin enforces a **minimum** `stationaryRadius` of 25 and in-practice, the native API won't respond for at least 200 meters

so I don't think that will help. What I want is for the plugin to engage location tracking **immediately** when the device starts moving while the app is backgrounded. With the code I have in this new [App.js](https://pastebin.com/qzRH8ZDQ) I achieve this; I can pick up the device and walk ten meters and that entire journey is tracked until it goes back to stationary. I know it's probably not great for the battery, but my project would only need to be this aggressive once in a while, not all the time. If my technique of using `onActivityChange` sounds wrong I'm happy to hear your suggestion. 

As for the original issue, I don't know what more details I can give. If you want to try reproducing it just follow the information in the issue template.

**Comment by JohnTheo13** [comment]
I can also confirm that
  disableStopDetection: true wont prevent the suspension of the task

**Comment by christocracy** [comment]
**Nothing** will prevent iOS from throttling your app when plugin is in *stationary* state, unplugged from power and screen off.

If you’re attempting to have some code running continuously in this state, give up now, you’re wasting your time.  It will never work.

**Comment by JohnTheo13** [comment]
It was actually for Android, so I guess that wouldn't work too.
Thank you, you saved me time from trying to have a task working in the background forever

**Comment by christocracy** [comment]
preventSuspend is an Android-only config option.  This issue is an iOS issue.

**Comment by JohnTheo13** [comment]
disableStopDetection is marked as common option and it's not working

**Comment by christocracy** [comment]
The title of this *closed* issue is "preventSuspend not working"
- Platform: iOS
