### ISSUE TITLE
Is it possible to get phone's battery changes even app closed?

### ISSUE THREAD

**Issue by srhtylmz19** [transistorsoft/react-native-background-geolocation#645]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Each recorded location provided to the `onLocation` event contains the current [battery state](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.location.html#battery)

**Comment by srhtylmz19** [comment]
Yes i know but i want to get user location when his/her battery changed when even app is closed/killed.
Is it possible to do that? Please help me i stucked for days

**Comment by christocracy** [comment]
No.

**Comment by srhtylmz19** [comment]
isn't it possible to do that using by voip . please check the 'zenly' app

**Comment by christocracy** [comment]
This is a location-tracking plugin.  Not a battery-monitoring plugin.
