### ISSUE TITLE
HTTP post SOAP

### ISSUE THREAD

**Issue by jmlavoier** [transistorsoft/react-native-background-geolocation#647]
## Your Environment
* Plugin version: ^2.14.2
* Platform: Android MIUI
* OS version: Android 7.1.2
* Device manufacturer / model: XIAOMI 5X
* React Native version (`react-native -v`): 0.57.4

## Context
I'm looking for a documentation for customising the config to make a post with XML. I have a SOAP WebService.

**Comment by christocracy** [comment]
Soap.  Poor you.

The plugin doesn’t support xml, only JSON.
