### ISSUE TITLE
How to get state variables in Headless mode

### ISSUE THREAD

**Issue by SirKadogan** [transistorsoft/react-native-background-geolocation#648]
## Your Environment
* Plugin version: 2.14.2
* Platform: Android
* OS version:
* React Native version (`react-native -v`): 0.55.2
* Plugin config:

## Expected Behavior
I want to send geofence events to my Http endpoint when in Headless mode, with the app terminated. 

## Context
I send location events to my firebase database using the Plugin's http method. That is alright. Locations are also sent in the background or when the app is terminated. 
I don't get geofence events when the app is terminated or in the background. I need to run some javascript code when these events happen and send these to my database using firebase methods. 

Is headless the way to go? If so, how can I pass state variables to my headless mode? I need them for my path. The variables that I need for the path are also on the plugin's params. Is there a way to get the config's params?

**Comment by christocracy** [comment]
For Firebase, have you tried out my companion plugin [`react-native-background-geolocation-firebase`](https://github.com/transistorsoft/react-native-background-geolocation-firebase)?

>Is headless the way to go? If so, how can I pass state variables to my headless mode?

Yes, headless mode.  You could use [`react-native-shared-preferences`](https://github.com/sriraman/react-native-shared-preferences).

**Comment by SirKadogan** [comment]
Sweet, I'll check those out. 

Just a question: when the app is minimized, Headless mode doesn't kick in, right? Only when it is terminated. 

What is the advantage of your react-native-background-geolocation-firebase plugin over sending stuff manually? Does it use the same Premium Key as react-native-background-geolocation?

**Comment by christocracy** [comment]
>Just a question: when the app is minimized, Headless mode doesn't kick in, right? Only when it is terminated.

Correct.  

>What is the advantage of your react-native-background-geolocation-firebase plugin over sending stuff manually? 

One less thing to worry about.  The plugin will automatically post events to Firestore without the need for a Headless-task.  You can probably encode your "state variables" into the plugin's [#extras](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#extras) or [#params](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#params) config options.

>Does it use the same Premium Key as react-native-background-geolocation?

It's a separate product, with separate key.  $99 for 1 app.  $179 for infinite apps.

**Comment by SirKadogan** [comment]
Thank you for your replies, I found a better workaround for my problem. I used a listener on the geofence events sent with the location events and created a function for what I needed. 

I might end up using headless for some other features, but that is for another time hehe

**Comment by christocracy** [comment]
Headless is very easy to implement with RN.  Much harder with Cordova, where one must write native Android Java code.  Don’t be afraid of Headless Mode.
