### ISSUE TITLE
RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by cpirich** [transistorsoft/react-native-background-geolocation#651]
## Your Environment
* Plugin version: 2.13.4
* Platform: Android
* OS version: 7.0, 7.1.1
* Device manufacturer / model: Various (Samsung, LG, etc.)
* React Native version (`react-native -v`): 0.57.3
* Plugin config: varies (can't be certain for these specific crashes)

## Expected Behavior
No exception/crash

## Actual Behavior
We are seeing these exceptions in the wild - it appears to be a threading issue with an EventBus notification coming on a worker thread doing something that expects to be on the main thread:
```
RuntimeException
Can't create handler inside thread that has not called Looper.prepare()
android.os.Handler in <init> at line 200
android.os.Handler in <init> at line 114
com.transistorsoft.rnbackgroundgeolocation.HeadlessTask in <clinit> at line 37
java.lang.Class in classForName
java.lang.Class in forName at line 400
java.lang.Class in forName at line 326
com.transistorsoft.locationmanager.util.a in a1
com.transistorsoft.locationmanager.adapter.BackgroundGeolocation in _onLocationChange
java.lang.reflect.Method in invoke
org.greenrobot.eventbus.EventBus in invokeSubscriber at line 485
org.greenrobot.eventbus.EventBus in postToSubscription at line 416
org.greenrobot.eventbus.EventBus in postSingleEventForEventType at line 397
org.greenrobot.eventbus.EventBus in postSingleEvent at line 370
org.greenrobot.eventbus.EventBus in post at line 251
com.transistorsoft.locationmanager.location.TSLocationManager in onSingleLocationResult
java.lang.reflect.Method in invoke
org.greenrobot.eventbus.EventBus in invokeSubscriber at line 485
org.greenrobot.eventbus.EventBus in invokeSubscriber at line 479
org.greenrobot.eventbus.BackgroundPoster in run at line 64
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1133
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 607
java.lang.Thread in run at line 762
```

## Steps to Reproduce
Unclear, these are coming in via crash reports

## Context
Unclear

## Debug logs
Tried to extract some logs that were reported remotely before the crash. I can see these lines, but not much info unfortunately:
```
...
TSLocationManager: [c.t.l.BackgroundGeolocationService onDestroy] 
╔═════════════════════════════════════════════
║ BackgroundGeolocationService destroyed
╠═════════════════════════════════════════════
TSLocationManager: [c.t.l.BackgroundGeolocationService r] 
🔴 Unregister PowerSaveChangeReceiver: com.transistorsoft.locationmanager.BackgroundGeolocationService$1@48d1249
TSLocationManager: [c.t.l.BackgroundGeolocationService r] 
🔴 Unregister ConnectivityReceiver: com.transistorsoft.locationmanager.BackgroundGeolocationService$2@919374e
TSLocationManager: [c.t.l.ActivityRecognitionService b] 
🔴 Stop activity updates
TSLocationManager: [c.t.l.g.TSGeofenceManager b] 
🔴 Stop monitoring geofences
TSLocationManager: [c.t.l.BackgroundGeolocationService k] 
🔴 Stop heartbeat
TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️ Persist config
TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :true
```

**Comment by christocracy** [comment]
Do you have a license for Android?

**Comment by cpirich** [comment]
Yes - do you need the company name?

**Comment by christocracy** [comment]
Please.

**Comment by cpirich** [comment]
Convoy

**Comment by christocracy** [comment]
It's good.  Are you using the npm version `react-native-background-geolocation` or from private repo `react-native-background-geolocation-android`?

**Comment by cpirich** [comment]
from private repo `react-native-background-geolocation-android`
synced with commits up through Oct 1, 2018

**Comment by christocracy** [comment]
Please post customer support issues at private repo.

**Comment by JAStanton** [comment]
@christocracy fellow Convoy employee here w/ current access to Private repo, can you give him private repo access so he can repost?

**Comment by christocracy** [comment]
@JAStanton you should be able to [+ Add Member] in the dashboard, no?

**Comment by christocracy** [comment]
I believe this was fixed [here](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/HeadlessTask.java#L119)
