### ISSUE TITLE
[QUESTION] Callback when entering to stationary state 

### ISSUE THREAD

**Issue by Jose4gg** [transistorsoft/react-native-background-geolocation#654]
I want to set the stopTimeout property to 12 minutes in the configuration so after that time I 
can send a notification, but I don't see any callback that I can use when the plugin enters to a stationary state, should I use my own JS timer for this?

**Comment by christocracy** [comment]
[`#onMotionChange`](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#onmotionchange)

**Comment by Jose4gg** [comment]
So, then, why when I start the services (BG.start()), I get this motion change of false, if the stopTimout hasn't been reached yet?

**Comment by christocracy** [comment]
`onMotionChange` fires when the plugin *changes* state:
1.  stationary -> moving (`isMoving: true`)
2.  moving -> stationary (`isMoving: false`).  This is where you `stopTimeout` will have elapsed.

**Comment by christocracy** [comment]
It will also fire when the plugin *first enters* the stationary state, right after you call `#start`.
