### ISSUE TITLE
new extras are sent with old events

### ISSUE THREAD

**Issue by banduk** [transistorsoft/react-native-background-geolocation#658]
## Your Environment
* Plugin version: 2.14.0-beta.3
* Platform: iOS
* OS version: 12.1.4
* Device manufacturer / model: Apple iPhone XR
* React Native version: 0.57.1
* Plugin config:
```
{
  params: { 
    test_param: 1,
  },
  extras: {
    test_extra1: 1,
  },
   ...
}
```
then update using `background-fetch` to:
```
{
  params: { 
    test_param: 1,
  },
  extras: {
    test_extra1: 1,
    test_extra2: 2,
  },
   ...
}
```

## Expected Behavior
If device is offline and collects some points before config update, send all events collected before the config update with only `test_extra1` and all events collected after the config update with `test_extra1` and `test_extra2`.

## Actual Behavior
Sends all events with `test_extra1` and `test_extra2`.

## Steps to Reproduce
1. Use app offline some time collecting info with only `test_extra1`
2. Access internet to allow background fetch to update config with `test_extra2`
3. The locations that were not sent before the update will all be sent with `test_extra2`

## Context
Update configs dynamically and remotely to try to control battery usage.

**Comment by christocracy** [comment]
`extras` are persisted to the database at the time the location is recorded.  It's impossible for new `extras` to be applied to already recorded locations

**Comment by christocracy** [comment]
In fact, the plugin's HTTP service class doesn't even contain the symbol "extras" in the code at all.  The plugin's HTTP service is completely unaware of the concept of extras.

When a location is recorded, it has the `extras` appended at that time then the whole JSON blob is inserted in the database.

The HTTP service operates by `SELECT`ing records from the database.

**Comment by christocracy** [comment]
Btw, `2.14.0` has been [out of beta for ages](https://github.com/transistorsoft/react-native-background-geolocation/releases).

If you want to use a beta, use the new [`3.0.0-beta.2`](https://github.com/transistorsoft/react-native-background-geolocation/pull/657)
