### ISSUE TITLE
HTTP & Persistence Options: trust self-signed certificate

### ISSUE THREAD

**Issue by skaciroy92** [transistorsoft/react-native-background-geolocation#659]
I have installed and config successfully for my app working with rn-background-geolocation. It's a great plugin. However, i got an problem with connecting to my server (ip address) without self-certificate (https). 

This is error message: 
```
* The certificate for this server is invalid. You might be connecting to a server that is pretending to be “103.237.144.8” which could put your confidential information at risk.
*
{
    NSErrorClientCertificateStateKey = 0;
    NSErrorFailingURLKey = "https://103.237.144.8:8009/api/updateLocationDirectly";
    NSErrorFailingURLStringKey = "https://103.237.144.8:8009/api/updateLocationDirectly";
    NSErrorPeerCertificateChainKey =     (
        "<cert(0x7f7f01867e00) s: onelog i: onelog>"
    );
    NSLocalizedDescription = "The certificate for this server is invalid. You might be connecting to a server that is pretending to be \U201c103.237.144.8\U201d which could put your confidential information at risk.";
    NSLocalizedRecoverySuggestion = "Would you like to connect to the server anyway?";
    NSURLErrorFailingURLPeerTrustErrorKey = "<SecTrustRef: 0x608000118a50>";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1202 \"The certific
```

## Your Environment
* Plugin version: ^3.0.0-beta.1
* Platform: iOS
* OS version: 10 & 11 & 12
* Device manufacturer / model: iPhone 8 plus
* React Native version (`react-native -v`): 0.57.1
* Plugin config 

```
BackgroundGeolocation.ready({
            distanceFilter: 1000,
            stopOnTerminate: false,
            startOnBoot: true,
            foregroundService: true,
            batchSync: true,
            url: 'https://103.237.144.8:8009/api/updateLocationDirectly',
            params: {
                latitude: '123', /* hard code value first */
                longitude: 456, /* hard code value first */
                current_location: 123456 /* hard code value first */
            },
            autoSync: true,
            debug: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
        }, (state) => {
            console.log('- Configure success: ', state);
            if (!state.enabled) {
                BackgroundGeolocation.start(function() {
                    console.log("- Start success");
                });
            }
        });
```

## Expected Behavior
==>> Trust self certification to connect to ip address with https
https://103.237.144.8:8009/api/updateLocationDirectly

## Actual Behavior
==>> Error message: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “103.237.144.8” which could put your confidential information at risk.
No HTTP posts seen after starting app

## Steps to Reproduce

1. Install app on device + configure it
2. See HTTP posts going to configured endpoint

Many thanks!!!!

**Comment by skaciroy92** [comment]
I have already trust cert to call my ip address in app. I can call directly from app to my Apis, however rn-background-geolocation couldn't do it
Steps are same with this link:
[https://stackoverflow.com/questions/36289125/react-native-fetch-from-https-server-with-self-signed-certificate]()

**Comment by christocracy** [comment]
Doesn’t work with self-signed certain.

**Comment by mikehardy** [comment]
@skaciroy92 with Let's Encrypt you may find it's almost trivial to get SSL certs though. For instance using Express it's just a couple lines of code in your app startup and poof, auto-SSL-cert requested and installed. https://git.coolaj86.com/coolaj86/greenlock.js/src/branch/master/lib

**Comment by christocracy** [comment]
I’ll look into it when I return from vacation in 10 days.  If it’s easy, fine.

**Comment by christocracy** [comment]
Btw, 3.0.0 beta is now at beta.3.

I’m on vacation so updates will cease for next 10 days, but make sure to subscribe to repo updates and get latest beta asap.

**Comment by skaciroy92** [comment]
Thanks for your support!! Yep, i have installed a valid certificate in my domain to verify. It's working fine now, thanks
