### ISSUE TITLE
onMotionChange event fired when exiting the app

### ISSUE THREAD

**Issue by Luke-Tan** [transistorsoft/react-native-background-geolocation#660]
## Your Environment
* Plugin version: ^2.12.2
* Platform: iOS 
* OS version: 11
* Device manufacturer / model: iPhone 6s
* React Native version (`react-native -v`): ^0.55.4
* Plugin config 

```
{
	reset: true, 
	desiredAccuracy: 0,
	distanceFilter: 50,
	debug: false, 
	stationaryRadius: 50,
	preventSuspend: true,
	heartbeatInterval: 300,
}
```
## Expected Behavior

onMotionChange event should only fire when the device stops moving from a moving state or starts moving from a stopped state.
## Actual Behavior

onMotionChange event is fired when the app is closed (Home button is pressed, but app still running in the background). Below is a short log of what happens after the home button is pressed:
```
isMoving: false
location: {extras: {…}, coords: {…}, is_moving: false, event: "motionchange", odometer: 475, …}
__proto__: Object

isMoving: true
location: {extras: {…}, coords: {…}, is_moving: true, event: "motionchange", odometer: 711.3, …}
__proto__: Object
```
## Steps to Reproduce

App is run on an iPhone 6s simulator with Debug > Location > Freeway Drive
Using the above config, 
```
BackgroundGeolocation.on("motionchange", this.onMotionChange, this.onError);`
onMotionChange = event => {
	const { isMoving, location } = event;
	console.log(event);
};
```

**Comment by christocracy** [comment]
The plugin does not fire motionchange event due to pressing home button.
