### ISSUE TITLE
Vehicle activity not recognised for 2km

### ISSUE THREAD

**Issue by gtaylor44** [transistorsoft/react-native-background-geolocation#662]
Please provide recommendations to make location tracking more persistant. We will have truck drivers who will spend more than 5 minutes offloading their loads. GPS tracking needs to resume as soon as they leave the stop. 

## Your Environment
* Plugin version: 2.14.2
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Samsung SM-J530Y
* React Native version (`react-native -v`): 0.55.4
* Plugin config
```
{
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 25,
    extras: { tripCode },
    stopOnTerminate: false,
    startOnBoot: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    foregroundService: true,
    reset: true,
    url: appConfig.baseUrl + "api/trips/updatePosition",
    headers: {
      "Authorization": bearerToken
    }
  }
```

## Expected Behavior
When vehicle is moving after a stationary state lasting more than 5 minutes, GPS tracking should resume immediately. 

## Actual Behavior
After vehicle stationary for > 5 minutes, GPS tracking is delayed when resuming movement. After location services were turned off, vehicle was moving for at least 5 minutes before tracking resumed. 

## Context
Location tracking should be more persistant. 

## Debug logs
03-07 17:40:12.664 DEBUG [c unlock] 
  ✅  UNLOCKED: cb6c6ae1-401c-44df-86c3-3a8b391bf25d
03-07 17:40:19.861 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (94%)
03-07 17:40:49.827 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (71%)
03-07 17:40:49.848 INFO [BackgroundGeolocationService onActivityRecognitionResult] 
  🔵  Stop-timeout timer initiated (5 min)...
03-07 17:40:49.865 INFO [BackgroundGeolocationService h] 
  🔵  Begin stop timer
03-07 17:40:58.621 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:40:58.649 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
03-07 17:41:07.986 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:41:08.008 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
03-07 17:41:16.785 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:41:16.815 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
03-07 17:41:25.587 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:41:25.612 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
03-07 17:41:34.390 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:41:34.417 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
03-07 17:41:43.178 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:41:43.202 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 0
03-07 17:41:51.972 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:41:51.989 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 1
03-07 17:42:00.753 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:42:00.775 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 1
03-07 17:42:09.579 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:42:09.598 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 1
03-07 17:42:18.364 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:42:18.384 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 1
03-07 17:42:27.202 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:42:27.222 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 1
03-07 17:42:35.993 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:42:36.013 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 1
03-07 17:42:44.804 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:42:44.822 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 1
03-07 17:42:53.596 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:42:53.624 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 2
03-07 17:43:03.450 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:43:03.471 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 2
03-07 17:43:12.268 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:43:12.291 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 2
03-07 17:43:21.101 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:43:21.128 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 2
03-07 17:43:29.890 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:43:29.915 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 2
03-07 17:43:38.685 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:43:38.714 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 2
03-07 17:43:47.473 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:43:47.496 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 2
03-07 17:43:56.260 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:43:56.283 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 3
03-07 17:44:05.048 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:44:05.078 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 3
03-07 17:44:13.869 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:44:13.888 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 3
03-07 17:44:22.665 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:44:22.687 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 3
03-07 17:44:31.445 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:44:31.460 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 3
03-07 17:44:40.269 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:44:40.289 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 3
03-07 17:44:49.069 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:44:49.091 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 3
03-07 17:44:57.872 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:44:57.895 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 4
03-07 17:45:06.706 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:45:06.722 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 4
03-07 17:45:15.515 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:45:15.541 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 4
03-07 17:45:24.311 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:45:24.338 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 4
03-07 17:45:33.090 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:45:33.117 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 4
03-07 17:45:41.888 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:45:41.910 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 4
03-07 17:45:50.701 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:45:50.723 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] 
  ℹ️  Waiting for stopTimeout (5 min): elapsed min: 5
03-07 17:45:50.743 DEBUG [BackgroundGeolocationService i] 
03-07 17:45:50.754 INFO [TSLocationManager d] 
  🔴  Location-services: OFF
03-07 17:45:50.764 INFO [BackgroundGeolocationService a] 
  🔵  setPace: true → false
03-07 17:45:50.776 DEBUG [TSConfig c] ℹ️   Persist config
03-07 17:45:50.790 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
03-07 17:45:53.369 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 3
╠═════════════════════════════════════════════
╟─ 📍  Location[fused -33.749480,151.263555 hAcc=16 et=+3d8h52m1s952ms alt=117.0 vel=0.089999996 vAcc=32 sAcc=??? bAcc=??? {Bundle[{requestId=3, verticalAccuracy=32.0}]}], age: 13ms, time: 1551941151009

03-07 17:45:53.372 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: false
03-07 17:45:53.408 DEBUG [TSLocationManager a] 7.0
03-07 17:45:53.435 INFO [c persist] 
  ✅  INSERT: fd0ae7cd-5479-4122-b3b8-d2f95a051383
03-07 17:45:53.447 DEBUG [HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service
╠═════════════════════════════════════════════

03-07 17:45:53.463 DEBUG [c first] 
  ✅  Locked 1 records
03-07 17:45:53.473 INFO [HttpService a] 
  🔵  HTTP POST: cb6c6ae1-401c-44df-86c3-3a8b391bf25d
03-07 17:45:53.484 WARN [HttpService$a onFailure] 
  ⚠️  Response: 0, Failed to connect to /223.27.19.221:1111
03-07 17:45:53.493 DEBUG [c unlock] 
  ✅  UNLOCKED: cb6c6ae1-401c-44df-86c3-3a8b391bf25d
03-07 17:46:00.445 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:46:09.249 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:46:18.080 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:46:26.923 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:46:35.721 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:46:44.528 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:46:53.339 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:47:02.503 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:47:11.503 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:47:20.489 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:47:29.352 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:47:38.487 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:47:47.506 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:48:01.487 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:48:10.491 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:48:19.502 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:48:28.501 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:48:37.516 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:48:46.491 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 17:48:55.489 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 18:01:08.179 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (49%)
03-07 18:01:42.976 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (66%)
03-07 18:02:13.210 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (74%)
03-07 18:02:22.508 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (90%)
03-07 18:02:22.534 INFO [BackgroundGeolocationService k] 
  🔴  Stop heartbeat
03-07 18:02:22.550 INFO [BackgroundGeolocationService a] 
  🔵  setPace: false → true
03-07 18:02:28.013 DEBUG [TSConfig c] ℹ️   Persist config
03-07 18:02:28.030 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
03-07 18:02:31.486 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] in_vehicle (96%)
03-07 18:02:31.785 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 4
╠═════════════════════════════════════════════
╟─ 📍  Location[fused -33.755154,151.285484 hAcc=700 et=+3d9h8m36s752ms vAcc=??? sAcc=??? bAcc=???], age: 3636ms, time: 1551942148148

03-07 18:02:31.786 DEBUG [TSLocationManager a] 7.0
03-07 18:02:33.219 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 4
╠═════════════════════════════════════════════
╟─ 📍  Location[fused -33.755154,151.285484 hAcc=700 et=+3d9h8m41s779ms vAcc=??? sAcc=??? bAcc=???], age: 40ms, time: 1551942153174

**Comment by gtaylor44** [comment]
Device has all motion sensors that the app utilises.

**Comment by gtaylor44** [comment]
Between these times, vehicle was moving. Phone was not moved from the seat during this time. 

03-07 17:48:55.489 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-07 18:01:08.179 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (49%)

**Comment by mikehardy** [comment]
I'm just a user like yourself, but you could try lower confidence values, and smaller distanceFilter I think, if I understand the docs correctly.

**Comment by christocracy** [comment]
You might have better luck with budget devices, such as your Samsung J, with 3.0.0-beta, which now uses a stationary geofence like iOS, in addition to the traditional Motion API triggering,

**Comment by gtaylor44** [comment]
Thanks for the recommendations. 

We will give this a go.

On the topic of budget phones, what phone model would you consider as an entry level phone for this library? What is the best value for buck? We got this model as our test device because it had all the sensors.

**Comment by christocracy** [comment]
No idea the exact constraints of budget device.  I happen to own a Samsung J among my family of ~13 test devices and it’s the cheapest, lightest crappiest, worst performing device of the lot.  

For me in Canada, a budget device is ~$200 and less.  $500 gets you a decent device for dev and testing.

**Comment by fas3r** [comment]
Hello @christocracy , 

Is there any list of "recommended" devices to use with ? I'm new with that plugin ( great btw ) and I'm just wondering how to manage very low cost phone ( < 20$ ), if we have a way to limit to specific model / brand. 

Thanks.

**Comment by christocracy** [comment]
These are my devices (* for preferred):

- Galaxy Nexus @ 4.3
- Nexus 4 @ 4.4.4
- Lenovo A6000 @ 5.0.2
- * Nexus 5 @ 6.0.1
- Nexus 6 @ 6.0.1
- * Google Pixel @ 9.0.0
- * Samsung S7 @ 6.0.1
- Samsung J @ 6.0.1
- * Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 9.0.0
- Nokia TA-1027 @ 8.0.0
- * OnePlus A5010 @ 8.0.0

**Comment by fas3r** [comment]
Hello @christocracy , 

Thanks for your reply I was not expecting any so soon. Ok, an other, a bit related, regarding power consumption. In case of geofencing with only few push (HTTP) to the server every X hours from the sqlite Db, can we expect the battery to latest half a day ? 
I know that the battery life with always depends on different factors like if the user is playing or watching something while using reac-native-background-geolocation it will not last long. 
I'm thinking of hiking for example, or the example around iceland. Just to make see some stats on the barrety consumption and based
