### ISSUE TITLE
Call start after setConfig

### ISSUE THREAD

**Issue by KowalskiP** [transistorsoft/react-native-background-geolocation#665]
## Your Environment
* Plugin version: 3.0.0-beta.4
* Platform: iOS, Android
* OS version: Doesn't matter
* Device manufacturer / model: Doesn't matter
* React Native version (`react-native -v`): 0.57.1
* Plugin config: changing frequently

## Steps to Reproduce

1. await BackgroundGeolocation.setConfig(newConfig)
2. await BackgroundGeolocation.start();

## Context
My app need to change config frequently. Should I always call 'start' after 'setConfig'?

**Comment by christocracy** [comment]
No.  The plugin has internal listeners on config changes and will automatically reconfigure itself in real time.
