### ISSUE TITLE
access states and props in task background

### ISSUE THREAD

**Issue by MatheusLima7** [transistorsoft/react-native-background-geolocation#666]
## Your Environment
* Plugin version: 3.0.0
* Platform: iOS
* OS version: 12.1
* Device manufacturer / model: iPhone 5s
* React Native version (`react-native -v`): 0.58.1
* Plugin config

## Expected Behavior
I would like to access states and props in task background.
If you do not have access:
Can I send some state or props to the background task?

## Actual Behavior
this.props undefined in onLocation
this.state undefined in onLocation

## Steps to Reproduce

    BackgroundGeolocation.onLocation(this.onLocation, this.onError);
    BackgroundGeolocation.onMotionChange(this.onMotionChange);
    BackgroundGeolocation.onActivityChange(this.onActivityChange);
    BackgroundGeolocation.onProviderChange(this.onProviderChange);
    BackgroundGeolocation.ready({
      reset: true, 
      foregroundService: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      notificationTitle: 'APP Essenziale',
      notificationText: 'Verificando sua posição',
      stopTimeout: 1,
      debug: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: true,
      startOnBoot: true,     
    }, (state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log("- Iniciou");
        });
      }
    });

 onLocation(location) {
    console.log('[Atualização na localização] -', location );
    console.log(this.props) // undefined
    console.log(this.state) // undefined
 }
  onError(error) {
    console.warn('[location] ERROR -', error);
  }
  onActivityChange(event) {
    console.log('[Alteração na Atividade de Movimento] -', event);  // eg: 'on_foot', 'still', 'in_vehicle'
  }
  onProviderChange(provider) {
    console.log('[Usuário ativou/desativou serviço de localização] -', provider.enabled, provider.status);
  }
  onMotionChange(event) {
    console.log('[Status do Movimento mudou (parado/Andando)] -', event.isMoving, event.location);
  }

**Comment by christocracy** [comment]
Your problem is a "Javascript 101" issue.  You're not binding `this` to your event-listeners.

```diff
+BackgroundGeolocation.onLocation(this.onLocation.bind(this), this.onError.bind(this));
+BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
+BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));
+BackgroundGeolocation.onProviderChange(this.onProviderChange.bind(this));
```

**Comment by MatheusLima7** [comment]
Great @christocracy
