### ISSUE TITLE
 Tried to start task BackgroundGeolocation while in foreground

### ISSUE THREAD

**Issue by listenyourheart** [transistorsoft/react-native-background-geolocation#667]
## Your Environment
* Plugin version:react-native-background-geolocation: "2.12.1"
* Platform:Android 7
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):2.0.1

* Plugin config
{
    "activityRecognitionInterval": 3000,
    "allowIdenticalLocations": false,
    "autoSync": false,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "debug": false,
    "deferTime": 0,
    "desiredAccuracy": 10,
    "desiredOdometerAccuracy": 100,
    "disableElasticity": false,
    "disableStopDetection": false,
    "distanceFilter": 5,
    "elasticityMultiplier": 1,
    "enableHeadless": true,
    "extras": {},
    "fastestLocationUpdateInterval": 1000,
    "forceReloadOnBoot": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnSchedule": false,
    "foregroundService": false,
    "geofenceInitialTriggerEntry": true,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {},
    "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",
    "heartbeatInterval": -1,
    "httpRootProperty": "location",
    "httpTimeout": 60000,
    "isMoving": false,
    "locationTemplate": "",
    "locationTimeout": 60,
    "locationUpdateInterval": 1000,
    "locationsOrderDirection": "ASC",
    "logLevel": 4,
    "logMaxDays": 4,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": 0,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 50,
    "notificationColor": "",
    "notificationLargeIcon": "",
    "notificationPriority": 0,
    "notificationSmallIcon": "",
    "notificationText": "Location Service activated",
    "notificationTitle": "",
    "params": {},
    "persist": true,
    "schedule": [],
    "startOnBoot": true,
    "stationaryRadius": 25,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": false,
    "stopTimeout": 5,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "",
    "enabled": true,
    "schedulerEnabled": false,
    "trackingMode": 1,
    "odometer": 1194360.75,
    "isFirstBoot": false
}
## Context
Hello, excuse my english, because I use a translator here.

I display push notifications in some situations, in headless mode and when the application is viewed (with alerts).

I noticed that after a duration, the notifications stop appearing, when I look at the logs, I suspect this error:

  **! ️ Tried to start task BackgroundGeolocation while in foreground, but this is not allowed.**

I have foregroundService: false in my configuration.
I do not have it all the time.

## Debug logs
03-23 13:29:06.461 DEBUG [SingleLocationRequest$2 onLocationResult] 
╔═════════════════════════════════════════════
║ SingleLocationRequest: 300
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 49******,2****** acc=21 et=+1d4h29m59s509ms alt=48.40346928406507 vel=0.0], age: 5ms, time: 1553344146453

03-23 13:29:06.463 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
03-23 13:29:06.478 DEBUG [TSLocationManager a] 23.123
03-23 13:29:06.495 DEBUG [BackgroundGeolocation isMainActivityActive] NO
03-23 13:29:06.528 INFO [c persist] 
  ✅  INSERT: ac487657-ff3c-464f-a378-fb1335ec1433
03-23 13:29:06.536 DEBUG [c a] 
  ℹ️  SHRINK: 0
03-23 13:29:06.545 DEBUG [HeadlessTask <init>] 💀  event: location
03-23 13:29:06.549 ERROR [HeadlessTask$2 run] 
  ‼️  Tried to start task BackgroundGeolocation while in foreground, but this is not allowed.
03-23 13:29:13.002 DEBUG [BackgroundGeolocation isMainActivityActive] NO
03-23 13:29:13.022 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
03-23 13:29:13.027 DEBUG [b a] 
  ℹ️  LocationAuthorization: Permission granted
03-23 13:29:13.039 DEBUG [BackgroundGeolocation isMainActivityActive] NO
03-23 13:29:13.052 DEBUG [HeadlessTask <init>] 💀  event: activitychange
03-23 13:29:13.068 ERROR [HeadlessTask$2 run] 
  ‼️  Tried to start task BackgroundGeolocation while in foreground, but this is not allowed.

Thank You

**Comment by christocracy** [comment]
This error is coming from react-native.

https://github.com/vikeri/react-native-background-job/issues/52

**Comment by listenyourheart** [comment]
thank you for the quick answer , but I don't understand why I do not have this error all the time
