### ISSUE TITLE
How to determine if someone is outside the geofence?

### ISSUE THREAD

**Issue by DusanDimitric** [transistorsoft/react-native-background-geolocation#668]
# How to determine if someone is inside or outside the geofence?

At the moment of creating a geofence - can we know if the user is **inside** or **outside** of it? That would be VERY valuable information.

The way we are doing it now is a **hack** that goes like this:

0. Start the plugin in geofencing mode with geofence listeners set up
1. Create a Geofence
2. Schedule a synthetic **EXIT** event to fire for that newly created geofence after 30 seconds
3. If an **ENTER** event fires before those 30 seconds expire, we cancel the scheduled **EXIT**.

That way we know - if the scheduled **EXIT** event fires we know someone is outside, if **ENTER** fires we know that he is inside.

This has proven not to be reliable when the app is in the background or killed and that's why we're opening this issue.

Thanks a lot!
Dusan D. - Mitipi

## Your Environment
* Plugin version: 2.14.2
* Platform: iOS and Android (both)
* OS version: (iOS 12, Android 9)
* Device manufacturer / model: Apple iPhone 5, Xiaomi Mi A2
* React Native version (`react-native -v`): 0.56.1
* Plugin config - we use the plugin in geofencing mode, by calling `.startGeofences()` method.

Configuration file:

```
{
  geofenceInitialTriggerEntry: true,
  geofenceProximityRadius: 7000, // only activate geofences logic for ones within these radius to save battery
  radius: 300, // geofence radius around 300m

  // Application config
  stopOnTerminate: false, // Allow the background-service to continue tracking when user closes the app.
  startOnBoot: true       // Auto start tracking when device is powered-up.
}
```

## Expected Behavior
We would like to know if someone is outside the geofence (or inside).

## Actual Behavior
We can't seem to find the way to do it.

## Context
_Irrelevant_

## Debug logs
_Irrelevant_

**Comment by christocracy** [comment]
Since you've configured `geofenceInitialTriggerEntry: true`, the geofence will fire immediately if the device is already **inside**.  If it does fire, the device is **outside**.
