### ISSUE TITLE
IOS Build fails

### ISSUE THREAD

**Issue by leighquince** [transistorsoft/react-native-background-geolocation#669]
* Plugin version: 3.0.0-beta.4
* Xcode version: 10.2
* react-native-cli: 2.0.1
* react-native: 0.59.2

## Context
I am unable to build a fresh project with the latest release as receive 2 errors in `RNBackgroundGeolocation.h:27`;

- `No type or protocol named 'RCTInvalidating'`
- `Reference to 'RCTInvalidating' is ambiguous `

## Steps to Reproduce
```
react-native init geolocation_test
cd geolocation_test
yarn add react-native-background-geolocation
react-native link react-native-background-geolocation
react-native link react-native-background-fetch
react-native link cocoa-lumberjack
react-native run-ios
```

## Debug logs
```
In file included from /Users/***/dev/workspaces/geolocation_demo/node_modules/react-native-background-geolocation/ios/RNBackgroundGeolocation/RNBackgroundGeolocation.m:8:
/Users/***/dev/workspaces/geolocation_demo/node_modules/react-native-background-geolocation/ios/RNBackgroundGeolocation/RNBackgroundGeolocation.h:27:55: error: reference to 'RCTInvalidating' is ambiguous
```

**Comment by christocracy** [comment]
I have a report of this from a customer in the private repo:

Quick fix: `RNBackgroundGeolocation.h`

Change:
```diff
-if __has_include(“RCTInvalidating.h”)
-    #import “RCTInvalidating.h”
-else
    #import <React/RCTInvalidating.h>
-endif

**Comment by leighquince** [comment]
thanks for the speedy reply much appreciated, will try that out now

**Comment by christocracy** [comment]
I will update the plugin in `3.0.0-rc.1` due out today.

**Comment by lfkwtz** [comment]
mind releasing a 2.14.3 with just this fix while 3.x is still in RC?
