### ISSUE TITLE
Question: does background-fetch help geofence to trigger events faster?

### ISSUE THREAD

**Issue by lkknguyen** [transistorsoft/react-native-background-geolocation#672]
Does configuring background-fetch to query location like every 15m helps geofence to trigger events faster or more accurate? I think when the system got an accurate location, it helps to trigger geofencing events better.

Am I correct or configuring background-fetch for location will not affect geofencing at all?

**Comment by christocracy** [comment]
>Does configuring background-fetch to query location like every 15m

No

> or configuring background-fetch for location will not affect geofencing at all?

Doesn't affect it.  Are you using [latest 3.0.0-rc.3](https://github.com/transistorsoft/react-native-background-geolocation/pull/671)?

**Comment by lkknguyen** [comment]
I'm using "^2.14.2", would it make any difference?

**Comment by christocracy** [comment]
3.0.0 is a significant re-factor of Android.  Read the PR note carefully and start using 3.0.0
