### ISSUE TITLE
Deviation from the real position

### ISSUE THREAD

**Issue by npasparuhov** [transistorsoft/react-native-background-geolocation#673]
## Your Environment
* Plugin version: 2.14
* Platform: Android
* OS version: SDK 24, 28
* Device manufacturer / model: Samsung A7 and Xiaomi Redmi Note 5
* React Native version (`react-native -v`): 0.58.6
* Plugin config:
```
activityRecognitionInterval: 0,
fastestLocationUpdateInterval: 0,
distanceFilter: 1,
disableElasticity: true,
debug: true,
foregroundService: true,
stopOnTerminate: false,
```

## Expected Behavior
To detect the position more accurate and into the right direction

## Actual Behavior
https://imgur.com/hWYHQfs
As you can see on the picture, the real path that was walked is in the black line, but the plugin itself gives us a point that are very far away from the real position, in the end the gap is around 50 meters for our purpose we need max 20m gap between the real path and the point that the plugin gives us

## Steps to Reproduce
1. react-native init helloworld
2. follow the instructions from the repo to install the plugin
3. use the config from above
4. walk around and send all location to some api, after the walk plot the locations on

**Comment by christocracy** [comment]
The plugin is the mail man.  It's not responsible for the contents of the mail it delivers.

What are the reported accuracy of those locations?  GPS isn't perfect.  It can get confused with reflections from tall buildings and other physical obstructions.

**Comment by npasparuhov** [comment]
https://www.google.com/maps/d/u/0/edit?mid=1a0CaUwsl-a3oQoAH015twgg4RqX3Lcmp&ll=48.865719054889894%2C2.3382598282498748&z=19

The accuracy is mostly around 5 and the confidence is around 85-95%

**Comment by christocracy** [comment]
The plugin has no possible way of assessing the validity of data returned by the device location api, whether it matches the real world, particularly when reporter accuracy is 5 meters.

It’s an anomaly due to the device or environment.

The plugin does now have an anomaly detector, but that only kicks in if the location “teleports” so far away that the apparent speed to get to current location from previous is > jet plane speed.

**Comment by mikehardy** [comment]
Fascinating! I see the API you mention here:

https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#speedjumpfilter

Disconnected (except for the context) from this issue, would it be possible to emit an event or call a callback instead of throwing it away? GPS is spoofable and this is one of the easiest ways to flag a point as possibly spoofed - something I'm interested in but thought I was going to have to implement in JS

**Comment by christocracy** [comment]
>GPS is spoofable and this is one of the easiest ways to flag a point 

If by *spoofable*, you mean via radio, yes.  If you mean via *mock* location app (eg: Lockito), you can detect those via [`Location.mock`](https://transistorsoft.github.io/react-native-background-geolocation-android/interfaces/_react_native_background_geolocation_android_.location.html#mock)

>would it be possible to emit an event or call a callback instead of throwing it away?

Sure.  Could emit into the `#onLocation` event with some flag like `teleport: true`.

**Comment by christocracy** [comment]
It should also be tagged with `sample: true` since people are already used to that and probably already have logic to ignore those.

```javascript
BackgroundGeolocation.onLocation((location) => {
  if (location.sample) {
    if (location.teleport) {
      console.warn('- Teleported: ', location);
    }
    return;
  }
  console.log('[onLocation] success: ', location);
}, (error) => {
  console.log('[onLocation] ERROR: ', error);
});
```

**Comment by mikehardy** [comment]
It is possible to root a phone and with Magisk still pass SafetyNet - i.e, it is impossible from an app to determine if the device is rooted, so you can't know that your programs inputs (the GPS coordinates coming in from the "sensors") are really from the sensors or not. And then there are programs that let you overlay a joystick on any app and just "drive" the GPS point around where ever you want, so the app thinks the coordinates are real. But even the best spoofer teleports occasionally, so teleport points are a very strong signal that you likely need to have a conversation with the user...

This is probably the most powerful one https://play.google.com/store/apps/details?id=com.incorporateapps.fakegps and I can tell you I have seen it work as can all of /r/PokemonGoSpoofing - one of the more fascinating sub-cultures I've seen...you might actually like that app for testing, vs Mockito.

I like the proposed API - exposing it for inspection for those that are interested

**Comment by christocracy** [comment]
Noted:
```java
} else if (locationIsInvalid(l)) {
                /* TODO enable following to allow teleport locations as samples into EventBus https://github.com/transistorsoft/react-native-background-geolocation/issues/673
                Bundle extras = l.getExtras();
                extras.putBoolean("teleport", true);
                extras.putBoolean("sample", true);
                */
                continue;
            }
```

**Comment by GigiRewind** [comment]
I just watched the screenshot of @npasparuhov and I feel like your algorithm is using the previous points to compute the next ones, is it correct ? or is it just faulty GPS data? 

Btw I detected a strange behaviour when turning (left or right), sometimes the data shows that I'm going left when I'm in fact doing the opposite and it takes 5-7 data points (refreshed every 1m) before refreshing the data. Is there any way to optimise that ?

Thanks so much for your help ! Big fan of your work btw

**Comment by christocracy** [comment]
> Is there any way to optimise that ?

No.  Native location-services API is like a tap of water.  The plugin is a robot that turns the taps on, allowing you to adjust the "flow" (`distanceFilter`) as well as the "heat" (`desiredAccuracy`).

The plugin holds a cup beneath the taps to gather the water that drips out, delivering them directly to you.

If the water is "poisoned", it's not the fault of the cup, it's the fault of the city's water system.
