### ISSUE TITLE
Is it possible to setConfig when app changes from foreground to background?

### ISSUE THREAD

**Issue by mchiang88** [transistorsoft/react-native-background-geolocation#675]
## Your Environment
* Plugin version:  3.0.0-rc.5
* Platform: iOS & Android
* OS version:
* Device manufacturer / model:
* React Native version:  0.59.0
* Plugin config:
```
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      stopOnStationary: false,
      stationaryRadius: 25,
      startOnBoot: true,
      locationUpdateInterval: 60000,
      foregroundService: true,

      allowIdenticalLocations: true,
      preventSuspend: true,
      heartbeatInterval: 60,
      locationAuthorizationRequest: 'Always',
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Location services must be enabled to use this app',
        titleWhenOff: 'Please turn location services on to use this app',
        instructions: 'Enable Always in location services',
        cancelButton: 'Cancel',
        settingsButton: 'Settings',
```

## Expected Behavior

Would like to set a different `heartbeatInterval` when app is in the background.

## Actual Behavior

Unable to setConfig when app changed to background

## Steps to Reproduce

1.
2.
3.
4.

## Context

I'm trying to `getCurrentPosition` at different intervals:  once every 60 seconds in foreground, once every 300 seconds in background

**Comment by christocracy** [comment]
Probably.  Why don't you try it?

**Comment by mchiang88** [comment]
Yes, I am trying - thanks for the suggestion.  Did not find any modules to determine app foreground/background status in the docs.

**Comment by mikehardy** [comment]
https://facebook.github.io/react-native/docs/appstate.html

**Comment by mikehardy** [comment]
I just saw that in the docs while looking for something else. Haven't tried it yet myself but am very interested how it goes if you try it...

**Comment by mchiang88** [comment]
Cheers @mikehardy
