### ISSUE TITLE
Sync method sometimes return error with an integer

### ISSUE THREAD

**Issue by theill** [transistorsoft/react-native-background-geolocation#677]
Calling `sync()` will throw an error with an integer sometimes and I'm not sure what this integer indicates. Can't find it in the docs.

## Your Environment
* Plugin version: 2.14.2
* Platform: iOS
* OS version: 12.0
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`): 0.53.2
* Plugin config

## Expected Behavior
It's probably related to a network issue but I just want to know what I need to do with the returned error code.

## Actual Behavior
An Error object with more details than just an integer.

## Steps to Reproduce
Calling

          try {
            await BackgroundGeolocation.sync()
          } catch (err) {
            Log.warn(`Unable to sync locations: ${err}`)
          }

Sometimes throw an `err` of `3` but I have also seen `undefined` in my logs.

## Context
Syncing existing locations

**Comment by christocracy** [comment]
Try listening to the `onHttp` event for errors.

**Comment by theill** [comment]
Thanks I'll try that but would still like to know what the thrown error with code "3" indicates from a `sync()` operation.

**Comment by christocracy** [comment]
I think it's the count of the number of records that successfully uploaded.

**Comment by theill** [comment]
Ah, ok - so the async/await implementation throws an error with the number
of records successfully synced before the error? That could make sense.
Thanks.

--
*Peter Theill*
CTO & Co-founder
+45 6171 5096 <61%2071%2050%2096>
peter@familiohq.com

*Familio*
Købmagergade 22, 2.
DK-1150 Copenhagen K
https://familiohq.com/

**Comment by christocracy** [comment]
A `#sync` action *has many* `onHttp` events.

Eg:  If there are current 3 records in the queue and assuming `batchSync: false`, there will be an `onHttp` event for each record:
```
sync
  - `onHttp` record 1
  - `onHttp` record 2
  - `onHttp` record 3
```
