### ISSUE TITLE
HeadlessJS events cannot be dispatched

### ISSUE THREAD

**Issue by tomekstankowski** [transistorsoft/react-native-background-geolocation#678]
## Your Environment
* Plugin version: 3.0.0-rc.5
* Platform: Android
* OS version: API 23, 28 (possibly others)
* Device manufacturer / model: Xiaomi Redmi 5 Plus, emulator
* React Native version (`react-native -v`): 0.59.3
* Plugin config
{
    distanceFilter: 0,
    stopOnTerminate: false,
    startOnBoot: true,
    heartbeatInterval: 60,
    stopTimeout: 1,
    reset: true,
    debug: true,
    // Android only
    enableHeadless: true,
    allowIdenticalLocations: true,
    foregroundService: true,
    locationUpdateInterval: 5000,
    // iOS only
    preventSuspend: true
  }
## Expected Behavior
All BackgroundGeolocation events should be handled by headless task.

## Actual Behavior
`connectivitychange` event is properly handled. For `heartbeat` event I get following exception logged (I know it's for heartbeat because it comes in regular intervals as specified in config):
```
04-08 11:46:01.129  5519  5550 I ReactNativeJS: '[BackgroundGeolocation HeadlessTask] -', 'connectivitychange', { connected: true }
04-08 11:47:00.360  5519  5519 E EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent to subscribing class class com.transistorsoft.rnbackgroundgeolocation.HeadlessTask
04-08 11:47:00.360  5519  5519 E EventBus:      at com.transistorsoft.rnbackgroundgeolocation.HeadlessTask.startTask(HeadlessTask.java:109)
04-08 11:47:00.360  5519  5519 E EventBus:      at com.transistorsoft.rnbackgroundgeolocation.HeadlessTask.onHeadlessEvent(HeadlessTask.java:95)
```
Also I can't see headless logs running `adb logcat -s TSLocationManager` (as shown in example), instead I do it via `adb logcat | grep Headless`.
## Steps to Reproduce
Here is how I register HeadlessTask in `index.js`:
```AppRegistry.registerComponent(appName, () => App)

let HeadlessTask = async (event) => {
    let params = event.params;
    console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params)
    
    switch (event.name) {
        case 'terminate':
            console.log('[BackgroundGeolocation HeadlessTask] - App has been terminated:');
            break
      case 'heartbeat':
        console.log('hearbeat HeadlessJS')
        break
    }
  }

  BackgroundGeolocation.registerHeadlessTask(HeadlessTask)
```
1. `react-native run-android`
2. terminate app
3. see logs with `adb logcat | grep Headless`

**Comment by christocracy** [comment]
I see the problem.  Fix will be posted tomorrow.

**Comment by 1602** [comment]
I just run into this issue too, was it fixed?

**Comment by christocracy** [comment]
See [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#304---2019-05-08)

>[Fixed] Android headless heartbeat events were failing (incorrect Context was supplied to the event).

**Comment by 1602** [comment]
Thanks, updating to version 3.0.4 fixed this issue for me.
