### ISSUE TITLE
getCurrentPosition on Android not working without Location Settings enabled

### ISSUE THREAD

**Issue by m00gl3** [transistorsoft/react-native-background-geolocation#679]
## Your Environment
* Plugin version: 3.0.0-rc.5
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: OnePlus2
* React Native version (`react-native -v`): 0.57.7
* Plugin config
{
            // Geolocation Config
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
            distanceFilter: 10,
            reset: true,
            preventSuspend: true,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            foregroundService: true,
            // Application config
            debug: true,    
            stopOnTerminate: false, 
            startOnBoot: true,
            heartbeatInterval: 60,
            //   enableHeadless: true
        }

## Expected Behavior

Running getCurrentPosition in the HeartBeat event should return location.

## Actual Behavior

I have Location Permissions enabled for the app.
I am getting an event in onHeartbeat every 60 seconds as expected, however, 
running getCurrentPosition in the HeartBeat event I get error == 1 (permission denied).

## Steps to Reproduce

This happens if the location settings is OFF.

![location_off](https://user-images.githubusercontent.com/1267581/55726352-441d5a00-5a18-11e9-816c-507876155fec.png)

If I MANUALLY turn on location settings, then everything works as expected.
Turning the location settings ON shows a dialog on Android.

![location_on](https://user-images.githubusercontent.com/1267581/55726365-4d0e2b80-5a18-11e9-8bbb-a085c13f9f2c.png)

## Context

We want to be able to get user location every 60 seconds WITHOUT intervention from the user, once he/she accepted the location permissions (foreground for now)

Is this possible? I tried with the Demo Application and it also DID NOT WORK unless Location Settings was enabled.

**Comment by christocracy** [comment]
How do you expect the device to return a location if location-services is *disabled*?

**Comment by m00gl3** [comment]
> How do you expect the device to return a location if location-services is _disabled_?

I come from an Android native development background. If I remember correctly, FusedLocation with aGPS (Wifi/Cellular) should allow to retrieve location (even lastKnownLocation) without the Location services being enabled.  If I choose priority DESIRED_ACCURACY_MEDIUM it should get the location via Wifi/Cellular.

Any thoughts on this?

**Comment by christocracy** [comment]
If the user wants to hide from an app by disabling location services, they can.

You must respect the user’s desire to hide from you.

**Comment by m00gl3** [comment]
> If the user wants to hide from an app by disabling location services, they can.
> 
> You must respect the user’s desire to hide from you.

We don't mind showing a dialog to the user, asking for permission to track him/her.
Once we have consent, we would like to be able to track the user without having to enable the location services each time (which would require an additional dialog)

What do you think about the solution described here?
[https://stackoverflow.com/a/50174178](StackOverflow)

**Comment by christocracy** [comment]
If the user has disabled location-services, the plugin isn't going to give you a location.
