### ISSUE TITLE
[Question] How can I send location most aggressively?

### ISSUE THREAD

**Issue by ohjeyong** [transistorsoft/react-native-background-geolocation#680]
## Your Environment
* Plugin version: 3.0.0-rc.5
* React Native version (`react-native -v`): 0.59.4

In my app, when user press start button, then location tracking should start. When user press stop button, then location tracking should stop. I don't need any location data except that tracking time. Tracking time will be at most 10 minutes, so the battery draining is not that problem.

During that time, I need to send location very aggressively.

I tried this config when ready.(Call 'ready' when user open app.)

```
{
    reset: true,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 0,
    disableElasticity: false,
    elasticityMultiplier: 1,
    stopAfterElapsedMinutes: 0,
    stopOnStationary: false,
    desiredOdometerAccuracy: 100,
    useSignificantChangesOnly: false,
    stationaryRadius: 1,
    locationAuthorizationRequest: 'WhenInUse',
    locationAuthorizationAlert: {
        titleWhenOff: 'Please turn on service.',
        titleWhenNotEnabled: 'Please turn on service',
        instructions:
            'Please turn on service',
        cancelButton: 'Cancel',
        settingsButton: 'Settings'
    },
    disableLocationAuthorizationAlert: false,
    locationUpdateInterval: 1000,
    fastestLocationUpdateInterval: 3000,
    deferTime: 0,
    allowIdenticalLocations: true,
    stopTimeout: 10,
    stopDetectionDelay: 0,
    disableStopDetection: true,
    pausesLocationUpdatesAutomatically: false,
    activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
    disableMotionActivityUpdates: false,
    stopOnTerminate: true,
    startOnBoot: false,
    heartbeatInterval: 60,
    schedule: undefined,
    preventSuspend: false,
    foregroundService: true,
    enableHeadless: false,
    notificationPriority:
        BackgroundGeolocation.NOTIFICATION_PRIORITY_DEFAULT,
    notificationTitle: 'My APP NAME',
    notificationText: 'MY APP NAME',
    notificationColor: undefined,
    notificationLargeIcon: 'mipmap/ic_launcher_foreground',
    notificationSmallIcon: 'mipmap/ic_launcher_foreground',
    forceReloadOnBoot: false,
    forceReloadOnGeofence: false,
    forceReloadOnHeartbeat: false,
    forceReloadOnLocationChange: false,
    forceReloadOnMotionChange: false,
    forceReloadOnSchedule: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
}
```

When user press start button I call,
```
BackgroundGeolocation.setConfig({
  url: MY_SERVER_URL,
  autoSync: true
})
```

When user press stop button I call,
```
BackgroundGeolocation.setConfig({
  url: undefined,
  autoSync: false
})
```

I think this config should work because I turn off every motion detection settings and set distanceFilter to 0 and set locationUpdateInterval to 1000.
But server only receive one or two location data as soon as user press start button, and then that is not frequently.

I know this feature is against this plugin's Philosophy of Operation. But can you recommand me the most aggressive config?
Thanks.

**Comment by christocracy** [comment]
```
distanceFilter: 0, 
locationUpdateInterval; 0, fastestLocationUpdateInterval: 0,
disableElasticity
```

Use changePace(true) to force plugin into tracking state in callback to #start.

**Comment by ohjeyong** [comment]
@christocracy 
Thank you for a quick response. I tried to call changePace(true), then server receive 7 ~ 10 location data as soon as user press start button and then nothing is sent when user doesn't move. What I understand is that even I force the plugin to set changePace true, if user doesn't move, plugin will automatically set pace as false even though the motion detection configuration is set to false. Is it right?

**Comment by christocracy** [comment]
Not until stopTimeout timer expires.

**Comment by christocracy** [comment]
What is the purpose of your app?

**Comment by ohjeyong** [comment]
Tracking electric scooter user's travel path. Electric scooter has maximum speed about 25km/h and based on user data, the average speed during tracking time is about 12km/h, average usage time is about 5min, which means, average travel distance is about 1Km.
In this purpose, I think sending location frequently is more important than saving battery consumption so I ask this question, but I'm not sure is it a good approach. Can you recommand me the configuration?

**Comment by christocracy** [comment]
The Config I recommended will work.

**Comment by ohjeyong** [comment]
Thank you @christocracy
