### ISSUE TITLE
Notification customisation not working as expected on Android Release build

### ISSUE THREAD

**Issue by BrantApps** [transistorsoft/react-native-background-geolocation#688]
When I create an Android release build of our React Native app the notification _branding_ and text is lost. Within debug the expected notification title and icon is shown.

## Your Environment
* Plugin version: 3.0.0-rc.4
* Platform: Android
* OS version: Android 9
* Device manufacturer / model: Pixel 3 (affects all 8+ Android req'ing foreground)
* React Native version: 0.58.6
* Plugin config: Excerpt below from the offending area...
```javascript
function startGeofenceMonitoring() {
  BackgroundGeolocation.ready({
    reset: true,
    enableHeadless: true,
    stopOnTerminate: false,
    startOnBoot: true,
    notificationTitle: "Looking for nearby gardens",
    notificationText: "I'll let you know if I find one",
    notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_LOW,
    notificationSmallIcon: "drawable/notification_icon",
  }).then(_ => {
    BackgroundGeolocation.startGeofences()
  })
```

## Expected Behavior
* The notification icon and text are displayed as expected in release builds of the Android app.
![notification-woking](https://user-images.githubusercontent.com/1109992/56204699-f1f3be80-603f-11e9-8da5-99084e7cb733.png)

## Actual Behaviour
* The notification icon and text fallback to the default within Android release mode.
![notification-not-working](https://user-images.githubusercontent.com/1109992/56204838-472fd000-6040-11e9-8dee-c5d42267c4e5.png)

## Steps to Reproduce
1. Create a foreground service notification using the plugin
2. Configure the plugin to have a notification title & label
3. Create a release version of your Android React Native application 
4. On first launch the foreground service checking my geofences is launched as expected but without aforementioned text and iconography.

## Context
Inform our users why the location services are "[being] activated" as the default text displays.

## Debug logs
```
--------- beginning of crash
--------- beginning of system
--------- beginning of main
04-16 11:59:03.728 10032 10175 I TSLocationManager: - Enable: true → true, trackingMode: 0
04-16 12:02:19.053 10442 10596 I TSLocationManager: - Enable: true → true, trackingMode: 0
```
Over this log period, the notification popped up and disappeared as expected. Although it did not respect the notification priority.

## Other notes
I'm using proguard with the configuration...
```
# React Native Background Geolocation
-keepnames class com.facebook.react.ReactActivity
-dontwarn ch.qos.logback.**
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
```

**Comment by mikehardy** [comment]
As a fellow 3.x user, I have notification custom text and notification working with 3.x so this it is possible, and makes me think this is likely a configuration issue of some sort though I won't begin to guess what - the details can be tricky. I'd triple-check everything though and compare with sample app (make sure it works there) first thing

**Comment by BrantApps** [comment]
Hi @mikehardy - thank you for the response. I too have custom notification text and icons in another part of the application working in release mode. It appears to be an artifact of being in release mode. Very strange. Going to try and turn a few things off to see if I can hunt it down.

**Comment by christocracy** [comment]
I'm having a look at this now...

**Comment by BrantApps** [comment]
Things I've tried. 
1) Upgraded to 3.0.1 - "plain" notification continued to show
2) turned off proguard - *success*!

will double check my proguard config....

**Comment by christocracy** [comment]
I enable Proguard in my SampleApp (`def enableProguardInReleaseBuilds = true`).  

I added a *Smily Face* icon.  I see no issue.
```javascript
BackgroundGeolocation.ready({
      reset: true,
      debug: true,
      notificationLargeIcon: 'mipmap/bg_geo',
      notificationSmallIcon: 'mipmap/bg_geo',
      notificationTitle: 'Transistor Software',
      notificationText: 'This is a test',
     .
});
```
![](https://dl.dropbox.com/s/rpny06b2544s39q/Screenshot%202019-04-16%2010.02.58.png?dl=1)
![](https://dl.dropbox.com/s/y63r49s4l6zghxi/Screenshot%202019-04-16%2010.03.25.png?dl=1)

**Comment by christocracy** [comment]
You've added the plugin's [Proguard Config](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-RNPM.md#proguard-config)

With `3.0.1`, I automated the `react-native link` script to now add the required `maven url`.  I could automate adding the proguard config as well (getting rid of it on `react-native unlink` would be difficult).

**Comment by mikehardy** [comment]
Interesting - I'm following this closely because I have a notification issue I'm sure is on my end (config, or device-specific) where it looks great in the status bar but goes black and white / no detail only as you pull it down on my OnePlus 5 w/Android 9.

But mostly commenting to say that proguard itself is about to have a revolution as the new Android build pipeline of D8 / R8 becomes default and supplants proguard. Which is to say, noting the version of your android/gradle toolchain and possibly testing for variance there might be a big deal. I'm a bit bleeding edge so I'm going to take my own advice in this case

R8 becomes available in Android studio 3.3.x https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html

R8 becomes default in 3.4 (currently RC3 status so this is just about to happen and many, like me, are trying it because I needed the emulator canary anyway because reasons) https://developer.android.com/studio/preview/features#R8-enabled

**Comment by christocracy** [comment]
> where it looks great in the status bar but goes black and white / no detail only as you pull it down on my OnePlus 5 w/Android 9.

You mean like this?
![](https://dl.dropbox.com/s/8uhi6yo1eno78qv/Screenshot%202019-04-16%2010.21.32.png?dl=1)
![](https://dl.dropbox.com/s/x4vjssavzwv4jby/Screenshot%202019-04-16%2010.21.57.png?dl=1)

**Comment by mikehardy** [comment]
yes or at least similar (hard to say 100% as it's during motion / pull-down) - looks great full-color just-as-intended when parked up there, and on pull down black and white circle (it is a circle shape to start with) like your pic. 🤷‍♂️ not the highest item on my list so not attacking it this moment but listening carefully...

**Comment by christocracy** [comment]
In my last case, I created an icon which wasn't purely transparent with the `[Shape][v]`

**Bad (Shape: "Circle")**
![](https://dl.dropbox.com/s/p9sv4ejgvyhgwkj/Screenshot%202019-04-16%2010.38.16.png?dl=1)

**Good (Shape: "None")**
![](https://dl.dropbox.com/s/5fkyuw10l41w1yq/Screenshot%202019-04-16%2010.38.52.png?dl=0)

**Comment by mikehardy** [comment]
Probably not a help for @BrantApps (sorry) but probably my issue there. Thanks

**Comment by BrantApps** [comment]
Just got back to this today. I compared the latest proguard notes to that which I had set-up and indeed they had evolved. Will report back if updating my proguard configuration has resolved this strange issue!

**Comment by BrantApps** [comment]
Ok, so part of the proguard I was missing must have been the one. Apologies for the false alarm and thank you for the support.

**Comment by christocracy** [comment]
[Notification](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.notification.html) system refactored in 3.0.4.  Fully custom layouts are now possible.
