### ISSUE TITLE
Align Android / iOS JSON post

### ISSUE THREAD

**Issue by jeroenbourgois** [transistorsoft/react-native-background-geolocation#69]
Hi

I noticed that the Android and iOS HTTP posts are different. A particular difference is the `is_charging` property of the battery. 

iOS treats it as an integer and Android as a boolean. Could you align both libraries? I have golang app that is handling the responses and it is difficult to have different data types for each platform, for the same property.

**Comment by christocracy** [comment]
Thanks.  Fix coming soon.

**Comment by christocracy** [comment]
Fixed in #master
