### ISSUE TITLE
plugin buildfire?  

### ISSUE THREAD

**Issue by fas3r** [transistorsoft/react-native-background-geolocation#690]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

Hello, 

Do you plan to sell/distribute  this plugin on buildfire ?

Thanks

**Comment by christocracy** [comment]
What's "buildfire"?

**Comment by fas3r** [comment]
App builder, https://buildfire.com/, as a plugin there too it could be easy to integrate in apps . 

Looking at your answer I dont think so 😂

**Comment by christocracy** [comment]
Nope.  Not interested in buildfire.
