### ISSUE TITLE
Geofencing on Android seems more unreliable than on iOS

### ISSUE THREAD

**Issue by Wouterjansen12** [transistorsoft/react-native-background-geolocation#691]
## Your Environment
* Plugin version:
`2.14.2`
* Platform:
`Android`
* OS version: 
`7.1.2`
* Device manufacturer / model:
`Wiko View V01.28.OPE.20-[Nougat-7.1]-V12BNLITE`
* React Native version (`react-native -v`):
```
react-native-cli: 2.0.1 
react-native: 0.51.0
```

* Plugin config:
```
const config = {
	autoSync: true,
	batchSync: false,
	debug: __DEV__,
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
	distanceFilter: 0,
	enableHeadless: false,
	forceReloadOnHeartbeat: true,
	heartbeatInterval: 3600,
	locationUpdateInterval: 60000,
	logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
	method: 'POST',
	notificationChannelName: 'Location Tracker',
	params: BackgroundGeolocation.transistorTrackerParams(DeviceInfo),
	reset: true,
	startOnBoot: true,
	stopOnTerminate: false,
	stopTimeout: 0,
	url: '', // Left out for privacy reasons.
};
```

## Expected Behavior
We expect the geofence functionality of the Android version of the plugin to work just as good as the iOS version.

## Actual Behavior
In the Android version of our app the geofence functionality of the plugin does not work well compared to the iOS version.

## Steps to Reproduce
This should already be clear by the explanation in the context section.

## Context
We did a field test with the geofence functionality of the plugin and had some good results with iOS and bad results with Android.
Below is an explanation of how the tests were conducted.
There are three important locations:
- Location A = At home
- Location B = Utrecht University
- Location C = At work

This was the time schedule of that day:
- 00:00 - 09:45 at location A
- 09:45 - 10:00 traveling
- 10:00 - 11:30 at Location B
- 11:30 - 13:00 traveling
- 13:00 - 18:00 at Location C

During the day we did a few checks if the plugin had correctly detected that a certain geofence was entered.

Checks Android:
- Location A at 09:30 did **not** go
- Location B at 11:15 did **not** go
- Location C at 14:15 did **not** go

Checks iOS:
- Location A at 09:30 **did** go
- Location B at 11:15 **did** go
- Location C at 14:15 **did** go

## Debug logs
[android-background-geolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/3091424/android-background-geolocation.log)

The iOS logs are spammed by `HTTP ERROR: 301` errors so searching for useful logs takes some time...
[ios-background-geolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/3091425/ios-background-geolocation.log)

Unfortunately the native logs for iOS and Android are not available because the tests were done with a production build by a customer of ours.

**Comment by christocracy** [comment]
>We expect the geofence functionality of the Android version of the plugin to work just as good as the iOS version.

Not possible.  Android geofencing is greatly affected by the device model, particularly the manufacturer's flavour of Android.

I've never heard of this device `Wiko View V01.28.OPE.20-[Nougat-7.1]-V12BNLITE`

See https://dontkillmyapp.com/

**Comment by christocracy** [comment]
What geofence radius are you using?  The minimum reliable radius is 150 meters.

**Comment by Wouterjansen12** [comment]
> What geofence radius are you using? The minimum reliable radius is 150 meters.

We use 1000 meters as geofence radius:
```
const geofence = {
  identifier: location.id,
  radius: 1000, // Meters
  latitude: coords.latitude,
  longitude: coords.longitude,
  notifyOnEntry: true,
  notifyOnExit: true,
};

BackgroundGeolocation.addGeofence(geofence);
```

**Comment by christocracy** [comment]
>The iOS logs are spammed by HTTP ERROR: 301 

The plugin's HTTP service allow HTTP 301 redirect.  HTTP 301 redirect turns a `POST` request into a `GET`, stripping the post-data from the request.  If you're using server redirect, use a `307`.

Try increasing the `geofenceProximityRadius`.   Set it to `5000`.

**Comment by christocracy** [comment]
Btw, you should update to latest [`3.0.x`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md)
