### ISSUE TITLE
Question / trip segments

### ISSUE THREAD

**Issue by rickgonzalez** [transistorsoft/react-native-background-geolocation#696]
My primary interest is to gather driving trip segments.  Interim data points between the start and end of the trip are not that interesting for my use case.  I would like to be able to do the determination of these points on the client.  I understand that I can use extras and my own location template and thought that might help, but the real issue might be that I don't have control over which locations are being gathered  and stored in Sqlite when my application is in the background/closed. I'm slightly paranoid after hearing that Lyft owed something like 300M to AWS (wishful problem to have). Is there any way to selectively throttle locations prior to storage or on the post?  Also if I'm totally thinking about this wrong, chime in.

**Comment by christocracy** [comment]
see #maxRecordsToPersist.

If you don’t want to persist *any* locations, set it to 0.
