### ISSUE TITLE
sync send mutliple http request instead of one

### ISSUE THREAD

**Issue by katalityk00** [transistorsoft/react-native-background-geolocation#697]
I am facing an issue while I try to use autoSync, the amount of locations send didn't match with the autoSyncThreshold property and seems to randomly sync the locations instead of sending them every 25 locations 

## Your Environment
* Plugin version: 3.0.2
* Platform:  Android
* OS version: 8.1.0
* Device manufacturer / model: Xiaomi Redmi 6A
* React Native version (`react-native -v`):  0.50.3
* Plugin config

      httpTimeout:30000,
      batchSync: true,       
      autoSync: true,         
      autoSyncThreshold: 25
      maxBatchSize:60000, 
      maxRecordsToPersist:-1, 
      maxDaysToPersist:-1,
      headers: {              
        "Content-Type": "application/json"
      },
      method:'POST',
      httpRootProperty:"location", 
      locationTemplate:'{ "lat":<%= latitude %>, "long":<%= longitude %>, "createdAt":"<%= timestamp %>" }'

## Expected Behavior

do a sync every 25 ( or more if the server don't return a success status ) locations stored in sqlite.

## Actual Behavior

the autosync send locations every 4 or 5 locations max and sometimes it send when no locations are stored.

## Steps to Reproduce

1.
2.
3.
4.

## Context

I need to send the locations stored every 25 locations if the server respond correctly and more if not

**Comment by christocracy** [comment]
The plugin ignores autoSyncThreshold on motionchange events.

**Comment by christocracy** [comment]
Btw, this is unnecessary (the plugin automatically appends this header:

headers: {              
  "Content-Type": "application/json"
},

**Comment by katalityk00** [comment]
Ok. Thanks.
So to do that I need to get the number of locations stored and sync manually.
By using the static function `BackgroundGeolocation.getCount();`

Because I didn't find how to disable on motionchange events on the doc

**Comment by christocracy** [comment]
>Because I didn't find how to disable on motionchange events on the doc

You *can't* "disable motionchange events".  This is a fundamental concept to the plugin's [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation).

The plugin ignores autoSyncThreshold on `motionchange` events, since:
1.  these events are *infrequent*.  They are the events where a device *started moving* or *stopped moving*.
2.  Since the device may have been idle for a long period of time when it *starts moving* and a motionchange event occurs, the plugin assumes you'll want to know the device started moving *as soon as possible*.  And for the opposite case, where a device becomes stationary, firing the motionchange event, the device is possibly going to site idle for an extended period of time, so the plugin again ignores autoSyncThreshold, since you may not hear from that device for a long period of time thus the plugin uploads all the remaining records in the queue.

**Comment by mikehardy** [comment]
Interesting - I didn't know that was how it worked but I have seen this behavior and this explains it. I like the style (I do like to see the queue of points on the server before or after idle) but it might be surprising as I don't think it is in the docs?

The API reference for the listener does not mention it will clear the location queue:
https://transistorsoft.github.io/react-native-background-geolocation-android/classes/_react_native_background_geolocation_android_.backgroundgeolocation.html#onmotionchange 


No mention in the philosophy:
https://github.com/transistorsoft/react-native-background-geolocation-android/wiki/Philosophy-of-Operation#two-states--moving--stationary

Or (maybe the best place) - in the config reference for autoSyncThreshold:
https://transistorsoft.github.io/react-native-background-geolocation-android/interfaces/_react_native_background_geolocation_android_.config.html#autosyncthreshold

Possibly worth mentioning (as it confused me until I'd tested it) - that the documentation for autoSync mentions in bold that it will send as soon as a location is recorded, without mention that autoSyncThreshold will actually alter that:
https://transistorsoft.github.io/react-native-background-geolocation-android/interfaces/_react_native_background_geolocation_android_.config.html#autosync

All together I'd understand most clearly if autoSyncThreshold mentioned it would clear queue onMotionChanged (without mentioning it elsewhere), and I'd alter the autoSync docs to mention that *unless you have autoSyncThreshold set* it will behave as currently described

Separately, tiny typo in the onPowerSaveChange listener example code -> "oPowerSaveChange" as a search and you'll see it https://transistorsoft.github.io/react-native-background-geolocation-android/classes/_react_native_background_geolocation_android_.backgroundgeolocation.html#onpowersavechange

**Comment by christocracy** [comment]
@mikehardy Could you please post this as a separate issue titled "[Docs] autoSyncThreshold behaviour"?

**Comment by mikehardy** [comment]
sure thing
