### ISSUE TITLE
[Docs] autoSyncThreshold behavior

### ISSUE THREAD

**Issue by mikehardy** [transistorsoft/react-native-background-geolocation#698]
As noted in discussion on #697 the documentation for autoSyncThreshold does not exactly match behavior. Behavior seems fine (to me) but the docs could be more clear.

Specifically:

The API reference for the listener does not mention it will clear the location queue:
https://transistorsoft.github.io/react-native-background-geolocation-android/classes/_react_native_background_geolocation_android_.backgroundgeolocation.html#onmotionchange 

No mention in the philosophy:
https://github.com/transistorsoft/react-native-background-geolocation-android/wiki/Philosophy-of-Operation#two-states--moving--stationary

Or (maybe the best place) - in the config reference for autoSyncThreshold:
https://transistorsoft.github.io/react-native-background-geolocation-android/interfaces/_react_native_background_geolocation_android_.config.html#autosyncthreshold

Possibly worth mentioning (as it confused me until I'd tested it) - that the documentation for autoSync mentions in bold that it will send as soon as a location is recorded, without mention that autoSyncThreshold will actually alter that:
https://transistorsoft.github.io/react-native-background-geolocation-android/interfaces/_react_native_background_geolocation_android_.config.html#autosync

**All together I'd understand most clearly if autoSyncThreshold mentioned it would clear queue onMotionChanged (without mentioning it elsewhere), and I'd alter the autoSync docs to mention that *unless you have autoSyncThreshold set* it will behave as currently described**

Separately, tiny typo in the onPowerSaveChange listener example code -> "oPowerSaveChange" as a search and you'll see it https://transistorsoft.github.io/react-native-background-geolocation-android/classes/_react_native_background_geolocation_android_.backgroundgeolocation.html#onpowersavechange

**Comment by christocracy** [comment]
I've placed a **Warning** in all the places you've mentioned.  Will be uploaded with next commit to master, where I release the new [Android Custom Notification Layout](https://github.com/transistorsoft/react-native-background-geolocation-android/wiki/Android-Custom-Notification-Layout)

![](https://dl.dropbox.com/s/zlj2o9bllnbgqg2/Screenshot%202019-05-02%2010.04.07.png?dl=1)

**Comment by Udbhav12** [comment]
@christocracy  - Can you please elaborate the difference between `autoSyncThreshold` and`maxBatchSize` ?

**Comment by christocracy** [comment]
`autoSyncThreshold`:  "How many locations does the plugin have to queue up in its internal SQLite database before the SDK even *considers* performing a "sync" action (ie: HTTP requests).
`maxBatchSize`:  Once a "sync" action *does* start happening, how many records to place into each HTTP request.
