### ISSUE TITLE
Can't compile RCTDownloadTaskWrapper.m

### ISSUE THREAD

**Issue by Javanaise** [transistorsoft/react-native-background-geolocation#7]
get this error: RCTDownloadTaskWrapper.m:65:49: Null passed to a callee that requires a non-null argument

**Comment by Javanaise** [comment]
sorry that's a react native issue of course https://github.com/facebook/react-native/issues/1955

**Comment by christocracy** [comment]
I've been away from React the past month or so.

I'll have a look.

**Comment by Javanaise** [comment]
Seems it's that's because of the react native version you use.
https://github.com/facebook/react-native/issues/3024
Is it possible to fix that ?
Thanks

**Comment by christocracy** [comment]
Why don't you first fork and tweak the version and let me know?

On Saturday, October 3, 2015, Javanaise <notifications@github.com> wrote:

> Seems it's that's because of the react native version you use.
> facebook/react-native#3024
> <https://github.com/facebook/react-native/issues/3024>
> Is it possible to fix that ?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/7#issuecomment-145232358>
> .
>


-- 
Snet form Gmail Mobile

**Comment by Javanaise** [comment]
@christocracy well I'm a total beginner on react native...

**Comment by Javanaise** [comment]
I'll give it a try ;)

**Comment by Javanaise** [comment]
npm ERR! peerinvalid The package react-native@0.11.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-background-geolocation@0.0.7 wants react-native@>=0.8.0
npm ERR! peerinvalid Peer react-native-mapbox-gl@0.4.0 wants react-native@>=0.4.3 <0.9.0
npm ERR! peerinvalid Peer react-native-vector-icons@0.6.11 wants react-native@>=0.4.0 || 0.5.0-rc1 || 0.6.0-rc || 0.7.0-rc || 0.7.0-rc.2 || 0.8.0-rc || 0.8.0-rc.2 || 0.9.0-rc || 0.10.0-rc || 0.11.0-rc

**Comment by Javanaise** [comment]
I gave it a try, there's quite a few changes to upgrade. still couldn't get it running...

**Comment by Javanaise** [comment]
I think there's an issue in having a directory called iOS, AppDelegate.m needs a few updates, you need to disable the bitcode in the build settings, Mapbox.bundle name had its name changed.

I ended up with this:
![screen shot 2015-10-03 at 14 33 23](https://cloud.githubusercontent.com/assets/14178589/10262904/c078beea-69db-11e5-9e55-d4957c2689bb.png)

**Comment by Javanaise** [comment]
Probably should go back to the react native beginners tutorials ;)

**Comment by christocracy** [comment]
Come back Monday.  I have to push an updated version for ios9.

On Saturday, October 3, 2015, Javanaise <notifications@github.com> wrote:

> Probably should go back to the react native beginners tutorials ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/7#issuecomment-145245388>
> .
>


-- 
Snet form Gmail Mobile
