### ISSUE TITLE
Background tasks

### ISSUE THREAD

**Issue by jeroenbourgois** [transistorsoft/react-native-background-geolocation#70]
Hi

I have a question regarding the background mode. Is it possible to track geolocations even when the app is killed? My client would like this and apparently Foursquare does that... I thought it was not possible and very intrusive. But it is possible :) Can the plugin do this too?

**Comment by christocracy** [comment]
Yes.  [stopOnTerminate: false](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/api.md#param-boolean-stoponterminate)
