### ISSUE TITLE
Geofence events aren't working when the android app is in background/killed state

### ISSUE THREAD

**Issue by cfmitrah** [transistorsoft/react-native-background-geolocation#703]
I am testing with android debug build. I have added local notification using this pacakge react-native-push-notification inside geofence events. the notification triggers when the app is active but when the app is in background state or killed by user the notification doesn't pop up however i could still hear the debug sounds correctly .

## Your Environment
* Plugin version:  3.0.2
* Platform:  Android
* OS version: 9.0
* Device manufacturer / model: Nokia 6.1 Plus
* React Native version (`react-native -v`): 0.55.4 
* Plugin config
    ```    BackgroundGeolocation.ready(
            {
                // Geolocation Config
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 1, // Need to be changed to 10
                // Activity Recognition
                stopTimeout: 1,
                enableHeadless: true,
                foregroundService: true,
                // Application config
                debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
                startOnBoot: true, // <-- Auto start tracking when device is powered-up.
                autoSync: true
            },
            state => {
                console.log('- BackgroundGeolocation is configured and ready: ', state.enabled);
                if (state.enabled) {
                    // //
                    // 3. Start tracking!
                    //
                    // BackgroundGeolocation.startGeofences();
                    BackgroundGeolocation.start(function() {
                        console.log('- Start success');
                    });
                }
            }
        );```
## Expected Behavior
the notification should pop up when the user enters/exits a geofence even if the app is in background or killed state.

## Actual Behavior
the notification pops up only when the app is active

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
test if the package works in background

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs, 
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat
-->
Should i include headless task for my use case. and please suggest some effective ways other than notification to test the events when the app is not active.

**Comment by cfmitrah** [comment]
I added headless task it is working now. Please tell me other ways to test

**Comment by christocracy** [comment]
I use a Fake GPS app (eg: Lockito).  However, firing geofences from mocked locations doesn't always work.  Sometimes it works, sometimes not.

**Comment by cfmitrah** [comment]
@christocracy do headless tasks work in iOS? if not how can i achieve background tasks in iOS?

**Comment by christocracy** [comment]
iOS has no concept of "Headless".  If an event occurs while the app is terminated (eg: geofence), iOS launches your entire app in the background, just as if it were launched from the home-screen icon.  Your javascript app will always be launched to receive the event.

You do not need to think any differently about your app's behaviour in the terminated state, as you do with Android.

**Comment by cfmitrah** [comment]
Thank You!

**Comment by nitishpccs89** [comment]
In android Geofences not firing when app is closed. How I can implement Geofences while app is in terminated. I also implement headless for android but it is not working. Please help me out
