### ISSUE TITLE
my application stops after a short time, after the update to android oreo

### ISSUE THREAD

**Issue by listenyourheart** [transistorsoft/react-native-background-geolocation#705]
## Your Environment
* Plugin version:
* Platform:  Android 8
* OS version:
* Device manufacturer / model: Huawei mate 10 lite
* React Native version (`react-native -v`): 0.49.5
* Plugin config
{
    "activityRecognitionInterval": 8000,
    "allowIdenticalLocations": false,
    "autoSync": false,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "debug": false,
    "deferTime": 0,
    "desiredAccuracy": 10,
    "desiredOdometerAccuracy": 100,
    "disableElasticity": false,
    "disableStopDetection": false,
    "distanceFilter": 5,
    "elasticityMultiplier": 1,
    "enableHeadless": true,
    "extras": {},
    "fastestLocationUpdateInterval": 1000,
    "forceReloadOnBoot": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnSchedule": false,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": true,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {},
    "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",
    "heartbeatInterval": -1,
    "httpRootProperty": "location",
    "httpTimeout": 60000,
    "isMoving": false,
    "locationTemplate": "",
    "locationTimeout": 60,
    "locationUpdateInterval": 1000,
    "locationsOrderDirection": "ASC",
    "logLevel": 5,
    "logMaxDays": 1,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": 0,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 50,
    "notificationColor": "",
    "notificationLargeIcon": "",
    "notificationPriority": 0,
    "notificationSmallIcon": "",
    "notificationText": "Location Service activated",
    "notificationTitle": "",
    "params": {},
    "persist": true,
    "schedule": [],
    "startOnBoot": true,
    "stationaryRadius": 25,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": false,
    "stopTimeout": 5,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "",
    "enabled": true,
    "schedulerEnabled": false,
    "trackingMode": 1,
    "odometer": 1203219.75,
    "isFirstBoot": false
}

thank you !

**Comment by listenyourheart** [comment]
hello , my app worked well in headless mode on android 7, when I updated my smartphone to version 8, the application stops by itself after few minutes , it no longer appears as foreground service.

**Comment by christocracy** [comment]
This is *the point* of `3.0.0`:  to only activate the foreground-service when the device is moving.  When the device is *stationary*, there is no foreground-service active.

This is not a bug, it's a *feature*.

**Comment by listenyourheart** [comment]
ok thanks,
does version 3.0.0 of the plugin work with android 7?

**Comment by christocracy** [comment]
>does version 3.0.0 of the plugin work with android 7?

Why wouldn't it?  I test from `4.4.4` up to latest (`9.0.0`)

**Comment by listenyourheart** [comment]
ok thank you !

**Comment by listenyourheart** [comment]
I have upgrade my plugin version to 3.0.4 , and now I have this error when application is terminated (enableHeadless:true ) : 

5-14 15:23:03.153 INFO [BackgroundGeolocation e] 
  🎾  Start monitoring location-provider changes
05-14 15:23:03.164 DEBUG [BackgroundGeolocation isMainActivityActive] NO
05-14 15:23:03.177 DEBUG [BackgroundGeolocation isMainActivityActive] NO
05-14 15:23:03.186 ERROR [a a] HeadlessTask failed to find com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService.java.  If you've configured enableHeadless: true, you must provide a custom BackgroundGeolocationHeadlessTask.java.  See Wiki: https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode
05-14 15:23:03.194 ERROR [a a] 
  ‼️  com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService
05-14 15:23:03.207 WARN [a a] 
  ⚠️  Attempted to post headless event providerchange but there are no listeners.
05-14 15:23:03.241 DEBUG [TSGeofenceManager c] ℹ️  Persist monitored geofences: []
05-14 15:23:03.254 INFO [b a] 
  🔵  LocationAuthorization: Requesting permission
05-14 15:23:03.282 INFO [HeartbeatService a] 
  🔴  Stop heartbeat
05-14 15:23:03.292 INFO [ActivityRecognitionService a] 
  🎾  Start motion-activity updates
05-14 15:23:03.305 INFO [TSGeofenceManager start] 
  🎾  Start monitoring geofences
05-14 15:23:03.316 DEBUG [HttpService startMonitoringConnectivityChanges] 
  🎾  Start monitoring connectivity changes
05-14 15:23:03.328 DEBUG [a c] 
  🎾  Start monitoring powersave changes
05-14 15:23:03.340 DEBUG [BackgroundGeolocation isMainActivityActive] NO

**Comment by christocracy** [comment]
Show me the entire file where you've called `BackgroundGeolocation.registerHeadlessTask`

**Comment by listenyourheart** [comment]
import {AppRegistry, AppState} from 'react-native';
import App from './src/App';
import BackgroundGeolocation from "react-native-background-geolocation";
import NotificationService from "./src/services/NotificationService";
import * as GPSState from "react-native-gps-state";

AppRegistry.registerComponent('eaP', () => App);

NotificationService.configure();


////
// Define your Headless task -- simply a javascript async function to receive
// events from BackgroundGeolocation:
//
var gpsErrorNotified = false;
let HeadlessTask = async (event) => {
    let params = event.params;

    switch (event.name) {
       
        case 'activitychange':
            NotificationService.showNotification("new event :"+ params.activity);
            if (params.activity !== "still"){
                GPSState.getStatus().then((status) => {
                    if ((status == 0 || status == 1 || status == 2) && !gpsErrorNotified) {
                        gpsErrorNotified = true;
                        NotificationService.showNotification("merci d'activer la localisation ", {});
                    }
                });
            }
            BackgroundGeolocation.getCurrentPosition();
            break;
        default:
            GPSState.getStatus().then((status) => {
                if ((status == 0 || status == 1 || status == 2) && !gpsErrorNotified) {
                    gpsErrorNotified = true;
                    NotificationService.showNotification("merci d'activer la localisation ", {});
                }
            });
            break;
    }
}


////
// Register your HeadlessTask with BackgroundGeolocation plugin.
//
BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

**Comment by christocracy** [comment]
You neglected the **Plugin Version** in issue-template!

**Comment by christocracy** [comment]
Show me `$ adb logcat -s TSLocationManager` of your app booting.

**Comment by christocracy** [comment]
And show me the config you're providing to `#ready`

**Comment by listenyourheart** [comment]
plugin version 3.0.4

**Comment by listenyourheart** [comment]
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.0.15 (315)
╠═════════════════════════════════════════════
{
  "activityRecognitionInterval": 3000,
  "allowIdenticalLocations": false,
  "autoSync": false,
  "autoSyncThreshold": 0,
  "batchSync": false,
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableElasticity": false,
  "disableStopDetection": false,
  "distanceFilter": 5,
  "elasticityMultiplier": 1,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": 1000,
  "forceReloadOnBoot": false,
  "forceReloadOnGeofence": false,
  "forceReloadOnHeartbeat": false,
  "forceReloadOnLocationChange": false,
  "forceReloadOnMotionChange": false,
  "forceReloadOnSchedule": false,
  "foregroundService": false,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": false,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {},
  "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": false,
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 4,
  "logMaxDays": 4,
  "maxBatchSize": -1,
  "maxDaysToPersist": 1,
  "maxRecordsToPersist": 0,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 50,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 0,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 1203109.25,
  "isFirstBoot": false
}

**Comment by christocracy** [comment]
the problem is this `"headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",`

Show me your `#ready`

**Comment by listenyourheart** [comment]
BackgroundGeolocation.ready({
            // Geolocation ConfiglinkedTickets
            reset: true,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 5,
            // Activity Recognition
            activityRecognitionInterval: 6000,
            minimumActivityRecognitionConfidence: 50,
            stopTimeout: 10,
            foregroundService: true,
            // Application config
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            logMaxDays:1,
            enableHeadless: true,
            fastestLocationUpdateInterval: 1000,
            stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
            // HTTP / SQLite config
            autoSync: false,        // <-- [Default: true] Set true to sync each location to server as it arrives.
            url: null,        // <-- [Default: true] Set true to sync each location to server as it arrives.
            maxRecordsToPersist: 0
        }, (state) => {

            if (!state.enabled) {
                ////
                // 3. Start tracking!
                //
                BackgroundGeolocation.start(function () {
                });
            }
        });

    }

**Comment by listenyourheart** [comment]
android/build.gradle:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.0.0"
        removeBackgroundGeolocationDebugSoundsInRelase = true
    }
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}

**Comment by christocracy** [comment]
I asked for *two* files

**Comment by listenyourheart** [comment]
android/app/build.gradle
apply plugin: "com.android.application"
/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
        entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true

android {

    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.ilesoft.eap"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionName "3.0.2"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }

}

dependencies {
    implementation project(':react-native-maps')
    implementation project(':react-native-push-notification')
    compile project(':react-native-background-geolocation')
    compile project(':react-native-background-fetch')
    compile project(':react-native-location-switch')
    compile project(':react-native-gps-state')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

**Comment by christocracy** [comment]
- Open your app in Android Studio:  *Build->Clean project*.

Show me `$ adb logcat -s TSLocationManager` of your app booting once again.

**Comment by listenyourheart** [comment]
ok thank you I don't see anymore this error :

**Comment by christocracy** [comment]
There was some old plugin-code still lying around somewhere in your build.  The `headlessJobService` class-name changed a few months ago.

It should look like this:
```
TSLocationManager: ╔═════════════════════════════════════════════
TSLocationManager: ║ TSLocationManager version: 3.0.16 (316)
TSLocationManager: ╠═════════════════════════════════════════════
TSLocationManager: {
.
.
.
TSLocationManager:   "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
```

**Not** like this:
```
"headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService",
```

**Comment by listenyourheart** [comment]
TSLocationManager version: 3.0.16 (316) ?

no I still have TSLocationManager version: 3.0.15 (315)

I have tried .gradlew clean , delete node modules  ,clean/rebuild project from android studio , delete android/build/*

**Comment by christocracy** [comment]
3.0.15 (315) is fine.  3.0.16(316) is my local build.
