### ISSUE TITLE
Questions before buying the license.

### ISSUE THREAD

**Issue by cfmitrah** [transistorsoft/react-native-background-geolocation#706]
1. Is the license applicable for both android and iOS?
2. There are four licences Starter, Venture, Pro, Studio . what are the differences between them? Geofence is an important feature in my app. so which will be better for me?

**Comment by christocracy** [comment]
>Is the license applicable for both android and iOS?

iOS is free.  Only Android consumes license keys.

>There are four licences Starter, Venture, Pro, Studio . what are the differences between them? 

How many apps are you making?  If Uber were to make 2 apps, 1 for *drivers* and another for *passengers*:
1.  `com.uber.driver`
2.  `com.uber.passenger`

Uber would require **2 keys** so they would purchase *Venture*, leaving 3 extra keys for future apps.
