### ISSUE TITLE
Get Battery lvl

### ISSUE THREAD

**Issue by Devmaticz** [transistorsoft/react-native-background-geolocation#707]
my question is realy a noob one, but i'll ask for it

i want in a view show a text with the current battery level, and this onLocation event.

can you help me achieve this.

Best

**Comment by christocracy** [comment]
See docs:
- [`onLocation`](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#onlocation)
- The type of Object returned is [`Location`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.location.html)

```typescript
BackgroundGeolocation.onLocation((location) {
  console.log('[onLocation] ', location, location.battery);
});
```

**Comment by Devmaticz** [comment]
thank you for you prompt response !!! i'll go with a license.

hope you'll patient whith my questions :-)
