### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_TSBackgroundFetch", referenced from:  objc-class-ref in TSLocationManager(TSLocationManager.o)

### ISSUE THREAD

**Issue by ZakeryFyke** [transistorsoft/react-native-background-geolocation#708]
-----------------------------------------------------------------------------
**[UPDATE]**: See solution [here](https://github.com/transistorsoft/react-native-background-geolocation/issues/708#issuecomment-488765667) re: `use_frameworks!`

-----------------------------------------------------------------------------

## Your Environment
* Platform: iOS
* OS version:12.2
* Device manufacturer / model: iPhone X
* React Native version (`react-native -v`): 0.58.5
* Plugin config

## Expected Behavior

Project should compile

## Actual Behavior

On build, error thrown: 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TSBackgroundFetch", referenced from:
      objc-class-ref in TSLocationManager(TSLocationManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Steps to Reproduce

1. Follow Pod Install instructions (including react-native link cocoa-lumberjack)
2. Attempt to build
3. Suffer

## Context

Build the project.

**Comment by christocracy** [comment]
And what about [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-RNPM.md)?

**Comment by ZakeryFyke** [comment]
I have linked react-native-background-fetch, as well.

Building RNBackgroundFetch individually succeeds, building RNBackgroundGeolocation fails with the above error.

**Comment by christocracy** [comment]
Did you:
```
$ cd ios
$ pod update
```
?

**Comment by ZakeryFyke** [comment]
Did that just now, same error:

ld: warning: Could not find auto-linked framework 'TSBackgroundFetch' (<- This was here before, I just missed it with my copy pasta, sorry!)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TSBackgroundFetch", referenced from:
      objc-class-ref in TSLocationManager(TSLocationManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by christocracy** [comment]
Show me your `Podfile`

**Comment by ZakeryFyke** [comment]
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VoximplantDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
rn_path = '../node_modules/react-native'

pod 'React', path: rn_path, subspecs: [
'Core',
'CxxBridge',
'DevSupport',
'RCTActionSheet',
'RCTAnimation',
'RCTGeolocation',
'RCTImage',
'RCTLinkingIOS',
'RCTNetwork',
'RCTSettings',
'RCTText',
'RCTVibration',
'RCTWebSocket',
]
  
  # Demo project dependencies
  pod 'react-native-voximplant', path: '../node_modules/react-native-voximplant'
  pod 'react-native-notifications', path: '../node_modules/react-native-notifications'
  pod 'RNCallKit', path: '../node_modules/react-native-callkit'
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'RNSecureStorage', :path => '../node_modules/react-native-secure-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'React'
        target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          new_xcconfig = xcconfig.sub('HEADER_SEARCH_PATHS = $(inherited)', 'HEADER_SEARCH_PATHS = $(inherited) "$(PODS_TARGET_SRCROOT)/ReactCommon/jsiexecutor"')
          File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
        end
      end
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
  
  target 'VoximplantDemoTests' do
    inherit! :search_paths
  end
  
end

```

**Comment by christocracy** [comment]
```
$ cd ios
$ rm Podfile.lock
$ pod install
```
Show me the entire output of running `pod install`

**Comment by ZakeryFyke** [comment]
```
Apples-iMac:ios appledeveloper$ rm Podfile.lock
Apples-iMac:ios appledeveloper$ pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `RNBackgroundFetch` from `../node_modules/react-native-background-fetch`
Fetching podspec for `RNBackgroundGeolocation` from `../node_modules/react-native-background-geolocation`
Fetching podspec for `RNCallKit` from `../node_modules/react-native-callkit`
Fetching podspec for `RNSecureStorage` from `../node_modules/react-native-secure-storage`
Fetching podspec for `RNVectorIcons` from `../node_modules/react-native-vector-icons`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/GLog.podspec`
Fetching podspec for `react-native-notifications` from `../node_modules/react-native-notifications`
Fetching podspec for `react-native-voximplant` from `../node_modules/react-native-voximplant`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Using CocoaLumberjack (3.4.2)
Using DoubleConversion (1.1.6)
Using Folly (2018.10.22.00)
Using RNBackgroundFetch (2.5.4)
Using RNBackgroundGeolocation (3.0.2)
Using RNCallKit (1.3.4)
Using RNSecureStorage (0.1.2)
Using RNVectorIcons (6.1.0)
Using React (0.58.5)
Using SocketRocket (0.5.1)
Using VoxImplantSDK (2.18.0)
Using VoxImplantWebRTC (66.0.3)
Using boost-for-react-native (1.63.0)
Using glog (0.3.5)
Using react-native-notifications (1.2.51)
Using react-native-voximplant (1.5.0)
Using yoga (0.58.5.React)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 24 dependencies from the Podfile and 17 total pods installed.

[!] The `VoximplantDemoTests [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-VoximplantDemoTests/Pods-VoximplantDemoTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `VoximplantDemoTests [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-VoximplantDemoTests/Pods-VoximplantDemoTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

```

**Comment by christocracy** [comment]
Boot a new "Hello World" RN app `$ react native init Foo`.

Set it up in isolation.

**Comment by christocracy** [comment]
And of course this could be causing your issues:
```
[!] The `VoximplantDemoTests [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-VoximplantDemoTests/Pods-VoximplantDemoTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `VoximplantDemoTests [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-VoximplantDemoTests/Pods-VoximplantDemoTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by christocracy** [comment]
Here's what my `SampleApp` shows for *Other Linker Flags*:
![](https://dl.dropbox.com/s/77w11gmaleg7k6i/Screenshot%202019-05-02%2012.23.00.png?dl=1)

**Comment by ZakeryFyke** [comment]
Hrm, the Foo app seemed to build with just the geolocation plugin in isolation. Let me take a look at the other linker flags, maybe something weird with that.

**Comment by ZakeryFyke** [comment]
Updating my Other Linker Flags to match yours removed the warning popping up with Pod Install when rerunning the rm Podfile.lock, pod install commands. Still the same error on trying to build, though.😓

**Comment by christocracy** [comment]
How about your *Framework Search Paths"?

![](https://dl.dropbox.com/s/5euftzm0ws6hziz/Screenshot%202019-05-02%2012.55.16.png?dl=1)

**Comment by ZakeryFyke** [comment]
<img width="1217" alt="Screen Shot 2019-05-02 at 11 59 16 AM" src="https://user-images.githubusercontent.com/17220638/57092753-bb6da300-6cd1-11e9-98c8-f4166bd5ccb0.png">

Hrm, mine seems a bit... cluttered, ha. Should it only be the $(inherited)?

**Comment by christocracy** [comment]
> Should it only be the $(inherited)?

Yes.

**Comment by ZakeryFyke** [comment]
<img width="1363" alt="Screen Shot 2019-05-02 at 12 06 06 PM" src="https://user-images.githubusercontent.com/17220638/57093145-ba894100-6cd2-11e9-9448-3d73579e495a.png">
Same result. 😓

**Comment by christocracy** [comment]
*Header Search Paths*?

![](https://dl.dropbox.com/s/g0dlnq6vdtjwq8g/Screenshot%202019-05-02%2013.27.25.png?dl=1)

**Comment by ZakeryFyke** [comment]
I'm beginning to sense a pattern here...😅

I've checked the header paths and matched them to yours, still the same result. :cry:

**Comment by christocracy** [comment]
- Do an *XCode -> Product -> Clean*
- Restart XCode.

**Comment by ZakeryFyke** [comment]
Same thing 😞

**Comment by christocracy** [comment]
Does `RNBackgroundFetch` appear in */Development Pods* as shown below?
![](https://dl.dropbox.com/s/w972h2c0pq1cqhi/Screenshot%202019-05-02%2013.41.20.png?dl=1)

**Comment by christocracy** [comment]
Oh, wait:  I see the problem in your `Podfile`:
```
target 'VoximplantDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!     #<---------- YOU CANNOT USE THIS.  It must be commented out.
```

**Comment by ZakeryFyke** [comment]
Oh, of course. 😅
Removing that seems to have removed the error! I'm getting a different run time complaint about CocoaLumberjack, "Library not loaded, reason image not found", but that might be unrelated so I'll go dig around for it.

**Comment by christocracy** [comment]
Actually, let's try a trick I learned from my [flutter version](https://github.com/transistorsoft/flutter_background_geolocation/issues/5).

Manually edit the `react-native-background-geolocation`  .podspec:
`node_modules/react-native-background-geolocation/RNBackgroundGeolocation.podspec`
```diff
.
.
.
Pod::Spec.new do |s|
  .
  .
  .
+s.static_framework = true
end
```

```
$ cd ios
$ pod install
```

**Comment by christocracy** [comment]
After setting this back to what it was:
```
target 'VoximplantDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!   #<-------- uncomment once again
```

**Comment by ZakeryFyke** [comment]
That also seems to have worked 😁Both ways build on my device. 🎉

**Comment by christocracy** [comment]
Ok, I'm going to add `s.static_framework = true` to the plugin's `.podspec` in next release.

**Comment by christocracy** [comment]
But still, you should only `use_frameworks!` if some 3rd-party module *specifically* requested it.

**Comment by mikehardy** [comment]
I just saw this come across in react-native-firebase, as it has known problems with use_frameworks (owing to the firebase libraries themselves) but FirebaseUI specifically needs it. It appears switching to the legacy build system might make your build work, even though that's not a great workaround it might be worth trying? https://github.com/invertase/react-native-firebase/issues/252#issuecomment-488877222

**Comment by christocracy** [comment]
Adding `s.static_framework = true` to background-geolocation.podspec should allow it to work with `use_frameworks!`

**Comment by christocracy** [comment]
What `use_frameworks!` does is shrink-wraps each Pod into Cocoa.framework.  Unfortunately, the plugin’s TSLocationManager.framework relies upon being able to reference TSBackgroundFetch.framework.  But once RNBackGroundFetch gets shrink-wrapped, it no longer exposes its TSBackgroundFetch to the outside world.

s.static_framework = true seems to fix all that.

**Comment by zyonnetworks** [comment]
I still get error even with latest versions....  XCode 10.3, Node 10.15.3

`ld: warning: Could not find auto-linked framework 'TSBackgroundFetch'`
`Undefined symbol: _OBJC_CLASS_$_TSBackgroundFetch`

Here is my POD file...
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'LocationApp' do
  use_frameworks!
  use_native_modules!
  
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'AWSCognito'
  pod 'AWSS3'
  pod 'AFNetworking'
  pod 'GoogleMaps'

  target 'FluteTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

Package.json uses `"react-native-background-geolocation": "3.2.2",` which uses `s.static_framework = true`
