### ISSUE TITLE
Request Example Comment Change for  // <-- [Default: true] Set true to sync each location to server as it arrives.

### ISSUE THREAD

**Issue by rickgonzalez** [transistorsoft/react-native-background-geolocation#709]
Recommend example comment change from

 // <-- [Default: true] Set true to sync each location to server as it arrives.

to

autoSync: true,  // <-- [Default: true] Set true to sync each location or batch of locations to server as it arrives.

It's very clear in the docs that this needs to be set to true in order to trigger batch posts.  However the comment in the example makes it seem that it is solely meant for use in combination with batchSync: false

I didn't figure it out until I wasn't seeing batch posts.

**Comment by christocracy** [comment]
Docs link please.

**Comment by rickgonzalez** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/README.md

**Comment by rickgonzalez** [comment]
#large_blue_diamond-example
