### ISSUE TITLE
How to update config after refresh token.

### ISSUE THREAD

**Issue by panda919** [transistorsoft/react-native-background-geolocation#710]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.55.4
* Plugin config

## Context

I used JWT troken auth.
When token is expired, i get new auth token and update BackgroundGeolocation 's config and call sync() function.
 BackgroundGeolocation.setConfig({
                 headers: ------,//new auth token header
                  reset: true,
    });
 this.sync();
But, I got 401 error yet.
What's wrong?

**Comment by mikehardy** [comment]
I'm also interested in this - @panda919 am I correct in saying that in the general sense the question is: If you already launched your app and have this plugin running, what is the best way to dynamically alter it's config?

My case is that I want extra user information available in the "extras" but I only have it available in certain situations and definitely only after app launch. If I'm able to get that info I'd like to alter the info included in extras and have that change take affect

I suppose I/we could do a stop/config/ready-with-reset ? (carefully checking state even)

**Comment by panda919** [comment]
Actually, I didn't find solution for update config dynamically !!!
While running, even if i update config via setConfig(), token in header is not updated!!!

**Comment by mikehardy** [comment]
did you try stop/config-with-reset/ready ? basically re-cycling the plugin ? I haven't tried it yet but this was going to be my test

**Comment by panda919** [comment]
I didn't not stop.
Only reset and call sync().

**Comment by panda919** [comment]
BackgroundGeolocation.setConfig({
                  headers: headers,
                  reset: true,
                });
                this.sync();

**Comment by christocracy** [comment]
Yes, #setConfig.  No need to #stop.  Listen to #onHttp for 401 as your cue to change your token.

Be sure to do that in your HeadlessTask, as well.

**Comment by panda919** [comment]
BackgroundGeolocation.onHttp(httpEvent => {
        //console.warn('[http] ', httpEvent.success, httpEvent.status);

        let statusCode = parseInt (parseInt(httpEvent.status) / 100 );
        if(statusCode == 4){

           ======================
                    // get new auth token
           =====================
                let headers = {
                  Accept: "application/json",
                  "Content-Type": "application/json",
                  Authorization: "Bearer " +--new token---
                };
                BackgroundGeolocation.setConfig({
                  headers: headers,
                  reset: true,
                });
                BackgroundGeolocation.sync();
      });
this is my source.
But , token is not updated, and i got 401 error yet.

**Comment by christocracy** [comment]
(It's *triple-backtick* for syntax-highlighting.)

**Comment by christocracy** [comment]
(triple-backtick, with optional language)

![](https://dl.dropbox.com/s/32zrqb5dlkmypna/Screenshot%202019-05-05%2010.47.03.png?dl=1)
```typescript . 
let foo = "bar"
```

**Comment by panda919** [comment]
thanks. but pls check above my code snipet. what is wrong?
I didn't get expected result for refresh token.

**Comment by christocracy** [comment]
```typescript
BackgroundGeolocation.setConfig({
  headers: headers,
  //reset: true,  // <-- reset doesn't apply to setConfig.  remove.
}).then((state) => {
  BackgroundGeolocation.sync(); 
});
```
The plugin's methods are asynchronous.  You can't execute #sync until #setConfig completes.

**Comment by panda919** [comment]
ah, got it.
I will try

**Comment by christocracy** [comment]
This should also work:

```typescript
BackgroundGeolocation.onHttp(httpEvent => async {
  await BackgroundGeolocation.setConfig({headers: headers});
  BackgroundGeolocation.sync();
});
```

**Comment by mikehardy** [comment]
awesome this will help me too, and I likely would have also forgotten async - thanks @christocracy

**Comment by panda919** [comment]
thanks very much

**Comment by christocracy** [comment]
@mikehardy you can't change `#extras` of a location already persisted to plugin's SQLite db.  Updated `#extras` will be applied to the *next* recorded location.

**Comment by mikehardy** [comment]
Yes - until you code up react-native-time-travel I'll have (from my perspective) incomplete data in the past but that's fine - with uids you only need one visible strobe to link thinks up and that's my use case, so works for me just fine

**Comment by 1602** [comment]
@christocracy when http sync happens in the background (without app running, swiped up to shut down), will `onHttp` hook still be triggered? I'm asking because I observe app sending outdated tokens over and over again.

As recommended in example from README I'm calling `removeListeners()` when component unmounts, perhaps it removes `onHttp` causing http to fail silently without token renewal logic to trigger.

What is recommended approach here?

**Comment by christocracy** [comment]
> swiped up to shut down), will onHttp hook still be triggered?

On Android, of course *not*.  That's what [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode) is for.

**Comment by panda919** [comment]
@christocracy 
I have 2 question.
- if i have to update config, I have to set {reset: true,} in first config object(meaning init config, not update config value.)
-if i set schedule config, it is not necessary   to call start() function, I may call only startSchedule() function?

**Comment by christocracy** [comment]
>if i have to update config, I have to set {reset: true,} in first config object(meaning init config, not update config value.)

In `3.0.4`, `reset: true` now defaults to false.  You can forget about this now.  `#ready` now *always* applies the supplied config.

`#setConfig` is *unaware* of `reset`.  `#reset` is not a strict config option of the plugin API itself.  It's implemented in the [React Native Android code.](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/RNBackgroundGeolocationModule.java#L334-L341)

-if i set schedule config, it is not necessary to call start() function, I may call only startSchedule() function?

Correct.  The Scheduler is a bot that automatically calls `#start` / `#stop` for you.  Like a cron-task.

-if i call sync() function, schedule action will continue ?

Yes, of course.  The HTTP Service is an independent entity that operates upon the SQLite database, selecting records, executing HTTP requests and deleting records when your server says `200`.

**Comment by panda919** [comment]
meaning, stopSchedule function call stop() function automatically implicty?
and startSchedule() call start() function automatically?
Because i got below guide.
http://prntscr.com/nmtq85

**Comment by christocracy** [comment]
>`stopSchedule` function call `stop()` function automatically implicty?  

Why don't you experiment?  No, it only stops the schedule bot.

>and `startSchedule()` call `start()` function automatically?

`#startSchedule` starts the bot.

**Comment by panda919** [comment]
I am meaning. 
```typescript
BackgroundGeolocation.start(() => {    
      BackgroundGeolocation.startSchedule();      
 });   
 BackgroundGeolocation.stopSchedule(() => {      
      BackgroundGeolocation.stop();     
 }); 
````
this code is correct?

**Comment by christocracy** [comment]
If you have a schedule configured, why would you explicitly call `#start`?  The schedule-bot will do that automatically according to your configured `schedule`.

As for the `stopSchedule` case, that's completely up to you.  If the user were logging out, I'd certainly tell the plugin to `#stop` in that case.
