### ISSUE TITLE
Motion and Fitness option is enabled by default in iOS.

### ISSUE THREAD

**Issue by cfmitrah** [transistorsoft/react-native-background-geolocation#711]
After linking this package, our app has `Motion and Fitness` option enabled in settings.
I don't need this for some privacy concerns. will the geofence work if it is disabled? can i make it disabled by default?
## Your Environment
* Plugin version: 3.0.2
* Platform: iOS
* OS version: 12.0
* Device manufacturer / model: iPhone 6 Plus
* React Native version (`react-native -v`): 0.55.4
* Plugin config

## Expected Behavior
Motion and Fitness should not be enabled and the geofence should work.

## Actual Behavior
Motion and Fitness option is enabled.

**Comment by christocracy** [comment]
See docs disableMotionActivityUpdates.
