### ISSUE TITLE
Library not loaded: CocoaLumberjack. Reason: image not found

### ISSUE THREAD

**Issue by ZakeryFyke** [transistorsoft/react-native-background-geolocation#712]
## Your Environment
* Platform: iOS
* OS version:12.2
* Device manufacturer / model: iPhone X
* React Native version (`react-native -v`): 0.58.5

## Expected Behavior

Project should run on simulator

## Actual Behavior

Project builds completely, but throws the error in the title upon attempting to run. 

## Steps to Reproduce

1. Follow Pod install instructions 
2. Clean
3. Build
4. Run on simulator. 

## Context

Run ze project.

## Debug logs

```
dyld: Library not loaded: @rpath/CocoaLumberjack.framework/CocoaLumberjack
  Referenced from: /Users/appledeveloper/Library/Developer/CoreSimulator/Devices/8A3C/data/Containers/Bundle/Application/E7C3/VoximplantDemo.app/Frameworks/VoxImplant.framework/VoxImplant
  Reason: image not found
```

**Comment by ZakeryFyke** [comment]
This is actually an issue with [VoxImplant](https://github.com/voximplant/react-native-voximplant) after removing use_frameworks from my podfile. I'll go bug them about it, they supposedly support it without use_frameworks now.

**Comment by christocracy** [comment]
Thank god...
