### ISSUE TITLE
Set stopTimeout value less than 5 minutes

### ISSUE THREAD

**Issue by Base29** [transistorsoft/react-native-background-geolocation#714]
## Your Environment
* Plugin version: 3.0.2
* Platform: iOS
* OS version: 12.2
* Device manufacturer / model: Apple/ iPad 6th Generation
* React Native version (`react-native -v`): 0.57.0
* Plugin config
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 10,
                activityRecognitionInterval: 1000,
                stopTimeout: 1,
                debug: true,
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                stopOnTerminate: false,
                startOnBoot: true, 
                stationaryRadius: 5

## Expected Behavior
I want the location-services to stop immediately as soon as the device is still.

## Actual Behavior
As per in the docs and the field tests that I have conducted the location-services stop after 5 minutes of the device being detected as still.

## Steps to Reproduce
it is the default behaviour of the plugin. so it can be easily reproduced.

## Context
We are trying to get the location coordinates of the device as soon as it is detected as still.

**Comment by christocracy** [comment]
See docs for `#ready` method.  Pay particular attention to the note about reset: true.

**Comment by Base29** [comment]
@christocracy ... `reset: true` worked ... but it seems to have no effect on `stationaryRadius` property ... it still defaults to 25 meters

**Comment by christocracy** [comment]
Plugin enforced min 25.

**Comment by Base29** [comment]
@christocracy ... so there is no way to override this ? also need to turn of the local notifications and don't wan't the plugin to ask permissions for those ... is this possible ? ... 
Also you have done a awesome work developing this plugin ... I really enjoyed working with it.

**Comment by christocracy** [comment]
Min stationaryRadius is 25.  You can make it 26 and higher.

debug: false.

Read the docs.
