### ISSUE TITLE
Can't get started

### ISSUE THREAD

**Issue by kiddkevin00** [transistorsoft/react-native-background-geolocation#716]
Hi, I've ejected my app from expo and I follow your setup guide and I retry many times but I keep getting the following two errors:

- React/RCTEventEmitter.h file not found
![Screen Shot 2019-05-08 at 8 13 05 AM](https://user-images.githubusercontent.com/7229339/57374809-c1e49a80-7169-11e9-915f-b8bf1d65aecf.png)

- Build input file cannot be found: '/Users/hsum/Desktop/.../ios/node_modules/react-native-background-fetch/ios/RNBackgroundFetch/RNBackgroundFetch+AppDelegate.m'
![Screen Shot 2019-05-08 at 8 13 05 AM](https://user-images.githubusercontent.com/7229339/57374640-54d10500-7169-11e9-8a1a-d2b9986cebc3.png)

I've been struggling for hours. Can you please help?

**Comment by kiddkevin00** [comment]
I created a new one following your template. Closing this issue for now.

**Comment by christocracy** [comment]
Why would you create a new issue instead of editing *this one*??
