### ISSUE TITLE
 Exit and enter of a geofence doesn't work

### ISSUE THREAD

**Issue by JPabloObando** [transistorsoft/react-native-background-geolocation#719]
When I entered a geofence or left the geofence I do not receive any event that I left or i entry--

## Your Environment
* Plugin version: 3.0.2
* Platform: iOS
* OS version: MacOs Mojave
* Device manufacturer / model: iPhone 6s
* React Native version: 0.58.6
* Plugin config: 
    BackgroundGeolocation.ready(
      {
        distanceFilter: 10,
        stopOnTerminate: false,
        startOnBoot: true,
        foregroundService: true,
        heartbeatInterval: 60,
        autoSync: true,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      },
      state => {
        BackgroundGeolocation.startGeofences()
      },
    )

## Expected Behavior
- If I enter the geofence walking or in a car I need to receive an event of enter
- If I leave the geofence walking or in a car  I need to receive an event of exit

## Actual Behavior
1- If i am inside of the geofence the method onGeofence send me the event action of ENTER and DWLL. 
2- When i am outside of the geofence the method Geofence doesn't send me anything, it never executes.
3- If i am inside of the geofence when i go outside of the geofence, i don't get an event action of EXIT
4- If i am outside of the geofence when i go inside of the geofence, i don't  get an event action of ENTER

## Steps to Reproduce
1.
    BackgroundGeolocation.onLocation(
      this.onLocation.bind(this),
      this.onLocationError.bind(this),
    )
    BackgroundGeolocation.onGeofence(this.onGeofence.bind(this))
    BackgroundGeolocation.ready(
      {
        distanceFilter: 10,
        stopOnTerminate: false,
        startOnBoot: true,
        foregroundService: true,
        heartbeatInterval: 60,
        autoSync: true,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      },
      state => {
        BackgroundGeolocation.startGeofences()
      },
    )

2- BackgroundGeolocation.addGeofence({
      geofenceInitialTriggerEntry: true,
      identifier: 'DANGER_ZONE',
      radius: 400,
      latitude: 9.931589760810795,
      longitude: -84.05873537063599,
      notifyOnEntry: true,
      notifyOnExit: true,
      notifyOnDwell: true,
      startOnBoot: true,
    })

3.

  onLocation(location) {
    console.log('[location] - ', location)
  }

  onLocationError(errorCode) {
    console.log('[location] ERROR - ', errorCode)
  }

  onGeofence(GeofenceEvent) {
    Alert.alert('Alert Title', `${GeofenceEvent.action}`)
    console.log('GeofenceEvent ', GeofenceEvent)
    const value = GeofenceEvent.action
    if (value === 'ENTER') {
      this.setState({insideRegion: true})
      return
    }

    if (value === 'EXIT') {
      this.setState({insideRegion: false, successGeofence: false})
      return
    }
  }

3- 
## Context
When a user enters; geofence can do things and when it goes outside no longer

**Comment by christocracy** [comment]
Please learn how to apply syntax-highlighting with triple-backticks.

the link to learn how to [use markdown](https://guides.github.com/features/mastering-markdown/) is right there at the bottom-right of the text-area i'm typing in right now.
![](https://dl.dropbox.com/s/0sfro3612w6afx4/Screenshot%202019-05-08%2018.05.33.png?dl=1)

**Comment by bilalsiddiqui786** [comment]
@JPabloObando

I was also facing same problem. I added `url` key with a valid url in configuartion and set some `heartbeatInterval` and it started working. It might help you.

**Comment by egunsoma** [comment]
@bilalsiddiqui786 Under valid you mean you fired up a working test server? Or just URL anything valid like www.google.com? Thanks!
