### ISSUE TITLE
Is this app track offline and push when connection will be ok?

### ISSUE THREAD

**Issue by stw-services** [transistorsoft/react-native-background-geolocation#720]
Hi,

I want to know these features:
1. If I will start background-geolocation tracking and close app, will it track in closing app mode. 
2. If there is not internet will background-geolocation upload tracked data when connect again ok.

**Comment by christocracy** [comment]
1. Yes.  With `stopOnTerminate: false`

2.  Yes

**Comment by stw-services** [comment]
is there any setting I need to add for specify offline and online or it will auto check.

**Comment by christocracy** [comment]
The plugin subscribes to http connection changes.
