### ISSUE TITLE
Permission request pops up before BackgroundGeolocation is instantiated

### ISSUE THREAD

**Issue by mernit** [transistorsoft/react-native-background-geolocation#723]
## Your Environment
* Plugin version: 2.13.3
* Platform: iOS 
* Device manufacturer / model: Apple iPhone 7+
* React Native version: 0.55.3

```
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        locationUpdateInterval: 1000,
        reset: true,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
        stopOnStationary: false,   // <-- Allow the background-service to stop tracking when user stops moving
        startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
        allowIdenticalLocations: true,
        url: postUrl,
        batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
        headers: {},
```

## Expected Behavior

The user should not be prompted with a location permission request before `BackgroundGeolocation.start` is instantiated. 

The initial run of the app includes an onboarding screen where the user can manually elect to "Allow Background Location." This opens the iOS system dialogue which asks the user to enable background location permission.

After the user has enabled all required permissions in our app (background geolocation and motion), the app will start and the background location service will be instantiated.

Our app will only instantiate `BackgroundGeolocation.start` _after_ the user has enabled background geolocation and motion permissions.

## Actual Behavior

The Permission Request dialogue pops up immediately when the app is opened. This prevents us from controlling when the dialogue is displayed, and it means that we can't "gently" display the popup during our onboarding flow.

This is occurring _before_ the background geolocation service is instantiated in our React-Native code. 

## Steps to Reproduce

This is only reproducible when running the app on a physical device. 

## Context

Control when the Permission Dialogue is served to the user. Apple only allows us one chance to display the Permission Dialogue, and this is preventing us from controlling when the dialogue is served to new users.

## Debug logs
N/A

**Comment by christocracy** [comment]
It doesn't.  You're probably executing `#getCurrentPosition` somewhere.

**Comment by christocracy** [comment]
Or you're using some map-component which will also request location-authorization.
