### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by mahesha12345** [transistorsoft/react-native-background-geolocation#724]

**Comment by christocracy** [comment]
The issue template is **not** optional -- it's **required**.
![](https://dl.dropbox.com/s/ewp0pipmy6vbuh6/Screenshot%202019-05-17%2010.05.29.png?dl=1)

Edit your issue and provide the required information.

**Comment by christocracy** [comment]
Go [here](https://github.com/transistorsoft/react-native-background-geolocation/issues/new), copy the issue-template into your post and fill out the required information.
