### ISSUE TITLE
Provider change event object incorrectly included in the location object

### ISSUE THREAD

**Issue by jpodpro** [transistorsoft/react-native-background-geolocation#729]
* Plugin version: 3.0.0-rc.4
* Platform: Android
* OS version: 28
* Device manufacturer / model: Samsung S6 device, Nexus and Pixel Emulators
* React Native version: 0.57.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 10,
stopTimeout: 1,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
stopOnTerminate: false, // Allow the background-service to continue tracking when user closes the app.
startOnBoot: false, // Auto start tracking when device is powered-up.
// HTTP / SQLite config
url: Config.MAPPING_SERVER + "/api/point",
httpRootProperty: ".",
locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"timestamp":"<%= timestamp %>"}',
batchSync: false,
autoSync: true,
headers: {
    "Content-Type": "application/json"
}
```

## Expected Behavior
When server URL reachability changes, stored location object format should not change from the configured template and extras.

## Actual Behavior
When the server URL becomes unreachable a provider change event object ```provider: {enabled, gps, network, status}``` is inserted into one of the unsynchronized location objects.

## Steps to Reproduce
1. Begin tracking locations with auto sync to server. 
2. Shut down the tracking server and wait for the onHttp error.
3. Terminate the app
4. Restart the app and use getLocations to view the inserted provider object in one of the stored locations.

In addition, i tried to fix this using getLocations, destroyLocations and insertLocation. However insertLocation does not work as expected as it does not allow the custom template formatting for the input Location object and does not transform the inserted location to the format specified by the location template.

**Comment by christocracy** [comment]
This is correct.  The Android plugin automatically inserts a location when the device's location provider changes, inserting a `provider` object into the location.

**Comment by jpodpro** [comment]
this is not correct as it is NOT part of the location template provided in the configuration.

**Comment by christocracy** [comment]
Modify your server accordingly to accept or ignore the provider information.

**Comment by christocracy** [comment]
Because I’d have to offer a dedicated `locationProviderTemplate` just for that single case (not going to happen) where a server can easily choose to ignore that extra added `provider` {}.
