### ISSUE TITLE
Android - Location notification randomly popping up when app is terminated

### ISSUE THREAD

**Issue by rstims** [transistorsoft/react-native-background-geolocation#732]
Location notification randomly popping up when app is terminated, background tasks are completely removed and headless is disabled.

## Your Environment
* Plugin version: 3.0.2
* Platform: Android
* OS version: Android 9
* Device manufacturer / model: Pixel 2
* React Native version (`react-native -v`): 0.59.8
* Plugin config
```javascript 
    useSignificantChangesOnly: true,
    disableLocationAuthorizationAlert: true,
    debug: true,
    locationAuthorizationRequest: 'Any',
    logLevel: 1,
    heartbeatInterval: 60,
    pausesLocationUpdatesAutomatically: false,
    httpRootProperty: '.',
    disableMotionActivityUpdates: true,
    headers: {
      Authorization: `Bearer xxx`,
    },
    locationTemplate:
      '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"accuracy":<%= accuracy %>,"timestamp":"<%= timestamp %>"}',
    logMaxDays: 1,
    maxDaysToPersist: 1,
    maxRecordsToPersist: 100,
    stopOnTerminate: false,
    foregroundService: true,
    stopOnStationary: true,
    stopTimeout: 2.5 * 60,
    enableHeadless: false,
    forceReloadOnBoot: true,
    notificationLargeIcon: 'mipmap/ic_notif',
    notificationSmallIcon: 'mipmap/logos_mark_accent',
   ...(all others are default)
```

## Expected Behavior
When app is terminated notification should never show

## Actual Behavior
When app is terminated, notification randomly shows

**Comment by christocracy** [comment]
It's not *random*, it's occurring with each `heartbeatInterval: 60`, since you told it to `stopOnTerminate: false`.

**Comment by rstims** [comment]
@christocracy doesn't that only work on android when headless task is enabled?

**Comment by christocracy** [comment]
No.  Watch your logs and see:  `$ adb logcat -s TSLocationManager`

**Comment by rstims** [comment]
@christocracy so in order to get the results Im looking for I would need to change the `stopOnTerminate` to `true`?

**Comment by christocracy** [comment]
If you don't want the plugin to track the location when user (or OS) terminates your app, then use `stopOnTerminate: true`.

**Comment by banduk** [comment]
@christocracy On android I'm seeing the same behaviour. 
I'm using `useSignificantChangesOnly: true` and expecting the notification never to show. But I noticed that it shows when the app uploads the location to the server. Is there a way not to show this?

**Comment by christocracy** [comment]
The plugin purposely launches a foreground service to ensure the os does not suspend the process before the http request is complete.  The foreground service is terminated once the http request completes.

**Comment by banduk** [comment]
I understand, would you consider an option to avoid this? In this case the problem would be that sometimes the OS would kill the process before the upload completes, right? From your tests it would be a rare case? 
It's just a matter of UX. I'd prefer not to bother the user with "random" notifications (i got they're not random, but for the user they are).

**Comment by mikehardy** [comment]
@banduk @christocracy I followed this from #734 - I think the remaining question is best addressed here as this is focused on the notification icon.

I had the same question as I just converted to significant changes only, in the hopes of not having location-related notification icons show up ever.

Having just read this I think I understand it now, and I think it might be possible to either greatly reduce or eliminate the location icon showing up outside the app at least by altering the config. You could set it to queue locations semi-indefinitely as the baseline config, then during app startup you could manually use the API to send locations. This style may not meet anyone else's business requirements but seems like the only way to do it.

If Chris made it so that he uses a foreground service when pushing http data out I'm guessing its because of observed app kills so the ability to toggle it off seems dangerous?

**Comment by christocracy** [comment]
The popular Life360 app, which I keep running to compare behaviour, has the same behaviour.

**Comment by mikehardy** [comment]
I'm working on pinning this down, but right now if I start my app with hardware location enabled, grant permissions in the app, config the plugin and start it, then turn hardware location off (no change to permission, app in background), I get a persistent notification after a while out and about. Have you ever seen this, or tested this scenario? I know you need logs to be definitive, I'll get them but thought you might have seen or might be able to easily toggle one of your stable of devices to significant changes mode then while in background turn off location

**Comment by mikehardy** [comment]
if I turn on location it persists for a moment then goes away.

**Comment by christocracy** [comment]
If state.enabled, that’ll be the providerchange event firing, which records a location.  This is a crucial location to the plugin, when location-services has just been enabled.
