### ISSUE TITLE
'AppDelegate.h' file not found & TSBackgroundFetch.h file not found 

### ISSUE THREAD

**Issue by akashdeepsharma1991** [transistorsoft/react-native-background-geolocation#736]
## Your Environment mac
* Plugin version: 2.14
* Platform: iOS or Android: IOS
* OS version: 12
* Device manufacturer / model: iphone X
* React Native version (`react-native -v`): 0.59
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Should not throw error in xcode or while running the using react native cli

## Actual Behavior

Getting error 'AppDelegate.h' file not found & TSBackgroundFetch.h file not found 
## Steps to Reproduce

1. follow the step for manual instruction 
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Did you carefully follow the react-Native link instructions?

**Comment by akashdeepsharma1991** [comment]
thnx u for the quick response. Yes i followed every step carefully that you have mention for installation

**Comment by christocracy** [comment]
And you followed that part that asked you to `react-native link react-native-background-fetch`?

**Comment by akashdeepsharma1991** [comment]
yes i ran that command and after that i get this error
![Screenshot 2019-06-18 at 5 37 16 PM](https://user-images.githubusercontent.com/33919907/59680788-d8adf080-91ef-11e9-8970-4fe80db614e7.png)
![Screenshot 2019-06-18 at 5 37 40 PM](https://user-images.githubusercontent.com/33919907/59680797-df3c6800-91ef-11e9-8358-8e84ca23b880.png)

**Comment by christocracy** [comment]
First try installing the plugin into a new "Hello World" RN app.

**Comment by christocracy** [comment]
and don't specify **Plugin version: latest**.  It's meaningless.  Edit your issue and enter the *exact* version you're using.

**Comment by akashdeepsharma1991** [comment]
does the plugin have any issue with other plugin becuz my app is almst done. so the plugin should work anytime when i added it. please help i am stuck in this from past 2 days.

**Comment by christocracy** [comment]
>does the plugin have any issue with other plugin

No.

First install into new *Hello World* app.

**Comment by akashdeepsharma1991** [comment]
Hi tried by making the new proj still getting error. I am trying to make build using xcode. Running the app using xcode play button

**Comment by christocracy** [comment]
I've have just generated a fresh new hello world app and it runs fine.
```
$ react-native init Foo
```
- package.json
```
{
  "name": "Foo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-background-geolocation": "^3.0.7"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

```
$ yarn add react-native-background-geolocation
$ react-native link react-native-background-geolocation
$ react-native link react-native-background-fetch
$ react-native link cocoa-lumberjack
```
- Open `Foo/ios/Foo.xcodeproj`
- Run in iOS sim.
- Success.

**Comment by christocracy** [comment]
- XCode version:  `10.2.1`

**Comment by akashdeepsharma1991** [comment]
this what error i am getting when i try to run app using xcode
![Screenshot 2019-06-18 at 7 27 03 PM](https://user-images.githubusercontent.com/33919907/59690482-22520780-91ff-11e9-9ac1-8050fe8074ba.png)

**Comment by akashdeepsharma1991** [comment]
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.0-rc.1",
    "react-native-background-geolocation": "^3.0.7"
  },
  "devDependencies": {
    "@babel/core": "7.4.5",
    "@babel/runtime": "7.4.5",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.8.0",
    "eslint": "5.16.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by christocracy** [comment]
`React/RCTEventEmitter.h` means your app isn't finding `React`.  Your app is configured wrong.  I see you're using Pods.  Did you run `$ pod install` after installing the plugin, [as directed by the install instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-COCOAPODS.md#react-native-link)?

**Comment by akashdeepsharma1991** [comment]
so i should the same in old project ... but i am not getting this error... would it be helpful.. i had follow the instruction given on git hub

**Comment by christocracy** [comment]
If you're using Cocoapods, follow the Cocoa pod install instructions.

**Comment by akashdeepsharma1991** [comment]
Hii just checked not using the coco pods. but i am still getting the error of Appdelegate and tsbackground

**Comment by akashdeepsharma1991** [comment]
hii i followed the manual steps again still getting the same error. any way that i can delete the reference and do all again for this plugin

**Comment by christocracy** [comment]
Get it working in hello world app first.

**Comment by akashdeepsharma1991** [comment]
its working in hello world via coco pod. how can i make it to work in my actual app?

**Comment by mikehardy** [comment]
For situations like this in react-native-firebase (also an apparently complicated install) I made this so people can see every.single.step. - https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by akashdeepsharma1991** [comment]
@christocracy  i tried again with the cocopods methods stiiling the TSbackgroundfetch.h error file not found

**Comment by akashdeepsharma1991** [comment]
@mikehardy  is the reference for me ... because i could really some help.. stuck on this issue for past 2 days

**Comment by mikehardy** [comment]
@akashdeepsharma1991 the reference is not for you - sorry - it was an example for Chris on how we're trying to deal with similar user project integration errors in another library. Because these errors are frustrating for everyone and take a lot of time, I finally followed the docs and made a shell script that demonstrates every step. That doesn't exist for this project, so it doesn't help you directly. I can say that if you follow the instructions very very carefully, you should get this to work. The proof of that is in your getting it to work in a fresh example. There must be something wrong with your Xcode project, and honestly if it were me I'd just throw away the whole ios project skeleton and reinitialize it piece by piece. That's the work of a half day or so, beats 2 days stuck. Good luck either way

**Comment by akashdeepsharma1991** [comment]
@mikehardy  thnx you for the quick response. I am new to react-native is there any way i can regenerate the ios skeleton fresh for same project. I will do everything from scratch ..

**Comment by mikehardy** [comment]
Yeah, I've had to do it before - I'm relatively new as well. I would start with a fresh react-native init basically, in a separate directory, just like your hello world app but with correct package names etc since the goal is it becomes your actual app.

Once you have the basic app working, carefully re-add your dependencies and link them one by one, building and checking each time that they work and instructions are all followed.

Then add your javascript (or typescript etc) code and configs back in and...it should be your app now, but working.

Since having to do that myself I have a healthy fear of Xcode project files

**Comment by akashdeepsharma1991** [comment]
One thing that i noticed i get error when i drag and drop the file RNBackgroundFetch+AppDelegate.h where appdelegate.m file is there.. its not able to get the tsbackgroundfetch.h file.... guess a reference issue is occuring

**Comment by mikehardy** [comment]
I would use react-native link every time, it handles that for you.

**Comment by akashdeepsharma1991** [comment]
i have used that well as.. Just wanna if this works with react-native-navigation plugin....

**Comment by akashdeepsharma1991** [comment]
just checked again with whole process also again with new project it seems i having issue. the drag and dropping of the file. its is not able to get the reference for appdelegate and tsbackgroundfecth header file.... any other way of doing stuff or any other plugin that can be helpful..

**Comment by christocracy** [comment]
>the drag and dropping of the file

You don't need to do that with `react-native link`.  The plugin has a custom script, initiated with `react-native link` that performs all manual setup steps automatically.

**Comment by christocracy** [comment]
And make sure you're using the latest XCode `10.2.1`

**Comment by akashdeepsharma1991** [comment]
i am using xcode version that u mention. did the react-native linking command but still getting the error
#import <TSBackgroundFetch/TSBackgroundFetch.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by amuraco** [comment]
Dropping in here, since I'm having a hard time getting this to work. I'm on React-native 0.60.4, and looking though the back and forth, it looks like @akashdeepsharma1991 has "react-native": "0.60.0-rc.1",  while @christocracy was using   "react-native": "0.59.9",

So what needs to happen for this plugin to build with >0.60.x since react-native significantly changed how it links everything for building?

**Comment by mikehardy** [comment]
I have this working on RN60 following the instructions, and while it was a pain that was largely due to other modules. I'd recommend doing a fresh init on a sample project, following the instructions and verifying it works - for me I need to *know* it's possible in the face of project-specific errors to give me the courage to continue on ;-). Following that, it's always possible to reset a module's ios integration with pod deintegrate, pod install to redo the pods stuff, and you can unlink and relink the packages as needed to reset that. (and in your quickie freshly-init-ed rn60 sample project you can verify that works as well)

**Comment by christocracy** [comment]
It works with 60.x  [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/package.json#L35).  My local copy of SampleApp is using 60.4.

**Comment by hamishwebb** [comment]
I'm running into the same error with a vanilla React Native build. I've followed these instructions - https://github.com/transistorsoft/react-native-background-geolocation/blob/HEAD/help/INSTALL-IOS-AUTO.md

Xcode: 10.3

project.json:
`{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/geolocation": "^1.4.2",
    "@react-native-community/netinfo": "^4.1.5",
    "@react-native-community/push-notification-ios": "^1.0.2",
    "art": "^0.10.3",
    "base-64": "^0.1.0",
    "base64-js": "^1.3.0",
    "d3": "^5.9.2",
    "firebase": "^6.3.4",
    "prop-types": "^15.7.2",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-background-fetch": "^2.7.0",
    "react-native-background-geolocation": "^3.2.0",
    "react-native-ble-plx": "^1.0.3",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-push-notification": "^3.1.9",
    "react-native-svg": "^9.7.1",
    "react-native-swipe-list-view": "^2.0.1",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.0.2",
    "react-redux-firebase": "^3.0.0-alpha.14",
    "redux": "^4.0.1",
    "redux-firestore": "^0.8.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "7.4.3",
    "@babel/runtime": "7.4.3",
    "babel-jest": "24.7.1",
    "jest": "24.7.1",
    "metro-react-native-babel-preset": "0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by christocracy** [comment]
- *Install Auto* instructions are for react-native >= 0.60
- react-native >= 0.60 is **all** Cocoapods.
- if you’re using >=0.60, you **are** using Cocoapods.

**Comment by hamishwebb** [comment]
Then how have I've been running RN 0.60 without any podfile just fine, and when I enter "pod install" in the ios folder, like the instructions say, I get this error:
`[!] No `Podfile' found in the project directory.`

**Comment by christocracy** [comment]
https://facebook.github.io/react-native/blog/2019/07/03/version-60#cocoapods-by-default

**Comment by christocracy** [comment]
If you're upgrading your app to `0.60` for the first time, see the [React Native Upgrade Guide](https://react-native-community.github.io/upgrade-helper/)

**Comment by hamishwebb** [comment]
Seems like adding Cocoapods will be a bit of a pain, but do you think it might be the cause of this issue?

**Comment by christocracy** [comment]
Adding cocoapods is required and makes your life 1000000 times easier.

**Comment by hamishwebb** [comment]
Looks like cocoapods fixed it for me.
Thanks!

**Comment by christocracy** [comment]
Yes, if your migrating to Cocoapods, you’ll want to destroy /Libraries
