### ISSUE TITLE
ld: framework not found TSLocationManager clang: error: linker command failed 

### ISSUE THREAD

**Issue by ryandury** [transistorsoft/react-native-background-geolocation#74]
Getting this error when trying to do a fresh install & build running RN v0.22 and Xcode 7.3. I am noticing that in my Xcode I only see 'Header Search Paths', not 'Framework Search Paths', and therefore cannot add it to "Framework Search Paths".  Guessing this could be the issue. Any idea how I can add a record for framework search paths?  

![image](https://cloud.githubusercontent.com/assets/411931/14405611/48282a60-fe47-11e5-996c-4f8ea05cc02d.png)

![image](https://cloud.githubusercontent.com/assets/411931/14405587/1e414a56-fe47-11e5-8e03-9640eda5e260.png)

Also, your installation instructions are not totally clear. At one point you mention finding a dependency in RCTMapboxGL but there is no indication that this needs to be installed. I believe it's a typo in your path indication.
![image](https://cloud.githubusercontent.com/assets/411931/14405622/91af90d8-fe47-11e5-98a7-ff6d744f3d5b.png)

Thank you.

**Comment by ryandury** [comment]
I was able to fix this by pasting a 'Framework Search Path' entry from another project. It's possible that this doesn't exist by default in Xcode 7. Might want to provide instructions on how to add it and remove the reference to mapbox :)

Thank you for building this.

**Comment by christocracy** [comment]
![](https://www.dropbox.com/s/8kn4ad00si5jao3/Screenshot%202016-04-09%2014.45.37.png?dl=1)

**Comment by ryandury** [comment]
Actually, the root of this missing entry may not exist when starting a new react project via react-native init

**Comment by NormalAndrew** [comment]
I've run into this same problem before, but was able to add what I believed was the correct framework search path.  Still had the "linker command failed" message.  @ryandury, are you saying I shouldn't start a react project via the "react-native init" call?  How should I create it?  Via Xcode?  I'm also wondering if I am just not including other dependencies in my project that I need, such as cocoapods or cordova?  Sorry, I'm a bit of a newbie, but am good at following instructions, just feel like there are steps missing that may be obvious to most people, just not me.

**Comment by christocracy** [comment]
You should definitely start your React Native project using:
```
$ react-native init Foo
```

**Comment by christocracy** [comment]
I just started a new project with 
```
$ react-native init Foo
```

I see **Framework search path** in **Build Settings**.
![](https://www.dropbox.com/s/msjiop678oghrca/Screenshot%202016-04-12%2009.32.14.png?dl=1)

**Comment by christocracy** [comment]
Update?  Can I close this?

**Comment by shulyugin** [comment]
check "All" in filters to see it
<img width="368" alt="screen shot 2016-06-18 at 17 00 29" src="https://cloud.githubusercontent.com/assets/9137705/16171380/41f4d0ba-3576-11e6-9cb6-50d174a90148.png">

**Comment by kristojorg** [comment]
I was having this issue, and solved it by making my framework search path recursive. I had previously selected to have only my root directory search path as recursive as indicated in the image in the install instructions. 

I will submit a PR once I have this fully working to update install instructions with correct image as well as the directory path mistake mentioned previously here.

Thanks so much for doing this @christocracy!

For reference, here is the step with the incorrect image. Will submit a PR later today :).


<img width="711" alt="screen shot 2016-06-22 at 1 21 40 pm" src="https://cloud.githubusercontent.com/assets/4398775/16276460/78d78600-387c-11e6-881b-78c54b89e404.png">

**Comment by christocracy** [comment]
Right.  The text documented as recursive but not screenshot

On Wednesday, June 22, 2016, kristojorg <notifications@github.com> wrote:

> I was having this issue, and solved it by making my framework search path
> recursive. I had previously selected to have only my root directory search
> path as recursive as indicated in the image in the install instructions.
>
> I will submit a PR once I have this fully working to update install
> instructions with correct image as well as the directory path mistake
> mentioned previously here.
>
> Thanks so much for doing this @christocracy
> <https://github.com/christocracy>!
>
> For reference, here is the step with the incorrect image. Will submit a PR
> later today :).
>
> [image: screen shot 2016-06-22 at 1 21 40 pm]
> <https://cloud.githubusercontent.com/assets/4398775/16276460/78d78600-387c-11e6-881b-78c54b89e404.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/74#issuecomment-227816015>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l7GX_WBMMDZlTmdzqluOZc5KIaR7ks5qOW-lgaJpZM4IDrP5>
> .
>


-- 
Snet form Gmail Mobile

**Comment by altagir** [comment]
thanks kristojorg, actually I did remove the ios part automatically included by react-native link...
works now
