### ISSUE TITLE
Execution failed for task ':react-native-background-geolocation:compileDebugJavaWithJavac'. >Compilation failed; see the compiler error output for details.

### ISSUE THREAD

**Issue by Sm038229** [transistorsoft/react-native-background-geolocation#742]
## Your Environment
* Plugin version: 3.0.7
* Platform: iOS or Android: Android
* OS version: MAC OS Mojave (10.14.5)
* Device manufacturer / model: Any
* React Native version (`react-native -v`): 0.49.9
* Plugin config

===============
build.gradle/app
===============
```gradle
apply plugin: "com.android.application"
project.ext.vectoricons = [
        iconFontNames: ['MaterialIcons.ttf'] // Name of the font files you want to copy
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

import com.android.build.OutputFile

project.ext.react = [
        bundleInDebug: true,
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "com.safehiringsolutions.safevisitor"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 20
        versionName "1.0.5"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

repositories {
    flatDir {
        dirs "../../node_modules/react-native-background-geolocation/android/libs"
    }
    flatDir {
        dirs "../../node_modules/react-native-background-fetch/android/libs"
    }
}

dependencies {
    implementation project(':react-native-material-kit')
    implementation project(':react-native-icons')
    implementation project(':react-native-background-geolocation')
    implementation project(':react-native-background-fetch')
    implementation project(':react-native-android-permissions')
    implementation project(':react-native-vector-icons')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:28.0.0"
    implementation 'com.facebook.react:react-native:+'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

================
build.gradle/android
================
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../../node_modules/react-native/android"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
        google()
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.3'
            }
        }
    }
}
```

==============
Logs in terminal
==============
```
> Task :react-native-background-fetch:compileDebugJavaWithJavac FAILED
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:7: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:9: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:13: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskConfig;
                                 ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:14: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskContext;
                                 ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:15: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskEventListener;
                                 ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:17: error: cannot find symbol
import com.facebook.react.common.LifecycleState;
                                ^
  symbol:   class LifecycleState
  location: package com.facebook.react.common
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:23: error: cannot find symbol
public class HeadlessTask implements HeadlessJsTaskEventListener {
                                     ^
  symbol: class HeadlessJsTaskEventListener
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:26: error: cannot find symbol
    private ReactNativeHost mReactNativeHost;
            ^
  symbol:   class ReactNativeHost
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:27: error: cannot find symbol
    private HeadlessJsTaskContext mActiveTaskContext;
            ^
  symbol:   class HeadlessJsTaskContext
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:63: error: cannot find symbol
    protected void startTask(final HeadlessJsTaskConfig taskConfig) {
                                   ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:89: error: cannot find symbol
    private void invokeStartTask(ReactContext reactContext, final HeadlessJsTaskConfig taskConfig) {
                                                                  ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:31: error: cannot find symbol
            ReactApplication reactApplication = ((ReactApplication) context.getApplicationContext());
            ^
  symbol:   class ReactApplication
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:31: error: cannot find symbol
            ReactApplication reactApplication = ((ReactApplication) context.getApplicationContext());
                                                  ^
  symbol:   class ReactApplication
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:37: error: cannot find symbol
        HeadlessJsTaskConfig config = new HeadlessJsTaskConfig(HEADLESS_TASK_NAME, new WritableNativeMap(), 30000);
        ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:37: error: cannot find symbol
        HeadlessJsTaskConfig config = new HeadlessJsTaskConfig(HEADLESS_TASK_NAME, new WritableNativeMap(), 30000);
                                          ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:46: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:50: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:78: error: cannot find symbol
                    reactInstanceManager.removeReactInstanceEventListener(this);
                                        ^
  symbol:   method removeReactInstanceEventListener(<anonymous ReactInstanceEventListener>)
  location: variable reactInstanceManager of type ReactInstanceManager
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:90: error: cannot find symbol
        if (reactContext.getLifecycleState() == LifecycleState.RESUMED) {
                        ^
  symbol:   method getLifecycleState()
  location: variable reactContext of type ReactContext
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:90: error: cannot find symbol
        if (reactContext.getLifecycleState() == LifecycleState.RESUMED) {
                                                ^
  symbol:   variable LifecycleState
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:93: error: cannot find symbol
        final HeadlessJsTaskContext headlessJsTaskContext = HeadlessJsTaskContext.getInstance(reactContext);
              ^
  symbol:   class HeadlessJsTaskContext
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:93: error: cannot find symbol
        final HeadlessJsTaskContext headlessJsTaskContext = HeadlessJsTaskContext.getInstance(reactContext);
                                                            ^
  symbol:   variable HeadlessJsTaskContext
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/RNBackgroundFetchModule.java:11: error: RNBackgroundFetchModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class RNBackgroundFetchModule extends ReactContextBaseJavaModule implements ActivityEventListener, LifecycleEventListener {
       ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/RNBackgroundFetchModule.java:115: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/RNBackgroundFetchModule.java:124: error: method does not override or implement a method from a supertype
    @Override
    ^
25 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-background-fetch:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 12s
32 actionable tasks: 2 executed, 30 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.
```

**Comment by christocracy** [comment]
Ignored issue template.

**Comment by christocracy** [comment]
Edit your issue and provide all the requested information.

**Comment by Sm038229** [comment]
Please find updated issue and provide a solution for it.

**Comment by christocracy** [comment]
1.  Missing `ext` params in `android/build.gradle`.  By default, react-native adds these params to newly created apps.  Your app was probably generated before RN implemented this.  Add the `ext` params as documented in [setup steps](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-RNPM.md#open_file_folder-androidbuildgradle)

2.  Hard-coded `support-lib-version` in `android/app/build.gradle`.  A newly created RN app uses the Gradle param `ext.supportLibVersion`:

```diff
dependencies {
    .
    .
    .
+  implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation 'com.facebook.react:react-native:+'
}
```

**Comment by christocracy** [comment]
In addition, use `ext` params here in `android/app/build.gradle` as well:
```diff
android {
+    compileSdkVersion rootProject.ext.compileSdkVersion
+    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
+       minSdkVersion rootProject.ext.minSdkVersion
+       targetSdkVersion rootProject.ext.targetSdkVersion
         .
         .
         .
    }
```

**Comment by christocracy** [comment]
And this is wrong:  get rid of it.

```diff
repositories {
-    flatDir {
-        dirs "../../node_modules/react-native-background-geolocation/android/libs"
-    }
-    flatDir {
-        dirs "../../node_modules/react-native-background-fetch/android/libs"
-    }
-}

dependencies {
    implementation project(':react-native-material-kit')
    implementation project(':react-native-icons')
    implementation project(':react-native-background-geolocation')
    implementation project(':react-native-background-fetch')
    implementation project(':react-native-android-permissions')
    implementation project(':react-native-vector-icons')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:28.0.0"
    implementation 'com.facebook.react:react-native:+'
}
```

**Comment by Sm038229** [comment]
Now getting error
==============

> Task :react-native-background-fetch:compileDebugJavaWithJavac FAILED
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:7: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:9: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:13: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskConfig;
                                 ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:14: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskContext;
                                 ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:15: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskEventListener;
                                 ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:17: error: cannot find symbol
import com.facebook.react.common.LifecycleState;
                                ^
  symbol:   class LifecycleState
  location: package com.facebook.react.common
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:23: error: cannot find symbol
public class HeadlessTask implements HeadlessJsTaskEventListener {
                                     ^
  symbol: class HeadlessJsTaskEventListener
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:26: error: cannot find symbol
    private ReactNativeHost mReactNativeHost;
            ^
  symbol:   class ReactNativeHost
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:27: error: cannot find symbol
    private HeadlessJsTaskContext mActiveTaskContext;
            ^
  symbol:   class HeadlessJsTaskContext
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:63: error: cannot find symbol
    protected void startTask(final HeadlessJsTaskConfig taskConfig) {
                                   ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:89: error: cannot find symbol
    private void invokeStartTask(ReactContext reactContext, final HeadlessJsTaskConfig taskConfig) {
                                                                  ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:31: error: cannot find symbol
            ReactApplication reactApplication = ((ReactApplication) context.getApplicationContext());
            ^
  symbol:   class ReactApplication
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:31: error: cannot find symbol
            ReactApplication reactApplication = ((ReactApplication) context.getApplicationContext());
                                                  ^
  symbol:   class ReactApplication
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:37: error: cannot find symbol
        HeadlessJsTaskConfig config = new HeadlessJsTaskConfig(HEADLESS_TASK_NAME, new WritableNativeMap(), 30000);
        ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:37: error: cannot find symbol
        HeadlessJsTaskConfig config = new HeadlessJsTaskConfig(HEADLESS_TASK_NAME, new WritableNativeMap(), 30000);
                                          ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:46: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:50: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:78: error: cannot find symbol
                    reactInstanceManager.removeReactInstanceEventListener(this);
                                        ^
  symbol:   method removeReactInstanceEventListener(<anonymous ReactInstanceEventListener>)
  location: variable reactInstanceManager of type ReactInstanceManager
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:90: error: cannot find symbol
        if (reactContext.getLifecycleState() == LifecycleState.RESUMED) {
                        ^
  symbol:   method getLifecycleState()
  location: variable reactContext of type ReactContext
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:90: error: cannot find symbol
        if (reactContext.getLifecycleState() == LifecycleState.RESUMED) {
                                                ^
  symbol:   variable LifecycleState
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:93: error: cannot find symbol
        final HeadlessJsTaskContext headlessJsTaskContext = HeadlessJsTaskContext.getInstance(reactContext);
              ^
  symbol:   class HeadlessJsTaskContext
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:93: error: cannot find symbol
        final HeadlessJsTaskContext headlessJsTaskContext = HeadlessJsTaskContext.getInstance(reactContext);
                                                            ^
  symbol:   variable HeadlessJsTaskContext
  location: class HeadlessTask
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/RNBackgroundFetchModule.java:11: error: RNBackgroundFetchModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class RNBackgroundFetchModule extends ReactContextBaseJavaModule implements ActivityEventListener, LifecycleEventListener {
       ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/RNBackgroundFetchModule.java:115: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/RNBackgroundFetchModule.java:124: error: method does not override or implement a method from a supertype
    @Override
    ^
25 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-background-fetch:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12m 41s
32 actionable tasks: 32 executed
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.

**Comment by christocracy** [comment]
Open your app in Android Studio.  It will give you more assistance about problems.

**Comment by Sm038229** [comment]
![Screenshot 2019-06-20 at 6 40 52 PM](https://user-images.githubusercontent.com/9651635/59851828-2f036680-938b-11e9-9879-21f7e4896c70.png)

**Comment by christocracy** [comment]
Great, now investigate the "No such file or directory".
- What *file or directory*?

**Comment by Sm038229** [comment]
> Task :react-native-background-fetch:compileDebugJavaWithJavac
/Users/sachchidanandmishra/Extra/Test Apps/ABC/safeapp/SafeApp/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:7: error: cannot find symbol
import com.facebook.react.ReactApplication;

**Comment by Sm038229** [comment]
25 errors

> Task :react-native-background-fetch:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-background-fetch:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by christocracy** [comment]
Create a new RN Hello World app and test the installation in isolation of your app.

**Comment by Sm038229** [comment]
Thanks its working.

**Comment by Sm038229** [comment]
Hi Chris,

Created fresh project and it is working as per expectation but,
when I try to use getCurrentPosition method following exception is blocking our progress. 

"possible unhandled promise rejection (id: 0): #getCurrentPosition requires options {} as first argument'"

here is how I am trying to access that method:

backgroundGeolocation.getCurrentPosition({timeout: 30}, function (location) {
                alert('success');
            }, function (error) {
                alert("Location error get current: " + error);
            });

Could you please help to resolve this roadblock? Thanks in advance.

**Comment by christocracy** [comment]
Look at [the source](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/src/index.js#L510-L513) for `getCurrentPosition`:
```javascript
static getCurrentPosition(options, success, failure) {
    if (typeof(options) === 'function') {
      throw "#getCurrentPosition requires options {} as first argument";
    }
    if (typeof(success) === 'function') {
      NativeModule.getCurrentPosition(options).then(success).catch(failure);
    } else {
      return NativeModule.getCurrentPosition.apply(NativeModule, arguments);
    }
  }
```

You are doing something wrong.

**Comment by Sm038229** [comment]
Thanks.
