### ISSUE TITLE
Build failed on Xcode

### ISSUE THREAD

**Issue by carmeloleonardi** [transistorsoft/react-native-background-geolocation#743]
## Your Environment
* Plugin version: react-native-background-geolocation": "^3.0.7"
* Platform: iOS 
* OS version: 12.3.1
* Device manufacturer / model: iPad
* React Native version (`react-native -v`): react-native: 0.59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
import React from 'react';
import { 
    View,
    StyleSheet,
    TouchableOpacity
} from 'react-native';

import BackgroundGeolocation, {
    State,
    Config,
    Location,
    LocationError,
    Geofence,
    GeofenceEvent,
    GeofencesChangeEvent,
    HeartbeatEvent,
    HttpEvent,
    MotionActivityEvent,
    MotionChangeEvent,
    ProviderChangeEvent,
    ConnectivityChangeEvent
  } from "react-native-background-geolocation";
  


export default class ControlScreen extends React.Component{

    componentWillMount() {
        ////
        // 1.  Wire up event-listeners
        //
    
        // This handler fires whenever bgGeo receives a location update.
        BackgroundGeolocation.onLocation(this.onLocation, this.onError);
    
        // This handler fires when movement states changes (stationary->moving; moving->stationary)
        BackgroundGeolocation.onMotionChange(this.onMotionChange);
    
        // This event fires when a change in motion activity is detected
        BackgroundGeolocation.onActivityChange(this.onActivityChange);
    
        // This event fires when the user toggles location-services authorization
        BackgroundGeolocation.onProviderChange(this.onProviderChange);
    
        ////
        // 2.  Execute #ready method (required)
        //
        BackgroundGeolocation.ready({
          // Geolocation Config
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10,
          // Activity Recognition
          stopTimeout: 1,
          // Application config
          debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
          startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
          // HTTP / SQLite config
          url: 'http://yourserver.com/locations',
          batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
          autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
          headers: {              // <-- Optional HTTP headers
            "X-FOO": "bar"
          },
          params: {               // <-- Optional HTTP params
            "auth_token": "maybe_your_server_authenticates_via_token_YES?"
          }
        }, (state) => {
          console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
    
          if (!state.enabled) {
            ////
            // 3. Start tracking!
            //
            BackgroundGeolocation.start(function() {
              console.log("- Start success");
            });
          }
        });
    }

    render(){
        return(
            <View>

            </View>
        )
    }
}
```

## Expected Behavior
Build success on Xcode

## Actual Behavior
Build failed on Xcode

## Steps to Reproduce

1. I read the guide for iOS
2.On Xcode make Run
3. Build failed
4.

## Context
Running the application on iPad

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
ld: warning: directory not found for option '-L/Users/carmeloleonardi/Library/Developer/Xcode/DerivedData/airplane_location-ggprbthzgnrhwegfaylauealjilu/Build/Products/Debug-iphoneos/DoubleConversion'
ld: warning: directory not found for option '-L/Users/carmeloleonardi/Library/Developer/Xcode/DerivedData/airplane_location-ggprbthzgnrhwegfaylauealjilu/Build/Products/Debug-iphoneos/Folly'
ld: warning: directory not found for option '-L/Users/carmeloleonardi/Library/Developer/Xcode/DerivedData/airplane_location-ggprbthzgnrhwegfaylauealjilu/Build/Products/Debug-iphoneos/React'
ld: warning: directory not found for option '-L/Users/carmeloleonardi/Library/Developer/Xcode/DerivedData/airplane_location-ggprbthzgnrhwegfaylauealjilu/Build/Products/Debug-iphoneos/glog'
ld: warning: directory not found for option '-L/Users/carmeloleonardi/Library/Developer/Xcode/DerivedData/airplane_location-ggprbthzgnrhwegfaylauealjilu/Build/Products/Debug-iphoneos/yoga'
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation).

</details>

Hi, I'm using this library for a project of background geolocation. I applied the guide for iOS but I have a problem with Xcode:

In the app React Native i have this error:

Native modules cannot be null.

How can I fix this errors?

**Comment by christocracy** [comment]
[Google it](https://www.google.com/search?safe=off&rlz=1C5CHFA_enCA816CA816&ei=LrQPXYnOFtKb_QbKtp_ACg&q=react-native+ld%3A+library+not+found+for+-lDoubleConversion&oq=react-native+ld%3A+library+not+found+for+-lDoubleConversion&gs_l=psy-ab.3...11331.14054..14289...2.0..0.125.931.14j1......0....1..gws-wiz.......0i71.C1A9AfaRoZQ)

**Comment by carmeloleonardi** [comment]
mmm So What?!

**Comment by christocracy** [comment]
If you're new to the plugin, first experiment with it in a fresh new React Native *Hello World* app.

**Comment by carmeloleonardi** [comment]
Yes, I’m new to the plugin. This is a “Hello World “app, but there are this problems with tue guide in this repository.

**Comment by christocracy** [comment]
Review the install instructions once again.  Restart XCode.  Make sure you're using latest XCode.

**Comment by carmeloleonardi** [comment]
I solved my issue. I skipped a step. Thank you!
