### ISSUE TITLE
Combine background-geolocation and background-fetch

### ISSUE THREAD

**Issue by AlexandreM59** [transistorsoft/react-native-background-geolocation#745]
This is not an issue, this is a question.

Is it possible to combine `react-native-background-geolocation` with `react-native-background-fetch` and use them together without any conflict while they are working (launching together when startOnBoot is on true for example when the phone restarts) ?

The idea is to use `react-native-background-geolocation` continuously in the background to track the position of the user, and at the same time check the server data in background with `react-native-background-fetch` every 15min.

Thank you for the answer !

**Comment by christocracy** [comment]
Yes.

**Comment by mikehardy** [comment]
Yeah - I do this happily in my app, with great appreciation that background-fetch exists on it’s own 🙏 - it’s a vital part of the strategy I’m using to prompt the user to upgrade versions when I release them (via the app doing periodic checks to a descriptor on a remote server)
