### ISSUE TITLE
DeviceSettingsRequest not working on MIUI (Xiaomi) devices

### ISSUE THREAD

**Issue by elieteyssedou** [transistorsoft/react-native-background-geolocation#746]
Hi,

It seems that there is an issue with device settings request ([showPowerManager](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.devicesettings.html#showpowermanager)) on devices using latest Android MIUI. I recently updated it, switching from Android 8 to 9.

## Your Environment
* Plugin version: `3.0.7`
* Platform: `Android`
* OS version: `Android 9`, `MIUI Global 10.3.1`
* Device manufacturer / model: `Xiaomi Redmi Note 5`
* React Native version: `0.59.9`
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.deviceSettings.showPowerManager().then((request) => {
  Alert.alert('...', '...', [
    {
      text: 'Confirm',
      onPress: () => BackgroundGeolocation.deviceSettings.show(request)
    }
  ], { cancelable: false })
})
```

## Expected Behavior
It should open Device Settings on `BackgroundGeolocation.deviceSettings.show`.

## Actual Behavior
I get an error and the app crashes. I get the following error message :
`calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK`. I guess that it is related to MIUI but I am not sure.

## Steps to Reproduce

1. Install last MIUI Stable version
2. Use device settings request in a new app
3. Get the error

## Context
I want the user to set correctly device settings to track location in background.

## Debug logs
![Screenshot_2019-06-26-11-29-50-134_ee deliver companion](https://user-images.githubusercontent.com/8143621/60171794-a877da80-980b-11e9-9c31-22270ed1a335.png)

**Comment by christocracy** [comment]
Will be fixed in next release.

```java
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
```

**Comment by elieteyssedou** [comment]
Thank you @christocracy !
