### ISSUE TITLE
locationTimeout clarification please

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#749]
The page https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#locationtimeout says the following about `locationTimeout`: 

> locationTimeout: number
> 
> Disable automatic, speed-based distanceFilter scaling.
> 
> Defaults to false. Set true to disable automatic, speed-based distanceFilter elasticity.

but if I look at this plugin's configuration, I see: 

>   "locationTimeout": 60,

on both iOS and Android (react-native-background-geolocation 3.0.x). We've never configured `locationTimeout` before so I'm guessing 60 is the default value?

So my questions are:

1. Is `locationTimeout` a number or a boolean? Your documentation is contradictory
2. What effect does a value of 60 have, if any?

**Comment by christocracy** [comment]
Docs bug.  You generally shouldn't need to worry about `locationTimeout`.  `60` seconds is the default.

**Comment by bengtan** [comment]
Okay, thanks.
