### ISSUE TITLE
invalid license when upgrading to latest version 

### ISSUE THREAD

**Issue by DavidPineda** [transistorsoft/react-native-background-geolocation#751]
My app show message of invalid license when upgrade from 2.14.2 to 3.0.7

## Your Environment
* Plugin version: 2.14.2
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Motorola / g6
* React Native version (`react-native -v`): 0.59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1. upgrade from 2.14.2 to 3.0.7
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Did you see the [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#300-rc1---2019-03-27)?

**Comment by DavidPineda** [comment]
Thanks, I had not seen it, however I can not access the product dashboard.

**Comment by christocracy** [comment]
Members added to the private repo are not granted access to the Dashboard.  Talk to the person who purchased and/or registered the product.  Only their Github account has access to the product dashboard.
