### ISSUE TITLE
Odometer issues

### ISSUE THREAD

**Issue by chrisid** [transistorsoft/react-native-background-geolocation#755]
Any idea why the odometer won't update?
Debugging I can see the coordinates and I can calculate the distance between them.
How is the odometer calculated?

* Plugin version: 3.0.7
* Platform: iOS
* OS version: iOS 12.3.1
* Device manufacturer / model: iPhone X
* React Native version (`react-native -v`): 0.59.9
* Plugin config

```javascript <!-- Syntax-highlighting:  paste your code below -->
reset: true,
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
distanceFilter: 5,
desiredOdometerAccuracy: 5,
disableElasticity: true,
locationUpdateInterval: 3000, 
fastestLocationUpdateInterval: 5000,
stationaryRadius: 5,
locationAuthorizationRequest: 'WhenInUse',
foregroundService: true,
debug: false,
logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
stopOnTerminate: true, 
startOnBoot: false,
```

## Expected Behavior
odometer to be updated

## Actual Behavior
Odometer is always 0

**Comment by KMR-86** [comment]
did you solved this problem?
if yes, then how?
