### ISSUE TITLE
Ready called during background tracking causes tracking to stop.

### ISSUE THREAD

**Issue by 1602** [transistorsoft/react-native-background-geolocation#758]
## Your Environment
* Plugin version: 3.0.4
* Platform: Android
* OS version: 9
* Device manufacturer / model: Galaxy S8 (SM-G950F)
* React Native version (`react-native -v`): 0.59.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        reset: true,
        enableHeadless: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 10,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        heartbeatInterval: 300,
}
```

## Expected Behavior

Launch of app during tracking should not cause tracking to stop.

## Actual Behavior

Launch of app causes tracking to stop due to call to `ready` method.

## Steps to Reproduce
1. install app
2. close app
3. start walking so that tracking engages
4. open app while walking (tracking stops at this point)

## Context

I'm working on an app which tracks walking routes, user might want to open an app during their walk and it should not cause tracking to stop.

## Current workaround
```javascript
const bgState = await BackgroundGeolocation.getState();

if (!bgState.isMoving) {
    const { enabled } = await BackgroundGeolocation.ready(config);
    if (!enabled) {
        BackgroundGeolocation.start();
    }
}
```

Question: is it expected behaviour and a correct workaround or a bug? Documentation does mention that `ready` should be called once per installation, but it is not clear what is the right way of achieving this. Currently app calls `ready` in `componentWillMount` as per demo application.

**Comment by christocracy** [comment]
You're only supposed to call `#ready` once.   `#ready` is a signal to the plugin that your app has just launched and is now "ready" to start emitting events.  A more recent version of 3.x redirects `#ready` to `#setConfig` if it's already been called.

**Comment by 1602** [comment]
Thank you, I will try upgrading to the latest version and remove the workaround.
