### ISSUE TITLE
Android- Not able to get current location when the app is terminated

### ISSUE THREAD

**Issue by Priyankavprk** [transistorsoft/react-native-background-geolocation#761]
## Your Environment
* Plugin version: 3.0.7
* Platform:  Android
* OS version: 7.0
* Device manufacturer / model: ASUS
* React Native version (`react-native -v`): 0.59.9
* Plugin config
```
BackgroundGeolocation.ready({
      enableHeadless: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      stopTimeout: 1,
      locationUpdateInterval: config.LOCATION_UPDATE_INTERVAL,
      fastestLocationUpdateInterval: config.LOCATION_UPDATE_INTERVAL,

      debug: true, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,  
      startOnBoot: true,       
      url: config.GPS_ENDPOINT,
      batchSync: false,       
      autoSync: true,       
      headers: {            
        "X-FOO": "bar"
      },
      params: {              
        device: deviceInfo,
        mobileDeviceId: deviceInfo.uuid,
      }
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
        });
      }
    });
  }

```

## Expected Behavior
I am getting the hearbeat events when the app is terminated and the heartbeat event is also triggered but the following error occurs on finding location 
Failed to get last location: com.google.android.gms.tasks.zzp@22c9702

## Actual Behavior
The hearbeat event should get location and hence make api call to post that data. 

## Steps to Reproduce
1. Added the enableheadless
2. Added code snipet for the heartbeat event as shown in wiki inside index.android.js
  let HeadlessTask = async (event) => {
  let params = event.params;
  console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);

  switch (event.name) {
    case 'heartbeat':
      await getCurrentPosition();
      console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:');
      break;
  }
}

let getCurrentPosition = () => {
  BackgroundGeolocation.getCurrentPosition({
    samples: 1,
    persist: true
  }).then((location) => {
    // console.log('[getCurrentPosition] ', location);
    postLoggerItem(Object.assign({}, location, {extras: {event: 'heartbeat'}}))
  });
};

export function postLoggerItem(item) {
 const body = JSON.stringify({
    ...item,
    mobileDeviceId: deviceInfo.uuid,
    device: deviceInfo,
  });
  return fetch(config.GPS_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body,
  })
    .then((response) => {
      if (!response.ok) {

        throw Error(response.statusText);

      }
      console.log(`POST ${config.GPS_ENDPOINT} SUCCESS`);
      return response;
    });
}

## Debug logs
``` 
07-05 06:53:04.993 21207 21207 I TSLocationManager:   🎾  Start monitoring location-provider changes
07-05 06:53:05.003 21207 21256 I TSLocationManager: [c.t.l.http.HttpService flush] 
07-05 06:53:05.003 21207 21256 I TSLocationManager: ╔═════════════════════════════════════════════
07-05 06:53:05.003 21207 21256 I TSLocationManager: ║ HTTP Service (count: 0)
07-05 06:53:05.003 21207 21256 I TSLocationManager: ╠═════════════════════════════════════════════
07-05 06:53:05.015 21207 21207 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
07-05 06:53:05.051 21207 21207 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
07-05 06:53:05.083 21207 21207 D TSLocationManager: [c.t.r.HeadlessTask onHeadlessEvent] 💀  event: providerchange
07-05 06:53:05.119 21207 21207 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
07-05 06:53:05.139 21207 21207 D TSLocationManager: [c.t.r.HeadlessTask onHeadlessEvent] 💀  event: terminate
07-05 06:53:05.163 21207 21207 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
07-05 06:53:05.179 21207 21207 D TSLocationManager: [c.t.r.HeadlessTask onHeadlessEvent] 💀  event: connectivitychange
07-05 06:53:49.924 21207 21207 D TSLocationManager: [c.t.l.service.HeartbeatService onStartCommand] ❤️
07-05 06:53:50.008 21207 21207 E TSLocationManager: [c.t.l.l.TSLocationManager getLastLocation] 
07-05 06:53:50.008 21207 21207 E TSLocationManager:   ‼️  Failed to get last location: com.google.android.gms.tasks.zzp@f880725
07-05 06:53:50.027 21207 21207 D TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
07-05 06:53:50.047 21207 21207 D TSLocationManager: [c.t.r.HeadlessTask onHeadlessEvent] 💀  event: heartbeat
07-05 06:54:50.032 21207 21207 D TSLocationManager: [c.t.l.service.HeartbeatService onStartCommand] ❤️
07-05 06:54:50.116 21207 21207 E TSLocationManager: [c.t.l.l.TSLocationManager getLastLocation] 

```

</details>

**Comment by christocracy** [comment]
The heartbeat never requests a current location, it only provides last known location.  After a reboot, there is no last known location.

You’re free to execute #getCurrentPosition as desired in your #onHeartbeat callback.
