### ISSUE TITLE
IOS doesn't receive location when app killed

### ISSUE THREAD

**Issue by narefyev91** [transistorsoft/react-native-background-geolocation#763]
## Your Environment
* Plugin version: 3.0.5 (higher doesn't allow to install expoKit)
* Platform: iOS or Android: IOS - Used Ejected expo from latest version
* OS version: 12.3
* Device manufacturer / model: iPhone 8
* React Native version (`react-native -v`): 0.59.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      reset: true,
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
    }```

## Expected Behavior
When I closed app I expect to get location
## Actual Behavior
When the app in background all is fine, locations come, but when kill the app, nothing happened
## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
Tested on the real app, installed from TestFlight
Tried to get location when app is killed here
  onLocation = async (location) => {
    const userId = await AsyncStorage.getItem('userId');
    setGeoLocation({
      latitude: Number(location.coords.latitude),
      longitude: Number(location.coords.longitude),
    }, userId);
    console.log('[location] -', location);
  };
All works if in the background
Any help or ideas will be appreciated
## Debug logs
Doesn't get anything in logs
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version: 3.0.5 (higher doesn't allow to install expoKit)

What version of XCode do you have installed?

**Comment by christocracy** [comment]
Have you tested this in the Simulator?

**Comment by narefyev91** [comment]
Version 10.2.1 (10E1001) - Xcode
In Simulator I tested only background realization.
Yes - all permissions are set correctly

**Comment by christocracy** [comment]
Boot your app in Simulator then terminate it, like [in this video](https://youtu.be/aR6r8qV1TI8?t=213).

**Comment by narefyev91** [comment]
Did this - in console nothing, no messages

**Comment by narefyev91** [comment]
Use moving in high way - in background goes fine

**Comment by narefyev91** [comment]
@christocracy any ideas?

**Comment by christocracy** [comment]
No idea.  Clone the sample app (linked in plugin README) to test the plugin in isolation of your app code.

**Comment by Obi1Kennoby** [comment]
I have the same issue with android (tested on samsung galaxy s8, android 9, react-native 0.59.9)
onLocation (and it seems another ones either, like onHttp) event not fires when app is killed.

**Comment by narefyev91** [comment]
@christocracy You can close this issue - it's problem on the expo side, this is connected answer - https://github.com/expo/expo/issues/4860#issuecomment-510940125
