### ISSUE TITLE
Missing version 3.0.8 in npm

### ISSUE THREAD

**Issue by vovkind** [transistorsoft/react-native-background-geolocation#766]
## Your Environment
* Plugin version: 3.0.7
* Platform: iOS or Android
* OS version: N/A
* Device manufacturer / model N/A:
* React Native version (`react-native -v`): 0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```
N/A

## Expected Behavior
Expected to get version 3.0.8 with npm

## Actual Behavior
Getting npm error about the unavailability of this version

## Steps to Reproduce
N/A

## Context
N/A

## Debug logs
N/A

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
N/A
```

</details>

**Comment by christocracy** [comment]
`3.0.8` wasn't released to npm, it was skipped (only released to private repo).  The [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#change-log) is incorrect.  All the items from `3.0.8` appeared in `3.0.9`.

Use `3.0.9`.

**Comment by christocracy** [comment]
CHANGELOG is updated, removing `3.0.8`
