### ISSUE TITLE
Not able to run the app when direclty deployed or release using archive mode

### ISSUE THREAD

**Issue by akashdeepsharma1991** [transistorsoft/react-native-background-geolocation#767]
## Your Environment
* Plugin version: 
"react-native-background-fetch": "^2.6.0",
    "react-native-background-geolocation": "^3.0.7",

* Platform: iOS or Android :IOS
* OS version: 12.1
* Device manufacturer / model:  IPhone any device
* React Native version (`react-native -v`): "0.59.5",
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Should get build and deployed in device as we use the react-native run-ios  command 
## Actual Behavior

Not able to run the app when direclty deployed or release using archive mode
We have purchase the plugin 
## Steps to Reproduce

1. product > Archive
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_CLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_CLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in TSLocationManager(TSCurrentPositionRequest.o)
      objc-class-ref in TSLocationManager(DatabaseQueue.o)
      objc-class-ref in TSLocationManager(TSConfig.o)
      objc-class-ref in TSLocationManager(LocationAuthorization.o)
      objc-class-ref in TSLocationManager(TSHttpService.o)
      objc-class-ref in TSLocationManager(GeofenceDAO.o)
      objc-class-ref in TSLocationManager(LocationDAO.o)
      ...
  "_OBJC_CLASS_$_DDTTYLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._maxAge", referenced from:
      -[TSDBLogger getLog] in TSLocationManager(TSDBLogger.o)
      -[TSDBLogger db_delete] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._saveThreshold", referenced from:
      -[TSDBLogger initWithLogDirectory:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDAbstractLogger._logFormatter", referenced from:
      -[TSDBLogger db_log:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._context", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._flag", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDLogMessage._function", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDLogMessage._message", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDLogMessage._tag", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDLogMessage._timestamp", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_METACLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_METACLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

</details>

**Comment by christocracy** [comment]
*carefully* go through the setup docs once again.  You missed something.

**Comment by akashdeepsharma1991** [comment]
i tried again i am getting this error can u please help.
![Screenshot 2019-07-12 at 7 32 15 PM](https://user-images.githubusercontent.com/33919907/61133829-d92e6400-a4db-11e9-9507-155f82e6dcc9.png)

**Comment by christocracy** [comment]
Your app is not finding the `React` framework.

I suggest you start by first testing the plugin in a fresh new Hello World app before attempting to integrate it into an existing app.

**Comment by christocracy** [comment]
Every single one of your dependencies is "Missing dependency target React".

**Comment by akashdeepsharma1991** [comment]
the plugin works in new project but what the use if i cannot integrate it in my actual app.  :( . i am really stuck can u please help..

**Comment by christocracy** [comment]
>but what the use if i cannot integrate it in my actual app

To test the plugin in isolation of your application code.  The problem is configuration issue in your app.

- Terminate XCode
```
$ cd ios
$ rm -rf Pods
$ rm Podfile.lock
$ pod install
```
- Re-open XCode and rebuild

**Comment by akashdeepsharma1991** [comment]
hii tried the above steps still getting same error :(

**Comment by christocracy** [comment]
Then you have a problem in your `Podfile`.  Paste it.

**Comment by akashdeepsharma1991** [comment]
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'driver_app_v2' do
  rn_path = '../node_modules/react-native'

  use_frameworks!
  pod 'CocoaLumberjack/Swift'
  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"




#  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

**Comment by christocracy** [comment]
Get rid of `use_frameworks!`
```diff
+  #use_frameworks!
```

**Comment by christocracy** [comment]
Also, who told you to do this?
```
pod 'CocoaLumberjack/Swift'
```

**Comment by akashdeepsharma1991** [comment]
i was getting error of  'CocoaLumberjack/Swift' not found.   so i google how to install it and follow the instruction on the  git repo of cocoalumberjack.

**Comment by christocracy** [comment]
Get rid of this:
```
pod 'CocoaLumberjack/Swift'
```

**Comment by akashdeepsharma1991** [comment]
yes doing that now and checking again

**Comment by christocracy** [comment]
Are you *sure* you followed the [iOS Setup Instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-RNPM.md#react-native--059)?

```
react-native link react-native-background-geolocation
react-native link react-native-background-fetch
react-native link cocoa-lumberjack       // <------------- You probably didn't do this
```

**Comment by akashdeepsharma1991** [comment]
after doing this i am getting this error..
![Screenshot 2019-07-12 at 8 31 56 PM](https://user-images.githubusercontent.com/33919907/61137963-2e6e7380-a4e4-11e9-8abc-62dc71e31a65.png)

**Comment by akashdeepsharma1991** [comment]
react-native link cocoa-lumberjack i have followed eveystep u mentioned in repo..

**Comment by akashdeepsharma1991** [comment]
And catch with this error is that it doesnt comes when i run react-native run-ios command.. only happen when i try to make a ipa for other to use

**Comment by christocracy** [comment]
- Clean your build
- Terminate XCode
```
$ react-native unlink react-native-background-geolocation
$ react-native unlink react-native-background-fetch
$ react-native unlink cocoa-lumberjack

$ react-native link react-native-background-geolocation
$ react-native link react-native-background-fetch
$ react-native link cocoa-lumberjack

$ cd ios
$ rm -rf Pods
$ rm Podfile.lock
$ pod install
```
- Open XCode and build.

**Comment by akashdeepsharma1991** [comment]
getting this error for coco-lumber react-native unlink cocoa-lumberjack
error Project "cocoa-lumberjack" is not a react-native library. Run CLI with --verbose flag for more details.

**Comment by christocracy** [comment]
Open your `Project.xcodeproj` and expend the `/Libraries` folder.  show me the screenshot.

**Comment by christocracy** [comment]
Note:  I said `Project.xcodeproj`, not `Project.xcworkspace`.  Close XCode and open `Project.xcodeproj`.

**Comment by akashdeepsharma1991** [comment]
![Screenshot 2019-07-12 at 8 45 04 PM](https://user-images.githubusercontent.com/33919907/61138916-f9fbb700-a4e5-11e9-9e00-6a5078a052db.png)

**Comment by akashdeepsharma1991** [comment]
when we run the react-native run-ios command its default take Project.xcworkspace file is this rite?

**Comment by christocracy** [comment]
*Right-click Lumberjack.xcodeproj -> Delete -> [Move to Trash]*

**Comment by christocracy** [comment]
Close `Project.xcodeproj` and `react-native link` everything again.

**Comment by akashdeepsharma1991** [comment]
getting this error react-native link cocoa-lumberjack
error Failed to get dependency config. Run CLI with --verbose flag for more details.

**Comment by akashdeepsharma1991** [comment]
how can in install  cocoa-lumberjack

**Comment by akashdeepsharma1991** [comment]
hii @christocracy  waiting for your reply for the error 

getting this error react-native link cocoa-lumberjack
error Failed to get dependency config. Run CLI with --verbose flag for more details.

please help

**Comment by nicholascm** [comment]
@akashdeepsharma1991  It looks like it used to be installed as a dependency but was removed https://github.com/transistorsoft/react-native-background-geolocation/compare/3.0.0...master#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L47.  

Seeing that you are running RN < v60, he says in the changelog that it needs to be manually added ( see [here](https://github.com/transistorsoft/react-native-background-geolocation/compare/3.0.0...master#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L47))  Probably just a `yarn add cocoa-lumberjack` or `npm install cocoa-lumberjack` should work followed by the linking step.
