### ISSUE TITLE
'TSBackgroundFetch/TSBackgroundFetch.h' file not found

### ISSUE THREAD

**Issue by kirkryan** [transistorsoft/react-native-background-geolocation#769]
## Your Environment
* Plugin version: 3.0.9
* Platform: iOS and Android
* OS version: NA
* Device manufacturer / model: NA
* React Native version (`react-native -v`): 0.60.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
N/A
```

## Expected Behavior
Following the install instructions [here](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-RNPM.md) (react-native link) for => 0.60.0 should result in a successful build.

Commands run:
This is a brand new project - react-native 0.60.3
```
react-native init installRNBG
yarn add react-native-background-geolocation
yarn add react-native-background-fetch
react-native link react-native-background-geolocation
react-native link react-native-background-fetch
```
![image](https://user-images.githubusercontent.com/18603029/61173151-21ef2700-a587-11e9-8f7f-ac79d374f5dc.png)

open project in xcode (10.2.1)
build to device

## Actual Behavior
xCode fails to build and shows the following error: 'TSBackgroundFetch/TSBackgroundFetch.h' file not found
![image](https://user-images.githubusercontent.com/18603029/61173173-9b871500-a587-11e9-9812-c7aeda276e42.png)

## Steps to Reproduce
As above

## Context
Here is my package.json
```
{
  "name": "installRNBG",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.3",
    "react-native-background-fetch": "^2.6.1",
    "react-native-background-geolocation": "^3.0.9"
  },
  "devDependencies": {
    "@babel/core": "^7.5.4",
    "@babel/runtime": "^7.5.4",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.0.1",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
/Users/kirkryan/Documents/dev/installRNBG/node_modules/react-native-background-fetch/ios/RNBackgroundFetch/RNBackgroundFetch+AppDelegate.m:11:9: fatal error: 'TSBackgroundFetch/TSBackgroundFetch.h' file not found
#import <TSBackgroundFetch/TSBackgroundFetch.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

</details>

**Comment by christocracy** [comment]
```
$ cd ios
$ pod install
```

**Comment by kirkryan** [comment]
Thanks, Chris, that worked. Still getting my head around the new way of doing things.

**Comment by rolfb** [comment]
Just leaving a comment here since the error may also be due to not explicitly adding react-native-background-fetch as a dependency with npm/yarn as it looks like it gets installed when you add react-native-background-geolocation.
