### ISSUE TITLE
maxRecordsToPersist doesn't appear to be honored

### ISSUE THREAD

**Issue by nevir** [transistorsoft/react-native-background-geolocation#77]
(latest version)

I'm attempting to disable persistence (we're not using it) by setting `maxRecordsToPersist` to `0`.  RNBG doesn't seem to honor this (event count keeps growing).  Same behavior when setting it to `1`.

---

Aside: Is a certain amount of history necessary for RNBG during regular operation?

**Comment by christocracy** [comment]
Thanks, I'll check it out

On Tuesday, April 26, 2016, Ian MacLeod <notifications@github.com> wrote:

> I'm attempting to disable persistence (we're not using it) by setting
> maxRecordsToPersist to 0. RNBG doesn't seem to honor this (event count
> keeps growing). Same behavior when setting it to 1.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/77>
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
This works for me.  What version of the plugin are you using?  `maxRecordsToPersist` is a very recent feature, first appearing in [version 1.1.0](https://github.com/transistorsoft/react-native-background-geolocation-android/blob/master/CHANGELOG.md#110---2016-04-04)

**Comment by nevir** [comment]
Hmm, k, I'll double check my environment

**Comment by christocracy** [comment]
Confirmation?
