### ISSUE TITLE
question - how to update component state from onLocation()

### ISSUE THREAD

**Issue by dakkafex** [transistorsoft/react-native-background-geolocation#771]
So maybe not completely related to the lib but i have looked trough the demo app and asked around but I just cant figure it out.

Im trying to update the state of my component in the onLocation() method as follows
```
  onLocation(location) {
    console.log('[location] -', location);
    this.setState({
      region: {
        latitude: location.coords.latitude,
        longitude: location.coords.longitude
      }
    })
  }
``` 
but all it results in is ``this.setState is not a function`` error 
I have looked in the ``simpleMap`` file of the demo app, but as far as i can see it looks the same.

again, sorry if its the wrong place, but i have exhausted my other resources.

**Comment by dakkafex** [comment]
nevermind.

**Comment by christocracy** [comment]
`.bind(this)`.
