### ISSUE TITLE
OnLocation mostly don't detecting moving when app is in the background

### ISSUE THREAD

**Issue by robert599** [transistorsoft/react-native-background-geolocation#772]
## Your Environment
* Plugin version: 3.0.7
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Huawai P10 Lite (and others)
* React Native version (`react-native -v`): 0.58.6
* Plugin config
```javascript
// init BackgroundGeolocation
        BackgroundGeolocation.ready({
            // Geolocation Config
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            // distance difference in meters
            distanceFilter: 5,
            // Activity Recognition - The number of **minutes** to wait before turning off location-services after the
            // ActivityRecognition System (ARS) detects the device is `STILL`
            stopTimeout: 200,
            // Interval while the device is in **stationary** state - 60 seconds are minimum for android.
            heartbeatInterval: 60,
            // Application config
            debug: true, // play sound if there is a location moving
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,   // Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true,        // Auto start tracking when device is powered-up.
            batchSync: false,       // Set true to sync locations to server in a single HTTP request.
            autoSync: true,         // Set true to sync each location to server as it arrives.
            startForeground: true, // hide location service notification for android < 8
            notification: {
                title: Localization('Settings.Notifications.BackgroundGeolocation.Title'),
                text: Localization('Settings.Notifications.BackgroundGeolocation.Message')
            },
        }, (state) => {
            if (!state.enabled && (this.props.allSettings && this.props.allSettings.geoNotification)) {
                // start tracking
                BackgroundGeolocation.start();
            }

            // disable tracking when geolocation notification is not wanted
            if (this.props.allSettings && !this.props.allSettings.geoNotification) {
                BackgroundGeolocation.stop();
            }
        });
```

## Expected Behavior
When the app is closed or just in the background and I stand still for a couple of minutes, the onLocation callback should send a callback with my location when I start to move. 

## Actual Behavior
When the app is closed or just in the background and I stand still for a couple of minutes, the onLocation callback doesn't triggered. 

## Steps to Reproduce
1. start the app (with the backgroundGeolocation task)
2. walk around -> location data is working
3. stand still for about 10 minutes
4. move on -> no location data

## Context
Looking for some points of interest in my near, while I walk e.g. along the city.

## Debug logs
<details><summary>Logs</summary>
``` 
07-16 12:45:23.432  6902  6902 D TSLocationManager: ╔═════════════════════════════════════════════
07-16 12:45:23.432  6902  6902 D TSLocationManager: ║ TrackingService: LocationResult
07-16 12:45:23.432  6902  6902 D TSLocationManager: ╠═════════════════════════════════════════════
07-16 12:45:23.432  6902  6902 D TSLocationManager: ╟─ �  Location[fused 50.912598,13.338598 hAcc=20 et=+1h58m36s660ms alt=0.0 vel=326.0 bear=174.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 14ms, time: 1563281124000
07-16 12:45:23.453  6902  6902 D TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult]
07-16 12:45:23.453  6902  6902 D TSLocationManager: ╔═════════════════════════════════════════════
07-16 12:45:23.453  6902  6902 D TSLocationManager: ║ Process LocationResult
07-16 12:45:23.453  6902  6902 D TSLocationManager: ╠═════════════════════════════════════════════
07-16 12:45:23.474  6902  6902 D TSLocationManager: [c.t.l.l.TSLocationManager locationIsInvalid] Distance from last location: 156.0929, apparent speed: 52.030964
07-16 12:45:23.491  6902  6902 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 20.0
07-16 12:45:23.500  6902  6902 D TSLocationManager: [c.t.l.l.TSLocationManager incrementOdometer] Odometer: 143979.77
07-16 12:45:23.509  6902  6902 I TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult]
07-16 12:45:23.509  6902  6902 I TSLocationManager:   �  Re-scaled distanceFilter: 70.0->330.0)
07-16 12:45:23.517  6902  6902 I TSLocationManager: [c.t.l.service.TrackingService a]
07-16 12:45:23.517  6902  6902 I TSLocationManager:   ℹ️  Distance from stoppedAtLocation: 116.092896
07-16 12:45:23.518  6902 12082 I TSLocationManager: [c.t.l.data.sqlite.b persist]
07-16 12:45:23.518  6902 12082 I TSLocationManager:   ✅  INSERT: 080d980c-fdd6-4128-af9e-582232d23eeb
07-16 12:45:23.526  6902  6902 D TSLocationManager: [c.t.l.service.TrackingService a]
07-16 12:45:23.526  6902  6902 D TSLocationManager:   ℹ️  Force cancel cancel stopTimeout due to apparent movement beyond stoppedAt location
07-16 12:45:23.546  6902  6902 D TSLocationManager: [c.t.l.service.TrackingService f]
07-16 12:45:23.546  6902  6902 D TSLocationManager:   ⏰ Reset stopTimeout timer
07-16 12:45:23.584  6902  6902 D TSLocationManager: [c.t.l.service.TrackingService a]
07-16 12:45:23.584  6902  6902 D TSLocationManager: ╔═════════════════════════════════════════════
07-16 12:45:23.584  6902  6902 D TSLocationManager: ║ TrackingService: LocationResult
07-16 12:45:23.584  6902  6902 D TSLocationManager: ╠═════════════════════════════════════════════
07-16 12:45:23.584  6902  6902 D TSLocationManager: ╟─ �  Location[fused 50.912598,13.338598 hAcc=20 et=+1h58m36s660ms alt=0.0 vel=326.0 bear=174.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 166ms, time: 1563281124000
07-16 12:45:23.597  6902  6902 D TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult]
07-16 12:45:23.597  6902  6902 D TSLocationManager: ╔═════════════════════════════════════════════
07-16 12:45:23.597  6902  6902 D TSLocationManager: ║ Process LocationResult
07-16 12:45:23.597  6902  6902 D TSLocationManager: ╠═════════════════════════════════════════════
07-16 12:45:23.612  6902  6902 D TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult]
07-16 12:45:23.612  6902  6902 D TSLocationManager:   ℹ️  IGNORED: same as last location
07-16 12:45:23.628  6902  6902 I TSLocationManager: [c.t.l.s.TSScheduleManager oneShot]
07-16 12:45:23.628  6902  6902 I TSLocationManager:   ⏰ Scheduled OneShot: STOP_TIMEOUT in 12000000ms (jobID: 2059034116)
07-16 12:45:23.649  6902  6902 I TSLocationManager: [c.t.l.service.TrackingService a]
07-16 12:45:23.649  6902  6902 I TSLocationManager:   ℹ️  Distance from stoppedAtLocation: -40.0

```

</details>

**Comment by christocracy** [comment]
I regularly test with a Huawei p20 and it’s the worst of my 11 test devices.

http://dontkillmyapp.com

**Comment by robert599** [comment]
Nice joke, but on a Pixel2 XL device it's the same behaviour. 
Do you think android is killing this process after a couple of minutes for saving energy?

**Comment by christocracy** [comment]
Android is not killing the process on a Pixel.

Are you observing your own adb logcat?

**Comment by robert599** [comment]
Yeah, the log say's that the listener is still running, even on the huawai device ;-). 
I found out that when the app is closed, the onLocation-Method is not called. Is there a way that this method is called, even when the app is closed? Sounds a little paradox, I know.

**Comment by jensengelmann** [comment]
This might to be related to these issues: https://github.com/transistorsoft/react-native-background-geolocation/issues/763, https://github.com/transistorsoft/react-native-background-geolocation/issues/735

**Comment by jensengelmann** [comment]
@christocracy Do you have any updates on this issue? Do you need any feedback oder further information?

**Comment by christocracy** [comment]
@robert599 
>I found out that when the app is closed, the onLocation-Method is not calle

Of course not.  When an Android app is terminated, your react-native Javascript app no longer exists.  That's what [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode) is for.

> I thought when the background-task is running, also the onLocation

No.  Your React Native UI lives inside an Android `Activity`.  When an app is terminated, the Android `Activity` is terminated and so too is your RN App.  Only the plugin's Android service remains running.  See [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode).

**Comment by 599markus** [comment]
Hi @christocracy 

Thanks for your help!

I've got the HeadlessTask set up and I can see in the log how the task starts after I terminate my app.
When I put a GPX file in the emulator to simulate a move, I see how the event 'location' is triggered.

Unfortunately, I have no idea how I get connected to GeoFencing ...
Perhaps you have an example for me, or something, where I can read how this is done?
With that you would help me a lot

**Comment by christocracy** [comment]
>Unfortunately, I have no idea how I get connected to GeoFencing ...

- Start monitoring geofences with [addGeofence](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#addgeofence)
- Listen to geofence events with [onGeofence](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#ongeofence)

**Comment by 599markus** [comment]
Hi @christocracy again ... 

Thanks for the two links, they helped me a lot!
But now I have a new problem and I do not really know ...
Start the HeadlessTask and evaluate the motion now works pretty well, so I get my data, which I need.
I would like to display this data via PushNotification, but that does not work.
(PushNotification works in the project, if I open the app and use it normally)
Do you have an example where something is done that I can watch?

**Comment by christocracy** [comment]
>I would like to display this data via PushNotification, but that does not work.

That's between you and the Push plugin you're using.
