### ISSUE TITLE
BackgroundGeolocation.addGeofence - promise issue

### ISSUE THREAD

**Issue by vovkind** [transistorsoft/react-native-background-geolocation#774]
## Your Environment
* Plugin version: 3.0.7
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Samsung A5 2017
* React Native version (`react-native -v`): 0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
      config = {
        //Geolocation Options
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: DISTANCE_WATCH,
        stopOnStationary: false,
        useSignificantChangesOnly: false,
        //[Geolocation] Android Options
        foregroundService: true,
        allowIdenticalLocations: false, //true in prev DD
        //Application Options
        stopOnTerminate: true, // Set false to continue tracking after user terminates the app.
        startOnBoot: false,
        //[Application] iOS Options
        preventSuspend: true,
        //HTTP & Persistence Options
        autoSync: false,
        //[Activity Recognition] iOS Options
        disableMotionActivityUpdates: true,
        debug: false,
        // prevent from stopping location when on stationary state
        stopOnStillActivity: false,
        disableStopDetection: true,
        pausesLocationUpdatesAutomatically: false,
        reset: true
      };
```

## Expected Behavior
On adding a new geofence in the following way, we expect to get success/failure promise returned:
    BackgroundGeolocation.addGeofence({
      identifier: identifier,
      radius: 200,
      latitude: parseFloat(lat),
      longitude: parseFloat(lng),
      notifyOnEntry: true,
      notifyOnExit: true,
    }).then(() => {
      **Log.info(`GeoFence - ${identifier} registered`);**
    }).catch((error) => {
      **Log.warn(`GeoFence - register ${identifier} failed`, error);**
    });

Please note, the issue
1) more appears when we run the debug version of our application.
2) appears when the users located WITHIN the geofence. The plugin initiation and sdk switch on happens within the geofence.

## Actual Behavior
No success/failure promise returned.

## Steps to Reproduce
Add a geofence.

## Context

The background - upon login, the user will be registered as located within the store. The store actually is the geofence we create.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Show me the native Android logs when you execute this.

```
$ adb logcat -s TSLocationManager
```

**Comment by vovkind** [comment]
Not relevant anymore.

**Comment by christocracy** [comment]
If it’s not relevant anymore, why don’t you signal this by closing the issue you opened?
