### ISSUE TITLE
Add Info to Location data & Manipulate Send Action

### ISSUE THREAD

**Issue by ramandika** [transistorsoft/react-native-background-geolocation#776]
## Your Environment
* Plugin version: 3.07
* Platform: iOS
* OS version: any
* Device manufacturer / model: any

## Expected Behavior

1. I want to modify local SQLite DB schema by adding some column, so I need a function hook right before a location data is saved temporarily in local SQLite DB. For example, for each location data, I need to know whether the device is online or not when getting that location. I plan to send those additional data to my backend server.
2. I need to be able to choose which location data to be deleted from local DB and which data to be resent based on some conditional column requirement.

## Actual Behavior
1. I can manipulate the extras property through setConfig function to setup my additional params and after that call BackgroundGeolocation.start() function

## Context
My backend server doesn't save those incoming location data directly, so it needs some time to tell the client whether their location data has been successfully saved or not (client will know by requesting next API, API will return successfully saved location id). Those ids will be used to delete all local location data, and the device should try to resend all unsuccessfully saved local location data.

</details>

**Comment by christocracy** [comment]
>I want to modify local SQLite DB schema by adding some column

You can't do this.  The plugin's SQLite database is private.

>so I need a function hook right before a location data is saved temporarily in local SQLite DB

Not possible.

**Comment by ramandika** [comment]
I try to use setConfig for adding extras whenever right before I call BackgroundGeolocation.start(). The extras are added to location object when the app is on the foreground but when the app starts to run in the background the config settings get back to the config I pass to BackgroundGeolocation.ready() method. Any solution for this?
