### ISSUE TITLE
Promise-based async methods

### ISSUE THREAD

**Issue by nevir** [transistorsoft/react-native-background-geolocation#78]
Feature request! (not pressing)

It'd be handy to have a promise-based interface to all of the async methods exposed by this module.  I'm finding myself wrapping them in promises as is

RN's recent [`RCTPromiseResolveBlock` and `RCTPromiseRejectBlock`](https://github.com/facebook/react-native/blob/master/docs/NativeModulesIOS.md#promises) make this pretty easy from the native side

**Comment by christocracy** [comment]
Yup

On Wednesday, April 27, 2016, Ian MacLeod <notifications@github.com> wrote:

> Feature request! (not pressing)
>
> It'd be handy to have a promise-based interface to all of the async
> methods exposed by this module. RN's recent RCTPromiseResolveBlock and
> RCTPromiseRejectBlock [
> https://github.com/facebook/react-native/blob/master/docs/NativeModulesIOS.md#promises]
> make this pretty easy from the native side
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/78>
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
This is done.
