### ISSUE TITLE
Listeners (onHeartbeat) not being called in release mode

### ISSUE THREAD

**Issue by kariscomp** [transistorsoft/react-native-background-geolocation#780]
## Your Environment
* Plugin version: 3.0.9
* Platform: Android
* OS version: Android 8.1
* Device manufacturer / model: Itel P33
* React Native version (`react-native -v`): 0.59.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        heartbeatInterval: 90,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 50,
        stopTimeout: 5,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_DEBUG,
        url: 'http://192.168.43.58:3000/driver-location/' + this.props.userId,
        batchSync: true,
        autoSync: true,
        autoSyncThreshold: 5,
        maxBatchSize: 5,
        maxDaysToPersist: 2,
        maxRecordsToPersist: 100,
        locationsOrderDirection: 'DESC',
        stopOnTerminate: true,
        startOnBoot: true,
        foregroundService: true,
        forceReloadOnBoot: true,
        notification: {
          title: 'Name',
          channelName: 'Name'
        },
        extras: {
          deviceId: this.props.gqlId,
        },
        headers: {
          'Authorization': 'Bearer ' + this.props.currentJwtToken
        },
        disableLocationAuthorizationAlert: true,
}
```

## Expected Behavior
When running the app in debug mode, heartbeat events are fired as required. However, when the app is in release, we no longer receive heartbeat events.

## Actual Behavior
- No onHeartbeat event
- No onLocation event
- Occasionally the error below is thrown

## Steps to Reproduce

1. Install plugin, set up listeners for onHeartbeat and configure a heartbeatInterval
2. Set minifyEnabled to true on build.gradle
3. Bundle app into release mode
4. Heartbeat events are not received

## Context
Receive heartbeat events from the plugin every 90 seconds.
Have enabled ProGuard with minify enabled for release apps
Have configured license for release mode

## Debug logs

<details><summary>Logs in Debug Mode</summary>
07-24 11:47:12.076  4555  5000 I TSLocationManager:   🎾  Start motion-activity updates
07-24 11:47:12.117  4555  5000 I TSLocationManager: [c.t.l.g.TSGeofenceManager start] 
07-24 11:47:12.117  4555  5000 I TSLocationManager:   🎾  Start monitoring geofences
07-24 11:47:12.273  4555  5000 D TSLocationManager: [c.t.l.http.HttpService startMonitor
ingConnectivityChanges] 
07-24 11:47:12.273  4555  5000 D TSLocationManager:   🎾  Start monitoring connectivity c
hanges
07-24 11:47:12.375  4555  4669 D TSLocationManager: [c.t.l.http.HttpService a] 
07-24 11:47:12.375  4555  4669 D TSLocationManager: ╔═════════════════════════════════════════════
07-24 11:47:12.375  4555  4669 D TSLocationManager: ║ 📶  Connectivity change: connected? true
07-24 11:47:12.375  4555  4669 D TSLocationManager: ╠═════════════════════════════════════════════
07-24 11:47:12.393  4555  5000 D TSLocationManager: [c.t.locationmanager.device.a c] 
07-24 11:47:12.393  4555  5000 D TSLocationManager:   🎾  Start monitoring powersave changes
07-24 11:47:12.490  4555  4669 I TSLocationManager: [c.t.l.http.HttpService flush] 
07-24 11:47:12.490  4555  4669 I TSLocationManager: ╔═════════════════════════════════════════════
07-24 11:47:12.490  4555  4669 I TSLocationManager: ║ HTTP Service (count: 0)
07-24 11:47:12.490  4555  4669 I TSLocationManager: ╠═════════════════════════════════════════════
07-24 11:47:12.609  4555  5000 I TSLocationManager: [c.t.l.g.TSGeofenceManager stopMonitoringSignificantLocationChanges] 
07-24 11:47:12.609  4555  5000 I TSLocationManager:   🔴  Stop monitoring significant location changes
07-24 11:47:12.748  4555  5000 I TSLocationManager: [c.t.l.service.HeartbeatService b] 
07-24 11:47:12.748  4555  5000 I TSLocationManager:   🎾  Start heartbeat (90s)
07-24 11:47:12.874  4555  5000 D TSLocationManager: [c.t.locationmanager.util.b a] 
07-24 11:47:12.874  4555  5000 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
07-24 11:47:12.995  4555  5000 I TSLocationManager: [c.t.l.service.TrackingService a] 
07-24 11:47:12.995  4555  5000 I TSLocationManager:   🔵  setPace: false → false
07-24 11:47:13.746  4555  4555 I TSLocationManager: [c.t.l.s.LocationRequestService b] 
07-24 11:47:13.746  4555  4555 I TSLocationManager:   ℹ️  Location availability: true
07-24 11:47:13.882  4555  4555 D TSLocationManager: [c.t.l.s.ActivityRecognitionService a] 
07-24 11:47:13.882  4555  4555 D TSLocationManager:   🚘 ️DetectedActivity [type=STILL, confidence=100]
07-24 11:47:14.072  4555  4555 D TSLocationManager: [c.t.l.s.ActivityRecognitionService onDestroy] 
07-24 11:47:14.072  4555  4555 D TSLocationManager:   🔴  ActivityRecognitionService destroyed
07-24 11:47:14.410  4555  4555 I TSLocationManager: [c.t.l.s.LocationRequestService a] 
07-24 11:47:14.410  4555  4555 I TSLocationManager: ╔═════════════════════════════════════════════
07-24 11:47:14.410  4555  4555 I TSLocationManager: ║ motionchange LocationResult: 1
07-24 11:47:14.410  4555  4555 I TSLocationManager: ╠═════════════════════════════════════════════
07-24 11:47:14.410  4555  4555 I TSLocationManager: ╟─ 📍  Location[fused -4.325181,15.272362 hAcc=16 et=+1d0h6m45s328ms vAcc=??? sAcc=??? bAcc=??? {Bundle[{}]}], age: 1447ms, time: 1563965232915
07-24 11:47:14.467  4555  4555 I TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
07-24 11:47:14.467  4555  4555 I TSLocationManager:   🔵  Acquired motionchange position, isMoving: false
07-24 11:47:14.507  4555  4555 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 16.0
07-24 11:47:14.894  4555  4555 I TSLocationManager: [c.t.l.s.ActivityRecognitionService a] 
07-24 11:47:14.894  4555  4555 I TSLocationManager:   🎾  Start motion-activity updates
07-24 11:47:14.909  4555  4555 D TSLocationManager: [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion] 
07-24 11:47:14.909  4555  4555 D TSLocationManager:   🎾  Start monitoring stationary region (radius: 150.0 meters)
07-24 11:47:14.969  4555  5000 I TSLocationManager: [c.t.l.data.sqlite.b persist] 
07-24 11:47:14.969  4555  5000 I TSLocationManager:   ✅  INSERT: 873803e4-46ab-4921-ade9-46ce702565d9
07-24 11:47:15.082  4555  4555 I TSLocationManager: [c.t.l.service.TrackingService g] 
07-24 11:47:15.082  4555  4555 I TSLocationManager: ╔═════════════════════════════════════════════
07-24 11:47:15.082  4555  4555 I TSLocationManager: ║ TrackingService motionchange: false
07-24 11:47:15.082  4555  4555 I TSLocationManager: ╠═════════════════════════════════════════════
07-24 11:47:15.255  4555  5000 D TSLocationManager: [c.t.l.data.sqlite.b a] 
07-24 11:47:15.255  4555  5000 D TSLocationManager:   ℹ️  SHRINK: 100
07-24 11:47:15.268  4555  4555 D TSLocationManager: [c.t.l.service.TrackingService onDestroy] 
07-24 11:47:15.268  4555  4555 D TSLocationManager:   🔴  TrackingService destroyed
07-24 11:47:15.365  4555  4555 D TSLocationManager: [c.t.l.s.ActivityRecognitionService a] 
07-24 11:47:15.365  4555  4555 D TSLocationManager:   🚘 ️DetectedActivity [type=STILL, confidence=100]
07-24 11:47:15.408  4555  5000 I TSLocationManager: [c.t.l.http.HttpService flush] 
07-24 11:47:15.408  4555  5000 I TSLocationManager: ╔═════════════════════════════════════════════
07-24 11:47:15.408  4555  5000 I TSLocationManager: ║ HTTP Service (count: 1)
07-24 11:47:15.408  4555  5000 I TSLocationManager: ╠═════════════════════════════════════════════
07-24 11:47:15.515  4555  4555 D TSLocationManager: [c.t.l.s.ActivityRecognitionService onDestroy] 
07-24 11:47:15.515  4555  4555 D TSLocationManager:   🔴  ActivityRecognitionService destroyed
07-24 11:47:15.643  4555  4555 I TSLocationManager: [c.t.l.u.BackgroundTaskManager onStartJob] ⏳ startBackgroundTask: 1
07-24 11:47:15.710  4555  4555 D TSLocationManager: [c.t.l.data.sqlite.b allWithLocking] 
07-24 11:47:15.710  4555  4555 D TSLocationManager:   ✅  Locked 1 records
07-24 11:47:15.731  4555  4555 I TSLocationManager: [c.t.l.http.HttpService a] 
07-24 11:47:15.731  4555  4555 I TSLocationManager:   🔵  HTTP POST batch (1)
07-24 11:47:23.815  4555  5039 I TSLocationManager: [c.t.l.http.HttpService$b onResponse] 
07-24 11:47:23.815  4555  5039 I TSLocationManager:   🔵  Response: 201
07-24 11:47:23.862  4555  5039 D TSLocationManager: [c.t.l.data.sqlite.b destroyAll] 
07-24 11:47:23.862  4555  5039 D TSLocationManager:   ✅  DELETED: (1)
07-24 11:47:23.941  4555  5039 D TSLocationManager: [c.t.l.data.sqlite.b allWithLocking] 
07-24 11:47:23.941  4555  5039 D TSLocationManager:   ✅  Locked 0 records
07-24 11:47:24.014  4555  5039 I TSLocationManager: [c.t.l.u.BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 1
07-24 11:47:24.096  4555  4555 D TSLocationManager: [c.t.l.s.BackgroundTaskService onDestroy] 
07-24 11:48:15.901  4555  4746 D TSLocationManager: [c.t.l.a.BackgroundGeolocation c] 
07-24 11:48:15.901  4555  4746 D TSLocationManager:   🔴  Cleared callbacks
07-24 11:48:26.174  4555  5138 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config, dirty: [debug, extras, headers]
07-24 11:48:26.220  4555  5138 D TSLocationManager: [c.t.locationmanager.util.b a] 
07-24 11:48:26.220  4555  5138 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
07-24 11:48:26.222  4555  5174 I TSLocationManager: [c.t.l.http.HttpService flush] 
07-24 11:48:26.222  4555  5174 I TSLocationManager: ╔═════════════════════════════════════════════
07-24 11:48:26.222  4555  5174 I TSLocationManager: ║ HTTP Service (count: 0)
07-24 11:48:26.222  4555  5174 I TSLocationManager: ╠═════════════════════════════════════════════
07-24 11:48:26.637  4555  4555 I TSLocationManager: [c.t.l.s.LocationRequestService b] 
07-24 11:48:26.637  4555  4555 I TSLocationManager:   ℹ️  Location availability: true
07-24 11:48:28.280  4555  4555 I TSLocationManager: [c.t.l.s.LocationRequestService a] 
07-24 11:48:28.280  4555  4555 I TSLocationManager: ╔═════════════════════════════════════════════
07-24 11:48:28.280  4555  4555 I TSLocationManager: ║ getCurrentPosition LocationResult: 2
07-24 11:48:28.280  4555  4555 I TSLocationManager: ╠═════════════════════════════════════════════
07-24 11:48:28.280  4555  4555 I TSLocationManager: ╟─ 📍  Location[fused -4.325181,15.272362 hAcc=16 et=+1d0h7m59s769ms vAcc=??? sAcc=??? bAcc=??? {Bundle[{}]}], age: 919ms, time: 1563965307357
07-24 11:48:28.448  4555  4555 I TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
07-24 11:48:28.448  4555  4555 I TSLocationManager:   🔵  Acquired current position
07-24 11:48:28.462  4555  4555 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 16.0
07-24 11:48:47.305  4555  4555 D TSLocationManager: [c.t.l.service.HeartbeatService onStartCommand] ❤️
07-24 11:50:12.963  4555  4555 D TSLocationManager: [c.t.l.service.HeartbeatService onStartCommand] ❤️
07-24 11:51:43.698  4555  4555 D TSLocationManager: [c.t.l.service.HeartbeatService onStartCommand] ❤️
07-24 11:53:14.351  4555  4555 D TSLocationManager: [c.t.l.service.HeartbeatService onStartCommand] ❤️
07-24 11:54:45.049  4555  4555 D TSLocationManager: [c.t.l.service.HeartbeatService onStartCommand]
</details>
<details><summary>Logs in Release Mode</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
7-24 11:26:31.355  2410  2493 E TSLocationManager:   ‼️  Cannot set private final  field java.util.List com.transistorsoft.locationmanager.adapter.TSConfig$Builder.a of class java.lang.Class<com.transistorsoft.locationmanager.adapter.TSConfig$Builder>java.lang.IllegalAccessException: Cannot set private final  field java.util.List com.transistorsoft.locationmanager.adapter.TSConfig$Builder.a of class java.lang.Class<com.transistorsoft.locationmanager.adapter.TSConfig$Builder>
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at java.lang.reflect.Field.set(Native Method)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.<init>(Unknown Source:168)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:199)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:61)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:87)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocation.createNativeModules(RNBackgroundGeolocation.java:19)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
07-24 11:26:31.355  2410  2493 E TSLocationManager:     at java.lang.Thread.run(Thread.java:764)
07-24 11:26:43.187  2410  2674 I TSLocationManager: - Enable: false → true, trackingMode: 1
07-24 11:34:23.163  3255  3700 I TSLocationManager: - Enable: false → true, trackingMode: 1
```

</details>

**Comment by kariscomp** [comment]
Update here, I managed to resolve this issue by setting `minifyEnabled` to `false` and this resolved my issue.

**Comment by christocracy** [comment]
You probably missed the required Proguard config in the Android Setup docs.

**Comment by kariscomp** [comment]
Yes I did! Closing and thank you!
