### ISSUE TITLE
locationTemplate is not changed

### ISSUE THREAD

**Issue by panda919** [transistorsoft/react-native-background-geolocation#782]
I changed locationTemplate in config.
But, old locationTemplate value is keeped.
I can not change locationTemplate.
What is issue?

**Comment by christocracy** [comment]
`BackgroundGeolocation.getCount()`

You will find you have old locations still persisted in the plugin's database.  Changing the locationTemplate does not modify already persisted locations.  Your server is returning a non-200 http response and the plugin keeps trying to post these.

**Comment by panda919** [comment]
then, How can reset  persisted location template value in the plugin's database?

**Comment by christocracy** [comment]
If the plugin has a method to fetch the *count*, there must be a method to *destroy* records as well, right?  Search the [Background Geolocation API](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html) for the word "destroy"

**Comment by panda919** [comment]
> If the plugin has a method to fetch the _count_, there must be a method to _destroy_ records as well, right? Search the [Background Geolocation API](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html) for the word "destroy"

Thanks
