### ISSUE TITLE
Doc fix: manual steps in android installation with rn >= 0.60.0

### ISSUE THREAD

**Issue by giacomocerquone** [transistorsoft/react-native-background-geolocation#787]
This is not a problem, but a doc fix that should be applied in my opinion.
I'm on rn 0.60.0 and yet, following the **reccomended** installation guide gradle wasn't able to find the packages.
This is because there was no mention about inserting the maven repos in build.gradle (and this is mentioned in the manual installation).

If some manual operation is needed because the autolinking functionality won't do it, it should be mentioned in the reccomended guide.

**Comment by christocracy** [comment]
React-Native link automatically writes the required maven repos.

**Comment by giacomocerquone** [comment]
very well, it didn't work then, so I'll compose a template in the next comment of this issue about my env info

**Comment by giacomocerquone** [comment]
And just for info, react-native link is not requested anymore, actually if you launch "react-native link" on version 0.60.4 it will throw an error that we must not launch the link command anymore

**Comment by christocracy** [comment]
It’s not throwing an error, it’s a warning

**Comment by giacomocerquone** [comment]
<img width="1076" alt="Schermata 2019-07-29 alle 20 32 01" src="https://user-images.githubusercontent.com/9303791/62072951-fa16e900-b23f-11e9-9a41-851933002a61.png">

**Comment by christocracy** [comment]
I’m fully aware of this.  The plugin’s link script still runs.

**Comment by giacomocerquone** [comment]
Ok I can close the issue, right now reproducing this error I discovered what happened.

For some reason I don't remember I launched react-native link (and then unlink as advised by the lib) and it removed the two maven repos (happened now too).

So sorry.

I want to take a moment to congratulate with you, this is, by far, the best library I've ever saw.
Thank you very much for your work.

**Comment by christocracy** [comment]
The plugin’s link-script will eventually be phased-out once I learn more about the new auto-linking in 0.60
