### ISSUE TITLE
Documentation clarification: desiredAccuracy / LocationAccuracy

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#788]
# iOS

In the documentation for [desiredAccuracy](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#desiredaccuracy), I see documentation of six accuracy values. It corresponds to the following stanza from `src/index.js`:

```
const DESIRED_ACCURACY_NAVIGATION = -2;
const DESIRED_ACCURACY_HIGH       = -1;
const DESIRED_ACCURACY_MEDIUM     = 10;
const DESIRED_ACCURACY_LOW        = 100;
const DESIRED_ACCURACY_VERY_LOW   = 1000;
const DESIRED_ACCURACY_LOWEST     = 3000;
```

This is all well and good for iOS. iOS is fine.

# Android

What about android?

Instead of those six values, Android has [four](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.html#PRIORITY_BALANCED_POWER_ACCURACY): PRIORITY_BALANCED_POWER_ACCURACY,  PRIORITY_HIGH_ACCURACY, PRIORITY_LOW_POWER and PRIORITY_NO_POWER.

Question 1. 
How do I configure the plugin to set these accuracy values? Is there a mapping from iOS's `DESIRED_ACCURACY_...` to android's `PRIORITY_...`? Or something?

Question 2.
If I look in the plugin's logs on an Android phone, I see:

```
    ...
    "desiredAccuracy": 0,
    ...
```

What accuracy is value `0`?

**Comment by christocracy** [comment]
Don't concern yourself with the specific value you see.  Just use the CONSTANTS.

The plugin automatically decodes the required value for each platform.

**Comment by christocracy** [comment]
```java
public Integer translateDesiredAccuracy(Integer accuracy) {
        TSLog.logger.debug("translateDesiredAccuracy (" + useCLLocationAccuracy + "): " + accuracy);
        if (!useCLLocationAccuracy) { return accuracy; }
        switch (accuracy) {
            case 0:
            case -1:
            case -2:
                accuracy = LocationRequest.PRIORITY_HIGH_ACCURACY;
                break;
            case 10:
                accuracy = LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY;
                break;
            case 100:
                accuracy = LocationRequest.PRIORITY_LOW_POWER;
                break;
            case 1000:
            case 3000:
                accuracy = LocationRequest.PRIORITY_NO_POWER;
                break;
            default:
                accuracy = LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY;
        }
        return accuracy;
    }
```

**Comment by bengtan** [comment]
Ah, that's the mapping. Thanks.
