### ISSUE TITLE
Foreground notification turned on/off muliple times

### ISSUE THREAD

**Issue by mailyokesh** [transistorsoft/react-native-background-geolocation#791]
## Your Environment
* Plugin version: 3.0.9
* Platform: Android
* OS version: 9
* Device manufacturer / model: Google Pixel 3, Pixel 2
* react-native-cli: 2.0.1
   react-native: 0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onLocation(this.onLocation, this.onError);

        // This handler fires when movement states changes (stationary->moving; moving->stationary)
        BackgroundGeolocation.onMotionChange(this.onMotionChange);

        // This event fires when a change in motion activity is detected
        BackgroundGeolocation.onActivityChange(this.onActivityChange);

        // This event fires when the user toggles location-services authorization
        BackgroundGeolocation.onProviderChange(this.onProviderChange);

        BackgroundGeolocation.onHttp(this.onHttp.bind(this));

        let success = await BackgroundGeolocation.destroyLocations();

        ////
        // 2.  Execute #ready method (required)
        //
        BackgroundGeolocation.ready(
            {
                // Geolocation Config
                enableHeadless: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 500,
                // Activity Recognition
                // useSignificantChangesOnly: true,
                stopTimeout: 1,
                // Application config
                debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
                logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
                stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
                startOnBoot: true, // <-- Auto start tracking when device is powered-up.
                batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                autoSync: true // <-- [Default: true] Set true to sync each location to server as it arrives.
            },
            state => {
                console.log(
                    "- BackgroundGeolocation is configured and ready: ",
                    state.enabled
                );

                if (!state.enabled) {
                    ////
                    // 3. Start tracking!
                    //
                    BackgroundGeolocation.start(function() {
                        console.log("- Start success");
                    });
                }

                // this.setupNotificationPreference();
            }
        );
```

## Expected Behavior
Expected to have the location tracking foreground notification always on during motion and when location is being reported

## Actual Behavior
Foreground notification turned on and off multiple times as if its in a loop. And the phone became hot and battery seemed to drain faster

## Steps to Reproduce
When we released this app version with this location plugin. 3 of our tester experienced this where the forground notification seemed to go on a loop. Whole phone heated up. I see a similar issue being mentioned as fixed in your release notes https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#304---2019-05-08

## Debug logs
Since this is with a remote tester i dont have logs

**Comment by christocracy** [comment]
This is normal.  [Read this](https://link.medium.com/X376IKWBKY)

**Comment by mailyokesh** [comment]
@christocracy forground service is being on a loop causing battery drain. Please read the issue, issue is not about foreground service notification coming up. But lets say in a minute the notification comes up and hide 30 times and this being on a loop.

**Comment by mailyokesh** [comment]
@christocracy can you please reopen this issue. I see this happening consistently in Google Pixel and Sony xPeria phone.

**Comment by nos-joel** [comment]
This plugin is spectacular and I really like it. The documentation is abundant and readable. I read your Medium article(https://medium.com/@transistorsoft/background-geolocation-v3-be8665b06c7), but what I still don't understand why does it require the persistent notification. I know that it is only when foreground-service is triggered. I oftenly use Life360, but would have uninstalled it if a persistent notification is shown all the time.

Other than that, I would say that this is a really good product.

**Comment by mailyokesh** [comment]
The issue i faced is not that foreground notification is showing, but continuously for 5 mins it will get toggled in the notification bar.

**Comment by christocracy** [comment]
First of all, the Android OS *requires* that foreground-services *must* show a persistent notification.

In order to receive constant location updates in background/terminated states, a foreground service is required.

If you don’t want to see a persistent notification, configure `useSignificantChangesOnly: true`; however, you’ll only get a few location updates/hour in background.

If you want to aggressively track the device’s location in background, **the only way** is to accept that there’s a persistent notification.  There is no magical way around this.

**Comment by mailyokesh** [comment]
Please check these videos. Where the notification bar is constantly changing. This is caused by enabling the location service with our app. Same doesnt happen with useSignificantChangesOnly: true
https://photos.google.com/share/AF1QipP9dR7wvqs07NrK3RcTMmTNy1IyAS9GHRMJAEjrz9QU9GLOaybB1zrpGEozE_Ia7Q?key=VlR4eEJWNVVKUU42VGZuYlYzRGYtcGU4MldGN0xB

**Comment by mailyokesh** [comment]
Issue is very similar to whats mentioned in this change log https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#304---2019-05-08 

[3.0.4] - 2019-05-08
[Fixed] iOS: changing pauseslocationUpdatesAutomatically was not being applied.
[Changed] reset parameter provided to #ready has now been default to true. This causes too many support issues for people using the plugin the first time.
**### [Fixed] Android threading issue where 2 distinct SingleLocationRequest were issued the same id. This could result in the foreground service quickly starting/stopping until locationTimeout expired.**

**Comment by christocracy** [comment]
Logs

**Comment by mailyokesh** [comment]
These are from release version with our testers. I donot have logs. This is only happening in certain version of android. I couldnt reproduce this in my pixel or motorolla phone. The fact that its mentioned in your release notes is what prompted me to ask the question here.

**Comment by christocracy** [comment]
Send a build to your testers configured with LOG_LEVEL_VERBOSE and add a UI button that executes #emailLog.

**Comment by mailyokesh** [comment]
Nice. Didn’t realize you have an option to email logs. Thanks. I can do the same to retrieve logs for this issue as well as the iOS idle issue I reported. Thanks for replying.

**Comment by mailyokesh** [comment]
@christocracy  Here are the logs when the foreground notification quickly toggled on and off. I had "useSignificantChangesOnly": true with this build and the tester mentioned that he hasnt seen the toggling go on for 5 minutes like before when i didnt had the "useSignificantChangesOnly": true. Currently he has seen it 3 times when it toggled and then the notification went away. What i mean by toggling is the foreground notification coming up and disappearing in less than a second for 4 times. Which used to go on for 5 minutes without "useSignificantChangesOnly": true
[background-geolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/3457581/background-geolocation.log)
