### ISSUE TITLE
IOS Version of plugin reporting erroneous location when device is not moving

### ISSUE THREAD

**Issue by mailyokesh** [transistorsoft/react-native-background-geolocation#792]
## Your Environment
* Plugin version: 3.0.9
* Platform: iOS
* OS version: 12.4
* Device manufacturer / model: Apple 7, xS
* react-native-cli: 2.0.1
react-native: 0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onLocation(this.onLocation, this.onError);

        // This handler fires when movement states changes (stationary->moving; moving->stationary)
        BackgroundGeolocation.onMotionChange(this.onMotionChange);

        // This event fires when a change in motion activity is detected
        BackgroundGeolocation.onActivityChange(this.onActivityChange);

        // This event fires when the user toggles location-services authorization
        BackgroundGeolocation.onProviderChange(this.onProviderChange);

        BackgroundGeolocation.onHttp(this.onHttp.bind(this));

        let success = await BackgroundGeolocation.destroyLocations();

        ////
        // 2.  Execute #ready method (required)
        //
        BackgroundGeolocation.ready(
            {
                // Geolocation Config
                enableHeadless: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 500,
                // Activity Recognition
                // useSignificantChangesOnly: true,
                stopTimeout: 1,
                // Application config
                debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
                logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
                stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
                startOnBoot: true, // <-- Auto start tracking when device is powered-up.
                batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
httpRootProperty: ".",
                headers: {
                    // <-- Optional HTTP headers	
                    "Content-Type": "application/json",
                    "Manufacturer": DeviceInfo.getManufacturer(),
                    "Model": DeviceInfo.getModel(),
                    "OSVersion": DeviceInfo.getSystemVersion(),
                    "Tablet": DeviceInfo.isTablet(),
                    "AppVersion": DeviceInfo.getReadableVersion(),
                    "AppApiVersion": Config.APP_API_VERSION,
                },
                url: Config.REACT_APP_GRAPHQL_API_URI,
                locationTemplate:
                    '{ "operationName": "RecordUserLocation", "query": "mutation RecordUserLocation($input: UserLocationInput!) {recordUserLocation(input: $input)}", "variables": { "input": { "latitude": <%= latitude %>, "longitude": <%= longitude %> } } }'
                
            },
            state => {
                console.log(
                    "- BackgroundGeolocation is configured and ready: ",
                    state.enabled
                );

                if (!state.enabled) {
                    ////
                    // 3. Start tracking!
                    //
                    BackgroundGeolocation.start(function() {
                        console.log("- Start success");
                    });
                }

                // this.setupNotificationPreference();
            }
        );
```

## Expected Behavior
When the phone is not moving not expecting location updates.

## Actual Behavior
I get random location updates pointing to a location which is away from the current location. I logged this in my server. And every time the random location update is from the same point and the next update is where the phone is currently located. This is happening only in IOS am not seeing this in android. I tried multiple version of ios device iphone 7s, iphone xS and this behavior is consistent. I tried different networks tmobile, verizone as well. I tried using the plugin http location reporting service as well as manually reporting the update to my server and i could see that randomly when the phone is in idle these updates happen.

Could this be due to switch from wifi to mobile network towers? Why would this happen in ios but not in android. 

## Steps to Reproduce
Install the latest version of the plugin and report all location updates to custom server. 
randomly when phone is not moving you will get couple of location updates, 1 away from the place you are and immediately after that you will get the correct location update.

If i leave the phone at night and i will get this behavior 3 or 4 times. 

I dont use the plugin inbuilt geolocation due to our need. So when this erroneous reporting happens in our backend service login this will create issue where the app is reported to be outside a geolocation area and then immediately back in the area.

## Context
Trying to report location updates to my server.

## Debug logs
No logs as its from a release ios version

**Comment by christocracy** [comment]
When the plugin comes alive, the first thing it does is ask “where am I?”, then enters the stationary state.  Yes, your app will periodically be terminated / relaunched in the background.

Why doesn’t Android do this?  iOS and Android are completely different operating systems.  There is an Android version of the plugin written in Java and and iOS version written in Obj-c.  It’s essentially 2 plugins with a common JavaScript api.

**Comment by mailyokesh** [comment]
@christocracy the problem is the erroneous location reported. I can consistently see a erroneous location which the plugin reports to my background randomly when the device is stationary. 

during night
1. Sends a erroneous location update
2. Immediately followed by correct location

this keeps repeating while the device is stationary.  Works fine when the device is moving. 

This is the issue which seems to happen only in iOS and not in android.

**Comment by christocracy** [comment]
Define “erroneous” with data, logs and image

**Comment by mailyokesh** [comment]
Yes i can. Anything specific from log you are looking for? Currently this happens with a release version of IOS, i store all the recorded location in my db and i have a google maps page where i plot all the reported locations.

**Comment by christocracy** [comment]
Show me a map view showing an “erroneous” location relative to a “correct” location, in addition to the lat/lng/timestamp and corresponding logs from plugin

**Comment by mailyokesh** [comment]
sure will do. It takes time since its not always happening. Happening only when the device is in prolonged period of stationary state. I will collect these today and send it here.

**Comment by mailyokesh** [comment]
Here is a log from ios device which did what i mentioned in the description.
1. Installed app in ios device with location service on and put the phone on a desk.
2. Location service correctly reported the initial location
3. Randomly it made another location update few hours later which is outside where my phone is
4. One more location update which corresponded to correct location

Logs from the device with LOG_LEVEL_DEBUG, as well as plot from our custom google maps integration which plots the 3 points. 1st location where the phone is located, 2nd location away from where the phone is, 3rd location correct location where the phone is. 

[background-geolocation (2).log](https://github.com/transistorsoft/react-native-background-geolocation/files/3450085/background-geolocation.2.log)

![image](https://user-images.githubusercontent.com/12601748/62187415-e8603f00-b32e-11e9-9494-7d351fc57fa1.png)

**Comment by christocracy** [comment]
I asked for LOG_LEVEL_VERBOSE

**Comment by mailyokesh** [comment]
IOS device staying stationary.

**log file with LOG_LEVEL_VERBOSE**
[background-geolocation (5).log](https://github.com/transistorsoft/react-native-background-geolocation/files/3452552/background-geolocation.5.log)

**Corresponding record in our servers showing the reporting from the iOS app**
![image](https://user-images.githubusercontent.com/12601748/62224125-c80aa180-b37b-11e9-83a3-5f5b0d1e815c.png)

**Map plotting the reported location from the app**
![image](https://user-images.githubusercontent.com/12601748/62224171-deb0f880-b37b-11e9-84ea-67e230459da6.png)

**Configuration as per the log email:**
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 500;
    elasticityMultiplier = 1;
    enableTimestampMeta = 0;
    enabled = 1;
    extras =    {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =    {
        "Content-Type" = "application/json";
        "APP-ID" = "REDACTED";
        "AppApiVersion" = 13;
        "AppVersion" = "2.0.166";
        "MaintCode" = EMPTY;
        "Manufacturer" = Apple;
        "Model" = "iPhone XS";
        "OSVersion" = "13.0";
        "Tablet" = 0;
    };
    heartbeatInterval = 60;
    httpRootProperty = ".";
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 1;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =    {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "REDACTED";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = 0;
    params =    {
    };
    pausesLocationUpdatesAutomatically = 0;
    persistMode = 2;
    preventSuspend = 0;
    schedule =    (
    );
    schedulerEnabled = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 1;
    trackingMode = 1;
    url = "REDACTED";
    useSignificantChangesOnly = 1;
}

**Comment by christocracy** [comment]
```
2019-07-31 09:45:26.282 
📍<+42.03151748,-88.06964537> +/- 1204.95m (speed -1.00 mps / course -1.00) @ 7/31/19, 9:45:26 AM Central Daylight Time
```
The locations provided by the device have accuracy `1204.95`.  If you don't like those inaccurate locations, simply filter them out at the server.

**Comment by mailyokesh** [comment]
@christocracy really appreciate the quick response. Yes i can definitely do that. 

to clarify I have configured the plugin with  
desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 500,
                // Activity Recognition
                useSignificantChangesOnly: true,
understand that in this case the distanceFilter is ignored.

 even with that am not guarenteed to get location updates with only few meters apart. Is there any other configuration i can set to lets say only send location update lets say with a accuracy of less than 100m?

**Comment by christocracy** [comment]
`desiredAccuracy` doesn't apply when using `useSignificantChangesOnly: true`.

See [Apple docs](https://developer.apple.com/documentation/corelocation/getting_the_user_s_location/using_the_significant-change_location_service?language=objc)

**Comment by mailyokesh** [comment]
huh thats where the catch is. So with useSignificantChangesOnly: true,

i can turn off location updates background mode, but will still receive location updates even if the app is totally killed or in background?

![image](https://user-images.githubusercontent.com/12601748/62226029-25542200-b37f-11e9-9311-91437418a3ff.png)

**Comment by christocracy** [comment]
>i can turn off location updates background mode,

Yes.

>but will still receive location updates even if the app is totally killed or in background?

Yes.

**Comment by mailyokesh** [comment]
Thanks for your time. really appreciate the help.

**Comment by christocracy** [comment]
And if you're not providing the location attribute `accuracy` to your `locationTemplate`, you'll want to add that for filtering.  It also helps to provide `uuid` so you can match locations on the server to those in the logs.

```
2019-07-31 10:03:24.670 ✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 4D18A860-3A2C-43A0-8D9A-BF45D079CCA6

2019-07-31 10:03:24.675 ✅-[TSHttpService schedulePost:] LOCKED: 4D18A860-3A2C-43A0-8D9A-BF45D079CCA6

2019-07-31 10:03:25.014 🔵-[TSHttpService doPost:] HTTP Response: 200

2019-07-31 10:03:25.018 ✅-[TSHttpService post:error:] DESTROY: 4D18A860-3A2C-43A0-8D9A-BF45D079CCA6
```

**Comment by mailyokesh** [comment]
sure i will add accuracy, and uuid to my template.

with useSignificantChangesOnly: true is there any prevention i can do on the plugin side to not report immediately. Like only milliseconds apart. I saw reporting to my server where the updates are only milliseconds apart. I dont have logs for that currently but i can definitely get those. But are there any setting in plugin i can say dont provide me updates faster than 1 minutes apart. I see that you have that setting for android when in timer mode. just trying to see if there are any other setting which will prevent this.

**Comment by christocracy** [comment]
> is there any prevention i can do on the plugin side to not report immediately

No.  Filter on the server as desired.

**Comment by mailyokesh** [comment]
cool thanks
