### ISSUE TITLE
Documentation Clarification for useSignificantChangesOnly

### ISSUE THREAD

**Issue by mailyokesh** [transistorsoft/react-native-background-geolocation#793]
## Your Environment
* Plugin version: 3.0.9
* Platform: iOS and Android

## What is the link for the latest documentation
Am trying to follow https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html 

but this doesnt have any mention of useSignificantChangesOnly mentioned in https://medium.com/@transistorsoft/background-geolocation-v3-be8665b06c7 . So trying to find where is the latest documentation which has all the latest settings for the latest version of the plugin.

**Comment by christocracy** [comment]
Scroll down in API docs to “Config API”.  Click it
