### ISSUE TITLE
getting RTCEventEmmiter.h file not found

### ISSUE THREAD

**Issue by leonardogutierrezh** [transistorsoft/react-native-background-geolocation#797]
## Your Environment
* Plugin version: react-native-background-geolocation@3.0.9 and react-native-background-fetch@2.6.1
* Platform: iOS
* OS version: iOS 11
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): react-native: 0.60.4
* Plugin config

## Expected Behavior
App should run

## Actual Behavior
Getting .../node_modules/react-native-background-fetch/ios/RNBackgroundFetch/RNBackgroundFetch.h:17:9: 'React/RCTEventEmitter.h' file not found

## Steps to Reproduce

1. npm install react-native-background-geolocation --save
2. npm install react-native-background-fetch --save
2. react-native link react-native-background-geolocation
3. react-native link react-native-background-fetch
4. cd ios
5. pod install
6. Open Xcode workspace
7. Run project

## Context
I updated my project to react native 0.60.4 

## Debug logs
React/RCTEventEmitter.h' file not found
/Users/leonardogutierrez/Projects/front/tidbit-react/tidbit_react/node_modules/react-native-background-fetch/ios/RNBackgroundFetch/RNBackgroundFetch.m:9:9: In file included from /Users/leonardogutierrez/Projects/front/tidbit-react/tidbit_react/node_modules/react-native-background-fetch/ios/RNBackgroundFetch/RNBackgroundFetch.m:9:

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Don't ignore the issue template.
![](https://dl.dropbox.com/s/49kawrii83h5jxf/Screenshot%202019-08-06%2012.30.51.png?dl=1)

**Comment by leonardogutierrezh** [comment]
Fixed the issue template...

**Comment by christocracy** [comment]
Did you [see this](https://facebook.github.io/react-native/blog/)?  There's *much more* to upgrading your RN app for `0.60` than simply updating your `package.json`.

Have you seen what a freshly generate RN `Podfile` looks like?
```
$ react-native init Foo
$ cat ios/Podfile
```
```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Foo65' do
  # Pods for Foo65
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'Foo65Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'Foo65-tvOS' do
  # Pods for Foo65-tvOS

  target 'Foo65-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

**Comment by leonardogutierrezh** [comment]
Haven't see it, let me check

**Comment by leonardogutierrezh** [comment]
Hey I'm going to try a different approach for upgrading, you can close this issue thanks
