### ISSUE TITLE
License validation error

### ISSUE THREAD

**Issue by arnaud-albalat** [transistorsoft/react-native-background-geolocation#800]
## Your Environment
* Plugin version: 3.0.9
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung Galaxy S9
* React Native version (`react-native -v`): 0.59.8

## Expected Behavior
The plugin should not display an error message at app launch.

## Actual Behavior
At app launch, we see a message that says "License validation error" .

## Context

We purchased a license key approximately 10 months ago. We used it in a mobile app it was working good. We decided to refactor this mobile app, so we created a new fresh app, and we tried to use the same license key.

This app has the same package name as the previous one.

We put our license key in the Android manifest like that:

`<meta-data android:name="com.transistorsoft.locationmanager.license" android:value="XXX" />`

We linked react-native-background-geolocation and react-native-background-fetch successfully.

Here is an extract from our android/build.gradle :

```
buildscript {
    ext {
	googlePlayServicesLocationVersion = "17.0.0"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
}
```

Do you see where the problem could come from please?

**Comment by christocracy** [comment]
Are you using the new `3.x` key?

**Comment by arnaud-albalat** [comment]
You are right it was the wrong key. Unfortunately even after I changed it in the manifest I get the same error.
