### ISSUE TITLE
Question about counting moving time

### ISSUE THREAD

**Issue by kiddkevin00** [transistorsoft/react-native-background-geolocation#804]
Hi, what the best way to track the moving time. I am currently using `onMotionChange` listener to count the moving time but it seems really off compared to the Garmin watch. Can you advise?

**Comment by christocracy** [comment]
Read the API docs for Config.stopTimeout

**Comment by kiddkevin00** [comment]
Okay, can I set config.stopTimeout to be `0` or `0.05` (3 seconds) since I want to remove the stationary time and count all the moving time as much accurate as possible? In addition, is the `location.timestamp` reliable for counting the whole moving time?

**Comment by christocracy** [comment]
stopTimeout is an Int.  You can’t provide a Float.  Set it zero.

timestamp is time as measured by gps (when outdoors; gps only works outdoors)

**Comment by kiddkevin00** [comment]
will set it to zero for the stopTimeout.

For the timestamp, it is a outdoor running app. Can you elaborate a bit what measured by GPS means? Is it coming from the iPhone's Operating System time?

**Comment by christocracy** [comment]
Native APIs don't talk directly to GPS.  They receive timestamp through high-level APIs [`CLLocation.timetamp`](https://developer.apple.com/documentation/corelocation/cllocation/1423589-timestamp?language=objc) (iOS) and [`Location.getTime`](https://developer.android.com/reference/android/location/Location#getTime()) (Android).

**Comment by kiddkevin00** [comment]
Okay, but is it accurate? In other words, is it the exact timestamp when that event happens? Or is there a delay? The reason I am asking this is because I am using this timestamp to calculate the moving by subtracting it to the previous timestamp

**Comment by christocracy** [comment]
The plugin delivers the timestamp to you exactly as provided by the native location APIs.  Why shouldn't it be considered to be the exact time that location was received?

**Comment by kiddkevin00** [comment]
Because we are experiencing some calculation is off. I guess my question is, in your experience, is there any time noticeable time difference when the event being triggered and timestamp being recorded. The delay might be caused by asynchronous operation or others.

**Comment by christocracy** [comment]
>there any time noticeable time difference when the event being triggered and timestamp being recorded

No

> The delay might be caused by asynchronous operation or others

No.

**Comment by kiddkevin00** [comment]
Got it. For the location object gathered from `BackgroundGeolocation.onMotionChange(event => { event.location}`, is the `event.location.timestamp` the same as when the event being triggered even the GPS has been turned off due to stationary over stopTimeout or the distance is not large than DF?

**Comment by christocracy** [comment]
>the same as when the event being triggered even the GPS has been turned off due to stationary over stopTimeout or the distance is not large

You're over-thinking this.  the timestamp is the exact timestamp of the location provided.

**Comment by kiddkevin00** [comment]
I might be over-thinking this but help me understand this. As you mentioned "timestamp is the exact timestamp of the location provided", but if the GPS has been turned off, then does the location (provided by GPS) is still providing the correct timestamp?

**Comment by christocracy** [comment]
>but if the GPS has been turned of

Turned off by who or what?

**Comment by kiddkevin00** [comment]
Turn off by stationary over stopTimeout or the distance is not large than DF

**Comment by christocracy** [comment]
When the plugin requests its `onMotionChange` position, it turned on GPS to fetch that.  You're over-thinking this.
