### ISSUE TITLE
Crash: [TSHttpService postBatch:error:] + 6335064 (TSHttpService.m:253)

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#806]
Came across an iOS crash.

## Your Environment
* Plugin version: 3.0.9
* Platform: iOS
* OS version: 12.4
* Device manufacturer / model: iPhone8,2
* React Native version (`react-native -v`): 0.59.2
* Plugin config: See log below

## Expected Behavior

The plugin should continue location tracking in the background.

## Actual Behavior

The plugin stops location tracking in the background until the next time the app is opened again.

## Steps to Reproduce

Keep driving

## Context

We're seeing this crash about once a day. Some days there will be none. Some days there will be two or three.

The stack trace is:

```
Thread 8 name:  Dispatch queue: com.transistorsoft.TSLocationManager
Thread 8 Crashed:
0   tinyrobotStaging              	0x0000000102936a58 -[TSHttpService postBatch:error:] + 6335064 (TSHttpService.m:253)
1   tinyrobotStaging              	0x0000000102936a58 -[TSHttpService postBatch:error:] + 6335064 (TSHttpService.m:253)
2   tinyrobotStaging              	0x000000010293674c -[TSHttpService scheduleBatchPost:] + 6334284 (TSHttpService.m:223)
3   libdispatch.dylib             	0x0000000192ef4a38 _dispatch_call_block_and_release + 24
4   libdispatch.dylib             	0x0000000192ef57d4 _dispatch_client_callout + 16
5   libdispatch.dylib             	0x0000000192e9e324 _dispatch_lane_serial_drain$VARIANT$mp + 592
6   libdispatch.dylib             	0x0000000192e9ee40 _dispatch_lane_invoke$VARIANT$mp + 428
7   libdispatch.dylib             	0x0000000192ea74ac _dispatch_workloop_worker_thread + 596
8   libsystem_pthread.dylib       	0x00000001930d6114 _pthread_wqthread + 304
9   libsystem_pthread.dylib       	0x00000001930d8cd4 start_wqthread + 4
```

There is a gap in the plugin's debug log:

```
2019-08-19 12:59:32.124 ⚠️-[TSHttpService flush:error:] No network connection

2019-08-19 13:19:31.215 ℹ️-[TSLocationManager init] {
```

and notice point 4FCE5358-71FC-42C2-B508-3DD0047A8B59 appears only once in the log. The `_block_invoke INSERT` is missing.

When this happens, our test person is just driving, and occasionally stopping by the roadside and/or taking phone calls.

The stack trace suggests it's a crash during the POST-ing of the data to our server. Some sort of null pointer or memory leak?

Also, the following may or may not be relevant:

Our test person has an unusual network with a quirky characteristic. When the phone is in the middle of a voice call, mobile data is unavailable.

So things might be working fine and then ... suddenly there's a phone call. Our test person picks up the phone to talk, and then mobile data is disconnected. I dunno if iOS indicates this to the app or plugin or if it's just a silent network drop.

So is it possible that this quirk is causing the postBatch function to use an outdated pointer/object or something?

Happy to help testing/debugging if you want to try debug versions of the plugin. Or if you don't mind showing me the source code, I'd be happy to try debugging it myself.

## Debug logs

[tinyrobotStaging-2019-08-19-130438.ips.beta.crash.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/3518659/tinyrobotStaging-2019-08-19-130438.ips.beta.crash.txt)

[background-geolocation.excerpts.redacted.log.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/3518660/background-geolocation.excerpts.redacted.log.txt)

**Comment by christocracy** [comment]
Thanks, I’ll check it out.  

Tracking *will* resume again after a crash — after the the device moves ~500-1000 meters, the iOS significant-location-change (SLC) api will receive an event and iOS will relaunch the app in the background.
