### ISSUE TITLE
"AppDelegate.h" file not found error in RNBackgroundFetch+AppDelegate.m

### ISSUE THREAD

**Issue by NooruddinLakhani** [transistorsoft/react-native-background-geolocation#807]
## Your Environment
* Plugin version: *3.0.9*
* XCode version: **10.1 (10B61)**
* Platform: iOS or Android: **IOS**
* Device manufacturer / model: **Simulator Iphone 7**
* React Native version (`react-native -v`): **0.57.8**
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
Should not throw an error in XCode

## Actual Behavior
Getting error 'AppDelegate.h' file not found in RNBackgroundFetch+AppDelegate.m:10:

## Steps to Reproduce

1. Installed the plugin with manual linking
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Do not do this, it's meaningless the next time I commit.  It's especially meaningless for someone come here a year from now.

>Plugin version: Latest

Specify the *exact* version.  Edit your post.

**Comment by NooruddinLakhani** [comment]
@christocracy  Done

**Comment by christocracy** [comment]
Are you using Cocoapods with your app?

**Comment by NooruddinLakhani** [comment]
@christocracy  Yes

**Comment by christocracy** [comment]
Show me a screenshot of XCode with the following folders expanded.
![](https://dl.dropbox.com/s/0bjbe1yc8n4n89b/Screenshot%202019-08-20%2010.37.27.png?dl=1)

**Comment by christocracy** [comment]
I have the latest version of background-geolocation `3.2.0` successfully booted with an earlier version of the [SampleApp with react-native@0.59.2](https://github.com/transistorsoft/rn-background-geolocation-demo/tree/3.0.5)

```json
{
  "name": "BGGeolocation",
  "version": "3.0.5",  
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.2",
    "react-native-background-fetch": "^2.7.0",
    "react-native-background-geolocation": "^3.2.0"
  }
}
```

**Comment by NooruddinLakhani** [comment]
I have done manual linking

![screenshot](https://user-images.githubusercontent.com/13660652/63357400-cb91b700-c382-11e9-8776-a4cb76c536e0.png)

**Comment by christocracy** [comment]
>I have done manual linking

Why?  just use [`react-native link` instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-RNPM.md)

Delete everything you did in the manual installation.  Expand all your folders and search for any sign of the `RNBackgroundGeolocation` / `RNBackgroundFetch` (use `[Remove references`] when removing, not `[Delete]`.)

**Comment by christocracy** [comment]
And before attempting to integrate the plugin into your app, I *highly* suggest you first test the plugin in a fresh RN app `react-native init foo` (don't use the word "test" at all in your app name).

Use the `react-native link` instructions.

**Comment by NooruddinLakhani** [comment]
I have integrated successfully in code. I just want to ask how would  I get the user's current location when the application is killed. If an application is killed, that means no component is alive then how can I see the logs when an application is killed? Is there any background callbacks?

**Comment by christocracy** [comment]
Your question is off-topic.  Android and iOS operate completely different in the terminated context.  See docs `Config.stopOnTerminate`.  For Android, see Wiki [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode)

**Comment by RishavGoswami** [comment]
I was stuck on this error for two days straight, tried everything that's been told but nothing worked until I realize to check my Xcode version. Turned out, I had Xcode v10. Just make sure before doing any other things, you have **Xcode v11.5** and **above**. Then

```
cd ios
rm -rf Pods
rm -rf Podfile.lock
pod install
```
