### ISSUE TITLE
[android] Change request: Don't recreate TSLocationManager channel if exists

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#808]
## Your Environment

* Plugin version: 3.0.9
* Platform: android
* OS version: 8.0 and 9.0
* Device manufacturer / model: Various
* React Native version (`react-native -v`): 0.59.2
* Plugin config: N/A

## Context

On Android 8.0+, our app has an Android notification channel named TSLocationManager. This channel is created by the plugin.

We'd like to be able to rename/configure this channel.

I added code to Android's mainActivity.onCreate() to create a notification channel with the same id (and our desired configuration) and this successfully configured the channel.

However, a few app starts later, it had changed back to the name/configuration that the plugin sets.

I presume the plugin is repeatedly `notificationManager.createNotificationChannel()`-ing it?.

I'd like to request the following change please:

Instead of recreating the channel unconditionally, please change the plugin to check whether the channel exists. If it exists, don't recreate it.

**Comment by christocracy** [comment]
I can do that

**Comment by bengtan** [comment]
That would be great. Thank you very much.

**Comment by christocracy** [comment]
Show me the Config you’re using with your channel.

**Comment by bengtan** [comment]
Oh, I don't have that code handy anymore. I deleted it since it wasn't working due to the plugin overwriting it.

But I wanted to give the channel a different name. Maybe also add a description?

**Comment by bengtan** [comment]
As in ... all I was doing was create a channel object with our desired configuration, and then calling createNotificationChannel(). The code was called from the main activity's onCreate() function so it was being called at every app startup.

**Comment by christocracy** [comment]
See the docs for Config.notification, as well as the interface Notification.  You can configure the name.

**Comment by bengtan** [comment]
How about this ... I'll reconstruct my code and then post it to you. Then you can reproduce what I saw. But gimme a day or two to get around to it.

**Comment by christocracy** [comment]
I’m not surprised the plugin would override your channel.  I’m just interested in the specific channel options You were interested in, there are many.

If you’re only concerned with the name, you can easily configure that with the plugin’s Notification config.

**Comment by bengtan** [comment]
Oh, I didn't even see the `Config.notification` option.

Since that exists, it makes sense to use/extend it rather than have a separate thing.

I'd like to configure the channel name and importance. (Maybe channel description in the future, but it's in the future so I don't want to make a fuss about it now.)

The name can be configured via `Config.notification.channelName`. That's covered.

Re: The channel importance ... I think you're setting it to IMPORTANCE_LOW? I'd like to configure it to IMPORTANCE_MIN.

Suggestions:

1. Add a new `Config.notification.importance` field, or
2. Set the channel importance to `Config.notification.priority + 3`

**Comment by bengtan** [comment]
Oh, I didn't even see the `Config.notification` option.

Since that exists, it makes sense to use/extend it rather than have a separate thing.

I'd like to configure the channel name and importance. (Maybe channel description in the future, but it's in the future so I don't want to make a fuss about it now.)

The name can be configured via `Config.notification.channelName`. That's covered.

Re: The channel importance ... I think you're setting it to IMPORTANCE_LOW? I'd like to configure it to IMPORTANCE_MIN.

Ideas:

1. Add a new `Config.notification.importance` field and set channel importance to `Config.notification.importance`, or
2. Re-use/map `Config.notification.priority` and set the channel importance to `Config.notification.priority + 3`.

**Comment by christocracy** [comment]
So me the docs link that proves `Config.notification.priority + 3 = IMPORTANCE_*

**Comment by bengtan** [comment]
It's not a proof. It's just a shortcut instead of creating a map/table lookup.

https://developer.android.com/reference/androidx/core/app/NotificationCompat.html#PRIORITY_DEFAULT

PRIORITY_MIN = -2
PRIORITY_LOW = -1
PRIORITY_DEFAULT = 0
PRIORITY_HIGH = 1
PRIORITY_MAX = 2

https://developer.android.com/reference/android/app/NotificationManager.html#IMPORTANCE_DEFAULT

IMPORTANCE_MIN = 1
IMPORTANCE_LOW = 2
IMPORTANCE_DEFAULT = 3
IMPORTANCE_HIGH = 4
IMPORTANCE_MAX = 5

If you don't want to use '+3', I'm fine with that.

**Comment by christocracy** [comment]
[`NotificationChannel`](https://developer.android.com/reference/android/app/NotificationChannel) is highly configurable but implementing just a small handful of crucial ones should suffice for a long time.

My existing `Notification` class in the library is built to easily scale up.  It'll take more time to add the properties to the Typescript interfaces, document them, then sync the Cordova and Flutter.  But it's Android-only, so reduced complexity with no iOS involved.

So it'll be `Notification.channelImportance`.  Why don't you develop the Typescript API, including necessary  documentation in the same style using `Notification.channelName` as a template?

I'll re-use the existing [`const NOTIFICATION_PRIORITY`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/src/index.js#L36-L40) rather than adding confusion of an extra set of `BackgroundGeolocation.IMPORTANCE_*` and do the `+3` math in the native code.

**Comment by bengtan** [comment]
> It'll take more time to add the properties to the Typescript interfaces, document them, then sync the Cordova and Flutter. But it's Android-only, so reduced complexity with no iOS involved.

This is a wishlist request, so no rush. It will happen when it happens.

> Why don't you develop the Typescript API, including necessary documentation in the same style using Notification.channelName as a template?

Huh? I don't really understand this. You want me to submit a documentation PR?

**Comment by christocracy** [comment]
Yes.  Here's [`Notification.channelName`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/src/declarations/interfaces/Notification.d.ts#L446-L474).  Add your desired `channel*` attributes (including docs with `@example`) and submit a PR.

**Comment by christocracy** [comment]
And also use [`Notification.priority`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/src/declarations/interfaces/Notification.d.ts#L36-L58) as a documentation template, wth the table map fo the constants `Value` and `Description`.

**Comment by bengtan** [comment]
See #818
