### ISSUE TITLE
Tracking points jump far from device's real location

### ISSUE THREAD

**Issue by plell** [transistorsoft/react-native-background-geolocation#809]
![image](https://user-images.githubusercontent.com/30448242/63537179-09e5be00-c4ca-11e9-90a6-0c1456cbe55e.png)

![image](https://user-images.githubusercontent.com/30448242/63537204-166a1680-c4ca-11e9-9ef9-78e1e3638578.png)

As seen in the images above, tracking sometimes jumps to points far from the device's real position.

## Environment
* Plugin version: 3.0.9
* Platform: Android
* OS version: 9
* Device manufacturer / model: Google Pixel 3
* React Native version: 0.59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      stopOnTerminate: false,
      startOnBoot: true,
      forceReloadOnBoot:true,
      foregroundService:true,
      preventSuspend:true,
      allowIdenticalLocations:true,      
      elasticityMultiplier:2,
      heartbeatInterval:300,
    }
```

## Expected Behavior
Reported tracking points should not jump far away from the device's real location

## Actual Behavior
Sometimes tracking points jump far from the device's real location.

## Steps to Reproduce
1. Walk around town
2. Pass wifi hotspots (?)

**Comment by christocracy** [comment]
Glitches *do* happen depending upon the environment.  The plugin is only the messenger, delivering locations as reported by the native device api.

**Comment by christocracy** [comment]
You will likely find evidence of these glitches in the `location.accuracy`.  Your server can choose to filter these as desired.

**Comment by plell** [comment]
Appreciate it! Thanks
