### ISSUE TITLE
Detect Mock Locations

### ISSUE THREAD

**Issue by AlexandreMaistret** [transistorsoft/react-native-background-geolocation#815]
## Your Environment
* Plugin version: 3.0.1
* Platform: iOS or Android: Android
* OS version: 8.0.0
* Device manufacturer / model: SONY
* React Native version (`react-native -v`): 0.59.4

Is there a way to detect mock locations with this plugin ?

I know there is already an issue on this topic but it is quite old (https://github.com/transistorsoft/react-native-background-geolocation/issues/326) but I followed it and I don't have the `"mock": [Boolean]`.

In this topic, you said that the `"mock": [Boolean]` only appears when it is true, but it should appear since I am using a location simulator. 
Moreover, in this same topic kriptonhaz said he had the same problem with android 6.0.1

The app I am using to make mock locations is : https://play.google.com/store/apps/details?id=com.rosteam.gpsemulator&hl=fr

**Comment by AlexandreMaistret** [comment]
I am so sorry indeed you are right, I tried several times but I was targeting the wrong path on the getCurrentPosition() results.

My bad.

**Comment by anniewey** [comment]
Is this work on rooted devices too?

**Comment by christocracy** [comment]
I don't know.  Probably.
