### ISSUE TITLE
Get current location every 30 seconds

### ISSUE THREAD

**Issue by vuhoangha** [transistorsoft/react-native-background-geolocation#819]
## Your Environment
* Plugin version: 3.2.0
* Platform: iOS and Android
* OS version: all
* Device manufacturer / model: all
* React Native version (`react-native -v`): "0.59.9"
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      reset: true,

      // android options
      // locationUpdateInterval: 5000,
      // fastestLocationUpdateInterval: 1000,

      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      heartbeatInterval: 60,
      preventSuspend: true,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: true,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    }
```

## Actual Behavior
I am setting "heartbeatInterval: 60" because the minimum interval is `60` seconds. In addition, "onHeartbeat" function not fired if the app is backgrounded (app still run and I lock the screen of the phone)

## Expected Behavior
I hope I can get the current location every 30 seconds

**Comment by christocracy** [comment]
The minimum `heartbeatInterval` is `60`.  You will *not* get the location "every 30s" while the device is stationary.

As for iOS, the OS throttles heartbeat events while the device is unplugged from power with screen off.  As soon as user *moves* or lights up the screen / unlocks device, heartbeat resumes.  

On iOS, you can experience a heartbeat with screen off / unplugged from power by simply shaking the device.  No there, is no "solution" to this:  iOS is *very* strict about conserving energy.
