### ISSUE TITLE
Tracking stops after small stops during the trip, doesn't continue properly. Also sometimes stops in the middle of a trip

### ISSUE THREAD

**Issue by costas-basdekis** [transistorsoft/react-native-background-geolocation#820]
## Your Environment
* Plugin version: 3.0.9
* Platform: Android
* OS version: Android 8.0.0 / OxygenOS 5.0.4
* Device manufacturer / model: OnePlus 5 A5010 (`A5010_43_180223`)
* React Native version (`react-native -v`): `react-native-cli: 2.0.1` / `react-native: 0.59.8`
* Running debug version with `react-native run-android`

<details><summary>Plugin config</summary>

```javascript
{
  "reset": true,
  "desiredAccuracy": -2,
  "distanceFilter": 5,
  "disableElasticity": false,
  "stopOnStationary": false,
  "desiredOdometerAccuracy": 100,
  "useSignificantChangesOnly": false,
  "disableLocationAuthorizationAlert": true,
  "stationaryRadius": 5,
  "locationAuthorizationRequest": "Always",
  "fastestLocationUpdateInterval": 2500,
  "deferTime": 1,
  "allowIdenticalLocations": true,
  "stopTimeout": 15,
  "stopDetectionDelay": 10,
  "disableStopDetection": false,
  "method": "POST",
  "httpRootProperty": "points",
  "locationTemplate": "{\"point\": [<%= longitude %>, <%= latitude %>], \"datetime\": \"<%= timestamp %>\"}",
  "autoSync": true,
  "autoSyncThreshold": 0,
  "batchSync": true,
  "maxBatchSize": 30,
  "maxDaysToPersist": 30,
  "maxRecordsToPersist": -1,
  "locationsOrderDirection": "ASC",
  "stopOnTerminate": false,
  "startOnBoot": true,
  "heartbeatInterval": 60,
  "foregroundService": true,
  "enableHeadless": false,
  "notification": {
    "title": "Tracking your trip",
    "text": "Example is tracking your current trip"
  },
  "debug": false,
  "logLevel": 5,
  "logMaxDays": 1,
  "url": "https://example.com/v2/trips/track/",
  "headers": {
    "accept": "application/json",
    "Authorization": "JWT XYZ123"
  },
  "extras": {
    "environment": "production",
    "user_id": 123,
    "vehicle_id": 456,
    "imei": "abcd1234"
  }
}
```

</details>

## Expected Behavior
Tracking should start when a trip starts, not stop during a trip, and start again after a small stop

## Actual Behavior
Sometimes the trip doesn't start after a small stop (either at all, or with a delay), and sometimes the tracking stops during a trip

### Trip 1 (`A` -> `B` -> `A` -> `C` -> `D` -> `A`):
* Walk from location `A` to location `B`
* Walk back to location `A`
* Wait a few minutes
* Motorcycle trip from location `A` to location `C`
* Brief stop at location `C`
* Motorcycle trip from location `C` to location `D`
* Longer stop at location `D`
* Motorcycle trip from location `D` to location `A`

<details><summary>Trip 1 Logs Annotation</summary>

### Correct: `A` -> `B`, End of walking, waiting a few minutes before starting a motorcycle trip

```
09-02 15:54:18.492 DEBUG [TrackingService a] 
╔═════════════════════════════════════════════
║ TrackingService: LocationResult
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 51.505121,-0.100165 hAcc=3 et=+4d14h29m44s915ms alt=75.594482421875 vel=0.0 vAcc=4 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 23ms, time: 1567436060000

09-02 15:54:18.506 DEBUG [TSLocationManager onLocationResult] 
```

### Correct: `C` -> `D`, After a couple of minutes of waiting, started tracking when continued the motorcycle trip

```
  🎾  Start heartbeat (60s)
09-02 16:04:22.868 INFO [LocationRequestService a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 51.514873,-0.082997 hAcc=15 et=+4d14h37m26s915ms alt=75.77276611328125 vel=9.82 bear=37.0 vAcc=16 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 142400ms, time: 1567436522000

09-02 16:04:22.882 INFO [TSLocationManager onSingleLocationResult] 
```

### Correct: `C` -> `D`, End of motorcycle trip, waiting a minute or two before continuing the motorcycle trip

```
09-02 16:12:38.497 DEBUG [TrackingService a] 
╔═════════════════════════════════════════════
║ TrackingService: LocationResult
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 51.526483,-0.077440 hAcc=7 et=+4d14h48m4s912ms alt=68.27392578125 vel=3.46 bear=104.0 vAcc=12 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 33ms, time: 1567437160000

09-02 16:12:38.509 DEBUG [TSLocationManager onLocationResult] 
```

### Unexpected: `D` -> `A`, The tracking didn't continue before returning to the original location

```
  ℹ️  Location availability: true
09-02 16:42:26.789 INFO [LocationRequestService a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 3
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 51.504856,-0.100475 hAcc=13 et=+4d15h17m51s676ms alt=44.69999694824219 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 1561ms, time: 1567438945227

09-02 16:42:26.807 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 13.342
09-02 16:42:26.846 INFO [LocationRequestService a] 
```

### Correct: `D` -> `A`, Last tracking before the trip starts

```
09-02 17:21:53.519 INFO [LocationRequestService a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 11
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 51.504858,-0.100469 hAcc=16 et=+4d15h57m18s610ms alt=44.599998474121094 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 1358ms, time: 1567441312161

09-02 17:21:53.540 INFO [HttpService flush] 
```

</details>

### Trip 2 (`A` -> `E` -> `F` -> `G` -> `H`):
* Walk around location `A`
* Motorcycle trip to `H` through `E` (no stop), `F` (no stop), and `G` (small stop) (`A` -> `E` -> `F` -> `G` -> `H`)

<details><summary>Trip 2 Logs Annotation</summary>

### Unexpected: `A` -> `E`, Started tracking quite after the trip started

```
09-02 20:18:51.444 INFO [LocationRequestService a] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 3
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 51.510667,-0.086685 hAcc=14 et=+4d18h54m15s170ms alt=59.79999923706055 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 2721ms, time: 1567451928720

09-02 20:18:51.466 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 14.441
09-02 20:18:51.506 INFO [LocationRequestService a] 
```

# Unexpected: `E` -> `F`, Stopped tracking in the middle of a trip:

```
09-02 20:24:32.650 INFO [BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 73
09-02 20:24:32.663 DEBUG [BackgroundTaskService onDestroy] 
09-02 20:55:34.648 INFO [TSConfig print] 
```

</details>

## Debug logs

[Logs are too big, attached as file](https://github.com/transistorsoft/react-native-background-geolocation/files/3569250/background-geolocation-3-sanitized.log)

**Comment by christocracy** [comment]
When you see something like this, the plugin's Service has been re-started after being terminated.

```
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.0.22 (322)
╠═════════════════════════════════════════════
```

There's no sign of any error before the service re-starts in any of your cases so it can only be the OS terminating the service for some reason.  How much free space do you have on that device?  These logs consume a lot of space.

Also see http://dontkillmyapp.com

I regularly field-test with a *OnePlus A510*, with the SampleApp running untouched for week-a-time.  This device is **very** reliable for me.

![](https://dl.dropboxusercontent.com/s/dhtigpcw56x86dk/Screenshot%202019-09-03%2010.24.52.png?dl=1)

**Comment by christocracy** [comment]
Try doing a test with a higher `distanceFilter: 50`

**Comment by costas-basdekis** [comment]
I'm doing a similar trip to Trip 1 with the example app:

http://tracker.transistorsoft.com/autotrip

The same issue:
* It corectly tracks me getting the motorcycle out of the garage
* It correctly stops tracking since I stop moving
* It incorrectly doesn't track me when I start my trip after a minute
* It correctly starts tracking when I open the app again
* It correctly stops tracking when I make a stop
* It incorrectly doesn't resume tracking when I resume my trip after the stop
* It incorrectly doesn't continue tracking even when I open another tracking app
* It correctly continues tracking when I open the example app itself

**Comment by christocracy** [comment]
Yes, the OS is terminating the plugin's Service for an unknown reason.  It will be helpful to observe the raw `adb logcat`.  In *Settings->Developer Options*, Configure your *Logger buffer sizes = 16M*.

Go out for a test then run back to your machine as quickly as possible, plugin your device into USB, and run:
```
adb logcat -d > logcat.log
```
to capture then entire log buffer to a file.  Attach that file here.

**Comment by costas-basdekis** [comment]
I captured the logs of a small walking trip. Incidentally, I turned `Doze mode` off, and that seemed to have improved it.

[logcat.log](https://github.com/transistorsoft/react-native-background-geolocation/files/3570352/logcat.log)

I'll be able to do bigger trips tonight and tomorrow to test.

BTW, about the `distanceFilter: 50`, how will a bigger distance help?

**Comment by christocracy** [comment]
My *OnePlus A510* tracked most of the first leg of an Airline trip I took this summer, then continued to track a 200km car trip after landing.
![](https://dl.dropboxusercontent.com/s/kyxlhtd1ciac9fh/Screenshot%202019-09-03%2011.54.38.png?dl=1)

*200km return car trip*
![](https://dl.dropboxusercontent.com/s/m9h8ee45h23l472/Screenshot%202019-09-03%2011.59.05.png?dl=1)

**Comment by christocracy** [comment]
>BTW, about the distanceFilter: 50, how will a bigger distance help?

Record fewer locations, fewer logs, consume less memory.

**Comment by costas-basdekis** [comment]
It looks like that with that suggestion it's tracking very reliably (tested for about a week). It's weird, because the example app with more aggressive settings was still quite more reliable.

For reference, my changes:
```diff
-  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
+  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
-  distanceFilter: 15,
+  distanceFilter: 25,
-  elasticityMultiplier: 1,
+  elasticityMultiplier: 5,
-  desiredOdometerAccuracy: 100,
+  desiredOdometerAccuracy: 2500,
-      stationaryRadius: 5,
+      stationaryRadius: 15,
-      fastestLocationUpdateInterval: 2500,
+      fastestLocationUpdateInterval: 15000,
-      deferTime: 20000,
+      deferTime: 60000,
-  heartbeatInterval: 60,
+  heartbeatInterval: 120,
-  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
+  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
```

I know I've cast a wide net, but it's good enough for now. I might try narrowing it down in the future.

**Comment by christocracy** [comment]
I can't see how any of those changes would affect long term tracking performance.

**Comment by costas-basdekis** [comment]
The `distanceFilter` was per your suggestion. and I also tried a few more settings for good measure. It does record quite fewer points per trip, and from the testing from the rest of the team it does look like to much more rarely to miss a trip.

I'm not claiming that all of them affected that, but then I wasn't sure which ones would.
