### ISSUE TITLE
addGeofence / addGeofences doesn't update extras param

### ISSUE THREAD

**Issue by littlehome-eugene** [transistorsoft/react-native-background-geolocation#821]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^3.2.0",
* Platform: iOS or Android android
* OS version: mac high sierra
* Device manufacturer / model: galaxy s10e
* React Native version (`react-native -v`):
react-native-cli: 2.0.1
react-native: 0.60.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
       reset: false,
       stopTimeout: 1,
       debug: true,
       logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
       foregroundService: true,
       autoSync: true,
       url: TRACKER_HOST + this.state.username,
       stopOnTerminate: false,
       startOnBoot: true,
       notification: {
         title: 'react-native-background-geolocation',
         text: 'Tracking engaged'
       },
       heartbeatInterval: 60,
       enableHeadless: true,
       params: BackgroundGeolocation.transistorTrackerParams(DeviceInfo),
       maxDaysToPersist: 14,
       geofenceProximityRadius: 3000,
     }, (state:State) => {
       if (state.schedule && state.schedule.length > 0) {
         BackgroundGeolocation.startSchedule();
       }
       this.setState({
         enabled: state.enabled,
         isMoving: state.isMoving,
         followsUserLocation: state.enabled,
         showsUserLocation: state.enabled,
         bgGeo: state
       });
     }, (error:string) => {
       console.warn('BackgroundGeolocation error: ', error)
     });
```

## Expected Behavior

addGeofence or addGeofences supposed to update `extras` parameter 
hope to see `geofence_event.extras.foo` change on `onGeofence` callback.
## Actual Behavior

but  geofence_event.extras.foo does not change and shows old value.

## Steps to Reproduce

I event tried removing geofences before adding, but still extras are 
```
      geofence.extras.foo = true
       geofences.map(geofence => {
         BackgroundGeolocation.removeGeofence(geofence.identifier);
       })
       BackgroundGeolocation.addGeofences(geofences, () => {
         console.log('- addGeofence success');
       }, (error) => {
         console.warn('- addGeofence error: ', error);
       })

      // onGeofence I see event.extras.foo = true

     // then I addGeofence with the above code again with event.extras.foo = false (change data on server side)
     // onGeofence I still see event.extras.foo = true
    // If i close react-native run-android and rerun, foo is changed to false, but I hope to see the value changing without restarting the app
```
1.
2.
3.
4.

## Context

I'm retrieving geofence locations with extras data from server and trying to update the geofence with new data

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Do not try to do this by removing / re-adding a geofence.  If you have configured [`geofenceInitialTriggerEntry: true`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#geofenceinitialtriggerentry) (the default), you'll create **an infinite loop** if you remove/re-add a geofence *when you're already inside it*.

What are you trying to do by updating `Geofence.extras`?

**Comment by littlehome-eugene** [comment]
I did manual remove because adding won't replace the old geofence (the `extras` part at least)

When user visits a location, I'd like to show user something if it has `extras.foo=true` set

I'm fetching the geofences data from server since `extras.foo` value can be changed on the server and has to be fetched from time to time. (I'm currently fetching if user moves 5km or more)

**Comment by littlehome-eugene** [comment]
So is this something how Geofence works at the moment, not that I messed up something?

(extras not upadating on by re-adding geofences)

**Comment by christocracy** [comment]
I just tried to reproduce this and I had no issue.  You're doing something wrong in your code.  Show me your *entire* `onGeofence` handler.
