### ISSUE TITLE
geofenceProximityRadius doesn't seem to work

### ISSUE THREAD

**Issue by littlehome-eugene** [transistorsoft/react-native-background-geolocation#822]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^3.2.0",
* Platform: iOS or Android android
* OS version: mac high sierra
* Device manufacturer / model: galaxy s10e
* React Native version (`react-native -v`):
react-native-cli: 2.0.1
react-native: 0.60.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
       reset: false,
       stopTimeout: 1,
       debug: true,
       logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
       foregroundService: true,
       autoSync: true,
       url: TRACKER_HOST + this.state.username,
       stopOnTerminate: false,
       startOnBoot: true,
       notification: {
         title: 'react-native-background-geolocation',
         text: 'Tracking engaged'
       },
       heartbeatInterval: 60,
       enableHeadless: true,
       params: BackgroundGeolocation.transistorTrackerParams(DeviceInfo),
       maxDaysToPersist: 14,
       geofenceProximityRadius: 3000,
     }, (state:State) => {
       if (state.schedule && state.schedule.length > 0) {
         BackgroundGeolocation.startSchedule();
       }
       this.setState({
         enabled: state.enabled,
         isMoving: state.isMoving,
         followsUserLocation: state.enabled,
         showsUserLocation: state.enabled,
         bgGeo: state
       });
     }, (error:string) => {
       console.warn('BackgroundGeolocation error: ', error)
     });
```

## Expected Behavior

D TSLocationManager: ║ TSGeofenceManager found 13/323 within 1000 meters

I thinkg this should be 3000 instead of 1000

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You said `reset: false`.  That means `#ready` consumes your config only at the first installation of your app.  Thereafter, it's ignored and loads state from persistence.

`reset: true` (or simply remove it because `reset: true` is the default).
