### ISSUE TITLE
Error "Waiting for previous start action to complete"

### ISSUE THREAD

**Issue by vuhoangha** [transistorsoft/react-native-background-geolocation#823]
## Your Environment
* Plugin version:3.2.1
* Platform: Android
* OS version:
* Device manufacturer / model: Redmi Note 4x, SM-G610F
* React Native version (`react-native -v`):0.59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      reset: true,
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 200,
      // Activity Recognition
      stopTimeout: 1,
      heartbeatInterval: 60,
      preventSuspend: true,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: true, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true // <-- Auto start tracking when device is powered-up.
    }
```

</details>

**Comment by christocracy** [comment]
Yes, it’s not unusual.  It takes some seconds after #start for the plugin to attain the first position.  It has no need to be started again if it’s already *starting*, thus the message “waiting for previous start action”.

The #ready method automatically executed #start upon itself when state.enabled == true.

This is why in example code in #ready callback, I always:

```
if (!state.enabled) { 
  BackgroundGeolocation.start()
}
```
  Background

**Comment by vuhoangha** [comment]
Can I configure it to only run in the background and stop in the foreground? Right now, I have to do it manually

**Comment by christocracy** [comment]
No.  That is very off behavior that I’ve never heard of in 5 years.  It doesn’t deserve a config option to handle that.  

It’s correct to expect to handle that in your own manner.

**Comment by AnurajDev** [comment]
@christocracy We are using 3.4.2 version of the library.  RN version is 0.60.3. The error "Waiting for previous start action to complete" is logged so many times from various devices.  We have used this code is ready. Still the log happens every other time. Do you have a solution for this?

```
if (!state.enabled) { 
  BackgroundGeolocation.start()
}
```

**Comment by christocracy** [comment]
This issue from last year is *closed* and you’re not providing any information.  I suggest you post a new issue.

**Comment by AnurajDev** [comment]
@christocracy What all information is required if I post a new issue? My question was even if _(!state.enabled)_ condition is provided the error is logged in Sentry logs.

**Comment by christocracy** [comment]
Just fill out all the requested info in the issue template.

**Comment by dyrkow** [comment]
I have same error.

It's because we have double call geolocation.start();

When i add check on double call, all work well.

```diff

MyWrapperGeoStart() {
-  if(this.isStarted) return;
+  if(this.isStarted || this.isStartInited) return;

    this.isStartInited = true;

    try {
        await BackgroundGeolocation.start();
      
        this.isStarted = true;
+     this.isStartInited = false;
    } catch(err) {
+     this.isStartInited = false;
    }

}
```

**Comment by JasimKotai** [comment]
i am getting same warning where to add those code in this code ..? also can somebody tell me what should i have to add for to run geofence even app is terminated.. this is my app.js code
 useEffect(() => {
    BackgroundGeolocation.ready(
      {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        // url: 'http://your.server.com/locations',
        autoSync: true,
        stopOnTerminate: false,
        startOnBoot: true,
      },
      state => {
        BackgroundGeolocation.start();
        BackgroundGeolocation.startGeofences();
      },
    );

    const addGeofences = async () => {
      try {
        await BackgroundGeolocation.addGeofences(geofences);
        console.log('Geofences added successfully');
      } catch (error) {
        console.error('Error adding geofences:', error);
      }
    };
    addGeofences();
    BackgroundGeolocation.onGeofence(geofence => {
      console.log('[geofence] ', geofence.identifier, geofence.action);
      if (geofence.action === 'ENTER') {
        PushNotification.localNotification({
          channelId: 'test-channel',
          title: geofence.identifier,
          message: `you have reached ${geofence.identifier}`,
          invokeApp: true,
        });
        BackgroundGeolocation.startGeofences();
        console.log('Enter this locayion ', geofence.identifier);
      } else if (geofence.action === 'EXIT') {
        PushNotification.localNotification({
          channelId: 'test-channel',
          title: geofence.identifier,
          message: `you are out of ${geofence.identifier}`,
          invokeApp: true,
        });
        console.log('exit from this locayion ', geofence.identifier);
        BackgroundGeolocation.startGeofences();
        BackgroundGeolocation.start();
      }
    });
  }, []);

**Comment by christocracy** [comment]
You're posting on a **closed issue from FOUR YEARS AGO**.

**Comment by endruuu** [comment]
Just an FYI. In my case, after adding a geofence, I called `startGeofences()`. Then, soon after that, I called `start()`.
I was thinking that the geofence monitoring needs to be started separately.

After removing `startGeofences()`, and just used `start()`, it then worked well.

**Comment by endruuu** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/issues/823#issuecomment-1935639139
> ```
>     console.log('exit from this locayion ', geofence.identifier);
>     BackgroundGeolocation.startGeofences();
>     BackgroundGeolocation.start();
>   }
> });
> ```

Looks like the same issue with me
