### ISSUE TITLE
Question: is it possible to use conditionals in locationTemplate/geofenceTemplate?

### ISSUE THREAD

**Issue by venstardeveloper** [transistorsoft/react-native-background-geolocation#824]
## Your Environment
* Plugin version: 3.0.6
* Platform: Both
* OS version: 
* Device manufacturer / model:
* React Native version (`react-native -v`): 59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    reset: true, // configure every time on startup

    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10, // 10 meter default
    stopTimeout: 1, // Activity Recognition
    stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.

    geofenceInitialTriggerEntry: true, // <-- When a device is already within a just-created geofence, fire the enter transition immediately


    logLevel: 4, // <-- don't keep any logs

    debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
    startOnBoot: true, // <-- Auto start tracking when device is powered-up.

    url: 'https://postman-echo.com/post',
    httpRootProperty: '.',
    batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request
    autoSync: true, // [Default: true ]
    autoSyncThreshold: 5, // wait for this many events to send to skyport

    headers: {
        authorization: 'uhohohohoh',
        'Content-Type': 'application/json',
    },
    locationTemplate:
        '{"latitude": <%= latitude %>, "longitude": <%= longitude %>}',
    geofenceTemplate:
        '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"locationID":"<%= geofence.identifier %>","action":"<%= geofence.action %>"}'
    }
```

## Expected Behavior

I was just wondering if it was possible to use some conditionals in the erb tags for `locationTemplate` and `geofenceTemplate`? 

Something like `{"isInside": <%= geofence.action === "ENTER" %>}` to produce 

## Actual Behavior

When I try to use conditionals or if-statements in the erb tags, the geofence events do not get recorded. Works just fine if I get rid of the `==="ENTER"` from the tag

## Steps to Reproduce

1. start app 
2. `BackgroundGeofencing.destroyLocations()`
3. Change simulator's location to inside/outside of a geofence
4. `BackgroundGeofencing.getLocations()`

## Context

I am trying to modify the body of the http request that is getting sent. 
instead of `{ "action": "ENTER" }`, I would like the body to have `{"isInside": true}`

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
No.  Logic is not supported.  Pretty easy for the server to handle this.

**Comment by venstardeveloper** [comment]
Thanks for the quick response! Will handle it on the server side. 
It might be a good idea to mention in the docs
