### ISSUE TITLE
Setting locationTemplate with an array populates data with an empty object

### ISSUE THREAD

**Issue by mc-da** [transistorsoft/react-native-background-geolocation#825]
## Your Environment
* Plugin version: 3.2.0
* Platform: All
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
      url: `http://localhost:8010/api/hub/gps-data`,
      httpRootProperty: 'data',
      locationTemplate: '[<%=latitude%>, <%=longitude%>, "<%=event%>", <%=is_moving%>]',
      batchSync: false,
      autoSync: true,
```

## Expected Behavior

Data should be sent to url with payload which follows locationTemplate.
## Steps to Reproduce

1. Set up built in http service
2. use locationTemplate with an array
3. observe payload received at server
4. last item in array is an empty object, which is not specified in locationTemplate

## Context

transmit gps data to server

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Data received at server:
{ data:
   [ 33.80328898335839,
     -118.1676979860483,
     'motionchange',
     false,
     {} ] }
```

</details>

**Comment by christocracy** [comment]
That would be where #extras / #params are provided.

It’s best to use the {} form for a locationTemplate

**Comment by mc-da** [comment]
I see.  Would it be possible to omit the object if no extras or params are specified?  I am not specifying either in this case.

I used the locationTemplate provided in docs for simplicity.
My actual locationTemplate shown below; HTTP requests are failing server validation as the object is being interpreted as a data set

```
locationTemplate: '[{"attributes": {"event": "<%= event %>", "coords": {"longitude": <%= longitude %>, "latitude": <%= latitude %>, "speed": <%= speed %>, "floor": null, "accuracy": <%= accuracy %>, "heading": <%= heading %>, "altitude": <%= altitude %>, "altitude_accuracy": <%= altitude_accuracy %>}, "is_moving": false, "odometer": <%= odometer %>, "activity": {"type": "<%= activity.type %>", "confidence": <%= activity.confidence %>}, "battery": {"level": <%= battery.level %>, "is_charging": <%= battery.is_charging %>}}}]'
```

**Comment by christocracy** [comment]
This isn’t going to be changed soon.  I suggest you not use [] in your template at all

**Comment by christocracy** [comment]
I suggest you use this template instead, omitting enclosing `[]`

```
locationTemplate: '{"attributes": {"event": "<%= event %>", "coords": {"longitude": <%= longitude %>, "latitude": <%= latitude %>, "speed": <%= speed %>, "floor": null, "accuracy": <%= accuracy %>, "heading": <%= heading %>, "altitude": <%= altitude %>, "altitude_accuracy": <%= altitude_accuracy %>}, "is_moving": false, "odometer": <%= odometer %>, "activity": {"type": "<%= activity.type %>", "confidence": <%= activity.confidence %>}, "battery": {"level": <%= battery.level %>, "is_charging": <%= battery.is_charging %>}}}'
```

**Comment by mc-da** [comment]
Got it, thank you.

**Comment by christocracy** [comment]
After all, the locationTemplate renders a single location instance.  Using an `[ ]` only makes sense when you're not rendering any *keys*.  It's pointless wrap an Object in Array: `[ { } ]`
