### ISSUE TITLE
Expo SDK v32.0.0 | Background Location and Geofencing

### ISSUE THREAD

**Issue by rfdc** [transistorsoft/react-native-background-geolocation#826]
Hi @christocracy,

The Expo Team release a new feature in SDK 32 that allow you tracking in background the location. 

Does that mean this plugin NOW will work with expo too?

What is the main differences between react-native-background-geolocation and Expo Background Location and Geofencing? 

Thanks

**Comment by christocracy** [comment]
The plugin has always worked with Expo, just that Expo is a nightmare of dependencies, with Expo typically falling behind.

Does Expo support AndroidX / RN 0.60 yet ?  I don’t think so.

**Comment by christocracy** [comment]
The Expo background geolocation / geofencing implementation doesn't have nearly the same feature as `react-native-background-geolocation`.  It will not automatically toggle location-tracking when device is detected moving / stationary.  No headless support.  It's not even in the same class.
