### ISSUE TITLE
Geofencing not working as expected when screen is off for long time

### ISSUE THREAD

**Issue by roysG** [transistorsoft/react-native-background-geolocation#827]
## Your Environment
* Plugin version: 3.0.9
* Platform: iOS
* OS version: 12.3.1
* Device manufacturer / model: iphone 6
* React Native version (`react-native -v`):
react-native-cli: 1.0.0
react-native: 0.58.3

## Expected Behavior
Geofencing suppose to work even the screen is off for long time.
(My location permission is on "Always")

## Actual Behavior
Geofencing not working if user do not touch in screen more than 5 minutes (estimated).

## Debug logs
I am driving in car, i do not have way to send the logs.

## Code
   locations.forEach(({locationLoc, id}) => {
                locationsList.push({
                    identifier: "Location_"+id,
                    radius: 200,
                    latitude: locationLoc.coordinates[1],
                    longitude: locationLoc.coordinates[0],
                    notifyOnEntry: true
                })
    })
      BackgroundGeolocation.addGeofences(locationsList);

BackgroundGeolocation.onGeofence(geofence => {
            console.log('[geofence] ', geofence);
            locationList.forEach((location)=>{
                if (geofence.identifier == "Location_"+location.id) {
                    if (geofence.action == 'ENTER') {
                        BackgroundGeolocation.start();
                    } else if (geofence.action == 'EXIT') {
                        BackgroundGeolocation.startGeofences();
                    }
                }
            })
        });

BackgroundGeolocation.ready({
                    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                    distanceFilter: 10,
                    autoSync: true
                }, state => {
                    BackgroundGeolocation.startGeofences();
                })

**Comment by christocracy** [comment]
See wiki Debugging

**Comment by christocracy** [comment]
Geofencing has nothing to do with screen on/off.  It doesn’t even matter if your app is launched/terminated.

use debug: true so you can *hear* events

**Comment by roysG** [comment]
Ok, But you know this problem in generally on iphone?

**Comment by christocracy** [comment]
Yes, that’s what you said in the issue template.  Now fetch the logs from your device, as described in the wiki and go field test with debug: true.

**Comment by roysG** [comment]
Ok and then paste the logs here?

**Comment by christocracy** [comment]
Use #emailLog and *attach* the received file.  Do *not* post an immense amount of logs to the thread.

**Comment by roysG** [comment]
ok
