### ISSUE TITLE
Error in ExpoKit project related to  CocoaLumberjack version conflict, after adding library 

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#829]
## Your Environment
* Plugin version:
* Platform: iOS 
* OS version: all
* Device manufacturer / model I:phone
* React Native version (`react-native -v`): 0.59.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

I expect that project will work after the adding of the library.

## Actual Behavior

I have ExpoKit project version 34.0.0, when I'm trying to add library to ExpoKIt project (IOS), I'm getting this error:  

```
"CocoaPods could not find compatible versions for pod "CocoaLumberjack":
  In Podfile:
    CocoaLumberjack (= 3.5.3)

    ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/2.12.1`) was resolved to 34.0.0, which depends on
      CocoaLumberjack (~> 3.2.1)

    RNBackgroundGeolocation (from `../node_modules/react-native-background-geolocation`) was resolved to 3.2.0, which depends on
      CocoaLumberjack (~> 3.5.1)

Specs satisfying the `CocoaLumberjack (= 3.5.3), CocoaLumberjack (~> 3.2.1), CocoaLumberjack (~> 3.5.1)` dependency were found, but they required a higher minimum deployment target."
```

Is this library compatible with ExpoKit? I was testing it 3 months ago and it was working, now I'm not sure what should I do with this error.  I'm getting this error, when I'm trying to do `pod install`.

## Steps to Reproduce

1. react-native link react-native-background-fetch
2. pod install

## Context

Add the library to the project

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
ExpoKit an old version of CocoaLumberjack.  There's an [issue there about it](https://github.com/expo/expo/issues/4481).

Use `patch-package` on ExpoKit to use `~> 3.5.1`. There's probably no issue with this. 

`CocoaLumberjack@3.5.0` introduced XCode 10 support -- you want that.  We'll soon be on *XCode 11*.

How far behind is ExpoKit? `CocoaLumberjack@3.2.1` [dates back to 2017-08-21](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/CHANGELOG.md#321---xcode-9-beta-on-aug-21st-2017), over two years ago.

**Comment by Luckygirlllll** [comment]
@christocracy what do you mean exactly by `patch-package`? You mean create a fork for ExpoKit and update there CocoaLumberjack to the 3.5.1?

**Comment by christocracy** [comment]
[patch-package](https://github.com/ds300/patch-package) is a tool you can use to provide your own custom overrides to a module.

**Comment by Luckygirlllll** [comment]
@christocracy Any ideas which exactly file in Expo I should update in order to update CocoaLumberjac there?

**Comment by christocracy** [comment]
[expo/ExpoKit.podspec](https://github.com/expo/expo/blob/master/ExpoKit.podspec#L25)

It seems they've [upgraded to `3.5.3` 10 days ago](https://github.com/expo/expo/pull/5500/commits/1fb47d06cd5867689147b98f69c3eb02fc346f8c)

**Comment by Luckygirlllll** [comment]
I have used the fork which was advised in the expo thread, however, now I'm getting new error: 

```
react-native link react-native-background-fetch
info Linking "react-native-background-fetch" iOS dependency
info iOS module "react-native-background-fetch" has been successfully linked
info Linking "react-native-background-fetch" Android dependency
info Android module "react-native-background-fetch" has been successfully linked
 [Object: null prototype] {
  '1A42804E64B7E9E0AB8B6799':
   [Object: null prototype] {
     isa: 'PBXGroup',
     children: [ [Object], [Object], [Object] ],
     name: 'Frameworks',
     sourceTree: '"<group>"' },
  '1A42804E64B7E9E0AB8B6799_comment': 'Frameworks',
  '55A1BBF65E084EFC98F9AC05':
   [Object: null prototype] {
     isa: 'PBXGroup',
     children:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     name: 'Resources',
     sourceTree: '"<group>"' },
  '55A1BBF65E084EFC98F9AC05_comment': 'Resources',
  '5B29BC350A332C58878A9F13':
   [Object: null prototype] {
     isa: 'PBXGroup',
     children: [ [Object], [Object] ],
     name: 'Pods',
     sourceTree: '"<group>"' },
  '5B29BC350A332C58878A9F13_comment': 'Pods',
  B56386381DB9693800A0598C:
   [Object: null prototype] {
     isa: 'PBXGroup',
     children: [ [Object], [Object], [Object], [Object], [Object] ],
     sourceTree: '"<group>"' },
  B56386421DB9693800A0598C:
   [Object: null prototype] {
     isa: 'PBXGroup',
     children: [ [Object] ],
     name: 'Products',
     sourceTree: '"<group>"' },
  B56386421DB9693800A0598C_comment: 'Products',
  B56386431DB9693800A0598C:
   [Object: null prototype] {
     isa: 'PBXGroup',
     children: [ [Object], [Object], [Object], [Object], [Object] ],
     path: '"civic-champs"',
     sourceTree: '"<group>"' },
  B56386431DB9693800A0598C_comment: 'civic-champs',
  B563865B1DB96A5E00A0598C:
   [Object: null prototype] {
     isa: 'PBXGroup',
     children:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     path: 'Supporting',
     sourceTree: '"<group>"' },
  B563865B1DB96A5E00A0598C_comment: 'Supporting' }
 [react-native-background-fetch] LINK ERROR: Failed to find projectGroup PBXGroup:  civic-champs
 [react-native-background-fetch] Failed to add RNBackgroundFetch+AppDelegate.m.  See Manual Setup instructions to add this file to your project.
 [react-native-bacgkround-fetch] Please post an issue at Github, including all the output above
```

**Comment by Luckygirlllll** [comment]
@christocracy Where can I find info about how to use Geofence? I remember there was examples how to use it, but I can't find them now.

**Comment by Luckygirlllll** [comment]
This problem was solved by using this fork of `ExpoKi`t: 

```
  pod 'ExpoKit',
    :git => "http://github.com/ec2-software/expo.git",
    :tag => "ios/2.12.4-ec2-1",
```

**Comment by bfarrgaynor** [comment]
It seems as though I'm running into this. 

Ejected expo 40.0.0

```
[!] CocoaPods could not find compatible versions for pod "CocoaLumberjack":
  In snapshot (Podfile.lock):
    CocoaLumberjack (= 3.6.2, ~> 3.6.1)

  In Podfile:
    RNBackgroundGeolocation (from `../node_modules/react-native-background-geolocation`) was resolved to 4.0.2, which depends on
      CocoaLumberjack (~> 3.7.0)

```

**Comment by bfarrgaynor** [comment]
I think I fixed this by upgrading my cocoapods and running a:
```
pod update CocoaLumberjack
```
Something in my project was relying on this but it didn't blow up after upgrading so..... fingers crossed

**Comment by christocracy** [comment]
See [CHANGELOG 4.0.2](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#402--2021-03-25), published 2 days ago.

>[Changed][iOS] Update pod CocoaLumberjack to latest ~> 3.7.0

[3.7.x is the latest version of CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/CHANGELOG.md)
