### ISSUE TITLE
How to use Geofence? 

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#831]
## Your Environment
* Plugin version: 3.2.0
* Platform: iOS and Android
* OS version: all
* Device manufacturer / model: all
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

Where can I find a guide how to use Geofence from react-native-background-geolocation library?

**Comment by christocracy** [comment]
See docs event #onGeofence

**Comment by Luckygirlllll** [comment]
and where is this docs? I see only how to [import Geofence ](https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-using-the-plugin) from the library and how to use basic background geolocation.

**Comment by christocracy** [comment]
You need to *read* the [README](https://github.com/transistorsoft/react-native-background-geolocation#contents).  The API docs are conveniently linked there.

**Comment by Luckygirlllll** [comment]
True, I missed API documentation point.
