### ISSUE TITLE
How to stop Geofences tracking?

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#833]
How to stop geofences tracking? Is there any specific method for this? or the only one way is to remove  geofences? 

```
 BackgroundGeolocation.removeGeofences().then(success => {
            console.log('[removeGeofences] all geofences have been destroyed');
  })
```

**Comment by christocracy** [comment]
Correct.  Don’t wanna track geofences anymore?  Destroy them.

And of course calling #stop will stop tracking everything: location & geofencing.

But if you want to track location but not geofences, then #removeGeofences.

**Comment by Luckygirlllll** [comment]
Okay, thanks!
