### ISSUE TITLE
Are there substitutes for `activityRecognitionInterval` and `minimumActivityRecognitionConfidence`?

### ISSUE THREAD

**Issue by ruanhao** [transistorsoft/react-native-background-geolocation#834]
## Your Environment
* Plugin version: 3.2.0
* Platform: iOS 
* OS version: 12.1.4
* React Native version (`react-native -v`): 0.60.5

## Question
I see `activityRecognitionInterval` and `minimumActivityRecognitionConfidence ` are both deprecated. I wonder are there any substitutes to control activity recognition?

Thanks!

**Comment by christocracy** [comment]
No.  The Plugin now implements the newer [activity transition API](https://developer.android.com/guide/topics/location/transitions).  This api is just on/off and has no need for controlling sample-rate and provides no “confidence”.
