### ISSUE TITLE
How to delay permission request? 

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#837]
I added code, where I invoked` BackgroundGeolocation` in` App.js` file, and I noticed that app started to ask permissions, once app is launched, however, I want to ask permissions, not during the app launch, but after the login, how I can delay permission request?

**Comment by christocracy** [comment]
When you call `#start` or `#startGeofences` or `#getCurrentPosition`, the plugin *automatically* requests permission.

Don't call *any* of those methods until *after* the user is logged-in.

**Comment by Luckygirlllll** [comment]
@christocracy I just have tried this solution, and I see that Notification permission request  still fires once app launch, location and motion request appears correctly! Should I add any extra setting for notification request?

**Comment by christocracy** [comment]
The plugin persists its `state.enabled` between launch.  if you:
1.  `#start` plugin
2.  Terminate app.
3.  Go to device Settings and revoke/change Location permission
4.  Reboot app:  The plugin detects location permission has changed.  Shows dialog prompting user to authorize permission.

**Comment by Luckygirlllll** [comment]
@christocracy I have in App.js such code:

 ```
componentWillMount() {
    // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.onLocation(this.onLocation, this.onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange(this.onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.onActivityChange(this.onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.onProviderChange(this.onProviderChange);

    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      // url: 'http://yourserver.com/locations',
      // batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      // autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
      
      }
    });
  }
```

Then after user have login I have such code:

```
  BackgroundGeolocation.startGeofences(function() {
            console.log("- Start Geofences success");
          });
```
The problem is that I'm still getting on the first screen permission request for notifications which is fired by background geolocation library, while I want that notification request will be also asked after login as well.

**Comment by christocracy** [comment]
Ohhh...for *notifications*.  That's because of `debug: true`, so the iOS plugin can post post those debug local-notifications while developing.

Presumably, you won't publish your app with `debug: true`, then that permission won't be requested.

**Comment by Luckygirlllll** [comment]
Ok, got it!
