### ISSUE TITLE
How to stop tracking once user leave geofence? 

### ISSUE THREAD

**Issue by rfdc** [transistorsoft/react-native-background-geolocation#839]
### Environment
- Plugin version: 3.2.0
- Platform: iOS and Android
- Device manufacturer / model: Samsung S5
- React Native version (react-native -v): 0.60.4

## Context
I only want to track users that are nearby the city region. What is the best approach to stop tracking users that are far from the city region? 

## Approach:
Do I need to use `BackgroundGeolocation.start` and `BackgroundGeolocation.startGeofences` together? So once the user enters the geofence the plugin starts?

Thanks for helping,

**Comment by christocracy** [comment]
`#start` = track location + geofences
`#startGeofences` = track geofences **only**.

- Put a geofence around the city.
```javascript
BackgroundGeolocation.onGeofence((event) => {
  if (event.identifier === 'MyCity') {
    if (event.action === 'ENTER') {
      BackgroundGeolocation.start();
    } else {
      BackgroundGeolocation.startGeofences();
    }
  }
});
```

**Comment by rfdc** [comment]
Hi Chris, thanks for your fast response. 
I just found that on the [Interface Geofence doc](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.geofence.html#extras).

Toggling between tracking-modes start and startGeofences
The SDK can easily be toggled between State.trackingMode simply by executing the corresponding start or startGeofences methods.

```javascript
// Listen to geofence events
BackgroundGeolocation.onGeofence(geofence => {
  console.log('[geofence] ', geofence);
  if (geofence.identifier == 'DANGER_ZONE') {
    if (geofence.action == 'ENTER') {
      // Entering the danger-zone, we want to aggressively track location.
      BackgroundGeolocation.start();
    } else if (geofence.action == 'EXIT') {
      // Exiting the danger-zone, we resume geofences-only tracking.
      BackgroundGeolocation.startGeofences();
    }
  }
})

// Add a geofence.
BackgroundGeolocation.addGeofence({
  identifier: "DANGER_ZONE",
  radius: 1000,
  latitude: 45.51921926,
  longitude: -73.61678581,
  notifyOnEntry: true,
  notifyOnExit: true,
})

// Ready the plugin.
BackgroundGeolocation.ready({
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  url: 'http://your.server.com/locations',
  autoSync: true
}, state => {
  BackgroundGeolocation.startGeofences();
}) 
```
Thanks
