### ISSUE TITLE
toggle logging

### ISSUE THREAD

**Issue by yonahforst** [transistorsoft/react-native-background-geolocation#84]
is there a way to toggle the logging information in the xcode debug area

**Comment by christocracy** [comment]
debug:false

On Monday, May 23, 2016, Yonah Forst <notifications@github.com> wrote:

> is there a way to toggle the logging information in the xcode debug area
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/84>
>


-- 
Snet form Gmail Mobile

**Comment by yonahforst** [comment]
thanks!
