### ISSUE TITLE
Location is not updating  for long time in IOS

### ISSUE THREAD

**Issue by ramkey-akil** [transistorsoft/react-native-background-geolocation#840]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by alexgsummer** [comment]
@ramkey-akil I'm not a maintainer, but you're more likely to get a helpful response if you fill out the issue template and provide as much detail as possible about your issue.
