### ISSUE TITLE
Location saved on server very frequently. I want to some interval to save location.

### ISSUE THREAD

**Issue by mohitsingh90** [transistorsoft/react-native-background-geolocation#850]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Do **NOT** ignore the issue template.  You've provided no information *at all*.
