### ISSUE TITLE
Module AppRegistry is not a registered callable module (calling startHeadlessTask)

### ISSUE THREAD

**Issue by niv-breez** [transistorsoft/react-native-background-geolocation#852]
## Your Environment
* Plugin version: 3.2.2
* Platform: Android
* OS version: linux
* Device manufacturer / model: try different android devices
* React Native version (`react-native -v`): 0.59.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
  reset: true, // <-- true to always apply the supplied config
  // Geolocation Config
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 0,
  // Activity Recognition
  stopTimeout: 1,
  // useSignificantChangesOnly: true,
  // Application config
  debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  enableHeadless: true,
  stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
  startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
}, (state) => {
  console.log("- BackgroundGeolocation is configured and ready!!", state.enabled);

  if (!state.enabled) {
    ////
    // 3. Start tracking!
    //
    BackgroundGeolocation.start(function() {
      console.log("BackgroundGeolocation started successfully");
    });
  }
});

////
// Define your Headless task -- simply a javascript async function to receive 
// events from BackgroundGeolocation:
//
let HeadlessTask = async (event: any) => {
  let params = event.params;
  console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);
  
  switch (event.name) {
    case 'location':
      // Use await for async tasks
      await sendLocationToServer(params)
      console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', params);
      break;
  }
}

// Register your HeadlessTask with BackgroundGeolocation plugin - for android on killed mode
BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

// This handler fires whenever bgGeo receives a location update - for foreground in android and ios + ios in killed mode
BackgroundGeolocation.onLocation(sendLocationToServer, errorCode => requestLogMessage(`onLoction failed with errorCode: ${errorCode}`));
```

## Expected Behavior
1. Locations should be send to my server event if the app is in killed mode.
1. I should see in the JS logs the logs from the headless task

## Actual Behavior
1. Locations not sent
1. it seems the the headless task is not invoked

**Comment by christocracy** [comment]
`BackgroundGeolocation.registerHeadlessTask` [must be placed in the *root* `index.js`](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode#step-2--backgroundgeolocationregisterheadlesstask) file, not in your Application components.

**Comment by niv-breez** [comment]
My app doesn't contains index.js, I have app.tsx this is the main JavaScript of my app

**Comment by christocracy** [comment]
In the same place where you `AppRegistry.registerComponent`, you must [place the BackgroundGeolocation.registerHeadlessTask](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/index.js).

`#ready` does in your Application components.  `registerHeadlessTask` does *not*.

**Comment by niv-breez** [comment]
Ok I will try to understand where is my 
`AppRegistry.registerComponent`
And put it there and let you know.

About what you said that the ready can be in my application component, is this just for Android or it's ok for IOS?

**Comment by christocracy** [comment]
Headless mode is an Android-only thing.  iOS has no such concept of “headless”.

#ready and #registerHeadlessTask do not live in the same file together.

**Comment by niv-breez** [comment]
Hi @christocracy,
I still get: `Module AppRegistry is not a registered callable module (calling startHeadlessTask)`
After moving `BackgroundGeolocation.registerHeadlessTask` to the `index.js` where is my `AppRegistry.registerComponent`

**Comment by niv-breez** [comment]
I don't know if it is related to the headless but I maybe this will helps with investigate the issue,
I put `Log.i("breez-location", "RNBackgroundFetchModule-start");` in the `RNBackgroundFetchModule.start` in order to check if something is starting there but I don't see the log.

**Comment by niv-breez** [comment]
Hi @christocracy ,
we wait 6 days for getting your  support for make the plugin work on our app, we purchased the licence and we except to get your response in order to get sense of how to continue from here.
Please let us know what to check and how to fix it.

Thanks.

**Comment by christocracy** [comment]
I suggest you create a simple, pure RN hello world and test headless mode in isolation of your app.

**Comment by niv-breez** [comment]
This is what I did and it working but I don't understand why it is not working on the real application.
Can you suggest what can be missing?

**Comment by chattes** [comment]
> In the same place where you `AppRegistry.registerComponent`, you must [place the BackgroundGeolocation.registerHeadlessTask](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/index.js).
> 
> `#ready` goes in your Application components. `registerHeadlessTask` does _not_.

Just a suggestion . Since we also pay for the Android component . I feel this should clerly documented in the main ReadMe file. I had to dig thorugh issue list etc to even find that there is a headless mode.. and then some.

> `BackgroundGeolocation.registerHeadlessTask` [must be placed in the _root_ `index.js`](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode#step-2--backgroundgeolocationregisterheadlesstask) file, not in your Application components.

Just a suggestion . Since we also pay for the Android component . I feel this should clearly documented in the main ReadMe file. I had to dig thorugh issue list etc to even find that there is a headless mode.. and then some.

**Comment by christocracy** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode#step-2--backgroundgeolocationregisterheadlesstask

**Comment by Jacky9425** [comment]
Hi @christocracy , is it possible to dispatch redux action or perform a POST method in headless task? Im trying to dispatch redux action and POST the result back to backend when a geofence action occurs at background

**Comment by christocracy** [comment]
I don’t know.  I don’t know much about redux.  I’d probably want to execute my actions within #startBackgroundTask.

**Comment by Jacky9425** [comment]
according to doc, `The Android plugin hardcodes a limit of 30s for your background-task before it automatically FORCE KILLs it.`.

Since i was trying to run a continuous service at the background so i can only implement it using registerHeadlessTask.

I actually execute registerHeadlessTask() at my HomeScreen's index.js, it works fine in debugging mode but on release mode, it works fine for few times but then it will crash. According to logs, it shows `No task registered for key BackgroundGeolocation`

**Comment by christocracy** [comment]
You do not register headless task in a “home screen”, you register it in the app’s root index.js

**Comment by Jacky9425** [comment]
is the requirement set by react native or the plugin?

**Comment by christocracy** [comment]
react-native.  You cannot register headless task within your application components.

Application components do not exist in the headless state.  They are not instantiated.

**Comment by Namec** [comment]
i followed strictly what the documention mentions about registering in HeadlessMode, but still have this error :  Reference Error : Can't find variable: BackGroundGeolocation

here is my Index.js

=====================

/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);

let HeadlessTask = async (event) => {
    let params = event.params;
    console.warn('[BackgroundGeolocation HeadlessTask] -', event.name, params);
    
    switch (event.name) {
      case 'heartbeat':
        // Use await for async tasks
        let location = await getCurrentPosition();
        console.warn('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
        break;
    }
  }


  BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

**Comment by christocracy** [comment]
You need to `import BackgroundGeolocation`

**Comment by Namec** [comment]
done, thank you
