### ISSUE TITLE
background Geo Location stops for iOS 13

### ISSUE THREAD

**Issue by itcurves** [transistorsoft/react-native-background-geolocation#853]
## Your Environment
* Plugin version: 2.14.2
* Platform: iOS
* OS version: 13 or higher 
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`): 0.58.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        reset: true,
        distanceFilter: 10,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        stationaryRadius: 25,        
        stopTimeout: 1,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,  
        startOnBoot: false,       
        autoSync: false,         
      }
```

## Expected Behavior

It was working fine before but on iOS 13 it stop working do I need to upgrade to the latest version? do we have any updates for iOS 13? 
## Actual Behavior

it stops once moved to the background now.

## Steps to Reproduce

just running watchposition every minute

not sure what details I can provide.

Thanks

</details>

**Comment by christocracy** [comment]
Read the changelog and update to latest 3.x

**Comment by itcurves** [comment]
ok great!!!

Do you have some documentation for the upgrade? or a command?
Thanks

**Comment by christocracy** [comment]
Changes are in...the CHANGELOG

**Comment by itcurves** [comment]
you are Awesome !!! thanks

**Comment by itcurves** [comment]
one more question please can I use 3.x with RN 0.58.3? or it has to be 0.60.+ ?

**Comment by christocracy** [comment]
Yes

**Comment by itcurves** [comment]
Yes for I can use it?

**Comment by christocracy** [comment]
Yes, it works for all versions of rn

**Comment by itcurves** [comment]
Hi,

I upgrade to version 3.2.2.

what i did unlink the old component
uninstall the new component
install using npm install and it did install 3.2.2
link using the manual process for iOS
but my app stop background tracking after 5-7 min 

I believe the iPhone keep the app running for at least 5 minutes. but after that, it stops.

any guess what I need to check?

Thanks

**Comment by christocracy** [comment]
>link using the manual process for iOS

why manual?  Use `react-native link`

>but my app stop background tracking after 5-7 min

- Are you *moving*?  The plugin tracks when the device is *moving*.  As long as the device remains moving, the plugin is going to track that device until it stops moving.  iOS requires movement of *at least* 200 meters before the plugin initiates tracking.
- Are you observing the logs?  See Wiki [Debugging](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Debugging)

**Comment by itcurves** [comment]
I only use it in iOS that is why use manual.

Also, we have an app that needs to send some location update to an API and it might be possible use is sitting on the same location for a long time.
we have timmer runs and call the watch position every minute.

is there any way it keeps working even user is not moving? it was working before with no issue, we face this problem after iOS 13.

Please guess what we need to check?
Thanks

**Comment by christocracy** [comment]
Show me your `android/app/build.gradle`

**Comment by itcurves** [comment]
we only getting issues with iOS we not even tracking in android as android let us run the timer in the background.

**Comment by christocracy** [comment]
>we not even tracking in android as android let us run the timer in the background.

And how are you doing that.  I suggest you watch [this video](https://youtu.be/q6UMmLMnLl8?t=483)

**Comment by christocracy** [comment]
If it's your intention to use only the iOS plugin without purchasing a license, you're not going to get much timely support from me.

**Comment by itcurves** [comment]
we have our app only running on iOS right now and it was working fine until now. it stops working after iOS 13
our android is up but no one using it, we have only apple users and right now we stuck in this issue that we never faced before.

I watched the video and understand but we had a working app it just stop now.

Thanks

**Comment by christocracy** [comment]
See [this blog-entry](https://medium.com/@transistorsoft/ios-13-and-android-q-support-beb7595d2c24)

**Comment by itcurves** [comment]
Yes. already check that and have it always allow for testing, but still not working.

**Comment by itcurves** [comment]
ok do you think any fix for this?

we are using BackgroundGeolocation.watchPosition() with a minute interval and it worked fine in past, but stop working with iOS 13 update.

Thanks

**Comment by Base29** [comment]
@christocracy  ... can i use 3.2.2 with RN 0.57.0 ?

**Comment by christocracy** [comment]
> can i use 3.2.2 with RN 0.57.0 ? 

I don’t understand why people ask this?

Is there something unclear in the [Setup Guides](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/README.md#large_blue_diamond-setup-guides)?

57.0 is < 60.0 so follow that path in the Setup Guides.

**Comment by Base29** [comment]
> > can i use 3.2.2 with RN 0.57.0 ?
> 
> I don’t understand why people ask this.
> 
> Is there something unclear in the [Setup Guides](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/README.md#large_blue_diamond-setup-guides)?
> 
> 57.0 is < 60.0 so follow that path in the Setup Guides.

Sorry about this ... the question was actually for the doing an upgrade from 3.0.2 to the latest one ... needed to confirm if I am doing it right ... Thanks
