### ISSUE TITLE
[Feature request] Native heartbeat

### ISSUE THREAD

**Issue by Sakarisson** [transistorsoft/react-native-background-geolocation#859]
## Note

This is a feature request rather than a bug report. I tried to keep it as close to the template as possible.

## Your Environment
* Plugin version: `3.2.2`
* Platform: iOS and Android
* React Native version: `0.60.4`
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
  debug: false,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
  disableElasticity: true,
  activityRecognitionInterval: 1000,
  stationaryRadius: 0,
  preventSuspend: true,
  heartbeatInterval: 30,
  autoSync: true,
  url: 'MY_URL',
}
```

## Desired Behavior
This question has been asked at least once before (https://github.com/transistorsoft/react-native-background-geolocation/issues/339#issuecomment-337996717).

In our app it would be highly useful to have a config option that would ping `url` with the newest location at specific or minimum intervals. 

## Actual Behavior
As far as I can tell, there is no such option. We are currently relying on `onHeartbeat`, which dies if the JS thread is suspended. 

## Context
I am working on an app where it is critical to know whether or not our users are currently active. For example, if they turn off their phone or if their device for other reasons loses connection to our servers, then we need to be aware of that to work around this issue. In many cases, our users are sitting still, so it's possible that there won't be any new location updates for some time.

We have been relying on `heartbeatInterval` for this, but recently both iOS and Android seem to have gotten stricter with allowing JS to run in the background.

**Comment by christocracy** [comment]
Just execute #getCurrentPosition in your #onHeartbeat callback.

**Comment by Sakarisson** [comment]
Will this work when the app has been terminated? It is my understanding that it won't, since the `onHeartbeat` callback runs in the JS thread.

**Comment by christocracy** [comment]
That’s what [Android Headless Mode](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode) is for.  iOS has no such concept.

**Comment by Sakarisson** [comment]
Okay. Is there no way to configure a maximum time between syncs to url?

**Comment by christocracy** [comment]
Time:  no.  But you can provide autoSyncThreshold to accurate x number records before uploading occurs.

**Comment by Sakarisson** [comment]
Thanks for answering. Hopefully it's okay that I continue a bit with my thoughts on the issue. 

My issue with the threshold and batching functionality is that there's no way to control the timing. 

For example, let's say my config is set to:

```javascript
{
  autoSync: true,
  autoSyncThreshold: 10,
  batchSync: true,
}
```

In this case, we wait until we have 10 new locations, and then send them all at once. But what if the device is just lying on the table? In this case it might take a long time before any new update is sent. 

Ideally I'd like to control the timing of these updates. The config in that case might look something like this:

```javascript
{
  autoSync: true,
  autoSyncInterval: 30,
  batchSync: true,
}
```

The above example would poll the provided URL every 30 seconds with the new locations gathered since last time. In case of no new locations, an empty array would be provided.

Do you think such functionality would be useful? If so is it even possible?

**Comment by christocracy** [comment]
>But what if the device is just lying on the table?

iOS and Android are becoming more and more strict about background operation.  For iOS, it's *impossible* to perform anything on a regular interval while your app is in the background.

`autoSyncInterval` is *impossible*.

Have you implemented [`react-native-background-fetch`](https://github.com/transistorsoft/react-native-background-fetch) (already included as a dependency).

**Comment by Sakarisson** [comment]
Sorry for the delay in getting back to this.

I understand that it's not possible to have any sort of regular intervals in the background on iOS. However, would it still be possible to have a minimum time between requests? This would ensure that devices would not send too many updates, while making sure that batches of updates would not be sent too rarely.

In this case we might have an API config that would look something like

```javascript
{
  autoSync: true,
  autoSyncMinimumTime: 30,
  batchSync: true,
}
```

On each location update, it would then check if the time since the last sync exceeds the `autoSyncMinimumTime`. If the value is less, just store the update. If the value is greater, sync the batch of updates and reset the timer.

In this way we could at least guarantee that the user wouldn't perform too many API requests, while also minimizing the likelihood of long periods of no updates.

**Comment by christocracy** [comment]
You’re aware that autoSyncThreshold is ignored when the device becomes stationary (when stopTimeout expires)?

**Comment by christocracy** [comment]
And if you manually execute #sync, autoSyncThreshold is ignored.

**Comment by Sakarisson** [comment]
Thanks for the answer. This makes sense. I think you've answered my concerns. I'll close this issue.
