### ISSUE TITLE
Location template is not working

### ISSUE THREAD

**Issue by vishgoel007** [transistorsoft/react-native-background-geolocation#860]
I have been using below configuration for my plugin. Now what i want to do is pass custom format of data on my server and for this i'm using location template field for that. But somehow it is not working and i'm getting all data on server not as per my requirement. 
I have checked logs also but not getting any error there.
## Your Environment
* Plugin version: 3.2.2
* Platform: iOS
* OS version:12.2
* Device manufacturer / model: IPhoneX
* React Native version (`react-native -v`): 0.59.10
* Plugin config: 
```javascript
{
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 1,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        foregroundService: true,
        locationAuthorizationRequest: "always",
        locationTemplate: '{"lat":<%= latitude %>,"lng":<%= longitude %>}',
        httpRootProperty: "data",
        url: "https://eny****he.x.pipedream.net",
        batchSync: false,
        autoSync: true
}
```

## Expected Behavior
This is what i supposed to get on my server.
```json
{
    "data": {
        "lat":23.23232323,
        "lng":37.37373737
      }
}
```
## Actual Behavior
This is what i'm getting on my server.
```json
{
    "data": {
        "coords": {
            "speed": 6.62,
            "longitude": -122.03649862,
            "floor": 0,
            "latitude": 37.33200038,
            "accuracy": 5,
            "altitude_accuracy": -1,
            "altitude": 0,
            "heading": 76.95
        },
        "extras": {},
        "is_moving": false,
        "event": "motionchange",
        "odometer": 0,
        "uuid": "F16F7C3B-9C5D-42E5-9A96-FD266F010A20",
        "activity": {
            "type": "unknown",
            "confidence": 100
        },
        "battery": {
            "level": -1,
            "is_charging": false
        },
        "timestamp": "2019-09-30T16:13:29.976Z"
    }
}
```

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
```
await BackgroundGeolocation.getCount()
```
You're going to find you have existing records in the plugin's database which were rendered with the default template.

**Comment by vishgoel007** [comment]
@christocracy How can i deal with this ? and is there any method to clear the database?

**Comment by christocracy** [comment]
>and is there any method to clear the database?

Of course there is.  [Search the docs](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html) for the word "destroy".

**Comment by vishgoel007** [comment]
Thanks, fixed. And sorry one last question is there any method to avoid storing locations in plugin sqlite database.

**Comment by christocracy** [comment]
>is there any method to avoid storing locations in plugin sqlite database?

Yes, buy *why*?

**Comment by christocracy** [comment]
The plugin's HTTP service operates by selecting records from the SQLite database.  If you tell the plugin not to *persist* records, you'll starve the HTTP Service and **no** records will be uploaded to your server.

Search [the docs](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html) for "HTTP Guide".

**Comment by vishgoel007** [comment]
Actually what i really want in my app to monitor location in every 10 seconds and send that monitored location to server and then delete the location from database. But somehow if any request fails then in the next 10 second cycle i want to send all failed requests together in batch.
Is this possible in this plugin? 
Sorry for being little off topic here. I'm really having hard time implementing this.

**Comment by christocracy** [comment]
Your answers are in the "HTTP Guide"

**Comment by vishgoel007** [comment]
Okay, thanks @christocracy .

**Comment by christocracy** [comment]
>my app to monitor location in every 10 second

You can't do that while the device is stationary.  The plugin tracks location when the device is *moving*.

**Comment by vishgoel007** [comment]
Okay, got it.
