### ISSUE TITLE
Multiple close locations reported at same time.

### ISSUE THREAD

**Issue by LukePenkava** [transistorsoft/react-native-background-geolocation#861]
## Your Environment
* Plugin version: 3.2.2
* Platform: iOS 
* Device manufacturer / model: iPhone6
* React Native version: 0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
            reset: true,
            disableElasticity: true,          
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 300, //900
            stopTimeout: 1,
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,
            startOnBoot: true,
            disableMotionActivityUpdates: true,
            autoSync: false,
            maxRecordsToPersist: 0
```

## Expected Behavior
Receive one location update.

## Actual Behavior
When receiving location update from field test ( was not able to reproduce in sim ) i frequently receive location update followed with next location update within one second, which is very close. Its not identical, but very close. I have distanceFilter set to 600 metres, so i am assuming it is some batched location or sample, but i am checking for samples. I am realy not sure what else i can check for to not get these additional location updates.

Here are sample data, how these location updates look like. These have same lat long, but are not duplicates.

```
latitude: 50.25261892450795
longitude: 14.31955915535536
timestamp: 2019-10-02T11:55:57.155Z
uuid: 05A2DF7B-8D5F-4B3E-A9CC-8BF1AA6F9354

latitude: 50.25261892450795
longitude: 14.31955915535536
timestamp: 2019-10-02T11:55:57.900Z
uuid: 29343E71-F403-4590-8243-02754BDABA7D

```

**Edit:**
Here are 3 samples of data which are in same area, but are not same and are probably over the 600m range, but were reported all at one time pretty much. I am not sure if this is perhaps update containing more unreported locations. I would prefer if its possible to just send the latest location and not old unreported locations if that is the case.

```
latitude: 50.136267661955806
longitude: 14.313998600987965
timestamp: 2019-10-02T12:43:31.344Z
uuid: 889B770A-0364-420B-A2F0-A32F7738B6D6

latitude: 50.13449954178772
longitude: 14.3084545494542
timestamp: 2019-10-02T12:43:32.139Z
uuid: D3635B51-DE66-4027-B6C5-E3715D913076

latitude: 50.14558191881528
longitude: 14.308400312451932
timestamp: 2019-10-02T12:43:33.994Z
uuid: 14836629-B35F-4821-8D1B-4FDA929A3257
```

## Steps to Reproduce
Here is my full code

```
componentWillMount() {
        BackgroundGeolocation.onLocation(this.onLocation.bind(this), this.onError);
        BackgroundGeolocation.ready({
            reset: true,
            preventSuspend: true,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 600,
            stopTimeout: 1,
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,
            startOnBoot: true,
            disableMotionActivityUpdates: true,
            autoSync: false
        }, (state) => {
            if (!state.enabled) {
                BackgroundGeolocation.start(function () {
                    console.log("- Start success");
                });
            }
        }); 
    }

    componentWillUnmount() {
        BackgroundGeolocation.removeListeners();
    }

    onLocation(location) {
        if (location && this.state.userObj.userKey.length > 0) {
            if (location.sample == true) {
                return;
            }
         
            if (location.coords.speed < 5) {  
                var dist = GetDistance(location.coords.latitude, location.coords.longitude, globalLat, globalLong, this.state.units);
                var distInM = dist * 1000;       

                globalLat = location.coords.latitude;  //Global variables
                globalLong = location.coords.longitude;
              
                if (distInM > 200) {    
                    firebase.database().ref(`Users/${this.state.userObj.userKey}/location`)
                        .push({
                            latitude: location.coords.latitude,
                            longitude: location.coords.longitude,  
                            timestamp: time,
                            distance: distInM,
                            data: location 
                        })
                        .catch(error => console.log(error))                      
                }
            }
        }
    }
```

**Comment by christocracy** [comment]
It's impossible to say without a picture.  Do you have a map to show me?

![](https://dl.dropbox.com/s/7ubf209miqk6qle/Screenshot%202019-10-02%2010.15.06.png?dl=1)

**Comment by LukePenkava** [comment]
@christocracy The most typical example of the issue is the first case, where the map data ( lat and long ) are exactly same, but the second data come like second after that. So with the map image, you would get only two data point on exactly same location. Previous location is for example kilometer away. Everything works fine, except for this additional location data being sent.

I am about to go field test with these settings changed from preventSuspend: true,
to preventSuspend: false and maxRecordsToPersist: 0. Not sure how much this can be of help.

Thanks.

**Comment by christocracy** [comment]
> maxRecordsToPersist: 0.

Why?

Why don't you configure your app to post locations to my demo server, so you can *see* the results easily on a map?

[BackgroundGeolocation.transistorTrackerParams](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#transistortrackerparams)

**Comment by LukePenkava** [comment]
@christocracy I dont know if maxRecordsToPersist will do anything, since its probably working only for http url, but it seems that there is some batching happening and i could not finding anything else for that in the config.

I am sorry, i dont see much point in seeing the locations on map. I might do it if nothing else works, but the data are very simple. I get location update once in about every kilometer correctly and then it for some reasons sends more similar locations in that area at the same time. That looks like some batching or something like that.
 I was just wondering if you might have some idea what could be causing it. I might setup your testing environment for locations if needed, but it seems to me like there is just some config settings i am missing.

**Comment by christocracy** [comment]
Without logs and a corresponding picture, impossible to speculate.

**Comment by LukePenkava** [comment]
@christocracy I understand it would be helpful to get those, but i am not using the url to upload the data, but custom call to firebase in onLocation. Would those data be of any relevance then ? I also dont have installed react-native-device-info right now, so i would have to install that, and then it seems the data are not representative for my use case, thats why i would prefer to solve it directly with these data.
 Could you just please point me in some direction why i could be getting data like this, i can then try to fix it, i just have no idea why is the plugin data like this ( ie cached/batched ). I just need to know whats the reason that multiple data are sent at one time. Thank you.


**Data 1 ( same as Data 3)** 
latitude: 50.0872
longitude: 14.4741
timestampe: 2019-10-03T15:35:31.899Z

**Data 2 ( different from Data 1 and Data 3, but 2 minutes later after Data3 eventho its sent before Data 3 )**
latitude: 50.0795
longitude: 14.4803
timestampe: 2019-10-03T15:37:21.629Z

**Data 3 ( same as Data 1, 2 minutes before Data 2)**
latitude: 50.0872
longitude: 14.4741
timestampe: 2019-10-03T15:35:31.899Z

**Comment by christocracy** [comment]
logs.

**Comment by LukePenkava** [comment]
@christocracy could you at least please read what i sent you ?

**Comment by LukePenkava** [comment]
For anyone else having similar issue, these two settings seem to have fixed the issue on top of my config

```
stationaryRadius: 100,
preventSuspend: true
```
