### ISSUE TITLE
GPS updating without Network is possible (IOS)?

### ISSUE THREAD

**Issue by ramkey-akil** [transistorsoft/react-native-background-geolocation#862]

**Comment by christocracy** [comment]
Yes.  It can sometimes track on commercial airline flights.  Gps even works in airplane mode.

**Comment by ramkey-akil** [comment]
Thanks @christocracy

**Comment by christocracy** [comment]
This plugin was originally designed for tracking emergency-workers in disaster zones.  One of its primary needs was the ability to operate in disconnected environments where the cell network is likely destroyed by an earthquake or hurricane.  It had to continue to track and queue all recorded locations and upload them once a network connection was re-established (eg: workers return to base-station where there was a satellite internet connection).
