### ISSUE TITLE
Allow once option is showing instead always option in location permission popup

### ISSUE THREAD

**Issue by vishgoel007** [transistorsoft/react-native-background-geolocation#863]
I'm not getting Always Allow option in my location permission popup because of this the user have to face the location permission popup every time when app is opened. 
## Your Environment
* Plugin version: 3.2.2
* Platform: iOS
* OS version: 13.1
* Device manufacturer / model: Iphone 6s
* React Native version (`react-native -v`):0.59.10
* Plugin config
```desiredAccuracy: 0,
        distanceFilter: 10,
        stopTimeout: 10,
        debug: false,
        disableElasticity: true,
        stationaryRadius: 25,
        stopAfterElapsedMinutes: 0,
        useSignificantChangesOnly: false,
        logLevel: this.BGeo.LOG_LEVEL_ERROR,
        stopOnTerminate: false,
        startOnBoot: true,
        stopOnStationary: false,
        persistMode: this.BGeo.PERSIST_MODE_LOCATION,
        foregroundService: true,
        locationAuthorizationRequest: "Always",
        maxBatchSize: 100, // for http request body array
        maxDaysToPersist: 4,
        maxRecordsToPersist: -1,
        locationTemplate: `{ "latitude":<%= latitude %>, "longitude":<%= longitude %>,"timestamp":"<%= timestamp %>"}`,
        httpRootProperty: ".",
        url:
          "https://us*****v1/coordinates",
        batchSync: true,
        autoSync: true,
        autoSyncThreshold: 1
```

## Expected Behavior
There should be three options in location permission popup as below:
`Only While using this app`
`Always Allow`
`Don't Allow`

## Actual Behavior
This is what i actually getting in mentioned device location permission popup:
`Only While using this app`
`Allow Once`
`Don't Allow`

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

**Comment by christocracy** [comment]
Welcome to iOS 13:
https://link.medium.com/UNt60Ze6t0

**Comment by vishgoel007** [comment]
@christocracy  It is mentioned in the article that user will get another pop up if he had chosen Only While using this app option after unlocking the phone. But i haven't  received another popup.

**Comment by christocracy** [comment]
You can test it in the simulator as I've done in the video in the blog above.  Notice how I used the power button on the simulator to turn off the screen then waited several seconds before "unlocking" the device.  Repeat that several times until you see the popup.
