### ISSUE TITLE
Android 10 and ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#864]
https://developer.android.com/training/location/receive-location-updates#request-background-location says:

> If your app targets Android 10 or higher, you must declare the ACCESS_BACKGROUND_LOCATION permission

Does this plugin require ACCESS_BACKGROUND_LOCATION if the encompassing app targets android 10?

It sounds like it does, but it's not mentioned in the documentation, AFAICT.

**Comment by christocracy** [comment]
The plugin has its own AndroidManifest containing all the required permissions.

You need not concern yourself with that.
