### ISSUE TITLE
Error while installing npm package on local machine.

### ISSUE THREAD

**Issue by sohel-khan** [transistorsoft/react-native-background-geolocation#865]
Hello @christocracy 

We are getting the error while installing npm package on local machine.
We are having the license key, here is the username for the same : rohanray@gmail.com
Hoping to get ASAP response from your side, as we are stuck in the release.
![Error](https://user-images.githubusercontent.com/32650196/66253965-63a9fb00-e78d-11e9-8a83-1f6413edeeca.png)

Below is the list of all information:

- react : 16.3.1

- react-native : 0.55.4

-  compileSdkVersion   = 26
  

-   targetSdkVersion    = 26

    

- buildToolsVersion   = "26.0.2"

  

-   supportLibVersion   = "26.1.0"

  

-   googlePlayServicesVersion = "11.6.0"

    

- minSdkVersion       = 16

And here is the list of all files below : 

**AndroidManifest.xml :** 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.recaho.tracker">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait"
        android:launchMode="singleTop"
      >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      
      <activity android:name="com.imeigetter.GPSMainActivity" android:noHistory="true" android:configChanges="keyboard|keyboardHidden|orientation|screenSize" android:screenOrientation="portrait" />
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

      <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="*****7c669576580327fb13ce58ca8********" />
    
    </application>

</manifest>

**Package.json** : 

{
  "name": "tracker",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "apollo-boost": "^0.1.6",
    "apollo-client": "^2.3.1",
    "aws-appsync": "^1.1.1",
    "aws-appsync-react": "^1.0.16",
    "aws-sdk": "^2.235.1",
    "geolib": "^2.0.24",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.9.2",
    "istanbul-lib-hook": "^1.1.0",
    "moment": "^2.22.1",
    "native-base": "^2.4.3",
    "react": "16.3.1",
    "react-apollo": "^2.1.2",
    "react-native": "0.55.4",
    "react-native-background-fetch": "^2.4.3",
"react-native-background-geolocation-android": "https://github.com/transistorsoft/react-native-background-geolocation-android.git",
    "react-native-device-info": "0.21.5",
    "react-native-easy-grid": "^0.1.15",
    "react-native-exit-app": "^1.0.0",
    "react-native-splash-screen": "^3.0.9",
    "react-navigation": "^2.0.4"
  },
  "devDependencies": {
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Android/app/build.gradle** : 

apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = true

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        applicationId "com.xyz.tracker"
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 18
        versionName "1.0.8"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            storeFile file(XYZ_TRACKER_PROJECT_RELEASE_STORE_FILE)
            storePassword XYZ_TRACKER_PROJECT_RELEASE_STORE_PASSWORD
            keyAlias XYZ_TRACKER_PROJECT_RELEASE_KEY_ALIAS
            keyPassword XYZ_TRACKER_PROJECT_RELEASE_KEY_PASSWORD
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release // add this line as well
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->

            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-exit-app')
    compile project(':react-native-splash-screen')
    compile project(':react-native-background-geolocation-android')
    compile project(':react-native-background-fetch')
    compile(project(':react-native-device-info')) {
        exclude group: 'com.google.android.gms'
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.android.support:appcompat-v7:$rootProject.supportLibVersion"

    // Override play-services version
    compile ("com.google.android.gms:play-services-base:11.6.0") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-location:11.6.0") {
        force = true;
    }
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

**Android/build.gradle** : 

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'

    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }

        maven {
            url 'https://maven.google.com'
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation-android/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}

ext {
    compileSdkVersion   = 26
    targetSdkVersion    = 26
    buildToolsVersion   = "26.0.2"
    supportLibVersion   = "26.1.0"
    googlePlayServicesVersion = "11.6.0"
    minSdkVersion       = 16
}

**Comment by christocracy** [comment]
https://help.github.com/en/articles/caching-your-github-password-in-git
