### ISSUE TITLE
[QUESTION] [iOS] Triggering logic after `stopTimeout` (app is background/terminated)

### ISSUE THREAD

**Issue by duyphambhtech** [transistorsoft/react-native-background-geolocation#867]
## Your Environment
* Plugin version: 3.0.2
* Platform: iOS
* OS version: 12.4
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`): 0.59.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
Platform.select({
  android: {
    desiredAccuracy: 10,
    stopTimeout: 20,
    stopOnTerminate: false,
    enableHeadless: true
  },
  ios: {
    desiredAccuracy: 10,
    stopTimeout: 20,
    stopOnTerminate: false,
    preventSuspend: false, // will be set to true when a journey starts, and back to false when it finishes
    heartbeatInterval: 60
  }
})
```

## Expected Behavior

Desired Behavior actually: triggering some logic once, even if app is in background/terminated, when User stays still after `stopTimeout`.
(More in Context)

## Actual Behavior

If iOS app is terminated, and User stays still, there seems to be no code running (as expected, since User does not exit the geofence that trigger BackgroundGeolocation to resume tracking)
(More in Context)

## Context

This is more of a general question instead of an issue.
We're implementing a journey tracking app, and currently there's a feature request to trigger auto-stop logic once the User is still after a set amount of Time.
One requirement is to store all data locally, app works mainly offline, so there's no server logic involved.
On Android, we use `registerHeadlessTask` successfully, and once `stopTimeout` elapsed, there's an event `name: activitychange` with `params: { activity: still }` for us to trigger our logic to finalize the journey data (this involves some calculation of other, unrelated data). This is triggered even if our app is terminated.
However, on iOS, we haven't been able to replicate the flow. `preventSuspend` does maintain the app location tracking even in background, screen locked as expected. However, once the app is terminated, and User stays still, there seems to be no code running (the same as I read from other similar issue threads)
I've examined both the Philosophy of Operation and API Documentation, but haven't found any clear direction to handle auto stop logic after `stopTimeout` on iOS

Here's my question:

**Is it only possible to handle the auto stop logic on iOS (triggering logic when iOS app is in background/terminated, after User is still for `stopTimeout` duration) with BackgroundFetch event? Or is there any other config I've overlooked on iOS?**

**Comment by christocracy** [comment]
iOS has no problem running your code in the background when stopTimeout expires, when the #onMotionChange event fires.  However, if the iOS app is terminated, the entire app process is terminated.  No code is running.  Yes, you will want to subscribe to background-fetch events, but fetch events halt when *the user* terminates the app.  The *only* thing that will re-awaken it will be to move ~200 meters.

**Comment by duyphambhtech** [comment]
Thank you very much for the swift answer.
We will see if we're able to change the requirements.
