### ISSUE TITLE
Get wrong coordinates for the geolocation

### ISSUE THREAD

**Issue by sohel-khan** [transistorsoft/react-native-background-geolocation#868]
@christocracy 

## Your Environment
* Plugin version:3.2.2
* Platform: Android
* React Native version (`react-native -v`): 0.61.2
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

Get current location coordinates accurately

## Actual Behavior

The location coordinates are not accurate, the location of device shows away from the actual on field location.
The geolocation jumps from one coordinate to other coordinate away for a distance of 500 meters and above.

## Steps to Reproduce

1.open app by clicking app icon in screen

## Context

I want to track the user activity, but the location coordinates are not correct, and that's the reason inaccurate data is generated.

I have attached the log file to issue. Please check and do let us know.
Please provide an appropriate solution to solve this.

[LogfileTrackerApp.log](https://github.com/transistorsoft/react-native-background-geolocation/files/3712683/LogfileTrackerApp.log)

**Comment by christocracy** [comment]
What time(s) in the log are you interested in?

**Comment by sohel-khan** [comment]
@christocracy it's not specific time or specific location. Please consider this scenario stated below :

1. User 'A' starts at 'X' position, but the position which are coming are inaccurate, i.e. say 'X1'.
2. When User 'A' starts to move to direction say 'Y', the coordinates jumps to different location say 'Z'.
3. This is the issue which is causing inappropriate data of the user to track the user activities.

Expected Outcome: User 'A' => starts at 'X' position => travels 'W' position => ends at 'Y' position.
Actual Outcome: User 'A' => starts at 'X1' position => travels 'U' position => ends at 'Z' position.

We want to know what is causing this behaviour of the API ?

**Comment by christocracy** [comment]
What *specific* time(s) in the log are you interested in?

>We want to know what is causing this behaviour of the API ?

The plugin is only the messenger, delivering locations to you exactly as provided by the device's location services API.

**Comment by sohel-khan** [comment]
@christocracy Is this due to the devices that is causing the inaccurate location coordinates ?
If the device is causing the issue then, is there any solution do you know ?
The devices are latest Android devices.

**Comment by christocracy** [comment]
What specific time(s) in the log are you interested in?

configure your app to post to the test server and go for a field-test.  [BackgroundGeolocation.transistorTrackerParams](https://transistorsoft.github.io/react-native-background-geolocation-android/classes/_react_native_background_geolocation_android_.backgroundgeolocation.html#transistortrackerparams)

**Comment by sohel-khan** [comment]
@christocracy forget about the time(s) from the log.

We just need to know why their is discrepancy between the actual geolocation and the response which we are getting through the library for the coordinates.

And one more solution is needed from you. When we have less sensor's on the phone or a low quality phone, at that time how we can use the library, as we need to have exact geolocation coordinates to track the user.

**Comment by christocracy** [comment]
> When we have less sensor's on the phone or a low quality phone,

You can’t squeeze blood from a stone.  The plugin provides location data to you exactly as provided by the device api.  There is no “magic”.

**Comment by sohel-khan** [comment]
@christocracy there is a situation where user is in idle state, and when the user start's again and if there is no motion sensor on the device, the motion change event will not fire up, and it will show the same location when the user was in idle state.

Is there any solution to solve this issue where the phone has less sensor's ?

**Comment by christocracy** [comment]
The plugin already has built-in safety mechanisms developed over the last 5 years for devices with poor sensors, including a stationary geofence around the last known location, the exit of which will cause the plugin to engage tracking.  

Once the device is detected to be moving, the plugin compares the distance of the current location with that of the last.  If, in spite of the motion api stating the device is stationary, there is a distance > stationaryRadius meters between those 2 locations, the plugin will cancel the stopTimeout timer.

This behavior can be observed in the logs.

**Comment by sohel-khan** [comment]
@christocracy I have uploaded the images for your reference, this green pin-point is the start location. The start and end location are same with our current location coordinates. But there is a jump of coordinates which give us wrong location. As you can see in the images as well.

This are the current coordinates which is our actual location : 
latitude : 18.5941168, longitude : 73.78918849999998

![UserTrack](https://user-images.githubusercontent.com/32650196/66731060-f6742500-ee72-11e9-8a2f-9dbf7d4351ab.png)
![UserTrack-1](https://user-images.githubusercontent.com/32650196/66731062-f70cbb80-ee72-11e9-81b3-52bce34dcc9a.png)
![UserTrack-2](https://user-images.githubusercontent.com/32650196/66731063-f70cbb80-ee72-11e9-8541-97f1a9ba1011.png)
![UserTrack-3](https://user-images.githubusercontent.com/32650196/66731064-f7a55200-ee72-11e9-9294-45465699a537.png)

**Comment by christocracy** [comment]
Your images are not at all unusual.  When the device is indoors, gps in unavailable so those locations can only come from WiFi, whose accuracy is typically 40-60 meters.

You are looking at the results through a microscope.  Go outside for a 5km field test and you see the plugin track so well that you can tell which side of the street the device is on.  Those little jumps while the device is stationary indoors are of no consequence.  Filter them out at your server as desired.  Gps accuracy is typically 5-10 meters; WiFi ~40-60 meters.

**Comment by christocracy** [comment]
> When the device is indoors, gps in unavailable

Or obstructed by the environment: bridges/overpasses, tall buildings, mountains, large bodies of water

**Comment by GurjeetLamba** [comment]
@sohel-khan  How did you resolve this issue As I am facing the same issue , I am not getting accurate location coordinates

**Comment by samp84531** [comment]
same
