### ISSUE TITLE
How to getting Location only from GPS ?

### ISSUE THREAD

**Issue by ramkey-akil** [transistorsoft/react-native-background-geolocation#869]

**Comment by christocracy** [comment]
Native location apis don’t allow one to specifically receive location from gps.  They automatically provide the best available location.

If the device is outdoors, the location will most likely come from gps (unless obstructed by the environment; tall buildings, bridges, tunnels, mountains).

If the device is indoors, the location will most likely come from WiFi.

If both gps and WiFi are unavailable, location comes from Cellular.

If you want location from gps, go outside.
