### ISSUE TITLE
StopOnTerminate does not resume as expected

### ISSUE THREAD

**Issue by Sakarisson** [transistorsoft/react-native-background-geolocation#870]
## Note
- I only tested this on iOS 13.1 on an iPhone XS. I do not know for sure if this issue is relevant for iOS 12 or older and for other iPhones.

## Your Environment
* Plugin version: `3.2.2`
* Platform: `iOS`
* OS version: `13.1`
* Device manufacturer / model: `iPhone XS`
* React Native version: `0.60.4`
* Plugin config
```javascript
const config = {
  reset: false,
  debug: true,
  logLevel: __DEV__
    ? BackgroundGeolocation.LOG_LEVEL_VERBOSE
    : BackgroundGeolocation.LOG_LEVEL_ERROR,
  pausesLocationUpdatesAutomatically: false,
  disableStopDetection: true,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
  preventSuspend: true,
  heartbeatInterval: 30,
  stopOnTerminate: false,
  httpRootProperty: '.',
  autoSync: true,
  url: 'my_url', // redacted
  locationTemplate:
    '{"location": {"latitude": <%= latitude %>, "longitude": <%= longitude %>}, "accuracy": <%= accuracy %>, "heading": <%= heading %>, "speed": <%= speed %>, "timestamp": "<%= timestamp %>"}',
};
```

## Expected Behavior
If my app gets terminated, it should reboot and continue running in the background when I go outside of a geofence.

## Actual Behavior
If the app gets killed by the system, it will reboot in the background but not get any location updates. If I kill the app myself, then it will eventually reboot and continue sending location updates.

## Steps to Reproduce
1. Turn on RN app with permission to always get background geolocation.
2. Minimize app and open Apple Maps in the foreground.
3. Wait until iOS terminates the RN app.
4. After moving outside of the stationary geofence, observe a push notification indicating that the "Authorization status changed 3" event occurred.
5. Even though the app has rebooted in the background, no location updates will be sent to the server, and no "SMS sent sound" occurs, indicating that the library is unable to detect location updates.

If you manually kill the RN app by force quitting in 2-3 rather than waiting for iOS to kill it, it will be able to send location updates when it reboots.

## Context
For our project, we only use the library for iOS.
I've noticed that iOS 13 is eager to terminate our app when there's some other battery-intensive activity going on in the foreground, such as navigating with Apple Maps (this is a very common use-case for our users). From my testing, it seems like iOS terminates our app after only around a minute of being in the background in this case. This happens regardless of the fact that I've set `preventSuspend` to true.

I had assumed that `stopOnTerminate: false` would at least mitigate this issue, as it should allow our app to continue sending updates after our users have moved a bit. However, this does not seem to be the case. I don't know if this is a bug with the library, if there's something I am doing wrong, or if this is simply a reality of iOS 13 that we will have to learn to live with.

**Comment by christocracy** [comment]
It doesn't matter if user or os terminates the app.

**Comment by Sakarisson** [comment]
If you don't believe my report is accurate, then I can make a recording of it happening

**Comment by christocracy** [comment]
I've been testing iOS 13 since august.  It doesn't perform any different on iOS 13 vs 12.

http://tracker.transistorsoft.com/transistor-rn

I run the SampleApp for RN, Cordova and Flutter simultaneously and monitor my results daily.

**Comment by christocracy** [comment]
I suggest you install the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo) on your device and test in isolation of your application code.

**Comment by Sakarisson** [comment]
I'll follow your suggestion and test the SampleApp. When you do your daily testing, how do you make sure that the system terminates the app? 

I don't know what logic goes into terminating an app, but for some reason, my phone doesn't terminate the SampleApp under the same conditions.

**Comment by christocracy** [comment]
>how do you make sure that the operating system terminates the app?

You can be sure that iOS is *always* terminating your app in the background to free up memory for the current foreground service.

**Comment by Sakarisson** [comment]
When you say *always*, do you mean that iOS will under all circumstances terminate my app immediately when it is in the background?

**Comment by christocracy** [comment]
Not immediately, but some time in the near future.

**Comment by Sakarisson** [comment]
I did some more digging and found out that the described behavior only happens when the app gets terminated from too much CPU usage. When it gets killed to save memory, it does resume sending background location updates, as expected. I was able to reproduce these results with the official demo app.

## Memory usage termination

In `App.js` (or anywhere else where the code will be executed immediately), add the following snippet. This introduces a massive memory leak into the app. 

```javascript
const memoryLeakContainer = []

const memoryLeaker = () => {
  for (let i = 0; i < 1000000; i++) {
    memoryLeakContainer.push(new Array(100).fill('Hello world!'))
  }
}

setInterval(() => memoryLeaker())
```

Open the app and immediately put it in the background. It will be terminated after only a few seconds. Move out of the stationary geofence, and observe that location updates will resume in the background.

## CPU usage termination

In `App.js` (or anywhere else where the code will be executed immediately), add the following snippet. This will basically consume 100% of your CPU without totally blocking the JS thread.

```javascript
const cpuIntensiveFunction = () => new Promise(r => {
  const arr = new Array(10000000).fill(123)
  arr.forEach(el => el ^ 6)
  setTimeout(r, 10)
})

const cpuIntensiveFunctionForever = async () => {
  while(true) {
    await cpuIntensiveFunction()
  }
}

cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
cpuIntensiveFunctionForever()
```

Put the app in the background, and notice that it will be terminated pretty quickly. The background location updates will never resume.

**Comment by christocracy** [comment]
My iPhone 11 Pro simulator survives your CPU attack and successfully reboots to engage tracking.

**Comment by Sakarisson** [comment]
Do you have a physical device? Not sure about the internal workings of simulators, but I was also only able to replicate this on real devices (an iPhone XS and an iPhone 6s)

**Comment by christocracy** [comment]
I have no issues on my iPhone 11 pro, 6s.  Doesn’t matter if I kill the app.  It always resumes tracking.  Test the sample app.

**Comment by Sakarisson** [comment]
Thanks in advance for trying to replicate this issue.

Can you verify that you ran the CPU-intensive code on a physical device, and then put it in the background and had the system terminate it? To me, your statement is slightly ambiguous. I'm not sure if you manually killed the app or if you waited for the system to do it. 

When I do the steps above, the app gets cut off with the final message: `Message from debugger: Terminated due to signal 9`. After this, the app behaves as described in the original issue description.

If I kill the app manually, the final entries in the log indicate that there is some logic being done to set up the stationary radius. 

```
ℹ️-[TSDBLogger db_save] Log committed
2019-10-22 16:59:31.491433+0300 BGGeolocation[2834:34178] ℹ️-[TSDBLogger db_save] Log committed
🔵-[TSLocationManager onAppTerminate] stopOnTerminate? 0
2019-10-22 16:59:31.496202+0300 BGGeolocation[2834:34180] 🔵-[TSLocationManager onAppTerminate] stopOnTerminate? 0
2019-10-22 16:59:31.502406+0300 BGGeolocation[2834:33717] [TSBackgroundFetch onAppTerminate]
2019-10-22 16:59:31.502587+0300 BGGeolocation[2834:33717] [TSBackgroundFetch stop]
2019-10-22 16:59:31.508648+0300 BGGeolocation[2834:34180] 🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 150
🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 150
```

Again, when I kill the app manually, `stopOnTerminate: false` behaves as expected. It's only when I let the system kill it from using too much CPU in the background that it does not.

I did all of this in the sample app. Specifically, I had the `SimpleMap` view open when putting the app in the background.

**Comment by christocracy** [comment]
If the system is not starting the app for some reason, there's nothing the plugin can do to force it.  The plugin is monitoring the significant location changes and geofencing APIs.  Events upon both those APIs cause a terminated iOS to be re-launched in the background.

**Comment by Sakarisson** [comment]
Alright, thanks for the information. Seems like this problem isn't solvable. 

On the positive side, this prompted me to fix a lot of the heavy CPU usage of our app.
