### ISSUE TITLE
'CocoaLumberjack/CocoaLumberjack.h' file not found, in file included from DDFileLogger+Buffering.m

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#872]
I'm getting an error 'CocoaLumberjack/CocoaLumberjack.h' file not found in file included from DDFileLogger+Buffering.m, this error appears in file DDFileLogger+Internal.h after the installation of the library. I migrated from ExpoKit project to bare workflow expo project. 

## Your Environment
* Plugin version:"^3.2.2" 
* Platform: iOS
* OS version: all
* Device manufacturer / model: all
* React Native version (`react-native -v`):0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior

I can build a project 

## Actual Behavior

I can't build a project

## Steps to Reproduce

1. Add library 
2. try to build a project

## Context

I have cocoa pods in the project 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Remove the plugin and re-add via react-native link instructions in readme.

**Comment by Luckygirlllll** [comment]
@christocracy I  added the plugin via react-native link instruction, should I remove it all do the same thing once again? Wouldn't I get the same result?

**Comment by Luckygirlllll** [comment]
@christocracy By plugin you mean react-native-background-geolocation library or CocoaLumberjack?

**Comment by christocracy** [comment]
Show me your ios/Podile

**Comment by Luckygirlllll** [comment]
here is the file: 

```
platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'com.civicchamps' do
  # Pods for com.civicchamps
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNReanimated', :podspec => '../node_modules/react-native-reanimated/RNReanimated.podspec'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  
  pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'
  
  # react-native-maps dependencies
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  
   pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  use_unimodules!

#  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
#  
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      targets_to_ignore = %w(React yoga)
           
           if targets_to_ignore.include? target.name
             target.remove_from_project
           end
      
      
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end

```

**Comment by Luckygirlllll** [comment]
Here is also Podfile.lock, if it will help:

```
PODS:
  - boost-for-react-native (1.63.0)
  - CocoaLumberjack (3.5.3):
    - CocoaLumberjack/Core (= 3.5.3)
  - CocoaLumberjack/Core (3.5.3)
  - Crashlytics (3.14.0):
    - Fabric (~> 1.10.2)
  - DoubleConversion (1.1.6)
  - EXAppLoaderProvider (7.0.0)
  - EXConstants (7.0.0):
    - UMConstantsInterface
    - UMCore
  - EXFileSystem (7.0.0):
    - UMCore
    - UMFileSystemInterface
  - EXFont (7.0.0):
    - UMCore
    - UMFontInterface
  - EXKeepAwake (7.0.0):
    - UMCore
  - EXLinearGradient (7.0.0):
    - UMCore
  - EXLocation (7.0.0):
    - UMCore
    - UMPermissionsInterface
    - UMTaskManagerInterface
  - EXPermissions (7.0.0):
    - UMCore
    - UMPermissionsInterface
  - EXSQLite (7.0.0):
    - UMCore
    - UMFileSystemInterface
  - EXWebBrowser (7.0.1):
    - UMCore
  - Fabric (1.10.2)
  - Folly (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - JKBigInteger2 (0.0.5)
  - OneSignal (2.11.2)
  - React (0.59.10):
    - React/Core (= 0.59.10)
  - react-native-maps (0.25.0):
    - React
  - react-native-onesignal (3.4.2):
    - OneSignal (= 2.11.2)
    - React (< 1.0.0, >= 0.13.0)
  - React/Core (0.59.10):
    - yoga (= 0.59.10.React)
  - React/CxxBridge (0.59.10):
    - Folly (= 2018.10.22.00)
    - React/Core
    - React/cxxreact
    - React/jsiexecutor
  - React/cxxreact (0.59.10):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React/jsinspector
  - React/DevSupport (0.59.10):
    - React/Core
    - React/RCTWebSocket
  - React/fishhook (0.59.10)
  - React/jsi (0.59.10):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
  - React/jsiexecutor (0.59.10):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React/cxxreact
    - React/jsi
  - React/jsinspector (0.59.10)
  - React/RCTActionSheet (0.59.10):
    - React/Core
  - React/RCTAnimation (0.59.10):
    - React/Core
  - React/RCTBlob (0.59.10):
    - React/Core
  - React/RCTGeolocation (0.59.10):
    - React/Core
  - React/RCTImage (0.59.10):
    - React/Core
    - React/RCTNetwork
  - React/RCTLinkingIOS (0.59.10):
    - React/Core
  - React/RCTNetwork (0.59.10):
    - React/Core
  - React/RCTSettings (0.59.10):
    - React/Core
  - React/RCTText (0.59.10):
    - React/Core
  - React/RCTVibration (0.59.10):
    - React/Core
  - React/RCTWebSocket (0.59.10):
    - React/Core
    - React/fishhook
    - React/RCTBlob
  - ReactNativeFabric (0.5.2):
    - Crashlytics
    - Fabric
    - React
  - RNAWSCognito (3.0.15):
    - JKBigInteger2 (= 0.0.5)
    - React
  - RNBackgroundFetch (2.7.1):
    - React
  - RNBackgroundGeolocation (3.2.2):
    - CocoaLumberjack (~> 3.5.1)
    - React
  - RNGestureHandler (1.3.0):
    - React
  - RNReanimated (1.3.0):
    - React
  - RNScreens (1.0.0-alpha.23):
    - React
  - UMBarCodeScannerInterface (4.0.0)
  - UMCameraInterface (4.0.0)
  - UMConstantsInterface (4.0.0)
  - UMCore (4.0.0)
  - UMFaceDetectorInterface (4.0.0)
  - UMFileSystemInterface (4.0.0)
  - UMFontInterface (4.0.0)
  - UMImageLoaderInterface (4.0.0)
  - UMPermissionsInterface (4.0.0)
  - UMReactNativeAdapter (4.0.0):
    - React
    - UMCore
    - UMFontInterface
  - UMSensorsInterface (4.0.0)
  - UMTaskManagerInterface (4.0.0)
  - yoga (0.59.10.React)

DEPENDENCIES:
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - EXAppLoaderProvider (from `../node_modules/expo-app-loader-provider/ios`)
  - EXConstants (from `../node_modules/expo-constants/ios`)
  - EXFileSystem (from `../node_modules/expo-file-system/ios`)
  - EXFont (from `../node_modules/expo-font/ios`)
  - EXKeepAwake (from `../node_modules/expo-keep-awake/ios`)
  - EXLinearGradient (from `../node_modules/expo-linear-gradient/ios`)
  - EXLocation (from `../node_modules/expo-location/ios`)
  - EXPermissions (from `../node_modules/expo-permissions/ios`)
  - EXSQLite (from `../node_modules/expo-sqlite/ios`)
  - EXWebBrowser (from `../node_modules/expo-web-browser/ios`)
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - react-native-maps (from `../node_modules/react-native-maps`)
  - react-native-onesignal (from `../node_modules/react-native-onesignal`)
  - React/Core (from `../node_modules/react-native`)
  - React/CxxBridge (from `../node_modules/react-native`)
  - React/DevSupport (from `../node_modules/react-native`)
  - React/RCTActionSheet (from `../node_modules/react-native`)
  - React/RCTAnimation (from `../node_modules/react-native`)
  - React/RCTBlob (from `../node_modules/react-native`)
  - React/RCTGeolocation (from `../node_modules/react-native`)
  - React/RCTImage (from `../node_modules/react-native`)
  - React/RCTLinkingIOS (from `../node_modules/react-native`)
  - React/RCTNetwork (from `../node_modules/react-native`)
  - React/RCTSettings (from `../node_modules/react-native`)
  - React/RCTText (from `../node_modules/react-native`)
  - React/RCTVibration (from `../node_modules/react-native`)
  - React/RCTWebSocket (from `../node_modules/react-native`)
  - ReactNativeFabric (from `../node_modules/react-native-fabric`)
  - RNAWSCognito (from `../node_modules/amazon-cognito-identity-js`)
  - RNBackgroundFetch (from `../node_modules/react-native-background-fetch`)
  - RNBackgroundGeolocation (from `../node_modules/react-native-background-geolocation`)
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler/RNGestureHandler.podspec`)
  - RNReanimated (from `../node_modules/react-native-reanimated/RNReanimated.podspec`)
  - RNScreens (from `../node_modules/react-native-screens`)
  - UMBarCodeScannerInterface (from `../node_modules/unimodules-barcode-scanner-interface/ios`)
  - UMCameraInterface (from `../node_modules/unimodules-camera-interface/ios`)
  - UMConstantsInterface (from `../node_modules/unimodules-constants-interface/ios`)
  - "UMCore (from `../node_modules/@unimodules/core/ios`)"
  - UMFaceDetectorInterface (from `../node_modules/unimodules-face-detector-interface/ios`)
  - UMFileSystemInterface (from `../node_modules/unimodules-file-system-interface/ios`)
  - UMFontInterface (from `../node_modules/unimodules-font-interface/ios`)
  - UMImageLoaderInterface (from `../node_modules/unimodules-image-loader-interface/ios`)
  - UMPermissionsInterface (from `../node_modules/unimodules-permissions-interface/ios`)
  - "UMReactNativeAdapter (from `../node_modules/@unimodules/react-native-adapter/ios`)"
  - UMSensorsInterface (from `../node_modules/unimodules-sensors-interface/ios`)
  - UMTaskManagerInterface (from `../node_modules/unimodules-task-manager-interface/ios`)
  - yoga (from `../node_modules/react-native/ReactCommon/yoga`)

```
SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - boost-for-react-native
    - CocoaLumberjack
    - Crashlytics
    - Fabric
    - JKBigInteger2
    - OneSignal

EXTERNAL SOURCES:
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  EXAppLoaderProvider:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-app-loader-provider/ios"
  EXConstants:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-constants/ios"
  EXFileSystem:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-file-system/ios"
  EXFont:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-font/ios"
  EXKeepAwake:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-keep-awake/ios"
  EXLinearGradient:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-linear-gradient/ios"
  EXLocation:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-location/ios"
  EXPermissions:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-permissions/ios"
  EXSQLite:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-sqlite/ios"
  EXWebBrowser:
    :path: !ruby/object:Pathname
    path: "../node_modules/expo-web-browser/ios"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  React:
    :path: "../node_modules/react-native"
  react-native-maps:
    :path: "../node_modules/react-native-maps"
  react-native-onesignal:
    :path: "../node_modules/react-native-onesignal"
  ReactNativeFabric:
    :path: "../node_modules/react-native-fabric"
  RNAWSCognito:
    :path: "../node_modules/amazon-cognito-identity-js"
  RNBackgroundFetch:
    :path: "../node_modules/react-native-background-fetch"
  RNBackgroundGeolocation:
    :path: "../node_modules/react-native-background-geolocation"
  RNGestureHandler:
    :podspec: "../node_modules/react-native-gesture-handler/RNGestureHandler.podspec"
  RNReanimated:
    :podspec: "../node_modules/react-native-reanimated/RNReanimated.podspec"
  RNScreens:
    :path: "../node_modules/react-native-screens"
  UMBarCodeScannerInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-barcode-scanner-interface/ios"
  UMCameraInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-camera-interface/ios"
  UMConstantsInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-constants-interface/ios"
  UMCore:
    :path: !ruby/object:Pathname
    path: "../node_modules/@unimodules/core/ios"
  UMFaceDetectorInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-face-detector-interface/ios"
  UMFileSystemInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-file-system-interface/ios"
  UMFontInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-font-interface/ios"
  UMImageLoaderInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-image-loader-interface/ios"
  UMPermissionsInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-permissions-interface/ios"
  UMReactNativeAdapter:
    :path: !ruby/object:Pathname
    path: "../node_modules/@unimodules/react-native-adapter/ios"
  UMSensorsInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-sensors-interface/ios"
  UMTaskManagerInterface:
    :path: !ruby/object:Pathname
    path: "../node_modules/unimodules-task-manager-interface/ios"
  yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"

SPEC CHECKSUMS:
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  CocoaLumberjack: 2f44e60eb91c176d471fdba43b9e3eae6a721947
  Crashlytics: 540b7e5f5da5a042647227a5e3ac51d85eed06df
  DoubleConversion: bb338842f62ab1d708ceb63ec3d999f0f3d98ecd
  EXAppLoaderProvider: 98f3e889fa48b441b19c64f19193c82ebb1c15ca
  EXConstants: 11210104ab59ee1cdfb79b0466add077f59c9218
  EXFileSystem: 217d1480b63c595d0620e64d6a6845dc52229bbd
  EXFont: ce93c38bb43624eac43d283ca42e6e09496342b6
  EXKeepAwake: 97c48386fa562a57956c99a1b66b422de1fa3a19
  EXLinearGradient: 31c43522ab53d432907e0aacac445d6f4e5b1275
  EXLocation: 89ec75877fcf40b3dfeca428c898d25fce299fb3
  EXPermissions: b4e5d6e134317bfb29bed37998b7c0deab318e6d
  EXSQLite: 62f542b96081e28e239317a6dbd759aa6e7200f7
  EXWebBrowser: 52ce377fa8fc0f4832e233d625d5a5ebb2801b64
  Fabric: 706c8b8098fff96c33c0db69cbf81f9c551d0d74
  Folly: de497beb10f102453a1afa9edbf8cf8a251890de
  glog: aefd1eb5dda2ab95ba0938556f34b98e2da3a60d
  JKBigInteger2: e91672035c42328c48b7dd015b66812ddf40ca9b
  OneSignal: 4e3e68bb6c29975286a2fa910cb49132bc6e20bb
  React: 36d0768f9e93be2473b37e7fa64f92c1d5341eef
  react-native-maps: 190c02ca533fddac5bb49cf17bdece3644612107
  react-native-onesignal: ede2c185dd3c4c04bdab98f10c92dfe6f9d61c5d
  ReactNativeFabric: d05320ff347d5c72567c115b97edeead111ac4d2
  RNAWSCognito: b0b908817ce6547cdddaa7842bc166b4c5e7c128
  RNBackgroundFetch: 08bdaaa13a5aa71cdce42068def5602ed1e982c2
  RNBackgroundGeolocation: 545a8e81e1cae0252606e140973cd6434c1dfa3a
  RNGestureHandler: 5329a942fce3d41c68b84c2c2276ce06a696d8b0
  RNReanimated: 6abbbae2e5e72609d85aabd92a982a94566885f1
  RNScreens: f28b48b8345f2f5f39ed6195518291515032a788
  UMBarCodeScannerInterface: 07047b4faa779e7963efa3d2c5951a71a0a807bf
  UMCameraInterface: f6a3e71ddd928617637084bfd67db2daec3b1927
  UMConstantsInterface: 20e6caaba4ddac70d0b50827d6cf35a202ac988f
  UMCore: 01d7ed248e2d4789105292a71ce1385ff4315c53
  UMFaceDetectorInterface: 623ca9703dc664d13edf315ec930df9d2246b7d0
  UMFileSystemInterface: c7dc550ff72d2b38258f218b086b32b3de536957
  UMFontInterface: a1ec983801daad298617d00dabbfdb609325665c
  UMImageLoaderInterface: f7b69ad8dfcae00c87d70a2081af78293e445fee
  UMPermissionsInterface: 0d060960ebb35d905d74a52461a3e6ab2d43b53b
  UMReactNativeAdapter: 619f5e9769977caf4a862e8e232ce1ef5c74ac01
  UMSensorsInterface: 1d276f7fdf781a09715091bad7873c27da271e9b
  UMTaskManagerInterface: 8f2117979aacb688fe304f834ff8800fadc320bb
  yoga: 684513b14b03201579ba3cee20218c9d1298b0cc

PODFILE CHECKSUM: 49c4d1b08a35192dbe1a09c5aab646bdf68b104c

COCOAPODS: 1.7.5
```
```

**Comment by Luckygirlllll** [comment]
@christocracy IS there any updates about this issue or advices how is possible to fix it?

**Comment by christocracy** [comment]
What makes you think it's `RNBackgroundGeolocation` complaining about this?  Your project is importing `CocoaLumberjack (3.5.3)`, which satisfies what `RNBackgroundGeolocation` wants (`CocoaLumberjack (~> 3.5.1)`).

```
$ cd ios
$ rm Podfile.lock
$ pod install
```

```
PODS:
  ...
  - CocoaLumberjack (3.5.3):
    - CocoaLumberjack/Core (= 3.5.3)
  - CocoaLumberjack/Core (3.5.3)
  .
  .
  .
  - RNBackgroundGeolocation (3.2.2):
      - CocoaLumberjack (~> 3.5.1)
```

**Comment by Luckygirlllll** [comment]
@christocracy My project was working just fine, after I added background geolocation library I have started getting this error, I just have tried:

```
$ cd ios
$ rm Podfile.lock
$ pod install
```
and it didn't help, I still see in `Podfile.lock CocoaLumberjack (3.5.3)`,maybe  it's some version conflict between `3.5.3` and version `3.5.1` which is `RNBackgroundGeolocation`? However, I'm not sure how to fix it.

**Comment by Luckygirlllll** [comment]
Is there any ways to remove CocoaLumberjack (3.5.3) from the project? or downgrade it to 3.5.1?

**Comment by christocracy** [comment]
RNBackgroundGeolocation requests [`CocoaLumberjack', '~> 3.5.1'`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/RNBackgroundGeolocation.podspec#L22)

What does [`~> 3.5.1` mean](https://stackoverflow.com/questions/20213751/what-is-the-usage-of-in-cocoapods)?  

`RNBackgroundGeolocation` will be perfectly happy with `CocoaLumberjack 3.5.3`.

**Comment by christocracy** [comment]
I suggest you have a look at this:
```
require_relative '../node_modules/react-native-unimodules/cocoapods'
```

**Comment by christocracy** [comment]
This isn't the first time you've had issues with Expo/CocoaLumberjack.
https://github.com/expo/expo/issues/4481

**Comment by Luckygirlllll** [comment]
@christocracy I know, I removed expoKit and now use bare expo workflow with `react-native-unimodules`

Here is the ../node_modules/react-native-unimodules/cocoapods file: 

```
require 'json'
require 'pathname'
require 'optparse'

def use_unimodules!(custom_options = {})
  options = {
    modules_paths: ['../node_modules'],
    target: 'react-native',
    exclude: [],
  }.deep_merge(custom_options)

  modules_paths = options.fetch(:modules_paths)
  modules_to_exclude = options.fetch(:exclude)
  target = options.fetch(:target)

  unimodules = {}
  unimodules_duplicates = []

  project_directory = Pod::Config.instance.project_root

  modules_paths.each { |module_path|
    canonical_module_path = Pathname.new(File.join(project_directory, module_path)).cleanpath
    glob_pattern = File.join(canonical_module_path, '**/*/**', 'unimodule.json')

    Dir.glob(glob_pattern) { |module_config_path|
      unimodule_json = JSON.parse(File.read(module_config_path))
      directory = File.dirname(module_config_path)
      platforms = unimodule_json['platforms'] || ['ios']
      targets = unimodule_json['targets'] || ['react-native']

      if unimodule_supports_platform(platforms, 'ios') && unimodule_supports_target(targets, target)
        package_json_path = File.join(directory, 'package.json')
        package_json = JSON.parse(File.read(package_json_path))
        package_name = unimodule_json['name'] || package_json['name']

        if !modules_to_exclude.include?(package_name)
          unimodule_config = { 'subdirectory' => 'ios' }.merge(unimodule_json.fetch('ios', {}))
          unimodule_version = package_json['version']

          if unimodules[package_name]
            unimodules_duplicates.push(package_name)
          end

          if !unimodules[package_name] || Gem::Version.new(unimodule_version) >= Gem::Version.new(unimodules[package_name][:version])
            unimodules[package_name] = {
              name: package_name,
              directory: directory,
              version: unimodule_version,
              config: unimodule_config,
              warned: false,
            }
          end
        end
      end
    }
  }

  if unimodules.values.length > 0
    puts brown 'Installing unimodules:'

    unimodules.values.sort! { |x,y| x[:name] <=> y[:name] }.each { |unimodule|
      directory = unimodule[:directory]
      config = unimodule[:config]

      subdirectory = config['subdirectory']
      pod_name = config.fetch('podName', find_pod_name(directory, subdirectory))
      podspec_directory = Pathname.new("#{directory}/#{subdirectory}").relative_path_from(project_directory)

      puts " #{green unimodule[:name]}#{cyan "@"}#{magenta unimodule[:version]} from #{blue podspec_directory}"

      pod "#{pod_name}", path: podspec_directory
    }

    if unimodules_duplicates.length > 0
      puts
      puts brown "Found some duplicated unimodule packages. Installed the ones with the highest version number."
      puts brown "Make sure following dependencies of your project are resolving to one specific version:"

      puts ' ' + unimodules_duplicates
        .uniq
        .map { |package_name| green(package_name) }
        .join(', ')
    end
  else
    puts
    puts brown "No unimodules found. Are you sure you've installed JS dependencies before installing pods?"
  end

  puts
end

def find_pod_name(package_path, subdirectory)
  podspec_path = Dir.glob(File.join(package_path, subdirectory, '*.podspec')).first
  return podspec_path && File.basename(podspec_path).chomp('.podspec')
end

def unimodule_supports_platform(platforms, platform)
  return platforms.class == Array && platforms.include?(platform)
end

def unimodule_supports_target(targets, target)
  return targets.class == Array && targets.include?(target)
end

def green(message)
  return "\e[32m#{message}\e[0m"
end

def brown(message)
  return "\e[33m#{message}\e[0m"
end

def blue(message)
  return "\e[34m#{message}\e[0m"
end

def magenta(message)
  return "\e[35m#{message}\e[0m"
end

def cyan(message)
  return "\e[36m#{message}\e[0m"
end

```

**Comment by Luckygirlllll** [comment]
@christocracy Do you think that problem can be related to `react-native-unimodules`?

**Comment by Luckygirlllll** [comment]
Is it possible to delete CocoaLumberjack.h from your libraries? I found pretty similar issue here: https://github.com/mauron85/react-native-background-geolocation/issues/318

**Comment by Luckygirlllll** [comment]
I don't see CocoaLumberjack.h in CocoaLumberjack folder:  

<img width="346" alt="Screen Shot 2019-10-16 at 11 52 48" src="https://user-images.githubusercontent.com/10096433/66908534-8b118b00-f00b-11e9-94b2-470900876a64.png">

**Comment by Luckygirlllll** [comment]
I found the solution, I removed folder with Pods and removed Podfile.lock, and reinstalled pods and error is disappeared.

**Comment by christocracy** [comment]
Well, done.  So this issue is closed?

**Comment by christocracy** [comment]
You’ll likely have a better time with Pod related issue after you migrate to RN >= 0.60

**Comment by Luckygirlllll** [comment]
yeah, I will close the issue!

**Comment by lucasluca** [comment]
in React native this resolved here => Found it. You have to open the xcode workspace, not the project.
