### ISSUE TITLE
Android - Other Build types license validation fails

### ISSUE THREAD

**Issue by liamlevesque** [transistorsoft/react-native-background-geolocation#874]
## Your Environment
* Plugin version: 3.2.2
* Platform: Android
* OS version: Any
* Device manufacturer / model: Any
* React Native version (`react-native -v`): 0.61.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
buildTypes {
        debug {
            signingConfig signingConfigs.debug
            applicationIdSuffix ".debug"
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug //Change to .release on release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        releasestaging {
            initWith release
            applicationIdSuffix ".releasestaging"
            matchingFallbacks =  ['release']
        }
    }
```

## Expected Behavior
My license doesn't work for build types other than release.  
For staging my app I have a staging environment and in app/build.gradle I've configured a stagingrelease build type that I can install simultaneously alongside the release version.  The problem is my license fails validation on those builds. Am I doing something wrong?
I'm probably being dumb and there may be a smarter way to do this (if so please let me know!!!) 

Thanks!!!

**Comment by christocracy** [comment]
`.staging` is supported with existing key.

**Comment by christocracy** [comment]
Customers, please post issues [at the private repo](https://github.com/transistorsoft/react-native-background-geolocation-android)

**Comment by christocracy** [comment]
See the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/app/build.gradle#L158-L182)
