### ISSUE TITLE
Im getting "Unauthorized"  https://www.transistorsoft.com/shop/customers 

### ISSUE THREAD

**Issue by cesarve77** [transistorsoft/react-native-background-geolocation#876]
In  https://www.transistorsoft.com/shop/customers 

## Expected Behavior
Get an application key
## Actual Behavior

![image](https://user-images.githubusercontent.com/3970983/67154383-c8915380-f33e-11e9-8175-2af325b0e25d.png)

## Steps to Reproduce

1. go to  https://www.transistorsoft.com/shop/customers

**Comment by christocracy** [comment]
Have you purchased a license?

**Comment by cesarve77** [comment]
No i dont . Sorry now understand . Thanks close the issue
