### ISSUE TITLE
BGTaskSchedulerPermittedIdentifiers required in info.plist to distribute

### ISSUE THREAD

**Issue by Brianop** [transistorsoft/react-native-background-geolocation#884]
## Your Environment
* Plugin version: 3.3.1
* Platform: iOS
* OS version: 13
* Device manufacturer / model: iPhone 11
* React Native version (`react-native -v`): 0.61.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const DEFAULT_BACKGROUND_CONFIG = {
  reset: true,
  debug: false,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 50,
  elasticityMultiplier: 2,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  foregroundService: true,
  forceReloadOnGeofence: true,
  startOnBoot: true,
  stopOnTerminate: false,
  useSignificantChangesOnly: true,
  allowIdenticalLocations: true,
  preventSuspend: true,
  heartbeatInterval: 60 * 10,
  locationAuthorizationAlert: {
    titleWhenNotEnabled: '¡Los servicios de ubicación no estan habilitados!',
    titleWhenOff: '¡Los servicios de ubicación estan apagados!',
    instructions: 'Debes habilitar "Siempre" en los servicios de ubicación',
    cancelButton: 'Cancelar',
    settingsButton: 'Ok',
  },
  notification: {
    title: 'Actualizando tu ubicacion!',
    text: '',
    smallIcon: 'mipmap/ic_notification',
    largeIcon: 'mipmap/ic_notification',
  },
  url: `${KINESIS_ENDPOINT}${STAGE}/streams/safy-positions/record`,
  method: 'PUT',
  batchSync: false,
  autoSync: true,
  httpRootProperty: '.',
  locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"event":"<%= event %>","accuracy":<%= accuracy %>,"createdAt":"<%= timestamp %>","batteryLevel": <%= battery.level %>,"isCharging":<%= battery.is_charging %>, "type": 1}',
  geofenceTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"event":"<%= event %>","accuracy":<%= accuracy %>,"createdAt":"<%= timestamp %>","batteryLevel": <%= battery.level %>,"isCharging":<%= battery.is_charging %>, "zoneId": <%= geofence.identifier %>, "action": <%= geofence.action %>, "type": 2}',
}
```

## Expected Behavior
Upload app to AppStore Connect

## Actual Behavior
We get next error:
![Captura de Pantalla 2019-10-24 a la(s) 15 17 05](https://user-images.githubusercontent.com/15720472/67522002-8be09780-f671-11e9-8375-8c6697411aa0.png)

## Steps to Reproduce

1. Select *Product -> Archive* in XCode
2. Open *Organizer*
3. Select *Distribute App*
4. Select continue until App starts uploading

## Context
[Apple's documentation](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler#3193599) mentions that it is required to update `info.plist` and to add all task indentifiers that are going to run in background

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by mikehardy** [comment]
Interesting. I've submitted a build with 3.3.0. 

The "processing" mode is not part of this module I don't think. I see it asking for other things but not processing - https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md#configure-background-capabilities

So that is maybe coming from some other functionality?

Seems like it might have some unintended side effects too - from your Apple Documentation link (nice link!) - 

```
Adding a BGTaskSchedulerPermittedIdentifiers key to the Info.plist disables 
application(_:performFetchWithCompletionHandler:) and 
setMinimumBackgroundFetchInterval(_:) on iOS 13 and later
```

If I recall this is an important part of how some packages work, for instance the background fetch that is a dependency here...  https://github.com/transistorsoft/react-native-background-fetch/blob/master/ios/RNBackgroundFetch/RNBackgroundFetch%2BAppDelegate.m#L15

**Comment by Brianop** [comment]
You were right the error wasn't related with this module. Closing the issue
