### ISSUE TITLE
iOS - Native Alert shown when locations/permissions are turned off.

### ISSUE THREAD

**Issue by Akash-T2S** [transistorsoft/react-native-background-geolocation#887]
<img width="314" alt="Screenshot 2019-10-29 at 2 46 45 PM" src="https://user-images.githubusercontent.com/39513832/67753673-13a41880-fa5b-11e9-93ad-e2a16f4832ca.png">

## Your Environment
* Plugin version: 2.14.2
* Platform: iOS
* OS version: 12.2
* Device manufacturer / model: iPhone 7 plus
* React Native version (`react-native -v`): 0.59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

            BackgroundGeolocation.on('location', this.onDriverLocationChanged.bind(this), this.onError);

            // This handler fires when movement states changes (stationary->moving; moving->stationary)
            BackgroundGeolocation.on('motionchange', this.onMotionChange);

            // This event fires when a change in motion activity is detected
            BackgroundGeolocation.on('activitychange', this.onActivityChange);

            // This event fires when the user toggles location-services authorization
            BackgroundGeolocation.on('providerchange', this.onProviderChange.bind(this));

            BackgroundGeolocation.configure({
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: AppConfig.updateDriverLocationDistanceFilter,
                stopTimeout: 1,
                debug: false,
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                stopOnTerminate: false,
                startOnBoot: false,
            }, (state) => {
                if (!state.enabled) {
                    this.startTracking();
                }
            });
```

## Expected Behavior

We have our own customized banner to show whether the master location and location permissions are off. Whenever I kill the app and open I get native iOS alert with text "Location services are off" with two options cancel and settings, where settings lead to app settings.

## Actual Behavior

Whenever I kill the app and open again I don't want to show that native iOS alert.

## Steps to Reproduce

1. Open the app with app permission "Never"
2. Native iOS alert is shown with two options "Cancel" and "Settings"

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See api docs Config.disableLocationAuthorizationAlert
