### ISSUE TITLE
iOS - Native iOS alert when mobile GPS/Location services are off

### ISSUE THREAD

**Issue by kishore-T2S** [transistorsoft/react-native-background-geolocation#889]
## Your Environment
* Plugin version: 3.3.2
* Platform: iOS
* OS version: 12.2
* Device manufacturer / model: iPhone 7 plus
* React Native version (`react-native -v`): 0.59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

BackgroundGeolocation.ready({
                disableLocationAuthorizationAlert: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: AppConfig.updateDriverLocationDistanceFilter,
                stopTimeout: 1,
                debug: false,
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                stopOnTerminate: false,
                startOnBoot: false,
            }, (state) => {
                if (!state.enabled) {
                    this.startTracking();
                }
            });

## Expected Behavior
When ever i turn off the GPS/Location services, there comes a native alert with content "Turn on you GPS Location". This appears intermittently i have also used the API property "disableLocationAuthorizationAlert"

## Actual Behavior
When GPS location is turned off and no native alert should be shown.

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1. Turn off GPS/Location from device
2. Re-launch App Native alert shown

## Context
<!--- What were you trying to do? -->

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
<img width="286" alt="Screenshot 2019-11-01 at 3 08 59 PM" src="https://user-images.githubusercontent.com/39514007/68016214-181a3c80-fcba-11e9-9b57-474956be26ae.png">

**Comment by christocracy** [comment]
Edit you issue:
- Plugin Config
- Post a screenshot of this alert

**Comment by kishore-T2S** [comment]
Can you please check the screen shot.

**Comment by christocracy** [comment]
That alert is produced automatically by the operating system.  There is no control over that.

**Comment by christocracy** [comment]
[Google images search “ios turn on location services”](https://www.google.com/search?q=ios+turn+on+location+services&safe=off&rlz=1CDGOYI_enCA591CA606&hl=en-US&prmd=nimv&sxsrf=ACYBGNSwvV4HCYp8rF4nqHiQXdC-8e-nWQ:1572603030084&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj7-evn4sjlAhUkwVkKHRL-BLEQ_AUoAnoECBAQAg&biw=375&bih=638&dpr=3)

**Comment by mikehardy** [comment]
I have an issue in my work project related to this. GPS is very useful in my project but also truly optional. I also know react-native-device-info can provide info on whether GPS is enabled or not ([detailed info](https://github.com/react-native-community/react-native-device-info#getAvailableLocationProviders) or a [boolean](https://github.com/react-native-community/react-native-device-info#isLocationEnabled)). 

Seems like when I start the app I can check if GPS is currently enabled or not before I call ready on the geolocation plugin? And if I don't call ready then I shouldn't get the popup?

I will likely test this myself unless you respond that you know better but seems like it should work.

Thinking farther, if this works - if re-enabling aggressively was important you'd have to either PR to react-native-device-info to make that something you could listen for, or use react-native-background-fetch and check for changes then call ready or similar.

Also not sure on the case where it was on when the app started but then was turned off during normal execution.

**Comment by christocracy** [comment]
>And if I don't call ready then I shouldn't get the popup?

`#ready` doesn't automatically `#start` until `state.enabled == `true`.  The plugin *remembers* its enabled state.  `state.enabled` is toggled via `#start` / `#stop`.

At first install of your app, `#ready` will not ask permission.  `#start` requests permission.

If one calls `#start`, revokes Location permission in Settings then re-launches app, `#ready` *will* request permission , since `state.enabled` is now `true`.
