### ISSUE TITLE
`onProviderChange` not triggered if the permission is changed while the app is in background on Android

### ISSUE THREAD

**Issue by ClementPF** [transistorsoft/react-native-background-geolocation#891]
##  Your Environment
* Plugin version: 3.0.9
* Platform: Android 
* OS version: multiple versions including 6.0.1
* Device manufacturer / model: mutiple device including Nexus 5
* React Native version: 0.59.5
* Plugin config
```javascript 
const backgroundGeolocationConfiguration = {
  // Common
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 200,

  // IOS
  stationaryRadius: 50,
  disableMotionActivityUpdates: false,
  activityType: 'AutomotiveNavigation',
  preventSuspend: true,

  // Android
  locationUpdateInterval: 1 * 60 * 1000, // in ms ~ 1 mins
  foregroundService: true,

  // Common Activity Recognition
  activityRecognitionInterval: 10000,
  stopTimeout: 2, // 2 minutes
  minimumActivityRecognitionConfidence: 80, // 0-100%.  Minimum activity-confidence for a state-change
  stopDetectionDelay: 1, // <--  minutes to delay after motion stops before engaging stop-detection system

  // Common Application Config
  debug: false,
  stopOnTerminate: true,
  startOnBoot: false,
  heartbeatInterval: 60
};
```

## Expected Behavior
onProviderChanged should be triggered when switching the location permission from OFF to ON from the settings.

## Actual Behavior
onProviderChanged is not triggered when switching the location permission from OFF to ON.

## Steps to Reproduce

```javascript
function debugOnProviderChange() {
  BackgroundGeolocation.onProviderChange(provider => {
    console.log('onProviderChange', { provider });
  });

  BackgroundGeolocation.ready(backgroundGeolocationConfiguration)
    .then(state => {
      if (!state.enabled) {
        BackgroundGeolocation.start(() => {
          console.log('started successfully');
        });
      }
    })
    .catch(error => {
      console.error({ error });
    });
}
```

1. run the above function
2. do not grant the permission when prompted
3. go to settings
4. turn location permission ON
5. notice that onProviderChange did not get called.

## Context
I'm trying to get an accurate representation of the permission state

**Comment by ClementPF** [comment]
identical to closes issue
https://github.com/transistorsoft/react-native-background-geolocation/issues/701

**Comment by ClementPF** [comment]
@christocracy Are you just playing the clock until it goes stale ?

**Comment by christocracy** [comment]
No, I’ve got lots of other stuff going on.

**Comment by Brianop** [comment]
Im also getting this issue, @ClementPF did you find a workaround ?

**Comment by ClementPF** [comment]
@Brianop I have not

**Comment by vhenri** [comment]
Hello from the future! Our team is currently experiencing this issue. Did anyone ever figure this out? 👀

**Comment by christocracy** [comment]
On a 4 year old, closed issue, it's best to open a new issue.
