### ISSUE TITLE
False positive geofence EXIT events for high accuracy values

### ISSUE THREAD

**Issue by Metroninja** [transistorsoft/react-native-background-geolocation#892]
I'm getting false positive geofence exit events for high accuracy values on the geofence response (not the plugins fault, obviously!).  I.e. after an ENTER and DWELL event have fired, if a position update event comes in with a high accuracy value (in my case 17k+) the EXIT event will fire which causes problems for my use case.  The plugin is operating as expected, I'm hoping for an undocumented minimum accuracy threshold config value for geofence events.

## Your Environment
* Plugin version: 3.3.2
* Platform: iOS and Android
* OS version: Multiple
* Device manufacturer / model: multiple
* React Native version (`react-native -v`): 0.60.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        // Geolocation Config
        reset: true,
        desiredAccuracy:
          Platform.OS === 'android'
            ? BackgroundGeolocation.DESIRED_ACCURACY_HIGH
            : BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 5,
        stopTimeout: 1,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
        stopOnTerminate: false,
        enabledHeadless: true,
        startOnBoot: false,
        preventSuspend: true,
        heartbeatInterval: 60,
        geofenceModeHighAccuracy: true,
        localAuthorizationRequest: 'Always',
        locationAuthorizationAlert: {
          titleWhenNotEnabled: 'Location services are not enabled',
          titleWhenOff: 'Location services are OFF',
          instructions: 'To properly track events please enable "Always" in location-services',
          cancelButton: 'Cancel',
          settingsButton: 'Settings',
        },
      },
```

## Expected Behavior
Geofence exit events would filter out high accuracy values to ensure false exit events aren't fired.

## Actual Behavior
I have had a few users in very low signal areas (in the middle of snow storms) trigger false exit events as the location event sent from the device are wildly outside the geofence radius, with an accuracy values exceeding 17000.  Obviously having a 10 mile + inaccuracy value is going to trigger any geofence related events.

## Steps to Reproduce
1.  Trigger a geofence enter event
2. Trigger the dwell threshold if needed (which in my case I do)
3. Receive a wildly inaccurate fluke location update from the device which will trigger the exit event

## Context
I currently use the plugin to track truck deliveries and in low signal areas with bad weather I'm receiving false positive exit events.  The particular problem with the exit event is that once it's fired it makes it difficult to ignore and then ensure the geofence is setup again, enter event fires again, and then monitor for another, more valid exit event.  We track the time on site for a delivery, and so having false exit events are throwing off these metrics.

I want to make it clear that I fully understand the plugin is operating perfectly, this is a problem with the users devices and not the plugin.  For a future release I don't think it would be unreasonable to have a minimum (Maximum?) accuracy config (or default) value to check against for geofence exit (or any) events.   I searched the existing issues to see if there was anything along these lines and am only posting as an issue so others in the future can see this resolution and not spam you for something you have already answered.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
example position update
Geofence enter position values
{"latitude":43.168030469890084,"longitude":-105.33949858910728,"accuracy":16,"altitude":1518.6,"altitudeAccuracy":null,"heading":180.18,"speed":10.6}
Geofence exit position value:
{"latitude":43.279388427734375,"longitude":-105.25268022135837,"accuracy":17195,"altitude":1511.6,"altitudeAccuracy":null,"heading":-1,"speed":-1}

geofence config
        {
          identifier: 'Destination',
          radius: 500,
          latitude: destinationLat,
          longitude: destinationLon,
          notifyOnEntry: true,
          notifyOnExit: true,
          notifyOnDwell: true,
          loiteringDelay: 1000 * 60 * 5,
        },
```

</details>

**Comment by christocracy** [comment]
No there's no way to prevent these.  Why don't you filter them out as desired on the server / add logic in your own app?

**Comment by Metroninja** [comment]
I actually can filter out the result easily, the problem is I still need to monitor the "real" exit event, so what I was hoping for was for the plugin to check the accuracy of the location event when determining if an exit has been achieved, ignore a high accuracy location event, and continue to monitor until a sufficiently reasonable location tracking event is found and then fire the exit event.

My current plan is to simply set back up the geofence after a false positive EXIT, which in theory should trigger a new enter ENTER/DWELL if I get a reasonable location update again but that's not guaranteed until the device reaches a better signal/weather area.

**Comment by christocracy** [comment]
Geofence events are handled automatically by the OS.  The plugin is only the messenger.

**Comment by Metroninja** [comment]
I didn't realize that!  Ok thanks, appreciate your help and all the work you do.
