### ISSUE TITLE
Android 8.1 crash - IllegalArgumentException: invalid displacement: -1.0

### ISSUE THREAD

**Issue by vovkind** [transistorsoft/react-native-background-geolocation#893]
## Your Environment
* Plugin version: 3.3.2
* Platform: Android
* OS version: 8.1
* Device manufacturer / model: Galaxy Note9 (crownlte)
--

* React Native version (`react-native -v`): 0.59.10
* Plugin config
```
javascript <!-- Syntax-highlighting:  paste your code below -->
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 75,
        stopOnStationary: false,
        useSignificantChangesOnly: false,
        foregroundService: true,
        allowIdenticalLocations: false,
        stopOnTerminate: true,
        startOnBoot: false,
        preventSuspend: true,
        autoSync: false,
        disableMotionActivityUpdates: false,
        stopOnStillActivity: false,
        disableStopDetection: true,
        pausesLocationUpdatesAutomatically: false,
        heartbeatInterval: 60,
        reset: true,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR
```

## Expected Behavior
No exception thrown during app/plugin using

## Actual Behavior
Crash happens multiple time for same device (15 times during a hour):
Fatal Exception: java.lang.IllegalArgumentException: invalid displacement: -1.0
       at com.google.android.gms.location.LocationRequest.a(LocationRequest.java:29)
       at com.transistorsoft.locationmanager.location.TSLocationManager.buildLocationRequest(TSLocationManager.java:49)
       at com.transistorsoft.locationmanager.location.TSLocationManager.requestLocationUpdates(TSLocationManager.java:61)
       at com.transistorsoft.locationmanager.location.TSLocationManager$c.run(TSLocationManager.java:452)
       at java.util.concurrent.ThreadPoolExecutor.
runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

## Steps to Reproduce
No steps to reproduce, issue reported by Google Play console and Firebase Crashlytics for some remote device

## Context
We try to retrieve user's location periodically and send it to server

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you setting the distanceFilter: -1 somewhere?

**Comment by vovkind** [comment]
> Are you setting the distanceFilter: -1 somewhere?

I don't see such assignment. It is reported only for specific device. All another devices are working fine.
Is it only reason could be? Is it reproducible with distanceFilter =-1?

**Comment by christocracy** [comment]
Your app is setting `distanceFilter: -1` somehow.

[LocationRequest#setSmallestDisplacement](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.html#setSmallestDisplacement(float))

![](https://dl.dropbox.com/s/d8ykp4p8qcgnrg1/Screenshot%202019-11-04%2016.59.35.png?dl=1)

I will add a guard to ensure `distanceFilter >= 0`.

**Comment by vovkind** [comment]
I will update soon. 
Big chance that it is what Chris told: set distanceFilter = -1 from app code.

**Comment by oren-meiron** [comment]
im experiencing this issue also, when will this be fixed ?

**Comment by christocracy** [comment]
@oren-meiron don’t shoot yourself in the foot by distanceFilter: -1.

The “fix” is merely preventing you from shooting yourself in the foot.

The plugin

**Comment by vovkind** [comment]
Confirmed that it was fixed in our side.
