### ISSUE TITLE
Illegal callback invocation from native module. This callback type only permits a single invocation from native code

### ISSUE THREAD

**Issue by vovkind** [transistorsoft/react-native-background-geolocation#895]
## Your Environment
* Plugin version: 3.2.2, 3.3.2
* Platform: Android
* OS version: 8, 9
* Device manufacturer / model: OnePlus 6, Samsung S9+,Moto Z (2) Play,  Galaxy S7 Edge, Honor 8X and other.
* React Native version (`react-native -v`): 0.59.10
* Plugin config
```
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 75,
        stopOnStationary: false,
        useSignificantChangesOnly: false,
        foregroundService: true,
        allowIdenticalLocations: false,
        stopOnTerminate: true,
        startOnBoot: false,
        preventSuspend: true,
        autoSync: false,
        disableMotionActivityUpdates: false,
        stopOnStillActivity: false,
        disableStopDetection: true,
        pausesLocationUpdatesAutomatically: false,
        heartbeatInterval: 60,
        reset: true,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR
```
## Expected Behavior

 No exception thrown and app crashed

## Actual Behavior

Following exception thrown:

Fatal Exception: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
       at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:23)
       at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule$12.onLocation(RNBackgroundGeolocationModule.java:16)
       at com.transistorsoft.locationmanager.location.TSLocationManager$c$1.run(TSLocationManager.java:12)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6898)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

## Steps to Reproduce
No steps to reproduce, the crash happened on remote phone device

## Context
Capture user's location via geolocation plugin

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Reproduction steps, please.

**Comment by christocracy** [comment]
This looks to me like a quirk involving refreshing the app while running the app with dev server.

**Comment by christocracy** [comment]
How are you registering your event-listeners?  You've not shown any code.

**Comment by vovkind** [comment]
BackgroundGeolocation.onLocation((location) => {
        // some logic
      },
      (error) => {
        Log.error('GL - onLocation error', error);
      });

    BackgroundGeolocation.onPowerSaveChange((isPowerSaveMode) => {
      Log.info('GL - onPowerSaveChange', isPowerSaveMode);
    });

    BackgroundGeolocation.onProviderChange((event) => {
      Log.info('GL - onProviderChange', event);
      let isEnabled = event.enabled;
      // .... some logic
    });

-------------------------------------------
I see only one crash for now, for about 260 users.

**Comment by christocracy** [comment]
I need more context of *where* you're registering these listeners.  Is this in `componentDidMount`?

**Comment by vovkind** [comment]
The geolocation plugin logic self it is not part of specific React component, just handler that connected to Redux. Here we register plugin listeners.

If still consider React lifecycle, it happens after App.js --> componentDidMount called.

You need more code? What exactly? I will send you.

**Comment by vovkind** [comment]
Hi, Chris.

Same issue we face with version 3.3.2 on Android 8 and 9, Samsung, Motorola, Huawei devices.
How can we help with investigation? Some more data needed?

**Comment by losnikitos** [comment]
Hi Chris!

Facing the same issue after updating to version 3.4.2. We register `onLocation` in `componentDidMount` https://gist.github.com/losnikitos/9105f037cddf3c23e0ea2310a3f11989#file-geolocation-js-L31.

It's been around for a while, but skyrocketed with newest plugin version
![2019-12-23_15-13-12](https://user-images.githubusercontent.com/5237443/71357499-10c72f00-2597-11ea-96f3-a62246236ad2.png)

<details>
<summary>Stacktrace</summary>

```
Fatal Exception: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
       at com.facebook.react.bridge.CallbackImpl.invoke + 28(CallbackImpl.java:28)
       at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule$12.onLocation + 553(RNBackgroundGeolocationModule.java:553)
       at com.transistorsoft.locationmanager.location.TSLocationManager$2.run + 16(:16)
       at android.os.Handler.handleCallback + 790(Handler.java:790)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 164(Looper.java:164)
       at android.app.ActivityThread.main + 6518(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 438(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main + 807(ZygoteInit.java:807)
```
</details>

**Comment by losnikitos** [comment]
@christocracy we need help from you. Issue occurs pretty often among the users:

![image](https://user-images.githubusercontent.com/5237443/75046240-ce0dce80-54d5-11ea-9a3a-506b642f1f47.png)

**Comment by rhoadsjustin** [comment]
@christocracy is there any update with this issue? we're seeing it as well.

**Comment by christocracy** [comment]
There are never updates on closed issues.  What version are you using?

**Comment by rhoadsjustin** [comment]
Thanks for the reply.

we're currently on 3.4.2, I looked through the next few releases and didn't see it called out specifically. I also didn't see a resolution in this thread so wanted to double check.

**Comment by christocracy** [comment]
You should always use the latest available version.

**Comment by rhoadsjustin** [comment]
Does the newest version have a fix for this issue?

**Comment by christocracy** [comment]
I'm not seeing or hearing of a problem.

**Comment by rhoadsjustin** [comment]
sweet! we'll look at upgrading and hopefully that will eliminate the issue.

**Comment by vovkind** [comment]
This exception also happens on Android 12 DP.

**Comment by christocracy** [comment]
This issue is over 2 years old.

I suggest you post a new issue.  I have Android 12 running in my *Pixel 3a*.
