### ISSUE TITLE
onGeofence() is not called when app is in background

### ISSUE THREAD

**Issue by zenkhas** [transistorsoft/react-native-background-geolocation#896]
[logs.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/3828055/logs.zip)

## Your Environment
* Plugin version: 3.3.2
* Platform: Android
* OS version: 9.0
* Device manufacturer / model: Android Emulator & Xiaomi Mi A3
* React Native version (`react-native -v`): 0.59.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const start = (geofences) => {

    AsyncStorage.getItem(WebConstants.USER_ACCESS).then((value) => {
        let userData = JSON.parse(value);


        const config = {
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
            distanceFilter: 10,
            url: WebConstants.ETRACK_HOST,
            params: {
                // Required for tracker.transistorsoft.com
                device: {
                    uuid: (DeviceInfo.getModel() + '-' + DeviceInfo.getSystemVersion()).replace(/[\s\.,]/g, '-'),
                    model: DeviceInfo.getModel(),
                    platform: DeviceInfo.getSystemName(),
                    manufacturer: DeviceInfo.getManufacturer(),
                    version: DeviceInfo.getSystemVersion(),
                    framework: 'ReactNative'
                }

            },
            extras: {cc: userData[1], t: userData[11], id: userData[3], employee: userData[5]},
            autoSync: true,
            startOnBoot: true,
            stopOnTerminate: false
            //debug: true
        };


        BackgroundGeolocation.ready(config, function (state) {
            log("ready()");
            log("Adding Geofences \n" + JSON.stringify(geofences));

            BackgroundGeolocation.removeGeofences().then(success => {
                console.log('[removeGeofences] all geofences have been destroyed');


                BackgroundGeolocation.addGeofences(geofences).catch(
                    (err) => log("Error adding geofences: " + err)
                );

                if (!state.enabled) {
                    BackgroundGeolocation.startGeofences(function (state) {
                        log('- Geofence-only monitoring started' + state.trackingMode);
                    });
                }


            });


        });


    })
};

```

## Expected Behavior

Plugin should trigger onGeofence when user enters/exits the geofence when app is not running or not in foreground

## Actual Behavior

onGeofence() is only called when app is opened and onGeofence() is called into a component.

## Steps to Reproduce

1. Configure the plugin
2.Add Geofences
3. Call onGeofence() in componentDidMount() of main component

## Context

I'm trying to get callback and generate some notifications when user enters or exits from a Geofence, but it should be done in background, even if the app is killed.

## Debug logs

<details><summary>Logs</summary>
Unable to paste logs here because of maximum characters limit, please find the zip file attached.
</details>

**Comment by christocracy** [comment]
If the app is terminated, your JavaScript app no longer exists, including event listeners you’ve subscribed on the plugin.

See wiki “Headless JS“.

**Comment by zenkhas** [comment]
Thanks, headless mode was the way to go.
