### ISSUE TITLE
No task registered for key BackgroundFetch

### ISSUE THREAD

**Issue by Kiran0791** [transistorsoft/react-native-background-geolocation#897]
No task registered for key BackgroundFetch [ON ANDROID]
## Your Environment
* Plugin version: ^3.3.1
* Platform:  Android
* OS version: Pie
* Device manufacturer / model: OnPlus , Google Pixel etc
* React Native version (`react-native -v`): 0.59
        BackgroundGeolocation.ready({
          // Geolocation Config
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter:  10,
          // Activity Recognition
          stopTimeout: 1,
          // Application config
          debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: true,   // <-- Allow the background-service to continue tracking when user closes the app.
          startOnBoot: false,        // <-- Auto start tracking when device is powered-up.
        }, (state) => {
          console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
          LogEvent("Background Geo",state)
    
          if (!state.enabled) {
            ////
            // 3. Start tracking!
            //
            BackgroundGeolocation.start(function() {
              console.log("- Start success");
            });
          }
        });

Seeing these error on the production version below is the log for from bugsnag
[bugsnag_error_stacktrace_Error_event_5dc563350052d50797010000.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/3829913/bugsnag_error_stacktrace_Error_event_5dc563350052d50797010000.txt)

**Comment by Kiran0791** [comment]
@christocracy  waiting on your feedback on this

Thank You

**Comment by christocracy** [comment]
This isn't an issue with `BackgroundGeolocation`.   Your issue references `BackgroundFetch`

**Comment by Kiran0791** [comment]
Background Fetch is not used in our app and this error has got introduced after adding the background-geolocation. react-native-background-fetch is added for the react-native-background-geolocation

Let us know if we are missing anything in the configuration part

**Comment by Nwekar-NS20** [comment]
Kiran0791 did you fix it?
