### ISSUE TITLE
invalid license key using on apk

### ISSUE THREAD

**Issue by anuj-njoshi** [transistorsoft/react-native-background-geolocation#899]
## Your Environment

* Platform:Android

I have  purchased license for android support. added this line in AndroidManifest.xml and replaced *** with  licence key.<meta-data android:name="com.transistorsoft.locationmanager.license" android:value="***" />
but  is showing invalid license key on beta version installed

**Comment by christocracy** [comment]
Customers, please use the [private repo](https://github.com/transistorsoft/react-native-background-geolocation-android) for support.
