### ISSUE TITLE
Getting framework not found TSLocationManager during build step

### ISSUE THREAD

**Issue by kristjanmik** [transistorsoft/react-native-background-geolocation#9]
I followed [the guide](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Installation) but was not able to get it running. I have double checked every step on the way but the error I get is:
ld: framework not found TSLocationManager
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by christocracy** [comment]
It's pretty tough to keep on top of all the rapid changes with RN.  I'll
have a look.

On Wednesday, October 7, 2015, Kristján Ingi Mikaelsson <
notifications@github.com> wrote:

> I followed the guide
> <https://github.com/transistorsoft/react-native-background-geolocation/wiki/Installation>
> but was not able to get it running. I have double checked every step on the
> way but the error I get is:
> ld: framework not found TSLocationManager
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/9>
> .
>


-- 
Snet form Gmail Mobile

**Comment by aphillipo** [comment]
Yep, sorry to be a pain, I'm seeing this too...

**Comment by christocracy** [comment]
Are you all using my sampleApp or dropping it into your own?

On Wednesday, October 7, 2015, Andrew Phillipo <notifications@github.com>
wrote:

> Yep, sorry to be a pain, I'm seeing this too...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/9#issuecomment-146361973>
> .
>


-- 
Snet form Gmail Mobile

**Comment by aphillipo** [comment]
dropping it into my own.

**Comment by aphillipo** [comment]
I will try the sample app...

**Comment by christocracy** [comment]
Nah, Sample app is broken

On Wednesday, October 7, 2015, Andrew Phillipo <notifications@github.com>
wrote:

> I will try the sample app...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/9#issuecomment-146362153>
> .
>


-- 
Snet form Gmail Mobile

**Comment by aphillipo** [comment]
Do i really need to include react-native-mapbox-gl as per the instructions...?

**Comment by christocracy** [comment]
MapboxGL has a major flaw when used with my plugin.  I'm very pissed off
about it.  They don't seem to understand.

https://github.com/mapbox/mapbox-gl-native/pull/2120

On Wednesday, October 7, 2015, Andrew Phillipo <notifications@github.com>
wrote:

> Do i really need to include react-native-mapbox-gl as per the
> instructions...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/9#issuecomment-146362480>
> .
>


-- 
Snet form Gmail Mobile

**Comment by aphillipo** [comment]
New Error:

ld: warning: object file (/Users/aphillipo/Library/Developer/Xcode/DerivedData/-djilkktgzbflitgzyfxgtjfcgcrd/Build/Products/Debug-iphonesimulator/libRNBackgroundGeolocation.a(RNBackgroundGeolocation.o)) was built for newer iOS version (8.3) than being linked (7.0)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TSLocationManager", referenced from:
      objc-class-ref in libRNBackgroundGeolocation.a(RNBackgroundGeolocation.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

x86_64??? 

Additionally I was referring to the instructions on the Wiki here; maybe a copy and paste error? 

    Select your project in the Project navigator. Click Build Phases then Link Binary With Libraries. Add node_modules/react-native-mapbox-gl/RCTMapboxGL/libRNBackgroundGeolocation.a

**Comment by christocracy** [comment]
X86_64 is not unusual.  It's for the sim

On Wednesday, October 7, 2015, Andrew Phillipo <notifications@github.com>
wrote:

> New Error:
>
> ld: warning: object file
> (/Users/aphillipo/Library/Developer/Xcode/DerivedData/-djilkktgzbflitgzyfxgtjfcgcrd/Build/Products/Debug-iphonesimulator/libRNBackgroundGeolocation.a(RNBackgroundGeolocation.o))
> was built for newer iOS version (8.3) than being linked (7.0)
> Undefined symbols for architecture x86_64:
> "*OBJC_CLASS*$_TSLocationManager", referenced from:
> objc-class-ref in libRNBackgroundGeolocation.a(RNBackgroundGeolocation.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
>
> x86_64???
>
> Additionally I was referring to the instructions on the Wiki here; maybe a
> copy and paste error?
>
> Select your project in the Project navigator. Click Build Phases then Link Binary With Libraries. Add node_modules/react-native-mapbox-gl/RCTMapboxGL/libRNBackgroundGeolocation.a
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/9#issuecomment-146364915>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
That's not an error, only a warning

On Wednesday, October 7, 2015, Andrew Phillipo <notifications@github.com>
wrote:

> New Error:
>
> ld: warning: object file
> (/Users/aphillipo/Library/Developer/Xcode/DerivedData/-djilkktgzbflitgzyfxgtjfcgcrd/Build/Products/Debug-iphonesimulator/libRNBackgroundGeolocation.a(RNBackgroundGeolocation.o))
> was built for newer iOS version (8.3) than being linked (7.0)
> Undefined symbols for architecture x86_64:
> "*OBJC_CLASS*$_TSLocationManager", referenced from:
> objc-class-ref in libRNBackgroundGeolocation.a(RNBackgroundGeolocation.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
>
> x86_64???
>
> Additionally I was referring to the instructions on the Wiki here; maybe a
> copy and paste error?
>
> Select your project in the Project navigator. Click Build Phases then Link Binary With Libraries. Add node_modules/react-native-mapbox-gl/RCTMapboxGL/libRNBackgroundGeolocation.a
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/9#issuecomment-146364915>
> .
>


-- 
Snet form Gmail Mobile

**Comment by aphillipo** [comment]
Okay well I have what I want polling away when the app is up but I am certain your solution is considerably orders of magnitude better than what I've built with react.

Amazed that it's even allowed to poll for location info in the background when the app is off!

**Comment by christocracy** [comment]
It's very sophisticated.  Unfortunately, I haven't had much time to play
with RN the last couple months.

The lib continues to evolve in the Cordova universe.  It's the exact same
TSLocationManager.framework

On Wednesday, October 7, 2015, Andrew Phillipo <notifications@github.com>
wrote:

> Okay well I have what I want polling away when the app is up but I am
> certain your solution is considerably orders of magnitude better than what
> I've built with react.
>
> Amazed that it's even allowed to poll for location info in the background
> when the app is off!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/9#issuecomment-146368149>
> .
>


-- 
Snet form Gmail Mobile

**Comment by aphillipo** [comment]
Well hopefully I'll be able to add this at a later date when I can have time to get it working!  Clearly it's an incredible piece of work :+1:

**Comment by christocracy** [comment]
The heart of it is wrapped up within an agnostic iOS framework (and aar for Android) which works just as well for pure native apps.

The React Native-ness (or Cordova-ness) is merely a thin facade binding to this common lib.

**Comment by christocracy** [comment]
Ok, I've got it working with react-native `0.12.0`.  I'm ripping out `MapboxGL` though.  It's unsuitable for use with my plugin.  

I have a simple Node app you use to sync with and map history.
https://github.com/transistorsoft/background-geolocation-console

**Comment by christocracy** [comment]
(Update coming soon)

**Comment by kristjanmik** [comment]
Awesome @christocracy !

**Comment by aphillipo** [comment]
Thanks dude!

**Comment by kristojorg** [comment]
I'm getting this same error right now trying to build with RN not using the demo app:

ld: framework not found TSLocationManager
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I've linked the framework and it does exist in my node_modules, so I'm not sure why this is happening. I'm not using anything related to MapBox I don't believe.

Any suggestions?

**Comment by christocracy** [comment]
I'm on vacation in Iceland currently.  I'll have a look ASAP

On Wednesday, June 22, 2016, kristojorg <notifications@github.com> wrote:

> I'm getting this same error right now trying to build with RN not using
> the demo app:
>
> ld: framework not found TSLocationManager
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
>
> I've linked the framework and it does exist in my node_modules, so I'm not
> sure why this is happening. I'm not using anything related to MapBox I
> don't believe.
>
> Any suggestions?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/9#issuecomment-227813190>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l6I7teeyN3AsP4F7QNo4rncCIYOYks5qOW1JgaJpZM4GK1zW>
> .
>


-- 
Snet form Gmail Mobile

**Comment by kristjanmik** [comment]
@christocracy small world, I live in Iceland!

**Comment by christocracy** [comment]
Here's the result of [tracking Iceland](http://www.transistorsoft.com/lab/iceland) with this plugin

(it was the Cordova version, but same `TSLocationManager.framework` under-the-hood.  Porting Android *right now*.

**Comment by reneedudley** [comment]
Was this issue ever resolved? I'm getting the same error on my current app.

**Comment by christocracy** [comment]
Yes, this issue is closed.  It was a setup error.

Revisit the setup steps and verify

**Comment by FlavioTeodosio** [comment]
ld: framework not found TSLocationManager
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm making the same mistake, how did you solve that mistake at the time?
