### ISSUE TITLE
'TSBackgroundFetch/TSBackgroundFetch.h' file not found

### ISSUE THREAD

**Issue by nene** [transistorsoft/react-native-background-geolocation#902]
## Your Environment
* Plugin version: 3.3.2
* Platform: iOS
* OS version: MacOS 10.15.1 
* Device manufacturer / model: Apple
* React Native version: 0.61.4
* Plugin config: Don't think it matters

## Expected Behavior
Able to build without errors.

## Actual Behavior
Build fails with error:

```
..../node_modules/react-native-background-fetch/ios/RNBackgroundFetch/RNBackgroundFetch+AppDelegate.m:11:9: fatal error: 'TSBackgroundFetch/TSBackgroundFetch.h' file not found
#import <TSBackgroundFetch/TSBackgroundFetch.h>
```

<img width="714" alt="Screen Shot 2019-11-18 at 16 35 40" src="https://user-images.githubusercontent.com/118201/69061806-90a32c00-0a22-11ea-9607-78d346a1734e.png">

## Steps to Reproduce & Context
I was upgrading my app from react-native 0.59.9 to 0.61.4

Followed the steps in https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md

Although I'm confused about the addition of `RNBackgroundFetch+AppDelegate.m` file. When I looked into adding it, I discovered that the file was already there. I removed and re-added it, but the error remained the same.

Found some other issues with the same title, tried to follow the devide suggested there:

- made sure I've run `pod install` in `/ios` dir.

but no success. I've also checked that:

- I've run `yarn add react-native-background-geolocation` and `yarn add react-native-background-fetch`
- The build fails both when executed from command line (`react-native run-ios`) or through Xcode.

## Debug logs
I suspect logs will only matter after I get the app running? Or would you like to see the full log of a build?

**Comment by christocracy** [comment]
```
$ cd ios
$ pod install
```

**Comment by nene** [comment]
I've done this several times already. But doesn't help.

**Comment by christocracy** [comment]
Terminate XCode and restart.

**Comment by nene** [comment]
Restarted Xcode. But build still fails.

**Comment by christocracy** [comment]
Don't know.  Uninstall both plugins and re-install.

**Comment by nene** [comment]
OK. I'll give it a try...

**Comment by nene** [comment]
Nope. Still fails exactly as before.

**Comment by christocracy** [comment]
```
$ cd ios
$ rm -rf Pods
$ rm Podfile.lock
$ pod install
```

**Comment by mikehardy** [comment]
My magic trick for these is `npx react-native-clean-project clean-project-auto`

It's the full wipe...

**Comment by nene** [comment]
So... I uninstalled the libs again.

But now after uninstalling I noticed that this `RNBackgroundFetch+AppDelegate.m` file and the `.framework` file are still handing around in Xcode. So I removed them from there manually.

After reinstalling the libs, it's now successfully building.

I didn't re-add the `RNBackgroundFetch+AppDelegate.m` file after installing as the installation guide is suggesting. Not sure if I should worry about this or not?

But at least it's building now. Can't yet say if it's fully working as now I have some other errors from other libs to sort out on my way of upgrading react-native.

But thanks for all the help.

**Comment by nene** [comment]
Yep. Looks like the lib is not only compiling but working as well. All good then.

**Comment by bolandrm** [comment]
To resolve this on react-native 0.61 i had to also manually run `yarn install react-native-background-fetch`

**Comment by christocracy** [comment]
@bolandrm thats precisely what the [iOS Setup](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md#ios-auto-linking-installation) directs you to do, no?

**Comment by bolandrm** [comment]
Ah yes, I missed that.

**Comment by RishavGoswami** [comment]
I was stuck on this error for two days straight, tried everything that's been told but nothing worked until I realize to check my Xcode version. Turned out I had Xcode v10. Just make sure before doing any other things, you have **Xcode v11.5** and **above**. Then

```
cd ios
rm -rf Pods
rm -rf Podfile.lock
pod install
```

**Comment by christocracy** [comment]
*Always* use latest XCode.

**Comment by christocracy** [comment]
*Always* use latest XCode.

**Comment by christocracy** [comment]
*Always* use latest XCode.

**Comment by blwinters** [comment]
> @bolandrm thats precisely what the [iOS Setup](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md#ios-auto-linking-installation) directs you to do, no?

@christocracy I missed this part too. I think the formatting of that doc could be improved slightly so that it's clear on first glance that there are 2 packages to install. Maybe add a line after the first install command (both Yarn and NPM) to the effect of: 

"Then, install the appropriate version of `react-native-background-fetch`:"

**Comment by defiantgoat** [comment]
For anyone else finding this issue, I had to specifically add the headers to my Targets Frameworks, Libraries and Embedded Content
<img width="684" alt="Screenshot 2023-05-04 at 9 10 50 AM" src="https://user-images.githubusercontent.com/3229911/236214858-ca0d006c-cdd1-4cb1-8b0d-ccebfa5194df.png">
