### ISSUE TITLE
applicationId and application key should be the same?

### ISSUE THREAD

**Issue by coderbag** [transistorsoft/react-native-background-geolocation#903]
I am getting `LICENSE VALIDATION FAILURE`.

![image](https://user-images.githubusercontent.com/20454863/69232526-3ce72e80-0b59-11ea-8373-bc3a0962e890.png)
![image](https://user-images.githubusercontent.com/20454863/69232573-5daf8400-0b59-11ea-98ab-8a5a6a2ad2b5.png)

**Comment by coderbag** [comment]
I have a valid licence.

**Comment by christocracy** [comment]
Whey are you showing a picture of that image?  It has no relevance to you at all.

**Comment by coderbag** [comment]
@christocracy `LICENSE VALIDATION FAILURE` error  is not related with `applicationId`. Right?

**Comment by christocracy** [comment]
Have you purchased a license?

**Comment by coderbag** [comment]
Yes My client has purchased the license.
