### ISSUE TITLE
Additional exceptions for "Context.startForegroundService() did not then call Service.startForeground()" story

### ISSUE THREAD

**Issue by vovkind** [transistorsoft/react-native-background-geolocation#905]
## Your Environment
* Plugin version: 3.3.2
* Platform: Android
* OS version: 9
* Device manufacturer / model: Galaxy S9/S9+, S10+
* React Native version (`react-native -v`): 0.59.10
* Plugin config
```
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 75,
        stopOnStationary: false,
        useSignificantChangesOnly: false,
        foregroundService: true,
        allowIdenticalLocations: false,
        stopOnTerminate: true,
        startOnBoot: false,
        preventSuspend: true,
        autoSync: false,
        disableMotionActivityUpdates: false,
        stopOnStillActivity: false,
        disableStopDetection: true,
        pausesLocationUpdatesAutomatically: false,
        heartbeatInterval: 60,
        reset: true,
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR
```
## Expected Behavior

 No exception thrown and app crashed

## Actual Behavior

Following exceptions thrown:

Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{809ec0 u0 com.myapp/com.transistorsoft.locationmanager.service.LocationRequestService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{eb0ca35 u0 com.myapp/com.transistorsoft.locationmanager.service.GeofencingService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1855)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

## Steps to Reproduce
No steps to reproduce, the crash recorded by Google Play Vital and Firebase Crashlytics on remote phone devices

## Context
Capture user's location via geolocation plugin

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I've had the SampleApp running `3.3.2` deployed to Play Store since October 24.  No crashes, no ANR.

![](https://dl.dropboxusercontent.com/s/mhc4o6174o8wuxh/Screenshot%202019-11-20%2012.06.32.png?dl=1)
![]()
![](https://dl.dropbox.com/s/x475lddwqeb3xld/Screenshot%202019-11-20%2012.07.01.png?dl=1)

The plugin is not necessarily directly responsible for the ANR.  If *anything* in your app blocks the main thread causing boot up to be delayed, these will happen.  Once a foreground-service is launched, it has a few seconds to call `startForeground`.  When the main-thread is blocked, this time-limit will expire and an ANR occurs.

**Comment by mamta-deswal** [comment]
i'm facing this issue from long time, crashes on firebase. 
Fatal Exception: android.app.RemoteServiceException
Context.startForegroundService() did not then call Service.startForeground()
android.app.ActivityThread$H.handleMessage
