### ISSUE TITLE
Geolocation not working in prod even with license

### ISSUE THREAD

**Issue by rodrigo-fonseca** [transistorsoft/react-native-background-geolocation#907]
I put, like the tutorial, the meta data with name and value inside application tag, but it still not work, it only work in debug mode, what I'm doing wrong?

"react": "16.6.3",
"react-native": "0.58.6",
"react-native-background-geolocation": "^3.0.0-beta.4",

**Comment by christocracy** [comment]
First-of-all, you're ignoring the issue-template and providing **zero** information.  You didn't notice that warning at the top of the template before deleting it all?

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by rodrigo-fonseca** [comment]
*** ANDROID  (5.1.1) ***
"react": "16.6.3"
"react-native": "0.58.6"
react-native-cli: 2.0.1
"react-native-background-geolocation": "^3.0.0-beta.4"

Plugin Config

Config
```
static ready() {
    if (isGeolocationReady) return Promise.resolve()

    return new Promise((resolve) => {
      BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 1,
        // enable this hear sounds for background-geolocation life-cycle.
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        batchSync: false,
        autoSync: true
      }, (state) => {
        isGeolocationReady = true
        return resolve(state)
      })
    })
  }
```

I'm using watchPosition function 

```
watchPosition(callback, {
    interval = 5000,
    timeout = 10000,
    desiredAccuracy = BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  } = {}) {
    GeolocationService
      .ready()
      .then(() => {
        BackgroundGeolocation.watchPosition((location) => {
          callback(null, location)
        }, (err) => {
          callback(err)
        }, {
          interval,
          timeout,
          desiredAccuracy,
        })
      }).catch((err) => callback(err))
  }
```

It only work in debug mode

**Comment by rodrigo-fonseca** [comment]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
*** ANDROID (5.1.1) ***
"react": "16.6.3"
"react-native": "0.58.6"
react-native-cli: 2.0.1
"react-native-background-geolocation": "^3.0.0-beta.4"
```

## Expected Behavior
Get geolocation coordinates

## Actual Behavior
Nothing is happening, even error

## Steps to Reproduce
1. READY 

BackgroundGeolocation.ready({
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 1,
        // enable this hear sounds for background-geolocation life-cycle.
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true,
        batchSync: false,
        autoSync: true
      }, (state) => {
        isGeolocationReady = true
        return resolve(state)
      })
    })

2. Watch Position

BackgroundGeolocation.watchPosition((location) => {
          callback(null, location)
        }, (err) => {
          callback(err)
        }, {
          interval,
          timeout,
          desiredAccuracy,
        })
      }).catch((err) => callback(err))

## Context
Get geolocation coordinates

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I suggest you have a *very thorough* read of the [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#change-log).

The plugin version is now at **`3.3.2`**.  **`3.0.0-beta.4`** is from March.

**Comment by rodrigo-fonseca** [comment]
> I suggest you have a _very thorough_ read of the [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#change-log).
> 
> The plugin version is now at **`3.3.2`**. **`3.0.0-beta.4`** is from March.

Ok, thanks! I'll try it

**Comment by rodrigo-fonseca** [comment]
it works!
