### ISSUE TITLE
Black box feature

### ISSUE THREAD

**Issue by Namec** [transistorsoft/react-native-background-geolocation#910]
Hello All,

we finaly got our licence and we are excited to start working with this library.

currently my project is to recorde an event each 60 seconds, and i know well how to do that.

but the challenge is implemeting some other conditional recording.

Example:

the application logs a position each seconds in a buffer that can contains up to 60 positions, but only the last one is realt flaged for sending to the server

if an accident occurs (sensors reach some values) the application flag the last 30 seconds before the sensor event and the next 30 seconds after for sending.

this way we can have realy an more accurate picture on what happened.

if you can help me achieve that i'll be very thankful.

best

**Comment by christocracy** [comment]
**Do not cross-post on both repos**.  It makes me **angry**
