### ISSUE TITLE
Location offset on iOS

### ISSUE THREAD

**Issue by armin23615** [transistorsoft/react-native-background-geolocation#912]
## Your Environment
* Plugin version: ^3.3.2
* Platform:  iOS
* OS version: 12.4.1
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`): 0.60
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      stopTimeout: 1,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      url: 'https://myapi.com/locations',
      batchSync: true, 
      autoSync: true, 
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      extras: { trip_id: 100},
      notificationsEnabled: false,
    }
```

## Expected Behavior

Locations should be sent to server every 100 meters whether the app is in active or in background.

## Actual Behavior

Locations are not sent that frequently and there are location offsets (coords are few kilometers from the actual ones) as you can see in the attached photo. Red dots are my path. This work perfectly on Android though.
![123456](https://user-images.githubusercontent.com/56969846/70049183-69289380-15cc-11ea-82b6-b0179a863e05.png)

## Steps to Reproduce

1. Sending location every 100 meters
2. Not sure what details I can provide

**Comment by christocracy** [comment]
Read docs for Config.distanceFilter

**Comment by armin23615** [comment]
> Read docs for Config.distanceFilter

Okay, that explains fewer sent locations, but what about incorrect coordinates (red circle)? 
![wrong](https://user-images.githubusercontent.com/56969846/70053116-07b8f280-15d5-11ea-93ca-99cc877eda52.png)

Is disabling elasticity going to solve this too?

**Comment by christocracy** [comment]
I have no idea.  Locations are provided by the native location API.  The plugin is just the mailman that delivers them to you.
