### ISSUE TITLE
ios, can't save location service authorization

### ISSUE THREAD

**Issue by littlehome-eugene** [transistorsoft/react-native-background-geolocation#913]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^3.2.0",
* Platform: iOS or Android android
* OS version: mac high sierra
* Device manufacturer / model: galaxy s10e
* React Native version (`react-native -v`):
react-native-cli: 2.0.1
react-native: 0.60.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
       reset: false,
       stopTimeout: 1,
       debug: true,
       logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
       foregroundService: true,
       autoSync: true,
       url: TRACKER_HOST + this.state.username,
       stopOnTerminate: false,
       startOnBoot: true,
       notification: {
         title: 'react-native-background-geolocation',
         text: 'Tracking engaged'
       },
       heartbeatInterval: 60,
       enableHeadless: true,
       params: BackgroundGeolocation.transistorTrackerParams(DeviceInfo),
       maxDaysToPersist: 14,
       geofenceProximityRadius: 3000,
     }, (state:State) => {
       if (state.schedule && state.schedule.length > 0) {
         BackgroundGeolocation.startSchedule();
       }
       this.setState({
         enabled: state.enabled,
         isMoving: state.isMoving,
         followsUserLocation: state.enabled,
         showsUserLocation: state.enabled,
         bgGeo: state
       });
     }, (error:string) => {
       console.warn('BackgroundGeolocation error: ', error)
     });
```
## Expected Behavior

User is getting alert popup regarding location service authorization, we want to minimize the number of occurence

![1-location-track](https://user-images.githubusercontent.com/24217396/70105425-18747180-1684-11ea-8f15-9944ae9ed522.jpg)

When user selects "when in use" , I wonder if there 's something we need to do in code to apply that setting. 

How do we minimize number of alert if we can't totally disable it?

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You can’t.  Every app on earth is subject to this new dialog produced automatically by the OS.  Read about iOS 13 changes to location services.

https://link.medium.com/US9Gilhh81

**Comment by littlehome-eugene** [comment]
Ok I understand it's impossible to avoid the notification completely, what are our options to minimize it? use `Config.useSignificantChangesOnly` ? 
Are there other settings that can reduce the # of notification?

**Comment by christocracy** [comment]
I have no idea.  This is produced by the operating system for every single iOS app that uses location services.  Presumably it would be shown less frequently if you request location less frequently. 

I see it often for Google Maps.
