### ISSUE TITLE
startGeofences() triggers a React Native App state change - Android

### ISSUE THREAD

**Issue by giacomocerquone** [transistorsoft/react-native-background-geolocation#915]
As you may know in a full enriched application it can get hard to handle everything properly, especially when this library is added, so for this reason, and because it's actually trivial to rewrite, there will not be any code to showcase this, but I like thinking that I have the code of my entire application under control. (Specifically, I find tricky the ready state handling. To sync that, I put up a small architecture with a stack as a data structure that gets flushed when the lib is ready etc.etc.)
This to say that I might be wrong but I don't have another key to use to test this on android and I can't modify a huge project to be 100% sure about what I'm saying- Let's just say I've 99% of confidence though.

## Your Environment
* Plugin version: 3.3.2
* Platform: Android
* OS version: Android X (reproducible also on 9 and 6)
* Device manufacturer / model: Emulator, Meizu Note and Samsung Galaxy a9
* React Native version (`react-native -v`): 
```
react-native-cli: 2.0.1
react-native: 0.60.4
```
* Plugin config
```javascript 
    {
      enableHeadless: true,
      stopTimeout: 5,
      desiredAccuracy: BGLoc.DESIRED_ACCURACY_HIGH,
      debug: GEOFENCE_SOUNDS,
      logLevel: BGLoc.LOG_LEVEL_OFF,
      ...(env.CONSOLE_TRACKING
        ? {
            url: 'https://tracker.transistorsoft.com/',
            params: BGLoc.transistorTrackerParams(DeviceInfo),
          }
        : {}),
      notification: {
        priority: BGLoc.NOTIFICATION_PRIORITY_MIN,
        channelName: 'Location Tracker',
        title: 'title',
        text: 'text',
        smallIcon: 'drawable/ic_notification',
      },
      geofenceModeHighAccuracy: true,
      foregroundService: true,
      stopOnTerminate: false,
      startOnBoot: true,
      locationAuthorizationRequest: 'WhenInUse',
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'title',
        titleWhenOff: 'titleoff',
        instructions:
          'instr',
        cancelButton: 'del',
        settingsButton: 'sets',
      },
      persistMode: BGLoc.PERSIST_MODE_GEOFENCE,
    },
```

## Expected Behavior
If I call startGeofences(), an app state switch shouldn't be triggered.

## Actual Behavior
If I call startGeofences() while app state is "active", it goes to "background" and then "active" again.

## Steps to Reproduce
1. Add a couple of geofence
2. Add a state change listener
3. call startGeofences()
4. watch the state change

## Context
So in the last four months I experienced a problem with a personal long tested component that retrieves the current react native app state.
I use this component with this library specifically to start and stop the watchposition.
The problem is that the while in an "active" state, the state gets changed after having made a proper call to startGeofences() **after** the plugin is ready. It goes from active to background and then again to active.
Since I hadn't much time to fix this weird problem I wasn't understanding, I ended up leaving it as it is and for all this time I watch the persistent notification that come and goes a couple of times when opening this app (since in background state I call stop watching the position and in foreground I start it again), but this issue has bugged me for too long.
And I've always thought that other libraries were bugging this so today I put a lot of patience on it and found out this.
Is this a normal behaviour? If so I'd like to know how to avoid collecting this change

**Comment by giacomocerquone** [comment]
I might say this could be related https://github.com/transistorsoft/react-native-background-geolocation/issues/505#issuecomment-398054497

**Comment by giacomocerquone** [comment]
Don't want to open another issue (also because that is indeed useful to me), but an equal state change (active -> background -> active) happens when you use the android dropdown to disable (or enable) the geolocation services

**Comment by christocracy** [comment]
See docs `Config.disableLocationAuthorizationAlert`.  The plugin is using a mechanism from play-services that can automatically prompt the user, with one button, to set device location-settings according to the plugin configuration (eg: GPS enabled, location-services enabled, wifi enabled).  This feature launches an invisible Activity to run.  It the launch of this activity which is causing these app state changes.

**Comment by giacomocerquone** [comment]
whoa... it works. Do you mind a PR that specify this in the docs?
Consider that this happens on startGeofences too and it is indeed strange since in the docs I read:

```
Disables automatic authorization alert when plugin detects the user has disabled location authorization
```

And I get an app state change also when no authorization has been disabled. It is part of the whole mechanism I suppose at this point... anyway that feature was indeed useful, what a pity, i'll need to listen for provider changes and use https://facebook.github.io/react-native/docs/linking#opensettings

**Comment by christocracy** [comment]
The invisible activity must run, regardless.  The current state of location-services can only be determined *after* the Activity has launched.  When all is fine, the activity kills itself.
