### ISSUE TITLE
Accuracy on Android tracking has jumps

### ISSUE THREAD

**Issue by joennlae** [transistorsoft/react-native-background-geolocation#916]
## Your Environment
* Plugin version: 3.3.0
* Platform: Android
* OS version: multiple versions
* Device manufacturer / model: multiple models
* React Native version (`react-native -v`):  0.59.10
* Plugin config
```javascript 
await BackgroundGeolocation.ready({
        disableStopDetection: true,
        pausesLocationUpdatesAutomatically: false,
        debug: false,
        distanceFilter: 0,
        stationaryRadius: 0,
        locationUpdateInterval: 2000,
        fastestLocationUpdateInterval: 1000,
        allowIdenticalLocations: true,
        preventSuspend: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        notification: {
            title: 'running.COACH',
            text: 'training is ongoing'
        },
        startForeground: true,
        locationAuthorizationRequest: "WhenInUse"
})
```

## Expected Behavior
It should accurately track a run in the application. As it does on iOS and other Android devices.

## Actual Behavior
It has unexpected jumps in the track. Maybe I am doing something wrong in the config and someone knows something more. I searched in the docs but I did not find an answer.

That is our tracking.
![Karte-3](https://user-images.githubusercontent.com/1493766/70213055-c3466780-1738-11ea-83ba-64cabecabcf2.jpg)

Same training but with a competitor app.
![Runtastic](https://user-images.githubusercontent.com/1493766/70213065-c6d9ee80-1738-11ea-96b3-daccd0df86a7.jpg)

## Context
We are a company which provides an app that tracking ability for running and other sports. Our core business is the making of the training schedule.

## Debug logs
unfortunately I don't have any because this is send in from multiple users.

**Comment by christocracy** [comment]
If you don’t like the accuracy of some particular location, throw it away.

This is what your “competitor” is doing.

**Comment by johnnyrockfort** [comment]
@christocracy can you explain how exactly to detect outliers?

**Comment by christocracy** [comment]
like I said, make a decision based upon the accuracy of each location.  You do know what “accuracy” means, right?
