### ISSUE TITLE
Collect location at OS-level only once a day on iOS / schedule callbacks happening outside of schedule

### ISSUE THREAD

**Issue by michaelhayman** [transistorsoft/react-native-background-geolocation#917]
Thanks for a great library.

We only want to collect the user's location maximum once per day, at the OS level.

How do I go about this?  The scheduler seems to only make the *callback* `onLocation` happen during those times in the scheduler, but the library continues tracking multiple times per day... but iOS doesn't give enough feedback to know if that's the case or not, it's just speculation.

UPDATE: Actually, on further inspection - I started the app in the simulator INSIDE of the schedule time, then waited until the scheduled window was over, I moved the current user's location in the simulator, and the location callback was called.  I think this should not happen; once the scheduled time is elapsed further callbacks should not take place.  Interestingly, if I start the app *outside* the scheduled window, no `onLocation` callback is called.

As you can see below, the location was collected 46 times over the space of 3 days; I want this to only be 3 times maximum.

Perhaps I'm misunderstanding how to configure the library.

I've been struggling with this issue for over a month, any help would be greatly appreciated!  Thanks.

## Your Environment
* Plugin version:
    "react-native-background-fetch": "^2.7.1",
    "react-native-background-geolocation": "^3.2.2",
* Platform: iOS
* OS version: 13+
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    const state = await BackgroundGeolocation.ready({
      distanceFilter: 50000,
      locationAuthorizationRequest: 'always',
      // useSignificantChangesOnly can affect testing -
      // you won't necessarily get an update even if you move halfway across the world
      useSignificantChangesOnly: true,
      // https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.state.html#schedule
      schedule: [
        '1-7 12:41-12:43',
      ],
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOWEST,
      disableMotionActivityUpdates: true,
      disableLocationAuthorizationAlert: true,
      // allow the background-service to continue tracking when user closes the app
      stopOnTerminate: false,
      // auto start tracking when device is powered-up
      startOnBoot: true,
})

    if (!state.enabled) {
      await BackgroundGeolocation.startSchedule()
    }
```

(*not* using `start()`)

## Expected Behavior
The library should only look at a user's current location within the interval.

In testing, the *callbacks* only seem to happen on that interval, but the OS reports that the library is at least *looking* at location data up to 20 times a day.

## Actual Behavior
![image_from_ios](https://user-images.githubusercontent.com/1134239/70216877-d74e9100-1759-11ea-806b-2c725689ce5f.png)

## Steps to Reproduce

1. Set schedule, configure app as above
2. Wait 3 days
3. See how many times the location has been updated when the OS pops up an alert

OR

1. Start the app in the simulator inside of the schedule time
2. Wait until the scheduled window is over 
3. Move the current user's location in the simulator
4. The location callback gets called

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
<img width="565" alt="Снимок экрана 2019-12-05 в 12 44 15" src="https://user-images.githubusercontent.com/1134239/70218735-fe5a9200-175c-11ea-8498-6889be8c9235.png">

**Comment by christocracy** [comment]
iOS scheduler requires engaging the significant location changes api; which records a location about every 1000 meters, when the plugin asks “Am I within a schedule period?”.

Don’t use the scheduler.  Simply listen to background-fetch api and make your own decision if now is a good time to execute #getCurrentPosition,

**Comment by michaelhayman** [comment]
Okay, thanks for your response, appreciate it.  Will check it out.
