### ISSUE TITLE
Removing an event handler

### ISSUE THREAD

**Issue by neno-giscloud** [transistorsoft/react-native-background-geolocation#92]
Could there be an off() method to remove event handlers?

**Comment by christocracy** [comment]
Nobody has ever asked for this in over 3 years.  What is your use-case?  Why would you want to continue to track but not receive events?  Why not just `#stop` the plugin?

**Comment by neno-giscloud** [comment]
An `error` event handler sets a flag to indicate if the user hasn't allowed background location access. This shows a warning in the app. 
It also attaches a handler to listen to next `location` event which would indicate the user set the proper permission, resets the flag and removes the warning label.
At this point I'd like to remove the `listen` handler.

**Comment by christocracy** [comment]
And what is your pain point?

On Sunday, June 12, 2016, neno-giscloud <notifications@github.com> wrote:

> An error event handler sets a flag to indicate if the user hasn't allowed
> background location access. This shows a warning in the app.
> It also attaches a handler to listen to next location event which would
> indicate the user set the proper permission, resets the flag and removes
> the warning label.
> At this point I'd like to remove the listen handler.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/92#issuecomment-225426063>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l2bQqKvxt7OKoN9qMLioh_3vkt21ks5qK-RfgaJpZM4Izwju>
> .
>


-- 
Snet form Gmail Mobile

**Comment by neno-giscloud** [comment]
Currently the `location` handler checks the aforementioned flag to see if any action is needed which is fine and doesn't affect the app but it shouldn't have to do anything. Cutting off that code path seems like a better practice.

**Comment by christocracy** [comment]
Is this functionality still desired?

**Comment by christocracy** [comment]
There is now an `#un` (@alias `removeListener`).  In fact, you should now `#un` your listeners in `componentDidUnmount` now.
