### ISSUE TITLE
Can set `distanceFilter` to 1(m)?

### ISSUE THREAD

**Issue by abinhho** [transistorsoft/react-native-background-geolocation#920]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
3.0.4
```

## Expected Behavior

When user moved 1m. Get lat/lng and send to server. Because I need to tracking user move from this room to other room in my house. 10m is not my expected.

## Actual Behavior

It's seem 10m is minimum.

## Steps to Reproduce

```
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 1,
      // locationUpdateInterval: 5000,
      locationAuthorizationRequest: 'always',
      stopTimeout: 15,
      // Application config
      debug: true,
      notification: {
        title: 'SocanApp',
        text: 'Tracking engaged'
      },
}
```

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
```

</details>

**Comment by christocracy** [comment]
You can set it 0 if you want.  The native device apis for Android/iOS will try their best.  No guarantee it’ll happen.

**Comment by abinhho** [comment]
Thanks you !
