### ISSUE TITLE
Accuracy of captured coordinates 

### ISSUE THREAD

**Issue by Jacky9425** [transistorsoft/react-native-background-geolocation#921]
Hi, I've noticed that in the `Location` object, there is an `accuracy` in the `coord` schema. May i know what is the measurement of the accuracy? (meaning does higher accuracy value indicating a more accurate captured coordinate?)

**Comment by christocracy** [comment]
No location is a simple point on earth.  The best possible accuracy you’ll get from gps is *5 meters*, meaning the *real* location is a circle where the center point is lat/lng and accuracy is the radius.  The real location is somewhere in that circle.

If you have an accuracy of 1000, draw a circle now with a radius of 1000 meters.  The *real* location is somewhere within the 1000 meter circle.

**Comment by Jacky9425** [comment]
Okay, thanks for justifying that.
Also, the doc mentioned 

"`⚠️ Do not execute any API method which will require accessing location-services until the callback to #ready executes (eg: #getCurrentPosition, #watchPosition, #start).`

does it means that without initialising `BackgroundGeolocation.ready`, we should not execute `BackgroundGeolocation.getCurrentPosition` alone ?

**Comment by Jacky9425** [comment]
May i know why `Location.coord` still can be captured even though `start()` is not initialised?

From my understanding:
1. BackgroundGeolocation.ready() gets ready the plugin, start() will toggle whether the tracking starts or pause/stop.

2. if the `state.enabled` is `false` at the callback function of `ready()`, calling `start()` afterwards will start the plugin (getting `state.enabled === true`).

3. If the plugin is not started, why is `getCurrentPosition` still returning the coordinates? Is the coordinates actually coming from `onLocation` listener (current testing calls `getCurrentPosition` directly regardless `state.enabled` being true or not)?

**Comment by christocracy** [comment]
You’re think too deeply about this.  Just follow the directions.

**Comment by Jacky9425** [comment]
Okay. However any advice if having issue of getting wrong location?
The obtained location is not too far from the exact but still its not giving the correct area
