### ISSUE TITLE
Timestamp in location

### ISSUE THREAD

**Issue by Jacky9425** [transistorsoft/react-native-background-geolocation#924]
May i know what does the `timestamp` in `Location` object indicating?

{
   "timestamp":     [Date],     // <-- Javascript Date instance
   "event":         [String],    // <-- motionchange|geofence|heartbeat
   "is_moving":     [Boolean],  // <-- The motion-state when location was recorded.
   "uuid":          [String],   // <-- Universally unique identifier
   "coords": {
       "latitude":  [Double],
       "longitude": [Double],
       "accuracy":  [Double],
       "speed":     [Double],
       "heading":   [Double],
       "altitude":  [Double]
   },
   "activity": {
       "type": [still|on_foot|walking|running|in_vehicle|on_bicycle],
       "confidence": [0-100%]
   },
   "battery": {
       "level": [Double],
       "is_charging": [Boolean]
   },
   "odometer": [Double/meters]
}

**Comment by christocracy** [comment]
What do you think it might be?

**Comment by Jacky9425** [comment]
could be the dateTime when the location is obtained?

**Comment by christocracy** [comment]
What else could it possibly be?  What would a geolocation be if you had no idea when it was from?

**Comment by Jacky9425** [comment]
okay, but currently my local time is 09:00 am, why the timestamp i get is 2019-12-13T01:00:21.683Z instead?

**Comment by christocracy** [comment]
Because it’s UTC format.

**Comment by Jacky9425** [comment]
sorry not very familiar with date format, does it means that the api return me a timestamp from another timezone?

**Comment by christocracy** [comment]
Google is your friend: “date format UTC”.

https://en.m.wikipedia.org/wiki/Coordinated_Universal_Time

**Comment by christocracy** [comment]
Programming languages *know* how to turn a UTC timestamp into one’s local time of he/she who views it.
