### ISSUE TITLE
onLocation is not updating during the trip

### ISSUE THREAD

**Issue by Jacky9425** [transistorsoft/react-native-background-geolocation#929]
## Your Environment
* Plugin version: 3.3.2
* Platform: Android
* OS version: android 10
* Device manufacturer / model: One Plus 7
* React Native version (`react-native -v`): 0.59.8
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
     {
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	distanceFilter: 0,
	locationTimeout: 120,
	stopTimeout: 10,
	debug: __DEV__,
	logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
	stopOnTerminate: false,
	startOnBoot: true,
	locationAuthorizationRequest: "WhenInUse",
	reset: __DEV__,
	allowIdenticalLocations: true,
	disableElasticity: true,
	persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
	maxRecordsToPersist: 1000,
	maxDaysToPersist: 7
};
```

## Expected Behavior
tracking the trips based on the route taken

## Actual Behavior
tracking seems fine when depart then in the middle of the trip it does not return any coordinates

## Steps to Reproduce

1. start tracking when walking to work
2. app went background (home button)

## Context
obtain the route taken on certain trips.

## Debug logs
its on release mode

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

remarks, i have the trips recorded in the attachments below:

this is the polyline mapview of recorded trips
![WhatsApp Image 2019-12-17 at 10 56 44 AM](https://user-images.githubusercontent.com/45056256/70961215-15ce3f00-20bc-11ea-8b43-8b1c9dfdc7b9.jpeg)

to ensure it obtain the correct positions i made a marker version and this is the results
![WhatsApp Image 2019-12-17 at 10 56 31 AM](https://user-images.githubusercontent.com/45056256/70961220-18309900-20bc-11ea-9170-dcd733345b54.jpeg)

My route: The departure is correct and the track is correct, then i passed by the road in front One Precinct and cross the road to TM Point and my destination is Subway. However the coordinates is not complete in the middle.

**Comment by christocracy** [comment]
>locationAuthorizationRequest: "WhenInUse"

You need “Always”.

When developing, use verbose logging with debug: true

**Comment by Jacky9425** [comment]
so it was `locationAuthorizationRequest` affecting the location listening?

also `adb logcat *:S TSLocationManager:V ReactNativeJS:V ReactNative:V ` is showing log only in debugging mode, can i get the logs (emailLog()) during release mode?

**Comment by Jacky9425** [comment]
Hi @christocracy , i've notice a pattern in my tracking. 
1. if BackgroundGeolocation.start() runs, and no notification displayed (informing about location service running), the app is more likely killed/terminated on background after some time

2. With notification, the app seems will execute tracking smoother. (OS will less likely kill the app)

My question is does  the notification related to `foregroundService` config in android?

since my own personal phone is running on Android 10, so more likely my other users are facing tracking issue cause the particular config is set to false if its < Android 8.
