### ISSUE TITLE
Android Vulnerability

### ISSUE THREAD

**Issue by stephen-standridge** [transistorsoft/react-native-background-geolocation#932]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS or Android: Android
* OS version: 28 + 29
* Device manufacturer / model: Not specific to device
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 15,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      disableLocationAuthorizationAlert: true,
      disableMotionActivityUpdates: true,
      disableStopDetection: true,
      locationAuthorizationRequest: 'Always',
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'title not enabled',
        titleWhenOff: 'title off',
        instructions: 'Opendoor requires background location permission',
        cancelButton: 'cancel',
        settingsButton: 'settings',
      },
      stopOnTerminate: false,
      startOnBoot: true,
      autoSync: false,
    }
```

## Expected Behavior
Encryption vulnerabilities should not occur. Maybe updating that library will fix it?

## Actual Behavior
We get this encryption vulnerability.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Are you talking about this?
![](https://dl.dropboxusercontent.com/s/4htluip2jos98v9/Screenshot%202019-12-18%2016.40.13.png?dl=1)

You're not using the new [`encrypt: true`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#encrypt) so ignore it.

**Comment by christocracy** [comment]
Android probably doesn't like how the `ENCRYPTION_PASSWORD` comes from a `<meta-data />` element in `AndroidManifest.xml`.  In the future, the encryption-password will be placed somewhere more secure.

But since you're not using the plugin's new Encryption feature, the warning doesn't apply to you.

**Comment by stephen-standridge** [comment]
Awesome, thank you for your quick reply!
