### ISSUE TITLE
QUESTION: How to determine if user is currently within or outside of a geofence

### ISSUE THREAD

**Issue by ninjz** [transistorsoft/react-native-background-geolocation#933]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS and Android
* OS version: all
* Device manufacturer / model: all 
* React Native version (`react-native -v`): 0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    // Geolocation Config
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    // Activity Recognition
    stopTimeout: 1,
    // Application config
    debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
    startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    // Geofence config
    geofenceInitialTriggerEntry: true,
}
```

## Context

I know that currently there is an option to trigger an initial **ENTER** event during the creation of a geofence. But i'm wondering if there's any way to determine if a user is currently within a geofence or not at any given moment. 

The edge cases I want to account for is:

### Case 1
A user has entered a geofence (where an **ENTER** event is then triggered) and then their phone dies (dead battery for example). If the user then goes outside of the geofence and powers up their device again, there should be an **EXIT** event so that we know the user has exited the geofence.

### Case 2
Similar to case 1, except, instead of powering on their device just outside of the geofence, they power on their device in another geofence B. The expected outcome of the onGeofence events would trigger a **EXIT** and then a **ENTER** event. 

So my question is, does this SDK already support that? Or is there some other way to handle these cases?

Thanks

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
The plugin does not maintain any memory of geofence events.  But your server, presumably, does.  You should be able to infer these events at your server, no?

**Comment by ninjz** [comment]
I was hoping to refrain from needing to post the tracking information to my server. In any case, I have worked out a solution last night by recreating the geofences on each app launch. This would trigger the `onGeofence` handler when `geofenceInitialTriggerEntry` is true, that way I always start the app in a state where the user is outside of all geofences and only consider them within one after the handler is called. 

Just to be sure, do you see any issues with this approach?

Thanks

**Comment by christocracy** [comment]
It’s unwise to recreate geofences in each launch.  It goes against Google’s geofencing best-practices.

**Comment by ninjz** [comment]
I see. Well in that case I assume I can still do that, but would just not be following the best practice. Which i'm fine with. In any case I am initially launching my application on iOS.

Though looking more into this through the Google documentation, I see that the geofences are to be re-registered after a device's boot complete action. I assume that is already being handled by this library, but what about when that event occurs an event be dispatched to the onGeofence handlers to register the current state of the geofences?

**Comment by christocracy** [comment]
The plugin does not remember where the device last was after a device reboot.  How is it supposed to determine if the current location relative to current geofences should fire a geofence event?

This memory should be saved on your server and determined there.
