### ISSUE TITLE
Not receiving correct updates of Activity on both onActivityChange and onLocation listeners

### ISSUE THREAD

**Issue by tusharsarkar** [transistorsoft/react-native-background-geolocation#935]
## Your Environment
* Plugin version: 3.3.2
* Platform: Android
* OS version: Android 9.0
* Device manufacturer / model: Redmi note 7 pro
* React Native version (`react-native -v`):  0.59.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->



        BackgroundGeolocation.onActivityChange(this.onActivityChange.bind(this));
        BackgroundGeolocation.onLocation(this.onLocation.bind(this), this.onError.bind(this));
        BackgroundGeolocation.ready({
          locationAuthorizationRequest: 'Any',
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter:  10,
          stopTimeout: 1,
          debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
          stopOnTerminate: true,   // <-- Allow the background-service to continue tracking when user closes the app.
          startOnBoot: false,        // <-- Auto start tracking when device is powered-up.
          preventSuspend: true,     //iOS Only location-services have been switched off while running in the background.
          persistMode: BackgroundGeolocation.PERSIST_MODE_NONE,  // Persist nothing (neither geofence nor location events)
        }, (state) => {
          console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
          LogEvent("Background Geo",state)
    
          if (!state.enabled) {
            
            BackgroundGeolocation.start();
          }
        });


```

## Expected Behavior
onActivityChange should get the listener trigger on the activity change with correct activity. Ex. If I am walking then I should get walking, and if I am driving I should get on_vehicle.

onLocation should get the location updates with the correct activity.

## Actual Behavior

But I am not getting the callbacks on a regular basis and even I got it sometimes it gives me wrong activity in response.
Also seen some time, two devices with the same activity at the same time did not give the same output.
I am getting an activity `Walking` on one device and the other giving me `on_vehicle`. 

onLocation listener is also sending location object with wrong activity.

There is no consistency of result sometimes it works perfectly and sometimes it is giving you the wrong response. When it sending you wrong output it continues to do so for a long time.

## Steps to Reproduce
1. Integrate the code and get the response on listeners

## Context
I have to identify switch on / off on_vehicle mode of the app.

**Comment by christocracy** [comment]
Google's [ActivityRecognitionClient](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient) depends on the presence and quality of sensors (accelerometer, gyroscope, magnetometer) on a particular device.  If any of those sensors are missing or are of low quality, the result returned by the API will be affected.

There is no configuration for this API -- it's just an **ON / OFF** switch.  It's either on or off.
