### ISSUE TITLE
BackgroundGeolocation.onGeofence not getting called when app is dead on IOS

### ISSUE THREAD

**Issue by surafelbm** [transistorsoft/react-native-background-geolocation#938]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS
* OS version: 13.3
* Device manufacturer / model: I Phone 11
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
            // Geolocation Config
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            geofenceModeHighAccuracy: true,
            // Activity Recognition
            stopTimeout: 1,
            enableHeadless: true,
            // Application config
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
            startOnBoot: true
        }, (state) => {
            console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
      
            if (!state.enabled) {

                
                
                BackgroundGeolocation.startGeofences()
            }
        });
```

## Expected Behavior

`BackgroundGeolocation.onGeofence` is supposed to be called and i should get a notification about the geofence i entered
## Actual Behavior

When i close the app and remove it from the recent apps the `BackgroundGeolocation.onGeofence` event doesn't get called 
## Steps to Reproduce

1. Configure the plugin with the above config code
2. Add a geofence 
```javascript
BackgroundGeolocation.addGeofence({
            identifier: "Home",
            radius: 200,
            latitude: 45.51921926,
            longitude: -73.61678581,
             notifyOnEntry: true,
            notifyOnExit: true,
             extras: {
              route_id: 1234
        }
        }).then((success) => {
        console.log("[addGeofence] success==========");
        }).catch((error) => {
        console.log("[addGeofence] FAILURE: ========", error);
        });

        BackgroundGeolocation.onGeofence(geofence => {
            console.log("[geofence] ", geofence.identifier, geofence.action);

            PushNotification.localNotification({
                title:"Hello",
                message: "You entered a geofence"
            })
            
        });
```
3. run the app
4.in the IOS simulator got to debug and change the custom location to lat:45.51921926 and long:-73.61678581

## Context

i am trying to get a notification when a user enters a certain geofence. i am using `react-native-push-notification` for handling notifications
the notification pops if the app is in the background (not removed from the recent apps).

i can see the app starting in the background when app is dead and geofence is entered but non of my code inside the `BackgroundGeolocation.onGeofence` is getting executed 

i tried turning on `degub:true` in the config and i get the default debug notification `ENTER Geofence: geofence_id` even when the app is dead.

<img width="293" alt="Screen Shot 2020-01-01 at 11 02 50 AM" src="https://user-images.githubusercontent.com/11531221/71639375-9d07df00-2c86-11ea-9201-a3a7efdbabe2.png">

but my custom notification is not getting fired.

i also have Headless task registered for Android and everything works fine on Android

**Comment by christocracy** [comment]
In your `onGeofence` handler, add the following log message:
```
BackgroundGeolocation.logger.debug("************ onGeofence fired");
```

Fetch the plugin logs to see if that log message exists in the plugin logs.  See `#emailLog` method to fetch the logs.

**Comment by surafelbm** [comment]
Okay, but how can i see the log when the app is terminated? In the documentation it says logs are printed on XCode but XCode automatically detaches from the app when its terminated.

**Comment by surafelbm** [comment]
Okay i tried that but didn't find any log messages like this `"************ onGeofence fired"`

**Comment by surafelbm** [comment]
Okay i got it to work.

i added the onGeofence event handler function on a static method of another class like this:

```
static registerGeofence(id,lat,long,data){

        BackgroundGeolocation.addGeofence({
            identifier: id,
            radius: 200,
            latitude:lat,
            longitude: long,
             notifyOnEntry: true,
            notifyOnExit: true,
             extras: {
              route_id: 1234
        }
        }).then((success) => {
        console.log("[addGeofence] success==========");
        }).catch((error) => {
        console.log("[addGeofence] FAILURE: ========", error);
        });
       BackgroundGeolocation.onGeofence(geofence => {
            console.log("[geofence] ", geofence.identifier, geofence.action);

            PushNotification.localNotification({
                title:"Hello",
                message: "You entered a geofence"
            })
            
        });
    }
```

and now i just moved the `onGeofence` handler to the `componentDidMount` function of the first screen and it started working

any idea why this happened?
