### ISSUE TITLE
IOS 13.x.x location permission not asking as "allow always", device xs, but properly working in iphone 6, 5s 12.x.x 

### ISSUE THREAD

**Issue by soban1234** [transistorsoft/react-native-background-geolocation#939]
"react": "16.8.6",
    "react-native": "0.60.3",
    "react-native-background-fetch": "^2.6.1",
    "react-native-background-geolocation": "^3.0.9",

i am using this package for android and ios both. working is quite fine.

only issue is, in IOS devices, for ios other than 13.x.x permission prompt is showing allow location always, but in 13.x.x it is not showing.

though i have added strings as 

<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>An App would like to use your location to navigate you from current location to your destination.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>An App would like to use your location to navigate you from current location to your destination.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>An App would like to use your location to navigate you from current location to your destination.</string>

**Comment by surafelbm** [comment]
Prior to iOS 13, there were two location permissions: When In Use (foreground) and Always (background). iOS 13 introduces a third option: Allow Once. The “Allow Once” option is considered a temporary authorization, with the app prompting again the next time it’s opened. This option allows users to grant When In Use for a single session

Read [this](https://gimbal.com/ios-13-location-permissions/) for details

**Comment by christocracy** [comment]
I wrote a blog-entry about this [in August](https://medium.com/@transistorsoft/ios-13-and-android-q-support-beb7595d2c24)
