### ISSUE TITLE
motion + fitness

### ISSUE THREAD

**Issue by yond** [transistorsoft/react-native-background-geolocation#94]
Is this permission necessary?
If not, how do I disable asking for it?
If yes, how do I stop these incessant push notifications giving motion updates?

**Comment by christocracy** [comment]
It's not necessary if you don't care about [activity data](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Location-Data-Schema) (ie: `on_foot, in_vehicle, running, still, on_bicycle, etc`.)

[disableMotionActivityUpdates: true](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/README.md#param-boolan-disablemotionactivityupdates-false)

The plugin doesn't post *Push* notifications.  It posts *local* notifications to help you while developing.  These are disabled with [debug: false](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#param-boolean-debug-false)
