### ISSUE TITLE
Plugin does not retry/recover after network or connectivity error

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#941]
## Your Environment

* Plugin version: 3.3.0 and 3.3.2
* Platform: Both iOS and Android
* OS version: iOS 13, android 9
* Device manufacturer / model: various
* React Native version: 0.61.5
* Plugin config: Will include in debug log later

## Description

One of our testers is in a rural location and often enters cellular cells where there is poor reception. A few times a day, the phone's cellular data connection will have trouble and this plugin (ie. 'RNBGL') will be unable to post location data to our server.

We have variously seen these types of error messages in the debug log:

⚠️  server.example.com is not responding.  Will try again after 10 records.
⚠️  Response: 0, Unable to resolve host "server.example.com": No address associated with hostname
⚠️  Response: 0, Failed to connect to server.example.com/n.n.n.n:443

These are legitimate errors and we accept that they will occur. Up to this point, it's all fine and good.

However, after one of these errors occurs, and the phone enters an area with good reception (or wifi), we expect the plugin to detect this and start uploading data again. However, this is not the case. We often have to restart/open/foreground our app and then the plugin will start emitting again.

So a sequence like this happens:

1. Tester's phone has network connectivity issues. Plugin stops uploading location.
2. Error messages are seen in the log.
3. Tester goes to a new area with good reception. Alternatively, tester goes home and connects to home wifi.
4. A variable amount of time elapses.
5. Tester opens the app. Plugin resumes uploading location again.

Expected: Soon after step 3 occurs, the plugin should resume uploading. In other words, step 4 only lasts for a short amount of time.

Observed: Step 4 lasts until the tester opens the app. Sometimes this can be 10-20 minutes or more. In one instance, it lasted for about 90 minutes.

## Expected Behavior

See above

## Actual Behavior

See above

## Discussion

Most of the time, the plugin works as expected. So if this issue doesn't occur, then all is good.

However, when one of the above-mentioned error messages occurs, the plugin stops uploading.

Also, when this happens, I can see in the log that the plugin is still acquiring locations and saving them in the offline database for uploading later. So the plugin is still operating and 'doing stuff', just that, for some reason, it doesn't upload to the server.

When connectivity resumes, the plugin successfully uploads all the 'offline' data points (we have `maxRecordsToPersist` of 20).

## Debug logs

Will email separately if needed later.

I'm going to test out a debug version of our app with some extra connectivity-related debugging. Hopefully that will produce a more useful debug log.

**Comment by christocracy** [comment]
Logs are required.

**Comment by bengtan** [comment]
For privacy reasons, I have sent you a log via email. Please let me know if you haven't received it.

## Overview

Overview

According to our server logs, the following data points were posted:

0c89baf0-172b-41dd-95ab-4025764ca12f recorded at 2020-01-03T20:18:19.00Z
96e28ba9-52f5-4d0d-8c63-ab8619515d74 recorded at 2020-01-03T20:33:45.00Z
19 data points in between
35db653c-f1f2-417d-bb1c-62c710733f02 recorded at 2020-01-03T20:35:11Z

0c89baf0 was the data point before connectivity broke. The app was restarted around 2020-01-03T20:35:11Z. Then data point 35db653c was uploaded, along with the 20 data points prior to that which were stored offline. The earliest 'offline' data point is 96e28ba9.

## Log file

I added in some extra debugging to the log. Some are specific to our app but the ones relevant to this ticket are:

* The `onHttp` handler logs the http response and whether it was successful.
* The `onConnectivityChange` handler logs the connectivitychange event.
* The line 'BGGL didMount' indicates the app was mounted (ie. restarted)

The log is in timezone GMT-6.

## Notable events

Notable events in the log (with line numbers):

Data point 0c89baf0 is acquired:

L46499 01-03 14:18:18.516: `✅  INSERT: 0c89baf0-172b-41dd-95ab-4025764ca12f`

Data point 0c89baf0 is uploaded:

L46520 01-03 14:18:19.031: `ℹ️  BGGL onHttp success: {...}`

Connectivity breaks:

L46611 01-03 14:18:37.371: `ℹ️  BGGL onConnectivityChange({"connected":false})`

which results in a bunch of http errors. The first one:

L46822 01-03 14:21:40.658: `‼️  BGGL onHttp error: {...}`

There are 7 consecutive http errors.

A few minutes later, connectivity is re-established:

L47265 01-03 14:22:14.903: `ℹ️  BGGL onConnectivityChange({"connected":true})`

However, the first HTTP request after connecting fails:

L47277 01-03 14:22:16.603: `‼️  BGGL onHttp error: {...}`

Maybe the internet isn't fully back up yet, so maybe this is okay.

Up until this point, everything is fine or could be legitimate errors.

However, for the next 13 minutes, until the app is restarted, no more HTTP requests are made. Locations continue to be acquired (there are 200+ of them) but only the most recent 20 are stored.

The app is restarted:

L54289 01-03 14:35:08.231: `ℹ️  BGGL didMount`

Data point 35db653c is acquired:

L54361 01-03 14:35:10.499: `✅  INSERT: 35db653c-f1f2-417d-bb1c-62c710733f02`

Data point 35db653c and other offline points are uploaded:

L54398 01-03 14:35:11.503: `ℹ️  BGGL onHttp success: {...}`

Normal operation resumes

**Comment by christocracy** [comment]
I believe this is due to a recent feature request where someone request the plugin throttle HTTP requests when an HTTP response `0` is returned, rather than continue needless consuming battery attempting HTTP requests.

01-03 14:22:11.572 INFO [HttpService a] 
  🔵  HTTP POST batch (20)
.
.
 ⚠️  staging.dev.tinyrobot.com is not responding.  Will try again after 10 records.

Here, the plugin internally sets an `autoSyncThreshold` of `count + 10`.  However, since you've configured `maxRecordsToPersist: 20` and the current `count` is `20`, this automatic `autoSyncThreshold` becomes `20 + 10 = 30` which will never be achieved.

```java
if (config.getIsMoving() && isConnectedMobile()) {
                // If we failed to connect, throttle HTTP attempts by applying an autoSyncThreshold, even if not configured to do so:  eg: COUNT + 10
                int count = BackgroundGeolocation.getLocationDAO(context).count();
                int offset = (config.getAutoSyncThreshold() > 0) ? config.getAutoSyncThreshold() : 10;
                mAutoSyncThreshold.set(count + offset);
                TSLog.logger.warn(TSLog.warn(call.request().url().host() + " is not responding.  Will try again after " + offset + " records."));
            }
```

I will add a 3rd condition to the logic above to *not* automatically apply the `autoSyncThreshold` when `maxRecordsToPersist` is set.
```java
if (config.getIsMoving() && isConnectedMobile() && config.getMaxRecordsToPersist() < 0) {
  .
  .
  .
}
```

**Comment by bengtan** [comment]
Progress!

The RNBGL maintainer concedes it's a (recent?) RNBGL bug.

I'll continue corresponding with him. (Maybe try to come up with a work-around?)

**Comment by bengtan** [comment]
DELETED. Wrong thread.

**Comment by bengtan** [comment]
Hi,

Thanks for confirming this issue. Some follow-up questions please.

Which version of the plugin did this bug appear in? (So I can work out which versions of our app are affected.)

Are you planning on releasing a fix 'soon'? (So I can decide whether to wait for a fix or try to devise a work-around myself.)

Also, I'm seeing this issue on both iOS and android. Whatever fix you devise, please apply to both platforms.

**Comment by bengtan** [comment]
> Also, I'm seeing this issue on both iOS and android. Whatever fix you devise, please apply to both platforms.

Furthermore ...

Is the logic for iOS the same? Could you post the relevent/corresponding snippet from the iOS code? This will help me devise work-arounds for both platforms if needed.

**Comment by christocracy** [comment]
Install from `#dev` branch in private repo:

```
yarn add https://github.com/transistorsoft/react-native-background-geolocation-android.git#dev
```

**Comment by bengtan** [comment]
Thanks. We'll give it a try and see how testing goes. It might be a day or two before we're done with testing though.

**Comment by bengtan** [comment]
Preliminary results of testing: The fix is good. I can see in the log that the plugin continues to retry once every 10-30 seconds.

We'll continue to test for another day or two. If you don't hear anything from me, then presume no news is good news.

**Comment by bengtan** [comment]
Another day of testing. The fix is good.

Please release (3.4.3?) 'soon-ish' into react-native-background-geolocation. That's the repository we prefer to use.

Thanks.

**Comment by christocracy** [comment]
I won’t be releasing to public repo for at least a month.

You should be using the private repo always.

**Comment by bengtan** [comment]
The public repository is much more convenient. Trying to configure our CI/CD tools to fetch code from a private repository for a dependency is ... possible but painful.

**Comment by christocracy** [comment]
I purposefully throttle releases to public repo to about every 3 months.  This will not change.

I’m experimenting with Github’s new package manager.

**Comment by RichardChua** [comment]
Hi Christocracy, may I know this still available?
yarn add https://github.com/transistorsoft/react-native-background-geolocation-android.git#dev
