### ISSUE TITLE
Issues With Android 9

### ISSUE THREAD

**Issue by Namec** [transistorsoft/react-native-background-geolocation#942]
Currently i am doing my tests with two devices

1 - OS Version Android 8.1
2 - OS Version Android 9

on the 8.1 device, everything works well, the backbround Task is working corectly and it rigers the in_vehicule activity.

but on the Android 9 device, i receive only one location and then it goes blind, when i start the plugin. 

any idea about this.

best

**Comment by christocracy** [comment]
see http://dontkillmyapp.com

**Comment by Namec** [comment]
i think that everything is ok from that side (http://dontkillmyapp.com)

i managed to solve this by assigning : BackgroundGeolocation.changePace(true)

when i start the plugin, and then it works OK.

then my new question is : 

when i force the moving status when changing pace to true, doest it detect when it's really back to stationary mode ???

i added : 
stopTimeout: 5 

but i don't know if it can do the job

**Comment by christocracy** [comment]
>doest it detect when it's really back to stationary mode ???

No idea.  That's up to your particular device.  Why not try it and see?

**Comment by Namec** [comment]
After tens of tests i found the probleme !!!

my setup trigers the in_vehicule only, and doesnt work on Android 9 (tested on Oppo A9 and Infinix S4)

but when i added the walking activity.

i found that the plugin works well, but the recognized activity is always Walking, even if i drive 100 Km by car.

is this related to the OS version or the hardware it self.

and do you have any advice to manage this.

best

**Comment by christocracy** [comment]
>is this related to the OS version or the hardware it self.

Probably the specific hardware of that device.

>and do you have any advice to manage this.

No.  The ActivityRecognition API from play-services is a "black box" with only an on/off switch.  There is no configuration to it.  You turn it on and magic happens.  This is proprietary code made by Google.  It aggregates sensor data from accelerometer, gyroscope and magnetometer to output an answer: `on_foot`, `in_vehicle`, etc.  It totally depends on the quality of sensors of that particular device.  Garbage in = garbage out.

**Comment by Namec** [comment]
then my only two choices : 

1 - avoid auto tracking, and make the service enabled/disabled by a user action
2 - try a 3rd party library to get the speed, and if it's more than 10, i'll trigger tracking 

let the force be with us

**Comment by Namec** [comment]
damn !!

this thing gona drive me Crazy !!!

now i am discovering that when using a position simulator (Mock Location) like Lockito, everythings works fine. 

but when driving a real car, i have a lot of problems

**Comment by christocracy** [comment]
Show me the Config you’re using.  You completely ignored the issue template which asked you that information, including a bunch of other helpful info, such as device model, os version, logs.  You provided nothing.
