### ISSUE TITLE
Annoying message about allow location always

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#943]
## Your Environment
* Plugin version: 3.2.2
* Platform: iOS
* OS version: all
* Device manufacturer / model: iPhone
* React Native version (`react-native -v`): 0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```
```
App.js

componentWillMount() {
    // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.onLocation(this.onLocation, this.onError);

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange(this.onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.onActivityChange(this.onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.onProviderChange(this.onProviderChange);

    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      //debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      // url: 'http://yourserver.com/locations',
      // batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      // autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

      if (!state.enabled) {
        // BackgroundGeolocation.start(function() {
        //   console.log("- Start success");
        // });
      //  BackgroundGeolocation.startGeofences(function() {
      //     console.log("- Start Geofences success 1");
      //   });
      }
    });
  }
```

## Expected Behavior

If user choose in IOS location permission "Allows only while using", app continues asking to change the permission to "Always allow", expected behavior it shouldn't ask about Always allow permission if user choose "Allows only while using"

## Actual Behavior

app continues asking to change the permission to "Always allow

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
See API docs `Config.disableLocationAuthorizationAlert`

**Comment by christocracy** [comment]
And `Config.locationAuthorizationRequest`

**Comment by Luckygirlllll** [comment]
@christocracy if I will choose disableLocationAuthorizationAlert to true, it will ask me only one time  "Allow location always"?  or it wouldn't ask user at all to "allow location always" in iOS 13?

**Comment by christocracy** [comment]
> it will ask me only one time "Allow location always"?

The plugin will not produce a Dialog warning the user they need to authorize always.

See also `Config.locationAuthorizationRequest`.  If you don't care if the user selects "Always" or "When in Use", you'll want to set that to `Any`.

**Comment by Luckygirlllll** [comment]
@christocracy I want that "Allow always" in IOS 13 is asked only once, so I left default value of `Config.locationAuthorizationRequest ` and `set disableLocationAuthorizationAlert` to true.
