### ISSUE TITLE
BackgroundGeolocation.onLocation failure handler fires on BackgroundGeolocation.getCurrentPosition error

### ISSUE THREAD

**Issue by chestercharles** [transistorsoft/react-native-background-geolocation#945]
I am observing that when location permission are set to "Never" and the `getCurrentPosition` method is invoked, both the failure handler passed to `getCurrentPosition` and the failure handler for `onLocation` are fired.

Is this expected? 
## Your Environment
* Plugin version:
* Platform: iOS
* OS version: iOS 13.2.3
* Device manufacturer / model: iPhone 11
* React Native version (`react-native -v`): 0.59.9
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 10,
  stopTimeout: 1,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
  stopOnTerminate: false,
  startOnBoot: true,
  disableLocationAuthorizationAlert: true,
},
```

## Expected Behavior

When an error occurs during the invocation of `getCurrentPosition`, only the error handler passed to this method will be fired.

## Actual Behavior

Both the error handler for `getCurrentPosition` and `onLocation` are fired.

## Steps to Reproduce

1. Set location permissions to "Never"
2. Run the following code:
```
BackgroundGeolocation.onLocation(
  location => {
    /* ... */
  },
  error => console.log('onLocation error')
);
BackgroundGeolocation.ready(
  {
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    stopTimeout: 1,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    stopOnTerminate: false,
    startOnBoot: true,
    disableLocationAuthorizationAlert: true,
    ...config,
  },
  ready => {
    BackgroundGeolocation.getCurrentPosition(
      {},
      location => {
        /* ... */
      },
      error => console.log('getCurrentPosition error')
    );
  }
);
```

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
N/A
```

</details>

**Comment by christocracy** [comment]
>Is this expected?

Yes.
