### ISSUE TITLE
startGeofences prompts background location notification without any geofences.

### ISSUE THREAD

**Issue by stephen-standridge** [transistorsoft/react-native-background-geolocation#948]
## Your Environment
* Plugin version: 2.0.2
* Platform: iOS
* OS version: 13+
* Device manufacturer / model: Iphone
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      disableLocationAuthorizationAlert: true,
      disableMotionActivityUpdates: true,
      disableStopDetection: true,
      locationAuthorizationRequest: 'Always',
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'title not enabled',
        titleWhenOff: 'title off',
        instructions: 'Opendoor requires background location permission',
        cancelButton: 'cancel',
        settingsButton: 'settings',
      },
      stopOnTerminate: false,
      startOnBoot: true,
      autoSync: false,
    });

    BackgroundGeolocation.onGeofence(onGeofence);
    BackgroundGeolocation.onProviderChange(onProviderChange);
    BackgroundGeolocation.startGeofences();

```

## Expected Behavior
According to the [ios documentation](https://developer.apple.com/documentation/corelocation/monitoring_the_user_s_proximity_to_geographic_regions), `Whenever the user crosses the boundary of one of your app's registered regions, the system notifies your app.`. 
In this [plugin's documentation](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#startgeofences), it says `In this mode, no active location-tracking will occur — only geofences will be monitored.`.

With these two points of data, I expect that the ios `<App> has used your location <x> times in the background.` prompt should only appear if we've created and used geofences and should only show locations that the user has interacted with the geofences.

## Actual Behavior
The `<App> has used your location <x> times in the background.` prompt appears wether we have created or used geofences and suggests that our app is using the background location far more than we actually are.

## Steps to Reproduce
1. Set up the plugin like above. 
2. Escalate your app permission to non-provisional `always allow`.
2. DO NOT create geofences or create geofences that you will never overlap with.
3. Change location multiple times, but never into a geofence
4. Wait ??? amount of time for the ios system prompt

## Context
There is no good documentation about this specific prompt from Apple, nothing to tell the actual expected behavior. Too, I'm not certain if this plugin works like I expect it to or if I've configured it in a way that it won't work like I expect it to.

**Comment by christocracy** [comment]
In order for the plugin's "infinite geofencing system" to work, it needs to periodically get the current location in order to activate those geofences within the [geofenceProximityRadius](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#geofenceproximityradius).

For this reason, the iOS plugin is monitoring the iOS Significant Location Changes API, which requests a location about every 1000 meters.

iOS can only monitor 20 geofences simultaneously.

In the near future, I'm going to add a mode to disable the "infinite geofencing" feature.  It will then be your responsibility to determine when to load new geofences based upon the current location.

**Comment by stephen-standridge** [comment]
That makes sense, Thank you for clarifying!

**Comment by christocracy** [comment]
I was doing some experimenting yesterday with disabling the Significant Location Changes API from running when the number of total geofences provided to the plugin is <= 18 (the plugin reserves 2 for its own purpose).

Are loading the plugin with <= 18 geofences?
