### ISSUE TITLE
getProviderState() returns iOS permission status as 'always' even when setting is 'when in use'

### ISSUE THREAD

**Issue by alixquentin** [transistorsoft/react-native-background-geolocation#949]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS 
* OS version: 13.1.2
* Device manufacturer / model: Apple
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.onProviderChange(console.log)
```

Code is generic because issue is just about the return value of `onProviderChange` or `getProviderState`. There is a lot more code involved, but I don't have any reason to believe it would affect the issue.

## Expected Behavior

At first launch on iOS, if user selects 'When In Use', the status in object returned by `onProviderChange` or `getProviderState` should be 4 (`AUTHORIZATION_STATUS_WHEN_IN_USE`)

## Actual Behavior

At first launch, iOS native window appears asking for geolocation permission, and offers only three options: 'Never', 'Just once', or 'When in use'. If user clicks on 'When in use', onProviderChange callback is called with status: 3 (`AUTHORIZATION_STATUS_ALWAYS`) and calling onProviderState will return the same thing. 

Only when user manually goes to Settings, selects never, then re-selects when in use does the app detect that the setting is actually 'when in use' and not 'always'

## Steps to Reproduce

1. Set the following keys in Info.plist – I would like to only offer `Always` option, but removing WhenInUse option makes geolocating impossible
```
  <key>NSLocationAlwaysUsageDescription</key>
  <string>Description 1</string>
  <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
  <string>Description 2</string>
  <key>NSLocationWhenInUseUsageDescription</key>
  <string>Description 3</string>
```
2. In a global component, insert
```javascript <!-- Syntax-highlighting:  paste your code below -->
    BackgroundGeolocation.onProviderChange(console.log)
    BackgroundGeolocation.getProviderState()
```
3. Build app and run on device with JS debugging enabled
4. At iOS permission dialog, select 'When in use'
5. Observe that the first log returns status 2 for denied (since it's first launch and it's executed before the dialog appears) and the second returns status 3 for always

## Context

I'm trying to block parts of my application and reserve it to users having selected always in their geolocation settings.

I have three problems: 
- Regardless of the three keys in Info.plist, user is not offered the 'Always' option at launch. 
- The plugin has an alert itself but it's not replacing the native dialog and it rarely runs because if the user selects 'when in use' at first launch then the plugin seems to believe 'always' is selected, so `locationAuthorizationRequest: 'Always'` changes nothing in options. This behaviour of iOS returning that 'always' has been selected is not specific to the plugin, I have tried many other ways to obtain the permission status and they all return the same thing.
- Since this is the behaviour, I've also tried to find ways to prevent dialog from opening at first launch because when user changes permissions in settings, the information returned by iOS is consistent and not corrupt. But I haven't found a way to do this.

Is there any way to obtain the right setting from iOS ? As long as I can know that always has not actually been selected, I can direct the user to the app's settings and force them to select 'always'. All the libraries offering to manually request permission don't work because the OS blocks it anyway.

**Comment by christocracy** [comment]
This is correct.  This is called "Provisional Always" authorization due to the change in iOS 13.

Read more [here](https://medium.com/@transistorsoft/ios-13-and-android-q-support-beb7595d2c24)

**Comment by alixquentin** [comment]
> This is correct. This is called "Provisional Always" authorization due to the change in iOS 13.
> 
> Read more [here](https://medium.com/@transistorsoft/ios-13-and-android-q-support-beb7595d2c24)

I had a feeling it was something like that. 

How do I configure the plugin to behave like it does in the video ? I've set `locationAuthorizationRequest` and `locationAuthorizationAlert` in the config but it only opens if geolocation is deactivated. I haven't observed the same behaviour.

**Comment by christocracy** [comment]
You just need to request "Always" authorization.  If using the simulator, simulate location with "Freeway Drive" then minimize the app for about 10s.  Open the app again.

On real device, go outside and walk about 200-300 meters.  Open the app.  At some point in the future, iOS will prompt you to promote location authorization to "Always".

**Comment by chestercharles** [comment]
When the app has "Provisional Always" authorization, should I expect it to receive locations from the `BackgroundGeolocaiton.onLocation` listener when in the background?

E.g. is this expected? 

BG=put app in background
FG=brought app to foreground
![image](https://user-images.githubusercontent.com/8016126/72110027-7d129400-32f4-11ea-9e2d-ff8d2ff1cc0d.png)

**Comment by christocracy** [comment]
You should not expect locations in background until *provisional always* has been promoted to *full always*.  

While in *provisional always*, your effectively has *When in Use* authorization.

**Comment by christocracy** [comment]
You're free to *manually* promote your app to "Always" via *Settings->Privacy->Location-Services->YourApp*
