### ISSUE TITLE
Multiple Recordings

### ISSUE THREAD

**Issue by Gnative** [transistorsoft/react-native-background-geolocation#95]
Say in the a scenario that someone was running and that run recorded, then wanted to save it and begin another run recording.. but was unable to sync the original recording first.

How could the two recordings be differentiated so that they could be synced to a server with extra data such as title, description etc.

Could I possibly set an ID to the start of recording and use getLocations(ID) to get the required location data ?

Thanks in advance for any reply

**Comment by christocracy** [comment]
See config #extras in docs

On Thursday, June 30, 2016, Gnative <notifications@github.com> wrote:

> Say in the a scenario that someone was running and that run recorded, then
> wanted to save it and begin another run recording.. but was unable to sync
> the original recording first.
>
> How could the two recordings be differentiated so that they could be
> synced to a server with extra data such as title, description etc.
>
> Could I possibly set an ID to the start of recording and use
> getLocations(ID) to get the required location data ?
>
> Thanks in advance for any reply
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/95>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l9LJnb0VoxhmSFxMVUWjGrOpcOHUks5qRD35gaJpZM4JCo0V>
> .
>


-- 
Snet form Gmail Mobile

**Comment by Gnative** [comment]
ah ok.. thanking you
