### ISSUE TITLE
"Exit provisional authorization inducer" while locationManager:didExitRegion

### ISSUE THREAD

**Issue by anton-sharpdev** [transistorsoft/react-native-background-geolocation#950]
Sometimes geofence events are not triggered. In logs I found out, that exitregion is called but return this message instead of usual 'identifier'

## Your Environment
* Plugin version: 3.4.2
* Platform: iOS
* OS version: 13.2.3
* Device manufacturer / model: 
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    activityRecognitionInterval = 10000;
    activityType = 1;
    authorization =     {
    };
    autoSync = 1;
    autoSyncThreshold = 0;
    batchSync = 0;
    debug = 0;
    desiredAccuracy = "-1";
    desiredOdometerAccuracy = 100;
    didLaunchInBackground = 0;
    disableAutoSyncOnCellular = 0;
    disableElasticity = 0;
    disableLocationAuthorizationAlert = 0;
    disableMotionActivityUpdates = 0;
    disableStopDetection = 0;
    distanceFilter = 100;
    elasticityMultiplier = "0.1";
    enableTimestampMeta = 0;
    enabled = 0;
    encrypt = 0;
    extras =     {
    };
    geofenceInitialTriggerEntry = 1;
    geofenceProximityRadius = 1000;
    geofenceTemplate = "";
    headers =     {
        Authorization = "Bearer eyJraWQiOiJjb1VLZVwvZndyY3dmTDgwRVZvVTFxaHFuYmlURVMrZm1qelB3MHFuZkZyYz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI0MmRjMGRhNS0xNTEzLTRmMzctYmQ3YS00YjQzNzAxNGUzZTIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX01ZTERQTjQ2biIsInBob25lX251bWJlcl92ZXJpZmllZCI6dHJ1ZSwiY3VzdG9tOmFjY291bnRpZCI6IjEyOTIiLCJjb2duaXRvOnVzZXJuYW1lIjoiNDJkYzBkYTUtMTUxMy00ZjM3LWJkN2EtNGI0MzcwMTRlM2UyIiwiZ2l2ZW5fbmFtZSI6IlRlc3QiLCJhdWQiOiI1bnJzYnJrNWJsMjU3djhzbGkwaDlqbnFzNCIsImV2ZW50X2lkIjoiMjY1M2JhN2ItN2NlOC00MWY4LTkxMmUtYjEzYTA2NDg3NTJkIiwiY3VzdG9tOmRyaXZlcmlkIjoiMjEzOCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTc4NTk1NjA0LCJjdXN0b206aW50ZXJuYWxJZCI6IjIxMzgiLCJwaG9uZV9udW1iZXIiOiIrMTYwNDg2MTI0MDgiLCJleHAiOjE1Nzg1OTkyMDUsImN1c3RvbTp1c2VyX3R5cGUiOiJkcml2ZXIiLCJpYXQiOjE1Nzg1OTU2MDUsImZhbWlseV9uYW1lIjoiZHJpdmVyOCJ9.RVpc-zXnWmCrimzjr5tPsw3TbdgT84oEEU_abhQ1xczzXITT2ql9p2lfEtZmU_UeE50A3-mmK-offP6kHr1zofimIo2Fw1KSiL8omohWGEs-BTJmLTqCrjBLX9htGgKdnXdDnf8DNyfJjDBlH2ajgrSeEl5jkJMHialeeqVyKw0GPT8ieOX3cL7VsQKA4-Lx5ZdugZhY8kyZRc2aYynxYhcjppenZFj_937YTjOqc2sXPV4-XwIaD4Z0kXrYxvE5s4I-tK2bOmXvR4Ub6XcrsfW2T93_WS-pTaL3kjRc5OLKhyKfFiswq45gjGLstYjHmTR465SD-iRQZcUMwmAFbw";
        "X-1SHIFT-DEVICE-INFO" = "Ryans iPhone-13.2.3";
        "X-1SHIFT-MOB-V" = "1.1911.1-105";
        "X-Amzn-Trace-Id" = "Root=1-8d212814-8be8-4d43-8a23-5f5c9d90e23e";
    };
    heartbeatInterval = 60;
    httpRootProperty = location;
    httpTimeout = 60000;
    iOSHasWarnedLocationServicesOff = 0;
    isFirstBoot = 0;
    isMoving = 0;
    lastLocationAuthorizationStatus = 3;
    locationAuthorizationAlert =     {
        cancelButton = Cancel;
        instructions = "To use background location, you must enable '{locationAuthorizationRequest}' in the Location Services settings";
        settingsButton = Settings;
        titleWhenNotEnabled = "Background location is not enabled";
        titleWhenOff = "Location services are off";
    };
    locationAuthorizationRequest = Always;
    locationTemplate = "";
    locationTimeout = 60;
    locationsOrderDirection = ASC;
    logLevel = 5;
    logMaxDays = 3;
    maxBatchSize = "-1";
    maxDaysToPersist = 1;
    maxRecordsToPersist = "-1";
    method = POST;
    minimumActivityRecognitionConfidence = 70;
    odometer = 0;
    params =     {
    };
    pausesLocationUpdatesAutomatically = 0;
    persistMode = 2;
    preventSuspend = 1;
    schedule =     (
    );
    schedulerEnabled = 0;
    startOnBoot = 1;
    stationaryRadius = 25;
    stopAfterElapsedMinutes = "-1";
    stopDetectionDelay = 0;
    stopOnStationary = 0;
    stopOnTerminate = 0;
    stopTimeout = 5;
    trackingMode = 1;
    url = "";
    useSignificantChangesOnly = 0;
}
```

## Expected Behavior
Triggering geofence exit event

## Actual Behavior
`ℹ️-[TSLocationManager locationManager:didExitRegion:] Exit provisional authorization inducer`

## Steps to Reproduce

1. install geofence
2. track in real time
3. enter geofence zone (event is happen)
4. exit geofence zone (event is not triggered)

## Context
Trying to track whole path of user and do some logic when user comes and exits geofence zone

## Debug logs

<details><summary>Logs</summary>
Logs is too long, I put it on [drive](https://drive.google.com/open?id=1BwInqMOLDIupQUVaghcVdhTWC0jp_7Nz)

</details>

**Comment by christocracy** [comment]
Are your geofence radius >= 200 meters?

**Comment by anton-sharpdev** [comment]
It's default value

**Comment by christocracy** [comment]
Set it to 200.

**Comment by anton-sharpdev** [comment]
Sorry for confusing you, geofence points is already using 200 as radius when it’s passing

**Comment by christocracy** [comment]
Are you testing in the iOS simulator?

**Comment by anton-sharpdev** [comment]
Real device, iPhone XS

**Comment by christocracy** [comment]
Test your geofences in the simulator with “Freeway Drive”.

Also try testing the SampleApp in simulator.  In the “Advanced App”, you can add geofences by long-pressing on the map.

**Comment by anton-sharpdev** [comment]
Okay, I’ll try to do that, but honestly I don’t think if it will help. We are using your plugin at least one year and already track a lot of stuff on real devices and sometimes geofencing don’t want to work properly and miss events

**Comment by ShoukriKattan** [comment]
to provide additional information : this behaviour that we are seeing is intermittent, and we are seeing this on live iOS devices. Our observation is that the geofence triggers ok on Android devices but isn’t triggering properly on some iOS devices. Our app and logic around geofence has been the same for the last 3 months and we haven’t implemented any changes there.

**Comment by christocracy** [comment]
I monitor 5 geofences in my neighborhood that I’ve been field-testing almost daily for the last 4 years.  They never fail.

**Comment by christocracy** [comment]
Yesterday's walk:
![](https://dl.dropbox.com/s/syomasqvvmm6mv0/Screenshot%202020-01-10%2009.05.25.png?dl=1)

~ last 5 weeks
![](https://dl.dropboxusercontent.com/s/umgzgyiambh7g6l/Screenshot%202020-01-10%2009.07.59.png?dl=1)

**Comment by christocracy** [comment]
Your logs contain 2 geofences.  I see enter & exit for both.

```
2020-01-09 10:58:03.800 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: ShipmentItem-24132
╚═══════════════════════════════════════════════════════════

2020-01-09 10:58:03.809 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: 55C38B43-5885-4EA4-968C-C7FA8EB7B95A

2020-01-09 10:58:03.810 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2020-01-09 10:58:03.811 ✅-[BackgroundTaskManager createBackgroundTask] 44

2020-01-09 10:58:03.812 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: ShipmentItem-24134
╚═══════════════════════════════════════════════════════════

2020-01-09 10:58:03.815 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: 048C0B86-B14A-4A83-A108-421D81BCF560
```

```
2020-01-09 10:58:03.800 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: ShipmentItem-24132
╚═══════════════════════════════════════════════════════════

2020-01-09 10:58:03.809 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: 55C38B43-5885-4EA4-968C-C7FA8EB7B95A

2020-01-09 10:58:03.810 
╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════

2020-01-09 10:58:03.811 ✅-[BackgroundTaskManager createBackgroundTask] 44

2020-01-09 10:58:03.812 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: ShipmentItem-24134
╚═══════════════════════════════════════════════════════════

2020-01-09 10:58:03.815 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: 048C0B86-B14A-4A83-A108-421D81BCF560
```

**Comment by ShoukriKattan** [comment]
Our log contains 3 geo-fences, please fast forward to 2020-01-09 11:17:02.184 🎾-[TSGeofenceManager locationManager:didEnterRegion:] ShipmentItem-24133  this is the item that has a geo-fence enter but no exit 

Kindly check  between 2020-01-09 11:17:02.184 and 2020-01-09 11:20:04.139 .  This happened to a real user in production version of the app.

**Comment by christocracy** [comment]
What is the lat/lng and radius of `ShipmentItem-24133`

**Comment by ShoukriKattan** [comment]
the Geo-Fence radius for the 3 are the same, 200m. 

2020-01-09 10:57:53.506 ℹ️-[TSLocationManager log:message:] Location::installGeofences [{"identifier":"ShipmentItem-24132","radius":200,"latitude":49.2535183,"longitude":-123.0099238,"notifyOnEntry":true,"notifyOnExit":true,"extras":{"driverId":2138,"itemId":24132,"shipmentId":10493}},{"identifier":"ShipmentItem-24133","radius":200,"latitude":49.2534191,"longitude":-122.9181315,"notifyOnEntry":true,"notifyOnExit":true,"extras":{"driverId":2138,"itemId":24133,"shipmentId":10493}},{"identifier":"ShipmentItem-24134","radius":200,"latitude":49.2535183,"longitude":-123.0099238,"notifyOnEntry":true,"notifyOnExit":true,"extras":{"driverId":2138,"itemId":24134,"shipmentId":10493}}]

**Comment by christocracy** [comment]
Are you trying to detect entry / exit on the Sky Train?

**Comment by ShoukriKattan** [comment]
In this case it was setup for / around "Production Way-University Station"

**Comment by christocracy** [comment]
- Enter geofence `24133` at [this location](https://www.google.com/maps/place/49%C2%B015'10.3%22N+122%C2%B054'55.7%22W/@49.2525069,-122.9176854,17z/data=!4m5!3m4!1s0x0:0x0!8m2!3d49.2528501!4d-122.9154753)
```
2020-01-09 11:17:02.190 🔵-[TSGeofenceManager locationManager:didUpdateLocations:] <+49.25285006,-122.91547531> +/- 8.46m (speed 14.43 mps / course 282.15) @ 2020-01-09, 11:17:02 AM Pacific Standard Time

2020-01-09 11:17:02.191 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: ShipmentItem-24133
╚═══════════════════════════════════════════════════════════
```


- The device stops moving; the stopTimeout timer engages.

2020-01-09 11:19:08.834 🔵-[TSLocationManager beginStopDetection] ⏲Stop-timeout engaged: 300 s...


- A [low accuracy location](https://www.google.com/maps/place/49%C2%B014'42.7%22N+122%C2%B056'05.9%22W/@49.2451918,-122.9437319,15z/data=!4m5!3m4!1s0x0:0x0!8m2!3d49.2451918!4d-122.9349772) arrives (accuracy: 1338 meters).  This causes the current geofence 24133 to exist outside the geofenceProximityRadius and the plugin stops monitoring it.

```
2020-01-09 11:20:04.138 ℹ️-[TSLocationManager locationManager:didUpdateLocations:] IGNORED LOCATION <+49.24519184,-122.93497715> +/- 1338.00m (speed -1.00 mps / course -1.00) @ 2020-01-09, 11:20:04 AM Pacific Standard Time

2020-01-09 11:20:04.139 ℹ️-[GeofenceDAO allWithinRadius:latitude:longitude:limit:]_block_invoke No geofences in proximity of 1000 meters

2020-01-09 11:20:04.139 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager evaluateProximity:] Found 0 / 2 within 1000 m
╚═══════════════════════════════════════════════════════════

2020-01-09 11:20:04.145 🔴-[TSGeofenceManager evaluateProximity:]_block_invoke STOP MONITORING ShipmentItem-24133
```


- About 5 min later, a Better location arrives.  24133 is detected within geofenceProximityRadius and monitoring is once again activated:

```
2020-01-09 11:24:05.918 
📍<+49.25366968,-122.91887996> +/- 12.87m (speed 0.08 mps / course 186.35) @ 2020-01-09, 11:24:05 AM Pacific Standard Time

2020-01-09 11:24:05.918 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 1 | df: 100.0m | age: 0.4s
╚═══════════════════════════════════════════════════════════
2020-01-09 11:24:05.974 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager evaluateProximity:] Found 1 / 2 within 1000 m
╚═══════════════════════════════════════════════════════════

2020-01-09 11:24:05.977 🎾-[TSGeofenceManager startMonitoringGeofence:] ShipmentItem-24133
```

- About 10 seconds later, the Geofence `24133` is enter once again [here](https://www.google.com/maps/place/49%C2%B015'13.4%22N+122%C2%B055'07.8%22W/@49.2537207,-122.9210302,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d49.2537207!4d-122.9188415)

```
2020-01-09 11:24:16.165 🔵-[TSGeofenceManager locationManager:didUpdateLocations:] <+49.25372070,-122.91884146> +/- 8.66m (speed 0.01 mps / course 137.28) @ 2020-01-09, 11:24:16 AM Pacific Standard Time

2020-01-09 11:24:16.166 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: ShipmentItem-24133
╚═══════════════════════════════════════════════════════════

2020-01-09 11:24:16.173 ✅-[TSGeofenceManager fireGeofenceEvent:] INSERT: 9D64AA76-075F-4DA3-AAAF-A6EE58FBAA0E
```

- About 5 min later, the device is detected to be stopped.  The plugin enters the stationary state [here](https://www.google.com/maps/place/49%C2%B015'13.3%22N+122%C2%B055'08.0%22W/@49.2537034,-122.9210844,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d49.2537034!4d-122.9188957)

```
2020-01-09 11:29:17.024 🔵-[TSLocationManager onStopTimeout:] stopTimer fired

2020-01-09 11:29:17.024 🔵-[TSLocationManager setPace:] 0

2020-01-09 11:29:17.093 ✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+49.25370339,-122.91889572> +/- 6.88m (speed 0.06 mps / course 229.02) @ 2020-01-09, 11:29:16 AM Pacific Standard Time

2020-01-09 11:29:17.093 🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 25
```

- About 4 min later, the plugin's motion-detector detects the device is moving:
```
2020-01-09 11:33:12.447 🔵-[TSLocationManager setPace:] 1
```

- Within the same time-frame, as the plugin turns on location-services to start tracking, [the initial location is poor accuracy](https://www.google.com/maps/place/49%C2%B014'28.7%22N+122%C2%B054'50.6%22W/@49.2412921,-122.916242,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d49.2412921!4d-122.9140533) arrives.  The plugin once again determines that geofence `24133` is outside the geofenceProximityRadius and stops monitoring it.
```
2020-01-09 11:33:12.459 ℹ️-[GeofenceDAO allWithinRadius:latitude:longitude:limit:]_block_invoke No geofences in proximity of 1000 meters

2020-01-09 11:33:12.459 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager evaluateProximity:] Found 0 / 2 within 1000 m
╚═══════════════════════════════════════════════════════════

2020-01-09 11:33:12.461 🔴-[TSGeofenceManager evaluateProximity:]_block_invoke STOP MONITORING ShipmentItem-24133

2020-01-09 11:33:12.515 
📍<+49.24129208,-122.91405328> +/- 567.42m (speed -1.00 mps / course -1.00) @ 2020-01-09, 11:33:12 AM Pacific Standard Time
```

- Finally, about 14 seconds later, [a high quality location](https://www.google.com/maps/place/49%C2%B015'15.3%22N+122%C2%B055'44.1%22W/@49.2543413,-122.9273427,17z/data=!4m5!3m4!1s0x0:0x0!8m2!3d49.2542362!4d-122.9289119) arrives and geofence 24133 is once again within geofenceProximityRadius.  However, the device is *already* outside this geofence when it becomes monitored.

```
2020-01-09 11:33:26.595 
📍<+49.25423618,-122.92891193> +/- 16.09m (speed 21.12 mps / course 271.87) @ 2020-01-09, 11:33:26 AM Pacific Standard Time
2020-01-09 11:33:26.618 
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager evaluateProximity:] Found 1 / 2 within 1000 m
╚═══════════════════════════════════════════════════════════

2020-01-09 11:33:26.625 🎾-[TSGeofenceManager startMonitoringGeofence:] ShipmentItem-24133
```

- The device carries on [moving west](https://www.google.com/maps/place/49%C2%B015'15.4%22N+122%C2%B056'06.3%22W/@49.254264,-122.9372655,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d49.254264!4d-122.9350768), away from the geofence 24133.

**Comment by christocracy** [comment]
The distance from geofende `24133` to the poor accuracy location that was used to evaluate geofences, causing `24133` to stop being monitored is ~1.5km, confirming it exists outside the `geofenceProximityRadius` (which defaults to `1000` meters.)

![](https://dl.dropboxusercontent.com/s/ac2f3t7lzaa7aiq/Screenshot%202020-01-10%2010.35.10.png?dl=1)

1.  I will make the plugin take the location accuracy into account when performing its geospatial query to find geofences within proximity-radius (ie:  `geofenceProximityRadius + location.accuracy`).
2.  It's completely safe to increase `geofenceProximityRadius` as desired (eg: `5000`).

**Comment by christocracy** [comment]
The plugin's default `geofenceProximityRadius: 1000` is probably too low.  I think I'll double it to `2000`.

**Comment by christocracy** [comment]
And if you're always monitoring less than 18 geofences at any given time, it wouldn't matter if you make `geofenceProximityRadius` the radius of earth (6371km).

**Comment by ShoukriKattan** [comment]
@christocracy we will wait for the next plugin update and in the meantime I will talk to the team to maybe increase the geo-fence radius.  

We appreciate your responsiveness.

**Comment by christocracy** [comment]
If all this stuff about "geofence proximity radius" is new to you, read the [Geofencing Guide](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.geofence.html) in API docs.  See the section *Infinite Geofencing*.

It's completely safe to use `geofenceProximityRadius: 5000`.  It's very clear to me it would have prevented the issue above.

**Comment by ShoukriKattan** [comment]
@christocracy thanks so yes, we will configure geofenceProximityRadius to a high number (5000) , and I will talk to the team to see if we can increase also geofence radius.. I think combined this should cover our use case. 

Thanks again

**Comment by ShoukriKattan** [comment]
Just found another interesting case: in this case the geo-fence got triggered pre-maturely because 1GPS fix was inaccurate, this relates back to your point that if you take location.accuracy into consideration when doing the geo-fence calculation, we won't have the geo-fence trigger prematurely. 

The excel attached shows the entire trip, see data item 

b8e812c6-ca9a-4392-8bfb-ffd4b1617787
--

In this case, a less accurate GPS fix triggered geo-fence prematurely 

Phone logs + XLS of entire trip attached. hope this helps refine geo-fencing 


[background-geolocation (4).log](https://github.com/transistorsoft/react-native-background-geolocation/files/4047738/background-geolocation.4.log)

[gps locaiton.xlsx](https://github.com/transistorsoft/react-native-background-geolocation/files/4047741/gps.locaiton.xlsx)
