### ISSUE TITLE
Android doesn't send all locations

### ISSUE THREAD

**Issue by armin23615** [transistorsoft/react-native-background-geolocation#952]
## Your Environment
* Plugin version: ^3.3.2
* Platform: Android
* OS version: 9
* Device manufacturer / model: Huawei P10
* React Native version (`react-native -v`): 0.60
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
    {
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      disableElasticity: true,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, 
      startOnBoot: true, 
      url: 'my_url',
      batchSync: true, 
      autoSync: true,
      headers: {
        // <-- Optional HTTP headers
      },
      extras: {
        trip_id: tripId,
      },
      notificationsEnabled: false,
    },
    (state) => {
      console.log('- BackgroundGeolocation is configured and ready: ', state.enabled)

      if (!state.enabled) {
        // Start tracking
        BackgroundGeolocation.start(function() {
          console.log('- Start success')
        })
      }
    }
  )
```

## Expected Behavior

Sending locations while driving from one point to another.
It works on iOS: 
![iOS](https://user-images.githubusercontent.com/56969846/72220123-cdd0f980-354d-11ea-8b83-7b4aaa5f5496.jpg)

## Actual Behavior

Android didn't send location of few last miles but it sent the last one when i opened the app at the final destination.
![ANDROID](https://user-images.githubusercontent.com/56969846/72220128-d45f7100-354d-11ea-93fb-d63591cae51a.png)

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Huawei devices are the most problematic.  See http://dontkillmyapp.com

**Comment by armin23615** [comment]
Is there any resolution or workaround for this? 
What do you suggest?

**Comment by christocracy** [comment]
Did you read this?  https://dontkillmyapp.com?

**Comment by swapanil** [comment]
Working fine in ios.

Locations are not updating in android as expected.

Particularly, when I kill the app.

It shows toast like license validation failure

However, I am using debug apk and according to the document license key is not required in debug mode.

https://github.com/transistorsoft/react-native-background-geolocation/blob/HEAD/help/INSTALL-ANDROID-AUTO.md

React-Native version: 0.61.5
OS: macOS Mojave 10.14.6
Android Studio: 3.5 AI-191.8026.42.35.5977832
Device: Smasung j6

**Comment by arun-singh-bisht** [comment]
This plugin is working(giving location update) if GPS is turned ON. IF User switch off the GPS from device setting , app stops giving location update. 
Even with  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM, it doesn't post location update.

**Comment by christocracy** [comment]
There's no way to "switch of GPS".  You can only *turn off location-services*.  When the user turns off *location-services*, that device cannot receive a location **at all**.

- Location-services !- GPS.
- Location-services = GPS + Wifi location + Cellular location
