### ISSUE TITLE
Accessing geofence extras in geofenceTemplate

### ISSUE THREAD

**Issue by tousdan** [transistorsoft/react-native-background-geolocation#954]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: Any
* Device manufacturer / model: Emulator
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript 
geofenceTemplate: '{ "operationName": "ADD_STORE_PRESENCE", "variables": { "occurredAt": "<%= timestamp %>", "storeId": "<%= geofence.identifier %>" }, "query": "mutation ADD_STORE_PRESENCE($storeId: ID!, $occurredAt: DateTime!) { addStorePresence(storeId: $storeId, occurredAt: $occurredAt) { id }}" }'
```

## Expected Behavior
I'm interfacing with a graphql query so to be able to adhere to it's format, I'm rewriting the whole object

My geofences have the following extras:
```json
 extras: {
            entreprise: {
              id: store.entreprise.id,
              name: store.entreprise.name,
            },
            storeId: store.id,
          }
```

and i'd like to extract the storeId field of that in the template.

I have tried; geofence.storeId, geofence.extras.storeId, extras.storeId, storeId and they all ended up generating a template error.

I understand the documentation merges the global, configuration level extras in this object so it is available to the template, but I need the geofence extras.

## Actual Behavior
Unable to access the geofence extras field from the template.

Also, oddly enough, as I inspect the request on the server, I notice that all the extra fields of my geofence are appended to the object that the geofenceTemplate has generated.

## Questions
Is there a better strategy that I could use to generate the request here?

Great work overall on the plugin and keep it up

**Comment by christocracy** [comment]
There is no ability to evaluate variables defined in `extras` into the `geofenceTemplate`.  The plugin's templating-system is *very* limited.

**Comment by tousdan** [comment]
Alright, this wouldn't be a problem if I didn't have to deal with the constraints of the graphql api. I'll use the identifier.

Are the extras of the geofence being appended as attributes to the result of the geofenceTemplate by design and is this something I can disable?

Thanks for the quick answer

**Comment by christocracy** [comment]
>and is this something I can disable?

No.

**Comment by christocracy** [comment]
It's probably simpler to provide a proxy /endpoint on the server to accept the plugin's default template and re-format the schema for graphql and forward that to your existing /endpoint.
