### ISSUE TITLE
Question: background track & removeListeners

### ISSUE THREAD

**Issue by netojose** [transistorsoft/react-native-background-geolocation#956]
I  want to track the user location while the application is closed. But in all demos, you recommend removing listeners using the code below:
```js
componentWillUnmount() {
    BackgroundGeolocation.removeListeners();
}
```
This code above will stop tracking when the app is closed? To keep tracking, should I don't use the code above?

**Comment by christocracy** [comment]
No matter what, your JavaScript app is terminated when the app is terminated.  

See api docs Config.stopOnTerminate.

**Comment by christocracy** [comment]
removeListeners does not stop tracking.  Only calling #stop method stops tracking.

**Comment by netojose** [comment]
@christocracy , thanks for the quick feedback!
