### ISSUE TITLE
Plugin does not retry/recover after voice call interruption

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#957]
## Your Environment

* Plugin version: react-native-background-geolocation-android#992e3d53
* Platform: iOS
* OS version: iOS 13
* Device manufacturer / model: iPhone 7 Plus (CDMA)
* React Native version (`react-native -v`): 0.61.5
* Plugin config: To be emailed
* Debug logs: To be emailed

## Description

One of our testers is on a cellular network which does not (cannot?) handle voice calls and data simultaneously. Whenever a voice call starts, the internet/data connection is dropped/disabled. After the voice call finishes, then the data connection is re-established.

I think this is some sort of CDMA limitation as the cellular network is CDMA based, or something like that. Apparently there are a few networks in the US which are still like this.

As an overview, we observed something like this happen (A more detailed break-down is further below):

0. User is moving. Data points are being uploaded. All is fine.
1. User starts a voice call.
2. Cellular network drops/disables the data connection. Plugin continues to acquire location data points (and stores them offline).
3. User stops moving.
4. User stops voice call.

When the data connection comes back up again ...

## Expected Behavior

Expected result: RNBGL should upload data points that it acquired whilst offline. This should happen automatically without user intervention.

## Actual Behavior

Observed result: RNBGL does not upload offline data points until the user re-opens the app.

## Steps to Reproduce

See above, but it must take place on a cellular network that does not handle simultaneous voice and data.

## Details

I will send you a debug log via email.

I will post log details and discussion in a separate comment below.

## Debug logs

Will send via email

**Comment by bengtan** [comment]
## Overview

According to our server logs, the following data points were posted:

9B396126-5904-4119-9B10-40800DE85CFA recorded at 2020-01-16T20:38:15.994Z
F7A51158-1EE2-4959-B9E1-A2EB118FA987 recorded at 2020-01-16T20:42:48.99Z
19 or 20 data points in between
34546E07-8CFA-42B5-81F9-F9BAB1CA57DC recorded at 2020-01-16T21:43:05.905Z

9B396126 was the data point before connectivity broke/was interrupted by a voice call. Then there was a gap of about 1 hour before the plugin resume uploading. 

Then data point 34546E07 was uploaded, along with the 20 data points prior to that which were stored offline. The earliest 'offline' data point is F7A51158.

The resumption of uploading coincided with either the app being restarted, or the phone being unlocked.

The voice call lasted for 18 minutes.

The log is in timezone GMT-6.

## Notable events

Data point 9B396126 is acquired:

L2113:2020-01-16 14:38:16.124 `✅-[TSLocationManager persistLocation:]_block_invoke INSERT: 9B396126-5904-4119-9B10-40800DE85CFA`

and uploaded:

L2144:2020-01-16 14:38:17.411 `✅-[LocationDAO destroyAll:] DESTROY: 9B396126-5904-4119-9B10-40800DE85CFA`

with HTTP success:

L2159:2020-01-16 14:38:17.433 `ℹ️-[TSLocationManager log:message:] BGGL onHttp success: {"success":true,"status":201,"responseText":"{\"watchers\":0,\"watched\":false,\"changed_at\":null}"}`

Connectivity breaks:

L2886:2020-01-16 14:39:33.638 `🔵-[TSHttpService init]_block_invoke Network: No Connection | Flags: -- `

L2888:2020-01-16 14:39:33.642:
```
⚠️-[HttpResponse handleResponse] HTTP ERROR: 0
***
* A data connection cannot be established since a call is currently active.
*
{
    NSErrorFailingURLKey = "<redacted>";
    NSErrorFailingURLStringKey = "<redacted>";
    NSLocalizedDescription = "A data connection cannot be established since a call is currently active.";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1019 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}";
    "_kCFStreamErrorCodeKey" = 50;
    "_kCFStreamErrorDomainKey" = 1;
}
```

At around 2020-01-16 14:57, the call would have finished. However, the plugin only resumes uploading much later:

L5616:2020-01-16 15:43:05.753 `🔵-[TSHttpService init]_block_invoke Network: Cellular | Flags: WR -t-----`

L5746:2020-01-16 15:43:07.349 `✅-[LocationDAO destroyAll:] DESTROY: F7A51158-1EE2-4959-B9E1-A2EB118FA987`

L5784:2020-01-16 15:43:07.349 `✅-[LocationDAO destroyAll:] DESTROY: 34546E07-8CFA-42B5-81F9-F9BAB1CA57DC`

L5792:2020-01-16 `15:43:07.364 ℹ️-[TSLocationManager log:message:] BGGL onHttp success: {"success":true,"status":201,"responseText":"{\"watchers\":0,\"watched\":false,\"changed_at\":null}"}`

There's also a gap of 57 minutes around line 5616:

```
2020-01-16 14:46:50.132 
╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager createMotionTypeChangedHandler]_block_invoke | still/33 | isMoving: 0
╚═══════════════════════════════════════════════════════════

2020-01-16 15:43:05.753 🔵-[TSHttpService init]_block_invoke Network: Cellular | Flags: WR -t-----
```

where the log is silent. I imply this to mean that the plugin is in a stationary state?

## Discussion

Please let me know what you think. I may have mis-guessed some parts of the debug log.

**Comment by christocracy** [comment]
Once the plugin enters the stationary state in the background, iOS will suspend that app.  There will be no code running at all and network connect events will not be posted to your app.  

However, if a background-fetch event occurs, the plugin initiate the HTTP service.  Other than that, there’s no possible way the plugin can do anything.  The os has suspended the app.

If the user terminates the call while the device is still *moving*, there will be no issue.

**Comment by bengtan** [comment]
Okay, thanks for the explanation.
