### ISSUE TITLE
stopOnTerminate POST on IOS and Android

### ISSUE THREAD

**Issue by smalbois-panoptio** [transistorsoft/react-native-background-geolocation#958]
## Your Environment
* Plugin version:
* Platform: iOS and Android
* OS version: 13
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const BGLocationConfig = {
  locationAuthorizationRequest: 'Always',
  locationAuthorizationAlert: {
    titleWhenNotEnabled: 'Location-services not enabled',
    titleWhenOff: 'Location-services OFF',
    instructions: 'You must set location-services to "Always" for pipio to determine your event eligibility.',
    cancelButton: 'Cancel',
    settingsButton: 'Settings'
  },
  desiredAccuracy: 0,
  distanceFilter: 0,
  heartbeatInterval: 60,
  // Activity Recognition
  stopTimeout: 1,
  activityRecognitionInterval: 0,
  // Application config
  debug: Config.debug,
  logLevel: (Config.debug ? BackgroundGeolocation.LOG_LEVEL_VERBOSE : BackgroundGeolocation.LOG_LEVEL_ERROR),
  enableHeadless: true,
  reset: true,
  stopOnTerminate: false,
  startOnBoot: true,
  // HTTP / SQLite config
  url: Config.url.post.activity,
  httpTimeout: 30000,
  geofenceModeHighAccuracy: true,
  method: 'POST',
  batchSync: false,
  autoSync: true,
  maxDaysToPersist: 1,
  autoSyncThreshold: 0,
  httpRootProperty: '.',
  geofenceProximityRadius: 20000,
  locationTemplate: `{"ts":"<%= timestamp %>","fence_id":0,"action":"ENTER","t":"<%= activity.type %>","c":"<%= activity.confidence %>","speed":<%= speed %>,"latitude":<%= latitude %>,"longitude":<%= longitude %>}`,
  geofenceTemplate: `{"ts":"<%= timestamp %>","fence_id":<%= geofence.identifier %>,"action":"<%= geofence.action %>","t":"<%= activity.type %>","c":"<%= activity.confidence %>","speed":<%= speed %>,"latitude":<%= latitude %>,"longitude":<%= longitude %>}`,
  headers: {              // <-- Optional HTTP headers
    'x-api-key': Config.API_KEY,
  },
  params: {               // <-- Optional HTTP params
    user_id: Config.userId,
    device_id: Config.deviceId
  }
};

```

## Steps to Reproduce

1.
2.
3.
4.

## Context
I am currently using the plugin to fetch a list of fences I want to track and post ENTER etc back to my server upon entering these fences. This works really well when the app is in the foreground or background on IOS and Android.

However I am trying to make this work on IOS and Android when the app is terminated. I looked into stopOnTerminate and headless mode for Android only. I can see that Android and IOS are likely to behave differently here.

Could you please let me know the answer to the following?

1. Will stopOnTerminate on IOS and Android POST my tracked events to my server when location is set to Always **when the app is closed/terminated**? 

2. Would I have a way to fetch these fences I wanted to retrieve onLocation or onMotion change when the app is terminated to IOS **and** Android?

Thank you!

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by smalbois-panoptio** [comment]
@christocracy sorry to flag this here. Would you be able to help please sir? I know you are the master here. Thank you.

**Comment by christocracy** [comment]
Customers should post issues to private repo.

>Will stopOnTerminate on IOS and Android POST my tracked events to my server when location is set to Always when the app is closed/terminated?

Yes.  What else would `stopOnTerminate: false` mean?

>Would I have a way to fetch these fences I wanted to retrieve onLocation or onMotion change when the app is terminated to IOS and Android?

The plugin is able to monitor any number of geofences, thousands if you want.  What you should *not* do is start monitoring the *same* set of geofences each time your app is launched.  You should avoid re-adding a geofence which is already being monitored.

Also, perhaps you're interested in the plugin's new "RPC" feature.  Search the [HTTP Guide](https://transistorsoft.github.io/cordova-background-geolocation/interfaces/_cordova_background_geolocation_.httpevent.html) for the text "RPC".

![](https://dl.dropboxusercontent.com/s/kf73a2quyzofbpi/Screenshot%202020-01-21%2012.20.03.png?dl=1)
