### ISSUE TITLE
Location service activated no icon

### ISSUE THREAD

**Issue by Wertuoz** [transistorsoft/react-native-background-geolocation#959]
## Your Environment
* Plugin version: react-native-background-geolocation@^3.4.2:
* Platform: Android
* any version 8+:
* Device manufacturer / model: any device and emulator
* React Native version (`react-native -v`): "react-native": "0.61.5",
* Plugin config: To be emailed

## Expected Behavior

There is icon that i configured

## Actual Behavior

There is no icon in notification tray, only default gray circle

## Steps to Reproduce

1.Start app
2.Init location service
3.Watch into notification tray

## Context

Shared image of this issue: [http://snpy.in/qDyEve](http://snpy.in/qDyEve)
I dont't know, how to fix this, i configured my notification style in config:
`public static default: ISettings = {
    locationConfig: {
      reset: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      stopOnTerminate: false,
      startOnBoot: true,
      elasticityMultiplier: 0.1,
      preventSuspend: true,
      debug: false,
      logLevel: 5,
      foregroundService: true,
      enableHeadless: true,
      geofenceInitialTriggerEntry: true,
      geofenceProximityRadius: 5000,
      notification: {
        smallIcon: 'drawable/ic_stat_1sl_logo_trans',
        largeIcon: 'drawable/ic_stat_1sl_logo_trans',
        color: '#f1911f',
        priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
      },
    },
    geofenceConfig: {},
    picturesConfig: {
      pod: {
        takePictureConfig: {
          quality: 0.75,
        },
      },
      exception: {
        takePictureConfig: {
          quality: 0.75,
        },
      },
    },
  };`

**Comment by christocracy** [comment]
That *is* your icon.  You need to regenerate it with transparency.

**Comment by Wertuoz** [comment]
Could you expand your answer, i don't understand what you mean.
I'm adding my icon here
![ic_stat_1sl_logo_trans](https://user-images.githubusercontent.com/1164355/72794563-440be500-3c4d-11ea-9457-70ec0a437820.png)

**Comment by christocracy** [comment]
Later versions of Android automatically monochrome your logo icon.  Where there is color becomes *white*; where there is transparency is made black.
