### ISSUE TITLE
[Question] Is there a way to prevent autosync of locations when changing states?

### ISSUE THREAD

**Issue by Eralyne** [transistorsoft/react-native-background-geolocation#960]
## Your Environment
* Plugin version: 3.3.2
* Platform: Both
* OS version: 10+
* Device manufacturer / model: All Devices
* React Native version (`react-native -v`): 0.60.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
          // Geolocation Config
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 25, // Distance required for an update event to be registered in meters
          elasticityMultiplier: 2,
          // Activity Recognition
          stopTimeout: 3, // Amount of time to wait in minutes while stationary before turning off location services
          // Application config
          debug: false, // See notifications for background-geolocation life-cycle.
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          stopOnTerminate: false, // Allow the background-service to continue tracking when user closes the app.
          startOnBoot: true, // Auto start tracking when device is powered-up.
          // Heartbeat config
          preventSuspend: true,
          heartbeatInterval: 60,
          foregroundService: true,
          enableHeadless: true,
          // HTTP Config
          url: '', // server url is here
          autoSync: true,
          autoSyncThreshold: 10,
          batchSync: true,
          httpTimeout: 60002,
          maxDaysToPersist: 1,
          // Extras
        }
```

## Expected Behavior

Locations don't sync on transition between moving to stationary.
## Actual Behavior

Locations in SQLite database are synced on transition between moving to stationary.
## Steps to Reproduce

1.
2.
3.
4.

## Context

I am attempting to manually insert locations into the database on stop and manually sync them, however, it causes a race condition as the sqlite locations start syncing on state change.
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Why would you want this?

**Comment by Eralyne** [comment]
I want to influence the points that get sent to my server on a stationary event. I need locations constantly sent in so manual sync at all times seems unproductive, it's only on a stationary transition that I want to change what is put in.

**Comment by christocracy** [comment]
What do you mean “change what is put in”?

**Comment by Eralyne** [comment]
I'm sorry, I'm just looking to know if something like this currently exists. I'm not trying to request something new.

**Comment by christocracy** [comment]
No, that feature has never been requested.
