### ISSUE TITLE
Battery saver still disabled in settings after showIgnoreBatteryOptimizations

### ISSUE THREAD

**Issue by Kranysys** [transistorsoft/react-native-background-geolocation#961]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 9.0
* Device manufacturer / model: Xiaomi Note 7
* React Native version (`react-native -v`): 0.60.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  reset: true,
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  disableElasticity: true,
  distanceFilter: 0,
  locationUpdateInterval: 1000,
  stopTimeout: 1,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  stopOnTerminate: true,
  startOnBoot: true,
  autoSync: true,
  batchSync: false,
  autoSyncThreshold: 0,
  foregroundService: true,
  url: SERVER_URL,
  allowIdenticalLocations: true,
  params: {
    device: {
      uuid: (DeviceInfo.getModel() + '-' + DeviceInfo.getSystemVersion()).replace(/[\s\.,]/g, '-'),
      model: DeviceInfo.getModel(),
      platform: DeviceInfo.getSystemName(),
      manufacturer: DeviceInfo.getManufacturer(),
      version: DeviceInfo.getSystemVersion(),
      framework: 'ReactNative',
    },
  },
```

## Expected Behavior

If we disable battery optmization, after showing `showIgnoreBatteryOptimizations()`, and `isIgnoring` became true, and we go back in the android settings (through "app"), we should still see that the battery saver is disabled.

## Actual Behavior

When we disable the battery optimization in the settings, after showing  `showIgnoreBatteryOptimizations()`, and `isIgnoring` became true, if we go in the android settings (through "app"), we still see that the battery saver is enabled.

## Steps to Reproduce

1. `showIgnoreBatteryOptimizations()` with `BackgroundGeolocation.deviceSettings.show(request);`
2. Going to the battery optimization settings page
3. Disabling battery optimization on the app
4. Going in the android settings (through "app"), we still see that the battery saver is enabled.

## Context

Disabling battery optimization in the Android settings

**Comment by christocracy** [comment]
The plugin isn't involved with changing any actual settings.  It only provides the ability to re-direct the user to that screen.
