### ISSUE TITLE
On Android stopAfterElapsedMinutes does not work if motion is still

### ISSUE THREAD

**Issue by mieszko4** [transistorsoft/react-native-background-geolocation#962]
I trigger location tracking for 1min (the deadline) by clicking on the button that runs `start` with `stopAfterElapsedMinutes` option.
However, after deadline passes, the `State.enabled`:
1. correctly changes to `false` If Location Service was turned on during the deadline
2. **does not change to `true` if Location Service was turned off (device was not in motion) during the deadline**
3. it still stays `true` if Location Service is on after the deadline and stays `true` forever even after reopening the app

## Your Environment
* Plugin version: 3.3.2
* Platform: Android
* OS version: 9
* Device manufacturer / model: emulator
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
          // Geolocation Config
          desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
          distanceFilter: 1,
          // Activity Recognition
          stopTimeout: 1,
          // Application config
          stopOnTerminate: false,
          foregroundService: true,
          enableHeadless: true,
          startOnBoot: true,
          // HTTP / SQLite config
          url: graphqlEndpoint,
          httpRootProperty: 'variables',
          params: {
            query: rawSendLocationQuery,
          },
          locationTemplate: '{ "location_coordinates": [<%= latitude %>, <%= longitude %>], "battery_level": <%= battery.level %> }',
          batchSync: false,
          autoSync: true,
}).then(state => console.log('STATE', state.enabled));

const HeadlessTask = async (event) => {
    const { params } = event;
    console.log('[BackgroundGeolocation HeadlessTask] -', event.name, params);

    if (event.name === 'heartbeat') {
      const location = await BackgroundGeolocation.getCurrentPosition({
        samples: 1,
        persist: false,
      });
      console.log('[BackgroundGeolocation HeadlessTask] - getCurrentPosition:', location);
    }
  };

BackgroundGeolocation.registerHeadlessTask(HeadlessTask);

const onClick = async () => {
  await BackgroundGeolocation.stop();
  await BackgroundGeolocation.setConfig({
    headers: {
      Authorization: 'MobileToken test-mobile_token',
    },
    stopAfterElapsedMinutes: 1,
  });

  await BackgroundGeolocation.start();
}
```

## Expected Behavior

After running `onClick` and waiting for 1 minute `State.enabled` should be `false`
## Actual Behavior

After running `onClick` and waiting for 1 minute `State.enabled` is still `true` if at that moment Location Services was off

## Steps to Reproduce

1. Open the app, make sure device is still
2. Click on Button to trigger `onClick`
3. Wait for 1 minute
4. Reopen the app - `State.enabled` is still `true`

## Context

I am trying to track location only for 1 minute.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
--------- beginning of system
--------- beginning of crash
--------- beginning of main
01-24 22:47:48.684 14655 14710 I TSLocationManager: - Enable: false → true, trackingMode: 1
01-24 22:51:05.156 14921 14980 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 22:52:08.448 15083 15138 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 22:52:33.885 15231 15288 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 22:58:21.209 15662 15698 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 22:59:50.839 16312 16368 I TSLocationManager: - Enable: false → true, trackingMode: 1
01-24 23:00:11.653 16472 16531 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:03:33.698 16771 16828 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:04:21.221 16941 16996 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:05:48.415 17115 17173 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:10:35.317 17410 17469 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:28:05.409 19596 19652 I TSLocationManager: - Enable: false → true, trackingMode: 1
01-24 23:29:01.065 19820 19876 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:32:39.926 20155 20211 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:38:27.009 20427 20483 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:38:54.934 20427 20483 I TSLocationManager: - Enable: false → true, trackingMode: 1
01-24 23:40:08.088 20614 20670 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-24 23:44:04.249 20614 20996 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-25 00:07:30.405 22454 22510 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-25 00:46:33.440 23839 23897 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-25 00:47:48.333 24113 24170 I TSLocationManager: - Enable: false → true, trackingMode: 1
01-25 00:49:19.832 24295 24351 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-25 00:49:59.119 24454 24511 I TSLocationManager: - Enable: true → true, trackingMode: 1
01-25 00:50:59.448 24627 24682 I TSLocationManager: - Enable: false → true, trackingMode: 1
01-25 00:52:16.572 24826 24883 I TSLocationManager: - Enable: true → true, trackingMode: 1

```

</details>

**Comment by christocracy** [comment]
This mechanism only engages *after* the the device enters the *moving* state.

**Comment by christocracy** [comment]
Execute changePace(true) and it will engage.  Or simply go for a walk.

**Comment by mieszko4** [comment]
Thanx for the answer.

I can execute ` changePace(true)` and it works as expected if I trigger it just before the deadline.
For example, I can execute it right after `read()` because I use `stopTimeout: 1 (min)` with  `stopAfterElapsedMinutes: 1 (min)` for the configuration.

However, this will not work in my case. I used 1 min to show the problem.

My real scenario is that I put `stopAfterElapsedMinutes: 90 (min)`.
I want to track my user for 90min starting from the time she accepts being tracked until the time she comes to the destination (to a teaching class).
I promise the user to only track her during that period and not after.

In details what happens is:
1. the user comes to the class after 80min (early)
2. puts the device aside and device becomes `still`
3. `stopTimeout: 1 (min)` passes which turns off Location Services
4. then another 9 min passes with device being `still`, i.e. the deadline of (`stopAfterElapsedMinutes: 90 (min)`) passes **but** `State.enabled` **is not** swtiched to  `false`
5. After the end of the class, i.e. after another 60min (150min after triggering `start`) user goes for a walk and the device is in `moving` state
6. But now the _sticky_ notification shows on her device that she is being tracked by my app because `State.enabled` is still `true`. (locations _are not_ sent to my server at this point which is expected for me)

This is a confusing behavior of `stopAfterElapsedMinutes` for which stopping which works during `movement` but does not work when mobile is `still`.

**Comment by christocracy** [comment]
I suggest you use your own application logic then.  It’s really quite a simple problem to solve in one’s own app code.

**Comment by mieszko4** [comment]
I am sorry, but I am confused with your answer.

The docs for `stopAfterElapsedMinutes` (https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html) says:

> Automatically stop tracking after x minutes.
> The plugin can optionally automatically stop after some number of minutes elapses after the start method was called.

It does not say anywhere that this _will not work_ for specific case, i.e. when mobile is `still`.

For me `stopAfterElapsedMinutes` is buggy and if it is simple to solve I do not understand why it would not be solved in `react-native-background-geolocation` package itself.
If it is not possible to solve in the package itself I believe that there should be at least a note about this problem in the docs, so the person who uses it knows what to expect.

**Comment by christocracy** [comment]
This feature was specifically designed for an existing customer with specific requirements.

The docs will be updated to reflect that.

Your use-case can easily be handled with your own application logic.

**Comment by mieszko4** [comment]
Great, thnx for the explanation!

Would you mind give me a tip how to do it with my own application logic?
You mean something like to check and stop it on heartbeat events?
