### ISSUE TITLE
Could not find auto-linked framework 'TSBackgroundFetch' Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_TSBackgroundFetch"

### ISSUE THREAD

**Issue by akash-wadhwa** [transistorsoft/react-native-background-geolocation#966]
## Your Environment
* Plugin version: 3.4.2
* Platform: iOS or Android: iOS
* OS version: 12.4
* Device manufacturer / model: iPhoneX
* React Native version :0.61.5
* Plugin config

## Expected Behavior
Project should compile

## Actual Behavior
On build below error is thrown:
Could not find auto-linked framework 'TSBackgroundFetch'
Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$_TSBackgroundFetch", referenced from:
objc-class-ref in TSLocationManager(TSLocationManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Steps to Reproduce

1. pod install
2. try to build
3. error thrown

## Context

Trying to build the project

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
```
yarn add react-native-background-fetch
pod install
```

**Comment by christocracy** [comment]
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md

**Comment by akash-wadhwa** [comment]
Awesome, It worked. Thanks for quick reply.

**Comment by haiderTkxel** [comment]
@christocracy I got this type of error after removing the react-native-background-fetch

**Comment by christocracy** [comment]
> got this type of error after removing the react-native-background-fetch

Why would you do that?

**Comment by haiderTkxel** [comment]
> > got this type of error after removing the react-native-background-fetch
> 
> Why would you do that?

because I don't use it but react-native-background-geolocation is in packge.json

**Comment by christocracy** [comment]
background-fetch is a required dependency of  background-geolocation.

when you remove a dependency, bad things happen.

**Comment by Keerthirathinam** [comment]
<img width="396" alt="image" src="https://github.com/user-attachments/assets/f8b54d87-8ea8-4afe-be83-2f95f13de62e" />


I installed background fetch cleaned the build file and installed pod and still issue exists
