### ISSUE TITLE
gelocation popup even after we remove library code.

### ISSUE THREAD

**Issue by littlehome-eugene** [transistorsoft/react-native-background-geolocation#970]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

    // we commented out this

    // BackgroundGeolocation.ready(config, (state:State) => {
    //   if (state.schedule && state.schedule.length > 0) {
    //     BackgroundGeolocation.startSchedule();
    //   }
    //   this.setState({
    //     enabled: state.enabled,
    //     isMoving: state.isMoving,
    //     followsUserLocation: state.enabled,
    //     showsUserLocation: state.enabled,
    //     bgGeo: state
    //   });
    // }, (error:string) => {
    // });

 // we also commented out headlesstask
  //  BackgroundFetch.registerHeadlessTask(BackgroundFetchHeadlessTask);
```

## Expected Behavior

No more `Location Service activated` notification after removing library
## Actual Behavior

Users still get the notification after we remove the libary 

![69520143-28fb5c80-0f9f-11ea-8a83-23400a1be5a6](https://user-images.githubusercontent.com/24217396/73730081-91be3c80-4779-11ea-94e1-613fadd56c27.jpg)

## Steps to Reproduce

1.
2.
3.
4.

## Context

We had to remove the library because of the high crash rate, but then users reported they keep seeing the `Location Service activated` 

We checked their app version and it was the version where we removed the above lines. 

How do we stop showing the notification and not using the library at the same time? 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You can't "disable" the plugin by merely commenting out the Javascript code.  You need to tell the plugin to `BackgroundGeolocation.stop()` *before* you comment-out the code.  The plugin operates independently of your Javascript and keeps track of its state between reboots.  Once the plugin is enabled (via `BackgroundGeolocation.start()`), it will be enabled *forever* until you `BackgroundGeolocation.stop()`.

**Comment by christocracy** [comment]
```
// we also commented out headlesstask
  //  BackgroundFetch.registerHeadlessTask(BackgroundFetchHeadlessTask);
```
This is **not** where you are supposed to `#registerHeadlessTask`.  You are supposed to do this in your root `index.js` file, **NOT** in your application components.

**Comment by christocracy** [comment]
In the [same place](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode#step-2--backgroundgeolocationregisterheadlesstask) where React Native's `AppRegistry.registerComponent` is where you `#registerHeadlessTask`

**Comment by christocracy** [comment]
If you don't understand how to use *Android Headless Mode*, don't use it.

**Comment by littlehome-eugene** [comment]
@christocracy 

We had `registerHeadlessTask` in our index.js. 

I want the functionality of google map where it knows where I go and prompt me to review the places or list them for me to review 

Although I only need to do this for several thousands places instead of every place like google do.


To do this,  I'm using `onGeofence` + headless because I need to know where they go even when app is closed.


Google map does this without showing `location activated` popups, am I able to achieve the same functionality using this library? Am I misusing it? or google is having a unfair advantage in `not notifying the users` ?
