### ISSUE TITLE
Documentation query: Server initiated commands

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#971]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by bengtan** [comment]
Sorry, messed this up. Closing and will post a new ticket.

**Comment by christocracy** [comment]
Why not just *edit*?

**Comment by christocracy** [comment]
![](https://dl.dropboxusercontent.com/s/bzgp3x7p7ewihaw/Screenshot%202020-02-04%2022.16.26.png?dl=1)
