### ISSUE TITLE
Documentation query: Server initiated commands

### ISSUE THREAD

**Issue by bengtan** [transistorsoft/react-native-background-geolocation#972]
Hi,

There was an email I received a few months ago from a react-native-background-geolocation mailing list or something ... about a new feature which allowed the server to send 'commands' to the plugin. (I can't find that email anymore)

I'm trying to find out more information/documentatio about this feature.

Any ideas?

**Comment by christocracy** [comment]
It's available in the *private* version docs' [Http Guide](https://transistorsoft.github.io/react-native-background-geolocation-android/interfaces/_react_native_background_geolocation_android_.httpevent.html) and this documented API only exists in the *private version*.

If you're installing the plugin from npm `react-native-background-geolocation`, you should be loading from the private repo instead for latest updates.
