### ISSUE TITLE
Getting exception in iOS when doing BackgroundGeolocation.start

### ISSUE THREAD

**Issue by mailyokesh** [transistorsoft/react-native-background-geolocation#975]
## Your Environment
* Plugin version: 
"react-native-background-fetch": "^2.8.0",
  "react-native-background-geolocation": "^3.4.2",
* Platform: iOS 
* OS version: Latest Simulator or IOS 13.3
* Device manufacturer / model: iphoneXS
* React Native version (`react-native -v`):
react-native-cli: 2.0.1
react-native: 0.61.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
This is being called from componentWillMount
setupLocationService() {
        // This handler fires whenever bgGeo receives a location update.
        BackgroundGeolocation.onLocation(this.onLocation, this.onError);

        // This handler fires when movement states changes (stationary->moving; moving->stationary)
        BackgroundGeolocation.onMotionChange(this.onMotionChange);

        // This event fires when a change in motion activity is detected
        BackgroundGeolocation.onActivityChange(this.onActivityChange);

        // This event fires when the user toggles location-services authorization
        BackgroundGeolocation.onProviderChange(this.onProviderChange);

        ////
        // 2.  Execute #ready method (required)
        //
        BackgroundGeolocation.ready(
            {
                // Geolocation Config
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 10,
                // Activity Recognition
                stopTimeout: 1,
                // Application config
                debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
                logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
                stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
                startOnBoot: true, // <-- Auto start tracking when device is powered-up.
                // HTTP / SQLite config
                url: "http://yourserver.com/locations",
                batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
                autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
                headers: {
                    // <-- Optional HTTP headers
                    "X-FOO": "bar"
                },
                params: {
                    // <-- Optional HTTP params
                    auth_token: "maybe_your_server_authenticates_via_token_YES?"
                }
            },
            state => {
                console.log(
                    "- BackgroundGeolocation is configured and ready: ",
                    state.enabled
                );

                if (!state.enabled) {
                    ////
                    // 3. Start tracking!
                    //
                    BackgroundGeolocation.start(function() {
                        console.log("- Start success");
                    });
                }
            }
        );
    }
```

## Expected Behavior
No Crash

## Actual Behavior
Getting crash when the BackgroundGeolocation.start is called

## Steps to Reproduce

1. Do the exact same steps as mentioned in the repo setup guide

## Context
We have your plugin integrated in to our app for a while now. But we havent shipped our app yet due to some other organization decision. I havent touched this branch as of December 10th thats the last time i can verify that the plugin was working in our app without a crash. Now when i try to run it the app started crashing.  So i took a fresh branch without the plugin and tried to integrate the plugin in to our app using the setup instructions descirbed and ended up getting the same crash. Basically when ever the BackgroundGeolocation.Start is called the app crashes. Both in iOS sim as well when a iPhone is connected to the mac and the debug app is deployed to the iphone. 

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
XCode Logs
ℹ️-[TSConfig persist] 
🔵-[TSLocationManager ready] 
2020-02-11 12:33:34.531 [info][tid:com.facebook.react.WebSocketModuleQueue][RCTSRWebSocket.m:518] SocketRocket: In debug mode.  Allowing connection to any root cert

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager start] 
╚═══════════════════════════════════════════════════════════
ℹ️-[TSLocationManager doStart:] trackingMode: 1
ℹ️-[TSConfig persist] 
🎾-[TSGeofenceManager start] 
🔵-[TSLocationManager setPace:] 0
🎾-[TSLocationManager startUpdatingLocation] Location-services: ON

📍<+37.53392599,-122.36202934> +/- 5.00m (speed 34.36 mps / course 340.66) @ 2/11/20, 12:33:33 PM Central Standard Time

╔═══════════════════════════════════════════════════════════
║ -[TSLocationManager locationManager:didUpdateLocations:] Enabled: 1 | isMoving: 0 | df: -1.0m | age: 1.0s
╚═══════════════════════════════════════════════════════════
✅-[TSLocationManager locationManager:didUpdateLocations:] Acquired motionchange position: <+37.53392599,-122.36202934> +/- 5.00m (speed 34.36 mps / course 340.66) @ 2/11/20, 12:33:33 PM Central Standard Time
🔵-[TSLocationManager startMonitoringStationaryRegion:radius:] Radius: 25
🔴-[TSLocationManager stopUpdatingLocation] 
🔵-[TSLocationManager calculateMedianLocationAccuracy:] Median location accuracy: 5.0
🎾-[TSLocationManager startMonitoringSignificantLocationChanges] 

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService flush:] 
╚═══════════════════════════════════════════════════════════
✅-[TSLocationManager persistLocation:]_block_invoke INSERT: C0E699BE-FFED-48FC-A425-938C822031D9
✅-[BackgroundTaskManager createBackgroundTask] 1
✅-[TSHttpService schedulePost] LOCKED: C0E699BE-FFED-48FC-A425-938C822031D9
⚠️-[HttpResponse handleResponse] HTTP ERROR: 0
***
* The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
*
{
    NSErrorFailingURLKey = "http://yourserver.com/locations";
    NSErrorFailingURLStringKey = "http://yourserver.com/locations";
    NSLocalizedDescription = "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1022 \"(null)\"";
}
✅-[TSHttpService post:]_block_invoke UNLOCKED: C0E699BE-FFED-48FC-A425-938C822031D9

╔═══════════════════════════════════════════════════════════
║ -[TSHttpService finish:error:] Success: 0
╚═══════════════════════════════════════════════════════════
ℹ️+[LocationAuthorization run:onCancel:] status: 4
ℹ️-[TSConfig persist] 
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
libc++abi.dylib: terminating with uncaught exception of type NSException
```

</details>

**Comment by christocracy** [comment]
Google the error.  This is not a plugin issue.  This is managed by your app’s .plist Config file.  Standard iOS app 101 stuff.

**Comment by christocracy** [comment]
- And it’s not an *Exception*.  It’s an http error.
- Also, Unrelated, but background-fetch @ 2.8.0 is incompatible with the public version of background-geolocation currently, which is pinned to background-fetch@2.7.1.

**Comment by mailyokesh** [comment]
I did google the error. But nothing related is coming up. If i follow the base steps as described in the plugin setup page am getting this. That is the max log i can get from this.  Where is it mentioned that the public version is pinned to background-fetch@2.7.1?

**Comment by christocracy** [comment]
- what did you google?

> Where is it mentioned that the public version is pinned to background-fetch@2.7.1?

Right [here](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/package.json#L47)

**Comment by mailyokesh** [comment]
See a similar issue in your Git issues #653 but its mentioned as an Expo issue. Am using pure RN, there is nothing special am doing. Just a base app trying to install the plugin from start. Again we have a branch with your plugin already installed which used to work until Dec 10th which stopped working, which lead to the investigation of installing from scratch

**Comment by christocracy** [comment]
What error text did you search for?

**Comment by mailyokesh** [comment]
libc++abi.dylib terminating with uncaught exception of type nsexception

**Comment by christocracy** [comment]
I thought you were talking about this:

> The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

The exception you mention **IS** because you’re using fetch@2.8.0.

You cannot do this until the next version of background-geolocation.

**Comment by mailyokesh** [comment]
Ah let me downgrade and test it then

**Comment by mailyokesh** [comment]
I was following the setup instructions mentioned here https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md. Should this be updated to mention that users are supposed to use fetch@2.7.1 or its expected that users need to look at devDependencies before installing anything?

**Comment by mailyokesh** [comment]
ok can confirm that am no longer getting the crash after updating to fetch@2.7.1. Also now calling the BackgoundGeolocation.Start am no longer getting the location/motion permission popup, this is something i used to get previously. Is this something which is changed to be handled from the app side?

**Comment by christocracy** [comment]
Yes, the install instructions need to be temporarily updated to enforce 2.7.1 until the next version of background-geolocation is released. 

I released a rare and large refactor of fetch@2.8.0 yesterday.

**Comment by mailyokesh** [comment]
Looks like i just choose to update on an unlucky day then :). Can you please confirm if the location/motion permission screens are no longer shown when calling BGLocation.Start, instead needs to be handled by te app?

**Comment by christocracy** [comment]
Nothing changed wrt location/motion permission request at #start in 5 years.

**Comment by mailyokesh** [comment]
looks like a sim issue. Everything is back to working. Thanks for responding quickly.
