### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by nanokoder** [transistorsoft/react-native-background-geolocation#976]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 8, 9
* Device manufacturer / model: Samsung mostly and others
* React Native version (`react-native -v`): 0.61.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
            {
                locationAuthorizationRequest: "Any",
                disableLocationAuthorizationAlert: true,
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOW,
                distanceFilter: 5,            // Must be 0 or locationUpdateInterval is ignored!
                locationUpdateInterval: 1000,  // Get a location every 5 seconds
                disableElasticity: true,
                desiredOdometerAccuracy: 50,
                fastestLocationUpdateInterval: 5000,
                locationAuthorizationAlert: {
                    titleWhenNotEnabled: "Location service is not enabled",
                    titleWhenOff: "Location service is OFF",
                    instructions: "You must enable 'Always' in location-services",
                    cancelButton: "Cancel",
                    settingsButton: "Settings"
                },
                minimumActivityRecognitionConfidence: 15,
                // Activity Recognition
                stopTimeout: 1,
                // Application config
                debug: false, 
                logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
                logMaxDays: 0,
                stopOnTerminate: false,
                startOnBoot: true,        
                foregroundService: true,

                url: 'http://yourserver.com/locations',
                batchSync: false,  
                autoSync: false,    
                headers: { "X-FOO": "bar" },
                params: { "auth_token": "maybe_your_server_authenticates_via_token_YES?" },
                enableHeadless: true,
            }
```

## Expected Behavior

Not crash

## Actual Behavior

Sometimes the App crash

Following exceptions thrown:

#0. Crashed: main
       at android.app.ActivityThread$H.handleMessage + 1855(ActivityThread.java:1855)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 6986(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

--

Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f637c22 u0 com.myapp/com.transistorsoft.locationmanager.service.TrackingService}
       at android.app.ActivityThread$H.handleMessage + 1855(ActivityThread.java:1855)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 6986(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

#0. Crashed: main
       at android.app.ActivityThread$H.handleMessage + 1855(ActivityThread.java:1855)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 6986(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

#1. OkHttp Dispatcher
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$ + 2137(Thread.java:2137)
       at sun.misc.Unsafe.park + 358(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos + 230(LockSupport.java:230)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill + 461(SynchronousQueue.java:461)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer + 362(SynchronousQueue.java:362)
       at java.util.concurrent.SynchronousQueue.poll + 937(SynchronousQueue.java:937)
       at java.util.concurrent.ThreadPoolExecutor.getTask + 1091(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1152(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 764(Thread.java:764)

## Steps to Reproduce

No steps to reproduce, the crash recorded by Google Play Vital and Firebase Crashlytics on remote phone devices

## Context

Capture user's location via geolocation plugin

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->

```

</details>

**Comment by Buthrakaur** [comment]
We observe the same crashes on `com.transistorsoft.locationmanager.service.GeofencingService`, `com.transistorsoft.locationmanager.service.ActivityRecognitionService`, `com.transistorsoft.locationmanager.service.LocationRequestService`. Plugin version 3.4.2 too.

**Comment by christocracy** [comment]
This is generally caused by your app taking too long to boot, where too many tasks are blocking the UI Thread, preventing the plugin's foreground-services from executing `startForeground` in time, causing Android to induce this error upon your app.

You gain insight into which tasks are taking too long by enabling Android [StrictMode](https://developer.android.com/reference/android/os/StrictMode) in your `Application.java`.

See the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/app/src/main/java/com/transistorsoft/backgroundgeolocation/react/MainApplication.java#L44) for an example of enabling `StrictMode`.

**Comment by Buthrakaur** [comment]
Hello @christocracy ,
we still see big amount of crashes caused by this so I researched this little bit deeper.. It looks like e.g. registering the service after phone is rebooted can easily cause these crashes as the phone is overloaded with all the starting apps etc. I also found a suggestion to use JobScheduler and JobService instead of foreground services to solve tasks like this (https://stackoverflow.com/a/56534432/77160) and prevent the crash as there's a timeout of just 5 seconds for the app to react which often can be a problem on lowend devices or after the restart - it's just out of control of the developer.

What's your opinion on this, please - would it make sense to switch to JobScheduler and JobService? This is unfortunately most frequent crash in our app so for us it's quite a pain - we are over 1% crash rate just because of this issue. 
![image](https://user-images.githubusercontent.com/126757/93864366-16d47280-fcc5-11ea-949b-1f993e304583.png)

**Comment by luskin** [comment]
@christocracy We as well are seeing hundreds of these crashes a day, by far our highest crash numbers. I was hoping, similar to @Buthrakaur, that you could help us dive deeper into our problems and help guide us towards a possible solution? You obviously have a much broader understanding of how the low-level processes work, any advice how we should proceed?

**Comment by christocracy** [comment]
See comment [above](https://www.dropbox.com/s/9velqx2cmp152sq/cordova-background-geolocation.mp4?dl=0).  The first thing to do is implement [Android `StrictMode`](https://developer.android.com/reference/android/os/StrictMode) in your `Application.java` then observe `logcat` for `StrictMode` violations.

```
$ adb logcat *:S StrictMode:V
```

**Comment by murtazakaz** [comment]
In android, the app is not responding due to this same issue happening frequently, anyone found a solution to resolve this? @christocracy 

<img width="1362" alt="Screenshot 2021-11-10 at 3 38 45 PM" src="https://user-images.githubusercontent.com/18357274/141098299-a81a1002-34c1-43a4-99e4-790b086c5577.png">

**Comment by christocracy** [comment]
This ANR is a well-known complaint from *all* Android developers everywhere.

See my last comment above and learn to observe StrictMode warnings in logcat when your app launches.

**Comment by tunguyenbhtech** [comment]
> This is generally caused by your app taking too long to boot, where too many tasks are blocking the UI Thread, preventing the plugin's foreground-services from executing `startForeground` in time, causing Android to induce this error upon your app.
> 
> You gain insight into which tasks are taking too long by enabling Android [StrictMode](https://developer.android.com/reference/android/os/StrictMode) in your `Application.java`.
> 
> See the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/app/src/main/java/com/transistorsoft/backgroundgeolocation/react/MainApplication.java#L44) for an example of enabling `StrictMode`.

Hi @christocracy we are also having this problem in our crash report, we tried running android in strict mode and can only see these 2 violations which seems to come from RN background geolocation lib, are those normal ?
Environment:
- Plugin version: 4.9.3
- Platform: Android
- OS version: 11, 12
- Device manufacturer / model: Samsung mostly and others
- React Native version (react-native -v): 0.70.5
- Plugin config:
```
{
    // Logging & Debug Options
    // debug: __DEV__, // debug sounds / notifications
    logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
    logMaxDays:0,

    // Geolocation Config
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 20,
    // Activity Recognition
    stopTimeout: 8,
    // Allow the background-service to continue tracking when user closes the app.
    stopOnTerminate: false,
    heartbeatInterval: 60,
    // app already handled it by listening to providerchange event
    // and react native has a bug with not being able to present multiple alert / modal at the same time
    // ( freeze UI - a view layer on top not being removed )
    // https://github.com/facebook/react-native/issues/10471
    disableLocationAuthorizationAlert: true,
    // request location permission "Always" dialog text config
    // https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353
    backgroundPermissionRationale: {
        title: `Allow ${APP_CONFIG.companyName} to access to this device's location in the background?`,
        message: `In order to track your activity in the background, please enable ${backgroundPermissionOptionLabel} location permission`,
        positiveAction: `Change to ${backgroundPermissionOptionLabel}`,
        negativeAction: 'Cancel',
    },
    startOnBoot: true,
    enableHeadless: true,
    maxRecordsToPersist: 0, // We dont use server sync so SQLLite database should not be used.
    reset: false,
}
```

![Screen Shot 2022-11-22 at 4 31 56 PM](https://user-images.githubusercontent.com/19772201/203454097-3490c236-95b1-44d2-b77b-474ecf565822.png)
![Screen Shot 2022-11-22 at 4 32 04 PM](https://user-images.githubusercontent.com/19772201/203454120-44eefa29-ff52-4735-89e6-5bcbbcf213de.png)

**Comment by christocracy** [comment]
It’s not unusual to see a few StrictMode violations.  The ones you show are blocking the main thread for only 19ms.  Not an issue.

**Comment by tunguyenbhtech** [comment]
> It’s not unusual to see a few StrictMode violations. The ones you show are blocking the main thread for only 19ms. Not an issue.

I see, thanks @christocracy, in our app we don't need to use sqlite for storing locations, do you think our config is optimal for minimizing disk workload ?

**Comment by christocracy** [comment]
> do you think our config is optimal for minimizing disk workload ?

Yes, you’ve configured maxRecordsToPersist: 0

**Comment by macielrsf** [comment]
Hi @christocracy,

I'm facing this same problem at Google Play Console. Can you validate my component ? Are there something wrong ? 

<img width="1221" alt="Image" src="https://github.com/user-attachments/assets/d95f743d-8e6e-4034-ac89-4f6f1fdae4c5" />

<img width="1214" alt="Image" src="https://github.com/user-attachments/assets/ea80618c-925d-410a-9520-704cd6a82eed" />

`import * as HttpRequest from '~/services/HttpRequest';
import * as types from '~/constants/ActionTypes';
import React, {useCallback, Fragment, useEffect, useState, useRef} from 'react';
import {AppState, Platform} from 'react-native';
import {checkRequest} from '~/hooks/sync_geolocation/Useful';
import {connect} from 'react-redux';
import {
    modificaNivelBateria,
    modificaDispositivoInfo,
    modificaStatusConexao,
} from '~/actions/DeviceInfoActions';
import {useDispatch} from 'react-redux';
import BackgroundGeolocation from 'react-native-background-geolocation';
import DeviceInfo from 'react-native-device-info';
import NetInfo from '@react-native-community/netinfo';
import moment from 'moment';
import showToast from '~/services/Toast';
import useSyncGeolocation from '~/hooks/sync_geolocation';

const HubsoftBackgroundGeolocation = ({
    navigation,
    os_reservada,
    nivel_bateria,
    modelo_dispositivo,
    fabricante,
    modificaNivelBateria,
    modificaDispositivoInfo,
}) => {
    const dispatch = useDispatch();
    const handleSync = useSyncGeolocation();

    const [enabled, setEnabled] = useState(false);
    const isProcessing = useRef(false);

    useEffect(() => {
        // Força a captura de localizações
        if ((__DEV__ && enabled) || (enabled && Platform.OS === 'ios')) {
            BackgroundGeolocation.changePace(true)
                .then(success =>
                    console.log(
                        '[HubsoftBackgroundGeolocation - useEffect] changePace(true)',
                    ),
                )
                .catch(err =>
                    console.error(
                        '[HubsoftBackgroundGeolocation - useEffect] changePace(false):',
                        err,
                    ),
                );
        }
    }, [enabled]);

    useEffect(() => {
        try {
            /// 1.  Subscribe to events.
            const onLocation = BackgroundGeolocation.onLocation(location => {
                console.log(
                    '[HubsoftBackgroundGeolocation - useEffect] onLocation',
                );
                _modificaDeviceInfo();
            });

            let config = {
                notification: {
                    title: 'Hubsoft',
                    text: 'Executando',
                },
                desiredAccuracy: Platform.select({
                    ios: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
                    android: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                }),
                debug: __DEV__,
                logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
                stopOnTerminate: false,
                startOnBoot: false,
                url: `${HttpRequest.getConfig(
                    'baseURL',
                )}api/v1/app/geolocalizacao/usuario`,
                autoSync: true,
                batchSync: true,
                locationTemplate:
                    '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"velocidade":<%= speed %>,"time":"<%= timestamp %>","id":"<%= uuid %>","nivel_bateria": <%= battery.level %>}',
                headers: {
                    accept: 'application/json',
                    'content-type': 'application/json',
                    authorization: HttpRequest.getConfig('Authorization'),
                },
                params: {
                    timezone: 'America/Recife',
                },
                extras: {
                    modelo_dispositivo,
                    fabricante,
                },
                //iOS Options
                showsBackgroundLocationIndicator: true,
                stationaryRadius: 10,
                heartbeatInterval: Platform.select({ios: 10, android: 60}),
                preventSuspend: Platform.select({ios: true, android: false}),
                activityType:
                    BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
            };

            /*
             * Caso possua uma O.S. reservada,
             * a sincronização das geolocalizações
             * serão feitas de forma mais rápida
             */
            if (os_reservada) {
                config = {
                    ...config,
                    autoSyncThreshold: 1,
                    distanceFilter: Platform.select({ios: 10, android: 10}),
                    stopTimeout: 20,
                };
            } else {
                config = {
                    ...config,
                    autoSyncThreshold: 5,
                    maxBatchSize: 100,
                    distanceFilter: Platform.select({ios: 10, android: 20}),
                    stopTimeout: 5,
                };
            }

            /// 2. ready the plugin.
            BackgroundGeolocation.ready(config)
                .then(state => {
                    setEnabled(state.enabled);

                    console.log(
                        '[HubsoftBackgroundGeolocation] BackgroundGeolocation is configured and ready: ',
                        state.enabled,
                    );

                    // Sincroniza geolocalizações
                    // ao iniciar APP
                    if (state.enabled) {
                        _handleSync();
                    }
                })
                .catch(err => {
                    console.error('[HubsoftBackgroundGeolocation] ', err);
                });

            return () => {
                // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
                // during development live-reload.  Without this, event-listeners will accumulate with
                // each refresh during live-reload.
                onLocation.remove();
            };
        } catch (error) {
            console.error(error);
        }
    }, [
        os_reservada,
        fabricante,
        modelo_dispositivo,
        _handleSync,
        _modificaDeviceInfo,
        _verificaStatusGeolocalizacao,
    ]);

    /// 3. start / stop BackgroundGeolocation
    React.useEffect(() => {
        _verificaStatusGeolocalizacao();
    }, [_verificaStatusGeolocalizacao]);

    /*
    useEffect(() => {
        BackgroundGeolocation.logger
            .emailLog('maciel@hubsoft.com.br', {
                order: BackgroundGeolocation.logger.ORDER_DESC,
                limit: 1000,
            })
            .then(success => {
                console.log('[emailLog] SUCCESS');
            })
            .catch(error => {
                console.log('[emailLog] ERROR: ', error);
            });
    }, []);
    */

    const _getCurrentPosition = useCallback(() => {
        if (enabled) {
            BackgroundGeolocation.getCurrentPosition({
                timeout: 30, // 30 second timeout to fetch location
                maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
                desiredAccuracy: 10, // Try to fetch a location with an accuracy of `10` meters.
                samples: 3, // How many location samples to attempt.
                extras: {
                    // Custom meta-data.
                    fabricante,
                    modelo_dispositivo,
                },
            })
                .then(location => {
                    console.log(
                        '[HubsoftBackgroundGeolocation - _getCurrentPosition] ',
                        location.uuid,
                    );
                    handleSync();
                })
                .catch(e => {
                    console.error(
                        '[HubsoftBackgroundGeolocation - _getCurrentPosition] ',
                        e,
                    );
                });
        }
    }, [fabricante, modelo_dispositivo, handleSync, enabled]);

    const _handleSync = useCallback(() => {
        try {
            _getCurrentPosition();
        } catch (e) {
            console.error('[HubsoftBackgroundGeolocation - _handleSync] ', e);
        }
    }, [_getCurrentPosition]);

    const _verificaStatusGeolocalizacao = useCallback(async () => {
        try {
            /*
             * Verifica se já excedeu o intervalo
             * de 2 minutos desde a última verificação do
             * status de geolocalização
             */
            const allowReq = await checkRequest('ultima_verificacao', 2);

            if (!allowReq) {
                return;
            }

            const state = await NetInfo.fetch();

            if (state.isConnected) {
                HttpRequest.get(
                    'api/v1/app/geolocalizacao/usuario/rastreamento/status',
                )
                    .then(response => {
                        dispatch({
                            type: types.MODIFICA_ULTIMA_VERIFICACAO_GEOLOCALIZACAO,
                            payload: {
                                ultima_verificacao: moment(),
                            },
                        });

                        _handleBgGeolocation(response.iniciar);
                    })
                    .catch(e => {
                        console.error(
                            '[HubsoftBackgroundGeolocation - _verificaStatusGeolocalizacao] ',
                            e,
                        );
                        _handleBgGeolocation(true);
                    });
            } else {
                _handleBgGeolocation(true);
            }
        } catch (e) {
            console.error(
                '[HubsoftBackgroundGeolocation - _verificaStatusGeolocalizacao] ',
                e,
            );
            showToast(
                'error',
                'Problema',
                'Falha ao tentar verificar status do rastreamento',
            );
        }
    }, [dispatch, _handleBgGeolocation]);

    const _handleBgGeolocation = useCallback(
        iniciar => {
            if (isProcessing.current) {
                console.log(
                    '[HubsoftBackgroundGeolocation - _handleBgGeolocation] Operação já em andamento, ignorando chamada duplicada.',
                );
                return;
            }

            setTimeout(() => {
                try {
                    isProcessing.current = true;

                    const _dispatch = () => {
                        dispatch({
                            type: types.MODIFICA_RASTREAMENTO_USUARIO,
                            payload: {
                                rastreamento_usuario: iniciar,
                            },
                        });
                    };

                    if (!enabled && iniciar) {
                        BackgroundGeolocation.start()
                            .then(state =>
                                console.log(
                                    '[HubsoftBackgroundGeolocation - _handleBgGeolocation] success: ',
                                    state,
                                ),
                            )
                            .catch(e =>
                                console.error(
                                    '[HubsoftBackgroundGeolocation - _handleBgGeolocation] ',
                                    e,
                                ),
                            )
                            .finally(() => _dispatch());
                    } else if (!iniciar && AppState.currentState === 'active') {
                        BackgroundGeolocation.stop()
                            .then(() => _dispatch())
                            .catch(() => _dispatch());
                    }
                } catch (error) {
                    console.error(
                        '[HubsoftBackgroundGeolocation - _handleBgGeolocation] ',
                        error,
                    );
                } finally {
                    isProcessing.current = false;
                }
            }, 5000);
        },
        [dispatch, enabled],
    );

    const _modificaDeviceInfo = useCallback(() => {
        try {
            DeviceInfo.getBatteryLevel().then(batteryLevel => {
                let value = Math.round(batteryLevel.toFixed(2) * 100);
                modificaNivelBateria(value);
            });

            modificaDispositivoInfo({
                modelo_dispositivo: DeviceInfo.getModel(),
                fabricante: DeviceInfo.getBrand(),
            });
        } catch (e) {
            console.error(
                '[HubsoftBackgroundGeolocation - _modificaDeviceInfo] ',
                e,
            );
        }
    }, [modificaDispositivoInfo, modificaNivelBateria]);

    return <Fragment />;
};

const mapStateToProps = state => ({
    nivel_bateria: state.DeviceInfoReducer.nivel_bateria,
    modelo_dispositivo: state.DeviceInfoReducer.modelo_dispositivo,
    fabricante: state.DeviceInfoReducer.fabricante,
    os_reservada: state.OrdemServicoExecucaoReducer.os_reservada,
});

const actions = {
    modificaNivelBateria,
    modificaDispositivoInfo,
    modificaStatusConexao,
};

export default connect(mapStateToProps, actions)(HubsoftBackgroundGeolocation);
`

**Comment by christocracy** [comment]
Well, you’re using a `setTimeout` with a 5s delay to call .start() or .stop()…that’s pretty weird.

**Comment by macielrsf** [comment]
> Well, you’re using a `setTimeout` with a 5s delay to call .start() or .stop()…that’s pretty weird.

Anything else ? 

I considered to use it because I saw in another thread here that could be a delay during the app's opening and the "start()" or "stop()" of the background service could overload the app causing the crash.

**Comment by christocracy** [comment]
At the Flutter version, I wrote a wiki about this:
https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-ANR-%22Context.startForegroundService()-did-not-then-call-Service.startForeground()%22

**Comment by simoneantonicchio** [comment]
@macielrsf have you solved, I'm facing similar issue

**Comment by chanphiromsok** [comment]
I also encounter the issue here is the log from firebase 
```
   Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{17b6b92 u0 com.my_app_package/com.transistorsoft.locationmanager.service.TrackingService c:com.my_app_package}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2483)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2451)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2807)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loopOnce(Looper.java:282)
       at android.os.Looper.loop(Looper.java:387)
       at android.app.ActivityThread.main(ActivityThread.java:9505)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
```

**Comment by UnderTheMoonspell** [comment]
We started seeing this also after upgrading from 4.17.2 to 4.18.5

**Comment by Nalymoslih** [comment]
any update?

**Comment by thisisadarshjaiswal** [comment]
Anyone able to find the solution for this? This is affecting our matrix by huge

**Comment by pubudithajayasekara** [comment]
I’m also seeing a number of these `Context.startForegroundService() `did not then call `Service.startForeground()` crashes in Crashlytics/Play Console, but like here, I haven’t been able to reproduce it locally or reliably.

**Has anyone here actually reproduced this crash through a specific set of steps?**

**Comment by christocracy** [comment]
You can reproduce this by doing a whole bunch of work on the main thread while your app launches.

This is not a bug of this sdk, it's a symptom of your app blocking the main thread.

**Comment by pubudithajayasekara** [comment]
Following up on [your earlier comment](https://github.com/transistorsoft/react-native-background-geolocation/issues/976#issuecomment-708537809) about observing logcat for StrictMode violations.

I enabled **StrictMode** in our Android app (debug builds) using `ThreadPolicy.Builder().detectAll().penaltyLog()` in `MainApplication.onCreate()` and captured logcat while launching and using the app.

What I’m seeing:

- Around ~20–25 StrictMode policy violations total.
- All of them are DiskReadViolation / DiskWriteViolation coming from [org.altbeacon.beacon.service.*] (e.g. MonitoringStatus, ScanHelper, CycledLeScanner).
- Each violation is very short, roughly 2–10 ms.
- I’m not seeing any obvious long‑running disk/network violations from our own package (com.AppName) around app startup.

Despite that, we’re still getting occasional crash reports in RayGun:

`ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord
`

Questions:

- Given that StrictMode only shows short (2–10 ms) violations in the altbeacon library, does that still fit your hypothesis that our app is blocking the main thread long enough to cause this LocationRequestService timeout?

- Is there anything specific you’d recommend we look at in the RNBG configuration or usage patterns (e.g., timing of [ready()], [getCurrentPosition()], etc.) that could contribute to this, even when StrictMode isn’t reporting obvious heavy work from our own code?

**Comment by spsaucier** [comment]
**Still happening on v4.19.2** — specifically on `GeofencingService`, not `TrackingService`.

```
android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground():
  ServiceRecord{... com.vehotechnologies.Driver/com.transistorsoft.locationmanager.service.GeofencingService}
```

This is our **most common Android crash** in production. Our app registers a high number of geofences (stop-level + facility-level for delivery drivers), so geofence transitions are frequent — especially on dense routes with clustered stops.

The root cause appears to be the same as described in #1627: `AbstractService.doStartForeground()` → `ForegroundNotification.build()` → `TSLocalNotification.build()` performs synchronous binder IPC (`getNotificationChannel`, `PendingIntent.getActivity`) on the main thread. When the main thread is under any load (React Native rendering, map updates, etc.), these calls stall past Android's foreground service timeout.

**Config:**
```js
{
  foregroundService: true,
  notification: {
    title: "...",
    text: "...",
    channelName: "Location Updates",
  },
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  distanceFilter: 5,
  // ... geofences added via addGeofences()
}
```

**Questions:**
1. Has the notification building path been moved off the main thread in v5.x?
2. Is there any v4.x mitigation beyond `enableHeadless: true` and reducing geofence count?
3. Would pre-creating the `NotificationChannel` in our `Application.onCreate()` help bypass the blocking `getNotificationChannel()` call?

**Comment by christocracy** [comment]
This is not a problem with the SDK.  Android provides exactly 10s for a foreground-service to call .startForeground on the main thread.  If your app is blocking the main thread, preventing the SDK from promoting is services to foreground, Android crashes your app on-purpose.

It's up to you to ensure your app is not blocking the main thread on app launch.

**Comment by spsaucier** [comment]
Understood — we're running StrictMode to identify main thread violations. One follow-up: does enableHeadless: true help with this specific scenario? Our concern is that the RN bridge initialization on background wake is consuming most of that 10s window before your service gets its turn.

**Comment by claudiovillalobos** [comment]
@spsaucier We’re running with enableHeadless: true, and we still see this crash fairly often in production. So headless mode alone doesn’t seem to prevent the ForegroundServiceDidNotStartInTimeException on our side.

We also use a large number of geofences (route/field operations use case). This made me revisit that, since multiple geofence wakeups + RN bridge initialization could be consuming much of the allowed window before the service calls startForeground().

The tricky part is that it’s hard to debug — this mainly happens with real clients in production, and we haven’t been able to reliably reproduce it locally.

**Comment by christocracy** [comment]
>does enableHeadless: true help with this specific scenario? 

No.

**Comment by spsaucier** [comment]
As a mitigation on our side, we've implemented **proximity-windowed geofencing**: instead of registering all stop geofences upfront, we only keep the 10 nearest stops registered as native geofences at any time, reassessing the window as the driver moves (200m distance threshold or 60s interval). This cuts active native geofences from 80–160+ down to 20, significantly reducing `GeofencingService` startup frequency.

**Comment by christocracy** [comment]
This issue has been closed since 2020.

I suggest you post a new issue.

**Comment by christocracy** [comment]
> only keep the 10 nearest stops registered as native geofences at any time

I could make this an SDK option.  The SDK already has proximity activated geofencing for when count > 100 ("*infinite geofencing*").

**Comment by saucier-consulting** [comment]
That would be nice if there's no other workaround.

**Comment by christocracy** [comment]
Try updating to latest `tslocationmanager`.  

```
cd android
./gradlew app:dependencies --refresh-dependencies | grep tslocationmanager

tslocationmanager:4.0.15
```

In response to Flutter user, I've implemented a "foreground-service launch queue" to delay FGS launch on a cold boot.

This user has reported a 70% decrease in these exceptions.

On cold boot, the SDK now queues all FGS launches and waits for `2000ms` (configurable via `AppConfig.serviceLaunchDelay`, though not yet exposed to `typescript` API).

In addition, and *importantly*, the SDK will also queue headless-events until the FGS launch-queue is flushed, to prevent client-code from possibly blocking the main-thread while FGS launch-queue is being flushed.

**Timeline example:**

* T=0ms:    Boot event → `ServiceLaunchReceiver` queues `ActivityRecognitionService`
  * Boot event → `HeadlessEventBroadcaster` queues 'boot' event
* T=100ms:  Geofence fires → `ServiceLaunchReceiver` queues `GeofencingService`
  * Geofence → `HeadlessEventBroadcaster` queues 'geofence' event
* T=2000ms: `ServiceLaunchReceiver` drains queue → launches 2 services
* T=2050ms: Both services call `startForeground()` → `notifyServiceReady()`
* T=2050ms: `HeadlessEventBroadcaster` receives signal → drains event queue
* T=2050ms: Customer's `BackgroundGeolocationHeadlessTask` receives events
