### ISSUE TITLE
Locations not being saved in SQL and uploaded

### ISSUE THREAD

**Issue by andrewanderson58** [transistorsoft/react-native-background-geolocation#978]
## Your Environment
* Plugin version:
    "react-native-background-geolocation": "^3.4.2",
    "react-native-background-location": "^1.0.2",
iOS
13.3.1
IPhone X
0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready(
      {
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 1,
        loiteringDelay: 300000,
        notifyOnDwell: true,
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        url: baseUrl,
        maxBatchSize: 10,
        batchSync: true, // <-- set to true
        autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
        autoSyncThreshold: 10,
        maxRecordsToPersist: 1000,
        maxDaysToPersist: 7,
        geofenceModeHighAccuracy: true,
        persistMode: BackgroundGeolocation.PERSIST_MODE_LOCATION,
        reset: true,
        headers: {
          ...headers,
        },
        params: {
          // <-- Optional HTTP params
        },
      }).then(state => {
        if (!state.enabled) {
          BackgroundGeolocation.start(() => {
            console.log('- GEOLOCATOR Start success');
          });
        }
        console.log(state)
        refreshTokenOnError();
        return state;
      });


const refreshTokenOnError = () => {
  BackgroundGeolocation.onHttp(httpEvent => {
    const statusCode = parseInt(parseInt(httpEvent.status) / 100);
    if (statusCode == 4) {
      getToken().then(headers => {
        BackgroundGeolocation.setConfig({
          headers
        });
        BackgroundGeolocation.sync();
      });
    } else {
      console.log('***HTPP EVENT****', httpEvent);
    }
  });
};
```

## Expected Behavior
When a new location is fired, pool in SQL and send based on config

## Actual Behavior
Events appear to be happeining based on debug push notifications but never appear to send via http. Also, do not appear when calling `BackgroundGeolocation.getLocations()`

## Steps to Reproduce

1.
2.
3.
4.

## Context
I will lead with I had this library working for a few months no issue. I recently, added in the geofences and added the dwell settings to the config and also added some background fetch work in another part of the app. Since then I do not seem to get any locations. I see the push notifications for entering geofence (do not see the exit or dwell) but I also see the stationary movement ones but they never seem to send to the backend. 

I have searched through issues for hours but do not seem to have found anyone with an issue similar. 

is `BackgroundGeolocation.getLocations()` the best way to see any locations that have not sent via the built in http?  

Also, if that is true what is a reason these would not be saved?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version

See the recent items in CHANGELOG referencing maxRecordsToPersist

**Comment by andrewanderson58** [comment]
@christocracy  The only recent items I see are from 2016 and involve [not persisting when == 0](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#051---2016-04-15)
and [maxRecordsToPersist added to the config](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#050---2016-04-04)

I am currently setting mine to 
```
        maxRecordsToPersist: 1000,
        maxDaysToPersist: 7,
```

Even without those, I am not seeing anything.

**Comment by christocracy** [comment]
Right, it’s in the private “customers only” repo in 3.5.0.  Do you own a license with active support subscription?

> [Fixed] Android: Do not throttle http requests after http connect failure when configured with maxRecordsToPersist.

It’s due to be mirrored here soon.

In the meantime, you can likely fix your problem by removing `maxRecordsToPersist`.  You should see interesting log entries referencing http failures.

**Comment by andrewanderson58** [comment]
@christocracy I do have a license and totally missed the separate repo. I will close this issue and read through any changes documented and open a new one with more details if the issue persists. Thank you.
