### ISSUE TITLE
getLocations - obtain subset of locations [enhancement]

### ISSUE THREAD

**Issue by Gnative** [transistorsoft/react-native-background-geolocation#98]
Be able to get a subset of locations based on an id or an extras key/value. This would really help with any custom functions or data syncing.

Also possibly delete locations based on the above or lack of.

**Comment by christocracy** [comment]
Not gonna happen.

Use the js callback to store locations in your own desired presence
mechanism.

The plugin stores locations as JSON string for simplicity and
schema-flexibility at the expense of queryability.

On Saturday, July 9, 2016, Gnative <notifications@github.com> wrote:

> Be able to get a subset of location base on an id or an extras key/value.
> This would really help with any custom functions or data syncing.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/react-native-background-geolocation/issues/98>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lxhc8KwCwDv135y5U1Y4ZsAZTV_wks5qT1W7gaJpZM4JIkiR>
> .
>


-- 
Snet form Gmail Mobile
