### ISSUE TITLE
Frequent notifications on iphone

### ISSUE THREAD

**Issue by swapanil** [transistorsoft/react-native-background-geolocation#980]
When an event happens as the auth state changed, motion changed, location change or other it is giving notification. Notification is good and informative but so many notifications give users a bad experience.

How can I disable all notifications?

Is there anything like:

```
BackgroundGeolocation.ready({
  notifications: false
})
```

**Comment by darkredz** [comment]
I also got this especially on every open of the app a notification "Authorization status changed 3" eventhough my config is with debug false

```
BackgroundGeolocation.ready({
  debug: false
})
```
