### ISSUE TITLE
Query: Periodic location 

### ISSUE THREAD

**Issue by mustaqeem** [transistorsoft/react-native-background-geolocation#981]
Hi @christocracy 

My requirement is to track user's location periodically but tracking stops when user is not moving.
## Your Environment
* Plugin version: "react-native-background-geolocation": "^3.4.2",
    "react-native-background-geolocation-firebase": "^0.3.0",
* Platform: Android
* OS version: 9
* Device manufacturer / model: Xiaomi
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
        // Geolocation Config
        reset: false,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        locationUpdateInterval: 100000,
        heartbeatInterval: 0.5,
        disableElasticity: true,
        foregroundService: true,
        enableHeadless: true,
        debug: true,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,
        startOnBoot: true
      }
```

## Expected Behavior
Location should be updated even when user is not moving.

## Actual Behavior
Location is not updating when user is not moving.

**Comment by christocracy** [comment]
Yes, this is the plugin's [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation):  to track location only when the device is moving and conserve energy when the device is stopped.

If you want periodic locations while the device is *stationary*, It's entirely your responsibility.

See:
- See API docs for event `#onHeartbeat`.
- [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch)
