### ISSUE TITLE
Issue during npm install v2.7.1

### ISSUE THREAD

**Issue by gkcom123** [transistorsoft/react-native-background-geolocation#985]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Actual Behavior

In file included from ../deps/grpc/include/grpc/support/port_platform.h:22:
../deps/grpc/include/grpc/impl/codegen/port_platform.h:201:9: warning: 'GRPC_ARES' macro redefined
      [-Wmacro-redefined]
#define GRPC_ARES 0
        ^
<command line>:3:9: note: previous definition is here
#define GRPC_ARES 1
        ^
In file included from ../deps/grpc/src/core/lib/surface/init.cc:32:
In file included from ../deps/grpc/src/core/lib/channel/handshaker_registry.h:26:
In file included from ../deps/grpc/src/core/lib/channel/handshaker_factory.h:26:
In file included from ../deps/grpc/src/core/lib/channel/handshaker.h:35:
In file included from ../deps/grpc/src/core/lib/iomgr/tcp_server.h:30:
In file included from ../deps/grpc/src/core/lib/iomgr/resolve_address.h:26:
../deps/grpc/src/core/lib/iomgr/port.h:211:2: error: "Must define exactly one of GRPC_POSIX_SOCKET,
      GRPC_WINSOCK_SOCKET, GRPC_CUSTOM_SOCKET"
#error \
 ^
1 warning and 1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Never seen this.  None of that references the plugin.

Are you sure you have the latest XCode installed?

**Comment by gkcom123** [comment]
Yes, i have Version 11.3.1 (11C504). 
When i do  yarn add react-native-background-fetch@2.7.1. 

Recent release of  react-native-background-fetch is crashing my app. Any suggestion

**Comment by christocracy** [comment]
>Recent release of react-native-background-fetch

`2.7.1` is not a recent release.  `3.0.0` is the recent release.

**Comment by gkcom123** [comment]
when i do yarn add react-native-background-fetch
i get below error
<command line>:3:9: note: previous definition is here
#define GRPC_ARES 1
        ^
In file included from ../deps/grpc/src/core/lib/surface/init.cc:32:
In file included from ../deps/grpc/src/core/lib/channel/handshaker_registry.h:26:
In file included from ../deps/grpc/src/core/lib/channel/handshaker_factory.h:26:
In file included from ../deps/grpc/src/core/lib/channel/handshaker.h:35:
In file included from ../deps/grpc/src/core/lib/iomgr/tcp_server.h:30:
In file included from ../deps/grpc/src/core/lib/iomgr/resolve_address.h:26:
../deps/grpc/src/core/lib/iomgr/port.h:211:2: error: "Must define exactly one of GRPC_POSIX_SOCKET, GRPC_WINSOCK_SOCKET, GRPC_CUSTOM_SOCKET"
#error \
 ^
1 warning and 1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static

**Comment by christocracy** [comment]
Are you following the *Auto Link" setup instructions?

```
yarn add react-native-background-fetch@2.7.1
```

**Comment by gkcom123** [comment]
Hi 
All i am doing is just trying to install below
    "react-native-background-fetch": "^2.7.1",
    "react-native-background-geolocation": "^3.4.2",
But i am unable to due to these error: 
I am not sure whether its module specific error. 
../deps/grpc/src/core/lib/iomgr/port.h:211:2: error: "Must define exactly one of GRPC_POSIX_SOCKET,
      GRPC_WINSOCK_SOCKET, GRPC_CUSTOM_SOCKET"
#error \
 ^
1 warning and 1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by christocracy** [comment]
I don't know.  Looks like something wrong on your local machine.

**Comment by gkcom123** [comment]
Sorry about that... did complete clean up npm cache, node_modules , package lock etc. Works fine
