### ISSUE TITLE
Question: Does the location change listener works when it is terminated by swiping from recent app list?

### ISSUE THREAD

**Issue by iamshadmirza** [transistorsoft/react-native-background-geolocation#987]
The module is working in background correctly but not when the app is killed from recent apps
So wanted to ask if there is any specific configuration for that or the module is supposed to stop when the app is terminated.
The headless js is set up correctly so I think it should work even after the app is killed
But I can't see any logs or hear the debug sound on location change.
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 7.1.2
* Device manufacturer / model: Xiaomi
* React Native version (`react-native -v`): 0.61.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
 BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      enableHeadless: true,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: 'http://yourserver.com/locations',
      batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {              // <-- Optional HTTP headers
        'X-FOO': 'bar',
      },
      params: {               // <-- Optional HTTP params
        'auth_token': 'maybe_your_server_authenticates_via_token_YES?',
      },
    }, (state) => {
      console.log('- BackgroundGeolocation is configured and ready: ', state.enabled);

      if (!state.enabled) {
        ////
        // 3. Start tracking!
        //
        BackgroundGeolocation.start(function () {
          console.log('- Start success');
        });
      }
    });
  }
```

## Context
Just a question, whether the app is supposed to work even when cleared from recent apps or the stopping behavior is correct. We have a required to get the location of user at all time.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Just a question, whether the app is supposed to work even when cleared from recent apps or the stopping behavior is correct

Yes.  After terminating your Android app, all events will be fired into your registered headless-task when the device is detected to be moving (you can simulate *walking* by shaking the device vigorously for some time, which depends on the device &mdash; some device take seconds while others can take a minute or more).

If that doesn't awaken your device, see http://dontkillmyapp.com.

**Comment by iamshadmirza** [comment]
Thanks for the info @christocracy. I'm closing the issue.
