### ISSUE TITLE
Device OnStop issue

### ISSUE THREAD

**Issue by gkcom123** [transistorsoft/react-native-background-geolocation#988]
## Your Environment
* Plugin version:
* Platform: iOS 
* OS version:11
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.61
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onMotionChange((event) => {
      if (event.isMoving) {
         //console.log("[onMotionChange] Device has just started MOVING ", event.location);
      } else {
         //console.log("[onMotionChange] Device has just STOPPED:  ", event.location);
         // Get the location and update the heading
         showToast(
          "Device has just STOPPED:"
        );
         const {coords} = event.location;
         const data = {lat:coords.latitude , lng: coords.longitude};
         this.props.GetGeocodeAddress(data,'user').then((result) => {
         
         });
      }```

## Expected Behavior
This method should trigger every time device movement stops
## Actual Behavior
This method does not trigger when device stops moving. I am moving with device and observerd that this is not triggered everytime. On Reload, it triggers only once. Am i missing something
## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- What were you trying to do? -->

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Plugin version:
>Device manufacturer / model:

**Comment by gkcom123** [comment]
"react-native-background-geolocation": "^3.4.2",
Device : iphone 11, Ios 13.1
I really appreciate your quick reply

**Comment by christocracy** [comment]
>Plugin config

**Comment by gkcom123** [comment]
`trackBgLocation = () => {
    const { appConfig } = this.props;
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100,
      maxRecordsToPersist: 2,
      // Application config
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when app terminated.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      url: BASE_API_URL+'/user/v1/bgLocation',
      batchSync: false,       // <-- Set true to sync locations to server in a single HTTP request.
      autoSync: true,         // <-- Set true to sync each location to server as it arrives.
      headers: {
        'Content-Type': 'application/json',
        'x-auth': appConfig.authToken,
      }
    }, (state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
        });
      }
    });`

Above method is called on ComponentDidMount

**Comment by christocracy** [comment]
When posting multiple-lines of code, you surround you code in *3 backticks*, not *one*.

**Comment by christocracy** [comment]
You can also optionally apply the syntax-highlighting language:
![](https://dl.dropboxusercontent.com/s/wy5ksnswdy9yk8n/Screenshot%202020-02-23%2011.59.50.png?dl=1)

**Comment by christocracy** [comment]
When having issues, the first thing you do is:
```javascript
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
debug: true
```

Then you boot your app in XCode and observe the logs or fetch the logs from the plugin's database.  See Wiki *Debugging*.

**Comment by christocracy** [comment]
You might also want to read the API docs for `Config.stopTimeout`.

**Comment by gkcom123** [comment]
Cool, i would try that . 
Quick question: Does above config means that onMotionChange will work only when my app not in Foreground. Just wanted to confirm

**Comment by christocracy** [comment]
The plugin doesn't care if your app in in foreground/background.
