### ISSUE TITLE
 Background Geolocation plugin location on event  is triggering continuously irrespective of the distance filter / time interval

### ISSUE THREAD

**Issue by manojkumaraut** [transistorsoft/react-native-background-geolocation#990]
Hi,
 Background Geolocation plugin location on event  is triggering continuously irrespective of the distance filter / time interval
 BackgroundGeolocation.configure({
        desiredAccuracy: 0,
        stationaryRadius: 5,
        distanceFilter: 300,
        debug: true,
        startOnBoot: false,
        stopOnTerminate: false,
        locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,     
        geofenceInitialTriggerEntry: false
    }, (state) => {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
        if (!state.enabled) {
            BackgroundGeolocation.start(function () {
                console.log("- Start success");
            });
        }
    });

i have **provided distance filter as 300m** , but the    BackgroundGeolocation.on('location', (location) => {
is triggering continuously irrespective of the distance filter 

2. Simliarly  for **Time Based ,  locationUpdateInterval:60000 , with distance Filter :0**  there is no change on time based location event BackgroundGeolocation.on('location', (location) => { is triggering continuously irrespective of the time interval

**Comment by christocracy** [comment]
The issue template is **not** optional.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by manojkumaraut** [comment]
Your Environment
Plugin version: 2.9.4
Platform: Android
OS version: 7.1
Device manufacturer / model:
React Native version (react-native -v): 0.55.4
**Plugin config**
BackgroundGeolocation.configure({
desiredAccuracy: 0,
stationaryRadius: 5,
distanceFilter: 300,
debug: true,
startOnBoot: false,
stopOnTerminate: false,
locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
geofenceInitialTriggerEntry: false
}, (state) => {
console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
if (!state.enabled) {
BackgroundGeolocation.start(function () {
console.log("- Start success");
});
}
});

## **Expected Behavior**
This method should  update location /get location based on Distance Filter/ Timing Interval
## **Actual Behavior**
Background Geolocation plugin location on event is triggering continuously irrespective of the distance filter / time interval
1 ) i have provided distance filter as 300m , but the BackgroundGeolocation.on('location', (location) => 
is triggering continuously irrespective of the distance filter

2 ) Simliarly for Time Based , locationUpdateInterval:60000 , with distance Filter :0 there is no change on time based location event BackgroundGeolocation.on('location', (location) => { is triggering continuously irrespective of the time interval

## **Steps to Reproduce**

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE

**Comment by christocracy** [comment]
[2.9.4](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#294---2017-09-25) is a release from 2017.  Upgrade to latest v3.

**Comment by manojkumaraut** [comment]
do we have the issue in current 2.9.4 version ?

**Comment by manojkumaraut** [comment]
Your Environment
Plugin version: 3.4.2
Platform: Android
OS version: 7.1
Device manufacturer / model:
React Native version (react-native -v): 0.61

**Plugin config**

   BackgroundGeolocation.ready({
        desiredAccuracy: 0,
        stationaryRadius: 5,
        distanceFilter: 200,
        debug: true,
        startOnBoot: false,
        stopOnTerminate: false,
        locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
        stopOnStillActivity: false,
        geofenceInitialTriggerEntry: false
    }, (state) => {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
        if (!state.enabled) {
            BackgroundGeolocation.start(function () {
                console.log("- Start success");
            });
        }
    });

## **Actual Behavior**
BackgroundGeolocation.onLocation((location) => {  -----> Triggers continuously i have updated the package to 3.4.2 ... but still experience the same issue  as the distance filter is not considered

**Comment by manojkumaraut** [comment]
Yes chris .. i using  mock location app
![image](https://user-images.githubusercontent.com/9800500/75782346-cd522380-5d84-11ea-83a2-4e082117e1bb.png)

**Comment by manojkumaraut** [comment]
> Are you testing this mock location app?

**Comment by christocracy** [comment]
Mock location apps don’t provide a natural simulation of real world behavior of distanceFilter.  Mock locations are throttled by Config.fastestLocationUpdateInterval.

**Comment by manojkumaraut** [comment]
so if we go in realtime with distanceFilter : 200 m ... will the location update will trigger only 200m eahc right chris...

**Comment by manojkumaraut** [comment]
Chris , can we use disableElasticity : true to take the configured distancefilter work in place ?

**Comment by christocracy** [comment]
Why not go outside and test it yourself?
