### ISSUE TITLE
AuthorizationStatus error code -1

### ISSUE THREAD

**Issue by azrosen92** [transistorsoft/react-native-background-geolocation#991]
I'm seeing strange behavior when attempting to request location permissions. I'm initiating a location permission dialog with `BackgroundGeolocation.requestPermission()` and the dialog immediately exits, returning an error code of -1 which I don't see as a documented [AuthorizationStatus](https://transistorsoft.github.io/react-native-background-geolocation/modules/_react_native_background_geolocation_.html#authorizationstatus). The code where this happens looks like the following.

```ts
try {
    await BackgroundGeolocation.requestPermission()
} catch (error) { // -> error === -1 here
    // handle error here
}
```

This seems to happen when the user taps the success button, navigating to the phone's settings, then immediately navigates back to the app without enabling location permissions. The next time the user performs an action that initializes the dialog, the dialog automatically closes (before any buttons are tapped) with an error code of -1.

## Your Environment
* Plugin version: 3.4.2
* Platform: iOS
* OS version: 13.3
* Device manufacturer / model: iPhone 11
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
`-1` means the user clicked `[Cancel]` button.

```obj-c
[LocationAuthorization requestLocationAuthorization:locationManager onCancel:^{
        failure([NSNumber numberWithInt:-1]);      
    }];
```

**Comment by christocracy** [comment]
you'll listen to `#onProviderChange` to capture changes to location authorization status.

**Comment by azrosen92** [comment]
Thank you!
