### ISSUE TITLE
Should heartbeat event be generated while app is in background? 

### ISSUE THREAD

**Issue by vvscode** [transistorsoft/react-native-background-geolocation#995]
## Your Environment
* Plugin version:
```
// package.json
"react-native-background-geolocation": "^3.4.2",
// Podfile.lock
RNBackgroundGeolocation: 8f0a20788100fbf08987d80f2053ae6eba79c566
```
* Platform: iOS
* OS version: iOS 13.2
* Device manufacturer / model: iPhone 8
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  return BackgroundGeolocation.ready({
    // Don't run the background-service when app is closed.
    stopOnTerminate: true,
    startOnBoot: false,
    // Android minimum interval is 60 seconds.
    // It is impossible to have a heartbeatInterval faster than this on Android.
    heartbeatInterval: 60,
    // [iOS only] Prevent iOS from suspending your application in the background.
    // Required to make heartbeatInterval work in iOS.
    preventSuspend: true,
    // The minimum distance (measured in meters) a device must move horizontally
    // before an update event is generated.
    distanceFilter: 0,
    // Use of foreground service should ensure the system doesn't kill it when low on memory.
    // Defaults to true on Android >= 8.0 (but we have users on older devices as well).
    foregroundService: true,
  });
```

## Expected Behavior
I should get heartBeat events even in the background. Should I? Checked the documentation, but that's still not clear if my expectations are wrong or not

## Actual Behavior
I don't receive events about the heartbeat in the background.   (whenever I change/do not change my location) (same on Android). What's the expected behavior. 

And in general, it's nice to elaborate on that heartbeat behavior - what are the conditions for getting that event. Event on keeping app on foreground I'm not constantly getting the event (again - I change my location ,or I don't change - it doesn't matter). Nice to better understand how to deal with it

Thanks in advance

**Comment by christocracy** [comment]
`preventSuspend` should not generally be used by most use-cases.  Read the :warning: in the API docs for [Config.preventSuspend](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#preventsuspend)

https://dl.dropboxusercontent.com/s/xr66ojqalhj9zss/Screenshot%202020-03-04%2020.52.51.png?dl=1

When the device is sitting completely still with your app in the background, *the OS throttles heartbeat events*.  If the device is shaken or the screen lit up, `onHeartbeat` resumes.  No, there is no way around it.
