### ISSUE TITLE
Tracking stops to emit new locations after some time

### ISSUE THREAD

**Issue by GabrielMachado11** [transistorsoft/react-native-background-geolocation#999]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android
* OS version: 9
* Device manufacturer / model: MAR-LX3A (Huawei P30 Lite), SM-G975F (Galaxy S10 Plus)
* React Native version (`react-native -v`): 0.59.3
* Plugin config
Config function:
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      // notification persist
      notification: {
        title: 'Viagem em andamento',
        text: 'Clique para voltar',
        channelName: 'Geolocalização',
        smallIcon: 'drawable/ic_stat_onesignal_default',
        notificationLargeIcon: 'drawable/ic_stat_onesignal_default'
      },
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: true,
      startOnBoot: false
    }, (state) => {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled)
    })
```
start function is executed only after a button is pressed
```javascript
BackgroundGeolocation.start((state) => {
    console.log('STATE RIDE STARTED', state)
})
BackgroundGeolocation.changePace(true)
```

## Expected Behavior
Low gaps between two emited locations

## Actual Behavior
Some devices like Samsumg S10 plus and Huawei P30 Lite works perfectly in the first 10 minutes, but after this time the device stop to emit new locations, i already checked `https://dontkillmyapp.com/`, i would wanna know if has some extra config that i can minimize it

After some locations emited i receive:
```BackgroundGeolocation is disabled```

</details>

**Comment by christocracy** [comment]
Your config is fine.  Huawei are the worst performing devices for background-services.  http://dontkillmyapp.com offers the only solutions.
